### ISSUE TITLE
Choosing graphical backend

### ISSUE THREAD

**Issue by sskras** [diasurgical/devilutionX#1]
@ApertureSecurity in diasurgical/devilution/issues/149 wrote:

> What libraries are you wanting to use? I was thinking SDL2 could be a simple library to use.

FWIW, I googled for DirectDraw-to-SDL conversion after the question.  This is what I found:
https://www.gamedev.net/forums/topic/287518-porting-a-game-from-directdraw-to-sdl/#comment-2808684
https://www.gamedev.net/forums/topic/280911-porting-directdraw-to-sdl/
https://discourse.libsdl.org/t/any-tips-on-porting-from-directdraw-to-sdl/9111/2
http://forum.pj64-emu.com/showthread.php?t=5283

I guess there are several approaches by going this route:
* writing wrapper functions / methods;
* conditionally defining a blocks of sensitive code (using #ifdef);
* rewriting (reducing) the original code directly (in place);
* adding some layers of abstracting to the DDraw API;
* rewriting all the graphical code from scratch.

@galaxyhaxz replied:

> I was thinking OpenGL would be the best route for graphics, and OpenAL for sound. We could probably use SDL for input.

@ApertureSecurity also added:

> Ok. I have had this conversation before and every time it went from SDL -> SDL2 -> OGL -> GLFW -> Death....
> 
> I am leaning between OGL and SDL2 . I like the idea of SDL2 because we have work already done using this for Diablo. I looks decorated enough that it might make good for quick use and it's the only one of these that I have some little experience using SDL2.
> 
> I will look at OGL though and maybe it is the better of the few.

Regarding DirectDraw-to-OpenGL conversion.  For some reason I can only think of a wrapper like wined3d, but it's X11 specific.  Well, others exist, but all are Windows dependent:
* https://github.com/jarikomppa/dxwrapper/
* https://github.com/RazorbladeByte/ddhack
* https://github.com/hifi/cnc-ddraw
* https://github.com/CnCNet/cnc-ddraw
* https://github.com/DXGLdotinfo/dxgl

So if the project is to follow approach other than rewriting everything, then maybe it would make sense to put effort into porting one of these Windows wrappers to other platforms.

**Comment by ApertureSecurity** [comment]
Good day @sskras  I am not sure why I am just seeing this now. Thank you for the open issue.

These links are usefull actually. 

It's been a few years since I have written anything in C so I think this will be a bit of fun. I will keep this open for a bit.

**Comment by AJenbo** [comment]
In regards to SDL vs OGL, SDL can give you a OGL context and it's probably the right solution for input and window management any easy so go with that, and if at some point you find a good feature that can only be achieved with OGL you can start rewriting that part for it.
In any case you would be bending OGL to your task since it's not targeted at 2d sprite games so probably it would also be easier to do things in SDL. This is probably also why you see a pattern of projects ending once they go down that route

**Comment by ApertureSecurity** [comment]
We have this in SDL2 already .

This will be completel soon.

Cheers
