### ISSUE TITLE
Game crashes when trying to use the Cathedral map

### ISSUE THREAD

**Issue by mtb-xt** [diasurgical/devilutionX#1003]
**Describe**
After defeating some mob on level 2 of the Cathedral, I got a map - Cathedral Map. Right clicking it immediately crashes the game -_-

**To Reproduce**
1. Go to Level 2 of the Cathedral, find a unique mob, kill him, get the map.
2. Right click the map.
3. ...
4. Segmentation fault (core dumped)

**Expected behavior**
To use the item

**Screenshots**
![Screenshot from 2021-02-13 23-02-50](https://user-images.githubusercontent.com/11381295/107847364-d2b44c80-6de2-11eb-87cc-0acce093dcaa.png)

**Additional context**
DevilutionX v1.1.0, Archlinux

**Comment by qndel** [comment]
Are you sure you didn't install some mod that makes the map drop? It's not supposed to drop at all

**Comment by AJenbo** [comment]
There is no way this is 1.1.0 since that is the Hellfire name, this must be some develop version you have installed.
