### ISSUE TITLE
Disapperaing items from inventory

### ISSUE THREAD

**Issue by UmmonPwr** [diasurgical/devilutionX#1005]
**Describe**
1.) Weapon in the character's hand is disappearing from the inventory.
2.) Oils and runes in the inventory are there but disappearing after clicking on it.

**To Reproduce**
I noticed this problem with Hellfire single player. I did not check Diablo and multiplayer so cannot confirm or deny if these versions also have this problem.
Build is MSVS 2019 x86 release from the newest repo.

In both cases everything is fine until you exit the app, no disappearing items. You can save and load your savegame without a problem if you don't exit the app.
Problem is manifesting when you exit the app, restart it and load your prevoiusly saved game.
1.) The disappearing weapon is random and unexpected, for me it is not obvious what triggers it. I am on dungeon level 10 and it is the second case when it happened.
2.) Disappearing oils and runes can be triggered always with exiting the app and reloading the savegame.

Attached save game is for the disappearing weapon. 
[single_0.zip](https://github.com/diasurgical/devilutionX/files/5984442/single_0.zip)

**Expected behavior**
Items should not disappear.

**Screenshots**
A character having a sword in its hand but according to the inventory it is having nothing.
![devilutionx_hell_disappearing_item](https://user-images.githubusercontent.com/16181245/107998896-5f7b2800-6fe6-11eb-8b2e-5923b08a6896.jpg)

**Comment by qndel** [comment]
known issue

**Comment by AJenbo** [comment]
Thanks for reporting. The problem is only with hellfire and is caused by us not handling hellfire items yet.
