### ISSUE TITLE
DiabloUI scroll bar selecton indicator does not take scroll view into consideration

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#1006]
**Describe**
In the Single Player character select screen, if you have enough characters that you have the option to scroll, you can move the selection one past New Character, which then makes the actual selection off by one from what is indicated by the cursors (the cursors disappear when you go one beyond New Character).

**To Reproduce**
1. Build latest master code in either x64debug or x64release for Windows.
2. Create enough characters in single player that the character select screen can scroll.
3. Keep pressing down on the keyboard until the selection goes past New Character.
4. If you press up, the stats and graphic for the character above New Character will show, but the cursor will be on New Character.

**Expected behavior**
Pressing down while New Character is selected should have no effect.

**Screenshots**
![image](https://user-images.githubusercontent.com/28605404/108004101-cedf2080-6fc2-11eb-93b7-7ce6efbcb0dd.png)
![image](https://user-images.githubusercontent.com/28605404/108004111-d6062e80-6fc2-11eb-8a42-491b3ed39612.png)

**Additional context**
This is on Windows 10. Don't know if other platforms are affected or not.

**Comment by AJenbo** [comment]
@glebm any chance you would be willing to look in to this

**Comment by glebm** [comment]
Sure

**Comment by glebm** [comment]
Bug introduced by this commit https://github.com/diasurgical/devilutionX/commit/85f44063df1da9a604daba4baad9ec5f21daf885, specifically this change:

```diff
-	ListViewportSize = SelectedItemMax - SelectedItemMin + 1;
+	ListViewportSize = count;
```

**Comment by glebm** [comment]
Ah, nevermind, it's probably a bit more complicated than that.

**Comment by AJenbo** [comment]
thanks that saves me some time to focus on the other bits for the next release :)

**Comment by AJenbo** [comment]
pypy has a possible rolution, bu there are some conflicts https://github.com/pionere/devilutionX/commit/0b8bafc7f1e8bbfadc79be2ce0b9d1d43360e901

**Comment by glebm** [comment]
Found a likely offending diff, I think https://github.com/diasurgical/devilutionX/commit/4e8843ee7ca23bb30cb4920378c32bfa5f269c21

```diff
- if (item->m_value == SelectedItem)
+ if (i == SelectedItem)
```

**Comment by glebm** [comment]
Reverting that line fixes the hero selection menu but breaks the main menu

Looks like some subtle bugs were introduced with these refactorings but I'll try to figure them out

**Comment by glebm** [comment]
The fix was simple once I understood what's going on there (things changed since I last touched DiabloUI)
