### ISSUE TITLE
Unable to launch game with user name that contains non a-z letters

### ISSUE THREAD

**Issue by Gr33nEyes** [diasurgical/devilutionX#1012]
When trying to launch the game i get the following error "Read-Only directory error"

Game was installed in c:\diablo, user data folder is C:\Users\Сергей\AppData\Roaming\diasurgical\devilutionx

![screen2](https://user-images.githubusercontent.com/40704849/108362474-d988f800-7204-11eb-9710-1243078bbc90.jpg)

**Comment by qndel** [comment]
idk how to fix because you decided to ignore the template and gave 0 info ;)

**Comment by Gr33nEyes** [comment]
Maybe because I using Russian version of Windows 7?

**Comment by qndel** [comment]
Or maybe because your dog is too big. No info = no help :)

**Comment by Gr33nEyes** [comment]
Well, I created directory named "diablo" in root of disk. Then, I unpacked executable file with libraries, and placed MPQ file. 
![Uploading screen1.jpg…]()

**Comment by Gr33nEyes** [comment]
![screen1](https://user-images.githubusercontent.com/40704849/108362374-b3635800-7204-11eb-8d6b-e5a799d1404e.jpg)

**Comment by qndel** [comment]
maybe don't put it on C:/ 🙄

**Comment by Gr33nEyes** [comment]
![screen2](https://user-images.githubusercontent.com/40704849/108362474-d988f800-7204-11eb-9710-1243078bbc90.jpg)

**Comment by qndel** [comment]
I'd assume it's caused by russian characters in your username, still, don't put stuff directly on C ...

**Comment by Gr33nEyes** [comment]
It is possible to fix this problem with cyrilical letters?

**Comment by Gr33nEyes** [comment]
Thanks =)

**Comment by qndel** [comment]
I'll try but feel free to join our discord server https://discord.gg/YQKCAYQ - chatting there is much faster

**Comment by qndel** [comment]
Seems atm we don't support special characters in any path, use this as a workaround
Create a file with .bat extension in devilutionx's folder
put this inside
```cpp
devilutionx.exe --save-dir .
```
and use it to run the game - make sure the path to your devilutionx folder doesn't contain any special characters

**Comment by AJenbo** [comment]
@Gr33nEyes could you let us know the path of your user folder.

**Comment by qndel** [comment]
he did 
![image](https://user-images.githubusercontent.com/14297035/108386038-8a46c580-720c-11eb-8c50-ffb0a318ae1d.png)

**Comment by Gr33nEyes** [comment]
C:\Users\Сергей\AppData\Roaming\diasurgical\devilutionx

**Comment by Gr33nEyes** [comment]
Will you mark this issue as a bug?

**Comment by Gr33nEyes** [comment]
BTW, I found this in Windows XP

**Comment by AJenbo** [comment]
Turns out this is a duplicate of https://github.com/diasurgical/devilutionX/issues/747
