### ISSUE TITLE
Item disappearing on pickup

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1018]
On latest build see savegame and attachment.

[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6005829/single_0.hsv.zip)
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6005831/output.mkv.zip)

Before that the weapon and both rings have also disappeared because of an unknown reason.

**Comment by AJenbo** [comment]
Thanks, but this is already reported. It's one of the last know issues to resolve before hellfire is done.

https://github.com/diasurgical/devilutionX/issues/981

**Comment by Chance4us** [comment]
Hi, thanks for the reply.
I think if this bug could be fixed the game would reach a very playable state.
Does this bug also occur in the upstream and can it be narrowed down in which function(s) it occurs?
Best regards.

**Comment by AJenbo** [comment]
No, the issue stems from handeling the differences between Hellfire and Diablos item lists. There are still some missing bits for it to be compleat. It's the only major thing left before we are ready to release hellfire support.
