### ISSUE TITLE
Unable to use belt item with numpad keys

### ISSUE THREAD

**Issue by RicoLeNecro** [diasurgical/devilutionX#1026]
Hi. This is my first time reporting anything here, so I hope I'm not doing anything wrong.

Background:
In the original game, people could use the the numpad keys to use items from their belt (provided that num lock is on).

For people such as us using french keyboards, this was more reliable than using the numbers above the alpha keys, as didn't require us to be holding shift at the same time.

However, when my sister and I tried playing devilutionX today, she noticed that numpad keys did not allow her to drink a healing potion from her belt, even though num lock was enabled.

Expected behaviour: while the keyboard's num lock is on, one should be able to use the numbers 1-8 on their numpad to use the corresponding item in their character's belt.

**Comment by qndel** [comment]
Thanks for reporting :)

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/pull/1027
