### ISSUE TITLE
Transparency issue with staircases

### ISSUE THREAD

**Issue by joewis** [diasurgical/devilutionX#1030]
**Important information**
Linux / Fresh clone from github, compiled myself

**Describe**
Staircases in the catacombs have an empty space when running in devilutionx.

**To Reproduce**
1. Start game
2. Walk down to the catacombs 
3. see the gap in the staircase

**Expected behavior**
Stair cases shouldn't look like this.

**Screenshots**
![diablo mode](https://user-images.githubusercontent.com/74438661/108612874-64e1d380-7427-11eb-8678-0157e2b48a94.png)

**Comment by joewis** [comment]
I tried to edit but seems not updated - it's not related to diablo or hellfire mode. (I started without ./ when doing the second test)

**Comment by qndel** [comment]
Broken on windows too

**Comment by AJenbo** [comment]
It's probably my fault :(

**Comment by AJenbo** [comment]
Oh, turns out it wasn't. Fix is on its way.
