### ISSUE TITLE
FreeBSD port fails to compile after 60d3e9c

### ISSUE THREAD

**Issue by nunotexbsd** [diasurgical/devilutionX#1034]
Hello,

I'm maintaining FreeBSD port and doing some tests for next release.

I can only build it ok until commit 60d3e9c
From this one ( 790c8e1 ) to latest commit I get this compile error:
https://termbin.com/kbn3

Latest commit 2cbe239 gives same error:
https://termbin.com/1a84

Thanks,

Nuno Teixeira

**Comment by qndel** [comment]
That's not latest

**Comment by AJenbo** [comment]
> Latest commit [2cbe239](https://github.com/diasurgical/devilutionX/commit/2cbe239d6d50e00421ba67acda5c82ce75bad0a4) gives same error:

the commit right after that one probably solves your issue. https://github.com/diasurgical/devilutionX/commit/b707b09b181d6de2bac821d3e9162d78ebfaac30

besides that your build server seams to not include the needed git files for the compile process to figure ot the version being build:
```

/bin/mkdir -p /usr/home/nunotex/Work/freebsd/ports/games/devilutionX/work/.build
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
CMake Warning at CMakeLists.txt:53 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

```

**Comment by nunotexbsd** [comment]
The port doesn't use git to fetch distfile. It just fetches from `GH PORTVERSION` or `GH_TAGNAME`, so it don't have any git files.

port Makefile have: `CMAKE_ARGS= -DGIT_TAG=${PORTVERSION}`, but I think it doesn't make sense to use it. f I remove this line, warning remains.

Any hint how to silent it?

Thanks

**Comment by AJenbo** [comment]
you can provide the version via -DVERSION_NUM= in cmake, it sounds like your build system will break once we start using git modules

**Comment by nunotexbsd** [comment]
We use GH_TUPLE for modules, and it will not be a problem.

e.g. `GH_TUPLE= FiloSottile:age:v1.0.0-beta7:filosottile_age/vendor/filippo.io/age` and it compiles toguether with main distfile.

I will try `-DVERSION_NUM=` in `CMAKE_ARGS`

**Comment by nunotexbsd** [comment]
It worked! It silent warning.

`PORTVERSION= 1.1.0`
`CMAKE_ARGS= -DVERSION_NUM=${PORTVERSION}`

Thank you!

**Comment by nunotexbsd** [comment]
And git-submodules:
https://docs.freebsd.org/en/books/porters-handbook/#makefile-master_sites-github-ex2
