### ISSUE TITLE
Text scrolling too fast

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1046]
For some reason text scrolling on the bookshelf is too fast on latest build.
Also got a description in the same way for the quest "Anvil of Fury" while talking to Griswold.

[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6031915/output.mkv.zip)

**Comment by Chance4us** [comment]
Savegame for test purposes:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6031930/single_0.hsv.zip)

**Comment by AJenbo** [comment]
Fixed
