### ISSUE TITLE
May the spirit of Arkaine protect me

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1047]
If Monk puts on the "Akaine's Valor", there is no sound "May the spirit of Arkaine protect me". 

Savegame for test purposes:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6031956/single_0.hsv.zip)

**Comment by galaxyhaxz** [comment]
I recently fixed the bug where quest items would reset the quest status every time they are picked up. Thus, you will hear the "May the spirit" once you complete the quest and pick it up *once*. After that you will only hear it on a new game doing the quest again.

**Comment by Chance4us** [comment]
So did I understand correctly that it was a vanilla bug and that the sound should only be played once?
And finally you solved this bug?

**Comment by galaxyhaxz** [comment]
More of a quirk/feature than a bug, but yeah: https://github.com/diasurgical/devilutionX/pull/992

It would act like you finished the quest each time you pick it up, which would screw up games that didn't have valor in them.

**Comment by Chance4us** [comment]
Thank you. Because the report no longer makes sense I close it immediately. Have a nice day. ;-)
