### ISSUE TITLE
Key mapping

### ISSUE THREAD

**Issue by geekifier** [diasurgical/devilutionX#1050]
Would it be feasible to support setting of arbitrary hotkeys for spells - similar to Diablo 2 behavior?

Function keys are quite a reach, and at least on a Mac, they are also normally used for OS functions, such as Play/Pause, Prev/Next song. This can of course be disabled, but then it would have to be re-enabled after playing.

I vaguely remembers setting up a,s,d,f etc as hotkeys in Diablo 2, which was nice when already using alt for highlight and ctrl for run.

I am OK patching my own copy of the source code to do this if someone could point me in the right direction, but I wanted to see if this is something that maybe could be implemented natively in the engine.

**Comment by AJenbo** [comment]
You could remap the F-keys: https://github.com/diasurgical/devilutionX/blob/master/SourceX/miniwin/misc_msg.cpp#L134

**Comment by geekifier** [comment]
@AJenbo Thanks for the pointer, I was looking in a completely different place.

This is silly, but I was not aware there was an ini file until you mentioned it.
Is the default location on MacOS documented somewhere?
Also, is the ini syntax documented anywhere?

**Comment by AJenbo** [comment]
It is self-populating so there aren't any hidden options, the values pretty self-evident as well, the only exception might be scaling quality which can be 0, 1, or 2.
Your welcome to submit some documentation if you feel it's needed. If nothing else it would mean I don't have to answer this question repeatedly.

**Comment by geekifier** [comment]
Thanks @AJenbo, I was looking in a completely wrong spot.

For anyone interested in remapping, here's what I ended up doing to satisfy my use case:

```c

diff --git a/SourceX/miniwin/misc_msg.cpp b/SourceX/miniwin/misc_msg.cpp
index 2cd40c52..0a28f330 100644
--- a/SourceX/miniwin/misc_msg.cpp
+++ b/SourceX/miniwin/misc_msg.cpp
@@ -231,6 +231,14 @@ static int translate_sdl_key(SDL_Keysym key)
                return DVL_VK_RMENU;
        case SDLK_RGUI:
                return DVL_VK_RWIN;
+       case SDLK_a:
+               return DVL_VK_F5;
+       case SDLK_s:
+               return DVL_VK_F6;
+       case SDLK_d:
+               return DVL_VK_F7;
+       case SDLK_f:
+               return DVL_VK_F8;
```

Basically, keys a-f become mapped to F5-F8. Not that you lose the `s` hotkey with this, but I did not care about that.
There is a link the SDL key codes in a comment on [line #83](https://github.com/diasurgical/devilutionX/blob/master/SourceX/miniwin/misc_msg.cpp#L83).

**Comment by AJenbo** [comment]
You could also do it in the engine closer to where hotkey specifc code lives, but this is the most flexible and best documented place atm :)

**Comment by rendomnet** [comment]
Can we remap in ini file?

**Comment by AJenbo** [comment]
No this still hasn't been implemented by anyone.

**Comment by julealgon** [comment]
Also, would suggest a separate options nested struct for this when it gets implemented called `Controls` (or similar).
