### ISSUE TITLE
[Enchancement] Variable map transparency

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1051]
Proposal to implement a variable transparency for the map controlled by diablo.ini file.

**Comment by AJenbo** [comment]
Are you suggesting that the automap should be rendered at 50% transparancy?

**Comment by Chance4us** [comment]
I suggest that the transparency of the automap can be set variably (between 0% -100%) in the ini file.
The reason is  the automap makes the game graphics less enjoyable, because it is there as a kind of scheme.

**Comment by Chance4us** [comment]
Yes, so that it is rendered at % transparency you typed in the ini file.
The default value should probably be 100% so that the originality of the game is not compromised.

**Comment by Chance4us** [comment]
I meant 0% transparency as the default value in the ini file.
Do you think it would be a useful enchancement for the 1.2.0 release?

**Comment by AJenbo** [comment]
> I suggest that the transparency of the automap can be set variably (between 0% -100%) in the ini file.
> The reason is the automap makes the game graphics less enjoyable, because it is there as a kind of scheme.

we only have the option of 50% transparency or none. And yeah I agree.

**Comment by AJenbo** [comment]
```
@@ -680,7 +680,8 @@ void ENG_set_pixel(int sx, int sy, BYTE col)
 	dst = &gpBuffer[sx + BUFFER_WIDTH * sy];
 
 	if (dst < gpBufEnd && dst > gpBufStart)
-		*dst = col;
+		if (sgOptions.blendedTransparancy)
+			*dst = paletteTransparencyLookup[*dst][col];
 }
 
 /**
```

**Comment by Chance4us** [comment]
Nice that you also would like the automap transparency.
I think 50%  transparency feature should be fine.

**Comment by Chance4us** [comment]
Hardcoded the code lines for testing.
Attached an example for the crypt. It's okay, but not total fulfillment. ;-)
[crypt.mkv.zip](https://github.com/diasurgical/devilutionX/files/6045847/crypt.mkv.zip)
At the moment no idea how it looks in the other levels.

**Comment by AJenbo** [comment]
> Attached an example for the crypt. It's okay, but not total fulfillment. ;-)
Yeah I wasn't to excited by the result either, so didn't spend more time on it. But maybe a side by side image would be nice.

FYI the way you cut you videos causes them to croup for the first part, it appears that they are missing the an I-frame.

**Comment by Chance4us** [comment]
Yes, I was a little careless and didn't cut at the key frame. I'll try to improve it next time.

**Comment by Chance4us** [comment]
I'll do a side by side image for you soon.

**Comment by Chance4us** [comment]
![cathedral](https://user-images.githubusercontent.com/45902449/109361103-a986c800-7888-11eb-8ebb-164fbad7d236.png)
![catacombs](https://user-images.githubusercontent.com/45902449/109361113-b1df0300-7888-11eb-9aa5-7eecbad92246.png)
![caves1](https://user-images.githubusercontent.com/45902449/109361141-bc010180-7888-11eb-876e-d3da3bcba20d.png)
![caves2](https://user-images.githubusercontent.com/45902449/109361149-c15e4c00-7888-11eb-8813-a6969f41ca25.png)
![hell](https://user-images.githubusercontent.com/45902449/109361174-ccb17780-7888-11eb-92aa-ad7b910cd16b.png)
![hive](https://user-images.githubusercontent.com/45902449/109361209-d89d3980-7888-11eb-92c0-3c7f7994c76f.png)
![crypt](https://user-images.githubusercontent.com/45902449/109361234-e18e0b00-7888-11eb-8bb6-cdc9852f824e.png)

**Comment by Chance4us** [comment]
It's kind of not that expected.
I think that there are generally also vanilla problems with the visibility in the caves and hive, so that the automap cannot be seen well, especially in the areas of the lava.

So the possibility to change the color of the automap, to make the automap smaller, to be able to set a fixed position for the automap could also be helpful.

**Comment by AJenbo** [comment]
I'm having a really hard time deciding if this is worth adding or not.

**Comment by Chance4us** [comment]
I think it's not worth it.
I would like to experiment with colors as well.

**Comment by Chance4us** [comment]
@AJenbo Would it be difficult for you to leave a line of code to change the color of the automap?

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/blob/master/Source/automap.cpp#L34

**Comment by Chance4us** [comment]
Thanks a lot.

**Comment by julealgon** [comment]
I'm a bit confused. Did we give up on this? I really liked the screenshots there, seemed like a nice option to have.

**Comment by AJenbo** [comment]
Yeah we didn't feel like it made enough of a difference.

**Comment by julealgon** [comment]
> Yeah we didn't feel like it made enough of a difference.

Oh, fair enough. It is quite a striking difference to me in those screenshots. I feel like a setting for this could have some appeal.

**Comment by AJenbo** [comment]
Yeah, it just felt less so when actually playing.
