### ISSUE TITLE
Inconsistent cursor warping

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#1055]
Opening some panels moves the mouse. This behavior isn't consistent in any way:
Panel name / does it move mouse or not

Left panels:
Character panel - yes
Quest panel - no

Right panels:
Inventory - yes
Spellbook - no

I'd suggest leaving the mouse alone, I can't see any gain from moving it after opening/closing panels.

**Comment by AJenbo** [comment]
The benefit is that you are still pointing at the same spot if you open or close a panel during a walk or attack.

**Comment by AJenbo** [comment]
... when opening the quick spell list, it loses the inventory, but none of the 3 other panels.

**Comment by galaxyhaxz** [comment]
I agree with Qndel, i don't like the game trying to move my cursor around, i'd rather it stay where i put it.

**Comment by AJenbo** [comment]
![menu](https://user-images.githubusercontent.com/204594/110037653-ffeb7f00-7d3e-11eb-80b3-81946421927f.gif)

**Comment by AJenbo** [comment]
As long as you aren't running the game in 640x480 it won't be moving the mouse.
