### ISSUE TITLE
[qol] Add personal stash on Tristram tavern

### ISSUE THREAD

**Issue by sheepo99** [diasurgical/devilutionX#1058]
Small qol suggestion: on the Beelzebub mod the problem with the (lack of) personal item storage was solved by adding a chest placed next to Tristam's tavern to act as the player's personal stash. I suggest we do one better and add a similar stash that can be accessed by talking to Ogden. This similarly suggests the player has rented a room at the tavern during his quest, which adds a bit more immersion, and one more reason to talk to Ogden about quest stuff.

**Comment by AJenbo** [comment]
Looks like someone beat you to it :) https://github.com/diasurgical/devilutionX/issues/1049
