### ISSUE TITLE
The output of the dialogue problem

### ISSUE THREAD

**Issue by ivan89el** [diasurgical/devilutionX#1059]
**Important information**
Operating system: Windows 10 x64
DevilutionX: lastest git as of Feb 26 x86

**Describe**
I can't finish the dialogue with Pepin with the mouse. The ESC works properly.

**Screenshots**
https://sun9-46.userapi.com/impg/809R4naTE7ZbTZCWmu634L8yJ_2YqqSWzLmwJA/UwZh9WD8dA0.jpg?size=1536x864&quality=96&sign=595aaa10f7439219fe9844b2138ee7f4&type=album

**Comment by qndel** [comment]
Thanks for reporting :)

**Comment by galaxyhaxz** [comment]
I guess after COVID hit Tristram company has been in short supply for Pepin and he doesn't want you to leave.
