### ISSUE TITLE
Suggestion : don't change character save date if nothing changed

### ISSUE THREAD

**Issue by RicoLeNecro** [diasurgical/devilutionX#1062]
Hello (again).

Sometimes I just load an existing multiplayer character to look at their equipment, but don't actually change anything.

Since I also try (and sometimes fail) to keep my character saves synchronized between multiple computers, I think it would probably help if the game didn't change the character save files' date and time when in the character stats or their inventory changed.

**Comment by qndel** [comment]
multiplayer characters are saved periodically

**Comment by RicoLeNecro** [comment]
Yes, they are, but there is no point in saving if neither the stats nor the inventory contents changed, is there?

**Comment by AJenbo** [comment]
your sync software should check the file hash (md5/sha1) or you could use a trainer to view the hero
