### ISSUE TITLE
[Suggestion] External launcher for configuring .ini and mods

### ISSUE THREAD

**Issue by sheepo99** [diasurgical/devilutionX#1064]
Right now most extended options on DevilutionX are handled via editing the diablo.ini file directly. My suggestion for the long run is to have an external game launcher that allows the player to enable/disable options more comfortably prior to game launch. This could also be further extended for mod support in the future. The main advantage with this type of external launcher is that it doesn't require further additions to the in-game menu, keeping it closer to vanilla and making it more flexible for developers.

Below are picture examples of the launchers used for the VCMI and OpenMW projects.

![image](https://user-images.githubusercontent.com/3621746/109382533-45442280-78e1-11eb-91ae-13938bdb1d2e.png)

![image](https://user-images.githubusercontent.com/3621746/109382489-fb5b3c80-78e0-11eb-901e-2d2444ce8c5b.png)

**Comment by AJenbo** [comment]
I think an in-game options menu would be a better solution as well as less work to develop and maintain.
The only benefit of a launcher is that it can be easier to develop a simple UI with a desktop framework.

If someone wants to make a config tool they are more than welcome to do so, it wouldn't be part of the main repo, but could be included with some of the releases if it works well on the given platform.
