### ISSUE TITLE
[Devilutionx bug] Two handed weapons are not displayed correctly

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1070]
![vanilla](https://user-images.githubusercontent.com/45902449/109415536-91629600-79b9-11eb-9b6c-0d5816df5f96.png)
![devilutionx](https://user-images.githubusercontent.com/45902449/109415539-96274a00-79b9-11eb-825a-80b357f36f50.png)

1. Not tested if it is diablo related as well
2. Issue does not affect gameplay
3. Savegame attached
4. Expected behaviour: Same drawing for the body and "The Protector" drawing also on on the right hand 
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6056613/single_0.hsv.zip)

**Comment by Chance4us** [comment]
Just test played again with an another character and I have to note that all two handed weapons currently look like this.
![screen01](https://user-images.githubusercontent.com/45902449/109423154-b87f8e80-79de-11eb-9f8c-b8e3a36543c5.png)

**Comment by AJenbo** [comment]
couldyou check if 9a9f6b01 if affected

**Comment by Chance4us** [comment]
If I change the number 99 back to 10, no change happens.

**Comment by Chance4us** [comment]
Commit 8283f85e248f5d214d754f2681b7dd37b53e4543 is the first bad commit.
It affects only the presentation of the weapon. The drawing of the body is an another issue and should be split up.

**Comment by AJenbo** [comment]
> If I change the number 99 back to 10, no change happens.

I wasn't suggesting that you revert 9a9f6b0, but that you check it out since it was the one before 8283f85 which is what I expected to cause the issue.

**Comment by Chance4us** [comment]
If you pay attention you will see that the magician in the picture above has the correct body drawing for the monk.

**Comment by Chance4us** [comment]
8283f85 affects the presentation of the weapon.

**Comment by AJenbo** [comment]
> If you pay attention you will see that the magician in the picture above has the correct body drawing for the monk.

I did.

> [8283f85](https://github.com/diasurgical/devilutionX/commit/8283f85e248f5d214d754f2681b7dd37b53e4543) affects the presentation of the weapon.

Yes we both mentioned this

**Comment by AJenbo** [comment]
@glebm any idea what causes this :)

**Comment by glebm** [comment]
Most likely a mis-resolved conflict during rebase

**Comment by AJenbo** [comment]
@Chance4us could you please test if it's fixed now?

**Comment by Chance4us** [comment]
Just a sec.

**Comment by Chance4us** [comment]
No change. The Bug is still there.

**Comment by glebm** [comment]
Does anyone have a non-hellfire save handy?

**Comment by glebm** [comment]
Nevermind that, sorc's starting weapon is 2-handed

**Comment by Chance4us** [comment]
I've just tried. The bug occurs in Diablo and Hellfire.
In Diablo, the magician starts with a two-handed staff and that's where the mistake is there too.

**Comment by Chance4us** [comment]
mistake = bug

**Comment by AJenbo** [comment]
> the magician

If he gets downgraded to an illusionist he will start being in trouble :)
![image](https://user-images.githubusercontent.com/204594/109435419-acb1bd80-7a1a-11eb-892a-f5dba6ab1f91.png)

**Comment by Chance4us** [comment]
The sorcerer meets monk, rogue and the warrior.
The warrior asks the sorcerer: What was the greatest spell you learned in this great game?
The sorcerer replies: I learned the blast spell this time.
The monk remarks: I didn't even know that there was such a spell.
Rogue then asks: Fine, and what will you learn next time in the hell?
The sorcerer: What's the hell?
