### ISSUE TITLE
Golem is less powerfull after loading a save game

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1071]
If you create a golem against diablo, then he can defeat the enemy. 
If you then first save the game during the fight, then leave it and then reload it, the golem no longer hits and can therefore no longer defeat the opponent.

How to reproduce: Just load the attached savegame and see that the golem can not defeat the opponent.
Create a new golem and see that he will defeat Diablo.

Expected behavior:
Even after relaunching of the application and reloading the saved game, the golem should hit the opponent.

[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6056646/single_0.hsv.zip)

**Comment by Chance4us** [comment]
Addendum after testing. It's not a vanilla bug.

**Comment by Chance4us** [comment]
Excuse me. After testing it more closely, I found that it is probably a vanilla bug after all.

If you load the following savegame, you will find that the golem never dies, that Diablo never dies either and that the player never dies either. The player does not need to restore health with potions and the game will run forever. 
I don't know if it's because the character is overpowered and can block well.
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6056716/single_0.hsv.zip)

**Comment by AJenbo** [comment]
This is just poor balancing in D1. You have 130 dex and your block chances ends up as 100% against Diablo. If you try on Nightmare he should be able to hit you still as you block chance would be 89%, and just 59% on Hell.

note in Vanilla you block chance would be 25% lower after loading a save game, leaving you with just 94% block chance in this scenario. Here It would take Diablo about 5 minutes to kill you if you just stand still. But this is due to a bug in vanilla.

**Comment by AJenbo** [comment]
Got confused by the multiple descriptions of issues here. Golem not dying is because Diablo isn't hitting him because he is focusing on the hero, the hero not dying is because he has a 100% block chance against Diablo.

**Comment by StephenCWills** [comment]
I added some debug code and confirmed that the Golem's chance to hit goes to zero when loading the savegame.

Before load:
![image](https://user-images.githubusercontent.com/9203145/114645869-373b3d00-9ca8-11eb-804f-1dc377725056.png)

After load:
![image](https://user-images.githubusercontent.com/9203145/114645881-3dc9b480-9ca8-11eb-92f7-532b02b5ac38.png)

---

I believe I also confirmed this is not a vanilla bug by adding the same code to a debug build of devilution.

Before load:
![image](https://user-images.githubusercontent.com/9203145/114646240-e8da6e00-9ca8-11eb-819e-378330f8ddd4.png)

After load:
![image](https://user-images.githubusercontent.com/9203145/114646317-07d90000-9ca9-11eb-84cc-8fb6237597bf.png)

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L592

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/5b1b5fa8ae54bc28d72380f8c8cf82d93a6a8edd

A quick solution would be to still load the values for monsters with id lower then MAXPLRS
