### ISSUE TITLE
[hellfire] Devilutionx does not offer a switch for jogging in the menu 

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1072]
![jog1](https://user-images.githubusercontent.com/45902449/109416337-e1435c00-79bd-11eb-9bdb-e554c8cf68a0.png)
![jog2](https://user-images.githubusercontent.com/45902449/109416343-e7393d00-79bd-11eb-8fda-0731796f995c.png)

**Comment by AJenbo** [comment]
This is intentional because there is no available lines, instead it has been relegated to the ini until there is an in-game menu for options.
