### ISSUE TITLE
[Vanilla bug] Inventory vanilla bug

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1073]
If you open the inventory and save the game and load it immediately, the inventory will remain open.

When you quit the application and reload the game, the inventory will be closed.

Expected behavior: If you save the game with an open inventory and quit the application, reopen it and load the game, the inventory should be open.

**Comment by AJenbo** [comment]
Is this a vanila bug or devilutionx specific?

**Comment by galaxyhaxz** [comment]
Vanilla, the flag isn't reset to false by simply loading the game from the menu.

**Comment by Chance4us** [comment]
Just checked. It is definitely vanilla specific.

**Comment by AJenbo** [comment]
Can probably be connected with the save/load of hot keys in https://github.com/diasurgical/devilutionX/pull/895

**Comment by AJenbo** [comment]
Actually, this no longer makes sense as the panels will now close when accessing the menu.
