### ISSUE TITLE
[Vanilla bug] Sorceror is a misspelling of sorcerer

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1074]
https://en.wiktionary.org/wiki/sorceror#English
Sorceror is a misspelling of sorcerer.

![sorceror](https://user-images.githubusercontent.com/45902449/109421022-d4cafd80-79d5-11eb-9951-5afd28917929.png)
![sorcerer](https://user-images.githubusercontent.com/45902449/109421030-d8f71b00-79d5-11eb-9125-de07d1782a88.png)

Expected: correct spelling

**Comment by Chance4us** [comment]
Occurrences attached:
[sorcerer.txt](https://github.com/diasurgical/devilutionX/files/6056917/sorcerer.txt)

**Comment by galaxyhaxz** [comment]
Sorcerawhhhhhh scary typos, can't spell, need English lessons, can't code either, plz halllllp

(Good work spotting this, I've made the same typo, they fixed it in the PSX port!)

**Comment by Chance4us** [comment]
Does the term "good first issue" mean that it is a vanilla bug? Or does it mean something else?

**Comment by galaxyhaxz** [comment]
It means it's a very easy task for someone new to the project, since it quite literally involves changing one letter. You can't fix all occurrences though since the MPQ uses the misspelled variant.

**Comment by julealgon** [comment]
>  AJenbo added this to the 1.2.0 milestone

❤️

**Comment by Chance4us** [comment]
Thank you for fixing it.
