### ISSUE TITLE
Unable to drop items on the ground in town!

### ISSUE THREAD

**Issue by GrayFace** [diasurgical/devilutionX#1079]
**Important information**
Win 7 (64 bit) / DevilutionX version 1.1.0 / Downloaded release

**Describe**
Dropping just does nothing. It's as if some limit has been reached despite the fact there's not a lot of items on the ground, no more than 2/3 of what I have at the end of the game. I can pick up an item and drop it or another one, but then can't drop anything again.

**To Reproduce**
1. Use this save: [single_1.zip](https://github.com/diasurgical/devilutionX/files/6060108/single_1.zip)
2. Try dropping any item from the inventory.
3. Nothing happens.

**Expected behavior**
Dropping.

**Additional context**
When I was playing Nightmare with this character I also had "A duplicate item has been detected.  Destroying duplicate..." issue with Empyrean Band. I had one from Normal and one from Nightmare and the game at some point started treating them as duplicates. Had to carry the 2nd one and eventually sold it. Now I also have 2 Empyrean Bands, both lying on the ground.

**Comment by Chance4us** [comment]
This is likely due to the internal limit of a maximum of 127 items that can lie on the ground.
I don't think it's a bug, just a limitation.

**Comment by AJenbo** [comment]
>  the fact there's not a lot of items on the ground

I realize that it's relative, but the fact that you have more then enough gold to cover the entire town square in piles of 5k makes this a bit of a false statement.
![image](https://user-images.githubusercontent.com/204594/109476524-5030bb80-7a77-11eb-9380-96249a42cd8c.png)

As @Chance4us mentioned this is how the game behaves when you hit 127 items on ground.

The good news is that we are working on adding a stash to the game.

>  II also had "A duplicate item has been detected. Destroying duplicate..." issue with Empyrean Band

The game will often see unique items (and some random ones) as duplicates even when gained legitimately. This restriction has already been removed from the current development version.

**Comment by GrayFace** [comment]
Thanks! Great to know.

> (total value 427231)

I actually have 282339 in total. Is 427231 a result of a check by a tool? Could there be ghost piles unassigned to squares making that tool see it bigger?

**Comment by AJenbo** [comment]
it's because i sold all your stuff
