### ISSUE TITLE
Suggestion: allow for disabling friendly fire?

### ISSUE THREAD

**Issue by RicoLeNecro** [diasurgical/devilutionX#1089]
Hi,

I guess not everyone will agree with that as that would change gameplay significantly (especially when spellcasters are around), however, I think it would be nice to have the option while creating a game to completely disable "friendly fire".

Since there appears to still be issues with character positions being synchronized in multiplayer and I'm getting tired of being shot accidentally by Rogues :/

**Comment by qndel** [comment]
`being shot accidentally by Rogues :/` what if I told you it's not accidental? 
![image](https://user-images.githubusercontent.com/14297035/109630544-5725ff80-7b45-11eb-9478-2e0e44226293.png)

**Comment by malvarenga123** [comment]
+1 to this. It could be an option when creating a multiplayer game.

**Comment by AJenbo** [comment]
It will probably be an ini option for now since the way the create game menu works now it basically asks you a question for each option.

**Comment by qndel** [comment]
disabling friendly fire takes 2 line of code, why not just make it respect the ingame "friendly fire" button? ;)

**Comment by AJenbo** [comment]
Some people thinks the old way is more realistic and will get upset if it's made sensible :shrug:

**Comment by qndel** [comment]
then they don't have to press the button 
![image](https://user-images.githubusercontent.com/14297035/109797038-33cc8480-7c19-11eb-8f02-1a890c95160e.png)

**Comment by malvarenga123** [comment]
> disabling friendly fire takes 2 line of code, why not just make it respect the ingame "friendly fire" button? ;)

Good idea. An option in the ini like "respect friendly fire button"

**Comment by AJenbo** [comment]
Here we go https://github.com/diasurgical/devilutionX/pull/1104
