### ISSUE TITLE
devilutionX w/ spawn.mpq looks broken

### ISSUE THREAD

**Issue by bloodhaze13** [diasurgical/devilutionX#1091]
**Important information**
MacOS 11.2.1 / DevilutionX v1.1.0 / Github release

**Describe**
Unable to use devilutionX w/ spawn.mpq. Either the file is not loaded resulting in the first error, of md5 hash verification of files fails if spawn.mpq is renamed diabdat.mpq to get around first error.

**To Reproduce**
1. Download/install DevilutionX v1.1.0 Github release
2. Download and recover spawn.mpq from https://github.com/diasurgical/devilutionX/blob/master/shareware
3. Move spawn.mpq to "~/Library/Application Support/diasurgical/devilution"
4. Launch devilution and you are greeted with an error stating diabdat.mpq is not found
5. Rename spawn.mpq to diabdat.mpq
6. Launch devilution, choose new game, make character etc. MD5 Hash verification failed after character setup

**Expected behavior**
Game should launch and allow me to play this timeless classic :)

**Screenshots**
Step 4:
![image](https://user-images.githubusercontent.com/21090642/109724583-ebef3280-7c03-11eb-84d9-8693ac34da30.png)
Step 6: 
![image](https://user-images.githubusercontent.com/21090642/109724620-f7425e00-7c03-11eb-939f-ec74ab0a6e61.png)

Thanks for any help

**Comment by AJenbo** [comment]
Prior to 1.2.0 DevilutionX, like the original, has to be build specifically for shareware (spawn.mpq), retail or Hellfire. What you are doing here is not supported and would result in the same issue if you did it in the original Diablo, but will be supported in 1.2.0.
