### ISSUE TITLE
Add missing transcriptions

### ISSUE THREAD

**Issue by yuripourre** [diasurgical/devilutionX#1093]
The diabdat.mpq file has some wav files without transcription from removed quests. They could be very handy for modders or anyone who would like to try to restore the removed content. Or maybe generate a TTS model?

- [X] ~barmaid~ (#1092)
- [x] blacksmith (#1203)
- [X] ~cow!?~ (#1140)
- [X] ~deadguy~  (#1141)
- [X] ~drunk~ (#1146)
- [x] healer (#1212)
- [X] ~narrator~
- [x] pegboy (#1341)
- [x] priest (#1341)
- [x] storyteller (#1341)
- [x] tavtown (#1341)
- [x] witch (#1341)

Very useful references: (thanks to @galaxyhaxz): https://diablo-evolution.net/index.php?pageid=q1b10

https://diablo2.diablowiki.net/D1_Unused_Dialogues

**Comment by galaxyhaxz** [comment]
Really glad to see this task brought up. It's great for preservation. I had planned on dubbing these myself eventually and then comparing what's on Diablo evolution, as people interpret them differently.

**Comment by galaxyhaxz** [comment]
Also want to mention that despite unused they also translated all of these on the psx to German, french, swedish, and Japanese. We would need a native speaker there to dub those.

**Comment by galaxyhaxz** [comment]
You missed one ;) (`pegboy41.wav` below)

While Diablo Evolution is a good start, it seems to have missing/wrong words, some incorrect punctuation and fractured sentences. Example below.
```
[Diablo Evolution]
Yeah, Tremain. He gets around, doesn't he? Or haven't you heard? 
My friends in some of the other towns say that he passes through. 
Picking up some books here, a pinch of bat claw there. Never seems 
to have the kind of problems most do getting in and out of Tristram, 
that's for sure.

[Mine]
Yeah Tremain! He gets around doesn't he... or haven't you heard? 
My friends in some of the other towns say that he passes through. 
Picking up a few books here, a pinch of bat claw there. Never seems 
to have the problems most do getting in and out of Tristram, 
that's for sure.
```

**Comment by yuripourre** [comment]
@galaxyhaxz 
> You missed one ;) (`pegboy41.wav` below)

Nice catch! Added.

**Comment by FitzRoyX** [comment]
> [Mine]
> Yeah Tremain! He gets around doesn't he... or haven't you heard? 
> My friends in some of the other towns say that he passes through. 
> Picking up a few books here, a pinch of bat claw there. Never seems 
> to have the problems most do getting in and out of Tristram, 
> that's for sure.
> ```

The two commas you removed are grammatically more proper to have.

I would also change "through. Picking" to "through, picking"

**Comment by galaxyhaxz** [comment]
I can see the first comma, but the second one after `around` doesn't sound right to me.

**Comment by FitzRoyX** [comment]
Most English guides call this a tag question
https://learnenglish.britishcouncil.org/grammar/intermediate-to-upper-intermediate/question-tags

**Comment by galaxyhaxz** [comment]
The pause in the speech comes after `doesn't he` which is why I usually don't place commas unless there is a slight pause. You may be correct in this case though.
```
Yeah, Tremain! He gets around doesn't he... or haven't you heard? 
My friends in some of the other towns say that he passes through,
picking up a few books here, a pinch of bat claw there. Never seems 
to have the problems most do getting in and out of Tristram, 
that's for sure.
```

**Comment by FitzRoyX** [comment]
If only it were that easy, putting them where people pause. Speech is so fast and fluid, it's almost easier to look at commas like turn signals for inflection.

I have an ear for these rules and my degree is in English. I'll probably just suggest edits to the submissions rather than do them all. I already see errors in evolution transcripts for Griswold (A bode tale > A bold tale)

**Comment by galaxyhaxz** [comment]
Great! Feel free to go over all 257-existing speeches and look for grammatical and spelling issues!

**Comment by yuripourre** [comment]
@FitzRoyX and if you have time, feel free to help with the transcriptions, too. Some audios are very hard to understand (at least for a non-native speaker).

**Comment by Tumayto** [comment]
@yuripourre I started a Google Sheets here https://docs.google.com/spreadsheets/d/16RmQqahc2euCpbVRW0itKA-QEUVTAE9tWySzkvca3mE/edit#gid=0. I think this may be the best way to keep track of all of it and edit together. Please request access if you're interested in helping. @FitzRoyX I'd love for your assistance with this, too. My next goal is to finish doing a rough transcription of all remaining wavs. I should have more time to listen to them later this weekend. Right now I would appreciate if what I already transcribed could be proofread.

**Comment by Tumayto** [comment]
I finished doing a first pass transcription of all 70 .wavs unchecked in the main post. That was an interesting experience! Note: These are not final yet, but I'd say they're nearly 99% accurate at this point. All that remains is proofreading and likely some minor tweaks.

**Comment by yuripourre** [comment]
@Tumayto that's awesome! I will have sometime today.
