### ISSUE TITLE
Gather vanilla items for testing

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1094]
In order to fully test item generation, we need to find items with each of the possible properties. If you can help find some of these it would be very helpful. Preferably the items would be verified in the original before submitted so that we know that the regeneration code works identical to the original.

You can probably even use item trainers to generate the items, as long as you test that they work after starting a new game.

Items can either be submitted as save games or `PkItemStruct` values
https://github.com/diasurgical/devilutionX/blob/master/SourceT/pack_test.cpp#L111

We are currently missing the following:
- [ ] Ring of Magma/Mystics
- [x] A spell book from the spawn version
- [x] A staff with spell charges from the spawn version
- [x] A healing potion from a barrel or chest in hellfire
- [x] A mana potion from a barrel or chest in hellfire
- [x] A healing potion from a barrel or chest in hellfire on first dungeon level
- [x] A mana potion from a barrel or chest in hellfire on first dungeon level
- [x] A town portal from a barrel or chest in hellfire (this never happens on the first dungeon level)

**Comment by Grotto143** [comment]
> In order to fully test item generation, we need to find items with each of the possible properties. If you can help find some of these it would be very helpful. Preferably the items would be verified in the original before submitted so that we know that the regeneration code works identical to the original.
> 
> 
> 
> You can probably even use item trainers to generate the items, as long as you test that they work after starting a new game.
> 
> 
> 
> Items can either be submitted as save games or `PkItemStruct` values
> 
> https://github.com/diasurgical/devilutionX/blob/master/SourceT/pack_test.cpp#L111
> 
> 
> 
> We are currently missing the following:
> 
> - [ ] Scroll of resurrection bought from Pepin
> 
> - [ ] Item bought from Wirth
> 
> - [ ] Item bought from Adria
> 
> - [ ] A staff with no spells
> 
> - [ ] Tin/Brass
> 
> - [ ] Useless/Bent/Weak
> 
> - [ ] Doppelganger's
> 
> - [ ] Fine/Warrior's/Soldier's/Lord's/Knight's/Master's/Champion's/King's
> 
> - [ ] Clumsy, Dull
> 
> - [ ] Vulnerable/Rusted
> 
> - [ ] White
> 
> - [ ] Plentiful/Bountiful
> 
> - [ ] Fool's Crest/Thundercall/The Protector/Naj's Puzzler",
> 
> - [ ] Lightning
> 
> - [ ] frailty/weakness
> 
> - [ ] the fool/dyslexia
> 
> - [ ] paralysis/atrophy
> 
> - [ ] illness
> 
> - [ ] trouble
> 
> - [ ] pain/tears
> 
> - [ ] Crystalline
> 
> - [ ] fragility
> 
> - [ ] Gnat Sting
> 
> - [ ] flame/fire/burning
> 
> - [ ] Flambeau
> 
> - [ ] corruption
> 
> - [ ] Deadly Hunter/Civerb's Cudgel
> 
> - [ ] Armor of Gloom/Gotterdamerung
> 
> - [ ] IPL_NOHEALMON
> 
> - [ ] IPL_STEALMANA 5
> 
> - [ ] IPL_STEALLIFE
> 
> - [ ] IPL_TARGAC
> 
> - [ ] IPL_FASTATTACK 1
> 
> - [ ] IPL_FASTATTACK 3
> 
> - [ ] IPL_FASTATTACK 4
> 
> - [ ] IPL_FASTBLOCK
> 
> - [ ] IPL_RNDARROWVEL
> 
> - [ ] IPL_SETDAM
> 
> - [ ] IPL_SETDUR
> 
> - [ ] IPL_FASTSWING
> 
> - [ ] IPL_ONEHAND
> 
> - [ ] IPL_DRAINLIFE
> 
> - [ ] IPL_INFRAVISION
> 
> - [ ] IPL_NOMINSTR
> 
> - [ ] IPL_ADDACLIFE
> 
> - [ ] IPL_ADDMANAAC
> 
> - [ ] IPL_FIRERESCLVL
> 
> - [ ] IPL_FIRERES_CURSE
> 
> - [ ] IPL_LIGHTRES_CURSE
> 
> - [ ] IPL_MAGICRES_CURSE
> 
> - [ ] IPL_ALLRES_CURSE
> 
> - [ ] IPL_DEVASTATION
> 
> - [ ] IPL_DECAY
> 
> - [ ] IPL_PERIL
> 
> - [ ] IPL_JESTERS
> 
> - [ ] IPL_ACDEMON
> 
> - [ ] IPL_ACUNDEAD
> 
> - [ ] IPL_MANATOLIFE
> 
> - [ ] IPL_LIFETOMANA
> 
> - [ ] Single player spellbooks

**Comment by AJenbo** [comment]
@Grotto143 not sure what you wanted to say but you just quoted my original post?

**Comment by Tiddalick** [comment]
Can you explain what you mean by this?
"Preferably the items would be verified in the original before submitted so that we know that the regeneration code works identical to the original."

So essentially you want to verify that these attributes and items spawn?

**Comment by AJenbo** [comment]
yeah load the save in 1.09 and DevilutionX and create a new game to check that the items are spawned the same in both.

**Comment by AJenbo** [comment]
Just so I don't have to retype this every time I get new items to dump :D
```cpp
    SDL_Log("{ %d, %d, %d, %d, %d, %d, %d, %d, %d, %d } { \"%s\", %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d } ",
	is->iSeed,
	is->iCreateInfo,
	is->idx,
	is->bId,
	is->bDur,
	is->bMDur,
	is->bCh,
	is->bMCh,
	is->wValue,
	is->dwBuff,
    id->_iIName,
	id->_itype,
	id->_iClass,
	id->_iCurs,
	id->_iIvalue,
	id->_iMinDam,
	id->_iMaxDam,
	id->_iAC,
	id->_iFlags,
	id->_iMiscId,
	id->_iSpell,
	id->_iCharges,
	id->_iMaxCharges,
	id->_iDurability,
	id->_iMaxDur,
	id->_iPLDam,
	id->_iPLToHit,
	id->_iPLAC,
	id->_iPLStr,
	id->_iPLMag,
	id->_iPLDex,
	id->_iPLVit,
	id->_iPLFR,
	id->_iPLLR,
	id->_iPLMR,
	id->_iPLMana,
	id->_iPLHP,
	id->_iPLDamMod,
	id->_iPLGetHit,
	id->_iPLLight,
	id->_iSplLvlAdd,
	id->_iUid,
	id->_iFMinDam,
	id->_iFMaxDam,
	id->_iLMinDam,
	id->_iLMaxDam,
	id->_iPrePower,
	id->_iSufPower,
	id->_iMinStr,
	id->_iMinMag,
	id->_iMinDex,
    id->IDidx);
    ```

**Comment by ZXParagonXZ** [comment]
_Zip Files with images of the items. Each image is labeled. The save files are the same save file just at different points. ( which is why they are separate. )_

**The following covered are:** 
- Warrior's
- Doppelganger's
- Item bought from Wirt
- Item bought from Adria
- Single Player Spellbook
- Gladiator's Ring
- Puncturing
- Vampire's (separate zip)
[Doppel, Warriors, Wirt, Adria, Book, Puncturing, Gladiator's,.zip](https://github.com/diasurgical/devilutionX/files/6176520/Doppel.Warriors.Wirt.Adria.Book.Puncturing.Gladiator.s.zip)
[Vampire's.zip](https://github.com/diasurgical/devilutionX/files/6176521/Vampire.s.zip)

**Comment by ZXParagonXZ** [comment]
_More Zip Files with images of the items. Each image is labeled. The save files in 2 of them are the same save file just at different points. The resist all is it's own character._

**The following covered are:**
- Blood
- Lightning
- Haste
- White
- Of Lightning
- Resist all ( a ring, a weapon, a helmet )

[Haste, White, Of Lightning.zip](https://github.com/diasurgical/devilutionX/files/6176553/Haste.White.Of.Lightning.zip)
[Lighting, Blood.zip](https://github.com/diasurgical/devilutionX/files/6176554/Lighting.Blood.zip)
[Resist All ( 3 items ).zip](https://github.com/diasurgical/devilutionX/files/6176555/Resist.All.3.items.zip)

_**All the above were tested on Vanilla Diablo 1.09. The save files were tested as they are, and by starting a new game to confirm no item changes.**_

**Comment by AJenbo** [comment]
Thanks, added the 12 new items to the tests: https://github.com/diasurgical/devilutionX/commit/4de1c05c17cd209f8edd577bb5f357a1c9f45194

**Comment by ZXParagonXZ** [comment]
_Even more Zip Files with images of the items stats included. Each image is labeled. All saves are the same character except for the Res Scroll._

**The following covered are:**
- Res Scroll purchased from Peppin. (Multiplayer D 1.09)
- Decay
- Resist Fire
- Butcher's Cleaver
- Peril
- Blocking
- Jester's
- Crystalline

[Blocking, Jester's.zip](https://github.com/diasurgical/devilutionX/files/6176909/Blocking.Jester.s.zip)
[Butcher's Cleaver, Peril.zip](https://github.com/diasurgical/devilutionX/files/6176910/Butcher.s.Cleaver.Peril.zip)
[Crystalline.zip](https://github.com/diasurgical/devilutionX/files/6176911/Crystalline.zip)
[Decay, Resist Fire.zip](https://github.com/diasurgical/devilutionX/files/6176912/Decay.Resist.Fire.zip)
[Peppin Scroll of Res.zip](https://github.com/diasurgical/devilutionX/files/6176913/Peppin.Scroll.of.Res.zip)

_**The Res Scroll was tested in Vanilla Diablo 1.09. The rest were tested on Vanilla Hellfire 1.01. The save files were tested as they are, and by starting a new game to confirm no item changes.**_

**Comment by AJenbo** [comment]
And additional 0,06% of the code is now tested :)

**Comment by Katana-Steel** [comment]
my Save file with Ring of Truth and Empyrean Band
[Ring.of.Truth.zip](https://github.com/diasurgical/devilutionX/files/6225765/Ring.of.Truth.zip)

**Comment by AJenbo** [comment]
Gnat Sting: https://dl.dropboxusercontent.com/s/821cfrm1mtz8hyy/single_0.hsv but needs verification in vanilla Hellfire.

**Comment by Chance4us** [comment]
Do you need also the following items?
![gibbous_moon](https://user-images.githubusercontent.com/45902449/114271662-c4656400-9a12-11eb-8960-9ccf98758b6d.png)
![red_armor_of_paralysis](https://user-images.githubusercontent.com/45902449/114271665-ca5b4500-9a12-11eb-8ee5-e30e8abb9aab.png)
Savegame:
[gibbous_moon.zip](https://github.com/diasurgical/devilutionX/files/6289936/gibbous_moon.zip)

**Comment by AJenbo** [comment]
@Chance4us Yeah, the `Red Armor of Paralysis` would cover another test case. Have you verified these in Hellfire 1.01?

**Comment by Chance4us** [comment]
If I load the savegame in vanilla-hellfire the items still are the same.
Is it correct that way?

**Comment by AJenbo** [comment]
Yes, could you also verify the two other submissions here?

Ring of Truth: https://github.com/diasurgical/devilutionX/files/6225765/Ring.of.Truth.zip

Gnat Sting: https://dl.dropboxusercontent.com/s/821cfrm1mtz8hyy/single_0.hsv

**Comment by Chance4us** [comment]
Yes. Just a second.

**Comment by BartyMae** [comment]
I have found Naj's Light Plate, Eater of Souls, Blitzen, Gnat Sting, and Acolyte's Amulet in a DevilutionX Hellfire multiplayer game. Unfortunately, I accidentally sold the Blitzen, but it did generate in my game. I've also seen Plentiful and Bountiful for sale at Adria's, but I've never actually purchased any.

https://dl.dropboxusercontent.com/s/pn9rppnt9a410aa/multi_3.hsv

**Comment by Chance4us** [comment]
Verified:
> Useless/Bent/Weak - Bent
> frailty/weakness - frailty

[bent-frailty.zip](https://github.com/diasurgical/devilutionX/files/6312328/bent-frailty.zip)

**Comment by Chance4us** [comment]
Verified:
> Deadly Hunter/Civerb's Cudgel - Civerb's Cudgel 

[civerb.zip](https://github.com/diasurgical/devilutionX/files/6312356/civerb.zip)

**Comment by Chance4us** [comment]
Do you need some of the following?
oil of hardening
fine axe of might
vicious bow of plenty
red bow of quality
deadly club
plate of protection
ring of vulture

All items are verified.
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6312394/single_0.hsv.zip)

**Comment by AJenbo** [comment]
@Chance4us could you test this https://dl.dropboxusercontent.com/s/pn9rppnt9a410aa/multi_3.hsv from @BartyMae

**Comment by Chance4us** [comment]
@AJenbo In Windows 10 Virtualbox I was not able to load this multiplayer save.
So I'll do a Window 98 installation first. Then I will report as soon as possible.

**Comment by Chance4us** [comment]
In linux-wine is stored a hrinfo_0.drv in C:/Windows for multiplayer if I create a multiplayer character.
So if I rename multi_3.hsv to hrinfo_0.drv and copy it to C:/Windows no character is recognized.
In Windows 10 I was not able to create a hellfire multiplayer character.
Unfortunately, my Windows 98 virtual machine does not work yet.

**Comment by qndel** [comment]
Order I dropped stuff in town (from left to right, starts near Gillian)
Tin
Brass/weakness
Useless
Frailty
Weak
Clumsy
The fool
Dull
Dyslexia
Vulnerable
Atrophy
Paralysis
Trouble
Fragility
Pain
Illness
Speed
Readiness
Corruption

[single_1.zip](https://github.com/diasurgical/devilutionX/files/6313806/single_1.zip)

**Comment by AJenbo** [comment]
> In linux-wine is stored a hrinfo_0.drv in C:/Windows for multiplayer if I create a multiplayer character.
> So if I rename multi_3.hsv to hrinfo_0.drv and copy it to C:/Windows no character is recognized.
> In Windows 10 I was not able to create a hellfire multiplayer character.
> Unfortunately, my Windows 98 virtual machine does not work yet.

hellfire does not officially have multiplayer and we do not support loading hellfire multiplayer heros for various reasons

**Comment by AJenbo** [comment]
> Order I dropped stuff in town (from left to right, starts near Gillian)

need it in the inventory :D

**Comment by qndel** [comment]
Tin
Brass/weakness
Useless
Frailty
Weak
Clumsy
The fool
[single_1.zip](https://github.com/diasurgical/devilutionX/files/6313985/single_1.zip)

**Comment by qndel** [comment]
Dull
Dyslexia
Vulnerable
Atrophy
Paralysis
Trouble
Fragility
Pain
[single_1.zip](https://github.com/diasurgical/devilutionX/files/6313986/single_1.zip)

**Comment by qndel** [comment]
Illness
Speed
Readiness
Corruption
Bountiful
Plentiful
[single_1.zip](https://github.com/diasurgical/devilutionX/files/6313989/single_1.zip)

**Comment by qndel** [comment]
Bent
Tears
[single_1.zip](https://github.com/diasurgical/devilutionX/files/6313991/single_1.zip)

**Comment by AJenbo** [comment]
Thanks for that :)

**Comment by Chance4us** [comment]
> oh, multiplayer is not compatible because hellfre was locked to the computer and wasent official

Will it be enough for Hellfire to verify the items in the single player?

**Comment by AJenbo** [comment]
are there any hellfire-multiplayer only items?

**Comment by Chance4us** [comment]
> are there any hellfire-multiplayer only items?

I have checked as far as I can and I am convinced it is not the case.

**Comment by AJenbo** [comment]
The latest batch increased the tests by 0.11% giving us 7.13% :tada:

**Comment by Chance4us** [comment]
> The list has been updated with what is left, but the names have not been made human-friendly and there might be impossible options.

I no longer understand which items we need.
Does it  refer to unique items (which?) or items with certain prefixes and suffixes?
Can the generation of these items be forced by hardcoding in order to then verify them?

**Comment by AJenbo** [comment]
prefixes and suffixes, I will get around to translating them into their presented names in a couple of days.

I'm not sure what you are saying regarding harcoding? Verifying them is a manual process of loading the save in the original game, starting a new game and checking that none of them morphed.

**Comment by Chance4us** [comment]
> I'm not sure what you are saying regarding harcoding? Verifying them is a manual process of loading the save in the original > game, starting a new game and checking that none of them morphed.

I mean when we force certain items to be dropped by changing the source code.
Afterwards checking that this item does not morph in vanilla.

**Comment by Chance4us** [comment]
I don't know if needed some unique items.
Thunderclap + Holy Defender:
[thunderclap+holy_defender.zip](https://github.com/diasurgical/devilutionX/files/6330860/thunderclap%2Bholy_defender.zip)
![screen02](https://user-images.githubusercontent.com/45902449/115140736-1a509200-a039-11eb-9b70-cba4b63b1e9a.png)
![screen03](https://user-images.githubusercontent.com/45902449/115140745-1f154600-a039-11eb-9a58-5d297ccb7401.png)

**Comment by Chance4us** [comment]
Stonecleaver:
![screen04](https://user-images.githubusercontent.com/45902449/115144419-ca7bc600-a04c-11eb-8545-877521b4f5c4.png)
[stonecleaver.zip](https://github.com/diasurgical/devilutionX/files/6331167/stonecleaver.zip)

**Comment by AJenbo** [comment]
We already have lots of unique items, off cause they are still useful if they have some of the powers that we are looking for.

**Comment by AJenbo** [comment]
@Chance4us i have updated the list to reflect the names you would see in game. There are indeed a lot of unique items on the list so let us know if you find any of them.

**Comment by Chance4us** [comment]
Gnat Sting is already verified.

**Comment by Chance4us** [comment]
Thunderclap is also verified and attached a little above.

**Comment by AJenbo** [comment]
> Gnat Sting is already verified.

It's from a multiplayer hellfire save which cannot be verified since they are not compatible with Hellfire 1.01. How are you verifying things?

**Comment by Chance4us** [comment]
> Gnat Sting: https://dl.dropboxusercontent.com/s/821cfrm1mtz8hyy/single_0.hsv but needs verification in vanilla Hellfire.

I verified your post.

**Comment by AJenbo** [comment]
Thanks both have now been added to the tests.

**Comment by Chance4us** [comment]
Rod of Onan found. In vanilla it looks the same if starting a new game.
![rod_of_onan](https://user-images.githubusercontent.com/45902449/116114477-ab6add00-a6b9-11eb-9f55-1194d928879f.png)
[rod_of_onan.zip](https://github.com/diasurgical/devilutionX/files/6378491/rod_of_onan.zip)

**Comment by Chance4us** [comment]
Flambeau found. In vanilla it looks the same if starting a new game.
![flambeau](https://user-images.githubusercontent.com/45902449/116784873-daf15f00-aa96-11eb-9621-6ac3d41527b2.png)
[flambeau.zip](https://github.com/diasurgical/devilutionX/files/6409678/flambeau.zip)

**Comment by Chance4us** [comment]
Now you can add "Rod of Onan" and "Flambeau" to the tests.

**Comment by Chance4us** [comment]
Ring of Thunder in vanilla new game:
![thunder](https://user-images.githubusercontent.com/45902449/120073804-36187080-c09a-11eb-8873-c60fcfa95be2.png)
[thunder.zip](https://github.com/diasurgical/devilutionX/files/6564805/thunder.zip)

**Comment by Chance4us** [comment]
Acolyte's Amulet in vanilla new game containing also the Ring of Thunder.
Very strange that I found two items in one game.
![acolytes](https://user-images.githubusercontent.com/45902449/120075924-95c74980-c0a3-11eb-81bc-1a1cb37af720.png)
[acolytes.zip](https://github.com/diasurgical/devilutionX/files/6564910/acolytes.zip)

**Comment by AJenbo** [comment]
Those are some interesting items, and good timing for me to add them.

It looks like we might actually have some issues with how we handle `Acolyte's Amulet`, so I will need to investigate that a bit.

**Comment by Chance4us** [comment]
I am happy for all members and that the search is useful.

**Comment by Chance4us** [comment]
Well, all good things come in threes.
Finally I found "The Protector" in the same game.
This savegame also includes Dreamflange, Acolyte's Amulet, Ring of Thunder.

The Protector" in a new hellfire game:
![protector](https://user-images.githubusercontent.com/45902449/120273082-53258d00-c2ae-11eb-9a9c-f359b560a241.png)
[protector.zip](https://github.com/diasurgical/devilutionX/files/6573683/protector.zip)

**Comment by ChaosMarc** [comment]
three Diablo 1.09 savegames attached with a lot of the needed items. Is it a problem if the items morphed once? All of the items come from item packs and are inserted with a trainer. some of them morphed their item type but the affix/suffix stayed the same. after that the items did not morph in new games.

0
- [x] Sharp
- [x] Fine
- [x] Soldier's
- [x] Lord's
- [x] Knight's
- [x] Master's
- [x] Champion's
- [x] King's
- [x] Town portal bought from Adria
- [x] Mana bought from Adria
- [x] Full Mana bought from Adria
- [x] Healing bought from Pepin
- [x] Full Healing bought from Pepin

1
- [x] Gotterdamerung
- [x] Constricting Ring
- [x] Naj's Light Plate
- [x] thorns
- [x] The Grandfather
- [x] The Rift Bow

2
- [x] of burning

[diablo.zip](https://github.com/diasurgical/devilutionX/files/6591314/diablo.zip)

**Comment by AJenbo** [comment]
@ChaosMarc what's important is how they look when starting a new game in 1.09. If you could hare screen shots showing what the items look like in 1.09 (there stats when hovered), then I can add them to the test :)

**Comment by ChaosMarc** [comment]
[screens.zip](https://github.com/diasurgical/devilutionX/files/6591650/screens.zip)
here you go :) all screenshots were taken after starting a new game

**Comment by ChaosMarc** [comment]
[hellfire.zip](https://github.com/diasurgical/devilutionX/files/6592411/hellfire.zip)

and another archive with a savegame and screenshots of all but one of the missing hellfire items:
- Blitzen
- Demon Plate Armor
- Bone Chain Armor
- of the leech
- of devastation
- blacksmith oil
- oil of skill
- oil of accuracy
- oil of death
- oil of fortitude
- oil of hardening
- oil of permanence
- oil of sharpness

as far as I can see now only Ring of Magma/Mystics is missing. sadly I can't find any item pack that includes one of the two

**Comment by AJenbo** [comment]
> ps: what do you mean with "All resistances negative"? how can this be achieved?

It should reduce you resistance to magic, fire and lightning (not just one of them)

**Comment by qndel** [comment]
> > ps: what do you mean with "All resistances negative"? how can this be achieved?
> 
> It should reduce you resistance to magic, fire and lightning (not just one of them)

![image](https://user-images.githubusercontent.com/14297035/120695998-4ff7f000-c4ac-11eb-95d7-cf08f121f490.png)

**Comment by AJenbo** [comment]
@qndel how do you not understand this?

![image](https://user-images.githubusercontent.com/204594/120698115-ddd4da80-c4ae-11eb-84f7-35dfcd3f43fb.png)

**Comment by ChaosMarc** [comment]
I would have liked a more precise explanation of the how, too. There are two possibilities. You need a char with all res negative (maybe by wearing multiple items with a single negative res) , or you need an item that has all 3 res negative which must not inevitably reduce the chars res to negative numbers but probably will. If it's the single item with all 3 res negative, I have no idea what it could be. I have checked. There is no unique wich reduces all 3 res (there are 3 rings that only reduce 2 and buff the third) and I couldnt find a suffix/affix that allows negative res for a magic item

**Comment by AJenbo** [comment]
> If it's the single item with all 3 res negative

We are searching for indiviudal Items, not heros ;)

> I have no idea what it could be. I have checked. There is no unique wich reduces all 3 res (there are 3 rings that only reduce 2 and buff the third) and I couldnt find a suffix/affix that allows negative res for a magic item

I can't easily from the code what item/suffix/affix it would be, just that there is an option for it.

It's apparently cursed, which might have been ovious from it having a negative effect:
```
	case IPL_ALLRES_CURSE:
		items[i]._iPLFR -= r;
		items[i]._iPLLR -= r;
		items[i]._iPLMR -= r;
```

The text would be: `Resist All: -x%`

It does look like this effect might not be applied to any item/suffix/affix, so it might be unused just like `IPL_INFRAVISION`.

**Comment by AJenbo** [comment]
@ChaosMarc you skipped the Oil of Mastery when taking screen shots :)

**Comment by AJenbo** [comment]
All 5 saves combined increased the coverage by 0.13% :tada:

With so many new items found I think it's time to update the list again :)

**Comment by AJenbo** [comment]
Alright went over the test coverage and it seams that we are now down to just 12 missing items fantastic work doing all this scavenging guys :)

**Comment by ChaosMarc** [comment]
![oil-of-mastery](https://user-images.githubusercontent.com/1343751/120774845-f7b00500-c522-11eb-9ed6-8de9439e7ddb.png)
- the missing screenshot of oil of mastery

[staffs.zip](https://github.com/diasurgical/devilutionX/files/6597083/staffs.zip)
- A magical staff that retains the War part of the name
- A Plentiful/Bountiful staff

[mp-scroll-of-resurrect.zip](https://github.com/diasurgical/devilutionX/files/6597110/mp-scroll-of-resurrect.zip)
- MP hero with A scroll of resurrection bought from the healer

**Comment by ChaosMarc** [comment]
[sp-potions-tp.zip](https://github.com/diasurgical/devilutionX/files/6597369/sp-potions-tp.zip)
- A healing potion from a barrel or chest in single player
- A full healing potion from a SARCOPHAGUS in single player (does this count as a chest/barrel?)
- A mana potion from a barrel or chest in single player
- A full mana potion from a barrel or chest in single player
- A town portal from a barrel or chest in single player

**Comment by ChaosMarc** [comment]
[mp-potions-tp.zip](https://github.com/diasurgical/devilutionX/files/6597557/mp-potions-tp.zip)
- A healing potion from a barrel or chest in multi player
- A full healing potion from a barrel or chest in multi player
- A mana potion from a barrel or chest in multi player
- A rejuvenation potion from a barrel or chest in multi player (not asked for, but why not ^^)
- A town portal from a barrel or chest in multi player

**Comment by ChaosMarc** [comment]
[spawn.zip](https://github.com/diasurgical/devilutionX/files/6597693/spawn.zip)

- A spell book from the spawn version
- A staff with spell charges from the spawn version

**Comment by ChaosMarc** [comment]
would generating an item in devilutionX and starting a new game in vanilla be a sufficient check too? if that's the case we could create a "mod" where every monster just drops unique rings and find the missing one very quickly :D

**Comment by qndel** [comment]
> would generating an item in devilutionX and starting a new game in vanilla be a sufficient check too? if that's the case we could create a "mod" where every monster just drops unique rings and find the missing one very quickly :D

its not that easy to do;p

**Comment by AJenbo** [comment]
> would generating an item in devilutionX and starting a new game in vanilla be a sufficient check too? if that's the case we could create a "mod" where every monster just drops unique rings and find the missing one very quickly :D

yes that would be perfectly fine

**Comment by ChaosMarc** [comment]
Great. My "dropmod" is almost complete. No nodrop, no gold drop, every monster drops like a boss-monster. Currently I'm looking into forcing one item type

**Comment by AJenbo** [comment]
> [spawn.zip](https://github.com/diasurgical/devilutionX/files/6597693/spawn.zip)
> 
>     * A spell book from the spawn version
> 
>     * A staff with spell charges from the spawn version

Oh boy, we are not handling this one correct...

![image](https://user-images.githubusercontent.com/204594/120898312-a3904800-c62a-11eb-97dc-0420526933b8.png)

**Comment by AJenbo** [comment]
Updated the list, turns out we needed items from hellfire and not multiplayer, my bad.

**Comment by AJenbo** [comment]
@qndel did you conclude that it is impossible to find Ring of Magma/Mystics in vanilla?

**Comment by ChaosMarc** [comment]
not impossible to find, but always morphing on a new game :(

**Comment by AJenbo** [comment]
would be interesting to see if it's fixable to where a new game in devilutionx would maintain it.

**Comment by AJenbo** [comment]
Spawn comparability is now fixed. It and the other items tess another 0.11% of the game. Just 5 more hellfire items and I think we can close this issue :)

**Comment by qndel** [comment]
> would be interesting to see if it's fixable to where a new game in devilutionx would maintain it.

It's definitely fixable but the problem is setting up a save to test it with. Ideally I'd need one with modified monster seeds so that the next 2 kills would drop some unique first on the list then one that's only findable after getting the first one. Then we could play with adding additional info to the items during the item generation process. I tried to produce such a save but ... it's tricky 😅

**Comment by ChaosMarc** [comment]
this should conclude the search (minus the morphing rings):

[hf-potions-tp-lvl2+3.zip](https://github.com/diasurgical/devilutionX/files/6603932/hf-potions-tp-lvl2%2B3.zip)
- A healing potion from a barrel or chest in hellfire
- A mana potion from a barrel or chest in hellfire
- A town portal from a barrel or chest in hellfire (this never happens on the first dungeon level)

[hf-potions-lvl1.zip](https://github.com/diasurgical/devilutionX/files/6603933/hf-potions-lvl1.zip)
- A healing potion from a barrel or chest in hellfire on first dungeon level
- A mana potion from a barrel or chest in hellfire on first dungeon level

**Comment by AJenbo** [comment]
> this should conclude the search (minus the morphing rings):

lets hope so, but the pods found on the first level has a 50% of being a regular pod so they might be duds :)

**Comment by ChaosMarc** [comment]
both potions came from the same chest. is there any way to verify that they're of the sort you're looking for?

**Comment by AJenbo** [comment]
Only by running the tests and analyzing the results

**Comment by AJenbo** [comment]
> this should conclude the search (minus the morphing rings):

Unfortunately both the healing potions turned out to be just random items, but the others where good :+1: 
And addition of 0.02% of the total code is now tested :D

**Comment by peter-lang** [comment]
I've created an issue, which might be related: https://github.com/diasurgical/devilutionX/issues/5420

**Comment by ChaosMarc** [comment]
@AJenbo this reminded me, that there are still potions to be hunted :D If collected some for you:
[potions1.zip](https://github.com/diasurgical/devilutionX/files/9827323/potions1.zip): 2 life pots from the same chest on lvl1
[potions2.zip](https://github.com/diasurgical/devilutionX/files/9827324/potions2.zip): 1 life, 1 mana pot lying arount on lvl1
[potions3.zip](https://github.com/diasurgical/devilutionX/files/9827326/potions3.zip): 1 full life pot dropped by a monster on lvl1
[potions4.zip](https://github.com/diasurgical/devilutionX/files/9827327/potions4.zip): 1 mana pot dropped by a chest on lvl1
[potions5.zip](https://github.com/diasurgical/devilutionX/files/9827328/potions5.zip): 1 life pot dropped by a monster on lvl1
[potions6.zip](https://github.com/diasurgical/devilutionX/files/9827329/potions6.zip): 1 life pot lying arount on lvl1

**Comment by AJenbo** [comment]
@ChaosMarc nice work, you managed to find 2 level 1 hellfire potions, and 1 from another one, so that coveres the missing potions :)
