### ISSUE TITLE
Is cross-play supported?

### ISSUE THREAD

**Issue by malvarenga123** [diasurgical/devilutionX#1096]
I don't have another supported platform to test this, but can I host and play a game in Windows and someone on a 3DS, for example, join my game?

**Comment by AJenbo** [comment]
Yes, I don't know why the industry has even made this a thing :shrug: 

The only exception is if you are on a Big Endian CPU as we haven't made the network code CPU agnostic yet.

(3DS is little endian ARM so it will work fine with x86/x86_64 etc.)
