### ISSUE TITLE
Exorbitant values for items

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1097]
Maybe I'm wrong, but I can't remember such great values for items.
+73 to strength is kind of extremely high.

>>> By the way, for some reason the mouse pointer is not included when taking a screenshot. <<<

![sword1](https://user-images.githubusercontent.com/45902449/109845483-7f008a80-7c4d-11eb-9915-fd3a6d942b88.png)
![sword2](https://user-images.githubusercontent.com/45902449/109845498-83c53e80-7c4d-11eb-8029-f551c754e18d.png)
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/6077875/single_1.hsv.zip)

**Comment by Chance4us** [comment]
Well Krul has lost them. Also the very expensive staff of apocalypse.
You can use the attached savegame.

**Comment by AJenbo** [comment]
This item was created with an older beta, the issue is already fixed:
![image](https://user-images.githubusercontent.com/204594/109851523-11a42800-7c54-11eb-899d-8511e52305b1.png)
