### ISSUE TITLE
Shifted transparency

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1098]
Shifted transparency  on latest build:
ca75c302ef9d75710a3a6a87d745e81a730e94f1

just started and discovered a new game.
savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6078406/single_0.hsv.zip)

![transparency](https://user-images.githubusercontent.com/45902449/109856397-bb39e800-7c59-11eb-8f1d-d7d83821f23f.png)

**Comment by AJenbo** [comment]
@glebm

**Comment by AJenbo** [comment]
@Chance4us thanks

**Comment by Chance4us** [comment]
@ master AJenbo Thank you very much
