### ISSUE TITLE
Solar shrine

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1099]
Solar shrine doesn't seem to be working properly.
Time at my location when activated :
![Uhrzeit](https://user-images.githubusercontent.com/45902449/109864158-c80f0980-7c62-11eb-9dec-80aeadefcef8.png)

According to the description, the effect should be as follows:
![shrines](https://user-images.githubusercontent.com/45902449/109864433-1e7c4800-7c63-11eb-9a0c-74325e2dd65f.png)

The actual effect:
![shrine](https://user-images.githubusercontent.com/45902449/109864540-3f449d80-7c63-11eb-9452-46605faf1421.png)

Savegame for testing:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6078808/single_0.hsv.zip)

**Comment by Chance4us** [comment]
At 21:01 the effect was as described and the barbarian felt refreshed.

**Comment by AJenbo** [comment]
The same standard code is used for getting the local time, if it's wrong then probably you have the wrong time settings on your computer. It defiantly doesn't check google for the current time :)

You can test this code to see what hour your computer is saying is the current for the local time zone. I would expect this to affect other software on your machine as well if wrong:
```cpp
time_t tm = time(0);
int hour = localtime(&tm)->tm_hour;
SDL_Log("%d", hour)
```

**Comment by Chance4us** [comment]
If I type date in the terminal, it shows
Mi 3. Mär 21:23:00 CET 2021

Is there a way or a command to check the system for correctness?

**Comment by galaxyhaxz** [comment]
If you are on windows you can to go Date/Time settings, set your region and click sync with internet time. I do it once a month to keep in sync.

**Comment by Chance4us** [comment]
i'm on linux and the time is actually synchronized via ntp.
I will soon test the vanilla game under wine and then report about it.
![Bildschirmfoto zu 2021-03-03 23-54-24](https://user-images.githubusercontent.com/45902449/109884086-b175ac00-7c7c-11eb-9062-bc5f8ac3093c.png)
![Bildschirmfoto zu 2021-03-03 23-57-16](https://user-images.githubusercontent.com/45902449/109884109-baff1400-7c7c-11eb-9337-2f2d4f0b4cd6.png)

**Comment by AJenbo** [comment]
your tz data could be out dated. youare free to investigate,but if there is an isue its not goibg to be with devilution, there simply isent room for it in the two lines of code that handles this.

**Comment by malvarenga123** [comment]
Maybe the description (20:00-04:00) is wrong?

**Comment by AJenbo** [comment]
:D you're right:
it's from 21:00-3:59
the 3 others are 19:00-20:59, 13:00-18:59, 5:00-12:59
This means that it does nothing from 4:00-4:59, which probably is a bug :joy_cat: 

```cpp
if (hour > 20 || hour < 4) {
} else if (hour > 18) {
} else if (hour > 12) {
} else if (hour > 4) {
}
```
