### ISSUE TITLE
Stop Sound properly

### ISSUE THREAD

**Issue by ApertureSecurity** [diasurgical/devilutionX#11]
@Chance4us 

If you have time, do you think you can make the sound stop correctly? For some reason, the sound will not stop any more.

**Comment by ApertureSecurity** [comment]
I am looking this I will look more later

**Comment by Chance4us** [comment]
**@ApertureSecurity** 
I tried to understand this issue. I will just open a new pull request.
Unfortunately I do not understand the code entirely and because of that could you please check the new code a little bit and try it out. I wish you a happy new year.

**Comment by Chance4us** [comment]
**@ApertureSecurity** 
Thank you. I just added a new pull request.
S novim godom.

**Comment by ApertureSecurity** [comment]
Added a halt channel which "works"
