### ISSUE TITLE
[Enhancement proposal] Removing a selected skill or spell

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1100]
I have not yet found a way to remove the selected spell or ability.
It probably makes sense to add such a keyboard shortcut, doesn't it?

**Comment by qndel** [comment]
???

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/109984720-5a1b1e80-7d04-11eb-851d-f0f86767765d.png)

**Comment by qndel** [comment]
but ... why ... xD

**Comment by Chance4us** [comment]
How can I choose the empty square?

**Comment by qndel** [comment]
why would you do it? it's pointless

**Comment by Chance4us** [comment]
It makes sense to avoid accidentally consuming a scroll (for example town portal).
Otherwise, when you play with the Barbarian you would have to select the rage skill.
I personally don't want to use it either because it would permanently damage the max health.

**Comment by Chance4us** [comment]
So I would prefer removing a selected skill or spell by a shortcut or otherwise.
What do you think about?

**Comment by qndel** [comment]
that's the most pointless thing I've ever heard of ;) what's next? ability to tell the difference between two identical healing potions? microtransactions? Horse armor? :D
![image](https://user-images.githubusercontent.com/14297035/110034420-b7ca5d80-7d3a-11eb-8d72-95cb40ebfab5.png)

**Comment by AJenbo** [comment]
Shift-click the icon to set it to blank?

**Comment by Chance4us** [comment]
Shift-click which icon below?
![screen16](https://user-images.githubusercontent.com/45902449/110035288-bfd6cd00-7d3b-11eb-8de4-4bffa8f45823.png)

**Comment by Chance4us** [comment]
Savegame for testing:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6086804/single_0.hsv.zip)

**Comment by malvarenga123** [comment]
Off-topic: This reminds me of the follower skills in Diablo 3. Once you choose one, there's no coming back. The only way to have a follower without selected skills is to create a new character.

**Comment by AJenbo** [comment]
> Shift-click which icon below?

It was a suggestion as to how this could be implemented, not saying that it is already there.

**Comment by Chance4us** [comment]
There is a way to remove the selected spell or ability.
But then you have to drop all the scrolls.
I was expecting our masters to see this as an improvement in usability, too.
But it doesn't matter at first, I have even more suggestions. ;-)

**Comment by Chance4us** [comment]
@AJenbo 
It could be also offered an empty box to click, or a keyboard shortcut or several possibilities at the same time.

**Comment by AJenbo** [comment]
You can also do it by removing a staff with an active spell.

**Comment by AJenbo** [comment]
@Chance4us you can now clear it with shift+click:
https://github.com/diasurgical/devilutionX/pull/1106/commits/b34296a4359cc8aee6d3b6dd9b7a3c0f18e573dd

**Comment by Chance4us** [comment]
Really nice. I hope qndel will like it in the future too.

**Comment by qndel** [comment]
I can't see myself ever using it :shrug:

**Comment by Chance4us** [comment]
@qndel You are still completely okay. ;-)
