### ISSUE TITLE
Test Bard / Test Barbarian in Diablo

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1105]
If the diablo.ini contains Test Bard=1 and Test Barbarian=1,
then both characters are depicted in a crippled manner in Diablo.

Expected behavior:
Both characters shouldn't appear in Diablo, even if the values are set.

![1](https://user-images.githubusercontent.com/45902449/110034789-2b6c6a80-7d3b-11eb-99a3-330b672d52c9.png)
![2](https://user-images.githubusercontent.com/45902449/110034819-30311e80-7d3b-11eb-8977-20474bbb8faa.png)

**Comment by AJenbo** [comment]
This is intentional, the profile image will be fixed: https://github.com/diasurgical/devilutionX/pull/936

**Comment by Chance4us** [comment]
Does that mean the Hellfire characters will also be playable in Diablo?

**Comment by AJenbo** [comment]
yes

**Comment by Chance4us** [comment]
That's good news.
