### ISSUE TITLE
Little bug: Town Portal returning to wrong location

### ISSUE THREAD

**Issue by GrayFace** [diasurgical/devilutionX#1110]
**Important information**
Win 7 (64 bit) / DevilutionX version 1.1.0 / Downloaded release

**Describe**
A fun little bug I've encountered. [setup.zip](https://github.com/diasurgical/devilutionX/files/6089909/setup.zip) is a save during step 1, [return.zip](https://github.com/diasurgical/devilutionX/files/6089912/return.zip) is a save after step 2.

**To Reproduce**
1. Set up a portal in Skeleton King's Lair, go through it
2. Enter level 1 of the dungeon, then exit right back to town
3. Use the teleporter in town
4. You'll end up in Level 1 instead of Skeleton King's Lair

**Expected behavior**
Returning to Skeleton King's Lair.

**Comment by qndel** [comment]
Fixed in 1.2.0
