### ISSUE TITLE
Dsync in Hive

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1112]
While testing multiplayer for Hellfire I came across this issue which is also present in the original:

https://www.lurkerlounge.com/forums/archive/index.php?thread-15760-11.html

>  There's also a bug with the Hive where the generation seed gets desync'd somewhere after creating the layout - many times in the Hive the players present will see the identical level structure and paths, but the location of monsters, barrels, chests, and consequently every item they drop, is totally out of sync, which leads to a lot of monsters teleporting when activated on other player's screens, and nobody but the host can pick up items pre-placed on the floor or dropped by monsters/containers. Not really anything you can do but rehost and try again. It seems to happen less often if you visit one of the vanilla dungeons first before going to the Hive.

**Comment by galaxyhaxz** [comment]
Can almost guarantee it's due to the way the level numbers are stored. Since they just hacked the Hive into the Caves algorithm, it's possible it uses one of the seeds from the Caves for the clients and the host is using the correct seed (or vice-versa).

**Comment by AJenbo** [comment]
Yeah was thinking it might also relate to how they didn't properly update the dungeon type. I have that part mostly sorted out here, but there is an issue I still need to debug for it to work correctly:
https://github.com/diasurgical/devilutionX/pull/1031

**Comment by galaxyhaxz** [comment]
Upon further reading:
> For Hellfire, only the player who turns in the quest reward to Celia will see the reward amulet generated, and if that player is anyone other than the host (or whoever is currently acting as host, if they left), it will disappear when they attempt to retrieve it. In general if you wish to attempt to interact with the quests/items at all, only the host should touch them.

Also, glad we could make this happen :)

> Hopefully some day we have an open source Diablo engine where all of the quests work properly in multiplayer. I spent some time working on them only to discover enabling them causes far more problems than I could fix.

**Comment by AJenbo** [comment]
Looks to be because of the extra items droped when cow quest is enabled. Fixed in 1.5.0
