### ISSUE TITLE
Another Ability (NW) in shop

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1117]
![ability](https://user-images.githubusercontent.com/45902449/110205979-74c3d380-7e7b-11eb-9bdf-5478b00d52a6.png)

Savegame: 
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6095254/single_0.hsv.zip)

**Comment by Chance4us** [comment]
It is caused by commit 783e4a70b15c29dc569a03a917bfcefb368c2c56

**Comment by AJenbo** [comment]
Thanks.
Fixed https://github.com/diasurgical/devilutionX/commit/e8fb559e5395cdeda5fcda775985d793e55eabad
