### ISSUE TITLE
[Improvement proposal] make close panels when hitting esc optional

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1119]
Closing the panels is not always convenient if you just want to save the game and keep sorting the items.
If you want to continue playing the game you are forced to open the panels again after saving.

**Comment by AJenbo** [comment]
I don't think this will be done. It's a very narrow scenario and a lot to have a config for.

**Comment by Chance4us** [comment]
It's not a big deal either, just a suggestion.
