### ISSUE TITLE
Black screen when using upscale=0 option

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#112]
When using the upscale=0 option in the diablo.ini there is only a black screen.
In SourceX/miniwin/misc.cpp the functions SDL_CreateRenderer, SDL_CreateTexture, SDL_RenderSetLogicalSize are being used only if upscale=1. So it results in black screen.
After uncommenting the line 352 and 366 i could reach proper output.

**Comment by AJenbo** [comment]
What are your other settings (fullscreen etc)? What system?

When upscale=0 is set the output will be directed directly to the window surface so no render or texture is involved. Your change is basically the same as upscale=1.

**Comment by AJenbo** [comment]
Unable to replicate this on:
Ubuntu 19.04 with Nvidia GPU
Arch with Intel GPU
PowerPC with software render
using latest master https://github.com/diasurgical/devilutionX/commit/73a29f0e68b2ff9f23a319f747f45a905376ddf0

**Comment by Chance4us** [comment]
My settings in the diablo.ini are:

[devilutionx] 
upscale=0
fullscreen=1
scaling quality=0
grab input=1
[Diablo] 
Intro=0
Gamma Correction=100
Color Cycling=1
Sound Volume=0
Music Volume=0

**Comment by Chance4us** [comment]
My Hardware:
Mainboard: Fatal1ty AB350 Gaming-ITX/ac
CPU: AMD Ryzen 3 2200G with integrated GPU "AMD Radeon VEGA"
My OS: Debian Testing with MESA 19.0.3-1 and SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux

**Comment by Chance4us** [comment]
Display: Asus VE228HR (21,5 Inch) Monitor (Full HD, HDMI, 5ms)

**Comment by Chance4us** [comment]
With these setup the output ends up in a black screen. The window title border on the top of the window is visible.

**Comment by AJenbo** [comment]
Try  fullscreen=0 it could be an issue with switching your system to 640x480
