### ISSUE TITLE
[Improvement proposal] Auto pickup gold

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1120]
Auto pickup gold is in fact a useful function.
Unfortunately it feels a bit unnatural because there is no feedback (no sound, no graphical message) when gold is collected at all.
Therefore a suggestion to display a short message with the amount of gold received.

**Comment by AJenbo** [comment]
Just to clarify it originally played the gold drop sound when picking up gold, but I personally found it distracting. But we should defiantly consider how to provide feedback, maybe a second option :/

**Comment by Chance4us** [comment]
Gold Drop sound on pickup would be irritating indeed.
Unfortunately, I don't remember what it was like in Diablo 2.

**Comment by AJenbo** [comment]
D2 did not have an auto pickup feature. D3 has a shorter version of the chime when picking it up.

**Comment by AJenbo** [comment]
I was thinking that maybe this could be "Audio Feedback" and also play a sound when leveling up.

**Comment by Chance4us** [comment]
That would be a good option. 
Is there a matching unused sound in the MPQ file?

**Comment by galaxyhaxz** [comment]
> 
> 
> I was thinking that maybe this could be "Audio Feedback" and also play a sound when leveling up.

It's sad that even the PSX had a sound for leveling up, putting stats in, and other UI button presses. Even sadder is when you walked over several piles of gold, it would pick all of them up at once pressing one button. :S

**Comment by Chance4us** [comment]
@AJenbo Perhaps PSX sounds and features should be built in optionally.
Anyone who have the PSX MPQ files could use it then.

**Comment by joewis** [comment]
> I was thinking that maybe this could be "Audio Feedback" and also play a sound when leveling up.

There is a patch for sound at level up - I haven't checked how it works, because it just works, but could probably back(forward?)-port it.

**Comment by AJenbo** [comment]
Could you figure out what the file names and frame number are for these :)

**Comment by galaxyhaxz** [comment]
Level up sound from PSX below, fix the extension, renamed for github.

[levelup.wav.txt](https://github.com/diasurgical/devilutionX/files/6096364/levelup.wav.txt)

**Comment by joewis** [comment]
Distributing assets would certainly be a problem, I wouldn't even link to it.

I just checked the patch - it's using the sound for IS_QUESTDN, which is nice but may be confusing.

**Comment by galaxyhaxz** [comment]
Yep, you won't be able to do much without providing a new MPQ, even with free/hand made graphics and sounds, it still has to be provided to the end user.

**Comment by yuripourre** [comment]
If I may add my two cents, the level up sound could be a procedural sound. So there would be no need to include extra assets.

Example:
https://stackoverflow.com/a/10111570

**Comment by galaxyhaxz** [comment]
> If I may add my two cents, the level up sound could be a procedural sound.

That's soooo 1986. Are we gonna have cool 8-bit sounds soon? :P

**Comment by joewis** [comment]
> > If I may add my two cents, the level up sound could be a procedural sound.
> 
> That's soooo 1986. Are we gonna have cool 8-bit sounds soon? :P

On a side note, Diablo was released closer to 1986 than to 2021.

Maybe we we can train an AI to talk like Farnham to announce level ups (I'm still looking for a purpose for him).

**Comment by yuripourre** [comment]
@galaxyhaxz 
> That's soooo 1986. Are we gonna have cool 8-bit sounds soon? :P

Well, we can fit the real sound data to a set of (math) functions and generate more high-quality sounds it may not sound so synthetic depending on how it's done.

@joewis 
> Maybe we we can train an AI to talk like Farnham to announce level ups (I'm still looking for a purpose for him).

Oh, you are not alone! I've been thinking a lot about it. That's the main reason I wanted to transcribe the missing audios because it would require as much data as possible.
https://github.com/mozilla/TTS#example-training-and-fine-tuning-lj-speech-dataset

**Comment by qndel** [comment]
@yuripourre I actually used AI on wirt but the results weren't impressive : P

**Comment by yuripourre** [comment]
@qndel that's good to know, do you have any sample? What AI did you use?

**Comment by qndel** [comment]
I don't remember : P I could probably dig something up on discord

**Comment by malvarenga123** [comment]
Can't you use the same sound that is played when you pickup gold manually?
That is what [Basemod](https://www.moddb.com/mods/basemod) does for D2.

**Comment by AJenbo** [comment]
> Can't you use the same sound that is played when you pickup gold manually?
> That is what [Basemod](https://www.moddb.com/mods/basemod) does for D2.

We already play no sound...

**Comment by malvarenga123** [comment]
Sorry, I was thinking of the generic pickup sound from the inventory.

**Comment by julealgon** [comment]
> ...and also play a sound when leveling up.

That reminds me of the level-up sound from the PSX version. I quite liked that one.

**Comment by AJenbo** [comment]
Other mods appear to have used IS_QUESTDN as the level-up sound.

**Comment by galaxyhaxz** [comment]
> That reminds me of the level-up sound from the PSX version. I quite liked that one.

I did too, and a download for it is provided above. Though I still liked the D2 sound better.

DevilutionX is slowly reaching yet another roadblock. Just as there are many game-breaking bugs that won't be fixed to maintain save compatibility, there are many features/improvements/additional fixes that can't be made without providing additional assets.

You have to make a decision on how far you are going to take it. Given users already have to download additional libraries (SDL) and a TTF alongside DevilX, you might as well throw in an additional MPQ. Want a graphic for stash? Want sound for leveling up? Want to fix the broken player animations? You have no choice but to provide the assets. I think it should be fine, as long as the assets come from Diablo or the author gives permission. Example:

`DEVILX.MPQ` asset credits
- Leveling up sound taken from PSX port
- Custom stash graphic made by GalaXyHaXz
- Custom store graphics made by DonJoe123
- Amulet sound taken from Diablo II

As long as you aren't stealing music from other games or taking assets without permission (unless they come from PSX/D2), I think you will be fine.

**Comment by AJenbo** [comment]
We already have devilutionx.mpq in the zip. We will not be distributing content from other games, ports etc. If people want to use content from other games they must own those games and extract the content item selfs.

**Comment by galaxyhaxz** [comment]
Yeah, I figured. You are really shooting yourself in the foot here, especially if you won't even provide user-created content.

**Comment by AJenbo** [comment]
> You are really shooting yourself in the foot here, especially if you won't even provide user-created content.

??? I just sad we already provide user-created content.

**Comment by galaxyhaxz** [comment]
I didn't see a devilutionx.mpq in the zip, at least for the windows release. Are you also against providing fixed/modified versions of existing assets from D1?

**Comment by alican3437** [comment]
I can't use it. I don't understand. There is a problem.

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 12 Mart 2021 Cuma 10:48
Kime: ***@***.***>
Bilgi: ***@***.***>
Konu: Re: [diasurgical/devilutionX] [Improvement proposal] Auto pickup gold (#1120)


I didn't see a devilutionx.mpq in the zip, at least for the windows release. Are you also against providing fixed/modified versions of existing assets from D1?

**Comment by Trihedraf** [comment]
@galaxyhaxz it is in the circleci windows and linux zips

**Comment by alican3437** [comment]
I didn't see a devilutionx.mpq in the zip, at least for the windows release. Are you also against providing fixed/modified versions of existing assets from D1?

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: Anders ***@***.***>
Gönderilme: 12 Mart 2021 Cuma 10:45
Kime: ***@***.***>
Bilgi: ***@***.***>
Konu: Re: [diasurgical/devilutionX] [Improvement proposal] Auto pickup gold (#1120)


You are really shooting yourself in the foot here, especially if you won't even provide user-created content.

??? I just sad we already provide user-created content.

**Comment by AJenbo** [comment]
> I can't use it. I don't understand. There is a problem.

@alican3437 what are you referring to?

**Comment by alican3437** [comment]
Who are you talking to whom are you artificial intelligence a real person?
________________________________
Gönderen: Anders Jenbo ***@***.***>
Gönderildi: 12 Mart 2021 Cuma 10:55
Kime: diasurgical/devilutionX ***@***.***>
Bilgi: alican3437 ***@***.***>; Mention ***@***.***>
Konu: Re: [diasurgical/devilutionX] [Improvement proposal] Auto pickup gold (#1120)


I can't use it. I don't understand. There is a problem.

@alican3437<https://github.com/alican3437> what are you referring to?

**Comment by galaxyhaxz** [comment]
Found it, so I see you have provided widescreen versions of some of the ui art, which is nice. Are there credits provided for the author? The credits background looks so natural it had to have originated from the original 3d models.

**Comment by AJenbo** [comment]
It's a 2D drawing done by BillieJoe, there is more on its way.

**Comment by galaxyhaxz** [comment]
Wow, what an artist. Can't believe how great it looks, I seriously thought it came from some blizzard movie or the like.

**Comment by Chance4us** [comment]
The gold pickup sound is really suitable.
When we talk about a devilutionx.zip, where can it be found and what's content in there?

**Comment by galaxyhaxz** [comment]
I agree, the pickup sound is also played in d2 when picking up items.

It's not a zip file it's the MPQ here: https://github.com/diasurgical/devilutionX/blob/master/Packaging/resources/devilutionx.mpq

The zip just contains the release builds and SDL.

**Comment by Chance4us** [comment]
The credits and the support screen are looking really nice.

**Comment by Chance4us** [comment]
@all What do you think about to "PlaySFX(IS_IGRAB);" also on manual pickup gold?

**Comment by julealgon** [comment]
> @ALL What do you think about to "PlaySFX(IS_IGRAB);" also on manual pickup gold?

We already discussed this on discord. I'm going to implement that for all items on a toggle, so it will make the IGRAB sound for every pickup (like D2).
