### ISSUE TITLE
Strange item attributes

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1121]
When equipped threre is more strength and resistance if using "Axe of swiftness".
Equipped:
![equipped](https://user-images.githubusercontent.com/45902449/110221273-9ea4e680-7ecb-11eb-9aa4-1dd80852a8ee.png)

Not equipped:
![unequipped](https://user-images.githubusercontent.com/45902449/110221277-a8c6e500-7ecb-11eb-986a-5a4b7cac8845.png)

If the object is at the mouse cursor, it will not be shown in the screenshot.
So there is also a bug when taking screenshots because the mouse cursor is not included.

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6096134/single_0.hsv.zip)

**Comment by Chance4us** [comment]
However, I have to add that the attached savegame in the vanilla game behaves the same way.

**Comment by Chance4us** [comment]
But in general, the damage values of the barbarian seem very excessive to me.
So I hope this is normal.

**Comment by AJenbo** [comment]
Your save game contains issues from a previous beta, start a new game to fix it.

**Comment by Chance4us** [comment]
I've already described the following bug.
This happened when I was playing with the magician.
https://github.com/diasurgical/devilutionX/issues/1097

Then I recompiled the game and deleted all of the game saves.
I created the Barbarian afterwards, but the bug repeats itself again.

Again Na Kruhl lost overpowerded items.
Is it sure we have thought of everything?
Should I start a new game again to test it more precisely?

**Comment by Chance4us** [comment]
I will compile the commit e8fb559e5395cdeda5fcda775985d793e55eabad and delete all game saves, retest and report again.

**Comment by Chance4us** [comment]
I tested with "BARD" and all item were OK.
I will test more with the other characters too.

**Comment by Chance4us** [comment]
Tested again with sorcerer. There is definitely still a problem if Na-Krul loses the items.
![screen02](https://user-images.githubusercontent.com/45902449/111068891-dfec5600-84ca-11eb-9aa6-44d262ac5c30.png)

As you can see, taking screenshots is also no longer working properly. 
Savegame:
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/6136679/single_1.hsv.zip)

**Comment by Chance4us** [comment]
I suggest to play a game with a sorcerer and convince yourself.

**Comment by AJenbo** [comment]
@Chance4us do these items morph in to there normal version if you start a new game on the same version?

**Comment by AJenbo** [comment]
Does this only happen with items droped by Na-Krul?

**Comment by AJenbo** [comment]
Ok found the cause, can only affected items dropped by Na-Krul, Slain Hero, Hork Demon/Little Girl.

**Comment by Chance4us** [comment]
As already reported eight days ago, I deleted all savegames and compiled the commit e8fb559.
Then I started a new game and played it quite a long way.
Today I compiled the commit 8e8e316 and continued playing the game. No anomalies occurred until Na Krul.
Only when I saw what items he lost.
Thanks for fast commit 2e3bb92, I will test more again.

**Comment by AJenbo** [comment]
> As already reported eight days ago, I deleted all savegames and compiled the commit [e8fb559](https://github.com/diasurgical/devilutionX/commit/e8fb559e5395cdeda5fcda775985d793e55eabad).

But that was 8 days ago, things change.

**Comment by AJenbo** [comment]
> As you can see, taking screenshots is also no longer working properly.

Screen shots should be fixed now: https://github.com/diasurgical/devilutionX/commit/d6f73b576cbe6c6adbbb3094f6697e6c6d77a57a

**Comment by Chance4us** [comment]
>But that was 8 days ago, things change.

Indeed, I am very happy. Many Thanks.
