### ISSUE TITLE
Make Blood Fountain and Purifying Spring work continually while holding down the mouse button

### ISSUE THREAD

**Issue by Deathrizes** [diasurgical/devilutionX#1133]
Currently Blood Fountain and Purifying Spring requires you to click once for every point of regeneration, as a QoL it would be nice to have it heal at the same rate as long as the user hold down the left mouse button.

**Comment by AJenbo** [comment]
Since most of these changes involve rebalancing/changes to gameplay they probably would fit better with a mod of DevilutionX it self. Most of them would be very easy to implement.

Regarding the Blood Fountain and Purifying Spring, I was thinking that we could make them restore at a rate 20/sec as long as you hold down the mouse button.

**Comment by julealgon** [comment]
@AJenbo 
> Regarding the Blood Fountain and Purifying Spring, I was thinking that we could make them restore at a rate 20/sec as long as you hold down the mouse button.

I'd suggest restoring a percentage of health instead of fixed values. That would make the process take always the same time which should improve gameplay experience.

---

@qndel 
> we could add repeated clicks to my "hold mouse button to keep attacking" if it doesn't cover objects already

Please don't do that if possible... forcing multiple clicks would be a hacky solution to this IMHO. There is no need to rush a solution to this problem, we should add first-class support for the concept of holding the mouse button instead. 

--- 

I agree that most of these things are for MODs, so would suggest splitting this into separate issues to avoid confusion.

**Comment by Chance4us** [comment]
What do you think about the alternative to display the effect of a shrine by pressing the Alt key.
The effects are described approximately as follows.

The blue ones have a predominantly good effect.
The yellows often have bad or unwanted effects. 
The reds have a predominantly bad effect and usually include permanent disadvantages.

Overview attached below:
[Shrines.htm.zip](https://github.com/diasurgical/devilutionX/files/6134692/Shrines.htm.zip)

**Comment by Chance4us** [comment]
I also suggest that "Blood Fountain" and "Purifying Spring" restore 100% immediately, otherwise it is just annoying clicking and destroying the computer mouse.

**Comment by AJenbo** [comment]
If the shrines retored full health instantly it would change how you approach a room fool of monsters and a fountain.

**Comment by Chance4us** [comment]
>> If the shrines restored full health instantly it would change how you approach a room fool of monsters and a fountain.

--> I absolutely agree. It changes the game a bit. 
From my experience these Shrines are in very small spaces and before you can enter the room you have already defeated all or almost all opponents. Then you have to click around to fill mana or life.

As it changes the game, this should of course be optional.

**Comment by galaxyhaxz** [comment]
Darkstone also had life/mana fountains. IIRC they heal you a certain % rather than instantly, so you have to click a few times but not as many.

**Comment by Chance4us** [comment]
What do you think about giving the player an overview of the effects of the shrines in some way?

**Comment by julealgon** [comment]
> What do you think about giving the player an overview of the effects of the shrines in some way?

After activation? I completely disagree with showing additional info before activation.

**Comment by AJenbo** [comment]
I think it's very much not in the spirit of the intent, the only thing that speaks for it is that there are now websites that list all the effects.

**Comment by FitzRoyX** [comment]
> What do you think about giving the player an overview of the effects of the shrines in some way?

If a shrine's effects were displayed on mouseover, you'd never click on a negative shrine. However, you could at least make it so that once a character uses a shrine, all future shrines of that type will have its effects displayed + times used.

**Comment by galaxyhaxz** [comment]
> What AJenbo said is also correct, which is why making shrines a mystery and possibly negative went away in D2. The only way to really stop people from consulting a guide to avoid negative shrines is having all shrines give out a random effect.

That's my line of thinking as well, and sadly it's also why shrines mostly suck in D2 and don't have much of an impact. In D1 it's far to easy to abuse the system by just saving before you click on a shrine. I think making all negative shrines have an additional positive effect could be good, along with forcing the game to save when you exit to prevent all sorts of abuse with this game.

**Comment by julealgon** [comment]
>...along with forcing the game to save when you exit to prevent all sorts of abuse with this game.

There we go! Yes please.
