### ISSUE TITLE
Animation Speed Desynchronization

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#1134]
**Important information**
Windows 10 / DevilutionX 1.1.0 / download

**Describe**
Animation speeds in multiplayer are not synchronized. This stems from a bug in vanilla D1 but is worse in DevilutionX. In vanilla D1, animation speeds of other players appear to take a longer amount of time than shown on the other players' games. In DevilutionX, other players appear to use the animation speeds of your own character's class, however in certain instances, I noticed that the animation speeds appear to be absurdly faster than expected.

**To Reproduce**
1. Open 2 instances of DevilutionX
2. Get a Rogue and Warrior into a game and enter dungeon.
3. Observe different combinations of weapon usage from the other instance of DevX.

**Expected behavior**
Your own animation speeds should be exactly the same as the animation speeds other players see on your character. 

**Screenshots**
Videos provided

**Additional context**
This is a long time problem in vanilla as well which has always affected PvP. from my own observation, I noticed that other players will see a Rogue shooting 12 arrows for every 16 arrows that she actually shoots. If all these arrows were making contact with another player, the player being hit would only see 12 arrows hit them, but lose HP 16 times, with only 12 hit recoveries.

The first video with 2 Rogues is in vanilla. This footage is from the Rogue, and another Rogue watching the rogue. In this same scenario in DevilutionX, the Rogue's bow speeds appear to be perfectly syncronized, leading me to conclude that other player's animations are based on the animation speeds of your own player class.
https://user-images.githubusercontent.com/68359262/110415756-713d7180-8060-11eb-8814-9be397130246.mp4

The second video is taken in DevilutionX 1.1.0. This was also tested watching a warrior swing a sword. He appeared to the Rogue as swinging the sword so fast the sword never appeared to go in front of him, as if he was swinging a lasso.
https://user-images.githubusercontent.com/68359262/110415771-7c909d00-8060-11eb-9f8f-6dce102600a1.mp4

**Comment by AJenbo** [comment]
Have you tried adding an artificial delay to the network to see if it causes it to behave more like you are used to it from vanilla?

**Comment by kphoenix137** [comment]
> 
> 
> Have you tried adding an artificial delay to the network to see if it causes it to behave more like you are used to it from vanilla?

I'm not sure how to do that, no. If it helps, I can try testing it out with another player and compare videos

**Comment by AJenbo** [comment]
Run one game from a VM and delay its network with something like https://blog.mrpol.nl/2010/01/14/network-emulator-toolkit/

**Comment by kphoenix137** [comment]
https://user-images.githubusercontent.com/68359262/110426956-fb8fd080-8074-11eb-9e23-f997bb48464a.mp4

barbarian shooting a bow. Top is Rogue's screen, bottom is Barb's screen

**Comment by AJenbo** [comment]
I can easily see how this could have cascaded in to sever game desync over the course of a level

**Comment by kphoenix137** [comment]
I'd like to expand a bit more on this bug after I've been spending a lot of time attempting to fix the issue. It appears that for the first 3 shots, the animation correctly restarts after pnum's action frame (with the provided fix in #2024, however, subsequent shots will not repeat after the action frame, and instead will appear to show the player performing the entire animation until they reach the point where they would begin standing again, and then repeat the next shot.
