### ISSUE TITLE
Moving Adria and Wirt

### ISSUE THREAD

**Issue by Deathrizes** [diasurgical/devilutionX#1135]
I propose moving Adria and her hut to where the house is just north of where the town portals spawn like in the Hellfire v.102.A5 patch. Also moving Wirt to the west of Farnham next to a tree.
![image](https://user-images.githubusercontent.com/80169548/110416696-26bcf480-8062-11eb-9f8c-7fd16ed30dee.png)
![image](https://user-images.githubusercontent.com/80169548/110416714-30def300-8062-11eb-82ac-1335d2bb69d6.png)

**Comment by AJenbo** [comment]
I saw that Hellfire 1.02.A5 has MPQs included, they are probably responsible for the new location of the hut.
As for With and Adrias location that is down to the application so we would need to make that change and sync it for multiplayer.

**Comment by AJenbo** [comment]
The other house :shrug:

**Comment by julealgon** [comment]
> The other house 🤷

My point is that the map would become too umbalanced with vast regions having nothing to interact with. I'd just reduce the actual map at that point.

Also, there is a problem with moving Adria since there are voice lines talking about her being "away from the village" and "across the lake". Changing her position would require revisiting those lines IMHO (probably removing them since we can't easily alter the audio).

**Comment by AJenbo** [comment]
Personally, I'm not a fan of moving them, though I know a lot of people prefer it for QoL, but we have run and game speed already :P

Definitely this should not be the default if at all.

**Comment by AJenbo** [comment]
P.s. I'm thinking that we don't edit the town level at all and instead let people use the Hellfire 1.02.A5 MPQs for that, all we would do is add an option to reposition the two towners (their location is hardcoded) for compatibility with people using those MPQs.

But this is also a bit of a slippery slope, maybe it's another one best left for a mod?

**Comment by julealgon** [comment]
> But this is also a bit of a slippery slope, maybe it's another one best left for a mod?

If it needs a non-generic solution to support, I'd vote to avoid it. I wouldn't want to be constrained by a third party file in DevilutionX.

**Comment by galaxyhaxz** [comment]
I agree with what julealgon said. Wirt and Adria being far away kinda has to do with the games lore. I think one way to handle this is maybe make warping points in town that teleport you to the other parts, like a waypoint but only for town, similar to the warp pads in Lazarus laie

**Comment by AJenbo** [comment]
ok, i think we are not going to have this option, but it would be very easy for a mod to do by simply using the existing hfoptx.mpq and changing the x/y of wirth and adria https://github.com/diasurgical/devilutionX/blob/master/Source/towners.cpp#L320 if someone starts such a mod i would be happy to help them out.

**Comment by galaxyhaxz** [comment]
Already one step ahead of you. They don't believe in social distancing!
![Untitled](https://user-images.githubusercontent.com/65138215/110609308-b772fd80-8152-11eb-9f44-7c68c6a8bef4.png)
