### ISSUE TITLE
Belt items cloning and creating them with wrong item image

### ISSUE THREAD

**Issue by ajes** [diasurgical/devilutionX#115]
When I start the game, and choose potion from the belt and then place it back it get cloned and is presented as dagger. It does not disappear from my "hand" but is presented as item, that cannot be used (red color). I can place it on the ground as "full potion of mana"

Screenshots as a proof:
[https://imgur.com/a/Y5OMEpc](https://imgur.com/a/Y5OMEpc)

Environment:
Fedora 30 x86_64. Build using SPEC file.

**Comment by AJenbo** [comment]
This is a known issue with 64bit builds:
https://github.com/diasurgical/devilutionX/issues/53
This is likly caused by CheckInvPaste https://github.com/diasurgical/devilution/blob/master/Source/inv.cpp#L685 not being cleaned upstream yet.
