### ISSUE TITLE
Unable to open chest in Ogden's Tavern Sign quest after talking to Snotspill

### ISSUE THREAD

**Issue by Tiddalick** [diasurgical/devilutionX#1152]
Running 64 bit build of devilutionX 3453, created automatically on circleci.

I am unable to open the Locked chest that holds Ogden's sign.
I have spoken to Snotspill who repeats his instruction to kill the 'Big Uglies'.
I already had the quest from Ogden originally.

I am unable to proceed with the quest and the game. I include a savegame at the location for testing.

I have enabled some of the additional ini settings, specifically the autogold pickup, monster health bars and the xp bar.

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6116925/single_0.zip)

**Comment by AJenbo** [comment]
intereatin thatsthe secoubd report about quests being stuck on 64bit windows. could you test with te 32bit build

**Comment by AJenbo** [comment]
what does the 3453 number refer to

**Comment by julealgon** [comment]
I think I heard in one of the streams that this happens in vanilla as well.

Question to OP: was this game started from scratch? Or did you play this character (and reach this quest) after playing with some other character/save in the same session, without quitting to desktop?

The Valor quest has a similar bug in vanilla where it becomes unoperable if you get there after having already played another character without quitting the game.

**Comment by qndel** [comment]
I edited

**Comment by AJenbo** [comment]
i know, but that doesn't answer the question :)

**Comment by AJenbo** [comment]
@alanbirtles how was the faulty build compiled?

**Comment by alanbirtles** [comment]
I'm pretty sure I was using a Circle Ci build from around the 3rd March (according to my download history)

**Comment by AJenbo** [comment]
Ok, I think that isolates this to a Mingw64-64bit issue then.

**Comment by alanbirtles** [comment]
Just tried a release visual studio build of the latest master with that save and it shows the same issue

**Comment by qndel** [comment]
well, it  shows 
![image](https://user-images.githubusercontent.com/14297035/110688969-74606b00-81e2-11eb-9f08-21de2e9dc428.png) for me, the question is what caused that situation

**Comment by AJenbo** [comment]
Yeah, the save is probably no good. Need to test with a fresh game.

**Comment by AJenbo** [comment]
Hmm Talk contains the value of the _speech_id which were broken in between https://github.com/diasurgical/devilutionX/commit/44a4224aad245db125b90aa3ca47595c9a5db5c5#diff-2c75719c0d772b1199a6bf80f45bbbc1335747473f0c08590b917d41a08e8b50 and https://github.com/diasurgical/devilutionX/commit/44a4224aad245db125b90aa3ca47595c9a5db5c5#diff-2c75719c0d772b1199a6bf80f45bbbc1335747473f0c08590b917d41a08e8b50

**Comment by AJenbo** [comment]
Still, it's a reasonable way to beta test :)

**Comment by AJenbo** [comment]
Talk 21 is TEXT_BANNER11 and at that state it expects TEXT_BANNER10, or that the quest hasn't progressed stage 2 yet.

The change to _speech_id probably shouldn't have affected this since the cow texts are much lower in the list. Also it was _sfx_id chat was actually charged ...

**Comment by AJenbo** [comment]
@alanbirtles @Tiddalick are you playing Hellfire or Diablo?

**Comment by qndel** [comment]
hellfire obviously since saves are .hsv

**Comment by AJenbo** [comment]
Haven't unziped them :)

I can confirm that the quest works correctly using a Linux 64bit build of d0c675b (Hellfire).

Could someone verify the issue using a new game and this build: https://19945-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

**Comment by AJenbo** [comment]
Please test this build to see if the issue is still present: https://19995-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

**Comment by julealgon** [comment]
> I think you should be able to edit the title?

Nope.

**Comment by Tiddalick** [comment]
Wow you move fast on these things.

I will try the test build and see what it does and then edit this comment.

> what does the 3453 number refer to
It seems each CircleCI  build is numbered, I was using that specific build.

**Comment by AJenbo** [comment]
ok looks like that would be 103cde5 (whatwe need is the commit hash), this was after the suspected commit.

**Comment by AJenbo** [comment]
This issue appears to be specific to Windows 64bit builds via mingw

**Comment by Tiddalick** [comment]
I just tried another round of this using both the x86 and x64 builds using the latest auto compiled version on circleci (reports as 1.1.0-56ACA000). At time of writing this it was generated 5 hours ago.

I can report that the issue still exists for both builds, not just the x64 version.

**Comment by AJenbo** [comment]
@Trihedraf this issue is caused by the Unique monster names being duplicated in the 64bit Windows builds. This isn't the case for 32bit build, and idea what would cause this?

![image](https://user-images.githubusercontent.com/204594/111026927-6894c480-83ed-11eb-82f5-869255dc024a.png)

This leads to this very unintuitive situation
```cpp
monster[i]._uniqtype = UMT_SNOTSPIL + 1;
// UniqMonst[monster[i]._uniqtype - 1].mName != UniqMonst[UMT_SNOTSPIL].mName
```

**Comment by Tiddalick** [comment]
Just confirming that the recent build does indeed fix this problem.
Checked with the x64 build.

**Comment by AJenbo** [comment]
It fixes the specific issue but not the underlying problem. Turns out that LTO for Windows is broken on GCC 8.3.0, 9.3.0 fixes it for 32bit but not for 64bit.

@Trihedraf I'll just disable LTO on Windows for now.
