### ISSUE TITLE
Camera has the wrong position for about a half second after loading a savegame which was saved while player is moving

### ISSUE THREAD

**Issue by FluffyQuack** [diasurgical/devilutionX#1160]
This is an extremely minor issue as it doesn't impact gameplay and it's only barely noticeable. But it's also easy to fix whenever we have a system for adding new variables to the savegame. Just save/load these from ScrollInfo:

ScrollInfo._sdir
ScrollInfo._sxoff
ScrollInfo._syoff

And these two if my automap jitter fix PR is approved:
ScrollInfo.pxoffDiff
ScrollInfo.pyoffDiff

**Comment by AJenbo** [comment]
good news such a system does exist https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L896

**Comment by FluffyQuack** [comment]
> good news such a system does exist https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L896

Is that what we'll be using for any kind of data addition to the savefile?

How that would work if we ever remove stuff? For instance, if we decide "hotkeys" is no longer necessary for whatever reason, would it always exist in save files which added it even if it's no longer loaded?

**Comment by AJenbo** [comment]
We could strip the hotkeys file if we know it's no longer needed. To be compatible saves should have a fix size of 2048 files, about 50 are used by the original game and the rest are available for extensions.
We also thought about adding a sqlite file or json for structured data.
