### ISSUE TITLE
Store cursor disappears after purchasing Wirt's item

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#1162]
**Important information**
Windows 10, latest `master` version (commit 75b351e6).

**Describe**
After purchasing Wirt's item, the cursor disappears on the store menu:

Tapping the arrow keys restores it.

**To Reproduce**
1. Purchase Wirt's item
2. Notice the store UI right after the purchase is made

**Expected behavior**
The cursor should automatically shift to the "Talk" option (double check behavior with vanilla, not 100% sure on this one)

**Screenshots**

![image](https://user-images.githubusercontent.com/461579/110882487-c5469100-82c0-11eb-9495-cd3b2ca20e1e.png)

**Comment by AJenbo** [comment]
Fixed by https://github.com/diasurgical/devilutionX/commit/f16ebb349dde4d3013ffd88a6c50797698c30a58 ... after cleaning up most of the file...
