### ISSUE TITLE
Lazarus bugged and "I can not cast that here" when using elexir/book

### ISSUE THREAD

**Issue by Tremain84** [diasurgical/devilutionX#1175]
Hello,
I am running the newest test version of devilutionX classic diablo: https://18553-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip
(I don't run hellfire and I didn't compile/add anything by myself).
I am using a Windows 10 PC (Ryzen 5600x + RTX 3080)

I encountered 1 major and 2 minor problems.

1. When entering Lazarus room I stone formed him to kill the other minions. Stone form wore off after a few seconds and he bugged out and just stood there doing nothing. I could not hit or kill him. Stoneform only lastet a few seconds and he repeated his dialogue over and over again when I clicked on him. Going back to town and again to him, didn't help. I had to restart the game.

2. When using an elexir/book with right click and the character is in town he says "I can not cast that here" or if no spell is selected "I have no spell ready" -> not a mayor problem but annoying.

3. When casting a spell, I often cast it twice in a row. So I teleport and it works but then he teleports again, but to the same location because my curser is still there from the first teleport -> I really hate this because I run out of mana with my Warrior/Rogue after 1 cast this way.

PS: Had a windforce drop before laz :)

Edit1:
Ok, I just tried Lazarus with my Rogue on normal difficulty as well and without using stonecurse I had the same problem, he just stands there is unkillable and just repeats his dialogue when clicked on.

If I play on the normal 1.1.0 build I can kill Lazarus and he behaves normal. Also bug 2 and 3 don't occure as well.

Edit2: testbuild version linked

**Comment by AJenbo** [comment]
What do you consider the latest test version? Is it 64bit or 32bit?

**Comment by AJenbo** [comment]
do you have a save we can use to replicate with

**Comment by Tremain84** [comment]
I run the x64 test build.
I can send you the diablo.ini file + the save file of the rogue I used or is there anything else you need?

PS: I have the 1.1.0 version also installed and I run the Test build. But I deleted the diablo.ini before doing so.

**Comment by AJenbo** [comment]
but what version did you test, there where 13 test builds just that day, but you dont even specify that was when you got the build, and similar issues on windows 64bit where addressed.

Why send things to me privately instead of attaching them to the issue here on github?

**Comment by Tremain84** [comment]
I used the testbuild you linked me via PM:
https://18553-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

I send you the files via pm, because I cant attach them to my post it says "We don't support that file type"
-> Trying to find a workaround since it wont accept rar files as well

**Comment by qndel** [comment]
it accepts zip 🙄

**Comment by Tremain84** [comment]
Yes, I run Winrar. Downloaded Winzip testversion and created a zip file :)
[Save and ini file.zip](https://github.com/diasurgical/devilutionX/files/6136447/Save.and.ini.file.zip)

**Comment by AJenbo** [comment]
> I used the testbuild you linked me via PM:
> https://18553-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

Ok, that is version v1.1.0 - 32ebc242 (version is in the menu, and shows if you press v in game) which is 9 days old, that's a lot around these parts :)
You can always get the latest from [CircleCI](https://app.circleci.com/pipelines/github/diasurgical/devilutionX) and downloading the latest artifact.

Please give the latest build a test and see if the issues have already been solved: https://20837-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

**Comment by galaxyhaxz** [comment]
It wouldn't let me upload zip files, I used 7-zip 18.05 to create them.

**Comment by Tremain84** [comment]
Ok I ran the new test build v.1.1.0-9EA85118
All 3 bugs are gone :) 
However, one of the most important features doesn't work anymore -> hold left mouse to attack. I hope this gets implemented since withouth it Rogue and Warrior are unplayable for me (especially with swiftness/haste weapons).

Some more feedback.
The gold auto pick up was great and felt very natural.
I am also happy to see that "Enable All Quests for Single Player=0" was integreated. I might go for another singleplayer run if it works.

**Comment by AJenbo** [comment]
> However, one of the most important features doesn't work anymore -> hold left mouse to attack. I hope this gets implemented since withouth it Rogue and Warrior are unplayable for me (especially with swiftness/haste weapons).

Yeah, this is not the QoL branch but main trunk.

**Comment by Tremain84** [comment]
> 
> 
> > However, one of the most important features doesn't work anymore -> hold left mouse to attack. I hope this gets implemented since withouth it Rogue and Warrior are unplayable for me (especially with swiftness/haste weapons).
> 
> Yeah, this is not the QoL branch but main trunk.

Ah OK. How can I get it included? Because my arm starts to hurt withouth this change?
Will it be included in 1.2.0 ?

PS: Wizzard also had no trouble killing Laz. 
But its kinde strange. Yesterday a Windforce and an Eaglehorn dropt and today with my Wizzard two Eaglehorns dropt in the same game. Was this insane luck or did some kind of dropchance change is also included in the test build?

**Comment by Tremain84** [comment]
Hey Jenbo
Where can I finde the latest test builds (maybe including the quality of life changes? So I can test the latests version.
I checked on Gitgub, but could not find it.

Thx a lot :)

________________________________
Von: Anders Jenbo ***@***.***>
Gesendet: Sonntag, 14. März 2021 11:30
An: diasurgical/devilutionX ***@***.***>
Cc: Tremain84 ***@***.***>; Author ***@***.***>
Betreff: Re: [diasurgical/devilutionX] Lazarus bugged and "I can not cast that here" when using elexir/book (#1175)


I used the testbuild you linked me via PM:
https://18553-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2F18553-143324737-gh.circle-artifacts.com%2F0%2Fdevilutionx_x64.zip&data=04%7C01%7C%7C444cad390abc4d7655e208d8e6d42ced%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513146240381685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WXlVHs6OEVT9gKPZWJrE9JNZfTx85ghSxOmPKW9Wq8U%3D&reserved=0>

Ok, that is version v1.1.0 - 32ebc24<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdiasurgical%2FdevilutionX%2Fcommit%2F32ebc24263f6a19a6eb35637e3e2ea3f06ad0dd9&data=04%7C01%7C%7C444cad390abc4d7655e208d8e6d42ced%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513146240391642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xs9WPWMBY5Xy1UoKNC03F7fFQLKDvxbU7l5M5coGcQM%3D&reserved=0> (version is in the menu, and shows if you press v in game) which is 9 days old, that's a lot around these parts :)
You can always get the latest from CircleCI<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fdiasurgical%2FdevilutionX&data=04%7C01%7C%7C444cad390abc4d7655e208d8e6d42ced%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513146240391642%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=phI46GSl9DzxEeYoRUcc2nFzCIwELRde65PjPGRL1gQ%3D&reserved=0> and downloading the latest artifact.

Please give the latest build a test and see if the issues have already been solved: https://20837-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2F20837-143324737-gh.circle-artifacts.com%2F0%2Fdevilutionx_x64.zip&data=04%7C01%7C%7C444cad390abc4d7655e208d8e6d42ced%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637513146240401609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bO4rfVgSyTSnyfsfKHhdokCXENLS9y4DEahWt8kytyA%3D&reserved=0>

**Comment by AJenbo** [comment]
> You can always get the latest from [CircleCI](https://app.circleci.com/pipelines/github/diasurgical/devilutionX) and downloading the latest artifact.

**Comment by Tremain84** [comment]
Thank you 😊

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Anders ***@***.***>
Gesendet: Montag, 15. März 2021 23:00
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [diasurgical/devilutionX] Lazarus bugged and "I can not cast that here" when using elexir/book (#1175)


You can always get the latest from CircleCI<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fdiasurgical%2FdevilutionX&data=04%7C01%7C%7C3e6d811c134d477856dc08d8e7fdc8bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637514424461391867%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cQMp8%2BMYWXaPqkD5TkMJs4TkFSXFgJ21i7wJA89bSRE%3D&reserved=0> and downloading the latest artifact.
