### ISSUE TITLE
Screenshot does not include a mouse cursor

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1187]
Screenshots do not contain a mouse cursor or an grabbed item on it.

Screenshot should be like following.
![screen01](https://user-images.githubusercontent.com/45902449/111072555-6872f280-84db-11eb-84a0-d21cf0e9d477.png)

Screenshot should not be like following.
![screen02](https://user-images.githubusercontent.com/45902449/111072574-77f23b80-84db-11eb-8d2a-90c6b88457dc.png)

**Comment by AJenbo** [comment]
Are you using a hardware cursor?

**Comment by AJenbo** [comment]
How were the two screenshots produced?

**Comment by Chance4us** [comment]
> Are you using a hardware cursor?
How can I find out that I'm using it?

**Comment by Chance4us** [comment]
The top one was made by a desktop screenshot tool.
The second was done by pressing the print key,
As far as I know, the in-game tool is then used, so that the screen briefly turns red.

**Comment by AJenbo** [comment]
We implement the same behavior as the original so this is not a bug:
![image](https://user-images.githubusercontent.com/204594/111078367-52722b80-84f5-11eb-9c86-0274b5ba555e.png)

**Comment by galaxyhaxz** [comment]
Diablo II captures the cursor in screenshots. Perhaps it should be worth implementing?

**Comment by AJenbo** [comment]
or use the OS or steam overlay etc

**Comment by Chance4us** [comment]
At least it's satisfying to know that it's not a bug.
