### ISSUE TITLE
Sound issues regarding npc dialogue

### ISSUE THREAD

**Issue by mjhmiller** [diasurgical/devilutionX#1193]
using odroid go super with retroOZ firmware, found voiced npc dialogue to sometimes be fine, and other times sounds very bad almost like a bad midi file sound in a way

i have this installed on an rg350m with no issues, not sure what that means but there you go for what its worth

**Comment by qndel** [comment]
either a duplicate of https://github.com/diasurgical/devilutionX/issues/230 or not something we'd deal with anyway

**Comment by AJenbo** [comment]
your device has a broken SDL version, upgrade or down grad to one that isen't.
