### ISSUE TITLE
Ingame chat hardcoded to US layout

### ISSUE THREAD

**Issue by RicoLeNecro** [diasurgical/devilutionX#1195]
Hello there,

This is probably related to issue #1026 but since I typically play multiplayer in the same room as my sister, I hadn't tried text chat yet until yesterday.

So, in case that makes any significant difference, I'm using DevilutionX v1.1.0 (from devilutionx-windows-i386.zip) on Windows 10 x64, v20H2 and up to date with the "French (France)" keyboard layout (see https://en.wikipedia.org/wiki/AZERTY#/media/File:KB_France.svg for reference)

I've noticed that while typing text in the chat field during a multiplayer game, while the alpha layout may seem to be correctly recognized because typing "AZERTY" does show as "AZERTY" and not "QWERTY", some keys seem to not be recognized at all, or not as the right character. By that I mean that either no character appears when trying to type them, or it's not the correct character that appears.

Here's a list (might not be completely exhaustive)

Numpad:
- Numpad numbers, Numpad "/", numpad "*" and numpad "." are not recognized
- Numpad "+" is replaced with "="
- Numpad "-" is correctly recognized

On the alpha part of the keyboard:
- "<" and ">"  (between left shift and the "w" key) are not recognized
- on the alpha pad, "," and ";" are correctly recognized, but holding shift while using these should produce  "?" and ".", yet "<" and ":" appear instead
- the key with "=" and "+" (on the left of the backspace key) works fine, but the key one position further left doesn't do anything
- the keys with "^", "$", "ù", "*", ":" and "!" do not work
- the keys above AZERTY… are recognized as numbers unless Shift is held, which is opposite of the normal behavior on french keyboards, and capslock has no effect on that
- Assuming we'd accept the weirdness about inverted "Shift" key behaviour for those keys, then when holding Shift and typing on the keys above AZERTY… from 1 to 0, we should get the following: &é"'(-è_çà but instead we get the same result as if we were typing on an US keyboard, that is !@#$%^&*()

I suppose I should also point out that the official Diablo game, at least when patched in 1.09, did not have that issue.

Also, the issue only happens when trying to use chat in game, but every key is recognized as it should when entering the name for a new character or when setting the password before creating a multiplayer game.

**Comment by AJenbo** [comment]
The game is still using raw input so chat has this issue. I'm painfully aware of it since I'm on a Danish keyboard.

The UI is clean code using SDL_text. Eventually, we will get around to refactoring how keyboard input is handled.
But it will probably be a while unless someone else is willing to do the work for this.

Not that if I close this issue it's not because it's ignored but because it has long-time prospects, and is somewhat ovious.
