### ISSUE TITLE
Monsters are duplicated when killed

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1198]
On the latest build, the enemies are duplicated very often when they are killed.
I suspect the problem has only existed for a few last commits.

It looks like the following.

[psychorb.mkv.zip](https://github.com/diasurgical/devilutionX/files/6141776/psychorb.mkv.zip)

**Comment by Chance4us** [comment]
Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6141810/single_0.hsv.zip)

**Comment by qndel** [comment]
does it happen only to hive/hellfire monsters or all?

**Comment by Chance4us** [comment]
I have the impression that it also happens in the Crypt.
It could possibly be if the barbarian is equipped with the axe.

**Comment by Chance4us** [comment]
Finally I could only guess why it happens.

**Comment by Chance4us** [comment]
It probably happens to all types of monsters.

**Comment by AJenbo** [comment]
you aren't by any chance using a doubleganger item? If so that's how it's supposed to work.

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/111199236-b44b9780-85c0-11eb-94fd-8a17222fa1f0.png)

**Comment by Chance4us** [comment]
Yes, the barbarian is equipped with a two-handed axe in this case.
But I don't understand why one monster should be replaced by a copy of it if it will be killed.
I've never seen that happen in the past 20 years.

**Comment by AJenbo** [comment]
Must not have used this type of item much :shrug: 

https://diablo2.diablowiki.net/D1_Modifiers

**Comment by Chance4us** [comment]
In fact it is my fault.
Yeah i just saw it. I'm sorry, I didn't expect it.

**Comment by Chance4us** [comment]
I'm really surprised.

**Comment by AJenbo** [comment]
No worries, I'm not sure I have ever seen this in game.

**Comment by AJenbo** [comment]
In case you want to scrutinize that weapon a bit more:
![image](https://user-images.githubusercontent.com/204594/111200191-c548d880-85c1-11eb-810a-23c60ef881d6.png)

**Comment by julealgon** [comment]
LOL for a moment I thought something wrong was going on with the cleave-attack logic but no, just a doppelganger item 😆

**Comment by AJenbo** [comment]
Some of your items are now part of our test suite to make sure that item generation happens correctly, so this issue was defiantly not for nothing :)
https://github.com/diasurgical/devilutionX/pull/1220/commits/3fe2143cd00b4449f6efead8c527f4ce9e26bf87
