### ISSUE TITLE
TESTED on RPI3 - RUNS OK UNDER MESA

### ISSUE THREAD

**Issue by Askmewho** [diasurgical/devilutionX#120]
HI! Yeah!! its working properly!!
I post here because some of you said than the game works better on nongl driver than on gl driver. that was not my case at all. at least on mesa 19, the game runs great under mesa... but it runs very bad on legacy driver..

TEST:
https://www.youtube.com/watch?v=6RjanHapim4&feature=youtu.be

My main concern its than th gl driver dont work on retropie
Thanks

**Comment by AJenbo** [comment]
Nice, when testing using the experimental driver included with Raspbian 10 (Stretch) I got either glitchy rendering or poor performance, but I suspected that with the right driver the Pi should be capable, good to see that it works :)

I'm actually in the process of installing Debian 11 (Mesa 18 by default) on my RPI3 and was going to test this once the installation was complete :D Oh well I still get to try out Arm64 :)

**Comment by AJenbo** [comment]
I still think we will keep the notice about disabling upscaling/hardware rendering for now since the driver that ships by default for the Pi won't cut it, but the game will still default to having upscaling enabled for now... maybe we should swap it for the Pi.

**Comment by AJenbo** [comment]
P.s. since we are on the topic of running Diablo on the RPI3, here is a video of a version I build that displays the game on the Raspberry Pi Sens HAT: https://www.youtube.com/watch?v=756WmJguxZA&t=82s

**Comment by Askmewho** [comment]
I made a guide to update mesa and sdl based on anholt wiki and my experience. Mesa 19 open a lot of doors on rpi3.

https://drive.google.com/file/d/1gXvu8sMwMGktR2Dsu4pt5Riu6OyMzlMd/view

**Comment by AJenbo** [comment]
The game works on 64bit ARM as well. The bad news is that the save games aren't compatible with the original Diablo, the good news is that they are compatible with the x86_64 builds so should be fixed at the same time.

I'm closing this issue as its purpose of informing about the current status on different RPI3 configurations is completed imo.
