### ISSUE TITLE
devilutionx 64-bit build crashes

### ISSUE THREAD

**Issue by VonKossa** [diasurgical/devilutionX#121]
Hi!

As the title says, when compiling devilutionx with gcc 8.30 you cannot start a single player game. The game crashes with the error message "segmentation fault".
If i understand everything correctly this should not be an issue in the current state. Therefore i believe it has something to do with the compiler version which got released for my distro (Gentoo) recently.

**Comment by AJenbo** [comment]
The title says that it's a 64bit issue but your description points to it being an issue with compiling under GCC 8.30. Did you try 32bit with GCC 8.30 and did you try 64bit with a different compiler?

When exactly does it crash?

**Comment by VonKossa** [comment]
>Did you try 32bit with GCC 8.30
No
>did you try 64bit with a different compiler?
No

It compiles as it should when building it as 64-bit.
Starting the game works.
Menu works.
Crashes when pressing "Single Player" in menu.

**Comment by VonKossa** [comment]
meeeeeeeeh nevermind, stupid me.
It was something with the old single player savegames, i deleted the and then it worked.

**Comment by AJenbo** [comment]
Save games as currently not compatible between 32bit and 64bit builds, hence the big warning when you try to compile for 64bit :)
