### ISSUE TITLE
Installer for Diablo :D

### ISSUE THREAD

**Issue by liberodark** [diasurgical/devilutionX#122]
[![https://imgur.com/ndoaX16.png](https://imgur.com/ndoaX16.png)](https://imgur.com/ndoaX16.png)

^^

**Comment by AJenbo** [comment]
Looks nice :)

**Comment by liberodark** [comment]
Thx ^^ is not only a installer is a full package of diablo with compatibility on linux :D
No need deps ^^

**Comment by AJenbo** [comment]
Closing as it's not directly related to the project.

**Comment by liberodark** [comment]
Yes no problem
