### ISSUE TITLE
32bit builds on 64bit platforms

### ISSUE THREAD

**Issue by johndoe71rus** [diasurgical/devilutionX#1221]
lubuntu 20.04 x64

I can build x64 version.
But get cmake config error to 32bit build.

cmake log https://paste.ubuntu.com/p/yRghdy84wD/
installed libsdl* packages https://paste.ubuntu.com/p/ZrsryhK7Hw/

**Comment by Trihedraf** [comment]
Did you follow all the [32-bit Linux](https://github.com/diasurgical/devilutionX/wiki/Compiling-from-Source#linux) instructions, specifically installing all the i386 dependencies?

**Comment by AJenbo** [comment]
also have a look at how the build bot does it: https://github.com/diasurgical/devilutionX/blob/master/.circleci/config.yml#L58

closing as this isn't an issue with the software but a support question (use discussions, or chat instead)
