### ISSUE TITLE
New libsodium building option from #1216 erroring out with CMake 3.13

### ISSUE THREAD

**Issue by Trihedraf** [diasurgical/devilutionX#1222]
When using the new libsodium building option from #1216 , builds do not work when using CMake 3.13, due to FetchContent_MakeAvailable requiring 3.14. 

Should we change the requirements or can a secondary version requirement be set if the option is enabled?
@glebm @AJenbo

**Comment by glebm** [comment]
@Trihedraf We can work around that, I'll send a PR in a minute

**Comment by AJenbo** [comment]
thanks guys
