### ISSUE TITLE
diabdat.mpq inside the DevilutionX MacOs package?

### ISSUE THREAD

**Issue by niccolomineo** [diasurgical/devilutionX#1224]
Is it possible to have DevilutionX read the `diabdat.mpq` stored inside the DevilutionX package itself, so as to avoid having it uncomfortably lying around?

**Comment by qndel** [comment]
I don't know anything about mac but wouldn't that require US to provide diabdat.mpq with it?

**Comment by AJenbo** [comment]
> Is it possible to have DevilutionX read the `diabdat.mpq` stored inside the DevilutionX package itself, so as to avoid having it uncomfortably lying around?

Check how the ttf is read.

**Comment by niccolomineo** [comment]
No. In MacOs, one can just right click on an app and select `Show package contents` to be able to inspect it.

**Comment by niccolomineo** [comment]
> > Is it possible to have DevilutionX read the `diabdat.mpq` stored inside the DevilutionX package itself, so as to avoid having it uncomfortably lying around?
> 
> Check how the ttf is read.

I am not able to get that information anywhere in the code.

**Comment by AJenbo** [comment]
@niccolomineo is it not possible to search for files in a package? I would expect it to be in a folder called resources or something similar.
