### ISSUE TITLE
[Minor bug] Hitting ESC+Enter (Save game) causes the mouse pointer to jump to the upper left corner

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1228]
Before ESC:
![before](https://user-images.githubusercontent.com/45902449/111916068-827f7880-8a79-11eb-8fb2-337c189a80b4.png)

After save game:
![after](https://user-images.githubusercontent.com/45902449/111916077-87dcc300-8a79-11eb-876d-881c7e32ab4c.png)

**Comment by Chance4us** [comment]
Additional information:
"ESC + 3x Key down + Enter" (Load game), causes the mouse pointer to jump to the upper left corner and disappear.

**Comment by glebm** [comment]
Thanks for reporting. Is this on master?
I'll bisect to try to find what broke it

**Comment by glebm** [comment]
Looks like it wasn't any of the recent changes.
The bug exists as far back as 8527d1e44ab28a30ae693a4704206cdbdc5f32fc

**Comment by AJenbo** [comment]
it's in 1.1.0 as well

**Comment by Chance4us** [comment]
That's from the beginning.
Commenting out the line 1467 in /Source/diablo.cpp containing "GetMousePos(lParam);" seems to solve it.
But I don't know if this is the right way to fix the bug.

**Comment by Chance4us** [comment]
In fact, it fixes the bug, but it is unclear whether this affects anything.
