### ISSUE TITLE
[controls] options should be in the config by default

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#1238]
This improves their discoverability and makes it easier for users to change

**Comment by malvarenga123** [comment]
I think that a comment above each option with a small explanation of what it does and possible values would be helpful too.

**Comment by glebm** [comment]
We'd like to add comments to all the options but for technical reasons that won't be in 1.2.0. See #1239

**Comment by malvarenga123** [comment]
Maybe, for now, this info could be added to the readme file within the package.

**Comment by AJenbo** [comment]
> Maybe, for now, this info could be added to the readme file within the package.

https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide
