### ISSUE TITLE
Consider switching to toml11 for ini files

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#1239]
The [TOML](https://toml.io/en/) configuration format is a modern INI-like format with some innate advantages and better libraries available.

### Benefits

Overall, TOML is a more powerful format, growing more popular thanks to its use in the Rust ecosystem.

One implementation, [toml11](https://github.com/ToruNiina/toml11), supports the following features that would be very useful today:

1. Comment preservation and manipulation.
2. Syntax and type validation with [great error messages](https://github.com/ToruNiina/toml11/tree/7782258e68a66a34531942ec89020d174a122787#in-the-case-of-syntax-error).
3. Macros to (de-)serialize an entire section into a C++ class/struct (pending the resolution in https://github.com/ToruNiina/toml11/issues/139)
   Though we'll likely write our own macros because we want comments as well.

In the future, we may also benefit from TOML's support for arrays, when we implement configurable controls.

The toml11 library is written in standard C++11 with no dependencies, matching DevilutionX's minimum requirements.

### Caveats

1. For the macros mentioned in 2 above to work, the key names must match the struct field names. The key names must be valid C++ literals (no spaces).
   * We probably want to be able to use these macros. These are type-checked, less error prone, and can remove lots of boilerplate code.
2. TOML does not support unquoted keys with spaces.
   * We probably shouldn't use such keys anyway in light of 1. Prettier key names are also not as useful if we have comments.
3. TOML does not support `;` comments and the original Diablo's `diablo.ini` has one.
   * If we must support the initial parsing of the original Diablo's `diablo.ini`, it should be possible with a patch to toml11 [here](https://github.com/ToruNiina/toml11/blob/7782258e68a66a34531942ec89020d174a122787/toml/lexer.hpp#L229):

   ```diff
   -using lex_comment_start_symbol = character<'#'>;
   +using lex_comment_start_symbol = either<character<'#'>, character<';'>>;
   ```

### Proposal

1. Agree on adopting this after the 1.2.0 release.
2. To make sure 1.2.0 config files are compatible with a future release, make the key names `snake_case` or `camelCase` **now, before 1.2.0 release.**

**Comment by glebm** [comment]
How about we ignore `diablo.ini` and use `diablo.toml` instead?
Then we can just use straight-up TOML.

Background: the original ini file may contain unquoted IP addresses as values. This is a bit nasty to patch toml to parse.

Alternatively, we may try to find an ini library that supports comments but I couldn't find one.

**Comment by AJenbo** [comment]
It's been a while at this point, but wasn't it just the 4 quick chat messages that were there?

**Comment by glebm** [comment]
I've found an ini library that supports comments: https://github.com/brofield/simpleini

**Comment by glebm** [comment]
It does have some issues: https://github.com/brofield/simpleini/issues/45

**Comment by AJenbo** [comment]
Oh, by "original ini" i thought you where referring to what came with Diablo, not DevilutionX.

**Comment by AJenbo** [comment]
> It does have some issues: [brofield/simpleini#45](https://github.com/brofield/simpleini/issues/45)

I don't know if Radon handles that, I don't think we generate it?

**Comment by glebm** [comment]
Filed https://github.com/diasurgical/devilutionX/issues/1246 to switch from Radon to simpleini
