### ISSUE TITLE
Failing to compile on Pi4/Buster

### ISSUE THREAD

**Issue by Exarkuniv** [diasurgical/devilutionX#1247]
trying to compile devilutionX on my Raspberry Pi4
running Buster/RetroPie

i download the lastet source 
i use 
 cd build
    cmake ..
    make -j3
and i get this

[ 18%] Building CXX object CMakeFiles/devilution.dir/Source/objdat.cpp.o
/home/pi/RetroPie-Setup/tmp/build/devilutionx/Source/multi.cpp: In function ‘dvl::BOOL dvl::NetInit(dvl::BOOL, dvl::BOOL*)’:
/home/pi/RetroPie-Setup/tmp/build/devilutionx/Source/multi.cpp:741:54: error: expected primary-expression before ‘;’ token
   sgGameInitInfo.versionMajor = PROJECT_VERSION_MAJOR;
                                                      ^
/home/pi/RetroPie-Setup/tmp/build/devilutionx/Source/multi.cpp:742:54: error: expected primary-expression before ‘;’ token
   sgGameInitInfo.versionMinor = PROJECT_VERSION_MINOR;
                                                      ^
/home/pi/RetroPie-Setup/tmp/build/devilutionx/Source/multi.cpp:743:54: error: expected primary-expression before ‘;’ token
   sgGameInitInfo.versionPatch = PROJECT_VERSION_PATCH;
                                                      ^
make[2]: *** [CMakeFiles/devilution.dir/build.make:570: CMakeFiles/devilution.dir/Source/multi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/devilution.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
/home/pi/RetroPie-Setup

not sure what it is telling me Thanks for any pointers

**Comment by AJenbo** [comment]
> i download the lastet source

Use Git or provide the version manually to CMake.
