### ISSUE TITLE
Commit 72ebba0 causes an compilation error

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1256]
Commit 72ebba0 causes an compilation error:

[ 63%] Building CXX object CMakeFiles/devilution.dir/Source/trigs.cpp.o
/home/user/Schreibtisch/devilutionX/Source/trigs.cpp: In function ‘void dvl::InitTownTriggers()’:
/home/user/Schreibtisch/devilutionX/Source/trigs.cpp:80:8: error: ‘debug_mode_key_j’ was not declared in this scope
   80 |    if (debug_mode_key_j)
      |        ^~~~~~~~~~~~~~~~

**Comment by AJenbo** [comment]
Sorry about that :)
