### ISSUE TITLE
[display.cpp] warning: extra tokens at end of #ifdef directive

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1257]
![warning](https://user-images.githubusercontent.com/45902449/112212845-c317f700-8c1d-11eb-9940-6285be5eaf3b.png)

**Comment by yuripourre** [comment]
My bad here, sorry. And thanks @glebm and @AJenbo for fixing it.

**Comment by Chance4us** [comment]
We are actively working on the game and that's how it can happen. So no problem at all.
