### ISSUE TITLE
Opening and closing a door causes it to be rendered twice

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1275]
**Describe**
The new trasnparancy reveals that doors are being rendered multiple times after closing them.

**To Reproduce**
1. Go to the cathedral, find a wall with a door that is being rendered with transparency.
2. Open and close the door
3. The wall section will now be rendered at 75% opacity instead of 50%.

**Expected behavior**
The wall should render the at 50% opacity at all times

**Screenshots**
![image](https://user-images.githubusercontent.com/204594/112499719-0bebbf00-8d88-11eb-880f-b37fac55904b.png)
![image](https://user-images.githubusercontent.com/204594/112499729-10b07300-8d88-11eb-888d-4a0b9c4cd919.png)

**Comment by galaxyhaxz** [comment]
Isn't this related to the Eflag issue? I know you mostly removed that but this seems to be what it is.

**Comment by AJenbo** [comment]
Eflag is fully removed, this isn't related to where I stand in relation to the door, I'm just standing there because I just closed the door.

**Comment by galaxyhaxz** [comment]
Ok you are right, it also happens in my project too. I believe this is because the arches above doors/walls are treated as special cels and stored inside the dSpecial array. So the dungeon draws both the regular dPiece (micros) then draws the special tile over it again. Once again they scrapped this system on the psx and simply changed the tile flags :S

**Comment by AJenbo** [comment]
I mean it's not even fair to compare the render since the tiles are partitioned differently and it's a completely different render, but sure yeah PSX version is better in 99% of all cases, we just don't have it so :shrug:

**Comment by galaxyhaxz** [comment]
Well this issue can be fixed without changing the render or modifying the tiles. A quick trick would probably be just resetting the special array back to its formal state when closing the door.

**Comment by julealgon** [comment]
This is a vanilla issue, right?

**Comment by AJenbo** [comment]
yes, but only visible because of blended transparency support.

**Comment by julealgon** [comment]
I know it's off-topic here, but seeing those screenshots makes me wonder: shouldn't we make the actual door transparent also in this scenario?

**Comment by AJenbo** [comment]
I would say no since you can target and open it.

**Comment by galaxyhaxz** [comment]
The door is both a dungeon tile and an object, so a solid door gets drawn over the transparent dungeon tile. If you make the door transparent you would wind up with double transparency. No way to fix it without modifying the game's tiles, as it has doors caked into all the arch graphics.

**Comment by julealgon** [comment]
> I would say no since you can target and open it.

That's fair, but what if there is a chest right behind the door? I think the main point of transparency is to enable the player to see what is "behind", and the door in this case is pretty much part of the wall there.

Even if it was transparent, it could stll be interacted with.

Hmm... I'm thorn on this. I'm wondering how it would look like and behave (if it would become unintuitive for some reason)

**Comment by AJenbo** [comment]
> That's fair, but what if there is a chest right behind the door?

Won't happen as you wouldn't be able to go through the door then.
