### ISSUE TITLE
[Enhancement] Independent music volume for different level types

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1279]
For the reason that the music in the crypt suddenly feels louder than the music in all other level types
I suggest to make the volume of the music in the different level types independent of each other.

**Comment by AJenbo** [comment]
I don't think that's feasible, if you set it to 25% in town and then enter the cathedral you will be shocked if it's now 100% for the music. It's an issue with an asset and there isn't so much we can do about that.

**Comment by Chance4us** [comment]
Indeed, what you said is a fitting argument.
What about the possibility of giving the player the possibility to play their own or modified soundtracks? For example, music could be built into the devilutionx.mpg or simply by specifying the file paths. What do you think about it?

**Comment by qndel** [comment]
but ... you can do that already by replacing original sounds 🤦‍♂️

**Comment by Chance4us** [comment]
@qndel Do I have to modify the diabdat.mpq in this case?

**Comment by qndel** [comment]
no ... devilutionx supports direct access = you don't even have to pack stuff into a mpq, or if you want one, put it in patch_rt.mpq

**Comment by Chance4us** [comment]
Thanks i will try it out.

**Comment by Chance4us** [comment]
@all Which tool can/should be used to extract all files of the diabdat.mpq?

**Comment by qndel** [comment]
google mpqeditor :S do some exploring yourself pls

**Comment by AJenbo** [comment]
here is the music file list https://github.com/diasurgical/devilutionX/blob/master/SourceX/sound.cpp#L58

**Comment by Chance4us** [comment]
Thanks i played around a bit.
I noticed that neither direct file access nor changing the patch_rt.mpq works.
I just swapped some Music WAV filenames and either it was silence or the music was unchanged.
Can you confirm?

**Comment by qndel** [comment]
means you did something wrong, it works 100%

**Comment by Chance4us** [comment]
That is of course possible.
Could I get exact instructions?

**Comment by qndel** [comment]
recreate the path to a file (without diabdat.mpq") and it will work 🤷

**Comment by Chance4us** [comment]
I can describe my steps as follows. I used MPQEditor to extract diabdat.mpq.
I used Diablo I.txt as the listfile and activated Diablo 1 compatibility.
Then there is a folder music and in it dintro.wav, dlvla.wav, dlvlb.wav, dlvlc.wav, dlvld.wav, dtowne.wav.
Then have swapped the filenames dintro.wav and dtowne.wav.
Then I copied the music folder into the directory of devilutionx binary.

**Comment by Chance4us** [comment]
If I omit the MPQ I get an error message that I am missing some MPQ files.

**Comment by qndel** [comment]
you ... don't omit the mpq

**Comment by AJenbo** [comment]
If you edit mpq files then make sure you save it as Diablo 1 compatible, or it will use compression that isn't supported.

To use direct file access simply create the folders and files next to diabdat.mpq, and make sure that they are all lowercase letters:
```
diabdat.mpq
music\dintro.wav
```

**Comment by AJenbo** [comment]
> If I omit the MPQ I get an error message that I am missing some MPQ files.

I'm not sure what you mean by "omit"? Are you saying you deleted diabdat.mpq? It must be there as a base, other MPQs and files will overwrite its content, so do that instead.

**Comment by Chance4us** [comment]
> To use direct file access simply create the folders and files next to diabdat.mpq, and make sure that they are all lowercase letters

I did. I kept all the MPQ files.
In the same folder as the MPQ files I have a folder called "music".
In the music folder I have dintro.wav, dlvla.wav, dlvlb.wav, dlvlc.wav, dlvld.wav, dtowne.wav.
Every file and folder is lowercase.

**Comment by Chance4us** [comment]
If I do it that way, there is silence both in the menu and in the town.

**Comment by AJenbo** [comment]
Do they work if you don't swap them?

**Comment by Chance4us** [comment]
Yes, then the music is unchanged.
But if I change the music in Audacity and export it as "WAV (Microsoft) signed 16-bit PCM", then there is silence again.

**Comment by AJenbo** [comment]
Ok, it sounds like the problem is with how you are saving the wave files.

![image](https://user-images.githubusercontent.com/204594/112768806-1de68f80-901e-11eb-8790-c188370e2a6c.png)

I just tested renaming dtown.wav to dintro.wav and putting it in music/ next to diabdat.mpq and this makes the town music play in the main menu instead of the intro music.

![image](https://user-images.githubusercontent.com/204594/112768894-8e8dac00-901e-11eb-9ea0-5721d7b74b61.png)

![image](https://user-images.githubusercontent.com/204594/112768899-964d5080-901e-11eb-824f-fff8cba1ce17.png)

Editing it in audacity also works fine.

![image](https://user-images.githubusercontent.com/204594/112768911-ab29e400-901e-11eb-9920-260c11412e14.png)

**Comment by AJenbo** [comment]
Maybe check that you do not have more than one diabdat.mp and you are putting things next to the one that is actually being loaded.

**Comment by Chance4us** [comment]
Thank you. I will check and report again.

**Comment by Chance4us** [comment]
The following folder structure and command ends up in no music in town.
![music](https://user-images.githubusercontent.com/45902449/112905740-37094200-90eb-11eb-91b8-341c810aea51.png)

**Comment by AJenbo** [comment]
Does it work with an unmodified version of `dtowne.wav`?

What version of SDL are you on?

**Comment by Chance4us** [comment]
> Does it work with an unmodified version of dtowne.wav?
Yes.
> What version of SDL are you on?
![sdl](https://user-images.githubusercontent.com/45902449/112906510-9287ff80-90ec-11eb-82fd-5c7ec8b0f483.png)

**Comment by Chance4us** [comment]
If I modify the diabdat.mpq itself, the music is changed.

**Comment by AJenbo** [comment]
2.0.4 is rather old, I think it might actually be the oldest we support. Could you try to update to 2.0.14 (I'm using SDL 2.0.12)?

Since it works with one file but not another it's probably about the file format, maybe 2.0.4 is pickier than later versions. I know some tracks are mono and others are in sterio.

**Comment by AJenbo** [comment]
> If I modify the diabdat.mpq itself, the music is changed.

Edit/create patch_rt.mpq instead.

**Comment by Chance4us** [comment]
I've included all sources in Debian, even the experimental ones.
![repo](https://user-images.githubusercontent.com/45902449/112908478-dfb9a080-90ef-11eb-896f-b110cecdcea8.png)

There is no libsdl2-mixer library more up-to-date.
![libsl2-mixer](https://user-images.githubusercontent.com/45902449/112908622-1e4f5b00-90f0-11eb-9624-485148c61879.png)
So I suggest waiting until Debian provides a newer library.
As soon as it happened I can report again.

**Comment by Chance4us** [comment]
> Edit/create patch_rt.mpq instead.

Thank you much, I will try it.

**Comment by Trihedraf** [comment]
@AJenbo SDL2-mixer 2.0.4 is the latest.

**Comment by AJenbo** [comment]
Arh, I was asking for SDL version, not SDL-mixer :)
