### ISSUE TITLE
Experience points no longer increase

### ISSUE THREAD

**Issue by barryw** [diasurgical/devilutionX#1286]
**Important information**
I'm using macOS 11.2.3
I'm using builds that I've compiled myself using the latest tagged release as well as master and it behaves the same.

**Describe**
My character no longer receives experience points for killing monsters. I'm a level 17 warrior and my experience is stuck at 486988.

**To Reproduce**
I'm not sure how to reproduce. I noticed that my experience wasn't increasing as I killed monsters and have no idea what triggered it. This also happens on my wife's computer which is also running macOS and a version of devilutionx built from master.

**Expected behavior**
I expect to be rewarded with sweet, sweet experience for dispatching monsters.

**Screenshots**

**Additional context**

**Comment by qndel** [comment]
I'm just going to assume you are killing monsters that are too low to give xp at your level, no save attached, no other info I can work with ...

**Comment by AJenbo** [comment]
17 is right around the point where you stop getting any XP for the first levels:
https://diablo2.diablowiki.net/D1_Experience_Table
