### ISSUE TITLE
Crash if "Show Monster Type" enabled, not visible "Enemy Health Bar"

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1290]
Crash if "Show Monster Type=1" is enabled in diablo.ini
Also the Enemy Health Bar is not rendered correctly.

The issue is caused by commit 699e451.

![screen00](https://user-images.githubusercontent.com/45902449/112753636-aa6e5f00-8fd8-11eb-9c5b-d581861de3ff.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6217354/single_0.hsv.zip)

**Comment by qndel** [comment]
do you have devilutionx.mpq? 🙄

**Comment by Chance4us** [comment]
Yes, but I see there is a newer one.

**Comment by Chance4us** [comment]
The issue is caused by an older devilutionx.mpq

**Comment by qndel** [comment]
meaning there's no issue :S

**Comment by Chance4us** [comment]
Is it intended that there will be no more resistance of monsters to be seen?

**Comment by AJenbo** [comment]
> Is it intended that there will be no more resistance of monsters to be seen?

there is, but you need to kill 15 just like normally
