### ISSUE TITLE
Readme and license seem to contradict

### ISSUE THREAD

**Issue by mjsonofharry** [diasurgical/devilutionX#1291]
Howdy! I was just reading up on this project out of sheer admiration for it and noticed something confusing.

The [Legal](https://github.com/diasurgical/devilutionX#legal) section of the readme forbids commercial use of the project's source code:

> The source code in this repository is for non-commerical use only. If you use the source code you may not charge others for access to it or any derivative work thereof.

However, the [LICENSE file](https://github.com/diasurgical/devilutionX/blob/master/LICENSE) included with the source code permits commercial use:

> Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

Furthermore, the readme seems to contradict itself, also stating:

> DevilutionX is released to the Public Domain.

Could these segments be clarified? Prospective contributors and even independent game developers may benefit from knowing the official position of this project on commercial use.

**Comment by AJenbo** [comment]
Please see https://github.com/diasurgical/devilution/issues/2208

**Comment by mjsonofharry** [comment]
Thanks!

**Comment by sskras** [comment]
> Please see [diasurgical/devilution#2208](https://github.com/diasurgical/devilution/issues/2208)

As the original topic is locked for the contributors, I put my findings here.  
Quoting [Can I license my project with an open-source license but disallow commercial use?](https://opensource.stackexchange.com/questions/9805/can-i-license-my-project-with-an-open-source-license-but-disallow-commercial-use/9811#9811) answer from **opensource.stackexchange.com**:

> There are several licences that disallow commercial use of the software (or other intellectual property). Most notably [CC BY-NC 3.0](https://creativecommons.org/licenses/by-nc/3.0/) but please keep in mind that it's generally not recommended to use CC BY-NC 3.0 licence for software (you still can!).

I thought that (result of) decompilation work is quite close to the Creative Commons license in the spirit.

Maybe even better for **devilution** it would be to use **CC BY-NC-SA** (Share-alike) license, which would remove ability for "[derivative works to be sublicensed with compatible but more restrictive license clauses](https://en.wikipedia.org/wiki/Creative_Commons_license#Four_rights)":

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Creative_commons_license_spectrum.svg/450px-Creative_commons_license_spectrum.svg.png)

Cheers.
