### ISSUE TITLE
[Feature Request] Auto-repeat attack/casting

### ISSUE THREAD

**Issue by BardurArantsson** [diasurgical/devilutionX#1296]
It would be really nice to have an option for auto-repeating attacks/casting when holding the mouse button down.

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/pull/895/

**Comment by BardurArantsson** [comment]
Ah, thanks -- in defense I did try to search, but apparently not hard enough :).

**Comment by qndel** [comment]
appreciate the effort :)
