### ISSUE TITLE
Crash when enabling "show monster types"

### ISSUE THREAD

**Issue by BardurArantsson** [diasurgical/devilutionX#1297]
**Important information**

Linux / ca2c2ba5e76a86c5d35b564dc8c9b5ee73876bac / self-compiled

**Describe**

The game crashes instantly when hovering over a monster when "Show Monster Type=1".

Here's the debug/ASAN output:

```
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: SFileOpenFile: Not found: data\healthbox.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: data\health.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: data\resistance.pcx
INFO: Failed to load image meta
INFO: Opening /home/bardur/.local/share/diasurgical/devilution/single_5.hsv
INFO: GetFileSize("/home/bardur/.local/share/diasurgical/devilution/single_5.hsv") = 224644
INFO: new std::fstream("/home/bardur/.local/share/diasurgical/devilution/single_5.hsv", std::ios::binary | std::ios::in | std::ios::out)
INFO: read(out, 104)
INFO: read(out, 32768)
INFO: read(out, 32768)
INFO: Closing /home/bardur/.local/share/diasurgical/devilution/single_5.hsv
=================================================================
==2928728==ERROR: AddressSanitizer: negative-size-param: (size=-6)
    #0 0x5629371e7508 in __asan_memset (/home/bardur/tmp/build-devilutionX-Clang-Debug/devilutionx+0x86d508)
    #1 0x562937224ea5 in dvl::(anonymous namespace)::FastDrawHorizLine(dvl::CelOutputBuffer, int, int, int, unsigned char) /home/bardur/tmp/devilutionX/SourceX/qol.cpp:35:2
    #2 0x562937222d09 in dvl::DrawMonsterHealthBar(dvl::CelOutputBuffer) /home/bardur/tmp/devilutionX/SourceX/qol.cpp:103:3
    #3 0x562937e33cfd in DrawView /home/bardur/tmp/devilutionX/Source/scrollrt.cpp:1194:2
    #4 0x562937e3e003 in DrawAndBlit /home/bardur/tmp/devilutionX/Source/scrollrt.cpp:1517:2
    #5 0x562937541ff1 in dvl::run_game_loop(dvl::interface_mode) /home/bardur/tmp/devilutionX/Source/diablo.cpp:334:4
    #6 0x562937541c8e in StartGame /home/bardur/tmp/devilutionX/Source/diablo.cpp:391:3
    #7 0x5629378f95c1 in dvl::mainmenu_init_menu(int) /home/bardur/tmp/devilutionX/Source/mainmenu.cpp:46:12
    #8 0x5629378f9425 in dvl::mainmenu_single_player() /home/bardur/tmp/devilutionX/Source/mainmenu.cpp:62:9
    #9 0x5629378f8c5d in mainmenu_loop /home/bardur/tmp/devilutionX/Source/mainmenu.cpp:153:9
    #10 0x5629375440a6 in DiabloMain /home/bardur/tmp/devilutionX/Source/diablo.cpp:633:2
    #11 0x5629373ff569 in main /home/bardur/tmp/devilutionX/SourceX/main.cpp:34:9
    #12 0x7fc6d64d9b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #13 0x562937141fad in _start (/home/bardur/tmp/build-devilutionX-Clang-Debug/devilutionx+0x7c7fad)
```

I believe the issue is that the SFileOpenFile calls failing due to not finding the appropriate files. Not 100% sure where they're supposed to come from, but MPQExtract can't seem to find them in diabdat.mpq or hellfire.mpq (not 100% my listfiles are correct, though).

This leads to ArtHealthbox's with and height being 0 and thus leads to attempting to draw a negative-width horizontal line.

I'm going to try to revert 699e451611c2f93718fdaf1558cb26cebd5dd0fc to see if that fixes it. I'll report back below.

Aside: I noticed something about that commit. At the top of qol.cpp there's this:

```C++
Art ArtHealthBox;
Art ArtResistance;
Art ArtHealth;
```

but this is extremely dangerous in C++ because Art is not a POD type and C++ does not guarantee order of initialization for any non-POD static locals. I would suggest changing to pointers (null-initialized) and having InitQol allocate and FreeQol free the pointers -- otherwise code maintenance might lead to extremely hard-to-debug problems over time. See https://isocpp.org/wiki/faq/ctors#static-init-order . Apologies if you already know this -- and FTR it's probably actually OK in this particular case -- but I though I'd point it out because it can become such an insidious bug over time due to all maintainers not necessarily being careful enough. Hence my suggestion to change to raw pointer(s).

**To Reproduce**

Set "Show Monster Type=1" in `diablo.ini`. Start game, hover mouse over any monster.

**Expected behavior**

Health, etc. should be shown

**Comment by BardurArantsson** [comment]
Can confirm that reverting

```
30d013edf9622eaa27109fb3039fad5499cd4721
699e451611c2f93718fdaf1558cb26cebd5dd0fc
```

in that order fixes it, which is perhaps not that surprising since the drawing was hardcoded before that :).

**Comment by yuripourre** [comment]
@BardurArantsson those are custom files from devilution.mpq

**Comment by BardurArantsson** [comment]
Ah, thank you. I somehow missed that from the README...

Re-tested and it works with that file copied in place.

Closing, but @AJenbo : The aside about ArtHealthBox, etc. is probably still relevant. I can prep a PR if you'd like.

**Comment by AJenbo** [comment]
> Ah, thank you. I somehow missed that from the README...
> 
> Re-tested and it works with that file copied in place.
> 
> Closing, but @AJenbo : The aside about ArtHealthBox, etc. is probably still relevant. I can prep a PR if you'd like.

Sure, feel free to also make it not crash if devilutionx.mpq is not in place. It doesn't for me :shrug:

**Comment by BardurArantsson** [comment]
See #1300

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/1ebf1c6b4e35ccf3663f37ecb1b435cc539bb378
