### ISSUE TITLE
Bug with loading music files instead of .mpq since #1200 was merged

### ISSUE THREAD

**Issue by Trihedraf** [diasurgical/devilutionX#1301]
Ex. When you put a dtowne.wav in ./music/ there will be no music played in town, even if it is the file directly out of diabdat.mpq. Going to the build before #1200 was merged it works correctly and plays whatever ./music/dtwone.wav is.

Issue discovered in #1279 as a separate issue.

**Comment by AJenbo** [comment]
I'm unable to reproduce the issue. But Diablo specifically avoided streaming files that were not in MPQs even when in developer mode so we are no worse than it :shrug: 
I guess this might be down to some combination of stormlib and SDL.

For now, I would say either compile with `DISABLE_STREAMING_MUSIC=ON` or put your music in an MPQ.

Maybe at some point we will have something a bit cleaner and custom build for MPQ handeling.

**Comment by Trihedraf** [comment]
@AJenbo it did it for me on Windows 10 as well as I just tried it on my Ubuntu 20.04 VM.
It spits this out when it doesn't play anything. `INFO: Mix_LoadMUSType_RW: Unknown WAVE format`
Which the .wav from the diabdat.mpq should be the correct format should it not?

**Comment by AJenbo** [comment]
StormLib has some issues when accessing files direction from disk, you will also get palette issues if doing so for the menu backgrounds. Probably a similar issue going on here.

**Comment by malvarenga123** [comment]
But @AJenbo from what @Trihedraf is saying, StormLib was able to access the files correctly before #1200. Don't you think there's an issue with that PR?

**Comment by AJenbo** [comment]
@malvarenga123 there is a big difference before it loaded the whole soundtrack into memory in one read. #1200 implements music streaming which requires seeking, which StormLib struggles with for directly accessed files. So no this is practically expected because of the known limits of StormLib.
