### ISSUE TITLE
How do I install Hellfire?

### ISSUE THREAD

**Issue by stilwell13** [diasurgical/devilutionX#1302]
I recently installed devilution and got it running fine. I then put the hellfire.mpq (and the other few files) in the same folder as my diab.mpq file thats needed to launch the game.  But i dont see hellfire anything just the regular version. I even tried moving the orignal diab.mpq file out of the folder to see if i just needed the hellfire in there but that didnt work when launching the game.

Any help would be greatly appreciated.

Screen shot of the instructions i followed. ![image](https://user-images.githubusercontent.com/81497778/112931970-20fb8180-90eb-11eb-9d21-892193de8880.png)
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

**Describe**

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by viniciusferrao** [comment]
As far as I know Hellfire support will only be available on 1.2.0 which should be near to release.

**Comment by AJenbo** [comment]
You didn't fill out any of the important information. Like @viniciusferrao I have to assume you installed 1.1.0 which does not have Hellfire support.
