### ISSUE TITLE
Gnat String's "Multiple arrows per shot" only fires one arrow

### ISSUE THREAD

**Issue by BartyMae** [diasurgical/devilutionX#1305]
**Description**
In DevilutionX (v1.1.0-9306D86B) with Hellfire, the unique bow Gnat Sting only fires one arrow per shot as if it were a normal bow.

**Expected behavior**
In the original Hellfire, Gnat Sting shoots a spray of three arrows every shot.

**Save file**
Rogue save file with Gnat Sting equipped: https://dl.dropboxusercontent.com/s/821cfrm1mtz8hyy/single_0.hsv

**Comment by julealgon** [comment]
> this should now be fixed

Out of curiosity, what caused it @AJenbo ? Do you have a link to the commit that fixes it so we can add some tracking here?

**Comment by qndel** [comment]
@julealgon check last commit

**Comment by AJenbo** [comment]
We some how missed a function when REing Hellfire :(
https://github.com/diasurgical/devilutionX/commit/fd641932084b7901b6581d1d1658dfbc6cd9372c
