### ISSUE TITLE
Na-Krul repeatedly dies from Reflection

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1311]
From user350-disc:

The Boss won't die, if he kill himself (use Reflect and let him hit you when he just have some life). He will drop the items infinitely, each time he die again. Since he don't have his life back, it's really fast to have a lot of item. Also, once he died that way the 1st time, you can walk through him & you can't select him (need to use Shift to hit him).

**Comment by julealgon** [comment]
Such a weird bug this is... is it really specific to Na-Krul?

**Comment by AJenbo** [comment]
Hmm good question, but I would think so since it would probably have been observed much more readily if all monsters behaved like this.

**Comment by AJenbo** [comment]
> I tested the bug on Na-krul that I found yesterday a little more and I was wrong about something. Here's an update:
A) After he died that way for the 1st time you can still kill it for real. I tried with a sword and apocalypse, it's working with both. So you should be able to use anything that work before.

It's weird that you can really kill it even if he still drop items but don't die. It's like if the boss have two separate life:
1) Damage from the player when not enough life = die for real even after becoming a "ghost"
vs 
2) Damage from himself when not enough life = drop all the items everytime and become a "ghost"

B) Also, all the items are duplicates. If you take an item and you put it on the floor, only one item will be delete even if there's several other duplicates.
This is an easy way to make money and to max out the spell Apocalypse. Unfortunately, there's no point to max out this spell, since in the GOG version you already have the minimum mana for it.

**Comment by obligaron** [comment]
While investigating #4318 I couldn't reproduce the issue.
Perhaps we fixed this with some refactoring? 🤔
