### ISSUE TITLE
Chamber of bone book

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#1317]
If you click the chamber of bone book, you technically cast a spell = you use mana equal to guardian's cost.
There are 4 "special" places in corners but guardian only spawns in one of them.
The things above don't make sense, imo 4 guardians should spawn and player's mana shouldn't be affected.

**Comment by galaxyhaxz** [comment]
Based on beta versions of Diablo, two things might help explain that:

1) Originally the book gave Nova, and was changed to Guardian right before the game released.
2) Some beta screenshots show a statue in the chamber of boner close to the plates:

![image](https://diablo-evolution.net/images/screens/beta/201.png)

**Comment by julealgon** [comment]
> chamber of boner 

Hmm.

**Comment by Chance4us** [comment]
Interesting. The beta versions seem to be different. Perhaps you should consider adding the betas as standalone games in Devilution, as they seem to have interesting game elements. I would love to see the gameplay difference.

**Comment by Chance4us** [comment]
By the way, you can download them here:
https://diablo-evolution.net/index.php?pageid=files
