### ISSUE TITLE
[diablo] Bard does not receive a weapon in the new game

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1324]
Bard has no weapon if you start a game with a new character in Diablo.
![bard2](https://user-images.githubusercontent.com/45902449/113461674-c8472400-941d-11eb-8507-24d2ccc2ffe4.png)

**Comment by glebm** [comment]
Reproduced with `--diablo` flag (works fine in Hellfire)

Barbarian is OK in both `--diablo` and Hellfire
