### ISSUE TITLE
[diablo] The main menu shows incorrect stats for Bard and Barbarian 

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1325]
Main menu:
![bard1](https://user-images.githubusercontent.com/45902449/113461724-093f3880-941e-11eb-93b3-c3ebf2679442.png)
![barbarian1](https://user-images.githubusercontent.com/45902449/113461740-16f4be00-941e-11eb-9245-1789d3a893d0.png)

Expected stats:
![bard2](https://user-images.githubusercontent.com/45902449/113461754-2e33ab80-941e-11eb-912b-b9d367569c42.png)
![barbarian2](https://user-images.githubusercontent.com/45902449/113461758-3390f600-941e-11eb-8628-27398eb6f908.png)

**Comment by glebm** [comment]
Note: Reproduced with `--diablo` flag (works fine in Hellfire)

**Comment by AJenbo** [comment]
@Chance4us thanks
