### ISSUE TITLE
[3DS] Game crashes every time a save occurs

### ISSUE THREAD

**Issue by warnwar** [diasurgical/devilutionX#1329]
**Important information**
On New 3DS with sys ver. 11.10.0-43U, using build 3965 from CircleCI 
https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3965/workflows/62a48a74-b2ee-4e5a-84e0-d4c5052ce6f2/jobs/24941

**Describe**
Any time the game saves, it crashes. The save does complete, but the 3DS turns off because of the crash.

It happens in the menu when creating a character, and it also happens whenever you save from within the game. I have included the crash dumps.
[crashdump.zip](https://github.com/diasurgical/devilutionX/files/6251862/crashdump.zip)

**Expected behavior**
Game should not crash when saving

**Comment by AJenbo** [comment]
@MrHuu are you able to see what is going on here?

**Comment by AJenbo** [comment]
> It happens in the menu when creating a character, and it also happens whenever you save from within the game. I have included the crash dumps.
> [crashdump.zip](https://github.com/diasurgical/devilutionX/files/6251862/crashdump.zip)

Thia looks like an empty folder?

**Comment by warnwar** [comment]
oops, sorry about uploading the wrong zip for the crashdumps. This one should actually have them:
[crashdump.zip](https://github.com/diasurgical/devilutionX/files/6251955/crashdump.zip)

**Comment by AJenbo** [comment]
Could you try this version https://24485-143324737-gh.circle-artifacts.com/0/devilutionx.cia

what model do you have, i belive some of the early ones are not able to fully run the game.

**Comment by MrHuu** [comment]
Tested both latest .3dsx and .cia circle-ci builds on my new3ds.
Both builds crash after saving.

I'll update my local builds and look into it.

**Comment by warnwar** [comment]
@AJenbo I have a New 3DS XL. I thought the original 3DS and the other lower-powered ones were incompatible.

I tried that build you suggested, and it also crashes in the same way. The game saves properly, but then the system turns off.

**Comment by AJenbo** [comment]
Kinda odd that this would fail, since it free is guarded by `if (p != null)` so I don't think this is a double-free :/

**Comment by AJenbo** [comment]
I tried explicitly calling `flush()`, could you see if this helps?
CIA:
https://24981-143324737-gh.circle-artifacts.com/0/devilutionx.cia
3DSX:
https://24981-143324737-gh.circle-artifacts.com/0/devilutionx.3dsx

**Comment by warnwar** [comment]
That build is still crashing for me. I'm seeing the "Saving..." window, and then it momentarily flickers back into the game before I get the black screen of death.

If it helps any, here is a picture of the crash:
![crash](https://user-images.githubusercontent.com/44714486/113485772-f6a41e00-9474-11eb-97b9-39dc6d0e48b9.jpg)

If a video or more crash dumps would help, I can add them.

**Comment by AJenbo** [comment]
@glebm do you think this is related to the issue you saw in `SaveHelper`?

**Comment by AJenbo** [comment]
@MrHuu any chance you have time to look in to this. would be really sad if it slips the release :(

**Comment by MrHuu** [comment]
Trying to bisect as we speak. Unfortunately, i'm running into multiple other issues with previous commits.
Not sure where it went wrong yet.

**Comment by glebm** [comment]
I don't think so but I am curious to know if #1314 fixes it

**Comment by glebm** [comment]
@MrHuu I have just rebased #1314, can you please try a build from that CI run?

**Comment by MrHuu** [comment]
> 
> 
> @MrHuu I have just rebased #1314, can you please try a build from that CI run?

The .3dsx build still seems to crash in a similar way.

I noticed some commits about audio streams not functioning properly.
Could it possibly be related to this?

**Comment by glebm** [comment]
It shouldn't be, the build was working at some point after 88a68f503a34cce70982b15fa4da247ddffce9ba

**Comment by warnwar** [comment]
After testing over 10 different builds, I think I found the commits that caused this issue:
Build 3894 works fine ( https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3894/workflows/d5291751-6318-49c7-a15f-6615d0df2ad9/jobs/24231 )
Build 3896 does not work ( https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3896/workflows/ae393c4c-61a3-4892-ad4b-171056cfac8a/jobs/24256/artifacts )

Hopefully this helps. I don't understand c++ well enough to investigate beyond this on the code side.

**Comment by AJenbo** [comment]
Looks like taking a shower before releasing payed off :D

**Comment by AJenbo** [comment]
Hmm the build you marked as broken isn't part of the main branch, I'm guessing that you did this going overbuilds in CircleCI. Would be best to have it filtered by branch.

Could you test this build as that is what actually got merged:
https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3904/workflows/5680ccce-2b9f-4146-b643-72a69260ea0f/jobs/24328/artifacts

We should also test bba73ea20f77777420a8c9756c1453a2028ef4cb as that is between the two, but doesn't have a CircelCI build. Let me know if you would like me to trigger a build for it in case it's easier for you then to build it locally.

**Comment by warnwar** [comment]
I knew I kinda messed it up comparing branch and master builds, still I think it was worth the effort. That build 3904 is broken. For my own understanding, should the ingame build number be 4082dee or bba73ea?. 

Feel free to start any other builds you would like me to test.

**Comment by AJenbo** [comment]
CircelCI build 3904 is a build of version `4082dee`, it skipped bba73ea because both were submitted together. But looking at it I see that 4082dee just added a test so the two versions would have been identified so no need to test them both anyway.

I have submitted a change that might fix the issue, but it's still a bit of a shot in the dark since we don't know what's really going one here. Just where it crashes (the commit you located is the one where the function was added). But it does confirm that this is where we should try to solve things probably.

**Comment by AJenbo** [comment]
@warnwar can you test this: https://app.circleci.com/pipelines/github/diasurgical/devilutionX/4063/workflows/df24d881-35e3-4d9f-89aa-83472acec03d/jobs/25914/artifacts

**Comment by AJenbo** [comment]
> After testing over 10 different builds, I think I found the commits that caused this issue:
> Hopefully this helps. I don't understand c++ well enough to investigate beyond this on the code side.

Wow, I thought that was @MrHuu replying :sweat_smile:
I was confused why you were writing that you didn't understand C++. Sorry for that, thank you for tirelessly going over all the builds and testing, even figuring that out is pretty nice for someone who is new to all of this :)

**Comment by warnwar** [comment]
Always willing to help, and finally some good news: 64575d4 saves properly. I tried creating a new character and that saved fine. Then saving within the game also worked.

**Comment by AJenbo** [comment]
OMG, I love you :D This is tight timing. I was going to push the release and retract the 3DS port until the next cycle. Decided to take a shower to give anyone working on the 3DS issue figure out what might be wrong, and that was exactly enough for you to find the offending build so I could guess at the issue from a previous comment by @glebm :joy:

So good news, issue solved and 3DS will be an official release target :tada:

**Comment by julealgon** [comment]
@warnwar your willingness to help is hugely appreciated. Going as far as to narrowing it down was honestly unexpected. Kudos to you.
