### ISSUE TITLE
As Monk, shift-click to equip a staff doesn't work

### ISSUE THREAD

**Issue by Tumayto** [diasurgical/devilutionX#1330]
**System/Build**
Windows 10 64-bit Pro / DevilutionX v1.1.0-c0f57f30

**Describe**
As a Monk, shift-click to unequip a staff works, but shift-click to equip it doesn't.
I haven't tested other classes/items thoroughly so it's possible this could affect others.

**Expected behavior**
As a Monk, shift-click to equip a staff should equip the staff.

**Save File**
[monk-staff.zip](https://github.com/diasurgical/devilutionX/files/6252004/monk-staff.zip)

**Comment by Jmgr** [comment]
Isn't that expected? https://github.com/diasurgical/devilutionX/blob/c0f57f3020566f6305a3c6e934e9c43b90aa1dcd/Source/inv.cpp#L777

**Comment by qndel** [comment]
> Isn't that expected?
> 
> https://github.com/diasurgical/devilutionX/blob/c0f57f3020566f6305a3c6e934e9c43b90aa1dcd/Source/inv.cpp#L777-L780

Well, I see a difference between autoequipping when picking up/shopping vs pressing shift + click on purpose

**Comment by julealgon** [comment]
Yep, clearly a bug. I'll take a look later.

**Comment by julealgon** [comment]
PR sent. Feel free to change the milestone if you want this to be part of the release @AJenbo .

**Comment by AJenbo** [comment]
I do :)
