### ISSUE TITLE
[Diablo] Enhancement proposal "Test Monk=1"

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1331]
I suggest to include monk in Diablo for players who own the Hellfire MPQ files by setting "Test Monk=1".

**Comment by qndel** [comment]
and then how will you play multiplayer with players that don't have hellfire mpq?

**Comment by Chance4us** [comment]
That is quite a legitimate and a logical question.
It would then require to create own graphics first.
By the way we could also create custom graphics for all hellfire heroes, and then insert them into the devilutionx.mpq file.
The rework the of diablo heroes could remain optional.

**Comment by AJenbo** [comment]
the monks skill also require hellfire.mpq and since it controls weather you have hellfire enabled or not i decided to not allow this as an option.

**Comment by qndel** [comment]
feel free to create custom graphics for all hellfire heroes, see you in 10 years 🤪
