### ISSUE TITLE
[diablo.ini] Option SItem=

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1332]
In the diablo.ini file it is unclear what the "SItem=" option stands for.

**Comment by NikoVP** [comment]
Maybe it doesn't need description, otherwise people will start sending each other cornerstone utem codes on messenger...

**Comment by AJenbo** [comment]
> Maybe it doesn't need description, otherwise people will start sending each other cornerstone item codes on messenger...

i don't think people rampantly shared items via .reg, it is after all a bit of effort to get to the stone
