### ISSUE TITLE
[diablo.ini] Intro=0 Diablo/Hellfire

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1333]
In the diablo.ini the option Intro=0 does not work for Diablo and Hellfire.
The intro cinematic is played anyway.

**Comment by Chance4us** [comment]
The cinematic does not play.
The intro picture is always displayed.
I think that's by design.

**Comment by AJenbo** [comment]
can use -n if you prefer to skip it

**Comment by Keith94** [comment]
I get this issue too. Intro is always set to 0 but the intro always plays.

**Comment by julealgon** [comment]
> I get this issue too. Intro is always set to 0 but the intro always plays.

@Keith94 did you read the second post on the issue?
