### ISSUE TITLE
Auto gold pickup is not working properly when inventory is full

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#1348]
**Important information**
Windows 10, latest master https://github.com/diasurgical/devilutionX/commit/c0f57f3020566f6305a3c6e934e9c43b90aa1dcd

**Describe**
When the inventory is full, auto-pickup behavior for gold does not work properly. Gold is not picked up, even when there is actual room in an existing gold pile in the inventory.

**To Reproduce**
1. Enable auto gold pickup
2. Fill inventory with items
2. Leave a gold pile in the inventory with enough space
3. Try to walk by a gold pile in the ground
4. Notice it is not picked up

**Expected behavior**
Gold should be picked up as long as the value fits in the inventory. It should be able to detect existing gold piles in the inventory as targets for the picked up gold.

**Evidence**
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6253807/single_0.zip)
![AutoGoldFullInventory](https://user-images.githubusercontent.com/461579/113494859-e7e45800-94c2-11eb-91bb-37d368461215.gif)

**Additional context**
Found during Nitekat's stream

**Comment by AJenbo** [comment]
Aw i missed the stream :(

**Comment by AJenbo** [comment]
You should have seen when it didn't take a full inventory in to account at all :joy:

**Comment by julealgon** [comment]
Took a while to repro this. This actually also causes out-of-bounds access of `InvList`.

Initially, I thought about just fixing the index, but the current implementation is too far from ideal. I'll change the logic completely.

**Comment by AJenbo** [comment]
I rushed it when I saw the issue that it was suppose to fix :roll_eyes:
