### ISSUE TITLE
Opening Diablo's chamber with only one lever

### ISSUE THREAD

**Issue by SoundChaser83** [diasurgical/devilutionX#1352]
This is a common trick abused by speedrunners regularly: flipping only one of the levers in the far west/final lever room of dlvl 16, portalling back to town, and coming back through the portal will open Diablo's chamber without needing to touch any other levers. I don't know if it's a bug or by design, but you can also use telekinesis to flip both levers in the final lever room and Diablo's chamber will open without needing to flip the first two levers in the northeastern wing of the level.

**Comment by julealgon** [comment]
The "flip one, go back to town, come back" is clearly a bug to me so we should definitely fix it.

The issue regarding only having to flip the levers in the last room are more debatable... While I personally would like to "fix" it, I think the more "correct" fix would be to actually disallow seeing/casting into the levers in closed rooms. That would be a much bigger change though that would impact other similar scenarios, like being able to teleport into the chamber of bone room and similar.

If we changed the lever behavior, we'd also have to consider changing the behavior for the other levers too. For example, if we flip the levers in the _second_ room, they will open up the third room without needing to flip the ones in the _first_ room. That could be seen as inconsistent.

**Comment by AJenbo** [comment]
Yeah skipping a room isn't a bug. If you break into a bank and don't trigger the alarm at the door it doesn't mean that you were defying the law of gravity, just that you broke in the window instead.

**Comment by johndoe71rus** [comment]
yesterday I had a case.
I only activated one lever in the second room. Teleport to the town. When i returned, i found that Diablo's room was open. I had to kill him earlier than planned.

**Comment by AJenbo** [comment]
In case i wasn't clear that is a bug, but deliberately opening the last room via telekinesis isn't :)
