### ISSUE TITLE
Mana shield makes player unable to be stunned under certain conditions

### ISSUE THREAD

**Issue by SoundChaser83** [diasurgical/devilutionX#1353]
Another trick used by speedrunners in the vanilla game. If the player has their current life at or below their clvl and they have mana shield active, hit recovery is skipped entirely whenever being hit.

**Comment by StephenCWills** [comment]
I thought it would help to compile a list of sources for damage and healing for a better understanding of how they should interact with Mana Shield. I also thought this might guide some discussion about how various mechanics *should* interact with Mana Shield, in case there are any strong opinions or bugs that come out during the process of fixing its behavior.

Damage Sources:
 - Monster damage `M_TryH2HHit()`
 - Missile damage `PlayerMHit()`
 - Rage `MI_Blodboil()` (#1111)
 - Blood Star `AddFlare()` (5 Damage to caster)
 - Bone Spirit `AddBoneSpirit()` (6 Damage to caster)
 - Burning crosses `Obj_BCrossDamage()`
 - Life drain `ProcessPlayers()` (Constricting Ring, 0.0625 Damage per frame)
 - ... of Peril suffix `PlrHitMonst()` (2x damage to monster, 1x damage to user)
   - Jarulf's Guide has a bunch of notes here, like how this suffix doesn't work for PvP and has no effect on bows.
 - Network packets
   - PvP damage to self: `On_PLRDAMAGE()`
   - Synchronizing remote players' HP (I think?): `multi_process_network_packets()`

Heal Sources:
 - Potion of Healing `UseItem()`
 - Potion of Full Healing `UseItem()` (Full heal)
 - Elixir of Vitality `UseItem()` (Full heal Hellfire only)
 - Potion of Rejuvenation `UseItem()`
 - Potion of Full Rejuvenation `UseItem()` (Full heal)
 - Heal `AddHeal()`
 - Divine Shrine `OperateShrineDivine()` (Full heal)
 - Spooky Shrine `OperateShrineSpooky()` (Full heal)
 - Blood Fountain `OperateFountains()` (Heal 1 HP)
 - Level up `NextPlrLevel()` (Full heal)
 - Life steal `PlrHitMonst()`
 - Change to vitality `ModifyPlrVit()`
 - Heal Other `DoHealOther()`

Currently, all sources of damage and healing operate directly on the player's HP regardless of Mana Shield. To make Mana Shield work, the Mana Shield missile captures the HP of the player at the time of casting and stores it in `_miVar1` and `_miVar2`. `MI_Manashield()` is directly invoked toward the end of `ProcessMissiles()`, seemingly to ensure that all potential sources of damage have all been processed first. Its job is to update the coordinates of the Mana Shield missile, redirect any HP deficit that was incurred to mana instead (reduced by 1/3), delete itself if the player reaches 0 mana, apply overflow damage to HP, and kill the player if their HP also reaches 0.

In addition to documenting the sources of damage and healing, I also wanted to document the routines that update the `_miVar1` and `_miVar2` variables for the Mana Shield missile.

Mana Shield Updates:
 - Mana Shield missile created `AddManashield()`
 - Making changes in the player's inventory `CalcPlrItemVals()`
   - This is actually invoked all over the codebase, which could really mess with the behavior of Mana Shield. For example, it's used by Rage and Infravision missiles, which seems bad for Mana Shield.
 - Mana Shield processing `MI_Manashield()`
   - Mana Shield only restores HP if there is a deficit. If the player is healed, then it skips redirecting HP. The missile variables are updated at the end to capture the new HP value.

Notes:
 - `SetPlayerHitPoints()` is also used in various places to update the player's HP, but it seems to deal only with death-related things, which shouldn't be relevant to the behavior of Mana Shield. Here are some examples of activities that would invoke `SetPlayerHitPoints()`.
   - Set player's HP to zero in dungeon if it goes below zero
   - Set player's HP to 1 in town if it goes below 1
   - Restart in Town
   - Resurrect

**Comment by AJenbo** [comment]
the less usage of _*var* the better.

It's hard to understand why hellpers where not made for managing health, especially considering the odd fraction handling.

Could you explain why CalcPlrItemVals can have an effect on Mana Shield?

**Comment by StephenCWills** [comment]
This for loop at the end of `CalcPlrItemVals()` updates those two `_var` variables on the Mana Shield missile.
https://github.com/diasurgical/devilutionX/blob/86afa95d2a15de5e7bdb61cca10670e8c663ebb5/Source/items.cpp#L930

If I'm understanding this right, it means that any time `CalcPlrItemVals()` is called for any reason, it will take the player's current HP value, whatever it is, and apply it as the target HP for the Mana Shield. For example, this means the player could theoretically lose HP through Mana Shield if they take damage in the same frame that Infravision wears off.
https://github.com/diasurgical/devilutionX/blob/master/Source/missiles.cpp#L5124

**Comment by StephenCWills** [comment]
It was a bit complicated to test, but I was able to confirm using Constricting Ring that the player does, in fact, lose HP through Mana Shield when Infravision wears off.

![image](https://user-images.githubusercontent.com/9203145/115100641-e3c92900-9f0b-11eb-9498-bbae1493ac89.png)

![image](https://user-images.githubusercontent.com/9203145/115100646-e9267380-9f0b-11eb-8a6d-fd8bdd713101.png)

**Comment by AJenbo** [comment]
Wow

**Comment by qndel** [comment]
@StephenCWills this bug is insane, feel free to add to https://github.com/diasurgical/devilution/issues/64 :D

**Comment by julealgon** [comment]
It would be nice to apply the chain of responsibility pattern when fixing this. Mana shield should "intercept" damage calculations, absorb the damage, and then redirect to the normal processing in case the damage caused it to wear off.

When casting mana shield, a wrapper should be added on top of a class/method that centralizes "taking a hit" that performs these checks, and removed once the spell effect vanishes.

**Comment by StephenCWills** [comment]
@julealgon Do we have an example of this in the codebase that can be referenced?

**Comment by julealgon** [comment]
> @julealgon Do we have an example of this in the codebase that can be referenced?

I don't think an example of chain of responsibility exists in the code right now, at least I'm not aware of one.

**Comment by AJenbo** [comment]
I think mostly we have a few examples of anti-patterns and recipes for various pasta dishes. Antipasto?

**Comment by StephenCWills** [comment]
I asked because I'm not sure it's a good idea to introduce a whole new design pattern alongside changes to the behavior of Mana Shield. I propose we start by consolidating the logic for damaging the player into a single function to fix the bugs, and then tackle improving design patterns as a future enhancement.

I do think that chain of responsibility makes good sense based on the current logic where Mana Shield overrides all damage to HP. However, it may be a bit much compared to simply handling Mana Shield as a special case. The pattern provides flexibility when configuring the chain to include various handlers in a specific order, but I'm not sure how common it would be to add anything else onto this chain.

Have you considered how it should work when making changes to the existing logic? For example, it's easy to conceive of a mod that would choose to bypass Mana Shield for specific damage sources like Constricting Ring, Blood Star, and Bone Spirit. When discussing changes to design patterns, I think the chosen pattern should focus on making these types of changes more feasible.

**Comment by julealgon** [comment]
> I asked because I'm not sure it's a good idea to introduce a whole new design pattern alongside changes to the behavior of Mana Shield. 

Oh I'm not suggesting it all be done in the same change, that would be ill-advised.

> I do think that chain of responsibility makes good sense based on the current logic where Mana Shield overrides all damage to HP. However, it may be a bit much compared to simply handling Mana Shield as a special case. The pattern provides flexibility when configuring the chain to include various handlers in a specific order, but I'm not sure how common it would be to add anything else onto this chain.

I don't necessarily think that having only 2 participants invalidate the use of the pattern. After all, it works with 2+. Dynamically configuring it is also not a requirement, it's just an option.

Having said that, we have many different behaviors that could benefit from it:
- \- X damage from enemies
- absorb half trap damage (dynamic based on presence of item)
- mana shield damage absorption (dynamic based on presence of spell)
- reflect damage absorption (dynamic based on presence of spell)
- block (dynamic based on presence of shield)
- armor
- elemental resistance
- special armor modifiers (monk)

Each of these behaviors could be modeled to work in a chain, where they apply their effects, and conditionally pass any remaining life to the next in the chain.

Equipping / unequipping / casting could update the chain accordingly, dynamically adding or removing the handlers. As another option, the chain could be static, but become a "passthrough implementation" when no corresponding items with that effect are found (say, one of the steps is "applyDamageReduction" but the player has 0 "- damage from enemies"). The order of the handlers define the priority of each effect.

> Have you considered how it should work when making changes to the existing logic? For example, it's easy to conceive of a mod that would choose to bypass Mana Shield for specific damage sources like Constricting Ring, Blood Star, and Bone Spirit. When discussing changes to design patterns, I think the chosen pattern should focus on making these types of changes more feasible.

Equipping specific items could add/remove handlers on the chain, dynamically adding the extra handling needed. The handlers could be added at any point of the "pipeline", to model whatever outcome the modder wants.

**Comment by StephenCWills** [comment]
> I don't necessarily think that having only 2 participants invalidate the use of the pattern. After all, it works with 2+. Dynamically configuring it is also not a requirement, it's just an option.

I didn't mean to suggest that it invalidates the pattern, but rather that it would be rather heavy-handed to define an interface, an abstract class, and two handler classes just so you can turn Mana Shield on and off by reconfiguring the chain at runtime. I see from your response that you're looking more broadly at the whole chain of events between when an attack connects and when the player takes damage, and it does make a lot more sense to me from that perspective. In the context of this issue, I have my Mana Shield blinders on.

**Comment by julealgon** [comment]
> but rather that it would be rather heavy-handed to define an interface, an abstract class, and two handler classes just so you can turn Mana Shield on and off by reconfiguring the chain at runtime.

You do not need interfaces and classes to model a chain of responsibility: just having a function that takes another function with the same signature would work just fine.

**Comment by StephenCWills** [comment]
> You do not need interfaces and classes to model a chain of responsibility: just having a function that takes another function with the same signature would work just fine.

I'm sure that's not true. What you're describing is not the chain of responsibility pattern.

Chain of responsibility is an object-oriented design pattern, not a functional programming design pattern. Furthermore, you can't create a chain of responsibility without the linked list of handlers, where each handler encapsulates both a method to invoke it and a pointer to the next handler in the chain. All handlers implement the same interface in order to abstract details from the caller. The abstract class is the only piece that's unnecessary, but it provides the boilerplate to simplify handler definitions.

**Comment by StephenCWills** [comment]
With a bit of obsessively deep research into the subject, I've come to learn that modern C++ standards support lambda functions and closures, and also that chain of responsibility can theoretically be implemented using said lambdas and closures. I'm pretty sure it should be possible to model chain of responsibility with a chain function signature to act as the interface, multiple handler functions to act as the handlers, and a wrapper function to augment the chain with a new handler. The wrapper uses a closure to capture the state that would normally be required to store the pointer to the next handler.

This is pretty close to what you described. Is this what you were thinking of?

**Comment by julealgon** [comment]
> This is pretty close to what you described. Is this what you were thinking of?

Yes.
