### ISSUE TITLE
Picking up the Cathedral map Plays a Sound Every Time

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#1354]
**Important information**
Windows 10 / 184fbde1fd96ca797b0004639462f98263726623 / Downloaded from circleci

**Describe**
Every time you pick up the Cathedral Map, the audio is played ("Uh huh" for warrior), much like it used to be with Valor and Arkane's Valor.

**To Reproduce**
1. Obtain the Cathedral Map.
2. Drop it on the ground.
3. Pick it up.
4. Hear that sweet sweet "uh huh"
5. Repeat steps 2 through 5 to your hearts content.

**Expected behavior**
The audio only plays once, the first time you pick it up.

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6253863/single_0.zip)

**Comment by julealgon** [comment]
> much like it used to be with Valor and Arkane's Valor.

Wait, did we change that?

**Comment by NiteKat** [comment]
Yes, I'm not sure which commit, but it was fixed at some point in DevilutionX. I believe the attached save still has Arkane's Valor on it so you can verify it doesn't say "May the spirit of Arkane protect me" whenever you pick up the armor.

**Comment by galaxyhaxz** [comment]
It was a bug, if you picked up Valor or others they would reset the quest state each time, allowing items from previous games to trash the dungeon. I was the one who fixed it, it was found by NiteKat.

#992

**Comment by AJenbo** [comment]
> Every time you pick up the Cathedral Map, the audio is played ("Uh huh" for warrior), much like it used to be with Valor and Arkane's Valor.

Well get to them on at a time :)
