### ISSUE TITLE
Corrupt items causing overvflow

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#1356]
**Important information**
Windows 10 / Vanilla

**Describe**
Glitch item

**To Reproduce**
1. Get someone on battle.net to dupe you one

**Expected behavior**
It shouldn't exist

**Screenshots**
![unknown](https://user-images.githubusercontent.com/68359262/113496748-af487c80-94ca-11eb-8785-f119a116aa84.png)

**Additional context**
Causes insane character damage (only works in PVE)
10 STR required to wear
Says it raises Vitality, but unable to right click it to consume

Uses Optic Amulet as base item, despite using Map of the Stars graphic (idx: 0A)
Has a seed of Demical: -1 / Hexadecimal: FFFFFFFFFFFFFFFF
Has a Creation Flag of 0
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6253914/single_0.zip)

**Comment by AJenbo** [comment]
Thanks this is probably also a security issue so let's get it fixed.

**Comment by AJenbo** [comment]
The way this worked was by setting the item type to 523 (or there about) which is way outside the games ~150 valid options in the `AllItemsList[]` reading the game to read random data from other data structures.
