### ISSUE TITLE
Drop items from inventory/belt/equipment with CTRL+CLICK

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#1358]
## Description

Dropping multiple items from the inventory is currently a painful process, as one needs to move the cursor back and forth between the inventory screen and the play area, while keeping track of occupied space on the ground.

We can introduce a new shortcut to make this process less problematic, similar to how shift+click works today for moving items around.

## Details

- CTRL+Click on an item in the belt, inventory or equipment should immediately attempt to drop that item to the ground.
- Equipment restrictions should be consistent: if unequipping while attacking or moving is in place, the same should hold while attempting to drop it
- If all 9 tiles around the player are already filled with an item, the item should not be dropped (consistency with standard dropping behavior).
- Add info about command in help screen (similar to shift actions)
- Logic for dropping items should be consistent with the one used on gamepads (rely on the same function/behavior for consistency)
- Dropping special items should automatically target their object (cathedral map, rune bomb, etc)

Behavior should be standard: no need for feature flag

**Comment by AJenbo** [comment]
This logic should tie in with `TryDropItem()` form `SourceX/controls/plrctrls.cpp`
