### ISSUE TITLE
Draw item graphics on vendor screens

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#1359]
## Description

Standard vendor pages are very barebones. We can improve on them without changing their logic too dramatically by rendering the item icons alongside the item descriptions.

## Details
- Draw the icons to the left of the item description
- Investigate potential impact on item template height

Behavior should be standard as there is zero gameplay impact. No need for feature flags.

**Comment by joewis** [comment]
Maybe a D2 style merchant screen would be a possibility to explore?

**Comment by galaxyhaxz** [comment]
@AJenbo actually helped make graphics and I coded that as a teaser a few years ago.

![image](https://raw.githubusercontent.com/diasurgical/scalpel/master/screens/mod2.png)

**Comment by julealgon** [comment]
> Maybe a D2 style merchant screen would be a possibility to explore?

Personally, i prefer the list style shop. Also, changing to the inventory style would be a much bigger change.

**Comment by NikoVP** [comment]
The icons would either have to be scaled-down or be in a separate preview window in the text dialog version. Otherwise the vertical spacing between items would have to increase leading to less displayed items on screen or the item graphics wound be really close to each other and overlapping which also would not be pretty.

**Comment by julealgon** [comment]
@NikoVP , I hope you read the description, in particular this part:

> Investigate potential impact on item template height

I'm aware that this will potentially cause impact on the existing template. This proposal is not to just slap the icon there and be done with it, but to do it in a way that works properly on the UI design.

**Comment by FitzRoyX** [comment]
It's not just images, list style also can't handle longer item descriptions in case rare/set/unique resale are added. Vendor inventories are just better design more mod-friendly.

**Comment by julealgon** [comment]
> It's not just images, list style also can't handle longer item descriptions in case rare/set/unique resale are added.

Just because they are not shown in vanilla doesn't mean a list style _can't_ be implemented to do so @FitzRoyX . It is most definitely possible to have unique item properties show correctly using a list strategy.

> Vendor inventories are just better design more mod-friendly.

Can you elaborate why they are a better design, and why they are more mod-friendly? I disagree with both statements so I wanted to hear your reasoning.

**Comment by galaxyhaxz** [comment]
@julealgon You sound like you are a bit old school and prefer the game exactly as it was, which is fine, but there is something to consider. Diablo 1 was rushed and unfinished, Brevik himself even admitted that it was more of a "starting point". They made mistakes and various bad design choices, learned from them, and tried not to make them again in Diablo 2. Now D2 isn't perfect either, but a lot of aspects in it show how they would have done the first game if they had more time/better computers in 1996.

For example a lot of people will complain that any kind of modern lighting in Diablo tarnishes the atmosphere. While it is true that the original is quite dark, that design was chosen more because computers weren't great at the time and most people had 8-bit 640x480 displays, rather than being what they really wanted.

Vendor inventories are more user-friendly because they lay all the items out so you can quickly navigate them. It also makes it easier to see more text as opposed to using abbreviations to cram everything into 3 lines which could be a problem when translated to some languages.

**Comment by joewis** [comment]
Thinking of it, D3 has list style vendor inventories. Both approaches have their merits.
The audience here (including myself) might feel more nostalgia for D2 though.

**Comment by galaxyhaxz** [comment]
Never played D3, but is this what you are talking about? I actually don't think it's a bad idea either. It's like a combination of D1/D2, and similar to what jule had wanted.
![image](https://i.imgur.com/GxQU1yP.jpg)

**Comment by joewis** [comment]
![DIA_Switch_UI_VidarCollector_TF_003.jpg](https://user-images.githubusercontent.com/74438661/113864089-0f963180-97dd-11eb-8c8f-28db4a784512.jpg)

This is how it looks on switch.

**Comment by julealgon** [comment]
> @julealgon You sound like you are a bit old school and prefer the game exactly as it was, which is fine, but there is something to consider. Diablo 1 was rushed and unfinished, Brevik himself even admitted that it was more of a "starting point". They made mistakes and various bad design choices, learned from them, and tried not to make them again in Diablo 2.

@galaxyhaxz I wouldn't say that. I have numerous times said that "just because it is done in D2, doesn't mean it's perfect design". I think people do that _a lot_: assume that D2 is a gold standard to be followed for every feature. To me, that's s huge mistake and every design has its own merits.

As you just saw, D3 actually got rid of the tetris inventory for vendors. Yes, i think something like that could work in D1, but i _also_ don't consider the D3 design perfect.

I'll even say something else here: the tetris inventory is actually _more_ limiting to mods than the list one. I have no idea why anyone would think otherwise. The inventory design introduces restrictions to an otherwise unbounded system: the space limitation alone creates complications if you want to have more items displayed.

As i said earlier, i feel everybody just needs to keep an open mind when it comes to designing features: take other games into consideration, but don't blindly copy something just because game X done it that way: that's not a valid argument for a feature.

**Comment by galaxyhaxz** [comment]
You skipped quoting that last sentence. Didn't say D2 was flawless, it did some things wrong and even did some things worse than D1. Overall I think the UI became a lot better with box descriptions when you hover over an item and view stores. If you need space for more items, you can always add tabs.

**Comment by FitzRoyX** [comment]
> I'll even say something else here: the tetris inventory is actually _more_ limiting to mods than the list one. I have no idea why anyone would think otherwise. The inventory design introduces restrictions to an otherwise unbounded system: the space limitation alone creates complications if you want to have more items displayed.

Why show item descriptions unless you're interested in the item type and hovering over it with your mouse? With the list, you're constantly scrolling past items you have no interest in to see if there are any good ones buried out of view. The scrolling aspect of a list is dumb and basically avoidable.

If you're not happy with the amount of items offered, just give vendor pages an unlimited refresh button. There are better options than a giant scrollbar-controlled list forcibly trying to show every item's description.

**Comment by julealgon** [comment]
I appreciate your open mind @FitzRoyX . I especially like how everything is "dumb" and how infinitely superior the other method is (ignoring completely the fact that many modern games do not use the approach).

Also, when presented with the **fact** that the inventory-based vendor adds restrictions and is more difficult to manage for a mod, you just say "well just implement X" which is precisely the point: there is no need to implement anything with the list approach.

Also
> Why show item descriptions unless you're interested in the item type and hovering over it with your mouse?

"Why force me to mouse over every item to check its properties when I could just show their descriptions directly?"

It's mind boggling to me that you cannot think of any possible way to improve a list-based system, the only sensible option possible is to use the Diablo 2 way.

I'm like "hey we could add the item picture to the vendor list" and people are like "list system bad! d2 inventories now!". No one is preventing you from designing a different inventory system, but that is _not_ the proposal here.

No wonder every game ever made uses the inventory system to great effect and proves that any other design is useless and a waste of time.

**Comment by joewis** [comment]
From real world experience, list style shop systems seem to work quite well.
If Amazon switched to an inventory style shop system, I'd expect some complaints ;)

**Comment by AJenbo** [comment]
Regarding the limits of an inventory based system, nothing dictates that you can't also add a scrollbar there.

**Comment by galaxyhaxz** [comment]
Coded a few variants. Sadly you can't really get more than two items at once as you don't have enough space for text (see second image). I still think it's an improvement over vanilla.

![inv1](https://user-images.githubusercontent.com/65138215/113986524-f14b2880-9812-11eb-8bb6-4664b91798cf.png)
![inv2](https://user-images.githubusercontent.com/65138215/113986543-f6a87300-9812-11eb-9272-c020836e8eb1.png)

**Comment by galaxyhaxz** [comment]
Another suggestion i'd make is to center the vendor dialogs. It doesn't make much sense for it to be on the right side of the screen as no panels could be open on the left side.
![Untitled](https://user-images.githubusercontent.com/65138215/113992205-d4b1ef00-9818-11eb-8b24-f3da5cefb80c.png)

**Comment by FitzRoyX** [comment]
That Griswold menu reminds me of maybe the biggest problem with vanilla shops: there's too much clicking back and forth between menu entries if you have multiple things to do. It's nice to be able to do everything on one screen.

**Comment by galaxyhaxz** [comment]
Yep, I still prefer the D2 style, but the above style can be implemented without changing as much.

**Comment by ChaosMarc** [comment]
I really like the two proposed vendor screens. On bigger screens there could be more items visible if the UI scaled correctly.

couldn't this be further enhanced by displaying the vendor view on the left hand side and (a list view of) the inventory on the right hand side? this way a direct comparison between the items could be done.

**Comment by joewis** [comment]
In the "are you sure you want to buy this item" screen - I believe that's confirm_enter, it would be quite helpful to see the item. 
I bought a gothic plate when expecting a full plate mail. But that may just be me.

**Comment by joewis** [comment]
> Another suggestion i'd make is to center the vendor dialogs. It doesn't make much sense for it to be on the right side of the screen as no panels could be open on the left side.
> ![Untitled](https://user-images.githubusercontent.com/65138215/113992205-d4b1ef00-9818-11eb-8b24-f3da5cefb80c.png)
> 

I think we can make use of the siege on the left - one of the mods implemented item comparison, which I'm interested in backporting. It would show how stats would change with the new item compared with the current one.

**Comment by NikoVP** [comment]
@galaxyhaxz Is it possible the list for the list to move a bit to the right while introducing the image on the left. something like this. image is centered at in the middle of the list [
![shop](https://user-images.githubusercontent.com/60973634/114181421-c4e1fa00-9941-11eb-97ee-a143de661ded.png)
](url)

**Comment by galaxyhaxz** [comment]
Of course it's possible! However with the stock Diablo font the kerning would make some strings not fit. See above in my pic how the font is closer together. You'd probably have to display requirements on a separate line and show 3 items instead of 4.

**Comment by NikoVP** [comment]
I do think that these proposals can all be implemented as an alternative to the current list. Similarly to amazon as someone already mentioned. A few new icons in the upper right corner can switch between views. 😁 Maybe add sort by price or type. Jeff Bezos would approve. Some text that is too wide could be condensed.Damage canbecome DMG, magic - Mag similar to requirements. I am no coder, and can't demand much but a function that dynamically expands or contracts the text depending on the available text might be a good solution. Just suggestions.

**Comment by galaxyhaxz** [comment]
You can also change `Required` to `REQ`. I think that alone should be enough to make your implementation work. Your idea is definitely the easiest, and would only require modifying a few lines of code.

**Comment by julealgon** [comment]
Really nice mockups @galaxyhaxz . Really impressive how quickly you put those together too.

**Comment by Psojed** [comment]
In case there isn't enough room for everything together, what if you switched between the item graphics and item description with a key press? Something like
- hold Shift to display item graphics instead of item descritption
or
- hold Shift to highlight the currently selected item (using one of galaxyhaxz's mockups)

**Comment by ikonomov** [comment]
I really love the idea of having the list with the item graphics.  I decided to see how they can look at 50% "thumbnail size" and surprisingly they are still quite recognizable.  I'm not sure if this will look good enough for most people or if the original list size can still be retained with this smaller size, but I thought it might be an idea worth exploring.
![Untitled-1](https://user-images.githubusercontent.com/5624187/213616598-9035ad17-768e-4be5-a21f-3913e1d8ffba.gif)

**Comment by ikonomov** [comment]
here it is how it would look in-game
![_sample](https://user-images.githubusercontent.com/5624187/213621545-d631d85c-9b6b-49fa-a99a-76181ed54974.gif)

**Comment by julealgon** [comment]
That's pretty cool @ikonomov !

Could be a decent enough workaround until we have actual global sprite/UI scaling (which would enable "render everything scaled 2x, then render the items in the vendor at normal 1x", thus not compromising image quality).

One point of discussion would be to potentially move the pentagram cursor to before the images as well (and maybe centralize them?). Obviously a bit subjective there.

**Comment by ikonomov** [comment]
@julealgon I don't see you in discord anymore.  You should join the discussion, glebm and staphen are working out ways to make the scaling happen in-game.

This is how the thumbnails would look in relationship to the normal item graphics once the game is upscaled to 1080p or 1440p resolution fullscreen:
![scaling](https://user-images.githubusercontent.com/5624187/213759560-c063080b-109d-4ef9-8b53-45ef24d63fe9.gif)
