### ISSUE TITLE
Differentiate "discovered" from "explored" sections on automap

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#1363]
## Description

When a player activates a secluded shrine, the entire map for the current floor is revealed. However, this leads to poor user experience since it becomes impossible to know exactly where the player has already been to in the floor without memorizing the layout, which defeats the purpose of a map in the first place.

Sections of the map that are revealed by a secluded shrine should appear in a different color compared to sections of the map that were actually explored by the player. This will provide the benefit of knowing the layout from the shrine, while still giving information to the player about where he has been to vs where he can go to next.

## Details

- Might need a new flag to keep track of a different map state (revealed vs explored). Save games will probably be impacted
- Loading a save without this information should behave as before: i.e. the map is just marked as explored
- Suggested color to use for revealed but unexplored map: blue

No feature flags should be needed for this as it doesn't impact gameplay. It is a simple, situational QOL.

**Comment by qndel** [comment]
I did a similar thing in infernity but couldn't find a way to port it in a clean way

**Comment by galaxyhaxz** [comment]
Could also change the shrine to say "you forgot where you are" and have it un-reveal the entire map :P

**Comment by AJenbo** [comment]
secluded shrine are the worst

**Comment by julealgon** [comment]
> secluded shrine are the worst

Exactly. They are _supposed_ to be good, but without differentiating the map they actually become annoying.

**Comment by RicoLeNecro** [comment]
> secluded shrine are the worst

That's a strange way to spell "sacred shrine"

**Comment by yuripourre** [comment]
Man! This one is harder than it sounds, I tried yesterday but had no success.

**Comment by galaxyhaxz** [comment]
> Man! This one is harder than it sounds

A reasonably easy way to achieve this is to add a flag to the function which plots the pixels. If flag is set, all pixels are X color, otherwise proceed as usual. Set the flag when using the shrine, then unset after.

**Comment by yuripourre** [comment]
@galaxyhaxz Yes! I tried something similar (adding a bool flag to the automap tile) but for some reason, the game start crashing :joy:

@qndel did it in a better way.
