### ISSUE TITLE
Unexpected cursor movement when toggling panel

### ISSUE THREAD

**Issue by Tumayto** [diasurgical/devilutionX#1364]
**Important information**
Windows 10 Home 64-bit Pro / DevilutionX v1.1.0-ae82fb0b

**Describe**
When pressing a button to toggle a panel, the cursor moves a very small amount.
This becomes noticeable if you hold down said button. 

**To Reproduce**
1. Make sure resolution is set to true 640x480, maximize or fullscreen (doesn't seem to occur at native window resolution).
2. When in-game, hold down a button to toggle a panel (e.g. i) and the cursor will move on its own.

**Expected behavior**
Cursor stays still.

**Video**
https://user-images.githubusercontent.com/80623433/113499983-7e774000-94e8-11eb-9cc8-029ea8cb8a94.mp4

**Comment by AJenbo** [comment]
This is rounding errors caused by the given resolution that you are upscaling to
