### ISSUE TITLE
Unique monsters leave glowing circles where they spawn

### ISSUE THREAD

**Issue by joankaradimov** [diasurgical/devilutionX#139]
Unique monsters sometimes get two light radii. One that follows them around (as it should) and one where they spawned. The second one is active even when they die. I'm seeing this in devilutionX (both in release 0.4.0 and in a version of master that I built myself). I don't know if it happens in devilution and/or in the original Diablo engine.

I've seen it on more than one occasion. But I believe it does not happen every time.

This can be seen clearly here with Lazarus and his two succubi:
![screen00](https://user-images.githubusercontent.com/221979/60543480-17c76000-9d1f-11e9-9d24-d7060009b273.png)

**Comment by AJenbo** [comment]
I believe this issue is in the original diablo also, it for sure happens with teleporting monsters

**Comment by galaxyhaxz** [comment]
Yeah pretty sure that was documented in the [DSF Bugs list](https://github.com/diasurgical/devilution/issues/64). The function `SetDead` in `dead.cpp` is probably related.

**Comment by AJenbo** [comment]
This issue should have been fixed together with other lighting issues in the game.
