### ISSUE TITLE
SDL_init() failing on Windows du to sensor permissions

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1391]
![image](https://user-images.githubusercontent.com/204594/113735638-b787fe00-96fc-11eb-86b6-cc4a30674797.png)

I had a similar issue running the windows builds via Wine, maybe we need to disable SDL_INIT_SENSOR, or rather switch to explicitly enabling things we need instead of disabling what causes issues over time.

**Comment by awsker** [comment]
I have this exact issue on a regular Windows 10 installation. SDL_INIT_EVERYTHING seems a bit heavy handed.

**Comment by AJenbo** [comment]
@awsker as a workaround try using an older version of SDL https://www.libsdl.org/release/SDL2-2.0.9-win32-x64.zip

in case it wasnt clear the error is from a real windows and not my wine setup.

**Comment by awsker** [comment]
A different error occurred with much less information. Nothing in the Windows Event Log either

![image](https://user-images.githubusercontent.com/604653/113902859-a27c9f00-97d0-11eb-9266-0344b3b42b49.png)

**Comment by AJenbo** [comment]
Please use the latest beta where this issue has been fixed.
https://26645-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip
