### ISSUE TITLE
No walking sound in town if "Run in Town=1"

### ISSUE THREAD

**Issue by malvarenga123** [diasurgical/devilutionX#1392]
**Important information**
Windows 7 x64
Devilution 1.2.0 x86 downloaded from release

**Describe**
If the option "Run in Town" is set to 1 in the ini file, there is no "walking" sound in town. The option "Walking Sound" makes no difference in this case

**To Reproduce**
1. Set "Run in Town=1" in the ini file
2. Walk in town

**Expected behavior**
When this was enabled in @Manuel-K patches, you could hear the steps when walking in town.

**Additional context**
I don't know if this is intentional or not. If it is, maybe a note should be added to the wiki.

**Comment by NikoVP** [comment]
I don't know if someone would want that on when Run in town is enabled. It wouldn't match the steps that the character is doing and if it is synchronized with the speed it would be producing awful noise...

**Comment by malvarenga123** [comment]
It didn't bother me, to be honest.
I also don't mind it being silent, and if it is intentional I think it should be written somewhere.

**Comment by AJenbo** [comment]
its by design as it skips the frame that produces the sound.
