### ISSUE TITLE
Dropped Staff is stuck in Background?

### ISSUE THREAD

**Issue by RetroGamer02** [diasurgical/devilutionX#1394]
Started a new game killed a few enemies in the first level came back to town with mostly full inventory went to drop a staff and it seems to be part of the building now I cant pick it up. I have included a screenshot and the game save.

![screen00](https://user-images.githubusercontent.com/70994866/113770364-0b401a80-96f0-11eb-9a7c-f508a5db9c01.png)
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6267187/single_0.zip)

**Comment by AJenbo** [comment]
This appears to be the same issue as seen in #1367

**Comment by AJenbo** [comment]
@RetroGamer02 could you let me know if it was hellfire or diablo you were playing?
