### ISSUE TITLE
Possible bug in CreatePlayer

### ISSUE THREAD

**Issue by GalLuvton** [diasurgical/devilutionX#140]
CreatePlayer sets the player _pDamageMod field before setting the _pLevel field, which is used in the _pDamageMod calculation (probably set to 0 at the start).
_pDamageMod is re-calculated when ModifyPlrStr, ModifyPlrDex, SetPlrStr, SetPlrDex, or CalcPlrItemVals are called.

**Comment by AJenbo** [comment]
Good catch, this has now been corrected. It won't have had an effect in-game as CalcPlrItemVals is called at the end of CreatePlayer.
