### ISSUE TITLE
Failure when attempting to Compile

### ISSUE THREAD

**Issue by jrugia** [diasurgical/devilutionX#1401]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

OS: Debian 9 (updated to 9.13)
DevilutionX version: 1.2 and Master branch up to commit 47feeda

**Describe**

Attempting to compile from source results in an error. See Screenshot for details.
Attempted builds (release and debug), no difference.

**Screenshots**

![Screenshot at 2021-04-07 16-14-42](https://user-images.githubusercontent.com/13750621/113881451-bae2be80-97bc-11eb-8a68-710160d4395d.png)

Let me know if you need anything else :)

**Comment by qndel** [comment]
use git

**Comment by jrugia** [comment]
I eventually found out the cause and solved it by filling the 3 respective fields by hand in the config.h file after running cmake.

Game is working as expected. Thanks :-)

**Comment by AJenbo** [comment]
Ok, but be aware that this isn't the proper way to supply the info and it could be overwritten by CMake at some point.
Instead you should set it via CMake defien `VERSION_NUM`.

`cmake .. -DVERSION_NUM=1.2.0`
