### ISSUE TITLE
Double input when using keyboard with AppImage

### ISSUE THREAD

**Issue by valeth** [diasurgical/devilutionX#1404]
**Important information**
Arch Linux / DevilutionX 1.2 / AppImage release

**Describe**
Each key input seems to be duplicated, which causes it to skip menu entries and immediately closes menus.
It is also noticeable when deleting text via backspace, it always deletes two characters.

**To Reproduce**
1. Install Devilution by using the AppImage release
2. Put base game files in place (excluding Hellfire) 
3. Start game
4. Menu items are skipped when pressing up/down on the keyboard due to double input

**Expected behavior**
Each key is registered once

**Comment by AJenbo** [comment]
Could you check if this is also the case for non AppImage builds?

**Comment by valeth** [comment]
@AJenbo just tested it and it seems to be an AppImage issue indeed

My system has the following SDL2 libraries installed:
sdl2: 2.0.14
sdl2_ttf: 2.0.15
sdl2_mixer: 2.0.4
sdl2_image: 2.0.5 (don't think that one is even used)

**Comment by AJenbo** [comment]
Is that Wayland or x11?

**Comment by valeth** [comment]
tested on X11

**Comment by valeth** [comment]
Also did a test on Wayland (with KDE Plasma) and it has the same behavior as the X11 backend.

**Comment by julealgon** [comment]
@valeth was this problem resolved? Can you provide a quick summary for future reference?

**Comment by AJenbo** [comment]
Probably, we did update SDL

**Comment by valeth** [comment]
No, it's just that I think that Appimage is a severely flawed packaging format, and I don't intend on testing it anymore.

**Comment by julealgon** [comment]
> No, it's just that I think that Appimage is a severely flawed packaging format, and I don't intend on testing it anymore.

If that's the case, this should either be left open for somebody else to fix, or be closed as "not planned" instead of "completed" IMHO.

**Comment by AJenbo** [comment]
Did you test with the 1.5.2 release ?
