### ISSUE TITLE
SDL Policy error on Windows 10

### ISSUE THREAD

**Issue by donizettilorenzo** [diasurgical/devilutionX#1405]
x86 and x64 builds

https://postimg.cc/bG2cZQ55

2 Win10 x64 20H2 tested, same fault.

**Comment by AJenbo** [comment]
Please try the latest beta: https://26646-143324737-gh.circle-artifacts.com/0/devilutionx_x86.zip

Duplicate of #1391

**Comment by donizettilorenzo** [comment]
It doesn't even start.

**Comment by AJenbo** [comment]
Ok, we expect to release a patch to correct this shortly

**Comment by donizettilorenzo** [comment]
No need to hurry! Thanks!
