### ISSUE TITLE
Problem with SDL_Init(SDL_INIT_EVERYTHING)

### ISSUE THREAD

**Issue by pgielda** [diasurgical/devilutionX#141]
I am using Linux (Gentoo). Gentoo allows you to compile libraries with certain compilation flags (unlike binary distros) so sometimes interesting problems occur.
In SourceX/miniwin/misc.cpp there is a call to "SDL_Init(SDL_INIT_EVERYTHING)".
This for some reason causes problems and ends with a "Unable to create main window" error.
There is an additional message:
"INFO: SDL not built with haptic (force feedback) support"
that might be the reason.

If I change this to "SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO)" devilutionx starts fine.

The question is if SDL_INIT_EVERYTHING is really needed here? Isn't video+audio not enough?

**Comment by AJenbo** [comment]
SDL_INIT_TIMER might be needed for SDL_GetTicks?
SDL_INIT_GAMECONTROLLER We will need this for consoles (Switch is comming)
SDL_INIT_JOYSTICK required by SDL_INIT_GAMECONTROLLER
SDL_INIT_EVENTS theres a good chance this is needed, also required by SDL_INIT_JOYSTICK.

So it looks like `SDL_Init(SDL_INIT_EVERYTHING & ~SDL_INIT_HAPTIC)` is the only meaning full change we could make.

**Comment by sskras** [comment]
@AJenbo wrote:

> SDL_INIT_GAMECONTROLLER We will need this for consoles (Switch is comming)
> SDL_INIT_JOYSTICK required by SDL_INIT_GAMECONTROLLER

I guess a lot of PC players don't plan using game controllers to play dX. IMO this should be a part of configuration phase. 

> SDL_INIT_EVENTS theres a good chance this is needed, also required by SDL_INIT_JOYSTICK.

Why not leave the minimal set and run testing?

> So it looks like `SDL_Init(SDL_INIT_EVERYTHING & ~SDL_INIT_HAPTIC)` is the only meaning full change we could make.

So, is no one going to implement Force Feedback in dX in future? : )

**Comment by AJenbo** [comment]
> I guess a lot of PC players don't plan using game controllers to play dX. IMO this should be a part of configuration phase.

It's not like disabling it will really give you any benefits, only more complicated code and confusing config files.

> Why not leave the minimal set and run testing?

Test what?

> So, is no one going to implement Force Feedback in dX in future? : )

Maybe, but no know plans of anyone doing so.

**Comment by pgielda** [comment]
I can confirm that SDL_Init(SDL_INIT_EVERYTHING & ~SDL_INIT_HAPTIC) indeed works fine for my issue.

**Comment by AJenbo** [comment]
Fixed https://github.com/diasurgical/devilutionX/commit/64f2b5299a6ba1b3ad95e0d46f166978f8f80b10
