### ISSUE TITLE
Using town portals in leorics tomb causes the light to dim down

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1410]
Thanks to @Chance4us for testing this.

Reproducing lighting bug:
[vanilla-run.mkv.zip](https://github.com/diasurgical/devilutionX/files/6274156/vanilla-run.mkv.zip)

The lighting is dimmer after change level between town/tomb.
[light-difference.mkv.zip](https://github.com/diasurgical/devilutionX/files/6274165/light-difference.mkv.zip)

Picture before entering town:
![before-town](https://user-images.githubusercontent.com/45902449/113927506-e16d1d80-97ed-11eb-8d68-96dc6491c371.png)

Picture Image after returning to the tomb. 
![after-town](https://user-images.githubusercontent.com/45902449/113927765-2c873080-97ee-11eb-8a7f-dcb48fb49a09.png)

**Comment by julealgon** [comment]
Isn't this the same bug that used to happen with Valor's corridor torches? It seems like the room lights stop working there. @qndel FYI

**Comment by AJenbo** [comment]
It feels similar yes, but I wouldn't want to conclude anything yet. Worth noting is that walking in and out using the entrance fixes the light so there is probably a simple call that we just need to copy from that logic.

**Comment by qndel** [comment]
why did the floor tiles change? Lol
