### ISSUE TITLE
Noisy audio VS2019 Debug SDL 2.0.14 Win 10 x64

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#1434]
Hearing noisy audio with this setup.

The audio had distortion at both high and low frequencies

A workaround that fixed the issue for me is `SDL_AUDIODRIVER=winmm`

For now, we should probably make sure we use the `winmm` driver on Windows (e.g. by calling `SDL_InitAudio("winmm")` manually).

This may be fixed in SDL HEAD by https://github.com/libsdl-org/SDL/commit/b98b5adcaea159fc6a9753f808875acf7d3ee945 though I'm not sure

**Comment by AJenbo** [comment]
looks like that is a sdl2 specific driver, was it using directsound by default?

**Comment by glebm** [comment]
I think it's WASAPI by default
