### ISSUE TITLE
Enemies Do Not Consistently Display Their Immunities

### ISSUE THREAD

**Issue by BartyMae** [diasurgical/devilutionX#1436]
**Important information**
Windows 10 LTSC 2019 x64, DevilutionX (v1.2.0-5F5DCIAF) with Hellfire, self-compiled, multiplayer.

**Description**
I have noticed a number of times enemies displaying their immunities incorrectly. What I mean by this is that some enemies that are e.g. fire immune will sometimes display that they are not immune to fire...and sometime they correctly will, even in the same play session and in the same area. Similarly, some enemies that are NOT immune to fire will display that they ARE immune to fire. I noticed the same occurring with lightning-immune enemies, so it is not localized to simply fire-immune creatures.

I started seeing this upon getting to the Caves and and coming across Flayed Ones and Storm Riders (I think those names are correct) and not being able to hit them with my spells as I expected based on what I was seeing with their immunity icons. It was confusing, too, because sometimes they would and sometimes they wouldn't display the proper icons. I can only assume that it's the result of displaying previously selected highlighted enemies' immunities for the new target, because there have been a number of times where a fire immune creature would e.g. display immunity to lightning instead, or both lightning and fire, as if it was a different creature type I had been fighting moments before.

**Expected behavior**
Enemies should display their correct immunities all of the time.

**Screenshots**
In the Catacombs, Familiars are immune to lightning, but they were not displaying it for me, leading me to try to target them with Chain Lightning that looked like it was simply missing, but which was actually the result of them being immune.

https://dl.dropboxusercontent.com/s/so81y7w388hovva/firefox_2WZ8cMPCdf.png

**Comment by qndel** [comment]
It follows the original behavior where you have to kill some monsters to see such info

**Comment by AJenbo** [comment]
you must have 15 kills to see the immunities

**Comment by BartyMae** [comment]
Ah, that explains the Familiar then - however, I swear I have seem some creatures display that they're immune to fire when I have smacked them in the face with a Fireball quite handily. I will be on the lookout and report back if I see it again.

**Comment by AJenbo** [comment]
note that there is a difference between them being resistant and immune. The icons are also different for this.
