### ISSUE TITLE
Jewelry Will Not Spawn on Griswold in Multiplayer

### ISSUE THREAD

**Issue by BartyMae** [diasurgical/devilutionX#1439]
**Important information**
Windows 10 LTSC 2019 x64, DevilutionX (v1.2.0-5F5DCIAF) with Hellfire, self-compiled, multiplayer.

**Description**
Unsure if bug with DevilutionX or original game (it's also possible that it's intended).

While playing multiplayer, I told the friend that I was playing with that Griswold can actually spawn magic rings and amulets - but it was unlikely unless the player attempting to do the purchasing didn't have any jewelry on them when Griswold's inventory was generated. In singleplayer, I can confirm this occurs quite easily - on a level ~30 character with no jewelry in DevilutionX singleplayer, Griswold pretty much immediately starts spawning magic jewelry after creating a new game. In multiplayer on a level ~25 character with no jewelry, I have created about 20 straight new games and he has not sold a single ring or amulet. Even after stuffing our inventories full of any item type BESIDES jewelry (as we understand it, this increases the chances of jewelry being sold since it reduces the chances of those other types of items being sold), he still refuses to sell any jewelry. Color us perplexed.

Initially, I thought this problem would be limited to Hellfire - however, I attempted the same in the base game in DevilutionX, and discovered that it's the same there - Griswold refuses to spawn jewelry in multiplayer. I am going to guess that this is actually intended for some reason, but just in case it's not, here's the report anyways. Feel free to close if you know it to be the proper behavior.

**Expected behavior**
Griswold should be able to sell jewelry in multiplayer?

**Comment by AJenbo** [comment]
original behavior https://diablo2.diablowiki.net/Griswold_the_Blacksmith

**Comment by BartyMae** [comment]
As I feared - thanks!

**Comment by qndel** [comment]
Actually I don't think so? The guy has a point, it was hellfire that introduced the whole "equipped items affect shop items" voodoo and atm it seems griswold in devilutionx is doing it for BOTH hellfire and vanilla which is wrong

**Comment by qndel** [comment]
https://github.com/diasurgical/devilution/blob/master/Source/items.cpp#L5063

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/blob/08c34400d35be294799f3db96d715ced1643106c/Source/items.cpp#L4664
