### ISSUE TITLE
Invisible town portal

### ISSUE THREAD

**Issue by malvarenga123** [diasurgical/devilutionX#1446]
**Important information**
Windows 7 x64
DevilutionX 1.2.0-4E92C866
Downloaded from: https://27487-143324737-gh.circle-artifacts.com/0/devilutionx_x64.zip

**Describe**
The town portal is invisible in town.

**To Reproduce**
Load the attached save
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6286341/single_0.zip)

**Screenshots**
1.2.0-4E92C866
![screen00](https://user-images.githubusercontent.com/61893389/114193330-cb15ad80-9924-11eb-8e95-a3f5a40e424d.png)
1.2.0 release
![screen01](https://user-images.githubusercontent.com/61893389/114193382-d7016f80-9924-11eb-8434-2cbef31b87ce.png)

**Additional context**
This didn't happen with 1.2.0 release

**Comment by AJenbo** [comment]
This was fixed here https://github.com/diasurgical/devilutionX/commit/6fcca51ec65c440d1d8ea6c45a8958213bb8fb91
