### ISSUE TITLE
[Android] ExaGear Windows Emulator for Android

### ISSUE THREAD

**Issue by qlGGlp** [diasurgical/devilutionX#1447]
**Important information**
ExaGear Windows Emulator for Android / DevilutionX 1.2.0 (i386) / downloaded

**Describe**
Moving from SDL version 2.0.12 to 2.0.14 made the game unable to run under this emulator for me.

**Additional context**
It's still possible to run it using the older library.

**Comment by qndel** [comment]
I don't think we care about any emulators, just wait for android version? 😅

**Comment by AJenbo** [comment]
Since there is a work around and like Qndel said our goal is to provide native implementations for platforms, this isn't really a concern. We specifically chose not to statically link SDL for situations like this.

**Comment by qlGGlp** [comment]
Yes, that's what I've found out myself and thank you for that! It's really nice to be able to play Diablo I (vanilla won't run under ExaGear), Diablo II and other older PC games on a phone.

**Comment by AJenbo** [comment]
hopefully we can get a native port for android in the not too fare future
