### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by JohnsterID** [diasurgical/devilutionX#1449]
Would the project please review and clarify the license for DevelutionX, the [README.md](https://github.com/diasurgical/devilutionX/blob/master/README.md) includes a [caveat ](https://github.com/diasurgical/devilutionX/blame/master/README.md#L64)(extract below) that is in conflict with the [LICENSE](https://github.com/diasurgical/devilutionX/blob/master/LICENSE) (The Unlicense).

> The source code in this repository is for non-commercial use only. If you use the source code you may not charge others for access to it or any derivative work thereof.

Other reverse engineering projects that express the above intent are usually GPLv2 or later.

For reference, the last archived version of the re3 Missing license issue (archive doesn’t include all of the discussion): https://web.archive.org/web/20210216093125/https://github.com/GTAmodding/re3/issues/794/

Reverse engineering for research or interoperability purposes might be lawful, however, the project must not include any derivative data.

[EFF - Coders’ Rights Project Reverse Engineering FAQ](https://www.eff.org/issues/coders/reverse-engineering-faq)

[Vidstrom Labs - The legal boundaries of reverse engineering in the EU](https://www.vidstromlabs.com/blog/the-legal-boundaries-of-reverse-engineering-in-the-eu/)

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilution/issues/2208
