### ISSUE TITLE
Leoric's tomb - Hidden door did not open

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1462]
Leoric's tomb hidden door didn't open, although all four crucified skeletons were killed.
After killing the skeletons, I used a town portal. Unfortunately, before using the town portal,
I did not pay attention to whether the hidden door had already been opened and closed when I returned to the tomb.
Also it is unclear whether it could be a defective seed.
![tomb](https://user-images.githubusercontent.com/45902449/114279955-6139f880-9a37-11eb-9f96-3ba8858d6541.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6290471/single_0.hsv.zip)

My version is commit 8826fd27c956ca857c24acfa33dcb4e69728c9be.

**Comment by Chance4us** [comment]
Additional information:
This is the same game I attached already in "Gather vanilla items for testing #1094" before entering the tomb.
If you go the shortest way to the leorics tomb once again you should experience the same issue.
Just take the mana shield scroll nearby Adria to be able to fight against Leoric.

Save game:
[gibbous_moon.zip](https://github.com/diasurgical/devilutionX/files/6290521/gibbous_moon.zip)

So it seems to be a bugged seed.

**Comment by galaxyhaxz** [comment]
Don't have hellfire setup atm so can you share the seed? To do this, just press the R key and take a screenshot. Thanks.

**Comment by Chance4us** [comment]
Only a normal screenshot did work.
By the way, I replayed in vanilla-hellfire and the door did open.

**Comment by Chance4us** [comment]
Now i bisected and then killed leoric, then killed him again, then again and again.
Kept digging and the fingers are almost broken.
Finally I can say the bug occurs since commit 6f1498d315b8d4fffdfdab52ee8a943ce30e4835.

**Comment by Chance4us** [comment]
@galaxyhaxz Why holding R + pressing Print does not work for me?

**Comment by galaxyhaxz** [comment]
Ah you must be playing release build then. You'd have to compile as debug in order for the seed to print. Perhaps this should be enabled in release builds for awhile, at least so end users can help debug issues.

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/114285250-095eba00-9a56-11eb-9ae1-fab5670f3ed0.png)

**Comment by Chance4us** [comment]
@galaxyhaxz Thank you now it worked.
![seed](https://user-images.githubusercontent.com/45902449/114285406-2051dc00-9a57-11eb-9b0f-d400f8624817.png)

@AJenbo The issue is caused by commit  6f1498d.

**Comment by AJenbo** [comment]
I loaded your save game and can open the room just fine.

**Comment by Chance4us** [comment]
> I loaded your save game and can open the room just fine.

You should please not use the first savegame. Because if you load or reenter the room, the room will be opened.
You can only reproduce this intricate bug if you load the second one (gibbous_moon.zip), kill the leoric, kill the crucified skeletons and the room doesn't open immediately.

**Comment by AJenbo** [comment]
I used the secound one

**Comment by Chance4us** [comment]
So you killed leoric and the crucified skeleton again?

**Comment by AJenbo** [comment]
![Uploading image.png…]()

**Comment by Chance4us** [comment]
Strange, that it happens only to me. I will make a video so you can see the difference.

**Comment by AJenbo** [comment]
It's not that i don't belive you.

**Comment by Chance4us** [comment]
I believe you that you believe me. I believe you too.
It could just be that I play a bit different, so that it causes to appear this issue.

**Comment by Chance4us** [comment]
Part 1 with compilation process of commit 836ea40d477256c73ab33d9fd82241ce6b5ea2d6.
Very compressed due to its length.
[part1.mkv.zip](https://github.com/diasurgical/devilutionX/files/6290933/part1.mkv.zip)

**Comment by Chance4us** [comment]
Part 1 with compilation process of commit 6f1498d315b8d4fffdfdab52ee8a943ce30e4835.
Very compressed due to its length.
[part1.mkv.zip](https://github.com/diasurgical/devilutionX/files/6290961/part1.mkv.zip)

**Comment by Chance4us** [comment]
Part 2 with compilation process of last good commit bc3dc545da64bb7f804dfce354811327a3a4ddcd.
[part2.mkv.zip](https://github.com/diasurgical/devilutionX/files/6290970/part2.mkv.zip)

**Comment by Chance4us** [comment]
I can also provide my ini file:
[diablo.ini.zip](https://github.com/diasurgical/devilutionX/files/6291340/diablo.ini.zip)

**Comment by Chance4us** [comment]
Unfortunately the issue seems to appear randomly.
Commit 77d0bb6690b76d60efb77eea1374ec77b8753e94 seems to work correctly.
So I close this one and will continue to monitor the situation.

**Comment by AJenbo** [comment]
Sounds good thanks.

**Comment by StephenCWills** [comment]
I actually started playtesting this one before it was closed this morning. I was able to reproduce this myself today on 6f1498d using Diablo, not Hellfire. I captured the seed and went to test it again, but the dungeon that was generated was not the same. In fact, the seed does appear to generate the same dungeon each time, but it has Poison Water instead of Leoric so it can't even be used for testing. Anyone have any idea what I did wrong?

![image](https://user-images.githubusercontent.com/9203145/114311554-3db99100-9abd-11eb-8e6d-cef1645331ad.png)

![image](https://user-images.githubusercontent.com/9203145/114311621-7c4f4b80-9abd-11eb-8326-8d45daf2fcf7.png)

**Comment by AJenbo** [comment]
Ok, let us know if it still happens on master, if you can bisect it that would be very helpful.

**Comment by StephenCWills** [comment]
What I didn't realize is that quests are still randomized regardless of the seed, which means the dungeon configurations could change as a result of having different quests. That's not particularly handy for testing, but it worked out fine for me since I could always just check the fountain. I ran the quest probably around a dozen times in total. For every run, I defeated Leoric first and then knocked the crucified skeletons in the order of South, West, North, and East to match video from @Chance4us. I was able to reproduce the issue 100% of the time on 6f1498d, but 0% of the time on master with the following seed: 1586010936. I think it's fairly safe to say the issue has been fixed, whatever it was.

**Comment by galaxyhaxz** [comment]
@StephenCWills thanks for reporting. Quests are chosen independently of the level seed, so for every seed you usually have 2 variants depending on which quests spawn, this is by design.

**Comment by Chance4us** [comment]
@StephenCWills Thanks for testplaying and reporting.
You can use the setting "Randomize Quests=0" in diablo.ini to play all available quests.

**Comment by AJenbo** [comment]
Oh if you could test on the soon-to-be-released 1.2.1 that would be appreciated:
https://app.circleci.com/pipelines/github/diasurgical/devilutionX/4365/workflows/6a8e6f07-c515-4d1f-aba1-68fd58a7930f

**Comment by Chance4us** [comment]
How can I download this code?
![circleci](https://user-images.githubusercontent.com/45902449/114321967-08915b00-9b1e-11eb-98fd-a12c07c6227a.png)

**Comment by Chance4us** [comment]
Do I have to download this?
![cerrcleci2](https://user-images.githubusercontent.com/45902449/114322137-daf8e180-9b1e-11eb-87d4-007e990856cb.png)

**Comment by Chance4us** [comment]
I downloaded this and tested.
Showing the following version:
![version](https://user-images.githubusercontent.com/45902449/114322389-41323400-9b20-11eb-9ff3-39918ba84243.png)
I can confirm that the hidden door opens normally.
