### ISSUE TITLE
Crash on selecting quest in quests window

### ISSUE THREAD

**Issue by AAS** [diasurgical/devilutionX#1463]
**Important information**
Windows 10 x64 / DevilutionX version 1.2.0 i386 / official build from github release page

**Describe**
Crash on selecting quest in quests window

**To Reproduce**
1. Press 'q' button to open quests window
2. Click on any quest (or press enter)
3. See crash

**Expected behavior**
Game should not crash.

**Additional context**
Savegame: [single_1.zip](https://github.com/diasurgical/devilutionX/files/6290557/single_1.zip)

**Comment by StephenCWills** [comment]
FYI, I did a bit of playtesting and found that this crash consistently occurs for Gharbad the Weak after loading a saved game. If you make it to Gharbad without ever having loaded a save, the crash does not occur.
