### ISSUE TITLE
Cursor loops back on right-to-left when there is no buffer padding

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#1466]
https://user-images.githubusercontent.com/216339/114287569-bee23b00-9a5f-11eb-9304-4925cda3bb2f.mov

**Comment by AJenbo** [comment]
It's one row lower down, this is because the render sees the buffer as liner and doesn't stop rendering when it hits the logical edge.

**Comment by glebm** [comment]
Did you mean to close this?

**Comment by AJenbo** [comment]
Yeah, it's not a bug but expected behavior. This is true for anything that renders past the edge of the screen and why there is a 64px padding on either side.

**Comment by glebm** [comment]
The cursor rendering is handled differently, I was surprised to see this issue there

**Comment by AJenbo** [comment]
Happens a lot with flame wave even with the buffer border if you walk in the right direction.

**Comment by AJenbo** [comment]
I see this as a poor design decision more then a bug, not sure what the intent was with the issue?

**Comment by glebm** [comment]
I thought `render.cpp` was the only piece of code at this point that needed the padding.

Cursor rendering is not done using `render.cpp`, so I did not expect this issue there.
Especially since it's not that obvious why that happens from looking at the code -- it looks like it's supposed to be clipping the width

**Comment by AJenbo** [comment]
All the cel/cl2 blitting needs left and right padding

**Comment by AJenbo** [comment]
There is only handeling for top and bottom when blitting

**Comment by glebm** [comment]
Ah right, I totally forgot about this issue with `CelBlit*` stuff

**Comment by AJenbo** [comment]
I try to too some times :)
