### ISSUE TITLE
Crash after modifying diablo.ini on v1.2.0

### ISSUE THREAD

**Issue by VenKamikaze** [diasurgical/devilutionX#1472]
**Important information**
ArchLinux kernel 5.11.11
Cinnamon DE
Devilutionx 1.2.0 built myself from source tag/1.2.0

**Describe**
Changed diablo.ini to enable windowed mode, and doubled width/height, turned on experience bar and enemy health bar.

I can run devilutionx and it brings up the menu, but when I now attempt to start a game in normal mode with my character, it brings up a red box with no text, and clicking the button then bombs out the game.

Prior to changing diablo.ini I was able to start a game.

**To Reproduce**
1. Modify diablo.ini to attached version.
2. Start devilutionx 1.2.0
3. Attempt to start a new single player game as any character, new or old.

**Expected behavior**
Game begins in town.

**Screenshots**
![image](https://user-images.githubusercontent.com/2378905/114289215-3bebcf80-9ab5-11eb-8821-6d96773eaf63.png)

**Additional context**
[diablo.ini.txt](https://github.com/diasurgical/devilutionX/files/6291025/diablo.ini.txt)
Note: diablo.ini already had the duplicated entries for width/height etc, so I changed both.

**Console output:**
There is a line mentioning a font that couldn't be found which might be related to the lack of text in the red box? I've included the console output as I think it could be relevant...

INFO: SFileOpenFile: Not found: ui_art\hero0.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\hero1.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\hero2.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\hero3.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\hero4.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\hero5.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\hero6.pcx
INFO: Failed to load image meta
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_KEYMAPCHANGED 0
INFO: SFileOpenFile: Not found: data\healthbox.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: data\health.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: data\resistance.pcx
INFO: Failed to load image meta
INFO: TTF_OpenFont: Couldn't open /usr/share/fonts/truetype/CharisSILB.ttf

**Comment by AJenbo** [comment]
You did not copy the font, so it can't draw the text:
` INFO: TTF_OpenFont: Couldn't open /usr/share/fonts/truetype/CharisSILB.ttf` <----

**Comment by qndel** [comment]
Well, give it the font + delete config and let devilutionx regenerate it, `diablo.ini already had the duplicated entries for width/height` - this doesn't sound right

**Comment by VenKamikaze** [comment]
Wow you guys are really quick. Sorry for the lacking report. I did see a reference to devilutionx.mpq in a readme at some point, but I wasn't sure where I should have got that from.

I've just done a find and found it in the source tree. Apologies. I'll sort that out.

find . -name '*mpq'
./devilutionX/Packaging/resources/devilutionx.mpq

**Comment by qndel** [comment]
why not download a release to get all the files?

**Comment by VenKamikaze** [comment]
I've copied devilutionx.mpq plus the font to the game folder. It now works fine. I'll close the report, and I might file a PR for updating the readme?

**Comment by AJenbo** [comment]
Don't forget the font or you won't know what the next error says :)

**Comment by AJenbo** [comment]
I guess we would make a note in the build instruction that people should go over the install instructions also?

**Comment by VenKamikaze** [comment]
Install instructions... I didn't notice that either :man_facepalming: 

Yeah OK a reference to that from the build instructions might help people like me that don't pay enough attention!

**Comment by julealgon** [comment]
> I've copied devilutionx.mpq plus the font to the game folder. It now works fine. I'll close the report, and I might file a PR for updating the readme?

A PR that ensures these files are also copied in development mode would be great. I think the MPQ is not copied from the resources folder to the build folder when building the project today so you have to do that manually.

**Comment by AJenbo** [comment]
it is on linux

**Comment by VenKamikaze** [comment]
I hesitate to say now, incase I've missed something else however devilutionx.mpq was _not_ copied to my build directory by CMake.

CharisSILB.ttf was, and I've just duplicated what was done for it and am filing a PR for it.
