### ISSUE TITLE
Precompiled Linux binary not working

### ISSUE THREAD

**Issue by Dartomic** [diasurgical/devilutionX#148]
I am running Fedora. I don't understand exactly what the issue is, I just know that I can not run it. When I compile it myself, the only difference in the output, is that there are some memory leaks in the binary my machine produces, and the binary does not attempt to use files from ajenbo's home directory. Here is the output of the precompiled binary for linux:
```
DUMMY: SetUnhandledExceptionFilter @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:507
DUMMY: GetSystemInfo @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:573
DUMMY: CreateFileMappingA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:665
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:431
DUMMY: LoadCursorA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:446
DUMMY: LoadImageA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:440
DUMMY: RegisterClassExA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:399
libGL error: MESA-LOADER: failed to open i965 (search paths /usr/lib/dri)
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  89
  Current serial number in output stream:  88
```

**Comment by AJenbo** [comment]
Do you have a working OpenGL driver on your system?
Did you try turning upscaling off?

It's not trying to load files from my home folder, just saying where the code was compiled from.

Yours show memory leaks because it's a debug build.

**Comment by Dartomic** [comment]
I believe so. I think I see a lot of libraries for various implementations of openGL in "/usr/lib/". But I do not see a directory, or file, labeled "dri" within the lib directory. I apologize  for the level of ignorance I have for linux drivers. Would it be helpful if I posted the output of the ls command?

**Comment by Dartomic** [comment]
Also, I did not try to turn up-scaling off. I apologize, but I do not know how to do that yet. I am now looking into how to manipulate upscaling.

Regardless; the Windows version of the precompiled binary DOES work on Fedora, through Steam's Proton implementation of Wine. But I am more interested in getting the Linux version to work, so that I can play with the code to make the game do different things.

**Comment by AJenbo** [comment]
What do you get here:
`glxinfo | grep version`
Also test with:
`glxgears`

You can disabled upscalling in the diablo.ini (probably located here ~/.local/share/diasurgical/devilution/diablo.ini) by setting it to 0.

**Comment by Dartomic** [comment]
[herbert@localhost ~]$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.8
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 19.0.8
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 



glxgears showed the gears turning, this is the console output:

[herbert@localhost ~]$ glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
301 frames in 5.0 seconds = 60.126 FPS
301 frames in 5.0 seconds = 60.001 FPS


This directory exists: "~/.local/share/diasurgical/devilution", but there is nothing in it.

**Comment by AJenbo** [comment]
Is it possible that you don't have 32bit Mesa installed? That would explain why your native (64bit) tools work, but diablo doesn't.

**Comment by Dartomic** [comment]
I did not have that installed. But now I do. Now a graphical window appears with a label which prints: "Unable to create main window"

**Comment by Dartomic** [comment]
Right after this line of the console input:

"DUMMY: RegisterClassExA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:399"

A statement prints:
"INFO: SDL_Init: Could not initialize UDEV"

**Comment by Dartomic** [comment]
This is the new console output:

DUMMY: SetUnhandledExceptionFilter @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:507
DUMMY: GetSystemInfo @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:573
DUMMY: CreateFileMappingA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:665
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:431
DUMMY: LoadCursorA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:446
DUMMY: LoadImageA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:440
DUMMY: RegisterClassExA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:399
INFO: SDL_Init: Could not initialize UDEV
DUMMY: SDrawDestroy @ /home/ajenbo/devilutionX/SourceX/storm/storm.cpp:688
DUMMY: SNetDestroy @ /home/ajenbo/devilutionX/SourceX/storm/storm_net.cpp:61
DUMMY: UiDestroy @ /home/ajenbo/devilutionX/SourceX/DiabloUI/diabloui.cpp:128
DUMMY: SVidDestroy @ /home/ajenbo/devilutionX/SourceX/storm/storm.cpp:430
DUMMY: SDrawDestroy @ /home/ajenbo/devilutionX/SourceX/storm/storm.cpp:688
DUMMY: StormDestroy @ /home/ajenbo/devilutionX/SourceX/storm/storm.cpp:693

**Comment by l0ophole** [comment]
I'm getting the same error message in a pop-up window that says "ERROR: Unable to create main window." I'm running Archlinux and I compiled the source code instead of using a prebuilt binary.

**Comment by l0ophole** [comment]
DUMMY: SetUnhandledExceptionFilter @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:513
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:437
DUMMY: LoadCursorA @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:452
DUMMY: LoadImageA @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:446
DUMMY: RegisterClassExA @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:405
INFO: Could not initialize UDEV
DUMMY: SDrawDestroy @ /home/loophole/diablo/devilutionX/SourceX/storm/storm.cpp:733
DUMMY: SNetDestroy @ /home/loophole/diablo/devilutionX/SourceX/storm/storm_net.cpp:61
DUMMY: SetUnhandledExceptionFilter @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:513
DUMMY: __debugbreak @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:801
DUMMY: SetUnhandledExceptionFilter @ /home/loophole/diablo/devilutionX/SourceX/miniwin/misc.cpp:513
DUMMY: UiDestroy @ /home/loophole/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:133                              DUMMY: SVidDestroy @ /home/loophole/diablo/devilutionX/SourceX/storm/storm.cpp:432                                  DUMMY: SDrawDestroy @ /home/loophole/diablo/devilutionX/SourceX/storm/storm.cpp:733
DUMMY: StormDestroy @ /home/loophole/diablo/devilutionX/SourceX/storm/storm.cpp:738                                 =================================================================                                                       ==8707==ERROR: LeakSanitizer: detected memory leaks                                                                     Direct leak of 8 byte(s) in 1 object(s) allocated from:                                                                     #0 0xf79ece75 in __interceptor_realloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:105                    #1 0xf2dfc350  (/usr/lib/../lib32/libX11.so.6+0x4a350)                                                              Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0xf79ecc3d in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:95                      #1 0xf2dfc31f  (/usr/lib/../lib32/libX11.so.6+0x4a31f)                                                              Indirect leak of 8 byte(s) in 2 object(s) allocated from:
    #0 0xf79eca35 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:86                      #1 0xf2dfcc7e  (/usr/lib/../lib32/libX11.so.6+0x4ac7e)                                                              SUMMARY: AddressSanitizer: 112 byte(s) leaked in 5 allocation(s).

**Comment by AJenbo** [comment]
Looks like it could be related to libudev1, make sure you have a 32bit version of it installed.

**Comment by l0ophole** [comment]
I got it working. I needed to install lib32-libgudev in the multilib repository. I'm on Archlinux, so it's probably named slightly different for you, OP.

**Comment by l0ophole** [comment]
Dartomic, I think the package for your system would be libgudev.i686 if you want to try to install that and see if it fixes it for you as well.

**Comment by AJenbo** [comment]
Closing this issue as it should be fixed by #53

**Comment by Dartomic** [comment]
l0ophole, I forgot to reply. It looked like it almost worked after I installed that, but I just get a black screen. The Windows version runs really well for me, and I saw AJenbo and other developers discussing the addition of controller support in the future, so I'm not worried about it. I just wanted to write in support for the XBox One controller.

**Comment by AJenbo** [comment]
We are using SDL so the Xbox One controller should be supported, along with a slew of other controllers. But for things to work best (I noticed that you have some audio stuttering and video flickering with Wine/Proton) I would recommend that you figure out whats missing on your system, the good news is that we will probably have 64bit support by the next release so there would be more installed by default.
