### ISSUE TITLE
In a Hellfire Multiplayer Game, Killing Diablo Can Make the Demon Crypts Crash the Game

### ISSUE THREAD

**Issue by BartyMae** [diasurgical/devilutionX#1487]
**Important information**
Windows 10 LTSC 2019 x64, DevilutionX (v1.2.0-5F5DCIAF) with Hellfire, self-compiled, multiplayer.

**Description**
If you slay Diablo in a multiplayer game, you are usually immediately kicked out of the game...but only if you're in the final area where Diablo is slain. If, for example, the host is still in town when Diablo is slain, the server continues on and the slaying player can simply rejoin to continue the game. While playing with a friend, we found that then attempting to enter the Demon Crypts would crash our games. I found a process that reproduced the issue twice more.

**Reproduce**
1. Have a character host the game, have another join the game.
2. With the non-host character, slay Diablo while the host stays in town.
3. Rejoin the game with non-host character.
4. Enter the Demon Crypts directly with the non-host character, don't bother with the Hive*.
5. Your game should crash.

*Actually, I'm not sure if this is a bug or not, but you can always enter the Demon Crypts without using the Cathedral Map by simply walking over where the entrance should be and it'll enter you in.

**Expected behavior**
The game should not crash - the Demon Crypts should load normally.

**Comment by julealgon** [comment]
Does it only crash in DevilutionX and not in vanilla?

**Comment by AJenbo** [comment]
I guess the proper fix is to end the game even if you are not on the proper level.

**Comment by BartyMae** [comment]
> 
> 
> Does it only crash in DevilutionX and not in vanilla?

There is no multiplayer in vanilla Hellfire, so I cannot test.

**Comment by julealgon** [comment]
@BartyMae 
> There is no multiplayer in vanilla Hellfire, so I cannot test.

https://www.reddit.com/r/Diablo/comments/3gdr8q/is_it_possible_to_play_diablo_1_hellfire/cxpry1r/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by BartyMae** [comment]
> 
> 
> @BartyMae
> 
> > There is no multiplayer in vanilla Hellfire, so I cannot test.
> 
> https://www.reddit.com/r/Diablo/comments/3gdr8q/is_it_possible_to_play_diablo_1_hellfire/cxpry1r/?utm_source=reddit&utm_medium=web2x&context=3

Thanks, figured it out and got it enabled. Using the same process I outlined in the original post, the game did not crash - I was able to proceed to the Crypts and even kill Na-Krul without issue.

**Comment by qndel** [comment]
Could you test with 1.2.1?

**Comment by BartyMae** [comment]
I did, and there was no crash. Did it twice to be sure. Hooray?!

**Comment by qndel** [comment]
Fixed by 1.2.1 then ;)

**Comment by AJenbo** [comment]
on a side note i cant find a version 5F5DCIAF, which I'm pretty sure is invalid since it has an "I" in it. Where did you get it from?

**Comment by BartyMae** [comment]
Not entirely sure - someone else is building them for me. Also, it's difficult to read, that I might actually be a 1.

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/pull/1345/commits/5f5dc1af28274c47dc6f76e8e289166b6b0d0ca9
@AJenbo all these are my highlighting

**Comment by AJenbo** [comment]
I did try with a 1 instead of I, but yeah it's from @qndel so that explains why the version isn't present in our history :)
