### ISSUE TITLE
[diablo] Cross loading savegame doesn't always work

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1488]
Cross loading a hellfire savegame doesn't work when you are in the hive.

In this case you will get the following message.
![message](https://user-images.githubusercontent.com/45902449/114321348-bac72380-9b1a-11eb-99ba-6b0334d015fa.png)

Since there is no hive in diablo, the logic is correct.
Could it be possible to make the character to appear in the town?

**Comment by AJenbo** [comment]
I looked at teleporting the player to town but it was way more complicated than it was worth, so no you have to exit the hive or crypt before doing the conversion. It's trivial enough to conclude what the issue might be as well IMO that most users should be able to figure it out in the few cases it does even happen.

**Comment by Chance4us** [comment]
That is understandable. Thank you.

**Comment by julealgon** [comment]
I wonder if it would make sense to encourage people to start a new game with their characters when going from Diablo to Hellfire and vice-versa to avoid these crazy issues. Perhaps a mention in the readme somewhere.

**Comment by AJenbo** [comment]
I wouldn't be opposed to removing the option in a later version and only allow new game. Our ability to load individual parts has become relatively robust (total corruption of game state aside)
