### ISSUE TITLE
Onlygood var not initilized

### ISSUE THREAD

**Issue by RetroGamer02** [diasurgical/devilutionX#1490]
Was attacking an enemy and crashed with this. Its a Windows x64 build v1.2.0-3c28D37 on Windows 10.

![onlygood var Error](https://user-images.githubusercontent.com/70994866/114329968-ae3cce00-9b0e-11eb-96de-0eb9901c8245.png)

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6293301/single_0.zip)

**Comment by julealgon** [comment]
Issue appears to be here:
https://github.com/diasurgical/devilutionX/blob/3c28d637a9ff5544fda93c664459ffcb70ee44a9/Source/items.cpp#L2787

![image](https://user-images.githubusercontent.com/461579/114331057-8dc64100-9b19-11eb-808e-1a877cc40d38.png)

**Comment by julealgon** [comment]
![image](https://user-images.githubusercontent.com/461579/114331521-95d2b080-9b1a-11eb-823f-43742a49841b.png)

This is related to the mushroom quest when attempting to drop the brain.

**Comment by AJenbo** [comment]
this isent strictly a crash but the msvc debugger showing a warning, which it does quite brutally.

**Comment by glebm** [comment]
Let's cherry-pick for 1.2.1?

**Comment by AJenbo** [comment]
It has no effect outside of running MSVC debug builds.
