### ISSUE TITLE
Solid Tile Where Player Spawns Levels 13 Through 16

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#1492]
**Important information**
Windows 10 / Release 1.2.0 / Downloaded Release

**Describe**
Sometimes on floors 13 through 16 you will be spawned on a solid tile when coming down stairs from either town or the previous floor. This is a vanilla bug related to dungeon generation.

**To Reproduce**
1. Have a seed where a solid tile is placed at a spawn point from one of the stairs on a floor from 13 through 16.
2. Enter that floor from the impacted staircase.

**Expected behavior**
The game should not put a solid tile where it will spawn a player.

**Screenshots**
![spawn on can't walk tile](https://user-images.githubusercontent.com/28605404/114340377-6ffed900-9b25-11eb-973f-5b8475788fd0.png)

**Additional context**
Here is a save file where the player is on floor 14 and spawned on the solid tile.
[single_1.zip](https://github.com/diasurgical/devilutionX/files/6293871/single_1.zip)

**Comment by AJenbo** [comment]
hm adding a map fix that clear the tiles around the spawn seams like an ok way to deal with that.
kinda reminds me od d2 where diablo would spawn spikes under you.

**Comment by mewmew** [comment]
> hm adding a map fix that clear the tiles around the spawn seams like an ok way to deal with that.

I think another solution may be to search around the spawn points for an ok placement tile, and then place the player there.

**Comment by AJenbo** [comment]
yeah, just have to see how much the multiplayer placment code continues to search, if it's more then 4 then we can just make it aware of solids

**Comment by galaxyhaxz** [comment]
You guessed it, they fixed this on the PSX port. While you could fix the stairs to not spawn next to solid tiles, this wouldn't take into account if monsters flooded the stairs and you went back down. Searching outward is the best way to go, and they added a function in 1.07 for resurrect to handle this job. First it searches in the ideal 8 positions, if no dice, it searches radial outward of 50 tiles.

To fix this bug and any other "spawn on solid tile", simple change this code in `InitPlayer`:
```c
if (pnum == myplr) {
	if ((!FirstTime) || (currlevel != 0)) {
		plr[pnum]._px = ViewX;
		plr[pnum]._py = ViewY;
	}
	plr[pnum]._ptargx = plr[pnum]._px;
	plr[pnum]._ptargy = plr[pnum]._py;
} else {
	plr[pnum]._ptargx = plr[pnum]._px;
	plr[pnum]._ptargy = plr[pnum]._py;
	for (int i = 0; i < sizeof(plrxoff2)/sizeof(plrxoff2[0]) - 1; i++) {
		if (PosOkPlayer(
			pnum,
			plr[pnum]._px + plrxoff2[i],
			plr[pnum]._py + plryoff2[i]
		)) break;
	}
	plr[pnum]._px += plrxoff2[i];
	plr[pnum]._py += plryoff2[i];
}
```
To this: (call PlacePlayer from spells.cpp)
```c
if (pnum == myplr) {
	if ((!FirstTime) || (currlevel != 0)) {
		plr[pnum]._px = ViewX;
		plr[pnum]._py = ViewY;
		PlacePlayer(pnum);
	}
} else {
	PlacePlayer(pnum);
}
```

**Comment by galaxyhaxz** [comment]
This is Frodo. Frodo no longer landed butt first onto a long spike. Frodo is happy.
![Capture](https://user-images.githubusercontent.com/65138215/114405976-c5aaa400-9b6c-11eb-81b4-cb6e9f8b917c.PNG)

**Comment by NiteKat** [comment]
Just wondering, would you consider it a bug to be spawned on the same tile a monster occupies? Because that will happen as well, I mostly see it in caves and hell if you crowd the stairs with enemies. It'd probably be fixed by the same methods, pretty sure PosOkPlayer checks for monsters.

**Comment by AJenbo** [comment]
yes it's a bug :D but the same fix should work for both problems.

**Comment by galaxyhaxz** [comment]
yep because if you spawn on a monster the monster can hit you but you can't hit it. PosOkPlayer checks for a couple of things:
- Solid tiles
- Other players
- Monsters
- Objects

**Comment by NiteKat** [comment]
Infinite loop of triggers if you set up the right conditions and don't check for that! :D
