### ISSUE TITLE
Gharbad quest progresses after moving 1 tile away instead full screen like in vanilla

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#1493]
**Important information**
Tested on https://github.com/diasurgical/devilutionX/commit/135f5e03c796f7184b52abf1abfba5ac0d525379

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6295259/single_0.zip)
Found by @Chance4us 

**Describe**
You can trigger next Gharbad's speech by moving 1 tile away

**To Reproduce**
Talk to Gharbad
Move 1 tile away
Talk again

**Expected behavior**
If you don't move away till Gharbad disappears on screen, the quest shouldn't progress

**Comment by qndel** [comment]
Caused by 
```cpp
	//Check if we reached new tile
	if (plr[pnum]._pVar8 >= anim_len) {

		//Update the player's tile position
		switch (variant) {
		case PM_WALK:
			dPlayer[plr[pnum]._px][plr[pnum]._py] = 0;
			if (leveltype != DTYPE_TOWN && pnum == myplr)
				DoUnVision(plr[pnum]._px, plr[pnum]._py, plr[pnum]._pLightRad); // fix for incorrect vision updating
				```
DoUnVision in walking

**Comment by Chance4us** [comment]
@qndel Thank you much for creating the report.

**Comment by qndel** [comment]
It's a bug I literally have no clue how to fix :D It's caused by my vision updating but without it we get situations like this 
![image](https://user-images.githubusercontent.com/14297035/114375140-ab7cc000-9b84-11eb-8980-7c43bd42178c.png)

**Comment by AJenbo** [comment]
i guess you could end in a situation where he never progresses :)

**Comment by Chance4us** [comment]
@ qndel maybe it would be enough to calculate just a greater radius of tiles.

**Comment by AJenbo** [comment]
the problem was that originally the old vision was unloaded after having moved and so it didn't actually unload the correct area. We fixed it by unloading it at the start of the frame, but since the AI processes between that and the walking it would look like the player had no vision to the AI.
