### ISSUE TITLE
PPA launchpad build error

### ISSUE THREAD

**Issue by muzena** [diasurgical/devilutionX#1494]
@AJenbo 
There is in launchpad git ppa [build error](https://launchpadlibrarian.net/532977826/buildlog_ubuntu-focal-amd64.devilutionx_1.2.0+git2012-a80aa286-202104111103~ubuntu20.04.1_BUILDING.txt.gz)

Error with pthread:
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed

**Comment by StephenCWills** [comment]
I believe this is the real error.

```
CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):
  error: could not find git for clone of libzt-populate
```

**Comment by muzena** [comment]
@StephenCWills 
`buildlog_ubuntu-focal-amd64.devilutionx_1.2.0+git2012-a80aa286-202104111103~ubuntu20.04

It's old version of devulutionx
launchpad can't downloading/git cloning outside launchpad
There exist somewhere bug report for this problem, they won't enable it due to security issues, something like that, or maybe allow downloads in future.

**Comment by AJenbo** [comment]
@muzena since most of these issues aren't with DevilutionX, but the config in launchpad. Could you maybe use the discussion section or chat?
