### ISSUE TITLE
Can't drop gold to ground

### ISSUE THREAD

**Issue by johndoe71rus** [diasurgical/devilutionX#1496]
**Important information**
Linux/ DevilutionX 1.2-2f3e0cb1 / build

**Describe**
Probably this is vanilla bug.
Can't drop gold to ground. But can take from ground and then drop one stack.

**To Reproduce**
1. load save 
2. try to drop gold from inv

[drop_gold_single_0.zip](https://github.com/diasurgical/devilutionX/files/6296354/drop_gold_single_0.zip)

**Comment by qndel** [comment]
You've hit the 127 item limit
