### ISSUE TITLE
Negative AC vs hellfire

### ISSUE THREAD

**Issue by pionere** [diasurgical/devilutionX#1497]
The AC of items with negative values are turned into a high positive AC when dropped on the ground.

The reason is that the value is stored in a BYTE field instead of an int.

Steps to reproduce:
Start a multiplayer(!) game.
Find an item with negative AC (Gnarled Root, The Celestial Star).
Drop to the ground.
Pick it up.
Now the item will have a high positive AC till the game is not restarted.

**Comment by AJenbo** [comment]
Thanks for reporting, this is now fixed in 1.2.1 https://github.com/diasurgical/devilutionX/pull/1485/commits/1ff91b3acacfb01bc4ed8df148546ca769752182
