### ISSUE TITLE
Garbage graphics at screen top when zoomed at 1280x960

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#1498]
**Describe**
Broken graphics near top border

**To Reproduce**
Throw a lot of gold or other stuff in town, walk up/down, watch top border

![paddinggobrrr](https://user-images.githubusercontent.com/14297035/114424528-80ac5f00-9bb8-11eb-8f71-43dbc02e4adc.gif)

**Comment by AJenbo** [comment]
Can't replicate it, what resolution is this? Post your ini plz

**Comment by qndel** [comment]
`
[diablo.ini.txt](https://github.com/diasurgical/devilutionX/files/6298116/diablo.ini.txt)
[Diablo] 
Intro=0
[Hellfire] 
Intro=0
SItem=
[Audio] 
Sound Volume=-1400
Music Volume=-1600
Walking Sound=1
Auto Equip Sound=0
[Graphics] 
Width=1280
Height=960
Fullscreen=0
Upscale=1
Fit to Screen=0
Scaling Quality=2
Integer Scaling=0
Vertical Sync=1
Blended Transparency=1
Gamma Correction=100
Color Cycling=1
FPS Limiter=1
[Game] 
Speed=50
Run in Town=0
Grab Input=0
Theo Quest=0
Cow Quest=0
Friendly Fire=1
Test Bard=0
Test Barbarian=0
Experience Bar=1
Enemy Health Bar=1
Auto Gold Pickup=1
Adria Refills Mana=0
Auto Equip Weapons=1
Auto Equip Armor=0
Auto Equip Helms=0
Auto Equip Shields=0
Auto Equip Jewelry=0
Randomize Quests=1
Show Monster Type=0
Alt Highlight Items=1
[Network] 
Bind Address=0.0.0.0
Port=6112
Previous Host=
[NetMsg] 
F9=I need help! Come Here!
F10=Follow me.
F11=Here's something for you.
F12=Now you DIE!
[Controller] 
Mapping=
Swap Shoulder Button Mode=0
Dpad Hotkeys=0
deadzone=0.07
`

**Comment by qndel** [comment]
@AJenbo no idea how I haven't noticed this earlier but I think this only happens while zoomed in? Did you manage to reproduce without zoom?

**Comment by glebm** [comment]
Minimal repro save, just press Z

[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/6321715/single_1.hsv.zip)

**Comment by glebm** [comment]
Looks like the game isn't rendering enough tiles in this case

**Comment by glebm** [comment]
This seems to fix the issue but I don't understand why:

https://github.com/glebm/devilutionX/commit/9f39738dd38915bc39c9535d0cf489aea141a047

Perhaps it helps someone else come up with a better fix or better explain this one

**Comment by glebm** [comment]
The fix above is not the correct fix, because it doesn't fix 1280x640

**Comment by ThomasChr** [comment]
@glebm Do you have it fixed? Shouldn't we have a PR for this if it's fixed?

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/129597660-af6c89e6-a8c7-43ba-ab47-f4056b49497c.png)
It's not fixed

**Comment by ikonomov** [comment]
It only happens when zoomed in at exactly 1280x960.  As a hopefully temporary solution, I have found that setting the size to the next closes whole numbers Width=1284 & Height=963 doesn't cause the issue.  It would be nice to have this fixed though.  Playing at this resolution and zooming in is truly a great experience and likely a common UI improvement that many people will want to have.
