### ISSUE TITLE
Bug introduced in d6ec6395e0b7c398db36e78597831d745cc9f144

### ISSUE THREAD

**Issue by KB3HNS** [diasurgical/devilutionX#1505]
## Overview:
Issue prevents the "Fungal Tome" quest from being able to be completed if the game is restored from a save after finding the mushroom.  Calling up the quest log causes a segmentation fault.

## Environment:
Code built from head@a85b03ec72405e1c68e6e36806c1ff2db42f64fa
OS: Raspberry PI OS Linux 5.10.17-v7l+ 32-bit Feb 22
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

## Summary 
*NB:  For this I refer to the files and line numbers as they were in the aforementioned commit hash*:
I was able to do some debug traces through the code and discovered that the examining the int stored in `quests[Q_MUSHROOM]._qmsg` at *towners.cpp:1006* was a negative number (-126).  The correct value should be 130 as per *enums.h:1423*.  Digging further, this negative number was coming when loading from the save file at *loadsave.cpp:128* `pQuest->_qmsg = Sint32(file->nextLE<Sint8>());`.  -126 is the expected value if truncating 130 as a signed 8-bit value.
Looking at the enum and usage within context, the value stored at this offset is being truncated.  The Enumeration has a range of -1 to 337.  Reverting this line back to `Uint8` resolves this issue, however overflow/truncation will still occur for other values -1,255..337.

**Comment by qndel** [comment]
Fixed in 1.2.1

**Comment by AJenbo** [comment]
Fix was here: https://github.com/diasurgical/devilutionX/commit/f062032e19fd5211b057d823af50fcd61192a232
