### ISSUE TITLE
Level Reroll Bug Reproducible 

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#1506]
**Important information**
Windows 10 / 1.2.0 / Release Copy

**Describe**
Attached save file was actually created using Vanilla 1.09, but when loaded with DevilutionX 1.2.0 (Vanilla not Hellfire), you can also get the level to reroll. Floor 5 rerolls on this save if you follow the steps below.

**To Reproduce**
1. Load the save, you will start on correct floor 5.
2. Go to floor 6.
5. Go back to floor 5, it is now rerolled.

**Expected behavior**
Level 5 should always load it's original layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/28605404/114486558-1f968280-9bdc-11eb-8fd1-935fe5b621a3.png)

**Additional context**
Screenshot is of my AI playing vanilla when it ran into this bug, you can see from the ASCII output the level of what is being seen and what the AI remembers does not make sense, and there are torches in the wall. In addition, the only way to get level 5 back to normal, that I have found, is to close the game, open it back up, then load the save. Going to floor 4 doesn't fix it, floor 6 doesn't fix it, saving and loading on floor 5 or other floors doesn't fix it. Only thing I didn't try was repeating the steps to produce the situation a second time.

Save file: 
[single_2.zip](https://github.com/diasurgical/devilutionX/files/6300806/single_2.zip)

**Comment by AJenbo** [comment]
Cool, was just talking about catacombs rerolling with SoundChaser :)

**Comment by NiteKat** [comment]
I just edited the issue. The steps to reproduce are simpler, just go from 5 to 6 then back to 5. No need for the bone chamber.

**Comment by Chance4us** [comment]
I think that just an additional variable needs to store that the level has already been rolled out.

**Comment by Chance4us** [comment]
@AJenbo , @qndel I consider this to be a critical and game-breaking bug.
So I would like to see if we can fix this annoying issue.
Do you have any idea in which lines of code this could be?

**Comment by AJenbo** [comment]
While pretty bad this is not new so it's not considered a release blocker. Afaik the reason it happens is that the quest status is updated and the level generation is affected by the quest status. The solution is to check if the quest is in an appropriate state before advancing it.

**Comment by qndel** [comment]
Love how the guy that claims he found it is still crying all over the internet :D I hope hes dumb enough to try and sue us or call the police, it would be a cherry on top haha

**Comment by Chance4us** [comment]
> While pretty bad this is not new so it's not considered a release blocker. Afaik the reason it happens is that the quest status is updated and the level generation is affected by the quest status. The solution is to check if the quest is in an appropriate state before advancing it.

I can think of something can have to do with that.
I eliminated all monsters in level 13, but didn't speak to Lachdanan.
I just wanted to test whether the "Golden Elixir" is in level 14 anyway.
So I eliminated all monsters also in level 14 and found no "Golden Elixir".
Only then did I speak to Lachdanan, picked up the potion at a random location and then came back.
Could it have anything to do with it?

**Comment by AJenbo** [comment]
Search for `_qactive = ` and put a debug message before them, that should let you know when it's happens.

```cpp
if (quest._qactive == QUEST_NOTAVAIL) {
   SDL_Log("%s :: %d", __FILE__, __LINE__);
}
quest._qactive = ...
```

**Comment by NiteKat** [comment]
Is this related to quest activity? I thought this particular reroll was due to the stair placement for the Chamber of Bone on floor 6, and the 5th floor generation being impacted by that because it's blocking where the 5th floor decided to put the stairs, since the floor generation for Catacombs depends on set piece placements that aren't cleared/initialized between floors?
