### ISSUE TITLE
tile and transparent 

### ISSUE THREAD

**Issue by johndoe71rus** [diasurgical/devilutionX#1510]
**Important information**
Linux x64 / DevilutionX version 1.2.1 / download 

**Describe**
Some wrong tile at lightning

**To Reproduce**
1. load save

**Screenshots**
![Снимок экрана_2021-04-13_13-31-06](https://user-images.githubusercontent.com/7861172/114545865-27e6d000-9c65-11eb-9505-7f40b8b9c284.png)
[_light_single_0.zip](https://github.com/diasurgical/devilutionX/files/6303373/_light_single_0.zip)

**Comment by AJenbo** [comment]
Sorry but there is probably not much we can do about this as it stems from how the assets where done for the game. It is actually part of the tile in the wall and looks more like two tiles if rendered by it self. This shows up on walls with bends in them as well as some end walls amongst others.
