### ISSUE TITLE
Map game functions/keys to extra mouse buttons

### ISSUE THREAD

**Issue by mgtroyas** [diasurgical/devilutionX#1513]
Many modern gaming mouse have extra buttons that could be assigned to game functions for quick access.

**Comment by AJenbo** [comment]
This should be resolved by https://github.com/diasurgical/devilutionX/pull/1368

**Comment by obligaron** [comment]
I can use the additional buttons of my mouse with the keymapper.
It also works with the settingsmenu. 🙂
