### ISSUE TITLE
Frequent crashes in the crypt

### ISSUE THREAD

**Issue by radek-sprta** [diasurgical/devilutionX#1515]
[crypt_crash.zip](https://github.com/diasurgical/devilutionX/files/6305286/crypt_crash.zip)

**Important information**
Version: DevilutionX 1.2.1 AppImage from the release page
OS: Ubuntu 20.10

**Describe**
The game randomly crashes while in the crypt with the following output `“./devilutionx-linux-x86_64.appi…” terminated by signal SIGSEGV (Address boundary error)`. Sometimes immediately upon loading, sometimes while interacting with the dungeon or just walking.

**To Reproduce**
I could not distill a specific set of steps to reproduce the issue. However, just trying to play the game from the attached save should cause a crash within 30 seconds.

**Expected behavior**
Crypt is playable without issues.

**Comment by qndel** [comment]
Start a new game in 1.2.1 as 1.2.0 had a bug that might've corrupted the save till you do a new game. Reopen if it happens again.

**Comment by AJenbo** [comment]
But that bug only really affected Windows. I'll try loading this in a debug build and see if it gives some more details.

**Comment by Marleene** [comment]
Same issue here. 

Version:1.2.1
Os: Windows 10 Pro
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6332363/single_0.zip)

**Comment by AJenbo** [comment]
Looks like OBJ_STORYCANDLE around the book is not loaded for some reason
```cpp
void SyncObjectAnim(int o)
{
    object_graphic_id index = AllObjects[object[o]._otype].ofindex;
    int i = 0;
    while (ObjFileList[i] != index) {
        i++;
    }
```

**Comment by radek-sprta** [comment]
> Start a new game in 1.2.1 as 1.2.0 had a bug that might've corrupted the dungeon till you do a new game. Reopen if it happens again.

In a new game, the crypt works fine so far.
