### ISSUE TITLE
Picking up Torn Note 3 with full inventory completes Reconstructed Note, but leaves Torn Note 3 on dungeon floor

### ISSUE THREAD

**Issue by thebigMuh** [diasurgical/devilutionX#1519]
**Important information**
Win 10, latest DevilutionX, built myself

**Describe**
Having a full inventory and picking up Torn Note 3 will result in the completed Reconstructed Note while leaving Torn Note 3 on the floor. You can still click on it afterwards, but nothing happens.

**To Reproduce**
- Have a completely full inventory, with Torn Note 1 and Torn Note 2 in it
- Click on Torn Note 3 to pick it up
- The Torn Note 3 item will remain on the dungeon floor, but the Reconstructed Note will also be completed in the inventory (leaving you with 1 free slot, since Torn Note 1 and 2 are removed)
 
**Expected behavior**
Torn Note 3 should disappear from the floor and the Reconstructed Note should appear in your inventory. This is what happens with the released version 1.2.1, btw.

**Additional context**
Attached a save file. The Torn Note 3 is just south of my warrior on the dungeon floor (hidden behind a wall).
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6307305/single_0.zip)

**Comment by AJenbo** [comment]
do you know if this happens in vanilla?

**Comment by glebm** [comment]
@thebigMuh bisected this to:

* https://github.com/diasurgical/devilutionX/commits/da18b0f97b858ee2ed31e26b12e8b48eec497a20 bad
* https://github.com/diasurgical/devilutionX/commits/da7567f06e5f06b7c9b6219e3e418f6a19b62585 good

@julealgon can you have a look?

**Comment by julealgon** [comment]
PR opened with the fix.
