### ISSUE TITLE
Staff not losing durability when blocking

### ISSUE THREAD

**Issue by Psojed** [diasurgical/devilutionX#1525]
I started a Monk playthrough and I noticed that my Staff durability never goes down when blocking.

According to [Jarulf's Guide](http://www.bigd-online.com/JG/Body/JG3-7.html#3.7.1), only shields can lose durability when blocking, so it's probably an oversight from Hellfire developers. This is a Hellfire specific issue, since only the Monk class can block with staves (and unarmed).

**Comment by julealgon** [comment]
This seems like a bug. Should we mark it as such?
