### ISSUE TITLE
Ingame settings menu

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1561]
To help with managing the ever-growing list of game options we would like to provide an advanced options menu based on the Help/Shop interface.

Here is a basic mockup of what such a menu could look like:
![image](https://user-images.githubusercontent.com/204594/115096584-1a13a200-9f26-11eb-8f92-3605ea239846.png)

I have not thought of how to indicate that some options will only take effect in new games or by restarting the game, feel free to be creative or have a debate about it.

I'm thinking that this menu will be accessed from `menu` -> `options` -> `advanced` and will replace the "game speed" option.

**Comment by galaxyhaxz** [comment]
Great idea, some games that require restart will usually have text that comes up when changing an option and then when leaving the menu it recreates the window context. This works perfectly fine on desktops, but doubt it would work well on game consoles.

**Comment by AJenbo** [comment]
Recreating the window probably won't work for enabling all quests :)

**Comment by galaxyhaxz** [comment]
Options like those should be added to the UI when creating a game IMO. Just like selecting difficulty.

**Comment by AJenbo** [comment]
Unfortunately, the game creates UI isn't good for handling multiple options. Currently you have to mandatorily go over each of them one at a time before you are allowed to start the game. So for the first iteration, I think it's acceptable to have all options listed in this menu. Then later we can create a more flexible Create Game screen that supports multiple options on a single screen (proposals wellcome).

**Comment by galaxyhaxz** [comment]
I've had this implemented in my own UI for almost a year now ;P
![Untitled](https://user-images.githubusercontent.com/65138215/115097357-33e5c280-9eef-11eb-9fb6-efe943c63e49.png)

**Comment by Sircrashalot** [comment]
Nice. Will you also add the option for attacking with just one click? Although i loved to spam click back in the good old days... i am just too old for that now :D

**Comment by julealgon** [comment]
> Will you also add the option for attacking with just one click? Although i loved to spam click back in the good old days... i am just too old for that now :D

@Sircrashalot this is not the place to ask about settings themselves. This issue is to discuss how the existing settings are displayed in-game. If you want to discuss actual settings proposals, open another issue or start a discussion.

Having said that, specifically talking about "holding mouse button to attack constantly", it is already in development in some form, so the feature is definitely being considered.

**Comment by AJenbo** [comment]
An even better place is the chat https://discord.gg/YQKCAYQ
