### ISSUE TITLE
Black Mushroom Quest not Advancing

### ISSUE THREAD

**Issue by oGkspAz** [diasurgical/devilutionX#1573]
**Important information**
Windows 7 Ultimate SP1 / DevilutionX v1.2.0 (1.2.1 crashes my windows audio process because of a Razer Synapse Issue) / Downloaded 64bit

**Describe**
Despite being on the Black Mushroom quest and having the brain in my inventory, Pepin is unaware of this. Clicking "Black Mushroom" in the quest log for dialog also crashes the game.

**To Reproduce**
1. Load save
2. Check inventory for Brain
3. Click on Pepin and if nothing happens "Talk to Pepin"
4. Check Quest log for "Black Mushroom"
5. Click and it should crash.

**Expected behavior**
Quest should complete/advance

**Screenshots / Files**
[BlackMushroom.zip](https://github.com/diasurgical/devilutionX/files/6329640/BlackMushroom.zip)

**Comment by qndel** [comment]
Use 1.2.1

**Comment by oGkspAz** [comment]
Ah apologies missed this one:
* Quest panel crashing the game for some quests

I don't however see any reference to the Black Mushroom issue.

**Comment by qndel** [comment]
Because it's probably related to quest panel issue, I just tested on 1.2.1, pepin happily took the brain
