### ISSUE TITLE
Multiplayer desyncs related to player position

### ISSUE THREAD

**Issue by FluffyQuack** [diasurgical/devilutionX#1576]
Desync cause 1:
Video example: https://www.youtube.com/watch?v=wDXCDKLnpNY

When moving after attacking, the movement becomes different on other clients (the character eventually catches up to the correct position, but it is wrong for a few seconds). The above video is recorded using DevX v1.2.1, but I also tested this using the Diablo build from GOG and the behaviour is identical there.

The cause is this: When clicking to walk, the game calls MakePlrPath() which does pathfinding to figure out a good path for the player, and it sets the _ptarx and _ptary values to be where the player ends up at the end of the pathfinding. However, when you end an attack, the game calls StartStand() which calls FixPlayerLocation() which sets _ptarx and _ptary to be the same as the player position.

The local player keeps sending player position values (including _ptarx and _ptary) to other clients so other clients and update a desynced location, but since the _ptarx and _ptary values are wrong, it ends up asking other clients to move the player to the wrong location.

Here is one way to fix this desync: https://github.com/diasurgical/devilutionX/pull/1593

Desync cause 2:
Video example: https://www.youtube.com/watch?v=eO6Ictu0Rns

This happens if you cancel pathfinding with an attack (it doesn't happen every single time. I think it happens if you attack at a certain part of the movement). And if you make sure to move immediately after the attack (which I do in the above video), then the second client won't even see the attack happen.

I didn't look too deeply into this, but I think _ptarx and _ptary are related once again. I tried a brute force fix where I set _ptarx  and _ptary to the correct values immediately before sending a packet with an attack command, and that almost entirely fixed the issue (it would still happen, but only very rarely).

Desync cause 3:
If two or more players enter a dungeon at the same time, there's a chance they'll try to spawn in the same position, and thus be in different positions on each client.

**Comment by AJenbo** [comment]
I'm not sure, but this is probably one of the things that has a butterfly effect in the game.

Nice work making a good test case to make this a manageable issue to work on.

**Comment by FluffyQuack** [comment]
I tried to debug this a bit, and here's my progress:

- Player 1 clicks to move after attacking and MakePlrPath() ends up being called once (with the correct information).
- Player 2 get the packet from player 1 and calls MakePlrPath() once (with the correct information), but then it also keeps calling MakePlrPath() in multi_process_network_packets() and most of the time it's with the player's old position.
- I don't fully understand what's happening in multi_process_network_packets(). I could be wrong, but I think that function was made by the Diablo team as a brute force way to "fix" desyncs by continuously updating a player's position. But in this case, it somehow uses the wrong information and keeps trying to send the player back to the tile they moved from.

If I comment away the MakePlrPath() call from multi_process_network_packets() then the issue disappears (and I don't even see any side effects, though I only tested for a few minutes).

I'll see if I can fully understand the problem and find a proper fix.

**Comment by julealgon** [comment]
> I could be wrong, but I think that function was made by the Diablo team as a brute force way to "fix" desyncs by continuously updating a player's position. But in this case, it somehow uses the wrong information and keeps trying to send the player back to the tile they moved from.

I wonder if that could be related to the unreliability of UDP at the time. Can't we just _trust_ the initial message now and let the player follow whatever path was set since we are using TCP?

The only updates needed after setting the path initially would be when the path needs to change due to an obstacle for example, but that is taken care on the client side, no need to send a message for that. If the source player actively changes the path with another move command, only then another message is sent over the network.

**Comment by AJenbo** [comment]
> I wonder if that could be related to the unreliability of UDP at the time. Can't we just _trust_ the initial message now and let the player follow whatever path was set since we are using TCP?

We also speak TCP in 1.3.0-dev

**Comment by FluffyQuack** [comment]
Closing this since https://github.com/diasurgical/devilutionX/pull/1593 fixes almost everything written in the issue.

**Comment by AJenbo** [comment]
Feel free to create a new issue with any leftovers :)
