### ISSUE TITLE
Berserk light gets lost when reentering the level

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#1588]
**Describe**
Berserked monsters lose light when you reenter the level

**To Reproduce**
1. Cast berserk on a monster (it has light)
2. Reenter the level
3. The monster has no light
4. Verify that the monster is still berserked by making it attack another monster

**Expected behavior**
The monster should keep its light

**Comment by k-bar** [comment]
seems like kind of not original hellfire bug
