### ISSUE TITLE
XBRZ scale

### ISSUE THREAD

**Issue by ivan89el** [diasurgical/devilutionX#159]
Is it possible to implement? This looks much better than bilinear interpolation. https://sourceforge.net/projects/xbrz/

**Comment by AJenbo** [comment]
Yes, it should be possible, it looks like there are SDL bindings to it might even be reasonably easy.

I'm going to close this issue as we should keep talks about upscaling techniques to the existing issue:
https://github.com/diasurgical/devilutionX/issues/3
