### ISSUE TITLE
"Unable to open save file archive" when entering portal to town (Hellfire single-player)

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#1591]
On master Hellfire single-player, entering this portal back to town causes app_fatal (save attached) in `LoadLevel`:

https://github.com/diasurgical/devilutionX/blob/95946e3a7ce3d0e9b3d460cac6548fdd04d27d71/Source/loadsave.cpp#L2023

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6331761/single_0.zip)

**Comment by qndel** [comment]
Weird,
```cpp
void LoadLevel()
{
	char szName[MAX_PATH];
	GetPermLevelNames(szName);
	LoadHelper file(szName);
	//if (!file.isValid())
	//	app_fatal("Unable to open save file archive");
	```
	
after commenting it out my whole level morphs! And that's before entering the portal, so I'd say something is wrong with the save in general :D
![image](https://user-images.githubusercontent.com/14297035/115154042-2c522500-a079-11eb-8a60-e2d980091799.png)

**Comment by glebm** [comment]
There is a bug in the call order, it does seeks after closing the file:

```
INFO: Closing /home/gleb/.local/share/diasurgical/devilution/single_0.hsv
VERBOSE: seekp(0, std::ios::beg)
VERBOSE: write(data, 104)
VERBOSE: write(data, 32768)
VERBOSE: write(data, 32768)
```

**Comment by glebm** [comment]
Ah, no, nevermind, it's just how this is logged, these `seekp` and `write` calls are part of the closing process

**Comment by glebm** [comment]
The save was created by starting a new game and going to the dungeon level 2.
Then I found my first TP scroll, tried to go into the portal, and got this crash

**Comment by AJenbo** [comment]
By commenting that out you are basically loading garbage so don't know whats going on here at all.

**Comment by glebm** [comment]
While this save file is not salvagable, I'm guessing the issue was fixed by https://github.com/diasurgical/devilutionX/pull/1621
