### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#16]
Currently video playback isn't supported by devilutionX, the good news here is that we should be able to make use of (libsmacker)[https://sourceforge.net/projects/libsmacker/] for decoding the video streams. OpenApoc also makes similar use of libsmacker with SDL2 so this might be a good place to glean a possible way of implementing this.
https://github.com/OpenApoc/OpenApoc/blob/master/framework/video/smk.cpp

**Comment by VonKossa** [comment]
After the addition of libsmacker it fails to build for, halting on /stub/movie.cpp. With errors like:
/Stub/movie.cpp:49:52: error: cannot convert ‘unsigned int*’ to ‘long unsigned int*’ for argument ‘3’ to ‘char smk_info_all(smk, long unsigned int*, long unsigned int*, double*)’
   smk_info_all(smacker, NULL, &nFrames, &usPerFrame);
/Stub/movie.cpp:50:48: error: cannot convert ‘unsigned int*’ to ‘long unsigned int*’ for argument ‘2’ to ‘char smk_info_video(smk, long unsigned int*, long unsigned int*, unsigned char*)’
   smk_info_video(smacker, &width, &height, NULL);

**Comment by AJenbo** [comment]
Please try deleting the content of you build folder and do a fresh build with cmake

**Comment by VonKossa** [comment]
Already did. Same result.

**Comment by VonKossa** [comment]
Can it be because of missing dependencies or missing compile flag on libsdl2 or sdl2-mixer?

**Comment by AJenbo** [comment]
It worked on 32bit, but not on 64bit. It's fixed now so that it will work on both.

**Comment by VonKossa** [comment]
Yepp, now it works!
Thanks a lot. :)

**Comment by AJenbo** [comment]
Video playback has been implemented. There are still improvements that could be made:
- Switch to libsmackerdec for a more liberal license
- Fix audio stuttering by streaming to the music channel

**Comment by AJenbo** [comment]
Audio playback has now been corrected
