### ISSUE TITLE
Can't buy anything from Wirt 

### ISSUE THREAD

**Issue by danellos** [diasurgical/devilutionX#160]
It seems that I am not able to buy items from Wirt in the 0.4.0 build. Even when I do have enough gold in my inventory, I still get the error message "You do not have enough gold" instead of the expected confirmation message.

When I transferred my save file to the Retail game, it appears to behave correctly. I do get the confirmation message "Do we have a deal?" and am able to select "Yes" or "No" to confirm the transaction. 

Here is my save file for testing: 
[single_0.zip](https://github.com/diasurgical/devilutionX/files/3365947/single_0.zip)

Screenshots:
![scr1](https://user-images.githubusercontent.com/6340021/60772032-31b9c780-a0be-11e9-8091-20f36373d2ff.png)
![scr2](https://user-images.githubusercontent.com/6340021/60772033-32eaf480-a0be-11e9-8528-f38ecbeb8185.png)

**Comment by AJenbo** [comment]
This bug has been solved in master, you will either have to wait for 0.5.0 or build from master.
