### ISSUE TITLE
objects.cpp Shrines abnormality

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1608]
Is it intended that Magical shrine appear twice?
![shrines](https://user-images.githubusercontent.com/45902449/115209831-43872600-a0fe-11eb-9ffa-38f05654e6fd.png)

**Comment by qndel** [comment]
yes

**Comment by ChaosMarc** [comment]
Out of curiosity, why?

**Comment by julealgon** [comment]
Is this the "crimson" prefix situation again?

**Comment by AJenbo** [comment]
> Out of curiosity, why?

Maybe it's done to make it more likely to appear in levels.
