### ISSUE TITLE
Casting lvl 0 spell produces "not enough mana" sound

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#1610]
**Important information**
Vanilla bug

**Describe**
When you cast a lvl 0 spell (you can achieve these with shrines), the character will say "Not enough mana" which is a lie

**To Reproduce**
1. Get a lvl 0 spell
2. Cast it
3. "Not enough mana"

**Expected behavior**
I'd expect a different message like "No way", not "Not enough mana" which isn't true

Better sounds:
PS_MAGE17 (No way)
PS_MAGE18 (Not a chance)
PS_MAGE19 (I would never use this) (Perfection!)
PS_MAGE28 (I cannot cast that yet)
PS_MAGE29 (That did not do anything)
PS_MAGE33 (I do not want that)
PS_MAGE34 (I do not have a spell ready)
PS_MAGE36 (I cannot do that) (YES!)
PS_MAGE37 (No!)
PS_MAGE39 (That will not work)

Oh well, seems I messed the enums (means we need a redesign ...) but the text matters ;p

**Comment by AJenbo** [comment]
PS_MAGE28

**Comment by nickgavran** [comment]
I like PS_MAGE36 the best

**Comment by julealgon** [comment]
I'm also partial to "I cannot cast that yet".

**Comment by RicoLeNecro** [comment]
How about randomly selecting one of those answers that kind of make sense each time the player attempts it? (Kind of like with the sounds of the cows in town.)

**Comment by qndel** [comment]
Not worth it.

**Comment by RicoLeNecro** [comment]
Well if we really have to chose a single one, my vote goes to PS_MAGE34.

**Comment by malvarenga123** [comment]
+1 to PS_MAGE28

**Comment by julealgon** [comment]
> Well if we really have to chose a single one, my vote goes to PS_MAGE34.

@RicoLeNecro I think that would be misleading. "Having a spell ready" in the game is having something selected in the "Readied Spell" icon (that's the actual name of the icon). If you select something there, then it means you _have_ a spell ready. 

Now, being unable to cast your readied spell is something else entirely and should be handled with a different message.

**Comment by RicoLeNecro** [comment]
One could interpret a level 0 spell as never being in a ready state, but I get how someone might get confused by the character saying that.
