### ISSUE TITLE
crash - back to windows 10 x64

### ISSUE THREAD

**Issue by Hellman6969** [diasurgical/devilutionX#1618]
**Important information**
Operating system : windows 10 x64 v1909
DevilutionX version : 1.2.1
did you download a release : yes

**Describe**
I use devilutionX since today, i use a savegame made on official diablo 1.09 yesterday (i made a sorcerer lvl 1 to 15 thince some days ago).
I play maybe 5 min all seems to be OK, and when i'm walking to go to town, the game crash always at the same point. Just walking, i dont do anything else...

**To Reproduce**
- i made a savegame just near to the point where the game is crashing.
- load my savegame and walk to the right (i'm coming from left)
- the game crash after 1 ou 2 sec
- back to windows, no error message, everytime the same.

**Expected behavior**
Do you thing it's a bug from devilutionx or it's because i used my savegame from "official" diablo ? Because i played 5 min with killing, spells, etc. and it's worked fine. I hope it's a bug who can be solved...

[save.zip](https://github.com/diasurgical/devilutionX/files/6337900/save.zip)
thanks a lot ! (PS : sorry i'm not english fluent...)

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/issues/1614

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/issues/1515
