### ISSUE TITLE
Support for armbian/Retrorangepi

### ISSUE THREAD

**Issue by PaddleStroke** [diasurgical/devilutionX#163]
Hey guys,
Thanks for your hardwork!
I was wondering if there's a version for Armbian ? I seen there's an image for Raspberry pi/raspbian.

My plan is to try to set it up on RetroStone (which runs Retrorangepi).
Thanks!

**Comment by AJenbo** [comment]
Helo @PaddleStroke 
It looks like Armbian is a Debian Linux based OS for ARM devices. That should mean that it will be able to run the same image as the Raspberry Pi. The only requirement is that your system support hard float (ARMv7) and that you have SDL2 32bit installed on your system.

**Comment by AJenbo** [comment]
Closing this as it should already work
