### ISSUE TITLE
Changing volume in options reduces the effect of sound volume changing based on source distance

### ISSUE THREAD

**Issue by FluffyQuack** [diasurgical/devilutionX#1632]
All sound effects change their volume based on the distance to the player. This is easy to test in multiplayer by having another player walk past the local client. The closer the player is, the louder the footsteps.

However, if you reduce the volume slider in options, this effect is reduced. If you change sound volume to the lowest setting where sound is still audible, everything will be at the same volume no matter how far away the sound source is.

I tested this in both original Diablo and DevilutionX 1.2.0, and the behaviour is the same in both.

I think the bug is caused by `static int CapVolume(int volume)` in sound.cpp

**Comment by FluffyQuack** [comment]
Here are videos showcasing the problem.

Max ingame volume: https://www.youtube.com/watch?v=rYuxCazj9KU
Near-minumum volume: https://www.youtube.com/watch?v=7j4TA0ZGblw

I should note that the warrior keeps moving constantly during those two videos. When you stop hearing footsteps, that's not because the warrior stopped moving, it's because he's out of range to be heard.

I'd say this is 3 different issues:
- Volume slider should act as a multiple, not a flat modifier.
- At a certain distance, the panning calculation becomes wonky and you can hear the footsteps on both channels even though the warrior is far left
- The volume doesn't smoothly fade into nothing. Rather you hear footsteps quite clearly at long distances, and then it suddenly changes to being silent.

**Comment by julealgon** [comment]
@soundchaser83 this could be related to the problem you described with sound panning/surround.

**Comment by julealgon** [comment]
> At a certain distance, the panning calculation becomes wonky and you can hear the footsteps on both channels even though the warrior is far left (this issue seems to be unique to DevilutionX. I could not reproduce this using the original game)

@FluffyQuack , could you isolate this in a separate issue? Otherwise it will be harder to track what is a vanilla bug and what isn't (with labels etc). Being able to properly categorize these issues can be helpful for when writing release notes, for example.
