### ISSUE TITLE
Opening the chests leads to disappear potions

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1642]
Opening the chests sometimes leads to disappear the potions from the belt.
I can only remember that in Hellfire the potions are sometimes manipulated when opening chests.

How to reproduce:
Unfortunately not simply reproducible as it happens randomly.
Simply open a randomly affected chest and many potions will disappear from the belt.
No sound effect is played as usually happens when opening trapped chests.

Expected behavior:
Potions should not disappear from belt when opening chests.

**Comment by johndoe71rus** [comment]
this is trap in chests

**Comment by Chance4us** [comment]
> this is trap in chests

It is normal that no sound effect is played for this trap?

**Comment by NikoVP** [comment]
There should be a burpy or breaking glass sound, if I remember correctly.

**Comment by AJenbo** [comment]
burp = drain mana
glass = remove potions

**Comment by NikoVP** [comment]
The break potions does not always remove them, but also lowers the grade full to small.

**Comment by Psojed** [comment]
Can confirm, this is a trap from Hellfire expansion. It plays the glass breaking sound, and works the same way in DevilutionX 1.2.1.
If you want to test this further, I recommend using a Rogue as she can see trapped chests.

**Comment by Chance4us** [comment]
Finally, I see that some participants sometimes like to do bashing without trying to understand the issue.
But to get ahead just try to open the box next to you and hear the sound.
Savegame:
[chest.zip](https://github.com/diasurgical/devilutionX/files/6447459/chest.zip)

**Comment by AJenbo** [comment]
Looks like this might be a vanilla bug that only happens if you only have potions in your belt.

**Comment by Chance4us** [comment]
Thanks a lot for fixing.
