### ISSUE TITLE
Anbernic 351v issue with d-pad and buttons

### ISSUE THREAD

**Issue by Gotcha007** [diasurgical/devilutionX#1653]
Hey guys, I'm having an issue with Diablo 1 port on Anbernic 351v. 
The D-pad and buttons and not doing much. I have to use the stick and the L1 button to move. I don't have that issue on the 351m. Am I missing something?

**Comment by AJenbo** [comment]
what release are you using?

**Comment by Gotcha007** [comment]
To be honest I'm not sure. I downloaded it from Anberports. How can I check that?

**Comment by AJenbo** [comment]
There is a version number in the main menu, but also this sounds like an unofficial port, and one where they did not map out the dpad, and so there isn't really anything we can do. Instead they should possibly look into up-streaming there port, untill then you will need to take it up with Anberports.

**Comment by AJenbo** [comment]
I took a quick look at there repo, for one thing they do not provide source for the port, but also it seams to be based on version 1.1.0 so a bit old at this point.

**Comment by Gotcha007** [comment]
I see, which version and platform should I use to work with RetroArena on the 351v?

**Comment by AJenbo** [comment]
Looks like the RG351v is a 64bit ARM CPU, are you looking to do a port?
