### ISSUE TITLE
Undead Crown does not heal player when using bow

### ISSUE THREAD

**Issue by PsychotropicDog** [diasurgical/devilutionX#1654]
version 1.2.1. Did not work in version 1.0.1
And before you ask I shot little bats and scavengers with a rogue. It will work with a sword.

**Comment by johndoe71rus** [comment]
as i remember Undead Crown work only with sword/axe. absolutely not work with magic.

**Comment by qndel** [comment]
Lifesteal never worked with ranged weapons

**Comment by Psojed** [comment]
This could be a nice gameplay enhancement.
With bows being unable to roll lifestealing modifiers, the only lifestealing source for Bows would be the Undead Crown and the Helm of Spirits unique.
