### ISSUE TITLE
Distant sound sources aren't panned correctly

### ISSUE THREAD

**Issue by FluffyQuack** [diasurgical/devilutionX#1657]
Example: https://www.youtube.com/watch?v=rYuxCazj9KU

When the warrior is far away, you can hear the sound is suddenly played on both channels rather than left.

I'm not sure why this happens. I tested it in original Diablo, and panning seems to work just fine there, so I think this issue is unique to DevilutionX.

**Comment by julealgon** [comment]
@soundchaser83 FYI
