### ISSUE TITLE
Crash on Quit Game when inside any dungeon level

### ISSUE THREAD

**Issue by Psojed** [diasurgical/devilutionX#1658]
**Important information**
Windows x64 / [latest master build](https://app.circleci.com/pipelines/github/diasurgical/devilutionX/4824/workflows/3d900a0a-1105-4393-937a-e37758790986/jobs/33518/artifacts)

**Issue**
1) Start a New Game using the included save:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6367745/single_0.zip)
2) Enter any dungeon (I tried with cathedral, catacombs and nest)
3) ESC -> Quit Game

Instead of quitting the game, I end on a black screen and I get a windows "app stopped working" dialogue with these details:

>  Název události problému:    APPCRASH
>  Název aplikace:    devilutionx.exe
>  Verze aplikace:    0.0.0.0
>  Časové razítko aplikace:    00000000
>  Název chybného modulu:    StackHash_3264
>  Verze chybného modulu:    6.1.7601.24291
>  Časové razítko chybného modulu:    5be7857f
>  Kód výjimky:    c0000374
>  Posun výjimky:    00000000000bf302
>  Verze operačního systému:    6.1.7601.2.1.0.768.3
>  ID národního prostředí:    1029
>  Další informace 1:    3264
>  Další informace 2:    32646d68bf2db89f1d7973d26440eed4
>  Další informace 3:    7e2e
>  Další informace 4:    7e2e4ce1505ded44360a43c05635a8e5

**Additional context**
I also crashed during the loading screen upon entering Catacombs for the first time after running this build, but I couldn't reproduce this crash afterwards.

- It's probably something character-specific, a newly created Warrior doesn't crash on quit while inside the cathedral.
- I'm using a monk save that I started in devilutionX 1.2.1 - Hellfire.
- The same save file doesn't crash on quit in dungeon in DeviluionX 1.2.1 Release.

**Comment by qndel** [comment]
I reproduced it faster - load save / enter hive / quit game
it's related to armor - game closes fine when I unequipped cow armor

**Comment by qndel** [comment]
doesn't happen anymore after reverting bugfix
```cpp
static DWORD GetPlrGFXSize(HeroClass c, const char *szCel)
{
	const char *a, *w;
	DWORD dwSize, dwMaxSize;
	HANDLE hsFile;
	char pszName[256];
	char Type[16];

	c = GetPlrGFXClass(c);
	dwMaxSize = 0;

	for (a = &ArmourChar[0]; *a; a++) {
		if (gbIsSpawn && a != &ArmourChar[0])
			break;
		for (w = &WepChar[0]; *w; w++) { // BUGFIX loads non-existing animagions; DT is only for N, BT is only for U, D & H (fixed)
			if (szCel[0] == 'D' && szCel[1] == 'T' && *w != 'N') {
				//continue; //Death has no weapon
			}
			if (szCel[0] == 'B' && szCel[1] == 'L' && (*w != 'U' && *w != 'D' && *w != 'H')) {
				//continue; //No block without weapon
			}
```

**Comment by qndel** [comment]
happens for bugfix + heavy armor + staff combo

**Comment by AJenbo** [comment]
What commit?
