### ISSUE TITLE
[enhancement] Make use of a more suitable color for the automap

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1659]
The problem is that, especially in the caves, the map is barely visible in the areas of the lava. 
Therefore I tried to choose a better color for the automap so that it fits to every level design.
The second goal was to achieve a less intrusive but more visible automap.
The color taste of different people is of course individual,
therefore the solution cannot be perfect and it is just intended to represent an another possibility.
The color index can be seen on the screenshot.

Some comparisons are given below.
![church1](https://user-images.githubusercontent.com/45902449/115926435-21d1ca00-a483-11eb-9de3-195b15bf20bc.png)
![church2](https://user-images.githubusercontent.com/45902449/115926451-26967e00-a483-11eb-8e62-3024ba273b28.png)
![catacombs1](https://user-images.githubusercontent.com/45902449/115926732-9d337b80-a483-11eb-8344-c867f84e7ad3.png)
![catacombs2](https://user-images.githubusercontent.com/45902449/115926747-a15f9900-a483-11eb-8f7b-91f4db766616.png)
![nest1](https://user-images.githubusercontent.com/45902449/115926871-d2d86480-a483-11eb-8c39-85ab24d9c10f.png)
![nest2](https://user-images.githubusercontent.com/45902449/115926880-d79d1880-a483-11eb-9c9d-ad698cd42943.png)
![hell1](https://user-images.githubusercontent.com/45902449/115926998-0915e400-a484-11eb-90ea-2f96e07c3612.png)
![hell2](https://user-images.githubusercontent.com/45902449/115927006-0d420180-a484-11eb-820a-633a279c2ad7.png)
![crypt1](https://user-images.githubusercontent.com/45902449/115927084-2ea2ed80-a484-11eb-8c68-a2882e3fc60a.png)
![crypt2](https://user-images.githubusercontent.com/45902449/115927105-32cf0b00-a484-11eb-8b2c-b082ef146832.png)
![caves1](https://user-images.githubusercontent.com/45902449/115927243-6ca01180-a484-11eb-933c-5d574d44c89b.png)
![caves2](https://user-images.githubusercontent.com/45902449/115927250-70cc2f00-a484-11eb-93e4-bb1b3a8d3659.png)
![caves3](https://user-images.githubusercontent.com/45902449/115927266-7590e300-a484-11eb-915f-1143dcb40368.png)
![caves4](https://user-images.githubusercontent.com/45902449/115927283-79bd0080-a484-11eb-9c1e-44426ad2a4c6.png)

**Comment by qndel** [comment]
> The problem is that, especially in the caves, the map is barely visible in the areas of the lava.

Still can't see your color over the lava xD

**Comment by Chance4us** [comment]
> > The problem is that, especially in the caves, the map is barely visible in the areas of the lava.
> 
> Still can't see your color over the lava xD

If you zoom in it is more visible-

**Comment by NikoVP** [comment]
Maybe use some kind of blend mode if available, or make the map lines render black when the terrain brightness levels are a ove certain threshold.

**Comment by Chance4us** [comment]
> Maybe use some kind of blend mode if available, or make the map lines render black when the terrain brightness levels are above certain threshold.

Only one color can be specified in the current program code.

**Comment by galaxyhaxz** [comment]
White or bright yellow are about your only options to make lines visible over the lava, short of using inverted colors to the current pixel which breaks the original design.
![Untitled](https://user-images.githubusercontent.com/65138215/115934046-c4735400-a455-11eb-8da1-8db5f3e7aa17.png)

**Comment by AJenbo** [comment]
Sure is visible...  maybe once we moved it to the side so it takes up less screen space...

**Comment by galaxyhaxz** [comment]
A mini automap would be a good idea, could have it in the top right corner of the screen.

**Comment by galaxyhaxz** [comment]
Another option is green. Too bad Diablo is prasinophobic.
![Untitled](https://user-images.githubusercontent.com/65138215/115936754-b58fa000-a45b-11eb-93b7-6cc9c41a1e39.png)

**Comment by julealgon** [comment]
Can anyone try the "render with shadow" approach using the original color and grab a screenshot? The black shadow might not be too intrusive in general layouts and would stand out in the lava I think. That could be a great approach.

**Comment by galaxyhaxz** [comment]
Original with shadow:
![Untitled](https://user-images.githubusercontent.com/65138215/115937660-0f916500-a45e-11eb-8897-c386546fcb2f.png)
White with shadow:
![Udntitled](https://user-images.githubusercontent.com/65138215/115937677-1324ec00-a45e-11eb-8df0-c15c4311e8f1.png)

**Comment by Trihedraf** [comment]
I like the original with shadow. Makes visible but not overly distracting.

**Comment by Chance4us** [comment]
Original with shadow looks good. White looks visible but too intrusive.
Could you try the blue (color index 183) with shadow?
Could you tell me where is the program code for the shadow?

**Comment by galaxyhaxz** [comment]
```c
void SetPixel(const CelOutputBuffer &out, int sx, int sy, BYTE col)
{
	if (!out.in_bounds(sx, sy))
		return;

	*out.at(sx, sy+1) = 0; // add black pixel beneath whatever is drawn
	*out.at(sx, sy) = col;
}
```

**Comment by Chance4us** [comment]
We can argue about the color of the automap.
In any case, we should optionally introduce the line of code for the shadow suggested by the the girl of the galaxy.
It leads definitely to significantly increased visibility without being intrusive.
![shadow1](https://user-images.githubusercontent.com/45902449/115956747-dfe66980-a4fe-11eb-8ac1-46cec3b9cc76.png)
![shadow2](https://user-images.githubusercontent.com/45902449/115956749-e4128700-a4fe-11eb-82bb-ad889487bc6e.png)
![shadow3](https://user-images.githubusercontent.com/45902449/115956755-e96fd180-a4fe-11eb-9eb0-b443a23c6671.png)
![shadow4](https://user-images.githubusercontent.com/45902449/115956760-ec6ac200-a4fe-11eb-875d-8a63ecb438e2.png)

**Comment by Chance4us** [comment]
It seems that unconsciously I almost hit the color of the magical items.
![screen00](https://user-images.githubusercontent.com/45902449/115960294-d36b0c80-a510-11eb-9560-ef1ad8192269.png)

**Comment by malvarenga123** [comment]
Shadow does make it visible in all colors. Subtitles always had this kind of problems.

![image](https://user-images.githubusercontent.com/61893389/115973782-040d6f00-a52e-11eb-9d6e-7b8e969e44de.png)

**Comment by Lywzc** [comment]
> Shadow does make it visible in all colors. Subtitles always had this kind of problems.
> 
> ![image](https://user-images.githubusercontent.com/61893389/115973782-040d6f00-a52e-11eb-9d6e-7b8e969e44de.png)

But, the spectrum does not include all colors. Pink, white, black and many others are not on it so your image is not evidential.
