### ISSUE TITLE
items dropped in town not showing up for other players

### ISSUE THREAD

**Issue by Berry2460** [diasurgical/devilutionX#1662]
**Important information**
Windows 10 running DevilutionX 1.2.1 release

**Describe**
when a player drops something in town, other players that are not in town currently cannot see it when they come to town.

**To Reproduce**
1. have one player in a dungeon and one in town
2. drop an item in town
3. other player comes back from dungeon and cannot see item

**Expected behavior**
both players should be able to see the item

**Comment by julealgon** [comment]
Can you please specify how the item is dropped exactly? I believe there are multiple drop flows in the game so it's important to know the exact steps you are taking.

**Comment by Berry2460** [comment]
In one instance I had dropped a book of healing for another player and they made a portal to town and couldnt see it on the ground, so I picked it up and dropped it again and they could see it.

**Comment by AJenbo** [comment]
So you dropped it by dragging it out of the inventory with the mouse and clicking on the ground, while the other player was not in town?

**Comment by Berry2460** [comment]
yep

**Comment by qndel** [comment]
Works fine for me, both on 1.2.1 and on master
