### ISSUE TITLE
low level characters trying to join nightmare/hell games causes massive lag

### ISSUE THREAD

**Issue by Berry2460** [diasurgical/devilutionX#1663]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

Windows 10 running DevilutionX 1.2.1 release

**Describe**
when a player that is under-leveled tries to join a nightmare/hell game and gets the error message on screen it freezes the game for as long as the error message is open.

**To Reproduce**
1. create a nightmare game with a level 20+ character
2. have a new character try and join
3. the new character will get the error message that they are too low leveled
4. the game will freeze for all other players until that player closes the error

**Expected behavior**
it shouldnt lag/freeze when failing to join a nightmare/hell game

**Comment by BartyMae** [comment]
Have seen this occur as well - even lead to a player already in the game being dropped because of it.

**Comment by AJenbo** [comment]
Fixed https://github.com/diasurgical/devilutionX/commit/6c4bad0af19a98c598480902e31d10fbab25e7d8
