### ISSUE TITLE
[vanilla] Overlord's Helm - Not always possible to wear

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1677]
Playing for over 20 years and just discovered something new again.
Regarding to http://www.lurkerlounge.com/forums/printthread.php?tid=3861
Not possible to wear this helm, although the requirements seem to have been met.
Requirements:
![requirements](https://user-images.githubusercontent.com/45902449/115963449-9b1efa80-a51f-11eb-843a-73eec4258804.png)
In game:
![overlords1](https://user-images.githubusercontent.com/45902449/115963465-ac680700-a51f-11eb-996a-2d57513a2b69.png)
![overlords2](https://user-images.githubusercontent.com/45902449/115963469-b25de800-a51f-11eb-83bb-8ec5e5b05e7e.png)
Savegame:
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/6370013/single_1.hsv.zip)

The fact that the magic goes below 0 makes the helmet non-wearable.
It is unclear whether something similar can be experienced with other items.

**Comment by qndel** [comment]
it's clear, the game doesn't allow stats to go below 0

**Comment by Chance4us** [comment]
It feels a little weird.
