### ISSUE TITLE
Doppelganger's affix causes desync

### ISSUE THREAD

**Issue by Droolguy** [diasurgical/devilutionX#1682]
**Important information**
Operating system Win10
 DevilutionX version 1.2.1
 did you download a release or did you compile yourself? Download

**Describe**
When fighting with this character file in multiplayer it seems to be extremely easy to cause desync. Even in localloop as the host I have seen killed NPC's ressurrect themselves after death to be killed a second time.

**To Reproduce**
Just play the character normally, easier to reproduce fighting large amounts of melee mobs, was able to desync almost the entire group of mobs around Leoric (Nightmare). I saw them all dead, host saw them almost all alive still.

**Expected behavior**
None, this is not a straight up replicatable bug, happens when it wants but is massively disproportionate compared to other characters I have.

**Screenshots**
N/A

**Additional context**
No idea which character file is the one for the character in question so I have dropped them all in here, character name is "Ubar", barbarian.

**Comment by Droolguy** [comment]
Files will not attach for some reason.
I get a notification that blinks "[Uploading... " and then dissapears leaving a text line break.

**Comment by StephenCWills** [comment]
Try putting them in a zip file? GitHub only supports certain file types.

**Comment by Droolguy** [comment]
https://drive.google.com/drive/folders/1vKc0hnT_42p7pDv4miTKwUfERkfyRNcW?usp=sharing

Threw them in a G drive.

**Comment by qndel** [comment]
[multi_3.zip](https://github.com/diasurgical/devilutionX/files/6370899/multi_3.zip)

**Comment by qndel** [comment]
"No idea which character file is the one for the character in question so I have dropped them all in here, character name is "Ubar", barbarian." seriously?

**Comment by StephenCWills** [comment]
Looks like it's multi_1.hsv.

**Comment by Droolguy** [comment]
Well, it's listed 1-4 without character names, and notepad returns gobbledygook so how am I supposed to know which one it is? If you launch the program. I suppose I can go one by one and pull the character files out and re launch the program over and over until I find it.

I figured you had ways of reading character files without the runaround.

**Comment by StephenCWills** [comment]
I can't speak for anyone else, but I just moved them in one at a time.

**Comment by qndel** [comment]
Doing exactly what the person opening the issue should've done 🙄

**Comment by Droolguy** [comment]
That's what I would have done, but I figured the dev had a way to read character files straight without the swapping.

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/115975217-2a99cd00-a563-11eb-9eb9-464fcda36c73.png)
aaand here's the cause

**Comment by StephenCWills** [comment]
Referencing #1147
> Doppelganger's: Cloning effect disabled in MP games due to sync issues and crashes

**Comment by julealgon** [comment]
One way to easily tell which file it is is to look at the latest modification date after saving and exiting the game: the most recently touched file is the one.

**Comment by AJenbo** [comment]
I have a feeling we might have fixed this, would some one we willing to test the latest beta :)
(Windows build: https://github.com/diasurgical/devilutionX/suites/3369358438/artifacts/79315974 )
