### ISSUE TITLE
No walls, only door generating for catacombs library room (same save as #1672)

### ISSUE THREAD

**Issue by Taohn** [diasurgical/devilutionX#1685]
**Important information**
Windows 10 Pro 64 / DevilutionX version 1.2.1 / downloaded release

**Describe**
Going further down the hall in same game from issue #1672 reveals library room with no walls. Goatmen archers inside were able to see and attack character (and vice versa). Door works normally.

**To Reproduce**
1. Load [single_1.zip](https://github.com/diasurgical/devilutionX/files/6371183/single_1.zip)
2. Proceed to lower right corner of screen (east?)
3. See error?

**Screenshots**
![no walls](https://user-images.githubusercontent.com/83104526/115979488-1f758a00-a5c1-11eb-8c15-25b5b3a572e9.png)
![walls](https://user-images.githubusercontent.com/83104526/115979497-2b614c00-a5c1-11eb-9fcf-1416a4568989.png)

**Additional context**
Game originally started in GOG Hellfire, where room appears as normal.
[GOG single_1.zip](https://github.com/diasurgical/devilutionX/files/6371185/GOG.single_1.zip)

**Comment by galaxyhaxz** [comment]
I tested this seed in both vanilla and vanilla hellfire and the bug does not occur, so it's an issue specific to DevilutionX and theme room generation.

**Comment by AJenbo** [comment]
Fixed, probably via https://github.com/diasurgical/devilutionX/commit/64d1e110aff4edf17d155234f5cc9bb2298847d8
