### ISSUE TITLE
Transparent room

### ISSUE THREAD

**Issue by Taohn** [diasurgical/devilutionX#1690]
**Important information**
Windows 10 Pro 64 / DevilutionX version 1.2.1 / downloaded release

**Describe**
Can see contents of room (monsters, barrels) in cathedral despite no line of sight.

**To Reproduce**
1. Load [single_2.zip](https://github.com/diasurgical/devilutionX/files/6371623/single_2.zip)

**Screenshots**
![transparent wall](https://user-images.githubusercontent.com/83104526/115987742-46e44b00-a5f1-11eb-84be-18fed1726fd4.png)

**Comment by qndel** [comment]
I'm pretty sure that's a vanilla issue

**Comment by galaxyhaxz** [comment]
Start the game in debug mode with the vision flag enabled, it will draw a yellow tile over all tiles that are in the players "vision" radius. Pretty sure the vision collision of the corner has incorrect flags which passes through the wall.
