### ISSUE TITLE
Items changing on pickup in multiplayer

### ISSUE THREAD

**Issue by kenvieira** [diasurgical/devilutionX#171]
I have seen a couple of issues where multiplayer games are not fully sync'd.  

In one situation I purchased a magical cap for a player and dropped it for them to pick it up, when they picked it up it changed to a non-magical item.  They then dropped it and I picked it up and it was now stuck as non-magical.

Another situation on my game there was one type of shrine seen, but the other play had a different shrine on screen.

Yet another instance I found a book of town portal but the game would not let me pick it up, so another player grabbed it and moved it to another location and then dropped it, but now the book was a book of inferno.

Now these issues were seen in a 3 person TCP game,  My character and the other I mentioned above were clients to the master character.  So seemed to be some issue with sync'ing between 2 client characters.

**Comment by AJenbo** [comment]
That's for the bug report. Some extra info that would help us try to replicate this:

Where all players using the same release? Where any of them self compiled?
If so where all or some of them 64bit builds?
What OSs where used?

**Comment by kenvieira** [comment]
Sure.. sorry for got to give those details.

All Diablo MPQ files are based on current GOG diablo image.. 1.09

All devilutionX files were binary downloads from github so not compiled.

My computer is running MacOS, the 2nd computer used was Windows based.
(interesting I didn't think to make that connection)

The server system was MacOS based.  Both MacOS are using same pre-compiled
devilutionX image.

**Comment by kenvieira** [comment]
Forgot to mention one more thing..  all DevilutionX files were downloaded
within last week.. so most current version to this date..

**Comment by ThomasChr** [comment]
I think I remember those bugs from the original diablo. So I‘m not sure if they are "new"...

**Comment by kenvieira** [comment]
Update..  so with more play time over the past weekend the issue was seen
again.  It does seem to be tied to windows vs Mac client.  What I saw was
that the Mac client (host) might see a book drop showing charge bolt, but
the windows client will show Telekinesis..  But then they can't pick it
up..  Then the mac client picks it up and drops it and the windows client
can now get it and it is set back to charge bolt.

We also saw a room with enemies  are cleared out on the Mac clients, but
windows still shows active enemies but can't shoot or hit them.  Those are
some of the sync issues I've seen and it generally falls between mac and
windows clients.

Since the original game did not have a Mac client this might be some new
issue seen due to the OS differences.  Perhaps this might be seen between
Linux and other OS's as well.

**Comment by AJenbo** [comment]
Actually, the original game did have a Mac client :)

I expect that it won't be too long before we have a new release, a lot has been fixed between 0.4.0 and now, so I'm hoping this will solve the issues you are seeing, but multiplayer is one of the main things that need testing before we are ready to release 0.5.0.

**Comment by kenvieira** [comment]
well keep me in mind if you would like some testing done..  I am a test
engineer in profession (network equipment testing but mindset is still
same) and do had 2 different client hardwares we play on to give interop
coverage.  At time I even can have a max 4 user game going so stress and
playability under different conditions is also possible.

**Comment by AJenbo** [comment]
@kenvieira would you be able to test the latest code to see if this is solved before we do a 0.5.0 release. Also feel free to test on native 64bit.

**Comment by kenvieira** [comment]
Hi Anders,

Sure I can give the new code a few test runs.  Is there a place I can
download the windows and Mac compiled versions of this code?

Ken

**Comment by AJenbo** [comment]
You can always download the latest windows, Linux and Nintendo switch builds from CircleCi builds (you need to be logged in via Github). Here is the latest for windows https://1127-143324737-gh.circle-artifacts.com/0/devilutionx_x86.exe

**Comment by AJenbo** [comment]
Closing this as there has been no feedback or confirmations for months
