### ISSUE TITLE
Commit causes crash when crypt loading

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1742]
affected commit : ad8f342db0767b18c198f781d25a25a4b5b3cd66

How to reproduce:
1. Go directly to the crypt using the attached savegame.
2. Become sad

[crypt.zip](https://github.com/diasurgical/devilutionX/files/6391546/crypt.zip)

**Comment by AJenbo** [comment]
Dulicate https://github.com/diasurgical/devilutionX/issues/1515
