### ISSUE TITLE
Option DISABLE_LTO "ON" causes crash when loading the crypt

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1746]
The option DISABLE_LTO "ON" causes crash when loading the crypt since commit e7ae8ddd045aec4aa7021a0e23cc91e5b738ca12

How to reproduce:
1. git checkout e7ae8ddd045aec4aa7021a0e23cc91e5b738ca12
2. Edit CMakeLists.txt and set the following setting:
option(DISABLE_LTO "Disable link-time optimization (by default enabled in release mode)" ON)
3. Compile
4. Load the game attached
[crash.zip](https://github.com/diasurgical/devilutionX/files/6394254/crash.zip)
5. Go to the crypt and see the crash when loading

**Comment by AJenbo** [comment]
You have a bad sate, disabeling makes the situation less likely to cause a crash, but it isn't really related.

Duplicate https://github.com/diasurgical/devilutionX/issues/1515

**Comment by Chance4us** [comment]
In my case, the opposite happens. If LTO is off, then there is a crash.
I am also not on Windows like the other user, but on Linux. Could it also be a compiler bug?
Could you check if the crash also happens on your OS?

**Comment by AJenbo** [comment]
no, you have a bad state. Changing compiler settings changes what is randomly affected by the bad state.

I am also on Linux. See the linked issue.

**Comment by Chance4us** [comment]
> no, you have a bad state.

Do you mean a corrupted savegame state?

**Comment by AJenbo** [comment]
No, the game state. If you save it will also be your save game. It's a bug in the original Hellfire that causes the game to become unstable, but what happens depends on memory layout, maybe nothing happens, maybe the game crashes, or maybe your mana turns into healing.

**Comment by Chance4us** [comment]
Can the problem be identified and resolved in the long term?

**Comment by AJenbo** [comment]
Of cause, but duplicate issues do not help. We have already solved 100s of this type of problem. I thnk there is already a PR that fixes this one as well.
