### ISSUE TITLE
Provide a way to skip outro sequence

### ISSUE THREAD

**Issue by flxs** [diasurgical/devilutionX#175]
Currently the outro sequence that play after killing Diablo isn't skippable. In the original game it was possible to achieve that by Alt-Tab-ing away from and back to Diablo while the sequence was running; that doesn't seem to work with DevilutionX, so some other means of doing that would be nice to have (it gets very annoying after the n-th hell/hell run).

**Comment by AJenbo** [comment]
Since it was a bug in the original this won't be changed before we release 1.00, but I agree all moves should be skippable once we hit 1.00+.

**Comment by sskras** [comment]
If the original game has a mechanism that _skips the outro on loosing focus_ from the main rendering window, then dX should have a way to trigger that too, IMO. 

It might be that this (catching the moment focus is lost) is done and used by Bink/Smacker renderers.

**Comment by AJenbo** [comment]
DevilutionX doesn't aim to have all the same bugs as Diablo, that is the aim of Devilution.

**Comment by sskras** [comment]
Why do you consider this as a bug?  For me as a user it's a feature (albeit not very polished one).

**Comment by AJenbo** [comment]
Because it clearly wasn't intentional.

**Comment by galaxyhaxz** [comment]
as a temporary fix, you can set the second flag in `play_movie` to always be true, so you can skip the movie.

**Comment by AJenbo** [comment]
I think for 1.1.0 we will have it so that ESC always skips movies. The reason that they aren't skippable is probably that the player might be clicking just as the movie starts and miss the in-game video.

**Comment by galaxyhaxz** [comment]
Diablo 2 allows you to skip all videos by pressing any key or clicking...

**Comment by AJenbo** [comment]
It also has a menu for replaying any cinematic that you unlocked.

**Comment by galaxyhaxz** [comment]
It also has five unique acts instead of one, plus 7 character classes.

**Comment by qndel** [comment]
It also has a final boss that isn't diablo.

**Comment by galaxyhaxz** [comment]
It also has a place where you can farm cows for steaks.

**Comment by flxs** [comment]
> I think for 1.1.0 we will have it so that ESC always skips movies. The reason that they aren't skippable is probably that the player might be clicking just as the movie starts and miss the in-game video. But ESC is not likely to be something that they would be pressing during game play.

That would be a superb solution 👍

**Comment by AJenbo** [comment]
So I figured out why this happened in the original:
https://github.com/diasurgical/devilutionX/blob/master/Source/movie.cpp#L30
`gbActive` becomes `false` when the application isn't in focus, so by minimizing you can always skip the movie. From what I can tell this was done here and in several other places so make the game use as little CPU as possible when minimized, but probably it just has skipped the rendering of the video and not interrupted it.
