### ISSUE TITLE
GitHub - Code Style (HTTP 404)

### ISSUE THREAD

**Issue by mpanneton** [diasurgical/devilutionX#1759]
**Important information**

**Describe**
When I click the link .clang-format (red rectangle) in the GitHub Code Style page it returns a HTTP 404 error.

**To Reproduce**
1. Go to https://github.com/diasurgical/devilutionX/wiki/Code-Style
2. Click on the link .clang-format: https://github.com/diasurgical/devilutionX/blob/master/.clang-format
3. The browser display a HTTP 404 page.

**Expected behavior**
Download a file to be import in your IDE or text editor or display that file in your Web browser.

**Screenshots**
![Screenshot_2021-04-29_10-31-40](https://user-images.githubusercontent.com/36534844/116573149-8dc88e00-a8da-11eb-87c3-143490b01053.png)

![Screenshot_2021-04-29_10-20-09](https://user-images.githubusercontent.com/36534844/116573299-ac2e8980-a8da-11eb-9e76-2112df65fc4a.png)

**Additional context**

**Comment by AJenbo** [comment]
The file was moved to https://github.com/diasurgical/devilutionX/blob/master/Source/.clang-format, your IDE should autodetect the file.
