### ISSUE TITLE
Crashes on startup - RG350 running OpenDingux beta

### ISSUE THREAD

**Issue by nicosensei** [diasurgical/devilutionX#1760]
**Important information**
RG350 running latest OpenDingux beta firmware

DevilutionX versions tested: 1.2.1, 1.2.0, 1.1.0

_diabdat.mpq_ file copied to _/media/data/local/home/.local/share/diasurgical/devilutionx_

**Describe**
App crashes on launch. Could not find any log file.

**Comment by glebm** [comment]
None of these releases support OpenDingux Beta. It will only be supported in the next release (and support for non-beta will be dropped).

In the meantime, here is a build from the current master (most likely has bugs).

[devilutionx-rg350.opk.zip](https://github.com/diasurgical/devilutionX/files/6400578/devilutionx-rg350.opk.zip)

**Comment by nicosensei** [comment]
Thanks a lot!

**Comment by glebm** [comment]
updated OPK that fixes some audio issues 
[devilutionx-rg350.opk.zip](https://github.com/diasurgical/devilutionX/files/6401761/devilutionx-rg350.opk.zip)
