### ISSUE TITLE
Keyboard hit "P" - "Pause" stops music playing

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1782]
To reproduce just hit "P"

**Comment by Chance4us** [comment]
Caused by commit acee2ef14ccad779d22554a7df6881877ea50a4b

**Comment by AJenbo** [comment]
This is caused by sound_stop() now also stopping music.

**Comment by Chance4us** [comment]
> Could you plz test if it now also interrupts dialog (like "the sanctity of the place has been fouled") and if that was the case in vanilla?

Yes. I will report.

**Comment by Chance4us** [comment]
It interrupted in fact a dialog "It is hot down here".
The dialogue does not continue to play when you exit the pause mode.
