### ISSUE TITLE
Multiple sound effects at the same time do not play to the end

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1794]
Multiple sound effects at the same time do not play to the end.

How to reproduce:
For example, sort the potions in the belt or drink from a fountain (Blood Fountain or Purifying Spring).
You will notice that the sounds produced by the mouse clicks do not play to the end.

Expected behavior:
Sound effects should play to the end like in vanilla.

**Comment by AJenbo** [comment]
It looks like SDL_audiolib behaves similar to DirectSound where a sound clip can only be played one time, and to play multiple instances we must duplicate at. To solve that we can restore some of the original sound logic https://github.com/diasurgical/devilution/blob/master/Source/sound.cpp#L195

**Comment by Chance4us** [comment]
Hi,
I attached a savegame for testing below.
[spring.zip](https://github.com/diasurgical/devilutionX/files/6410048/spring.zip)
