### ISSUE TITLE
Migrate Linux builds to GitHub Actions

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1818]
Our CI load is pretty heavy, some times we end up with quite a backlog on CircleCI where most of our build happen. To better manage this we could move our Linux builds to GitHub Action to better balance the load.

linux_x86_64_test (note this needs a env var to be able to contact codecov)
linux_x86_64_sdl1
linux_x86_64
linux_x86

Alternativly feel free to move some of the other builds if that makes more sens some how.

**Comment by Trihedraf** [comment]
#1834

**Comment by AJenbo** [comment]
Thank you :)
