### ISSUE TITLE
Raspbian buster - Launching from desktop low performance, from console good

### ISSUE THREAD

**Issue by snigel** [diasurgical/devilutionX#184]
When I launch devilutionx from the desktop of Raspbian Buster the performance is very low, the intro video framedrops, the mouse pointer lags in the menu and the gameplay runs in slow motion.

But, if I launch the game straight from the console, everything works great. Video, menu, gameplay. What's going on here? Is there a correct way of launching the game from a desktop environment?

**Comment by snigel** [comment]
I could reproduce the issue with other applications. Not an issue with devilutionx.

**Comment by AJenbo** [comment]
Did you enable the experimental GPU driver or disable upscaling? Might be helpful in pinpointing the issue with Raspbian.

**Comment by snigel** [comment]
Hi, it's a fresh installation, so I guess neither of those are done.
Where do I disable scaling? As I understand it the experimental gpu driver can be enabled from raspi-config, right?

**Comment by AJenbo** [comment]
README.txt included when downloading the armhf image:
> # Raspberry Pi performance
>  - For the best experience set upscale=0 in diablo.ini and set the system resolution to 640x480
> 
> # Save Games and configurations
> The configurations and save games are located in:
> ~/.local/share/diasurgical/devilution

But if you enabled GPU rendering then I would keep upscaling enabled :)

**Comment by snigel** [comment]
My bad, thought it was a raspberry setting. Thanks for the support.
