### ISSUE TITLE
Footsteps sound different than in vanilla

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#1852]
The sound is a bit weird on master - compare footsteps sound with vanilla, in devilutionx there's a slight pause between replaying the sound

**Comment by StephenCWills** [comment]
Is this related to the buffer size issues we've been chasing? Does it sound better if you change buffer size in diablo.ini to 0?

**Comment by FitzRoyX** [comment]
I get lots of pauses at a value of 2048 (default). Setting to 1024 to 0 fixes it for me. Maybe the default value should be lowered?

**Comment by julealgon** [comment]
Is there any other sound library we could use? This new library is causing so many issues lately.

**Comment by AJenbo** [comment]
Seams more like we are looking thoroughly at the audio implementation then that SDL_audiolib is causing more issues then we already had.

**Comment by StephenCWills** [comment]
> Is there any other sound library we could use? This new library is causing so many issues lately.

I would also add that I think most of these issues would have occurred with any streaming audio library. For example, changing audio libraries won't make StormLib thread safe. Similarly, I believe we also confirmed that this particular issue was not introduced by aulib, but rather by increasing the buffer size. If another such audio library does exist to fix this, you would likely have to search for something that doesn't use SDL for audio.
