### ISSUE TITLE
Error when compiling to 3DS - 'TTF_FONT_DIR'

### ISSUE THREAD

**Issue by SkullEmperor** [diasurgical/devilutionX#1865]
**Important information**
Operating system: Windows 10 
DevilutionX version: Latest from source 
Did you download a release or did you compile yourself?: Compile Myself

**Describe**
I got an error during the compilation about the 'TTF_FONT_DIR'

**To Reproduce**
1. Clone github project on your machine (I used git GUI, sorry noob here...)
2. Open build folder
3. In Msys from devkitpro, use the following commands:
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/3ds.cmake -DVERSION_NUM=1.2.1 -DVERSION_SUFFIX=-old3DS-04-05-2021 -DCMAKE_BUILD_TYPE=Release
$ make
4. After the make command the error appears

**Expected behavior**
This is show:
[ 73%] Building CXX object CMakeFiles/devilutionx.elf.dir/Source/utils/paths.cpp.obj
<command-line>: warning: missing terminating " character
<command-line>: error: missing terminating " character
<command-line>: note: in definition of macro 'TTF_FONT_DIR'
In file included from C:/GitProjects/devilutionXmaster/build/_deps/fmt-src/include/fmt/ranges.h:18,
                 from C:/GitProjects/devilutionXmaster/Source/utils/log.hpp:5,
                 from C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:6:
C:/GitProjects/devilutionXmaster/Source/utils/log.hpp: In function 'std::string devilution::detail::format(const char*, Args&& ...) [with Args = {char*}]':
C:/GitProjects/devilutionXmaster/build/_deps/fmt-src/include/fmt/format.h:126:24: warning: control reaches end of non-void function [-Wreturn-type]
  126 | #  define FMT_CATCH(x) catch (x)
      |                        ^~~~~
C:/GitProjects/devilutionXmaster/Source/utils/log.hpp:48:9: note: in expansion of macro 'FMT_CATCH'
   48 |         FMT_CATCH(const fmt::format_error &e)
      |         ^~~~~~~~~
make[2]: *** [CMakeFiles/devilutionx.elf.dir/build.make:1322: CMakeFiles/devilutionx.elf.dir/Source/utils/paths.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:295: CMakeFiles/devilutionx.elf.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Additional context**
Reverting back the changes in comitt 7398ffa8aa27701a20cb67ecfa2a2787540fe100 fixed for me.
(https://github.com/diasurgical/devilutionX/commit/7398ffa8aa27701a20cb67ecfa2a2787540fe100)

**Comment by StephenCWills** [comment]
This seems like it could be a difference between how Msys handles slashes and escape sequences. It's probably possible to simplify to make it work on both platforms. I'll play around with it for a bit and give you something to try.

**Comment by StephenCWills** [comment]
@SkullEmperor Can you try using the following?

```CMake
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DTTF_FONT_DIR=\"romfs:/\"")
```

**Comment by SkullEmperor** [comment]
Still getting an error, but appears to be a little different:

[ 73%] Building CXX object CMakeFiles/devilutionx.elf.dir/Source/utils/paths.cpp.obj
<command-line>: error: stray '\' in program
C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:94:33: note: in expansion of macro 'TTF_FONT_DIR'
   94 |                 ttfPath.emplace(TTF_FONT_DIR);
      |                                 ^~~~~~~~~~~~
<command-line>: error: stray '\' in program
<command-line>: note: in definition of macro 'TTF_FONT_DIR'
<command-line>: error: stray '\' in program
<command-line>: note: in definition of macro 'TTF_FONT_DIR'
C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp: In function 'const string& devilution::paths::TtfPath()':
<command-line>: error: 'romfs' was not declared in this scope
C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:94:33: note: in expansion of macro 'TTF_FONT_DIR'
   94 |                 ttfPath.emplace(TTF_FONT_DIR);
      |                                 ^~~~~~~~~~~~
C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:93:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
   93 |         if (!ttfPath)
      |         ^~
<command-line>: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:94:33: note: in expansion of macro 'TTF_FONT_DIR'
   94 |                 ttfPath.emplace(TTF_FONT_DIR);
      |                                 ^~~~~~~~~~~~
<command-line>: error: 'devkitPro' was not declared in this scope
C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:94:33: note: in expansion of macro 'TTF_FONT_DIR'
   94 |                 ttfPath.emplace(TTF_FONT_DIR);
      |                                 ^~~~~~~~~~~~
<command-line>: warning: label 'C' defined but not used [-Wunused-label]
C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:94:33: note: in expansion of macro 'TTF_FONT_DIR'
   94 |                 ttfPath.emplace(TTF_FONT_DIR);
      |                                 ^~~~~~~~~~~~
In file included from C:/GitProjects/devilutionXmaster/build/_deps/fmt-src/include/fmt/ranges.h:18,
                 from C:/GitProjects/devilutionXmaster/Source/utils/log.hpp:5,
                 from C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:6:
C:/GitProjects/devilutionXmaster/Source/utils/log.hpp: In function 'std::string devilution::detail::format(const char*, Args&& ...) [with Args = {char*}]':
C:/GitProjects/devilutionXmaster/build/_deps/fmt-src/include/fmt/format.h:126:24: warning: control reaches end of non-void function [-Wreturn-type]
  126 | #  define FMT_CATCH(x) catch (x)
      |                        ^~~~~
C:/GitProjects/devilutionXmaster/Source/utils/log.hpp:48:9: note: in expansion of macro 'FMT_CATCH'
   48 |         FMT_CATCH(const fmt::format_error &e)
      |         ^~~~~~~~~
make[2]: *** [CMakeFiles/devilutionx.elf.dir/build.make:1322: CMakeFiles/devilutionx.elf.dir/Source/utils/paths.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:295: CMakeFiles/devilutionx.elf.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by StephenCWills** [comment]
I think I get it. The quotes need to be in the value. That is to say, the end result needs to be `-DTTF_FONT_DIR="\"romfs:/\""`. With all the quotes and backslashes, it requires some backflips to get that escaped in CMake. Let me search for a better way.

**Comment by StephenCWills** [comment]
There's no "literal string" feature in CMake so I guess we'll just have to bite the bullet and escape things carefully. It's an ugly mess, but give this a try.

```CMake
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DTTF_FONT_DIR=\"\\\"romfs:/\\\"\"")
```

**Comment by SkullEmperor** [comment]
Still with error, but it changed again:

[ 73%] Building CXX object CMakeFiles/devilutionx.elf.dir/Source/utils/paths.cpp.obj
<command-line>: warning: missing terminating " character
<command-line>: error: missing terminating " character
<command-line>: note: in definition of macro 'TTF_FONT_DIR'
In file included from C:/GitProjects/devilutionXmaster/build/_deps/fmt-src/include/fmt/ranges.h:18,
                 from C:/GitProjects/devilutionXmaster/Source/utils/log.hpp:5,
                 from C:/GitProjects/devilutionXmaster/Source/utils/paths.cpp:6:
C:/GitProjects/devilutionXmaster/Source/utils/log.hpp: In function 'std::string devilution::detail::format(const char*, Args&& ...) [with Args = {char*}]':
C:/GitProjects/devilutionXmaster/build/_deps/fmt-src/include/fmt/format.h:126:24: warning: control reaches end of non-void function [-Wreturn-type]
  126 | #  define FMT_CATCH(x) catch (x)
      |                        ^~~~~
C:/GitProjects/devilutionXmaster/Source/utils/log.hpp:48:9: note: in expansion of macro 'FMT_CATCH'
   48 |         FMT_CATCH(const fmt::format_error &e)
      |         ^~~~~~~~~
make[2]: *** [CMakeFiles/devilutionx.elf.dir/build.make:1322: CMakeFiles/devilutionx.elf.dir/Source/utils/paths.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:295: CMakeFiles/devilutionx.elf.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by StephenCWills** [comment]
So from what I could find with some Google searches, it seems the path is being interpreted as a Windows path. The forward slash is being converted to a backslash. and that's causing problems for the escape sequence. To make matters worse, I doubt that `romfs:\CharisSILB.ttf` would resolve to the proper location, and I think the preprocessor might try to interpret `\C` as an escape sequence in the first place (can't say for sure). I'm not sure where the conversion from forward slash to backslash occurs, so I guess I'll try downloading Msys myself and do some testing there.

**Comment by StephenCWills** [comment]
Okay, so it seems MSYS applies a heuristic to locate file paths in a command that is passed to a Windows executable and sanitizes them to pass the appropriate Windows paths into Windows applications automatically. In MSYS2, this heuristic can be bypassed by setting the `MSYS2_ARG_CONV_EXCL` environment variable. So the appropriate way to build the application using devkitPro's MSYS would be...

```Bash
export MSYS2_ARG_CONV_EXCL=-D

cmake .. \
  -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/3ds.cmake \
  -DVERSION_NUM=1.2.1 \
  -DVERSION_SUFFIX=-old3DS-04-05-2021 \
  -DCMAKE_BUILD_TYPE=Release

make -j$(nproc)
```

@SkullEmperor Please give this a try using the version from 7398ffa and let us know how it goes.

```CMake
set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE}\ -DTTF_FONT_DIR=\\"romfs:/\\")
```

**Comment by glebm** [comment]
Instead of setting release flags, simply `set(TTF_FONT_DIR \"romfs:/\")` and add `TTF_FONT_DIR` to the `# Defines with value` list in CMakeLists.txt

**Comment by StephenCWills** [comment]
I just ran another build in MSYS against `set(TTF_FONT_DIR \"romfs:/\")`, and it seems to work fine so long as you export the `MSYS2_ARG_CONV_EXCL` environment variable first. I've also changed the build instructions so I'm closing this issue.
