### ISSUE TITLE
 Windows 8.1 "This app can't run on your PC"

### ISSUE THREAD

**Issue by pedromiguel83** [diasurgical/devilutionX#1879]
**Important information**
Windows 8.1 Pro 32 bits / 1.2.1 / Release

**Describe**
I'm getting the error "This app can't run on your PC" and can't run the port.

**To Reproduce**
Run the DevolutionX.exe

**Comment by StephenCWills** [comment]
Did you download the i386 version of the game?

**Comment by pedromiguel83** [comment]
No. I downloaded the x83_x64 version.

**Comment by AJenbo** [comment]
You have a 32bit i386 so you can't run 64bit x86_64 applications. Download the i386 build instead.

**Comment by pedromiguel83** [comment]
Thank you and sorry for reporting this as an issue.
