### ISSUE TITLE
Game crashes in Crypt Level 1

### ISSUE THREAD

**Issue by ricardonservino** [diasurgical/devilutionX#1887]
**Important information**
Windows 10 / DevilutionX v1.2.1  / downloaded release

**Describe**
Game crashes in Crypt Level 1 without an evident cause.

**To Reproduce**
1. Open attached save file [single_0.zip](https://github.com/diasurgical/devilutionX/files/6442366/single_0.zip)
2. Walk northeast, game will crash

**Comment by AJenbo** [comment]
thanks for reporting. this is a bug in the original game that has been fixed in the latest beta https://github.com/diasurgical/devilutionX/pull/1748
