### ISSUE TITLE
The hero can flicker as soon as Diablo is killed

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1893]
The hero can flicker as soon as Diablo is killed.

How to reproduce:
Not easy to reproduce as the flicker does not appear in every fight.
Kill Diablo and sometimes the problem occurs.

What can it look like:
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6444237/output.mkv.zip)

Savegame for testing:
[flicker.zip](https://github.com/diasurgical/devilutionX/files/6444239/flicker.zip)

The commit could not be determined exactly since when the problem began.

**Comment by AJenbo** [comment]
> The commit could not be determined exactly since when the problem began.

Are you saying this wasn't always the case? If so then I think @obligaron might be the right person for looking in to it.

**Comment by Chance4us** [comment]
> Are you saying this wasn't always the case? If so then I think @obligaron might be the right person for looking in to it.

I never paid attention to this before.
It may well be that it always has been.

**Comment by obligaron** [comment]
I think this was introduced with Animation Distribution Logic.
In my first prototype there was a similar bug when I paused the game.
So I will take a look.
