### ISSUE TITLE
Error ‘SDL_SetWindowInputFocus’ was not declared in this scope

### ISSUE THREAD

**Issue by Chrizzle0112** [diasurgical/devilutionX#190]
Following the instructions for a 32bit build on a 64bit Linux machine. 

`$ uname -a`
> Linux xxx-ThinkPad-X220 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

cmake returns no error: 
`~/Programme/devilutionX-master/build $ cmake -DASAN=OFF -DCMAKE_TOOLCHAIN_FILE=../CMake/mingwcc.cmake ..`
> -- Using 32-bit toolchain
> -- Using 32-bit libraries from /usr/lib/i386-linux-gnu
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/cboeser/Programme/devilutionX-master/build`

When building I get the following error.
`$ linux32 make -j$(nproc)`
[...]

> [ 79%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/miniwin/misc_io.cpp.o
> /home/cboeser/Programme/devilutionX-master/SourceX/miniwin/misc.cpp:293:36: error: ‘SDL_SetWindowInputFocus’ was not declared in this scope
>   if (SDL_SetWindowInputFocus(window) <= -1){`

**Comment by AJenbo** [comment]
Your SDL is outdated, please upgrade to 2.0.5 or later:
https://wiki.libsdl.org/SDL_SetWindowInputFocus
https://packages.ubuntu.com/xenial/libsdl2-2.0-0

You can do this either but using the one Provided by Steam or find a PPA, or upgrading to Ubuntu 18.04.
