### ISSUE TITLE
Hork Demon unusual low vitality

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1927]
Hork Demon is strangely colored in red.
In addition, he could be killed with just one fireball.

In game:
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6453433/output.mkv.zip)

Screenshot:
![hork_demon](https://user-images.githubusercontent.com/45902449/117689805-69ae5c00-b1ba-11eb-8985-8b7e930a85b8.png)

Savegame:
[hork_demon.zip](https://github.com/diasurgical/devilutionX/files/6453450/hork_demon.zip)

**Comment by StephenCWills** [comment]
This could be two separate issues. Fortunately, it looks like at least one of them was resolved already: #1921.

**Comment by Chance4us** [comment]
Thanks. I'll try the color fix right away.

**Comment by Chance4us** [comment]
Indeed the red color is already fixed. So there is only low vitality left.

**Comment by Chance4us** [comment]
How should I know that these are separate errors.
Maybe you should hold back a little.

**Comment by Chance4us** [comment]
But sorry for the language, it is honestly not meant badly.

**Comment by qndel** [comment]
I would've reported it the same way - I see a red guy, he died in 1 hit, it's obvious to try to make a connection between these two things

**Comment by AJenbo** [comment]
Hork Demons HP appears correct when testing

**Comment by Chance4us** [comment]
Great news. Thanks a lot for verification.
