### ISSUE TITLE
Text wrap in gamepad controls

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#1931]
The word "MENU" is text wrapped so the "U" shows up on a separate line.
![image](https://user-images.githubusercontent.com/9203145/117745434-7772da00-b1d8-11eb-9219-3541bf22c2e4.png)

**To Reproduce**
1. Enter the game
2. Hold the Start button on the gamepad

**Comment by glebm** [comment]
@AJenbo do we always do wrapping with the new text renderer? There should probably be non-wrapping versions, to avoid unnecessary computation
