### ISSUE TITLE
Left/Right gamepad options are swapped

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#1933]
I just noticed while playing 3DS that INV and CHAR are swapped. See the screenshot from #1931.

Actually, all the left/right options got moved to the opposite side (e.g., QUEST is supposed to be on the left). It still highlights the CHAR option when I press Start+Left and opens the character sheet so the only thing that's changed is the side they're being rendered on.

**Comment by glebm** [comment]
That sounds like perhaps the mappings in n3ds_defs.cmake are incorrect?

**Comment by glebm** [comment]
Nevermind, it's not 3DS-specific, reproduced on another device
Not sure what broke it

**Comment by AJenbo** [comment]
I might have gotten my pluses and minuses mixed up.
