### ISSUE TITLE
Map only shows small quads.

### ISSUE THREAD

**Issue by Cowcat5150** [diasurgical/devilutionX#1937]
System Morphos, cpu ppc32

Instead of drawing all map, only small quads with/without lines at their corners are rendered. Text characters work.

**Comment by AJenbo** [comment]
Hmm could you post an image of this?

**Comment by Cowcat5150** [comment]
Yep
![IMG_20210511_145451](https://user-images.githubusercontent.com/43408115/117817495-f2370600-b267-11eb-9dcd-480ddb36407a.jpg)

**Comment by AJenbo** [comment]
@glebm I'm guessing this is because of the change I did to how files are loaded rather then the changes you did to auto-map?

I guess I can deal with it on my PowerPC next time i have a bit of time.

**Comment by AJenbo** [comment]
Looks like this works correctly now, at least on my PowerPC

**Comment by Cowcat5150** [comment]
Yep. No problem here.
