### ISSUE TITLE
Quest NPC quotes

### ISSUE THREAD

**Issue by BF3000** [diasurgical/devilutionX#195]
As far as I remember, every NPC have it opinion on every quest.
But everything I see, is "Gossip".

**Comment by BF3000** [comment]
Looks like it not present in that test build AJenbo provided to me in other issue.
Maybe it was fixed in the recent builds.

**Comment by AJenbo** [comment]
Sounds plausible

**Comment by BF3000** [comment]
After some more testing I can see, this is not fixed.
I'ts just dialogues for some quests work (like Butcher), but most of them is not.

**Comment by AJenbo** [comment]
Not every towner has something to say about every quest, you can see the table here:
https://github.com/diasurgical/devilutionX/blob/master/Source/towners.cpp#L96

**Comment by BF3000** [comment]
https://youtu.be/CkKBWl7D6xA
Thats not the case.

**Comment by BF3000** [comment]
[single_0.zip](https://github.com/diasurgical/devilutionX/files/3438080/single_0.zip)
And the save file.

**Comment by BF3000** [comment]
Butcher quest (it was already complited) dialogs present, Ogden's Sign quest is present but no dialogs about it.
I spend more than a hour to check it on original Diablo.
