### ISSUE TITLE
Damage value on character sheet wraps to next line

### ISSUE THREAD

**Issue by thebigMuh** [diasurgical/devilutionX#1950]
The new text renderer doesn't compress the damage value shown on the character screen, which results in wrapping:
![image](https://user-images.githubusercontent.com/81810641/118060897-1e4fa580-b394-11eb-935d-5f225500f67d.png)

For comparison, here's an older version (different values, but you get the idea):
![image](https://user-images.githubusercontent.com/81810641/118061020-6969b880-b394-11eb-8921-32f0063c3279.png)

**Comment by AJenbo** [comment]
Could you test with https://github.com/diasurgical/devilutionX/pull/1958, and/or provide a save game for testing this.
