### ISSUE TITLE
Diablo.ini not working

### ISSUE THREAD

**Issue by JFBrittes** [diasurgical/devilutionX#1953]
Hello,

I just started using the mod and I was trying out to change some of the configurations from diablo.ini but as I edit it I don't see the effects taking change in the game.

First I was unable to find the diablo.ini...

I searched where it was supposed to be created but it wasn't anywhere.
So I searched the forums and found this guide: 

https://github.com/diasurgical/devilutionX/wiki/DevilutionX-additional-arguments-configuration-guide

I was able to change the folder and finally found the diablo.ini file. After I made the changes I wanted I saved it.

However, the changes did not work.

PS: I'm using the newest version of the beta I was given the link when I had this issue:

https://github.com/diasurgical/devilutionX/discussions/1862

**Comment by AJenbo** [comment]
Unfortunatly the ini file is still affected by the international symbol issue

To work around it you need a path that does not have international symbols in it and point to it using `--config-dir`. You can do this by creating a short cut to the exe and add it at the end of the target followed by the path with no international symbols.

Example:
`c:\Diablo\devilutionx.exe --config-dir c:\config`

Be sure that the new parth is writable using your default user settings.

![image](https://user-images.githubusercontent.com/204594/118126207-4ffa5800-b3f8-11eb-97c8-b77216eb991c.png)

**Comment by AJenbo** [comment]
The issue will be resolved once https://github.com/diasurgical/devilutionX/issues/1246 is implemented

**Comment by JFBrittes** [comment]
ok it worked. thanks :)
