### ISSUE TITLE
Monster light does not follow monster when it blinks

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#1965]
**Important information**
Windows 10
Version: 1.2.1 (Release Version)

**Describe**
Bat enemies have the ability to blink (teleport) when you hit them. Moonbender, a unique bat, has a light source. The light source does not follow him upon blinking. Only when he moves after blinking does the light source return to his position.

**To Reproduce**
1. Load save file
2. Hit Moonbender

**Expected behavior**
light should follow its source on all repositions 

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6475029/single_0.zip)

**Comment by galaxyhaxz** [comment]
Make this change to `M_Teleport` to fix this bug:
```c
dMonster[x][y] = i + 1;
// add this
if (Monst->mlid != NO_LIGHT)
	ChangeLightXY(Monst->mlid, x, y);
```

**Comment by ThomasChr** [comment]
@galaxyhaxz Would you like to make that fix and make a PR for that?

**Comment by galaxyhaxz** [comment]
I'm on break, trying to enjoy summer and work and all. It's a simple one if someone else wants to do it (:

**Comment by ThomasChr** [comment]
I would like to try!
Where do I need to sign up and sell my soul?

**Comment by qndel** [comment]
discord ;)

**Comment by galaxyhaxz** [comment]
Hell is only a tear drop away, but despite any tears you cry Hell is currently under lockdown and Satan is working from home.

Mail a letter to the following address and you'll be signed up in 666 Hell business days:
```
Satan
1337 Lucifer Ave, Apt B
Sulfur Tear City, Fire Lake
Hell
```

**Comment by ThomasChr** [comment]
I was so proud having found the right place and the right function to call right from the start. And then @qndel told me that the code is already in this issue. Not so proud anymore :-(
But thanks a lot qndel for helping me!

**Comment by ThomasChr** [comment]
@galaxyhaxz Thank you very much for letting me take this issue!
