### ISSUE TITLE
[render] Sign of Reflect spell flickers when walking to the north direction

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1971]
The sign of the Reflect spell flickers when walking to the north direction.
No big deal. As a reminder for cosmetic operations.

It looks like the following:
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6480696/output.mkv.zip)

Savegame:
[reflect.zip](https://github.com/diasurgical/devilutionX/files/6480870/reflect.zip)

**Comment by AJenbo** [comment]
Is this also the case in vanilla?

**Comment by Chance4us** [comment]
No, in vanilla it does not flicker.

**Comment by julealgon** [comment]
Does this happen while using only Reflect, without Mana Shield?

**Comment by Chance4us** [comment]
> Does this happen while using only Reflect, without Mana Shield?

Without "mana shield" flickering does not happen.

**Comment by Chance4us** [comment]
This is fixed by commit 86e1d488e68e2088aa27b5499ea95d88ef854c83 and can be closed.
