### ISSUE TITLE
[render] Gold on a sensitive place - difference between devilutionx / vanilla

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1972]
This could be a "wontfix", although the gold pieces are not fully displayed.
As a reminder, if there is a desire to improve the appearance of gold on such places.

It looks like the following.
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6480850/output.mkv.zip)

Savegame:
[gold.zip](https://github.com/diasurgical/devilutionX/files/6480858/gold.zip)

**Comment by AJenbo** [comment]
yeah it's a trade off between that and the multiple other issues that are visible in the vanilla screen shot.
