### ISSUE TITLE
Get ASIO via CMake

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1982]
To make it easier to cache the dependency and have less in repo dependencies it would be good to move AISO out and instead get it via CMake like we do most other dependencies.

This will also make it easy to upgrade with out causing thousands of lines of change.

See:
https://github.com/diasurgical/devilutionX/pull/1979

**Comment by julealgon** [comment]
You might want to fix the typo on the title/description (in case you want to search for ASIO later).
