### ISSUE TITLE
Stuttery Reflect overlay while moving

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#1989]
**Important information**
Windows 10, DevilutionX latest commit 55fa72d1

**Describe**
Rendering of Mana Shield and Reflect overlays are inconsistent: while Mana Shield properly follows the hero using the same update frequency and position as the character, Reflect appears to be using a different logic that results in jittery motion.

**To Reproduce**
1. Cast Mana Shield
2. Cast Reflect
3. Move and observe the difference in motion

(hero with both spells for testing)
- [single_7.zip](https://github.com/diasurgical/devilutionX/files/6490015/single_7.zip)

**Expected behavior**
Reflect should be rendered using the same approach used for Mana Shield, resulting in a smooth motion.

**Screenshots**
![ReflectManaShieldOverlayInconsistency](https://user-images.githubusercontent.com/461579/118412110-948f2900-b66e-11eb-95b9-8e1e572fc7ee.gif)

(It actually looks worse the higher the framerate is. This gif makes it look "less bad" than it is)

**Additional context**
Discovered while testing #1971. They might be related in some form.

Tested on original Hellfire and cannot repro the issue there. I assume it's related to the increase in FPS in DevilutionX?

**Comment by AJenbo** [comment]
Reflect uses the old way of adding icons to players. This should be updated to match the 1.09 logic used for manashield as it solves multiple issues.

**Comment by julealgon** [comment]
I see you added vanilla/hellfire tags @AJenbo , but I wasn't able to repro this in original Hellfire. Is there something else to it?

**Comment by Chance4us** [comment]
@all It happens since commit 4d2ac0502a92e652e28da6f4b37cd932b6d07f70.

**Comment by AJenbo** [comment]
@Chance4us I don't know what your exactly intending with the shout out to ALL, but he probably isn't very interested. There is no short hand for mentioning all involved parties in a specific issue if that is what your trying to do. If your intend is to call for the attention of all 40 million GitHub users I think that is a very bad idea.

**Comment by Chance4us** [comment]
By the way I also have the impression that since this commit the monsters are stuttering when they follow you closely.

**Comment by AJenbo** [comment]
> By the way I also have the impression that since this commit the monsters are stuttering when they follow you closely.

They don't, they use the fixed update interval. This is gradually being migrated, one entity at a time. Also this is the wrong place for having a discussion about that.

**Comment by Chance4us** [comment]
> @Chance4us I don't know what your exactly intending with the shout out to ALL, but he probably isn't very interested. There is no short hand for mentioning all involved parties in a specific issue if that is what your trying to do. If your intend is to call for the attention of all 40 million GitHub users I think that is a very bad idea.

I'm sorry, I didn' know that all in fact would receive the message.

**Comment by AJenbo** [comment]
> I see you added vanilla/hellfire tags @AJenbo , but I wasn't able to repro this in original Hellfire. Is there something else to it?

There are multiple render issues related to the old logic, and updating the logic to match what was done as part of [1.07](https://diablo.fandom.com/wiki/Patch_1.07_(Diablo_I)) solves all of it, I would consider this to be a Vanilla Hellfire issue, it just so happens that now there is another way to notice it.

**Comment by Chance4us** [comment]
@AJenbo and @julealgon this kind of stuttering happens since since commit 4d2ac05.
I just found out through bisect.

**Comment by AJenbo** [comment]
@Chance4us, we know, and you already mentioned it 7 minutes earlier. 4d2ac05 is not the cause, but makes it constantly apparent.

Here is where the drawing of the manashield is handled:
https://github.com/diasurgical/devilutionX/blob/master/Source/scrollrt.cpp#L361
Reflect should be updated to be handled in the same way.
