### ISSUE TITLE
No Butcher in multiplayer

### ISSUE THREAD

**Issue by Howlinmoon** [diasurgical/devilutionX#199]
I have looked through all of the currently open issues and the closed ones to see if this has been reported previously.
I am using the 0.4.0 MacOS build.  I am using the diabdat.mpq from my original Windows Diablo CD - which I bought as soon as it was released.

Normally, in multiplayer there is only a subset of quests available.  Besides Diablo himself, I can't recall if there are any other endgame quests - but there were definitely two early game quests in multiplayer:

The Butcher on Level 2
The Skeleton King on Level 3.

In single player, the Skeleton King properly gets his own subLevel, and in Multiplayer, he is spawned randomly someplace on the 3rd level - just like I remember.

The issue I am seeing is the room containing the Butcher hasn't appeared on the 2nd level in the multiplayer games I have tried.

I have created 4-5 new games and have explored the 2nd level completely and each time, there is no sign of the Butcher's room.

All players are local and are running MacOS and I setup the game using TCP.

The butcher's room DOES properly appear in the single player instances I have tried.

####

What is the preferred method of asking general questions.  I'd prefer not to clog "Issues", but I haven't been able to find any place suitable for asking them.  Is there a Forum or discussion area someplace?

**Comment by AJenbo** [comment]
The quest issue has been addressed upstream and a new release should be out in not to long: https://github.com/diasurgical/devilution/issues/581

For general questions please use our Discord chat (see top of readme)
