### ISSUE TITLE
Missing door frames

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#1990]
For some reason the door frames are missing.

![screen00](https://user-images.githubusercontent.com/45902449/118413324-0b441a80-b69f-11eb-9b72-87ff1d773273.png)

Savegame:
[doors.zip](https://github.com/diasurgical/devilutionX/files/6490069/doors.zip)

**Comment by AJenbo** [comment]
Does using the doors solve it. Where does the save originate from?

**Comment by Chance4us** [comment]
> Does using the doors solve it. Where does the save originate from?

I started a new game on commit 55fa72d138d8349444907845ebeb9c70bde53143.
And I was just about to try out the doors and loaded the game, but after reloading the game, the doors weren't there anymore. Strange isn't it?

![screen00](https://user-images.githubusercontent.com/45902449/118414575-b6f06900-b6a5-11eb-83c4-8df35b8666bf.png)

**Comment by AJenbo** [comment]
Looks like the issue is solved now?

**Comment by Chance4us** [comment]
It fixed itself after reloading.
Why it occurred during the game is unclear.
Since the bug cannot be traced, I have now closed.
