### ISSUE TITLE
Translation-related crash when attacking a Crypt Demon monster

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#1992]
**Important information**
Windows 10 commit 55fa72d1

**Describe**

**To Reproduce**
1. Load save
2. Attack the crypt demon unit
3. Observe crash

Save:
- [single_7.zip](https://github.com/diasurgical/devilutionX/files/6490105/single_7.zip)

**Expected behavior**
No crashes :)

**Screenshots**

![image](https://user-images.githubusercontent.com/461579/118413970-6c0c2c80-b678-11eb-8713-f8aeb2607fc6.png)
![image](https://user-images.githubusercontent.com/461579/118413964-5eef3d80-b678-11eb-8adb-e230d84d98c0.png)

**Comment by ThomasChr** [comment]
Can't reproduce it in 1.2.1 and in c11929e282b1efb6c9e72b6701f2372fe7f2b13e
Sure the crash does still exist?

**Comment by qndel** [comment]
Failed to reproduce on master and mentioned commit
