### ISSUE TITLE
Delays in movement from standstill while click is held

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#1993]
**Important information**
latest build

**Describe**
Holding click at your character's feet to stop creates a 1 second delay before movement can start again. Julealgon suspects that the delay is equal to the idle animation cycle completing. This appears to be a byproduct of recent animation changes by @obligaron.

**To Reproduce**
1. Click and hold character's tile
2. Move cursor away from tile

**Expected behavior**
Movement away from current tile should be instant when click is held

**Comment by obligaron** [comment]
I will take a look 🙂
