### ISSUE TITLE
Refactor devilution.DefaultClass::StartWalk(int, int, int, int, int, int, int, int, int, direction, _scroll_direction, int, bool)

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#1998]
I've selected [**devilution.DefaultClass::StartWalk(int, int, int, int, int, int, int, int, int, direction, _scroll_direction, int, bool)**](https://github.com/diasurgical/devilutionX/blob/0c7c71d579c60b33467c065b9d7ad76ef4ca6394/Source/player.cpp#L1404-L1510) for refactoring, which is a unit of **85** lines of code and **13** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.
Using `Point` instead of the X/Y pairs would help reduce the number of parameters, but even more so most of the parameters are directly related to the walk direction. The logic for paring them up could be moved in to the function instead so that it simply becomes `void StartWalk(int pnum, Point velocity, direction EndDir, bool pmWillBeCalled);`

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by matheusgomes28** [comment]
I can pick this up, will give someone a shout on discord if I need help (new to the codebase 😄 )

**Comment by AJenbo** [comment]
@matheusgomes28 grate, I'll be happy to assist you in finding you way around :)
