### ISSUE TITLE
D-Bus not built with -rdynamic so unable to print a backtrace

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#20]
If you get the following error it is likely a bug in your distribution's 32bit SDL package.

```
dbus[8661]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Afbrudt (SIGABRT) (smed kerne)
```

The issue has been reported against Ubuntu here:
https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1775067

A workaround is to run the game like this:
```shell
DBUS_FATAL_WARNINGS=0 ./devilutionx
```

**Comment by llcool** [comment]
Great work.

I installed the libs
`$ sudo apt install libsdl2-mixer-dev:i386 libsdl2-ttf-dev:i386 libsodium-dev libsodium-dev:i386`

Installed steam
`sudo apt install steam`

And downloaded your prebuild file:
devilutionx

I also bought a copy of GOG Diablo 1

**Comment by AJenbo** [comment]
Thanks. The libs are only needed if you build from source :slightly_smiling_face: 

Good point about having to install the GoG version in Windows. I will ask my frind if he can document how he extracted the files from the GoG setup file.

Stick around, the next release should be fairly exciting :smiling_imp:

**Comment by mnhauke** [comment]
**Extract DIABDAT.MPQ from the GoG installer**

01) First download the offlineinstaller of the GoG.

02) Install the latest git snapshot of [innoextract](http://constexpr.org/innoextract/)
```
git clone https://github.com/dscharrer/innoextract.git
cd innoextract/cmake/
cmake ..
make
sudo make install
```

03) Check innoextract version (must be > 1.7)
```
$ innoextract --version
innoextract 1.8-dev + 38ae68f
Extracts installers created by Inno Setup 1.2.10 to 6.0.0
```

04) Get some info about the installer
```
$ innoextract --info 'setup_diablo_1.09_v2_(27882).exe'
Inspecting "Diablo" - setup data version 5.6.2 (unicode)

Languages:
 - en-US

GOG.com game ID is 1412601690

Setup is not passworded!
```

05) Extract DIABDAT.MPQ from the installer
```
$ innoextract --include DIABDAT.MPQ --lowercase 'setup_diablo_1.09_v2_(27882).exe'
Extracting "Diablo" - setup data version 5.6.2 (unicode)
 - "diabdat.mpq" [en-US]
Done.
```
06) have fun :-)

**Comment by DCsunset** [comment]
Hi,

After installing steam, there is only `libSDL2-2.0.so.0` in `~/.steam/bin32`.
`libSDL2_ttf-2.0.so.0` and `libSDL2_mixer-2.0.so.0` are still not found.

Is there any idea how to get the missing libraries?
Thanks.

**Comment by AJenbo** [comment]
@DCsunset did you try installing them threw normal means?
`sudo apt install libsdl2-ttf-2.0:i386 libsdl2-mixer-2.0:i386`

**Comment by DCsunset** [comment]
Oh, I got it.
`libsdl2-ttf-2.0:i386` and `libsdl2-mixer-2.0:i386` are not buggy, and install through apt is OK.
(I just uninstalled them after the failure)

**Comment by AJenbo** [comment]
@DCsunset thanks for confirming the solution.

**Comment by ctrl-meta-f** [comment]
This is a known sdl2 bug in Ubuntu 18.04

https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1775067

Another workaround is to run the game like this:

```shell
DBUS_FATAL_WARNINGS=0 ./devilutionx
```

**Comment by AJenbo** [comment]
Thanks that's a simpler solution.

**Comment by AJenbo** [comment]
Closing this as we now support native 64bit builds in stead.
