### ISSUE TITLE
Using "staff of mana" in town consumes 4 charges at once

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2003]
Using "staff of mana" in town often consumes 4 charges at once.
It is also so common that no charge is consumed.

Whether the issue also takes place in the dungeon has not yet been investigated.
Since which commit the issue occurs has not yet been investigated too.

How to reproduce on commit 55fa72d138d8349444907845ebeb9c70bde53143:
1. Load the attached game and cast using equipped staff
2. Keep an eye on the number of charges remaining
3. You should be able to observe that either 4 charges are consumed very quickly or none

Savegame:
[manastaff.zip](https://github.com/diasurgical/devilutionX/files/6492815/manastaff.zip)

How it looks like (the video is very short, so try to observe the number of charges as soon as possible):
[output.mkv.zip](https://github.com/diasurgical/devilutionX/files/6492820/output.mkv.zip)

**Comment by obligaron** [comment]
Could you try #1980?

**Comment by Chance4us** [comment]
@obligaron
Many Thanks. I was finally able to try out PR after work. Since then, multiple casting has not occurred.

But I have one more important question about the following PR's.
commit 19615c69765e3b4577c29bd009ea19c6d60e5442
commit be13a0f72749d0a17ab0b57a9dad9cc8f9fe7e28
commit 4de25cd2eab810aae981bf86f380f52952dc2a2d
commit 4d2ac0502a92e652e28da6f4b37cd932b6d07f70
commit 55fa72d138d8349444907845ebeb9c70bde53143

These seem to have caused some side effects such as #1985, #1989, #1993, #1102 (?) #2003.

However, there was basically a subjective impression that the graphics performance has improved significantly.
Among other things, I notice it when I change direction while jogging in the city. The changes of direction seem to me to be very fluid, the stuttering is gone and the movements are fluid as if they were oiled. Is it just my impression or do the changes actually have something to do with it?

**Comment by AJenbo** [comment]
The performance is the same, but animation is no long locked to the 50ms logic tick, that is the very intent with the commits you highlighted.

**Comment by Chance4us** [comment]
> The performance is the same, but animation is no long locked to the 50ms logic tick, that is the very intent with the commits you highlighted.

Thank you very much, the game feels extremely nice with it.

**Comment by obligaron** [comment]
It's good that you like the changes. 🙂 
PR #1987 also contains some before/after videos. 😉

**Comment by Chance4us** [comment]
Thanks for polishing the game.
And I think although not all side effects are fixed yet it's a really big step in the right direction.

**Comment by obligaron** [comment]
@AJenbo I think with #2025 this can be closed 🙂
