### ISSUE TITLE
Hero stutterstops when click is held 1 tile from hero (fastwalk only)

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#2005]
**Important information**
latest build

**Describe**
Hero stutterstops when click is held 1 tile from hero (fastwalk only)

**To Reproduce**
1. Enable fastwalk in town
2. Go to town
3. Click and hold 1 tile from hero's standing tile

**Expected behavior**
Hero walks fluidly without interruption

**Comment by AJenbo** [comment]
This is probably down to `track_process()` expecting to only needing to check for the player position at a rate that fits the move speed for normal walking. Adjusting line 35 might be all that is needed to fix this.

**Comment by Trihedraf** [comment]
> This is probably down to `track_process()` expecting to only needing to check for the player position at a rate that fits the move speed for normal walking. Adjusting line 35 might be all that is needed to fix this.

In line 37 of track.cpp if you delete the * 6 it fixes the stutter.
@AJenbo Would that be a good fix or would that break something else?
```if ((int)(tick - sgdwLastWalk) >= gnTickDelay * 6) {```
```if ((int)(tick - sgdwLastWalk) >= gnTickDelay) {```

**Comment by AJenbo** [comment]
preferably it would be gnTickDelay * 3 if in town with fastwalk enabled, else gnTickDelay * 6

**Comment by FitzRoyX** [comment]
I can still trigger this if the cursor is close enough to the hero. It is better now after the merge, though.
