### ISSUE TITLE
Quick save and quick load hotkeys functional in multiplayer games

### ISSUE THREAD

**Issue by IAmTrial** [diasurgical/devilutionX#2008]
**Important information**
Windows 10 x64 Build / Compiled commit 1c77a22735d87078d7810d4044be30c1e3942f90

**Describe**
The hotkeys for quicksave and quickload (default F2 and F3, respectively) work in Multiplayer, when it should only work in Single Player. This may lead to a loss of progress for a character and a potential crash.

**To Reproduce**
1. Start a Multiplayer game with any character.
2. Press the quick save hotkey.
3. Press the quick load hotkey.
4. Character will be reloaded to the state when the quicksave was performed.

**Expected behavior**
Multiplayer games should not have quick save nor quick load enabled. Single Player games should have quick save and quick load enabled.

**Additional context**
If the quick save button was not pressed at any point in the game, but the quick load button is pressed, the game will crash.

**Comment by julealgon** [comment]
Caused by #1389
