### ISSUE TITLE
Talking to Cain after getting the The Staff of Lazarus crashes the game

### ISSUE THREAD

**Issue by CaptainCosmotic** [diasurgical/devilutionX#2010]
**Important information**
Win10 / Version 1.2.1 / download form github
**Describe**
When I try to talk to Cain after I grabbed the Staff of Lazarus the game crashes.

**To Reproduce**
1. Take my savegame
2. Talk to Cain
3. Crash the game

**Expected behavior**
I expect Cain to start the Diablo dialogue.
**Screenshots**
![D1crash](https://user-images.githubusercontent.com/57239116/118688476-617f9d80-b806-11eb-804e-f53ba97ceabd.jpg)

The German text in the screenshot is translated to: The targeted/indicated modul was not found.

**Additional context**
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6502839/single_0.zip)

**Comment by AJenbo** [comment]
The missing DLL can be found here:
https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4-win32-x64.zip

Or if you are on a 32bit Windows build:
https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4-win32-x86.zip

**Comment by CaptainCosmotic** [comment]
> You are missing libmodplug-1.dll, it can be found here:
> https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4-win32-x64.zip
> 
> Or if you are on a 32bit Windows build:
> https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4-win32-x86.zip

![D1crash2](https://user-images.githubusercontent.com/57239116/118690189-16ff2080-b808-11eb-97f3-2ff03383d71f.jpg)
After putting the missing dll in teh Deviultioon folder this crash message came

**Comment by AJenbo** [comment]
Could you calculate the hash of your diabdat.mpq, it looks like it might be corrupted. Firstly it should not have triggered the game to think the audio might have been .mod since they are all .wav.

**Comment by CaptainCosmotic** [comment]
DIABDAT.MPQ	(n/a) - 517501282 bytes
SHA-1	474f1f7f7369eb03dd8c2a79a17ba634c285bf9d

SHA-256	a30eea3f0f5567092800a197319c760f842420b75895bce4a6902d9f5fcb78f5

SHA-384	f90b8d21c54abd719e63eed5ba2b362953a1e51d4fe4ec49db606e8c0bd83948b1c24e012a61ccf41adec16cff8ed9ee

SHA-512	ce1b919e14e805ab85a57f0db0853dabefe8aac02ba12b44ff1e121b61eac598fc756e2c747b839d9e7c95442755aaa8941e46060322ae1c4ce1e9ec9dc0fcae

**Comment by CaptainCosmotic** [comment]
Okay it seems to be a corrupted DIABDAT.MPQ
I took one from a gog install and its now working again

**Comment by AJenbo** [comment]
> DIABDAT.MPQ (n/a) - 517501282 bytes
> SHA-1 474f1f7f7369eb03dd8c2a79a17ba634c285bf9d
> 
> SHA-256 a30eea3f0f5567092800a197319c760f842420b75895bce4a6902d9f5fcb78f5
> 
> SHA-384 f90b8d21c54abd719e63eed5ba2b362953a1e51d4fe4ec49db606e8c0bd83948b1c24e012a61ccf41adec16cff8ed9ee
> 
> SHA-512 ce1b919e14e805ab85a57f0db0853dabefe8aac02ba12b44ff1e121b61eac598fc756e2c747b839d9e7c95442755aaa8941e46060322ae1c4ce1e9ec9dc0fcae

Those are all SHA hashes, I only have a list of valid MD5 values :)
