### ISSUE TITLE
Camera/character jerks when playing with controller

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#2011]
All you need to do to reproduce is change direction mid-stride using controller. This definitely started after the recent ADL changes, but given that it can't be reproduced with the mouse controls, the fix for this may end up being unrelated to ADL.

Here is a video of the issue.

https://user-images.githubusercontent.com/9203145/118727673-1e6efb80-b801-11eb-8665-959aeae9dde6.mp4

Here is a "before" video for comparison, in case it's relevant. Something I always noticed with controller is how the direction on the map updates immediately based on controller inputs despite the character still walking in the same direction.

https://user-images.githubusercontent.com/9203145/118728614-7b1ee600-b802-11eb-8a52-045184cedc9a.mp4

**Comment by julealgon** [comment]
>  Something I always noticed with controller is how the direction on the map updates immediately based on controller inputs despite the character still walking in the same direction.

This sounds like a bug as well, and might be actually related. Perhaps fixing _that_ ends up fixing this camera issue.

@obligaron FYI here.

**Comment by StephenCWills** [comment]
After reviewing some of the code for handling controller movement, I thought I might see some similar behavior in a multiplayer game using mouse movement. The result was indeed similar, but not quite what I expected.

https://user-images.githubusercontent.com/9203145/118731217-e66ab700-b806-11eb-96aa-0d71874588b1.mp4

**Comment by StephenCWills** [comment]
> This sounds like a bug as well, and might be actually related. Perhaps fixing _that_ ends up fixing this camera issue.

I have actually confirmed this is the case. Changing the player's direction prematurely causes the camera to freak out and the player to teleport, even with mouse controls. The multiplayer issue is separate so I'll open another issue.

**Comment by AJenbo** [comment]
> After reviewing some of the code for handling controller movement, I thought I might see some similar behavior in a multiplayer game using mouse movement. The result was indeed similar, but not quite what I expected.
> 
> EDIT: Video moved to #2013 where it will be more relevant.

That makes sens as part of it uses the same mechanism for transmitting commands to the player rather then doing mouse click events.
