### ISSUE TITLE
Switching to a different app using Win+Tab requires two attempts

### ISSUE THREAD

**Issue by karaluh** [diasurgical/devilutionX#2027]
**Important information**
Windows 7 Pro / 1.2.1 / downloaded

**Describe**
When switching apps using Win+Tab the first attempt doesn't succeed and the action has to be repeated.

**To Reproduce**
1. Start the game
2. Press and hold Win key
3. Press Tab key
4. Release the Win key

**Expected behavior**
The next app gets the focus.

**Comment by AJenbo** [comment]
Do you have "grab input" enabled in the ini?

**Comment by karaluh** [comment]
No, it's disabled.

**Comment by obligaron** [comment]
I tried current master, 1.4.1 and 1.2.1.
All behave the same as other windows apps.
(Tested on windows 10)

Perhaps this issue is windows 7 specific?
Or the issue is caused by a third party app? (for example a recording software)

**Comment by StephenCWills** [comment]
Honestly, this seems to be the intended behavior in Windows 7. I believe you have to hold the Windows key and press Tab twice to switch to the next window. If you only press Tab once, it won't switch.

https://youtu.be/8obZVUzpNXA?t=40
