### ISSUE TITLE
[hellfire] Misaligned lava tiles

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2028]
Since the beginning of the Hellfire support the lava tiles have been misaligned.
I tested down to the commit a1281d8b5459625ea47678d77d4d97cac7bb1f2d of Jan 23, 2021
and there it was also.

Comparison vanilla vs. devilutionx.
![vanilla](https://user-images.githubusercontent.com/45902449/119058268-524b4c00-b9ce-11eb-9f6a-fbd840468b56.png)
![dx](https://user-images.githubusercontent.com/45902449/119058277-58d9c380-b9ce-11eb-9b29-cfad1b0ef068.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6519081/single_0.hsv.zip)

No big deal, just graphically in need of improvement.
By the way, they are everywhere.

**Comment by julealgon** [comment]
Please consider taking screenshots using the same resolution when comparing graphics.

**Comment by FitzRoyX** [comment]
Why are the placements of things (like sarcophagi) so different between the two as well? Is this the result of map generation fixes in devx?

**Comment by AJenbo** [comment]
I think there is a recent bug that has objects off by one

**Comment by qndel** [comment]
@Chance4us 
![image](https://user-images.githubusercontent.com/14297035/120190734-4b67d900-c219-11eb-987c-9ad42815e1a8.png)
any idea what's up with the tile marked green? Is it a flaw in the original dungeon generation?

**Comment by nickgavran** [comment]
Just to shed some light on these "weird" tiles that look broken, they're actually not. They are designed so you cannot step on them. I don't know if they go unused in regular hellfire.

Here's a link to the full Crypt tileset, wherein you can see all of the tiles posted above: https://www.spriters-resource.com/pc_computer/diablodiablohellfire/sheet/63724/

**Comment by qndel** [comment]
So the question is if we want to stay the same as original hellfire 🤷

**Comment by AJenbo** [comment]
> So the question is if we want to stay the same as original hellfire 🤷

yes plz :D

**Comment by Chance4us** [comment]
> @Chance4us
> ![image](https://user-images.githubusercontent.com/14297035/120190734-4b67d900-c219-11eb-987c-9ad42815e1a8.png)
> any idea what's up with the tile marked green? Is it a flaw in the original dungeon generation?

It looks strange, but it's the same in vanilla.
