### ISSUE TITLE
[Diablo] Wall tile not rendered correctly in automap

### ISSUE THREAD

**Issue by agris-codes** [diasurgical/devilutionX#2036]
**Important information**
Win7x64 source build from 5/21/2021, no hellfire .MPQ

**Describe**
Automap does not display several wall tiles in Hell.

**To Reproduce**
1. Load the attached saved games
[single_1_hellTileBug.zip](https://github.com/diasurgical/devilutionX/files/6526958/single_1_hellTileBug.zip)

2. Turn on the automap

**Expected behavior**
Automap shows wall segments

**Screenshots**
![tile automap bug](https://user-images.githubusercontent.com/39627597/119236927-1916f700-bb08-11eb-968e-e307f67dd2a6.jpg)

![tile automap bug 2](https://user-images.githubusercontent.com/39627597/119237634-d5be8780-bb0b-11eb-870f-decbd3b76960.jpg)

edit: I encountered this with another, different wall segment. Updated post.

**Comment by Chance4us** [comment]
If you mean that corner on the automap that I've marked below, it's a vanilla bug.
![vanilla](https://user-images.githubusercontent.com/45902449/119240770-49838300-bb52-11eb-8e6f-d7102991f31f.png)

**Comment by qndel** [comment]
First one is not an automap as you can't physically enter that corner.

**Comment by sumyunggai** [comment]
> 
> 
> First one is not an automap bug as you can't physically enter that corner.

I think it is, in that if there's a barrier to movement (i.e. wall) it should be represented in the automap. The game doesn't require that you hug all the tiles of a wall to render them on the automap.

There may be something wrong with the tile in this case as well.

**Comment by FitzRoyX** [comment]
These both appear to be fixed. I don't know what PR fixed the first one, but the second screenshot was fixed by #6555 I believe.
