### ISSUE TITLE
Holding down the left ALT key prevents mouse commands

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2044]
Holding down the left ALT key prevents mouse commands.

How to reproduce:
1. Start or load a game
2. Hold the left ALT key down
3. Try to walk in any direction

Effect:
The hero is not able to walk

Side effect:
If you hold down the left ALT key and any mouse button at the same time, you should no longer to be able to move the mouse cursor.

**Comment by julealgon** [comment]
I can't repro this on master. The only thing ALT does is disable wall transparency when held but mouse works just fine. What version are you using?

**Comment by Chance4us** [comment]
> I can't repro this on master. The only thing ALT does is disable wall transparency when held but mouse works just fine. What version are you using?

Latest master on linux.

**Comment by Chance4us** [comment]
I'm sorry. I found that it is a desktop related issue caused by the following setting:

![alt](https://user-images.githubusercontent.com/45902449/119275591-405bea00-bc16-11eb-8cca-d4fdc6f62eb7.png)

Translation:
To move a window, hold down the following key while clicking: Alt

**Comment by nddipiazza** [comment]
instructions to fix Ubuntu - and Linux mint

`Menu` -> `Windows`

![Image](https://github.com/user-attachments/assets/712d5e0c-2f45-4cda-8ccb-565de4ff4674)

close and re-open diablo
