### ISSUE TITLE
Translation(s) : Text, Strings & Coherence

### ISSUE THREAD

**Issue by inukaze** [diasurgical/devilutionX#2053]
Hi there, i had update from src some minutes ago, well i open the PoEdit for continue my Spanish translation. but now i got the follow errors

First : 
Mon 24 May 2021 17:08:57 -04: textdat.cpp:609: attention: empty msgid. It is reserved by GNU gettext:
Mon 24 May 2021 17:08:57 -04: gettext("") returns the header line with the.
Mon 24 May 2021 17:08:57 -04: meta-information, not an empty string.

![Scrot_2021-05-24|05:09:16_pm](https://user-images.githubusercontent.com/1647332/119408008-07258780-bcb3-11eb-9e59-3434af584862.png)

Second : On the lines, PoEdit ID 892 & 893 
Error: 'msgstr' is not a valid C string format, unlike 'msgid'. Reason: The string

![Scrot_2021-05-24|05:12:11_pm](https://user-images.githubusercontent.com/1647332/119408116-33d99f00-bcb3-11eb-96cc-09ba2c004463.png)

3:
And well some weapons names, like "Iron Bow" on spanish must be "Arco de Acero" but i just found a word for "Iron" and another word for "Bow" inside the translations in PoEdit.

4:
Well i hope in future src updates, you can add some missing characters like : 
¡ (this is not an " i " is a exclamation start, the opposite of  " ! " exclamation end, on spanish )
¿ ( start question on spanish, the opposite of ? , end question, on spanish )
Ñ ( n with above tilde, the english equivalent may be "GN" for example on words like "Gnome" )

**Comment by AJenbo** [comment]
First of all try to limit it issue to a single problem.

> Well i hope in future src updates, you can add some missing characters like :
> ¡ (this is not an " i " is a exclamation start, the opposite of " ! " exclamation end, on spanish )
> ¿ ( start question on spanish, the opposite of ? , end question, on spanish )
> Ñ ( n with above tilde, the english equivalent may be "GN" for example on words like "Gnome" )
> 
> On this screenshot the spanish word for child is "niño" because pepin is talking about wirt.

You have mentioned this multiple times, and the answer remains the same. We are working on it, it will be part of the next release. Please be patient.

**Comment by AJenbo** [comment]
> 3:
> And well some weapons names, like "Iron Bow" on spanish must be "Arco de Acero" but i just found a word for "Iron" and another word for "Bow" inside the translations in PoEdit.

Item names are generated, there are about 250000 possible combinations, so providing them directly in the translation file is not feasible. We will let you swap the or of the prefix and item name by translating `{prefix} {itemName}` in to `{itemName} de {prefix}`. This will probably happen in the next week or so. However this isn't flexible enough for some languages so eventually there will the an option to provide a Lua script that defines how exactly item names should be generated.

**Comment by AJenbo** [comment]
> Error: 'msgstr' is not a valid C string format, unlike 'msgid'. Reason: The string
> 
> ![Scrot_2021-05-24|05:12:11_pm](https://user-images.githubusercontent.com/1647332/119408116-33d99f00-bcb3-11eb-96cc-09ba2c004463.png)
 
Please provide the text version of the message so that I can search for it like I asked on chat. I cannot search for images in code.

**Comment by julealgon** [comment]
Please add some mention of "spanish" to the title on this PR.

**Comment by AJenbo** [comment]
Found the text for the two offending lines by updating the Italian translation since it has all strings translated.

**Comment by inukaze** [comment]
> First of all try to limit it issue to a single problem.
> 
> > Well i hope in future src updates, you can add some missing characters like :
> > ¡ (this is not an " i " is a exclamation start, the opposite of " ! " exclamation end, on spanish )
> > ¿ ( start question on spanish, the opposite of ? , end question, on spanish )
> > Ñ ( n with above tilde, the english equivalent may be "GN" for example on words like "Gnome" )
> > On this screenshot the spanish word for child is "niño" because pepin is talking about wirt.
> 
> You have mentioned this multiple times, and the answer remains the same. We are working on it, it will be part of the next release. Use the proper characters in your translation, when we implement the fonts in the game the texts will appear correctly. Please be patient.

i am patience, because of that i say "i hope in future src updates". 

> 3:
> And well some weapons names, like "Iron Bow" on spanish must be "Arco de Acero" but i just found a word for "Iron" and another word for "Bow" inside the translations in PoEdit.
> 
> Item names are generated, there are about 250000 possible combinations, so providing them directly in the translation file is not feasible. We will let you swap the or of the prefix and item name by translating {prefix} {itemName} in to {itemName} de {prefix}. This will probably happen in the next week or so. However this isn't flexible enough for some languages so eventually there will the an option to provide a Lua script that defines how exactly item names should be generated.
> 

Thanks for the information

> Please provide the text version of the message so that I can search for it like I asked on chat. I cannot search for images in code.

Like look in the above line of image, below of line say "Second :" 
`Error: 'msgstr' is not a valid C string format, unlike 'msgid'. Reason: The string`

almost ever time i share a screenshot like that i share the text too, well yesterday i just forgot paste the text, because discord take too much on my machine for do something, because wait hours for share the screenshot, make me forget i not had paste the text of error msg.

**Comment by AJenbo** [comment]
We needed the needed text (`+{:d}% light radius` and `-{:d}% light radius`), not the error message.

**Comment by inukaze** [comment]
Updated & Fixed, Thanks

**Comment by muzena** [comment]
@AJenbo 
Where it must be copied devilutionx.mo file in linux, to test translation?
I try to copy in:
/usr/share/locale-langpack/hr/LC_MESSAGES
and
/usr/share/locale/hr/LC_MESSAGES
but devilutionx is not localized.

**Comment by AJenbo** [comment]
@muzena you really shouldn't hijack issues for support questions. Either crease a discussion or ask on the chat. But first check the translation guide: https://github.com/diasurgical/devilutionX/wiki/Translation-Guide#step-3-testing

**Comment by licaon-kter** [comment]
Still seeing the light radius error here, what was the fix exactly?

 ![](https://i.imgur.com/W4rYJz8.jpg)

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/68249d07e3e2bc6d490077c0d9e32a38fc8b8fbf

We removed some after refactoring the function, might need to add it again.

**Comment by inukaze** [comment]
Interesting well i just testing my own spanish translation (again) XD for just using the limit the version of Devilution 1.3.0. 

The next year (on January) i will test with friends on intranet gameplay after of that i share my definite version of spanish translation

**Comment by AJenbo** [comment]
@licaon-kter I reapplied the fix, thanks for making me aware of the issue.
