### ISSUE TITLE
Shrine effects stay after New game

### ISSUE THREAD

**Issue by CaptainCosmotic** [diasurgical/devilutionX#2058]
**Important information**
Windows 10/ DevilutionX version 1.2.1  / I did download a release

**Describe**
In Vanilla Diablo the effects of Gloomy Shrine and Weird Shrine are lost when starting a new game. This is not the case in DeviltuionX.
I love it since it gives me a possibility to get my Godly Armor of the Whale to a high AC but it's just not vanilla. I suggest making it an option in the config.
 

**To Reproduce**
1. Find a Gloomy Shrine or a Weird Shrine. 
2. Let the Shrine enhance your weapons/armor
3. Start a new game
4. See the effects stay
![35AChollydefender](https://user-images.githubusercontent.com/57239116/119497465-e61d6f00-bd64-11eb-8f01-97f0fdff2fee.jpg)

**Comment by AJenbo** [comment]
The effect not staying after starting a new game was a limitation of the way items where handled original. This having been fixed is mentioned in the release note of 1.2.0/1.2.1

**Comment by CaptainCosmotic** [comment]
I read the whole changelog before and couldn't find it. Sorry for the post then.

**Comment by AJenbo** [comment]
No worries. The change log for 1.2.0 is extremely long and to keep it from being even longer something are a bit generically formulated.
