### ISSUE TITLE
Screenshots VK_SNAPSHOT

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#206]
Screenshots VK_SNAPSHOT key is always stolen from the desktop environment and taken from the desktop screenshot tool, so no screenshots are possible.

Probably it should be possible to reassign the key or to do something else.

**Comment by AJenbo** [comment]
This is an issue with your OS

**Comment by Chance4us** [comment]
I do not understand that.
Why should it be a problem with a current Debian 10 operating system and a current Mate desktop environment?
Does a Debian 10 and a Mate Desktop environment not conform to a modern popular operating system? I think the goal of DevilutionX is to work with modern hardware under a modern operating system. If not please correct me.
Why we don't leave room for improvements?

**Comment by AJenbo** [comment]
Mate grabs the keypress before it hits the application so we never see it and there is nothing we can do. If you want to use the in game screen shot function you have to disable that function from your OS.

It already works on desktops that do not grab the screen shot key.
