### ISSUE TITLE
Pause is displayed smaller and not centered

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2062]
Pause is displayed smaller and not centered since commit 6acb49bea4cc3a1ea77bad73bfa7a831e7ae3fbf.

![pause](https://user-images.githubusercontent.com/45902449/119563455-db37fe00-bda7-11eb-8c2b-16de73c0d87f.png)

**Comment by julealgon** [comment]
Wait, isn't the screen supposed to be red when paused as well?

**Comment by Chance4us** [comment]
> Wait, isn't the screen supposed to be red when paused as well?

It is supposed to be red only in dungeon. In town it is not supposed to be red. Only the text is no longer entirely correct.

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/119569909-b21b6b80-bdaf-11eb-9a6b-cd7bf7c40577.png)
devilutionx 640x480

**Comment by julealgon** [comment]
> It is supposed to be red only in dungeon. In town it is not supposed to be red.

Interesting. I never noticed that detail. Thanks for clarifying @Chance4us .

**Comment by Chance4us** [comment]
@julealgon Don't mention it. You are welcome!
