### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2071]
I have noticed that we have a fairly big Korean user base, but no one has started work on a Korean translation.

We still haven't started work on the necessary fonts, but it might still be a good time to work on it as there is a lot of text to cover.

If you are interested in working on this please see:
https://github.com/diasurgical/devilutionX/wiki/Translation-Guide

And maybe contact us via the chat (see readme) if you have any questions.

**Comment by AJenbo** [comment]
@british-choi @sana2dang I have heard that you guys have worked on similar translations for other games, is this something that you might be interested in working on?

**Comment by qqkookie** [comment]
I volunteer unless other suitable people are not interested. Is it right to translate the Translation/devilutionx.pot?

**Comment by british-choi** [comment]
> @british-choi @sana2dang I have heard that you guys have worked on similar translations for other games, is this something that you might be interested in working on?

Sorry, I am busy now. so I will support other developers.

**Comment by AJenbo** [comment]
@british-choi thanks for the reply :)

@qqkookie that would be great, yes that is the translation template.

**Comment by qqkookie** [comment]
I worked on Korean translation for three days.  And current progress is about 4-5% of all quest/gossip  messages, so I guess  that it will take a month or so. long way to go.

**Comment by AJenbo** [comment]
> I worked on Korean translation for three days. And current progress is about 4-5% of all quest/gossip messages, so I guess that it will take a month or so. long way to go.

Thanks for the update. Feel free to submit the changes gradually, that way others can follow the progress and give feedback. Maybe some will even help out with other parts of it.

**Comment by nsm53project** [comment]
I have Korean translation data of Diablo that I translated 10 years ago(HaHa). I want to provide it soon.

The word order of Korean and English is different. I wonder how the combination of item names works in devilutionX.

**Comment by AJenbo** [comment]
We do provide an option for simple swapping of prefix and item name, but for more advanced rules we will eventually add support for generating names via lua script.

**Comment by nsm53project** [comment]
When will you start working on the necessary fonts? All characters are displayed as '???'.

**Comment by AJenbo** [comment]
We are already looking in to way of generating the needed fonts, but it won't land till after Extended Lating and Cyrillic, which I hope will be done this month.

**Comment by uwodb** [comment]
> When will you start working on the necessary fonts? All characters are displayed as '???'.

hangul font? I remember a question I asked 2 years ago :) I'll comment on your tistory,

**Comment by AJenbo** [comment]
In addition to the game texts we will also need to translate the install instructions for the Android port, it's just 9 strings so not as much work to do :)

Template: https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values/strings.xml

Translation file: https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/values-ko-rKR/strings.xml

**Comment by AJenbo** [comment]
Thanks

![image](https://user-images.githubusercontent.com/204594/127748659-8b92c775-b70b-4858-970b-756a368ad048.png)

**Comment by AJenbo** [comment]
Here is a preview of the game with Korean translation and font:
![image](https://user-images.githubusercontent.com/204594/134643282-e811d480-8e82-4bc6-9886-cf62374f4f24.png)

**Comment by bcko** [comment]
@AJenbo the game with Korean translation looks pretty good! :+1:

**Comment by uwodb** [comment]
nice work!

**Comment by AJenbo** [comment]
It's now possible to test the translation in-game using the latest test build and this mpq: [devilutionx-font.zip](https://github.com/diasurgical/devilutionX/files/7229029/devilutionx-font.zip)

There is still some work being done to improve the look of the font (which is why it currently isn't included by default), so things may still change.

If you have time to update the translation that would be really appreciated as we are planing to do a release next month :)

**Comment by british-choi** [comment]
"Gillian the Barmaid" -> "여바텐더 질리언"
"Pepin the Healer" -> "치료사 페핀"

**Comment by bcko** [comment]
@british-choi Feel free to open a pull request to update the translation file. Thanks!

**Comment by nsm53project** [comment]
Diablo 3 official Korean font. Unfortunately, it's not free. 


![d02](https://user-images.githubusercontent.com/85224046/135646738-a395f692-dc66-40ed-8d23-3fd3f1b2e7c6.jpg)
![d01](https://user-images.githubusercontent.com/85224046/135646780-8564c7aa-b904-4be2-908e-fe457d121649.jpg)

**Comment by nsm53project** [comment]
@AJenbo There are not many Korean free fonts that fully support the Korean Unicode(UTF-8) 11,172 characters, only support 2,350 characters in EUC-KR. 

In general, Korean is used within the EUC-KR range, so even if all 11,172 characters are not displayed, it's not a problem.

No Koreans use 갃(EAB083), 갴(EAB0B4) or out of EUC-KR like that :)

**Comment by AJenbo** [comment]
> No Koreans use 갃(EAB083), 갴(EAB0B4) or out of EUC-KR like that :)

Thanks, but I'm not sure what to do with that information :sweat_smile: Are you suggesting to remove the symbols to reduce the size of the font?

**Comment by nsm53project** [comment]
> Thanks, but I'm not sure what to do with that information 😅 Are you suggesting to remove the symbols to reduce the size of the font?

Sorry, my meaning wasn't clear. 

My meaning that If you change Korean font, it doesn't matter if the font contains only 2,350 characters.

**Comment by AJenbo** [comment]
Ok, it looks like they are pretty scattered so I'm not sure it makes much of a difference since we build them one row at a time.

**Comment by AJenbo** [comment]
@nsm53project I just read you blog, let me know if you need help with GitHub. If you prefer you can just post your updated translation (.po) as a file in the comments here and I can push it to the project for you.

We are probably going to work on the renaming Korean fonts this weekend.

**Comment by nsm53project** [comment]
> @nsm53project I just read you blog, let me know if you need help with GitHub. If you prefer you can just post your updated translation (.po) as a file in the comments here and I can push it to the project for you.
> 
> We are probably going to work on the renaming Korean fonts this weekend.

Thank you. Good news :D

**Comment by nsm53project** [comment]
Koreans, we need to discuss whether to use the full translation or transliteration of the names of spell, monter and item.

**Comment by AJenbo** [comment]
The test version of the font is now ready.

You will need the latest test version of the game:
https://github.com/diasurgical/devilutionX/suites/4075258311/artifacts/103659206
(you must be logged in to GitHub to download)

Download and extract the font files so that the `assets` folder is next to `devilutionx.exe`.
https://github.com/diasurgical/devilutionx-assets/archive/refs/heads/main.zip

Note that there are some minor issues with it that still needs to be fixed.

- There are some artifacts caused by low quality scaling
- Some text in the main menu is the wrong color and is missing shadows
- The small font is not textured
- Some punctuation like `。` is not aligned correctly

These issues will be added in the coming week, but you should still be able to get a good feeling for how the translation looks in-game.

![image](https://user-images.githubusercontent.com/204594/137615425-7be50b2b-6729-41db-8de5-4d0bf182c119.png)
![image](https://user-images.githubusercontent.com/204594/137615427-c5c30af1-4ca2-4b4b-8e79-3f844fd7d72a.png)
![image](https://user-images.githubusercontent.com/204594/137615430-85b8a209-d817-4ea1-acf9-4d6b58c52068.png)

**Comment by AJenbo** [comment]
Just to keep every one in the look, here is the state of things:

![image](https://user-images.githubusercontent.com/204594/142749756-c1fbd46d-b290-4353-af62-28326221666c.png)
![image](https://user-images.githubusercontent.com/204594/142749769-d43df63a-88c3-436b-989b-e1adff5bb1b5.png)
![image](https://user-images.githubusercontent.com/204594/142749824-95c74db5-64a4-4545-a8eb-4995db90bf43.png)
![image](https://user-images.githubusercontent.com/204594/142749838-876d9f4b-293a-49c5-97bf-7f32dbf4bbd1.png)

On top of that it should soon be possible to start translating the items in to Korean as well :)
Once that is ready I will close this issue as the translation has advanced enough to be considered generally useful :+1:

**Comment by nsm53project** [comment]
Text cut off

![a](https://user-images.githubusercontent.com/85224046/142767490-f5135c30-ff5c-4260-8d13-94e683a27175.jpg)
Delete Single Player Hero
싱글 플레이어 영웅 삭(제)

![image](https://user-images.githubusercontent.com/85224046/142767552-dcb01c9a-b3c2-49f2-9f3f-ba6d9f76736a.png)
Delete Multi Player Hero
멀티 플레이어 영웅 삭(제)

**Comment by AJenbo** [comment]
You are running an older build, this issue was fixed in 3e1ea708a9a1ae0c55705626dbda1e236274351c a couple of days ago.

**Comment by AJenbo** [comment]
@nsm53project should we look into also have the game voiced in Korean?

**Comment by nsm53project** [comment]
> @nsm53project should we look into also have the game voiced in Korean?

I have no idea about it. I'm not a voice actor. :D

**Comment by AJenbo** [comment]
@nsm53project
Are you on Discord? Would be interesting to talk about what options there would be for doing it.
