### ISSUE TITLE
Android required fixes in progress

### ISSUE THREAD

**Issue by KonstantineLazarenko** [diasurgical/devilutionX#2089]
This is a list of problem needed to be fixed before Android builds will work correctly.

- [x] SDL_GetPrefPath isn't returning the correct directory - it is returning the path to the APK directory which is owned by root.
- [x] SDL_GetBasePath is returns null on Android so should not be used in init_archives(). Instead we need a way to get the external storage directory, the path here may vary on different devices so some research is required.
- [x] The app should request access to the external storage so that we can load DIABDAT.MPQ from there.
- [x] Touch events are not currently recognized on Android. This might have been disabled when Vita support was merged.
- [x] FreeType is currently committed to the git tree in https://github.com/diasurgical/devilutionX-android/tree/master/freetype. Instead it should be build from the folder included in SDL_ttf.
- [x] Integrate SDL_audiolib into project.
- [x] prepare.sh (downloads SDL src) should be ported to CMake
- [x] SDL_audiolib needs to be told where to find the SDL src.

**Comment by AJenbo** [comment]
Build error for SDL_audiolib when building after rebasing on master:

```
/home/ajenbo/code/devilutionX/CMakeLists.txt : C/C++ debug|x86 : CMake Error at /home/ajenbo/code/devilutionX/android-project/app/.cxx/cmake/debug/x86/_deps/sdl_audiolib-src/CMakeLists.txt:207 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

/home/ajenbo/code/devilutionX/CMakeLists.txt : C/C++ debug|x86 : Configuration failed.
executing external native build for cmake /home/ajenbo/code/devilutionX/CMakeLists.txt
/home/ajenbo/code/devilutionX/CMakeLists.txt : C/C++ debug|x86 : CMake Deprecation Warning:
  The 'cmake-server(7)' is deprecated.  Please port clients to use the
  'cmake-file-api(7)' instead.
```
