### ISSUE TITLE
[Bug] Church loading screen when entering other dungeons

### ISSUE THREAD

**Issue by oli25** [diasurgical/devilutionX#2097]
Compared with vanilla game and when u enter area, loading screen should show that area. Right now it always shows church loading screen no matter what area are u entering from town.

**Comment by AJenbo** [comment]
:thinking:

**Comment by oli25** [comment]
Updated this issue. I was actually right, and it applies to all dungeons not only nest

**Comment by julealgon** [comment]
@oli25 I'd suggest using the "bug issue template" next time when opening bugs.
