### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by Magissia** [diasurgical/devilutionX#212]
Would be nice to have proper packaging files (deb, rpm, and makepkg for Arch) in the repo.
Running binaries outside of path supposed to hold said binaries is meh, and adding them manually, outside of the package manager sight is meh.

I understand it would be low prio, but has to be kept somewhere.

May be related to #167, but AppImage has it's own set of problem. (Cannot execute on hardened  systems)

**Comment by AJenbo** [comment]
We have talked about using CPack

**Comment by MBeijer** [comment]
I've been looking at setting CPack up for devilutionX as I've done this for
other projects before. It's rather easy to set up, but anyone that can help
with specifics for their distribution is always helpful.

Keep this issue and assign it to me and I'll refer to it in my upcoming PR.

**Comment by AJenbo** [comment]
We now use CPack for macOS, so would definatly be nice to also have it handle the dep and rpm so we don't have to maintin that seperatly.

**Comment by MBeijer** [comment]
I will have a look at it. Forgot about it tbh

**Comment by AJenbo** [comment]
No worries :) I haven't had time to look at it either.

**Comment by vv221** [comment]
**[./play.it]** can be used to generate Diablo packages for multiple distributions, but is not a replacement for a real devilutionX package for the following reasons:
* the generated packages include Diablo data, not only devilutionX binary
* it needs access to a supported gog.com-provided Diablo installer to generate the packages, other sources like CD-ROM can not be used yet

Still, I think it can be an acceptable alternative for a lot of people ;)

[./play.it]: https://www.dotslashplay.it/en/start

**Comment by AJenbo** [comment]
We now use CPack for Mac and Linux. Windows is a much bigger problem as .msi pretty much requires building on Windows. Maybe it's possible via Wine but the tools do not appear ready. As such this issue will be closed for now.
