### ISSUE TITLE
[vanilla] Thaumaturgic shrine doesn't close all chests

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2126]
As already known, there is a "Thaumaturgic shrine" in the game and it has the following effect.
a) Refills all chests on level with new contents.
b) Message: What once was opened now is closed

Unfortunately, it doesn't close all chests and I've actually known this issue for more than two decades and I'm probably not the only one. But we have had to fix so many worse bugs that I have withheld it until now. 

How to reproduce.
1. Load attached game
2. Touch the shrine next to you
3. Follow the mana potions
4. Notice that the chest next to the last mana potion is not closed

![screen00](https://user-images.githubusercontent.com/45902449/120900771-0556af00-c637-11eb-9fae-ddb766cca79a.png)
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6602980/single_0.hsv.zip)

**Comment by qndel** [comment]
Making a potion path leading to stuff should be the new bug reporting standard <3
