### ISSUE TITLE
Chinese Translation?

### ISSUE THREAD

**Issue by Lywzc** [diasurgical/devilutionX#2133]
I see there is a Chinese translation file but the word choice in it is weird and there are quite some errors.
I wonder, is there anyone working on this? Since we have official translation in D3 and D2R, many terms and names or even passages can be borrowed from them.
Also, why are there spaces between translated characters, and why a few lines do not have them.
I see in the Korean translation issue that there still does not have a font for them. I assume it is the same for Chinese? Especially since it requires much more characters than Korean.

**Comment by AJenbo** [comment]
@M0Rf30 and @Jmgr have done most of the Chinese translation up to this point. I don't know if they are still activly working on translating the rest of the game, but i'm sure they would welcome help in doing so regardless.

Rearding fonts, they are currently limited to basic latin, later this month we expect to add extended latin, cyrillic and then look in to how to generate CJK fonts.

**Comment by Lywzc** [comment]
Thanks for the quick reply. Then I suppose I can start my own translation.
And another question, can I currently define how conbined word should be ordered? Like Prefix Item of Suffix. In Chinese and some other languages like Japanese, You can only use Prefix and Suffix Item.

**Comment by AJenbo** [comment]
You bill be able to swap the order of prefix and item name soon.

For more complex rules you will have to wait for scripting to become a thing

**Comment by tytannial** [comment]
Project has been set. https://paratranz.cn/projects/2306

**Comment by tytannial** [comment]
Do to the original Diablo zhCN locale is awful.....A game translated by machine translation completely in 90s. There' s a lot of work to do. 🤣

**Comment by Lywzc** [comment]
> Due to the original Diablo zhCN locale is awful.....A game translated by machine translation completely in 90s. There' s a lot of work to do.

That's why I think D2R and D3 is a better place to start rather than the original D1 translation. It simply contains too many errors.

**Comment by tytannial** [comment]
> > Due to the original Diablo zhCN locale is awful.....A game translated by machine translation completely in 90s. There' s a lot of work to do.
> 
> That's why I think D2R and D3 is a better place to start rather than the original D1 translation. It simply contains too many errors.


1. 我准备还是调用机翻接口，把暗黑破坏神1的基础文本替换成新的机翻，至少这个版本都比奥美当年的机翻质量高。
2. 根据暗黑破坏神3和暗黑破坏神2重生版校对专有名词。

**Comment by tytannial** [comment]
已经使用新的机翻程序重新机翻了游戏，补全了缺失翻译。但仍需要后续游戏内进行测试寻找问题和人工校对剩下的文本。
总之至少现代化的机翻已经能勉强看懂游戏了。可以在https://paratranz.cn/projects/2306下载最新的文本。

**Comment by AJenbo** [comment]
please submit it here as a po file

**Comment by tytannial** [comment]
> please submit it here as a po file

The pull request should be ready soon. 🎉

**Comment by tytannial** [comment]
> please submit it here as a po file

[zh_CN.zip](https://github.com/diasurgical/devilutionX/files/6882685/zh_CN.zip)

Here is the po file. Still, there is much more work to do. It will take a long time for proofreading. 😣

**Comment by AJenbo** [comment]
Oh, erh are you able to do this as a pull request :) I would prefer that so that you get the proper credit.

**Comment by tytannial** [comment]
> Oh, erh are you able to do this as a pull request :) I would prefer that so that you get the proper credit.

Done. Pull request has been created.

**Comment by AJenbo** [comment]
Closing this task as it can be considered complete at this point with just  regular maintenance required from this point. Thanks for all the work you did on this.

**Comment by tytannial** [comment]
> Closing this task as it can be considered complete at this point with just regular maintenance required from this point. Thanks for all the work you did on this.

You are welcome. Proofreading is on the way and tons of the machine translation mistake will be fixed. yea!
