### ISSUE TITLE
Torn note reconstruction incorrect

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2140]
Since commit 6ce8f1375184d60afcdf2ac47fdb02610d140509 the torn note reconstruction is incorrect.

How to reproduce:
1. Load attached savegame
2. Collect the fragments of the torn note (1+2+3)
3. See the result

Normal behavior:
1. Torn note
![torn](https://user-images.githubusercontent.com/45902449/121594086-e728ee80-ca3c-11eb-8b9c-2ce0a33b6d3a.png)
2. Reconstructed note
![reconstructed](https://user-images.githubusercontent.com/45902449/121594179-00ca3600-ca3d-11eb-8ff5-16cc2d416472.png)

Unusual behavior:
Reconstructed note + Torn note 3
![unusual](https://user-images.githubusercontent.com/45902449/121594279-235c4f00-ca3d-11eb-9dd1-609545efb4db.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6634300/single_0.hsv.zip)

The cause is unclear, just discovered and bisected.

**Comment by AJenbo** [comment]
> See the result

It's not really clear what the incorrect behavior is. Does it always leave you with node 3 or does that depend on the order you pick them up?

**Comment by Chance4us** [comment]
> > See the result
> 
> It's not really clear what the incorrect behavior is. Does it always leave you with node 3 or does that depend on the order you pick them up?

Good point. Just a few minutes. I will test right away.

**Comment by Chance4us** [comment]
Abbreviations legend: rn = reconstructed note, 1 = rn 1, 2 = rn 2, 3 = rn 3
Results according to the collection sequence:
1,2,3 = rn + 2
1,3,2 = rn + 3
2,1,3 = default/normal
2,3,1 = rn + 3
3,1,2 = default/normal
3,2,1 = default/normal
Vanilla: Always default/normal

**Comment by Chance4us** [comment]
The bug can be found in the function CheckNaKrulNotes.
If you restore the original "switch (idx) {" statement, everything works normally again.
