### ISSUE TITLE
Unique items dropped by NPCs should come pre-identified

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#2153]
I'd like to propose a change that makes every unique item dropped by NPCs be pre-identified when dropped, eliminating the need for players to manually identify them (via Cain or scroll).

To me, it seems extremely nonsensical for Griswold to make "Griswold's Edge" and then drop the item without "communicating its attributes to the hero", and forcing him to go to Cain to identify or use a scroll.

This is a simple change but one that I think is intuitive and nonintrusive enough to warrant inclusion in DevilutionX without any sort of toggle.

Quest related items dropped by enemies (like Butcher's Cleaver or The Undead Crown for example) should still need to be identified, as it would not make sense for the hero to know about it's properties upfront.

Auto-identify guide (initial version from @agris-codes):

| Quest | Reward | Game | Drops as ID'd (includes real name or not) | Notes |
| -- | -- | -- | -- | -- |
| The Butcher | The Butcher's Cleaver | Diablo | No | |
| Poisoned Water Supply | Ring of Truth | Diablo | Yes | |
| The Curse of King Leoric | The Undead Crown | Diablo | No | |
| Gharbad the Weak | random non-unique | Diablo | No | |
| Ogden's Sign | Harlequin Crest | Diablo | No | Dialogue makes it clear he should not know the properties. >> Ogden: "Oh, you didn't have to bring back my sign, but I suppose that it does save me the expense of having another one made. Well, let me see. What could I give you as a fee for finding it? Hmmm. What have we here... Ah, yes! This cap was left in one of the rooms by a magician who stayed here some time ago. Perhaps it may be of some value to you."  |
| The Magic Rock | Empyrean Band | Diablo | Yes | |
| Valor | Arkaine's Valor | Diablo | No | >> Cain: "... The nature of this treasure is shrouded in speculation, my friend, but it is said that the ancient hero Arkaine placed the holy armor Valor in a secret vault." |
| The Chamber of Bone | Guardian spell | Diablo | n/a | |
| Halls of the Blind | Optic Amulet | Diablo |  No* | *I believe it is thematically correct for this item to drop as identified, as the theme of "seeing where others are blind" is consistent with this item making its properties self-evident to the player. But, despite feeling this way, it is more rigorous / conservative to assign it a "no". If others feel as I do, I think it would be a good thematic change. |
| Zhar the Mad | random spell books | Diablo | n/a | |
| Black Mushroom | Spectral Elixir | Diablo | n/a | |
| Anvil of Fury | Griswold's Edge | Diablo | Yes | |
| Warlord of Blood | random magic items | Diablo | n/a | |
| Lachdanan | Veil of Steel | Diablo | No | |
| Archbishop Lazarus | Hell lvl 16 | Diablo | n/a | |
| Diablo | n/a | Diablo | n/a | |
| Farmer's Orchard | Auric Amulet | Hellfire | No* |  *Currently it drops as non-magical identified, but doesn't make a lot of sense given the NPC dialogue. >> Lester: "I heard the explosion from here! Many thanks to you, kind stranger. What with all those things comin' out of the ground, monster taking over the church, and so forth, these are trying times. I am but a poor farmer, but here -- take this with my great thanks." |
| The Defiler | Cathedral Map | Hellfire | n/a | |
| Little Girl (Theo Quest) | random magic amulet | Hellfire | No | |
| Grave Matters | opens Crypt tileset | Hellfire | n/a | |
| Jersey's Jersey | Bovine Plate | Hellfire | No | |
| Na-Krul | spellbook | Hellfire | n/a | |
| Reconstructed Note | magic items | Hellfire | No | |

**Comment by sumyunggai** [comment]
As a purist, I like this and think it's reasonable. The fact that it's limited to NPCs _in town_ is the real kicker. That means that Lachdanan's VoS still needs to be identified, so overall this is a very commonsense approach.

**Comment by AJenbo** [comment]
Ogden clearly doesn't know what the helmet left by a wizard does.

**Comment by qndel** [comment]
> Ogden clearly doesn't know what the helmet left by a wizard does.
> 
> Same with the girl when she drops the ring that was stuck to Theodor

what ring?

**Comment by AJenbo** [comment]
Amulet...

**Comment by ChaosMarc** [comment]
> what ring?
https://diablo.fandom.com/wiki/Little_Girl

**Comment by julealgon** [comment]
> Ogden clearly doesn't know what the helmet left by a wizard does.
> 
> Same with the girl when she drops the ring that was stuck to Theodor

Good points. Those could be exceptions, though in case of Ogden, I feel like having it already named `Harlequin Crest` is also arguable then: how does he know it is a "Harlequin Crest"? it should be named as the base type and change the name once identified like other normal unique items.

I don't remember if the ring dropped by the girl is already named before identified. If not, same applies there.

**Comment by sumyunggai** [comment]
I have a slightly different take on this @julealgon; rather than defer to the name "as received", I think it makes more sense to rely on the NPC's text surrounding providing the item to the player. Thinking of the new player experience, that is the (in)consistency your PR addresses, and is probably the better criteria to use for determining what is/is not pre-identified. 

I'll follow up with a suggested list a bit later.

**Comment by julealgon** [comment]
> I'll follow up with a suggested list a bit later.

@sumyunggai did you forget about this agris? Was looking forward to your take.

**Comment by sumyunggai** [comment]
> @sumyunggai did you forget about this agris? Was looking forward to your take.

Thanks for the reminder, see below:

```
QUEST | REWARD | | Game | Drops as ID'd (includes real name or not)
The Butcher, The Butcher's Cleaver, Diablo, No
Poisoned Water Supply, Ring of Truth, Diablo, Yes
The Curse of King Leoric, The Undead Crown, Diablo, No
Gharbad the Weak, random non-unique, Diablo, No
Ogden's Sign, Harlequin Crest, Diablo, No* 
 *Dialogue makes it clear he should not know the properties
>> Ogden: "Oh, you didn't have to bring back my sign, but I suppose that it does save me the expense of having another one made. Well, let me see. What could I give you as a fee for finding it? Hmmm. What have we here... Ah, yes! This cap was left in one of the rooms by a magician who stayed here some time ago. Perhaps it may be of some value to you." 
The Magic Rock, Empyrean Band, Diablo, Yes
Valor, Arkaine's Valor, Diablo, No
>> Cain: "... The nature of this treasure is shrouded in speculation, my friend, but it is said that the ancient hero Arkaine placed the holy armor Valor in a secret vault."
The Chamber of Bone, Guardian spell, Diablo, n/a
Halls of the Blind, Optic Amulet, Diablo, No*
 *I believe it is thematically correct for this item to drop as identified, as the theme of "seeing where others are blind" is consistent with this item making its properties self-evident to the player. But, despite feeling this way, it is more rigorous / conservative to assign it a "no". If others feel as I do, I think it would be a good thematic change. 
Zhar the Mad, random spell books, Diablo, n/a
Black Mushroom, Spectral Elixir, Diablo, n/a
Anvil of Fury, Griswold's Edge, Diablo, Yes
Warlord of Blood, random magic items, Diablo, n/a
Lachdanan, Veil of Steel, Diablo, No
Archbishop Lazarus, Hell lvl 16, Diablo, n/a
Diablo, n/a, Diablo, n/a
Farmer's Orchard, Auric Amulet, Hellfire, No*
 *Currently it drops as non-magical identified, but doesn't make a lot of sense given the NPC dialogue
>> Lester: "I heard the explosion from here! Many thanks to you, kind stranger. What with all those things comin' out of the ground, monster taking over the church, and so forth, these are trying times. I am but a poor farmer, but here -- take this with my great thanks."
The Defiler, Cathedral Map, Hellfire, n/a
Little Girl (Theo Quest), random magic amulet, Hellfire, No
Grave Matters, opens Crypt tileset, Hellfire, n/a
Jersey's Jersey, Bovine Plate, Hellfire, No
Na-Krul, spellbook, Hellfire, n/a
Reconstructed Note, magic items, Hellfire, No
```
In summary, I recommend:
* Ring of Truth should drop ID'd
* Harlequin Crest should require identification (and name not known until ID'd), 
* Empyrean Band should drop ID'd
* Optical Amulet should drop ID'd (see note above)
* Griswold's Edge should drop ID'd
* Auric Amulet should require identification
and I don't remember how the Bovine Plate appears in vanilla Hellfire, but it should also require identification.

**Comment by StephenCWills** [comment]
> ...and I don't remember how the Bovine Plate appears in vanilla Hellfire, but it should also require identification.

This is one of the few things I do remember about Hellfire. It drops unidentified, and I usually left it that way so it wouldn't increase my light radius.

**Comment by julealgon** [comment]
I like your suggestions @agris-codes .  Added your notes to the OP in table form.

As for the Optic Amulet, I think it would make more sense to have it pre-identified if it only had light radius and/or infravision as properties.

I have thought about having "partial identification" as a concept while reading this again... In the case of the Optic Amulet, the "light radius" property would come pre-identified, but the rest would be hidden still. For another issue in the future though.

**Comment by FitzRoyX** [comment]
> To me, it seems extremely nonsensical for Griswold to make "Griswold's Edge" and then drop the item without "communicating its attributes to the hero", and forcing him to go to Cain to identify or use a scroll.

Counter-argument: Griswold is a meathead who would only know that he was making an item with magic potential. Since he's giving it away free, he dgaf to ID it himself. Cain has been watching and is the one who gives the items their name.
