### ISSUE TITLE
[enhancement proposal] Interacting with the door frames

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2158]
Well, what does the topic mean?
Anyone who has played the game for several years or maybe decades will know that in some unfavorable situations the doors cannot be opened.

As an example, below is the picture and savegame for the caves.
To try out the problem, just load the attached game and try to open the door without killing the monsters. You will notice that you are not able to select the door frame and open the door.

Of course, it's not a problem for every hero. Because the rogue or the sorcerer can shoot the monsters from the distance. In the case of the warrior or barbarian, however, it can look very hopeless to open the door.

In situation below, the problem can still be circumvented because the room is spacious,
but there can be no way out if the room is small and full of monsters.

So what could be a possible solution to the problem? Maybe it makes sense to activate the focus on the door frame by pressing the ALT key. Or maybe you have even better ideas?

![door](https://user-images.githubusercontent.com/45902449/121864744-867c0900-ccfd-11eb-8a23-ff229b7ef1b1.png)

Savegame:
[door.zip](https://github.com/diasurgical/devilutionX/files/6646808/door.zip)

**Comment by AJenbo** [comment]
You can if you use a gamepad :D

**Comment by qndel** [comment]
How about extending alt highlighting to objects? ;)

**Comment by ChaosMarc** [comment]
I would love that change as it would also highlight chests being hidden by walls

**Comment by qndel** [comment]
![blockdoor](https://user-images.githubusercontent.com/14297035/121880678-951eec00-cd0e-11eb-9179-b77875abf0de.gif)

**Comment by Chance4us** [comment]
Instead of "potato obj" maybe better "open / close" description ;-)

**Comment by FitzRoyX** [comment]
Even with the monsters gone, it feels overly difficult to select that gate. When you mouse over the top third of it, nothing happens.

**Comment by qndel** [comment]
can you stop comparing stuff to belzebub which doesn't have a single line of code in common with diablo? 🙄 oh geez, 100% different codebase, they don't have the same bug, who would've thought ...

**Comment by FitzRoyX** [comment]
It's just an example of the gate behaving how you would expect with all parts selectable. Good info considering everyone thus far is assuming it's just because the monsters are in front of it?

**Comment by julealgon** [comment]
> When you mouse over the top third of it, nothing happens.

This is bad. I agree it should be fixed regardless of how it works in Belzebub. I think the same thing happens with clicking on stairs, which can be very spotty as well.

**Comment by julealgon** [comment]
BTW, I'd suggest creating a bug as you suggested @FitzRoyX for the spotty mouse hover detection issue and isolate from this one. While they are definitely related, they are essentially 2 distinct issues.

**Comment by obligaron** [comment]
Fixed with #6368

**Comment by Chance4us** [comment]
I suspect that there is a side effect.
The moster health bar is visible on the other side of the walls.
I don't know if it has anything to do with the fix.

![bar](https://github.com/diasurgical/devilutionX/assets/45902449/c7af0d7e-3d6a-4c0f-b252-08b1413160d7)
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/12448222/single_0.hsv.zip)

**Comment by AJenbo** [comment]
@Chance4us hm, could you open a new issue for this. Also are you running 1.5.1-dev og 1.6.0-dev?
