### ISSUE TITLE
PvPGN support?

### ISSUE THREAD

**Issue by ssjkakaroto** [diasurgical/devilutionX#216]
Are there any plans to support playing through PvPGN servers in DevilutionX? AFAIK it already supports the official 1.09 client.

**Comment by qndel** [comment]
no

**Comment by OrangBuangan** [comment]
I don't think devilutionx supports joining the official 1.09 client?

**Comment by VasylSamoilov** [comment]
It would be great to implement PvPGN support, as both products are open-source. Maybe even some kind of closed realm/ladder functionality can be implemented.

**Comment by qndel** [comment]
the difference is nobody has been sued for devilution and we'd like to keep it that way

**Comment by malvarenga123** [comment]
Couldn't DevilutionX be added to PvPGN as a different client (incompatible with vanilla Diablo)?

**Comment by AJenbo** [comment]
Probably there are better options then pvpgn

**Comment by malvarenga123** [comment]
> Probably there are better options then pvpgn

Maybe, but would those other options (whichever they are) be availabe in-game as a Battle.net replacement and with source code available?
I think the key here is that the original code already has everything in place (UI and backend) for using a Battle.net/PvPGN server.

**Comment by AJenbo** [comment]
> Maybe, but would those other options (whichever they are) be availabe in-game as a Battle.net replacement and with source code available?

That would be the point.

> I think the key here is that the original code already has everything in place (UI and backend) for using a Battle.net/PvPGN server.

None of that exists in this project, it is part of external liberties and not the main game.
