### ISSUE TITLE
[Documentation] Add build instructions for Android

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#2167]
Since Android target have been merged into master and added to CI (thanks for that BTW!), it would be beneficial to add needed dependencies and build instructions to [building.md](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md) and/or Github Wiki

**Comment by AJenbo** [comment]
Install Android Studio, open the android-project, wait for it to load press the play button

**Comment by licaon-kter** [comment]
FYI I'm working on the F-Droid recipe now. Builds fine so far but trying to include multiplayer and fix landscape before adding it.
