### ISSUE TITLE
Pause text is not centred correctly if the translated text isn't exactly as wide as the english text

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#2169]
**Important information**
Windows 10 running a build based on DevilutionX/master

**Describe**
The text drawn in the centre of screen while the game is paused is using hardcoded constants based on the width of the english text. If this text is significantly longer or shorter it is quite visibly offset to the left/right of the screen.

**To Reproduce**
1. Run a translated version of the client (or edit https://github.com/diasurgical/devilutionX/blob/3f7ad14306220e9b6f97b07a213a4db21bf9c66b/Source/gmenu.cpp#L42 with a longer string)
2. Start a single player game
3. Pause the game
4. The "PAUSE" text will be drawn in a way that makes it look off-centre.

**Expected behavior**
The text should be centred no matter how long the text is.

**Screenshots**
Current behaviour:
![2021-06-15T215107_DevilutionX](https://user-images.githubusercontent.com/357684/122048714-f933d400-ce24-11eb-824a-77565f682052.png)

Expected behaviour:
![2021-06-15T215147_DevilutionX](https://user-images.githubusercontent.com/357684/122048748-018c0f00-ce25-11eb-9cc9-e431930a528a.png)

**Additional context**
Fixing this requires changing the DrawString call on the highlighted line to use UIS_CENTER and an x position of 0, similar to the way the main menu items are drawn. I'll include a bug fix as part of pull request #2154, mainly logging this as an issue to give context for why I am making that change.

**Comment by julealgon** [comment]
@qndel didn't you mess around with the PAUSE text recently?

**Comment by qndel** [comment]
I don't know how to use translations :P

**Comment by julealgon** [comment]
BTW, I just realized that the original centering is less than idea. Shouldn't we center vertically while taking into consideration the size of the font? It seems like it centers it as if it was 1 pixel tall.

**Comment by ephphatha** [comment]
The existing vertical alignment is based on the vertical alignment of the player in the viewport so the text ends up drawn over the player sprite.
![2021-06-17T084301_DevilutionX](https://user-images.githubusercontent.com/357684/122304763-182b8680-cf49-11eb-88a7-099bcf2bdd2b.png)
I'd love it if the viewport was shifted so the player is drawn a little lower personally, but without that change changing the vertical alignment of the pause text wouldn't look right.

**Comment by julealgon** [comment]
@AJenbo , what's your take on this? I feel like we should consider changing the default vertical alignment to align on the sprite center instead of aligning on the sprite's bottom.

**Comment by AJenbo** [comment]
I would go with what ever Word or Chrome does when vertically aligning text. But also note that the current position is correct and if we change how we align things then we need to adjust all positions to match the current one.
