### ISSUE TITLE
Bug: Binaries can't find "libSDL2_ttf-2.0.so.0"

### ISSUE THREAD

**Issue by jkpubsrc** [diasurgical/devilutionX#217]
Hi!

libSDL2_ttf is installed (`/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0`) but the downloaded binary `devilutionx` still complains about `libSDL2_ttf-2.0.so.0` would be missing:

    ./devilutionx: error while loading shared libraries: libSDL2_ttf-2.0.so.0: cannot open shared object file: No such file or directory

Operating system: Ubuntu 16.04

**Comment by pgielda** [comment]
Can you do "ldd devilutionx" and paste the results?

**Comment by OrangBuangan** [comment]
@jkpubsrc devilutionX is only released for 32bit now, the you have the 64bit version of libSDL2_ttf installed /usr/lib/**x86_64**-linux-gnu/libSDL2_ttf-2.0.so.0

Also, SDL with Ubuntu 16.04 is too old, so make sure you have upgraded to SDL 2.0.5 or later (can be done with Steam).
