### ISSUE TITLE
Android friendly UI

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#2174]
This is besides https://github.com/diasurgical/devilutionX/issues/493

Two big issues for now:
* Orientation
* Keyboard

Orientation:
* for starters should be forced landscape, now splash and video appear in portrait, then everything is black unless rotated to landscape
* I could envision a portrait mode, many Android games have this, it's nicer to be able to handle it one-handed, but this needs a special UI, discussed in https://github.com/diasurgical/devilutionX/issues/493 I guess

Keyboard is used in multiplayer, for server address, password and chat. Currently a landscape keyboard will cover most of the game Ui, also once dismissed it can't be brought up (needs detection of in game fields to trigger keyboard up I guess)

**Comment by licaon-kter** [comment]
DIABLO.INI access: on Android it's not available, without root :) for now, this would need to be put in /sdcard/devilutionx first _(but keep a reference in internal app storage in case the user deletes the external one, and merge them if existing etc)_ so users can edit it as they wish.

Ideally some sort of minimal UI could be made with some toggles for all the options, eg. like OpenMW has: https://omw.xyz.is/images/game_language.png

**Comment by julealgon** [comment]
Can you please open different issues for different problems? Seems like you are conflating a lot of things in here.

**Comment by AJenbo** [comment]
Maybe this intended as an epic?

**Comment by AJenbo** [comment]
See https://github.com/diasurgical/devilutionX/issues/1561 for ingame settings.

**Comment by licaon-kter** [comment]
No idea :))

@julealgon didn't want to polute and just to keep it under a single issues

**Comment by julealgon** [comment]
> @julealgon didn't want to polute and just to keep it under a single issues

If the problems are different, please don't worry about that. It is better to have granular issues so that PRs can be linked to each of them separately and for documentation and discussions reasons.

**Comment by AJenbo** [comment]
Can always create a mile stone or epic to connect related issues.

**Comment by licaon-kter** [comment]
F-Droid is live, one odd thing, regarding the OP, it works fine in portrait orientation too, unusable of course, but the image in on the screen.

One difference, that I know about, is that my local builds were with gradle downgraded to 7.0 from 7.0.2, since my buildserver has not yet been updated, but I wouldn't expect that to affect it.

**Comment by licaon-kter** [comment]
HEAD has forced Landscape, yay :)

**Comment by AJenbo** [comment]
See https://github.com/diasurgical/devilutionX/issues/1195 for resolving the keyboard issues.

> Ideally some sort of minimal UI could be made with some toggles for all the options, eg. like OpenMW has: https://omw.xyz.is/images/game_language.png

The intend is to have the game detect the language on first load, and let you overwrite it in the game setting if you want to force it to a different one.

See https://github.com/diasurgical/devilutionX/pull/2461 for the Android specific screen.

Closing this issue, for tracking the state of the Android port please see: https://github.com/diasurgical/devilutionX/issues/2476
