### ISSUE TITLE
Any plans to support Emscripten maybe a joint effort with diabloweb project?

### ISSUE THREAD

**Issue by ZaDarkSide** [diasurgical/devilutionX#218]
Are there any plans to support Emscripten maybe a joint effort with diabloweb project?
It will be very nice to have all platforms including Web into a single project.

**Comment by qndel** [comment]
I think it's way too early for that, other things have priority over that ;) but later I can't see why not

**Comment by ZaDarkSide** [comment]
Well as this project is based on SDL2 and Emscripten has good support for SDL2 in the future it can became a good target platform.

**Comment by AJenbo** [comment]
This is now tracked by https://github.com/diasurgical/devilutionX/issues/228

**Comment by briancullinan** [comment]
@ZaDarkSide https://github.com/d07RiV/diabloweb
