### ISSUE TITLE
devilutionX command line option

### ISSUE THREAD

**Issue by legluondunet** [diasurgical/devilutionX#219]
Hello,
I tried this command line:
$ ./devilutionx --help
but it launches directly the program.
It would be nice to obtain info or give options to the command line, for example:
-h or --help: list all command line options
-v or --version: show devilutionx version (or git branch/revision/commit)
--data-dir path to diabdat.mpq
etc...

**Comment by cmhobbs** [comment]
I'm sure someone else will get to this before I do but I'm tinkering with this on my local machine.  I hope to also add the [debug switches](https://github.com/diasurgical/devilutionX/blob/master/docs/debug.md) to this output.

**Comment by cmhobbs** [comment]
I did also consider using `Boost.Program_options` as it's used in a 3rd party library but that seemed overkill, plus it doesn't look like boost is being used by anything else at the moment.

**Comment by cmhobbs** [comment]
It looks like no option currently exists for --data-dir so I'll try to implement that.

What's the best way to get the version or git branch/revision/commit?  I assume those would have to be compiled in and/or updated manually each time as part of the release process.  Is there documentation on the release process?

Are there any undocumented command line options beyond the debug switches?  I have not found any yet.

**Comment by OrangBuangan** [comment]
`--data-dir` should overwrite the path returned by `GetModuleFileNameA`

I don't think there is any agreed on way to handle the version, but maybe the one from `VerQueryValueA` should be used

**Comment by cmhobbs** [comment]
Just working on getting the `--data-dir` switch to work and I'll get a PR done for this.

**Comment by cmhobbs** [comment]
I closed PR #234 because I had not yet updated it with the upstream master.  #235 has those changes included.
