### ISSUE TITLE
Picking one of two options is performed in multiple ways in the code

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#2193]
There are a few places in the code where the intent is to pick between two options at random but due to inconsistent implementations it is non-obvious that they have the same intent.

For example, this code gets either +1 or -1 (avoiding the value 0) to use as a tile offset.
https://github.com/diasurgical/devilutionX/blob/4e6870a92fcbffa8f15b82f0a1b7b7edc4b30649/Source/monster.cpp#L2485

Other places also use +1 or -1 (avoiding the value 0), in this case as a rotation direction. This is the same intent as above but a much simpler implementation.
https://github.com/diasurgical/devilutionX/blob/4e6870a92fcbffa8f15b82f0a1b7b7edc4b30649/Source/missiles.cpp#L994

There are other places performing coin flips to determine which branch to take. These usually use a comparison of `random value in the interval [0, 1] != 0`.
https://github.com/diasurgical/devilutionX/blob/4e6870a92fcbffa8f15b82f0a1b7b7edc4b30649/Source/monster.cpp#L2836
With some exceptions, e.g.
https://github.com/diasurgical/devilutionX/blob/4e6870a92fcbffa8f15b82f0a1b7b7edc4b30649/Source/missiles.cpp#L1423

I think it would be worth having a GenerateRndBoolean function for this use case. Probably just a wrapper for `GenerateRnd(2) != 0`, preferably using the generator from #2084.

**Comment by AJenbo** [comment]
If alone :

GenerateRndBoolean ? 1:-1

Else 

if(GenerateRndBoolean && otherSuff)

**Comment by ephphatha** [comment]
Turns out there's a [bernoulli distribution](https://en.cppreference.com/w/cpp/numeric/random/bernoulli_distribution). This would allow replacing calls such as:
https://github.com/diasurgical/devilutionX/blob/43bc08bd63e321505ec4961a9339391f9c3bc9ac/Source/monster.cpp#L3343
with code like:
```cpp
GenerateRndBoolean(double p)
{
    return bernoulli_distribution(rng, p) //rng is a std::mersenne_twister_engine or similar Generator
}

// Get a true value 75% of the time
//GenerateRnd(4) != 0
GenerateRndBoolean(0.75)
```

**Comment by AJenbo** [comment]
Not that we must call RNG identical to the original for thing like item and level generation.

**Comment by julealgon** [comment]
Can't we have a `GenerateRandomFrom<T>(T values...)` that picks from one of N values passed in? That would feel a bit more natural in some cases (like the `-1` and `1` for example).

**Comment by ephphatha** [comment]
Sure, though using varargs is awkward for arbitrary indexing. std::initializer_list is a bit better (still a bit ugly imo, I'd prefer a type that allows for direct indexing instead of incrementing an iterator).

``` cpp
template<typename T>
T ChooseAtRandomFrom(std::initializer_list<T> choices) {
    return choices.begin() + GenerateRndV2(choices.size());
}

ChooseAtRandomFrom<int>({-1, 1});
```
