### ISSUE TITLE
Skipping dialog doesn't stop audio

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#22]
Using the 0.1 release, whenever I skip an NPC dialog the text disappears as expected, but the voice isn't stopped from playing.

**Comment by AJenbo** [comment]
This is a known issue and is mentioned in the release notes. Currently there are a lot of lacking features in regards to the audio side of things. Fixing the audio system in general is the next big milestone.

**Comment by predator8bit** [comment]
Sorry, just noticed it at the known issues as well as the other things I ran into. Everything else is working wonderfully!

I cheated a bit with the fonts by "sudo ln -s /usr/share/fonts/TTF/LiberationSerif-Bold.ttf /usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Bold.ttf" so I didn't have to install all the ms corefonts. I didn't notice any missing text so far.

**Comment by AJenbo** [comment]
Yes that is also a totally valid solution to having the font :) I hope we can eventually find a system agnostic way of locating the font and if not found fall back to the system default serif-font.

Glad to hear things are working as expected :+1:

**Comment by predator8bit** [comment]
Or just ship an open source serif font and use that if the corefonts aren't installed.

**Comment by AJenbo** [comment]
This is now fixed in the latest build, feel free to get from the build server to test it:
https://circleci.com/gh/diasurgical/devilutionX/47#artifacts/containers/0
(devilutionx_linux_x86)
