### ISSUE TITLE
Refactor devilution.DefaultClass::SaveItemPower(int, item_effect_type, int, int, int, int, int)

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2211]
I've selected [**devilution.DefaultClass::SaveItemPower(int, item_effect_type, int, int, int, int, int)**](https://github.com/diasurgical/devilutionX/blob/713abdca8fc78427070d0b2b9b7fe2422c38a8b4/Source/items.cpp#L1695-L2080) for refactoring, which is a unit of **382** lines of code and **7** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping the power parameters into an `ItemPower` struct so the function becomes `SaveItemPower(int, ItemPower)`. `PLStruct` and `UItemStruct` should also be made to be composed of this type to make it easy to pass to the function.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by matheusgomes28** [comment]
If no one is on this yet, I'll make a start tonight. Maybe will get a PR this weekend, depending on how much actual work I have in the upcoming days :smile:

**Comment by AJenbo** [comment]
Go for it :)
