### ISSUE TITLE
Upper half of tall objects not selectable

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#2227]
**Screenshots**
![spotty](https://user-images.githubusercontent.com/57089001/123444792-e5af0880-d59c-11eb-9ac5-1352f8e5b157.png)

**Comment by obligaron** [comment]
I checked it on vanilla. It's the same. 😉

**Comment by julealgon** [comment]
This is actually a big one, leads to some annoying moments. I guess the game will only detect the cursor over the tile having the object or something like that, instead of taking all tiles where the object is rendered on top.

**Comment by AJenbo** [comment]
You can designate it different sizes, but the logic is pretty complicated to read:
https://github.com/diasurgical/devilutionX/blob/master/Source/cursor.cpp#L639

1: select only on exact tile
2: select only on tile +SE, +SW, and +S
3: select on all 4 tiles

Doors have it set to mode 3.
Cleaning this up and adding a new mode for door that also go north might work.

**Comment by julealgon** [comment]
@AJenbo , instead of having different hardcoded modes, can't we just append some sort of "size" data to the objects, and handle it dynamically?

**Comment by AJenbo** [comment]
If only there was some sort of `Rectangle` structure we could use. Though we should also consider that this might cause issues where you can't clear out barrels that are standing behind the door and might block access.

**Comment by FitzRoyX** [comment]
Forgive my ignorance, but why is selection based on a series of boxes and not simply the pixels comprising the graphic?

**Comment by AJenbo** [comment]
Because there are no non-trasparent pixels on the output image, it's just a bunch of pixels in a 640x480 layout.

Doing something like that would require rendering objects to a G-buffer and doing lookups there, which is slow and time consuming to implement.

**Comment by qndel** [comment]
> Forgive my ignorance, but why is selection based on a series of boxes and not simply the (non-transparent) pixels comprising the graphic?

ignorance forgiven this time, next time you shall be fed to the hedgehogs 🤪

**Comment by obligaron** [comment]
Fixed with #6368
