### ISSUE TITLE
Difficulty playing multiplayer

### ISSUE THREAD

**Issue by Lykos6766** [diasurgical/devilutionX#2228]
**Important information**
Win 10 / DevilutionX 1.2.1 / i downloaded release

**Describe**
I followed instructions for install and added all the needed hellfire .MPQ files, 

i changed the settings in the appdata folder, i had my buddy do the same, 

I went to my router settings and set a rule to allow UDP or TCP traffic on port 6112, 

i then created an inbound rule on windows defender firewall allowing traffic on port 6112 UDP (i also troubleshooted to TCP) 

I hosted the game told my buddy what my ip was, they attempted to join, they got this error.

"a connection attempt failed because the connected party did not properly respond after a period of time, or establishe"

We are not on the same network, My buddy tried joining another random ip. same issue. Im not sure what i could be doing wrong, I appreciate the help in advance.

**To Reproduce**
1. Forward Port 6112 on router and computer firewall
2. Host game on computer 1 with password
3. Computer 2 enters IP address and password and attempts to join
4. Above error occurs

**Expected behavior**
Computer 2 joins hosted multiplayer session

**Screenshots**
none

**Additional context**

**Comment by StephenCWills** [comment]
The error message you shared suggests there is still a firewall blocking packets between you and your friend. Based on what you described, I don't see anything obviously wrong with how you've set things up. Off the top of my head, possible causes could include...

* You gave your friend the wrong IP (public vs private)
* Incorrect NAT/firewall rule setup
* Packets are blocked further upstream, such as by your ISP or outbound firewall rules on your friend's network

FYI, DevilutionX only needs TCP port 6112 so you can remove all the UDP rules from your router and firewall.

As this is more of a networking issue than a DevilutionX issue, I'm closing this.

**Comment by AJenbo** [comment]
@Lykos6766 you might want to give the latest test build a try as it has experimental support for ZeroTier build in, which can avoid network issues like this: https://github.com/diasurgical/devilutionX/suites/3085134057/artifacts/70419924
