### ISSUE TITLE
NPCs only talk about 1 thing

### ISSUE THREAD

**Issue by vimino** [diasurgical/devilutionX#223]
After taking an initial _Quest_, talking to NPCs will henceforth show the same two options, even long after completing said _Quest_.
An example is an end-game Character whose current quest is "**Diablo**" and has "**Gossip**" and "**The Butcher**" on every _Talk to_.

![pic](https://user-images.githubusercontent.com/23475800/62495042-c4887780-b7cc-11e9-9a52-9960ca54e20d.png)

PS: This version is updated to the latest commit (884fb45193865bd143f80fa6ef758d76023d8ca3)

**Comment by BF3000** [comment]
https://github.com/diasurgical/devilutionX/issues/195
Well, its not the first time somebody reported this.
Looks like it was fixed already, but old saves are still buggy, so only new game work like it should.

**Comment by AJenbo** [comment]
Actually this also happens with new heroes:
![image](https://user-images.githubusercontent.com/204594/63991832-8e979400-cae9-11e9-97be-b954fb966245.png)
(notice the clever on the ground)

What happens:
0. Start new game with new hero
 - Quest log is empty
1. Talked to the wonded towns man
 - "The Butcher" appears in quest log
2. Killed The Butcher
 - Quest log is empty
3. Move to level 3, talk to Ogden get Leoric quest
 - "The Butcher" appears in quest log

Expected:
 - Leoric appears in quest log

**Comment by AJenbo** [comment]
confirmed for single player, multiplayer, 32 and 64 bit

**Comment by mewmew** [comment]
Verified upstream in https://github.com/diasurgical/devilution/commit/c26ec70434edea223341eb10cfc0535efa886f1e

**Comment by AJenbo** [comment]
This has now been fixed
![image](https://user-images.githubusercontent.com/204594/65003935-d9434980-d8fa-11e9-9d91-cba3e25d7e79.png)
