### ISSUE TITLE
Item shows as hardware cursor when selling items

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2236]
**Important information**
Linux, master, self build

**Describe**
When selling items and hardware cursor is enabled the cursor briefly shows the item you are about to sell.

**To Reproduce**
1. Enable hardware cursor
2. Go to Griswold, enter the sell menu
3. Select an item from the list
4. Notice the mouse cursor change to the item for a few frames before changing back

**Expected behavior**
The cursor should remain the gauntlet

**Additional context**
You do not actually have to confirm the sell dialog to see the issue.

**Comment by julealgon** [comment]
This type of bug... man, I hate it so much. I assume this is related to "let's use the player's `HoldItem` as a sort of buffer to move items around" thing.

**Comment by qndel** [comment]
ez fix, add a field to HoldItem saying "yo, should it display as a cursor or nah?" and don't display shop items as cursor 😆

**Comment by AJenbo** [comment]
`HoldItem` is a regular item so you would be adding it to all items, alternatively you could add it to be player, but boy does it not belong there. Probably it's not to hard to add a `tempItem` variable to the functions that use `HoldItem` as such.

**Comment by glebm** [comment]
@AJenbo Let's merge #2257, which works around the issue by disabling hw cursor for items by default.

**Comment by obligaron** [comment]
This was fixed in #4304 🙂
