### ISSUE TITLE
I get an error when I try to move to the next page, unsure if this is related to the previous pagination issue.

### ISSUE THREAD

**Issue by Blacklion55** [diasurgical/devilutionX#2258]
I get an error when I try to move to the next page, unsure if this is related to the previous pagination issue.
<img width="1180" alt="screen shot 2016-01-12 at 11 46 03 pm" src="https://cloud.githubusercontent.com/assets/638672/12286102/e17e6d9c-b986-11e5-8301-f6b12e58bd00.png">

__Originally posted by @spara in https://github.com/jlord/sheetsee-tables/issues/6__

**Comment by ephphatha** [comment]
Not entirely sure how this ended up here 😅 . Closing as this is an issue from an unrelated project.

**Comment by glebm** [comment]
Looks like a spambot based on this and https://github.com/diasurgical/devilutionX/pull/137#issuecomment-869243787

**Comment by AJenbo** [comment]
I have blocked the user. This one also seams a bit suspicious, can't even delete it which is surprising:

https://github.com/diasurgical/devilutionX/pull/1485#pullrequestreview-693466273
