### ISSUE TITLE
dLight array is saved/loaded twice

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2267]
dLight array is saved/loaded twice

See LoadGame/SaveGameData

https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1194
https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1224

https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1960
https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L1990

**Comment by julealgon** [comment]
What's the underlying issue related to this double save/load? Can you detail the problem it causes a bit more?

**Comment by ephphatha** [comment]
It's effectively dead code when loading/saving in a dungeon as the second read/write tramples the first. It also is redundant for saves made while in town as the light array should be all zeroes, vanilla logic loads non-zero values if they're present in the save which causes bugs/crashes with dodgy saves that devilutionX can handle gracefully.
