### ISSUE TITLE
Refactor OperateFountains to clarify the stat modification logic of TEARFTN

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#2278]
This case in OperateFountains removes a point from an attribute at random and adds a point to a different attribute at random.
https://github.com/diasurgical/devilutionX/blob/3f69faaecfa7069c17e51c05e84f6ddc27e56814/Source/objects.cpp#L4648-L4692

The stat modification logic can be split into a function, then the loop can be refactored so it's expressed as the following steps:
1. Select a random stat
2. Remove an attribute point from that stat
3. Call GenerateRnd in a loop until a different stat is selected
4. Add an attribute point to that stat

**Comment by vlolteanu** [comment]
> 3\. Call GenerateRnd in a loop until a different stat is selected

Selecting a second stat can be done with a single call to `GenerateRnd` without any bias: `rnd = GenerateRnd(3); if (rnd >= prev) rnd++`. That would certainly alter the game's behavior, but would it break anything?

However, generating random stuff in a loop doesn't offer any kind of guarantees on how many iterations are required.

**Comment by AJenbo** [comment]
> Selecting a second stat can be done with a single call to `GenerateRnd` without any bias: `rnd = GenerateRnd(3); if (rnd >= prev) rnd++`. That would certainly alter the game's behavior, but would it break anything?

This should be safe as it happens at game time where RNG sequence doesn't have to be locked to the original implementation.

**Comment by ephphatha** [comment]
> Selecting a second stat can be done with a single call to `GenerateRnd` without any bias: `rnd = GenerateRnd(3); if (rnd >= prev) rnd++`. That would certainly alter the game's behavior, but would it break anything?

`GenerateRnd()` with a non-power of two argument has a chance at returning an unexpected result (see #2206). This could result in a point being removed from a stat and not being added to another stat. It's not a major issue though, it can be avoided by checking for negative results or by using a safer implementation like the functions provided in #2084 or #2261

**Comment by ephphatha** [comment]
This was closed by #2314/#2318 :D
