### ISSUE TITLE
SaveHelper writes unitialised memory to the save file

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#2281]
**Important information**
Win10 / devilutionx from https://github.com/diasurgical/devilutionX/commit/f33f7ae7ebb8583a2bb270b4d27b3f39281a9929 

**Describe**
An optimisation to the SaveHelper constructor means that the backing buffer is left uninitialised. When skipping over unused blocks of memory using SaveHelper::skip the skipped buffer region ends up getting written to file with garbage values. If this save file is then loaded in an earlier version of devilutionx/devilution or vanilla Diablo/Hellfire that version of the game may end up reading the garbage values into areas where it expects structured data.

**To Reproduce**
Using #2270 as an example of the conditions that trigger this bug.
1. Build and run devilutionx from duplicate-dlight
2. Start a new game or load an existing save and navigate to town
3. Save the game and quit
4. Build and run devilutionx from https://github.com/diasurgical/devilutionX/commit/3f69faaecfa7069c17e51c05e84f6ddc27e56814
5. Load the saved game

In this situation the game crashes with an OOB memory read.

**Expected behavior**
The game loads and runs as normal

**Additional context**
This is more visible in debug builds due to memory watchdogs. I think this affects vanilla Diablo but due to how buggy the game already is it seems like the OS allows it to keep on trucking regardless.

**Comment by ephphatha** [comment]
I think a simple fix would be to write 0 to bytes in skip instead of simply incrementing the pointer.

**Comment by qndel** [comment]
An interesting find, I was aware this would happen but thought town didn't care about dLight at all :D

**Comment by AJenbo** [comment]
> I think a simple fix would be to write 0 to each skipped byte in SaveHelper::skip instead of simply incrementing the pointer.

This sound resonable, but maybe we should rename it to `blank`

**Comment by qndel** [comment]
imo we should have both skip and blank to differentiate between regions that aren't used by vanilla at all (and having garbage in them is fine) and regions that we 0 on purpose
