### ISSUE TITLE
DrawMissile code doesn't handle cases where dMissile[x][y] == 0

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#2286]
**Important information**
Operating system / DevilutionX master

**Describe**
The `dMissile[]` array uses `0` and `-1` as flag values (FREE or INVALID from what I can tell) expecting actual missile indexes to be 1-based values. This function doesn't guard against the 0 case so can read before the start of the `missile[]` array and pass garbage data to `DrawMissilePrivate()`.
https://github.com/diasurgical/devilutionX/blob/d7a86330c6e152a287aa245a1a92eea37358ce3f/Source/scrollrt.cpp#L284-L291

**To Reproduce**
1. Same reproduction as #2285 

**Expected behavior**
`DrawMissile()` should check the value is positive (`>0`) before trying to use it.

**Comment by rbrishabh** [comment]
I can help with this!

**Comment by julealgon** [comment]
Is there a real need to distinguish between FREE and INVALID? Which cases exactly would warrant using INVALID instead of FREE, for instance?

**Comment by AJenbo** [comment]
It looks like invalid missiles has been marked for deletion but not yet cleaned up yet and should be taken in to account for the current tick until cleaned up by the next call to `ProcessMissiles()`.
