### ISSUE TITLE
[ARM64/Linux] NPCs have robotic voices

### ISSUE THREAD

**Issue by vanfanel** [diasurgical/devilutionX#230]
Hi!

Maybe I am being a bit too experimental here, but I am running DevilutionX on a Debian 10 system on Raspberry Pi3b+ in 64bit mode (64bit kernel and libs, rootfs coming from Debian 10 aarch64 debootstrap).
I am using latest stable SDL2 (2.0.10) and latest stable SDL2_Mixer and SDL2_ttf, built by me for this ARM64 system.
SDL2 in turn uses MESA here, latest 19.1.3 version, VC4 driver.

The bug consists on wrong voices for the NPC characters: they all seem to have a robotic voice. Sound effects seem to be affected, too. This does not seem to happen main characters voice since I can clearly hear the "I dont have a spell ready" message (are the samples for NPC dialogs any different?)

My main concern here is that SDL 2.0.10 included some changes to the ARM-specific audio resampling code, but I hope this is not the cause.

It does not seem to happen on X86_64.

I am building devilutionX with:
`
cmake -DBINARY_RELEASE=ON -DDEBUG=OFF -DASAN=OFF -DCMAKE_CXX_FLAGS="-march=armv8-a+crc -mtune=cortex-a53" ..`

I saw that @AJenbo had intention to test on ARM64, too, using a Raspberry PI 3, here:
https://github.com/diasurgical/devilutionX/issues/120
So, did you test it? Do you get the robotic NPC voices too with latest GIT?

**Comment by AJenbo** [comment]
Yes I did test it, I didn't observer any issues that weren't on x86_64, the SDL version was 2.0.8 i believe and using HDMI output. One of my friends also tested on a 3b+, I believe using SDL 2.0.9, but I don't remember if there where any speakers connected.

**Comment by vanfanel** [comment]
@AJenbo Thanks for your response. I have just rebuilt SDL2 2.0.10 without ARM_NEON resampling support, and NPC voices are right. This is clearly an SDL2 issue. I already reported a similar issue years ago: https://bugzilla.libsdl.org/show_bug.cgi?id=4186
I was busy to test the supposedly working code, but it seems its still very broken and DOES cause these robotic voices on ARM.
The workaround I use to disable ARM resampling code is editing src/audio/SDL_audiotypecvt.c in SDL2 sources and changing 
`#define HAVE_NEON_INTRINSICS 1`
to
`#define HAVE_NEON_INTRINSICS 0`
The resulting libSDL2 makes devilutionX work perfectly well on ARM64 with no robotic voices and sounds.

I will report this to SDL2 bugzilla, so ARM_NEON code is either fixed or definitively took out.

**Comment by qndel** [comment]
@vanfanel you got me curious, could you record some of the "robotic voices"? :)

**Comment by AJenbo** [comment]
Thanks, going to close this issue since it's not DevilutionX specific.

**Comment by Rolen47** [comment]
This bug has re-appeared in versions 20210603. Here's a video:

https://streamable.com/r2ny4v

Is it because SDL2 was rolled back to v2.0.10
