### ISSUE TITLE
-Question-

### ISSUE THREAD

**Issue by infiniteNo0b** [diasurgical/devilutionX#2308]
hello
could anyone please point the exact dependencies for compiling on windows. i have just setup a clean environment and MVS is asking for alot of missing stuff im not familiar with. i have attacked them below.
PS.. i will not be using discord or achievements. thanks in advanced.

[deps.txt](https://github.com/diasurgical/devilutionX/files/6761534/deps.txt)

**Comment by qndel** [comment]
This is devilutionx, not duckstation ...
