### ISSUE TITLE
Idle the cpu between logic frames

### ISSUE THREAD

**Issue by vanfanel** [diasurgical/devilutionX#231]
Hi,

I have been measuring CPU usage on the Pi3 running aarch64 kernel & libs, with SDL2 on MESA with FOSS drivers (VC4), which is the "future standard" scenario or ARM SBCs.

-I built DevilutionX with `
cmake -DBINARY_RELEASE=ON -DDEBUG=OFF -DASAN=OFF -DCMAKE_CXX_FLAGS="-march=armv8-a+crc -mtune=cortex-a53" ..`
so its really a Release build with no debug code activated.
-SDL2 is of course accelerated, using the GLES2 renderer on the MESA VC4 GLES2 implementation. No X server is running: SDL2 rendering context is using KMS/DRM as any other games/demos on this machine.

-My diablo.ini explicitly disables upscaling:
```
pi@raspi:~$ cat diablo/diablo.ini 
[devilutionx]
upscale=0
fullscreen=1
scaling quality=0
grab input=1
[Diablo]
Intro=0
Gamma Correction=100
Color Cycling=1
Sound Volume=0
Music Volume=0

```

With all that in mind, CPU usage on the menu is a steady ~55% in one core, and in-game it moves between 70%-80%.
The game runs fine: characted movement is smooth, gameplay is smooth too... but I find it hard to believe that the Diablo engine running natively in a Pi3b+ uses SO much CPU even in static situations like the menu or even the credits static picture where its ~50% too.
Comparatively, MYST ME running on Scummvm on the exact same enviroment and with the same "internal" resolution (640x480, which is scaled to full physical resolution of 1360x768 by SDL2 using GLES2 in a relatively low-cpu-usage way) uses ~25%.
I know comparing Diablo engine to Myst engine is apples to oranges, and I take that 640x480 texture uploading takes up some CPU on the Pi, but no so much, and game logic isnt taking up CPU on the main menu, for example.

**Comment by AJenbo** [comment]
The engine runs as fast as the cpu allows it, it will eventually be changed to an either event based or tick based model, but this issue is in no way pi specific.

**Comment by vanfanel** [comment]
That explains it. Good to know! Thanks for the information, I was very curious :)

**Comment by AJenbo** [comment]
There is a conditional sleepfix that can be enabled at compile time. It will sleep the cpu for an abetrary amount of time between each frame and there by lower cpu usage. The reason this isn't enabled by default is that it might slow down the game if the cpu needs more time then the sleep alowes.

If you feel like it you could submit a patch that makes it sleep for 50ms - time of last frame. Then I think it would be safe to enable by default and should lower cpu usage even more on fast systems.

**Comment by vanfanel** [comment]
@AJenbo : I dont know the inner workings of the engine as you do, so even a simple patch like that one could require a lot of understanting on my side...
But wouldnt it be better if the game simply relied on vsync to limit the engine internal speed? In my experience, sleeping for a given amount of time in the game code ALWAYS breaks up framerate, while relying on vsync is a very good idea and the games that rely on vsync run smooth.
SDL_RenderPresent() for example is synchronous if the SDL2 renderer was created with the SDL_RENDERER_PRESENTVSYNC flag. Then, the game CPU usage is limited inside the SDL_RenderPresent() logic, while it waits for vsync.

Maybe I am misunderstanting an DevilutionX runs the game logic in a thread an video in another different thread??

**Comment by AJenbo** [comment]
The engine runs several threads, but only the render should be tied to vsync, the rest should run at regular intervals to keep the game in sync regardless of the render performance.

The sleep isn't strictly to set this interval but more about when to check if it's time to perform the logic.

I think this would be a good first task since there is already a primitive implementation that just needs to be improved and it should be doable in less then 10. Ofcause I might be able to do it faster but it will be a long time before I can get to it since I'm tied up with rewriting the render and several other areas of the code.

**Comment by AJenbo** [comment]
Here is the relevant line in the code:
https://github.com/diasurgical/devilutionX/blob/98ab9b96006060a5a0cb03f3a82c3b21124d64d9/Source/diablo.cpp#L166

**Comment by vanfanel** [comment]
@AJenbo : I have tried exchanging

                        `Sleep(1);`

for 

                   ```
     lastFrameTime = now; 
                        now = GetTickCount() * 1000;
                        Sleep(now - lastFrameTime);

```
Both `lastFrameTime` and `now` are `double`. 
But that just hangs the game once it starts... Any indications, please?

**Comment by qndel** [comment]
ofc it hangs, why are you doing * 1000 :D

**Comment by AJenbo** [comment]
You know what, looking at the current it actually isn't to bad since it's a sleep of 1 ms fore something that waits 500ms and in the meantime processes input events. What also helps is that it appears to be after all pending events have already been processed.

It might be possible to improve it to lower cpu usage even further, but let's enable this for now.

**Comment by vanfanel** [comment]
@qndel ok, now I am simply doing:

 ```
                       lastFrameTime = now; 
                        now = GetTickCount();
                        elapsedTime = now - lastFrameTime;
                        Sleep(50 - elapsedTime);
```

..but the game stalls like it did before.

**Comment by AJenbo** [comment]
The menu runs at full vsync and redraws the whole screen. In game is limited to 20fps despite your screen refresh rate and part of the screen is static, so if you run 60hz then a 3x increase in cpu usage during the menu wouldn't be a surprise.

You say that the credit screen is static, that makes me think you didn't put the font in the right folder, so you aren't able to see the scrolling text.

There are still a lot about the original render that's are non ideal whick is why we are working on rewriting it, this will also help the load during the menu rendering once it's fully done.

**Comment by vanfanel** [comment]
@AJenbo Sorry but where should I put the font? what font? I used the find command on the devilutionX repository clone, and I see no .ttf files included.
Also, no mention to it on Readme.md or in the docs folder.

**Comment by AJenbo** [comment]
Download the release, all the extras and a readme is included there.

**Comment by vanfanel** [comment]
Ah, ok, found the CharisSILB.ttf font file, now I can see the credits sequence.
On X86_64, it looks good, but not on ARM64, where the text rolling is broken: once a text line gets to the upper limit of the screen, text "teleports" down again sometimes.

**Comment by AJenbo** [comment]
I wonder if that could be related to char being singed/unsinged on different platforms. Can you test if this is also the case with the 32bit arm image?

**Comment by vanfanel** [comment]
@AJenbo : I dont have a 32bit ARM system ready, so I need to setup one, but I dont have enough data traffic in my phone account so it will take several days, until someone comes to visit and lends me some traffic.
So, is there a variable or group of variables I can change from char to uint8_t or int8_t to test on ARM64?

**Comment by vanfanel** [comment]
@AJenbo : OK, I finally could setup a 32bit ARM Raspbian system (Latest stable Raspbian based on Debian 10 Buster).

**I can finally confirm that scrolling problems in the credits screen are also present in ARM32 mode.**

**Comment by AJenbo** [comment]
@vanfanel the menu CPU load should now have dropped significantly (tests show a 57% drop). There is still more to be done but at least things should run a bit cooler now :)

**Comment by vanfanel** [comment]
@AJenbo CPU usage on the menu has lowered, yes. But CPU usage on the credits sequence is still VERY high (around 75% on the Pi3b+!)

In game CPU usage is low: around 30%! Nice!
Only the credits sequence remains as an unjustified CPU eater :D

**Comment by glebm** [comment]
@vanfanel Can you see if #352 fixes the credit sequence for you?

**Comment by vanfanel** [comment]
@glebm I have tested it, and it seems to work great! No more roll-backs in the scrolling sequence. CPU usage is still a bit high for what is being done on screen (around 60% according to TOP on the Pi3b+, which is better than previous 75% anyway).
Also scrolling is not smooth, but I guess its because it runs at ~20FPS on a ~60Hz video mode.

**Comment by AJenbo** [comment]
The menu runs at full monitor refresh rate, but it's moving on a 640x480 grid.

**Comment by vanfanel** [comment]
@AJenbo In that case, shouldnt bilinear filtering in SDL2 give smooth scrolls if 640x480 is scaled by SDL2 to the native monitor resolution?

**Comment by AJenbo** [comment]
No, the rendering is done at 640x480 and then scaled afterwards. So there is only 640 lines of persission (we don't do sub pixel rendering).

**Comment by glebm** [comment]
Managed to optimize it a bit more. Interestingly, it is much faster with `-DUSE_SDL1=ON`.

**Comment by glebm** [comment]
@vanfanel Can you please try the latest version from #352 and also try with `-DUSE_SDL1=ON`? Thanks!

**Comment by vanfanel** [comment]
@AJenbo Oh, I understand. Then its as smooth as it originally was on Win95 on a CRT, I guess.

@glebm With latest version, credits just dont appear, only the static background image. Also, CPU usage has gone up to ~65%.
I can not test SDL1 on the Pi3 because x-less SDL1 is broken on it. SDL1 is useless on my platform. I could test on an X86_64 desktop GNU/Linux system, but I am sure you have already tried there.

**Comment by glebm** [comment]
> @glebm With latest version, credits just dont appear, only the static background image.

This is really odd. I can't reproduce that on my Linux desktop. Is there something special about the Pi display setup? Can you repro this on your desktop?

**Comment by AJenbo** [comment]
PI er based off of Debian 9 https://packages.debian.org/stretch/libsdl2-2.0-0

**Comment by glebm** [comment]
I think I know what the problem was. Fix pushed.

**Comment by AJenbo** [comment]
By the way @glebm here is the code changes I did to skip the extra backbuffer stop and blit the menu directly to `surface instead` in case you want to look in to that.
https://github.com/diasurgical/devilutionX/commit/2b244a49e89c5c936923a2036b5fe4004f5a77cf
- `bufferUpdated` to still be checked for when the game is running since it still uses the backbuffer.
- The menu screen needs to be set to black in between the logo video and the first menu frame.

After that is done there should be several other optimizations that becomes possible.

**Comment by glebm** [comment]
@AJenbo Is it faster? We blit many things and it seems like it may be faster to write 8-bit data than 32-bit data

**Comment by AJenbo** [comment]
I haven't had time to benchmark, but we should also convert things at load time of we do this and want to measure performance, the question then becomes what to do with transitions as blirting a transparent black rectangle probably doesn't come for free.
But in any case we will eventually have to make this move to support png sprites. Ofcause we could wait until we have rewritten the game render also.

**Comment by glebm** [comment]
@vanfanel I've fixed performance issues with SDL2 + scaling (#354, already merged, branch rebased). Please try again, should be massively better overall now!

**Comment by vanfanel** [comment]
@glebm Wow!! Thats something!! Scroll is now smooth, no strange movements and low CPU usage (~50%). You really fixed it!

**Comment by glebm** [comment]
Awesome, thanks for testing!

> When a lot of text appears on screen, later on the credits sequence, CPU goes up to 70%, but I guess thats normal when rendering TTF fonts?

Yes, it could be optimized even further but I this is good enough :)
