### ISSUE TITLE
Can't see Hellfire content

### ISSUE THREAD

**Issue by Eckee** [diasurgical/devilutionX#2315]
**Important information**
Manjaro / DevilutionX version 1.2.1 / I installed AUR package: https://aur.archlinux.org/packages/devilutionx

**Describe**
I have required Hellfire files in the directory but I can't see any Hellfire content. I can play the vanilla version with no issues.

**Screenshots**
https://imgur.com/a/Uk1Kpbg

**Comment by AJenbo** [comment]
Please try with the official release: https://github.com/diasurgical/devilutionX/releases

Also it would be helpful if you could run the latest test build with `--verbose` from a terminal and how us the output.

**Comment by Eckee** [comment]
> Please try with the official release: https://github.com/diasurgical/devilutionX/releases
> 
> Also it would be helpful if you could run the latest test build with `--verbose` from a terminal and how us the output.

Oh, I didn't see there was an "appimage" version. It worked. I'm closing this. Thanks.
I couldn't build from github, cmake showed errors that's why I had used AUR.

**Comment by AJenbo** [comment]
Ok, feel free to let us know what your issue with building was, as well as letting the AUR people know that there is a problem with there build.
