### ISSUE TITLE
A horde of enemy golem minions is spawned

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#2323]
**Important information**
Windows 10 / Master

**Describe**
A horde of golem minions in the caves surrounded by a unique gargoyle, game can crash on approach.

**To Reproduce**
1. Load Save File
2. Go down stairs to LVL 12
3. Walk South a bit

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6779106/single_0.zip)

**Comment by obligaron** [comment]
When I reset the level with current master, there are no golems and no crash. Only a pack of gargoyles.
So I think this was fixed with #2312 🙂 

I attached the save game with the reseted level.
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6779219/single_0.zip)

**Comment by julealgon** [comment]
For a second I thought we were talking about the The Hell mod here 🤣
