### ISSUE TITLE
New Iconset for AmigaOS

### ISSUE THREAD

**Issue by samo79** [diasurgical/devilutionX#233]
Copied from:

**Comment by samo79** [comment]
https://github.com/diasurgical/devilutionX/pull/232

I have created an iconset for DevilutionX, both folder and game icon are included.
Fell free to commit it in repository

Link:
http://s000.tinyupload.com/index.php?file_id=03435418993704798118

**Comment by AJenbo** [comment]
You opened the issue in the wron repo, the amiga port is here https://github.com/AmigaPorts/devilutionX/issues/new/choose
