### ISSUE TITLE
Dark one moves strangely when under fire

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2338]
Dark one moves strangely when under fire.
I haven't investigated since when and why it happened.
I cannot add any information about whether other monsters are also affected.
In order to reproduce this movement it is important to leave a little distance and to fire from a distance.
You can see what it looks like on the following video.

https://user-images.githubusercontent.com/45902449/125136224-b35bea00-e10a-11eb-981f-51d2c1dfe168.mp4

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/6793932/single_0.hsv.zip)

I will provide more information a bit later.

**Comment by Chance4us** [comment]
Caused by commit [cada4a5ac4172abecd8b09cd98236325c36ecf4c] Introduce MonsterStruct.IsWalking()

**Comment by AJenbo** [comment]
> Caused by commit [[cada4a5](https://github.com/diasurgical/devilutionX/commit/cada4a5ac4172abecd8b09cd98236325c36ecf4c)] Introduce MonsterStruct.IsWalking()

That commit doesn't change anything, it adds a new function but doesn't apply it anywhere. Is it the next commit that is the issue?

**Comment by Chance4us** [comment]
> That commit doesn't change anything, it adds a new function but doesn't apply it anywhere. Is it the next commit that is the issue?

I bisected and the result was this commit. I'll try again, maybe I wasn't paying enough attention.

**Comment by Chance4us** [comment]
I paid more attention again. It's been happening since following:
commit 0bf39432543ef9fa7b20628a5a7424e000d1d46e Use GetOffsetForWalking in DrawMonsterHelper

**Comment by AJenbo** [comment]
Nice work that makes more sens :)

**Comment by obligaron** [comment]
I will take a look. 🙂 
It seams `_mdir` (monster direction) is changed but the animation isn't. So they don't match. That's why ADL calculates the wrong rendering position.
