### ISSUE TITLE
Broken level generation (catacombs and hell)

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2340]
While testing a clean up I noticed that we appear to have broken some level generation in a subtle way

Using this save from the original Hellfire:
https://github.com/diasurgical/devilutionX/files/5373942/hsv.zip

Hell level 15:
It would have been impossible for the hero to get to this point with out seeing the area south west of where he is standing in this screen shot.
![image](https://user-images.githubusercontent.com/204594/125144803-50288280-e11f-11eb-9b1d-6f44416f017f.png)

Catacombs level 7:
A free floating closed and open door plus two candle sticks just hanging out in the middle of a room.
![image](https://user-images.githubusercontent.com/204594/125144905-bc0aeb00-e11f-11eb-8a15-1e1e573aedaf.png)

If someone could help bisect it it would be appreciated :)

**Comment by Chance4us** [comment]
In the first picture I see that the automap is defective. But when I load the game and go up to level 15, it looks normal.
Do I have to pay attention to something or what exactly differs from the normality?

**Comment by AJenbo** [comment]
Odd, what version are you running? This was with the https://github.com/diasurgical/devilutionX/commit/74584bb02a9e47e8730f6aefdb1f84a24c589c29 and a debug build.

The way i went to level 15 was taking the TP and then the stairs up before diablo get to many hits in.

**Comment by Chance4us** [comment]
In fact you are right. The automap looks broken and a chest is unusually close to the wall.
To be honest, the bug looks like #1506 or something related to it. I'll investigate soon.

**Comment by Chance4us** [comment]
In the first picture the automap is broken by the following commit.
373f1db22edec89860eafdf4a0bb0f7199203b78 If cleanup + bugfixes (#2273)

**Comment by ephphatha** [comment]
Great work tracking that down :D.

https://github.com/diasurgical/devilutionX/blob/e25d287ba97346946d94a6d6f51195fc8dea2e9b/Source/drlg_l3.cpp#L1868
The `145` case (in both checks) should be `134`.

https://github.com/diasurgical/devilutionX/blob/e25d287ba97346946d94a6d6f51195fc8dea2e9b/Source/drlg_l4.cpp#L543
This is missing case `8`

Those were the only two changes to level generation logic I could see, can't guarantee I got everything though 😅. I think this would have a flow on effect to the monster spawns, worth testing after this is fixed.

**Comment by Chance4us** [comment]
The single door is an another issue.

**Comment by Chance4us** [comment]
Bad news for the second picture.
Since the beginning of the Hellfire support the single door and the missing room is an issue.
I tested down to the commit a1281d8 of Jan 23, 2021
and there it was also.

**Comment by AJenbo** [comment]
Interesting, we would need someone to check the original Hellfire, it could be a reroll issue with vanilla

**Comment by Chance4us** [comment]
> Interesting, we would need someone to check the original Hellfire, it could be a reroll issue with vanilla

The room and the door looks normal in vanilla.

**Comment by Chance4us** [comment]
If you load the attached savegame in vanilla it looks like following.
[cross_load.zip](https://github.com/diasurgical/devilutionX/files/6796896/cross_load.zip)
![vanilla](https://user-images.githubusercontent.com/45902449/125195138-a8ad6c00-e254-11eb-9f53-b64436d62547.png)

The same savegame in devilutionx:
![devilutionx](https://user-images.githubusercontent.com/45902449/125195158-b9f67880-e254-11eb-9da7-a895439f53fa.png)

**Comment by AJenbo** [comment]
Good thing DevilutionX supports converting Hellfire saves to the regular Diablo format :D

![image](https://user-images.githubusercontent.com/204594/125204676-b24bc980-e27e-11eb-9932-0ed57c4ba2dd.png)

This one goes back a loooooooong way

**Comment by AJenbo** [comment]
It worked in 0.5.0 :D This is fortunate since prior to that you would have to compile for 32bit which complicates things.

![image](https://user-images.githubusercontent.com/204594/125204773-300fd500-e27f-11eb-8096-339e8d3bccb8.png)

Attacked is the converted save game in case some one wants to bisect between 0.5.0 and 1.0.1:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/6797365/single_0.zip)
The hero is already standing in the location so just loading the game is enough to verity it.

**Comment by Chance4us** [comment]
Caused by commit a1b7b8522a528cc5fd309b4295bbb3aa255bea30

Date:   Thu Jul 11 15:47:26 2019 +0000

    Bugfixes

 Source/drlg_l2.cpp | 10 +++++-----
 Source/drlg_l3.cpp | 30 +++++++++++++++---------------
 Source/drlg_l4.cpp | 10 ++++++----
 Source/gendung.cpp |  4 ++--
 Source/monster.cpp |  6 +++---

**Comment by Chance4us** [comment]
@AJenbo. By the way, a very nice trick to convert the savegame.

**Comment by julealgon** [comment]
Should we split this issue in 2? Seems like we are talking about 2 distinct incidents here.

**Comment by Chance4us** [comment]
> Should we split this issue in 2? Seems like we are talking about 2 distinct incidents here.

I think this is no longer necessary because one of two issues has already been fixed.

**Comment by qndel** [comment]
@Chance4us you are a wizard
![image](https://user-images.githubusercontent.com/14297035/125207696-dfec3f00-e28d-11eb-9e23-e35ccd56ea81.png)
caused by this

**Comment by AJenbo** [comment]
> @AJenbo. By the way, a very nice trick to convert the savegame.

I did have to fudge it a bit since the save was with a barbarian 😅

**Comment by AJenbo** [comment]
@Chance4us thanks for locating this.

**Comment by Chance4us** [comment]
The first case in Hell level 15 needs to be reopened. I commented in the PR #2353.

**Comment by AJenbo** [comment]
Here is a picture of what Level 15 should look like:
![image](https://user-images.githubusercontent.com/204594/125366704-eacece80-e376-11eb-9d64-6341f644a372.png)
(DeviultionX 1.2.0)

**Comment by Chance4us** [comment]
Both issues are resolved. This report can be closed.
