### ISSUE TITLE
3 versions of FindTransparencyValues in: drlg_l1.cpp, drlg_l2.cpp, drlg_l4.cpp

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2348]
I've selected for refactoring 38 lines of code which are duplicated in 3 file(s) ([1](https://github.com/diasurgical/devilutionX/blob/42e2c174acdfc1b0f22e9c4d26a1b9f9c9dde407/Source/drlg_l1.cpp#L1953-L2003), [2](https://github.com/diasurgical/devilutionX/blob/42e2c174acdfc1b0f22e9c4d26a1b9f9c9dde407/Source/drlg_l2.cpp#L2769-L2819), [3](https://github.com/diasurgical/devilutionX/blob/42e2c174acdfc1b0f22e9c4d26a1b9f9c9dde407/Source/drlg_l4.cpp#L1190-L1240)).  Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Write Code Once** guideline rating! 👍 

Here's the gist of this guideline:
- **Why**❓ 
When code is copied, bugs need to be fixed in multiple places. This is both inefficient and a source of regression bugs.
- **How** 🔧 
The 3 versions of `FindTransparencyValues` are identical except for tile ID being checked in the first line. Change the function to take this id as an argument and move the unified version to gendung.cpp to avoid the duplication of code here.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by bcko** [comment]
Hello @AJenbo , I am interested in working on this issue. Thank you for writing an instruction in detail. I will try opening a pull request based on your instruction.

**Comment by AJenbo** [comment]
sounds good, will be looking forward to your pull request

**Comment by bcko** [comment]
> sounds good, will be looking forward to your pull request

#2554 Just opened a pull request. This is my first time contributing to the DevilutionX project. I appreciate your feedback!

**Comment by julealgon** [comment]
Should we consider adding a new label to track technical debt-type issues like this?

**Comment by AJenbo** [comment]
I like the though of that.
