### ISSUE TITLE
Warlord of Blood moonwalking

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#2359]
**Important information**
Master / Windows 10

**Describe**
The Warlord of Blood will sometimes slide around sideways/backwards when trying to move towards the player. Pretty sure this is some kind of newish bug, but if not feel free to close it out

**To Reproduce**
1. Load Save

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6797838/single_0.zip)

**Comment by AJenbo** [comment]
![image](https://i.chzbgr.com/full/8173186304/h1A34C5E0/if-anyone-can-moonwalk-he-can)
