### ISSUE TITLE
Arch linux, Awesome WM - game hangs unless run with strace

### ISSUE THREAD

**Issue by stupid-genius** [diasurgical/devilutionX#236]
Very bizarre issue, but when I run the game as normal, it opens a window but never displays it and then hangs.  I have to kill it, manually.
```
allen@arch-laptop:~/diablo$ ./devilutionx 
DUMMY: SetUnhandledExceptionFilter @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:507
DUMMY: GetSystemInfo @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:573
DUMMY: CreateFileMappingA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:665
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:431
DUMMY: LoadCursorA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:446
DUMMY: LoadImageA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:440
DUMMY: RegisterClassExA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:399
DUMMY: UpdateWindow @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:382
DUMMY: UiAppActivate @ /home/ajenbo/devilutionX/SourceX/DiabloUI/diabloui.cpp:422
DUMMY: GetWindowLongA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:778
DUMMY: SetWindowLongA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:784
DUMMY: SDrawRealizePalette @ /home/ajenbo/devilutionX/SourceX/storm/storm.cpp:705
DUMMY: DefWindowProcA @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:769
DUMMY: SetCooperativeLevel @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:100
DUMMY: SetDisplayMode @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:106
DUMMY: CreateSurface @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:57
DUMMY: CreatePalette @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:42
DUMMY: SetPalette @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:203
DUMMY: GdiSetBatchLimit @ /home/ajenbo/devilutionX/SourceX/miniwin/misc.cpp:270
DUMMY: GetCaps @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:159
DUMMY: CreateSurface @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:57
DUMMY: SDrawManualInitialize @ /home/ajenbo/devilutionX/SourceX/storm/storm_dx.cpp:19
DUMMY: WaitForVerticalBlank @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:116
DUMMY: BltFast @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:136
DUMMY: Unlock @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:209
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  302
  Current serial number in output stream:  303
DUMMY: UiDestroy @ /home/ajenbo/devilutionX/SourceX/DiabloUI/diabloui.cpp:128
DUMMY: SVidDestroy @ /home/ajenbo/devilutionX/SourceX/storm/storm.cpp:430
DUMMY: SDrawDestroy @ /home/ajenbo/devilutionX/SourceX/storm/storm.cpp:688
DUMMY: Release @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:130
DUMMY: Release @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:130
DUMMY: Release @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:240
DUMMY: Release @ /home/ajenbo/devilutionX/SourceX/miniwin/ddraw.cpp:28
Killed
allen@arch-laptop:~/diablo$ 
```

But if I run it with `strace` then it runs fine.

**Comment by AJenbo** [comment]
What version of SDL do you have, and what is your system spec? Can you try compiling the latest code and see if the issue is still there?

**Comment by stupid-genius** [comment]
``
allen@arch-laptop:~/diablo$ pacman -Qs sdl
local/lib32-sdl2 2.0.9-1
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard (Version 2.
    32 -bit)
local/lib32-sdl2_mixer 2.0.4-1
    A simple multi-channel audio mixer
local/lib32-sdl2_ttf 2.0.14-3
    Library that allows you to use TrueType fonts in your SDL applications (Version 2) (32-bit)
local/sdl 1.2.15-10
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard
local/sdl2 2.0.9-1
    A library for portable low-level access to a video framebuffer, audio output, mouse, and keyboard (Version 2)
local/sdl2_image 2.0.4-2
    A simple library to load images of various formats as SDL surfaces (Version 2)
local/sdl2_mixer 2.0.4-1
    A simple multi-channel audio mixer (Version 2)
local/sdl2_net 1:2.0.1-2
    A small sample cross-platform networking library (Version 2)
local/sdl2_ttf 2.0.14-2
    A library that allows you to use TrueType fonts in your SDL applications (Version 2)
local/sdl_image 1.2.12-5
    A simple library to load images of various formats as SDL surfaces
local/sdl_ttf 2.0.11-5
    A library that allows you to use TrueType fonts in your SDL applications
allen@arch-laptop:~/diablo$ 
```
Intel(R) Celeron(R) CPU B815 @ 1.60GHz
16GB RAM
Intel 2nd Generation Core Processor Family Integrated Graphics Controller

**Comment by AJenbo** [comment]
Looks like it could be related to this issue:
https://github.com/SFML/SFML/issues/991

**Comment by kraileth** [comment]
@stupid-genius: Did you test another WM / DE and the issue is specific to Awesome, since you are mentioning that WM explicitly? Just curious.

I'm an Awesome user, too (and a former Archer), so I could try it out on different hardware if that might be helpful.

**Comment by stupid-genius** [comment]
No, I did not.  I mention it specifically because that's specifically what I'm using.  I would be surprised if other software configs were having this issue since it doesn't seem to have been reported and it's such a bizarre issue.

**Comment by AJenbo** [comment]
We run the game on Arch on a regular basis so I would think this is specific to Awesome, until it can be narrowed down to a single component there isn't much we can do about it.

**Comment by AJenbo** [comment]
@stupid-genius does the game work if you run it via strace?

**Comment by stupid-genius** [comment]
Yes.

**Comment by AJenbo** [comment]
@stupid-genius looks like it could be related to using alsa vs pulseaudio. Have you made any changes to you system in this regard?

**Comment by stupid-genius** [comment]
It's been a while, but it is Arch, so I likely had to install the sound system myself.  I likely just did the simplest, quickest thing I could find.

I don't know much about the sound server, but I could check anything you wanted to know.

**Comment by AJenbo** [comment]
I guess you can try running `pulseaudio --version` and `cat /proc/asound/version`. Maybe check if pulseaudio is already running: `pulseaudio`

**Comment by stupid-genius** [comment]
```
allen@arch-laptop:~$ pulseaudio 
E: [pulseaudio] socket-server.c: bind(): Address already in use
E: [pulseaudio] module.c: Failed to load module "module-native-protocol-unix" (argument: ""): initialization failed.

^Callen@arch-laptop:~$ pulseaudio --version
pulseaudio 12.2
allen@arch-laptop:~$ cat /proc/asound/version 
Advanced Linux Sound Architecture Driver Version k4.19.4-arch1-1-ARCH.
allen@arch-laptop:~$ 
```

**Comment by stupid-genius** [comment]
I just ran it again (same way as before), first time since I last posted here and it ran fine without `strace`.  I've since done a full system update, so perhaps it was some package that needed to be updated.  Either way it was a strange issue that isn't happening anymore, so I'm closing this.

**Comment by AJenbo** [comment]
Indeed, good to hear that it's solved
