### ISSUE TITLE
2x2 items cannot be placed in the upper left corner of the inventory

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2366]
Video:

https://user-images.githubusercontent.com/45902449/125354707-6a06d700-e364-11eb-9c4b-a10ad06af4af.mp4

Savegame:
[magic_rock.zip](https://github.com/diasurgical/devilutionX/files/6804297/magic_rock.zip)

**Comment by julealgon** [comment]
Is it exclusive to magic rock? Can you test with other items? Other 2x2 items perhaps?

**Comment by Chance4us** [comment]
I can confirm that it also affects other 2x2 items tested on a book of reflect.

**Comment by Chance4us** [comment]
The issue was introduced with commit fd3893190fc6822ed5676a81feab0a1e72f2452c
