### ISSUE TITLE
Separate entries for better translation

### ISSUE THREAD

**Issue by NikoVP** [diasurgical/devilutionX#2369]
The translation entry for Lightning Spell should be separated from Lightning item prefix. Many inflected languages, mine included will have different cases for both. Another case is the entry for Town Portal which in some inflected languages (Chinese comes to mind) might have different spelling in the case of spell name and portal creator in town.

Example in Bulgarian
Lightning (spell)  - Мълния
Lightning (prefix) - Светкавични

The entries should be separated for better language handling

**Screenshots**

![image](https://user-images.githubusercontent.com/60973634/125384551-5fb30000-e399-11eb-8177-197af8e31604.png)

![image](https://user-images.githubusercontent.com/60973634/125384968-f4b5f900-e399-11eb-8577-a36618461a45.png)

**Comment by ephphatha** [comment]
Would this also apply to "Normal" (difficulty) and "Normal" (game speed)?

**Comment by NikoVP** [comment]
I'd separate the double entries just in case. In Bulgarian it isn't needed but other languages like Russian, Polish, German or Chinese might.

**Comment by AJenbo** [comment]
Spell name are not there own separate translation strings

**Comment by StephenCWills** [comment]
I assume you meant "now" rather than "not"?

**Comment by AJenbo** [comment]
Yep
