### ISSUE TITLE
Camera shifts after Teleporting / phasing

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2377]
When teleporting or phasing, the position of the hero is shifted.

https://user-images.githubusercontent.com/45902449/125682708-554bf186-82c2-45d0-9115-da449d31d5a7.mp4

Savegame:
[teleport.zip](https://github.com/diasurgical/devilutionX/files/6818577/teleport.zip)

It hasn't been investigated since when the issue appears yet.

**Comment by Chance4us** [comment]
In retrospect, it looks more like camera shake.

**Comment by AJenbo** [comment]
@Chance4us on a completely different not I wanted to let you know that I have noticed your reports being improving in quality over the last few months, and also thank you for all the testing you have been doing as well as tracking down the commits for various issues. It has really been invaluable in keeping the project in a good decent state and ensuring that they do not accumulate :+1:
