### ISSUE TITLE
Broken autopause

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2380]
Caused by https://github.com/diasurgical/devilutionX/pull/2337

How to break:
Alt tab out of the game during loading screen
Alt tab back to the game = game gets paused

**Comment by qndel** [comment]
@JoBergeron feeling like poking it? ;p

**Comment by JoBergeron** [comment]
Yeah, I'll take a look at it today or tomorrow!

**Comment by JoBergeron** [comment]
I created a pull request for the fix here https://github.com/diasurgical/devilutionX/pull/2387
