### ISSUE TITLE
Guardians no longer fire

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2382]
Guardians no longer fire since commit 13eb1d9bb4ed11ec7e02cbb81fbf3854767a78e8 Clean up GuardianTryFireAt

https://user-images.githubusercontent.com/45902449/125811787-b5517f50-04dc-48e3-a6a9-02e34781894b.mp4

[savegame.zip](https://github.com/diasurgical/devilutionX/files/6824190/savegame.zip)

**Comment by qndel** [comment]
why aren't you on devilution discord? ;p

**Comment by Chance4us** [comment]
> why aren't you on devilution discord? ;p

Does it make sense to report the issues there too?

**Comment by qndel** [comment]
No, but it's faster to chat :D

**Comment by Chance4us** [comment]
> No, but it's faster to chat :D

OK, I'll consider it next time. ;-)
