### ISSUE TITLE
On ARM it doesn't respect overscan

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#241]
**To Reproduce**
1. Start X on Raspberry Pi B 256Mb via composite video or HDMI
2. See that config.txt overscan is respected and image is complete
3. Start the game

**Expected behavior**
Game is shown on screen completely

**Actual result**
Game image is cut off

![noeversacn](https://user-images.githubusercontent.com/2282799/64473567-c80a7800-d157-11e9-861d-add74c746f94.jpg)

Tried some SDL env vars like CENTER and POS, but did not help, not sure they even apply to SDL2

Is this helpful: https://projects.drogon.net/raspberry-pi/raspberry-pi-and-sdl/ ?

**Comment by AJenbo** [comment]
Are you using upscaling in Deivlution?

**Comment by licaon-kter** [comment]
No combination of upscale and fullscreen help.

**Comment by AJenbo** [comment]
The link doesn't relate to overscan, also I would say that if there is an issue then it's probably with SDL2 or how the PI handels overscan. When upscaling we simply use the current resolution, and else we set the display to 640x480.

The pi in general dosent implement the GPU driver in a nice way and have custome solutions for things like overscan. Other GPS would normally allow you to configure the amount of overscan via the generic randr system tools.

**Comment by licaon-kter** [comment]
I can disable overscan from config.txt too, it gets worse.

I've tested with plain no-GL driver, with fake-KMS and with full-KMS ones.

**Comment by AJenbo** [comment]
This isn't an issue with DevilutionX but an issue with the Raspberry Pi graphics drivers.
