### ISSUE TITLE
[walking/running] Stutter stop regression

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2431]
Stutter stop regression since f4897c31396f9e36416d326931b15173a2d2aa17.

https://user-images.githubusercontent.com/45902449/126217656-c67998f1-c8e1-4a05-8c83-a106857a8f49.mp4

I also got the impression that in some situations the hero stops walking in the dungeon even though the left mouse button is held down. This is likely to happen when pointing to impassable areas.

**Comment by AJenbo** [comment]
@julealgon why assign me :D

**Comment by julealgon** [comment]
> @julealgon why assign me :D

The commit referenced by @Chance4us that caused the issue is yours.

**Comment by Chance4us** [comment]
I'm sorry guys. I didn't mean to cause trouble.

**Comment by julealgon** [comment]
The effort you put in finding these problems is extremely appreciated @Chance4us . If it wasn't for you, I think we'd have a ton of new bugs by now 😅 

Thanks again and please keep doing this!

**Comment by FitzRoyX** [comment]
The video looks like it's trying to demonstrate two different things. The idle animation resetting when clicking on a solid object near your character has been there for ages and may even be a vanilla thing. The stopping and starting while walking when the cursor is close to the char is probably new, but it was an issue in the past.

**Comment by AJenbo** [comment]
The rock thing is just coincidental. The issue is probably related to the following lines:
https://github.com/diasurgical/devilutionX/commit/f4897c31396f9e36416d326931b15173a2d2aa17#diff-4701097b107e2f0033378f375e8431b9a6c0a237c7cbc3deb753d1b700683758R33-R35

**Comment by AJenbo** [comment]
> The commit referenced by @Chance4us that caused the issue is yours.

Fair enough, it needed an overhaul any way: https://github.com/diasurgical/devilutionX/pull/2452

**Comment by Chance4us** [comment]
It feels good now. But I have to test a little more.
