### ISSUE TITLE
Unable to cast some spells, after 12 firewalls have been cast. 

### ISSUE THREAD

**Issue by GiladAmar** [diasurgical/devilutionX#2447]
**Important information**
I'm working on Ubuntu 20.04, with a released version of devilutionX.

**Describe**
Using a sorcerer, I can cast up to 12 firewalls and at that point no more can be created (it seems until some of the active ones die out).
The animation around the Sorcerer still shows, mana is still used, but no wall is created.
Other spells also show the character animation, but do not take affect.
I've found fireball shoots off a fireball maybe once every 4 or 5 seconds.

Some spells such as telekinesis, healing, teleport and guardian are unaffected.
It seemed that anything that is a projectile, or wall (or flame wave), is affected.

It does not appear to be related to where I am at all in the dungeons.

**Comment by julealgon** [comment]
This is a fairly well known issue with the original Diablo, and is related to the maximum number of concurrent sprites handled by the game.

We do intent to fix this at some point.

See here (yours is a duplicate):
https://github.com/diasurgical/devilutionX/issues/768

**Comment by GiladAmar** [comment]
> This is a fairly well known issue with the original Diablo, and is related to the maximum number of concurrent sprites handled by the game.
> 
> We do intent to fix this at some point.
> 
> See here (yours is a duplicate):
> #768

Ah thanks @julealgon.
I did try see if there's a duplicate issue here but clearly wasn't using the right keywords.
Fantastic project btw, I haven't played this in ages and it was awesome.
