### ISSUE TITLE
Mouse pointer visible in the cutscenes

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2448]
At the moment the mouse pointer is visible in the cutscenes.
It has not been investigated since when this is the case and further information will be provided later.

![cursor](https://user-images.githubusercontent.com/45902449/126778857-1981effe-03d8-42e0-95b0-8a1b9321073d.jpg)

**Comment by NikoVP** [comment]
I can also confirm the same issue with the latest builds

**Comment by Chance4us** [comment]
The issue happens since commit f9d20b44d6e05b0a4fb3ab5560c60990a2ba227e
Savegame for testing below:
[cursor_test.zip](https://github.com/diasurgical/devilutionX/files/6870218/cursor_test.zip)
