### ISSUE TITLE
Possible CMake issue when building on Windows with vcpkg and Visual Studio 2019.

### ISSUE THREAD

**Issue by ropufu** [diasurgical/devilutionX#2454]
**Important information**
Windows 10 / master branch / compiled myself with vcpkg and VS 2019.

**Describe**
When compiling, CMake is looking for **SDL2_ttf** and **SDL2** libraries in **mingw** (which I do not have) instead of **vcpkg**. These are the only two libraries that are affected.

**To Reproduce**
1. Follow instructions on https://github.com/diasurgical/devilutionX/blob/master/docs/building.md under "Windows via Visual Studio" > "Using vcpkg (recommended)", and "Compiling" > "Through Open->CMake in Visual Studio" (including running **vcpkg integrate install**).
2. Proceed with building. Installation process halts with
> CMake Error at cmake_install.cmake:52 (file):
> file INSTALL cannot find
> ".../devilutionX/SDL2_ttf-2.0.15/i686-w64-mingw32/bin/libfreetype-6.dll":
> File exists.".
3. When the file is manually copied from vcpkg to the path above, happens again several times for various **SDL2_ttf** and **SDL2**-related files.
4. Manually copying the two libraries (**SDL2**, and **SDL2_ttf**) with appropriate naming adjustments from vcpkg into the devilutionX folder fixes the problem, and installation completes successfully.

**Expected behavior**
I expected the installation to complete successfully without additional actions and manual fixes :^)

**Comment by StephenCWills** [comment]
Ah, I reproduced it. I had to select the `Install DevilutionX` option from the `Build` menu.
![image](https://user-images.githubusercontent.com/9203145/126907911-a7020c63-7b91-4179-820d-35fbabc56d0e.png)

That `cmake_install.cmake` file is generated during the configure step based on calls to the `install()` command. You can see the corresponding `install()` command that's causing the error message in `CMakeLists.txt`, and it's followed up by a few more commands just like it.

https://github.com/diasurgical/devilutionX/blob/ab8afa7cd7e83b7df295cac7956cd6358f068728/CMakeLists.txt#L951-L953

I have no idea if these install commands still work with the mingw build, but they will need to be updated to get the install step working with Visual Studio.

**Comment by ropufu** [comment]
Thanks for looking into it! Also, since it's currently hard-coded into CMakeLists.txt, it would probably be a good idea to keep the library versions (2.0.15, etc) dynamic as well---whatever the latest installed version is, I guess.

**Comment by ropufu** [comment]
Sorry, hit the wrong button. Was trying to discard my previous comment \*^_^\*

**Comment by ropufu** [comment]
If rather than selecting the "Install DevilutionX" from the Build menu one clicks the Green Arrow Button, the compilation succeeds without copy/pasting. Worked for me just now.
![Untitled](https://user-images.githubusercontent.com/4440456/126911082-6edfcd5f-2dac-4907-8163-9052df52b006.png)

**Comment by AJenbo** [comment]
We do not have install instructions for Windows in cmake so this is expected.

**Comment by ropufu** [comment]
May I ask you to update the "Build Instructions" then? At least on my machine, all I had in the Build Menu was the "Install DevilutionX" option---which seemed closer to the
> Select Build devilution.exe from the Build menu.

instruction than **Build Current Document (...)** one.

![Untitled](https://user-images.githubusercontent.com/4440456/126911411-6c66557e-3776-40d3-ae4f-a298bd74733e.png)

**Comment by AJenbo** [comment]
"Build All" is probably the correct option, "All" should cover devilution.exe.

**Comment by ropufu** [comment]
If only I knew how to do that. I'll leave it to a conscientious savvy reader...

**Comment by StephenCWills** [comment]
> At least on my machine, all I had in the Build Menu was the "Install DevilutionX" option

I just cleaned out my repo to start fresh, and indeed it does not have `Build devilutionx.exe` in the `Build` menu.

![image](https://user-images.githubusercontent.com/9203145/126911739-b4bfa1a2-383b-4e51-b669-e611620ad276.png)

The missing step is selecting the startup item.

![image](https://user-images.githubusercontent.com/9203145/126911756-1883cc55-96bc-4e15-ba4e-61ddde53081d.png)

![image](https://user-images.githubusercontent.com/9203145/126911775-d368696d-1783-44c6-8f94-f6ed8a68205e.png)

> May I ask you to update the "Build Instructions" then?

Since this is a simple change to the documentation, it's a good way to get started with contributing to the project. Therefore, I would rather encourage you to update them yourself.

> "Build All" is probably the correct option, "All" should cover devilution.exe.

`Build All` does work as well. At the very least, selecting the startup item allows you to run the game with the debugger.

**Comment by ropufu** [comment]
> Since this is a simple change to the documentation, it's a good way to get started with contributing to the project. Therefore, I would rather encourage you to update them yourself.

Watch me spend a week on figuring out how. But I will try.

**Comment by AJenbo** [comment]
> Watch me spend a week on figuring out how. But I will try.

You can edit it directly in the browser: https://github.com/diasurgical/devilutionX/edit/master/docs/building.md

**Comment by ropufu** [comment]
> You can edit it directly in the browser: https://github.com/diasurgical/devilutionX/edit/master/docs/building.md
Only if I am a developer for this project :^P Otherwise it's PR's for me.

**Comment by AJenbo** [comment]
Editing will create a PR. That's true for developers as well.

**Comment by ropufu** [comment]
> Editing will create a PR. That's true for developers as well.

I phrased poorly. I cannot edit at all. Forking (and later, I'd imagine, pull request) is the only option here.
![Untitled](https://user-images.githubusercontent.com/4440456/126912608-a81adf6e-e96c-4146-8d3b-a44d3741381c.png)

**Comment by AJenbo** [comment]
It sounds like you think this is more complicated than it is, you just need to hit "Fork this repository" and it should take you to the edit page.

Once you have made your changes you go to the bottom of the page and write one line describing the change, then hit a the green button that says "Propose file change".

![image](https://user-images.githubusercontent.com/204594/126913381-53f4f87d-cd53-4c75-b319-2dad58a47a01.png)

It will then show you what you changed and you get to hit a green button that says "Create pull request". That's all there is to it.

**Comment by ropufu** [comment]
Yaay, it took me less than a week! But my solution (https://github.com/diasurgical/devilutionX/pull/2472) was blocked. I'm closing this issue.

**Comment by AJenbo** [comment]
Nice that you are trying to add the support rather then just adding "not supported" to the docs :)

**Comment by ropufu** [comment]
Thank you thank you.

**Comment by ropufu** [comment]
Btw, what's the minimal version of CMake that you would support? I know that you currently have **3.13**; would it be acceptable to push it up (if need be)?

**Comment by AJenbo** [comment]
Afaik 3.13 is required for one or another target... @glebm probably remembers better then I, or at least he remembers the link for the page that lists the state of CMake on various systems :angel:

**Comment by ropufu** [comment]
That was fun.

**Comment by AJenbo** [comment]
Hope you tick around to find other things to improve :)
