### ISSUE TITLE
Floating dialogs

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2475]
See video:
Issue 1a (Floating dialogs):

https://user-images.githubusercontent.com/45902449/127697698-5053a753-06f7-45d9-a0c5-f491562214ca.mp4

How to reproduce:
1. Click on a NPC
2. Click on the ground just before the NPC
3. The timing has to be very precise
4. Before commit fba534de0ac51f182af53899e294b9eda04cb5d0, it was much easier to reproduce, or it's possible that I'm just imagining it

**Comment by julealgon** [comment]
Can you repro this in vanilla as well?

**Comment by Chance4us** [comment]
> Can you repro this in vanilla as well?

I was not able to do that.

**Comment by Chance4us** [comment]
By the way, there is another problem with the mouse control.
Usually I can describe it well, but this time it's not easy. There is a kind of indolence. That means you command to run to a position with a mouse click, then you click again to a second position, but if you click again to a third position, then the hero only walks to the second position.
The specification of the third position is ignored and it doesn't feel like the original diablo. In the original, the hero always followed the mouse clicks. The issues started after working on the mouse routine.

**Comment by Chance4us** [comment]
In general I would like to suggest the following.
For all new changes in the mouse control ti introduce an option, for example, "Experimental Mouse".
Or to provide "Enable classic mouse" as an option for the old mouse routine.
The reason for this is very complex and I would like to describe all the differences in detail step by step.

1. Cancel targeted attack on dead monster
https://github.com/diasurgical/devilutionX/pull/962

Since this feature was introduced, I have experienced the following.
I stood with the hero in front of the "Chamber of Bone" with the many skeletons and chose the spell "Holy Bolt".
Then I opened the door and started firing. Unfortunately, my fire sequence was unexpectedly interrupted and the hero was hit. Since my style of gameplay is more offensive, which means I try to distribute as many punches as possible so as not to get one, I found the interruption very annoying. It's like playing chess. When the game starts the white color dictates what happens. The black must therefore always react and is permanently at a disadvantage. But if the player with white is inexperienced and inattentive, this advantage can slip away and he begins to react instead of acting. This new option felt just as detrimental to my style of play, or at least I had the impression that it had to do with this change.

2. Since the commit f4897c31396f9e36416d326931b15173a2d2aa17 there was problem #2431 which already has been fixed.

But the behavior that I described in the message above was very likely already there, I just couldn't understand it completely and couldn't put it into words, what exactly doesn't feel natural.

Hence my suggestion that all mouse routine changes should be made available as an option,
but also to give the function "Cancel targeted attack on dead monster" an own option. 

All for the reason that the old mouse routine gave the game a special characteristic. But if we're not careful here, the game could eventually feel like it wasn't intended.

I hope that I have expressed myself reasonably understandably.
I would be happy to answer further possible questions.

**Comment by NiteKat** [comment]
Is the cancel targeted attack on dead monster also cancelling spell casts mid animation? What I'm picturing in your chamber of bone incident is you trying to spam cast Holy bolt into the room, but the spell cast being interrupted when the monster dies, allowing time enough for another horror to step into the door way and whack you.

If it can cancel spell animations like that, I can see that option being detrimental when trying to use a door as a choke against a large group of monsters, such as in the Chamber of Bone.

**Comment by Chance4us** [comment]
That's exactly the impression I got.
But I'm not a very good programmer and I don't know how to judge about it.

**Comment by AJenbo** [comment]
It bails before starting the cast, not mid cast.

**Comment by AJenbo** [comment]
>  For all new changes in the mouse control to introduce an option, for example, "Experimental Mouse".

It's not simple to do as there is no distinct point in the code where, things are entangled all over the place. Instead that is what the master vs release offer and you have the option of only advancing by a few commits instead of taking in all changes.

**Comment by AJenbo** [comment]
> chose the spell "Holy Bolt".
> Then I opened the door and started firing. Unfortunately, my fire sequence was unexpectedly interrupted

Try shift+right-click if you want to fire with out interruptions.

**Comment by Chance4us** [comment]
I am also not against keeping all changes, but it would be nice if we rework all problem areas again.
I have discovered a few more and will describe them in detail soon.

**Comment by Chance4us** [comment]
Issue 3:
> There is a kind of indolence. That means you command to run to a position with a mouse click, then you click again to a 
> second position, but if you click again to a third position, then the hero only walks to the second position.
> The specification of the third position is ignored and it doesn't feel like the original diablo. In the original, the hero always 
> followed the mouse clicks.

Issue 3 Example:
To reproduce this, you have to click in front of and behind the hero with a certain frequency. If done right, the hero will only follow in one direction. 

https://user-images.githubusercontent.com/45902449/127734014-0c55305d-788a-4c0e-992c-c80a043db5a1.mp4

**Comment by Chance4us** [comment]
Issue 4 "Door Stuck":
I haven't described this yet.
Your task is to walk from one level entrance to the other.
You you are only aalowed to click once and hold the mouse down.
The hero can get stuck in the door frame. This does not always happen, but apparently always when the mouse pointer briefly hovers over the door frame.


https://user-images.githubusercontent.com/45902449/127734417-f863b533-ef04-4881-884d-bcafe56befc7.mp4

**Comment by Chance4us** [comment]
I think 3 and 4 are a too big change in the game mechanics. I can't call the game classic if i've played differently for 20 years.
But as I mentioned already once, maybe I'm just a too sensitive person.

**Comment by Chance4us** [comment]
EDIT:
The issue 4 does not exist in the master. It only has to do with object highlighting.

**Comment by Chance4us** [comment]
I summarize again for a better overview.
Issue 1a (floating dialogs) is available in the master.
Issue 3 "Mouse input lag / response delay": is available in the master.
Issue 1 "Cancel targeted attack on dead monster" is not that bad.

**Comment by FitzRoyX** [comment]
> Issue 3 Example:
> To reproduce this, you have to click in front of and behind the hero with a certain frequency. If done right, the hero will only follow in one direction.

I'm struggling to see the difference here. The hero will never change direction in the middle of a tile change and never has. I can reproduce this on 1.2.1, before any of these changes were made. If you manage to click backwards and forwards while the hero is mid-tile, the backwards click never has a chance to take effect.

> Then I opened the door and started firing. Unfortunately, my fire sequence was unexpectedly interrupted and the hero was hit.

I think you're imagining things again. Left-click melee targeting specifically was producing pointless swings on a dead target. Spells are right-click actions and go off when you click on anything, that bugfix should've had no effect on spellcasting speed.

**Comment by AJenbo** [comment]
>  I have discovered a few more and will describe them in detail soon.

Don't post them in the same issue, it becomes impossible to deal with them if they are not handled individually

**Comment by Chance4us** [comment]
@FitzRoyX, @AJenbo  It sounds good. So there are left the Issues (floating dialogs)
and maybe would it be worth to try to improve the vanilla issue "Mouse input lag / response delay"?

**Comment by AJenbo** [comment]
Being able to change direction would be nice, despite it actually changing the game. But for that reason and also the changes it introduces I think we should wait with it until 1.4.0, right now i would like to move the focus to finishing 1.3.0 and not introduce more issues till after the release.
