### ISSUE TITLE
enable `command.txt` - "hack" from hellfire

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2485]
**Important information**
used provided 1.2.1 windows binaries

**Describe**
tried to place a command.txt in the game directory to enable hellfire secrets

**To Reproduce**
n/a

**Expected behavior**
activate the hellfire secrets
 - theoquest
 - bardtest
 - barbariantest
 - cowquest
 - nestart
 - cryptart
 - (multitest) -obviously not needed

**Comment by AJenbo** [comment]
Use diablo.ini https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide

**Comment by vladtepesch** [comment]
> Use diablo.ini https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide
oh sorry, I missed this
