### ISSUE TITLE
devilution does not work with username containing `é`

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2492]
**Important information**
used provided 1.2.1 windows binaries

**Describe**
User name contains special character `é` 
It seems that the game has problems with this on creating the user profile data and shows a screen at states it can not write to profile data directory (see screenshot)

A folder `C:\Users\René\AppData\Roaming\diasurgical\devilution`  was created by the game.

Using command line option to set alternative paths is a workaround

**To Reproduce**
1. user name with special characters e.g. `René` as in my case
3. Start game

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1601159/128154908-ab22a705-022e-43a6-a759-4cd1119d9a3c.png)

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/pull/1920
