### ISSUE TITLE
Joining a UDP game always failes

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#250]
Back when TCP was implemented it unfortunately turned out to break the UDP implementation.

ae60e94670c174a5fdb9c8847ded9d4c9733b3f7

Probably the UDP implementation simply needs to be updated with the latest changes.

**Comment by obligaron** [comment]
It can't fail, because we don't support UDP anymore. 😉

**Comment by AJenbo** [comment]
rip
