### ISSUE TITLE
Android hardware cursor not visible when using gamepad

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#2502]
When using the hardware cursor on Android, the mouse cursor is not visible in the inventory, character sheet, or when freely moving the cursor using the right analog stick.

SDL on Android implements hardware cursor using the [PointerIcon](https://developer.android.com/reference/android/view/PointerIcon) class. `PointerIcon` objects can be used to set the default cursor for a `View`, but the SDK doesn't seem to provide any control over the position or visibility of the mouse cursor. From what I can tell, the `PointerIcon` is only visible when a hardware mouse is used to interact with the device.

Incidentally, these `PointerIcon` objects are stored in a hash table to be referenced by an integer ID, but the SDL implementation doesn't provide a JNI function for `SDL_FreeCursor()` to remove them from the hash table. This represents a bit of a memory leak for the application so perhaps hardware cursor on Android should be avoided entirely.

---

SDL_CreateColorCursor:
https://github.com/diasurgical/devilutionX/blob/9aee0581374858991705ecae373c20392f93646f/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L1501-L1515

SDL_SetCursor:
https://github.com/diasurgical/devilutionX/blob/9aee0581374858991705ecae373c20392f93646f/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L1520-L1532

**Comment by AJenbo** [comment]
I'm thinking that the cursor smoothness is less important on Android given that it will most likely be moved using a gamepad (virtual) and rarely an actual mouse. If some one does play it using a mouse on an Android device they are probably enough of a power user that they can change the ini?
