### ISSUE TITLE
Applying oil of accuracy does not update char sheet before re-equipping the item

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2506]
- find oil of accuracy
- open char
- apply to an equipped item
- notice numbers did not update
- re-equip item
- see change

This is probably a vanilla issue

**Comment by ThomasChr** [comment]
I'll would like to try it.
I think it's allowed to Modify RndItem() to just give me the oil of accuracy?

**Comment by ThomasChr** [comment]
Can't reproduce. Barb, Level 1, just the starting sword. I opened char stats and inventory and applied the oil. Chance to hit changed from a white 60% to a blue 62% immediatly.
I also tried with a club. Also did work.

**Comment by qndel** [comment]
> Can't reproduce. Warrior, Level 1, just the starting sword. I opened char stats and inventory and applied the oil to the equiped sword. Chance to hit changed from a white 60% to a blue 62% immediately.
> I also tried with a club. Also did work.
> Also tried with a completely new character. Did still work, the numbers updated immediately.

can you upload save? ;)

**Comment by ThomasChr** [comment]
Of course, I could do that. What savefile do you want? After I have a few oils in the inventory, or after I applied one?

**Comment by qndel** [comment]
With oils ofc

**Comment by ThomasChr** [comment]
Enough oils, before applying any...
[single_2.zip](https://github.com/diasurgical/devilutionX/files/6946383/single_2.zip)

**Comment by AJenbo** [comment]
Ok, maybe we where wrong, I will have to check the details with my brother tomorrow :D

**Comment by julealgon** [comment]
Wasn't this fixed by one of @qndel 's changes recently? I remember there was something which required you to unequip/re-equip to update the character info and that was fixed.

**Comment by AJenbo** [comment]
It's possible, we where playing 1.2.1 so there are some fixes that are already done that we did not have.

**Comment by qndel** [comment]
> Wasn't this fixed by one of @qndel 's changes recently? I remember there was something which required you to unequip/re-equip to update the character info and that was fixed.

nope, my change was only for updating damage on leveling up

**Comment by qndel** [comment]
Works fine for me.
