### ISSUE TITLE
Golem is only unsummoned for the owner

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2507]
- play multiplayer
- player A spawn golem
- have player B leave the dungeon
- player A leaves the dungeon (golem unspawns)
- player A enter the dungeon
- player B enter the dungeon
- Player B can see golem alive and well, player A cannot

This is probably a vanilla issue

**Comment by qndel** [comment]
Faster reproduction:
1. player A spawns golem
2. player A leaves dungeon
3. player B enters dungeon and sees golem from player A

**Comment by julealgon** [comment]
Oh wow, so this was a vanilla issue huh... damn, how can something so incredibly obvious not work like that.
