### ISSUE TITLE
Shift equip/autoequip does not load item spell

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2509]
- Find a staff with charges
- Do not have any spell ready
- Equip the staff by way of shift-click in the inventory
- Notice that there still isn't a readies spell

**Comment by julealgon** [comment]
Equipping via pickup with auto-equip weapons enabled results in the same behavior.

The logic for reseting the readied spell is completely hardcoded in the inventory "paste" code path.
