### ISSUE TITLE
multiplayer rejoining game

### ISSUE THREAD

**Issue by namtsui** [diasurgical/devilutionX#251]
Steps to reproduce:
Player 1 creates multiplayer game
Player 2 joins game
Player 2 presses escape and selects new game
Player 2 ends up on the Join TCP/UDP Games and is able to: Create Game, Enter IP
Player 2 re-enters information and tries to join
popup shows: Unable to establish a connection. A game of Devilution 0.2.0 was not detected at the specified IP address.
After clicking to close the popup,  Player 2 gets redirected to main menu
Player 2 successfully joins the game again.

This popup only shows up if you try to rejoin from the Join TCP/UDP Games screen. If you escape back to the select TCP or UDP screen, or escape back to the main menu, you can actually rejoin the game.

**Comment by AJenbo** [comment]
It's probably as simple as clearing a variable when entering the multplayer menu, the value appears to be cleared by attempting/failing to join a game.
