### ISSUE TITLE
Ironman Game Mode

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2515]
It would be cool to add game modes. and can server as good inspiration for people looking to make more creative mods

One of the most popular out there is Ironman, the rules are simple:
> When playing Ironman style characters can not use any items they do not find themselves, repeat/replay areas, or buy items from NPCs. Ironman characters are generally hardcore, and are forbidden to return to town or interact with NPCs in any way other than as required to complete progress-stopping quests. There is naturally no twinking or muling or other such activities either. 

https://www.diablowiki.net/Ironman

Having the rules implemented in the game would make it easier to make sure that all are following the same rules when playing and comparing.

To prevent players from returning to town you could simply use the same code that prevents the player from going to level 3 in the shareware: https://github.com/diasurgical/devilutionX/blob/bc51e1616d8ce443b8d4121d30b7dab890589f9c/Source/trigs.cpp#L807

For how to add it to the main menu you can look at how game speed was added for multiplayer:
https://github.com/diasurgical/devilutionX/blob/master/Source/DiabloUI/selgame.cpp#L286

**Comment by julealgon** [comment]
Do you have an idea already of where to save the new flag to indicate the game mode? Do we have free positions in the existing save data right now, or would we need to add extra files to the MPQ for this?

> To prevent players from returning to town you could simply use the same code that prevents the player from going to level 3 in the shareware:

Also, note that pure ironman not only doesn't allow one to go to town, but also prevents one from moving upstairs. We need to be very clear what "flavor" of ironman we are going to implement (or if we are going to implement more than one of them).

Lastly, the "hardcore" part of this feature would probably warrant a separate issue altogether and I'd recommend implementing that separately, first.

**Comment by AJenbo** [comment]
> Do you have an idea already of where to save the new flag to indicate the game mode? Do we have free positions in the existing save data right now, or would we need to add extra files to the MPQ for this?

There is enough free data to do so, but not really sure where this idea will lead atm :)

**Comment by qndel** [comment]
remember we got A LOT of "free" space where they saved/loaded the light twice ;)

**Comment by ChaosMarc** [comment]
Just my two cents: I think this shouldn't be implemented in DevilutionX but in a mod. There were many discussions about new features to the game and if they should be toggleable and I think this is most definite no feature of vanilla and no QoL feature but a specific playstyle some players choose (which they still can by just following the rules). An ironman mod could go much further that just preventing going upstairs. Some kind of score system comes to mind or different kinds of ironman rulesets to choose from when starting a game: no potions (they just don't drop at all, naked ironman (absolutely no drops) etc. This is quickly going to be way to much to just integrate in in DevilutionX

**Comment by AJenbo** [comment]
Yeah I think it would make a good mod

**Comment by Chance4us** [comment]
I can also recommend the hardcore mode.
https://diablo2.diablowiki.net/Hardcore

**Comment by t-kuester** [comment]
Not sure how hard it would be to implement this, but instead of making this a game mod(e) and _prohibiting_ going back to town, how about keeping track of certain "conducts" similar to how [Nethack](https://en.wikipedia.org/wiki/NetHack#Character_death) does it, e.g. "never bought an item", "never used a shrine", "never went back to town", etc.

**Comment by julealgon** [comment]
> Just my two cents: I think this shouldn't be implemented in DevilutionX but in a mod. There were many discussions about new features to the game and if they should be toggleable and I think this is most definite no feature of vanilla and no QoL feature but a specific playstyle some players choose (which they still can by just following the rules). An ironman mod could go much further that just preventing going upstairs. Some kind of score system comes to mind or different kinds of ironman rulesets to choose from when starting a game: no potions (they just don't drop at all, naked ironman (absolutely no drops) etc. This is quickly going to be way to much to just integrate in in DevilutionX

I don't disagree entirely but I think we _can_ implement some aspects of it in a general-purpose manner that can then be composed into a full-fledged mode by mods later.

For example, the hardcore aspects require a system where you can't save/load at any point, and to mark a character as blocked so it cannot be loaded after death. I think we should definitely implement those mechanisms.

Similarly for ironman, I think the game should make it easier to "add" the ironman rules by creating extension points in the code for it.

**Comment by AJenbo** [comment]
It might be a good first use case for LUA scriptability.

**Comment by julealgon** [comment]
Wait, is this implemented now @AJenbo ? Or did you perhaps mean to close as not planned?

**Comment by AJenbo** [comment]
Just learned that they added a "not planned" option today :shrug:
