### ISSUE TITLE
Windows: diabdat.mpq missing

### ISSUE THREAD

**Issue by superbonaci** [diasurgical/devilutionX#253]
Running devilutionx-windows-i386

Data File Error
Diablo cannot read a required data file.
Your diabdat.mpq may not be in the Devilution folder or it's read only.
Please ensure that the filename is in all lower case and try again.

`DUMMY: SetUnhandledExceptionFilter @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:507
DUMMY: GetSystemInfo @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:573
DUMMY: CreateFileMappingA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:665
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: LoadIconA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:431
DUMMY: LoadCursorA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:446
DUMMY: LoadImageA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:440
DUMMY: RegisterClassExA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:399
DUMMY: UpdateWindow @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:382
DUMMY: UiAppActivate @ /home/ajenbo/code/diablo/devilutionX/SourceX/DiabloUI/diabloui.cpp:422
DUMMY: GetWindowLongA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:778
DUMMY: SetWindowLongA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:784
DUMMY: SDrawRealizePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:705
DUMMY: DefWindowProcA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:769
DUMMY: SetCooperativeLevel @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:100
DUMMY: SetDisplayMode @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:106
DUMMY: CreateSurface @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:57
DUMMY: CreatePalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:42
DUMMY: SetPalette @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:203
DUMMY: GdiSetBatchLimit @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:270
DUMMY: GetCaps @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:159
DUMMY: CreateSurface @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:57
DUMMY: SDrawManualInitialize @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm_dx.cpp:19
DUMMY: WaitForVerticalBlank @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:116
DUMMY: BltFast @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:136
DUMMY: Unlock @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/ddraw.cpp:209
DUMMY: sound_DirectSoundCreate @ /home/ajenbo/code/diablo/devilutionX/SourceX/sound.cpp:409
DUMMY: SVidInitialize @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:424
DUMMY: GetFileVersionInfoSizeA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:167
DUMMY: GetFileVersionInfoA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:175
DUMMY: VerQueryValueA @ /home/ajenbo/code/diablo/devilutionX/SourceX/miniwin/misc.cpp:183
BasePath: C:\Users\Miguel\Desktop\devilutionx-windows-i386\
DUMMY: SFileSetBasePath @ /home/ajenbo/code/diablo/devilutionX/SourceX/storm/storm.cpp:699
SFileOpenFile: Not found: ui_art\title.pcx`

**Comment by superbonaci** [comment]
![Diablo can't find diabdat.mbq](https://i.imgur.com/Ak34uzD.png)

**Comment by AJenbo** [comment]
What's the full path of your mpq and what is the assess level for or?
Also what is It's md5 sum?

**Comment by superbonaci** [comment]
download url:
https://github.com/diasurgical/devilutionX/releases/download/0.4.0/devilutionx-windows-i386.zip

**Comment by qndel** [comment]
do you have diabdat.mpq?

**Comment by superbonaci** [comment]
It's not int he zip:

    e4ea77cda068d8b065f636328d5cf663  c:\Users\user\Desktop\devilutionx-windows-i386\LICENSE\LICENSE.CharisSILB.txt
    95dfaa6e4ee83fcfe7393f494069f71f  c:\Users\user\Desktop\devilutionx-windows-i386\LICENSE\LICENSE.freetype.txt
    b1303b058adb1e7ec07a1295b9c6caf3  c:\Users\user\Desktop\devilutionx-windows-i386\LICENSE\LICENSE.zlib.txt
    fb6c89288fdfdf543b77e2ce6b0a3a8d  c:\Users\user\Desktop\devilutionx-windows-i386\LICENSE\README-SDL.txt
    038940dc155f9bd2118421a559d90fe9  c:\Users\user\Desktop\devilutionx-windows-i386\LICENSE\README-SDL_mixer.txt
    6a23e7d95519a0ad3225617232bfc63d  c:\Users\user\Desktop\devilutionx-windows-i386\LICENSE\README-SDL_tff.txt
    2a8937ad0a0afed6f819bb3c5424158f  c:\Users\user\Desktop\devilutionx-windows-i386\README.txt
    1541846e4dac468a905e73a672205d0a  c:\Users\user\Desktop\devilutionx-windows-i386\libfreetype-6.dll
    7b55d301989467f27d6e6de00a5f2239  c:\Users\user\Desktop\devilutionx-windows-i386\SDL2_ttf.dll
    d6642b15609a56fbb947b44760d1e5a9  c:\Users\user\Desktop\devilutionx-windows-i386\SDL2_mixer.dll
    f43d94bcf96337cb2ea712686f528a25  c:\Users\user\Desktop\devilutionx-windows-i386\zlib1.dll
    1ac348b651d446702ab616981587ac37  c:\Users\user\Desktop\devilutionx-windows-i386\CharisSILB.ttf
    098c661f98cd7fd85a82ebc34db5be15  c:\Users\user\Desktop\devilutionx-windows-i386\SDL2.dll
    3c21866788021e9d71efc25f15389a3c  c:\Users\user\Desktop\devilutionx-windows-i386\devilutionx.exe

**Comment by qndel** [comment]
ofc it's not, we aren't providing diabdat.mpq, you have to own the game to have it

**Comment by superbonaci** [comment]
Ok I didn't know, I though it was all completely open source. So the assets are from the original game.

**Comment by qndel** [comment]
yup
