### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by goblinrieur** [diasurgical/devilutionX#255]
Documentation says to cmake (ok) then to do make -j$(nproc)

after first %'s  the make fails on an error that seems to be code error 

`[ 75%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/packet.cpp.o
/home/francois/diablo/SourceX/dvlnet/packet.cpp: In constructor ‘dvl::net::packet_factory::packet_factory(std::__cxx11::string)’:
/home/francois/diablo/SourceX/dvlnet/packet.cpp:165:45: error: ‘crypto_pwhash_argon2id_PASSWD_MAX’ was not declared in this scope                                       
  pw.resize(std::min<std::size_t>(pw.size(), crypto_pwhash_argon2id_PASSWD_MAX));                                                                                
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                    `

**Comment by AJenbo** [comment]
Your libsodium is outdated compared to what is required by DevilutionX.

**Comment by goblinrieur** [comment]
Thanks I need a dist-upgrade first :) then I 'll upgrade libsodium packages to the last version.

**Comment by AJenbo** [comment]
You can probably also pull just the latest libsodium, that's what I do when compiling on Debian 9 (for releases)
