### ISSUE TITLE
Compiling: Getting the _TARGET_ARCH from the compilation log seems rather odd

### ISSUE THREAD

**Issue by ThomasChr** [diasurgical/devilutionX#2558]
**Important information**
Compiling on Windows with Visual Studio Compiler but not using Visual Studio

**Describe**
When cmake does it's thing it searches for the libsodium libraries. That happens in 'CMake/Findsodium.cmake'.
Around Line 115 the following happens:
```
        string(REGEX REPLACE ".*ARCH_VALUE ([a-zA-Z0-9_]+).*" "\\1" _TARGET_ARCH "${_COMPILATION_LOG}")

        # construct library path
        if (_TARGET_ARCH STREQUAL "x86_32")
            string(APPEND _PLATFORM_PATH "Win32")
        elseif(_TARGET_ARCH STREQUAL "x86_64")
            string(APPEND _PLATFORM_PATH "x64")
        else()
            message(FATAL_ERROR "the ${_TARGET_ARCH} architecture is not supported by Findsodium.cmake.")
        endif()
```
So we're getting the '_TARGET_ARCH' from the Compilation Output Log. This does include the x86_64 when compiling with Visual Studio. This does not work when compiling with CLion (or any other IDE).

For me I fixed it by setting the Architecture like this:
```
set(_TARGET_ARCH "x86_64")
```

But for sure there has to be a better way?
For one we could use a new cmake variable or we could use another variable to get the architecure. My system has got the following which could help:
```
-- CMAKE_CXX_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe
-- CMAKE_LINKER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/link.exe
-- SDL2_DIR=C:/Program Files/vcpkg/installed/x64-windows/share/sdl2
-- VCPKG_TARGET_TRIPLET=x64-windows

-- CMAKE_CXX_COMPILER_ARCHITECTURE_ID=x64
-- CMAKE_EXE_LINKER_FLAGS=/machine:x64
-- CMAKE_HOST_SYSTEM_PROCESSOR=AMD64
-- CMAKE_SHARED_LINKER_FLAGS=/machine:x64
-- CMAKE_STATIC_LINKER_FLAGS=/machine:x64
-- CMAKE_SYSTEM_PROCESSOR=AMD64
-- MSVC_CXX_ARCHITECTURE_ID=x64
-- MSVC_C_ARCHITECTURE_ID=x64
```

Any ideas?

**Comment by StephenCWills** [comment]
Looks like libsodium used this approach all the way up to the very last moment when they decided it wasn't worth keeping an unmaintained `Findsodium.cmake` script (jedisct1/libsodium@178359d). So, unfortunately, we won't be getting any help from there.

Maybe we can use something from here?
https://stackoverflow.com/questions/39258250/how-to-detect-if-64-bit-msvc-with-cmake
