### ISSUE TITLE
Attempting to cast a resurrect scroll on self causes a CTD

### ISSUE THREAD

**Issue by 0mnicydle** [diasurgical/devilutionX#2576]
**Important information**
Windows 10  x64 / latest master / download or compile

**Describe**
Attempting to cast a resurrect scroll on self causes a CTD.

**Expected behavior**
Nothing happens, scroll is wasted, game continues.

**Additional context**
I believe I tracked it down to commit 7effa1a931e7e33d2afface5438e55ed76e3dc15

[multi_0.zip](https://github.com/diasurgical/devilutionX/files/6970118/multi_0.zip)

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/129081919-424fefd2-6503-4a45-86bf-a2ec1cc2cf1d.png)

**Comment by 0mnicydle** [comment]
Just in case someone is waiting for me to respond, I can report this PR does indeed fix the crash on my end.

**Comment by julealgon** [comment]
Why remove the 1.3.0 milestone @qndel ?

**Comment by AJenbo** [comment]
Probably because it was a bug introduced after 1.2.1, so he might be keeping the milestone more useful once we need to create a change log.
