### ISSUE TITLE
Theo-Quest Girl is still crying after finishing quest

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2578]
**Important information**
win 10 64bit self build based on commit 0e56e52c75

**Describe**
Clicking the girl after finishing the theo quest just plays the crying sound.

**Expected behavior**
I am quite sure that it not cried after returning Theo. I tried to verify this but I was unable to get the original game running on my computers.

**Comment by AJenbo** [comment]
She only has 4 lines, i'm going to assume that she probably doesn't say anything when the quest is over.

Here is the extremely hard to read bin exact version:
https://github.com/diasurgical/devilution/blob/master/Source/towners.cpp#L1387

**Comment by julealgon** [comment]
It's such terrible design to have a character that you can click on but doesn't say anything..... I have no idea why they didn't record a final voice for her.

Would be nice if we could provide at least a text-only version of some kind of farewell or thank-you message for her and use that instead of doing nothing.

**Comment by NikoVP** [comment]
The end of her final speech would do. "Thanks again, hero person "

**Comment by AJenbo** [comment]
Yeah the hellfire towners stick out for not having any gossip or menus. I'm wondering if it wouldn't make more sens to simply make them non clickable once there quest is finished.

**Comment by vladtepesch** [comment]
> Could you check if there is a similar issue with `TalkToCowFarmer` and `TalkToFarmer`?

actually another thing that made me wonder was that the Farmer allways talks about the explosion after getting the auric amulet. Afair he also reacts differently.
And another thing: the cowfamer does not wear the dress i brought to him 
But for this two Bugs I wanted to check if it is actual my own fault because I changed the Cowquest to not replace the Farmer but be both to be active - but this change seemed to be quite minor --> https://github.com/vladtepesch/devilutionX/tree/CowQuestAndFarmer  



> Yeah the hellfire towners stick out for not having any gossip or menus.
The girls quest of course was never be official, but also the official HF quests are badly integrated. At least Cain should have something to say about Na'Kroul (or however its called) and the Cornerstone

**Comment by NikoVP** [comment]
Sadly they never employed the original diablo voicecast when making the expansion. Our only hope is using artificial intelligence to generate dialogs. Someone has to write the dialog, make sure it's consistent with original diablo game lore. Another setback is that there aren't many good free generators. Maybe the free trial of Overdub can be used for that https://www.descript.com/overdub. Again we are entering mod area with that.

**Comment by julealgon** [comment]
> I'm wondering if it wouldn't make more sens to simply make them non clickable once there quest is finished.

This is also better than having them clickable but do nothing. Would support this change until we can have actual text defined (if any).

**Comment by vladtepesch** [comment]
> Our only hope is using artificial intelligence to generate dialogs.

I guess the training samples are not enough for this. The better hope would be to get some similar voice and an expert removing the remaining differences with software.



> Again we are entering mod area with that.

I still not get the border line you (as the dev team) draw. 
Imho the half of DevilutionX is like a mod. (and i think its good that way)
 - adaption to widescreen/resolution
 - alt-highlight
 - improved clicking
 - speed settings
 - controller support
 - fixed game bugs
 - ...

anybody what wants to play the true original could use a VM with the original executable

**Comment by AJenbo** [comment]
AI is over rated and overshadows existing solutions:
https://user-images.githubusercontent.com/204594/129231056-574f4501-1f42-4caf-bbeb-a9344d3b7b9f.mp4

**Comment by AJenbo** [comment]
> I actually like NikoVP's suggestion more.

It was mostly just a joke, not seriously intended for adding it to the game.

**Comment by AJenbo** [comment]
>  Would support this change until we can have actual text defined (if any).

Should be trivial, all of it is there, just needed and if for using the NOSOUND path when the naration sound is set to -1

**Comment by vladtepesch** [comment]
should be this issue renamed to cover farmer and girl quest or do you want to handle both issues separately?
The Cow seems okay. has the bovine suit on because in my test save i indeed had not finished the quest. in the other one it works as expected

**Comment by AJenbo** [comment]
Regarding making her go away. The farmer is suppose to go away after his quest finishes (not appear on next visit to town).
But the girl has two different sprites, one with and one with out Theo, which changes on next visit to town.

**Comment by AJenbo** [comment]
Had the idea to update the sprite as you complete the quest instead of next visit to town, looks way better:
![Peek 2021-08-15 17-36](https://user-images.githubusercontent.com/204594/129484065-d8ef6cc9-62aa-400d-8137-52c4d9d43823.gif)

**Comment by AJenbo** [comment]
![Peek 2021-08-15 18-02](https://user-images.githubusercontent.com/204594/129484741-e3a961f9-246e-43cd-b3da-f3094ad1ef21.gif)

**Comment by AJenbo** [comment]
![Peek 2021-08-15 18-03](https://user-images.githubusercontent.com/204594/129484775-6cf30a0b-7aea-493d-81db-4c42506fa65c.gif)

**Comment by vladtepesch** [comment]
changing the sprites right the moment is great, but i still would not remove them. i didn't liked the emptyness they leave

**Comment by vladtepesch** [comment]
the farmer is also not supposed to go, I guess. There is just a bug that it does not apeear, if both the cow quest and the farmer was started and then the cowquest param is disabled again.

At all I would like to disable this "exclusive or" between these quests. there is no really reason for this.

**Comment by AJenbo** [comment]
If you initiate the quest at the farmer you won't get the intro for the cow quest, you can get both to drop the bomb but only pick up one. They are intertwined since they are actually both running the same quest, having them both work at the same time would requier a bit of rewriting of the quest, it would at the very least be hard to do in a way that is compatible with existing saves.

**Comment by vladtepesch** [comment]
But the only quest of the farmer is to clear the hive entrence. at this point the quest of the cow hasn't even started. The only thing I do not like is both drop the bomb if you do talk to them subsequently without picking the first bomb. If you already picked them then the other one will not drop one.
Currently the only quirk is that the cows talk-routine checks the rune bomb at top level rather than at the appropriate quest level. 

But th point I wanted to make was, that neither the farmer not the cowfarmer is supposed to disappear. the farmer only disappers if the qow quest was started and even does not reappear if the cowquest option is disabled again.

**Comment by AJenbo** [comment]
Your not wrong, but it requires a bit of work and it will probably break comparability.

On a different note TEXT_GIRL1 seams to be unreachable. I'm guessing it could originally have been used where the girl would spawn before the quest was made available, not sure though.

**Comment by vladtepesch** [comment]
yes i also stumbled about the fact that the default case just plays the sound and not calls the usual message routine.
Maybe the entry condition of the girl should be lowerd to some smaller level (maybe the same as the farmer or cows) and the talk-`INIT` case should check and let her cryand she cried if the player not visited the hive.

**Comment by AJenbo** [comment]
I can see the issue from a game design though; Why would you talk to her after going to the hive if all she did on all other caes was cry for no reason.
