### ISSUE TITLE
Town portal visual anomaly 

### ISSUE THREAD

**Issue by 0mnicydle** [diasurgical/devilutionX#2584]
**Important information**
Windows 10 x64 / master b76e8c060b5415699fc8b0b6b869951b45aca7ce and up

**Describe**
Casting town portal results in the portal briefly appearing and then visually disappearing, but still usable if you know where to click.

[multi_0.zip](https://github.com/diasurgical/devilutionX/files/6972757/multi_0.zip)

**Comment by 0mnicydle** [comment]
Actually I don't think the commit I mentioned is necessarily the actual commit that caused the bug, but I'm pretty sure it's something from this PR that was merged:

https://github.com/diasurgical/devilutionX/pull/2440

I'm actually going to close this issue because I think this issue is actually the same as mine:

https://github.com/diasurgical/devilutionX/issues/2579

**Comment by virox** [comment]
This is happening to me and my buddy as well.
When casting, the portal appears, but it becomes invisible when it's casted.
Commit [bb4d087](https://github.com/diasurgical/devilutionX/commit/bb4d087d60e3492a0febeec0ef32d6974d839716)
