### ISSUE TITLE
Broken --ttf-name / --ttf-dir options

### ISSUE THREAD

**Issue by Pinkbyte** [diasurgical/devilutionX#2588]
**Important information**
Gentoo Linux / DevilutionX 1.2.1(from release AppImage) or 1.2.1-bb4d087d(compiled from sources)

**Describe**
--ttf-name / --ttf-dir appears to do nothing

**To Reproduce**
1. Set --ttf-name / --ttf-dir
2. Run DevilutionX with --ttf-dir /absolute/path/to/font/dir --ttf-name fontname.ttf
3. No custom font is present in game

**Expected behavior**
Custom font should be loaded

**Additional info**
Running DevilutionX via strace does not show any attempts to load font via open call (on the other hand - all mpq load attempts are shown)

**Comment by AJenbo** [comment]
Please provide a screen shot so we can see where you expected this to take effect.

**Comment by Pinkbyte** [comment]
Hm, it seems that currently i was able to trigger load of custom font only during error messages of DevilutionX itself (for example, if i remove all *.mpq from data directory)...

Sorry for the noise then, my mistake
