### ISSUE TITLE
Killing Snotspill causes CTD

### ISSUE THREAD

**Issue by 0mnicydle** [diasurgical/devilutionX#2603]
**Important information**
Windows 10 x64 / latest master

**To Reproduce**
Load attached save and kill Snotspill right through the doorway to the immediate East using the equipped spell.

**Additional context**
The oldest automated master build I could find where the crash first starts to show up is: https://github.com/diasurgical/devilutionX/commit/c5e09661907d966fcbbf42119935dad0d9a9d31c

[single_0.zip](https://github.com/diasurgical/devilutionX/files/6987276/single_0.zip)

**Comment by AJenbo** [comment]
> the equipped spell

What spell is it? The title sounds misleading if it's only with a specific spell that this happens.

**Comment by 0mnicydle** [comment]
It's not just that spell, but the equipped spell is at least guaranteed to trigger it. I believe the one equipped in the save was firebolt, but at least inferno was causing it too. Unfortunately this character isn't very well equipped yet, sorry :(

**Comment by 0mnicydle** [comment]
I just loaded it back up and confirmed even melee kills cause the crash.
