### ISSUE TITLE
Some menus don't wrap around

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2605]
I'd expect all of them to wrap around = you are on the lowest item and press arrow down = you end up being on the top one.

So far found 2 that don't do it:
Multiplayer connection selection and character selection menus.

**Comment by ThomasChr** [comment]
That can't be too difficult. I would like to try!

**Comment by ThomasChr** [comment]
Thanks to the nice and clean codebase it was very easy!

**Comment by AJenbo** [comment]
> Thanks to the nice and clean codebase it was very easy!

That's the first time I have heard that, guess we must have been doing something right over the past few months :D
