### ISSUE TITLE
Advertise automated Android builds more?

### ISSUE THREAD

**Issue by Espionage724** [diasurgical/devilutionX#2614]
I noticed a build of devilutionX on Google Play, but it hasn't been updated since last year. I see an Android build folder in the source, but didn't have access to an Android development set-up to compile. I saw in a few different Issue reports about progress and TODOs, and was under the impression that devilutionx sort of works on Android, but you'd need to build it manually unless you got the old version off Google Play.

That is until I stumbled upon https://github.com/diasurgical/devilutionX/issues/131#issuecomment-861088568 which links to fresh Android builds: https://app.circleci.com/pipelines/github/diasurgical/devilutionX

I've looked casually into this for the past few months mainly because I was curious if the Android build would work on an Oculus Quest 2 with a bluetooth controller (it does). ~~I'm not sure if that CI link is mentioned anywhere else visibly, but I believe it would be nice to have a link to it on the README.md or releases page.~~

Edit: That CI link is mentioned on the README.md, but I guess I didn't think to check it for Android builds. Perhaps some kind of hint that Android builds exist would be nice.

**Comment by StephenCWills** [comment]
We've been actively discussing the Android build for at least a couple months on the Discord. We've been commenting in, creating, and closing relevant issues and PRs. We've also added instructions to both the [Installation Instructions](https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md) page and the [Build Instructions](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md) page for Android. There's plenty of activity to keep people informed of the progress.

Although it's sort of a landing page for the project, the README.md file hasn't previously been used to keep people informed of recent events or the features that are in active development. It wasn't even updated to announce the release of 1.2.0. Perhaps there is an argument made for adding more information to the `Test builds` section of the README so I won't close this issue just yet, but there are better ways to track our progress than periodically checking the README. Honestly, I think this advice could apply to nearly all GitHub projects.

**Comment by NikoVP** [comment]
The version on Google Play is an old port that wasn't created and uploaded by the Diasurgical, they only recently got a hold over the rights of that port. Until the stable version with proper controls is ready I presume they will not advertise.

**Comment by AJenbo** [comment]
I prefer the ReadMe to stay minimalistic, and instead link to individual pages with additional details, but the `Test builds` section is indeed a bit bare bones so would be good if someone could add a sentience to it :)

Regarding Android builds, I'm not even sure what is being produced on the build server is installable under normal conditions so advertising it is a bit premature i think.
