### ISSUE TITLE
hitting space to close side panels also closes map

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2622]
**Important information**
current master

**Describe**
hitting space to close open windows also closes the automap

**Expected behavior**
Not sure it it was in vanilla the same way, but i think in later Diablo Versions the first hit closes the panels and an additional hit also closes the map.

I recognize that I really often reopen the map after closing the panels - so maybe other also feel that way?

**Comment by AJenbo** [comment]
It is the same for vanilla. Hitting esc to close panels is not.
