### ISSUE TITLE
Bugged Doors

### ISSUE THREAD

**Issue by GrayFace** [diasurgical/devilutionX#2625]
**Important information**
Win 7x64 / DevilutionX version 1.2.1 / downloaded release

**Describe**
The bug happened after I entered this level, saved and loaded. All open doors became closed and non-interactive. If I exit the level and enter again, they become open until I save-load again.
There's also a door with a glitched look, see the screenshot.

**To Reproduce**
1. Load [single_5.zip](https://github.com/diasurgical/devilutionX/files/6996994/single_5.zip)

**Expected behavior**
Being able to open doors.

**Screenshots**
![screen01](https://user-images.githubusercontent.com/5989806/129662233-5fcbba16-7903-4c78-b850-7f69576e62f8.png)

**Comment by ThomasChr** [comment]
Could confirm on linux, commit dc059dadb8addbfe79524b314c45e31905424bf8

**Comment by AJenbo** [comment]
@GrayFace how was the save original started

**Comment by AJenbo** [comment]
@ThomasChr from what I can see only releases where used in which case we should deal with the issue

**Comment by ThomasChr** [comment]
@AJenbo To me it seems that the doors aren't really in the dObject Array. I thought that doors are objects, and so they should be in the array and should be drawn in DrawObject(). Also they should be hightlighted in CheckCursMove() - but if my cursor stays over the doors CheckCursMove() does not detect any object.

**Comment by Chance4us** [comment]
Could it also be a rerolled level?
![screen00](https://user-images.githubusercontent.com/45902449/129697701-25466193-fbf5-455f-a9b2-cb6439cff6b2.png)
![screen01](https://user-images.githubusercontent.com/45902449/129697716-5b969642-d9f7-4e10-aa4b-7979865de055.png)
[single_5.hsv.zip](https://github.com/diasurgical/devilutionX/files/6998595/single_5.hsv.zip)

**Comment by qndel** [comment]
doubt it's a level reroll as next levels have broken doors too

**Comment by AJenbo** [comment]
It's related to our fix for double rendered doorframes in catacombs

**Comment by GrayFace** [comment]
> @GrayFace how was the save original started

What do you mean by original? It's a regular single player save. I went through Normal and started Nightmare. I don't have a backup of Nightmare save before this point.

I'v also now noticed that the game crashes if I teleport in the up-right direction.

> doubt it's a level reroll as next levels have broken doors too

Next level doesn't have any issues as far as I see. Unlike that referenced reroll bug, the layout of level 5 didn't change, only doors. Nothing seemed suspicious until I save-loaded on this floor and the doors got bugged. Something mush have gone wrong during either generation of the level or saving of the game. Could be related to https://github.com/diasurgical/devilutionX/issues/2340

**Comment by qndel** [comment]
> > @GrayFace how was the save original started
> 
> What do you mean by original? It's a regular single player save. I went through Normal and started Nightmare. I don't have a backup of Nightmare save before this point.
> 
> I'v also now noticed that the game crashes if I teleport in the up-right direction a few times.
> 
> > doubt it's a level reroll as next levels have broken doors too
> 
> Next level doesn't have any issues as far as I see.
> 
> Unlike that referenced reroll bug, the layout of level 5 didn't seem to change, only doors. Nothing seemed suspicious until I save-loaded on this floor and the doors got bugged. Something mush have gone wrong during either generation of the level or saving of the game. Could be related to #2340

he meant originally, how did you create that character?

**Comment by GrayFace** [comment]
Wait, it could have been rerolled! I can't rule that out. My very first visit actually was from town. When I start a game Nightmare+ I visit all dungeon enters just so I know where the town exits are. So, if during that visit the dungeon was different, I wouldn't have noticed the change.

> he meant originally, how did you create that character?
Through New Game in this version of Devilution X.

**Comment by GrayFace** [comment]
Some doors are in the middle of rooms. I guess it was a reroll.

Probably a side note: Since it also happened in this game, here's hall of mirrors effect on another level: [single_5_2.zip](https://github.com/diasurgical/devilutionX/files/7009849/single_5_2.zip) (it's a few squares to the left of hero). Probably unrelated. I think I've seen it before once in another game.

**Comment by AJenbo** [comment]
Sounds like an invalid tile, that happens with the original game also

**Comment by obligaron** [comment]
After the work for #4034 I also think it is possible to get this with a level reroll.
Your level 5 has no quest sets room, that means that the uninitialized variables aren't set (`nSx1`, ...).
If you previous visit a catacomb level with the same game process (didn't closed the game between) and even if it was on a different character/game this could happen.
But after #4034 it should be fixed (for new games).
