### ISSUE TITLE
Clicking a hero name selects name above click when scrollbar is bottomed out

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#2629]
**Important information**
Windows 10 / Latest build

**Describe**
When scrollbar is bottomed out in player selection, clicking a hero name selects name above click.

**Comment by julealgon** [comment]
Can you check whether this is a regression? Did it also happen on 1.2.1 and 1.2.0 for example?

**Comment by qndel** [comment]
Actually it's not 1 off, it's the "x don't fit on the list" off
