### ISSUE TITLE
Reflect spell is no longer active after loading the game

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2632]
Self-explanatory.
To reproduce:
1. Play a game
2. Read the book of reflect
3. Cast Reflect spell and save the game
4. Leave the game to stop process
5. Open the game binary and load the saved game
6. Be surprised that Reflect is no longer activated

EDIT: 4. Exit the binary is not needed, it is sufficient just to load the game while playing

**Comment by ThomasChr** [comment]
could confirm on windows e1db9ba77b06500e43bc49f310323758e67ba743 - works with manashield, does not work with reflect

**Comment by ThomasChr** [comment]
Hey! That does seem to work great!
Unfortunately it also leaves the reflect spell active even if you are starting a new game. And that does not seem quite right to me!

Happy litle sorcerer starts with reflect:
![grafik](https://user-images.githubusercontent.com/13014163/130191263-1c5795c3-1136-4ef2-840c-150ce7475957.png)

**Comment by qndel** [comment]
fixed

**Comment by ThomasChr** [comment]
checked, and it works. Haven't doubt that for a second!
