### ISSUE TITLE
Crash on killing a petrified monster

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2633]
**Important information**
local build vs2019 win64 based on commit 54b60101

**Describe**
game reproducable crashes if killing the stone cursed warlord.

**To Reproduce**
1. load the save
2. lure the warlord around the corner
3. stone curse it (seems not to crash without the curse)
4. kill it with apocalypse

-> game crashes 
 in debug the following screen is shown (color should be changed to blue ^^):
![grafik](https://user-images.githubusercontent.com/1601159/129977122-8a2a8274-ae00-44ce-9cd5-df40c7f102cd.png)

don't know if this will help: (haven't deep dived into it)
![grafik](https://user-images.githubusercontent.com/1601159/129977196-f6a36924-f0d8-4227-ba44-cf0d42bb1605.png)

**Expected behavior**
no crash

**Additional context**
save game:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/7010427/single_0.zip)

**Comment by AJenbo** [comment]
Was this game started on the same build or an older one? This would be expected if the save is from the range where the death animations where shifted.

**Comment by vladtepesch** [comment]
the character is a few versions old, but the game was startet on a build based on this commit (If I do not recall wrong). when was which commit was this change? I thought save games should be compatible?

**Comment by AJenbo** [comment]
Master is not stable by definition as it is the development branch, only releases gets that level of support.

The issue was present from https://github.com/diasurgical/devilutionX/commit/f289fbcec5f984da8428445530f452880063f617 to https://github.com/diasurgical/devilutionX/commit/e9f1d6ad882b4be26d513857a6cf6fa54206a696, any monster spawned in that range will cause the game to crash in debug for any other versions.

**Comment by AJenbo** [comment]
The way to test it is to create a new game, use stone curse on a monster and kill the monster while still petrified.

**Comment by vladtepesch** [comment]
indeed it crashes if I kill any petrified monster in the current game and also in a new created game (with the same character - but this should not matter, I guess)

**Comment by AJenbo** [comment]
That sounds to me like it would affect all new games as well, the hero doesn't retain this aspect of the game world.

**Comment by vladtepesch** [comment]
yeah. I confirmed this behaviour also on the current master. with an old game and a newly created one.

**Comment by vladtepesch** [comment]
I assume the crash has to do something with this line:

https://github.com/diasurgical/devilutionX/blob/a97d64af1b2614bf4d50b63db43d16e3460c88ea/Source/missiles.cpp#L4084


together this this few lines:
https://github.com/diasurgical/devilutionX/blob/a97d64af1b2614bf4d50b63db43d16e3460c88ea/Source/dead.cpp#L53-L58:

Using a global index in this context looks wrong.  
In Anyway the using of the array counter as index is wrong.

**Comment by AJenbo** [comment]
That `nd++` on line 56 looks suspiciously like the issue.

**Comment by vladtepesch** [comment]
moving the assignment before the increment, (on the first glance) does not crash the game anymore. But I am not sure if a destroyed petrified monster should leave some dead body/some debris on the floor.

**Comment by AJenbo** [comment]
it should leave debri.

I looked further in to it and the reason it has the extra `++` is that the id in `dDead` should be one higher then the actual index and for some reason this isn't done by `AddDead()`.

**Comment by vladtepesch** [comment]
index that is passed to `AddDead()` already is one off at all places, so internally it does not need to add an additional 1.

so maybe this is fine. So maybe the index is correct but the initialization of this this additional `Dead` data that is used for dead petrified monsters is just missing

**Comment by vladtepesch** [comment]
I think  I understood the dead-code now 😃

The problem is not the increment in line 56 but the increment in line 51:

https://github.com/diasurgical/devilutionX/blob/a97d64af1b2614bf4d50b63db43d16e3460c88ea/Source/dead.cpp#L48-L58

the comment at the increment states that the slot `n+1` is an unused slot for some gore but the Shatter animation is loaded into this slot.

I guess this increment should be right after the end of the previous for loop to just skip this entry and then load the shatter animation into the next slot those number (already incremented by 1) is then stored at the `stonendx `

**Comment by AJenbo** [comment]
Oh your right, it should be moved up before the loop :D

**Comment by AJenbo** [comment]
Thanks for investigating and fixing.
