### ISSUE TITLE
Running on Pinephone

### ISSUE THREAD

**Issue by phoenixbyrd** [diasurgical/devilutionX#2652]
**Important information**
Compiled on pinephone mobian distro just fine.

when running from terminal it outputs this. game title movie flickers, after that the menu doesn't work. Unsure what the actual issue is. Maybe due to being a mobile device?

INFO: SFileOpenFile: Not found: ui_art\hero5.pcx
INFO: Failed to load image meta
INFO: SFileOpenFile: Not found: ui_art\hero6.pcx
INFO: Failed to load image meta
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
DRM_IOCTL_MODE_CREATE_DUMB failed: Invalid argument
DRM_IOCTL_MODE_CREATE_DUMB failed: Invalid argument
DRM_IOCTL_MODE_CREATE_DUMB failed: Invalid argument

**Comment by phoenixbyrd** [comment]
Plays ok after running scale-to-fit

**Comment by phoenixbyrd** [comment]
Never mind, even with scale to fit improving it, after about 30 seconds the screen flickers making it unplayable.

**Comment by qndel** [comment]
I've never even heard about Pinephone before, so feel free to figure out how to get it to work :D

**Comment by julealgon** [comment]
...just to make sure: we are talking latest `master` version, right?

**Comment by phoenixbyrd** [comment]
Yes, master version

Trying to figure out the screen flicker issue, other than that the game performance is great. 

@qndel Pine phone is an awesome linux based mobile phone, I've had mine almost a week so still learning the ins and outs and hardware limitations, but awesome device.

**Comment by AJenbo** [comment]
Sounds like a buggy video driver, try disabling upscaling (switches to software rendering), or switch to building with SDL1.2. There isn't really anything we can do so closing the issue, but feel free to comment for feedback/updates
