### ISSUE TITLE
Reflect remains active after leaving the hell

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2658]
Reflect remains active after leaving the hell.
To reproduce enter and leave the hell through the exit "up to town".
![reflect](https://user-images.githubusercontent.com/45902449/130313305-23f153d0-2d42-46b3-ad48-44e7a855f2b2.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/7025058/single_0.hsv.zip)

**Comment by qndel** [comment]
dear god, I literally copied all the code from manashield and it's still doing stuff like this? 🤦

**Comment by qndel** [comment]
Guess you didn't test latest version

**Comment by Chance4us** [comment]
I'm sorry. I would like to add that I accidentally pressed "s" so that the list of spells was displayed when I went into town. But I don't know if my typing played a role. My commit is 46844c03cbede487347f03af78a406ccb8357f55.

**Comment by qndel** [comment]
![workingreflect](https://user-images.githubusercontent.com/14297035/130314354-3ec35eda-5dbd-46ef-bde1-8759a828987f.gif)

**Comment by Chance4us** [comment]
I can confirm that it does not occur. So it was false alarm because of not latest commit.

**Comment by Chance4us** [comment]
It happened again with latest commit. To test, load the attached savegame and go up into town.
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/7025169/single_0.hsv.zip)
Or is my savegame already defective?

**Comment by qndel** [comment]
How did you end up in that situation? You have reflect charges but there's no reflect 'missile' connected to them ;o

**Comment by Chance4us** [comment]
> How did you end up in that situation? You have reflect charges but there's no reflect 'missile' connected to them ;o

That's a good question.

**Comment by qndel** [comment]
Doesn't matter, I rewrote reflect so it doesn't use missiles anymore :)
