### ISSUE TITLE
-100 mana crashes on debug builds

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2660]
![image](https://user-images.githubusercontent.com/14297035/130319869-48989ff4-6458-4ec8-8787-1bb830d08cdd.png)
Looks like this on release builds ;D

```cpp
lineWidth = GetLineWidth(&text[i + 1], size, spacing, &charactersInLine);
```
in
```cpp
uint16_t DrawString(const Surface &out, string_view text, const Rectangle &rect, UiFlags flags, int spacing, int lineHeight, bool drawTextCursor)
```

**Comment by AJenbo** [comment]
I would consider this a vanilla bug, cause it only happens if you have negative 100 or less, and you shouldn't be able to get less then 0 :D

**Comment by qndel** [comment]
ofc you should, if not, then equipping a +mana item and unequipping it could make you lose some mana which is unacceptable :)

**Comment by AJenbo** [comment]
I'm pretty sure it would make you gain some mana :D

**Comment by qndel** [comment]
> I'm pretty sure it would make you gain some mana :D

ye, that's even worse xD keep swapping, casting ,swapping , congrats on destroying ironman and everything else :D

**Comment by qndel** [comment]
Fixed by https://github.com/diasurgical/devilutionX/commit/a737d72dd977e98b4a593b2701e9b28959596875
