### ISSUE TITLE
Some spells don't deal damage anymore

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2683]
Torchant cannot be killed introduced with commit bea8cc9d87d04271ee2adc83f635e6c5b0aeade8.
Savegame:
[torchant.zip](https://github.com/diasurgical/devilutionX/files/7033904/torchant.zip)

**Comment by ThomasChr** [comment]
I can't kill Bloodgutter.
Works on 1.2.1. Possibly the same problem.
[single_9.zip](https://github.com/diasurgical/devilutionX/files/7034151/single_9.zip)

**Comment by ThomasChr** [comment]
![image](https://user-images.githubusercontent.com/13014163/130500514-a7bd88d6-0066-4fdf-b290-34e0706268a9.png)
mindam is 0, maxdam is 0, so dam will always be 0.

**Comment by qndel** [comment]
The problem is not with monsters but with spells, a lot of them don't deal damage - lightning wall / lightning / nova / apoc etc.
