### ISSUE TITLE
crash on debug command "help"

### ISSUE THREAD

**Issue by vladtepesch** [diasurgical/devilutionX#2687]
**Important information**
current master build with VS 2019

**Describe**
crash happens if debug command "help" is issued.  
crashes within `NetSendCmdString` coming from the `while` loop in `CheckDebugTextCommand`

**To Reproduce**

- open a game in a debug build (singleor multiplayer)
- hit enter to open chat window
- type "help" enter

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/issues/2672
