### ISSUE TITLE
Right clicking inventory triggers spell casting

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2696]
**To Reproduce**
1. Select a spell (that you can cast)
2. Open the inventory and right click some where blank on it.

**Expected behavior**
Nothing

**Comment by ThomasChr** [comment]
Can't reproduce on Linux, 4e44e1e10e768eaf2565dd8ed3bc8cefec27a2c5 - am I doing something wrong? Seemed like a rather easy bug to reproduce (and fix).

**Comment by ThomasChr** [comment]
Also no reproducing in windows 4e44e1e10e768eaf2565dd8ed3bc8cefec27a2c5 - I must be doing something wrong.
I noticed that I can reproduce it (kind of) when clicking a few times right next to the inventory window and then while clicking all the time in the inventory window. There was one(!) firebolt which I wouldn't have expected because the click was while I was on the inventory window. But that was just one bolt and I won't really call that a bug.

**Comment by AJenbo** [comment]
640x480?

**Comment by ThomasChr** [comment]
Nope, tried 640x480 in fullscreen and windowed on Windows. Couldn't reproduce... Am I really this dumb?

**Comment by AJenbo** [comment]
maybewatch soundchasere83 stream from last night

**Comment by ThomasChr** [comment]
I'm on it. But it's so long and I don't have that much time :-)
Surely I will get to it!
You don't have a timestamp, do you?
Link to stream: https://www.twitch.tv/videos/1128433201

**Comment by AJenbo** [comment]
The best I have is that it was shortly before i posted this issue.

**Comment by ThomasChr** [comment]
Shortly after 00:55:20. He drinks the potions and at the same time calls healing spell.

**Comment by ThomasChr** [comment]
And I can reproduce it. It's only with the healing spell. Not with firebolt!

**Comment by ThomasChr** [comment]
This does seem by choice. Some spells can be called even when in the inventory!
See: CheckPlrSpell()
![grafik](https://user-images.githubusercontent.com/13014163/130809626-cf229a16-812a-471b-85ff-69d6155c3369.png)

**Comment by ThomasChr** [comment]
This does some to come from Devilution. So it's vanilla, I suppose, but I can't check because I don't have vanilla here.

**Comment by AJenbo** [comment]
Thanks for figuring out what was going on 😅

This does seem oddly inconsistent.

**Comment by qndel** [comment]
It's not a bug, it's a feature.

**Comment by NiteKat** [comment]
This is 100% Vanilla behavior, I know it was confirmed from Devilution code, but I also confirmed in GOG real quick.

**Comment by ThomasChr** [comment]
So we could change that, but we need to know:
a) No casting of Infravision or Healing while in Inventory anymore, or
b) Adding all spells which don't have a direction, such as Mana Shield or Reflect.

**Comment by qndel** [comment]
definitely b

**Comment by qndel** [comment]
then you wouldn't be able to keep drinking mana potions and casting healing which is way more serious than accidentally casting a spell - you will learn and won't repeat that mistake again ;)

**Comment by StephenCWills** [comment]
If that's our justification for including the Healing spell, then I suppose the same logic should apply to Mana Shield as well. By that reasoning, Infravision and Reflect shouldn't need to be on that list.

Personally, I don't spam-click potions in my inventory so I can't really assert a preference. However, I'm inclined to think that casting from the inventory should be limited to spells that require the user to interact with the inventory so my vote is for option a.

**Comment by AJenbo** [comment]
> casting from the inventory should be limited to spells that require the user to interact with the inventory

That's my thinking, but I'm not a pro gamer so :shrug:
