### ISSUE TITLE
Magic Mushroom

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#27]
The quest goes as follows, you find a fungal tome item bring that back to Adria the witch. She tells you that Pepin wants to make some sort of potion and when you talk to Pepin he tells you he needs the brain of a demon. The first monster you kill after this should drop said brain, but for some reason it never did for me.

Related to this issue I think, is that when I talked to Pepin the healer after completing the Black mushroom part of the "Magic Mushroom" quest, the first monster I killed didn't drop the quest item "Monster Brain" so I wasn't able to return that to Pepin and complete the quest.

_Originally posted by @predator8bit in https://github.com/diasurgical/devilutionX/issues/24#issuecomment-468927385_

**Comment by predator8bit** [comment]
I did 2 more runs, couldn't replicate the issue so I'll just close it for now.

**Comment by AJenbo** [comment]
Duplicate of #24
