### ISSUE TITLE
Monster on same tile as a door

### ISSUE THREAD

**Issue by ThomasChr** [diasurgical/devilutionX#2700]
**Important information**
Linux on commit d8a0211da864a9195311f01af19797652e3a5814

**Describe**
I'm not quite sure if the monster spawned exactly there, but I've never been at the door to my left. But there seems to be a monster occupying the same tile as the (closed) door. You can hit it with a firebolt and if you come too close it can hit you through the closed door without opening it.

**To Reproduce**
Open the savegame, walk to the left. Please don't kill my hero!

**Expected behavior**
Either it's behind the closed door or in front of the closed door. Both things at the same time sound to me like Schrödinger's cat.

**Screenshots**
![image](https://user-images.githubusercontent.com/13014163/130851224-40933bd0-782b-41e3-b6fd-967dfde8f2ef.png)
![image](https://user-images.githubusercontent.com/13014163/130851231-7f725375-18d3-40e1-a451-59f462e559fa.png)
[single_9.zip](https://github.com/diasurgical/devilutionX/files/7049359/single_9.zip)

**Comment by ClayCthulhu** [comment]
[single_4.zip](https://github.com/diasurgical/devilutionX/files/7574279/single_4.zip)
Bat's struck in door. Go some southeast.
