### ISSUE TITLE
Import missile generic viable documentation

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/DevilutionX#2704]
**Describe**
@pionere has taken the time to document the intent of the generic missile variables which is really useful. Since the fork is only selectively synced with upstream there is a significant diff between the two forks, and so a bit of manual work would be required to bring the import the documentation.

The task is then to match the relevant function and check that the generic variables still match up. Relevant downstram can be found here:
https://github.com/pionere/devilutionX/blob/master/Source/missiles.cpp

Diasurgical DeviutionX:
```cpp
void AddCbolt(MissileStruct &missile, Point dst, Direction midir)
```

Pionere DeviutionX:

```cpp
/**
 * Var1: light strength
 * Var2: base direction
 * Var3: movement counter
 * Var4: rnd direction
 */
int AddCbolt(int mi, int sx, int sy, int dx, int dy, int midir, char micaster, int misource, int spllvl)
```

**Expected result**
```cpp
/**
 * var1: Light strength
 * var2: Base direction
 * var3: Movement counter
 * var4: Random direction
 */
void AddCbolt(MissileStruct &missile, Point dst, Direction midir)
```

**Additional**
Bonus point for simultaneously renaming the variables from `_miVar#` to `var#`.

**Comment by Sid672** [comment]
I will work on the issue if anything is remaining.

**Comment by Sid672** [comment]
Missile.cpp and missile.h file is already completed by @bcko. @AJenbo do you want to change any other file?
