### ISSUE TITLE
Cel created with png2cel crashes

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2715]
[squares.zip](https://github.com/diasurgical/devilutionX/files/7064658/squares.zip)

a cel created with png2cel crashes in devilutionx
failed to get pcx to work as well

**Comment by AJenbo** [comment]
Works perfectly fine:

![image](https://user-images.githubusercontent.com/204594/131222379-2b65986f-3762-44d5-bcd6-20a8af8ba81e.png)

```cpp
@@ -927,7 +927,7 @@ void InitControlPan()
 	pManaBuff.emplace(88, 88);
 	pLifeBuff.emplace(88, 88);
 
-	pChrPanel = LoadCel("Data\\Char.CEL", SPANEL_WIDTH);
+	pChrPanel = LoadCel("square_orange.cel", 64);
```

My guess is that you either provided the wrong width or loaded it as a different type of CEL

**Comment by qndel** [comment]
Yup :D I've never used png2cel so didn't know it supports different cel types, I only copy/pasted the debug square code and it crashed, changing CelDrawClipped into CelDraw fixed it :)
