### ISSUE TITLE
Port inventory synchronization from Pionere's fork

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2724]
**Describe**
@pionere has a lot of interesting in his port, one of the major parts is inventories syncronization for multiplayer

This is mainly done via the two following commits: https://github.com/diasurgical/devilutionX/commit/ee39ebabd354bf963141a8e73620ceb7de63e255 - https://github.com/diasurgical/devilutionX/commit/5baf6a6dc99dd106754cdb3fe0a2bb84609f8139

Porting this is complicated a bit by large part of the fork still using an holder iteration of the code and a different code style, but it should still be reasonably to do do so.

**Steps**
1. Go over the two commits and get a good feel for the semantic changes, and separate it from the style changes.
2. Start applying the same changes to the code
3. Run two clients on your local system and run a TCP game where you test that the items are being synced (you could do this by adding some player debug info).
4. Create a pull request with the backported code

**Expected behavior**
It might be a good idea to also test this on the fork before starting the process to get a good feel for how it works and now to verify it.

**Comment by obligaron** [comment]
I think with #5217 this is obsolete/done.
