### ISSUE TITLE
Move documentation from implementations to declarations

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2735]
**Describe**
A lot of documentation has been added to the implementation in .cpp files, but the proper place for it is in the header files (.h).

**Steps**
1. Find functions with documentation comments
2. Cut the comment
3. Insert it above the function definition in the .h file

**Additional context**
![image](https://user-images.githubusercontent.com/204594/131220345-ae1235c8-024e-46a5-bca1-aa3c81c482ae.png)
![image](https://user-images.githubusercontent.com/204594/131220367-359de284-5b03-49b0-bc8b-3e9a2efdf2ac.png)

**Comment by qndel** [comment]
What about functions that aren't in headers? ;)

**Comment by AJenbo** [comment]
They are locale so there descriptions stay in the .cpp file, they are easy to spot as they are all in the anonymous `namespace {}`.

**Comment by bcko** [comment]
I will work on this.

**Comment by Sid672** [comment]
@bcko if u are not working on this. I would like to contribute to this issue. 
@AJenbo can I work on this?

**Comment by bcko** [comment]
@Sid672 sure, you can also reference #2740

**Comment by AJenbo** [comment]
>  @AJenbo can I work on this?

Please :) There is plenty of it.

**Comment by Sid672** [comment]
@AJenbo  created a pull request https://github.com/diasurgical/devilutionX/pull/2767 after moved documentation of town.cpp to town.h. Please review it.

**Comment by Sid672** [comment]
Thanks, @AJenbo  for explaining everything. I start working on other files too.

**Comment by Sid672** [comment]
@AJenbo I think all files are completed. If any file is remaining please tell me.
