### ISSUE TITLE
Dungeon items appearing in town

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2765]
do changelevel 0
![image](https://user-images.githubusercontent.com/14297035/131569404-b7ad7479-764c-420a-9f8a-9fbcf6e31dbb.png)

[single_33.zip](https://github.com/diasurgical/devilutionX/files/7086585/single_33.zip)

Must be dItem/Items/whatever not being cleared

**Comment by obligaron** [comment]
How can i reproduce?
I loaded the save and did `changelevel 0`, but i didn't found any items in town.

**Comment by qndel** [comment]
Uh actually no idea now, doesn't work for me either :D
