### ISSUE TITLE
Missiles do not get properly purged when blocked

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2770]
**Describe**
Blocking a missile causes it to be removed, but does not clear it from the map

**To Reproduce**
1. Fight a succubus
2. Block a flare projectile
4. See error `INFO: Draw Missile 2 type 24: NULL Cel Buffer`

**Expected behavior**
The missile references should be cleared so that the render no longer attempts to draw it

**Additional context**
This is likely a vanilla issue

**Comment by StephenCWills** [comment]
I don't think they're supposed to be removed. See #1531

**Comment by qndel** [comment]
> I don't think they're supposed to be removed. See #1531

I think it's about blocking them generating an error?

**Comment by StephenCWills** [comment]
> I think it's about blocking them generating an error?

I mentioned it here.
https://github.com/diasurgical/devilutionX/issues/1531#issuecomment-824462722

Here's where I spotted the error.
https://github.com/diasurgical/devilutionX/issues/1531#issuecomment-824498851

And I fixed it in my draft PR.
https://github.com/diasurgical/devilutionX/pull/1641/commits/fd8a463f5a69c129a543b9efd9a3480a1dd2e687

**Comment by StephenCWills** [comment]
To be clear, when a missile is blocked by the player, the missile keeps traveling along the same path and continues to check collisions after the frame on which it's blocked. To add a bit of flavor, the game rotates the missile to make it fly crooked as a visual indicator that the missile did indeed collide with the shield/monk that blocked it. At that point, the game generates a random number to determine which direction the missile should be rotated. Also, looking at the code below, it looks like this behavior is specific to Hellfire.

https://github.com/diasurgical/devilutionX/blob/03eb86b1186f69e1e87366b1ed5e59556fa9d231/Source/missiles.cpp#L474-L482

Note that the logic RNG logic here will produce either a 1 or -1 which is used to calculate the index of an adjacent animation from the `mAnimData` array. Blood Star only has animation data at index 0 so a value of 1 will cause it to read null animation data. Upon reviewing the logic again, it looks to me like this may just be an off-by-one error.

```diff
  if (dir < 0)
      dir = mAnimFAmt - 1;
- else if (dir > mAnimFAmt)
+ else if (dir >= mAnimFAmt)
      dir = 0;
```
