### ISSUE TITLE
Shift Click Melee Attacks Hurt Players While Player Friendly

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#2772]
**Important information**
Windows 10 Pro / DevilutionX 1.2.1 / Downloaded release

**Describe**
If you shift click to melee attack while player friendly, your attack can hit another player.

**To Reproduce**
1. Enter a multiplayer game with at least two players.
2. Go to dungeon level 1.
3. Position the players next to each other, and while player friendly hold shift and click on the other player.
4. Do this enough times and you'll see that you can damage the player.

**Expected behavior**
Melee attacks should NEVER be able to hurt another player while you are player friendly.

**Comment by julealgon** [comment]
Just to be clear: this doesn't happen in vanilla?

**Comment by NiteKat** [comment]
Correct. In Vanilla, Melee attacks should never friendly fire while you are Player Friendly. Missiles do, but melee doesn't. This is often used to pass time in Ironman runs when you're waiting for another player who stepped away for a moment, we just start swinging at each other while player friendly. 😆

**Comment by AJenbo** [comment]
We broke Ironman :(

![image](https://user-images.githubusercontent.com/204594/131708082-76f618f3-c7b9-4a43-b6ad-7d3dc5b2f75a.png)
