### ISSUE TITLE
Little Girl Quest Menu Dialog Broken for Non-Host Players

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#2781]
**Important information**
Windows 10 Pro / 1.2.1 / Downloaded release

**Describe**
Selecting the Little Girl option from the quest menu is playing Cain's quote about King Leoric.

**To Reproduce**
1. Join a multiplayer game in Hellfire.
2. Have the host talk to Celia to activate the Little Girl quest.
3. Talk to Celia.
4. Open quest menu.
5. Select Little Girl. Decard Cain is now speaking to you about King Leoric.

**Expected behavior**
The initial quest text from Celia should play when Little Girl is selected.

**Additional context**
Not sure if *all* of the steps are needed, but this is how the situation happened for @AJenbo and I. It might just be broken for players 2-4 and not player 1.

**Comment by obligaron** [comment]
This is already fixed. 🙂
In 1.2.1 it's reproducible and in 1.4.1 it's already fixed.
