### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#279]
Several flags are defined in our CmakeLists.txt so silence both errors and warnings during compilation. Instead, these should be solved. If possible all errors relating to the Source folder should be fixed upstream, but if they cannot be solved in a way that doesn't change the ASM then they can be dealt with in DeviliutionX, for now we should however try to limit it to the SourceX folder since we want to avoid merge issues in the future (Hellfire, reordered function, and global alignment may change quite a bit of the code).

**Comment by vichoca9** [comment]
I was compiling the current source on an old PC, and I found that the current version of libsodium-dev(1.0.8-) was giving errors. I updated it to latest and now it is OK.

 Maybe recommend to use latest(or specific) libraries if posible?

**Comment by AJenbo** [comment]
To progress on this we need to merge https://github.com/diasurgical/devilution/pull/1749

**Comment by aydjay** [comment]
I think this issue can be closed as #1749 has been merged in manually.

**Comment by AJenbo** [comment]
Well that has only really allowed use to start working on the actual warnings. Most of the ones at the current level has been fixed, but I belive there are a lot more that will show if we allow stop supressing them in CmakeList.txt

**Comment by AJenbo** [comment]
We should still enable more warnings from the compilers and deal with them, and there are also still some in MSVC. But the majority has now been fixed, so closing this issue.

**Comment by julealgon** [comment]
> We should still enable more warnings from the compilers and deal with them

❤️
