### ISSUE TITLE
Implement pgettext to allow translation of identical string with different meanings

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2790]
**Describe**
Some texts may appear identical in English, but needs to be translated differently for other languages. To facilitate this we need to implement [pgettext](https://www.gnu.org/software/gettext/manual/html_node/Contexts.html) and utilize it for the offending strings.

Once implemented the monster names in `monstdat.cpp` should be translated using `pgettext` and given the context of "monster". Since they are in a static array we will need to add a NOP macro `P_(context, message)`, which should be added to the translation file's additional search keywords: `P_:1c,2`

**Additional context**
See `LanguagePluralTranslate` for a function that solves a similar issue.

See the GetText macro implementation of [pgettext](https://github.com/coreutils/gnulib/blob/master/lib/gettext.h#L111)

**Comment by NikoVP** [comment]
I have already opened an issue a while back for the cases of lightning and town portal https://github.com/diasurgical/devilutionX/issues/2369

**Comment by AJenbo** [comment]
Monster name are not there own separate translation strings

**Comment by StephenCWills** [comment]
I assume you meant "now" rather than "not"?
