### ISSUE TITLE
Spooky Shrine without effect in TCP/IP multiplayer

### ISSUE THREAD

**Issue by Tmkrth** [diasurgical/devilutionX#2821]
Hello!

While playing devilutionX release 1.2.1 without Hellfire via TCP/IP multiplayer (host: Linux, connected friend: Windows) we noticed that Spooky Shrines don't seem to work. They should grant "full rejuvenation potions for other players" [1].

While the messages are shown correctly to the players, nothing happens. No rejuvenation potions drop or appear in other's inventory.

Friendly melee is off via button in game and friendly spelldamage is off via config file.

[1] https://diablo2.diablowiki.net/Diablo_I_Shrines

**Comment by qndel** [comment]
This website is shit, it actually fully heals other players, that's it.

**Comment by Tmkrth** [comment]
Thanks qndel, do you know of a better ressource for looking up shrine effects for D1?

**Comment by qndel** [comment]
Not really, quick google got me this and it looks better already - http://www.lurkerlounge.com/lochnar/shrines.txt
