### ISSUE TITLE
Game changes if first word does not fit in the text area

### ISSUE THREAD

**Issue by inukaze** [diasurgical/devilutionX#2829]
@AJenbo : i had strange bug if i translate "Resist Magic" (ID : 1316) to "Rest. Magica" / "Magica" / "Magicka" the Devilution Client or hang up or make a segmentation fault.

![DevilutionX-TraSpa-001](https://user-images.githubusercontent.com/1647332/132582988-367d1b79-5309-4fb3-9768-c9f098040957.png)

The most accurate translation of "Resist Magic" to spanish is "Resistencia Magica" but is too long, because of that i use the abreviature "Rest." but the error looks like is something character quantity, because if i add "Rest. Magia1" i got same error. and is just adding one character more.

But is something strange because is i just put the word "Magica" (less character) happend the same, is something prohibiting the use of word "Magica" or similars ?

Well i should leave the translation with "Rest. Magia" is not right but the spanish speakers goes to think "Resistencia a la magia".

![DevilutionX-TraSpa-002](https://user-images.githubusercontent.com/1647332/132583005-fa3bacc1-649d-4081-a109-a84d25cc5461.png)

i left a copy of my Spanish Translation Here -> https://www.mediafire.com/file/c84tkhi4tseryxm/es_VE.po/file

**Comment by julealgon** [comment]
Off-topic: "Golpe" seems completely wrong for "chance to hit". It's basically just the "hit" part, which has a completely different meaning. Or maybe I'm missing something?

Is this a partially automatic translation?

**Comment by AJenbo** [comment]
This is a bug that happens when a single word (maybe just in cases when it's the first) will not fit in the assigned area.

I have a fix for it, but it's currently tied up with some other changes.

**Comment by inukaze** [comment]
> Off-topic: "Golpe" seems completely wrong for "chance to hit". It's basically just the "hit" part, which has a completely different meaning. Or maybe I'm missing something?

On Spanish if you see "Golpe" (hit) an next the number with " % " the people automatically asume is porcent of probability to make hit, 

Maybe you miss something. Spanish can be quite complicated, since, like Japanese. It allows too many things that even native speakers may find strange.

> Is this a partially automatic translation?
No is translate for spanish 100% native

**Comment by julealgon** [comment]
> On Spanish if you see "Golpe" (hit) an next the number with " % " the people automatically asume is porcent of probability to make hit,

That seems really weird. I'm Brazilian and the translation would be very similar, but if I saw the same thing in pt-BR it would barely make sense.

> Maybe you miss something. Spanish can be quite complicated, since, like Japanese. It allows too many things that even native speakers may find strange.

I'll take your word for it then.
