### ISSUE TITLE
Keymapping request -> Item pickup "Alt" key

### ISSUE THREAD

**Issue by Baracudus** [diasurgical/devilutionX#2832]
Requesting an option in "diablo.ini" for remapping the "Item pickup key" 

![image](https://user-images.githubusercontent.com/71731621/132782182-7839d6e7-c93d-4f21-9122-57b359aaa6a7.png)

**Comment by julealgon** [comment]
This should be generalized to all inputs IMHO. It is a known limitation of the mapper. Clicks, shift, esc, space bar etc all should be remappable.

**Comment by qndel** [comment]
> This should be generalized to all inputs IMHO. It is a known limitation of the mapper. Clicks, shift, esc, space bar etc all should be remappable.

Have fun after pressing shift x5

**Comment by StephenCWills** [comment]
Is there a key for item pickup?

**Comment by Baracudus** [comment]
> Is there a key for item pickup?
> 
> EDIT: I guess if it's the Alt key, it must be item highlight.

In the beta, Alt is mapped to Item pickup. In diablo 2, I mapped it since 20 years to space.. so.. Would be nice . 😁🤙

**Comment by julealgon** [comment]
> > This should be generalized to all inputs IMHO. It is a known limitation of the mapper. Clicks, shift, esc, space bar etc all should be remappable.
> 
> Have fun after pressing shift x5

Are you alluding to sticky keys? That can be disabled easily.
