### ISSUE TITLE
Golem can spawn on a player's tile

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#2833]
**To Reproduce**
Cast the Golem spell on top of a player or on an object directly northeast of a player.

**Expected behavior**
Golem should spawn on a nearby empty tile instead of the player's tile.

**Screenshots**

https://user-images.githubusercontent.com/9203145/132797058-411e180c-27d1-42af-b9fc-75cdec8ac702.mp4

**Additional context**
It seems the `AddGolem()` function uses the crawl table to locate the nearest dungeon tile that isn't occupied, but it only checks for monsters, solid tiles, and objects. The crawl table checks southwest first if the initial tile is occupied so that's how I did it in the video, but it seems you can literally just cast at the player's feet and the golem will spawn there.

This bug is actually documented on lurkerlounge, although their description suggests you need to be standing next to an enemy. I suppose that just keeps the Golem from moving right away.

> http://www.lurkerlounge.com/forums/thread-12422.html
> If, while standing adjacent to an enemy, you cast a golem with your cursor on yourself, the golem will appear on your tile. Your golem takes no damage with this bug.

**Comment by julealgon** [comment]
Damn this one was quick 🤣
