### ISSUE TITLE
Bugged Ring "+65528% chance to hit"

### ISSUE THREAD

**Issue by AGChenier** [diasurgical/devilutionX#2842]
I have looted a blue ring named "Tin ring of the night", which was doing negative chance to hit bonus and -20% light radius. When I dropped it to show it to my friend, suddenly, the negative % chance to hit became +65528% ! I assume this is a converting error type. I believe the stats are true. I have tried to attack monsters with it equipped and it seems that I don't ever miss my attacks. 

![Diablo1 Bug Ring2](https://user-images.githubusercontent.com/80531885/132952684-89de27a3-1e04-4f31-bee2-b3eadc8fd48c.png)

**Comment by StephenCWills** [comment]
Please follow the template for submitting issues. In particular, it would be helpful if you could share what version of the game you are playing and the savegame with the item that you found.

I suspect this is already resolved in master.

![image](https://user-images.githubusercontent.com/9203145/132953382-79f6f9e9-a757-4e2c-a5d3-89295ec89b88.png)

**Comment by AJenbo** [comment]
It's fixed and will be part of 1.3.0, you can also grab a test build if you would like to help test things before release (a few weeks from now):

![image](https://user-images.githubusercontent.com/204594/134255377-be096894-d1ce-42ac-a951-14c8328be99b.png)
