### ISSUE TITLE
Multiplayer-only buttons showing up in single player

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#2854]
**Important information**
Linux / a12a7511a94fc674e25c221bacc5aa529269d922 / compiled by myself
**Describe**
The "Send message" and "Player friendly/attack" buttons show up in single player.

**To Reproduce**
1. Start or load a single player game.

**Expected behavior**
The "Send message" and "Player friendly/attack" buttons should not be there.

**Comment by AJenbo** [comment]
It's being used for debug commands in debug builds, since you did a self build I'm going to assume that you did not compile a release build.

https://github.com/diasurgical/devilutionX/blob/master/Source/debug.cpp#L618

Eventually will create a separate console for it.

**Comment by vlolteanu** [comment]
That's right. I made a debug build.
