### ISSUE TITLE
Trigger text takes priority over item name

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2859]
When mouse button is pressed down, trigger text is taking priority over item name as seen on the gif
![triggertext](https://user-images.githubusercontent.com/14297035/133044917-4bd9c93f-3484-404b-b96f-e90fe22ee22c.gif)

**Comment by julealgon** [comment]
Why is the trigger text even being activated there? I don't think this is a matter of priority at all. It just shouldn't highlight the trigger if the inventory is on top of it.

How does this behave in vanilla?

**Comment by qndel** [comment]
> Why is the trigger text even being activated there? I don't think this is a matter of priority at all. It just shouldn't highlight the trigger if the inventory is on top of it.
> 
> How does this behave in vanilla?

Correctly. Hence no vanilla tag.
