### ISSUE TITLE
Update to libsmacker 1.2

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#2870]
Looks like libsmacker 1.2 is out

Hoping that it will let us enable streaming video everywhere and fix the video issues on Amiga

https://sourceforge.net/projects/libsmacker/files/libsmacker-1.2/

**Comment by AJenbo** [comment]
I hope our patch for checking for palette changes where included :D

**Comment by glebm** [comment]
It was not :(

**Comment by glebm** [comment]
Unfortunately, no new API for streaming either
