### ISSUE TITLE
Inconsistency in splash screen

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#2887]
Windows 10:

Full sound - windowed:
https://user-images.githubusercontent.com/14297035/133771732-e1a58644-938d-47e5-bef8-d28508856a77.mp4

Sound cut off - fullscreen
https://user-images.githubusercontent.com/14297035/133771738-3bb425e9-9902-4c25-b438-0c11cc07e3cd.mp4

After going fullscreen, beginning of splash screen sound is cut off

#edit 
seems to be related to "upscale" setting
with upscale=1 and fullscreen the sound is smooth
with upscale=0 and fullscreen the start of splash screen is cut off

and is not only about sound but more generic - when there's no sound, splash screen isn't being displayed either so with upscale=0 it seems like start of it (audio/video) is cut off

Seems I've narroved it down to `SDL_WINDOW_FULLSCREEN_DESKTOP` flag, with it it's smooth, without it splash screen is cut off

My config:
```
;Diablo.ini
;customize your "hotkey" msgs by changing the text below


[NetMsg]
F9=I need help! Come Here!
F10=Follow me.
F11=Here's something for you...
F12=Now you DIE!
QuickMessage1=I need help! Come Here!
QuickMessage2=Follow me.
QuickMessage3=Here's something for you.
QuickMessage4=Now you DIE!


[Diablo]
Intro=0


[Hellfire]
Intro=0
SItem=


[Audio]
Sound Volume=0
Music Volume=-1600
Walking Sound=1
Auto Equip Sound=1
Sample Rate=22050
Channels=2
Buffer Size=2048
Resampling Quality=5


[Graphics]
Width=640
Height=480
Fullscreen=0
Upscale=0
Fit to Screen=0
Scaling Quality=2
Integer Scaling=0
Vertical Sync=0
Blended Transparency=1
Gamma Correction=100
Color Cycling=1
Hardware Cursor=0
Hardware Cursor For Items=1
Hardware Cursor Maximum Size=128
FPS Limiter=1
Show FPS=0


[Game]
Speed=20
Run in Town=0
Grab Input=0
Theo Quest=0
Cow Quest=0
Friendly Fire=1
Test Bard=0
Test Barbarian=0
Experience Bar=0
Enemy Health Bar=0
Auto Gold Pickup=0
Adria Refills Mana=0
Auto Equip Weapons=1
Auto Equip Armor=0
Auto Equip Helms=0
Auto Equip Shields=0
Auto Equip Jewelry=0
Randomize Quests=1
Show Monster Type=0
Disable Crippling Shrines=0
Recolor Stairs On Map=1


[Network]
Bind Address=0.0.0.0
Port=6112
Previous Host=localhost


[Controller]
Mapping=
Swap Shoulder Button Mode=0
Dpad Hotkeys=0
deadzone=0.070000


[Language]
Code=en


[Keymapping]
Help=F1
QuickSpell1=F5
QuickSpell2=F6
QuickSpell3=F7
QuickSpell4=F8
QuickMessage1=F9
QuickMessage2=F10
QuickMessage3=F11
QuickMessage4=F12
DecreaseGamma=G
IncreaseGamma=F
Inventory=I
Character=C
QuestLog=Q
Zoom=Z
DisplaySpells=S
SpellBook=B
GameInfo=V
BeltItem1=1
BeltItem2=2
BeltItem3=3
BeltItem4=4
BeltItem5=5
BeltItem6=6
BeltItem7=7
BeltItem8=8
QuickSave=F2
QuickLoad=F3
QuitGame=
StopHero=
ItemInfo=
QuestDebug=
DebugToggle=X
```

**Comment by StephenCWills** [comment]
I believe this is because `Upscale=0` causes SDL to change the resolution of your monitor at startup, like an old game would. If I set `Width=1920` and `Height=1200` to match the resolution of my monitor, nothing gets cut off in either the video or audio.

Also, I think this is somewhat hardware- and OS-dependent. The beginning of the audio doesn't cut off on my system, but the beginning of the video does. Are your speakers built into (or plugged into) your monitor?
