### ISSUE TITLE
Shooting arrows crackling sound

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2888]
Since I promised to test intensively before the next release, I decided to test a bit more broadly and to play with other characters that I otherwise rarely use.

And then it happened that I discovered something that otherwise probably no one would have noticed.
So I have now played with the rogue and noticed cracking noises again and again when shooting the arrows.

How to reproduce:
1. load the attached game
[sound_test.zip](https://github.com/diasurgical/devilutionX/files/7188317/sound_test.zip)
2. to  hear it better, mute the in game music
3. make sure that your surroundings are as quiet as possible 
4. shoot lots of arrows and watch out for crackling noises

Example:
In the attachment pay attention to the last shot.

https://user-images.githubusercontent.com/45902449/133850760-6ea98444-574d-495f-abe4-70532089e2f5.mp4

Since when does it happen:
After bisecting it was discovered that the issue appeared since commit 3ae5abc9577b44930d8b398e9e30fc82237f0284.

What is desired:
No crackling noises when shooting arrows

**Comment by StephenCWills** [comment]
I can hear it in the video, but I'm having difficulty reproducing myself. Can you share what platform you're running as well as the sound settings from your diablo.ini file?

**Comment by Chance4us** [comment]
I'm on linux (Debian stable release).
SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
[diablo.ini.txt](https://github.com/diasurgical/devilutionX/files/7188637/diablo.ini.txt)
![hwinfo](https://user-images.githubusercontent.com/45902449/133858733-cfe05d48-8c37-41cd-bd76-553d1e52d8b7.png)

**Comment by Chance4us** [comment]
user@3600:~$ lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Starship/Matisse IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:01.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse GPP Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:03.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:03.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse GPP Bridge
00:04.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:05.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:07.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:07.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
00:08.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
00:08.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Internal PCIe GPP Bridge 0 to bus[E:B]
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 61)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Matisse Device 24: Function 7
03:00.0 USB controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset USB 3.1 XHCI Controller (rev 01)
03:00.1 SATA controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset SATA Controller (rev 01)
03:00.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Bridge (rev 01)
20:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
20:01.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
20:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
20:05.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
20:06.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
20:07.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
21:00.0 Network controller: Intel Corporation Wireless-AC 9260 (rev 29)
22:00.0 Ethernet controller: Intel Corporation I211 Gigabit Network Connection (rev 03)
26:00.0 Multimedia controller: Philips Semiconductors SAA7160 (rev 03)
29:00.0 VGA compatible controller: NVIDIA Corporation TU117 [GeForce GTX 1650] (rev a1)
29:00.1 Audio device: NVIDIA Corporation Device 10fa (rev a1)
2a:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Starship/Matisse PCIe Dummy Function
2b:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Reserved SPP
2b:00.1 Encryption controller: Advanced Micro Devices, Inc. [AMD] Starship/Matisse Cryptographic Coprocessor PSPCPP
2b:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Matisse USB 3.0 Host Controller
2b:00.4 Audio device: Advanced Micro Devices, Inc. [AMD] Starship/Matisse HD Audio Controller
30:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 51)
31:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 51)
user@3600:~$ lsmod
Module                  Size  Used by
xt_CHECKSUM            16384  1
xt_MASQUERADE          20480  3
xt_conntrack           16384  1
ipt_REJECT             16384  2
nf_reject_ipv4         16384  1 ipt_REJECT
xt_tcpudp              20480  9
nft_compat             20480  16
nft_chain_nat          16384  2
nf_nat                 53248  2 nft_chain_nat,xt_MASQUERADE
nf_conntrack          176128  3 xt_conntrack,nf_nat,xt_MASQUERADE
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
nft_counter            16384  33
nf_tables             245760  106 nft_compat,nft_counter,nft_chain_nat
nfnetlink              16384  2 nft_compat,nf_tables
bridge                253952  0
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
lz4                    16384  12
btusb                  65536  0
btrtl                  24576  1 btusb
btbcm                  20480  1 btusb
btintel                32768  1 btusb
snd_hda_codec_realtek   151552  1
bluetooth             737280  5 btrtl,btintel,btbcm,btusb
snd_hda_codec_generic    98304  1 snd_hda_codec_realtek
edac_mce_amd           32768  0
ledtrig_audio          16384  1 snd_hda_codec_generic
iwlmvm                339968  0
snd_hda_codec_hdmi     73728  1
kvm_amd               114688  0
jitterentropy_rng      16384  1
snd_hda_intel          57344  3
binfmt_misc            24576  1
snd_intel_dspcfg       28672  1 snd_hda_intel
mac80211              983040  1 iwlmvm
soundwire_intel        45056  1 snd_intel_dspcfg
kvm                   917504  1 kvm_amd
drbg                   40960  1
soundwire_generic_allocation    16384  1 soundwire_intel
snd_soc_core          315392  1 soundwire_intel
libarc4                16384  1 mac80211
irqbypass              16384  1 kvm
snd_compress           32768  1 snd_soc_core
aes_generic            36864  0
soundwire_cadence      36864  1 soundwire_intel
ghash_clmulni_intel    16384  0
snd_hda_codec         172032  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
vhba                   28672  1
nvidia_drm             61440  3
aesni_intel           368640  0
snd_hda_core          110592  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
iwlwifi               294912  1 iwlmvm
crypto_simd            16384  1 aesni_intel
snd_hwdep              16384  1 snd_hda_codec
soundwire_bus          90112  3 soundwire_intel,soundwire_generic_allocation,soundwire_cadence
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
glue_helper            16384  1 aesni_intel
ansi_cprng             16384  0
snd_pcm               135168  7 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,soundwire_intel,snd_compress,snd_soc_core,snd_hda_core
ecdh_generic           16384  1 bluetooth
ecc                    36864  1 ecdh_generic
cfg80211              970752  3 iwlmvm,iwlwifi,mac80211
drm_kms_helper        274432  1 nvidia_drm
joydev                 28672  2
evdev                  28672  18
rapl                   20480  0
snd_timer              49152  1 snd_pcm
wmi_bmof               16384  0
libaes                 16384  3 bluetooth,aesni_intel,aes_generic
snd                   110592  16 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_compress,snd_soc_core,snd_pcm
cec                    61440  1 drm_kms_helper
ccp                   106496  1 kvm_amd
k10temp                16384  0
rfkill                 28672  6 bluetooth,cfg80211
soundcore              16384  1 snd
sg                     36864  0
rng_core               16384  1 ccp
nvidia_modeset       1232896  6 nvidia_drm
button                 24576  0
acpi_cpufreq           32768  0
nvidia              34205696  191 nvidia_modeset
nct6775                73728  0
hwmon_vid              16384  1 nct6775
zram                   36864  1
zsmalloc               32768  1 zram
parport_pc             40960  0
ppdev                  24576  0
lp                     20480  0
drm                   618496  6 drm_kms_helper,nvidia_drm
parport                69632  3 parport_pc,lp,ppdev
fuse                  167936  3
configfs               57344  1
ip_tables              32768  0
x_tables               53248  7 xt_conntrack,nft_compat,xt_tcpudp,xt_CHECKSUM,ipt_REJECT,ip_tables,xt_MASQUERADE
autofs4                53248  2
ext4                  921600  5
crc16                  16384  2 bluetooth,ext4
mbcache                16384  1 ext4
jbd2                  151552  1 ext4
raid10                 65536  0
raid456               180224  0
async_raid6_recov      24576  1 raid456
async_memcpy           20480  2 raid456,async_raid6_recov
async_pq               20480  2 raid456,async_raid6_recov
async_xor              20480  3 async_pq,raid456,async_raid6_recov
async_tx               20480  5 async_pq,async_memcpy,async_xor,raid456,async_raid6_recov
xor                    24576  1 async_xor
raid6_pq              122880  3 async_pq,raid456,async_raid6_recov
libcrc32c              16384  4 nf_conntrack,nf_nat,nf_tables,raid456
crc32c_generic         16384  0
raid1                  53248  0
raid0                  24576  0
multipath              20480  0
linear                 20480  0
md_mod                184320  6 raid1,raid10,raid0,linear,raid456,multipath
sd_mod                 61440  9
t10_pi                 16384  1 sd_mod
sr_mod                 28672  0
crc_t10dif             20480  1 t10_pi
crct10dif_generic      16384  0
cdrom                  73728  1 sr_mod
uas                    32768  0
usb_storage            81920  4 uas
hid_generic            16384  0
usbhid                 65536  0
hid                   147456  2 usbhid,hid_generic
xhci_pci               20480  0
ahci                   40960  5
xhci_hcd              307200  1 xhci_pci
libahci                45056  1 ahci
libata                290816  2 libahci,ahci
crct10dif_pclmul       16384  1
igb                   262144  0
crct10dif_common       16384  3 crct10dif_generic,crc_t10dif,crct10dif_pclmul
usbcore               323584  6 xhci_hcd,usbhid,usb_storage,btusb,xhci_pci,uas
crc32_pclmul           16384  0
scsi_mod              262144  7 vhba,sd_mod,usb_storage,uas,libata,sg,sr_mod
crc32c_intel           24576  11
i2c_algo_bit           16384  1 igb
i2c_piix4              28672  0
dca                    16384  1 igb
ptp                    32768  1 igb
pps_core               24576  1 ptp
usb_common             16384  2 xhci_hcd,usbcore
wmi                    36864  1 wmi_bmof
gpio_amdpt             20480  0
gpio_generic           16384  1 gpio_amdpt

**Comment by StephenCWills** [comment]
Successfully reproduced on Debian Bullseye. As far as I can tell, it only happens with the bow's sound effect, and changing attack speed doesn't seem to have any effect.

**Comment by Chance4us** [comment]
I am very impressed that it could be reproduced so quickly.
Is it possible to bisect and improve sdl_audiolib also?

**Comment by StephenCWills** [comment]
The commit you referenced upgrades to the following commit from the previous one. There's nothing to bisect.
https://github.com/realnc/SDL_audiolib/commit/ce8d83768ab9a798f16143cbebdb29a0a6377af3

However, this seems to be more than a simple regression. It could be a timing issue, an issue with the sound driver on Linux, or something else I haven't thought of. Plus, the maintainer has pushed a few commits to SDL_audiolib since the last time we updated. So it would be worth doing a more thorough investigation.

**Comment by Chance4us** [comment]
Thanks @StephenCWills
