### ISSUE TITLE
Character file corruption upon transferring to Vanilla Diablo  ?

### ISSUE THREAD

**Issue by Neratibt** [diasurgical/devilutionX#2889]
Operating system: Win 10 
DevilutionX version: 1.2.1 

I've been playing DevX lately but upon transferring my characters files back to the Vanilla Diablo client the following happens:

I can log in normally with my singleplayer characters but when I try to enter multiplayer B.net or TCP my screen freezes and turns black . I normally have to sign out in order to kill the Diablo.exe but sometimes it happens on it's own. I don't know what might have caused it I didn't play or change any settings and transferring character files worked with no problem before.

Here is a link to a video showing the problem: https://www.youtube.com/watch?v=FPDLjl26O2Y

Thanks for your support

**Comment by StephenCWills** [comment]
Can you access the multiplayer menus in vanilla Diablo if you remove the save files? If so, can you provide the save files?

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/133874472-157a5f08-fc9d-4fe1-846e-fceacb167b60.png)

**Comment by AJenbo** [comment]
0x00469E1B is right outside the function range, if you build a debug version of devilution (not x) do you get any additional insights?

**Comment by qndel** [comment]
No corruption, the character was a ... bard ...
