### ISSUE TITLE
Winged Demon stuttering animation

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#2917]
The issue is as follows. I've played as a rogue.
I noticed extremely stuttering winged demons in level 5.
I have tried to isolate the issue and to bisect and unfortunately I have not yet come to a positive result.

How can it be reproduced.
1. First of all, I recommend loading the following savegame and shooting far into the crowd.
[level5_crowd.zip](https://github.com/diasurgical/devilutionX/files/7206102/level5_crowd.zip)

Then you can see several winged demons suddenly awakening. Their awakening and sleep animations are just as jerky.
2. Following you can see a scene from level 5

https://user-images.githubusercontent.com/45902449/134243714-58cbb7d7-5bae-461f-a5f3-53a49d97c3a1.mp4

3. The second scene and savegame from level 7
[level7_2nd.zip](https://github.com/diasurgical/devilutionX/files/7206119/level7_2nd.zip)

https://user-images.githubusercontent.com/45902449/134244368-092841e7-d6b5-442a-920d-0d3eacd1110e.mp4

4. The third scene and savegame from level 7
[level7_3rd.zip](https://github.com/diasurgical/devilutionX/files/7206133/level7_3rd.zip)

https://user-images.githubusercontent.com/45902449/134244461-777012be-b89a-4eb7-92ff-5a1858f4d3f9.mp4

Unfortunately, it doesn't look quite as stuttery on the videos as it does in the game.
Then I bisected and maybe not enough and assumed that it is probably normal and that the animations are so bad because they may not have a sufficient number of single frames.

But after that I also played with the sorcerer and paid attention to it.
It gave a surprising result. I came across Blood Claws in the caves and they had liquid animations as they should be.
Savegame and an scene attached.
[sorcerer.zip](https://github.com/diasurgical/devilutionX/files/7206138/sorcerer.zip)

https://user-images.githubusercontent.com/45902449/134244569-e28e90da-3897-436e-887b-b5ab07a43b30.mp4

At least the wake-up animation on the Blood Claws seems to run faster.

Ultimately, there are the following categories of this type of monster.
The main category:
https://diablo.fandom.com/wiki/Category:Gargoyles
All subspecies:
https://diablo.fandom.com/wiki/Winged_Demon
https://diablo.fandom.com/wiki/Blood_Claw
https://diablo.fandom.com/wiki/Death_Wing
https://diablo.fandom.com/wiki/Viletouch
The unique pieces of this family:
https://diablo.fandom.com/wiki/Goldblight_of_the_Flame
https://diablo.fandom.com/wiki/Nightwing_the_Cold

Now I have the following guesses as a possible cause.
1. It is because the game was played with rogue, so it maybe depends on the player class
2. It is because it happens in the catacombs, so it is maybe level-dependent
3. It is because these are different gargoyle categories and are therefore animated differently
4. It is maybe an optical illusion

It would be helpful if someone could also try out and confirm the things described.
I hope that we can adjust the animations so that they run smoothly.

**Comment by julealgon** [comment]
@obligaron maybe the movement part might be related with the diagonal special?

I don't understand the normal standing animation being choppy though.

**Comment by StephenCWills** [comment]
Using the `spawn` command, I can verify that the discrepancy is based on monster type. Blood Claws and Death Wings don't look choppy whereas Gargoyles and Winged-Demons do. A bit of logging revealed that the choppy ones have an animation rate of 2 whereas the others have an animation rate of 1.

My understanding is, an animation rate of 2 means it's displaying each frame for two game ticks instead of one. In other words, it's playing a 20 Hz animation at 10 Hz. I suppose it's no wonder that it appears to stutter. I think we'd have to interpolate between frames to smooth this out.

**Comment by julealgon** [comment]
> A bit of logging revealed that the choppy ones have an animation rate of 2 whereas the others have an animation rate of 1.

WTF. This seems like a data initialization issue. Why would they have different animation delays to begin with?

> My understanding is, an animation rate of 2 means it's displaying each frame for two game ticks instead of one. In other words, it's playing a 20 Hz animation at 10 Hz. I suppose it's no wonder that it appears to stutter.

Yep. It would appear as the idle animation appears, but the movement in the idle animation is very subtle so it's a bit harder to see than a normal monster movement animation.

> I think we'd have to interpolate between frames to smooth this out.

I think this is an animation initialization issue. We should remove the animation delay instead.

I see you added the "vanilla" tag. Does this really repro in vanilla?

**Comment by StephenCWills** [comment]
> WTF. This seems like a data initialization issue. Why would they have different animation delays to begin with?

I assumed the intent was to make the weaker Gargoyles take a bit longer to make that transition. Perhaps it gives the player a bit longer to hit them or run away during those transitions.

> I see you added the "vanilla" tag. Does this really repro in vanilla?

Yes, I loaded the Rogue and Sorcerer saves into vanilla Hellfire and was able to see the same behavior. You can also clearly see the different animation rates in the Devilution codebase so the data wasn't inadvertently changed in DevilutionX or anything like that.

**Comment by AJenbo** [comment]
Things are working as intended, it's simply some of the monsters being slower then others.

**Comment by Chance4us** [comment]
But I think it's worth to adjust the animations of "Blood Claws" and "Death Wings", even though it's vanilla behavior. The animations of the "Death Wings" are so jerky that you think you are playing with a 33 MHz CPU.
More and better is simply possible here and at least we should consider an option to develop more potential here.
The game can do more.

**Comment by AJenbo** [comment]
That would be the same argument as setting default gamespeed to 3x by default to get 60 fps animations instead of 20fps.

It would make the monsters faster and that would change gameplay, with the only justication being that it looks smooth

**Comment by Chance4us** [comment]
We should consider, and I have already realized, that devilutionx is not diablo.
And to fix bugs, the gameplay has already changed.
Seen in this way, we shouldn't have changed a lot of things about the game that we have already changed.
As an example, @obligaron put a lot of time and effort into making the game smoother and more modern.
But here on this exception we're not taking the final step and the game looks old and very stuttery.
And then we should consider what are the advantages and what are the disadvantages.
The advantage would be that gameplay would be much smoother.
The disadvantage would be that the game would be slightly harder because these monsters would getting faster.
I see it as worth making the game look better.
And in #2831 we already accepted that the game gets little more difficult.
That is just one of the examples I could give.  And nobody cares that the game got a bit tough.
Then why do we go halfway, I think it is sometimes important to weigh the advantages and disadvantages.
In this situation it is the same. If it should be nice, let's make it nice, after all, we don't want to make the whole game 3x faster, but only this type of monster.

**Comment by Chance4us** [comment]
By the way, it would certainly be possible to provide an option for this in diablo.ini.

**Comment by StephenCWills** [comment]
I agree that it isn't worth considering changes to gameplay for this. However, we could potentially work around this by redistributing or interpolating between the animation frames so even then it's not entirely a lost cause. However, I see it as a fair amount of effort for a relatively small issue.

And since it doesn't cost anything to share my opinion, I think the `wontfix` label is more accurate than the `invalid` label.

**Comment by julealgon** [comment]
I tend to agree with "wontfix" for now, but we could decouple the animation frame increments from the monster speed here and keep gameplay the same while making the animation smoother.

I wanted to do something similar for walking, for example, making you "take longer to travel a diagonal" but "walk at the same speed while doing it".

**Comment by StephenCWills** [comment]
That makes sense for walking since it's a looping animation, but this is a transition from one state to another so how would that work?

**Comment by julealgon** [comment]
> That makes sense for walking since it's a looping animation, but this is a transition from one state to another so how would that work?

The issue is not only in transitions. Animation delay 1 causes every animation frame to be displayed twice, no matter if you are changing from one animation to another.

It would still work here since it would apply to their idle animations, to when they are moving (in the same direction) and it would still be noticeable even for single-tile movements.

**Comment by StephenCWills** [comment]
> The issue is not only in transitions. Animation delay 1 causes every animation frame to be displayed twice, no matter if you are changing from one animation to another.
> 
> It would still work here since it would apply to their idle animations, to when they are moving (in the same direction) and it would still be noticeable even for single-tile movements.

Okay, but I'm not talking about transitions between animations. For gargoyle-type monsters, the animation rate of 2 only applies to the Gargoyle and Winged-Demon "special" animations. This is the animation that plays when the monster is transitioning between the "healing" and "active" states. All other gargoyle-type animations have a rate of 1, which means there is no delay between frames.

So, given that this animation moves between two distinct monster states and therefore cannot loop, how are you going to play that 14-frame animation at 20 Hz and still get that transition to last 28 frames?

**Comment by julealgon** [comment]
> Okay, but I'm not talking about transitions between animations. For gargoyle-type monsters, the animation rate of 2 only applies to the Gargoyle and Winged-Demon "special" animations. This is the animation that plays when the monster is transitioning between the "healing" and "active" states. All other gargoyle-type animations have a rate of 1, which means there is no delay between frames.

Ohhh ok, my bad. For some reason I thought this affected all animations and not only the to/from stone ones. Disregard what I said then.

> So, given that this animation moves between two distinct monster states and therefore cannot loop, how are you going to play that 14-frame animation at 20 Hz and still get that transition to last 28 frames?

You're right, there is not much that can be done besides some artificial interpolation (preferably with subpixel precision, which we also don't have support for).

**Comment by ikonomov** [comment]
Just to add our last discussion on the issue, a possible solution can be playing the 14 frame animation and then add before when they are landing, or after when they are getting off ground their idle animation, which also happens to be 14 frames.  This will accomplish both goals, make the animations look fluid and allow extra time to attack them while they are "transitioning".
