### ISSUE TITLE
Incorrect automap arrow alignment

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#2929]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Latest master

**Describe**
The arrows representing players in the automap are drawn with incorrect alignment in most positions. The alignment also changes compared to a moving hero vs a stationary one.

**To Reproduce**
1. Open the automap
2. Stand close to a door in the automap (which draws a perfect tile square for comparison purposes)
3. Horizontal walk
4. Notice how the arrow "jumps" when you stop and start walking
5. Stay in front of the door and take note at how the arrow is drawn: instead of appearing in the middle of the tile (which would make it consistently symetrical), it is drawn always starting from the top left corner of the automap tile, meaning the arrow can invade the tiles surrounding it depending on the direction you face

**Expected behavior**
The arrow shoud be drawn in a consistent manner so that it transitions smoothly while moving, as well as not invades adjacent tiles in the automap

My suggestion is as follows:

| Direction | Current | Proposal |
| :-: | --- | --- |
| Southeast | ![image](https://user-images.githubusercontent.com/461579/134445845-13898e73-9841-41b8-abf4-36ed3d48558e.png) | ![image](https://user-images.githubusercontent.com/461579/134445286-114ccea7-f720-45cb-860d-bfce830cb214.png) |
| Northwest | ![image](https://user-images.githubusercontent.com/461579/134445889-cc28de2f-d55d-459d-aeae-0ecb9cf3faeb.png) | ![image](https://user-images.githubusercontent.com/461579/134445307-ee11b591-7314-4846-93cc-19864e07fdb2.png) |
| Northeast | ![image](https://user-images.githubusercontent.com/461579/134445987-19f52241-5144-4b0d-92d3-0176252c2917.png) | ![image](https://user-images.githubusercontent.com/461579/134445323-02e785f6-23bb-4f69-8f5c-db8b4c8e15f3.png) | 
| Southwest | ![image](https://user-images.githubusercontent.com/461579/134446043-0a40ee0c-d229-4f1a-808c-4ff48ccfe0d5.png) | ![image](https://user-images.githubusercontent.com/461579/134445351-5658be17-652b-4690-88b8-560430d950b4.png) | 
| South | ![image](https://user-images.githubusercontent.com/461579/134445162-53e82a77-73a3-4264-a6f3-5f9fd01c1cae.png) | ![image](https://user-images.githubusercontent.com/461579/134445162-53e82a77-73a3-4264-a6f3-5f9fd01c1cae.png) |
| North | ![image](https://user-images.githubusercontent.com/461579/134446308-60fce2bc-ae4a-4d7b-a179-460149bd3b70.png) | ![image](https://user-images.githubusercontent.com/461579/134445188-62d3df7d-2080-4d68-901f-7d0f9f41d124.png) |
| East | ![image](https://user-images.githubusercontent.com/461579/134446252-0c96d3bb-a41f-4ad3-b3e9-58f47f926184.png) | ![image](https://user-images.githubusercontent.com/461579/134445229-37afb87d-1473-4229-b5e5-7def336aa8a3.png) |
| West | ![image](https://user-images.githubusercontent.com/461579/134446143-919bed1b-d5e4-4234-a6d0-f0353229578e.png) | ![image](https://user-images.githubusercontent.com/461579/134445264-d95dde7e-eca8-4a5f-abd1-391ea0bea192.png) |

**Screenshots**

Horizontal walking (jumping arrow):
![AutoMapHorizontalWalkArrow](https://user-images.githubusercontent.com/461579/134444778-dbf3da5e-65a4-4245-a9e9-01d33aeafd01.gif)

Alignment issue (arrow draw from tile corner regardless of direction):
![AutoMapArrowAlignment](https://user-images.githubusercontent.com/461579/134444939-ac7c4848-fd33-4086-a933-c89b4c17ee39.gif)

Arrow is draw starting from the corner:
![image](https://user-images.githubusercontent.com/461579/134445599-c711aefb-bb5c-484e-a4e5-7a14742a3208.png)

**Comment by AJenbo** [comment]
Looks like this should be fixed by https://github.com/diasurgical/devilutionX/pull/3002

**Comment by qndel** [comment]
No.

**Comment by qndel** [comment]
Fixed by https://github.com/diasurgical/devilutionX/pull/3005
