### ISSUE TITLE
How to use translations?

### ISSUE THREAD

**Issue by Defcon0** [diasurgical/devilutionX#2945]
Hello,

might be obvious, but how do I use the translation *.po files provided in the Translations folder in this repo? I tried putting the de.po in my devilutionx folder and setting 

```
[Language] 
Code=de
```

in my diablo.ini

But without success.

What am I doing wrong?

Thanks!

Bye Defcon0

**Comment by AJenbo** [comment]
See the instruction for testing translations here: https://github.com/diasurgical/devilutionX/wiki/Translation-Guide#step-3-testing

Would you be interested in helping with finishing the German translation?
