### ISSUE TITLE
Target tracking persist even when monsters are hidden

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2962]
**Describe**
When a monster either teleports (advocate), or hides (illusion weaver) a sustained click will keep tracking them to there new location. This shouldn't be the case as the player would not be able to track there position under normal circumstances.

**To Reproduce**
1. map 5
2. Use inferno against an Advocate, and keep holding the attack
3. Wait till it teleports
4. Notice that you are still attacking it when it reappears

**Comment by julealgon** [comment]
Should tracking remain if the user has the infravision effect?

**Comment by obligaron** [comment]
> Should tracking remain if the user has the infravision effect?

Normal selection logic doesn't allow to select a monster that is only visible cause of infravision. So we also shouldn't track?
