### ISSUE TITLE
Make spell highlighting translatable

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#2972]
When hovering spells you get to see if it's a Spell, Skill, Staff, or Scroll. This is correctly part of frame that gets overlayed (`DrawSpellCel()`) on top, which means it's not currently translatable.
Previously the same was the case for the 4 hot key indications F5, F6, F7, F8, but this as been replaced by `PrintSBookHotkey()` so that it is now done dynamically. The same change should be done to the type label.

The relevant function is `DrawSpellList()`.

![image](https://user-images.githubusercontent.com/204594/135065393-9273acd7-77ec-4a49-9316-5c5ea6fe82ae.png)

**Comment by yuripourre** [comment]
@AJenbo, nice!

The challenge now is to make those translations fit into 5 letters.

**Comment by uwodb** [comment]
I can edit ctrlpan/spelicon.cel file using hex editor.
It is difficult for me to make its background transparent, so I painted with black-and-white.
![Image1](https://user-images.githubusercontent.com/56031577/135129706-ee063c7f-bef5-4ecb-ab6b-0ed60ec706a2.png)
![Image2](https://user-images.githubusercontent.com/56031577/135129710-c5fa6d01-4db5-494b-a1d4-7465920fde36.png)

**Comment by AJenbo** [comment]
Thanks, but the idea here is to not use the cel and instead use a font, that way we can render any text based on the translation text from the .po files. Other wise you would need to edit it for every language that is added.

**Comment by yuripourre** [comment]
I am working on it!
