### ISSUE TITLE
Make debug messages translatable

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#2974]
Debug console has messages that are displayed after applying the command, for example "A god descended" after `god` cheat
![screen04](https://user-images.githubusercontent.com/4958520/135087276-cdd2bb68-96cc-4598-bb53-7b71ab1111c5.png)
These need to be exposed for translation

**Comment by AJenbo** [comment]
On the other hand it is extra work for the translator that will never be seen by players as debug messages are not in release builds.

**Comment by tsunamistate** [comment]
IMO, debug cheats should be brought into release builds activated via INI or button combination, since compiling your own build is a pretty high barrier for cheats

This is more in "nice to have" category, so can be excluded from 1.3.0

**Comment by AJenbo** [comment]
We don't add cheats to the game.
