### ISSUE TITLE
Blank Screen in Chrome 

### ISSUE THREAD

**Issue by shayansea** [diasurgical/devilutionX#2981]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
MAC OS/DevilutionX 

**Describe**
The game played great two days ago and now it opens to a blank screen but WITH audio
I tried it on safari and it's working, but alas the saved data is not there.

Have cleared cookies, checked chrome settings for the git.io website

HAVE no clue what to do?

**Comment by AJenbo** [comment]
Considering that DevilutionX isn't ported to browsers I think you likely talking about [diabloweb](https://github.com/d07RiV/diabloweb) instead.

I would instead recommend that you use the macOS native port of DevilutionX: https://github.com/diasurgical/devilutionX/releases/download/1.2.1/devilutionx-mac-x86_64.dmg

Regarding your save game, it's stored in the browsers localStorage, so clearing cookies/history may well result in deleting it.
