### ISSUE TITLE
[Locale] CJK language line break feature.

### ISSUE THREAD

**Issue by tytannial** [diasurgical/devilutionX#2990]
With CJK locale, If we don't add a line break manually, Some of the line are missing.
![20210930142633](https://user-images.githubusercontent.com/11215623/135407012-50449835-f662-45db-8259-545b8028baf8.png)

In CJK language, new line doesn't require space.

**Comment by AJenbo** [comment]
@tytannial the screen shot is a bit misleading as it includes the PO encoding and we aren't given the actual text so we can't tell what code points are there. Can you please reference the relevant line, or preferably include it here.

**Comment by tytannial** [comment]
#. TRANSLATORS: Neutral Text spoken by Ogden
#: Source/textdat.cpp:523

![20210930155545](https://user-images.githubusercontent.com/11215623/135411284-6b313d5b-876c-40be-8514-2664ae69a319.png)

**Comment by AJenbo** [comment]
Please provide the translated Chinese text, as text and not an image :)

**Comment by tytannial** [comment]
> Please provide the translated Chinese text, as text and not an image :)

Sorry. 😳

DevilutionX/Translations/zh_CN.po, line 9509.

#. TRANSLATORS: Neutral Text spoken by Ogden
#: Source/textdat.cpp:523
msgid ""
"Thank goodness you've returned!\n"
"Much has changed since you lived here, my friend. All was peaceful until the "
"dark riders came and destroyed our village. Many were cut down where they "
"stood, and those who took up arms were slain or dragged away to become "
"slaves - or worse. The church at the edge of town has been desecrated and is "
"being used for dark rituals. The screams that echo in the night are inhuman, "
"but some of our townsfolk may yet survive. Follow the path that lies between "
"my tavern and the blacksmith shop to find the church and save who you can. \n"
" \n"
"Perhaps I can tell you more if we speak again. Good luck."
msgstr ""
"谢天谢地你回来了\n"
"自从你住在这里，我的朋友，一切都变了。一切都很平静，直到黑暗骑士来摧毁我们的"
"村庄。许多人在原地被砍倒，拿起武器的人被杀或被拖走成为奴隶，甚至更糟。城市边"
"缘的教堂被亵渎，被用来举行黑暗的仪式。夜晚回响的尖叫声是不人道的，但我们的一"
"些市民可能还活着。沿着我的小酒馆和铁匠铺之间的小路去寻找教堂，拯救你能拯救的"
"人。\n"
" \n"
"如果我们再谈的话，也许我可以告诉你更多。祝你好运"

**Comment by AJenbo** [comment]
Ok thanks, here is the text with out PO encoding :)

```
谢天谢地你回来了
自从你住在这里，我的朋友，一切都变了。一切都很平静，直到黑暗骑士来摧毁我们的村庄。许多人在原地被砍倒，拿起武器的人被杀或被拖走成为奴隶，甚至更糟。城市边缘的教堂被亵渎，被用来举行黑暗的仪式。夜晚回响的尖叫声是不人道的，但我们的一些市民可能还活着。沿着我的小酒馆和铁匠铺之间的小路去寻找教堂，拯救你能拯救的人。
 
如果我们再谈的话，也许我可以告诉你更多。祝你好运
```
As you can see most of the mentioned lines are actually a single line, it might just be co incidence that it broke the text at roughly the same point in game.

I'll try and see if i can figure out why it left out part of the line.

**Comment by tytannial** [comment]
> Ok thanks, here is the text with out PO encoding :)
> 
> ```
> 谢天谢地你回来了
> 自从你住在这里，我的朋友，一切都变了。一切都很平静，直到黑暗骑士来摧毁我们的村庄。许多人在原地被砍倒，拿起武器的人被杀或被拖走成为奴隶，甚至更糟。城市边缘的教堂被亵渎，被用来举行黑暗的仪式。夜晚回响的尖叫声是不人道的，但我们的一些市民可能还活着。沿着我的小酒馆和铁匠铺之间的小路去寻找教堂，拯救你能拯救的人。
>  
> 如果我们再谈的话，也许我可以告诉你更多。祝你好运
> ```
> 
> As you can see most of the mentioned lines are actually a single line, it might just be co incidence that it broke the text at roughly the same point in game.
> 
> I'll try and see if i can figure out why it left out part of the line.

The most strange thing is why there be 4 lines. If problem is the line break, should be 3 lines.🤣

**Comment by AJenbo** [comment]
Just merged @glebm 's improvnments to the WordWrap function (https://github.com/diasurgical/devilutionX/pull/2993), it should now be able to handle basic CJ content, could you please test again and see if the situation is resolved?

**Comment by AJenbo** [comment]
Looks like the full text is now rendered correctly:

![image](https://user-images.githubusercontent.com/204594/135523709-8c147e6f-5510-4f67-aa7a-c6bd6f990cb7.png)

**Comment by glebm** [comment]
I missed the fact that these were fullwidth commas due to this rendering, which is why the text above is only wrapped on periods.

**Comment by glebm** [comment]
> Is this something that is important to solve, and are you able to help with it :)

It is important. Also the vertical alignment of `。` is very off.

**Comment by AJenbo** [comment]
> but that could be due to this temporary font.

It would be helpful with an issue listing either the range or individual U+XXXX cods or a range, where it should be a specific width and not trimmed to the visual portion.
