### ISSUE TITLE
Automap arrow jumps during walking horizontally

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3000]
Caused by e62aaa562f12e50db62ee288c6c15c5d3aa9febf
![jumpingarrow](https://user-images.githubusercontent.com/14297035/135577071-13669776-f7df-4f77-80c0-888658da7a42.gif)

**Comment by AJenbo** [comment]
Isn't this a known vanilla issue?

**Comment by qndel** [comment]
> Isn't this a known vanilla issue?

no? it works fine in vanilla, that's entirely on us

**Comment by julealgon** [comment]
Mentioned here as well:
- #2929
