### ISSUE TITLE
Walking towards / Teleporting into a room in crashes the game

### ISSUE THREAD

**Issue by Barfie** [diasurgical/devilutionX#3007]
**Important information**
Win10 / DevilutionX version v1.2.1  / downloaded the release

**Describe**
Walking towards a room causes the game to crash to desktop. Teleporting into the "Crash site" causes a game crash without the screen loading anything. After a lot of exploration, some routes allow one to inch closer, but all result in a crash.

**To Reproduce**
1. Load the attached game 
[crashy.zip](https://github.com/diasurgical/devilutionX/files/7270621/crashy.zip)

Your start position looks like this 

![start position](https://user-images.githubusercontent.com/91764587/135696953-25f4533a-030b-4c90-b98c-0f5b81f40ee8.png)

the red circle actually has a dual purpose. On the map, anywhere in that room will crash the game. Also, if you didn't have the map on, walking anywhere within it causes a crash. Southeasterly movement results in a game crash.

I've played through the game with full exploration 5 times now, and haven't encountered this anywhere else.

Thank you and I love you.

**Comment by qndel** [comment]
Fixed by https://github.com/diasurgical/devilutionX/pull/1748, will work fine in 1.3.0
