### ISSUE TITLE
Support original targets

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#301]
Now that we have SDL1 and BigEndian support mostly in place it would be fun to start supporting some of the original target platforms

For Mac OS 9 there is:
https://github.com/autc04/Retro68 (GCC 9 + CMake toolchain)
https://nondisplayable.ca/2017/12/20/sdl-on-classic-mac.htm (SDL)l

For Windows 95 I'm not exactly sure what would be required, maybe it enough to simply compile with SDL1 enabled?

Targeting the PS1 might be a struggle, the team that ported the game first of all cut a lot of animations and rescaled the game to 60% resolution, and even then they had to split the exe up to fit it all in memory. Never the less here is the needed tools if any one feel inclined to try :)
https://github.com/ggdrt/psxsdk-20190410
https://github.com/root670/docker-psxsdk
(this doesn't include SDL, I did see some reference to there migth being a version for PSX, but didn't fine it on first try)

Lastly if some one want to go even deeper DOS is also an option since it was the original intended platform for the developers (probably while most where still written in ASM).
There is an at least partial DOS port of SDL https://github.com/jayschwa/SDL/tree/dos-vga
And some context: https://discourse.libsdl.org/t/porting-sdl-to-dos/27361/6

**Comment by kraileth** [comment]
The only framework that comes to my mind when I think "DOS" is Allegro. But I don't think it's remotely compatible with SDL. Are there others as well?

Heck, if Diablo was available for DOS, I'd surely try it out on FreeDOS (which I haven't installed in years...), just because it's possible! :smiling_imp:

**Comment by AJenbo** [comment]
The game can now run from the original CD https://www.youtube.com/watch?v=fk9GwVIhOGc

**Comment by julealgon** [comment]
Can you add "platforms" to the title as well @AJenbo ? Had to open this one to see what it was about.

**Comment by AJenbo** [comment]
Found a DOS port of SDL :P

**Comment by glebm** [comment]
There is a good post on cross-compiling to Windows 98 here: https://fanael.github.io/stockfish-on-windows-98.html

**Comment by AJenbo** [comment]
It now works on Windows 95+, with the caveatthat you need a Penitum Pro or better (Penitum II) to run it.
