### ISSUE TITLE
Ctlr + Left Clicking Empty Belt Slots Generates Fake Items

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#3024]
**Important information**
Windows 10 / master / Compiled 403f507d myself

**Describe**
If you ctrl + left click an empty slot in the belt, the game will drop a fake item that looks like the item that was previously in that slot. You cannot pick up the item, but clicking it multiple times will eventually cause the fake item to disappear. Sometimes, this causes you to need to click the real item that dropped from that slot multiple times to pick it up.

**To Reproduce**
1. Create a new character.
2. Use ctrl + left click to drop one of your starting healing potions.
3. ctrl + left click that same belt slot to drop as many "fake" healing potions as your heart desires.

**Expected behavior**
ctrl + left clicking an empty belt slot should do nothing.

**Comment by NiteKat** [comment]
Note: This also impacts the inventory. If you ctrl + left click empty inventory slots, it does the same thing as ctrl + left clicking belt slots. Should that be a separate issue?

**Comment by yuripourre** [comment]
Yep, I can confirm the issue. It might be related to #2978

**Comment by yuripourre** [comment]
@NiteKat Thank you for flagging, I just submitted a fix.
