### ISSUE TITLE
Inline UI errors

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#303]
here is an example from trying to create more then the allowed 10 heros:
![image](https://user-images.githubusercontent.com/204594/66021134-d5fab100-e4e9-11e9-8665-0215a7a17ca1.png)
 note that the name is blanked (also after clicking ok) and the input box stops showing

![image](https://user-images.githubusercontent.com/204594/66021151-e579fa00-e4e9-11e9-85ec-434d773350d6.png)

This should also be used for showing a failure to connect to a server, instead of the current SDL popup.

**Comment by glebm** [comment]
How does it work for the diabdat.mpq not found dialog? Where do the graphics come from?

**Comment by glebm** [comment]
This red box is `ui_art\srpopup.pcx` (also lrpopup.pcx is a bigger box) and the OK button is `ui_art\but_sml.pcx`.

**Comment by AJenbo** [comment]
Regarding the graphics for the "Please insert the Diablo CD" error message. The diabloui.dll contains 3 embedded data files that are used in this dialog:
IDR_POPUPART
IDR_BTNART
IDR_ARTPAL

These are simply copies of ui_art\srpopup.pcx and ui_art\but_sml.pcx (cropped to a version only containing the firs of the 3 buttons) in a binary format (probably uncompressed) with there palet in a separate file.

**Comment by AJenbo** [comment]
I have updated the issue with non streached versions of the dialogs to make it easier to implement this pixel perfect :)

**Comment by glebm** [comment]
I've just implemented the UI for these dialogs, but they still need to be "hooked up" in most places, not sure if this should be closed.

**Comment by AJenbo** [comment]
Some errors should be handled by the error page https://github.com/diasurgical/devilutionX/issues/60
I think we should have a separate issue that lists what error messages should be displayed by which of the 3 methods.
