### ISSUE TITLE
Runes of Lightning Only Hit Monsters Once

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#3041]
**Important information**
Windows 10 / 403f507 / Compiled myself

**Describe**
Runes of Lightning only hit once.

**To Reproduce**
1. Set a Rune of Lightning on a tile in the dungeon.
2. Have a monster walk on the tile with the rune to activate it.
3. Hear the monster get hit once.
4. Get the monster to stand in the tile. You will not hear them get hit again by the lightball.

**Expected behavior**
The lightball, like lightning wall, should probably hit multiple times.

**Additional context**
This was probably broken with the recent missile changes that made most missiles only do one check per tile. Exceptions were made for the wall spells, but lightning ball missiles should probably be included in the exception, since the missile stays in place for a set time instead of disappearing after hitting once.

**Comment by NiteKat** [comment]
Discussed this with @StephenCWills , and Nova uses lightball, so lightball can't be made to do multiple checks. Maybe a rune of lightning should spawn a single tile lightning wall instead then? Might also fix https://github.com/diasurgical/devilutionX/issues/3040 if it did.

**Comment by NiteKat** [comment]
> * Monsters avoid stepping in lightwalls

Would make sense for monsters to avoid a rune of lightning after it has triggered.

**Comment by qndel** [comment]
this bug doesn't happen in original hellfire = no hellfire tag

**Comment by qndel** [comment]
Bisected to 836bb92e8ed6b602b980ee2393dcf93d66524f6f

**Comment by AJenbo** [comment]
I was more seeing the bug as being them having set it to lightingball instead of lighting wall, which is a bug in the original game...

**Comment by AJenbo** [comment]
bug + bug = feature
