### ISSUE TITLE
Failed to open file: fonts\22-00.bin File not found

### ISSUE THREAD

**Issue by efedo** [diasurgical/devilutionX#3043]
**Important information**
Windows 10 / c39c6ce / Compiled myself (MSVC 16.11.3)

**Describe**
Fatal error appears immediately after Hellfire splash screen.

**Steps To Reproduce**
1. Clone fresh repository, compile and run.
![image](https://user-images.githubusercontent.com/70902412/136189598-df849c9e-e2d8-4683-aef2-4159c13f64e8.png)

**Additional context**
Regression post-66e1e38. Appears to occur because devilutionX.mpq is not built by default but is now required for font handling.

**Comment by StephenCWills** [comment]
You'll need to install smpq to build devilutionx.mpq. [building.md](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md) has links and instructions.

**Comment by efedo** [comment]
Now that devilutionx.mpq is required smpq should be installed by default. It's a bad look to not have the CMake configuration work out of the box.

**Comment by StephenCWills** [comment]
It works fine if you follow the instructions. It's a prerequisite like vcpkg. I don't understand the distinction.

Well, if you can get it to work, feel free to submit a PR.

**Comment by efedo** [comment]
It's nothing at all like vcpkg. Vcpkg is widely used and installed by default in most dev environments. New users trying to compile devilutionx for the first time are going to either already have vcpkg or be able to set it up without difficulty based on any number of installation guides. 

Smpq is by comparison an obscure library. As far as I can tell, it doesn't have any binaries or packages available for Windows. And building.md has no instructions for how to compile or install it on Windows or most other platforms. This is going to deter most newcomers on non-*NIX platforms from running devilutionx.

But by all means, continue with your rude attitude.

**Comment by StephenCWills** [comment]
I explained to you what you needed to build smpq, and explained that it's already in the build instructions to justify closing the issue. I also explained that it is a prerequisite, like vcpkg, and that I didn't understand what you were getting at, but suggested that you could submit a PR since it seemed you felt strongly about it. Considering this issue exists in the first place because you didn't follow the documented build instructions, I feel I've been more than gracious. I ask that you tone it down.

**Comment by efedo** [comment]
The build instructions mention smpq is an _optional_ dependency on a limited subset of platforms, but it appears to now be a _required_ dependency on all platforms. Smpq, and packaging of devilutionX.mpq, is likewise treated as an optional dependency in the CMake configuration, even though it is now required.

**Comment by AJenbo** [comment]
It's not a requirement, you can get devilutionX.mpq by other means.

**Comment by AJenbo** [comment]
It's a runtime requirement yes, but not a build time requirement. Hens it's not required for the build process to succeed.

**Comment by StephenCWills** [comment]
FYI, it should also work without devilutionx.mpq if you just place the resources in your data path alongside diabdat.mpq.

**Comment by AJenbo** [comment]
> Having build instructions and a default CMake configuration that no longer produce a functional application without manual (and undocumented) copying of dependencies

You will always have to provide the original game data your self.

> It just seems rather like a shame, since this is a considerable regression in the user-friendliness of the build process compared to just a few weeks back.

It's a trade of like many things, having the MPQ be generated makes things a lot easier for the artists, making them less dependent on the programmers, giving them more time to write meaningful code.

> Personally I would strongly suggest avoiding the issue by switching to a newer package format for original content that does not require an obscure binary dependency. MPQ was great for its day, but there are better options going forward.

Removing MPQ support would require users to have to convert the original archive before being able to run the game.
We do have plans to *add* support for zip files, but have not had time to do so yet. If this is something you would be interested in working on it would be greatly appreciated.

**Comment by StephenCWills** [comment]
> Having build instructions and a default CMake configuration that no longer produce a functional application without manual (and undocumented) copying of dependencies puts up a considerable wall for newcomers who are compiling for the first time and may be interested in joining your community.

Perhaps the simplest solution to this would be updating the documentation, which would also be a noble pursuit if you'd like to work on that.

**Comment by NiteKat** [comment]
> Removing MPQ support would require users to have to convert the original archive before being able to run the game.

Wouldn't it be possible to still support MPQ for the original archive, while supporting some other format for new content? I don't feel like @efedo was suggesting dropping MPQ support altogether, just for new content that is added such as the fonts.

**Comment by efedo** [comment]
Yes, that is correct @NiteKat. If everyone is okay with that, I'll dig around and see how much effort would be required to add zip support.

Alternatively, we can at least repost the [abandoned smpq source](https://launchpad.net/smpq) (GPL) on github, so that smpq can be automatically installed in the CMake config. I'm assuming that people don't want to bundle smpq as a third-party lib due to license issues?

**Comment by AJenbo** [comment]
@efedo I would expect people who want to get the application up and running to also, preferably first, take a look at the [installation instructions](https://github.com/diasurgical/devilutionX/blob/1f61e8c57b153a0127380c796684aa017342463f/docs/installing.md) where devilutionx.mpq is clearly listed as required for running the application, and ways to obtain it are mentioned.

Also please keep in mind that the project and code is actively changing and large changes may require a few iterations before everything is smoothed out.

> I know for a fact that if a user receives that error, they did not follow the build instructions fully. They are missing devilutionx.mpq, and the instructions explain how to build devilutionx.mpq. I don't know why you continue to insist that the build instructions don't include this step because you have _repeatedly_ been told that they do. I'm not sure what you stand to gain by pushing so hard on this narrative, but it's verifiably false by anyone with eyes and an internet connection so I wish you'd stop.

I think at this point @efedo is acknowledges that it's there, but is saying that it being optional can lead the mentioned error, if you also skipped over the alternatives.

 I think it would be good if we all reset our views before continuing this debate.

Maybe it would be enough to stipulate that if they skip it, they will need to download devilutionx.mpq instead.
Copying the raw assets automatically in case smpq isn't found unfortunately doesn't appear to be an option as we can't reliably determine the data path at build time.

**Comment by AJenbo** [comment]
@julealgon the issue is locked, please do not post in it, use the chat instead.
