### ISSUE TITLE
Debug Build Crashing with Assert when Release Build Picks Up Ear

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/DevilutionX#3052]
**Important information**
Windows 10 / 071206a9 / Compiled myself

**Describe**
Trying to pick up one of the two ears on this character will trigger an assert for other characters in game that are on debug builds.

**To Reproduce**
1. Host a multiplayer game with any other character while using a debug build of DevilutionX
2. Join the multiplayer game with the character in the attached save file with a release build of DevilutionX
3. Drop both Ears that are in the inventory.
4. Close inventory.
5. Click on one of the ears on the ground with the character that dropped the ears. The debug build client will crash, ear will not pick up at first.

**Expected behavior**
Character should pick up the ears without issue, and debug client should not assert.

**Additional context**
[multi_0.zip](https://github.com/diasurgical/devilutionX/files/7298279/multi_0.zip)
You can pick the ears up if you click on them enough times after the debug build client crashes.

**Comment by AJenbo** [comment]
![Screenshot from 2021-10-07 03-08-09](https://user-images.githubusercontent.com/204594/136310999-32d46ab3-28ec-43e9-9332-2e3256e96350.png)
```

/home/ajenbo/code/diablo/devilutionX/Source/storm/storm_net.cpp:80:55: runtime error: member access within null pointer of type 'struct abstract_net'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==38418==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x555dfb690ac2 bp 0x7ffc13e78430 sp 0x7ffc13e78390 T0)
==38418==The signal is caused by a READ memory access.
==38418==Hint: address points to the zero page.
    #0 0x555dfb690ac2 in SNetUnregisterEventHandler /home/ajenbo/code/diablo/devilutionX/Source/storm/storm_net.cpp:80
    #1 0x555dfb0dea34 in EventHandler /home/ajenbo/code/diablo/devilutionX/Source/multi.cpp:414
    #2 0x555dfb0e4113 in devilution::NetClose() /home/ajenbo/code/diablo/devilutionX/Source/multi.cpp:678
    #3 0x555dfae3e269 in devilution::init_cleanup() /home/ajenbo/code/diablo/devilutionX/Source/init.cpp:139
    #4 0x555dfaceb669 in DiabloDeinit /home/ajenbo/code/diablo/devilutionX/Source/diablo.cpp:981
    #5 0x555dfacf6c19 in devilution::diablo_quit(int) /home/ajenbo/code/diablo/devilutionX/Source/diablo.cpp:1558
    #6 0x555dfac245bd in devilution::app_fatal(char const*, ...) /home/ajenbo/code/diablo/devilutionX/Source/appfat.cpp:73
    #7 0x555dfac24829 in devilution::assert_fail(int, char const*, char const*) /home/ajenbo/code/diablo/devilutionX/Source/appfat.cpp:91
    #8 0x555dfae68ebc in devilution::SyncGetItem(devilution::Point, int, unsigned short, int) /home/ajenbo/code/diablo/devilutionX/Source/inv.cpp:1664
    #9 0x555dfb09f488 in OnRequestAutoGetItem /home/ajenbo/code/diablo/devilutionX/Source/msg.cpp:757
    #10 0x555dfb0d5b72 in devilution::ParseCmd(int, devilution::TCmd const*) /home/ajenbo/code/diablo/devilutionX/Source/msg.cpp:2666
    #11 0x555dfb0dcae7 in HandleAllPackets /home/ajenbo/code/diablo/devilutionX/Source/multi.cpp:298
    #12 0x555dfb0e3434 in devilution::multi_process_network_packets() /home/ajenbo/code/diablo/devilutionX/Source/multi.cpp:628
    #13 0x555dface7005 in RunGameLoop /home/ajenbo/code/diablo/devilutionX/Source/diablo.cpp:745
    #14 0x555dfacf6ace in devilution::StartGame(bool, bool) /home/ajenbo/code/diablo/devilutionX/Source/diablo.cpp:1541
    #15 0x555dfaf59290 in InitMenu /home/ajenbo/code/diablo/devilutionX/Source/menu.cpp:51
    #16 0x555dfaf59346 in InitMultiPlayerMenu /home/ajenbo/code/diablo/devilutionX/Source/menu.cpp:67
    #17 0x555dfaf59a57 in devilution::mainmenu_loop() /home/ajenbo/code/diablo/devilutionX/Source/menu.cpp:146
    #18 0x555dfacf6c6f in devilution::DiabloMain(int, char**) /home/ajenbo/code/diablo/devilutionX/Source/diablo.cpp:1573
    #19 0x555dfac2412d in main /home/ajenbo/code/diablo/devilutionX/Source/main.cpp:38
    #20 0x7f6a2be0a564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
    #21 0x555dfac2403d in _start (/home/ajenbo/code/diablo/devilutionX/build/devilutionx+0x143103d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/ajenbo/code/diablo/devilutionX/Source/storm/storm_net.cpp:80 in SNetUnregisterEventHandler
==38418==ABORTING

```

**Comment by ephphatha** [comment]
The debug assert is checking that after picking up an item no other item exists on the ground in the current level with the same identifying information, this doesn't handle cases where someone has harvested a few ears from a player and drops more than one on a single level 😄 .

I think we can remove the assert, I guess it was meant to check that no duplicate items exist? But that would be better handled when dropping an item instead of on pickup.

I don't think multiple ears existing is an issue, the logic for creating an ear prevents another ear dropping if one is already on the ground somewhere in the current level however multiples can be harvested by simply picking up the dropped ear or killing the player on different levels.
