### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by stefanoconiglio** [diasurgical/DevilutionX#3062]
I get this error upon running the binary (I'm using the shareware version of the game on ubuntu; manual installation):

en.gmo: No such file or directory
INFO: Removed file: /home/coniglio/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo
ERROR: Error
Failed to open file:
fonts\24-00.bin

File not found
ERROR: Error
Failed to open file:
fonts\22-00.bin

File not found

**Comment by AJenbo** [comment]
@stefanoconiglio where did you build devilutionx your self? In that case make sure you have smpq installed so that it can generate devilutionx.mpq file.

**Comment by ThomasChr** [comment]
@stefanoconiglio
You can download the latest build from github. It's a little bit hidden but I have a friendly gnome who explained it to me, just click where the red rectangle is:
![image](https://user-images.githubusercontent.com/13014163/136615567-bd70aba5-e7a4-4dee-8624-2c633fd0edc7.png)
![image](https://user-images.githubusercontent.com/13014163/136615624-6438d3d0-c0a2-4173-9511-da17fc1f108c.png)
(of course, you could select windows too...)
![image](https://user-images.githubusercontent.com/13014163/136615743-49c90c74-cf7b-4fb3-97c1-718e8a118760.png)
There you can download the most recent build (which is not a release, so be aware!) which has a brand new devilutionx.mpq in it.

Doest that help? Just write here if you need anymore help.

**Comment by stefanoconiglio** [comment]
I built version 1.2.1 by myself, yes, but without having smpq installed. Fetching devilutionx.mpq as @ThomasChr suggested worked, though.

**Comment by stefanoconiglio** [comment]
Re-built after installing smpq. It works without manually bringing devilutionx.mpq into the build dir. I still get this error, though:
en.gmo: No such file or directory
there's a bunch of .gmo files in the build folder (it, es, de, ...) but not the en one.

**Comment by stefanoconiglio** [comment]
I just cloned the 
git clone https://github.com/diasurgical/devilutionX.git

**Comment by AJenbo** [comment]
> I just cloned the master branch with:
> git clone https://github.com/diasurgical/devilutionX.git

Ok, if you want 1.2.1, you have to check out that tag before building.
