### ISSUE TITLE
Set hotspot position of software cursor

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3066]
Currently to align the cursor when moving items, the mouse is shifted by haft the item size. This has a few issues and has to be reverted in some instances, leaving the code a bit fragile. It would be much better if we could make it work like the hardware cursor where instead the alignment is handled by the rendering and not by shifting the mouse position.

```cpp
				if (!IsHardwareCursor()) {
					// For a hardware cursor, we set the "hot point" to the center of the item instead.
					SetCursorPos(cursorPosition - Displacement(cursSize / 2));
				}
```

**Comment by StephenCWills** [comment]
Resolved by #6512
