### ISSUE TITLE
Equipping Weapon with Charges does not Equip Spell

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#3074]
**Important information**
Windows 10 / 2c1aa0c / Compiled Myself

**Describe**
When you equip a weapon that gives you charges of a spell, the right click spell is not set to the charges.

**To Reproduce**
1. Start a new game as a Sorcerer.
2. Left click the starting staff he has equipped so it is now the hold item.
3. Left click with the staff so the sorcerer equips the staff.

**Expected behavior**
The right click spell should be set to the charges when the staff is equipped.

**Additional context**
Not sure when this changed, but when playing fast (speedrunning or not) this is often used for swapping to a staff of heal to quickly heal, or when recharging a staff for the sorcerer, since the mouse is on top of the item you can just pick it up and then equip it again really quick to get the charges set back as the right click skill.

I've almost died a few times with characters when trying to use a heal staff mid battle and the heal spell didn't auto-set.

**Comment by AJenbo** [comment]
Thanks I forgot about this since it was mentioned :sweat_smile: 

Could you test if this fixes it: https://github.com/diasurgical/devilutionX/pull/3077

**Comment by julealgon** [comment]
I remember this being fixed before? Has it resurfaced?
