### ISSUE TITLE
Number of charges / scrolls is no longer displayed

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3079]
Number of charges / scrolls is no longer displayed since commit ec13c333a9eddc1f8708e189bdfb8b8e9f88faa6.
![not_displayed](https://user-images.githubusercontent.com/45902449/136691099-2b9a7d34-e663-4aaf-a662-c95818fd8df5.png)

Desired behavior:
![displayed](https://user-images.githubusercontent.com/45902449/136691125-f82d0dc6-8cb6-4f32-828a-5b16ed683714.png)

**Comment by NiteKat** [comment]
Hah! I noticed this, but thought "Oh I must be thinking of Diablo 2" since I've been playing more Diablo 2 lately, and for whatever reason didn't think to look back at vanilla to confirm. XD Glad you opened this issue!

**Comment by AJenbo** [comment]
Nice catch
