### ISSUE TITLE
Multiplayer - Bugged Player Animation and Movement Updates

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#3086]
**Important information**
Windows 10, Commit 9833445, Compiled myself

**Describe**
Other players appear to be stuck in a south walking animation, and their position does not update while walking until they stop walking. When performing other actions while standing still, the animation does not change but the static walking south animation persist during these actions. 

**To Reproduce**
Unable to reproduce the error

**Expected behavior**
To not do the thing I described

**Screenshots**
N/A as I am unable to replicate yet

**Additional context**
The bug occurred twice during gameplay in one session, and appeared to resolve itself without either player leaving the dungeon level.

**Comment by AJenbo** [comment]
> **To Reproduce**
> Unable to reproduce the error

... this is going to be a problem

**Comment by julealgon** [comment]
Weren't you recording the play session when this happens? Can you point to the segment in the video for reference?

**Comment by obligaron** [comment]
I think this is the same issue as #5046.
The issue was fixed with #5324. 🙂
