### ISSUE TITLE
:bug: paused multiplayer game

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3119]
**Describe**
Multiplayer games can end up being paused locally. This seams to happen if the game is set to a paused state before the multiplayer game is started.

**To Reproduce**
1. start a multiplayer game
2. Before the game loads switch to a different application
3. Switch back to the game after load has compleated
4. See that the game is paused...

**Expected behavior**
Multiplayer games should not be paused ever.

**Extra**
You can make the game unpause by hitting esc

**Comment by StephenCWills** [comment]
I couldn't figure out how to do this the way it was described in this issue. However you can minimize the window while a cinematic plays, let the cinematic end on its own while the window is in the background, then start or join a Multiplayer game to enter the game paused.
