### ISSUE TITLE
Codecov.io Bash uploader is deprecated

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#3126]
https://docs.codecov.com/docs/about-the-codecov-bash-uploader

Codecov.io have introduced a new universal uploader replacing the Bash based uploader used in the linux_x86_64_test CI build. We're in the "scheduled outage" phase so builds will fail at predictable times (announced... somewhere?) until the call to `bash <(curl -s https://codecov.io/bash)` is replaced

**Comment by AJenbo** [comment]
I was wondering which of the projects i'm involved in this email was for:

![image](https://user-images.githubusercontent.com/204594/137477527-58f8e9e0-2094-4706-9657-3bb10421a89d.png)

https://about.codecov.io/blog/introducing-codecovs-new-uploader/

https://docs.codecov.com/docs/codecov-uploader

https://about.codecov.io/blog/codecov-uploader-deprecation-plan/
