### ISSUE TITLE
Support screen text right side cutoff 

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/DevilutionX#3138]
5a75e076b6816e01b185343d97e15e961cd2d7ae on Linux amd64 and Android aarch64

**Comment by NiteKat** [comment]
So I see the same thing, but I see something a little more off.

![image](https://user-images.githubusercontent.com/28605404/138208885-532b56f4-b944-4c11-8a81-88312becf426.png)

I'm using f51768a5 in this screenshot.

**Comment by licaon-kter** [comment]
@NiteKat can't repro on Linux amd64, what resolution and/or settings?
