### ISSUE TITLE
Graphical Glitch with Monster Health Bar and Lava When Paused

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/DevilutionX#3144]
**Important information**
Windows 10 / 2b71f3ea / Compiled myself

**Describe**
When paused, empty portions of the monster health bar that are over lava still animate.

**To Reproduce**
1. Go to the caves.
2. Find a spot you can get a monster where the health bar will be over lava.
3. Make them lose some health so that a portion of the health bar that is empty is over a spot with lava.
4. Pause the game.

**Expected behavior**
Lava under the health bar should not animate, just like the rest of the lava while paused.

**Screenshots**
![pauselava](https://user-images.githubusercontent.com/28605404/137592270-f4a44c07-c704-41d4-85b5-7f98c66538e7.gif)

**Comment by agris-codes** [comment]
the animation continuing occurs for a small piece of the lava tile next to the hole in the wall *without* any monster HP bar as well, I've marked the section of tile that continues to animate with a white circle.

![animated lava](https://user-images.githubusercontent.com/39627597/137635207-ce9b1ca6-15be-4e55-81fb-1921d55fa90c.jpg)

**Comment by agris-codes** [comment]
:howdareyou: haha, yes I will check and let you know.

**Comment by AJenbo** [comment]
@agris-codes the issue is also present in Poison Waters on the left send of the stream in case that makes it easier to change.
