### ISSUE TITLE
Maps can create 0 gp treasure piles

### ISSUE THREAD

**Issue by agris-codes** [diasurgical/devilutionX#3154]
**Important information**
Win10 / modified source build from ~1 day ago, x64

**Describe**
In the catacombs, I came across a room with gold all over the floor. One of the piles of gold was 0 gp. 

**To Reproduce**
Load the attached save game and observe. [single_42.zip](https://github.com/diasurgical/devilutionX/files/7358457/single_42.zip)

**Expected behavior**
If a 0 gp gold pile is rolled, it is not placed. Conversely, it may be rounded up to a minimum of 1 gp. 

**Screenshots**
![0 gp](https://user-images.githubusercontent.com/39627597/137605613-333779cb-b8e7-486f-abdf-eff6da4d281f.jpg)

**Additional context**
I've never seen this happen before, with a lot of hours clocked in vanilla D1. AJenbo thinks this is a "bug in the original game where RNG can return negative numbers, it could be that the gold amount is set to less 4, and then capped to 0."

**Comment by AJenbo** [comment]
@Chance4us could you test if this is a vanilla issue?

**Comment by agris-codes** [comment]
> 
> 
> @Chance4us could you test if this is a vanilla issue?

I just loaded it in Diablo v1.09 and the 0 gp pile is still there.

**Comment by Chance4us** [comment]
The 0 gp piles are actually generated in the master. I'll bisect it as soon as there is free time.

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/137627448-4f58b477-f3cc-4159-92e6-e7ad23055a08.png)
Checked on 1.2.1, seems the whole map layout changed

**Comment by Chance4us** [comment]
>  so just enter the quick entrance to test faster

Is the "quick entrance" some kind of debug feature?
