### ISSUE TITLE
Enemy missiles failing to hit PC when fired from certain angles

### ISSUE THREAD

**Issue by agris-codes** [diasurgical/devilutionX#3156]
**Important information**
Win10 / modified source build from ~1 day ago, x64. Playing in --diablo mode w/ hellfire MPQs present. 

**Describe**
Enemy missiles, including arrows, don't appear to hit the PC as often as they should, or sometimes ever. Most obvious on poison spitters since their missiles show the impact animation

**To Reproduce**
Load this save. [single_19 - missiles.zip](https://github.com/diasurgical/devilutionX/files/7358737/single_19.-.missiles.zip)

Note that the poison spits are impacting *something* prior to arriving at the player. The invisible barrier that is interrupting enemy missiles moves with the player. Move horizontally after loading the save and note that the enemy missiles track the player, but still do not connect. This occurred periodically throughout this encounter. I've also been in situations with groups of archers where it felt like none of their arrows were hitting me, when some should. I expect whatever is triggering the poison missiles to be blocked is also impacting arrows and other missiles.

**Expected behavior**
Some percentage of missiles to hit the PC

**Screenshots**
Image demonstrating the impact of a poison spit on something invisible, blocking it from hitting the PC.
![missles blocked](https://user-images.githubusercontent.com/39627597/137611385-50cb8280-600e-4557-b9e9-8431c5661f47.jpg)

**Additional context**
I recall there was a PR regarding how missiles move at-angle and the tiles they can hit. I couldn't find it in the merged PRs after a brief review, but I wonder if that is unintentionally causing the behavior I've observed on this playthrough. 

It is also *much* easier to hit enemies at an angle with missiles (arrows), reducing the need for player skill. I used to have to do much more dancing to align enemies on my cardinal N/S/E/W to hit them, diagonal shots almost always missed. I recognize the PR (that I can't find) was a bug fix, but it may have (a) introduced another bug and (b) really reduced the difficulty of playing a ranged character. 

edit: loaded the same save in Diablo v1.09 and observed the same behavior.

**Comment by StephenCWills** [comment]
I bumped up the range of their missiles, and it's hitting the Rogue now.

![image](https://user-images.githubusercontent.com/9203145/137612148-8f050676-fec1-4d4b-99fe-19de5e8aecb7.png)

**Comment by agris-codes** [comment]
@StephenCWills Is there a possibility that increasing the range reset something else that may have been responsible for what I observed? That seems incredibly short for their maximum range, and inconsistent with my experience. Those suckers can hit you from off the screen or at least at the very edge. Maybe I'm thinking of the variants encountered in the Cave tileset, and they have a longer range.

**Comment by qndel** [comment]
That's exactly how it works in vanilla

**Comment by agris-codes** [comment]
Thanks for the consideration, sorry to waste everyone’s time.

**Comment by qndel** [comment]
> Thanks for the consideration, sorry to waste everyone’s time.

No worries, in the future you can check yourself in vanilla :D
