### ISSUE TITLE
[Windows MinGW with WSL] Building fails, SDL2 and Sodium not found

### ISSUE THREAD

**Issue by johannes87** [diasurgical/devilutionX#316]
I used Windows Services for Linux (WSL) for builidng. I use Ubuntu 18.04 LTS inside WSL. cmake can't find SDL2 and Sodium. 

Here's the output of `cmake`:
```
johannes@JOHANNES-WIN10:~/devilutionX/build$ cmake -DASAN=OFF -DCMAKE_TOOLCHAIN_FILE=../CMake/mingwcc.cmake ..
-- Could NOT find Sodium (missing: sodium_LIBRARY_RELEASE sodium_LIBRARY_DEBUG sodium_INCLUDE_DIR)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR
  SDL2_SDLMAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindSDL2.cmake:152 (find_package_handle_standard_args)
  CMakeLists.txt:79 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/johannes/devilutionX/build/CMakeFiles/CMakeOutput.log".
See also "/home/johannes/devilutionX/build/CMakeFiles/CMakeError.log".
```

I followed the instructions in the README. I downloaded the MinGW development libraries and put them in `/user/i686-w64-mingw32`. I had to create the directory first.

```
$ ls /user/i686-w64-mingw32/
SDL2-2.0.10  SDL2_mixer-2.0.4  SDL2_ttf-2.0.15  libsodium-win32  libsodium-win64
```

**Comment by AJenbo** [comment]
Thanks for reporting this. It appears to be a typo in the readme, the folder should be /usr/i686-w64-mingw32

You can see the build bot doing the process here:
https://github.com/diasurgical/devilutionX/blob/master/.circleci/config.yml#L60

**Comment by AJenbo** [comment]
The readme has now been corrected: https://github.com/diasurgical/devilutionX/commit/21fb588e5659e6e2fb7695a16099a605f3f2f9ca
