### ISSUE TITLE
Barbarian chance to hit rate

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3163]
The Barbarian wins 1% chance to hit rate with every clvl. This behavior does not occur in vanilla.
Further research is needed. A savegame is attached for testing purposes just before a next clvl.
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/7368198/single_0.hsv.zip)

**Comment by qndel** [comment]
Displayed vanilla hit chance formula is dogshit, we are better than that.
