### ISSUE TITLE
Check report of barbarian spell issue in Diablo mode

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3164]
@kphoenix137 mentioned that the game crashed when playing the Barbarian in Diablo mode.

**Comment by CaptainCosmotic** [comment]
[bugreport.zip](https://github.com/diasurgical/devilutionX/files/10158545/bugreport.zip)

Hi, I also got a reproducible crash with the barbarian in diablo mode. 
I'm using a nightly build 8 days old.
How to reproduce: 
Take the savegame in the zip file.
Play with RUFUS - load game
Go around the corner and fight with the Guardians
crash

**Comment by kphoenix137** [comment]
> Barbarian

My crash was related to setting the rage quick spell, probably about a year ago

**Comment by DakkJaniels** [comment]
You should probably indicate what commit your build is based is on, there are no nightly builds.

**Comment by CaptainCosmotic** [comment]
You are right its the Windows MinGW x64 v1.4.0 and I downloaded the zip file at the bottom of this link
https://github.com/diasurgical/devilutionX/actions/runs/3560295399

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/commit/1e20a5721f18c8d36806ef23bb116d2e4dca15b8

**Comment by qndel** [comment]
Cannot reproduce anymore.
