### ISSUE TITLE
Berserked Hell Spawn Destroyed All Light But One on Death

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#3166]
**Important information**
Windows 10 / f3b4da8a / Compiled myself

**Describe**
When I killed a berserked Hell Spawn that had been fighting for me for a while, everything went dark except for what I suspect was her light radius, which had detached from her prior to her death. I guess I destroyed the light of my life.

**To Reproduce**
Steps to reproduce the behavior: Not sure exactly how to reproduce, but this is how it happened to me...
1. Berserk a Hell Spawn.
2. Let it fight another Hell Spawn for a while. They do so little damage to each other they won't be able to kill each other.
3. Wait for the berserk light radius to detach I guess?
4. Kill Berserked Hell Spawn.
5. Profit.

**Expected behavior**
Everything shouldn't go dark when the Berserked Hell Spawn is killed.

**Screenshots**
![image](https://user-images.githubusercontent.com/28605404/137820115-6449e0ba-8c8b-454e-a5fe-b61d66806c0f.png)

**Additional context**
Save file: 
[single_0.zip](https://github.com/diasurgical/devilutionX/files/7369097/single_0.zip)

**Comment by NiteKat** [comment]
I suspect this bug was my light source getting deleted instead of the berserked monster's, probably related to the light source for the berserk monster getting detached from it. I can't quite figure out how to reliably replicate it.

Off topic: I am for replacing light source with an outline with regards to indicating Berserk.

**Comment by k-bar** [comment]
should be reopen until #4628 merged.
![berserkLightLoad](https://user-images.githubusercontent.com/92504151/172084328-fefea09f-e037-4588-adc8-271acdd72941.gif)
