### ISSUE TITLE
Level state gets saved on quitting the game

### ISSUE THREAD

**Issue by SoundChaser83** [diasurgical/DevilutionX#3167]
**Important information**
Version 1.2.1-2dea91b5

**Describe**
Items can be duped, picked up, and sold.

**To Reproduce**
1. Load [this save file.](https://github.com/diasurgical/devilutionX/files/7371403/single_0.zip)
2. Portal out of Lazarus' room.
3. Drop something from your current inventory on the floor in town.
4. Take the stairs to level 5 from town.
5. QUIT the game (do not save or load).
6. Re-launch the game and load the save file again.
7. Portal back to town, and your items should still be on the floor and also in your inventory.

**Expected behavior**
Quitting and reloading the game should restore the game state to exactly what it was when it was saved.

**Comment by qndel** [comment]
Tracked down to using giNumberOfLevels before initializing.
