### ISSUE TITLE
Hell tile with invisible collision

### ISSUE THREAD

**Issue by agris-codes** [diasurgical/devilutionX#3183]
**Important information**
Win10 / compiled x64 myself, almost-vanilla build from ~1 week ago

**Describe**
It appears that this Hell tile with a body has collision set incorrectly, such that missiles impact it and the player can't walk there.

**To Reproduce**
Load this save, observe missiles impacting mid-air. 
[single_8 - hell_tile.zip](https://github.com/diasurgical/devilutionX/files/7383670/single_8.-.hell_tile.zip)

**Expected behavior**
No collision. 

**Screenshots**
DevilutionX
![DX_Hell](https://user-images.githubusercontent.com/39627597/138155602-c3940945-1391-4117-8970-490cea6ee8c1.jpg)

Vanilla 1.09b
![v109b_Hell](https://user-images.githubusercontent.com/39627597/138155607-d60b1141-bd50-4ee0-9eb7-865b73799056.png)

**Comment by qndel** [comment]
Turns out these bodies are "objects" and they are so weird that to end up aligned with the wall, they have to be placed 1 tile in front of it and got collision set to true
