### ISSUE TITLE
The font size can sometimes be a little too big

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/DevilutionX#3195]
In the practical example, the value for damage.
![screen00](https://user-images.githubusercontent.com/45902449/138249304-4e0c4692-9135-4ec9-90eb-c04d17d515d3.png)

Savegame:
[barbarian.zip](https://github.com/diasurgical/devilutionX/files/7387734/barbarian.zip)

**Comment by AJenbo** [comment]
This actually is also a problem with the vanilla panel, the space here is already fairly cramped, especially with translations, so not sure what the best option would be @qndel any thoughts?

**Comment by AJenbo** [comment]
@Chance4us could you add a comparison from 1.09?

**Comment by agris-codes** [comment]
Could the text layer be a logical object that if [OBJECT_SIZE] > [BOX_WIDTH] the object is scaled? I.e. selective scaling of the text that would overflow the box, such that it's < [BOX_WIDTH]. It wouldn't take much to bring the values within the bounds of that UI element, I'm guessing 0.95 would be enough for damage.
