### ISSUE TITLE
Attacking unique Blink doesn't teleport its light

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#32]
The save is at a room with blinks and the unique one like all unique monsters has a light aura around it. Attacking the monster from a distance will teleport it right next to the player, but the light will remain at the place the monster teleported from.

If the monster moves on its own, the light will correct itself and move to wherever the monster is again.

[blink.zip](https://github.com/diasurgical/devilutionX/files/2945987/blink.zip)

**Comment by AJenbo** [comment]
I know that there were some similar issues in the original game, so we should test so see if that is the case here.

Not to say that we shoudn't fix this, but we should document and prioritize it.

**Comment by AJenbo** [comment]
This issue at least also happens upstream in Devilution.

**Comment by AJenbo** [comment]
this issue is in the original game;
http://www.lurkerlounge.com/forums/thread-12422.html
> MOONBENDER'S LIGHT RADIUS
> 
> The light square of Moonbender (a Blink boss) will freeze in place if it 'blinks' next to you, and won't follow the boss even if the boss moves afterward.
It's referenced in https://github.com/diasurgical/devilution/issues/64 so I'm going to close this issue as this will eventually be addressed after we hit 1.0
