### ISSUE TITLE
[README, How To Play] Where is the DevilutionX game directory?

### ISSUE THREAD

**Issue by johannes87** [diasurgical/devilutionX#320]
The README says: "Copy diabdat.mpq from your CD, or GoG install folder, to the DevilutionX game directory ; Make sure it is all lowercase"

Where is the DevilutionX game directory (on Windows, Mac and Linux)?

**Comment by AJenbo** [comment]
Where ever you decide to put the application

**Comment by ssokolow** [comment]
For anyone trying to install devilutionX on a mac who gets led here by search engines, right-click/Control-click the devilutionX app and choose "Show Contents", then go into the "Contents" folder and drop `diabdat.mpq` into the Resources folder.

**Comment by AJenbo** [comment]
Just FYI it's a bug in the 1.5.3 Mac build, normally it goes next to the app, not inside it

**Comment by ssokolow** [comment]
Ouch. That's the kind of thing which would make me file a "BUG: 1.5.4 requires me to clutter up Applications unless I put the game somewhere else and use an alias" over.

I think I'll stay on 1.5.3 for my High Sierra hand-me-down indefinitely then.

**Comment by ssokolow** [comment]
That'd be more suitable, given that I'm already doing similar things for stuff like ScummVM. Thanks.

**Comment by AJenbo** [comment]
It's not really a bug here though it's because we had help from Mac Ports to build it and there system overwrote the build script. They have been informed. I can't really do much since I don't want to pay for a new Mac just so I can do builds myself

**Comment by AJenbo** [comment]
It's also been like that for all previous versions an you never complained before

**Comment by ssokolow** [comment]
> It's also been like that for all previous versions an you never complained before.

I usually run it on Linux via Flatpak.

This is the first version I ever tried to run on the High Sierra hand-me-down that only just borderline qualifies for my retrocomputing hobby.

**Comment by AJenbo** [comment]
We are not there yet with the os 9 support

**Comment by ssokolow** [comment]
That's fine. Aside from having enough exclusives (Ambrosia Software, anyone?), OS 9 is fun in and of itself so I don't need to go searching for uses like I [do](https://www.wired.com/2002/10/the-mac-os-that-cant-be-tweaked/) with OS X.

Heck, I'm currently waiting for the rest of the books I ordered on classic Mac OS programming to arrive in the hope that I'll be able to budget enough study time over the Christmas holidays to get the knowledge to stick if I loop back to chapter 1 of Programming Starter Kit for Macintosh.
