### ISSUE TITLE
Try switching to libmpq

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#3223]
As of #3180 and #3222, we've completely isolated MPQ reading logic. We already use our own code for writing mpqs.

There are a few issues with StormLib:

1. It is not thread-safe, requiring a lock around open, read, and close, which is not ideal for streaming music.
2. It is not very portable, requiring lots of platform-specific ifdefs internally in the past.
3. It mmaps the whole archive, requiring loads of virtual memory (was a problem on the SerenityOS 32-bit port).

https://github.com/ge0rg/libmpq does not seem to have any of these issues. Its source code is also somewhat more readable.

However, it is quite low-level: the only way to stream files out of it is to operate directly on blocks.

It would be worth investigating if we can write an `SDL_RWops` wrapper around the block API (the current StormLib wrapper is at https://github.com/diasurgical/devilutionX/blob/master/Source/storm/storm_sdl_rw.cpp).

Adding the dependency via CMake was fairly straightforward: https://github.com/glebm/devilutionX/commits/libmpq

**Comment by Chance4us** [comment]
@glebm 
Obviously the installation of smpq is still required to generate the devilutionx.mpq.
I noticed that libbz2-dev needs to be installed now, but devilutionx is not generated without smpq.
Is it possible that I misunderstood the purpose of libmpq?

**Comment by qndel** [comment]
> @glebm Obviously the installation of smpq is still required to generate the devilutionx.mpq. I noticed that libbz2-dev needs to be installed now, but devilutionx.mpq is not generated without smpq. Is it possible that I misunderstood the purpose of libmpq?

It's for reading MPQs while for devilutionx.mpq we need to write a mpq which smpq does if I understand it correctly.
