### ISSUE TITLE
Font overlap

### ISSUE THREAD

**Issue by yahooboby** [diasurgical/devilutionX#3231]
![123](https://user-images.githubusercontent.com/72782990/138560919-2be83016-3a9d-4481-b2b5-506eda137d75.png)

devilutionX-master\Translations\zh_CN.po
line:6754-6764:
#. TRANSLATORS: Quest dialog spoken by Griswold
#: Source/textdat.cpp:27
msgid ""
"I made many of the weapons and most of the armor that King Leoric used to "
"outfit his knights. I even crafted a huge two-handed sword of the finest "
"mithril for him, as well as a field crown to match. I still cannot believe "
"how he died, but it must have been some sinister force that drove him insane!"
msgstr ""
"我打造的武器和盔甲大部分被李奥瑞克国王武装他的骑士。我还为他本人锻造了一把趁"
"手的秘银双手大剑和一顶与之相配的王冠。我始终无法接受他的驾崩，一定是某种强大"
"的邪恶把他逼疯了！"

line:8377-8386:
#. TRANSLATORS: Neutral dialog spoken by Cain (Gossip)
#: Source/textdat.cpp:311
msgid ""
"I know of many myths and legends that may contain answers to questions that "
"may arise in your journeys into the Labyrinth. If you come across challenges "
"and questions to which you seek knowledge, seek me out and I will tell you "
"what I can."
msgstr ""
"我知道许多神话和传说，其中可能包含对你在迷宫之旅中可能出现的问题的答案。如果"
"你遇到挑战和问题，你寻求知识，寻找我出来，我会告诉你我能做什么"

**Comment by AJenbo** [comment]
@glebm should we close this?

**Comment by glebm** [comment]
Still need to do Japanese but yeah let's close this one
