### ISSUE TITLE
Guide: Getting the MPQ from the GoG installer with out Windows

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#33]
We should make wiki page for how to handle the GoG version with out the need of Windows. See the link below for a first draft:
https://github.com/diasurgical/devilutionX/issues/20#issuecomment-471043336

**Comment by AJenbo** [comment]
Oh, that would be nice if the listed it :)

**Comment by predator8bit** [comment]
https://lutris.net/games/diablo/ I created an installer that asks for the GOG exe and takes care of the rest. At the moment the installer is still unpublished, but I'm sure someone will approve it sooner or later. :)

**Comment by AJenbo** [comment]
nice

**Comment by mewmew** [comment]
@predator8bit Great work! The installer is published now I think. https://lutris.net/api/installers/diablo-gog-devilutionx-win3?format=json

Would you mind updating it to work with the latest DevilutionX (i.e. [release 0.4.0](https://github.com/diasurgical/devilutionX/releases/tag/0.4.0))?

@AJenbo, even with the installer script in Lutris, we should probably add the MPQ extraction instructions as a Wiki page for users who do not want to use the full Lutris installer, but just the extraction tool. What do you think?

**Comment by AJenbo** [comment]
Yeah a guide should definitely be written on the wiki page, that's why the issue is still open :)

**Comment by predator8bit** [comment]
I will update it asap!

8 Jun 2019, 05:18 by notifications@github.com:

**Comment by predator8bit** [comment]
The installer you linked @mewmew wasn't the one I originally submitted, someone deleted that. So I forked it into a new native one. 

The hellfire gog installer doesn't work, innoextract throws 1error and 1 warning, looking at the files it managed to successfully extract the DIABDAT.MPQ is only "19.9 MiB (20,889,600 bytes)" instead of "493.5 MiB (517,501,282 bytes)" what you get from the standalone diablo installer.

**Comment by dallemon** [comment]
Using current innoextract-git (from Arch AUR) works fine. So a new official release of innoextract is needed (newer than 1.7) or compile it yourself from git.

File extracted successfully running "innoextract -I DIABDAT.MPQ setup_diablo_1.09_hellfire_v2_\(30038\).exe"

Did a quick test with a fresh 32-bit build and it works, although it seems that DIABDAT.MPQ name is case sensitive and needs to be lowercase.

**Comment by matthewrkarlsen** [comment]
Hello,
I could update the Wiki page if you want. I don't seem to have edit permissions right now though...

Thanks,
Matthew

**Comment by AJenbo** [comment]
Thanks that would be helpful.

**Comment by matthewrkarlsen** [comment]
Hello AJenbo,

I created a local branch of the wiki `devilutionX-issue-33` and was then going to create a wiki PR (somehow, UI seems to be missing for this). Unfortunately on push I am getting `remote: Permission to diasurgical/devilutionX.wiki.git denied to matthewrkarlsen`. I have a complete document, I just need to be able to get it to CR... please advise?

Sorry for the basic GitHub question. I did RTM and it seems I need to be a contributor to edit the wiki?

Thanks,
Matthew

**Comment by AJenbo** [comment]
Thanks I posted it on the wiki:
https://github.com/diasurgical/devilutionX/wiki/Extracting-the-DIABDAT.MPQ-from-the-GoG-installer

Closing this issue, but we should probably promote the guide on the main page or such.
