### ISSUE TITLE
Regression - Error During Compiling

### ISSUE THREAD

**Issue by jrugia** [diasurgical/devilutionX#332]
As of commit d15bd453c606e3c8e67d65756987b1ea850e7798 I'm getting errors at the end of compiling, tested with the previous commit and errors don't occur

Log:

> /home/jojo/devilutionX-master/Source/drlg_l2.cpp: In function ‘CreateL2Dungeon’:
> /home/jojo/devilutionX-master/Source/drlg_l2.cpp:1072:23: warning: iteration 40 invokes undefined behavior [-Waggressive-loop-optimizations]
>     if (predungeon[i][j] == 44) {
>                        ^
> /home/jojo/devilutionX-master/Source/drlg_l2.cpp:1059:17: note: within this loop
>    for (i = 0; i <= DMAXX; i++) { /// BUGFIX: change '<=' to '<'

Nevertheless the game runs fine, haven't tested it extensively though.

**Comment by glebm** [comment]
This is not an error, it's a warning, and it does occur with the previous commit (you probably didn't `make clean` before checking)
