### ISSUE TITLE
Crash when using spanish translation and shopping at Griswold

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3323]
Crash happened on an Android 11 Redmi 9 Phone for González who also reported the issue in a review.

> The redesign of the graphical interface makes it much easier to play on the touch screen, plus it feels more fluid, aesthetically pleasing. Detail: the Spanish translation is incomplete and sometimes it seems to have used Google Translate. Problem: after a certain amount of time the game crashes, losing progress, something that did not happen prior to this update.

It's unclear to me what exact prefix or item is causing this, so some investigation is required. Hopefully González will add some more details later.

```
ibzt.so (abort_message) (SourceCode: portlistingparse.c)
ibzt.so (demangling_terminate_handler()) (SourceCode: cxa_default_handlers.cpp)
ibzt.so (std::__terminate(void (*)())) (SourceCode: portlistingparse.c)
ibzt.so (__cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*)) (SourceCode: cxa_exception.cpp)
ibzt.so (__cxa_throw)
ibdevilutionx.so (fmt::v7::detail::error_handler::on_error(char const*))
ibdevilutionx.so (char const* fmt::v7::detail::parse_replacement_field<char, fmt::v7::detail::format_handler<fmt::v7::detail::buffer_appender<char>, char, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >&>(char const*, char const*, fmt::v7::detail::format_handler<fmt::v7::detail::buffer_appender<char>, char, fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char> >&)) (SourceCode: format.cc)
ibdevilutionx.so (void fmt::v7::detail::vformat_to<char>(fmt::v7::detail::buffer<char>&, fmt::v7::basic_string_view<char>, fmt::v7::basic_format_args<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<fmt::v7::type_identity<char>::type>, fmt::v7::type_identity<char>::type> >, fmt::v7::detail::locale_ref))
ibdevilutionx.so (fmt::v7::detail::vformat(fmt::v7::basic_string_view<char>, fmt::v7::format_args))
ibdevilutionx.so (devilution::PrintItemPower(char, devilution::Item*))
ibdevilutionx.so (devilution::(anonymous namespace)::PrintStoreItem(devilution::Item*, int, devilution::UiFlags)) (SourceCode: stores.cpp)
ibdevilutionx.so (devilution::(anonymous namespace)::ScrollSmithPremiumBuy(int)) (SourceCode: stores.cpp)
```

**Comment by obligaron** [comment]
I checked the es translation and found a [wrong number of fmt-arguments translation](https://github.com/diasurgical/devilutionX/blob/60f562d1dd8468c00e56730937042f1293c3cc62/Translations/es.po#L3912).

Steps to reproduce:
- drop king's club
- pick king's club item up and hover it in inventory => crash

Perhaps we could add a unit test that checks that the argument counts match between `en` and other languages. New (separate) issue?

**Comment by AJenbo** [comment]
Nice I had a suspicion that might have been the issue :)
