### ISSUE TITLE
CharisSILB.ttf called as ./CharisSILB.ttf ?

### ISSUE THREAD

**Issue by Vitexus** [diasurgical/devilutionX#333]
Hi, i have problem with error message font. If is the file CharisSILB.ttf  in same directory as ./devilutionx binary everything is OK. 
But what to do if i want have this font in /usr/share/fonts ?

Is best solution patch source code fonts.cpp:61 before packaging for linux  like this? : 

	font = TTF_OpenFont("/usr/share/fonts/truetype/CharisSILB.ttf", 17);

Be sure without it i get:

TTF_OpenFont: Couldn't open CharisSILB.ttf

![obrazek](https://user-images.githubusercontent.com/2621130/66276853-f5e9f600-e896-11e9-91ff-b632a5fb972b.png)

Is there any way how to request font by name but not by filename ? 

Any adivises how to do best ?

Thank for any help

I want it for Debian & Fedora packaging to be nice done  without nasty symlinks or any other ugly hacks.

**Comment by AJenbo** [comment]
Unfortunately I haven't been able to find any (especially not cross-platform) way of requesting a font, the only solution I could find was to request it the way you see here. Especially on Mac this is a bit odd since the file is actually located in `../resources` but that is the current folder when running a program from a bundle.

**Comment by Vitexus** [comment]
Ok. I'l fix it in debian/redhat package building. 
Thank you for your point of view.

P.s. Here you can find my RPMs: https://build.opensuse.org/package/show/home:vitexus/devilutionX

![obrazek](https://user-images.githubusercontent.com/2621130/66277743-33548080-e8a3-11e9-9c32-7b0ef51ec243.png)

p.s.s. Font problem not fixed yet. Please wait for next builds.

**Comment by AJenbo** [comment]
Cool thanks for doing this

**Comment by Vitexus** [comment]
Is this solution acceptable for you ?:

**debian/rules:**
export DEB_CFLAGS_MAINT_APPEND  = -Wno-error -DMSG_FONT=/usr/share/fonts/truetype/CharisSILB.ttf


**fonts.cpp:** 
![obrazek](https://user-images.githubusercontent.com/2621130/66349504-55103f00-e959-11e9-9329-5a93c67ceddf.png)

**Comment by Vitexus** [comment]
Or second solution way:

![obrazek](https://user-images.githubusercontent.com/2621130/66352550-06b26e80-e960-11e9-8091-373723de1d07.png)

**Comment by MBeijer** [comment]
https://stackoverflow.com/questions/39805355/use-sdl2-ttf-to-open-a-system-font/39835756

**Comment by AJenbo** [comment]
Oh looks like we will need that anyway for translation support, feel free to send a patch that allows it to open system fonts :)
