### ISSUE TITLE
Shift clicking red weapons

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3345]
If you shift click a weapon you don't have the stats to wear, it still unequips your current weapons.
@joewis can you look at it? ;)

**Comment by joewis** [comment]
Yes should be rather straight forward. Why do you shift-click weapons where you don't have the stats for? ;)

**Comment by joewis** [comment]
https://github.com/diasurgical/devilutionX/pull/3349

**Comment by AJenbo** [comment]
> #3349

Probably better to write `Fixes #3345` in the description of the PR so that this one is close automatically when the PR is merged.
