### ISSUE TITLE
Polish sound pack results in corrupted sounds on Switch

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3350]
https://github.com/diasurgical/devilutionx-assets/releases/download/v1/pl.mpq

https://user-images.githubusercontent.com/204594/139605701-c660eced-eb4c-41c8-b0ed-6925c5af97c1.mov

**Comment by SourceCodeDeleted** [comment]
Those are not corrupted sounds. That is how Polish sounds ))) 

@qndel  ))) I am joking mate )

**Comment by StephenCWills** [comment]
This was fixed on 3DS ever since StormLib was replaced by libmpq. Can someone test the latest test build on Switch to see if it's fixed?
https://70999-143324737-gh.circle-artifacts.com/0/devilutionx.nro

**Comment by J013k** [comment]
I have the same problem on PS Vita.

With [optional dub](https://github.com/diasurgical/devilutionx-assets/releases/download/v1/pl.mpq) by professional voice actors instead of e.g. gossip\rumor voice I have a weird annoying sound for a short (1-2 sec) period of time.

Without pl dub all sounds are fine.

**Comment by AJenbo** [comment]
> I have the same problem on PS Vita.

Can you test the test build: https://72746-143324737-gh.circle-artifacts.com/0/devilutionx.vpk

**Comment by J013k** [comment]
> Can you test the test build: https://72746-143324737-gh.circle-artifacts.com/0/devilutionx.vpk

With this version I cannot start new game when I have `pl.mpq` in `ux0:/data/diasurgical/devilution/`.
I have uploaded a crash log:
[psp2core-1638031707-0x00002c2c17-eboot.bin.zip](https://github.com/diasurgical/devilutionX/files/7612116/psp2core-1638031707-0x00002c2c17-eboot.bin.zip)
 
Additionally something bad happens with some animations and with the intro FMV:
![2021-11-27-174807](https://user-images.githubusercontent.com/54805484/143690533-325b972d-57bc-406e-aeb1-218b3baae690.jpg)
These stripes does not appear in v1.3.0.

**Comment by StephenCWills** [comment]
Hmm, I also cannot start a new game when using `pl.mpq` on Windows, but it still works fine on 3DS. I haven't noticed any issues with animations or the FMV.

**Comment by AJenbo** [comment]
> Hmm, I also cannot start a new game when using `pl.mpq` on Windows, but it still works fine on 3DS. I haven't noticed any issues with animations or the FMV.

The on in the original release has this issue, but later releases have a fixed MPQ where the video was corrected. But somehow libsmacker was able to compensate for it. But libsmackerdec does not.

**Comment by glebm** [comment]
For libsmacker, we had our own fix for a similar issue: https://github.com/diasurgical/devilutionX/pull/2910

**Comment by StephenCWills** [comment]
> With this version I cannot start new game when I have `pl.mpq` in `ux0:/data/diasurgical/devilution/`.

@J013k I believe the crash is fixed in the latest test build. It would help us out if you could test again.
https://73298-143324737-gh.circle-artifacts.com/0/devilutionx.vpk

**Comment by J013k** [comment]
Unfortunately once again after starting new game, the game crashes at this screen:
![2021-11-30-190439](https://user-images.githubusercontent.com/54805484/144105000-c8791f1e-e8a5-470e-9a40-1e96a718081b.png)

Here is a crash log:
[psp2core-1638295813-0x00003e2f33-eboot.bin.zip](https://github.com/diasurgical/devilutionX/files/7627901/psp2core-1638295813-0x00003e2f33-eboot.bin.zip)

**Comment by AJenbo** [comment]
@J013k sorry for more wish full thinking, but could you test this again :sweat_smile:

**Comment by J013k** [comment]
Not a problem.
Just write which version you want me to check.

Is it the one from 30 Nov 2021 (or any other version?):
> I believe the crash is fixed in the latest test build. It would help us out if you could test again.
> https://73298-143324737-gh.circle-artifacts.com/0/devilutionx.vpk

Additionally I will delete all files for devilutionX, and re-install it.

**Comment by AJenbo** [comment]
The most recent one is 8 hours old, that would be preferred over one that is over 4 months behind :sweat_smile: 
https://output.circle-artifacts.com/output/job/5e54b9db-efcd-423a-a7ee-b8d194efbd5d/artifacts/0/devilutionx.vpk

**Comment by J013k** [comment]
With this new build game still crashes at the same time\moment with `pl.mpq` in `ux0:/data/diasurgical/devilution/`.
When I delete `pl.mpq`, game starts normally.

Dub was downloaded from here:
https://github.com/diasurgical/devilutionx-assets/releases/download/v1/pl.mpq.

The only upside with this new version is that I do not have any problems with intro FMVs.

**Comment by AJenbo** [comment]
Thank

**Comment by isage** [comment]
I'll take a look.

**Comment by AJenbo** [comment]
We narrowed it down to issues with how the Hoffman decompression is manipulating pointers to encode additional meaning.

Also we concluded that it works correctly on 3DS

**Comment by AJenbo** [comment]
Switch tested via emulator, it appears to be doing well. Only Vita is having issues at this point.
