### ISSUE TITLE
Make script for detecting fmt errors in translations

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3360]
Currently we have an unfortunate issue with the Spanish and French users of the Android port as they will some times crash because of a translation error, and we cannot push a new update for a while. To avoid this in the future we should not terminate the application in case of invalid fmt string.

https://github.com/diasurgical/devilutionX/blob/4274cc6f1fff3191ff17babb6f2d77274d44e4d9/Source/utils/log.hpp#L52

**Comment by glebm** [comment]
> To avoid this in the future we should not terminate the application in case of invalid fmt string.

Alternatively, we could verify the translation strings, e.g. with a test.

**Comment by AJenbo** [comment]
I would prefer both, since that still woudnt prevent it from happening in the english strings afaik

**Comment by glebm** [comment]
My guess is, if it crashes, problems will be noticed and fixed quicker

**Comment by AJenbo** [comment]
I was thinking that is a strategy more suited for debug builds

**Comment by AJenbo** [comment]
Hmm this might be less critical as we can more easily pump out new versions following the next release, since it ends the Android migration window any way.
