### ISSUE TITLE
1.3.0 RG350 does not start. Exits to main screen on boot.

### ISSUE THREAD

**Issue by LanceJZ** [diasurgical/devilutionX#3367]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
1.3.0

**Describe**
Game exits to main menu.

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

Start game on RG350.

**Expected behavior**
Game runs.

**Screenshots**

**Additional context**

**Comment by glebm** [comment]
1.3.0 requires OpenDingux Beta

**Comment by glebm** [comment]
OpenDingux Beta update OPK can be downloaded from http://od.abstraction.se/opendingux/latest/
More details over at https://opendingux.net/
