### ISSUE TITLE
[Question] Difficulty comparison Diablo vs. Hellfire

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3372]
I tried a Hell difficulty game with a new hero in Diablo and Hellfire.
I noticed very big differences, so the question arose as to whether the differences are intentional.

The monsters in Diablo are much easier to kill on this difficulty than they are in Hellfire. They seem to have a lot more hitpoints in Hellfire.

Desired behavior:
Diablo should also be about the same in difficulty.

Comparison:

Diablo + savegame:
[diablo.zip](https://github.com/diasurgical/devilutionX/files/7466565/diablo.zip)

https://user-images.githubusercontent.com/45902449/140037836-40413396-ff4b-480a-8f46-902ee6ffd7c2.mp4

Hellfire + savegame:
[hellfire.zip](https://github.com/diasurgical/devilutionX/files/7466567/hellfire.zip)

https://user-images.githubusercontent.com/45902449/140038013-922ec517-8711-4019-8c3c-f017aabf31ee.mp4

**Comment by qndel** [comment]
That's how it is, they had more hp in hellfire.

**Comment by Chance4us** [comment]
> That's how it is, they had more hp in hellfire.
> 
> ```c++
> 	} else if (sgGameInitInfo.nDifficulty == DIFF_HELL) {
> 		monster._mmaxhp = 4 * monster._mmaxhp;
> 		if (gbIsHellfire)
> 			monster._mmaxhp += (gbIsMultiplayer ? 200 : 100) << 6;
> 		else
> 			monster._mmaxhp += 192;
> 			
> 
> 	if (sgGameInitInfo.nDifficulty == DIFF_NIGHTMARE) {
> 		monster._mmaxhp = 3 * monster._mmaxhp;
> 		if (gbIsHellfire)
> 			monster._mmaxhp += (gbIsMultiplayer ? 100 : 50) << 6;
> 		else
> 			monster._mmaxhp += 64;
> ```
> 
> Hell bonus: Vanilla: +3 hp Hellfire: + 200 for multi, +100 for single
> 
> Nightmare bonus: Vanilla: +1 hp Hellfire: + 100 hp for multi, +50 for single

But I also had the impression that those in Hellfire heal much faster, is it the way it should be also?
Somehow Diablo is way too easy.

**Comment by qndel** [comment]
Hellfire hasn't touched monster levels which affect healing speed, so if anything, you should see the health bar fill slower in hellfire because the monster has more hp and same regen speed = takes more time to fully heal

**Comment by julealgon** [comment]
@Chance4us you can use "Discussions" in github instead of "Issues" for this type of item.
