### ISSUE TITLE
[touch] joystick can get stuck when switching to a menu

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3375]
> However, I have met a bug that if you were dead when pushing the direction panel, the menu will automatically moving so that the user can’t push any key.

I have experienced this my self on one occasion, i was holding the joystick in a direction and entered a menu where the joystick isn't active, the cursor would then constantly move up making it impossible to navigate the menu.

**Comment by SourceCodeDeleted** [comment]
yes this will happen if you disconnect to . In short , when menu opens, closes or a return to main game menu, we need to have a joystick reset.

**Comment by AJenbo** [comment]
@StephenCWills any chance you can have a look, since you are intimate with the virtual controller :)
