### ISSUE TITLE
Use our own code to generate devilutionx.mpq

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#3377]
We already have code to write mpq files (in `mpqapi.h`).
We could wrap it in a binary and use it instead of requiring `smpq`.

This should make packaging devilutionx somewhat easier.

**Comment by AJenbo** [comment]
why not replace mpqapi with libmpq?

**Comment by glebm** [comment]
libmpq can only read MPQs, not write them

**Comment by glebm** [comment]
On the other hand, smpq is available in most distros so whatever. Closing this for now unless someone actually works on this.
