### ISSUE TITLE
[Question] Wide screen loading screens

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3378]
I read the release notes from 1.3.0 and came across the description "Widescreen loading screens".
By the way there's a typo "sceens" instead of "screens".
In fact, many loading screens are already widescreen, but not all, for example the Church.
Could it be a bug or are the graphics still in progress and if so, can someone extract the graphic (PCX?) for the church and make it available by upload?

![church](https://user-images.githubusercontent.com/45902449/140071791-9c472751-3422-4b1c-8009-ddd8769fcba6.png)

**Comment by AJenbo** [comment]
There are still some that aren't widescreen yet

>  By the way there's a typo "sceens" instead of "screens".

scenes

>  are the graphics still in progress and if so, can someone extract the graphic (PCX?) for the church and make it available by upload?

yes, no cause they are still in progress, nothing to extract
