### ISSUE TITLE
Use appropriate terms for mouse/gamepad/touch

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3380]
Currently the help texts will always instruct users how to do things with mouse+keyboard, we should make the text dynamically fit the current input device.

`Right-click to read` -> `Press Y to read`

Additionally we should try and detect the controller layout to show △/Y/X for Sony/Microsoft/Nintendo layouts on gamepads.

I'm not sure how best to handle the texts for touch, maybe "Activate to read", or simply get rid of the info panel :eyes:

**Comment by glebm** [comment]
The info box is done

There is no way to toggle the help screen from a gamepad, so I guess it's fine that it's not adapted?

**Comment by daedrixxx2** [comment]
I could add that, in the given example above "press Y to read", the button doesn't currently change in the case the layout has been remapped (for instance I remapped Y to use magic, but the "read button" remained Y.

Also in the newer test builds, and in the incoming v1.5.0 I presume, the help screen can be mapped on a gamepad, so it makes sense that it (like any other on screen info like "press I for the Inventory") should also be adapted to whatever controller the game detects, right?

**Comment by AJenbo** [comment]
it would be good to have a help screen for gamepad users, but we can take that as a separate task
