### ISSUE TITLE
Android release builds contain git hash in version

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3382]
It appears that Android CMake includes the commit has despite build a release build, for 1.3.0 i had to edit the CMake files to "fix" the version number.

**Comment by StephenCWills** [comment]
Did you build the release variant in Android Studio? Seems like that uses `-DCMAKE_BUILD_TYPE=RelWithDebInfo` instead of `-DCMAKE_BUILD_TYPE=Release`.

**Comment by AJenbo** [comment]
Yeah, that was the simplest way to get it signed with my key for upload. I guess RelWithDebInfo is also why we get the nice crash dumps.
