### ISSUE TITLE
[SDL1] Scrolling text in conversations is drawn over UI

### ISSUE THREAD

**Issue by Medard22** [diasurgical/devilutionX#3388]
**Important information**
Open Dingux Beta  v2021-10-15/ 1.3.0 / downloaded from github

**Describe**
I tried the latest build on my RG-350M. When talking to NPC the scrolling text draws over all UI elements at the bottom of the screen. Parts of the text are stuck on the UI making it unreadable. Using a potion from the quick slot will refresh the UI, but the problem will return with the next conversation. It looks like some kind of  Z ordering issue. See the screenshots below, sorry for the crappy picture quality. I am not sure if it´s a common issue in all OpenDingux devices, or if it´s present only on RG-350M (this one has a 640x480 screen, while others have mostly 320x240 screen).

Before this release I was using a custom opk built from source from here: 
https://boards.dingoonity.org/ingenic-jz4760-devices/devilutionx-for-opendingux-beta/

It was posted at the end of June, and while it was buggy, this particular bug was not present in this build. So it´s most likely a regression that was introduced in the past couple of months. I can help with testing if necessary.

**Screenshots**
![01](https://user-images.githubusercontent.com/42897361/140375073-18c63be2-2533-4417-af0d-dbb2e15b1b3f.jpg)
![02](https://user-images.githubusercontent.com/42897361/140375114-7812c9a3-d5c5-4853-853b-6f04e9f95d27.jpg)

**Comment by qndel** [comment]
I'd risk saying it's present only on 640x480 because this resolution is the only one that doesn't redraw UI

**Comment by AJenbo** [comment]
There is defiantly a general issue with the SDL1 backend:
![dialog](https://user-images.githubusercontent.com/204594/140400079-40c87428-0bcd-4096-9680-b258092eb30d.gif)

**Comment by glebm** [comment]
Updated OPKs:
[devilutionx-rg350.opk.zip](https://github.com/diasurgical/devilutionX/files/7487002/devilutionx-rg350.opk.zip)
[devilutionx-retrofw.opk.zip](https://github.com/diasurgical/devilutionX/files/7487006/devilutionx-retrofw.opk.zip)
[devilutionx-lepus.opk.zip](https://github.com/diasurgical/devilutionX/files/7487009/devilutionx-lepus.opk.zip)
[devilutionx-gkd350h.opk.zip](https://github.com/diasurgical/devilutionX/files/7487012/devilutionx-gkd350h.opk.zip)

**Comment by Medard22** [comment]
Thank you for the updated packages. The bug is fixed now. There are some
minor occasional flashes of text here and there, but that seems to be
another issue. Now the game is perfectly playable. Thank you and the team
for the quick fix ^^b

**Comment by glebm** [comment]
@Medard22 The other issue is now also fixed! OPK: https://github.com/diasurgical/devilutionX/releases/download/1.3.0/devilutionx-rg350.opk

**Comment by Medard22** [comment]
Tested and it works perfectly now :) Many thanks. You are awesome!
