### ISSUE TITLE
Only 4 players in network game ?

### ISSUE THREAD

**Issue by Vitexus** [diasurgical/devilutionX#339]
There is defined constant MAX_PLRS in **defs.h** to 4 

Is possible to play with more people ?

**Comment by qndel** [comment]
set it to more than 4, get more than 4 people, find out ;)

**Comment by AJenbo** [comment]
As of fae2be813a55c1bbb57165f231236ba232a1acdb it has been possible to increase this up to 9 player:
![MMO])(https://user-images.githubusercontent.com/204594/65007176-9e92de80-d905-11e9-936d-600d072cc45e.png)

**Comment by Vitexus** [comment]
What about any widget to change number of players in network game setup ? Not anyone is able to edit & compile source.

**Comment by AJenbo** [comment]
I'm not sure yet, I think for DevilutionX 1.1.0 we will just bump it to 9, there isn't really any reason to limit it to 4 since only friends can join.

**Comment by Vitexus** [comment]
At saturday on lanparty after LinuxDays.cz the sad fifth guy was forced play only sigleplayer and watch us dying by butchers knife before he fall sleep ... :sob:

**Comment by AJenbo** [comment]
Sorry we hadn't made more of a note about this, send the guy my regards :)

**Comment by naggie** [comment]
I presume this was never changed. Will you accept a PR? :-)

**Comment by StephenCWills** [comment]
@naggie Maybe yes, but it's trickier than it seems. See #6680
