### ISSUE TITLE
Failed to open file: fonts\yellowdialog.trn

### ISSUE THREAD

**Issue by ryanccf** [diasurgical/devilutionX#3390]
**Important information**
macOS Big Sur 11.6  / DevilutionX version 1.3.0 / release

**Describe**
The program crashes upon load with the following message:
"Failed to open file:
fonts\yellowdialog.trn

File not found"

**To Reproduce**
1. download DevilutionX 1.3.0
2. Copy 'hfvoice.mpq', 'hfmusic.mpq', 'DIABDAT.MPQ', hellfire.mpq', and 'hfmonk.mpq' to the directory that devilutionx and devilutionx.mpq reside in.
3. Attempt to run DevilutionX 1.3.0

**Expected behavior**
The game should run.

**Screenshots**
<img width="376" alt="Error" src="https://user-images.githubusercontent.com/49543952/140379437-89e45886-1a39-46a4-8953-b29a6243e991.png">

**Additional context**

**Comment by StephenCWills** [comment]
`fonts\yellowdialog.trn` is loaded from devilutionx.mpq. First, make sure that you are using the latest version of that file.
https://github.com/diasurgical/devilutionx-assets/releases/download/v1/devilutionx.mpq

If you're sure you have the right version, you can run the application from the terminal with the `--verbose` command. The output should provide some insight into where the application where the MPQs were loaded from. Something like the following.

```
VERBOSE: Paths:
    base: /home/username/code/diablo/devilutionX/build/
    pref: /home/username/.local/share/diasurgical/devilution/
  config: /home/username/.local/share/diasurgical/devilution/
  assets: /home/username/code/diablo/devilutionX/build/assets/
VERBOSE: MPQ search paths:
     1. '/home/username/code/diablo/devilutionX/build/'
     2. '/home/username/.local/share/diasurgical/devilution/'
     3. '/usr/share/diasurgical/devilutionx/'
     4. '/usr/local/share/diasurgical/devilutionx/'
     5. ''
VERBOSE:   Found: devilutionx.mpq in /home/username/code/diablo/devilutionX/build/
VERBOSE: Missing: fonts.mpq
VERBOSE: Missing: DIABDAT.MPQ
VERBOSE:   Found: diabdat.mpq in /home/username/.local/share/diasurgical/devilution/
VERBOSE:   Found: hellfire.mpq in /home/username/.local/share/diasurgical/devilution/
VERBOSE:   Found: hfmonk.mpq in /home/username/.local/share/diasurgical/devilution/
VERBOSE: Missing: hfbard.mpq
VERBOSE: Missing: hfbarb.mpq
VERBOSE:   Found: hfmusic.mpq in /home/username/.local/share/diasurgical/devilution/
VERBOSE:   Found: hfvoice.mpq in /home/username/.local/share/diasurgical/devilution/
```

**Comment by ryanccf** [comment]
I had the assets in the wrong location. Thank you!
