### ISSUE TITLE
the underscore symbol (_) is a bit too high

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3391]
![image](https://user-images.githubusercontent.com/204594/140396716-efe778f9-cc6a-420a-8da3-8c19119f6628.png)

**Comment by ThomasChr** [comment]
Maybe it just defines itself as an upperscore?
Who are you to tell it otherwise?

**Comment by StephenCWills** [comment]
This is probably pretty obvious, but I used ImageMagick to split the largest font and confirmed it's simply misaligned at the source.

![image](https://user-images.githubusercontent.com/9203145/140425189-c2cde71a-86de-4e5f-b520-4aea39054614.png) ![image](https://user-images.githubusercontent.com/9203145/140424941-ab2aa843-704b-4e2b-8c5b-c368b428ddb4.png)

**Comment by StephenCWills** [comment]
This was fixed by #3537.
