### ISSUE TITLE
X error on Ubuntu 20.04

### ISSUE THREAD

**Issue by Rene2LeLorrain** [diasurgical/devilutionX#3398]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

1) O/S: `Linux 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

2) Program: v0.23 Downloaded tar file, installed from DEB. The executable is under "/usr/bin" and the data under  /usr/share/diasurgical/devilutionx/" where I copied the necessary mpq files. The desktopop file is in "~/localshare/applications" 

**Describe**

Here is what  happened when II started the game:

        rene@TRISTRAM:~/Desktop$ devilutionx --diablo
        X Error of failed request:  BadValue (integer parameter out of range for operation)
          Major opcode of failed request:  151 (GLX)
          Minor opcode of failed request:  3 (X_GLXCreateContext)
          Value in failed request:  0x0
          Serial number of failed request:  105
          Current serial number in output stream:  106
        rene@TRISTRAM:~/Desktop$ 

**Additional context**
Hardware:
CPU: Intel I7-8700k 6 cores @ 4.2Ghz
RAM: Corsair  32 GB  4000Mhz
Video: nVidia GTX-750ti from ASUS

**Comment by AJenbo** [comment]
what gpu driver?

**Comment by AJenbo** [comment]
We are also missing a version for wher ethis happened
