### ISSUE TITLE
Shareware Hellfire monk crashes game

### ISSUE THREAD

**Issue by JohnsterID** [diasurgical/devilutionX#3400]
**Important information**
Windows 7 / DevilutionX 1.3.0 release

**Describe**
Loading monk on spawn hellfire crashes the game.
Test on 1.3.0 release after reading https://github.com/diasurgical/devilutionX/issues/3217

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Single Player
2. Select Monk character
3. Play

**Expected behaviour**
Loading warrior on spawn hellfire works.

[procdump](https://github.com/diasurgical/devilutionX/files/7489927/devilutionx.exe_211106_155329.zip)

**Comment by StephenCWills** [comment]
I am unable to reproduce on Windows 10.

* Did you use devilutionx-windows-i386.zip or devilutionx-windows-x86_64.zip?
* Is this a crash-to-desktop or was there an error message?
* If there was an error message, can you share it?

---

> Testing after #3217

What does this mean? You did test the release version from https://github.com/diasurgical/devilutionX/releases/tag/1.3.0, correct?

**Comment by JohnsterID** [comment]
devilutionx-windows-x86_64.zip for release 1.3.0 used.

Crash to desktop with no error message so I attempted to use procdump.

I edited the issue to clarify why I was mentioning that previous issue. The concept sounded interesting.

Tested devilutionx-windows-i386.zip for 1.3.0 crash to desktop as well.

SYMBOL_NAME:  sdl2!SDL_DYNAPI_entry+71848
MODULE_NAME: SDL2
IMAGE_NAME:  SDL2.dll
FAILURE_BUCKET_ID:  BREAKPOINT_80000003_SDL2.dll!SDL_DYNAPI_entry

**Comment by qndel** [comment]
Can you list all mpq files your devilutionx has access to?

**Comment by JohnsterID** [comment]
spawn plus hellfire
devilutionx.mpq SHA1: 97729C97F14D81EA5897A3DD398C251F76032133
hellfire.mpq SHA1: 4852A68A70F7F55A28084281A96E95C2027C5137
hfmonk.mpq SHA1: 47F44845803B05FA243C4733995B08CBAA0DBE37
hfmusic.mpq SHA1: 5D64D26798738C503B0AA1651C1534FF5488291C
hfvoice.mpq SHA1: 04E7FE3A5509013CBF22D0937817E2775226993E
spawn.mpq SHA1: 198053225411A5B0DC28CB7EECE7E1E16E8CC4D9

**Comment by qndel** [comment]
Crashes on 
![image](https://user-images.githubusercontent.com/14297035/140607376-46367931-8b0a-44a2-b19c-b73b32f8fb67.png)

**Comment by qndel** [comment]
> spawn plus hellfire devilutionx.mpq SHA1: 97729C97F14D81EA5897A3DD398C251F76032133 hellfire.mpq SHA1: 4852A68A70F7F55A28084281A96E95C2027C5137 hfmonk.mpq SHA1: 47F44845803B05FA243C4733995B08CBAA0DBE37 hfmusic.mpq SHA1: 5D64D26798738C503B0AA1651C1534FF5488291C hfvoice.mpq SHA1: 04E7FE3A5509013CBF22D0937817E2775226993E spawn.mpq SHA1: 198053225411A5B0DC28CB7EECE7E1E16E8CC4D9

This error happens only when you have spawn.mpq + hellfire mpqs but no diabdat.mpq so as a temporary fix you can just put diabdat.mpq where devilutionx can see it

**Comment by JohnsterID** [comment]
Thanks for the detective work! Better way to report crashes in the future? Full minidump?

**Comment by qndel** [comment]
> Thanks for the detective work! Better way to report crashes in the future? Full minidump?

Actually I haven't even opened your dump, the description was enough 😅

**Comment by JohnsterID** [comment]
When you just know the content/code. Keen to follow the next bug.

**Comment by StephenCWills** [comment]
> Better way to report crashes in the future? Full minidump?

FYI, you did fine. The rule of thumb would be: the more detail the better. But usually you should need someone else to jump in and ask the right questions to get to the most relevant details so it's best to just follow the issue template as best you can.
