### ISSUE TITLE
Transparent rect rendering is slow (both stippled and blended)

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#3405]
Quest dialogues significantly affect the FPS, likely because ~~they're blitted character by character.~~
~~We can cache the lines in a circular buffer to fix this, similar to the solution we previously had for credits.~~

Update: One issue is `DrawHalfTransparentRectTo`

**Comment by AJenbo** [comment]
I noticed this as well, on RG300 FPS drops from 25 to 10. It's not to noticeable (probably in part because of the resolution, but would probably be nice to solve)

**Comment by glebm** [comment]
I also noticed FPS drops in store menus, looks like we should either improve text rendering performance or cache the lines everywhere

**Comment by glebm** [comment]
I know we shouldn't be measuring performance in debug builds, but, as a starting point

Debug build, store menu:

![image](https://user-images.githubusercontent.com/216339/140627014-2eed244d-a9e1-4993-b041-7f15bff705f3.png)

Debug build, quest dialogue:

![image](https://user-images.githubusercontent.com/216339/140627064-ed20b66b-f830-42e1-bb72-a3832344fce2.png)

From this, looks like text is not the issue and the culprit is actually `devilution::DrawHalfTransparentRectTo`

**Comment by AJenbo** [comment]
What if you set `Blended Transparency=0`?

**Comment by glebm** [comment]
It still tanks the FPS but stippled transparency is also quite expensive. Let me try with 1.2.1

**Comment by glebm** [comment]
The FPS tanks in 1.2.1 as well.

**Comment by AJenbo** [comment]
Currious, i just tested on RG300

1.3.0 blended: 10fps
1.3.0 stripped: 11fps
1.2.1 blended: 27fps
1.2.1 stripped: 29fps

**Comment by qndel** [comment]
It's really slow, even the debug command rectangle tanks my FPS 😂 one of the reasons why I made the "fps" command display no text lol

**Comment by glebm** [comment]
https://github.com/diasurgical/devilutionX/pull/3419 should improve the text rendering performance and #3413 should improve the transparent rect rendering performance.
