### ISSUE TITLE
Instructions for cross compiling for arm

### ISSUE THREAD

**Issue by JarrettR** [diasurgical/devilutionX#3410]
This is evidently possible from the platform being listed in releases. I can't find it in either the docs page on building, or in the wiki.

I currently have this:

```
wget https://zlib.net/zlib-1.2.11.tar.gz -Ozlib-1.2.11.tar.gz
tar -xzf zlib-1.2.11.tar.gz
cmake .. DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_TOOLCHAIN_FILE=../CMake/32bit.cmake -DZLIB_ROOT=/libzlib-1.2.11/ 
```

But am still running into this issue:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
M_LIBRARY
    linked by target "png" in directory /home/jarrett/Documents/linux/diablo/devilutionX/build/_deps/png-src
    linked by target "png-fix-itxt" in directory /home/jarrett/Documents/linux/diablo/devilutionX/build/_deps/png-src
```

And (for the moment) have run out of time to troubleshoot.

**Comment by AJenbo** [comment]
This is the first i hear of gnueabihf, where are you seeing it mentioned?

Have you installed libpng, what disto are you on?

**Comment by AJenbo** [comment]
Ok, looks like you are cross compiling for armhf. Yes we support armhf, but we do the compiles natively on an ARM CPU running 32bit Debian. So the scenario you trying isn't officially supported. So this isn't considered an issue, more a question.
