### ISSUE TITLE
Building without network access

### ISSUE THREAD

**Issue by jpalus** [diasurgical/devilutionX#3412]
For distribution packaged software it is desirable to do compilation in an isolated environment without network access (reproducible builds, no risk of downloading malicious code etc). In latest devilutionx version (1.3.0) that is no longer possible since ie asio must be downloaded. Therefore would it be possible to provide "full" source tarball as a part of release including all dependencies that are otherwise downloaded?

**Comment by AJenbo** [comment]
The needed dependencies depend on the target platform. If this is desirable for you I suggest having the system that downloads the code in the first place also download the dependencies before pushing it to your build server.

**Comment by StephenCWills** [comment]
> In latest devilutionx version (1.3.0) that is no longer possible since ie asio must be downloaded.

FYI, it's not necessary to download ASIO during the build process.
`cmake -DFETCHCONTENT_SOURCE_DIR_ASIO=/path/to/asio ...`

**Comment by glebm** [comment]
First, set this option:

```
-DFETCHCONTENT_FULLY_DISCONNECTED=ON
```

This will make sure none of the FetchContent calls do any network access.

You can then specify every dependency similar to how it is done here:

https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/ports/devilutionx/devilutionx.mk

**Comment by jpalus** [comment]
While I'm interested in particular platform it does not change the fact that I believe all sources which cannot be satisfied by system library should be included in source release. So I wouldn't mind including SDL2 in a source tarball because Android needs it. Not up to me though. Thanks for the tips with FETCHCONTENT_* vars -- I will start maintaining dependencies manually.

**Comment by AJenbo** [comment]
Including them in git will affect performance during development, if you develop a script for generating a full tarball you are welcome to open a PR with it. It's worth noting that we do checksum validation on dependencies so reproducible builds are assured as the build will fail if they change.

**Comment by glebm** [comment]
@jpalus DevilutionX now provides a full source tarball that includes all fetchcontent deps and devilutionx.mpq.
This makes packaging it a lot easier, e.g. https://github.com/batocera-linux/batocera.linux/pull/5146
