### ISSUE TITLE
armhf version problem

### ISSUE THREAD

**Issue by cjv123** [diasurgical/devilutionX#3417]
I installed the armhf version, the language is switched to Chinese, the expansion piece Hellfire, it becomes very stuck when there is magma

**Comment by qndel** [comment]
what magma?
what does very stuck mean? ...

**Comment by sunydo** [comment]
is FPS Very low

**Comment by sunydo** [comment]
Near the tenth floor underground

**Comment by qndel** [comment]
I can't do anything with info like this. For me I actually get more fps on areas with a lot of lava.
Does it lag only with chinese language?
You can show fps in config, how does fps change when "it's very low"?

**Comment by glebm** [comment]
@sunydo Can you please attach a save file?

**Comment by AJenbo** [comment]
> Near the tenth floor underground

Where you reading the story book at the time?

**Comment by sunydo** [comment]
[save.zip](https://github.com/diasurgical/devilutionX/files/7501765/save.zip)
hellfire save file

**Comment by AJenbo** [comment]
@sunydo what device, try turning `color cycling` off to see if it makes a difference.

**Comment by sunydo** [comment]
@AJenbo  
Oh, that's cool！
try turning color cycling off  
the game get back to normal
FPS is ok！everything is ok！
I use Nintendo switch and odroid go advance
Thank you very much！

**Comment by AJenbo** [comment]
That option is there for computers that where slow in 1997 :D I had been thinking of removing it, I guess we won't :)

**Comment by AJenbo** [comment]
> For me I actually get more fps on areas with a lot of lava.

Probably because a lot of tiles are full bright and do not have to be color adjusted when rendered.
