### ISSUE TITLE
Valor book looks poo

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3420]
![image](https://user-images.githubusercontent.com/14297035/140643151-d0e1ba87-ebf6-43c5-ad34-2765084bae4c.png)
These two dots in new line look disgusting :)

**Comment by glebm** [comment]
Oh we should probably tweak line breaking to not split there. Please attach a save so I can test

**Comment by qndel** [comment]
[single_4.zip](https://github.com/diasurgical/devilutionX/files/7492178/single_4.zip)

**Comment by AJenbo** [comment]
> Oh we should probably tweak line breaking to not split there. Please attach a save so I can test

It's also an issue for something like `github.com` being split when viewing the support text.

**Comment by glebm** [comment]
The github.com case will be easy to fix once #3425 is merged

**Comment by AJenbo** [comment]
I'm not sure if it would ever be valid to line break after `,`/`.` that isn't followed by a space, so maybe they shouldn't be in the list of valid chars to break after?

**Comment by AJenbo** [comment]
> ![image](https://user-images.githubusercontent.com/14297035/140643151-d0e1ba87-ebf6-43c5-ad34-2765084bae4c.png) These two dots in new line look disgusting :)

The proper fix would be to use an ellipsis `…` :thinking:
