### ISSUE TITLE
Broken bloodstone in valor quest

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3422]
Save got created with 1.3.0 but I'm not sure if I haven't transferred it to vanilla a few times - was testing constricting ring after all.
Warped to dlvl 5 and found valor book - there's a bloodstone next to it that I can't pick up, after picking next ones up, the final one and the one near book morphed into unpickable piles of gold.
https://github.com/diasurgical/devilutionX/files/7492178/single_4.zip

**Comment by Chance4us** [comment]
> Save got created with 1.3.0 but I'm not sure if I haven't transferred it to vanilla a few times - was testing constricting ring after all. Warped to dlvl 5 and found valor book - there's a bloodstone next to it that I can't pick up, after picking next ones up, the final one and the one near book morphed into unpickable piles of gold. https://github.com/diasurgical/devilutionX/files/7492178/single_4.zip

I noticed that the quest "Anvil of Fury" doesn't work with the savegame that you made available in https://github.com/diasurgical/devilutionX/issues/3376. I just brought the "Anvil of Fury" to the Griswold without receivin the quest before, but he doesn't make a sword with it. I suspect that there must be a general problem with the savegame.
Have you possibly used a trainer to insert the consticting ring? Could the trainer have damaged the savegame?

**Comment by qndel** [comment]
No, I used "dropu constricting" debug command

**Comment by AJenbo** [comment]
> I noticed that the quest "Anvil of Fury" doesn't work with the savegame that you made available in #3376. I just brought the "Anvil of Fury" to the Griswold without receiving the quest before, but he doesn't make a sword with it. I suspect that there must be a general problem with the savegame.

You need to complete all previous Griswold quests before he will accept it.

**Comment by AJenbo** [comment]
Works perfectly fine at this point.
