### ISSUE TITLE
/assets/ folder doesn't get copied to build folder

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3424]
Refs https://github.com/diasurgical/devilutionX/issues/3423

I've just deleted my build folder and opened CMakeLists.txt
The game doesn't run because there's no assets folder for it to load stuff from.
Windows 10/Visual studio

Looks like this doesn't work anymore.
```cpp
# Copy assets to the build assets subdirectory. This serves two purposes:
# - If smpq is installed, devilutionx.mpq is built from these files.
# - If smpq is not installed, the game will load the assets directly from this directoy.
foreach(asset_file ${devilutionx_assets})
  set(src "${CMAKE_CURRENT_SOURCE_DIR}/Packaging/resources/assets/${asset_file}")
  set(dst "${CMAKE_CURRENT_BINARY_DIR}/assets/${asset_file}")
  list(APPEND DEVILUTIONX_MPQ_FILES ${asset_file})
  list(APPEND DEVILUTIONX_OUTPUT_ASSETS_FILES ${dst})
  add_custom_command(
    COMMENT "Copying ${asset_file}"
    OUTPUT "${dst}"
    DEPENDS "${src}"
    COMMAND ${CMAKE_COMMAND} -E copy "${src}" "${dst}"
    VERBATIM)
endforeach()
```

**Comment by qndel** [comment]
@glebm I think https://github.com/diasurgical/devilutionX/commit/5e675dcd6a194791572ddc74c33c43e9b77ef3b6 broke it as my assets folder has a creation date before it

**Comment by glebm** [comment]
The creation date of the **folder** doesn't matter. I can't reproduce this on Linux

**Comment by qndel** [comment]
Yes but it indicates when it worked for me :P

**Comment by glebm** [comment]
Are there spaces in your directory path?

**Comment by qndel** [comment]
no

**Comment by glebm** [comment]
It's something else Windows-specific then but I have no idea what so far

**Comment by qndel** [comment]
```cpp
foreach(asset_file ${devilutionx_assets})
  set(src "${CMAKE_CURRENT_SOURCE_DIR}/Packaging/resources/assets/${asset_file}")
  set(dst "${CMAKE_CURRENT_BINARY_DIR}/assets/${asset_file}")
  list(APPEND DEVILUTIONX_MPQ_FILES ${asset_file})
  list(APPEND DEVILUTIONX_OUTPUT_ASSETS_FILES ${dst})
  message("COPYING:  ${asset_file}")
  message("SRC: ${src}")
  message("DST: ${dst}")
  ```
  
  1> [CMake] COPYING:  ui_art/supportw.pcx
1> [CMake] SRC: H:/Diablo/devilutionX/Packaging/resources/assets/ui_art/supportw.pcx
1> [CMake] DST: H:/Diablo/devilutionX/build/x64-Debug/assets/ui_art/supportw.pcx

Even manually creating /assets/ folder didn't do anything so I guess the copying command doesn't work

**Comment by glebm** [comment]
Well that by itself doesn't do any copying, it's only when the custom command is triggered that the actual copy happens. This happens at build time, not at configure time.

**Comment by qndel** [comment]
where is the custom command triggered?

**Comment by glebm** [comment]
It's triggered because it's a dependency of the custom target here:

https://github.com/diasurgical/devilutionX/blob/53f89fb9d94606fbd3f6cbfa34ea5ff0b300a880/CMakeLists.txt#L851

The custom target is an `ALL` target so it gets built whenever the project is rebuilt.

**Comment by qndel** [comment]
Looks like it does when doing "Rebuild" in VS so I'll just blame VS for being shit.
