### ISSUE TITLE
`WordWrapString` calls `remove_prefix` with negative value

### ISSUE THREAD

**Issue by obligaron** [diasurgical/devilutionX#3433]
**Important information**
Windows 10
current master at b7beb2fb x64 debug build

**Describe**
`WordWrapString` crashes/asserts in debug build.

> 	devilutionx.exe!std::basic_string_view<char,std::char_traits<char>>::remove_prefix(const unsigned __int64 _Count) Line 1389	C++
	devilutionx.exe!devilution::WordWrapString(std::basic_string_view<char,std::char_traits<char>> text, unsigned __int64 width, devilution::GameFontTables size, int spacing) Line 319	C++
 	devilutionx.exe!devilution::`anonymous namespace'::CreditsRenderer::CreditsRenderer(const char * const * text, unsigned __int64 textLines) Line 46	C++
 	devilutionx.exe!devilution::`anonymous namespace'::TextDialog(const char * const * text, unsigned __int64 textLines) Line 131	C++
 	devilutionx.exe!devilution::UiCreditsDialog() Line 172	C++

`remaining.remove_prefix(lastBreakablePos + lastBreakableLen - (remaining.data() - begin));` evaluates to `-4` and the cast to `size_t` get us to `18446744073709551612`.

**To Reproduce**
1. Start Diablo or Hellfire
2. Click on `Show Credits`
3. See error

**Expected behavior**
No exception / error.

**Additional context**
Occurs since 8e5bc059
Doesn't crash in release build, cause no checks are run (undefined behavior ?)

**Comment by qndel** [comment]
I'm getting a crash when loading a save too, 
![image](https://user-images.githubusercontent.com/14297035/140661089-626d0ec0-1bb1-49ba-8322-06d5335b9338.png)
