### ISSUE TITLE
Black screen on Nintendo 2DS

### ISSUE THREAD

**Issue by 3F2A8C4AE9** [diasurgical/devilutionX#3444]
**Important information**
This was using the provided download from the Releases page, v1.3.0. I used the .cia version to install the app onto my 2DS. I originally tried this on a 2DS that was not fully up to date system-wise, but updating it had no impact on performance.

**Describe**
When you start the app, you can hear the audio of the Blizzard logo and if you interact with the game, you can hear the menu and the Tristram music and your character's footsteps/etc. But there is simply no video output regardless of settings in the diablo.ini file. 

The game screen does appear when you have to name your character, but it disappears again once you're finished. When you hit the Home button, you then can see the screen as it pulls away, but it disappears when you close the Home Menu once more. Putting the system to sleep will also show the game screen for a split second when waking. 

As I had a spare system lying around, I installed it the same way onto an Old 3DS, and the game works as expected. 

**To Reproduce**
1.) Install the game as a .cia through FBI onto a non-New 2DS. 
2.) Edit diablo.ini to disable the Hellfire intro (issue #3445).
3.) Attempt to open the game. 
4.) Experience black screen, but still can interact with the game. 

**Expected behavior**
The expected behavior is for the game to display anything on the top screen. 

**Screenshots**
The amusing thing is that even with the black screen, taking screenshots through Luma works as expected. Screenshots show the game screen in full despite nothing showing on the screen during play. 

**Additional context**
I've nothing further to add.

**Comment by StephenCWills** [comment]
I wonder if this has something to do with shutting the code to shut the backlight off on the bottom screen.

https://github.com/diasurgical/devilutionX/blob/69e7e7bc0d25ff1b294582bf5836318fad610977/Source/platform/ctr/system.cpp#L77-L78

**Comment by StephenCWills** [comment]
@3F2A8C4AE9 Can you please test this build to see if it works better?
https://70551-143324737-gh.circle-artifacts.com/0/devilutionx.cia

**Comment by 3F2A8C4AE9** [comment]
> 
> 
> @3F2A8C4AE9 Can you please test this build to see if it works better? https://70551-143324737-gh.circle-artifacts.com/0/devilutionx.cia

Hey, sorry it took me a while to get back.  I gave this new version a spin. 

With diablo.ini set to disable both Intros and with resolution set to 800x480, it boots and displays on the top screen! I got as far as the title, making a character, diving into Level 1 and making a couple of kills, but I can confirm that the screen displays normally, and it keeps working after putting the system into sleep mode and after pressing Home and returning from the Home Menu. 

I also tested it on 640x480 resolution, and also with Fit To Screen set to 0 too. Everything seems to work as expected now!

**Comment by StephenCWills** [comment]
That's great news! Thanks for testing. I'd like to do a bit more research before submitting a fix to master so I'll be leaving this issue open. That build is up to date with the 1.3 branch so it should be good for playing on 2DS in the meantime.

**Comment by jimmiejoe** [comment]
I just downloaded the app via universal-updater. I am have this same issue with no video on a 2DS model:FTR-001. I saw there was a branch to address this, but it is no longer active. How do you not disable the backlight? The current .cia I just downloaded from here also has the same issue with no video. I tried changing the resolution from 800 to 640, but that did not help. I looked at #3477, but I do not see a solution there either. I have GBC, GBA, DS Lite, o3DS, n3DS XL, o2DS, N64, Gamecube, Wii, WiiU hardware so if you need to test something I can do that. I just do not see the solution for this closed issue.

**Comment by AJenbo** [comment]
Can you please link to the exact thing you downloaded.

**Comment by jimmiejoe** [comment]
https://github.com/diasurgical/devilutionX/releases/download/1.3.0/devilutionx-3ds.cia

**Comment by jimmiejoe** [comment]
I will download it again and install it again with FBI just to make sure.

**Comment by AJenbo** [comment]
The 1.3.0 release is not compatible with 2DS. The current test build is known to be unstable since there is a bug in the current SDL port and it must be build manually to avoid this. 1.4.0 should be compatible with 2DS, I'm not sure if we still have an available test build for it.

**Comment by jimmiejoe** [comment]
Is there a timeline for the 1.4.0 to be released? Where would I get the 1.4.0 to test?

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/milestone/7

**Comment by jimmiejoe** [comment]
Download and install the circleci 3ds (85914) and the graphics now work on the 2DS, but the intro stutters.
