### ISSUE TITLE
Berserked monsters won't target each other

### ISSUE THREAD

**Issue by SoundChaser83** [diasurgical/devilutionX#3451]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
1.3.0

**Describe**
Berserked monsters never seem to want to target each other despite this being a mechanic that exists in vanilla Hellfire. I'm not sure if this is related or not, but non-Berserked Hellfire monsters also seem to never shoot projectiles at Berserked monsters (this _does_ seem to be vanilla behavior, though). This means that you can Berserk a Spider Lord and have it seek out and kill a bunch of Necromorbs without them fighting back at all.

**To Reproduce**
1. Berserk two or more monsters
2. Clear out any non-Berserked monsters
3. Observe that your Berserked monsters won't attack each other even if you bunch them right up next to each other

**Expected behavior**
Berserked monsters should be disposed to attack the nearest creature even if they are also Berserked. Projectile shooting monsters, whether Berserked or not, should also be disposed to attack nearby Berserked creatures.

**Comment by qndel** [comment]
Bisected to 202ac36a5209eef2ced8953fb525f2ded29211c9
