### ISSUE TITLE
"Resist lightning" wrong wordwrap

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3456]
Dear friends, commit e9a9daa7947c3fb4a655a38e73037f51dd97e7b5 caused a wordwrap in "resist lightning".
![resistlightning](https://user-images.githubusercontent.com/45902449/141010280-7d25b1c6-037f-4002-9a21-2601f2c6debc.png)

**Comment by glebm** [comment]
`WordWrap` wraps the string correctly (with the fix from #3457), so the problem is elsewhere, likely in `RenderText`

**Comment by Chance4us** [comment]
> `WordWrap` wraps the string correctly (with the fix from #3457), so the problem is elsewhere, perhaps in `RenderText` or `GetLineWidth`

Yes, i saw it was just a side effect. So thanks a lot for solving the other issues.
