### ISSUE TITLE
DevilutionX hellfire dungeon layout changed in original hellfire

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3465]
Hellfire cathedral dungeon layout changed after loading devilutionx save in original hellfire
[devilution.zip](https://github.com/diasurgical/devilutionX/files/7510840/devilution.zip)

Attaching hsv and sv versions of the same save - hellfire save was the one I created first, sv got converted from it - dungeon layout didn't change in vanilla. For hellfire save it did.

**Comment by AJenbo** [comment]
It sounds like we are creating Diablo levels by default despite running Hellfire

**Comment by qndel** [comment]
Turns out my save must've originally been a diablo one and had `pOriginalCathedral` true
While devilutionx offers the ability to convert saves freely between diablo and hellfire, the original didn't, which means that after loading the same save in original diablo and original hellfire, one of these will always have a morphing cathedral layout and there's nothing we can do about it.
