### ISSUE TITLE
1.3.0 wont start on N3DS

### ISSUE THREAD

**Issue by PabbaShabba25** [diasurgical/devilutionX#3471]
N3DS, luma is updated, dsp is dumped and Im on the newest version of devilutionX 

It wont open beyond a failed  screen stating" Failed to open file :fonts\yellowdialog.trn
file not found "

Im not sure how to reproduce, the ver before worked great.   Try downloading it on new3ds xl and see if it happens to you :o     I am using the GOG version if that helps

Failed message screen

maybe its l2 being turned on?  I have no idea, im new to this scene.  thank you guys for your amazing project!

**Comment by AJenbo** [comment]
Delete the old devilutionx.mpq

**Comment by PabbaShabba25** [comment]
Fixed my issue.   Thanks for your time!
