### ISSUE TITLE
Weird death animation after getting killed by a barrel

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#3473]
**Important information**
Linux / c15123688ab179afb147a736324c36ed8fe7d785, also reproducible with the official release binary

**Describe**
After getting killed by an exploding barrel, the character briefly flashes standing upright.

**To Reproduce**
1. Load attached save
2. Try to get killed by a barrel. The two at the ends of the C-shaped arrangement are explosive.
3. If you didn't die, load and try again.

**Expected behavior**
Once down, the character should stay down.

**Additional context**
[single_2.zip](https://github.com/diasurgical/devilutionX/files/7515500/single_2.zip)

This doesn't happen if you get killed by a monster.

**Comment by qndel** [comment]
player.AnimInfo.GetFrameToUseForRendering() for some reason returns frame #1 in the middle of rendering last death frame
Probably somehow related to getting attack animation interrupted by death?

**Comment by qndel** [comment]
![funnydeath](https://user-images.githubusercontent.com/14297035/141193222-c7d43ec6-0e93-4912-a9cd-2974dd2bcbb8.gif)

**Comment by julealgon** [comment]
@qndel does it repro if you are interrupted and killed by a monster as well? Or conversely, if you are killed by a barrel that was broken by a different player?

**Comment by qndel** [comment]
> @qndel does it repro if you are interrupted and killed by a monster as well? Or conversely, if you are killed by a barrel that was broken by a different player?

No, only when you destroy a barrel, it's caused by the death happening in ProcessPlayers in DoAttack, the animation manages to get 1 frame further than usual because of that and the game attempts to loop it.
