### ISSUE TITLE
Import character from single player/multiplayer

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#3474]
It would be nice to be able to import your characters from single player to multiplayer and vice-versa.

UI-wise, I would envision a new menu entry under "New hero" called "Import hero".

**Comment by AJenbo** [comment]
What where you thinking should happen to the hero's equipment?

**Comment by vlolteanu** [comment]
It should stay the same.

I take it the item seeds produce different items for single player and multiplayer?

**Comment by AJenbo** [comment]
> I take it the item seeds produce different items for single player and multiplayer?

Yeah, so that's why I'm curious what your thoughts where regarding how to handle that :) Hellfire just simply stripped all items from the hero when converting from vanilla to Hellfire.

**Comment by vlolteanu** [comment]
Unless there's an easy way of converting them (i.e. not brute-force), I see little point in this proposal.

**Comment by AJenbo** [comment]
Nothing short of adding support for single player items in multiplayer (and vice versa), and saves that go threw this process will no longer be backwards compatible with vanilla.

**Comment by julealgon** [comment]
> ...and saves that go threw this process will no longer be backwards compatible with vanilla.

What if DevilutionX introduced a third type of save, that is neither vanilla SP nor vanilla MP, but a new unified mode, where characters can be migrated _to_ but not _from_? Have you considered something like this?

**Comment by vlolteanu** [comment]
> > ...and saves that go threw this process will no longer be backwards compatible with vanilla.
> 
> What if DevilutionX introduced a third type of save, that is neither vanilla SP nor vanilla MP, but a new unified mode, where characters can be migrated _to_ but not _from_? Have you considered something like this?

With https://github.com/diasurgical/devilutionX/pull/2930 on the horizon, this might be the prudent approach.

**Comment by AJenbo** [comment]
We would need to rewrite how multiplayer works then. And it would make it harder to verify if some issue is vanilla or not

**Comment by julealgon** [comment]
> And it would make it harder to verify if some issue is vanilla or not

Why is this aspect important? Shouldn't any issue be evaluated by its own merits and potentially fixed anyways?

**Comment by AJenbo** [comment]
It affects how critical it is. Figure out what solution should be applied. How to document the change. And sometimes figure out if something is an issue at all or just miss remembering hot things worked originally.
