### ISSUE TITLE
Quick-loading via F3 keeps towner menu/store open

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#3476]
**Important information**
Linux / 1.3 official build

**Describe**
Quick-loading via F3 keeps towner dialogue/store open. The menu is still functional.

**To Reproduce**
1. Start single player game
2. Save game anywhere
3. Go to town and click someone; optionally open the store or talk to them
4. Hit F3

**Expected behavior**
The menu/store/dialogue should be gone.

**Screenshots**
![screen08](https://user-images.githubusercontent.com/3142367/141377488-f30fcfa0-bf53-406e-a37a-4f1e0f834fa6.png)
![screen06](https://user-images.githubusercontent.com/3142367/141377533-968082e9-2518-44ad-a77f-aca27ac9d74f.png)

**Comment by StephenCWills** [comment]
> The menu/store/dialogue should be gone.

Perhaps better yet, don't allow quick load while in menus.
