### ISSUE TITLE
Drop gold beyond reach

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3481]
Commit 335b0b934922172fb60779749e4e27b864c3d45f caused the following side effect.
Savegame:
[gold_test.zip](https://github.com/diasurgical/devilutionX/files/7529446/gold_test.zip)

https://user-images.githubusercontent.com/45902449/141511170-d100e925-c6ae-46ed-a5b7-837d686daf66.mp4

It is also possible that the behavior also applies at dropping items.
Desired behavior: vanilla 3x3 piles

**Comment by qndel** [comment]
Actually isn't this an improvement over original mechanic?

**Comment by Chance4us** [comment]
> Actually isn't this an improvement over original mechanic? I've been testing spawning a lot of rings recently and I like it : P (Try dropping 40 rings from inv ...)

If it doesn't have any other undesired effects and you like it, you can leave it that way. It didn't bother me, I just noticed the difference and wondered about it.

**Comment by SourceCodeDeleted** [comment]
I actually might use this

**Comment by ephphatha** [comment]
This was the intent of the original code as far as I can tell, but a side effect of the way it searched for free spaces meant that it dropped items at your feet before going more than one tile away.

The drop logic is:
1. Try drop in the neighbouring tiles towards the mouse cursor
2. Check if the player character is standing on an item
3. If not, try drop an item in the closest free space within 50 tiles.

The search code for step 3 is what changed. Previously it would drop an item at your feet before it got further than 1 tile away. Then step 2 would stop you dropping more items. Now the search code excludes the current tile, but you can still manually drop an item at your feet and you'll not be able to drop more items.

**Comment by qndel** [comment]
That's fkin weird xD

**Comment by ephphatha** [comment]
> Desired behavior: vanilla 3x3 piles

For reference, I took a video of the vanilla behaviour:

https://user-images.githubusercontent.com/357684/141645105-e4015750-fcee-422d-b138-6ee9306edc8b.mp4

Clicking in the same direction drops somewhere between 5-8 (but never 9) items depending on your chosen direction. Exactly 3 items if you're standing on an item when you start dropping more (assuming all other tiles are free 😄 ).

**Comment by FitzRoyX** [comment]
The only issue with the first video is that it goes 3 tiles away before filling the south and north tiles that are only 2 tiles away. The cursor-directed dropping is great.

**Comment by Chance4us** [comment]
@qndel, @AJenbo
I have now tested the new behavior (335b0b9) over a longer period of time.
Due to the unpredictable dropping position, IMO the new logic is worse than vanilla, even if you can drop more items.
Unless the positioning could be made more logical and predictable. So the items should drop either in the north / east / west / south on the side of the mouse pointer direction.

**Comment by ephphatha** [comment]
I've opened #3530 to restrict item dropping to neighbouring tiles (using an unrolled loop to make the drop pattern more consistent). I do prefer the flood fill approach that qndel's PR uses since this appears to be the intent of the original code. The original logic is broken and it was lucky that it happened to be broken in a way that prevented the other issues coming to light 😂

**Comment by Chance4us** [comment]
I can live well with both approaches, it's just up to your decision which approach should be merged, friends.

**Comment by Chance4us** [comment]
@AJenbo I think this one issue can be closed as an improvement has already taken place.
