### ISSUE TITLE
Feature request: remove hardcoding from button assignments for functions in Help screen

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#3483]
Right now, button assignments in Help screen are hardcoded text, but since #1368 we allow remapping most of these keys in `diablo.ini`

It will be a nice feature to pull button assignments from `diablo.ini` or `Keymapper` class
![screen09](https://user-images.githubusercontent.com/4958520/141642906-c51fd169-28da-4b8c-92a7-6b76dcef1a66.png)

**Comment by AJenbo** [comment]
Duplicate of https://github.com/diasurgical/devilutionX/issues/3380
