### ISSUE TITLE
Gold pokes through trees in town

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3484]
![image](https://user-images.githubusercontent.com/14297035/141643177-0b9f0527-20a3-46a9-86d4-915b0d5c8977.png)

**Comment by nickgavran** [comment]
The gold isnt poking through the trees, the gold is behind it. The leaves have gaps in them, showing the gold underneath.

**Comment by qndel** [comment]
> The gold isnt poking through the trees, the gold is behind it. The leaves have gaps in them, showing the gold underneath.

I don't mean leaves, look at the trunk

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/141643309-1284c885-3c59-4fd1-93a6-558a1f357cbf.png)

**Comment by agris-codes** [comment]
Gold does this with the small rock in front of Peppin’s hut as well.

**Comment by AJenbo** [comment]
How does this compare to vanilla...

**Comment by qndel** [comment]
> How does this compare to vanilla...

![image](https://user-images.githubusercontent.com/14297035/141650411-31b7b1c1-a824-4c4d-a574-a8bbe32ed39e.png)
XD

**Comment by AJenbo** [comment]
The issue here is that the tree sprites do not have any pixels in that area, the part the you see otherwise is painted on the ground. Solving it is way more work then it's worth.
