### ISSUE TITLE
No mouse cursor in AppImage version

### ISSUE THREAD

**Issue by laenion** [diasurgical/devilutionX#3488]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

Linux (Slackware64 current) / 1.3.0 / download from https://github.com/diasurgical/devilutionX/releases/tag/1.3.0

**Describe**

Using the AppImage version, the game cursor is not visible, neither in the menu nor ingame.

When using the _tar.xz_ version instead (and after extracting the _devilutionx.mpq_ from the included RPM, as it's not available in the archive directly), the cursor is shown as expected.

**To Reproduce**
1. Download AppImage file
2. Go to directory containing _diabdat.mpq_
3. Execute AppImage file

**Expected behavior**

The cursor should be visible.

**Screenshots**

**Additional context**

**Comment by AJenbo** [comment]
The appimage contains and older version of SDL that does not support hardware cursors. If you have previously run the game from a different build that supports hardware cursors and ended up with it enabled in your ini then you will experience this issue when running the appimage.

**Comment by jpalus** [comment]
Self build of 1.3.0 linked to SDL 2.0.16 on Linux arm64 (rk3399):
- no cursor under wayland
- cursor flickers under X11

Both work perfectly fine in 1.2.1. @AJenbo any clues what might be wrong?

**Comment by qndel** [comment]
Nothing is wrong, 1.2.1 didn't have hardware cursor, if it doesn't work for you, just disable it in ini
Hardware Cursor=0

**Comment by jpalus** [comment]
Thanks. Works fine with `Hardware Cursor=0`.

**Comment by AJenbo** [comment]
> clues what might be wrong?

X11: Your GPU driver is having issues with displaying large cursors. 
Wayland: The security model is to strict to do anything sensible.
