### ISSUE TITLE
Fullscreen and Upscaling not working on AMD Ryzen-3-2200G

### ISSUE THREAD

**Issue by smeagal64** [diasurgical/devilutionX#351]
**Fullscreen and Upscaling not working**
Fullscreen and Upscaling not working on my brothers pc using Kubuntu 18.04 and AMD Ryzen-3-2200G (my nvidia works fine).

**Config**
Setting fullscreen=1 in config screenshot :
![Fullscreen](https://user-images.githubusercontent.com/55181392/66596138-a0665f80-eb9c-11e9-9423-c35fd292bf52.png)
The image stays small and completely in the left upper corner of the screen.

Setting upscale and trying to resize the window:
![upscaling](https://user-images.githubusercontent.com/55181392/66596272-e02d4700-eb9c-11e9-87b5-599e9b9034f5.png)
The content of the window never gets redrawn. However the music is still audible in the background. So most likely the game did not crash, but the video gets no refresh.

For the moment my brother is stuck with the orginigal 640x480 res :-)

**Comment by glebm** [comment]
Probably a drivers issue; does it work with 19.10 beta? Any errors in the console?

**Comment by AJenbo** [comment]
What GPU, what driver

**Comment by smeagal64** [comment]
The GPU is the built-in from the AMD Ryzen 3 2200G, it is called Radeon Vega 8 Graphics.
Here is a link to the CPU Specs: [https://www.amd.com/en/products/apu/amd-ryzen-3-2200g](url)
The OS is kubuntu 18.04, and with the default installed open source driver fullscreen/upscale did not work.
Thats why i added the oibaf ppa [https://linuxconfig.org/how-to-install-the-latest-amd-radeon-drivers-on-ubuntu-18-04-bionic-beaver-linux](url) to get the newest driver available.
Sadly this did not change anything.
Just to be on the safe side we tried "Warzone 2100", both fullscreen and window mode, that worked fine.

**Comment by Chance4us** [comment]
Same hardware and same issue already told about it:

Black screen when using upscale=0 option #112
https://github.com/diasurgical/devilutionX/issues/112

Reporting the error is completely superfluous.
It'll end up blaming your hardware or driver anyway.
You will probably need to hack by yourself.

**Comment by AJenbo** [comment]
@Chance4us I'm sorry you feel this way, but we do take issues seriously. But we need to get enough infromation to repoduce the issue or find a reference in the documentation there isn't anything we can. Also, you never replied about whether your system is capable of switching to 640x480 or not?

**Comment by AJenbo** [comment]
@smeagal64 your links all pointed to github :)
Could you possibly provide us with the PCI-ID of the GPU `(lspci -nn | grep -i vga)`

Could you try another game that makes use of SDL2.

Please start the game via the terminal and show us the log (@Chance4us if you can do this also that would be helpful)

**Comment by glebm** [comment]
Also there were some changes to the upscale renderer setup since the last release. Perhaps building from master resolves the issue?

**Comment by AJenbo** [comment]
P.s. what SDL2 version do you have installed

**Comment by Chance4us** [comment]
@AJenbo thank you for your patience with me.
I attached a report.
[Report.txt](https://github.com/diasurgical/devilutionX/files/3720999/Report.txt)

**Comment by Chance4us** [comment]
Some of the picture.
![1](https://user-images.githubusercontent.com/45902449/66705772-5fe91c00-ed2b-11e9-899d-b0d87fb1996a.png)

**Comment by Chance4us** [comment]
And a very different thing.
![2](https://user-images.githubusercontent.com/45902449/66705802-a9d20200-ed2b-11e9-809d-85e69f8ee36d.png)

**Comment by glebm** [comment]
Is this master or 0.5?

**Comment by Chance4us** [comment]
![sdl](https://user-images.githubusercontent.com/45902449/66705824-edc50700-ed2b-11e9-95ad-c39c3552d045.png)

**Comment by Chance4us** [comment]
@glebm It is just -> git clone https://github.com/diasurgical/devilutionX

commit 356e276b0a8c354e37ac3d3c9a1c929cf5a6559f (HEAD -> master, origin/master, origin/HEAD)

**Comment by Chance4us** [comment]
The only thing that helps against the black screen is to not disable the renderer in any case.
Of course, it could be a hardware specific thing.

**Comment by AJenbo** [comment]
Doing so may very well not work for systems that don't have hardware acceleration.

It looks like this happens because the window surface has been marked as invalid:
https://github.com/spurious/SDL-mirror/blob/master/src/video/SDL_video.c#L2351

This happens when resizing the window, but we don't allow for that when upscaling is disabled.
https://github.com/spurious/SDL-mirror/blob/master/src/video/SDL_video.c#L2599

It also appears to happen in some cases for EGL and GL drivers where it can decide to recreate the window:
https://github.com/spurious/SDL-mirror/blob/53385fcc1afd96735e6eccd2c11835388829a044/src/video/SDL_video.c#L1642

This could maybe be solved by listening for the right even and then calling SDL_GetWindowSurface() to update our reference to the window.

**Comment by AJenbo** [comment]
Your suggestion doesn't really make sense to me. If you simply change:
```
	if (upscale) {
		renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED);
```
to
```
		renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED);
	if (upscale) {
```
then this will break rendering for systems that do not have hardware acceleration.
Doing the following might work, but doesn't really make sense:
```
	SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED);
	if (upscale) {
		renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED);
```

Could you try the latest master (https://github.com/diasurgical/devilutionX/commit/a8e4db538f0e3cbd7cd1a89e68cfe222ca596bb7). It should give us a better idea about where in the process this issue occurs, and it looks nicer :)

**Comment by glebm** [comment]
Does #358 fix the issue for you?

**Comment by Chance4us** [comment]
For commit 263ab2bb484bac2e42290f4b2002f821741d9144 (HEAD -> master, origin/master, origin/HEAD)
Attached 3 logs. First is crash when missing CharisSILB.ttf

**Comment by Chance4us** [comment]
[missing_font.txt](https://github.com/diasurgical/devilutionX/files/3721548/missing_font.txt)

**Comment by Chance4us** [comment]
[Crash1.txt](https://github.com/diasurgical/devilutionX/files/3721549/Crash1.txt)

**Comment by Chance4us** [comment]
[Crash2.txt](https://github.com/diasurgical/devilutionX/files/3721550/Crash2.txt)

**Comment by Chance4us** [comment]
I don't know how to clone #358. So additional instructions are needed.

**Comment by glebm** [comment]
```
git remote add glebm git@github.com:glebm/devilutionX.git
git checkout glebm/window-surface
```

**Comment by glebm** [comment]
> First is crash when missing CharisSILB.ttf

While it shouldn't crash, you do need to place `CharisSILB.ttf` in the same folder as the binary.

**Comment by Chance4us** [comment]
I was not able to do:
git remote add glebm https://github.com/glebm/devilutionX.git
git checkout glebm/window-surface

So I did:
git clone https://github.com/glebm/devilutionX -b window-surface

**Comment by Chance4us** [comment]
The black screen is gone.

**Comment by Chance4us** [comment]
There are still some leaks.
I do not know if it has anything to do with the issue.
The log is attached.
[Leaks.txt](https://github.com/diasurgical/devilutionX/files/3721644/Leaks.txt)

**Comment by AJenbo** [comment]
@Chance4us leaks can com from system liberies

**Comment by AJenbo** [comment]
@smeagal64 please confirm the change has also solve your issue, since @Chance4us seamed to indicate that he was getting a black screen and you appeared to be getting a an image that just wasn't scaling. If you need a prebuild binery you can get it from the nightly build server:
https://3127-143324737-gh.circle-artifacts.com/0/devilutionx_linux_x86_64

**Comment by smeagal64** [comment]
Great news - my brother tried your nightly build and it seems to work.
Thanks you for fixing this.

**Comment by AJenbo** [comment]
Glad this mystery was solved. Also thanks you @glebm for doing the fix.
