### ISSUE TITLE
Southernmost pillar near Chamber of Bone entrance not drawn on automap

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#3522]
**Important information**
Linux / 1.3 official binary

**Describe**
The southernmost pillar near the Chamber of Bone entrance is not drawn on the automap.

**To Reproduce**
1. Load attached save
2. Hit tab

**Expected behavior**
There should be 8 pillars on the automap. There are only 7.

**Screenshots**
![image](https://user-images.githubusercontent.com/3142367/141827309-b0f71f7b-92c4-4b66-a40c-38c40a2e52cc.png)

**Additional context**
[single_2_1.zip](https://github.com/diasurgical/devilutionX/files/7540548/single_2_1.zip)

**Comment by FitzRoyX** [comment]
This has been fixed by #6555 I believe
