### ISSUE TITLE
Cyrillyc font kerning too wide in Credits font

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#3523]
**Important information**
Windows 10 / since https://github.com/diasurgical/devilutionX/commit/09db8f1b86033b8d1794ae7c382409bf97e6d58c / compiled myself via VS2022

**Describe**
Font kerning for Cyrillic font for Credit and Support is wider than Latin

**To Reproduce**
Steps to reproduce the behaviour:
1. Change `Code=` in `diablo.ini` to Cyrillic language (`ru`, `bg` or `uk`)
2. Launch game
3. Click on "Credits" menu item ("Виж Създателите" in Bulgarian, "Показать Авторов" in Russian, or "Показати Авторів" in Ukrainian)
4. Compare font kerning between English and Cyrillic text

**Expected behaviour**
Font kerning comparable to English font.

**Screenshots**
![2021-11-15_19-32-19](https://user-images.githubusercontent.com/4958520/141827759-609724d8-b521-49ab-af67-3ee0916d5f44.png)

**Additional context**
Here is a pangram (sentence that uses all Russian letters) for Cyrillic `Charis SIL Bold`, size 12pt typed in LibreOffice for reference
![2021-11-15_19-34-03](https://user-images.githubusercontent.com/4958520/141827809-2292e838-9369-418d-9a7f-a14a7ff5e932.png)

Bonus Ukrainian pangram
![image](https://user-images.githubusercontent.com/4958520/141830129-0a50afa5-2cf7-456f-80c1-c124f6c4bf0a.png)

**Comment by AJenbo** [comment]
We do not actually support kerning, only letter spacing.

![image](https://user-images.githubusercontent.com/204594/141834066-630d5eea-d9b0-409c-bdcd-9cdc22f09298.png)

**Comment by tsunamistate** [comment]
"Kerning" was taken from https://github.com/diasurgical/devilutionX/commit/09db8f1b86033b8d1794ae7c382409bf97e6d58c name "Fix cyrillic UI font kerning"
Still, the spacing is too wide

**Comment by AJenbo** [comment]
Yeah, it's a bit miss leading because of legacy, but wanted to make the distinction clear so that we have the same expectations of what is feasible :)

The Cyrilic credit font letter width is located in 22-04.bin (each byte is the width of a letter) this is the mapping of the 256 letters, as well 22-04.pcx is where the actual letters are. The proper width should be the white part, not including the shadow.

**Comment by AJenbo** [comment]
This turned out to be an issue for all core fonts.
- Some symbols where not trimmed to the left of the font image
- Font size had the shadow subtracted from the symbol width instead of setting spacing to -1
- The additional white space symbols on page 20 did not have a width defined

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/161458544-4703a801-2e64-4dbf-b160-b8fa541135f4.png)

**Comment by tsunamistate** [comment]
That looks much better, thank you for taking the time to fix this!
