### ISSUE TITLE
UI/QOL Suggestion: Visually show cost of currently-selected Spell/Skill directly on Mana meter.

### ISSUE THREAD

**Issue by Shockwave508** [diasurgical/devilutionX#3525]
Since there is no way of identifying how much a given Spell costs without directly opening the Spellbook menu, I think it would be nice if there is some sort of visual representation of Mana Cost, regarding the currently-selected Spell/Skill. Perhaps make certain portions of the Mana meter shine a brighter shade of blue, separated by thin lines, letting players know how many "charges" of the current Spell one can cast at any given time, if they decide to "spam" it until they run out of Mana. Naturally, this would be toggled on/off in Diablo.ini, suited to player prefefence.

**Comment by ThomasChr** [comment]
I like the idea. But before we implement it we should make sure that others do also.
@julealgon Don't you like the idea at all, or do you favor another implementation?

I also like the idea (not from me, from discord) to simply show the mana cost directly on the spell icon.

**Comment by julealgon** [comment]
> @julealgon Don't you like the idea at all, or do you favor another implementation?

I think its just unnecessary clutter on the UI. The game already tells you whether or not you have mana to cast the current readied spell (the icon becomes gray if you don't have enough mana), so adding another visual indicator is redundant.

Additionally, I don't see any benefit of knowing precisely how many casts you can do with your current mana pool (the other aspect of this proposal). Attempts to do that in the mana orb, to me, go against the original visual design of the orbs, so I'm not fond of it.

I do not have any other implementation suggestion as I just don't see a need for this one.

**Comment by ThomasChr** [comment]
@Shockwave508 According to this vote it does seem that no one want's to have this feature.
So it's a good question if one should take the time to code it down if it will never be merged.
