### ISSUE TITLE
RFC: Embedding color switching in text

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3546]
This is currently already done to some extend for the help menu where $ means the line should be rendered red.

We currently support 5 colors, white, red, blue, gold and black. Being able to color a single line in multiple colors can have several benefits:

- It would allow a better looking options menu
- It can be helpful for gamepad hints (ⓍⓎⒶⒷ)
- Some people enjoy having lots of colors in there names or chat messages

I suggest that we the text render look for ⬜🟥🟦🟨⬛, and instead of rendering it, switch the current color when encountered so that the remainder of the text will be rendered with the given color rather then what was given via flags. 

Example:
`DrawString(_("Press 🟦Ⓧ⬜ to cast spell"))`
`DrawString(_("Run in town: ⬜On"), UiFlags::ColorGold)`

The potential down side is that you would not be able to use the 5 symbols. An alternative would be to only do it if given in a combination with a control character like U+2061 (FUNCTION APPLICATION) or U+91 (PRIVATE USE ONE). The down side being that they are harder to enter in to the text.

**Comment by AJenbo** [comment]
@qndel @glebm @obligaron please comment on this proposal :)

**Comment by qndel** [comment]
Yeah sounds good

**Comment by glebm** [comment]
Perhaps we should handle this in the code instead, e.g.:

```c++
DrawStringWithColors(_("Press {} to cast spell"), {"Ⓧ", UiFlags::ColorBlue});
DrawStringWithColors(_("Run in town: {}"), {_("On"), UiFlags::ColorWhite}, UiFlags::ColorGold));
```
We probably only need to support `{}` at least initially.

**Comment by AJenbo** [comment]
Sure if you can figure out how to do that in a good way :)

**Comment by glebm** [comment]
I think I have :tada:  #3576

**Comment by AJenbo** [comment]
> Some people enjoy having lots of colors in there names or chat messages

To bad it doesn't allow for the user text part, oh well.

**Comment by glebm** [comment]
Mixing translations with formatting is what I wanted to avoid with the submitted PR.

Markup for user input can be done as a separate feature!
