### ISSUE TITLE
Crashes when selecting Hell difficulty level.

### ISSUE THREAD

**Issue by bubio** [diasurgical/devilutionX#3551]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Operating system: macOS 12.0.1（21A559）
DevilutionX version : #3550 self compile

**Describe**
I don't know if this is the right place to write this, but recently I've been getting frequent crashes when running in Japanese.

When you hover the cursor over Difficulty Hell.
When you choose to delete a character.
etc...

**To Reproduce**
1. diablo.ini  Code=ja
2. Select 'Single Player'
3. Select 'New Hero'
4. Select Any Class
5. Enter Name
6. Select Difficulty Hell
7. Crash!

**Additional context**
The location is the same, the DecodeFirstUtf8CodePoint function.
Log file is attached.

[CrashLog_Mac_Japanese.txt](https://github.com/diasurgical/devilutionX/files/7573992/CrashLog_Mac_Japanese.txt)

**Comment by bubio** [comment]
This seems to be due to the presence of many ZWSP (Zero-width_space) in the PO file.
This was inserted by segment_en.py.

Before:
![スクリーンショット 2021-11-20 18 50 07](https://user-images.githubusercontent.com/78299054/142721986-0486b613-b533-4aed-b374-f1a208bc849c.png)

After:
![スクリーンショット 2021-11-20 18 51 04](https://user-images.githubusercontent.com/78299054/142721988-185dad68-2054-44ec-94d3-b5279bb99de8.png)

If you use a file with ZWSP removed, it will almost never crash.

However, when I try to delete a character, it still crashes. This seems to be a different cause.

/cc @glebm

**Comment by bubio** [comment]
Even if it contains ZWSP, if you shorten the string, it will not crash.

`"ヘル<200b>の<200b>難易度<200b>\n"
"<200b>地獄<200b>へ<200b>の<200b>入り口<200b>に<200b>は、地下<200b>世界<200b>の<200b>最強<200b>の<200b>生物<200b>が<200b>潜ん<200b>で<200b>い<200b>ます。経験<200b>豊富<200b>な<200b>キャラク"
"ター<200b>だけ<200b>が、この<200b>領域<200b>に"`

This suggests that the string is getting longer with the insertion of ZWSP and that some buffer size is insufficient.

**Comment by glebm** [comment]
I've sent a PR fixing the 2 places you mention. Feel free to do something similar if you find any more!

**Comment by bubio** [comment]
Fix confirmed.

![スクリーンショット 2021-11-20 21 41 47](https://user-images.githubusercontent.com/78299054/142726752-b67395f8-545b-4917-bc72-c404b045aecd.png)
![スクリーンショット 2021-11-20 21 42 10](https://user-images.githubusercontent.com/78299054/142726753-13e199c5-2596-43c8-b26a-0b289033d126.png)

**Comment by AJenbo** [comment]
> This seems to be due to the presence of many ZWSP (Zero-width_space) in the PO file.

Oh that a good point as well, each ZWSP will chew up another 3 bytes, and I haven't tested the game with Chinese since they where added. But from what I have seen Japanese will trigger the issue more frequently then Chinese because. So Japanese will likely be a better test for finding problem areas.
