### ISSUE TITLE
Android: Game crashes every other startup.

### ISSUE THREAD

**Issue by Shockwave508** [diasurgical/devilutionX#3553]
Device: Xiaomi Black Shark 2 Pro (128GB + 8GB RAM)
Gamepad: Razer Kishi for Android (Xbox Variant)
OS: Android 10
DevilutionX Version: v1.3.0

Description: When quitting the game, there is a high chance that the app will instacrash next time you try to run it. Trying again after said crash will start the game normally. Thankfully, settings and saves aren't affected by this issue.

To Reproduce:
1) Start DevilutionX normally.
2) Quit the game.
3) Attempt to start DevilutionX again, and note how it fails to start, going to a black screen briefly before crashing, with no error message.
4) Try to start to game one more time, and it'll boot properly now.

Expected Behavior: The game would boot up every time. without fail.

Screenshots: None.

Additional Context: None.

**Comment by StephenCWills** [comment]
Can you add some more information about your hardware, like the make/model of the phone and whether you are using a physical gamepad?

**Comment by StephenCWills** [comment]
Also, what is v1.3.9? Did you mean to say v1.3.0?

**Comment by Shockwave508** [comment]
Updated as requested.

**Comment by AJenbo** [comment]
I think this is related to how the app tends to linger in the background rather the actually quit.

From tests and documentation it seams that to fully quit an app you need to call:
```java
		System.exit(0);
```

But if I do this after `nativeRunMain()` has been called, it seams to have no effect.

**Comment by AJenbo** [comment]
It's only for when you quit the game, not when you minimize or switch to a different app.
