### ISSUE TITLE
Truncated UTF8 item names can cause crashes

### ISSUE THREAD

**Issue by bubio** [diasurgical/devilutionX#3556]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Operating system: macOS 12.0.1（21A559）
DevilutionX version : #3550 self compile

**Describe**
When using TOWNPORTAL, it sometimes crashes while displaying the progress bar.
This seems to happen when using it on dungeon levels lower than 13.

**To Reproduce**

[single_3.hsv.zip](https://github.com/diasurgical/devilutionX/files/7574632/single_3.hsv.zip)
Use this save file.
After loading, enter the Town Portal.

https://github.com/diasurgical/devilutionX/blob/a3378f998273711f06d0eb9293fef24b8c0bcef2/Source/items.cpp#L1314
Probably because the buffer size here is insufficient, but why does it run when I enter the town portal?

Similar to the following:
#3551 

/cc @glebm

**Comment by AJenbo** [comment]
This is related to generating item names. I'm guessing what is happening is that cutting the line at 67 bytes is resulting a cut in the middle of a multi byte character. Resulting in an invalid string that then isn't being handled safely by `ConsumeFirstUtf8CodePoint()`.

@glebm do you have any thoughts on this?

**Comment by AJenbo** [comment]
The specific issue here should be solved by https://github.com/diasurgical/devilutionX/pull/3566

But there may still be a general issue with `ConsumeFirstUtf8CodePoint()`

**Comment by glebm** [comment]
The issue with `ConsumeFirstUtf8CodePoint()` was fixed in https://github.com/diasurgical/devilutionX/pull/3568

**Comment by AJenbo** [comment]
Oh, forgot to close this :)
