### ISSUE TITLE
Scrolling Help screen past a certain point in Cyrillic languages hits debug assert

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#3561]
**Important information**
Windows 10 on dbdae7b3899e3898d14230d69fc4bc20352834af, self compile, debug build

**Describe**
Scrolling Help screen past a certain point in Cyrillic languages hits xstring debug assert
![image](https://user-images.githubusercontent.com/4958520/142739202-95c251a0-21e2-4364-9c6d-268e0306e540.png)

**To Reproduce**
1. Change `Code=` section in `diablo.ini` to Cyrillic language (`bg`, `ru` or `uk`)
2. Start a debug build of DevilutionX
3. Start a single-player game with any character or load any single-player save
3. Press F1 to show Help screen
4. Scroll the screen until the end
5. See `Debug Assertion Failed` dialogue

**Additional context**
Languages hit the assert in different places. `ru` hits it after
https://github.com/diasurgical/devilutionX/blob/cbda2c848dc511613fde6d83a076ed2c910bc82a/Source/help.cpp#L80

`bg` hits after
https://github.com/diasurgical/devilutionX/blob/cbda2c848dc511613fde6d83a076ed2c910bc82a/Source/help.cpp#L73

`uk` hits after
https://github.com/diasurgical/devilutionX/blob/cbda2c848dc511613fde6d83a076ed2c910bc82a/Source/help.cpp#L56

**Comment by AJenbo** [comment]
Could you check if this PR fixes this issue: https://github.com/diasurgical/devilutionX/pull/3560

**Comment by tsunamistate** [comment]
Yes, it does for all three languages!
However, it doesn't fix it for `drop` command, I'll file a ticket for it

**Comment by AJenbo** [comment]
3558
