### ISSUE TITLE
Using "drop" debug command in Cyrillic languages hits debug assert

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#3562]
**Important information**
Windows 10 on dbdae7b, self compile, debug build

**Describe**
Using "drop" debug command in Cyrillic languages hits xstring debug assert.
![image](https://user-images.githubusercontent.com/4958520/142739730-aa0839d1-7591-456b-be1d-b92066d40fee.png)

**To Reproduce**
1. Change `Code=` section in `diablo.ini` to Cyrillic language (`bg`, `ru` or `uk`)
2. Start a debug build of DevilutionX
3. Start a single-player game with any character or load any single-player save
4. Press `Enter` to start debug console
5. Type `drop` command with any item (e.g. `drop staff`)
6. See `Debug Assertion Failed` dialogue

**Expected behaviour**
Requested item drops near player.

**Screenshots**

**Additional context**
This blocks playtesting whether TL'd items are displayed correctly in-game.

**Comment by qndel** [comment]
for me it crashes on `Благославенный Кольцевая кольчуг�` in russian - this is a serious problem as we just got an item that doesn't fit in 
```cpp
	char _iName[64];
	char _iIName[64];
```
so not sure how expanding it would affect compatibility with vanilla

**Comment by AJenbo** [comment]
We have to truncate the name, vanilla does the same, though I don't think it can hit names that long.

**Comment by AJenbo** [comment]
This looks like a duplicate of https://github.com/diasurgical/devilutionX/issues/3556

**Comment by qndel** [comment]
> This looks like a duplicate of #3556

Yup but I wouldn't close it as it introduces a new way to test it and a quite fast one :)

**Comment by AJenbo** [comment]
Can you test this from https://github.com/diasurgical/devilutionX/pull/3566

**Comment by tsunamistate** [comment]
Fix from #3566 confirmed
