### ISSUE TITLE
Unique Item information is not displayed.

### ISSUE THREAD

**Issue by bubio** [diasurgical/devilutionX#3565]
**Important information**
Operating system: macOS 12.0.1（21A559）
DevilutionX version : Self compile (tree/84646188adc7dc05c5a19e97fc0763314c3f9a2d)
https://github.com/diasurgical/devilutionX/tree/84646188adc7dc05c5a19e97fc0763314c3f9a2d

**Describe**
Unique Item information is not displayed.

**To Reproduce**
Use this save file.
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/7575679/single_1.hsv.zip)

**Screenshots**
![スクリーンショット 2021-11-21 11 45 44](https://user-images.githubusercontent.com/78299054/142747569-1110262a-8bbb-4a72-9bb4-082be56657ab.png)

**Comment by bubio** [comment]
Occurs from this build:
https://github.com/diasurgical/devilutionX/actions/runs/1485322113

**Comment by qndel** [comment]
```cpp
void DrawUniqueInfo(const Surface &out)
{
	const Point position { GetLeftPanel().position.x - SPANEL_WIDTH, GetLeftPanel().position.y };
	if ((chrflag || QuestLogIsOpen) && GetLeftPanel().Contains(position)) {
		return;
	}

	SDL_Log("%d %d", position.x, position.y);
```
`INFO: -320 0`

**Comment by AJenbo** [comment]
`	const Point position { GetRightPanel().position.x - SPANEL_WIDTH, GetRightPanel().position.y };`

**Comment by bubio** [comment]
Fast work!!

![スクリーンショット 2021-11-23 8 45 51](https://user-images.githubusercontent.com/78299054/142951937-5c1c9112-4767-4801-a7a9-2eb1ecaddb09.png)
![スクリーンショット 2021-11-23 8 47 22](https://user-images.githubusercontent.com/78299054/142951950-eff4100c-590f-4b7e-a355-bec34ce4d039.png)
