### ISSUE TITLE
List of zerotier games overflows

### ISSUE THREAD

**Issue by ThomasChr** [diasurgical/devilutionX#3567]
**Describe**
Ajenbo noticed in discord that the list of available zerotier games does overflow

**To Reproduce**
Have enough open zerotier games, then go to the zerotier network menu

**Expected behavior**
The list should be scrollable

**Screenshots**
![E364B3C1-2E00-4AB2-BD62-22BFDD4F4606](https://user-images.githubusercontent.com/13014163/142756634-77ed20c7-3a59-45da-91d7-08e2c7a4e88e.png)

**Comment by obligaron** [comment]
#3437 contains diablouI enhancements (caller doesn't need to managed viewport logic and scroll-bar simplifications) that could help with fixing this.
