### ISSUE TITLE
Russian translation character screen issues

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#3570]
![image](https://user-images.githubusercontent.com/14297035/142771278-7f447c6d-0987-4add-8789-d06e05516ac2.png)

Base/current stats labels overlap

Hit chance overlaps stats area

**Comment by SourceCodeDeleted** [comment]
Looks like we need to shorten a bit .

maybe just add a part of the word and shorten with "." in the end.,

**Comment by qndel** [comment]
> Looks like we need to shorten a bit .
> 
> maybe just add a part of the word and shorten with "." in the end.,

no idea, you are russian here ;p

**Comment by AJenbo** [comment]
@Iniquitatis any input on this :)

**Comment by glebm** [comment]
"Меткость" could be another option

**Comment by SourceCodeDeleted** [comment]
> "Меткость" is another option

This is a good choice, but it doesn't solve the "базовый" issue. I am just saying in the Ukrainian version we are making shorts of the words. I assume we will need to do the same here. 

I just don't want to alone order a fix, but make some suggestions, and we can see what fits best.

**Comment by NikoVP** [comment]
You can maybe use a trick to separate Текущий from Базовь by adding spaces in front of Текущий and after Базовь to displace them a bit. I used something similar in the Bulgarian translation.

**Comment by SergBrNord** [comment]
![1](https://user-images.githubusercontent.com/71232876/148682798-c8f1573b-f6c7-4a18-9472-c267e0ded204.png)
![2](https://user-images.githubusercontent.com/71232876/148682799-bf86fbb1-acb7-4c7d-977d-066f877a4bef.png)

I'm propose this options..

**Comment by qndel** [comment]
@SergBrNord feel free to open a PR
