### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by Grog0** [diasurgical/devilutionX#3577]
**Important information**
MacOS 12.0.1/1.30/download release [Operating system / DevilutionX version / did you download a release or did you compile yourself?]

**Describe**
Failed to open file:
fonts\yellowdialog.trn [clear and concise description of what the bug is.]

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/issues/3390
