### ISSUE TITLE
Some tiles are not drawn

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#3582]
**Important information**
Linux / 1.3.0 official build

**Describe**
It seems that some tiles are not drawn in level 9 for the particular seed in the attached savegame.

**To Reproduce**
1. Load attached save
2. Walk around

**Screenshots**
![screen15](https://user-images.githubusercontent.com/3142367/142978589-ed8ff469-8cac-47d0-9f86-3ec0f33748a2.png)

**Additional context**
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/7586091/single_0.hsv.zip)

**Comment by AJenbo** [comment]
Duplicate: https://github.com/diasurgical/devilutionX/issues/3182

The issue is that the tiles do not exist.
