### ISSUE TITLE
`upscale=0 fulscreen=1` not working with with multi-monitor setup on Ubuntu + Nvidia drivers under SDL2

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#360]
Ubuntu 19.04, GTX 1080 proprietary drivers, multi-monitor setup. Looking into it.

Other combinations of flags work (e.g. `upscale=1 fullscreen=1`)

**Comment by glebm** [comment]
No idea what's happening

**Comment by AJenbo** [comment]
I can take a look tomorrow

**Comment by glebm** [comment]
I have just checked at 0.4.0 and it was broken then already.

**Comment by glebm** [comment]
It works just fine if I unplug my 2nd monitor

**Comment by glebm** [comment]
This just seems like a bug in SDL or NVidia drivers.

**Comment by glebm** [comment]
Also doesn't work under SDL1.
Definitely a driver bug.
