### ISSUE TITLE
Tiles disappearing while on screen

### ISSUE THREAD

**Issue by NikoVP** [diasurgical/devilutionX#3601]
**Important information**
Windows 10 / DevilutionX 273b9e7 / Github actions build

While walking in the Crypt in lower part of the screen you can clearly notice floor tiles disappearing.

It appears to be part of 1.3.0 or later
Use save state.

[single_1.zip](https://github.com/diasurgical/devilutionX/files/7596682/single_1.zip)

Walk around the floor. I also checked release 1.2.0 and this wasn't occurring there

Tiles shouldn't disappear while on screen.

![Animation2](https://user-images.githubusercontent.com/60973634/143266424-1a0fe858-451d-458c-b1cc-0e6b51b71af4.gif)

**Comment by Chance4us** [comment]
@NikoVP I didn't really understand which tiles, but possibly discovered something similar.
Could you check if you have been experiencing the problem since commit 92db72719d9a8efcc24292f96be9866f2e0c0c13?

**Comment by NikoVP** [comment]
What I was referring to was the ground floor tiles. On the animation you can see some of the flame tiles on the crypt floor dissappearing and reappearing. I wasn't able to record a good video, had some trouble even doing that one. Still, you can see how the exir reappears suddenly (after having dissappeared while on screen) instead of just coming into view from the edge of the screen.

**Comment by AJenbo** [comment]
Regarding the issue not appearing in 1.2.0, it's true that things did not pop out of view as much at that point, but there where still many visual artifacts and things did pop into view. These issues have now been resolved and will be part of 1.5.0
