### ISSUE TITLE
Hellfire test classes available in vanilla

### ISSUE THREAD

**Issue by vlolteanu** [diasurgical/devilutionX#3624]
**Important information**
Linux / 6273f700fa07bd96bc432ddd13645380e9b5a1b0

**Describe**
The bard and barbarian can be enabled in the options menu, and then selected when creating new characters in vanilla.

**Screenshots**
![image](https://user-images.githubusercontent.com/3142367/143677900-a90d9268-b088-4990-bb47-196660dbd6b6.png)

**Comment by glebm** [comment]
I believe that's on purpose

**Comment by qndel** [comment]
> I believe that's intended

yup
