### ISSUE TITLE
[Feature Request] Update XBox Port

### ISSUE THREAD

**Issue by Gunnar-GO** [diasurgical/devilutionX#3630]
There is an XBox Classic Port of this game, but it's kinda old (1.0).

May it be possible to add in the build-chain?

**Comment by AJenbo** [comment]
There was already an effort to upstream the port, but the effort has currently stalled. See https://github.com/diasurgical/devilutionX/pull/730 and https://github.com/diasurgical/devilutionX/pull/760 You are well come to pick up things where they where left off. DevilutionX should at this point work with what is provided by OpenXDK.

P.s. It might be good to familiarize yourself with the project and it's features, preferably by joining https://discord.gg/YQKCAYQ or the [Discussion](https://github.com/diasurgical/devilutionX/discussions) section.

**Comment by AJenbo** [comment]
A big update has happened on this. https://github.com/diasurgical/devilutionX/pull/4838
