### ISSUE TITLE
Find best matching language

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3641]
Currently if a user's system language is set to `fr_CA` it will automatically match the `fr` translation after failing to locate a Canadian specific dialect. But for `pt_PT` it will fall back to `en_US` instead of matching `pt_BR`, which would be a better solution in most cases.

Since scanning for files isn't to portable and we already need a curated list, it might be good to change `HasTranslation()` to simply use the list from https://github.com/diasurgical/devilutionX/blob/master/Source/options.cpp#L758

This way we can simply match the string lengths (first 5, then 2) when looking for matches.

**Comment by ephphatha** [comment]
Having a play around with windows internationalisation and the win32 api provides a function to retrieve the list of supported languages for the system, maybe other platforms have similar functionality? on my system I have it configured for `en-AU`, `en-GB`, `en-US` and could reasonably expect a fallback to `en` if no other translation exists.

The current approach of using the default language if the regional variation doesn't exist seems appropriate as long as we ensure that a neutral translation is provided for all languages where we have a regional translation.

**Comment by AJenbo** [comment]
I don't think such a thing as a neutral language variant exists. But we could have a default if more then one transformation exists.

**Comment by julealgon** [comment]
> But for pt_PT it will fall back to en_US instead of matching pt_BR, which would be a better solution in most cases.

Are you sure about that? How did you conclude this?

I'd personally not want to fallback to pt-PT if pt-BR was missing (the opposite situation), and I don't think that's common at all (I might be wrong here).

**Comment by AJenbo** [comment]
@julealgon do you have you system language set to `pt` or `en`?

10 base languages most commonly spoken in regions with low English proficiency, based on number from the EF:
Arabic, Chinese, French, Japanese, Portuguese, Punjabi, Russian, Spanish, Tamil, Turkic

Additionally from what I have read and the people I have spoken with it seams that most variants of are intelligible to the speakers of other variants. Brazilian is supposedly one of them most derived variants.

**Comment by julealgon** [comment]
>@julealgon do you have you system language set to pt or en?

My personal laptop is unfortunately setup with pt-BR as it is a single language OEM Windows install. I don't understand how relevant the question is however. What are you alluding to?

> 10 base languages most commonly spoken in regions with low English proficiency, based on number from the EF:
Arabic, Chinese, French, Japanese, Portuguese, Punjabi, Russian, Spanish, Tamil, Turkic

Again, I'm not getting your point here.

> Additionally from what I have read and the people I have spoken with it seams that most variants of are intelligible to the speakers of other variants. Brazilian is supposedly one of them most derived variants.

I was only sharing my personal perspective as a Brazilian: I don't even remember the last time I saw a pt-BR -> pt-PT fallback: the languages are actually not as similar as one would think for this to even work IMHO.

**Comment by ephphatha** [comment]
> I don't think such a thing as a neutral language variant exists. But we could have a default if more then one transformation exists.

I was referring to the non-regional variants that currently exist in devx/translations, not sure if there's an accepted term for something like `fr` as opposed to `fr_FR`. MSDN refers to these as [neutral language representations](https://docs.microsoft.com/en-us/windows/win32/intl/user-interface-language-management#neutral-language-representation).

Windows also distinguishes between UI languages and Locales which complicates things a bit. On my system `en-AU` is my default locale, which defines date/time/number format and currency symbols, but there is no Australian English language pack available from Microsoft so I have a fallback language pack installed of British English. This means that `GetUserDefaultLocale()` returns `en-AU` only, and `GetUserPreferredUILanguages()` returns `en-GB, en-US` only (as I have US English as a second choice in my configured languages).

I think for devx on windows it makes sense to preference the language configured in diablo.ini, then the user default locale, then the preferred UI languages in order, before falling back to the untranslated strings if all else fails.

One thing I'm wondering though is how to fit this around the current logic of looking for a regional translation followed by the regional-invariant/neutral translation. if I had a preference order of `cpe-SG, en-SG, zh-SG, ms-SG, zh-CN` should the checks for neutral representations be interleaved (`cpe-SG, cpe, en-SG, en, zh-SG, zh, ms-SG, ms, zh-CN, zh?`), appended to the end (`cpe-SG, en-SG, zh-SG, ms-SG, zh-CN, cpe, en, zh, ms, zh?`), or skipped entirely?

I'll do a PR for windows that doesn't do any neutral fallback as a demo, maybe that'll be good enough for a best effort and we can let the user pick from the settings menu options added in #3634

**Comment by ephphatha** [comment]
Opened #3663 as a draft, this runs through all configured languages on my system with no fallback. I had to remove the fallbacks for other platforms to make it behave nicely so I wouldn't want to use it as is.

Because no english regional translation is provided for en-AU, en-GB, or en-US (and `en` shouldn't be provided if I understand the GetText usage recommendations) this code will always run for english users. It seems fast enough that there's no impact on load times.

**Comment by ephphatha** [comment]
Oh yuck, I see now that other platforms give different expectations around the resolution of localisations. Android does a closest match similar to what you've described (and what juleagon recommends against) - https://developer.android.com/guide/topics/resources/multilingual-support#postN - though I have no idea how that handles language families like creole pigeon english...

**Comment by julealgon** [comment]
> Android does a closest match similar to what you've described (and what juleagon recommends against)

To be clear, I was specifically talking about the Brazil vs Portugal Portuguese, and not as a general rule. IMHO, those are a completely different beast compared to stuff like `en-US` vs `en-GB` vs `en-AU` which are much, _much_ more similar to each other.

**Comment by bubio** [comment]
On macOS, the following will probably be executed, but it will return an empty string.

https://github.com/diasurgical/devilutionX/blob/d22dfc95541769f6e7936daa3f38b08bc7cf985d/Source/options.cpp#L801

I tried a simple program.

```
#include <iostream>
#include <locale.h>
using namespace std;

int main()
{
    std::string locale = std::locale("").name().substr(0, 5);
    cout<<"Locale: "<<locale<<endl;

    setlocale(LC_ALL, "");
    cout << "LC_ALL: " << setlocale(LC_ALL, NULL) << endl;
    cout << "LC_CTYPE: " << setlocale(LC_CTYPE, NULL) << endl;

    return 0;
}
```

The results are as follows.

```
@"Locale: \r\n"
@"LC_ALL: ja_JP.UTF-8\r\n"
@"LC_CTYPE: ja_JP.UTF-8\r\n"
```

For this reason, it will always fall back to en_US.

**Comment by ephphatha** [comment]
> On macOS, the following will probably be executed, but it will return an empty string.
> 
> https://github.com/diasurgical/devilutionX/blob/d22dfc95541769f6e7936daa3f38b08bc7cf985d/Source/options.cpp#L801

Looks like macOS provides [CFLocaleCopyCurrent](https://developer.apple.com/documentation/corefoundation/1542508-cflocalecopycurrent) and [CFLocaleCopyPreferredLanguages](https://developer.apple.com/documentation/corefoundation/1542887-cflocalecopypreferredlanguages) (similar to the win32 `GetUserDefaultLocaleName` and `GetUserPreferredUILanguages`), an approach like #3663 could be added for that platform.

**Comment by AJenbo** [comment]
@bubio mentioned a possible implementation. But I'm not sure where exactly he posted it :sweat:

**Comment by ephphatha** [comment]
Didn't mean to imply I was ignoring/hadn't seen that snippet. It uses the C language `setlocale` function (defined in `<clocale>`) as an alternative to what I'm guessing is an incomplete implementation of the C++ language `std::locale` class (defined in `<locale>`). From what I can see in a standards compliant environment `std::locale("").name()` should return the same string as `setlocale(LC_ALL, NULL)`. This will be a single locale identifier unless certain facets have been redefined.

For example [this snippet sets the ctype locale to the "C" system locale using both std::locale and setlocale](https://tio.run/##lVBNi8IwEL3nVwzx0oKK57YKUrwFXXD3sCfJpoNU0rS004Ms/vZumyjbagXNLe/N@5hRRTFTWppj00xSo3SdIERpXlGJMluxf0znSmrsI@oGsdQQZDI1ns9@GbRP1pSDo3c/J1QES6goCQKHeZz7oR20oMprgigCLiwLThIA78C@y9zIDD2/g60QTaLD@8D9uSLMYjoXeJfat5oOGH/wbRt16tGKzh3sADzv2ysxXtpZI10LiPiwFmIKzw5j6WvCo2r7JcTYVQaT8ef3x6ZNiPkLi72fZy1LpLo0sAjZpWn@AA "C++ (clang) – Try It Online").
This works as expected on linux/WSL with clang and g++, giving me the following output:
```
Locale Object: C.UTF-8
System ctype Locale Object: LC_CTYPE=C;LC_NUMERIC=C.UTF-8;LC_TIME=C.UTF-8;LC_COLLATE=C.UTF-8;LC_MONETARY=C.UTF-8;LC_MESSAGES=C.UTF-8;LC_PAPER=C.UTF-8;LC_NAME=C.UTF-8;LC_ADDRESS=C.UTF-8;LC_TELEPHONE=C.UTF-8;LC_MEASUREMENT=C.UTF-8;LC_IDENTIFICATION=C.UTF-8
LC_ALL: C.UTF-8
System ctype LC_ALL: LC_CTYPE=C;LC_NUMERIC=C.UTF-8;LC_TIME=C.UTF-8;LC_COLLATE=C.UTF-8;LC_MONETARY=C.UTF-8;LC_MESSAGES=C.UTF-8;LC_PAPER=C.UTF-8;LC_NAME=C.UTF-8;LC_ADDRESS=C.UTF-8;LC_TELEPHONE=C.UTF-8;LC_MEASUREMENT=C.UTF-8;LC_IDENTIFICATION=C.UTF-8
```

For windows the C++ object isn't named and doesn't return the expected string for unnamed locales, instead I get the following output:
```
Locale Object:
System ctype Locale Object: C
LC_ALL: English_Australia.1252
System ctype LC_ALL: LC_COLLATE=English_Australia.1252;LC_CTYPE=C;LC_MONETARY=English_Australia.1252;LC_NUMERIC=English_Australia.1252;LC_TIME=English_Australia.1252
```

I can't test macOS but I assume it has the same shortcoming as windows where the C++ implementation is incomplete.

**Comment by bubio** [comment]
I've been experimenting a bit with Core Foundation.

The system settings have been changed as follows.
<img width="250" alt="Screen Shot 2021-12-10 at 16 50 37" src="https://user-images.githubusercontent.com/78299054/145537464-d9bc1ba2-4bb9-4ca1-b519-32305fed217f.png">

<details>
<summary>Code.</summary>

```cpp
#include <iostream>
#include <CoreFoundation/CoreFoundation.h>

std::string getOSXSystemLang()
{
    CFArrayRef languages;
    CFStringRef language;
    
    char ret[16];
    
    // Get the user's language list (in order of preference)
    languages = CFLocaleCopyPreferredLanguages();
    if (CFArrayGetCount(languages) == 0) {
        return "en_US";
    }
    CFShow(languages);
    
    language = (CFStringRef)CFArrayGetValueAtIndex(languages, 2);
    if (!CFStringGetCString(language, ret, 15, kCFStringEncodingUTF8)) {
        CFRelease(languages);
        
        return "en_US";
    }
    
    // Convert to the underscore format expected by gettext
    std::string lang_code(ret);
    std::replace( lang_code.begin(), lang_code.end(), '-', '_' );
    
    /**
     * Handle special case for simplified/traditional Chinese. Simplified/Traditional
     * is actually denoted by the region code in older iterations of the
     * language codes, whereas now (at least on OS X) region is distinct.
     * That is, CDDA expects 'zh_CN' but OS X might give 'zh-Hans-CN'.
     */
    if ((int)lang_code.find("zh_Hans") > -1) {
        return "zh_CN";
    } else if ((int)lang_code.find("zh_Hant") > -1) {
        return "zh_TW";
    }
    
    return lang_code;
}

int main(int argc, const char * argv[]) {
    
    std::string lang = getOSXSystemLang();
    std::cout << "Languge: " << lang << "\n";
    return 0;
}
```
</details>

Results.
```
(
    "en-JP",
    "ja-JP",
    "en-AU",
    "zh-Hans-JP",
    "zh-Hant-HK",
    "pt-BR"
)
Languge: zh_CN
```

If you can use CoreFoundation, this looks like a better option.

**Comment by AJenbo** [comment]
@ephphatha do you think we can close this now?

**Comment by ephphatha** [comment]
I think so with the languages that are currently supported. Could possibly drop the region suffix from ko_KR and ro_RO to match the other languages and let them get picked up in fallback? They seem to be the most appropriate default for their respective language families.

**Comment by AJenbo** [comment]
Yeah lets do that :)
