### ISSUE TITLE
[IDEA] [3DS] Tweak Touchscreen On 3DS

### ISSUE THREAD

**Issue by Kristopian** [diasurgical/devilutionX#3647]
On old 3ds, no idea about this on new 3ds

Please make it an option to change stylus control. So that you click on release instead of click on touch. Another solution is to display the game on both screens. Just the menu on the bottom, some shortcuts, or just leave it blank.

**Comment by glebm** [comment]
It is very difficult to read a sentence where Every Word Is Capitalized.

**Comment by qndel** [comment]
> On old 3DS, No Idea About This On New 3DS
> 
> Please Make It An Option To Change Stylus Control So That You Click On Release Instead Of Click On Touch, Or Another Solution Is To Display The Game On Both Screens, Just The Menu On The Bottom, Some Shortcuts, Or Just Leave It Blank.

![image](https://user-images.githubusercontent.com/14297035/144043723-5a7e8a80-ea58-43c5-8ab8-3cff66ff1681.png)

**Comment by Kristopian** [comment]
Just A Realy Bad Habit.

**Comment by Kristopian** [comment]
I Do It Less On Mobile
