### ISSUE TITLE
Android: Game crashes on startup

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#3652]
**Important information**
Google Pixel 2, Android 10 / ac152589f960b200a74d53c6c1d920a3610851b3 / self-compile from Android Studio

**Describe**
Upon startup, the game crashes immediately without reaching cinematic.

**To Reproduce**
1. Tap on game shortcut
2. Crash to Main Screen

**Additional context**
Here's the logs of the crash
[devxcrash.txt](https://github.com/diasurgical/devilutionX/files/7626169/devxcrash.txt)
Note: Installed the APK from [CI artefact](https://github.com/diasurgical/devilutionX/suites/4504252546/artifacts/120249959), it also crashes. [Here is the link to CI run](https://github.com/diasurgical/devilutionX/actions/runs/1520325952)

**Comment by glebm** [comment]
Oh, looks like when I updated SDL to 2.0.16 in https://github.com/diasurgical/devilutionX/commit/b038b3ce3d304cde0cc0e305756b2ad858741b36 I forgot to copy-paste the new Java stuff.

**Comment by AJenbo** [comment]
Maybe helpful: https://github.com/diasurgical/devilutionX/pull/3491/files

**Comment by glebm** [comment]
@tsunamistate Can you please try the build from https://github.com/diasurgical/devilutionX/pull/3653? My Android Studio installation appears to be borked at the moment

**Comment by tsunamistate** [comment]
@glebm fix confirmed, game starts up for both data screen with no MPQs and for game itself with MPQs

**Comment by glebm** [comment]
Thanks for testing!
