### ISSUE TITLE
Devilutionx 3ds wont work due to a "missing" file

### ISSUE THREAD

**Issue by Jimmy2048** [diasurgical/devilutionX#3658]
**Important information**
3ds

**Describe**
when i launch the game it wont let me showing me an error (image below)

**Expected behavior**
well i used to be able to play the game until i updated the app through unistore

**Screenshots** also i speak English its just the 3ds i own is Japanese
![20211201_162420 1](https://user-images.githubusercontent.com/58403159/144316679-d2c03f92-019e-4536-b934-563da41ad395.jpg)
.

**Comment by AJenbo** [comment]
Simply delete the old devilutionx.mpq file from previous installations.

**Comment by Jimmy2048** [comment]
thanks
