### ISSUE TITLE
MacOS error on startup v1.3.0

### ISSUE THREAD

**Issue by jockking** [diasurgical/devilutionX#3660]
**Important information**
MacOS Montery / DevilutionX 1.3.0 / Downloaded latest Release?

**Describe**
After launch and opening logo - the following error message comes up:

Error:  Failed to open file: fonts/yellowdialog.trn - File not found

**To Reproduce**
1. Launch app from Finder

**Screenshots**
<img width="265" alt="Screenshot 2021-12-01 at 23 27 00" src="https://user-images.githubusercontent.com/7249682/144331001-97b91b1c-9bc1-4075-bbe2-2a9501441f8c.png">

**Additional context**
Rolled back to earlier version and working properly

.

**Comment by AJenbo** [comment]
You need to update devilutionx.mpq as well.

Duplicate: https://github.com/diasurgical/devilutionX/issues/3390
