### ISSUE TITLE
Fails to launch in Yuzu (Are Switch instructions correct?)

### ISSUE THREAD

**Issue by heinermann** [diasurgical/devilutionX#3685]
Since I'm making commits to [Yuzu](https://github.com/yuzu-emu/yuzu) (Switch emulator) I will be looking into this. For context I think it will be easier to debug from this side than emulator-side.

Since this is probably the fault of Yuzu, I'll create a sister issue for them once I can compile and rule out anything dumb such as not checking the right directory.

## Steps
1. Copied `DIABDAT.MPQ`, `devilutionx.nro`, and `devilutionx.mpq` to `AppData\Roaming\yuzu\sdmc\switch\devilutionx`.
2. In Yuzu (master), File -> Load File... -> `devilutionx.nro` (or from the games list).
3. Yuzu shows loading bar for 1s, followed by game immediately closing back to the rom list.

## Notes
- Does create a `diablo.ini` in `yuzu\sdmc`, so it is doing something before closing.

**Comment by Trihedraf** [comment]
Try removing devilutionx.mpq. For some of the platforms it is built in to the executable now instead.

**Comment by heinermann** [comment]
> Try removing devilutionx.mpq. For some of the platforms it is built in to the executable now instead.

Same issue. I'll deep dive tomorrow.

**Comment by heinermann** [comment]
With the latest build from CircleCI, if I move `DIABDAT.mpq` to the `sdmc` root folder, it plays the intro video before closing.

**Comment by heinermann** [comment]
Ah was missing devilutionx.mpq in sdmc root. Otherwise appears to be working perfectly fine. But that means there's a discrepancy in the instructions.

Can someone confirm that on actual hardware it *must* be placed in `sdmc://switch/devilutionx/` rather than root?

**Comment by StephenCWills** [comment]
Closed due to inactivity and unfortunate circumstances for Yuzu.
