### ISSUE TITLE
Setting Fullscreen to ON does not return game to full screen

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3697]
**Important information**
master, self build, linux, radeon

**Describe**

**To Reproduce**
1. Go to Settings
2. Switch Fullscreen off
3. Switch Fullscreen on

**Additional context**
alt+enter still works correctly for setting the game back to fullscreen

Several other graphics options will force the game to ext fullscreen mode.

Scaling quality works as expected.

**Comment by AJenbo** [comment]
@obligaron Ok, I figured out what is going on here :)

If you start the application with `-x` and then switch to full screen with `alt+enter`, recreating the window will always create a windowed window :)

**Comment by obligaron** [comment]
I can produce the issue with `-x`. 👍 

The question is, is this a bug?
`alt+enter` is a sdl feature and doesn't honor `-x` or?
We could set `gbForceWindowed` to `false` when fullscreen option is toggled.

Should I open a pr for that or should we close the issue?

**Comment by AJenbo** [comment]
I'm slowly typing out a possible change to it that I hope will make things more intuitive.
