### ISSUE TITLE
Display freezing on Windows when changing graphics settings with VSync and Upscale On

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#3706]
**Important information**
Windows 11 / DevilutionX master / compiled through VS2022

**Describe**
With both VSync and Upscale set to On, changing another graphics setting that requires reinitialising the renderer causes the display to freeze.

**To Reproduce**
1. Go to Settings > Graphics
2. Ensure Vertical Sync and Upscale are both On
3. Change resolution, toggle fullscreen, toggle fit to screen, change scaling quality, or toggle integer scaling
4. The display will freeze on the last displayed frame

The game still responds to keyboard input and can be exited/have other settings changed. Turning any of Vertical Sync or Upscale Off will cause the display to update immediately.

**Expected behavior**
Settings changes take effect immediately without freezing

**Additional context**
Unsure if this is a driver issue. I'm on a AMD + Nvidia system, unfortunately I don't have another system I can easily test on.

**Comment by obligaron** [comment]
@ephphatha can you post your `[Graphics]` settings in the ini? Perhaps then I can reproduce the issue.

**Comment by ephphatha** [comment]
Sure, current ini looks like this:
```ini
[Graphics]
Width=1280
Height=720
Fullscreen=0
Upscale=1
Fit to Screen=1
Scaling Quality=2
Integer Scaling=1
Vertical Sync=1
Blended Transparency=1
Gamma Correction=95
Color Cycling=1
Hardware Cursor=1
Hardware Cursor For Items=0
Hardware Cursor Maximum Size=128
FPS Limiter=1
Show FPS=1
```

I can reproduce the issue with a default config (deleting every key and launching devX). This gives me the following settings:
```ini
[Graphics]
Width=640
Height=480
Fullscreen=1
Fit to Screen=1
Upscale=1
Scaling Quality=2
Integer Scaling=0
Vertical Sync=1
Blended Transparency=1
Color Cycling=1
FPS Limiter=1
Show FPS=1
Gamma Correction=100
Hardware Cursor=1
Hardware Cursor For Items=0
Hardware Cursor Maximum Size=128
```

**Comment by ephphatha** [comment]
I was able to reproduce this with a very simple SDL2 program, it's only after the second time initialising a renderer with the SDL_RENDERER_PRESENTVSYNC flag set that causes the issue. No errors get reported though... so not sure why it's failing to update after that point. https://gist.github.com/ephphatha/d0e68a79f38e8762145bdc47a16f8483

**Comment by ephphatha** [comment]
Put an issue up on the SDL repo (https://github.com/libsdl-org/SDL/issues/5099) and slouken has suggested a workaround of adding a hint to pick the dx11 renderer which I'll try when I get a chance. Should be able to target this only for windows builds.
