### ISSUE TITLE
Civerb's Cudgel and going below 0 Magic

### ISSUE THREAD

**Issue by johnnyaeba** [diasurgical/devilutionX#3707]
I started playing a Barbarian in Vanilla (not Hellfire) on the latest release version 1.3. The unique item _Civerb's Cudgel_ dropped, giving minus 5 to Dexterity and minus 2 to Magic. However, equipping it on my Barbarian makes my character suddenly not being able to use it - along with my headgear, but neither shield nor chest (oddly enough), even though it's all basic gear with no requirement listed.

Perhaps there is an issue with going below zero Magic? I added a few screenshots to illustrate the problem.

I didn't get to test whether this problem persists when having items that give bonus to Magic or all stats yet, basically negating the negative negative effect, but maybe this is already sufficient info.

![SC_1](https://user-images.githubusercontent.com/95660014/145123980-c18bf547-260a-40f0-91fd-f95862c48dd1.jpg)
![SC_2](https://user-images.githubusercontent.com/95660014/145123985-eee5f509-c596-4523-8c58-5d6c437f36f3.jpg)
![SC_3](https://user-images.githubusercontent.com/95660014/145123987-ead7e581-12bb-49bb-b3ff-6d527339cfc2.jpg)

**Comment by AJenbo** [comment]
Can you add a save game?

**Comment by johnnyaeba** [comment]
Sure, first thing in the morning! Can't do it earlier :(

**Comment by qndel** [comment]
It's because of a flaw in CalcSelfItems
0 is equal to no stat requirement but still follows the regular math, technically all items should be unusable in this scenario, but the algorithm adjusts the stats after seeing civerb's, it's just that head slot is checked before hands and after it's set to unusable, it's not recalculated again.

**Comment by mewmew** [comment]
> Sure, first thing in the morning! Can't do it earlier :(

@johnnyaeba no rush :) just a gentle reminder, please upload the save game when you get a chance.

Cheers,
Robin

**Comment by qndel** [comment]
Tbh we shouldn't request saves for such trivial issues - that's what debug builds are for
Create a barbarian
drop cap
dropu civerb

test 🙃

**Comment by johnnyaeba** [comment]
Hey, yeah, I thought after qndel indentified the issue, a save game wouldn't be needed anymore. :)
