### ISSUE TITLE
[android] Multiple renderers when reenabling upscaling

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3708]
Switch upscalling off, then on:

![image](https://user-images.githubusercontent.com/204594/145129382-1f2403ea-6dde-4261-9b44-8838058e0302.png)

**Comment by StephenCWills** [comment]
Looks like it's creating a new renderer under the covers when we attempt to get the window surface.

![image](https://user-images.githubusercontent.com/9203145/145726829-64fb3abd-c063-46b2-8c66-45ecfa7d9e94.png)

**Comment by AJenbo** [comment]
The exact same issue happens on macOS
