### ISSUE TITLE
Page down/up in DiabloUI should not wrap

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#3723]
Unlike the arrow keys, it is really odd for page up/down to wrap past the start/end.

**Comment by glebm** [comment]
@obligaron This is how the previous DiabloUI code behaved by the way. Can you please have a look?

**Comment by obligaron** [comment]
Sure I can take a look.

Question: I can only reproduce this issue in the new settings menu. Does it also occur elsewhere?

**Comment by glebm** [comment]
I haven't seen it elsewhere (tried hero list and Delete Hero menu)
