### ISSUE TITLE
Spell book cheating and disadvantages

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3728]
One day the game was changed so that when the game was reloaded, the items in the shop of Adria were no longer randomized.
I found that this change created pros and cons.

This can be a big disadvantage, since as a sorcerer have to rely on various important key spells like Fireball, Chain Lightning, Golem, Mana Shield.
And this is exactly what you don't get to buy so often, which can lead to a massive disadvantage.
For example, you've already done a great job, but your hero lacks the Mana Shield spell and is therefore very vulnerable for a long time.

Finally, the goal of the change was that you couldn't build up the hero too quickly, for example with the help of the elixirs.
But the idea has a side effect that can do exactly the opposite.

As an example, you have enough gold and buy the book Fire Ball and save the game.
Then you load the game and can buy the book again immediately. And after saving / reloading again you can buy it again until you reach the maximum (Level 15). So you can achieve the minimum mana consumption and maximum damage in the shortest possible time. I can't imagine that was intended. What is your opinion?

**Comment by obligaron** [comment]
I think this the same as #3172 
And @qndel has already a bug fix on the way #3176 🙂

**Comment by Chance4us** [comment]
Yes absolutely. I missed. Thanks a lot.
