### ISSUE TITLE
Guest crashes when joining TCP game multiple times

### ISSUE THREAD

**Issue by guillaume-roche** [diasurgical/devilutionX#373]
**Description**
Joining a TCP game multiple times from the same guest instance makes the game crash.

**How to Reproduce**
1. Start Devilutionx and host a TCP/IP game
2. Start another instance of Devilutionx, and join the game.
3. Exit game from guest instance (don't exit Diablo, just hit new game)
4. Join again
5. Exit game from guest instance (again, don't exit Diablo)
6. Join again

**Observed behavior**
In guest instance, the mouse pointer turns to a hourglass, and we can't do anything. Behind the scene, it makes a core dump.

**Expected behavior**
The game can be played normally from the guest.

**Additional context**
Reproduced on a local build on up-to-date `master`, with Fedora 30 x86_64. Both host and guest instances were ran from the same build on the same machine.

It seems that the guest get kicked out of the game from the host. See the backtrace:
```
#0  0x00007ffff650be35 in raise () from /lib64/libc.so.6
#1  0x00007ffff64f6895 in abort () from /lib64/libc.so.6
#2  0x000000000048bb84 in dvl::net::base::recv_local (this=0x617000008580, pkt=...) at [...]/devilutionX/SourceX/dvlnet/base.cpp:91
#3  0x00000000004d34de in dvl::net::tcp_client::handle_recv (this=0x617000008580, error=..., bytes_read=52) at [...]/devilutionX/SourceX/dvlnet/tcp_client.cpp:83
```

The related source code is just below. The `ABORT()` is called.

```
case PT_DISCONNECT:
        if (pkt.newplr() != plr_self) {
                if (connected_table[pkt.newplr()]) {
                        auto leaveinfo = pkt.leaveinfo();
                        _SNETEVENT ev;
                        ev.eventid = EVENT_TYPE_PLAYER_LEAVE_GAME;
                        ev.playerid = pkt.newplr();
                        ev.data = reinterpret_cast<unsigned char *>(&leaveinfo);
                        ev.databytes = sizeof(leaveinfo_t);
                        run_event_handler(ev);
                        connected_table[pkt.newplr()] = false;
                        clear_msg(pkt.newplr());
                        turn_queue[pkt.newplr()].clear();
                }
        } else {
                ABORT(); // we were dropped by the owner?!?
        }
        break;
```

This contribution is sponsored by my company, [Genymobile](https://github.com/Genymobile), for #hacktoberfest.

**Comment by AJenbo** [comment]
This is probably a bit related to https://github.com/diasurgical/devilutionX/issues/132

P.s. instead of saying updated master it's often better to just reference a commit hash ;)

**Comment by AJenbo** [comment]
Fix in https://github.com/diasurgical/devilutionX/pull/429
