### ISSUE TITLE
Gear Lost on Death (Multiplayer)

### ISSUE THREAD

**Issue by IDoomYou** [diasurgical/devilutionX#3765]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?

Windows 10 / DevilutionX v1.3.0 / Download

**Describe**

You can permanently lose your gear in multiplayer if you accidently quit out after death if your friend is on a different floor then you.

**To Reproduce**
I would try having 2 people in a multiplayer game in zerotier on separate floors, have 1 die and leave the game and see if there gear is still present when they re-join.

**Expected behavior**
I expected to not lose my gear

**Screenshots**

**Additional context**
Might be weird to re-create I'm not sure all I know is I've lost two full gear setups to this.

**Comment by kphoenix137** [comment]
This was fixed right?

**Comment by AJenbo** [comment]
At least some instance since the reported version. Please open a new issue if you still experience an issue after 1.5.1
