### ISSUE TITLE
0.5.0 win release contain 0.4.0 version

### ISSUE THREAD

**Issue by matej-prokop** [diasurgical/devilutionX#377]
When you download `devilutionx-windows-i386.zip` from assets that belongs to 0.5.0 version (https://github.com/diasurgical/devilutionX/releases). It is actually version 0.4.0 (at least game reports so)

**Comment by AJenbo** [comment]
Your right that the version appears wrong, I'm not sure why this is but I can confirm that it is indeed 0.5.0.

One simple way to check it is to remove your MPQ, the error message in 0.5.0 is now in app where 0.4.0 had a popup message.
