### ISSUE TITLE
Radon fails to compile on NetBSD

### ISSUE THREAD

**Issue by teknokatze** [diasurgical/devilutionX#378]
**Describe the bug**
/usr/work/games/devilutionx/work/devilutionX-0.5.0/3rdParty/Radon/Radon/source/Key.cpp:33:18: error: use of undeclared identifier 'atof'
                return (float)(atof(value.data()));
                               ^
1 error generated.

**To Reproduce**
with pkgsrc, cd to games/devilutionx, make

This is with clang from NetBSD 9.99.15 base (clang 7).
None of the include files in Radon seem to include <stdlib.h> which provides atof.

**Comment by AJenbo** [comment]
@ng-0 we currently don't officially support NetBSD, would you be able to make a PR with the needed changes?

**Comment by ng-0** [comment]
Hi,

Okay, I will do so or defer to the maintainer of the pkgsrc package to make the PR.

**Comment by niacat** [comment]
NetBSD support depends on ladislav-zezula/StormLib/pull/160

Otherwise it's very simple. I haven't tested with clang yet (the default system compiler is gcc).
