### ISSUE TITLE
[ios] Mouse emulation dies after changing graphics settings

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3788]
The menu becomes unresponsive after changing one of the following graphics options:
  - [ ] Resolution
  - [ ] Fit to screen
  - [ ] scaling quality
  - [x] integer scaling
  - [ ] vertical sync

This happens even if scaling quality is isolated to the following, but only about 1/3 of the time:
```cpp
void ReinitializeTexture()
{
	if (texture)
		texture.reset();

	auto quality = fmt::format("{}", static_cast<int>(*sgOptions.Graphics.scaleQuality));
	SDL_SetHint(SDL_HINT_RENDER_SCALE_QUALITY, quality.c_str());

	texture = SDLWrap::CreateTexture(renderer, SDL_PIXELFORMAT_RGB888, SDL_TEXTUREACCESS_STREAMING, gnScreenWidth, gnScreenHeight);
}
```

Printing out the events shows that we still get touch events, but no longer any mouse emulation. Which is actually in line with what we requested. But when we had mouse emulation enabled from the start we would receive 2x the number of expected mouse events.

**Comment by bubio** [comment]
https://github.com/diasurgical/devilutionX/blob/74a77666b9676057822f26e4b3a494197ab6e8fc/Source/utils/display.cpp#L331

When I run SDL_CreateRenderer, the touch doesn't work anymore.
But if you change the settings on the keyboard, you're good to go.

**Comment by bubio** [comment]
https://github.com/libsdl-org/SDL/blob/11ae43ca167476070225d493a642fe6e5bbb96da/src/video/uikit/SDL_uikitview.m#L287

Before releasing the finger, the Window, etc. will be rebuilt, so touchesEnded will not occur and the internal state of SDL will be wrong.

**Comment by AJenbo** [comment]
Maybe this should be reported as an issue to libsdl?

**Comment by bubio** [comment]
https://github.com/diasurgical/devilutionX/blob/74a77666b9676057822f26e4b3a494197ab6e8fc/Source/DiabloUI/diabloui.cpp#L924

```cpp
if (event.type != SDL_MOUSEBUTTONUP || event.button.button != SDL_BUTTON_LEFT)
```

I think this problem can be fixed by changing the timing for enabling touch to when the finger is released.

**Comment by AJenbo** [comment]
i dont think i follow, maybe you can ma a test buid?

**Comment by bubio** [comment]
> i dont think i follow, maybe you can ma a test buid?

How do I do this?

**Comment by AJenbo** [comment]
If you make the change and create a PR a test build will automatically be build.

**Comment by bubio** [comment]
I will report the issue to libsdl.
