### ISSUE TITLE
Client-Server Game Crash when sending null-bytes

### ISSUE THREAD

**Issue by g1ng3rr00t** [diasurgical/devilutionX#3789]
**Important information**

Manjaro (AUR package)
DevilutionX v1.3.0

**Describe**
Able to cause crash in Client-Server (TCP) multiplayer mode when sending null bytes to port 6112.

**To Reproduce**
1. Start a multiplayer Client-Server (TCP) game
2. Run the following code in another terminal

```
#!/usr/bin/env python

import socket

meatloaf = socket.socket(socket.AF_INET,socket.SOCK_STREAM)


meatloaf.connect(('127.0.0.1',6112))
message = (b'\x00'*50)
meatloaf.send(message)

```

**Expected behavior**
Game crashes, error message of 'Incorrect frame size' , SIGABRT signal sent.

**Screenshots**

![frame_size](https://user-images.githubusercontent.com/89753991/146617257-51c55cce-8747-4b6e-a3f9-bb01cdae19b5.png)

![crash](https://user-images.githubusercontent.com/89753991/146617052-07486fbb-b295-4320-a839-eeba396d95b6.png)

**Comment by AJenbo** [comment]
Thanks for reporting this, the issue should now be solved. Let us know if you find any other issues with the way network messages are handled :)
