### ISSUE TITLE
Random item flickers when picking up another one in inventory

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#379]
A random item flickers when picking up another one in inventory.
It happens possibly since refactoring render code.

**Comment by AJenbo** [comment]
I intended to solve this later as the effect was so minimal. It's probably related to running the game at more than 20 fps. Likely the hover state is only cleared during logic frames. Good to have a reminder for the issue :+1:

**Comment by Chance4us** [comment]
You are welcome master Jenbo.

**Comment by galaxyhaxz** [comment]
Master Jedi is quite busy, so it's much appreciated.
