### ISSUE TITLE
Do not show hardware cursor options when not supported

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#3792]
Calling `HardwareCursorDefault()` will let you know if it's supported or not.

https://github.com/diasurgical/devilutionX/blob/master/Source/options.cpp#L230

Additionally we can avoid [this issue](https://github.com/diasurgical/devilutionX/issues/3488) if we simply ignore the ini file when `HardwareCursorDefault()` returns `false`.

**Comment by obligaron** [comment]
I'm not familiar which platform can't support a mouse and have a SDL2 build (cause on SDL1 hardware cursor is not shown/compiled).

- iOS?
- Switch?
- Vita?

On android you can have a (bluetooth) mouse.

**Comment by StephenCWills** [comment]
Android hardware cursor has some issues: #2502

**Comment by AJenbo** [comment]
iOS will simply emit an error to the console when trying to set a hardware cursor. And the feature did not work in general before SDL 2.0.12.

Calling `HardwareCursorDefault()` will let you know if it's supported or not.

https://github.com/diasurgical/devilutionX/blob/master/Source/options.cpp#L230

Additionally we can avoid [this issue](https://github.com/diasurgical/devilutionX/issues/3488) if we simply ignore the ini file when `HardwareCursorDefault()` returns `false`.

**Comment by obligaron** [comment]
Reread #2502

> I'm thinking that the cursor smoothness is less important on Android given that it will most likely be moved using a gamepad (virtual) and rarely an actual mouse. If some one does play it using a mouse on an Android device they are probably enough of a power user that they can change the ini?

Is this not a argument that we should show the option on android (with default off)?
Would this leave only iOS (`TARGET_OS_IPHONE`)?

**Comment by glebm** [comment]
Android can support a hardware cursor but only when a physical mouse is plugged in.

It'd probably make sense to extract a separate function, something like this:

```c++
bool HardwareCursorSupported()
{
	SDL_version v;
	SDL_GetVersion(&v);
	return SDL_VERSIONNUM(v.major, v.minor, v.patch) >= SDL_VERSIONNUM(2, 0, 12);
}
```

**Comment by obligaron** [comment]
Added #3799

It gets only hidden based on the SDL version.
Also iOS also has [mouse cursor support](https://www.youtube.com/watch?v=iH9QZAzWGiA)?
So I thought that iOS should also allow it. It's only deactivated per default, like Android.

**Comment by AJenbo** [comment]
> Reread #2502
> 
> > I'm thinking that the cursor smoothness is less important on Android given that it will most likely be moved using a gamepad (virtual) and rarely an actual mouse. If some one does play it using a mouse on an Android device they are probably enough of a power user that they can change the ini?
> 
> Is this not a argument that we should show the option on android (with default off)? Would this leave only iOS (`TARGET_OS_IPHONE`)?

I suggest we make the following change:
```cpp
If (SDL < 2.0.12 || TARGET_OS_IPHONE)
  hardwareMouse = false;
else
  hardwareMouse = LoadBoolFromIni("graphics", "hardwareMouse");
```

iOS doesn't implement HardwareCursors at all, so if it somehow endes up as on the user will have no cursor (this could happen if they copy the ini from the computer).
Similarly if they use the AppImage that bundels an old version of SDL, after having used a regular build with a more recent SDL; they will not have a cursor.
