### ISSUE TITLE
Suggestion: when hosting TCP/IP, display the IP address on the top left 

### ISSUE THREAD

**Issue by sixcy** [diasurgical/devilutionX#3794]
Hello,

Currently, the IP address is shown when joining a game, however it is not shown when hosting. In my use case I was trying to instruct my young nephew how to create/join multiplayer game in LAN, but I did not want to explain him to type ipconfig in windows command line for that..

I think this would be a very nice quality of life update - assuming there is a way to easily access what is your own IP address. I would like to tell my nephew "host a game, then tell your friends to type the numbers that are on the top left of your screen"

**Comment by AJenbo** [comment]
It's not possible to know what IP the game is being exposed on. There maybe be multiple IPs, Firewalls, NATs and port forwarding involved. We found that listing any of this information was simply misleading to players as they would get stuck trying to connect to the wrong IP for there given setup.

For a more intuitive way to play multiplayer we provide a ZeroTier intergration where you will instead have an unique string and it also provide auto discovery of public games.

**Comment by sixcy** [comment]
Thanks for the reply. Does ZeroTier work if you are in the same house (in a LAN under the same router, with addresses like 192.168.x.y) ?

**Comment by AJenbo** [comment]
yes, but it requires an internet conenction
