### ISSUE TITLE
Display freezing on Windows when turning Upscale off with VSync on

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#3806]
**Important information**
Windows 10 / DevilutionX master / compiled through VS2019

**Describe**
With both VSync and Upscale set to On, changing Upscale to Off causes the display to freeze.

**To Reproduce**
1. Go to Settings > Graphics
2. Ensure Vertical Sync and Upscale are both on
3. Turn Upscale off
4. The display will freeze on the last displayed frame

The game still responds to keyboard input and can be exited/have other settings changed. Turning Upscale back on will cause the display to update again. However, once the D3D11 renderer has been selected even once by turning both VSync and Upscale on, I can no longer get the display to update when Upscale is off.

**Expected behavior**
Turning Upscale off does not freeze the display.

**Additional context**
Plagiarized almost verbatim from #3706 because the symptoms are really similar, but that's almost 100% coincidence. I didn't want to reopen the other issue since the cause is fundamentally different. I'm sorry if this seems really familiar.

Introduced by #3775

**Comment by AJenbo** [comment]
Could you test this with #3803 applied

**Comment by StephenCWills** [comment]
Unfortunately, I noticed this in the first place while testing #3803.

**Comment by ephphatha** [comment]
This happens on Win11 as well -_-. I can switch between the d3d9 and d3d11 renderers at will, but as soon as it goes to rendering to a surface the display freezes. Can probably adapt the sample program I made for the other issue to trigger this as well.

**Comment by ephphatha** [comment]
Oooor, it turns out calling SetHint with a nullptr value bails early, leaving the direct3d11 hint set for all future calls. There doesn't appear to be any way to remove a single hint.

**Comment by obligaron** [comment]
Can a empty string instead of a nullptr "remove" the hint?

**Comment by AJenbo** [comment]
what if you use opengl?

**Comment by obligaron** [comment]
> what if you use opengl?

opengl fixes this issue for me. But didn't experiment much with other settings.
Perhaps we should always use opengl on windows? 🤔

**Comment by AJenbo** [comment]
not being able to reset it to null isn't a bit issue from what i can tell.

With the way things are looking I suggest we set it to OpenGL, and if we get DirectX9/11 we mark it as buggy and require restarts for changing graphics options. The same will probably be required for iOS unless we implement touch input for the menu.

**Comment by AJenbo** [comment]
As I remember the iOS issue has been solved, but is Windows still affected by this?

**Comment by StephenCWills** [comment]
Yes, I can still reproduce this.
