### ISSUE TITLE
Trap multihit death

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3809]
I've already spotted a fix below, but the problem still persists:
fix trap multihit #1675

![trap](https://user-images.githubusercontent.com/45902449/146832116-badd5abe-4a24-41ca-8862-5a7eee4ef766.png)

1. To reproduce load the following game:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/7747945/single_0.hsv.zip)

2. Open the chest equipped with the trap next to the hero.
3. Notice the hero cannot survive the trap suffering multiple hits

**Comment by AJenbo** [comment]
looks like a duplivate of #1672
