### ISSUE TITLE
Empty room in level 8

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3811]
In level 8 I met a completely empty room. There was no monster at all. The level was otherwise filled with gargoyles.
I can't tell if it's a bug at all. I can't remember ever having encountered an empty room.

![empty_room](https://user-images.githubusercontent.com/45902449/146834261-f52ee5ac-0c0d-44ca-94db-03b79684a7a0.png)

Savegame:
[empty_room.zip](https://github.com/diasurgical/devilutionX/files/7748004/empty_room.zip)

**Comment by Chance4us** [comment]
New another game. Doorless room completely empty. Again in level 8. Happened by chance?
![empty](https://user-images.githubusercontent.com/45902449/146978572-810c964e-0041-47d7-ac98-76570743d5fb.png)
[empty.zip](https://github.com/diasurgical/devilutionX/files/7757230/empty.zip)

**Comment by AJenbo** [comment]
Could someone test the offending save games in vanilla :)

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/161429612-d923df1c-9f42-4536-968b-341d2a1585a4.png)
Confirmed empty in original hellfire

**Comment by AJenbo** [comment]
Thanks :)
