### ISSUE TITLE
Mouse pointer jumps on choice between Hellfire and Diablo

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#3812]
When choosing between Hellfire and Diablo, the mouse pointer jumps up a little.

To reproduce delete diablo.ini and start the game.

You will notice that the mouse pointer jumps a little higher after the selection.

**Comment by AJenbo** [comment]
This where changed a bit so I don't think this applies any longer, since you do not stay on the screen after choosing. 

After the video has played the mouse will be moved to the center of the screen, but this doesn't sound like what you are describing?
