### ISSUE TITLE
Town loading image is not shown. (SDL1/BigEndian/Amiga)

### ISSUE THREAD

**Issue by arczi84** [diasurgical/devilutionX#382]
On current master town loading image is not shown.
![image](https://user-images.githubusercontent.com/3505526/67189783-24b3b080-f3ef-11e9-9c43-e38372d1cb82.png)

> $ git log
> commit 56f953b (HEAD -> master, origin/master, origin/HEAD)
> Author: Gleb Mazovetskiy glex.spb@gmail.com
> Date: Sun Oct 20 18:59:17 2019 +0100
> 
> sdl2_to_1_2_backports.h: Add missing #include
> commit 0d7f876
> Author: Anders Jenbo anders@jenbo.dk
> Date: Sun Oct 20 19:23:20 2019 +0200
> 
> Remove width from info panel sy value
> 
> This was left behind when doing 337bc9b125ec5449c54ee8b0780d1722c41afaac

**Comment by arczi84** [comment]
Also HUD is not updated on gamma change, moving mouse over updates it.
![image](https://user-images.githubusercontent.com/3505526/67190094-a4417f80-f3ef-11e9-8631-863f7cd5dc2e.png)

**Comment by arczi84** [comment]
Done.

**Comment by AJenbo** [comment]
Please make sure both of thease lines are applied on your branch:
https://github.com/diasurgical/devilutionX/blob/master/Source/init.cpp#L56

**Comment by arczi84** [comment]
Right.
