### ISSUE TITLE
Error building on OS X (Catalina)

### ISSUE THREAD

**Issue by Nanoc-ice** [diasurgical/devilutionX#3823]
OS X Catalina
DevilutionX 1.3.0 
clone and trying to build
All dependencies installed via brew

did brew install bundle successfully
then followed the instructions for a Mac:
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
cmake --build build -j $(sysctl -n hw.physicalcpu)

while running make I get an error building multi.cpp:
...
[ 50%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/inv.cpp.o
[ 50%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/itemdat.cpp.o
[ 50%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/items.cpp.o
[ 50%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/lighting.cpp.o
[ 50%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/loadsave.cpp.o
[ 51%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/menu.cpp.o
[ 51%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/minitext.cpp.o
[ 51%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/misdat.cpp.o
[ 51%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/missiles.cpp.o
[ 51%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/monstdat.cpp.o
[ 52%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/monster.cpp.o
[ 52%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/movie.cpp.o
[ 52%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/msg.cpp.o
[ 52%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/multi.cpp.o
[ 53%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/nthread.cpp.o
/Users/greggjensen/dev/devilutionX/Source/multi.cpp:690:54: error: expected
      expression
                sgGameInitInfo.versionMajor = PROJECT_VERSION_MAJOR;
                                                                   ^
/Users/greggjensen/dev/devilutionX/Source/multi.cpp:691:54: error: expected
      expression
                sgGameInitInfo.versionMinor = PROJECT_VERSION_MINOR;
                                                                   ^
/Users/greggjensen/dev/devilutionX/Source/multi.cpp:692:54: error: expected
      expression
                sgGameInitInfo.versionPatch = PROJECT_VERSION_PATCH;
                                                                   ^
[ 53%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/objdat.cpp.o
3 errors generated.
make[2]: *** [Source/CMakeFiles/libdevilutionx.dir/multi.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Source/CMakeFiles/libdevilutionx.dir/all] Error 2
make: *** [all] Error 2

**Comment by AJenbo** [comment]
Looks like you are not using git, or do not have the cli installed, please see https://github.com/diasurgical/devilutionX/blob/master/docs/building.md

**Comment by AJenbo** [comment]
Yeah this all matches what happens if you aren't using git. You should also have gotten this warning at the very start of the process:

```
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
CMake Warning at CMakeLists.txt:111 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.
```

**Comment by Nanoc-ice** [comment]
Did a shallow clone

**Comment by AJenbo** [comment]
Ok, well it needs enough commits to find the latest version tag. The whole repo is only 50mb so shouldn't be to bad :)
