### ISSUE TITLE
Translation Hellfire missing settings menu

### ISSUE THREAD

**Issue by hiperiondev** [diasurgical/devilutionX#3832]
The settings menu is not translated in Diablo/Hellfire (tested in Spanish)
The texts are not found in devilutionx.pot and es.po

**Comment by AJenbo** [comment]
In Poedit click update from from source:

![image](https://user-images.githubusercontent.com/204594/147170081-0bb5ad09-5de3-495c-bace-48d96c886a4f.png)

**Comment by hiperiondev** [comment]
Added pull request for missing translations in Spanish
