### ISSUE TITLE
In the settings menu not all texts are displayed correctly in translation

### ISSUE THREAD

**Issue by hiperiondev** [diasurgical/devilutionX#3834]
Some texts are shown below the scroll bar, another by the top and others are clipped to the next line.
Tested on Spanish translation.

**Comment by AJenbo** [comment]
Any chance you could post a screen shot of this :)

**Comment by hiperiondev** [comment]
![1](https://user-images.githubusercontent.com/17483817/147185719-04b46879-a871-4775-afdd-181a6ffe804b.png)

![2](https://user-images.githubusercontent.com/17483817/147185734-2e7c95b7-141d-4272-8ce1-189b684f10ed.png)

![3](https://user-images.githubusercontent.com/17483817/147185739-dcde80c2-5c8f-4448-98ac-1923d19a1044.png)

**Comment by hiperiondev** [comment]
I understand that the texts can be shortened but I think it is a bug that behaves differently in each case

**Comment by ephphatha** [comment]
Screenshots 1 and 2 show the same behaviour, options entries are only allocated a single line so when they wrap they overflow the next line. There's a blank line as padding between sections which allows the line to be visible in shot 1, shot 2 ends up getting overdrawn by the next line (you can see the O character behind ap in "Lanzamiento Rapido").

Shot 3 is an interesting case, the way words are wrapped at the moment relies on them being drawn fully outside the containing rectangle. If characters at the end of a line overlap the in bounds area by even a pixel then they don't get wrapped.
![2021-12-28T233623_devilutionx](https://user-images.githubusercontent.com/357684/147567348-8076710c-5215-4e8a-8b98-406d39296428.png)
The red box is the containing rectangle for settings menu items, the S at the start of the line and M at the end of the line are drawn partially out of bounds.

The left boundary isn't calculated properly either, characters at the start of a line are free to wander left as far as necessary as if the text fit on a single line.
![2021-12-28T234018_devilutionx](https://user-images.githubusercontent.com/357684/147567327-f8a06689-dea7-44f6-9560-4e24774a4a21.png)

**Comment by hiperiondev** [comment]
> Screenshots 1 and 2 show the same behaviour.

Not exactly the same, I think. In the first screen "Titulo" is wrapped after "Tit", not overlapped in any letter nor missing. In the second screen "Apagado" miss the last letter.

**Comment by ephphatha** [comment]
![image](https://user-images.githubusercontent.com/357684/147861524-6f43ef21-0488-44eb-b54c-f89cc54caa89.png)
The O is getting overdrawn with the next line, it's visible where the cursor is pointing in this screenshot.

Definitely still a bug though, need to rework text rendering so that it wraps as expected and also the way the settings menu is drawn so it handles multi-line options.

**Comment by AJenbo** [comment]
we could use a smaller font
