### ISSUE TITLE
gamecontrollerdb.txt not working

### ISSUE THREAD

**Issue by 25minutes** [diasurgical/devilutionX#3849]
I have followed the instruction in https://github.com/diasurgical/devilutionX/wiki/Retropie-Guide (with some changes to folder locations) to add devilutionX on Pi3B. I can set SDL_GAMECONTROLLERCONFIG environment varible to make controller work properly, but if I simply use gamecontrollerdb.txt, the controller doesn't work.

I've put gamecontrollerdb.txt in following locations:
- ~/.config/SDL-GameControllerDB/gamecontrollerdb.txt
- in same folder as the bin file (devilutionx), with a symbolic link to ~/.config/SDL-GameControllerDB/gamecontrollerdb.txt
- in data-dir folder where diabdat.mpq resides, with a symbolic link to ~/.config/SDL-GameControllerDB/gamecontrollerdb.txt
- save-dir and config-dir are configured to be the same as data-dir, so it also has a symbolic link to ~/.config/SDL-GameControllerDB/gamecontrollerdb.txt

However, it seems devilutionX just cannot load the setting from gamecontrollerdb.txt. What do I miss?

**Comment by AJenbo** [comment]
I don't see any references to a gamecontrollerdb.txt anywhere in the link you posted or anywhere else in our documentation, so I'm not really sure what you are expecting here.

If you prefer to have the mapping in a file rather then as an enviroment variable then add it to the ini: https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide#mapping
