### ISSUE TITLE
Some sub-menus/movies act on mouse-down, leading to unintended menu item interaction on release

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#3850]
**Important information**
Windows 11 / DevilutionX since https://github.com/diasurgical/devilutionX/commit/d1315e934aa26a49ac5dd598090cc3ec9b734ad2 / compiled

**Describe**
Some menu actions (notably skipping a movie) occur on mouse down, which has an unfortunate interaction with certain actions which now trigger on mouse up. Skipping the splash screen by clicking will often put the player straight into multiplayer as that's the closest option to the center of the screen on the main menu. Cancelling out of that submenu often quits the game as the cancel text (triggered on mouse down) overlaps "Exit Game" (triggered on mouse up).

**To Reproduce**
1. Launch devX
2. Get to the main menu
3. Click on "Support"
4. Without moving the mouse, click to exit the text scroll.
5. The main menu flashes up, the mouse up event is processed, and the support text scroll starts again.

**Expected behavior**
To be back at the main menu.

**Screenshots**
https://user-images.githubusercontent.com/357684/147460560-49979a80-dbcf-493d-84db-4cef4f367f71.mp4

**Additional context**
I think acting on key/mouse up is the expected behaviour, it's how most applications behave that I've used. I don't mean to blame the commit I've referenced as the fix is correct. I'm using it as an example because it's made the inconsistent handling of menu interaction more visible.

**Comment by AJenbo** [comment]
this was introduced with the workaround for a bug in sdl on ios https://github.com/diasurgical/devilutionX/issues/3788
