### ISSUE TITLE
libpng CMakeLists logical block mismatch

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#3851]
**Important information**
Windows (MinGW) test builds

**Describe**
The following warning appears when testing MinGW builds.

```txt
CMake Warning (dev) in build/_deps/libpng-src/CMakeLists.txt:
  A logical block opening on the line

    /home/runner/work/devilutionX/devilutionX/build/_deps/libpng-src/CMakeLists.txt:275 (if)

  closes on the line

    /home/runner/work/devilutionX/devilutionX/build/_deps/libpng-src/CMakeLists.txt:471 (endif)

  with mis-matching arguments.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**To Reproduce**
Try running a MinGW build. You should see the message pop up during the CMake configure step.

Alternatively, just check the output for the `Configure CMake` step in the latest Windows_x64 test build.
https://github.com/diasurgical/devilutionX/runs/4635912144?check_suite_focus=true

**Expected behavior**
The `if()` and `endif()` conditions should match. Considering that the `IOS` flag was added to the `endif()` in https://github.com/diasurgical/libpng/commit/062dbf095f84b6db90d13e820fb60ec4ed545639, I suspect it should also need to be added to the if statement. Does the iOS build have issues with libpng that could be solved by fixing this?

**Comment by glebm** [comment]
The actual upstream PR does not have the `IOS` in the endif: https://github.com/glennrp/libpng/pull/403/files, so I think this was a git accident

**Comment by glebm** [comment]
The commit that we're missing is this one https://github.com/glennrp/libpng/commit/5e8b45c436c1c1bef18b3a8e18b4f0b980e946fc
