### ISSUE TITLE
Dupe Detection Bugged

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#3854]
**Important information**
Windows 10 / Commit 1c25cb4b / Compiled myself

**Describe**
Dupe detection not working (Run as Diablo instead of Hellfire)

**To Reproduce**
1. Drop 2 identical items

**Expected behavior**
Dupe detection should remove the first dropped item.

https://youtu.be/nk9QZDw4xpY

**Comment by AJenbo** [comment]
There is no dup detection in devilutionx
