### ISSUE TITLE
Can't find the Ring of Engagement

### ISSUE THREAD

**Issue by Canaan-2** [diasurgical/devilutionX#3857]
Hi everyone. Here's a bug I'd like to report.

**Important information**
Operating system : Mac OS Catalina version 10.15.7 / DevilutionX version : 1.2.1 / did you download a release or did you compile yourself? I downloaded the release.

**Describe**

The issue is that I've been trying to find the ring of engagement (roe) several times, thinking I'd have a good shot. Instead, I've found the gladiator's ring I would guess over 10 times (under devolutionx version 1.2.1). This doesn't make sense because according to Jarulf's guide, the roe should be found on average once every few games, whereas the gladiator's ring should be found once every 150 or more games. I expected to have found at least one roe by now, but couldn't.

Not sure if this has already been addressed, but a readme from an unofficial patch released in 2003 states : 

"RINGS.

These were an absolute MESS. There were SEVEN qlvl 8 unique rings, two qlvl 1s, a qlvl 2, a qlvl 5, a qlvl 10, and a qlvl 11. On top of that, they were positioned in the code so wrongly that Gladiator's Ring (qlvl 10) would override Ring of Engagement (qlvl 11) despite the latter having the higher qlvl. This mess has been cleaned up. "

link to the readme : http://www.lurkerlounge.com/lemming/hffreadme.htm#ver

**Additional context**

- Not sure if that that makes a difference, but I pulled diadat.mpq directly from the windows version CD, same for hellfire.mpq and related mpqs. I did not download from gog.
- I've since upgraded to version 1.3.0 about a week ago and I have since found one gladiator's ring on dlvl4, but no roe yet. 

Thanks guys

**Comment by qndel** [comment]
Dunno how posting a readme from some random mod is supposed to be relevant

**Comment by Canaan-2** [comment]
The quote I added made reference to  the gladiator’s ring somehow overriding roe in original Hellfire despite the roe qlvl being higher. Not sure how that’s not relevant.

**Comment by AJenbo** [comment]
Changing how the items drop work can cause existing savegame items to morph which makes it impossible for us to correct. There are also other issues with some of the unoptainable uniques that makes soving it seam like a bad idea.

I know that the the unofficiall patch mod referes to us as a recommended replacement so it can seam that we might have the exact same changes as they do, but our goals are a bit different. We do not change things for balance, or break backwards comparability.

**Comment by Canaan-2** [comment]
I appreciate your clarifications. Of course, I'm not suggesting to change things for balance like the modders do, nor change anything original hellfire purists might not want to see, I just wanted to point out this bug because, as I'm sure you're well aware of, the reason many unique items are unfindable, is because the same qlvl is found on multiple items of the same type.

This is not the case with the roe. The reason the roe is unfindable is, and correct me if I'm wrong, a rare case, because not only does it have a different qlvl (qlvl 11) than the gladiator's ring (qlvl 10), it has the highest qlvl of all rings, and it still won't drop in a game of hellfire (not for me anyway).

The reason for this post is simply to bring to your attention this one-off in case you weren't aware of it (and I don't doubt that you were aware of it), and to see if there's anything you guys can do to fix it without breaking backwards compatibility. If a fix is not possible without compatibility issues, well at least we tried/we exchanged ideas, and we move on to the next case.

**Comment by qndel** [comment]
It always picks the last matching item from the list and since gladiator's ring has lower qlvl and is after ring of engagement, it means that if the game can generate a ring of engagement, it can generate gladiator's ring and it will always be the one picked.

Quick test with `dropu ring of eng` debug command in multiplayer
![image](https://user-images.githubusercontent.com/14297035/147732276-1620e1fd-4c68-4525-95ce-fc49df67b14d.png)
The PR I linked above fixes this situation by picking a random one from the list, not always last.

**Comment by Canaan-2** [comment]
cool
