### ISSUE TITLE
Languages can't be translated

### ISSUE THREAD

**Issue by hiperiondev** [diasurgical/devilutionX#3881]
Language names are not found in the translation po file and cannot be translated.

![Languages](https://user-images.githubusercontent.com/17483817/147860775-1aebabc9-28c7-4b5e-96f7-a5eabd54397f.png)

**Comment by hiperiondev** [comment]
I think may be a good change show every name in the original translation (best in more than one ex: English or translated to actual language and native). Not all knows how your native language is named in other languages.

Here are a list of all of them:
https://www.internationalphoneticalphabet.org/languages/language-names-in-native-language/

**Comment by ephphatha** [comment]
I have a branch which does this but Korean, Japanese, Chinese scripts use characters from a very large set that is distributed separately. This causes them to not render unless the player also has fonts.mpq available. Displaying the names in both english and autonyms is still possibly nicer, Simplified Chinese would display as "汉语 (Simplified Chinese)" for people with fonts.mpq, "   (Simplified Chinese)" for people without.
