### ISSUE TITLE
DevilutionX Android  User Interface and Items with 1 durability

### ISSUE THREAD

**Issue by Connaiseur** [diasurgical/devilutionX#3886]
The default user interface for DevilutionX android should be exactly as diabloweb since most android devices are touch and the diabloweb interface for touch is magnitudes better then whatever you are using now which seems more optimized for a controller.  Also provide option in main menu to switch between the two interfaces for all versions of devilutionX or load devilution launch screen each time to ask the preferred interface.

This is absolutelly and fundamentally required.  I will simply delete devilutionx once again should this change not be implemented. 

 Also it would be awesome if you had a hero editor within devilutionx.  Ie i had the thinking cap but due to a moment of profound stupidity and inattention, i saved whilest it had been destroyed.  Really all items of 1 durability should be amended to 2 durability for that reason alone.  And to add to insult i had found the hidden shrine and was just about to use it.

**Comment by AJenbo** [comment]
Closing since this seams more of an opinion and is describing several unrelated things.

**Comment by qndel** [comment]
@Connaiseur `I will simply delete devilutionx once again should this change not be implemented.` good riddance, bye
