### ISSUE TITLE
custom path for mpq files (android 11)

### ISSUE THREAD

**Issue by mrdeathjr28** [diasurgical/devilutionX#3892]
**Important information**
Android 11

**Describe**
default path for mpq files (Android/data/org.diasurgical.devilutionx/files) is non writable on android 11

**To Reproduce**
try copy files to default location (Android/data/org.diasurgical.devilutionx/files) but on android 11 this is not allowed

**Expected behavior**
mpq files must copied with issues to default folder (Android/data/org.diasurgical.devilutionx/files) but storage in android 11 is a huge mess

**Additional context**
other apps use folder directly on sd root example Android/appnamefolder for save app settings and other things, again thanks google for your huge storage mess in android 11

**Comment by StephenCWills** [comment]
This is no longer possible as of November 2021. Google now requires app updates on Google Play to target SDK 30, which heavily restricts the way apps can request file permissions. At the moment, the best recommendation I can give would be to download a third party file management app, such as Total Commander. File management apps are now being scrutinized by Google so they can be explicitly granted permission to request access to files outside their data directories.

**Comment by AJenbo** [comment]
The recomended way is to access the folder from you computer via USB which will give the computer write access to the folder.
