### ISSUE TITLE
Language audio patches not loaded

### ISSUE THREAD

**Issue by john-tornblom** [diasurgical/devilutionX#3919]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
master branch compiled on ubuntu 20.04 (x86_64)

**Describe**
I have used my own patch_rt.mpq with Swedish audio in the past. Recently, the mechanism to load patch_rt.mpq was removed, in favor of language-specific patches, e.g., sv.mpq. Hence, I renamed patch_rt.mpq to sv.mpq, but archives are initialized before user options, so the language code is set to the emtpy string and a file called ".mpq" is loaded instead.

**To Reproduce**
1. launch with --verbose flag
2. Note the log message "VERBOSE: Missing: .mpq"

**Expected behavior**
Language patches are loaded (and unloaded) when the language option changes (either during init, or when a user changes the language from the Settings menu)

**Additional context**
Quick workaround: name the file ".mpq" instead of "patch_rt.mpq"

**Comment by AJenbo** [comment]
rename it to sv.mpq and set your langauge to sv

**Comment by AJenbo** [comment]
Thanks, i was curious why it had started loading .mpq instead of the language
