### ISSUE TITLE
cmake -DDISABLE_ZERO_TIER=ON does not work anymore

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#3925]
**Important information**
8bf05571a10f702c7d4359505b88f91cf9ea56aa Debian Sid amd64

**Expected behavior**
Be able to exclude non-FOSS ZeroTier lib

**Comment by StephenCWills** [comment]
Does not work how? Do you receive an error? I tested the build myself just now on Debian Bookworm and encountered no issues.

**Comment by licaon-kter** [comment]
It builds ZeroTier...

**Comment by StephenCWills** [comment]
Sure, but how are you confirming that? I see no trace of ZeroTier on my system.

```
$ ls _deps
asio-build     libmpq-src           libsmackerdec-subbuild  simpleini-build
asio-src       libmpq-subbuild      sdl_audiolib-build      simpleini-src
asio-subbuild  libsmackerdec-build  sdl_audiolib-src        simpleini-subbuild
libmpq-build   libsmackerdec-src    sdl_audiolib-subbuild
```

**Comment by licaon-kter** [comment]
```
devilutionX on  master [!?] 
➜ ls _deps
asio-build     libfmt-subbuild  libsmackerdec-build     libzt-src           sdl_audiolib-subbuild  simpleini-src
asio-src       libmpq-build     libsmackerdec-src       libzt-subbuild      sdl_image-src          simpleini-subbuild
asio-subbuild  libmpq-src       libsmackerdec-subbuild  sdl_audiolib-build  sdl_image-subbuild
fmt-subbuild   libmpq-subbuild  libzt-build             sdl_audiolib-src    simpleini-build
```

**Comment by StephenCWills** [comment]
Yes, `libzt` is the ZeroTier library. There are a couple things you can do to troubleshoot.

1. Search your `CMakeCache.txt` file for `DISABLE_ZERO_TIER` to verify that the value is `ON`.
2. Delete the `libzt-*` folders in that directory and run CMake again to reconfigure the project. If the folders come back, then CMake is indeed still including ZeroTier in your build.

**Comment by licaon-kter** [comment]
`cmake -S. -Bbuild .. && cmake -DDISABLE_ZERO_TIER=ON -DCMAKE_BUILD_TYPE=Debug`: https://gist.github.com/licaon-kter/5011a04f87f645256186a474352226b1

Then `cd build && make` starts with:
```
[  1%] Building CXX object _deps/libzt-build/CMakeFiles/zt_pic.dir/src/Central.cpp.o
[  1%] Building CXX object _deps/libzt-build/CMakeFiles/zt_pic.dir/src/Controls.cpp.o
...
```
And the game has this:
![devilutiondisablezt](https://user-images.githubusercontent.com/2282799/148658373-750c1cde-38bc-41c5-abec-a445674f2ecc.jpg)

I deleted `build` before testing:
> grep ZERO CMakeCache.txt      
`DISABLE_ZERO_TIER:BOOL=ON`

> grep ZERO build/CMakeCache.txt 
`DISABLE_ZERO_TIER:BOOL=OFF`

**Comment by StephenCWills** [comment]
`cmake -DDISABLE_ZERO_TIER=ON -DCMAKE_BUILD_TYPE=Debug` is malformed. You need to specify the source and build directories every time you run `cmake`.

**Comment by licaon-kter** [comment]
>  Delete the libzt-* folders in that directory and run CMake again to reconfigure the project. 

Ok, this fixed it...

> You need to specify the source and build directories every time you run cmake

I guess it evolved to malformed from the past line that I used to the current build instructions.

> I'm unsure what the function of .. is in cmake -S. -Bbuild .. 

Not something that I invented, for sure.(eg. https://github.com/diasurgical/devilutionX/commit/c066a3d56d7a08543841ad0478709a64338af488#diff-af936db1633489b017d1e45a55448545529ebc354aeb40eda83af5db7317a6e1L31 )

Anyway, yes, now ZT is not build... it fails elsewhere later :) :)

**Comment by AJenbo** [comment]
> > I'm unsure what the function of .. is in cmake -S. -Bbuild ..
> 
> Not something that I invented, for sure.(eg. [c066a3d#diff-af936db1633489b017d1e45a55448545529ebc354aeb40eda83af5db7317a6e1L31](https://github.com/diasurgical/devilutionX/commit/c066a3d56d7a08543841ad0478709a64338af488#diff-af936db1633489b017d1e45a55448545529ebc354aeb40eda83af5db7317a6e1L31) )

You combined `cmake ..` with `cmake -S. -Bbuild`, which is not something the instructions ever said to do. One was swapped for the other.

`cmake ..` = source is in the `../`, configure in `./` (which is why you need `cd build` first)

`cmake -S. -Bbuild` = source is in `./`, configure in `./build`

**Comment by licaon-kter** [comment]
Not sure how I ended up with those command lines. :) :(
