### ISSUE TITLE
iOS app doesn't shut down on exit

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#3940]
On my iPad, DevilutionX app does not close on Quit, leaving a black screen and requiring a manual close

**Comment by Trihedraf** [comment]
Happens for me as well.

**Comment by AJenbo** [comment]
Also happens on Android. I have been considering just removing the quit option for now.

**Comment by Trihedraf** [comment]
> Also happens on Android. I have been considering just removing the quit option for now.

Don't we have to have it initialize Diablo.ini? Because doesn't it only save when you quit?

**Comment by StephenCWills** [comment]
Yes, but we can fix that too.

**Comment by AJenbo** [comment]
Yeah now that options are all being initialized to there defaults up front we could simply save after loading the config if no ini file exists.
