### ISSUE TITLE
Localization string missing: "EXTRAS" on the main menu and "Game:" on main minimap

### ISSUE THREAD

**Issue by xGnoSiSx** [diasurgical/devilutionX#3970]
Hi,

I've started the Greek translation effort and I'm currently at 30%. I think I located 2 strings that are missing from the localization files:

1. the "EXTRAS" option in the main menu.
2. The "GAME:" String on the top left of the minimap layer before the password field.

**Comment by NikoVP** [comment]
The strings might be obsolete, and thus removed. Download the latest test build and check it there.

**Comment by xGnoSiSx** [comment]
> The strings might be obsolete, and thus removed. Download the latest test build and check it there.

I am working with the latest release, 1.3 and see the problems there. Do you issue a nightly build newer than this?

**Comment by xGnoSiSx** [comment]
Apologies, just found the test workflows on CircleCi. However it seems there's no windows target, only linux for desktop.

**Comment by ephphatha** [comment]
If you're running devilutionX on windows you can get a recent build from https://github.com/diasurgical/devilutionX/actions/workflows/Windows_x64.yml

**Comment by xGnoSiSx** [comment]
Thanks!

I'll check it out. BTW, I'm not sure if the Greek translation will make it for 1.4

**Comment by AJenbo** [comment]
Even more specific link: https://github.com/diasurgical/devilutionX/actions/workflows/Windows_x64.yml?query=branch%3Amaster+is%3Asuccess

If you wanted to translate 1.3.0 you should grab the po file from that tag. But obviously that isn't recommended :D

Regarding finishing the translation by 1.4, no worries, there is always 1.5 :)
