### ISSUE TITLE
On load game bought items from vendor reappear

### ISSUE THREAD

**Issue by finalclass** [diasurgical/devilutionX#3974]
**Important information**
linux / devilutionx@1.3.0 / downloaded the release

**Describe**
When you buy from a vendor, save the game, load it from save then the item still appears in vendor's store.

**To Reproduce**
1. Go to Adria
2. Buy some random a book
3. Save the game
4. Load the game
5. Buy the same book again

**Expected behavior**
The book should not reappear because it has already been bought.

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/issues/3172
