### ISSUE TITLE
Lazarus quest does not start

### ISSUE THREAD

**Issue by finalclass** [diasurgical/devilutionX#3979]
**Important information**
Linux / DevilutionX@master (commit: dcb376d2) / compiled myself

**Describe**
When you enter lvl 15, find the lazarus staff and come back to cain, then cain is not reacting.

**To Reproduce**
1. Go to level 15
2. Find staff of Lazarus
3. Go to Cain
4. Cain is not reacting
5. Red portal never opens

**Expected behavior**
Cain is reacting and red portal opens

I'm attaching my [save](https://github.com/diasurgical/devilutionX/files/7919097/single_0.hsv.zip) which leads to a single player game where my character (Sel=BH=) is in town and a town portal is opened to a Lazarus Staff.

**Comment by qndel** [comment]
Bisected to https://github.com/diasurgical/devilutionX/commit/5b21e0188fffd727aaa390fab8ba76208a0b72aa

**Comment by StephenCWills** [comment]
FYI, this has been fixed, but the quest state in the attached savegame has been corrupted. You will have to start a new game to complete the Lazarus quest.

**Comment by finalclass** [comment]
I can confirm, it is working fine now. Thanks
