### ISSUE TITLE
Bringing Magic Rock to Griswold does not trigger the quest

### ISSUE THREAD

**Issue by finalclass** [diasurgical/devilutionX#3985]
**Important information**
Linux / devilutionX@master (commit: dcb376d2) / compiled myself.

**Describe**
When you bring magic rock to griswold it should trigger the quest

**To Reproduce**
1. Go to Level 5
2. Find Magic Rock
3. Take it back to Griswold
4. Nothing happens

**Expected behavior**
Griswold is telling you something and then drops an "Empyrean Band".

![image](https://user-images.githubusercontent.com/1343930/150670703-3b00484d-5dd9-4eda-8e0b-5d3324e2e1b7.png)

**Comment by AJenbo** [comment]
you must first trigger the quest by visiting th ealier levels

**Comment by finalclass** [comment]
ok, thx. I really thought that it was not working like this in the vanilla but it was a long long time ago since I played it.
