### ISSUE TITLE
Shareware version with spawn.mpq is not working

### ISSUE THREAD

**Issue by john-tornblom** [diasurgical/devilutionX#3986]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Ubuntu 20.04 / 1.3.0 / released appimage

**Describe**
When using spawn.mpq, I get the follwoing error message:ERROR: SDL Error
drwav_init failed.

The error occurred at: /home/ajenbo/devilutionX/Source/sound.cpp line 176
INFO: SFileRwRead error: 128 1 ERROR CODE 1004
INFO: LoadArt("ui_art\black.pcx"): LoadPcxMeta failed with code 100

**To Reproduce**
1. wget https://github.com/diasurgical/devilutionX/releases/download/1.3.0/devilutionx-linux-x86_64.appimage
2. wget https://d07riv.github.io/diabloweb/spawn.mpq
3. chmod +x devilutionx-linux-x86_64.appimage
4. ./devilutionx-linux-x86_64.appimage

**Expected behavior**
The shareware version starts

**Screenshots**
N/A

**Additional context**
I compiled current master and experienced the same issue. I managed to bypass the problem by remove the check at Source/sound.cpp line 177. However, after creating a character, I get the following issue during the loading screen:

Sfx\Misc\BFire.wav

Felet uppstod vid: /home/john/devel/devilutionX/Source/sound.cpp rad 168
ERROR: OpenAsset failed
Sfx\Misc\BFire.wav

The error occurred at: /home/john/devel/devilutionX/Source/sound.cpp line 168

**Comment by AJenbo** [comment]
> wget https://d07riv.github.io/diabloweb/spawn.mpq

This is not the official shareware, the real one is about 64mb, this one is 25mb.

**Comment by qndel** [comment]
> > wget https://d07riv.github.io/diabloweb/spawn.mpq
> 
> This is not the official shareware, the real one is about 64mb, this one is 25mb.

Literally thought that'd be the case :D

**Comment by john-tornblom** [comment]
Baa, god damn it. Thanks

Btw, I've been trying to extract the file without using wine:

```
$ wget http://ftp.blizzard.com/pub/demos/diablosw.exe
$ 7z e -so /home/john/diablosw.exe '[0]' > diablosw.mpq
$ file diablosw.mpq 
     diablosw.mpq: MoPaQ (MPQ) archive

$ smpq -l diablosw.mpq 
         177 1970-01-01 01:00 File00000007.xxx
    50274091 1970-01-01 01:00 File00000012.xxx
      257536 1970-01-01 01:00 File00000004.exe
      147456 1970-01-01 01:00 File00000013.exe
       34816 1970-01-01 01:00 File00000001.exe
       66048 1970-01-01 01:00 File00000005.xxx
       86528 1970-01-01 01:00 File00000008.exe
       73216 1970-01-01 01:00 File00000011.xxx
       13824 1970-01-01 01:00 File00000009.xxx
         166 1970-01-01 01:00 File00000000.xxx
       61440 1970-01-01 01:00 File00000015.exe
      689152 1970-01-01 01:00 File00000002.exe
        8192 1970-01-01 01:00 File00000003.exe
       21570 1970-01-01 01:00 File00000014.xxx
       84992 1970-01-01 01:00 File00000016.exe
      229888 1970-01-01 01:00 File00000006.exe
       16384 1970-01-01 01:00 File00000010.xxx
```
But I cannot extract all files:
```
$ smpq -x diablosw.mpq 
smpq: diablosw.mpq: Error: Cannot read file `File00000007.xxx': (null)
smpq: diablosw.mpq: Error: Cannot read file `File00000012.xxx': (null)
smpq: diablosw.mpq: Error: Cannot read file `File00000005.xxx': (null)
smpq: diablosw.mpq: Error: Cannot read file `File00000011.xxx': (null)
smpq: diablosw.mpq: Error: Cannot read file `File00000009.xxx': (null)
smpq: diablosw.mpq: Error: Cannot read file `File00000000.xxx': (null)
smpq: diablosw.mpq: Error: Cannot read file `File00000014.xxx': (null)
smpq: diablosw.mpq: Error: Cannot read file `File00000010.xxx': (null)
```
Is there some compatibility issues between different versions I am not aware of?

**Comment by glebm** [comment]
You can get spawn.mpq from here https://github.com/d07RiV/diabloweb/raw/3a5a51e84d5dab3cfd4fef661c46977b091aaa9c/spawn.mpq

**Comment by ephphatha** [comment]
I'm getting the same error with spawn.mpq from diablosw.exe (from an install on win11, not extracted manually). titlemov.wav from spawn.mpq appears to be a 1322 byte MP3 file (from an install of diablosw.exe, but it's got the same md5 hash as the file linked by john-tornblom and glebm), titlemov.wav from diabdat.mpq is a 1168 byte RIFF wav file.

**Comment by AJenbo** [comment]
@ephphatha You must have used the tool created by the webdiablo project to convert you spawn.mpq to there format after extracting it. Please extract it anew and check again.
