### ISSUE TITLE
Sounds are at mixed volumes

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#40]
Setting the sound level doesn't affect the people in town, they still talk with full volume.

Also a more curious issue, attacking monsters from afar makes their death sounds more quiet and ranged monsters attacking are completely silent.
[muted_range.zip](https://github.com/diasurgical/devilutionX/files/2977447/muted_range.zip)

The attached save is at a room full of goat archers.

**Comment by AJenbo** [comment]
Did you have the volume at max when observing the issue with monster sounds? If not then it sounds like this from the release notes:
"Sounds fads too much over distance when the volume is lowered"

**Comment by predator8bit** [comment]
Sorry didn't notice that in the release notes, yes it was at a lower volume.

**Comment by predator8bit** [comment]
A good workaround for the time being is to set everything to max volume in-game and adjust the levels in the mixer on the OS. At-least that works on PulseAudio for me.

**Comment by AJenbo** [comment]
The dialog volume is now fixed.
