### ISSUE TITLE
Localization strings for quick chat messages (F9 to F12) are ignored

### ISSUE THREAD

**Issue by xGnoSiSx** [diasurgical/devilutionX#4002]
Version latest (1.3 after merge #3999 today)

I still get default english for those instead.

**Comment by AJenbo** [comment]
Probably you generated the ini file while the game was set to English, so the default messages where English when they where inserted.

**Comment by xGnoSiSx** [comment]
You are correct my friend.

Please delete this!

**Comment by AJenbo** [comment]
Can't delete, but already closed :)
