### ISSUE TITLE
Game crash in french with sorcerer 

### ISSUE THREAD

**Issue by 3v0k** [diasurgical/devilutionX#4018]
Hello

**Important information**
Windows 10 up to date
DevilutionX release 1.3.0
DIABDAT.MPQ from old officiel game iso

**Describe**
when i click on spells (sorts in french) the game crash but i don't have this problem in english

![](https://user-images.githubusercontent.com/59344354/151983402-a95cc2d0-5e04-43db-bf87-e195583d14c4.png)

**To Reproduce**
edit diablo.ini
and remplace en to fr
[Language]
Code=fr

thanks

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/issues/3793
