### ISSUE TITLE
selgame.cpp Loopback navigation issue

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#4020]
Win10 / compiled

1. create Loopback MP
2. pick Hero
3. on game difficulty screen change to a different difficulty selection
4. BUG: pressing ESC acts like Enter, creating a game.  Expected behavior: go back to "select connection" screen.

**Comment by ikonomov** [comment]
The issue only happens when picking an already created hero in step 2 above.  If I create a new hero, then ESC in difficulty selection screen works as normal.

**Comment by StephenCWills** [comment]
The issue seems to be somewhat intermittent. Sometimes it sends me back to the "select connection" menu, sometimes it doesn't.

When the error occurs on x64-Debug, I get sent back to the main menu.

When the error occurs on x64-Release, I get forced into a game as described in this issue.

**Comment by glebm** [comment]
I'm guessing this may have been fixed by #5226 or #5545

**Comment by AJenbo** [comment]
im kinda rewriting that part atm, but not going to object if someone gets to it first

**Comment by glebm** [comment]
Oh I was going through the 1.5 issues to see if there are any that we can close already

**Comment by AJenbo** [comment]
that might also be true :) @ikonomov can you test it?

**Comment by ikonomov** [comment]
> that might also be true :) @ikonomov can you test it?

Yep, it's fixed already!  :) closing...
