### ISSUE TITLE
 Setting strings from speedbook to spellbook (12 of them) do not use localization strings.

### ISSUE THREAD

**Issue by xGnoSiSx** [diasurgical/devilutionX#4035]
Just updated from the most recent build and merged in the new POT file for 1.4. I think there's a regression bug: Setting strings from speedbook to spellbook (12) do not use localization strings.
And it seems this was an issue in slightly older builds as well.

https://github.com/diasurgical/devilutionX/commit/2d6c602ef54cd84b6287a3b8af16bfc40183c761

https://cdn.discordapp.com/attachments/518541192993046562/939841723775975474/unknown.png

https://cdn.discordapp.com/attachments/518541192993046562/939841824934219816/unknown.png

**Comment by british-choi** [comment]
https://github.com/diasurgical/devilutionX/blob/9a2002e2009878c0a62af3e80b5eb9409f422732/Source/options.h#L572
index = -1 should be changed to index = 0.
