### ISSUE TITLE
Shift-swapping does not work as intended on Barbarian

### ISSUE THREAD

**Issue by sixcy** [diasurgical/devilutionX#4059]
**Important information**
Windows 11 Home / 1.3.0 / release

**Describe**
As a barbarian, when wearing a Mace + Shield, shift-swapping a Maul will remove (place back in the inventory) the Shield.
Similarly, when wearing a Maul, shift-swapping the Shield will remove the Maul.
It looks like the Barbarian got omitted from the shift-swapping logic

**To Reproduce**
See above.

**Expected behavior**
Shift-swapping in the above-presented scenarios should not result in the Shield getting removed, or the Maul getting removed.

**Screenshots**
https://cdn.discordapp.com/attachments/518541192993046562/942050888187539556/unknown.png
https://cdn.discordapp.com/attachments/518541192993046562/942050935419568238/unknown.png

**Additional context**
Playing Hellfire.

**Comment by AJenbo** [comment]
Barbarian can use them with 1 hand
