### ISSUE TITLE
Translation overlap graphic

### ISSUE THREAD

**Issue by hiperiondev** [diasurgical/devilutionX#4066]
In the game menu the translation "speed" overwrites the control bar (at least in Spanish) 

![speed](https://user-images.githubusercontent.com/17483817/154092416-f7250bd8-d788-4022-a361-0f3a4ed4ab67.jpg)

**Comment by qndel** [comment]
can't you make it shorter?

**Comment by hiperiondev** [comment]
I can use an abreviation (Vel. or veloc.). Not pretty but it works.
