### ISSUE TITLE
Trapped Chest's Missile Causing Crashes

### ISSUE THREAD

**Issue by Trihedraf** [diasurgical/devilutionX#4078]
Win11 / Current Master / Downloaded from test builds and self built. Both x86 mingw

When opening trapped chest the game crashes.

1. Go to Level 5 shortcut
2. Find trapped chest
3. Open trapped chest
4. Crash

Only occurs with #4056 .
I think it has do with the changes in missiles.cpp. Undoing just those changes stops the crashing.
@qndel maybe you have an idea as to what it is.

[multi_1.zip](https://github.com/diasurgical/devilutionX/files/8106081/multi_1.zip)

**Comment by qndel** [comment]
I'll test today, thanks for finding out :)

**Comment by qndel** [comment]
@Trihedraf does it only happen in multi? I've just opened a trapped chest in catacombs and everything worked fine ...
