### ISSUE TITLE
You can't talk with town people anymore after killing the butcher

### ISSUE THREAD

**Issue by sharp299** [diasurgical/devilutionX#408]
Describe the bug:
Once the butcher is killed you can't talk to no one you can click on them they will show you the options (gossip or other quest dialog) but they do nothing.

1. I deleted my character and recreated her (a Rogue) to get specific quests.
2. the quest pool must contain the Butcher and Poisoned Water Supply
3. kill the butcher and voila You can't talk to anyone anymore.

Expected behavior;
open dialog window after clicking gossip or the information of the quest selected

Additional context:

The first save game was create in the build https://github.com/diasurgical/devilutionX/archive/0.5.0.zip , and restarted (new game) in different builds from the master.

[savegame1.zip](https://github.com/diasurgical/devilutionX/files/3787853/savegame1.zip)

this second one is a clean version, it was created on the latest build from the master.  

[savegame2.zip](https://github.com/diasurgical/devilutionX/files/3787890/savegame2.zip)

NOTE : if you run the save-games in the web version of diablo the town people keeps the butcher option in their dialogs but in your quest log is not anymore.

**Comment by AJenbo** [comment]
To be more specific you can only tak to towneres if you have a quest, not specifically butcher. 

The web version is by a different developer and hasn't been synced with upstream for several months so has lots of issues.

**Comment by sharp299** [comment]
It seems complete every quest broke the game, not specifically the butcher... :/

**Comment by galaxyhaxz** [comment]
They all have very sour feelings about the butcher, especially after you bothered Farnham. Maybe they will talk later :P

**Comment by mmaret** [comment]
Should be fixed by https://github.com/diasurgical/devilutionX/commit/e79b1afe84015ccbf8dfeb1ec6e29186ad25f8c1

**Comment by sharp299** [comment]
it is fixed now!, thanks guys for the hard work and the time you have given to this awesome project!
