### ISSUE TITLE
EL font spacing is wrong in the main screen and in the in game dialogues [Localization]

### ISSUE THREAD

**Issue by xGnoSiSx** [diasurgical/devilutionX#4083]
The two, or single large fonts for greek in the main menu and in the game dialogues has improper or missing glyph spacing.

As you can see from the attached, you can't even make out seperate words. I assume the creator just copy pasted a single glyph width for everything and also inserted some error values as well!

I can't touch the space character because that's universal and will break all transations. I need to edit the glyph widths and reduce each value by 15-20%

The aim is not to make the font perfect, I just need to make words stand out - a few overlaps won't be noticeable, because right now it looks like ancient greek - unreadable! Yes, we didn't use spaces back then, but the language was different and the text was unambigious and easy to read without spaces!

This should be easy to do for me because:
1. The width should be more or less a single number copy pasted around for all 40-60? glyphs.
2. All valuse should be in a single location/file.

Can you please advise wich files and locations within them to change, and also point me to the compatible MPQ archive editor to test it nefore I push it?

I should make a PR for this fix immediately, since I'm pushing the GR translation PR as a beta now more or less.

Thanks!

![main menu spacing gr](https://user-images.githubusercontent.com/8305672/155141452-44eeb609-5ce6-4097-9c62-aa6dec6d201b.JPG)
![dialog spacing gr](https://user-images.githubusercontent.com/8305672/155141457-58aece2f-4806-4068-b99c-545da7ba1b72.JPG)

**Comment by AJenbo** [comment]
This is controlled by https://github.com/diasurgical/devilutionX/blob/master/Packaging/resources/assets/fonts/30-03.bin which needs to contain the pixel width of the 256 (one byte each, use a hex editor to edit binary files) symbols found in https://github.com/diasurgical/devilutionX/blob/master/Packaging/resources/assets/fonts/30-03.pcx

**Comment by xGnoSiSx** [comment]
Will work on it thanks!

**Comment by NikoVP** [comment]
Haven't we generated that whe we did the initial fonts? I have to check on that but currently don't have the time, due to personal reasons. I might have a way to generate those fast but need about a week or two to sort my stuff out...

**Comment by AJenbo** [comment]
Well it looks like we did do so for all but one font size. I could also do it, but "currently don't have the time, due to personal reasons" also applies to me :)

**Comment by xGnoSiSx** [comment]
> Haven't we generated that whe we did the initial fonts? I have to check on that but currently don't have the time, due to personal reasons. I might have a way to generate those fast but need about a week or two to sort my stuff out...

Please be my guest!

We're finishing up several things on the translation including QA and proofing and it will take us some time.

At best, this fix is needed for 1.4.

**Comment by xGnoSiSx** [comment]
> Haven't we generated that whe we did the initial fonts? I have to check on that but currently don't have the time, due to personal reasons. I might have a way to generate those fast but need about a week or two to sort my stuff out...

@NikoVP Any chance you had some progress with the fornt spacing?

**Comment by NikoVP** [comment]
@xGnoSiSx Hi, Ít's been a while since I´ve checked my files. I didn't remeber how exactly we've generated the files. I think @AJenbo made the bin files using cut and extracted batches of charactres. My asumption is probably some mistake occured on when taking the width values from these split files, or another possibility that  might have happened is @AJenbo forgot to remove/convert extra files used to preserve the count number from 100 to 0. Will try to resolve tonight with @AJenbo

**Comment by NikoVP** [comment]
![image](https://user-images.githubusercontent.com/60973634/159187422-2fae9c28-4c66-4c9d-9035-d959c6484d1d.png)
Hope this resolves it well.

**Comment by xGnoSiSx** [comment]
Many Thanks!!! this is perfect!!!
