### ISSUE TITLE
Multiplayer sync problems

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#4098]
**Important information**
Windows 10 / c6abd740 / compiled myself
**Describe**
In both ZeroTier and TCP:
Duplicate items drop in the dungeon, with the second one unable to be picked up for a brief time, and sometimes can be picked up later, or be picked up by the other person.
Sometimes items drop and are unable to be picked up by either player, and then vanish.
Frequent hourglass which is not seen in vanilla.

**To Reproduce**
Unable to reproduce, other than by standard gameplay co-op MP.

**Expected behavior**
Hourglass should occur at same rate as vanilla (which is rare) or less frequently.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://www.youtube.com/watch?v=aDNQJ6g6CuE)

**Comment by AJenbo** [comment]
This seams to be listing several issues, some I believe are vanilla, some can depend on your specific setup and there is little detail regarding the environment or what can affect it in various ways. As such it's going to be hard to work on this as an issue.

Also the video is over 8 minutes long, please post time codes for the relevant parts of it.

**Comment by AJenbo** [comment]
Both issues should now be resolved.
