### ISSUE TITLE
OpenBSD/amd64 build fixes (clang)

### ISSUE THREAD

**Issue by brynet** [diasurgical/devilutionX#413]
This is all that is required now to build on OpenBSD with default clang/libc++

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2e4d786f..9eb3b137 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -62,8 +62,12 @@ endif()
 
 list(APPEND CMAKE_MODULE_PATH "${DevilutionX_SOURCE_DIR}/CMake")
 
-if(${CMAKE_SYSTEM_NAME} STREQUAL FreeBSD)
+if(${CMAKE_SYSTEM_NAME} STREQUAL FreeBSD OR ${CMAKE_SYSTEM_NAME} STREQUAL OpenBSD)
   set(ASAN OFF)
+  set(UBSAN OFF)
+  add_definitions(-D_BSD_SOURCE)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DO_LARGEFILE=0 -Dstat64=stat -Dlstat64=lstat -Dlseek64=lseek -Doff64_t=off_t -Dfstat64=fstat -Dftruncate64=ftruncate")
 endif()
 
diff --git a/SourceS/miniwin.h b/SourceS/miniwin.h
index a2d0079f..94b5aa17 100644
--- a/SourceS/miniwin.h
+++ b/SourceS/miniwin.h
@@ -3,7 +3,7 @@
 #include <ctype.h>
 #include <math.h>
 // work around https://reviews.llvm.org/D51265
-#if defined(__APPLE__) || defined(__FreeBSD__)
+#if defined(__APPLE__) || defined(__FreeBSD__) || defined(__OpenBSD__)
 #include "macos_stdarg.h"
 #else
 #include <stdarg.h>
```

**Comment by AJenbo** [comment]
Please send a PR

**Comment by brynet** [comment]
I'm still a bit unfamiliar with GitHub workflow. I can try to do that if manually applying is too difficult, but it may take me some time.

**Comment by AJenbo** [comment]
1. Click Fork
2. Clone your fork to your local machine
3. Edit the code
4. Commit and push your changes:
```
git commit -am "Fix NetBSD build"
git push
```
Got to https://github.com/diasurgical/devilutionX and push the big green "Create Pull Request" button

**Comment by brynet** [comment]
Thanks. If I'm not mistaken, in order to push I'd need to create a fork of the project on my own GitHub account. Push my changes there. A lot of extra steps just to submit a one-off patch, especially for someone unfamiliar this ecosystem. I'll try to do that.. can't imagine futzing with the Web UI is any easier. But this is all my problem, sorry for the noise.

**Comment by AJenbo** [comment]
Maybe you will find something else to commit at a later point :)
I tihnk most of the hoops comes down to security btw

**Comment by AJenbo** [comment]
@brynet is the build instruction identical to FreeBSD?

**Comment by brynet** [comment]
> @brynet is the build instruction identical to FreeBSD?

It is not. This should be enough.

Installing Dependencies
  pkg_add cmake sdl2-mixer sdl2-ttf libsodium gmake

Compiling
   cd build
   cmake -DCMAKE_MAKE_PROGRAM=gmake ..
   cmake --build . -j $(sysctl -n hw.ncpuonline)

**Comment by AJenbo** [comment]
Still good to have the instructions for knowing how test it in the future.
