### ISSUE TITLE
Shifted Reflect sign

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4132]
The Reflect sign appears in a shifted kind.
After bisecting the issue is present since commit f4bce388754948927a010f483bbf643e69019847.
![screen00](https://user-images.githubusercontent.com/45902449/156940552-fb055252-73ab-4b65-9b1e-b81fe24e1c6b.png)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/8193419/single_0.hsv.zip)

I would like to thank you for all your efforts, even if something like this happens sometimes.

**Comment by qndel** [comment]
@glebm :D

**Comment by glebm** [comment]
Thanks for testing, reporting, and bisecting!
