### ISSUE TITLE
Arcaine's Valor - torches remain in the air

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4134]
In the quest for Arcane's Valor, the torches can get stuck in the air. This happens at the point where the wall disappears to open access to the Arcane's Valor. After that, the savegame is corrupted and the torches stay in the air forever.
I can't tell if it's a vanilla issue. After the savegame is already corrupted, it looks the same in vanilla anyway.
The question is whether it can be ensured that the wall will always disappear with the torches together.
![torches](https://user-images.githubusercontent.com/45902449/156940916-105e757a-fa52-4606-8f54-b37465a0977c.png)

Savegame:
[torches.zip](https://github.com/diasurgical/devilutionX/files/8193440/torches.zip)

**Comment by qndel** [comment]
how did u get that? looks all good to me
![image](https://user-images.githubusercontent.com/14297035/156942074-946281e4-0b05-4669-8f48-464ad7d968d6.png)

**Comment by Chance4us** [comment]
> how did u get that? looks all good to me ![image](https://user-images.githubusercontent.com/14297035/156942074-946281e4-0b05-4669-8f48-464ad7d968d6.png)

I don't know, it just happened at some point.

**Comment by qndel** [comment]
Any details? Was that save 100% devilutionx? U saved/loaded a lot? First playthrough? Anything xD

**Comment by Chance4us** [comment]
Was that save 100% devilutionx? >>>>> YES
First playthrough? >>>>> YES
U saved/loaded a lot? >>>>> Quicksaved at some few points
Maybe skipped some quests.
May not have completely cleaned the levels above.
The issue only came up once and I wondered -> Higher Power? Cosmic bit flip?

**Comment by AJenbo** [comment]
It looks like the level generator though this was a good wall for hanging a couple of torches.

![image](https://user-images.githubusercontent.com/204594/161439269-c425a48c-07cb-495e-9edf-47abc6e06c9b.png)

We could try to reset the level and see if the original game also places the torches. But we do allow for a slightly different object placement, so even if it doesn't then it won't be an indication of a bug (but if it does then we can would know that this is a vanilla issue).

The fix should be to not allow the level generator to place objects in areas that are build from presets.

**Comment by AJenbo** [comment]
This issue should be fixed, but we need to test to verify (reset the save game and re enter the level)

**Comment by Chance4us** [comment]
Could you attach the reset save game?

**Comment by FitzRoyX** [comment]
Surely we can close this one out now? I think we'd have seen many reports of floating torches in the past year if this hadn't been fixed. Fixed by https://github.com/diasurgical/devilutionX/pull/4572

**Comment by AJenbo** [comment]
![image](https://github.com/diasurgical/devilutionX/assets/204594/85647810-c88d-4ece-8692-b07054ae6544)
