### ISSUE TITLE
Extreme camera shaking after Diablo's death

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4135]
Everybody can experience extreme camera shaking after Diablo's death.
To reproduce, load the attached game and move the hero to the north direction.
This is also a vanilla issue.

https://user-images.githubusercontent.com/45902449/156942740-e0367611-2ae5-493c-815f-2903b3926c08.mp4

Savegame:
[shaking.zip](https://github.com/diasurgical/devilutionX/files/8193532/shaking.zip)

**Comment by qndel** [comment]
That's because diablo's death disables movement but that lock gets removed when you load the game = you aren't supposed to move when he's dying :D

**Comment by qndel** [comment]
No need for [vanilla] in title, we have labels for that ;)

**Comment by qndel** [comment]
> I don't think [Chance4us](https://github.com/Chance4us) has the option to apply labels

that's what we are for 🤪
