### ISSUE TITLE
Item/gold dupe with auric amulet

### ISSUE THREAD

**Issue by MaxAyam** [diasurgical/devilutionX#4150]
**Important information**
Operating system: Windows 10 / DevilutionX version 1.30 / did you download a release or did you compile yourself? Downloaded

**Describe**
Player A creates a multiplayer game.
Player B joins, drop an item X and pick it up.
Player A with 16 stacks of 10k gold and inventory full of random gears takes off his auric amulet. (doesn't need to be 16 stacks but not sure what amount triggered this bug)
A bunch of item X drops around Player B, some of them can be picked up by Player A.

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/158008166-10b02859-841e-4df5-8150-94b1dba8ce1f.png)
Looks like it still happens.

**Comment by qndel** [comment]
Nvm didn't have the commit with fix on my improved item dropping branch :D
