### ISSUE TITLE
Defeat Diablo while you are dead.

### ISSUE THREAD

**Issue by cw2k** [diasurgical/devilutionX#4158]
Well I was amazed that I can just win against Diablo when I'm dead.
Dunno if that is intended. I find it funny so I share it with you. 

Okay Just load this save game.
[single_1.zip](https://github.com/diasurgical/devilutionX/files/8247226/single_1.zip)
(put unzipped file in ~/.local/share/diasurgical/devilution/)

Left click to summon a golem, now just wait until Diablo kills you.
After screen gets red press esc to leave main menu and let the game running.
Diablo is still so busy with ya corpse it shouldn't take to long until the golem kills Diablo 
![image](https://user-images.githubusercontent.com/3834079/158227262-52c6245a-a8c5-4ce2-a2b2-d4a87b3fa858.png)
...and then wow you see the ending screen.

**Comment by qndel** [comment]
Yes that's indented
