### ISSUE TITLE
Bad item costs more than one piece of gold

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4163]
I noticed that one Hyena's staff of healing costs 114 gold pieces instead of only one piece of gold.
I know that harmful items usually only cost one gold when being sold.
I want to leave this topic here to clarify if it is a game design flaw.
Of course I also make the savegame available to you.
[item.zip](https://github.com/diasurgical/devilutionX/files/8257433/item.zip)

![item](https://user-images.githubusercontent.com/45902449/158478722-3dfd07e9-08ea-4e92-8a46-5dc51b140e60.png)

**Comment by qndel** [comment]
You should really join the discord ;) We've discussed this recently. Hyena's is not considered a cursed affix despite having a negative effect. It's not the only bug with affixes but we can't really touch them or all existing items would morph = not worth it.
