### ISSUE TITLE
Improved <1> and <+> display in the game

### ISSUE THREAD

**Issue by yahooboby** [diasurgical/devilutionX#4175]
Improved <1> and <+> display in the game

<1> often looks like in games;
<+> looks like a circle;
I modified 12-00.pcx with GIMP;
That makes it a little bit clearer;

![22](https://user-images.githubusercontent.com/72782990/159112694-4dd443ba-5985-4d3c-b4c5-acee1792a810.PNG)
![33](https://user-images.githubusercontent.com/72782990/159112695-53a82845-317b-411d-9975-a786012b6431.PNG)
![11](https://user-images.githubusercontent.com/72782990/159112699-e991c95b-7e62-4803-b184-1b805400396d.PNG)

This is the modified 12-00.pcx
![12-00](https://user-images.githubusercontent.com/72782990/159112840-2e7fea90-44f9-41a9-93ef-4a711e39c8a4.jpg)
Since PCX is not supported, change JPG to PCX after downloading

**Comment by yahooboby** [comment]
12-00.pcx
MD5: 351F6907782E2A56048A2CE2D394E23A
SHA1: 1E8D08843433CC125DEE4A17EEC0A968E414353E
CRC32: C91451CD

**Comment by AJenbo** [comment]
Your JPG is not valid, also JPG is the wrong format to use as it is lossy so is the wrong choose for graphics, especially palettede 8bit. Instead try PNG.

**Comment by yahooboby** [comment]
3 are modified effect drawings.
This is the original rendering
+ 15
![22](https://user-images.githubusercontent.com/72782990/159114016-021b6e59-0000-41fd-9d82-9154169117c0.PNG)

Please ask me again.
How to create the effect of this font with GIMP,
I'll tell you how to do it, because there are some fonts that are wrong,
It needs to be modified.
![11](https://user-images.githubusercontent.com/72782990/159114002-a9561bda-fa2a-4dd8-ad6a-b8ec627c838c.PNG)

**Comment by AJenbo** [comment]
There where some minor issues with the changes you made (`1` was wider and would also require changes to 12-00.bin, and `+` looked checkered and a bit to clean). So I made a new one based on your feedback:

First one is the current one, secound is yours and the 3rd one is the new one I have made.

![image](https://user-images.githubusercontent.com/204594/159114150-d16c9e26-3f6a-4f6e-90fe-394fc99f5658.png)

Hope that works for you :)

**Comment by AJenbo** [comment]
> Please ask me again. How to create the effect of this font with GIMP, I'll tell you how to do it, because there are some fonts that are wrong, It needs to be modified. ![11](https://user-images.githubusercontent.com/72782990/159114002-a9561bda-fa2a-4dd8-ad6a-b8ec627c838c.PNG)

Sorry I don't understand what you are trying to say? What effect? What issues?

**Comment by yahooboby** [comment]
Good ~
Can you change the modified 12-00.pcx and 12-00.bin
Put it up, and because I'm using GOOGLE Translate, so
The translation is not very clear, let me make it clear, I make a font,
Can't produce the effect of the above picture, all monochrome. Pure gold, pure black.
I want to make a font that has black borders. It's gold in the middle.
This is the original:
![11](https://user-images.githubusercontent.com/72782990/159114626-df5a100a-66d1-4927-b037-93dab3423c8d.PNG)
I made this. It's far from the original.
![44](https://user-images.githubusercontent.com/72782990/159114629-20b555ee-fa09-4752-ba78-33645f1fb9b0.PNG)
Can you tell me how to make fonts in GIMP?
Thank you ~

**Comment by qndel** [comment]
Join discord for questions like these or open a discussion.

**Comment by AJenbo** [comment]
> I'm using GOOGLE Translate

Ok. I will try to make my text easy to translated.

> Can you change the modified 12-00.pcx and 12-00.bin

It is already on GitHub: https://github.com/diasurgical/devilutionX/blob/master/Packaging/resources/assets/fonts/12-00.pcx

I changed `1` so that 12-00.bin could stay the same.

**Comment by yahooboby** [comment]
China cannot open a forum like discord.
Many forums, such as Google, youtube and Facebook, cannot be opened.
I can only ask questions here..

**Comment by AJenbo** [comment]
> I want to make a font that has black borders. It's gold in the middle.

Only the 12 size font was made in GIMP. I think what you are showing is a larger one? Can you let me know which file this is from?

**Comment by yahooboby** [comment]
12 is just an example,
Learn how to make these fonts.
Understand the manufacturing method. It's not difficult to make 24, 30 and 42

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/159115381-2471ffa4-cc5c-408a-b84f-dd5414873f7b.png)

This does not look like 12. Please tell me which one it is. If I don't know what it is then I can't help. I don't read the Chinese? so I don't know what symbol this is. I need to know either what file it is in, or you need to type it in text.

**Comment by yahooboby** [comment]
all-51.PCX(24 30 42 46)
关
中文：<十六进制：E5 85 B3>
english：<hexadecimal: E5 85 B3>
There is nothing wrong with this < 关 >,
I'm learning how to make
Let's talk about how to make it.

**Comment by AJenbo** [comment]
24/30/42/46 where made by @NikoVP using this PhotoShop template:

[template.zip](https://github.com/diasurgical/devilutionX/files/8308907/template.zip)

If you do it in GIMP you will have to come up with your own way, and they will look different.

This is the best I know how to do it using GIMP:

![image](https://user-images.githubusercontent.com/204594/159116402-f38610d4-5d91-40d0-9cd3-178b59a3a5a8.png)
(PhotoShop on the left. GIMP on the right)

1. Draw the shape with the font tool
2. Add noise to it with filter->noise
3. Select the shape (alpha to selection)
4. Grow selection 2 px
5. Make new layer under the font shape
6. Fill with dark color
7. duplicate layer
8. Use filter->distor->embos to make it 3D
9. set blend mode to overlay
10. adjust opacity
11. keep making adjustments until you like the result

**Comment by yahooboby** [comment]
Thanks~
