### ISSUE TITLE
Multiplayer Playtest issues

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4182]
- [x] #4184
- [x] #4187
- [x] When auto equiping items the other player will sometimes not see that it has been equiped
- [x] If network dies for player 1, player 2 is kicked and the game disapears
- [x] #4186
- [x] Sometimes a monster will be alive for player 2 but dead for player 1, player 2 is not able to target them. If player 2 changes levels the monster is corrected to being dead. Monster HP some times appear to stutter, this might be caused by syncing monster HP, and appears to maybe only be happening when both players are hitting the same monster.
- [x] The vegetable line is played when entering level 16
- [x] #4252
- [ ] Repair menu gives wrong text ("No requirements") when no items are repairable (can't reproduce)

**Comment by AJenbo** [comment]
- When auto equiping items the other player will not see that it has been equiped
- Sometimes player 2 can't pick items up (this might be the origina hellfire loot bug)
- Player 2 can't pickup gray suit (might be related to previous issue)
- When casting heal other there is no way to canel it if you don't have anyone to heal

**Comment by StephenCWills** [comment]
> Multiplayer: Loot drops 2x for the player that does not trigger the drop

> Sometimes player 2 can't pick items up (this might be the original hellfire loot bug)

I believe these two issues are related. Also, these were previously reported in #4098 with a video. I bisected the loot drop 2x issue to eeb9ac3.

**Comment by AJenbo** [comment]
- If network dies for player 1, player 2 is kicked and the game disapears

**Comment by AJenbo** [comment]
- When selecting Join in ZeroTier it says "Join TCP game", description says "enter IP or Hostname", should be "game id"

**Comment by AJenbo** [comment]
- Some times a monster will a live for player 2 but deat for player 1, player 2 is not able to target them

**Comment by StephenCWills** [comment]
> If network dies for player 1, player 2 is kicked and the game disapears

This appears to be intentional behavior.

https://github.com/diasurgical/devilutionX/blob/8424ad4c6d816de7da30991500b809363d9900c9/Source/multi.cpp#L283-L293

* `bGroupPlayers` is the number of active players
* `bGroupCount` is the number of inactive players
* `nLowestActive` is the lowest player index of all the active players
* `nLowestPlayer` is the lowest player index of all the connected players

Assuming a 2-player game, player 1 and player 2 are both connected. From player 2's perspective, player 1 is no longer active.

* `bGroupPlayers = 1`
* `bGroupCount = 1`
* `nLowestActive = 1`
* `nLowestPlayer = 0`

This hits the `bGroupPlayers == bGroupCount` and `nLowestPlayer != nLowestActive` branch which means `gbGameDestroyed = true` on line 287. I imagine this logic is meant to prevent situations where multiple instances of the game resume on separate clients as a result of network interruptions.

**Comment by AJenbo** [comment]
- Monster HP some times appear to stutter, this might be caused by syncing monster HP

**Comment by ephphatha** [comment]
> > Multiplayer: Loot drops 2x for the player that does not trigger the drop
> 
> > Sometimes player 2 can't pick items up (this might be the original hellfire loot bug)
> 
> I believe these two issues are related. Also, these were previously reported in #4098 with a video. I bisected the loot drop 2x issue to [eeb9ac3](https://github.com/diasurgical/devilutionX/commit/eeb9ac3303d890d77e122949280d990e1fe8644d).

I suspected the double drop could happen but didn't manage to trigger it when I was testing #3987. Would be useful to know which player entered the level first and which player is performing the killing blow.

**Comment by ephphatha** [comment]
> * Multiplayer: Hellfire Cow thinks he already gave player 2 the rune and the quest won't start

On this one, quest progression is (meant to be) synced between all players. If any player triggers the rune drop all players should get the quest entry in their log. If the controlling player for town (whoever entered town first) has the quest active and player 2 doesn't then it looks like a failed sync of quest state (probably while joining the game)

**Comment by AJenbo** [comment]
> I suspected the double drop could happen but didn't manage to trigger it when I was testing https://github.com/diasurgical/devilutionX/pull/3987. Would be useful to know which player entered the level first and which player is performing the killing blow.

It happens in both directions

**Comment by AJenbo** [comment]
- Nakrul does his Arow-smith line when unlocked in multiplayer
- The vegtable line is played when entering level 16

**Comment by AJenbo** [comment]
Alright that's all I noticed when playing a multiplayer session :)

**Comment by AJenbo** [comment]
> > If network dies for player 1, player 2 is kicked and the game disapears
> 
> This appears to be intentional behavior.

A bit unfortunate as you loos the game session as well as all loot in town, but at least now there is a stash :D

**Comment by StephenCWills** [comment]
> A bit unfortunate as you loos the game session as well as all loot in town, but at least now there is a stash :D

You're right. It might be a decent trade-off to risk duplicating the game session by forcibly setting player 1's state to disconnected when the TCP connection fails. I'll do a bit of testing and submit a PR for that.

**Comment by AJenbo** [comment]
Fyi this was a ZeroTier based game

**Comment by AJenbo** [comment]
> Nak-rul does his Aerosmith line when unlocked in multiplayer

This was simply because we had the Cow Quest enabled. I forgot that they where linked.

**Comment by AJenbo** [comment]
I think both the HP jitter and monsters being alive on one client but not the other where cause by the constant HP syncing, so I consider both as solved for now.

**Comment by AJenbo** [comment]
Things went smooth with the second play through. Only hick up was an odd instance where the repair menu showed some incorrect options. Unfortunately we didn't get a screen shot of it and I'm unable to replicate it, so unless someone can spot the issue we will probably ignore it for 1.4.0. The shops will probably be rewritten for 1.5.0 anyway.
