### ISSUE TITLE
Disable corner stone of the world in multiplayer

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4193]
I don't think there is any way to make this mechanic work in multiplayer.

- What happens if both players have an item on the corner stone?
- Should players be able to take others players items?
- The data is shared between multiplayer and singleplayer which will cause the item to morph.

**Comment by NikoVP** [comment]
Is it possible to make it so that the cornerstone room doesn't spawn in multiplayer games?

**Comment by AJenbo** [comment]
Yes, making a check here should be enough: https://github.com/diasurgical/devilutionX/blob/master/Source/drlg_l1.cpp#L1834
