### ISSUE TITLE
misc.cpp - CreateFileMappingA

### ISSUE THREAD

**Issue by VonKossa** [diasurgical/devilutionX#42]
Hi!

After compiling experimental 64bit version i get the following when running devilutionx binary. Known problem or something i do wrong?

DUMMY: CreateFileMappingA @ /devilutionX-master/SourceX/miniwin/misc.cpp:588
devilutionx: /devilutionX-master/SourceX/miniwin/misc.cpp:589: void* dvl::CreateFileMappingA(dvl::HANDLE, dvl::LPSECURITY_ATTRIBUTES, dvl::DWORD, dvl::DWORD, dvl::DWORD, dvl::LPCSTR): Assertion `hFile == (HANDLE)-1' failed.
Aborted

**Comment by AJenbo** [comment]
What platform and compiler are you using?
Both the Mac and Linux (Debian) builds are passing for 64bit so I would say this is unexpected.

**Comment by VonKossa** [comment]
Gentoo Linux x86-64
cmake 3.14.0
Gnu Make 4.2.1
GCC 8.2.0

**Comment by VonKossa** [comment]
I also tested to delete devilution directory under .local/share

**Comment by AJenbo** [comment]
@VonKossa could you give it another tire, I'm not sure it's fixed, but might be.

**Comment by VonKossa** [comment]
Same problem.
I configured it with this flag before compiling it if it has something to do with it:
cmake -DDEBUG=OFF ..

**Comment by AJenbo** [comment]
This should now be fixed. You may also want to run it with `-DBINARY_RELEASE=ON` (this will disable all debugging)
