### ISSUE TITLE
closing stash while holding an item

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#4205]
There is a possible scenario where the player can lose an item, being forced to exit the game: 
1. select and hold an item with the cursor from the stash
2. close the stash using ESC (or hitting C, Q, I or B) key but:
  A. inventory is full and can't place the item there
  B. tiles around the character are occupied with other items

**Comment by kphoenix137** [comment]
Additionally, this can happen if the ground array is full
