### ISSUE TITLE
Storage jumping back pages when taking item out of storage not on page 1

### ISSUE THREAD

**Issue by DrGonzo564** [diasurgical/devilutionX#4216]
**Important information**
Mac OS 12.3 / DevilutionX 1.4b /Compiled ( artifact came from this PR https://github.com/diasurgical/devilutionX/pull/4212 )

**Describe**
Storage will randomly jump back pages, this happens after I advance storage past page 1 and select and item from either storage or characters inventory. It always jumps back pages never forward.

**To Reproduce**
1. Go to Storage advance past page 1 of storage 
2. Select and item from storage page 2 or higher or select item from inventory 
4. Storage will jump back pages 

**Additional context**
iMac 2017 5K Radeon Pro 580 

https://user-images.githubusercontent.com/82344993/159404887-e66b3e0c-5b3a-4047-9a4d-27d28af84bbf.mov

**Comment by AJenbo** [comment]
Is there any chance that you are some how scrolling when you do this? I know mice on Mac are a bit special :)

**Comment by DrGonzo564** [comment]
> Is there any chance that you are some how scrolling when you do this? I know mice on Mac are a bit special :)

Welp..... yes thats the issue I guess i'm a bit special too :D user error not a bug :( the up and down motion on the mouse scrolls it left and right... sigh my bad... That other mouse issue I posted tho idk not scrolling when doing that one... lol

**Comment by AJenbo** [comment]
Ha ha, I'm glad we figured this one out :)
