### ISSUE TITLE
Cursor jumps to bottom right corner of screen when selecting item in inventory 

### ISSUE THREAD

**Issue by DrGonzo564** [diasurgical/devilutionX#4217]
**Important information**
Mac OS 12.3 / DevilutionX 1.4b / Compiled (Artifact came from https://github.com/diasurgical/devilutionX/pull/4212 )

**Describe**
When selecting an item from my inventory the cursor will jump to the bottom right corner of the screen 

**To Reproduce**
1. Go to inventory
2. Click on item
3. Cursor jumps to bottom right corner of screen

**Additional context**
5K iMac Radeon Pro 580 maybe issue because high DPI monitor 27" ??

https://user-images.githubusercontent.com/82344993/159406491-2656668b-e310-4b1e-ba6c-11bfba9e0369.mov

**Comment by bubio** [comment]
https://github.com/diasurgical/devilutionX/blob/af59f7e254b18ea47d98112b5e64778e46d97923/Source/utils/display.h#L93

There seems to be a problem with the scale value that can be obtained with the SDL_RenderGetScale function.
