### ISSUE TITLE
Duped and floating torn note

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4240]
Torn note is duped and floating in the air see below.
Bisected down to commit 4ff83431d223e4bbad1e889156e714c9faacb91a.

https://user-images.githubusercontent.com/45902449/160261564-51b3e039-6900-4ab1-a519-81e6c5fa8014.mp4

Savegame:
[torn_note.zip](https://github.com/diasurgical/devilutionX/files/8356567/torn_note.zip)

**Comment by AJenbo** [comment]
Thanks, we are getting close to the 1.4.0 release now :)
