### ISSUE TITLE
[gamepad] Inventory cursor missing

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4242]
Initially when utilizing the inventory the cursor can be missing or dark and stuck. This can be solved by moving the cursor. Probably replicating this may require the game to run in windowed mode and the cursor to start offscreen.

It also appears that the cursor does not snap to the first slot when opening the inventory, this may be the cause of the issue.

(this may or may not be related to the stash-gamepad branch)

**Comment by StephenCWills** [comment]
Confirmed this issue occurs in 9226f14 so it probably is not related to stash-gamepad.

It seems that in 1.3.0, the cursor snaps to the center of the window at startup. This doesn't seem to happen anymore.

**Comment by StephenCWills** [comment]
Bisected to 543f988

**Comment by glebm** [comment]
Hmm I can't reproduce this

**Comment by glebm** [comment]
Nevermind, reproduced
