### ISSUE TITLE
[gamepad] Enable use of targeted spells from the inventory

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4273]
A few spells can not be triggered from the inventory, there isn't any specific reason for this in most cases as they work without an  active target when using a gamepad.

https://github.com/diasurgical/devilutionX/pull/4266/files#diff-be3ecbe1ead4062ccd317dfeb0428b38adf3d54377059e602229c75bfc052da8R1813

**Comment by StephenCWills** [comment]
Part of the reason for this may be that the player cannot target monsters when the inventory is open (`pcursmonst` will always be -1). If I cast a scroll of lightning from my inventory, the spell will never attempt to target a monster.

**Comment by AJenbo** [comment]
That might be a fair reason, I was thinking it would give the player a way to cast the spell in the direction they are currently facing, even if there are monster around.
But we should defiantly remove the limitation from the town portal scroll and other scrolls that do not target monsters.
