### ISSUE TITLE
Destruction of savegames 

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4284]
Unfortunately, I can no longer narrow it down because the savegame below is already broken.
Savegame:
[disappear.zip](https://github.com/diasurgical/devilutionX/files/8389113/disappear.zip)

What happened?
1. Played the game and after killing the butcher, carried some items to town.
2. Sold some books to the witch
3. Bought a bow from Griswold
4. Items on the floor suddenly disappeared
5. Unable to right click/read the Book of Town Portal in inventory
6. If you left-click on the book, the book disappears in inventory

Approximately since when does the problem occur?
My last working configuration is commit 3c54925a84fed575579710530a62bfb914bac4e2

Is there a possibility that some subsequent commits might have affected the savegames?
If so, then there is an urgent need for action.

**Comment by AJenbo** [comment]
Thank for reporting. It was broken in https://github.com/diasurgical/devilutionX/commit/6a30cd39504d43f67fa6e699512dee39358db71a most of it should already be fixed. If possible please test again to verify if there are still some issues left.

**Comment by Chance4us** [comment]
The issue doesn't seem to come up anymore.
So I close and let you know if it happens again.
