### ISSUE TITLE
Full screen switching option menu does not appear in macOS

### ISSUE THREAD

**Issue by bubio** [diasurgical/devilutionX#4299]
**Important information**
macOS 12.3 / self build

**Describe**
Full screen switching option menu does not appear in macOS.

![issue_4299_1](https://user-images.githubusercontent.com/78299054/161377484-7bf0eb3d-aed7-42ec-834e-c5a5e1a7efef.png)

**Comment by bubio** [comment]
You are using TARGET_OS_IPHONE incorrectly.
It is always defined and must be determined by its value.

**Comment by ephphatha** [comment]
Looks like the hardware cursor related options also weren't appearing, I assumed those were caused by the same issue since they had the same guards. Hoping #4300 fixes it?

**Comment by bubio** [comment]
Both Fullscreen and Hardware Cursor are now displayed. (^.^)

![issue_4299_2](https://user-images.githubusercontent.com/78299054/161378707-95477f2d-8461-48fb-a105-83380d11f924.png)

**Comment by AJenbo** [comment]
thanks :)
