### ISSUE TITLE
Use Liberation Seriff as replacemenent for Times New Roman in credits

### ISSUE THREAD

**Issue by sheepo99** [diasurgical/devilutionX#43]
I'm aware this project is all about staying true to the original, but would it be possible to tell the GNU/Linux executable to use Liberation Seriff as a fallback for Times New Roman on the game's credits section? Both fonts are nearly identical to each other, and it would prevent users on GNU/Linux having to install non-free fonts in order to just see the game's credits properly. Future GNU/Linux packages could even require the font as a dependency, for this purpose.

**Comment by AJenbo** [comment]
Looks ok I think:
![image](https://user-images.githubusercontent.com/204594/54728479-668d2780-4b7e-11e9-9117-57b092ea0c6e.png)

I think now is a good time to do this, the ports are mature enough that they carry some of there own dependencies (a readme in the case of Linux), expect to see this font included in the next release. Thanks for the suggestion.

**Comment by AJenbo** [comment]
I think I found a better font:
![image](https://user-images.githubusercontent.com/204594/55664787-5f2f7480-5834-11e9-9958-2e895253e28f.png)
CharisSILB.ttf

**Comment by AJenbo** [comment]
Here is the original for comparison:
![image](https://user-images.githubusercontent.com/204594/55664861-ae29d980-5835-11e9-9b09-b7eb7870102c.png)

**Comment by sheepo99** [comment]
My suggestion is for you to look for a font with better Unicode Support. That font looks more metrically exact to times than Liberation Serif, but it will make it impossible to support, for example, Russian translation.

I would suggest you to test the following ones:

FreeSerif: best unicode support of all Times lookalikes
Linux Libertine: better unicode support than liberation, but still inferior to FreeSerif

**Comment by sheepo99** [comment]
My bad, it does appear Charis, does support Russian and Greek. No Hebrew though:

https://software.sil.org/charis/support/character-set-support/

I would still advise to test libertine and FreeSerif

**Comment by AJenbo** [comment]
The font is only used for the credits and one button, all other text is done via the UI or in-game pixel fonts that are limited to a subset of https://en.wikipedia.org/wiki/Windows-1250 and some times even https://en.wikipedia.org/wiki/ASCII (all in-game text) so before that is solved I don't see much point in looking for a credit front that supports Russian. You're however welcome to experiment with various fonts and report if you find one that looks good for the original text/render-style and also supports full Unicode.

**Comment by sheepo99** [comment]
As far as language support goes, I am perfectionist. Russian/Greek/Hebrew support is important because there is a good chance there will be fan translations made for these languages, and keeping the credits section in English would be lack of polish.

Moreover, with mod support coming through, modders might feel the need to use the font as well for their own projects.

Could you let me know how can I replace the font using a compiled version so I can test it? Is it a simple matter of replacing a font file and renaming it?

**Comment by AJenbo** [comment]
If you make a build of the current code then just rename the font to CharisSILB.ttf and place it next to the game program. If you are still running 0.3.1 then you will have to place it in this path `/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Bold.ttf` on Windows is would probably be on the same drive as the program is located `c:\usr\share\fonts\truetype\msttcorefonts\Times_New_Roman_Bold.ttf `.
