### ISSUE TITLE
Render PCX directly

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#4301]
We can reduce RAM usage / allocator pressure by rendering certain PCX graphics directly rather than converting them.

The largest file is `hf_logo1.pcx`. It is a 2.4 MiB PCX file without transparency (4.6 MiB as an SDL surface).

As we do not have to worry about clipping these, the rendering code can be quite simple.

**Comment by obligaron** [comment]
@glebm is this done with #4551? 🤔

**Comment by AJenbo** [comment]
Done and redon
