### ISSUE TITLE
No gold pickup sounds while opened inventory

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4326]
I noticed that there are no pickup sounds when the inventory is open.
I don't understand why I didn't notice it sooner, but it is what it is.
So I would like to share this discovery with you.

**Comment by qndel** [comment]
What pickup sounds?

**Comment by qndel** [comment]
I think that's by design, when you pick something up with inventory open, it goes to cursor, so it's not like you'd need a sound to help you notice that you got something in your cursor xD

**Comment by Chance4us** [comment]
> I think that's by design, when you pick something up with inventory open, it goes to cursor, so it's not like you'd need a sound to help you notice that you got something in your cursor xD

I found it strange that I don't hear the gold coins when I throw them on the floor.
Wouldn't it be better if we improve the design?

**Comment by AJenbo** [comment]
I like the way it currently work :)

**Comment by StephenCWills** [comment]
Good point with the gold coins. For items that go to the cursor, it's not a big deal, but it does feel a bit weird with gold since those don't go to the cursor.

**Comment by qndel** [comment]
> Good point with the gold coins. For items that go to the cursor, it's not a big deal, but it does feel a bit weird with gold since those don't go to the cursor.

It was described in PR with this feature.

**Comment by AJenbo** [comment]
> Good point with the gold coins. For items that go to the cursor, it's not a big deal, but it does feel a bit weird with gold since those don't go to the cursor.

That's fair enough. I only tested what happens if you have so much gold that the remaining ends up in the cursor :)
