### ISSUE TITLE
Key remapping for 'P' Pause

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#4329]
I was doing the keyboard controls wiki yesterday and I noticed that there are two keys mapped to pause the game in single player, the key Pause and P, but only Pause is configurable in the .ini.  It is a minor thing, but I think we should add a second "Pause Game" key mapping so that P can be remapped and used for something else especially now that we have 8 extra quick spell hotkeys.

**Comment by qndel** [comment]
Tbh I wouldn't allow remapping the "pause" key and only allow remapping P :D it'd be more logical

**Comment by ikonomov** [comment]
I agree, some keyboards also lack a Pause button, so it would still be useful to have an extra configurable button for it and also to able to have the vanilla key mapping.  No real reason to have the Pause button do anything but what it says on it :D ...there are plenty of other unused keys if needed
