### ISSUE TITLE
Stash: Shift-click on gold should move it to stash

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#4335]
Shift-clicking on gold with the stash open currently does nothing.

Perhaps it should move the gold to stash?

**Comment by qndel** [comment]
Quick transfer is ctrl + click, was this what you meant?

**Comment by AJenbo** [comment]
Idk, nothing else reacts to shift+click, but ctrl+click works to transfer gold.

**Comment by qndel** [comment]
Quick transfer is ctrl + click, shift + click is autoequip :)

**Comment by glebm** [comment]
Ah, right, thanks!

**Comment by glebm** [comment]
First time play-testing the stash :)
