### ISSUE TITLE
Advocates/Counselor behaviour and teleport is not like it was in Diablo - they stay invisible, and more.

### ISSUE THREAD

**Issue by xGnoSiSx** [diasurgical/devilutionX#4340]
1. In the original diablo they couldn't stay phased out, now it seems like they can. And the golem keeps attacking the air.
2. the mob type in general does not follow/hunt the player. I noticed this with 3-6 of them, as they stayed clustered. The original D1 strategy to 'trigger' them and have them follow you around corners doesn't work at all. they stay put, even if they are dozens of them.

The above standed out enormously in hell/hell, with the triple immune advocates, which you have to single out and kill, especially for a wizard, using SC, golem and/or a sword. 

You can tp in a quadrant on  lvl 16 hell that has a dozen of them, have hundreds of fireballs thrown at you, but none will follow you/hunt you to your safe space.

Also, I was able to target the phasing mages with stone curse, but in this version, they must be fully phazed in for the curse to work.

**Comment by AJenbo** [comment]
Tested using 73194b58a9ee42f8432ac2989d0a9bba723e6296 on level 16

> In the original diablo they couldn't stay phased out, now it seems like they can.

Unable to reproduce

> And the golem keeps attacking the air.

Unable to reproduce

> the mob type in general does not follow/hunt the player. I noticed this with 3-6 of them, as they stayed clustered. The original D1 strategy to 'trigger' them and have them follow you around corners doesn't work at all. they stay put, even if they are dozens of them.

Advocates/Counselor never followed the player when the line of sight is broken:
![image](https://user-images.githubusercontent.com/204594/161613880-fa32797f-0b8b-4053-8716-7ef58aaedaca.png)

You can get them to disperse and move around corners, they won't just follow you like for example the Steel Lords.

> You can tp in a quadrant on lvl 16 hell that has a dozen of them, have hundreds of fireballs thrown at you, but none will follow you/hunt you to your safe space.

That's how it's always been.

> Also, I was able to target the phasing mages with stone curse, but in this version, they must be fully phazed in for the curse to work.

I was able to stone curse several when phasing when I tested it.

**Comment by xGnoSiSx** [comment]
I'm just sad.

Once I get around to it, I'll create a video for the first 2 points.

**Comment by AJenbo** [comment]
otheres have confirmed the game is working like the original in this regard
