### ISSUE TITLE
Underscore "_" is not displayed correctly.

### ISSUE THREAD

**Issue by testing1209** [diasurgical/devilutionX#4349]
Windows_x64 #6915

I noticed that the underscore "_" is not displayed correctly on the character information screen:
![12212121](https://user-images.githubusercontent.com/103140580/162041522-067722dd-92fa-4e7c-85aa-e2c007dee5ac.jpg)
.

The same goes for chat:
![1212121](https://user-images.githubusercontent.com/103140580/162042068-919c07a0-371d-42eb-9edd-a055f2e83448.jpg)

These are the only two cases that I'm aware of. Everything is correctly displayed on the character selection screen.

**Comment by AJenbo** [comment]
> Windows_x64 #6915

Please post the commit hash instead of the build job id.

Is this the regular https://www.compart.com/en/unicode/U+005F underscore?

**Comment by glebm** [comment]
Can reproduce on the current master

**Comment by qndel** [comment]
It looks like not really a duplicate - previous issue was about character selection screen, it got fixed there but it's still broken ingame.
