### ISSUE TITLE
Chat Log hides automap

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#4355]
Currently opening the Chat Log hides the Automap, which is necessary, but it would be nice to have the game remember the state of the Automap when Chat Log was opened so that Automap is restored when Chat Log is closed.

**Comment by glebm** [comment]
Hmm, why is it necessary to hide the automap?

**Comment by glebm** [comment]
I'm guessing it was necessary in the past due to stippled transparency. We have blended transparency now so it shouldn't be necessary
