### ISSUE TITLE
Cursor changes to Windows default

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#4357]
The cursor changes to Windows default when moving along the edges of the screen even when at Full Screen.  Enabling Grab Input in the .ini does not fix the problem.

**Comment by qndel** [comment]
works fine for me, can u record and post your config and specs?

**Comment by ikonomov** [comment]
https://user-images.githubusercontent.com/5624187/162244702-49480eda-cbe1-4cf9-a3f0-f57c5b8dd2f9.mp4

**Comment by ikonomov** [comment]
this is with the default settings, deleted previous .ini and this is straight out of the build

**Comment by glebm** [comment]
That bright line at the top of the screen is suspicious. Is full screen really full screen?

**Comment by ikonomov** [comment]
I don't see a bright line on my screen.  It is really at full screen.  The problem it turned out is caused by windows scaling.  I normally have Windows scaling at 125%, when I set it to 100% this problem disappears.  Another way to resolve it I just found out is to set this inside the compatibility file properties for devilutionx.exe

![image](https://user-images.githubusercontent.com/5624187/162248531-90994190-5f01-4799-8d83-12028af0d3a6.png)

**Comment by qndel** [comment]
Works fine with 125% scaling and these settings for me (I haven't changed anything, these were default)
![image](https://user-images.githubusercontent.com/14297035/162249193-73cdb1b6-3fc0-41c5-a629-6656911f0252.png)

Anyway not a devilutionx issue

**Comment by ikonomov** [comment]
It turns out, the problem is caused by using a compiled .exe from GitHub's test builds.  If I use a compiled .exe by Visual Studio I don't have this problem.

**Comment by AJenbo** [comment]
> It turns out, the problem is caused by using a compiled .exe from GitHub's test builds. If I use a compiled .exe by Visual Studio I don't have this problem.

Which of the text builds are you refering to, there are 3, and one of them is build with Visual Studio.

If this is an issue with mingw builds then it's an issue since it would affect release. But it sounds more likely that this is related to the version of SDL being used.

**Comment by qndel** [comment]
@AJenbo 
If I build master with visual studio, I don't have this issue.
if I run https://github.com/diasurgical/devilutionX/actions/runs/2108354471 I can see windows cursor

**Comment by ikonomov** [comment]
I might be wrong but pretty sure it's not the SDL version, but the compiler itself.

**Comment by AJenbo** [comment]
> @AJenbo If I build master with visual studio, I don't have this issue. if I run https://github.com/diasurgical/devilutionX/actions/runs/2108354471 I can see windows cursor @ikonomov confirmed that this happens in 1.3.0 release.

yeah, that is what the bug report says why are you repeating it :)

**Comment by qndel** [comment]
dunno, are they using a different SDL version then?

**Comment by qndel** [comment]
I swapped SDL2.dll in release compiled with visual studio to one from 1.3.0 and everything works fine 🤷

**Comment by ikonomov** [comment]
Found another anomaly.  When running with the build from GitHub with hardware cursor set to ON for items when picking up items they are downsized while holding them with the cursor while running with a compiled .exe from Visual Studio doesn't resize.

**Comment by AJenbo** [comment]
> the build from GitHub

There are 3, tell us which one you are using!

**Comment by ikonomov** [comment]
As discussed this only happens for me with GitHub compiled .exe (x64) with gcc-mingw.

**Comment by AJenbo** [comment]
Can you test again with the latest build?

**Comment by ikonomov** [comment]
https://github.com/diasurgical/devilutionX/pull/4361

**Comment by ikonomov** [comment]
[Fix application manifest in MinGW builds #4361](https://github.com/diasurgical/devilutionX/pull/4361)
