### ISSUE TITLE
Hardware cursor for items changes image size

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#4358]
Possibly related to https://github.com/diasurgical/devilutionX/issues/4357.  When running with the build from GitHub with hardware cursor set to ON for items when picking up items they are downsized while holding them with the cursor.  Running with a compiled .exe from Visual Studio doesn't have this behavior and there is no resizing of the item images.  It appears this is resolution dependent, it happens for me at 1280x960 resolution, but likely can happen at other resolutions as well and at some lower resolutions it doesn't happen.

https://user-images.githubusercontent.com/5624187/162288523-98be034b-6cd2-4893-a07b-f5807e472e44.mp4

**Comment by AJenbo** [comment]
Did you switch between full screen and windowed at some point?

**Comment by AJenbo** [comment]
> Running with a compiled .exe from Visual Studio doesn't have this behavior and there is no resizing of the item images.

This is pretty definitively related to SDL and not the compiler, also you still haven't said which of the 3 Windows builds you are running (again one of them is using Visual Studio as well)

**Comment by ikonomov** [comment]
Windows_x64 #6929

**Comment by ikonomov** [comment]
Windows_x64 gcc-mingw-w64-x86-64

**Comment by StephenCWills** [comment]
I can't reproduce this at all given the information provided. Can you provide the `[Graphics]` section of your INI, and also your Windows display settings (resolution and scale)?

**Comment by ikonomov** [comment]
Qndel was able to reproduce this.  I use default settings of the .ini except changed the resolution of the game to 1280x960 and turn hardware cursor and hardware cursor for items ON.  This only happens with the test builds on GitHub compiled with gcc-mingw.  My Windows display settings that I use are 2560x1440 with a scaling of 125%, Qndel uses the same resolution as me with the same scaling.  This appears to be a Windows scaling issue, if I force scaling to be controlled by the application in the Properties/Compatibility of devilutionx.exe then it is fixed.

**Comment by glebm** [comment]
If this helps, the hardware cursor size is decided here:

https://github.com/diasurgical/devilutionX/blob/9c0960589ea4951e94fc6ceb245b80d54b4d03ce/Source/hwcursor.cpp#L33-L43

**Comment by StephenCWills** [comment]
> with a scaling of 125%

Hmm, that's my bad. Earlier I was trying at 100% at 150%, but it seems I can only reproduce at 125% and 175%. Looks like the game resolution and fullscreen settings don't matter.

**Comment by StephenCWills** [comment]
The cursor size is the same between MinGW and VS, but the MinGW build creates a larger window at 125% scaling where VS does not.

![image](https://user-images.githubusercontent.com/9203145/162341560-4ed0d66c-5dfd-4e08-855b-1c58e86f8a3f.png)

I don't know that this really explains anything, however, since 150% also creates a larger window and uses the same cursor size, but I don't see the cursor get smaller.

**Comment by StephenCWills** [comment]
> This is pretty definitively related to SDL and not the compiler, also you still haven't said which of the 3 Windows builds you are running (again one of them is using Visual Studio as well)

Sorry to muddy the waters even further, but I placed SDL2.dll from the MinGW build in my Visual Studio release build folder and I could not reproduce the issue that way.

**Comment by AJenbo** [comment]
> The cursor size is the same between MinGW and VS, but the MinGW build creates a larger window at 125% scaling where VS does not.

Related to the manifest?
