### ISSUE TITLE
Missing reference to who spoke the text

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#4362]
**Important information**
Windows 10 / since https://github.com/diasurgical/devilutionX/commit/6502a3ca4d67b9f247f2cbfc86ba2f472bd74fac

**Describe**
There is no reference who speaks the text in **https://github.com/diasurgical/devilutionX/blob/6502a3ca4d67b9f247f2cbfc86ba2f472bd74fac/Source/textdat.cpp#L198** It's just `"Quest dialog spoken by  "`

**Expected behaviour**
Comment references who says the quest dialogue (Cain, Adria, Narrator etc).

**Additional context**
A minor bug that will help with translation

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/5e28fe4201c3331ee382d607e4237444a2624d4a
