### ISSUE TITLE
SELECT + D-Pad mouse emulation clicks broken on master

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#4369]
1. Clicks don't work
2. The hint menu is visible during mouse emulation

**Comment by AJenbo** [comment]
Same issue it seems: https://github.com/diasurgical/devilutionX/issues/4368

**Comment by glebm** [comment]
Not necessarily, I can reproduce this one on Linux + SDL2 but not the other one

**Comment by jimmiejoe** [comment]
For #4368 most of the clicks work, just 1 does not, and the menu is present.
