### ISSUE TITLE
Ground item names not regenerated on language change

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#4382]
This is a somewhat tricky and minor issue

If an item on the ground was generated with a different language, its name is not updated until it is picked up and then dropped.

E.g.:

1. Set language to Polish
2. Kill a monster, leave the item on the ground, save game
3. Set language to English, load game
4. Item on the ground uses the Polish name
5. Pick up the item -- still Polish name
6. Drop the item -- name is now English (as it should be)

**Comment by AJenbo** [comment]
I thought updating names only worked multiplayer.

I'm thinking that the way to solve this is have a name property that isn't saved and will be generated on first use. This isn't super trivial as the item does not retain the needed info for generating the name. We could try and reverse the items properties to guess what affix and suffix it was based on. Or we could fully regenerate the item based on the seed (this will fail for converted hellfire single player items i belive)

**Comment by glebm** [comment]
Updating names does work in single player after dropping the item

**Comment by AJenbo** [comment]
It is regenerating the entire item from the seed. It is a bit worrisome that this also happens in single player as it could cause converted items to morph.

**Comment by glebm** [comment]
Perhaps we could store the source of the item (diablo/hellfire single/multi) in addition to the seed? As I understand, this would allow us to always regenerate it correctly?

**Comment by AJenbo** [comment]
We do but, there is one case we where not able to cover. Since items in a Hellfire save game are already generated we have no way of knowing if it's an item that was generated in vanilla Hellfire or and item that was converted from a Diablo save game.

**Comment by StephenCWills** [comment]
> It is regenerating the entire item from the seed. It is a bit worrisome that this also happens in single player as it could cause converted items to morph.

FYI, this is due to one of the `HoldItem` fixes (#4276). If we need to avoid regenerating the item, then I guess we'll need to revert this and add swap space for `CMD_PUTITEM`.

**Comment by glebm** [comment]
> we have no way of knowing

One option to automatically upgrade save games would be generate all 4 versions of the item and compare the attributes with the stored attributes (except for the name)

**Comment by AJenbo** [comment]
We use `int32_t dwBuff;` since it is only used for ears and they are not affected by which game type it is.

```cpp
enum icreateinfo_flag2 {
	// clang-format off
	CF_HELLFIRE = 1,
	// clang-format on
};
```
