### ISSUE TITLE
Chain lightning can shoot through walls

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#4384]
Happens when there are enemies behind the wall:

![image](https://user-images.githubusercontent.com/216339/162626863-03f7a129-b62f-4bf9-befa-8fd5fa3b050c.png)

Save: [single_1.zip](https://github.com/diasurgical/devilutionX/files/8459317/single_1.zip)

**Comment by AJenbo** [comment]
Is this only at corners? I would think this is also in vanilla?

**Comment by glebm** [comment]
Yeah so far only at corners. Haven't tested vanilla

**Comment by obligaron** [comment]
This can also happen with the normal lightning spell (if the tile is selected where the monster stands).

**Comment by AJenbo** [comment]
Related to https://github.com/diasurgical/devilutionX/issues/1690 & https://github.com/diasurgical/devilutionX/issues/1283

**Comment by Chance4us** [comment]
I confirm the issue as vanilla.
![vanilla1](https://user-images.githubusercontent.com/45902449/162636163-120efcb2-53b9-4896-a28b-7b7d04e63666.png)
![vanilla2](https://user-images.githubusercontent.com/45902449/162636167-4ebe5792-6c65-41ae-8472-f4f99ed7313d.png)
