### ISSUE TITLE
Demo Support

### ISSUE THREAD

**Issue by actraiser30** [diasurgical/devilutionX#439]
Hello,can you add support for the Demo version for the raspberry pi platform?

or is there a switch to play the demo?

i tried the latest version but it gives me files missing errors and i already have this files installed
anyway thats not my concern i tried version 0.4 and works 
i put the spawn.mpq file from the demo and is not loading, if i rename the file to diabdat.mpq it loads the blizzard video and then exits,so can you add support for the demo version?

thanks

**Comment by AJenbo** [comment]
Use `-DSPAWN=ON` to configure CMake to compile the shareware (spawned) version of the game.
```
cmake .. -DSPAWN=ON -DBINARY_RELEASE=ON
```

We currently do not precompile the spawned version.

**Comment by actraiser30** [comment]
i cannot compile the game i get missing files errors,files that i have already installed so i used the compiled version instead,do you have version 0.4 compiled for shareware to download it somewere?

**Comment by AJenbo** [comment]
Any reason you specifically want 0.4.0 and not 0.5.0 or current master?

What specific error are you getting when trying to compile?

What system are you running on your PI?

**Comment by actraiser30** [comment]
im using raspbian stretch lite,version 0.5 is not working in raspberry pi it asks fo rmissing files that are already present, when i try to compile i get a cmake 3.10 or higher is required,you are running version 3.7.2

**Comment by glebm** [comment]
You can install a more version of CMake by upgrading to buster or, alternatively, by using the stretch-backports package repository.

1. Add the stretch-backports repo to apt:
   https://github.com/superjamie/lazyweb/wiki/Raspberry-Pi-Debian-Backports#installation

2. Install CMake from stretch-backports:

   ```bash
   sudo apt install -t stretch-backports cmake
   ```

**Comment by actraiser30** [comment]
how can i build version 0.4 ?

**Comment by AJenbo** [comment]
> how can i build version 0.4 ?

Why do you specifically want 0.4.0? It has several known ingame bugs.

**Comment by actraiser30** [comment]
coz i dont have buster for this

**Comment by AJenbo** [comment]
0.5.0 doesn't require buster, it's just that the precompiled version was compiled on butster. So if you just compile it your self you can have 0.5.0. Afaik 0.4.0 also didn't have spawn support so you pretty much need. 0.5.0 for what you want.

Not besides cmake you will also need to update libsodium-dev
`sudo apt-get install -y -t stretch-backports cmake libsodium-dev`

**Comment by actraiser30** [comment]
i tried the pre compiled version 0.5 for armhf in stretch it asks for libc.so.6 (libc6) that i have installed

**Comment by AJenbo** [comment]
Yes, the precompiled version requires buster because I upgraded my PI, but as mentioned you can compile it yourself and then it will be build for the version you are running.

**Comment by actraiser30** [comment]
so i will compiled it on buster and will work in stretch?

**Comment by AJenbo** [comment]
Compile it on the system you want it to run on, then cpu and liberies will be corrected for that system.


If you compile on Debian 9 (stretch) then it will work on Debian 10 (buster). But not the other way around.
If you compile it on x86_64 then it won't work on armhf, and that goes both ways.

**Comment by actraiser30** [comment]
i want it to work in stretch but i cannot compile it there

**Comment by glebm** [comment]
Yes you can, it does compile on stretch.

**Comment by actraiser30** [comment]
how? i get the cmake 3.10 or higher is required

**Comment by glebm** [comment]
@actraiser30 Comment https://github.com/diasurgical/devilutionX/issues/439#issuecomment-552201434 explains how update cmake.

**Comment by actraiser30** [comment]
sorry its too complicated for me,thanks anyway

**Comment by glebm** [comment]
You can simply run the following commands.

Add the Debian package signing keys:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E0B11894F66AEC98
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7638D0442B90D010
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
```

Add the Backports repository:

```
echo 'deb http://httpredir.debian.org/debian stretch-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
```

Update your package lists:

```
sudo apt-get update
```

Install CMake and libsodium from backports:

```
sudo apt-get install -y -t stretch-backports cmake libsodium-dev
```

**Comment by AJenbo** [comment]
@actraiser30 I have downgraded my PI so that the latest release is now compatible with Streach:
https://github.com/diasurgical/devilutionX/releases

Also here is a prebuild Shareware version of 1.0.0 for the Raspberry Pi:
[devilutionx_s.zip](https://github.com/diasurgical/devilutionX/files/4013434/devilutionx_s.zip)
