### ISSUE TITLE
Space too wide for the 12px font

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#4397]
The space is somewhat too wide for the 12px font.

This results in some store items not fitting on a single line.

Example by @ikonomov:

![store screenshot](https://user-images.githubusercontent.com/216339/162709149-702d1a36-a86c-4ece-8400-2269b5cd4f81.png)

**Comment by glebm** [comment]
Just checked against 1.3 and it's the same there, so not a regression.
Still, the space should probably be a somewhat narrower.

**Comment by AJenbo** [comment]
Considering that the item being shown has an addition value added this doesn't necessarily follow

**Comment by ikonomov** [comment]
![screen05](https://user-images.githubusercontent.com/5624187/162799651-5856a739-bf71-4fe2-ad56-d5af5e1db190.gif)

This is with 6px width.
