### ISSUE TITLE
Veil of Steel glitch after new game

### ISSUE THREAD

**Issue by yevhene** [diasurgical/devilutionX#441]
**Describe the bug**
After I killed Diablo and run new game Veil of Steel become Healing Potion

**To Reproduce**

[single_0.zip](https://github.com/diasurgical/devilutionX/files/3829231/single_0.zip)

If you Load Game, you will load just before Diablo with Veil of Steel on your head.
If you start a New Game, Veil of Steel become Healing Potion with Unique Item properties.

**Expected behavior**
I expect the Veil of Steel is still the Veil of Steel.

**Screenshots**
![Screenshot from 2019-11-10 23-45-19](https://user-images.githubusercontent.com/241623/68551352-c3429880-0414-11ea-8cf1-7e968b1710cb.png)

**Comment by qndel** [comment]
platform/version

**Comment by yevhene** [comment]
Platform: Ubuntu 18.04.3 LTS x64
Version: 
```
DevilutionX https://github.com/diasurgical/devilutionX

git commit 890f414
compiled on Ubuntu 18.04 27 september 2019

compile options:
 ASAN                             OFF                                          
 BINARY_RELEASE                   OFF                                          
 CMAKE_BUILD_TYPE                 Release                                      
 CMAKE_INSTALL_PREFIX             /usr/local                                   
 DEBUG                            OFF                                          
 DIST                             ON                                           
 FASTER                           OFF                                          
 NIGHTLY_BUILD                    OFF                                          
 SDL2_DIR                         /usr/lib/x86_64-linux-gnu/cmake/SDL2         
 USE_SDL1                         OFF                                          
 sodium_USE_STATIC_LIBS           ON 

dependencies:
$ objdump -p devilutionx | grep NEEDED
  NEEDED               libSDL2_ttf-2.0.so.0
  NEEDED               libSDL2_mixer-2.0.so.0
  NEEDED               libSDL2-2.0.so.0
  NEEDED               libm.so.6
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
```

**Comment by qndel** [comment]
27 september is pretty old, get latest

**Comment by yevhene** [comment]
@qndel Reproduces on 0.5.0 (88039e9) and current master (af0a7c0)

**Comment by qndel** [comment]
thx

**Comment by AJenbo** [comment]
Not saying we shoudn't try to fix it, but this is actually a known bug in the original Diablo:
https://www.gog.com/forum/diablo/veil_of_steel_glitching_upon_new_game
![Screenshot](https://www.gog.com/upload/forum/2019/04/26b3c604ab31e614bf4b473d4b67fa8acd457b02.png)

**Comment by Chance4us** [comment]
This on I already experienced when beginning a new game with an existing character after completing the previous game.

**Comment by AJenbo** [comment]
> This on I already experienced when beginning a new game with an existing character after completing the previous game.

Sorry I don't understand what you are trying to say.

**Comment by Chance4us** [comment]
I meant when all quests are completed including killing the final boss.
And you start a new game with an existing character already wearing the "veil of steel".
In this case it comes to the described bug.

**Comment by AJenbo** [comment]
> I meant when all quests are completed including killing the final boss.
> And you start a new game with an existing character already wearing the "veil of steel".
> In this case it comes to the described bug.

Maybe I'm missing your point, but that just sounds like repeating what is in the original post?

**Comment by yevhene** [comment]
@AJenbo @Chance4us Wearing is not required. It can be in your inventory with the same effect.

**Comment by Chance4us** [comment]
@AJenbo in my case it appeared a little bit other way. After I killed the final boss and while it was screaming and dieing I just saved the game in this moment. Of course the final result was the same.
Maybe it can be resolved by little bit modifying the savegame file as an enhancement later?

**Comment by qndel** [comment]
"Maybe it can be resolved by little bit modifying the savegame file as an enhancement later?" - that's not an enhancement, that's a waste of time, as AJenbo has already said, it's a vanilla bug, we might fix it in devilutionx but I believe there are more important things to do at the moment ;)

**Comment by yevhene** [comment]
@qndel You guys made a great work, I passed through the game three times and it is the only bug I have seen. (Except spamming messages about items duplications when I was by killed by Diablo once, but it didn't affect gameplay anyway).

**Comment by yevhene** [comment]
@qndel If I want to investigate this issue by myself where the best places to start? Do you have any suspicions?

**Comment by qndel** [comment]
I'd print item values and see what's special with veil of steel

**Comment by Chance4us** [comment]
@qndel Maybe it can be resolved by little bit modifying the savegame file as an enhancement later?
If there are more important things to do at the moment ;)
You know wath I mean. Great job so far all of you guys :1st_place_medal:

**Comment by AJenbo** [comment]
I belive new game uses the compact hero data and load game uses the full strict, so probably compare them when unpacked.

It would poebably happen if you started a new game at any point

**Comment by Orthotope** [comment]
Pretty much what AJenbo said. Looking at pack.cpp, it only actually saves an item's current and max durability and charges, identified state, and the random seed used to create it. This is why gloomy and weird shrines don't have a permanent effect; it re-creates items for a new game, so the modified armor and damage are lost. For some reason, sometimes the re-creation process doesn't use the same sequence of random() calls, so the new item is broken. I ran into the same problem when trying to implement D2/D3-style rare items, worked around it by modifying the pack functions to save the entire item struct.

**Comment by qndel** [comment]
I added rare items in infernity by reusing one of the existing variables :P

**Comment by AJenbo** [comment]
afaik there is little to no unused space in the packed player data, but we could make the game load items from the full data when creating a new game.

**Comment by AJenbo** [comment]
Still not exactly sure what is happening here, but if you unset the CF_UPER1 flag the item will be recreated correctly.
