### ISSUE TITLE
Replace __FILE__ and __LINE__ wtih some form of relative path.

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4420]
`<command-line>: warning: "__FILE__" redefined [-Wbuiltin-macro-redefined]`

People get confused when they see my home path in error messages and sometimes thinks that I hardcoded my system paths in the code and that is why it's failing to work :cry: 

If we can't redefine them or find an alternative maybe we can wrap them in a function that cuts out the first bit (look for `*Source/`).

**Comment by glebm** [comment]
From looking at StackOverflow https://stackoverflow.com/questions/8487986/file-macro-shows-full-path

For GCC 8+ and recent clang we can do:

```
--ffile-prefix-map="${PWD}/=/"
```
