### ISSUE TITLE
[Virtual Gamepad] Flash missile interferes with controller logic

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#4427]
**Important information**
Reproduced in 1.4.0, but this should affect any version with touch controls

**Describe**
Pressing the primary action button while the local player's Flash missile is active hides the automap.
Pressing the cancel button while the local player's Flash missile is active brings up the game menu.

**To Reproduce**
1. Go to the dungeon
2. Open the automap
3. Cast the Flash spell
4. After the hit frame and before the spell has ended, press the primary action button
5. The automap should disappear

**Expected behavior**
Assuming no menus are open, these buttons should do nothing at all during the Flash spell.

**Video**
The following video demonstrates the issue twice, first around 20 seconds and then again around 30 seconds.

https://user-images.githubusercontent.com/9203145/163315747-0ce816e0-c399-4269-9968-36a3eef9cd29.mp4

**Additional context**
The primary action button generates a spacebar action when the player is in certain menus.

https://github.com/diasurgical/devilutionX/blob/a66ca446950bceb25ac31ee268dfc8e2ec9259ce/Source/controls/game_controls.cpp#L126-L138

It seems that the `inGameMenu` flag evaluates to `true` when the local player's Flash missile is active because the `InGameMenu()` function checks the `Player::_pInvincible` flag.

https://github.com/diasurgical/devilutionX/blob/a66ca446950bceb25ac31ee268dfc8e2ec9259ce/Source/controls/plrctrls.cpp#L54-L64

Reported on Discord by SinfulPain.

**Comment by glebm** [comment]
The `pInvincible` check was added in https://github.com/diasurgical/devilutionX/commit/d94b2454971d1cd7c6a42083f91e0ce377d67631, not sure why though.

**Comment by glebm** [comment]
There is another `pInvincible` check in this file and from the commit message it seems to have something to do with the town portal: https://github.com/diasurgical/devilutionX/commit/4c39ac44028210720fd29931474359d662d0946a

**Comment by StephenCWills** [comment]
I suspect the `InGameMenu()` check was most likely added for opening the game menu with the cancel button while the player is dead.
