### ISSUE TITLE
PS4 workflow

### ISSUE THREAD

**Issue by Cpasjuste** [diasurgical/devilutionX#4431]
Hi,

I'm the maintener of the PS4 toolchain installer "pacbrew". The server was down because of hardware failure, I just successfully restored it. You should be able to enable the workflow again.

Sorry for that,
cpasjuste.

**Comment by glebm** [comment]
Thanks, I've reenabled the workflow! Will let you know if it's successful

**Comment by Vecinagamer** [comment]
🥇Wonderfull🥇

**Comment by AJenbo** [comment]
Confirmed working :+1:

**Comment by AJenbo** [comment]
@Cpasjuste could you test the game. We had a report that the 1.4.0 release crashes on startup but none of the devs have a PS4 :(

https://github.com/diasurgical/devilutionX/releases/download/1.4.0/devilutionx-ps4.pkg

**Comment by Cpasjuste** [comment]
Hi,

I will try to do that when I find some time, probably next week.
Else, I think it's missing some required modules (https://github.com/PacBrew/ps4-openorbis-sample/tree/master/data) in the package (https://github.com/diasurgical/devilutionX/tree/master/Packaging/ps4).

**Comment by Brutal-sam** [comment]
@Cpasjuste any chance you could build a new pkg and upload it before next week?
