### ISSUE TITLE
Character corrupted?

### ISSUE THREAD

**Issue by AAthias** [diasurgical/devilutionX#4458]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Windows 10 / v1.3.0 / download

**Describe**
When I select multiplayer barbarian Kronk to play with him, game exits fast with no error messages.

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'
[AthiasDevolutionMultiSaves.zip](https://github.com/diasurgical/devilutionX/files/8499285/AthiasDevolutionMultiSaves.zip)

Go to Hellfire, click on Kronk, click on loopback, game exits fast
... tcp or that other option, load Kronk, select join game, exits fast

**Expected behavior**
Load up Kronk and away I go grinding some more.

**Screenshots**
N/A

**Additional context**
It might have happened when I exited the game when I was about to die.

**Comment by StephenCWills** [comment]
I am completely unable to reproduce the issue. Tested on Windows 10 using both 32-bit and 64-bit versions of 1.3.0 as well as x64-Debug on the latest master.

![image](https://user-images.githubusercontent.com/9203145/163684597-66d3f63e-c1c1-45a5-bd6c-89628d8847e8.png)

**Comment by AAthias** [comment]
I was still having the problem with 1.3.0, but I did install 1.4.0, and it works now.
