### ISSUE TITLE
Wrong durability indicator

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#4474]
As you can see in the picture, the durability indicator is wrong.
The helm has a durability of 48, but it shows as badly damaged.
The indicator should show broken armor though, and in fact if you remove the armor the helmet's indicator will disappear.
![durability](https://user-images.githubusercontent.com/45902449/163716891-2826188f-72fa-4c57-967e-f05192f28e82.png)

I couldn't narrow down the issue perfectly because some tested commits crashed the game.

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
20c13b7b0789a57d8c2b8f9e61efafb9d2509d3f
6a04d441c1854e6e7b840711b30d9e5b07354d01
6dca3b50c13608eacf31b53416f20be94237ad33
a66ca446950bceb25ac31ee268dfc8e2ec9259ce
8ed94ec365aa73ac505033bc9db2ce83648e7ce7

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/8501752/single_0.hsv.zip)

**Comment by StephenCWills** [comment]
Surely it's this one: a66ca44

**Comment by DakkJaniels** [comment]
Maybe this part? https://github.com/diasurgical/devilutionX/blob/de71117b6699907507ac1de4519b2ca0a1c442d4/Source/control.cpp#L275

If everything was 0 indexed (I think I recall seeing that commit), it looks like these are off by one.

**Comment by Chance4us** [comment]
Thanks a lot for fixing. I will report if further issues should occur.
