### ISSUE TITLE
[android] Crash in settings menu from mouse handeling

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4476]
This looks similar to the issue in the hero menu, but I haven't been able to replicate it yet.

```
backtrace:
libc.so (abort+166)
libdevilutionx.so (offset 0x1000) (devilution::(anonymous namespace)::HandleMouseEvent(SDL_Event const&, devilution::UiItemBase*) (.llvm.7318811127165588370)) (SourceCode: libgcc2.c)
libdevilutionx.so (offset 0x1000) (devilution::UiFocusNavigation(SDL_Event*))
libdevilutionx.so (offset 0x1000) (devilution::UiPollAndRender(std::__ndk1::function<bool (SDL_Event&)>))
libdevilutionx.so (offset 0x1000) (devilution::UiSettingsMenu())
```

**Comment by AJenbo** [comment]
This appears to be related to rebinding keys. At least This is one place where I can provoke a crash. It's not entirely clear how, but aggressively clicking the screen, will often either crash the menu immediately or when hitting return.

**Comment by StephenCWills** [comment]
Seems to be easy to reproduce by clicking below `Previous Menu` on submenus with fewer than 8 options, similar to how it worked in https://github.com/diasurgical/devilutionX/issues/4441#issuecomment-1100587324.

![image](https://user-images.githubusercontent.com/9203145/164952186-ac2155e3-6399-42ff-898d-c9d39a832199.png)
