### ISSUE TITLE
[PS4] Installation instructions missing for PS4 version. 

### ISSUE THREAD

**Issue by Xirious** [diasurgical/devilutionX#4480]
**Important information**
PS4. Downloaded it myself. 

**Describe**
The installation instructions:
https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md

Does not contain detailed instructions of how to install it on a PS4. 

**To Reproduce**
1. Read Readme. 
2. See nothing about PS4. 

**Expected behavior**
A clear and concise description of what you need to do to install on a PS4. 

**Additional context**
I am quite new to installing things on PS4 so as detailed instructions as possible for myself and others would be appreciated.

**Comment by Brutal-sam** [comment]
@Xirious the PS4 app doesn't work right now, it crashes cause it's missing some modules but the instructions are here: https://github.com/diasurgical/devilutionX/tree/master/Packaging/ps4
- install the pkg
- copy diabdat.mpq from game disc (can be found on the internet) or spawn.mpq from the shareware to /user/data/diasurgical/devilution/
- run the game.

**Comment by rtx92** [comment]
same for me here  cant get this port to run tried even building a new pkg with the needed mpq onboard but with same ce-304878-0 error

**Comment by rtx92** [comment]
another way to install if youre ps4 kept offline or ftp wont work for any reason would be  : get the ps4 explorer pkg put your mpq files on an usb start the ps4 explorer and copy your mpq files from mnt/usb1/  to  /user/data/diasurgical/devilution/

**Comment by john-tornblom** [comment]
I believe this issue is addressed by https://github.com/diasurgical/devilutionX/pull/4494 and thus can be closed.
