### ISSUE TITLE
Wirt item generation solo game

### ISSUE THREAD

**Issue by M-Paladin** [diasurgical/devilutionX#4489]
**Important information**
Linux / DevilutionX version 1.4.0 / downloaded

**Describe**
In a solo game, Wirt's item generation is not random at all

**To Reproduce**
1. Create a new solo game
2. Go to Wirt
3. Save game
4. Buy Wirt's item
5. Go down to dungeon lvl 9 next to him
6. Go up and repeat step 4 to 6 as many time as you want.
7. Reload the game
8. Retry from step 4 --> items you buy are exactly the same as before (I tried with 4 items in a raw, each time they where identical)

**Expected behavior**
I don't know if it's normal, but it's pretty strange to my opinion.
I would imagine random is random, even after reloading a game.

**Comment by yuripourre** [comment]
Random is random but the seed is the same in this case, right?

**Comment by M-Paladin** [comment]
Clearly the seed is not dependent of time of day, or character position or else.
It's pretty basic it seems.

**Comment by AJenbo** [comment]
Levels are also generated randomly but there seed is locked at the start of the game so that the level won't change each time you use a town portal. The shops work in a similar way.
