### ISSUE TITLE
__int64 in structs.h not understood by C compiler

### ISSUE THREAD

**Issue by mewmew** [diasurgical/devilutionX#449]
**Describe the bug**
I've been trying to include the Devilution headers of DevilutionX as C headers, as a way to hook into the engine from a mod.

It *almost* works, and only a few errors are reported by the C compiler. Fixing these would enable further interopability between DevilutionX and potential mods.

The errors reported are as follows:

```
structs.h:220:18: error: expected ';' at end of declaration list
        unsigned __int64 _pMemSpells;
                        ^
                        ;
```

**To Reproduce**
1. Run `clang -x c -o foo.o structs.h`
2. Observe the `__int64` error.

**Expected behavior**
Successful compile.

Note, the issue here is that the standard int types on Linux cannot be "hooked" into `__int64` in the current way it is used, as `__int64` is preceded by `unsigned`.

One solution that would work well in this case would be to use `uint64_t` instead, as defined in `stdint.h`. And if not present on Windows, add a typedef for Windows along the lines of:

```c
typedef unsigned __int64 uint64_t;
```

Then the following change could be made to `structs.h`:

```diff
-	unsigned __int64 _pMemSpells;
-	unsigned __int64 _pAblSpells;
-	unsigned __int64 _pScrlSpells;
+	uint64_t _pMemSpells;
+	uint64_t _pAblSpells;
+	uint64_t _pScrlSpells;
```

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/c29030d6f631c4b039cd1a445111c802d0d1da16
