### ISSUE TITLE
[stash] Books are not adjusted to current hero on first opening the stash

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#4499]
From GutoHertzog on Discord:
> 2. About minimum level for read books (i think this one is more critical). I got some books with my Barbarian. Because his low magic level, all books had the minimum ML to read them. Stored them into the "stash". When I got my sorcerer, all the book kept the barbarian magic level to read (ML around 30 of requirement) . Only when I read the first book, all the others updated to sorcerer's ML requirement. This readed book needed around ML of 250, but I read it with ML 30 of requirement. I checked, I got the spell level.

**Comment by gutohertzog** [comment]
Leaving a video to show how to to reproduce the issue.

https://www.youtube.com/watch?v=ViWOtEJToUI
