### ISSUE TITLE
[docs] -DVERSION_NUM=1.0.0 should be updated -DPROJECT_VERSION_*=

### ISSUE THREAD

**Issue by hiperiondev** [diasurgical/devilutionX#4503]
Build https://github.com/diasurgical/devilutionX/archive/refs/tags/1.4.0.tar.gz with instructions (https://github.com/diasurgical/devilutionX/blob/master/docs/building.md) breaks with:

[ 70%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/palette.cpp.o
/tmp/devilutionX-1.4.0/Source/multi.cpp: En la función ‘void devilution::InitGameInfo()’:
/tmp/devilutionX-1.4.0/Source/multi.cpp:440:60: error: expected primary-expression before ‘;’ token
  440 |         sgGameInitInfo.versionMajor = PROJECT_VERSION_MAJOR;
      |                                                            ^
/tmp/devilutionX-1.4.0/Source/multi.cpp:441:60: error: expected primary-expression before ‘;’ token
  441 |         sgGameInitInfo.versionMinor = PROJECT_VERSION_MINOR;
      |                                                            ^
/tmp/devilutionX-1.4.0/Source/multi.cpp:442:60: error: expected primary-expression before ‘;’ token
  442 |         sgGameInitInfo.versionPatch = PROJECT_VERSION_PATCH;
      |                                                            ^
gmake[2]: *** [Source/CMakeFiles/libdevilutionx.dir/build.make:636: Source/CMakeFiles/libdevilutionx.dir/multi.cpp.o] Error 1
gmake[2]: *** Se espera a que terminen otras tareas....
En el fichero incluido desde /tmp/devilutionX-1.4.0/Source/options.cpp:11:
/tmp/devilutionX-1.4.0/build/_deps/simpleini-src/SimpleIni.h:888:12: aviso: se descartan los calificadores de tipo en el tipo de devolución de la función [-Wignored-qualifiers]
  888 |     inline const bool SectionExists(
      |            ^~~~~
/tmp/devilutionX-1.4.0/build/_deps/simpleini-src/SimpleIni.h:895:12: aviso: se descartan los calificadores de tipo en el tipo de devolución de la función [-Wignored-qualifiers]
  895 |     inline const bool KeyExists(
      |            ^~~~~
/tmp/devilutionX-1.4.0/Source/options.cpp:174:6: aviso: se define ‘void devilution::{anónimo}::SetIniValue(const char*, const char*, uint32_t)’ pero no se usa [-Wunused-function]
  174 | void SetIniValue(const char *keyname, const char *valuename, std::uint32_t value)
      |      ^~~~~~~~~~~
gmake[1]: *** [CMakeFiles/Makefile2:2164: Source/CMakeFiles/libdevilutionx.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

**Comment by glebm** [comment]
Building from that requires a git clone (and a network connection) but you can use this archive instead: https://github.com/diasurgical/devilutionX/releases/download/1.4.0/devilutionx-src.tar.xz

**Comment by AJenbo** [comment]
Regarding missing version when not building from a git clone, see the first notice on https://github.com/diasurgical/devilutionX/blob/master/docs/building.md#building-from-source

**Comment by StephenCWills** [comment]
I don't think it's wrong. Are you saying it didn't work with `-DVERSION_NUM=1.0.0`?

**Comment by hiperiondev** [comment]
Yes, doesn't work.
My mistake, in F35 works with:
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DPROJECT_VERSION_MAJOR=1 -DPROJECT_VERSION_MINOR=4 -DPROJECT_VERSION_PATCH=0 -DVERSION_NUM=1.4.0

cmake version 3.22.2
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)

**Comment by glebm** [comment]
That sounds like a bug, `VERSION_NUM` should be sufficient:

https://github.com/diasurgical/devilutionX/blob/90132b23cc16d3dd831c0fbc4eb5088a428b98b1/CMakeLists.txt#L91-L92

**Comment by StephenCWills** [comment]
I am unable to reproduce the error using the following commands.

```bash
wget https://github.com/diasurgical/devilutionX/archive/refs/heads/master.zip
unzip master.zip
cd devilutionX-master/
cmake -S. -Bbuild -DVERSION_NUM=1.0.0 -DVERSION_SUFFIX=FFFFFFF -DCMAKE_BUILD_TYPE=Release
cd build
make -j8
```

cmake version 3.23.0
gcc (Debian 11.2.0-19) 11.2.0

**Comment by hiperiondev** [comment]
This refers to master git: https://github.com/diasurgical/devilutionX/archive/refs/heads/master.zip
The problem is with 1.4.0 version on release: https://github.com/diasurgical/devilutionX/archive/refs/tags/1.4.0.tar.gz
