### ISSUE TITLE
Add quick cast to controllers

### ISSUE THREAD

**Issue by Xazax-hun** [diasurgical/devilutionX#4516]
Currently, it is a hassle to switch between spells, while both dpad and the left stick is used for movements. It would be nice to have the option to use the arrows of the dpad to switch between 4 spells. Alternatively, it would be nice to have the option to remap gamepad controls.

**Comment by glebm** [comment]
> It would be nice to have the option to use the arrows of the dpad to switch between 4 spells

The "Dpad Hotkeys" option does just this IIRC

**Comment by AJenbo** [comment]
holding select lets you use the 4 right side buttons as spell hotkeys. Remapping is planned, the current scheme is intended for also working with controls that do not have joysticks.
