### ISSUE TITLE
Golem walking in the dungeon without being summoned

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#4517]
Confirmed by me and Gonzo on Discord, it appears that Golems can sometimes show up in the dungeon without being summoned.  For me this happened on every level in church (MP), but did not in catacombs, while in Gonzo's game it happened on dlvl 15.

**Comment by qndel** [comment]
Thanks for following issue template ...

**Comment by AJenbo** [comment]
@ikonomov Gonzo had and issue with a stuck Golem in a beta of 1.4.0. And on a different level. For you I think you are seeing this in your own mod (which version is it actually based on?), and not on level 15, and they are not stuck? This sounds like two different issues. And one that may already have been solved.

**Comment by ikonomov** [comment]
It's based on the master right before [Fix build error] that was committed yesterday.  We haven't seen any more Golems after church (just finished lvl 10), but in church it happened on every level.  We were playing with my mod, so I can't say with 100% certainty it wasn't from my changes, but this is the first time I have seen this, and I haven't made any significant changes recently to cause this.  I know it's possible that something in my mod can cause this, but I went over all my changes yesterday thinking about what it can be, and I just can't come up with an explanation based on my changes.

Gonzo's golem was stuck, but most importantly according to him it wasn't summoned by anyone in his game, which would be the same problem that I had, if only on different levels.

**Comment by AJenbo** [comment]
I can't replicate it, please add more info if you figure out how to replicate it.

**Comment by qndel** [comment]
> It's based on the master right before [Fix build error] that was committed yesterday. We haven't seen any more Golems after church (just finished lvl 10), but in church it happened on every level. We were playing with my mod, so I can't say with 100% certainty it wasn't from my changes, but this is the first time I have seen this, and I haven't made any significant changes recently to cause this. I know it's possible that something in my mod can cause this, but I went over all my changes yesterday thinking about what it can be, and I just can't come up with an explanation based on my changes.
> 
> Gonzo's golem was stuck, but most importantly according to him it wasn't summoned by anyone in his game, which would be the same problem that I had, if only on different levels.
> 
> Edit: Golems were not stuck, they were roaming about.

trying to describe the commit without actually giving a link to said commit is useless xD

**Comment by AJenbo** [comment]
I guess it's this one: https://github.com/diasurgical/devilutionX/commit/3aca1a50c3936c83025f4cd883110ab729d53a33

**Comment by qndel** [comment]
nothing better than having to guess things

**Comment by ikonomov** [comment]
OK, I just checked my last merge for the build that we used, I was wrong, it was this https://github.com/diasurgical/devilutionX/pull/4515 one.  We played the day before yesterday and yesterday with the same build and as I said it only happened the day before yesterday and only in church.  I've never seen this before, but I don't believe this is something that came about with the latest commits.  It could be something that only happens rarely.  I suggest we keep this issue open, and if I or anybody else encounters this again we can add more details.  Besides the regular bugs, weird and rare bugs in vanilla do happen, I have seen very strange things that happen so rarely that it would be impossible to track down.  So there is the possibility that something like this happened and we will just have to ignore it.

**Comment by AJenbo** [comment]
If it's impossible to track down having an issue open for it only serves as a distraction. Strange and rare bugs like that usually happens because of OOB errors else where in the code. Meaning that there is no logical way to find the issue. Instead the solution is to do general clean ups and hardening of the over all code. Again making a specific issue pretty pointless.

**Comment by AJenbo** [comment]
> By the way, in the same game we encountered the butcher outside his room. His door was closed and we somehow found him while exploring level 2. I don't believe I have ever seen this before. I know this is a separate issue, but maybe what happened is some kind of error in the dungeon generation that caused both of these occurrences.

Sounds more like there was a general issue with positions. The Butcher is always spawned on a specific tile, so he would have had to be offset some how. The Golems around always standing in the very corner of the level, if they where shifted in to the level then that would explain them wondering around in it.

Closing as it's not been replicated on master and sounds like something unrelated causing memory corruption, rather then a logic fault. We can always open it again if it turns out to be something constant.

**Comment by ikonomov** [comment]
We encountered a golem again in level 13, but no golems in the caves in the same gaming session.  We played most of caves and catacombs two times in separate gaming sessions and no golems in those levels.  Will report if we see golems again.
