### ISSUE TITLE
Game opens on wrong monitor on startup

### ISSUE THREAD

**Issue by BCullen2201** [diasurgical/devilutionX#4526]
**Important information**
Ubuntu 22.04 LTS / 1.4.0 / Downloaded release

**Describe**
Game should open on my primary display, but instead opens on my 2nd monitor.

**To Reproduce**
1. Open DevilutionX (through desktop icon or through activities menu)
2. Game opens on 2nd monitor

**Expected behavior**
Game should open on primary monitor

**Screenshots**
![devilutionxmonitors](https://user-images.githubusercontent.com/94326161/165878752-5f9050c2-2c8e-44aa-bf9a-7ab7a0218f48.png)

**Additional context**
Looked through `diablo.ini` for a way to make the game open on my primary monitor, but couldn't find anything.

**Comment by AJenbo** [comment]
Are you using Wayland or Xorg?

**Comment by BCullen2201** [comment]
Wayland

**Comment by AJenbo** [comment]
Can you try switching to Xorg. In any case this would be an issue with with SDL and should be reported here: https://github.com/libsdl-org/SDL/issues/new

**Comment by yuripourre** [comment]
@BCullen2201 Are you using an NVidia board? You can try switching your driver between nouveau and official NVidia drivers and check if one of them works better.

**Comment by BCullen2201** [comment]
@AJenbo Switching to Xorg solved this issue

**Comment by AJenbo** [comment]
Known issues with Wayland:
- VNC doesn't work
- The wrong monitor is seen as the primery
- Can't move the mouse pointer programmatically
- Drag and drop/copy paste doesn't work between all aplication

Why Canonical thought it was sane to enable this as the default in an LTS I don't understand. I guess I can ask them when I meet with them next week...
