### ISSUE TITLE
[XBOX] translation files missing from release

### ISSUE THREAD

**Issue by 20Phoenix** [diasurgical/devilutionX#4527]
XBOX Series X / DevilutionX 1.4.0 / release download

Hello :)
First a HUGE THANKS for the XBOX UWP release - awesome. 🥰
I'm happy to see a language selection in the settings. 😁

But how to use them ?
I thought I have to download the needed PO file and place it beside the MQP files.
In my case I want to use German, so I've used the file DE.PO .
But that doesn't change anything when switching the language.
Is a different location needed for the language PO file or does the XBOX version still not support translations ?

**Comment by glebm** [comment]
For German, there's no need to download anything, it's already included. Simply switch to German in the Settings menu.

**Comment by 20Phoenix** [comment]
But that doesn't change anything.
Not in the menu, not ingame.

**Comment by 20Phoenix** [comment]
Ok, no extra files needed. But why is nothing happening ?
I checked the diablo.ini, there thevalue has been change to German:
```
[Language]
Code=de
```
But anyway there comes no German :(

**Comment by 20Phoenix** [comment]
> Can you try and generate the mo file (or grab the data file from here: https://github.com/diasurgical/devilutionx-assets/releases/download/v2/devilutionx.mpq) and place them in your data folder.

Yeah, that works. Thanks a lot. 🥳
