### ISSUE TITLE
Can't Build Full Featured Release

### ISSUE THREAD

**Issue by katnatek** [diasurgical/devilutionX#4531]
Actually i have to add -DDISABLE_ZERO_TIER=ON to cmake's options to be able to reach a successful build.
If i don't do that the build fail due some errors on Source/dvlnet/zerotier_native.cpp

My system is Mageia Linux Version 8  x86_64
Here the log of the build process
[build_log.txt](https://github.com/diasurgical/devilutionX/files/8600426/build_log.txt)

**Comment by StephenCWills** [comment]
The `zts_event_msg_t` type and those functions should all be declared in `ZeroTierSockets.h`. It seems like the directory it's in is being added to your include path so I'm not sure what the issue is. Maybe you can check the following path for that file and see what's in it?

`/home/katnatek/rpm/BUILD/devilutionX-1.4.0/build/_deps/libzt-src/include/ZeroTierSockets.h`

**Comment by katnatek** [comment]
> The `zts_event_msg_t` type and those functions should all be declared in `ZeroTierSockets.h`. It seems like the directory it's in is being added to your include path so I'm not sure what the issue is. Maybe you can check the following path for that file and see what's in it?
> 
> `/home/katnatek/rpm/BUILD/devilutionX-1.4.0/build/_deps/libzt-src/include/ZeroTierSockets.h`

This is (at less i can't found the type definition)
[ZeroTierSockets.h.txt](https://github.com/diasurgical/devilutionX/files/8600701/ZeroTierSockets.h.txt)
)
But also is not on none of the versions i try https://github.com/diasurgical/ZeroTierOne/raw/master/include/ZeroTierDebug.h & https://github.com/diasurgical/ZeroTierOne/raw/7f026edea747525189da8d5a58b3a6ff59190246/include/ZeroTierOne.h

**Comment by StephenCWills** [comment]
I see now that you are using `-DFETCHCONTENT_SOURCE_DIR_LIBZT` so you must have downloaded the master branch of https://github.com/diasurgical/libzt manually for your build. The master branch was used for 1.3.0, but we tried to upstream a number of our modifications and clean up the libzt repos a bit for 1.4.0 so we moved the code to another branch. Try downloading https://github.com/diasurgical/libzt/tree/devx-1.4.0 and then give it another try.

**Comment by AJenbo** [comment]
Please follow the issue template

**Comment by katnatek** [comment]
> I see now that you are using `-DFETCHCONTENT_SOURCE_DIR_LIBZT` so you must have downloaded the master branch of https://github.com/diasurgical/libzt manually for your build. The master branch was used for 1.3.0, but we tried to upstream a number of our modifications and clean up the libzt repos a bit for 1.4.0 so we moved the code to another branch. Try downloading https://github.com/diasurgical/libzt/tree/devx-1.4.0 and then give it another try.

I was already try that, but change of commit because i'm getting lots of **undefined reference to** messages
[build_log. with libzt-devx1.4.0.txt](https://github.com/diasurgical/devilutionX/files/8605718/build_log.with.libzt-devx1.4.0.txt)

**Comment by StephenCWills** [comment]
It seems like those two libraries, `lwip_pic` and `zt_pic`, are interdependent so it sort of makes sense that those symbols would be unresolved when compiling them independently as shared object libraries. However, I am unable to reproduce those errors on Debian Linux using GNU 11.2.0 compilers. I don't know exactly why the behavior is different between your platform and mine, but I do know that you will likely be able to work around it by building libzt's dependencies as static libraries. See StephenCWills/libzt@0ce98ee.

**Comment by katnatek** [comment]
> It seems like those two libraries, `lwip_pic` and `zt_pic`, are interdependent so it sort of makes sense that those symbols would be unresolved when compiling them independently as shared object libraries. However, I am unable to reproduce those errors on Debian Linux using GNU 11.2.0 compilers. I don't know exactly why the behavior is different between your platform and mine, but I do know that you will likely be able to work around it by building libzt's dependencies as static libraries. See [StephenCWills/libzt@0ce98ee](https://github.com/StephenCWills/libzt/commit/0ce98ee).

Its possible that compiler and cmake versions are related, in Mageia 8 we have GNU 10.3.0 and cmake 3.19.2
The static branch solve the issue for me, thank you
