### ISSUE TITLE
free firebolt no mana charges

### ISSUE THREAD

**Issue by MAXIMADSIMUS** [diasurgical/devilutionX#4540]
yo after i set quick cast: on ... and i had no spell to the hotkey f5, f5 was blank.... but after i have a spell on that hotkey it work normal so the bug is only there if your hotkey is empty

**Comment by MAXIMADSIMUS** [comment]
[](url)https://discord.com/channels/518540764754608128/764970679564501052/971426372188782642

**Comment by yuripourre** [comment]
@MAXIMADSIMUS could you please follow the issue template? I am having a hard time understanding what the problem is.
