### ISSUE TITLE
Not gaining XP past level 50

### ISSUE THREAD

**Issue by myself600** [diasurgical/devilutionX#4543]
**Important information**
Windows 7 SP1 64-bit / both 1.4.0/release 64-bit and latest (https://github.com/diasurgical/devilutionX/commit/851b03215b86f626499e6d0c45c7bcf6299dd86a) test builds/master 64-bit / I have downloaded a release and a test build

**Describe**
Previously, it was possible to gain experience points after reaching clvl 50 (1,310,707,109).

**To Reproduce**
1. Enter the dungeons
2. Open the character screen window
3. Kill an enemy
4. Hero's XP points does not change

**Expected behavior**
The hero should gain XP points.

**Screenshots**
Before killing a monster
![image](https://user-images.githubusercontent.com/3542623/167253372-cdb3fea2-124d-46df-b706-bdaab6a9b89c.png)

After killing some monsters
![image](https://user-images.githubusercontent.com/3542623/167253412-15ec4f09-0a4a-45dd-b559-0f6309174705.png)

**Additional context**
(none)

**Update**: Updated the bug report to match the template.

**Comment by AJenbo** [comment]
Please follow the issue template, you left out several key bits of information

**Comment by myself600** [comment]
OS: Windows 7 SP1 64-bit
Version: both 1.4.0/release 64-bit and latest (851b032) test builds/master 64-bit

**Comment by qndel** [comment]
https://github.com/diasurgical/devilution/blob/a44cb36af6cb755c419e83fa4b3259e001849813/Source/player.cpp#L3974-L3975

![image](https://user-images.githubusercontent.com/14297035/167256073-8922ff87-fdcf-4d0b-9614-0b19427b9b06.png)

**Comment by qndel** [comment]
Since there's no use for xp above 50 atm, I'm not sure if it's something we want to fix ...

**Comment by myself600** [comment]
I tested how this works, and I was able to gain XP on hell difficulty only via ZeroTier and Loopback, running DevX, while vanilla/1.09 allowed me to gain XP in both nightmare/hell difficulties, except normal (I killed a bunch of monsters to test this), via Direct Cable Connection. Weird. I've done a few (2-3) dlvl 15-16 runs on normal via ZT on 1.4.0 release with 0 XP gain.

**Comment by myself600** [comment]
I've also tried using lower XP points (below 1,310,707,109), and it didn't worked either (both running vanilla and DevX master)

![image](https://user-images.githubusercontent.com/3542623/167261225-afe568ec-2f42-4290-853a-fb17a5bc4259.png)
![image](https://user-images.githubusercontent.com/3542623/167261245-04478cb1-b8c2-4916-8e36-6793263f11ce.png)

**Comment by StephenCWills** [comment]
> I tested how this works, and I was able to gain XP on hell difficulty only via ZeroTier and Loopback, running DevX, while vanilla/1.09 allowed me to gain XP in both nightmare/hell difficulties, except normal (I killed a bunch of monsters to test this), via Direct Cable Connection. Weird. I've done a few (2-3) dlvl 15-16 runs on normal via ZT on 1.4.0 release with 0 XP gain.

Nothing is weird here. If the player is at least 10 levels higher than the monster, there will be no experience gain.
https://github.com/diasurgical/devilution/blob/a44cb36af6cb755c419e83fa4b3259e001849813/Source/player.cpp#L1040-L1044

The link Qndel provided only applies to the rubber banding effect that occurs right after you reach clvl 50. If you leave the game session and rejoin or join another, the rubber banding should stop, enabling you to gain experience again.

**Comment by myself600** [comment]
> Nothing is weird here. If the player is at least 10 levels higher than the monster, there will be no experience gain. https://github.com/diasurgical/devilution/blob/a44cb36af6cb755c419e83fa4b3259e001849813/Source/player.cpp#L1040-L1044

While this does answer my question, it still doesn't explain the different behavior in nightmare difficulty with DevX vs. vanilla. Thank you for answering my question tho.

Therefore, this issue can be closed. (it's invalid)

**Comment by StephenCWills** [comment]
> ... it still doesn't explain the different behavior in nightmare difficulty with DevX vs. vanilla.

Are you sure? Excluding unique monsters and Hellfire, here is the full list of monster types that will provide experience to a clvl 50 hero in Nightmare. Make sure you run your tests against the same monster types.

* Balrog
* Azure Drake
* Snow Witch
* Hellspawn
* Soul Burner
* Doom Guard
* Steel Lord
* Blood Knight
* Magistrate
* Cabalist
* Advocate

**Comment by myself600** [comment]
> https://www.youtube.com/watch?v=oHC1230OpOg

It worked! (all the aforementioned monsters gave me XP in nightmare). Tested on 1.4.0/release 64-bit. Thank you for your patience! My bad.
