### ISSUE TITLE
Shareware MPQ file could not be found

### ISSUE THREAD

**Issue by sskras** [diasurgical/devilutionX#4553]
**Important information**
Windows 10 Pro 64-bit **21H2** [Version 10.0.19044.1645]
DevilutionX 1.4.0 (not sure how can I check it directly). I downloaded [the release](https://github.com/diasurgical/devilutionX/releases/download/1.4.0/devilutionx-windows-x86_64.zip) from GitHub.

**Describe**
The game doesn't find the shareware MPQ file.

**To Reproduce**
1. Extract DevilutionX files from the archive.
2. Extract SPAWN.MPQ file from `diablosw.exe` into the same dir.
3. Run `devilutionx.exe`
4. See error:

> Unable to open main data archive (diabdat.mpq or spawn.mpq).
> 
> Make sure that it is in the game folder.

**Expected behavior**
I expect the game to start successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/7887758/167306581-4c8b6777-514a-44f3-a954-5e8eead5e59a.png)

---

**Additional context**
I tried renaming the MPQ into `DIABDAT.MPQ` to no avail.

Here is log from my MSYS2 console:
```
$ ./devilutionx
ERROR: Couldn't open C:\Users\saukrs\Downloads\devilutionx\assets/ui_art\title.pcx
ERROR: Data File Error
Unable to open main data archive (diabdat.mpq or spawn.mpq).

Make sure that it is in the game folder.

$ ll
total 67792
-rw-r--r-- 1 saukrs None 52066296 Jan  8  1997 DIABDAT.MPQ
drwxr-xr-x 1 saukrs None        0 Apr 13 20:12 LICENSE
-rw-r--r-- 1 saukrs None     2417 Apr 13 14:08 README.txt
-rwxr-xr-x 1 saukrs None  2231296 Apr 13 20:09 SDL2.dll
-rwxr-xr-x 1 saukrs None  6254592 Apr 13 20:12 devilutionx.exe
-rw-r--r-- 1 saukrs None  4959824 Apr 13 20:11 devilutionx.mpq
-rwxr-xr-x 1 saukrs None  3891512 Nov 27  2019 discord_game_sdk.dll
```

**Comment by AJenbo** [comment]
`SPAWN.MPQ` -> `spawn.mpq`

**Comment by AJenbo** [comment]
You can get the version via `devilutionx --version`

**Comment by StephenCWills** [comment]
Where did you get that spawn.mpq? It appears to be the wrong size.

![image](https://user-images.githubusercontent.com/9203145/167307345-ff80b518-cedb-44d5-9672-e41410cccbe3.png)

**Comment by AJenbo** [comment]
@sskras what you have here appears to be the container MPQ from the exe, probably you used 7z, which is not the right way to get spawn.mpq.

**Comment by sskras** [comment]
@AJenbo:

> You can get the version via `devilutionx --version`

This didn't work in my MSYS2 terminal:
```
saukrs@DESKTOP-O7JE7JE MSYS /C/Users/saukrs/Downloads/devilutionx
$ time ./devilutionx --version

real    0m0.078s
user    0m0.000s
sys     0m0.031s
```

When I use CMD, it somehow works.  Albeit there is still something wrong with the output:

https://user-images.githubusercontent.com/7887758/167309456-999283c1-9b14-4078-92e1-320d23af20ba.mp4

Could be a missing flush on stdout?
Should I open a bug for that?

**Comment by StephenCWills** [comment]
That is because the game is not compiled as a console app. I'm pretty certain Microsoft considers this to be expected behavior, so there's no need for a bug report.

**Comment by AJenbo** [comment]
Sorry I don't know anything about MSYS and little about Windows in general.

**Comment by sskras** [comment]
> That is because the game is not compiled as a console app. 

Why it's writing to the stdout then?

> I'm pretty certain Microsoft considers this to be expected behavior, so there's no need for a bug report.

I need some testcase to prove that point.

**Comment by StephenCWills** [comment]
> Why it's writing to the stdout then?

Because sometimes the window fails to launch. Even if it doesn't fail, we can't necessarily use it to display help text in a user-friendly way. Also keep in mind that Windows isn't the only platform DevilutionX runs on.

> I need some testcase to prove that point.

By all means, feel free to make one. Use `/SUBSYSTEM:WINDOWS`
https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170

**Comment by sskras** [comment]
> > Why it's writing to the stdout then?
> 
> Because sometimes the window fails to launch. 

Not in that case: the application was putting text both on the window and into the stdout.

> Even if it doesn't fail, we can't necessarily use it to display help text in a user-friendly way. 

But the app does it. It even does it when it has two windows created.  Either your eplanation is wrong or the app logic is flawed.

> Also keep in mind that Windows isn't the only platform DevilutionX runs on.

That's a bad excuse for a cross-platform app.

> > I need some testcase to prove that point.
> 
> By all means, feel free to make one. Use `/SUBSYSTEM:WINDOWS` https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170

This starts feeling rude.  The statement was made by you.  It looked improbable to me as 16y ago I was writing related test cases for Wine project.  And so I asked for a proof.  You seem to avoid to base your certainty using the code.

So your argument stays just a hypothesis, not a fact.

**Comment by glebm** [comment]
@sskras This is an open-source project with many contributors. Rather than arguing in bad faith, consider looking into the code and sending a PR. The relevant function is `printInConsole`.

**Comment by StephenCWills** [comment]
> Not in that case: the application was putting text both on the window and into the stdout.

The application doesn't have stdout. It attaches to the console of the parent process and puts its output into that console's stderr.

> But the app does it. It even does it when it has two windows created. Either your eplanation is wrong or the app logic is flawed.

There is at least one more explanation. Perhaps your understanding is wrong.

> That's a bad excuse for a cross-platform app.

I'm not sure what it is you think I am excusing. All I'm saying is that we shouldn't have to avoid using stderr just because Windows handles it in a strange way.

> This starts feeling rude. The statement was made by you. It looked improbable to me as 16y ago I was writing related test cases for Wine project. And so I asked for a proof. You seem to avoid to base your certainty using the code.
>
> So your argument stays just a hypothesis, not a fact.

I'm sorry that you thought I was being rude. You said you needed a testcase, so I assumed you intended to prove it to yourself. I don't think it's strange for me to say that not going to spend my time providing one, if that's what you were expecting.
