### ISSUE TITLE
FreeBSD: build failing (ZeroTier)

### ISSUE THREAD

**Issue by nunotexbsd** [diasurgical/devilutionX#4554]
Hello,

I'm FreeBSD devilutionX port maintainer and I'm having some troubles updating to latest version.
Port is at 1.2.1 version and I'm trying to update it to 1.3.0 first and next to 1.4.0.

Could anyone take a look at my [build logs](https://people.freebsd.org/~eduardo/logs/devilutionX/) to give some hints to fix it?

FreeBSD [devilutionX port](https://www.freshports.org/games/devilutionX/) started at 0.4.0 to 1.2.1 version.

Thanks,

Nuno Teixeira

**Comment by AJenbo** [comment]
It's failing to build ZeroTier, try disabeling it with this CMake argument: `-DDISABLE_ZERO_TIER=ON`

**Comment by nunotexbsd** [comment]
Thanks a lot it builds ok now!
Now I need to make some adjustments to port and testing it in game mode.

Thank you :)

**Comment by AJenbo** [comment]
Note that this also appears to be an issue for other BSD systems so it might be good if you can add this to the BSD build configuration: https://github.com/diasurgical/devilutionX/blob/master/CMake/Platforms.cmake#L9

**Comment by glebm** [comment]
The error appears to come from libzt:

```
/usr/home/nunotex/Work/freebsd/ports/games/devilutionX/work/.build/_deps/libzt-src/include/net/route.h:66:10: fatal error: 'sys/appleapiopts.h' file not found
#include <sys/appleapiopts.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by AJenbo** [comment]
Please submit patches as PRs so we can integrate them and know what actual requirement the platform has for building.

**Comment by nunotexbsd** [comment]
Sorry it build it to ./.build/devilutionx and I can run it from there.

Maybe I need a tweek to move it to port stage /usr/local/bin

I will ask for help and do more tests to see whats hapenning.

But it runs ok.
