### ISSUE TITLE
[Request] Ubuntu Touch Builds

### ISSUE THREAD

**Issue by nitanmarcel** [diasurgical/devilutionX#4559]
Could we have an [Ubuntu Touch](https://ubuntu-touch.io/) build? I'm not so good with these things, and what I've done is create a bookmark for the old diabloweb project is now it's getting old. I also had diabloweb hosted on the device but I reverted back to bookmarks due to license issues. The webapp can be found [here](https://gitlab.com/nitanmarcel/diablo-web-ubuntu-touch).

All I can help with is pointing to the Ubuntu Touch app development documentation:

https://docs.ubports.com/en/latest/appdev/index.html

https://docs.ubports.com/en/latest/appdev/guides/index.html

Something that could help in the porting process is the OpenTTD port for Ubuntu Touch https://gitlab.com/abmyii/openttd-ubports

**Comment by AJenbo** [comment]
It's already being worked on: https://github.com/diasurgical/devilutionX/pull/4223
