### ISSUE TITLE
Repair Bug With Cursed Items

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#4575]
**Important information**
Windows 10 / 1.4.0 / Re;ease

**Describe**
Hitting Enter in the Repair screen with a damaged cursed item in your inventory and all other items at full durability (or no other items) will bring you to a repair item screen that says "NO REQUIRED ATTRIBUTES" and ask if you want to repair the item. If you choose yes, nothing happens.

**To Reproduce**
1. Obtain a cursed item that is missing durability.
2. Clear inventory of all other items or restore durability on all items except the cursed item.
3. Talk to Griswold
4. Select Repair Items
5. Notice "Back" is not selected by the spinning icons.
6. Press Enter on keyboard to see bugged menu.

**Expected behavior**
Back should be selected, and enter should take you back to Griswold's talk menu. Cursed item should not impact the repair screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/28605404/168458142-161343c5-d6fa-414e-a730-cb98845e89de.png)
![image](https://user-images.githubusercontent.com/28605404/168458145-6130b908-d860-48e7-b492-11643d59f5fe.png)
![image](https://user-images.githubusercontent.com/28605404/168458147-2005622e-431b-4520-b7d3-55cba3278217.png)

**Comment by qndel** [comment]
@NiteKat can u check if it's a vanilla bug?
