### ISSUE TITLE
Panel redraw and position issue when minimizing window

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#458]
To reproduce:
1. use upscale=0 in diablo.ini
2. minimize and maximize the window
3. After maximizing yo will get shifted and wrong colored panel.
![panel](https://user-images.githubusercontent.com/45902449/68708392-e5aef000-0593-11ea-8769-85bb879026b0.png)

**Comment by AJenbo** [comment]
Could you test this again on latest master and give us the terminal output

**Comment by AJenbo** [comment]
I am unable to replicate this. I have a feeling that this is specific to your GPU, but I'm not sure what triggers it so I can't really do anything about it without more information.

**Comment by Chance4us** [comment]
Now I tested again and can give you important additional information.
The issue only happen when you are affected by #457 at the same time.
So you have to wait until the Lazarus cutscene is ended.
After the cutscene you could get some of following panels.
![2](https://user-images.githubusercontent.com/45902449/68744716-88e42180-05f5-11ea-8dd0-0e7494a4b3c1.png)
![1](https://user-images.githubusercontent.com/45902449/68744728-8c77a880-05f5-11ea-8ce9-b0adf103c0c0.png)

**Comment by Chance4us** [comment]
Just tested the latest commit.
Because # 457 is resolved, the error no longer occurs.

**Comment by Chance4us** [comment]
Feel free to close the report.

**Comment by AJenbo** [comment]
Probably the previous fix solved it, except when you also had the event issue as it would block the redraw event.
