### ISSUE TITLE
Black mushroom quest wont complete if the potion is in your belt

### ISSUE THREAD

**Issue by CaptainCosmotic** [diasurgical/devilutionX#4583]
**Important information**
Windows 10 / v1.4.0 Nightly build from 2 days ago / download

**Describe**
If you pick up the potion from Pepin after delivering the brain it can go into your belt. Then Adria won't take it from there. You have to put it into your inventory before ending the quest. Very small issue but maybe a simple fix

**To Reproduce**
1. Do the black mushroom quest
2. deliver the brain to Pepin
3. Pick up the potion with a free slot in your belt
4. go top Adria
5. try to complete the quest

**Expected behavior**
The potion should either not go to your belt, or complete the quest if it's in your belt

**Screenshots**

**Additional context**
It's a very small issue but maybe an easy fix

**Comment by AJenbo** [comment]
`Player::HasItem()` and `Player::RemoveInvItem()` should be updated to also check the belt.

**Comment by glebm** [comment]
We may want to add something like this to avoid passing indices around:

```c++
bool TryRemoveItem(_item_indexes item);
```

**Comment by glebm** [comment]
Nevermind, looks like we have that already and it uses it:

https://github.com/diasurgical/devilutionX/blob/354e329644b3ccaf303081cdfffa41dae02cd727/Source/towners.cpp#L423

Internally it does use `HasItem` and `RemoveItem`, which rely on indices in the inventory array:

https://github.com/diasurgical/devilutionX/blob/30a6d3412f4a254b1b933c11b3b2e3c8c772f528/Source/player.cpp#L1934-L1942

**Comment by glebm** [comment]
This could be implemented very similar to `RemoveScroll` instead of relying on `HasItem/RemoveInvItem`:

https://github.com/diasurgical/devilutionX/blob/354e329644b3ccaf303081cdfffa41dae02cd727/Source/inv.cpp#L1946-L1968

**Comment by AJenbo** [comment]
Sounds good :+1:
