### ISSUE TITLE
Right-clicking golem scroll does not create targeting cursor

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#4589]
**Important information**
Windows 10 / Latest master

**Describe**
Right-clicking a golem scroll makes golem spawn noise, but does not prompt targeting cursor. Using it as a hotspell does work as this bypasses the need for another click to target the ground.

**Expected behavior**
Targeting cursor to left click spot where you want golem should appear.

**Comment by AJenbo** [comment]
`Latest master` which one was this for you at time of writing?

**Comment by DakkJaniels** [comment]
Right clicking made golems for me when I just tried it on latest master (d56ca5da)

**Comment by FitzRoyX** [comment]
https://github.com/diasurgical/devilutionX/actions/runs/2337749038

Could this be an old save issue? I'll try to load my save too
[ddd.zip](https://github.com/diasurgical/devilutionX/files/8711328/ddd.zip)

**Comment by FitzRoyX** [comment]
Oh wait, after trying again several times, I can find him really far south from me. But if I'm near a wall, sometimes I can't find him at all like he's spawning in the wall or in another room somewhere.

**Comment by FitzRoyX** [comment]
Ok, some new info. The spawn location seems to be related to where the belt is onscreen. So if you're in a high resolution like 1600x900, the golem spawns much farther away from you than if you're in 640x480.

**Comment by StephenCWills** [comment]
Confirmed in vanilla. I agree that it's pretty unintuitive, but I removed the bug label because the golem does spawn.

If anyone wants to go after this one, I recommend experimenting with the `sTargeted` flag in spelldat.cpp. Also, it will need to be tested with gamepad to ensure that it can still be used to cast golems.

**Comment by FitzRoyX** [comment]
Worth noting that the scroll does say it's a targeting, so maybe it is indeed a vanilla bug?

![sd](https://user-images.githubusercontent.com/57089001/171490228-4434c2ba-5c76-4550-94a8-c9909e8199b0.jpg)

The opposite issue happens with Flash, where a scroll says it's targeting, but it's not. I'll create a separate report for that later.

**Comment by nwildner** [comment]
Don´t know if this already incorporated to `1.4.1` but, had this same issue while playing Rogue

Right clicked the scroll in the Inventory, and the scroll is gone while no targeting cursor is created, neither a Golem is spawned.

Right clicking the scroll in the belt bar does work(while no targeting is provided), and using the spell right click action also works.

```
devilutionx --version
DevilutionX v1.4.1
```
