### ISSUE TITLE
Sony Interactive Entertainment Controller not working in the game with my OS

### ISSUE THREAD

**Issue by Dartomic** [diasurgical/devilutionX#4596]
**Important information**
 
Operating system:
Funtoo Linux - 64bit - Mate DE - skylake

DevilutionX version: 1.4.0

did you download a release or did you compile yourself?
Downloaded the appimage release.

**Describe**
A clear and concise description of what the bug is:

I know this controller works with the appimage on Ubuntu, because I have used it in this game when I used to have Ubuntu.

The game does recognize the controller, because the console outputs this message:

INFO: Adding joystick 0: Sony Interactive Entertainment Controller

But for some reason, it is not responding to any of the buttons that I press on the controller.

The controller does work in my OS. I just tested it with the Retroarch appimage on my OS.

**To Reproduce**
I am thinking that it would be easier if someone could tell me where I should look, such as a configuration file, or an option given in the terminal when I launch the appimage. This is because in order to reproduce it, you either would have to install a stage3 funtoo build, with the Mate DE, or do the same thing, but on a skylake system.

Other than the Linux distribution, I ran the game like this:
1. chmod u+x ./devilutionx-linux-x86_64.appimage
2. ./devilutionx-linux-x86_64.appimage
3. Try using your "Sony Interactive Entertainment Controller" (the controller that comes with the PS1 Classic)
4. It will probably work for you if you are not running Funtoo, or the same Stage3 version of Funtoo as me. So that's probably a barrier to reproducing my issue.

**Expected behavior**
Controller should allow me to use it to interact with the game.

**Comment by AJenbo** [comment]
The issue seams to be with the controller DB that ships with your OS being out of date: https://github.com/gabomdq/SDL_GameControllerDB
