### ISSUE TITLE
after updating to 1.4, after selecting character, game crashes while loading into world

### ISSUE THREAD

**Issue by MrSco** [diasurgical/devilutionX#4597]
**Important information**
Nintendo Switch  Current Version: 13.1.0|AMS 1.3.2|S / DevilutionX version 1.4 / downloaded release 

**Describe**
after updating to 1.4, after selecting character, game crashes while loading into world. the progress bar gets about half way and then switch system error black screen with ok button to close back to switch home screen. (using hold 'R' button override app method to launch.)

**To Reproduce**
1. Go to select character to start game
2. wait for loading
3. game crashes while loading

**Expected behavior**
game world should load and not crash game

**Screenshots**
see attached video

**Additional context**
tried both regular diablo and hellfire. both crash the same way. i also tried deleting my diablo.ini so it would create a fresh one on launch (which it did) but still no go.

https://user-images.githubusercontent.com/11297411/169532725-c98f0f16-cffe-40e0-a949-b0272ed56cf8.MOV

**Comment by DakkJaniels** [comment]
Does it crash with a new character?

**Comment by MrSco** [comment]
> 

yes, new old. doesn't matter.

**Comment by StephenCWills** [comment]
If you have a copy of `devilutionx.mpq` on your SD card, remove it and try again.

**Comment by MrSco** [comment]
> Oh, devilutionx.mpq
Isn’t needed anymore?
On May 20, 2022, 9:12 AM -0400, Stephen C. Wills ***@***.***>, wrote:
	If you have a copy of devilutionx.mpq on your SD card, remove it and try again.

**Comment by StephenCWills** [comment]
The appropriate version of `devilutionx.mpq` is now embedded in `devilutionx.nro` file so it does not need to be on your SD card.

**Comment by MrSco** [comment]
> The appropriate version of `devilutionx.mpq` is now embedded in `devilutionx.nro` file so it does not need to be on your SD card.

awesome! that was it. thanks!
