### ISSUE TITLE
IOS Instalation problem

### ISSUE THREAD

**Issue by marcinwielocha** [diasurgical/devilutionX#4622]
**Important information**
IOS 15.5 / DevilutionX version 1.4 / Download release .ipa file?

**Describe**
When i try to install ipa file using https://sideloadly.io/ or any other programs i can see that info: ERROR: Guru Meditation da8d42@132:556260@220:bede73 This does not look like valid iOS app! 

**To Reproduce**
1. Go to 'Sideloadly program'
2. Click on 'Start button'
3. See error
Sideloadly version 0.26.2, Windows 10.0, amd64
Using IPA file: C:/Users/Wieloszki/Downloads/devilutionx-ios (1).ipa: 779bd908206158eba011166e2baf985e
Checking iOS version...
iOS version 15.5, will mangle bundleID
Obtaining team ID
Using team "Marcin Wielocha" (Individual) with id R96L72Q89J
Making sure device ID 00008030-001469A23C45802E is registered
Device 00008030-001469A23C45802E is already registered
Checking private key
Looking up app ID
Using app ID "DevilutionX" with id 4MQPUWUP5B
Signing...
ERROR: Guru Meditation da8d42@132:556260@220:bede73 This does not look like valid iOS app!

**Expected behavior**
Information or fix

**Comment by Trihedraf** [comment]
I just installed the 1.4.0 Release ipa using AltStore and it worked normally.

**Comment by StephenCWills** [comment]
Can someone provide a link to an ipa that has been confirmed valid by Sideloadly?

**Comment by Trihedraf** [comment]
Fixed by #5056
