### ISSUE TITLE
Builds fail on aarch64 enviroment when compiling AES

### ISSUE THREAD

**Issue by nitanmarcel** [diasurgical/devilutionX#4624]
I've been trying to build for aarch64 so I can run it on my Droidian distro (Debian for mobile phones) but without any success. Somewhere at the middle of the compilation it crashes:

The full build log can be found at on the Build Artifacts step.

https://github.com/nitanmarcel/devilutionX/runs/6646091273?

Been trying to also paste the log to a pastebin but it's broken due to colored errors. But here it is if for some reason can't browse the workflow logs:

https://pastebin.ubuntu.com/p/4vxvrKftgD/

**Comment by AJenbo** [comment]
We compile to multiple ARM targets on every commit so this isn't a general issue. Your log indicates the issue is ZeroTier and appears to be related to neon optimizations, maybe something in your env isn't setup correctly for that? Try starting with building without ZeroTier.

**Comment by StephenCWills** [comment]
Maybe this will help. https://github.com/diasurgical/devilutionX/issues/3930#issuecomment-1008329237

**Comment by nitanmarcel** [comment]
> We compile to multiple ARM targets on every commit so this isn't a general issue. Your log indicates the issue is ZeroTier and appears to be related to neon optimizations, maybe something in your env isn't setup correctly for that? Try starting with building without ZeroTier.

Yep. Disabling ZeroTier fixed the issue. About the AES error totally is the way I'm compiling, probably because I'm compiling on an arm64 machine.

**Comment by nitanmarcel** [comment]
Btw, idk if it's related to the compilation but I'm facing this error when trying to run it on my device:

```
The error occured at: `Source/sound.cpp line 202
```
```
INFO: Removed file: /home/droidian/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo
ERROR: SDL Error
drwav_init failed.

The error occurred at: Source/sound.cpp line 202
INFO: Adding joystick 0: uinput-fpc
INFO: Opening game controller for joystick at index 0
INFO: Opened game controller with mapping:
0600000075696e7075742d6670630000,uinput-fpc,a:b0,b:b1,x:b3,y:b4,lefttrigger:a0,platform:Linux
```

**Comment by nitanmarcel** [comment]
> Btw, idk if it's related to the compilation but I'm facing this error when trying to run it on my device:
> 
> ```
> The error occured at: `Source/sound.cpp line 202
> ```
> 
> ```
> INFO: Removed file: /home/droidian/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo
> ERROR: SDL Error
> drwav_init failed.
> 
> The error occurred at: Source/sound.cpp line 202
> INFO: Adding joystick 0: uinput-fpc
> INFO: Opening game controller for joystick at index 0
> INFO: Opened game controller with mapping:
> 0600000075696e7075742d6670630000,uinput-fpc,a:b0,b:b1,x:b3,y:b4,lefttrigger:a0,platform:Linux
> ```
> 
> Debian Bookworm Ran with `DISPLAY=:0 devilutionx --diablo` Using brach 1.4

On master this occurs at line 86.

Should I open another issue about this? @AJenbo 

```
Keyboard layout unknown, please report the following to the SDL forums/mailing list (https://discourse.libsdl.org/):
code = 1, sym = 0x30 (0) scancode = 39 (0)
code = 2, sym = 0x31 (1) scancode = 30 (1)
code = 3, sym = 0x32 (2) scancode = 31 (2)
code = 4, sym = 0x33 (3) scancode = 32 (3)
code = 5, sym = 0x34 (4) scancode = 33 (4)
code = 6, sym = 0x35 (5) scancode = 34 (5)
code = 7, sym = 0x36 (6) scancode = 35 (6)
code = 8, sym = 0x37 (7) scancode = 36 (7)
code = 9, sym = 0x38 (8) scancode = 37 (8)
code = 10, sym = 0x39 (9) scancode = 38 (9)
code = 11, sym = 0x41 (A) scancode = 4 (A)
code = 12, sym = 0x42 (B) scancode = 5 (B)
code = 13, sym = 0xFF08 (BackSpace) scancode = 42 (Backspace)
code = 14, sym = 0x43 (C) scancode = 6 (C)
code = 15, sym = 0x44 (D) scancode = 7 (D)
code = 16, sym = 0x45 (E) scancode = 8 (E)
code = 17, sym = 0x46 (F) scancode = 9 (F)
code = 18, sym = 0x47 (G) scancode = 10 (G)
code = 19, sym = 0x48 (H) scancode = 11 (H)
code = 20, sym = 0x49 (I) scancode = 12 (I)
code = 21, sym = 0x4A (J) scancode = 13 (J)
code = 22, sym = 0x4B (K) scancode = 14 (K)
code = 23, sym = 0x4C (L) scancode = 15 (L)
code = 24, sym = 0x4D (M) scancode = 16 (M)
code = 25, sym = 0x4E (N) scancode = 17 (N)
code = 26, sym = 0x4F (O) scancode = 18 (O)
code = 27, sym = 0x50 (P) scancode = 19 (P)
code = 28, sym = 0x51 (Q) scancode = 20 (Q)
code = 29, sym = 0x52 (R) scancode = 21 (R)
code = 30, sym = 0xFF0D (Return) scancode = 40 (Return)
code = 31, sym = 0x53 (S) scancode = 22 (S)
code = 32, sym = 0x54 (T) scancode = 23 (T)
code = 33, sym = 0x55 (U) scancode = 24 (U)
code = 34, sym = 0x20 (space) scancode = 44 (Space)
code = 35, sym = 0x21 (exclam) scancode not found
code = 36, sym = 0x22 (quotedbl) scancode not found
code = 37, sym = 0x23 (numbersign) scancode not found
code = 38, sym = 0x24 (dollar) scancode not found
code = 39, sym = 0x25 (percent) scancode not found
code = 40, sym = 0x26 (ampersand) scancode not found
code = 41, sym = 0x27 (apostrophe) scancode = 52 (')
code = 42, sym = 0x28 (parenleft) scancode not found
code = 43, sym = 0x29 (parenright) scancode not found
code = 44, sym = 0x2A (asterisk) scancode not found
code = 45, sym = 0x2B (plus) scancode not found
code = 46, sym = 0x2C (comma) scancode = 54 (,)
code = 47, sym = 0x2D (minus) scancode = 45 (-)
code = 48, sym = 0x2E (period) scancode = 55 (.)
code = 49, sym = 0x2F (slash) scancode = 56 (/)
code = 50, sym = 0x3A (colon) scancode not found
code = 51, sym = 0x3B (semicolon) scancode not found
code = 52, sym = 0x3C (less) scancode not found
code = 53, sym = 0x3D (equal) scancode = 46 (=)
code = 54, sym = 0x3E (greater) scancode not found
code = 55, sym = 0x3F (question) scancode not found
code = 56, sym = 0x40 (at) scancode not found
code = 57, sym = 0x5B (bracketleft) scancode = 47 ([)
code = 58, sym = 0x5C (backslash) scancode = 49 (\)
code = 59, sym = 0x5D (bracketright) scancode = 48 (])
code = 60, sym = 0x5E (asciicircum) scancode not found
code = 61, sym = 0x5F (underscore) scancode not found
code = 62, sym = 0x60 (grave) scancode = 53 (`)
code = 63, sym = 0x7B (braceleft) scancode not found
code = 64, sym = 0x7C (bar) scancode not found
code = 65, sym = 0x7D (braceright) scancode not found
code = 66, sym = 0x7E (asciitilde) scancode not found
code = 67, sym = 0xA3 (sterling) scancode not found
code = 68, sym = 0xA5 (yen) scancode not found
code = 69, sym = 0xA9 (copyright) scancode not found
code = 70, sym = 0xAE (registered) scancode not found
code = 71, sym = 0xB0 (degree) scancode not found
code = 72, sym = 0xB6 (paragraph) scancode not found
code = 73, sym = 0xB7 (periodcentered) scancode not found
code = 74, sym = 0xD7 (multiply) scancode not found
code = 75, sym = 0xF7 (division) scancode not found
code = 76, sym = 0x10003C0 (U03C0) scancode not found
code = 77, sym = 0x10003C4 (U03C4) scancode not found
code = 78, sym = 0x10020AC (U20AC) scancode not found
code = 79, sym = 0x100221A (squareroot) scancode not found
code = 80, sym = 0x56 (V) scancode = 25 (V)
code = 81, sym = 0x57 (W) scancode = 26 (W)
code = 82, sym = 0x58 (X) scancode = 27 (X)
code = 83, sym = 0x59 (Y) scancode = 28 (Y)
code = 84, sym = 0x5A (Z) scancode = 29 (Z)
code = 85, sym = 0x61 (a) scancode = 4 (A)
code = 86, sym = 0x62 (b) scancode = 5 (B)
code = 87, sym = 0x63 (c) scancode = 6 (C)
code = 88, sym = 0x64 (d) scancode = 7 (D)
code = 89, sym = 0x65 (e) scancode = 8 (E)
code = 90, sym = 0x66 (f) scancode = 9 (F)
code = 91, sym = 0x67 (g) scancode = 10 (G)
code = 92, sym = 0x68 (h) scancode = 11 (H)
code = 93, sym = 0x69 (i) scancode = 12 (I)
code = 94, sym = 0x6A (j) scancode = 13 (J)
code = 95, sym = 0x6B (k) scancode = 14 (K)
code = 96, sym = 0x6C (l) scancode = 15 (L)
code = 97, sym = 0x6D (m) scancode = 16 (M)
code = 98, sym = 0x6E (n) scancode = 17 (N)
code = 99, sym = 0x6F (o) scancode = 18 (O)
code = 100, sym = 0x70 (p) scancode = 19 (P)
code = 101, sym = 0x71 (q) scancode = 20 (Q)
code = 102, sym = 0x72 (r) scancode = 21 (R)
code = 103, sym = 0x73 (s) scancode = 22 (S)
code = 104, sym = 0x74 (t) scancode = 23 (T)
code = 105, sym = 0x75 (u) scancode = 24 (U)
code = 106, sym = 0x76 (v) scancode = 25 (V)
code = 107, sym = 0x77 (w) scancode = 26 (W)
code = 108, sym = 0x78 (x) scancode = 27 (X)
code = 109, sym = 0x79 (y) scancode = 28 (Y)
code = 110, sym = 0x7A (z) scancode = 29 (Z)
ERROR: Missing file: ui_art\focus.pcx
INFO: Removed file: /home/droidian/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo
ERROR: SDL Error
drwav_init failed.

The error occurred at: Source/sound.cpp line 86
INFO: Adding joystick 0: uinput-fpc
INFO: Opening game controller for joystick at index 0
INFO: Opened game controller with mapping:
0600000075696e7075742d6670630000,uinput-fpc,a:b0,b:b1,x:b3,y:b4,lefttrigger:a0,platform:Linux
```

**Comment by nitanmarcel** [comment]
> @nitanmarcel Seems like something is off with diabdat.mpq, or possibly libmpq. Can you take an MD5 hash of diabdat.mpq to verify integrity? It should match one of these two results.
> 
> ```
> $ md5sum DIABDAT.MPQ
> 011bc6518e6166206231080a4440b373  DIABDAT.MPQ
> 68f049866b44688a7af65ba766bef75a  DIABDAT.MPQ
> ```

Yes it was. And I used the one from the readme.

Anyway got it run it but not fullscreen and the touch controls aren't working.

**Comment by nitanmarcel** [comment]
Nvm. I had to start the game in landscape mode for it to fully go fullscreen. And the touch buttons work except the joystick which seems to not work at all

**Comment by StephenCWills** [comment]
The on-screen buttons and joystick all react to the same touch events so I wouldn't be sure where to begin troubleshooting that.

https://github.com/diasurgical/devilutionX/blob/master/Source/controls/touch/event_handlers.cpp#L162

**Comment by nitanmarcel** [comment]
> Nvm. I had to start the game in landscape mode for it to fully go fullscreen. And the touch buttons work except the joystick which seems to not work at all
> 
> No extra logs
> 
> ```
> INFO: Removed file: /home/droidian/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo
> INFO: Adding joystick 0: uinput-fpc
> INFO: Opening game controller for joystick at index 0
> INFO: Opened game controller with mapping:
> ```

oh. the joystick is actually the fingerprint

> Adding joystick 0: uinput-fpc

Doesn't do nothing for me, rest of the buttons work. Also afaik isn't `uinput-fpc` the fingerprint input (which doesn't work on my device)?

**Comment by nitanmarcel** [comment]
Not sure how related to this but kinda the same thing happens. except it doesn't hide the touch input.

https://github.com/libgdx/libgdx/issues/5596

**Comment by StephenCWills** [comment]
Ah, in the logs, the joystick refers to a physical gamepad. Looks like there's a workaround for this upstream, but it's compiled only for Android. https://github.com/libsdl-org/SDL/commit/a2e856523089d5d95ba565a26a35ab367c960f12

**Comment by nitanmarcel** [comment]
This uses SDL too. Looks like it's

> Ah, in the logs, the joystick refers to a physical gamepad. Looks like there's a workaround for this upstream, but it's compiled only for Android. [libsdl-org/SDL@a2e8565](https://github.com/libsdl-org/SDL/commit/a2e856523089d5d95ba565a26a35ab367c960f12)

Probably there can be a `#if defined(__LINUX_MOBILE__)` or something? Anyway I'll test the workaround and report back

**Comment by nitanmarcel** [comment]
Ah wait. it's the actual SDL code

**Comment by AJenbo** [comment]
> Also afaik isn't `uinput-fpc` the fingerprint input (which doesn't work on my device)?

I don't even know what device you have :shrug:

**Comment by nitanmarcel** [comment]
> > Also afaik isn't `uinput-fpc` the fingerprint input (which doesn't work on my device)?
> 
> I don't even know what device you have 🤷

Redmi Note 9 Pro, running on Droidian (Debian). 

And it looks like the issue is known and fixed but they didn't excepted for linux phones to become a thing

https://discourse.libsdl.org/t/sdl-the-google-pixel-fingerprint-sensor-isnt-actually-a-joystick/33716

**Comment by nitanmarcel** [comment]
Even if sdl detects the fingerprint as a joystick, the virtual gamepad doesn't go away. Probably because the fingerprint isn't working on the my device but got me thinking: Shouldn't the virtual joystick work until the actual joystick event was triggered?

For now it looks like the fingerprint captures the events that should be sent to the virtual controller and it stops it from listening from touch events.

Also I got an issue open on sdl github https://github.com/libsdl-org/SDL/issues/5737#issuecomment-1141491213

**Comment by StephenCWills** [comment]
> Even if sdl detects the fingerprint as a joystick, the virtual gamepad doesn't go away. Probably because the fingerprint isn't working on the my device but got me thinking: Shouldn't the virtual joystick work until the actual joystick event was triggered?
> 
> For now it looks like the fingerprint captures the events that should be sent to the virtual controller and it stops it from listening from touch events.

You haven't really described the behavior well enough for me to know what you're talking about, but perhaps there is a constant stream of spurious joystick events coming from the analog inputs of your fingerprint reader that are switching the control mode of the game from `VirtualGamepad` to `Gamepad`.

**Comment by nitanmarcel** [comment]
> > Even if sdl detects the fingerprint as a joystick, the virtual gamepad doesn't go away. Probably because the fingerprint isn't working on the my device but got me thinking: Shouldn't the virtual joystick work until the actual joystick event was triggered?
> > For now it looks like the fingerprint captures the events that should be sent to the virtual controller and it stops it from listening from touch events.
> 
> You haven't really described the behavior well enough for me to know what you're talking about, but perhaps there is a constant stream of spurious joystick events coming from the analog inputs of your fingerprint reader that are switching the control mode of the game from `VirtualGamepad` to `Gamepad`.

Yes but on switching shouldn't the display being hidden?

The actual behavior is: 

- The game starts
- I can navigate the menu with my touch
- I can click on the virtual buttons excepting the virtual joystick which doesn't work at all

Unless my OS receives input from the fingerprint constantly which it isn't implemented in the OS, just exists there, in the system but can not be read from, I don't really see how the virtual one wouldn't work, since also the UI does not disappear because nothing from an `Gamepad` is pressed

**Comment by StephenCWills** [comment]
> Yes but on switching shouldn't the display being hidden?

Yep, you're spot on.

> The actual behavior is:
> 
> * The game starts
> * I can navigate the menu with my touch
> * I can click on the virtual buttons excepting the virtual joystick which doesn't work at all

Okay, that sounds like what I initially assumed you meant, but the fingerprint reader discussion had me second-guessing. I agree that the fingerprint reader probably has nothing to do with it.

The link I provided before points to the function where each on-screen button as well as the joystick (referred to in the code as the d-pad) is checked to determine whether the touch event interacts with it. I'd guess that either the touch events are being suppressed in that area of the screen or else the touch event coordinates somehow don't match up with the location of the joystick on screen. I recommend putting in logging statements there to help troubleshoot.

FYI, if you open the inventory, you should be able to see the cursor in the location on the screen where you touch. You might want to try opening the inventory and touching the joystick to see what happens. Perhaps you'll gain some insight without any code changes that way.

**Comment by nitanmarcel** [comment]
Or I can increase the resolution to move the joystick above another UI element. Does that still count?.

The joystick is above the "__Quests__" button, I can click at the margin of the joystick to open the quest menu but I can't move the joystick.

**Comment by AJenbo** [comment]
on regular linux it should just use the system provided sdl.

does the touch screen not send continuous finger down, or does it immediately release?

**Comment by nitanmarcel** [comment]
> Ah, in the logs, the joystick refers to a physical gamepad. Looks like there's a workaround for this upstream, but it's compiled only for Android. [libsdl-org/SDL@a2e8565](https://github.com/libsdl-org/SDL/commit/a2e856523089d5d95ba565a26a35ab367c960f12)

Now this should also be fixed for non-android devices.

**Comment by AJenbo** [comment]
https://github.com/libsdl-org/SDL/commit/7fa46ec40b8b6a58f174f0992ecead0a1ab23817
