### ISSUE TITLE
Multiple OOB in dlrg_l3.cpp

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#463]
Simply load this save to reproduce:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/3846107/single_0.zip)

Causes crashes on MIPS (RG300)

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/9e45a6928058105e376097a0ad4978131d9c4c3c
