### ISSUE TITLE
Request some commits in 1.4.1

### ISSUE THREAD

**Issue by dmitryluhtionov** [diasurgical/devilutionX#4633]
Is it possible to add the following commits to the 1.4.1 branch ?
https://github.com/diasurgical/devilutionX/pull/4588
https://github.com/diasurgical/devilutionX/pull/4591
https://github.com/diasurgical/devilutionX/pull/4592

**Comment by glebm** [comment]
Also https://github.com/diasurgical/devilutionX/pull/4545 and https://github.com/diasurgical/devilutionX/pull/4544

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/pull/4545 is already in.
https://github.com/diasurgical/devilutionX/pull/4544 depends on other PRs and I would like to not risk introducing audio issues, maybe once things settle down.
