### ISSUE TITLE
Barbarian's rage causes him to lose health twice

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#4654]
**Important information**
1.4.0 / master / https://github.com/diasurgical/devilutionX/commit/0a71f1ffb39d3a3b8ae4e5c21f2fa96076b4daf6

**To Reproduce**
1. Cast rage with barbarian and gain bonus stats
2. Lose health when bonus expires and penalty starts
3. Lose health when stats penalty expires

**Expected behavior**
Barbarian loses health only once - in hellfire it happened when stats penalty ended

**Comment by StephenCWills** [comment]
https://github.com/diasurgical/devilutionX/issues/1111#issuecomment-820908169

**Comment by qndel** [comment]
Guess I just felt it was hitting harder because devx fixed a bug where it wouldn't take any hp if you swapped any item, I consider it a trash skill and pretty much unusable in current state :D but can't see a bug here
