### ISSUE TITLE
Hotkeys reset after closing and re-opening application

### ISSUE THREAD

**Issue by YuviTz1** [diasurgical/devilutionX#4657]
**Important information**
Linux (Pop!_OS 22.04 LTS) / DevilutionX version 1.4.0 / Build from source

**Describe**
All hotkey bindings are removed whenever application is closed

**To Reproduce**
1. Go to Settings.
2. Scroll down to Keymapping.
3. Bind hotkeys.
4. Close and re-open the application.
5. All hotkeys are reset.

**Expected behavior**
Hotkeys should be saved along with other settings like resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/69211421/172018219-3e44511a-5a93-47bc-916d-5d38710b48f3.png)

**Comment by AJenbo** [comment]
Is this actually the 1.4.0, or just the latest commit at the time that you cloned? In case of the later please let us know which commit. If your intention is to build 1.4.0 and play multiplayer with other uses of 1.4.0, then you should check out the 1.4 branch and build that instead.

**Comment by YuviTz1** [comment]
It was commit 1047e408

**Comment by StephenCWills** [comment]
It's already fixed in #4634. The bug modified your INI, so you might want to delete it after updating to a later commit.

**Comment by YuviTz1** [comment]
Yeah just tried out the latest commit and it seems to be fixed.
Thank you.
