### ISSUE TITLE
patch_rt.mpq doesn't work

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#466]
Tried a `patch_rt.mpq` with Spanish dialogs but the dialogs are still in English.

**Comment by AJenbo** [comment]
Does the multiplayer menu correctly change when using the original 1.09 patch_rt.mpq?

Could you provide access to the mentioned MPQ? What exactly does it contain?

**Comment by glebm** [comment]
What's the expected change in the multiplayer menu?

**Comment by AJenbo** [comment]
The leftside box is shorter and has an additional line through it (to seperat the gateway button when present).

**Comment by glebm** [comment]
Closing for now as user error. The `patch_rt` I was looking at doesn't contain Spanish dialogs.
