### ISSUE TITLE
FPS limit skips frames

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#467]
The way FPS limit is implemented currently guarantees we will skip some frames because it waits for exactly the intra-frame time without taking the time it takes to render into account.

One possible mitigation is to remember the last time-to-render (or max of a few) and subtract it from the delay (+ some additional safety margin). This would result in more rendered frames but would hopefully remove most stutter.

**Comment by glebm** [comment]
Actually, why do we even have explicit frame limit?

Isn't the following check sufficient?

https://github.com/diasurgical/devilutionX/blob/aa23194591f46f0f8903ae64a59f7b8f444c6002/SourceX/dx.cpp#L214-L216

**Comment by glebm** [comment]
Also the current code doesn't do any frame limiting for SDL1.

**Comment by AJenbo** [comment]
Is the sleep not inside code that is active for sdl1?

**Comment by glebm** [comment]
@AJenbo That's right. I've attempted to fix both issue in the linked PR
