### ISSUE TITLE
Cabalist cause massive frame drops

### ISSUE THREAD

**Issue by Marcelo20XX** [diasurgical/devilutionX#4690]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Compiled under Windows 10 using VS2019

**Describe**
Whenever Cabalist spawns on level 15 the games drops the frame to almos 5FPS, something about that enemy or its AI is causing the bug...

**To Reproduce**
1. Create a New Game
2. Go or reach to level 15
3. Check if Cabalist is spawned

**Expected behavior**
Cabalist shouldn't cause massive FPS issues

**Comment by AJenbo** [comment]
Make sure it's not a debug build

**Comment by StephenCWills** [comment]
Can you share your audio settings? If `Sample Rate` is not 22050, `Resampler` is Speex, and `Resampling Quality` is higher than 3, this is very likely to happen.

**Comment by Marcelo20XX** [comment]
Will test with those setting and report back...

**Comment by AJenbo** [comment]
>  Sample Rate 48000, Resampler Speex and Resampling Quality 10

This is probably the issue, try quality 3 or sample rate 22050
