### ISSUE TITLE
Everything freeze every 5seconds

### ISSUE THREAD

**Issue by lord-re** [diasurgical/devilutionX#470]
**Describe the bug**
Every 5seconds (approx) the game freeze for half a second.
It does it even during the cinematic intro, the menu, ingame.

**To Reproduce**

1. Launch the game
2. Wait

**Expected behavior**
No freeze.

**Strace dump**
I launched latest DevilutionX with strace and it appears the freeze occur when these lines appear :

```
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
openat(AT_FDCWD, "/dev/input", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 12
fstat(12, {st_mode=S_IFDIR|0755, st_size=540, ...}) = 0
getdents64(12, /* 27 entries */, 32768) = 840
stat("/dev/input/event20", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xd, 0x54), ...}) = 0
openat(AT_FDCWD, "/dev/input/event20", O_RDONLY) = 13
ioctl(13, EVIOCGBIT(0, 8), [EV_SYN, EV_KEY, EV_MSC, EV_LED, ...]) = 8
ioctl(13, EVIOCGBIT(EV_KEY, 96), [KEY_ESC, KEY_1, KEY_2, KEY_3, ...]) = 96
ioctl(13, EVIOCGBIT(EV_ABS, 8), [ 0 ])  = 8
close(13)                               = 0
stat("/dev/input/event19", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xd, 0x53), ...}) = 0
openat(AT_FDCWD, "/dev/input/event19", O_RDONLY) = 13
ioctl(13, EVIOCGBIT(0, 8), [EV_SYN, EV_KEY, EV_REL, EV_ABS, ...]) = 8
ioctl(13, EVIOCGBIT(EV_KEY, 96), [KEY_ESC, KEY_ENTER, KEY_KPMINUS, KEY_KPPLUS, ...]) = 96
ioctl(13, EVIOCGBIT(EV_ABS, 8), [ABS_VOLUME]) = 8
close(13)                               = 0
stat("/dev/input/event18", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xd, 0x52), ...}) = 0
openat(AT_FDCWD, "/dev/input/event18", O_RDONLY) = 13
ioctl(13, EVIOCGBIT(0, 8), [EV_SYN, EV_KEY, EV_ABS, EV_MSC]) = 8
ioctl(13, EVIOCGBIT(EV_KEY, 96), [KEY_UP, KEY_LEFT, KEY_RIGHT, KEY_DOWN, ...]) = 96
ioctl(13, EVIOCGBIT(EV_ABS, 8), [ABS_MISC]) = 8
close(13)                               = 0
stat("/dev/input/event17", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xd, 0x51), ...}) = 0
openat(AT_FDCWD, "/dev/input/event17", O_RDONLY) = 13
ioctl(13, EVIOCGBIT(0, 8), [EV_SYN, EV_KEY, EV_MSC, EV_LED, ...]) = 8
ioctl(13, EVIOCGBIT(EV_KEY, 96), [KEY_ESC, KEY_1, KEY_2, KEY_3, ...]) = 96
ioctl(13, EVIOCGBIT(EV_ABS, 8), [ 0 ])  = 8
close(13)
…
```

It happens regularly and tries every /dev/input/event each time.

**Comment by AJenbo** [comment]
What system are you running it on?

**Comment by glebm** [comment]
Does https://github.com/diasurgical/devilutionX/pull/468 fix the issue?

**Comment by lord-re** [comment]
I'm on a Gentoo amd64.

 I tried #468 but doesn't change it at all.

I don't know if it's relevant or not but the [web version](https://github.com/d07RiV/diabloweb) works well.

**Comment by qndel** [comment]
I'd say forget the web version exists for now :P

**Comment by AJenbo** [comment]
Dos the console produce any messages?

**Comment by lord-re** [comment]
No, nothing appears in the console that's why i launched it with strace to have some clues.

**Comment by AJenbo** [comment]
What devices are connected?

**Comment by lord-re** [comment]
A classic keyboard and mouse. No gamepad or else.

**Comment by AJenbo** [comment]
Hmm this is hard to track down :(

Have you tested on 0.5.0 and 0.4.0?

What's in your diablo.ini?

**Comment by lord-re** [comment]
I always try with latest git commits (tried 9a31b78d8e1666bd40e74399af7f666165df5f75 and it did it).

Here is diablo.ini
```
[devilutionx]
upscale=1
fullscreen=1
grab input=1
scaling quality=2
[Diablo]
Intro=0
Gamma Correction=100
Color Cycling=1
Sound Volume=0
Music Volume=0
```
I tried with grab input=0 and 1 but still the same.

Could it be a SDL thing ?

**Comment by AJenbo** [comment]
> I always try with latest git commits (tried [9a31b78](https://github.com/diasurgical/devilutionX/commit/9a31b78d8e1666bd40e74399af7f666165df5f75) and it did it).
Please try 0.5.0

> Could it be a SDL thing ?
Definatly

**Comment by lord-re** [comment]
I have the same behavior on 0.5.0 :-/

Thanks a lot for your time ;-)

**Comment by AJenbo** [comment]
Ok, at this point don't have any more ideads so you would have to add some info output to the code so that we can see where it stalls please add the following to the start and end of `DrawAndBlit`, `game_loop` and `PeekMessageA`

```
	printf("Start %s\n", __func__);
	int tc = GetTickCount();
```
```
	printf("Ended %s in %dms\n", __func__, GetTickCount() - tc);
```

This should let you see what 3 major parts of the game loop it gets stuck in, most likely it's PeekMessageA, if that is the case then change the code to just crapp `SDL_PollEvent` on line 379-381, if that still slows the stall then we at least know if it's SDL specific.

**Comment by lord-re** [comment]
Ok i solved it.

It was a libsdl2 thing.
I reinstalled it with the "udev" flag.
It may be something interesting to add to the install page for gentoo-specific instructions ?

**Comment by AJenbo** [comment]
Well this should also be affecting other application using SDL2 (at least for the input responsiveness) and it's probably also a very edge case issue considering you have to compile SDL2 with parts left out.
