### ISSUE TITLE
undefined symbol: SDL_CreateRGBSurfaceWithFormat

### ISSUE THREAD

**Issue by snow-frog** [diasurgical/devilutionX#471]
Running the 5.0 linux-x86-64 binary, fails to open and gives error:
./devilutionx: symbol lookup error: ./devilutionx: undefined symbol: SDL_CreateRGBSurfaceWithFormat
libsdl2-2.0-0, libsdl2-mixer-2.0-0 and libsdl2-ttf-2.0-0 are installed

**Comment by AJenbo** [comment]
What version of sdl do you have installed, what distribution are you running?

**Comment by snow-frog** [comment]
2.0-0, as said above, from the repository. I'm running Mint 19.2.

**Comment by glebm** [comment]
Try on master, I believe this may have been fixed by https://github.com/diasurgical/devilutionX/commit/df8d7a1f46b712a679ad1082fe6fb144f4998986

**Comment by AJenbo** [comment]
@snow-frog that isn't the actual version but just the package name, so that is why I aske. Please check the actual version in your package manager.

**Comment by benbotto** [comment]
Looks live version 2.0.4 on Ubuntu 16.04, which has the same problem on the latest release.  I haven't tried master yet.  Ubuntu 18.04 appears to have version 2.0.9, which works.

**Comment by AJenbo** [comment]
0.5.0 require SDL 2.0.9, next release (master) should be ok with 2.0.3
