### ISSUE TITLE
Cannot load level due to lowercase BonechaT.dun

### ISSUE THREAD

**Issue by Chief-Detektor** [diasurgical/devilutionX#4718]
**Important information**
Operating system / DevilutionX version / did you download a release or did you compile yourself?
Arch Linux / self build

**Describe**
When I attempt to enter the bonechamber level I receive an error message stating that the file BonechaT.dun could not be opened.

**To Reproduce**
1. Build on linux
2. Enter Level 6 and attempt to enter the bonechamber.

**Expected behavior**
Loading of the level

**Screenshots**
![Bildschirmfoto vom 2022-06-16 14-14-52](https://user-images.githubusercontent.com/10716635/174068959-e8cb760f-d976-4ce8-9bc3-953cf42d5448.png)

**Additional context**
The problem is that the build on linux saves BonechaT.dun as bonechaT.dun.
Since the filesystem is case sensitve the file cannot be found.
Renaming to BonechaT.dun fixes the problem.

**Comment by AJenbo** [comment]
Thanks this is fixed now. I didn't even notice despite being on Linux since I always build the MPQ. I miss the days when we always checked for files in lowercase :D
