### ISSUE TITLE
Request: Instructions for deploying on MacOS

### ISSUE THREAD

**Issue by prurigro** [diasurgical/devilutionX#473]
It's mentioned in a number of places that the `diabdat.mpq` file should be placed in `~/.local/share/diasurgical/devilution` on Linux, but this doesn't work on MacOS. The following locations also don't work:

* `~/Library/diasurgical/devilution`
* `/Applications/devilutionx.app`
* `/Applications/devilutionx.app/diasurgical/devilution`
* `/Applications/devilutionx.app/Contents`
* `/Applications/devilutionx.app/Contents/diasurgical/devilution`
* `/Applications/devilutionx.app/Contents/MacOS`
* `/Applications/devilutionx.app/Contents/MacOS/diasurgical/devilution`
* `/Applications/devilutionx.app/Contents/Resources`
* `/Applications/devilutionx.app/Contents/Resources/diasurgical/devilution`

I've looked for instructions explaining where to deploy `diabdat.mpq` on MacOS in the wiki, readme and sources but haven't found anything. Something simple explaining how to get things running would be really helpful :)

Thanks!

**Comment by prurigro** [comment]
OK, I don't know why updatedb/locate wasn't including files in `~/Library`, but `find . -iname '*diasurgical*'` found the directory the game created, and placing `diabdat.mpq` in there makes everything run correctly.

I'd like to keep this issue open as a request to add the expected path to either the readme, or better yet, to the error message that appears when starting the game without `diabdat.mpq`.

In the mean time, for anyone else looking for where to place `diabdat.mpq` on MacOS, the correct location is: `~/Library/Application Support/diasurgical/devilution`.

Thank you to everyone making this project happen-- being able to play Diablo natively on Linux and MacOS all these years later is pretty awesome :)

**Comment by AJenbo** [comment]
Place it next to devilutionx.app

**Comment by de4me** [comment]
macOS version search for:
```
DevilutionX.app/Contents/Resources/
/Users/{ME}/Library/Application Support/diasurgical/devilution/
```
and if sandbox enabled:
```
DevilutionX.app/Contents/Resources/
/Users/{ME}/Library/Containers/com.diasurgical.devilutionx/Data/Library/Application Support/diasurgical/devilution/
```
