### ISSUE TITLE
Yellow strip in the end sequence

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#476]
Yellow strip in the end sequence happens only in case of the sorcerer between 1.20 min and 1.30 min.
[1.mkv.zip](https://github.com/diasurgical/devilutionX/files/3854241/1.mkv.zip)

**Comment by Chance4us** [comment]
![1](https://user-images.githubusercontent.com/45902449/68994317-eee4d900-0881-11ea-8a2d-34db96da4b41.jpg)

**Comment by AJenbo** [comment]
This is in the original video file, nothing can really be done about it

**Comment by Chance4us** [comment]
In this case it seems to be a well documented vanilla attribute.

**Comment by AJenbo** [comment]
Actually it looks like this is probably a bug in libsmacker, might want to repport it upstream. Also VLC does a horrible job of playing the video but they look correct in mpv.

![image](https://user-images.githubusercontent.com/204594/68995291-50aa4080-088c-11ea-8bd8-bbe72acc7f23.png)

**Comment by AJenbo** [comment]
The fix might be here https://github.com/JonnyH/libsmacker/commit/21332e23e4937cd13b2faf39678ff473866b327b

**Comment by AJenbo** [comment]
This is now fixed.

**Comment by Chance4us** [comment]
Thank you ;-)

**Comment by AJenbo** [comment]
Thank you :)
