### ISSUE TITLE
The number of gold coins does not reach 5000

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#478]
Description:
Before the number of gold coins reaches 5000 in the first slot, a new slot is occupied with new coins.

Expected behaviour:
The number of gold coins reaches 5000 in the first slot.
Only then will a new slot be occupied with coins.

I can not remember that it was a vanilla bug.
But maybe I'm wrong.

![amount](https://user-images.githubusercontent.com/45902449/68999311-435a7980-08bf-11ea-8810-8b654c57a9b6.png)

**Comment by AJenbo** [comment]
This is the same as vanilla, only shelling in shops gets you to exactly 5000.
