### ISSUE TITLE
Suggestion to add an option to keep game zoomed in by default

### ISSUE THREAD

**Issue by AlphaNERD-** [diasurgical/devilutionX#4797]
Hello developers,

as the title says i wish to suggest a setting to keep the game zoomed in by default. Being zoomed out has the advantage of seeing the whole map which is okay for the city but in my opinion not very useful within the cathedral since the game doesn't show enemies and stuff when it's not nearby and sometimes within line of sight anyway. I could keep the game at 640x480 or 800x600 but then i'd have black bars which don't look too good either.

Thank you for your attention and have a nice day

**Comment by AJenbo** [comment]
640x480 and 800x600 shoudn't have black bars if you enable fit to screen.

**Comment by AJenbo** [comment]
Also it's already been implemented and being evaluated for 1.5.0: https://github.com/diasurgical/devilutionX/pull/4432
