### ISSUE TITLE
SP loadgame bar

### ISSUE THREAD

**Issue by k-bar** [diasurgical/devilutionX#4821]
**Important information**
win7/ master (ddafe87ed3e11e6b91d8bf2454a9b675af6dc80b) / myself

**Describe**
bar appear when loading SP not from main menu, but from within a game already.

**To Reproduce**
1. Load SP game from ingame-menu

**Expected behavior**
suppose this bar as on gif is unintended

**Screenshots**
![spload](https://user-images.githubusercontent.com/92504151/176514037-e33b9d18-7e38-40e5-b695-fa52d259be04.gif)

**Comment by qndel** [comment]
Broken by https://github.com/diasurgical/devilutionX/commit/9d2948c78257d1a89efe5e1ed49dcbda32370e4b
