### ISSUE TITLE
Monster disappearing when crossing door

### ISSUE THREAD

**Issue by k-bar** [diasurgical/devilutionX#4822]
**Important information**
win7/ (ddafe87ed3e11e6b91d8bf2454a9b675af6dc80b) / myself

**Describe**
goat disappear for a while, when crossing door.

**To Reproduce**
1. open room full of goats
2. observe how they walk through door

**Expected behavior**
goat shall not disappear

**Screenshots**
![goatsdoor](https://user-images.githubusercontent.com/92504151/176514861-1a5010df-2496-4152-a40a-24a06b6af018.gif)

**Comment by AJenbo** [comment]
Do you happen to have a save for this? Would be useful for finding out if it's a regression, as well as trying to fix it.

**Comment by qndel** [comment]
Broke between 1.2.0 and 1.3.0, will try to bisect
