### ISSUE TITLE
Cannot target berserked monster when using gamepad 

### ISSUE THREAD

**Issue by beelzebielsk** [diasurgical/devilutionX#4848]
**Important information**
Operating system: PSVita
DevilutionX version: 1.4.0, downloaded release

**Describe**
If I cast berserk on a monster, I can't target it anymore with the gamepad. 

**To Reproduce**
1. Cast berserk on a monster, preferably when they're the only monster around 
2. See that they have no highlight and trying to attack them using the gamepad doesn't work.

**Expected behavior**
I can still target them and attack them, at least if they're attacking me. Or if they are the only monster(s) around, in which case they're *definitely* attacking me.

**Additional Context**
It's an issue because they can still attack you and hit harder than normal when they do. This makes it hard to defend yourself from them. Also, they can be targeted fine with a kb+m, or moving the cursor with a gamepad.

**Comment by AJenbo** [comment]
Good point
