### ISSUE TITLE
Problem building Devilutionx on Launchpad

### ISSUE THREAD

**Issue by muzena** [diasurgical/devilutionX#4926]
When I install DevilutionX from [Launchpad PPA](https://code.launchpad.net/~devilutionx/+recipe/devilutionx-test) builds DevilutionX won't start.
<details>
<summary>I get this error in terminal</summary>

```
    goran@goran-X470-AORUS-ULTRA-GAMING:~$ devilutionx --verbose
VERBOSE: Paths:
    base: /usr/bin/
    pref: /home/goran/.local/share/diasurgical/devilution/
  config: /home/goran/.local/share/diasurgical/devilution/
  assets: /usr/bin/assets/
VERBOSE: MPQ search paths:
     1. '/usr/bin/'
     2. '/home/goran/.local/share/diasurgical/devilution/'
     3. '/usr/share/diasurgical/devilutionx/'
     4. '/usr/local/share/diasurgical/devilutionx/'
     5. ''
VERBOSE:   Found: devilutionx.mpq in /usr/share/diasurgical/devilutionx/
VERBOSE: Missing: fonts.mpq
VERBOSE: Paths:
    base: /usr/bin/
    pref: /home/goran/.local/share/diasurgical/devilution/
  config: /home/goran/.local/share/diasurgical/devilution/
  assets: /usr/bin/assets/
VERBOSE: MPQ search paths:
     1. '/usr/bin/'
     2. '/home/goran/.local/share/diasurgical/devilution/'
     3. '/usr/share/diasurgical/devilutionx/'
     4. '/usr/local/share/diasurgical/devilutionx/'
     5. ''
VERBOSE: Missing: hr.mpq
VERBOSE: Paths:
    base: /usr/bin/
    pref: /home/goran/.local/share/diasurgical/devilution/
  config: /home/goran/.local/share/diasurgical/devilution/
  assets: /usr/bin/assets/
VERBOSE: MPQ search paths:
     1. '/usr/bin/'
     2. '/home/goran/.local/share/diasurgical/devilution/'
     3. '/usr/share/diasurgical/devilutionx/'
     4. '/usr/local/share/diasurgical/devilutionx/'
     5. ''
VERBOSE: Missing: DIABDAT.MPQ
VERBOSE:   Found: diabdat.mpq in /home/goran/.local/share/diasurgical/devilution/
VERBOSE:   Found: hellfire.mpq in /home/goran/.local/share/diasurgical/devilution/
VERBOSE:   Found: hfmonk.mpq in /home/goran/.local/share/diasurgical/devilution/
VERBOSE: Missing: hfbard.mpq
VERBOSE: Missing: hfbarb.mpq
VERBOSE:   Found: hfmusic.mpq in /home/goran/.local/share/diasurgical/devilution/
VERBOSE:   Found: hfvoice.mpq in /home/goran/.local/share/diasurgical/devilution/
DEBUG: No available video device
ERROR: SDL Error
No available video device

The error occurred at: Source/utils/display.cpp line 259
DEBUG: That operation is not supported
DEBUG: No message system available
ERROR: No message system available

```

</details>

Launchpad PPA build system use DevilutionX source with "fully_vendored" build dependencies to generate deb's.
But when I build and install deb's localy on PC, DevilutionX work without error.
Is this some problem with build dependencies?

**Comment by AJenbo** [comment]
It says you do not have a graphics card, how and where are you launching it?

**Comment by muzena** [comment]
On PC 

> Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series]

**Comment by AJenbo** [comment]
Does it work if you use one if the Linux builds attached to the release on Github, or is it only an issue with the one build on launchpad?

**Comment by muzena** [comment]
Latest release 1.4.0 from github work.

>  But when I build and install deb's localy on PC, DevilutionX work without error.

This problem is only in launchpad builds deb's.

**Comment by AJenbo** [comment]
I guess this is some sort of dependency issue. @glebm do you have any input?

**Comment by glebm** [comment]
@muzena Where can I find the build commands used to compile that build?

**Comment by glebm** [comment]
> Launchpad PPA build system use DevilutionX source with "fully_vendored" build dependencies to generate deb's.

You shouldn't use `fully_vendored` for this. All of the necessary packages exist in Ubuntu for a non "fully_vendored" build.
If you use fully_vendored, that compiles everything, including SDL2, from scratch, and I guess it doesn't include the necessary render backends for your system.

**Comment by AJenbo** [comment]
That makes sens, since it was build on a build servere probably no render system was detected and so the whole video part was left out.

**Comment by glebm** [comment]
If you do need the "fully_vendored" package for some other reason, pass it `-DDEVILUTIONX_SYSTEM_SDL2=ON`  explicitly.

**Comment by AJenbo** [comment]
Regarding build command I can't finding anything meningsfuld in Launchpad either, this is the closest i get:
```
# git-build-recipe format 0.4 deb-version {latest-tag}+git{revno}-{git-commit}-{time}
lp:~devilutionx/+git/devilutionX master
nest-part packaging lp:~devilutionx/+git/devilutionX Packaging/debian debian master

# git-build-recipe format 0.4 deb-version {latest-tag}+git{revno}-{git-commit}-{time}
lp:~devilutionx/+git/devilutionX master
nest-part packaging lp:~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging Packaging/debian debian fix-debian_versioning
```

But I can't see how that is suposed to work

**Comment by AJenbo** [comment]
@muzena can you give a crash course in LP? I have given up helping with it several times as I can't find anything that remotely resembles code or build commands :/

**Comment by muzena** [comment]
Problem with Launchapd is to not allowing to 'download' 'or 'git cloning' files outside Launchpad
so to this above recipe you need to add/nest build dependencies, so i upload "fully_vendored" dependencies
[So build recipe must contain added/nested build dependencies and debian packaging](https://code.launchpad.net/~devilutionx/+recipe/devilutionx-test).


`#` git-build-recipe format 0.4 deb-version {latest-tag}+git{revno}-{git-commit}-{time}
lp:~devilutionx/+git/devilutionX master
nest-part dependencies lp:~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging dist dist debian_build
nest-part packaging lp:~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging Packaging/debian debian debian_build

**Comment by muzena** [comment]
@glebm 

> If you do need "fully_vendored" for some other reason, pass it -DDEVILUTIONX_SYSTEM_SDL2=ON explicitly.

I add this [flag to cmake](https://github.com/muzena/devilutionX/blob/debian_build/Packaging/debian/rules)
but  this gave [another error](https://launchpadlibrarian.net/612454623/buildlog_ubuntu-jammy-amd64.devilutionx_1.4.0+git5707-6181e53c1-202207111825~ubuntu22.04.1_BUILDING.txt.gz)

<details>
<summary>sdl2 error</summary>

```
    -- 📚 SDL2: dynamic system library
CMake Error at CMake/Dependencies.cmake:32 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:268 (include)


-- Configuring incomplete, errors occurred!
See also "/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
See also "/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/CMakeFiles/CMakeError.log".
	cd obj-x86_64-linux-gnu && tail -v -n \+0 CMakeCache.txt
==> CMakeCache.txt <==
```

</details>

**Comment by glebm** [comment]
@muzena Well that just looks like your package doesn't depend on SDL2. It should.

**Comment by muzena** [comment]
I forget to enable [libsdl2-dev  in debian packaging ](https://git.launchpad.net/~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging/commit/?id=97b8c7e92627b7971330645d05fffd738269514d)

So building was successfully for amd64 and armhf arc.
I will check for 20 min when deb's be published if now works.

**Comment by AJenbo** [comment]
Ok, I guess the bulid commands are managed by a file in this repo?
https://git.launchpad.net/~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging/tree/Packaging/debian/control?id=97b8c7e92627b7971330645d05fffd738269514d&h=master


Idealy you should change the Build-Depends section to this:
```
	debhelper,
	pkg-config,
	cmake,
	g++,
	gettext,
	libsdl2-dev,
	libsdl2-image-dev,
	libsodium-dev,
	libpng-dev,
	smpq,
	libbz2-dev
	zlib-dev
```

And then you probably also want the following:
-DDEVILUTIONX_SYSTEM_SDL2=ON
-DDEVILUTIONX_SYSTEM_ZLIB=ON
-DEVILUTIONX_SYSTEM_BZIP2=ON
-DEVILUTIONX_SYSTEM_SDL_IMAGE=ON
-DEVILUTIONX_SYSTEM_LIBSODIUM=ON

For Ubuntu 22.04 you can also have `-DEVILUTIONX_SYSTEM_LIBFMT=ON` and add `libfmt-dev`, and for the upcomming releases `-DDEVILUTIONX_SYSTEM_SIMPLEINI=ON` and add `libsimpleini-dev`

**Comment by AJenbo** [comment]
Also it looks like you are checking out the maintenance branch and not the actual release tag:
https://git.launchpad.net/~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging/tree/Packaging/debian/devilutionx-stable-upload?h=debian-manually&id=0f71c95cd501296b27c96dec74ee969993813d89#n67

It should be `1.3.0`, not `1.3` as that is a moving target.

**Comment by muzena** [comment]
@AJenbo 

> It should be 1.3.0, not 1.3 as that is a moving target.

I will check this.

I fixed compilation for all releases from Ubuntu Bionic to Ubuntu Kinetic.
Except for **arm64** and **ppc64el** architecture, I don't understand why is failing, I think some dependencies issue, ZeroTier.
I made debian packaging for [ZeroTier](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/devilutionx-test/+sourcepub/13808306/+listing-archive-extra) on **arm64** build failed on **ppc64el** build is successful.

This **arm64** and **ppc64el** build failure is reason why I didn't update stable PPA to 1.4.0 version.

**Comment by AJenbo** [comment]
nice :)

1.4.1 should be out this weekend :sweat_smile:

**Comment by muzena** [comment]
[**ppc64el**](https://code.launchpad.net/~trebelnik-stefina/+archive/ubuntu/devilutionx-git-focal-test/+build/24176204) is being built successfully now when I disabled devilutionx.mpq build.
Problem is in [**smpq package or stormlib**](https://launchpadlibrarian.net/613271532/buildlog_ubuntu-jammy-ppc64el.devilutionx_1.4.0+git5767-dd2644373-202207161632~ubuntu22.04.1_BUILDING.txt.gz)

> smpq: /build/stormlib-anY3Dj/stormlib-9.22/src/SFileAddFile.cpp:103: int FillWritableHandle(TMPQArchive*, TMPQFile*, ULONGLONG, DWORD, DWORD): Assertion `sizeof(hf->hctx) >= sizeof(hash_state)' failed.
Aborted (core dumped)
make[3]: *** [CMakeFiles/devilutionx_mpq.dir/build.make:226: devilutionx.mpq] Error 134
make[3]: *** Deleting file 'devilutionx.mpq'
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-aarch64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:934: CMakeFiles/devilutionx_mpq.dir/all] Error 2

[**arm64**](https://launchpadlibrarian.net/613271854/buildlog_ubuntu-jammy-arm64.devilutionx_1.4.0+git5767-dd2644373-202207161632~ubuntu22.04.1_BUILDING.txt.gz)
I think this problem is in detecting architecture in libzt and zerotire
I tried this two patches [**patch1**](https://github.com/zerotier/ZeroTierOne/pull/1605/files) [**patch2**](https://github.com/zerotier/libzt/pull/179/files)

> /usr/lib/gcc/aarch64-linux-gnu/11/include/arm_neon.h:10913:1: error:

Above quoted errors are gone, but something is wrong with patch2 i get error:

> FATAL: architecture could not be determined by CMake: arm64

**Comment by StephenCWills** [comment]
> [**arm64**](https://launchpadlibrarian.net/613271854/buildlog_ubuntu-jammy-arm64.devilutionx_1.4.0+git5767-dd2644373-202207161632~ubuntu22.04.1_BUILDING.txt.gz) I think this problem is in detecting architecture in libzt and zerotire I tried this two patches [**patch1**](https://github.com/zerotier/ZeroTierOne/pull/1605/files) [**patch2**](https://github.com/zerotier/libzt/pull/179/files)
> 
> > /usr/lib/gcc/aarch64-linux-gnu/11/include/arm_neon.h:10913:1: error:
> 
> Above quoted errors are gone, but something is wrong with patch2 i get error:
> 
> > FATAL: architecture could not be determined by CMake: arm64

I've already addressed the errors in your log through my responses to #3930. You need to add the `-march=armv8-a+crypto` compiler option to the `zto_pic` target. Since you still seem to be struggling with this, I assume your attempt to update the Debian rules file must not have worked. In that case, I suggest simply adding something like the following toward [the bottom of .../3rdParty/libzt/CMakeLists.txt](https://github.com/diasurgical/devilutionX/blob/78f2fa6221d679e70eb10323292a1c46de332a53/3rdParty/libzt/CMakeLists.txt#L56).

```cmake
if(#[[my architecture supports ARMv8 crypto extensions]])
    target_compile_options(zto_pic PRIVATE -march=armv8-a+crypto)
endif()
```

Note, I've placed a comment in the if statement because I don't know how to reliably detect the architecture for your system. See below.

---

The patch you've referenced attempts to add `-march=armv8-a+crypto` to the global set of compiler flags when it detects either the `arm64` or the `aarch64` system processor. I suspect this should indeed fix the problem (albeit overkill), except that your fatal error message suggests either this is not a valid way to detect the architecture or else you might have applied the patch incorrectly.

```cmake
SET(ZT_ARCHITECTURE 999)
...
ELSEIF (${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm64" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "aarch64")
    SET(ZT_ARCHITECTURE 4)
...
IF (${ZT_ARCHITECTURE} EQUAL 999)
    message(FATAL_ERROR "FATAL: architecture could not be determined by CMake: ${CMAKE_SYSTEM_PROCESSOR}")
else()
    message(STATUS "Detected architecture: ${CMAKE_SYSTEM_PROCESSOR}")
ENDIF()
```

**Comment by muzena** [comment]
@StephenCWills 

> if(#[[my architecture supports ARMv8 crypto extensions]])
    target_compile_options(zto_pic PRIVATE -march=armv8-a+crypto)
endif()

This dosen't work.

But I add '-march=armv8-a+crypto' to [C_FLAGS and CXX_FLAGS](https://github.com/muzena/devilutionX/blob/4505059e7a1319d860d9efc686d1998c6ee56243/dist/libzt-src/CMakeLists.txt#L61) and now building works.

Now building finally works on all architectures.

**Comment by AJenbo** [comment]
@muzena Please disable platforms that don't build so we don't get bombed with emails of failed builds.

**Comment by muzena** [comment]
@AJenbo 
All builds now works, [for all architectures](https://code.launchpad.net/~devilutionx/+recipe/devilutionx-git-arm64-aarch64-test).

**Comment by AJenbo** [comment]
Will you be able to build 1.4.0 for stable now?

**Comment by muzena** [comment]
@AJenbo 

> Will you be able to build 1.4.0 for stable now?

[Stable build fixed](https://code.launchpad.net/~trebelnik-stefina/+recipe/devilutionx-stable-test-gogo)
