### ISSUE TITLE
DevilutionX 1.4.0 does not start on OD Beta (RG280V)

### ISSUE THREAD

**Issue by Creamynips** [diasurgical/devilutionX#4953]
**Important information**
OpenDingux Beta (RG280V) / DevilutionX 1.4.0 / Downloaded release

Newest release of DevilutionX doesn't start. 

**To Reproduce**
1. Set up device & .mpq files as per install guide
2. Start OPK

**Expected behavior**
Game starts to splash screen or title screen, but screen goes black and returns to OD browser

**Additional context**
Version 1.3.0 starts fine on same device & OS.

**Comment by glebm** [comment]
Anything in the log?

**Comment by Creamynips** [comment]
The log appears completely blank. I've deleted the log and tried opening the Log Viewer a few times and it always appears empty for DevilutionX 1.4.0. The log for 1.3.0 shows up fine, indicating several "INFO" lines, mainly about video mode settings.

**Comment by glebm** [comment]
I don't have a device to debug with at the moment.

Does the build from here work for you?

https://github.com/diasurgical/devilutionX/actions/runs/2646338005

**Comment by Creamynips** [comment]
No, this build doesn't work either - same result. Blank log file as well.

**Comment by glebm** [comment]
What version of OD beta are you using?

**Comment by Creamynips** [comment]
2022-04-03 (version 5.17) that is packaged with the Adam Image 2.0 update.

**Comment by glebm** [comment]
I'm not sure about the Adam Image. I've asked on the OpenDingux Discord if somebody can test with the actual OD firmware on RG280v.

In the meantime, can you try this build https://github.com/glebm/devilutionX/actions/runs/2651114384

Also, can you try launching directly from the terminal instead of the UI (e.g. using `opkrun`)? Sometimes you get much better error messages this way.

**Comment by Creamynips** [comment]
![20220711_115653](https://user-images.githubusercontent.com/103981290/178327940-31e76aa8-36ee-4ef8-b008-47769076f8db.jpg)
Attempting to run the OPK you linked shows basically nothing happening in the terminal.
![20220711_115706](https://user-images.githubusercontent.com/103981290/178328064-7952310d-a21b-43db-8e34-79c302b745e9.jpg)
For reference, running the OPK for 1.3.0 (I renamed the file to differentiate) via the terminal works fine.

**Comment by AJenbo** [comment]
Looks like it tries to render the log and intro video and then the menu at which point it exits.

**Comment by glebm** [comment]
OpenDingux folks confirmed that it segfaults on startup with vanilla OD Beta firmware.
We're using a March 2021 toolchain to build DevilutionX, let me see if updating to the latest toolchain helps.

**Comment by glebm** [comment]
@Creamynips Thanks for testing. Can you please try https://github.com/glebm/devilutionX/suites/7309298017/artifacts/295315822? It's built with the November 2021 OD toolchain instead of the March 2021 one.

**Comment by Creamynips** [comment]
Nothing, unfortunately. Same results with opkrun from before.

**Comment by narical** [comment]
Can confirm, nothing except 1.3.0 works, I've got the very same results as @Creamynips

**Comment by glebm** [comment]
I've no idea what the cause is and don't have a device to test with, hopefully someone else can debug this at some point.

I think @citral23 looked at it but not sure whether he's discovered something.

**Comment by narical** [comment]
> I've no idea what the cause is and don't have a device to test with, hopefully someone else can debug this at some point.
> 
> I think @citral23 looked at it but not sure whether he's discovered something.

Isn't there some way to get direct console output? Like, not the (empty) result of opkrun but some segfault messages? I'd like to help with it

**Comment by AJenbo** [comment]
I would suggest doing a debug build. Maybe look in to attatching a debug console

**Comment by glebm** [comment]
You could recompile OpenDingux with `BR2_ENABLE_DEBUG` and use a remote debugger.

On the device, unpack the OPK and run:

```
gdbserver 10.1.1.1:8001 devilutionx
```

IN VS Code, add a launch configuration for remote debugging.
This is what I use for rg99, a similar device:

```json
    {
      "name": "rg99 remote debug",
      "type": "cppdbg",
      "request": "launch",
      "program": "build-rg99/devilutionx",
      "stopAtEntry": true,
      "miDebuggerPath": "/home/gleb/repos/glebm/od_buildroot/output/rs90/host/bin/mipsel-linux-gdb",
      "miDebuggerArgs": "-ix /home/gleb/repos/glebm/od_buildroot/output/rs90/staging/usr/share/buildroot/gdbinit",
      "MIMode": "gdb",
      "miDebuggerServerAddress": "10.1.1.3:8001",
      "targetArchitecture": "mips",
      "additionalSOLibSearchPath": "/home/gleb/repos/glebm/od_buildroot/output/rs90/host/mipsel-rs90-linux-musl/sysroot",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "externalConsole": false,
      "cwd": "${workspaceFolder}"
    },
    {
```

**Comment by glebm** [comment]
Thanks to the amazing @pcercuei we've discovered that disabling LTO makes it work! :tada:

**Comment by AJenbo** [comment]
Glad you guys figured it out :)

**Comment by glebm** [comment]
In the meantime, feel free to try out this build from the latest master https://github.com/diasurgical/devilutionX/suites/7485166754/artifacts/307094526

**Comment by a-dekker** [comment]
Just tried the latest devilutionx-rg350.opk (1.4.1) on my RG350M with OD-beta, but it won't start (Segmentation fault).

So I compiled it myself (following the github actions steps as close as possible), and that version did work. I did use an slightly older toolchain (Oct. 2020) with compiler version 10.2 instead of 11.1 as used in github actions. But I doubt this has any impact.

There are also some differences in the resulting shared object dependencies (just for the record):

ldd on my compiled version:
```
libz.so.1 => /lib//libz.so.1 (0x77e3f000)
libSDL-1.2.so.0 => /lib//libSDL-1.2.so.0 (0x77dea000)
libc.so.0 => /lib//libc.so.0 (0x77d37000)
ld-uClibc.so.1 => /lib/ld-uClibc.so.0 (0x77e65000)
libiconv.so.2 => /lib//libiconv.so.2 (0x77c45000)
libdrm.so.2 => /lib//libdrm.so.2 (0x77c24000)
libudev.so.1 => /lib//libudev.so.1 (0x77bef000)
libts.so.0 => /lib//libts.so.0 (0x77bdb000)

```
ldd on github version:
```
libSDL_image-1.2.so.0 => /lib//libSDL_image-1.2.so.0 (0x77eb1000)
libz.so.1 => /lib//libz.so.1 (0x77e8b000)
libSDL-1.2.so.0 => /lib//libSDL-1.2.so.0 (0x77e36000)
libc.so.0 => /lib//libc.so.0 (0x77d83000)
ld-uClibc.so.1 => /lib/ld-uClibc.so.0 (0x77ecb000)
libpng16.so.16 => /lib//libpng16.so.16 (0x77d42000)
libjpeg.so.9 => /lib//libjpeg.so.9 (0x77cfd000)
libiconv.so.2 => /lib//libiconv.so.2 (0x77c0b000)
libdrm.so.2 => /lib//libdrm.so.2 (0x77bea000)
libudev.so.1 => /lib//libudev.so.1 (0x77bb5000)
libts.so.0 => /lib//libts.so.0 (0x77ba1000)
```
Maybe it is just me, as I do not see any other new error reports here.

**Comment by Creamynips** [comment]
I also didn't have any luck with the new version, but I thought it was just me as others sounded pretty confident the issue was fixed.

**Comment by a-dekker** [comment]
@Creamynips meanwhile you could try my build from a few days ago and see it if works for you https://github.com/a-dekker/repackaged-opks/raw/main/devilutionx-rg350.opk

**Comment by Creamynips** [comment]
That build works! Thanks a-dekker.

**Comment by a-dekker** [comment]
Just tested, https://github.com/diasurgical/devilutionX/pull/5116/commits/4bff36cae760d7793f0aa3ad56850f87c1804b1f is indeed needed to prevent a segmentation fault. So the issue seems to be in the build process itself over here.

**Comment by glebm** [comment]
Looks like perhaps we didn't reupload the correct release after pushing through the fix.
Does the build from here work for you? https://github.com/diasurgical/devilutionX/actions/runs/2915256726

**Comment by a-dekker** [comment]
No, this build also does not work unfortunately.

**Comment by glebm** [comment]
Odd, is the CI perhaps using a different version of the toolchain? https://github.com/diasurgical/devilutionX/actions/runs/2915256726/workflow#L21

**Comment by a-dekker** [comment]
It is, that is what I already mentioned in my first comment here.

**Comment by a-dekker** [comment]
And did a build with gcw0-toolchain.2021-03-10 now (which is also c compiler 10.2, I thought is was 11.1 at first) and this one also works for me.

**Comment by glebm** [comment]
> I did use an slightly older toolchain (Oct. 2020) with compiler version 10.2 instead of 11.1 as used in github actions. But I doubt this has any impact.

I'd guess this to be the root cause. A new buildroot is being released soon (2022.08) with GCC 12. Let's wait and see whether we can simply re-enable LTO at that point.

**Comment by citral23** [comment]
Nothing of great value I'm afraid :

Starting program: /media/RG280M/apps/squashfs-root/devilutionx
Program received signal SIGSEGV, Segmentation fault.
0x77ac87e8 in __uClibc_main () from /lib//libc.so.0

That's on 1.4.0 built with debug on

1.3.0 still works fine, just verified

**Comment by glebm** [comment]
Latest build from master: https://github.com/diasurgical/devilutionX/actions/runs/3399976392

**Comment by a-dekker** [comment]
This build indeed is working again on OD-beta.
