### ISSUE TITLE
macOS: DevilutionX.app run from virtual volume and can't find diabdat.mpq

### ISSUE THREAD

**Issue by de4me** [diasurgical/devilutionX#501]
Before opening downloaded software for the first time, macOS requests your approval.
After approve it run DevilutionX.app from virtual volume:

![Снимок экрана 2019-12-01 в 23 03 07](https://user-images.githubusercontent.com/13272997/69974494-6a0ee600-1536-11ea-8bd6-e0d2b05be6ec.png)

I found two solutions:

1. After download run in the Terminal command: xattr -r -d com.apple.quarantine DevilutionX.app
2. Use macOS private API SecTranslocateIsTranslocatedURL() and SecTranslocateCreateOriginalPathForURL() from [<Security/SecTranslocate.h>](https://opensource.apple.com/source/Security/Security-57740.51.3/OSX/libsecurity_translocate/lib/SecTranslocate.h.auto.html)

**Comment by AJenbo** [comment]
What version of macOS are you running?
Did you unpack the app from the dmg first?

How is your workaround to be applied (by who)?

**Comment by de4me** [comment]
> What version of macOS are you running?

macOS 10.15.1 Catalina

> Did you unpack the app from the dmg first?

Yes, this happens for all unsigned applications.

> How is your workaround to be applied (by who)?

Write about workaround in readme and users can disable quarantine using the Terminal.
Or you can add platform specific code to application and know original directory url for searching diabdat.mpq.

**Comment by AJenbo** [comment]
Do we have to pay a fee to Apple in order to sign it and can it be done with out direct access to a Mac?

**Comment by de4me** [comment]
Sorry, I checked it and must correct: **every** application **downloaded** from internet run from virtual volume. I try signed, signed+notarized and sandboxed+signed+notarized application. All run from virtual volume:

![Снимок экрана 2019-12-03 в 10 35 22](https://user-images.githubusercontent.com/13272997/70029996-4d67c200-15b9-11ea-9e5b-f5e6604c6c79.png)
(sandboxed+signed+notarized application downloaded from internet)

> Do we have to pay a fee to Apple in order to sign it and can it be done with out direct access to a Mac?

Yes, If you need signed and notarized application you must join Apple Developer program.
Sorry, I don't know nothing about developing for macOS without macOS. But I think there will be problems. Are there any solutions to these problems, I do not know.

**Comment by AJenbo** [comment]
The walls around Apples garden just grew taller :(

I only have spotty access to macOS 10.13 available to me. Since I can't test or replicate this I'm going to have to defer to community developers for this one.

**Comment by AJenbo** [comment]
The Readme now hints at putting it in the data folder, which I see in your first image is in the normal location, so I consider this issue solved.
