### ISSUE TITLE
[UI/Enhancement] Display difficulty clear status for each character

### ISSUE THREAD

**Issue by adpa** [diasurgical/devilutionX#5031]
I recall the Battle.net lobby UI for Diablo displaying icons with dots for every difficulty that character has killed Diablo on.

To my knowledge, this was the only indication of a given character's difficulty clear status in game.

I think it would be rather nice if the same (or similar) icons could be added to the character select menu and/or the character status pane in game in order to be able to see difficulty clear status for single player and offline play.

**Comment by AJenbo** [comment]
Single player does not automatically save so this information is only available for multiplayer heros

**Comment by adpa** [comment]
Fair point on the single player limitation, but I still think the idea has merit for multiplayer characters. Given that DX doesn't support Battle.net (are the servers even up for the vanilla client at this point?), the difficulty clear status is kind of lost as it stands today.

I recall getting your dots as being sort of an aspirational thing for B.net players back in the day. It would be nice to recreate that feeling for DX.

**Comment by AJenbo** [comment]
You mentioned specifically wanting this for offline play so didn't think you wanted it for multiplayer?

**Comment by adpa** [comment]
Ah, sorry, I guess that's poor wording on my part. I intended for "offline" to refer to non-B.net multiplayer play. I mostly play my multiplayer characters solo via the direct connect mode, which doesn't require connecting to any external servers. Sorry for the confusion.

**Comment by AJenbo** [comment]
Ok, In DevilutionX you have loopback for that, it doesn't even listen to a network interface. So yeah that is offline, but would exclude ZeroTier and possibly TCP depending on your definition.

**Comment by adpa** [comment]
Fair point. It was not my intent to exclude the ZeroTier or TCP use cases from consideration.
