### ISSUE TITLE
Tiles are mixed up when using bomb to entry Hellfire levels

### ISSUE THREAD

**Issue by UmmonPwr** [diasurgical/devilutionX#5032]
### Operating System

Windows x86

### DevilutionX version

1.4.0 (latest release)

### Describe

When you use the bomb to open the entry to Hellfire nest levels the tiles are mixed up and you cannot go down to the nest.
![Screenshot from 2022-07-17 21-18-29](https://user-images.githubusercontent.com/16181245/179422167-8a8d0e1c-c388-4030-aedf-7cfffa171368.jpg)

Savegame to reproduce:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/9128421/single_0.zip)

Checked the latest Win x86 and x64 builds from Github and both have the bug.

Probably this is not the only place where this bug happens. If I remember correctly I saw this tile mixing also in Diablo cathedral levels when I went back one level and found a place where tiles were mixed up and prevented me to get back to Town. This place was OK when I first went through it. Unfortunately I don't have evidence for this occasion.

### To Reproduce

1. Go to the cow guy in the town, get the bomb and use it to open the entry to Hellfire Nest levels.

### Expected Behavior

Tiles are in correct order.

**Comment by AJenbo** [comment]
You mention both latest release and latest build, are you actually using the release, or is this a beta build taken from the CI?

**Comment by UmmonPwr** [comment]
It is the beta build taken from CI.

**Comment by AJenbo** [comment]
... is it actually on Windows x86?
