### ISSUE TITLE
[Improvement] Add the ability to pull up onscreen keyboard for text fields

### ISSUE THREAD

**Issue by minusfourty** [diasurgical/devilutionX#506]
Certain menus such as names require (or at least would be improved with) some form of proper keyboard input. In the OpenMW port it was possible to pull up the onscreen keyboard by pressing the minus button while in a text input field, would it be possible to implement something like this? At the very least it'd be nice to be able to change the default name in an INI or something if that's not already implemented. USB keyboard and mouse support would also be ideal although I understand full keyboard and mouse support would be a pain to implement.

**Comment by AJenbo** [comment]
I'm not sure what platform you are referring to. On pc and raspberry pi mouse and keyboard is the default and on Nintendo Switch it should also be supported, in addition to the onscreen keyboard.

**Comment by AJenbo** [comment]
Since you mention "minus button" i'm going to guess you are refering to Nintendo Switch. Please see the readme about how to properly start the game so that the onscreen keyboard works correctly:
https://github.com/diasurgical/devilutionX/blob/master/Packaging/switch/readme-switch.md
