### ISSUE TITLE
Shift+Left Click Fail To Equip Two Handed Weapons If The Main Hand Is Empty

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#5076]
### Operating System

Windows x64

### DevilutionX version

1.4.0 (latest release)

### Describe

If you have a shield equipped in the hand slot on the right side of the screen and Shift + Left Click a bow, it will say you have no room and not swap the shield for the bow.

Shift + Left Click will work if you have a weapon and shield equipped, with a shield in the left hand on the screen, but fails in the right.

### To Reproduce

1. Find a bow and a shield.
2. Equip shield into the hand visually on the right side of inventory.
3. Shift + Left Click bow in inventory, hear message you have no room.

### Expected Behavior

Shield and bow should be swapped (or bow equipped and shield unequipped)

### Additional context

![image](https://user-images.githubusercontent.com/28605404/179865199-b6a5a518-66a8-440c-9054-a34069c5ee41.png)
![image](https://user-images.githubusercontent.com/28605404/179865221-bcb69492-8728-4d49-89c7-8cbb2ffd06d9.png)
Both screen shots, should be able to Shift + Left Click the bow and equip it, but you cannot. In second screenshot, if the spiked club is also equipped, it will swap both weapon and shield off and equip the bow.

**Comment by ephphatha** [comment]
Shift-clicking fails to equip any two-handed weapon with a one handed item in the off-hand, but only if the item in the off-hand was dropped into the off-hand slot from the inventory. If you swap the item from the main hand to the off-hand then shift-clicking works.
