### ISSUE TITLE
[Launchpad PPA] Ubuntu 20.04 requires libfmt8

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#5077]
@muzena 
We received a report from Discord user Grendel Aelfgar that the DevilutionX stable package for Ubuntu 20.04 has a dependency on libfmt.so.8 which is not generally available for that platform. Launchpad PPA does have an "Fmtlib backports" package for libfmt7, but it's only available for amd64. Probably, you will need to add `-DDEVILUTIONX_SYSTEM_LIBFMT=OFF` to cmake.

FYI, here is the output from `readelf -d`.

```
$ readelf -d devilutionx

Dynamic section at offset 0x1b3eb10 contains 38 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libasan.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2_image-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfmt.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libbz2.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libsodium.so.23]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libubsan.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
...
```

**Comment by muzena** [comment]
@StephenCWills 

I will check this tomorrow, I will try to rebuild libfmt,
I build devilutionx stable with libfmt system off, excepte ubuntu bionic, on bionic build was done with system libfmt.,

**Comment by AJenbo** [comment]
We require version 8 which only because available in jammy

**Comment by muzena** [comment]
@AJenbo @StephenCWills 
Whic source do I use for libfmt?
https://github.com/diasurgical/fmt/tree/nxdk-2022-07-19
or
https://github.com/fmtlib/fmt

**Comment by muzena** [comment]
@StephenCWills 

> (NEEDED) 

So, this libraries all 'missing'?
I have all dependencies installed, and upload to PPA [libfmt 9](https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/diablo5/+packages) for (for Ubuntu Focal, Jammy and Kinetic, for Bionic build failed) and get same output in terminal.

Dynamic section at offset 0x551d60 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2_image-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfmt.so.9]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libbz2.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libsodium.so.23]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]

**Comment by StephenCWills** [comment]
These are the executable's direct dynamic dependencies. I presented this list as evidence of the dependency on libfmt.so.8. I also thought you might find it useful for verifying your solution or cross-checking against the packages available on the platform.

If `readelf -d` lists libfmt.so.9, then the situation has not been resolved. Try statically linking against the library (`-DDEVILUTIONX_STATIC_LIBFMT=ON`).

**Comment by AJenbo** [comment]
you have two options, either you build libfmt and make it avalible on the PPA and set it as a dependency of the devilutionx package. Or hardlink it.

**Comment by muzena** [comment]
@AJenbo 

> either you build libfmt and make it avalible on the PPA and set it as a dependency

That's what I did, but the problem still exists.

@StephenCWills 
I add statically linking [-DDEVILUTIONX_STATIC_LIBFMT=ON](https://github.com/muzena/devilutionX/blob/a64b25691614ec8578d6ddf76594a02006623cda/Packaging/debian/rules#L37), same thing problem still exists.

**Comment by StephenCWills** [comment]
> I add statically linking [-DDEVILUTIONX_STATIC_LIBFMT=ON](https://github.com/muzena/devilutionX/blob/a64b25691614ec8578d6ddf76594a02006623cda/Packaging/debian/rules#L37), same thing problem still exists.

Surely you can figure this out. Here is what I get.

```
$ cmake ../.. -DCMAKE_BUILD_TYPE=Release -DDEVILUTIONX_SYSTEM_LIBFMT=OFF -DDEVILUTIONX_STATIC_LIBFMT=ON
...
-- 📚 libfmt: static library from source
...
-- Configuring done
-- Generating done
-- Build files have been written to: ...

$ make -j8 devilutionx
...
[100%] Built target devilutionx

$ readelf -d devilutionx

Dynamic section at offset 0x520788 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2_image-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libbz2.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libsodium.so.23]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
...
```

**Comment by AJenbo** [comment]
> @muzena
> 
> > either you build libfmt and make it avalible on the PPA and set it as a dependency
> 
> That's what I did, but the problem still exists.

libfmt8 is clearly not available on the list of packages in your PPA:
![image](https://user-images.githubusercontent.com/204594/180402716-57580097-7b7f-4dc6-bd34-385e6ded8f9e.png)

> I add statically linking [-DDEVILUTIONX_STATIC_LIBFMT=ON](https://github.com/muzena/devilutionX/blob/a64b25691614ec8578d6ddf76594a02006623cda/Packaging/debian/rules#L37), same thing problem still exists.

If you are trying to build it statically you should also disable use of the system library:
https://github.com/muzena/devilutionX/blob/a64b25691614ec8578d6ddf76594a02006623cda/Packaging/debian/rules#L36

**Comment by muzena** [comment]
I'm testing here  to not spamming mail
https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/diablo5/+packages

**Comment by AJenbo** [comment]
In that case you should just need to add the libfmt9 as a dependency for the devilutionx package.

**Comment by muzena** [comment]
libfmt9 is dependency in deb file.
I will test libfmt build flags/options in clean install in virtualbox.

**Comment by muzena** [comment]
@StephenCWills 
What when I set:
	-DDEVILUTIONX_SYSTEM_LIBFMT=ON
	-DDEVILUTIONX_STATIC_LIBFMT=ON

then it said:
-- 📚 libfmt: static system library

**Comment by AJenbo** [comment]
Why are you doing that when he suggested:
-DDEVILUTIONX_SYSTEM_LIBFMT=OFF
-DDEVILUTIONX_STATIC_LIBFMT=ON
?

**Comment by muzena** [comment]
> Why are you doing that when he suggested:
-DDEVILUTIONX_SYSTEM_LIBFMT=OFF
-DDEVILUTIONX_STATIC_LIBFMT=ON
?

I just trying, options.

I add libfmt static, but with static -DDEVILUTIONX_STATIC_LIBFMT=ON, build on [armhf](https://launchpadlibrarian.net/614353862/buildlog_ubuntu-jammy-ppc64el.devilutionx_1.4.0-202207231228~ubuntu22.04.1_BUILDING.txt.gz) failed.

**Comment by AJenbo** [comment]
Disabling armhf for now is probably your best option so that most users can get an updated build. Then you can enable armhf once you figure out a solution. Ubuntu on 32bit arm is probably very rare, I'm not even sure it's officially supported.

**Comment by StephenCWills** [comment]
> What when I set: -DDEVILUTIONX_SYSTEM_LIBFMT=ON -DDEVILUTIONX_STATIC_LIBFMT=ON
> 
> then it said: -- 📚 libfmt: static system library

As far as I can tell, this isn't going to work. At least on my Debian system, fmt-config.cmake does not have an option for static linking.

**Comment by StephenCWills** [comment]
As for the armhf error, it could be due to this.
https://github.com/fmtlib/fmt/issues/2840

**Comment by muzena** [comment]
> As for the armhf error, it could be due to this.
> https://github.com/fmtlib/fmt/issues/2840
> 

This patch is included in source.

This is insane, same libfmt source code, when is builds in libfmt deb's armhf is successfully built, but when is built same source code with static source build option then build failed.

**Comment by AJenbo** [comment]
then build it as a lib and set it as a dependency

**Comment by muzena** [comment]
**armhf** build succesffully when it uses **system libsimpleini** dependecy, and **arm64** smpq core dump error was gone.
readelf gave me this output, is this now ok? 

>readelf -d /usr/bin/devilutionx 

Dynamic section at offset 0x1b6ccb0 contains 38 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libasan.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2_image-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libbz2.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libsimpleini.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libsodium.so.23]
 0x0000000000000001 (NEEDED)             Shared library: [libSDL2-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libubsan.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]

**Comment by AJenbo** [comment]
libubsan and libasan should only be there for debug builds, not for releases. Please make sure that is also what you are building. If not the game will perform very poorly.

libsimpleini is only avalible from Ubuntu 22.04 so if you are targeting older versions you need to provide libsimpleini in the ppa.

**Comment by muzena** [comment]
`We received a report from Discord user Grendel Aelfgar that the DevilutionX stable package for Ubuntu 20.04 has a dependency on libfmt.so.8 which is not generally available for that platform. Launchpad PPA does have an "Fmtlib backports" package for libfmt7, but it's only available for amd64. Probably, you will need to add -DDEVILUTIONX_SYSTEM_LIBFMT=OFF to cmake.`

I will uploaded libfmt9 and problem solved?
On my system DevilutionX build with **-DDEVILUTIONX_SYSTEM_LIBFMT=ON** built option normally works despite terminal output: 

>  0x0000000000000001 (NEEDED)             Shared library: [libfmt.so.8]

**Comment by AJenbo** [comment]
> On my system DevilutionX build with **-DDEVILUTIONX_SYSTEM_LIBFMT=ON** built option normally works despite terminal output:
> 
> > 0x0000000000000001 (NEEDED)             Shared library: [libfmt.so.8]

Yes, because you have libfmt installed. But the package in the PPA doesn't specify that libfmt needs to be installed. So when users install DevilutionX from the PPA they may not have libfmt installed, leaving them with a game that just gives an error that libfmt is missing.

Note that it has to be the same version of libfmt, so if you are linking with libfmt9 you need to also upload that to your PPA as Ubuntu does not have it yet.

You can see here what versions of libfmt are in the various versions of Ubuntu:
https://packages.ubuntu.com/search?keywords=libfmt

**Comment by muzena** [comment]
Ok, then I think problem is solved, I add libfmt9 and simpleini dependencies to [stable PPA](https://launchpad.net/~devilutionx/+archive/ubuntu/stable/+packages).

**Comment by Quix0r** [comment]
On Devuan 4.0 (stable) I have maximum `7.1.3+ds1-5` available. As I can see with `git blame CMake/Dependencies.cmake |grep fmt` the change to 8.0.0 was introduced with commit d2d9fcb5b5 which currently prevents me from building this game. Is there any reason for going forward with such a "newer" version? I know libfmt9 is around but that's way more unstable I guess.

**Comment by glebm** [comment]
Yes, there are some useful features in the newer versions, and we're not going to be stuck on old versions because you can trivially vendor the dependency (`-DDEVILUTIONX_SYSTEM_LIBFMT=OFF` will handle fetching, building, and linking it statically) or set up a separate PPA like @muzena did above.

**Comment by Quix0r** [comment]
Ah, that's what I didn't know! Thank you so much. :-) And I understand it that you need then the "newer" version.

**Comment by Quix0r** [comment]
When I did a `make install` and `devilutionx` (means ran it from where it was installed I got the famous message that `libfmt.so.9` was missing. So I did a `cp _deps/libfmt-build/libfmt.so* /opt/lib` and `sudo ldconfig` and I was able to start the game as usual. PS: `/opt` is writable to my user so I can install games without `sudo`. :-)

**Comment by glebm** [comment]
@Quix0r DevilutionX automatically detects if your system version is too old and falls back to the vendored version:

https://github.com/diasurgical/devilutionX/blob/7604cc2c1ba3c555fa667393f0c16d46001ce973/CMake/Dependencies.cmake#L120-L134

Which commands did you use to build it?

**Comment by AJenbo** [comment]
@Quix0r considering that your issue isn't with creating a PPA and building it via Launchpad you couldn't hijack this issue. Possibly your issue would also have been better as a discussion or chat.
