### ISSUE TITLE
Do not highlight monsters when targeting with Heal Other or Resurrect

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5104]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

asd

### To Reproduce

sad

**Comment by obligaron** [comment]
This was fixed with #5268 or? 🙂

**Comment by qndel** [comment]
Probably, dude just wrote "implements" instead of fixes/resolves 🙄
