### ISSUE TITLE
[QoL] after leaving the dungeon, move alive monsters to spawn points.

### ISSUE THREAD

**Issue by M1sh2** [diasurgical/devilutionX#5127]
### Operating System

Windows x64

### DevilutionX version

1.4.0 (latest release)

### Describe

Briefly: If players are dead or out of dungeon, i think should move alive monsters to spawn points.

Because there is an extremely strong problem (probably for me) when enemies pile up near the entrance/exit, they start spamming the attack, the player (or players) can not do anything. For multiplayer this is utter madness, I tried to show my friend diablo (he is never played it), as a result both burned out :D.

*issue made with deepl

### To Reproduce

1. It's enough to play multiplayer without restarting,
2. Step by step, go to 5-9, 9-13, where too dangerous , and prevent spamming already too damn hard.

### Expected Behavior

At the entry/exit point, if you collect monsters, they are beaten you to death.

**Comment by qndel** [comment]
If you block entrances with monsters so you die instantly after entering, it's not a problem with the game, it's a problem with your skill

**Comment by M1sh2** [comment]
Really, I should have listened to mr. clown qndel before playing your port.

**Comment by qndel** [comment]
I feel like people want to remove every single aspect of the game that makes it just a bit of a challenge (dying after stacking monsters on entrance, losing items after dying, items being destroyed after durability reaches 0) - that's not within scope of DevilutionX.

**Comment by M1sh2** [comment]
Oh , nice, you deleted my comment.
Did you even read what I wrote? 

I can't communicate with someone who can't see me, can't hear me, calls me a casual.

It's absolutely boorish behavior, I might make a joke about myself, I wouldn't do that to anyone else. In a ratty way deleting something that was written to you says something about you.

But more than that, I will not recommend your port. It's not a bad experience in singleplayer, but no one in their right mind is going to sit around grindin' till blue in the face if it doesn't bring any enjoyment to that process.

That's what quality of life is for, I'm not suggesting that we ruin the game. I'm suggesting making it more accessible, it's like with dark souls, when instead of the mechanics of restoring humanity at the campfire, it can be restored everywhere. Did it make it worse?
Oh no, they sagged to the housewives, what have they done.

**Comment by qndel** [comment]
> But more than that, I will not recommend your port. It's not a bad experience in singleplayer, but no one in their right mind is going to sit around grindin' till blue in the face if it doesn't bring any enjoyment to that process.

Love the attitude - "do what I suggest or I won't recommend the port".
Think we can live with that. 

That's not "quality of life", that's "I refuse to accept I played poorly and suffer the consequences of it".
Also sounds very QoL to have to search for the monsters scattered over the whole level after just going to town to buy some potions.
