### ISSUE TITLE
Unexpected top level directory name in 1.4.1 release

### ISSUE THREAD

**Issue by jpalus** [diasurgical/devilutionX#5133]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

`src` archive for release `1.4.1` contains top level directory `devilutionx-src-1.4.1-5ad792133`. Two issues that I see with this:
1. After #3743 I was expecting `src` archive to have top level directory `devilutionx-src-1.4.1` 
2. 5ad792133 is not a hash of commit that belongs to `1.4.1`, it's one commit after the tag. Even more confusingly this hash is only in directory name, actual contents of archive do not seem to include this change.

### To Reproduce

1. Extract `src` archive for `1.4.1` release

**Comment by glebm** [comment]
Thanks, I've fixed the directory name and reuploaded
