### ISSUE TITLE
Hellfire can not click on npc

### ISSUE THREAD

**Issue by therezor** [diasurgical/devilutionX#5136]
### Operating System

Mac

### DevilutionX version

1.4.1 (latest release)

### Describe

Some NPC became unclickable when you return to town and you simply can not repair armor.
Also I can not withdraw money from storage.
Env: Latest osx, mac book pro 14 (m1 pro cpu)

### To Reproduce

1. Go out of town
2. Return to town
3. You can not click on some npcs

**Comment by DakkJaniels** [comment]
I can't reproduce this on PC. Are you sure this is 1.4.1 and not latest (or a recent) master?

**Comment by therezor** [comment]
@DakkJaniels  No, definitely not master, Version 1.4.1 (1.4.1)

**Comment by therezor** [comment]
Here is a short video:
https://youtu.be/NSdusfAQU3o
- I can select the money amount, but pressing enter does nothing
- NPCs are not highlighted and clicking on them has no effect

**Comment by StephenCWills** [comment]
Reproduced on MacBook Air.

@AJenbo Seems like the `devilutionx-macos-universal.zip` release was built from the wrong version of the source.

**Comment by AJenbo** [comment]
https://www.reddit.com/r/Devilution/comments/w87a7r/cannot_install_141_release_mac_air_2018/

**Comment by therezor** [comment]
Tried build form 1.4 branch and it is working fine (https://github.com/diasurgical/devilutionX/actions/workflows/MacOSX.yml?query=branch%3A1.4)

**Comment by AJenbo** [comment]
@therezor please be aware that you have download an older beta that may not be fully multiplayer compatible with the release. We will upload the proper Mac build to the release page shortly.

**Comment by AJenbo** [comment]
@therezor the new build of 1.4.1 for mac is now avaible https://github.com/diasurgical/devilutionX/releases/download/1.4.1/devilutionx-macos-x86_64.dmg
