### ISSUE TITLE
Linux armhf build missing for v1.4.1

### ISSUE THREAD

**Issue by celentanos** [diasurgical/devilutionX#5139]
### Operating System

Other (please specify)

### DevilutionX version

1.4.1 (latest release)

### Describe

Hello, I don't know if this was intentional, but I'm missing the armhf build for the latest 1.4.1 version.

Is this still being done? Or were there reasons to end the armhf builds?

### To Reproduce

1. Go to [1.4.1](https://github.com/diasurgical/devilutionX/releases/tag/1.4.1)
2. Find armhf build

**Comment by glebm** [comment]
Someone would need to set up release build automation for an armhf Linux build since we no longer build it manually.

See here for an example release build workflow: https://github.com/diasurgical/devilutionX/blob/master/.github/workflows/retrofw_release.yml

**Comment by AJenbo** [comment]
Ok, we weren't really sure they where being used anymore as downloads had dropped to just over 1%. Do you specifically want armhf or is ARM64/ARMv8/AArch64 also an option?

**Comment by guitmz** [comment]
hey v1.4.1 is also missing macOS binaries, even though they are mentioned in the changelog.

**Comment by AJenbo** [comment]
@guitmz Yes, that is unrelated to this issue though. It was build off the wrong code and we are looking in to correcting it and uploading a new build. It's best to not mix different issues.

**Comment by AJenbo** [comment]
@guitmz the macOS build for 1.4.1 are now up https://github.com/diasurgical/devilutionX/releases/download/1.4.1/devilutionx-macos-x86_64.dmg it's only build for x86_64, but should work perfectly fine on M1. Hopefully we can have a native build by the next release.

**Comment by guitmz** [comment]
Thats great, thanks a lot! 😁

**Comment by AJenbo** [comment]
@flxs the macOS build for 1.4.1 are now up https://github.com/diasurgical/devilutionX/releases/download/1.4.1/devilutionx-macos-x86_64.dmg it's only build for x86_64, but should work perfectly fine on M1. Hopefully we can have a native build by the next release.

**Comment by celentanos** [comment]
There are some handhelds (e.g. Odroid Go Advance) based on RK3326. I don't know how much EmuELEC and "the others" depend on this builds. Maybe they build them themselves.

**Comment by glebm** [comment]
Most distros for these handhelds compile themselves, including EmuElec, Batocera, RetroLX, etc

**Comment by AJenbo** [comment]
@celentanos are you needing it for Odroid Go Advance?

**Comment by celentanos** [comment]
@glebm thank you, i did not know that.

@AJenbo thank you, but no. I don't want to keep the 1% downloads alive. I will then also compile myself if I need it :)

Best regards.
