### ISSUE TITLE
I cannot start new game with Polish sound pack [PS Vita].

### ISSUE THREAD

**Issue by J013k** [diasurgical/devilutionX#5141]
### Operating System

PlayStation Vita

### DevilutionX version

1.4.1 (latest release)

### Describe

I cannot start new game with Polish sound pack on a PS Vita.

When I delete this sound pack I can start new game.

### To Reproduce

1. Put [pl.mpq](https://github.com/diasurgical/devilutionx-assets/releases/download/v1/pl.mpq) in `ux0:data/diasurgical/devilution/`.
2. Select Polish language.
3. Start new game.
4. Almost immediately when the loading bar will be shown the game will crash:
![https://i.imgur.com/BcQVgWq.png](https://i.imgur.com/BcQVgWq.png)
![https://i.imgur.com/IJJMCmH.png](https://i.imgur.com/IJJMCmH.png)
![https://i.imgur.com/i5Xyo32.png](https://i.imgur.com/i5Xyo32.png)

### Expected Behavior

It will be nice if Polish sound pack can work for PS Vita.

### Additional context

A similar issue has been fixed for Switch:
https://github.com/diasurgical/devilutionX/issues/3350.

**Comment by AJenbo** [comment]
You are still using the old release of the sound pack, please update: https://github.com/diasurgical/devilutionx-assets/releases/download/v2/pl.mpq

**Comment by J013k** [comment]
Thank you! Thank you very much!
v2 Polish sound pack seems to work.

Is there a way to easily find the latest sound packs?

Currently e.g. Russian dub points to v2:
* Improve Russian localization ([optional dub](https://github.com/diasurgical/devilutionx-assets/releases/download/v2/ru.mpq) by Stream)
[1.4.0](https://github.com/diasurgical/devilutionX/releases/tag/1.4.0)

Polish dub points to v1:
* Added Polish ([optional dub](https://github.com/diasurgical/devilutionx-assets/releases/download/v1/pl.mpq) by professional voice actors)
[1.3.0](https://github.com/diasurgical/devilutionX/releases/tag/1.3.0)

**Comment by AJenbo** [comment]
Se the latest install instructions
https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md#installing

or the additional assets release:
https://github.com/diasurgical/devilutionx-assets/releases

**Comment by J013k** [comment]
Thank you once again for help.
Have a good day.
Best regards.
