### ISSUE TITLE
Skullwings are gold in color instead of red.

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5153]
Skullwings are gold in color instead of red.

Current master:
![skullwings](https://user-images.githubusercontent.com/45902449/181958005-45bc0eb6-1352-4297-939b-a307a7237b3c.png)

Release 1.2.0:
![skullwing](https://user-images.githubusercontent.com/45902449/181958720-4fb98cb8-953d-412e-94cc-7da213808a01.png)

Savegame:
[skullwing.zip](https://github.com/diasurgical/devilutionX/files/9227166/skullwing.zip)

I don't know if this is intentional.
But I think that the golden color creates a better contrast. We're happy to keep it that way.

Or would you like a research since when do they look like this?

**Comment by glebm** [comment]
This was somewhat intentional because there were 2 monsters that look identical but I'm still not sure what the best colors for each are

**Comment by Chance4us** [comment]
In any case, I think they look really good. I was just a little surprised because I've never seen them like this before. Thank you for the fast feedback. So I close the issue immediately.

**Comment by AJenbo** [comment]
Before this i didn't even realize they where different monsters :)

This one doesn't fire missiles the other one does.
