### ISSUE TITLE
Toggling upscaling crashes the game

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#5168]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Commit: 59482b5e9f9bb9c4d0b3a54eba5902f8df93998e Debian Sid, nVidia 470.129.06

```
./devilutionx
DEBUG: Using udev for HIDAPI joystick device discovery
DEBUG: Failed loading udev_device_get_action: /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0: undefined symbol: _udev_device_get_action
DEBUG: Using udev for joystick device discovery
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
INFO: Removed file: ./Diablo1ReadOnlyTest.foo
SDL_audiolib debug: SDL initialized with sample format: SDL_audiolib debug: S16LSB
INFO: OpenGL shaders: ENABLED
INFO: Created renderer: opengl
DEBUG: Renderer already associated with window
ERROR: SDL Error
Renderer already associated with window

Eroare s-a produs la: Source/utils/display.cpp linia 397
DEBUG: Parameter 'renderer' is invalid
```

### To Reproduce

0. Start game
1. Settings
2. Upscale is ON
3. Turn it OFF
4. Turn it ON
5. Crash

### Expected Behavior

Not crash

**Comment by Chance4us** [comment]
In fact, the following message appears.
![error](https://user-images.githubusercontent.com/45902449/182253447-b1bb3720-a7fb-4df9-9c10-42df26200291.png)
