### ISSUE TITLE
Object state is not synced if you where not on the floor when the object was operated

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5172]
Because object network messages are now validated based on object position `DeltaSyncObject()` will only be populated if you where present on a level with an object at the same location (most likely the same level)
https://github.com/diasurgical/devilutionX/blob/master/Source/msg.cpp#L1643

Broken in https://github.com/diasurgical/devilutionX/commit/de83d9440ef8b881945286a722cfa2d9fc947f2e#diff-3ca88f26b73a54abe9ce9eb981f4ab2ae1e454516047fa1854c37992d0afa7b8R1712

I'm not sure if it would be best to change deltasync to be x/y indexed or revert the change.

**Comment by ephphatha** [comment]
Making the object delta position based isn't too hard, the difficulty is how the deltas are passed over the network -_-. Opened a draft but I can't work on it more till after work.
