### ISSUE TITLE
Underscore is wrong

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#5175]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Commit https://github.com/diasurgical/devilutionX/commit/439a9926e54f5688f5142abb6f0d4d74afc7f6c2
Underscore is rendered incorrectly
![image](https://user-images.githubusercontent.com/14297035/182314247-f6f78b2c-40f5-46f9-9b38-c0f2664f2794.png)

### To Reproduce

Name your char containing underscore or write on chat

**Comment by glebm** [comment]
Huh I thought this was fixed by https://github.com/diasurgical/devilutionX/pull/4350

**Comment by qndel** [comment]
> Huh I thought this was fixed by #4350

Looks like I had an old copy of devilutionx.mpq messing things up :D
