### ISSUE TITLE
Stairs hero position offset

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5185]
If you go down a level like in this example and then come back, then the hero is in the following position.

![offset1](https://user-images.githubusercontent.com/45902449/182655360-ebd8381b-6e66-448d-999f-179cb448a239.png)

If you then use the warp spell, then your hero will be moved to the following position.

![offset2](https://user-images.githubusercontent.com/45902449/182655452-2252fc81-e57c-4881-9c4f-8e024aa79262.png)

As you can see, the two positions differ and it is desirable to treat the positions for the stairs equally in both cases.

I can't currently tell if it's a vanilla issue or since when it was introduced.

Savegame:
[stairs_test.zip](https://github.com/diasurgical/devilutionX/files/9253177/stairs_test.zip)

EDIT:
Of course, the same applies to the stairs that lead upstairs.

**Comment by qndel** [comment]
That's not only crypt - leo's tomb for example
Entered:
![image](https://user-images.githubusercontent.com/14297035/182852457-78eeaeee-a541-4c4e-8476-e3400872cc72.png)

Warped:
![image](https://user-images.githubusercontent.com/14297035/182852503-40a856fc-5f19-4073-b84d-7243f8974daf.png)

**Comment by Chance4us** [comment]
The position in nest is still not correct.
Savegame:
[nest.zip](https://github.com/diasurgical/devilutionX/files/9541471/nest.zip)

To reproduce:
1. Go level up and go down
2. Use warp spell

I can't say at the moment if there are more of such situations in game.

**Comment by Chance4us** [comment]
Thanks for reopening @qndel 
To reproduce the issues you need to go lever up and down or the other way around and to use Warp.
Then you will see the offset. This means that either the hero's position or the warp position is incorrect.

1. cathedral: Down to level 4 ("ogden's sign" only) hero/warp position shifted, all other cathedral stairs are ok
2. catacombs: all upstairs positions are shifted, bone chamber position shifted as well, downstairs are ok
3. caves: all upstairs positions are shifted, downstairs are ok
4. nest: all upstairs positions are shifted, downstairs are ok
5. hell: tested only upstairs.
The warp and hero position is the same, but the hero stands displaced in the entrance (unclear if vanilla behavior)
Downstairs not tested yet.

**Comment by Chance4us** [comment]
Updated.
