### ISSUE TITLE
Help window is missing its scrollbar

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5192]
When opening the in game help no scroll bar appears on the right side of the window.

Version 1.4.1, Windows

**Comment by vlolteanu** [comment]
![image](https://user-images.githubusercontent.com/3142367/183944409-ea8de07d-8503-4d6d-a9ac-62a65b04b29a.png)

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/183955035-da2bad46-79b4-4d68-bf65-17aac85788e9.png)

**Comment by Raphalex46** [comment]
A friend and I have started working on this as it seems like a good first issue for us (beginners for open source contributions and for devilutionX as well). Is that ok ?

**Comment by AJenbo** [comment]
@Raphalex46 yes that is excellent, thank you for making a note of this

**Comment by vlolteanu** [comment]
@Raphalex46 
![image](https://user-images.githubusercontent.com/3142367/200970427-5ed93cc9-31b2-443d-8a41-fcaa1d4bf2b9.png)
