### ISSUE TITLE
Hit boxes in latest master

### ISSUE THREAD

**Issue by FireIceTalon** [diasurgical/devilutionX#5215]
First screen shot is 1.4.1 and second one is master
![Screen Shot 2022-08-07 at 3 19 57 PM](https://user-images.githubusercontent.com/98377923/183311864-af873c5b-04cb-4115-bb43-4794c9f5b4ea.jpg)
![Screen Shot 2022-08-07 at 3 24 08 PM](https://user-images.githubusercontent.com/98377923/183311866-77ecb810-8533-408a-9f1f-e3647e527d1b.jpg)
### Operating System

Windows x64

### DevilutionX version

[Other (please specify version number)](https://github.com/diasurgical/devilutionX/commit/d741018fee1952ac338415a34af56d741633bcbc)

### Describe

In the latest master it feels like the hit boxes have become significantly smaller. When clicking on chests, corpses, or ground objects in general I often have to reposition my cursor to be able to highlight the item so I can pick it up or activate it. It seems to happen on monsters as well, though to a somewhat lesser extent. Can anyone verify?

### To Reproduce

go to any dungeon level, select a chest, corpse or any object on the ground and see if you have to reposition your cursor to pick up the item or activate it.

### Expected Behavior

For items on ground to be highlighted when I put my cursor over them regardless of where I put the cursor.

**Comment by qndel** [comment]
Bisected to https://github.com/diasurgical/devilutionX/commit/2493f06116c1458c2ccaf2e5b8d913561705226d

**Comment by FitzRoyX** [comment]
Heh, I was just complaining about this in discord, but I didn't realize that it got worse since 1.4.1.

**Comment by FitzRoyX** [comment]
I don't think the hitbox got smaller than before, it looks like it just shifted down about 1 tile.

**Comment by AJenbo** [comment]
> Heh, I was just complaining about this in discord, but I didn't realize that it got worse since 1.4.1.

You make it sound like 1.4.1 was different from vanilla

**Comment by FireIceTalon** [comment]
1.4.1 feels ok to me. Its only in the master as far as i can tell.

**Comment by qndel** [comment]
Medium chest is a good way to test
Master:
![image](https://user-images.githubusercontent.com/14297035/183349636-2926fb31-602c-4c4a-b979-95534d436eed.png)
Somewhere else:
![image](https://user-images.githubusercontent.com/14297035/183349651-33864e3e-053f-4555-b538-7c45df1b400d.png)

**Comment by AJenbo** [comment]
@obligaron do you have time to look at this :)
