### ISSUE TITLE
Lighting does not apply to sprites with unique TRNs

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#5219]
If we consider this a bug, it is easy to fix with the new rendering system:

![image](https://user-images.githubusercontent.com/216339/183357046-88764145-9b77-4a1a-afa9-cb9e41e0a7ab.png)

In the screenshot, the 2 dead monsters at the bottom edge of the screen have full lighting applied.

**Comment by qndel** [comment]
Don't think it's a bug but they keep their light? I mean it's only logical that if they "glowed" while being alive, they corpses would keep doing it too :D
