### ISSUE TITLE
PvP mod/master bug - Murkey Pools for the arena's cost the player 30 mana.

### ISSUE THREAD

**Issue by FireIceTalon** [diasurgical/devilutionX#5237]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Here is a link to the build in question - https://github.com/diasurgical/devilutionX/suites/7789559185/artifacts/328190699

After the player casts telekineses to click on a Murky Pool shrine in either Arena 2 or 3, the pool removes 30 mana.

### To Reproduce

type /arena 2 or /arena 3 to proceed to the arenas, cast telekineses on any Murky Pool shrine.

### Expected Behavior

For normal mana cost (8) to be withdrawn from a normal telekinesis cast, but no mana withdrawn from actually touching the Murky Pool shrine

### Additional context

https://user-images.githubusercontent.com/98377923/184463020-b1085f09-1ff4-454a-9f5e-6ea9d84d708e.mov

**Comment by qndel** [comment]
That arena part was unnecessary, I was about to close this issue because arena still not merged = unofficial = not sure if we care

But I'd risk saying all objects that cast any spells atm will consume player's mana

**Comment by qndel** [comment]
Broken by https://github.com/diasurgical/devilutionX/commit/aa6ea3907e4df3d14595605e8b41976ad40e01f0 ...

**Comment by StephenCWills** [comment]
> That arena and telekinesis part was unnecessary, I was about to close this issue because arena still not merged = unofficial = not sure if we care
> 
> But I'd risk saying all objects that cast any spells atm will consume player's mana

It's fine, because that's what they tested. It's better than claiming it's in master when maybe it wasn't.

**Comment by qndel** [comment]
> > That arena and telekinesis part was unnecessary, I was about to close this issue because arena still not merged = unofficial = not sure if we care
> > But I'd risk saying all objects that cast any spells atm will consume player's mana
> 
> It's fine, because that's what they tested. It's better than claiming it's in master when maybe it wasn't.

but then it should only be reported if it's in master :D

**Comment by Chance4us** [comment]
By the way, since you're talking about murky pool and mana consumption. In single player I had recently the impression activating a murky pool causes consuming mana. I don't remember it was the case in vanilla.
However, I would have to double-check this suspicion.

**Comment by FireIceTalon** [comment]
It definitely does not happen in vanilla.

**Comment by DakkJaniels** [comment]
I think this should be fixed with #5243.

#4999 switched the shrine missiles to TARGET_MONSTERS for some reason, which I think was incorrect, as this causes the Add[missile] functions to use mana.

**Comment by AJenbo** [comment]
it was switched so that `sourceType()` will return `MissileSource::Player`, else `sourcePlayer()` will return `nullptr`.

**Comment by DakkJaniels** [comment]
> it was switched so that `sourceType()` will return `MissileSource::Player`, else `sourcePlayer()` will return `nullptr`.

so change to TARGET_BOTH so it uses mana?

**Comment by AJenbo** [comment]
Yeah I think that would work.

**Comment by DakkJaniels** [comment]
Ok switched it, It did seem to work fine for the few shrines I was able to quickly find and test with (found Holy and Magical) for `TARGET_PLAYERS` . It also worked fine with `TARGET_BOTH` for the shrine I was able to find in a quick test run.

**Comment by AJenbo** [comment]
I noticed that the code hasn't been updated for the shrines yet, so TARGET_PLAYERS won't have the negative effect yet, but could soon. So good that we use TARGET_BOTH already and won't have to fix it again :)
