### ISSUE TITLE
Withdrawing money from stash is not feasible.

### ISSUE THREAD

**Issue by joex3999** [diasurgical/devilutionX#5244]
### Operating System

Nintendo 3DS

### DevilutionX version

1.4.1 (latest release)

### Describe

When trying to withdraw gold from the stash on the Nintendo-3DS version. Pressing **select** prompts you to choose an amount to withdraw but there is no way to supply input to the prompt. ( Also thank you for this amazing port !! ).

### To Reproduce

1. Go to Gillian ( on 3DS Version)
2. Press select to open " How many gold pieces do you want to withdraw " prompt

### Expected Behavior

Withdrawing money successfully from the stash

**Comment by AJenbo** [comment]
It should popup the virtual keyboard, but I guess that is not the case.

As a side note there should be little need to withdraw gold, other then to give it to other players. Since you can pay vendors directly with the gold from your stash.

**Comment by joex3999** [comment]
`Since you can pay vendors directly with the gold from your stash.`
Didn't know this fact, I guess the issue could be closed due to lack of importance of the feature in this case. Thanks for the fast reply.

**Comment by StephenCWills** [comment]
> It should popup the virtual keyboard, but I guess that is not the case.

The virtual keyboard on 3DS doesn't pop up while in-game because it hijacks the main thread. This would probably be okay in single player, but would likely cause problems in multi. I've been holding my breath for #2249 to resolve this.
