### ISSUE TITLE
Hellfire - Multiplayer - Brown/gray suit respawn bug 

### ISSUE THREAD

**Issue by CuraeL** [diasurgical/devilutionX#5245]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

Hellfire specific bug. When enabling the crazy nut quest and go multiplayer (I haven't tested in single player) You can go and find the brown suit again and again and always get a bovine plate dropped from the quest NPC. 

Same behavior with grey suit on floor 3 of nest.

### To Reproduce

1. Go to the quest NPC and get the bomb for opening the nest, in a multiplayer game
2. Blow up the entry to the nest
3. Descend to level 4
4. Grab the brown suit
5. Make town portal and go to quest NPC
6. He drops bovine plate
7. Take town portal back to level 4
8. Pick up respawned brown suit again
9. Town portal back to the quest NPC again, he drops another bovine plate
10. Rinse repeat as many times as you'd like

### Expected Behavior

I would expect the brown suit to disappear once bovine plate has been spawned on town floor (at least in current game)

**Comment by obligaron** [comment]
This was fixed with #5484 (brown suit only spawns once) and will be included in 1.5 🙂
