### ISSUE TITLE
Enable Android TV support

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5246]
- Needs a banner
    - Size: 320 x 180 px, xhdpi resource
    - Text should be included in the image. If your app is available in more than one language, you must provide versions of the banner image for each supported language.
    - Manifest <application> tag needs appropriate attribute
        - Example:
            android:banner="@drawable/banner"
- Needs to be classified as a game (Android TV separates games from other apps in its app drawer)
    - Manifest <application> tag needs appropriate attribute:
        android:isGame="true"                
- Needs an intent type of ACTION_MAIN with category CATEGORY_LEANBACK_LAUNCHER
    - Example:
```xml
          <activity
            android:name="com.example.android.TvActivity"
            android:label="@string/app_name"
            android:theme="@style/Theme.Leanback">
            <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
            </intent-filter>
          </activity>
```

**Comment by slajerek** [comment]
I've just realised that DevilutionX is still not available for Android TV? That's really bad as it seems most of work of porting this to Android is already done. Please confirm is it really that complex to add these requirements? 

Is there anything I can help with to make it available for Android TV? Thanks in advance.

**Comment by AJenbo** [comment]
Mostly it's just hard to verify that it was done correctly without owning an Android TV.

**Comment by slajerek** [comment]
I have Nvidia Shield TV and Mibox, can try on both, question is if it's already compilable from Android Studio on Mac or if you have some APK then I can give it a try.

**Comment by AJenbo** [comment]
Well it should already work just fine on Android TV, the issue is that Google wants some extra device specific promotional elements. Like making banners in 20 languages (tip don't add text and just do one if this makes sens).

Then figure out what manifest they are talking about and add the attributes.

The most helpful thing would be finding another app that complies with these requirements and can be used as an example of how and where.

**Comment by slajerek** [comment]
It actually works indeed, but one note the buttons on AndroidTV remote are reversed in menus for step into and back, i.e. button back steps into menu items, and 'fire' steps back which is not natural. I guess that may be related to controller mapping being reversed too. But apart from that it works indeed quite perfectly. I asked my friend who is graphics designer to prepare the banner.

**Comment by AJenbo** [comment]
the next version has mapping options in the settings menu

**Comment by slajerek** [comment]
Thanks. Is it already on master branch?

My friend Isildur/Samar ( https://csdb.dk/scener/?id=3864 ) created two 320x180 px banners, I wonder if that's something were looking for, is it acceptable for this?

![DevilutionX-320x180-banner](https://user-images.githubusercontent.com/1021783/229792552-d8d62f2e-9550-484a-801a-0532adeb3d24.png)
![DevilutionX-320x180-banner-with-frame](https://user-images.githubusercontent.com/1021783/229792566-e47999f2-a05d-4a8e-9f07-061521a2e3ba.png)

**Comment by AJenbo** [comment]
i do love the faded colors :)

**Comment by AJenbo** [comment]
![image](https://github.com/diasurgical/devilutionX/assets/204594/9430431b-6f81-4f9a-9973-cee105f68671)
