### ISSUE TITLE
[3DS] Not seeing 3DS player (and potentially other players) when hosting a server.

### ISSUE THREAD

**Issue by JetAltOne** [diasurgical/devilutionX#5252]
### Operating System

Nintendo 3DS

### DevilutionX version

1.4.1 (latest release)

### Describe

When you start hosting a server on a 3DS with TCP, You don't seem to see the 3DS player, and maybe other players i have only tested with 1 3DS and 1 PC, but it doesn't kick you out and seems to think you are connected.

I have not tried to replicate it and investigate further.

### To Reproduce

1. Start a 3DS server.
2. Connect to 3DS server.

### Expected Behavior

Seeing other players and being able to play with each other.

**Comment by DakkJaniels** [comment]
While still a problem, the 3DS manual does recommend that you host games on more capable platforms, rather than hosting on the 3DS: https://github.com/diasurgical/devilutionX/blob/master/docs/manual/platforms/3ds.md#multiplayer

Does this problem occur the other way around (host on PC, join with 3DS)?

**Comment by StephenCWills** [comment]
The first time PC attempts to connect to 3DS, it hangs at 0% in the `UiProgressDialog`, indicating that the 3DS client is not sending deltas to the PC. If the PC client cancels and attempts to join again, it skips the `UiProgressDialog` and just jumps right into the game. However, at this point, the two clients are not in the same game. The 3DS client cannot see chat messages from the PC and they don't see the same dungeon layouts. From what I've been able to tell from my brief testing, they are effectively both playing loopback.

I'm not entirely sure what's going on here, but I can say that I am unable to reproduce the issue connecting from PC to PC. If I cancel the `UiProgressDialog` before the player joins the game and then immediately rejoin, it will still wait for deltas from the remote player. Therefore, I can only reproduce this using a 3DS to host the game.

> Does this problem occur the other way around (host on PC, join with 3DS)?

No, the 3DS can join PC games just fine.

**Comment by StephenCWills** [comment]
I am unable to reproduce in master, so whatever was causing it is probably fixed already.
