### ISSUE TITLE
Debian/Ubuntu PPA building problem

### ISSUE THREAD

**Issue by muzena** [diasurgical/devilutionX#526]
@Vitexus @AJenbo 
I'm trying to build a DevilutionX in multiarch [PPA repository](https://launchpad.net/~devilutionx/+archive/ubuntu/dev).
So I made some changes in debian packaging [rules](https://github.com/muzena/devilutionX/blob/debian-packaging/Packaging/debian/rules) file:
I've added flag $(DEB_HOST_MULTIARCH) for autodetecting system arch.
amd64 compiles and generates deb's without problem, but in i386 building there is problem I don't know why, maybe is bug in cmake or something missing in CMakeLists options.
Here's i386 build [log](https://launchpadlibrarian.net/458425055/buildlog_ubuntu-bionic-i386.devilutionx_0.5.0.3+git893-c3f2834-201912311215~ubuntu18.04.1_BUILDING.txt.gz)
Problem is in $(DEB_HOST_MULTIARCH) subtitution:
Search in log for more details "obj-i686-linux-gnu" and "obj-i386-linux-gnu"
cmake sets build directory in obj-i686-linux-gnu and $(DEB_HOST_MULTIARCH) made obj-i386-linux-gnu subtitution, so after trying copy devilutionx binary from obj-i386-linux-gnu instead but build file is in obj-i686-linux-gnu.
Why cmake set build directory in obj-i686-linux-gnu instead obj-i386-linux-gnu?

**Comment by AJenbo** [comment]
no clue how that works, but it looks like you have a lot of debug dependencies
libasan5, libgcc1, libsodium23, libstdc++6, libubsan1

**Comment by muzena** [comment]
Fixes #531

**Comment by AJenbo** [comment]
By the way did you see this topic?
https://github.com/diasurgical/devilutionX/issues/387#issuecomment-570090805
