### ISSUE TITLE
Raspberry Pi4 - building from source

### ISSUE THREAD

**Issue by vliapis** [diasurgical/devilutionX#5275]
### Operating System

Linux aarch64

### DevilutionX version

1.4.1 (latest release)

### Describe

Hi, i've searched for a prebuild package of DvX and since i haven't found anything, i've tried building from source.

I build with: 
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release

then enter build directory and: 
cmake --build build -j $(getconf _NPROCESSORS_ONLN)

I get the following errors:
[ 25%] Linking CXX static library libPKWare.a
make[1]: *** [CMakeFiles/Makefile2:1977: _deps/libzt-build/CMakeFiles/zto_pic.dir/all] Error 2

[ 26%] Linking CXX static library liblibsmackerdec.a
[ 26%] Built target libsmackerdec
make: *** [Makefile:163: all] Error 2

### To Reproduce

1.

**Comment by DakkJaniels** [comment]
If you aren't using git (not clear to me how you started), the instructions say you have to supply the version number too. https://github.com/diasurgical/devilutionX/blob/master/docs/building.md

**Comment by StephenCWills** [comment]
FYI, you didn't provide any actual error messages. However, based on your architecture and the message you did provide, I'm willing to go out on a limb and assume that this might help.

https://github.com/diasurgical/devilutionX/issues/4926#issuecomment-1186338350

**Comment by vliapis** [comment]
Didn't manage to make heads or tails from troubleshooting the errors, but i managed to make it work by installing the snap package.
https://snapcraft.io/install/devilutionx/raspbian

Full instructions are displayed so all went good.

**Comment by AJenbo** [comment]
Look for `Error: ` in the build output and provide the following part of the log or we won't know what is happening.

**Comment by JanJenicek** [comment]
Same issue. I'm following [Building from Source](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md) guide for linux. Tried with release as well as repo.

```
/home/user/devilutionX/build/_deps/libzt-src/ext/ZeroTierOne/node/AES_armcrypto.cpp:272:18: note: called from here
  272 |   d0 = vaesmcq_u8(vaeseq_u8(d0, k0));
      |        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/home/user/devilutionX/build/_deps/libzt-src/ext/ZeroTierOne/node/AES_armcrypto.cpp: At top level:
cc1plus: note: unrecognized command-line option ‘-Wno-everything’ may have been intended to silence earlier diagnostics
gmake[2]: *** [_deps/libzt-build/CMakeFiles/zto_pic.dir/build.make:108: _deps/libzt-build/CMakeFiles/zto_pic.dir/ext/ZeroTierOne/node/AES_armcrypto.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
```
Full build output:
[log.txt](https://github.com/diasurgical/devilutionX/files/10460333/log.txt)

**Comment by StephenCWills** [comment]
This issue has been closed. Try following the links in the discussion and applying the proposed solutions.

**Comment by JanJenicek** [comment]
I did, but did not find the answer.

- SNAP is not an option for me. 
- [Building from Source](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md) does not cover ARM at all. (I understand that it is not supported)
- https://github.com/diasurgical/devilutionX/issues/4926#issuecomment-1186338350 leads to rabbit hole. Where if it describes how to build code from this repo for RPI4, it is beyond my skill set. As well as the builds mentioned there does not work for me on Raspberry Pi OS (64-bit).

I was actually able to surpass this error by running modified commands from: [Compiling](https://github.com/muzena/devilutionX/blob/build_arm64_aarch64_new/docs/building.md#compiling) section of Building from Source as follows.
```
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=armv8-a+crypto" -DCMAKE_C_FLAGS="-march=armv8-a+crypto"
cmake --build build -j $(getconf _NPROCESSORS_ONLN)
```
Bu there are still some warnings <details>
<summary>Click to expand</summary>
<p>
<pre>
...
[ 75%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/dvlnet/base.cpp.o
/home/janje/devilutionX/Source/DiabloUI/settingsmenu.cpp: In function ‘void devilution::{anonymous}::ItemFocused(int)’:
/home/janje/devilutionX/Source/DiabloUI/settingsmenu.cpp:163:9: warning: enumeration value ‘ListOption’ not handled in switch [-Wswitch]
  163 |  switch (shownMenu) {
      |         ^
/home/janje/devilutionX/Source/DiabloUI/settingsmenu.cpp:163:9: warning: enumeration value ‘KeyInput’ not handled in switch [-Wswitch]
/home/janje/devilutionX/Source/DiabloUI/settingsmenu.cpp:163:9: warning: enumeration value ‘PadInput’ not handled in switch [-Wswitch]
[ 75%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/dvlnet/cdwrap.cpp.o
...
[ 89%] Linking CXX executable devilutionx
In function ‘format_decimal’,
    inlined from ‘write’ at /home/janje/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:2205:28,
    inlined from ‘BufCopy’ at /home/janje/devilutionX/build/_deps/libfmt-src/include/fmt/compile.h:223:23,
    inlined from ‘DrawFPS’ at /home/janje/devilutionX/Source/utils/str_cat.hpp:63:16,
    inlined from ‘_ZN10devilution11DrawAndBlitEv.part.0’ at /home/janje/devilutionX/Source/engine/render/scrollrt.cpp:1678:9:
/home/janje/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:1178:11: warning: writing 2 bytes into a region of size 0 [-Wstringop-overflow=]
 1178 |     memcpy(dst, src, 2);
      |           ^
/home/janje/devilutionX/Source/engine/render/scrollrt.cpp: In function ‘_ZN10devilution11DrawAndBlitEv.part.0’:
/home/janje/devilutionX/Source/engine/render/scrollrt.cpp:1276:15: note: at offset -2 to object ‘buf’ with size 15 declared here
 1276 |   static char buf[15] {};
      |               ^
In function ‘format_decimal’,
    inlined from ‘write’ at /home/janje/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:2205:28,
    inlined from ‘BufCopy’ at /home/janje/devilutionX/build/_deps/libfmt-src/include/fmt/compile.h:223:23,
    inlined from ‘DrawFPS’ at /home/janje/devilutionX/Source/utils/str_cat.hpp:63:16,
    inlined from ‘_ZN10devilution11DrawAndBlitEv.part.0’ at /home/janje/devilutionX/Source/engine/render/scrollrt.cpp:1678:9:
/home/janje/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:1208:12: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 1208 |     *--out = static_cast<Char>('0' + value);
      |            ^
/home/janje/devilutionX/Source/engine/render/scrollrt.cpp: In function ‘_ZN10devilution11DrawAndBlitEv.part.0’:
/home/janje/devilutionX/Source/engine/render/scrollrt.cpp:1276:15: note: at offset -1 to object ‘buf’ with size 15 declared here
 1276 |   static char buf[15] {};
      |               ^
[ 89%] Built target libdevilutionx_so
Scanning dependencies of target test_main
[ 89%] Building CXX object test/CMakeFiles/test_main.dir/main.cpp.o
...
</pre>
</p>
</details>
 Resulting in:
<pre>
~/devilutionX $ ./build/devilutionx 
Illegal instruction
</pre>

**Comment by glebm** [comment]
> [Building from Source](https://github.com/diasurgical/devilutionX/blob/master/docs/building.md?rgh-link-date=2023-01-19T22%3A02%3A49Z) does not cover ARM at all. (I understand that it is not supported)

There is nothing special about ARM.

Do not pass `-DCMAKE_CXX_FLAGS="-march=armv8-a+crypto" -DCMAKE_C_FLAGS="-march=armv8-a+crypto"`, your CPU does not support Armv8A Cryptography Extensions.

Just use the build command in the instructions.

**Comment by glebm** [comment]
There might be an issue with the zero tier dependency on ARM, just pass `-DDISABLE_ZERO_TIER=ON`.

ZeroTier is kinda broken in that it uses the crypto extension instructions without checking if the CPU supports them on ARM.

**Comment by JanJenicek** [comment]
Thank You for clear instructions. Build was successful. I've got to the menu, did not have time to test further this morning.

Just from curiosity what is affected by disabling this option?

I can offload my sons gaming to his RPI400 now, thanks. :-)

**Comment by glebm** [comment]
> Just from curiosity what is affected by disabling this option?

Global online multiplayer via ZeroTier (games from `#games-list` on Discord)

**Comment by glebm** [comment]
@JanJenicek Can you please try building with `-DDISABLE_ZERO_TIER=OFF` from the latest master?
I believe https://github.com/diasurgical/devilutionX/pull/5691 may have fixed the underlying issue

**Comment by JanJenicek** [comment]
With last commit build works with `-DDISABLE_ZERO_TIER=OFF`. There have been some warnings see below. 
<details>
<summary>Click to expand</summary>
<p>
<pre>
...
[ 75%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/dvlnet/base.cpp.o
/home/user/devilutionX/Source/DiabloUI/settingsmenu.cpp: In function ‘void devilution::{anonymous}::ItemFocused(int)’:
/home/user/devilutionX/Source/DiabloUI/settingsmenu.cpp:163:9: warning: enumeration value ‘ListOption’ not handled in switch [-Wswitch]
  163 |  switch (shownMenu) {
      |         ^
/home/user/devilutionX/Source/DiabloUI/settingsmenu.cpp:163:9: warning: enumeration value ‘KeyInput’ not handled in switch [-Wswitch]
/home/user/devilutionX/Source/DiabloUI/settingsmenu.cpp:163:9: warning: enumeration value ‘PadInput’ not handled in switch [-Wswitch]
[ 75%] Building CXX object Source/CMakeFiles/libdevilutionx.dir/dvlnet/cdwrap.cpp.o
...
[ 89%] Linking CXX executable devilutionx
In function ‘format_decimal’,
    inlined from ‘write’ at /home/user/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:2205:28,
    inlined from ‘BufCopy’ at /home/user/devilutionX/build/_deps/libfmt-src/include/fmt/compile.h:223:23,
    inlined from ‘DrawFPS’ at /home/user/devilutionX/Source/utils/str_cat.hpp:63:16,
    inlined from ‘_ZN10devilution11DrawAndBlitEv.part.0’ at /home/user/devilutionX/Source/engine/render/scrollrt.cpp:1678:9:
/home/user/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:1178:11: warning: writing 2 bytes into a region of size 0 [-Wstringop-overflow=]
 1178 |     memcpy(dst, src, 2);
      |           ^
/home/user/devilutionX/Source/engine/render/scrollrt.cpp: In function ‘_ZN10devilution11DrawAndBlitEv.part.0’:
/home/user/devilutionX/Source/engine/render/scrollrt.cpp:1276:15: note: at offset -2 to object ‘buf’ with size 15 declared here
 1276 |   static char buf[15] {};
      |               ^
In function ‘format_decimal’,
    inlined from ‘write’ at /home/user/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:2205:28,
    inlined from ‘BufCopy’ at /home/user/devilutionX/build/_deps/libfmt-src/include/fmt/compile.h:223:23,
    inlined from ‘DrawFPS’ at /home/user/devilutionX/Source/utils/str_cat.hpp:63:16,
    inlined from ‘_ZN10devilution11DrawAndBlitEv.part.0’ at /home/user/devilutionX/Source/engine/render/scrollrt.cpp:1678:9:
/home/user/devilutionX/build/_deps/libfmt-src/include/fmt/format.h:1208:12: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
 1208 |     *--out = static_cast<Char>('0' + value);
      |            ^
/home/user/devilutionX/Source/engine/render/scrollrt.cpp: In function ‘_ZN10devilution11DrawAndBlitEv.part.0’:
/home/user/devilutionX/Source/engine/render/scrollrt.cpp:1276:15: note: at offset -1 to object ‘buf’ with size 15 declared here
 1276 |   static char buf[15] {};
      |               ^
[ 89%] Built target libdevilutionx_so
Scanning dependencies of target test_main
...
</pre>
</p>
</details>


In gameplay there are some minor issues:

- By default the mouse cursor is hidden, I guess the build is more focused to gamepads or touch screen. Gamepad works fine. When i load my linux pc config and saves mouse works flawlessly. 
- More serious issue is that casting portal from scroll results in crash wirth error: `ConsumeScroll: Invalid item index 3`
- game also freezes when gamepad is unplugged while in menu (not tested elswhere)

I did not check whether those are know issues or not. Let me know if more testing will be needed.

**Comment by AJenbo** [comment]
> I guess the build is more focused to gamepads or touch screen. Gamepad 

its not, it switches depending on what you use

> More serious issue is that casting portal from scroll results in crash with error: ConsumeScroll: Invalid item index 3

@kphoenix137

**Comment by glebm** [comment]
Thanks for testing!

> More serious issue is that casting portal from scroll results in crash with error: ConsumeScroll: Invalid item index 3

For this, can you please create an issue and attach a save file? Thanks!

**Comment by kphoenix137** [comment]
> > I guess the build is more focused to gamepads or touch screen. Gamepad
> 
> its not, it switches depending on what you use
> 
> > More serious issue is that casting portal from scroll results in crash with error: ConsumeScroll: Invalid item index 3
> 
> @kphoenix137
> 
> > Let me know if more testing will be needed.
> 
> create issues

Unable to reproduce. Tested by casting town portal from the belt, from the inventory, and from the speedbook
Tested on commit 8db52172

**Comment by JanJenicek** [comment]
I double checked first two points and can confirm that after clearing `~/.local/share/diasurgical/devilution` first run on RPI400 does not show mouse cursor. Following HW configurations have been checked:
- only build-in keyboard is attached
- keyboard and Bluetooth mouse is attached
- keyboard and USB mouse with BT disabled

in all cases no gamepad has been connected

Second issue I can reproduce only with single character when casting spell first time by right click to space. Problem disappears when scrolls are swapped with stashed ones or by casting them from inventory. I can still upload save file if it would be helpful for development, otherwise I can fix it and don't need further analysis.

**Comment by glebm** [comment]
@JanJenicek Do you perhaps have SDL_NOMOUSE=1 set in the environment?

For the second issue, please file a separate issue with a save file attached.

**Comment by JanJenicek** [comment]
System variable no. Anywhere else I should check?

**Comment by glebm** [comment]
I guess this is an issue that you can report to your OS distribution.
Perhaps their SDL2 or window manager is customized somehow.

**Comment by JanJenicek** [comment]
Ok, thank You for your support. It is great how well you all take care of this game.
