### ISSUE TITLE
"libzt" breaks the Haiku build process.

### ISSUE THREAD

**Issue by reedlove** [diasurgical/devilutionX#5281]
### Operating System

Other (please specify)

### DevilutionX version

1.4.1 (latest release)

### Describe

In file included from /boot/system/develop/headers/posix/net/if.h:9,
                 from /boot/system/develop/headers/posix/netinet/in.h:9,
                 from /boot/home/Desktop/devilutionX-1.4.1/build/_deps/libzt-src/ext/ZeroTierOne/ext/libnatpmp/getgateway.c:33:
/boot/home/Desktop/devilutionX-1.4.1/build/_deps/libzt-src/include/net/route.h:66:10: fatal error: sys/appleapiopts.h: No such file or directory
   66 | #include <sys/appleapiopts.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

### To Reproduce

Just try to compile devilutionX 1.4.1 from the source tar.gz on Haiku x64.

**Comment by StephenCWills** [comment]
Maybe we can we just remove this?
https://github.com/diasurgical/libzt/blob/37a2efb0b925df632299ef07dc78c0af5f6b4756/include/net/route.h

The only (dubious) rationale I can find for putting it there is that it's not available on iOS.
https://developer.apple.com/forums/thread/84607

**Comment by AJenbo** [comment]
It's disabled for iOS so might as well remove it:
https://github.com/diasurgical/devilutionX/blob/master/CMake/platforms/ios.cmake#L15

**Comment by AJenbo** [comment]
If you want to you can skip libzt and just have tcp multiplayer for testing by adding the cmake parameter `-DDISABLE_ZERO_TIER=ON`
