### ISSUE TITLE
Dungeon lvl loads fine on 1.4.1, but mutates on latest master

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#5297]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

This savefile is from another bug report. The tavern sign quest structure is spawning ontop of existing generation, causing strange issues like braziers to go missing and the floor color to change.
[single_1.zip](https://github.com/diasurgical/devilutionX/files/9438856/single_1.zip)

### To Reproduce

1. Load attached Savegame
2. See dungeon layout

### Expected Behavior

The level loads normally

**Comment by AJenbo** [comment]
Also a single chamber map, probably the same issue as #5299

![image](https://user-images.githubusercontent.com/204594/187515562-818a3f12-9f7a-4efa-8b8b-c54bd8c4e7a0.png)

**Comment by AJenbo** [comment]
This was indeed the same issue, snot spills room was placed out to the right instead of in the center. Going to use the other one for the fix since I better documented it. But I have confirmed both are fixed. Thanks for the report :+1:
