### ISSUE TITLE
Light data can bug out when loading at high resolutions

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#5298]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

![lji1](https://user-images.githubusercontent.com/57089001/187052478-60844ab3-f779-472a-86dc-272a5622d585.png)
[single_3.zip](https://github.com/diasurgical/devilutionX/files/9438859/single_3.zip)

### To Reproduce

1. Load attached savefile at 1600x900
2. See light where darkness should be.

**Comment by AJenbo** [comment]
From what I can tell this is caused by lighting not being calculated fare away from the player spawn position after level initialization, only once  you get closer will the lighting get calculated.

This might be related to loading lighting data from save rather then recalculating it.
