### ISSUE TITLE
Missing pillar on automap (bone chamber)

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5300]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

I suspect it could be a vanilla issue.
As you can see, a pillar is missing at the bone chamber entrance on the automap, although the pillar itself is actually there.

![pillar](https://user-images.githubusercontent.com/45902449/187073138-b116e64c-23e1-4f3f-b05a-aabaca0fa4e6.png)

### To Reproduce

The issue is always there.

### Expected Behavior

The pillar should be drawn on the automap.

### Additional context
Currently unable to upload the savegame.

**Comment by pionere** [comment]
#3522

**Comment by Chance4us** [comment]
> #3522

Thanks. Closed duplicate.
