### ISSUE TITLE
Flatpak cannot find devilutionx.mpq because app does not search its preferred path

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#5304]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

After talking to folks in Flatpak Matrix room, the reason why Flatpak cannot find devilutionx.mpq, even though it's installed into /app/share location, is because paths are hardcoded to /usr/share

https://github.com/diasurgical/devilutionX/blob/a3e94d6b558893afd6f6fcae4582a6168ab67e53/Source/init.cpp#L96-L97

From gasinvein in Flatpak Matrix room:

> The proper fix would be patching the app to search for the files in paths specified in XDG_DATA_DIRS. Or at least adding /app/... path to search list.

### To Reproduce

1. Install `flatpak` and `flatpak-builder` 
2. Install Freedesktop 21.08 runtime and SDK: `flatpak install flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08`
3. Copy https://github.com/diasurgical/devilutionX/blob/master/Packaging/nix/org.diasurgical.DevilutionX.yml to any empty writable folder and go to it in terminal
4. Build and install flatpak: `flatpak-builder --user --install build org.diasurgical.DevilutionX.yml --force-clean`
5. Launch flatpak from Start menu or run it from terminal: `flatpak run org.diasurgical.DevilutionX`

### Expected Behavior

Error dialogue is displayed to show data files are missing instead of game screen showing the error

**Comment by StephenCWills** [comment]
Did they perhaps fail to notice the paths that are not hardcoded?

https://github.com/diasurgical/devilutionX/blob/a3e94d6b558893afd6f6fcae4582a6168ab67e53/Source/init.cpp#L90-L91

https://github.com/diasurgical/devilutionX/blob/a3e94d6b558893afd6f6fcae4582a6168ab67e53/Source/init.cpp#L109

**Comment by AJenbo** [comment]
I also wouldn't say it's hardcoded since it's a list of search paths, and it can be overwritten with command line arguments.

**Comment by tsunamistate** [comment]
The problem is that `devilutionx.mpq` is installed into `/app/share/diasurgical/devilutionx` (which in case of user install is aliased to `~/.local/share/flatpak/app/<app-id>/current/active/files/share/diasurgical/devilutionx`)

Flatpak can't find `devilutionx.mpq` in share location and needs to be copied into XDG_location to work (which is where BasePath and PrefPath come in)

**Comment by AJenbo** [comment]
Either add it to the search path, or add a parameter to the startup options that specify the appropriate path for the environment.

**Comment by tsunamistate** [comment]
>Or adjust where it is copied to I guess.

Nah, file is copied to correct folder (`devilutionx.mpq` doesn't need write access after all, we don't modify it during runtime) it just can't find it

The share paths **are** hardcoded, BasePath is where executable is (bad location), PrefPath is where savefiles and ini files are saved (it works, when copied there, but folder is created only after first run, and as gasinvein said, `devilutionx.mpq` doesn't need write access), and PWD is the same as BasePath in flatpak and a bad location

I'm currently testing a patch to add `paths.emplace_back("/app/share/diasurgical/devilutionx/");`, but it's a hack. Maybe you guys will come up with a better solution?

**Comment by tsunamistate** [comment]
BTW, if you want to talk to flatpak devs: https://app.element.io/#/room/#flatpak:matrix.org

**Comment by AJenbo** [comment]
> add a parameter to the startup options that specify the appropriate path for the environment.

Or you can replace the offending section with a loop that parses XDG_DATA_DIRS, constructs the full paths and added them to the search list

**Comment by AJenbo** [comment]
> BTW, if you want to talk to flatpak devs: https://app.element.io/#/room/#flatpak:matrix.org

Thanks, but we aren't pushing to add Flatpak support.

**Comment by StephenCWills** [comment]
> I'm currently testing a patch to add `paths.emplace_back("/app/share/diasurgical/devilutionx/");`, but it's a hack. Maybe you guys will come up with a better solution?

Is this valid?

```diff
diff --git a/Packaging/nix/org.diasurgical.DevilutionX.yml b/Packaging/nix/org.diasurgical.DevilutionX.yml
index 530e1edfa..0b147508b 100644
--- a/Packaging/nix/org.diasurgical.DevilutionX.yml
+++ b/Packaging/nix/org.diasurgical.DevilutionX.yml
@@ -2,7 +2,7 @@ app-id: org.diasurgical.DevilutionX
 runtime: org.freedesktop.Platform
 runtime-version: '21.08'
 sdk: org.freedesktop.Sdk
-command: devilutionx
+command: devilutionx --data-dir /app/share/diasurgical/devilutionx
 rename-desktop-file: devilutionx.desktop
 rename-appdata-file: devilutionx.metainfo.xml
 rename-icon: devilutionx
```

https://github.com/diasurgical/devilutionX/blob/1d57a5e6e9845b5488b79e9b07ae060aff667955/Packaging/nix/org.diasurgical.DevilutionX.yml#L5

**Comment by gasinvein** [comment]
> > add a parameter to the startup options that specify the appropriate path for the environment.
> 
> Or you can replace the offending section with a loop that parses XDG_DATA_DIRS, constructs the full paths and added them to the search list

Looping over `XDG_DATA_DIRS` would be ideal, since it's the [standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) way for apps on linux to find their assets and other non-executable read-only data. As a bonus, I believe it would help NixOS and other distros packaging that don't use `/usr` install prefix.

**Comment by tsunamistate** [comment]
> Is this valid?

Unfortunately, no.
`Error: Command 'devilutionx --data-dir /app/share/diasurgical/devilutionx' not found. Use a shell wrapper for passing arguments`

> Or you can replace the offending section with a loop that parses XDG_DATA_DIRS, constructs the full paths and added them to the search list

I would if I could, I'm not a programmer :(

**Comment by StephenCWills** [comment]
> Unfortunately, no. `Error: Command 'devilutionx --data-dir /app/share/diasurgical/devilutionx' not found. Use a shell wrapper for passing arguments`

Well, maybe not that unfortunate. It sounds like everyone would prefer the `XDG_DATA_DIRS` solution.

**Comment by tsunamistate** [comment]
@glebm https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories

**Comment by glebm** [comment]
@tsunamistate That link doesn't mention `XDG_DATA_DIRS`, only `XDG_DATA_HOME`

**Comment by glebm** [comment]
On my Ubuntu system, `XDG_DATA_DIRS` is `/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`.

With #5306, I get the following MPQ search paths (non-flatpack):

     1. '/home/glebm/devilutionX/build/' (`paths::BasePath()`)
     2. '/home/glebm/.local/share/diasurgical/devilution/' (`paths::PrefPath()`)
     3. '/usr/local/share/diasurgical/devilutionx/'
     4. '/usr/share/diasurgical/devilutionx/'
     5. '/var/lib/snapd/desktop/diasurgical/devilutionx/'

**Comment by gasinvein** [comment]
> Out of curiousity, what's the actual value of `XDG_DATA_DIRS` with flatpack?

It's `/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share` inside the sandbox.

**Comment by glebm** [comment]
OK, you'll just have to make sure that the MPQ is in the `diasurgical/devilution/` subdirectory of any of these.

**Comment by gasinvein** [comment]
> OK, you'll just have to make sure that the MPQ is in the `diasurgical/devilution/` subdirectory of any of these.

I suppose it'll end up in `/app/share/diasurgical/devilution` if installed with `/app` prefix.

**Comment by AJenbo** [comment]
> I would if I could, I'm not a programmer :(

Sorry, from your commits to the android stack and other things I assumed you where :)

**Comment by tsunamistate** [comment]
Looks like flatpak still cannot find the file, unfortunately :(
Game errors out after cutscene that it can't find `diablo.pal` (Pallet file which is in` devilutionx.mpq`)

@gasinvein sorry to bother you, but could you please explain this discrepancy?

```
flatpak enter <pid> ls /app/share/diasurgical/devilutionx
README.txt  devilutionx.mpq

flatpak enter <pid> echo $XDG_DATA_DIRS
/home/<user>/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
```
So, according to `/app/share` alias, file should be accessible, but according to XDG_DATA_DIRS, share should be `~/.local/share/flatpak/exports/share` while file is installed in `~/.local/share/flatpak/app/<app-id>/current/active/files/share/`

Why this discrepancy? Should the file be installed into `<snip>/exports/share`?

**Comment by AJenbo** [comment]
Are you sure your devilutionx.mpq is up to date? The file content was change recently to optimize it's size.

**Comment by gasinvein** [comment]
@tsunamistate When running `flatpak enter ... echo` like this, you're seeing the `XDG_DATA_DIRS` from host. Run something like `flatpak run --command=printenv the.app.Id XDG_DATA_DIRS` instead to see the value inside sandbox.

> it can't find `diablo.pal` (Pallet file which is in `devilutionx.mpq`)

So it does find the `devilutionx.mpq` file, but doesn't find some content item inside it? If so, I'm afraid I can't be of much help here, since I'm not familiar with the app.

**Comment by tsunamistate** [comment]
Whelp, looks like the file is accessible

```
flatpak run --command=printenv org.diasurgical.DevilutionX XDG_DATA_DIRS
/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share

flatpak run --command=ls org.diasurgical.DevilutionX -lah /app/share/diasurgical/devilutionx
total 4.4M
drwxr-xr-x 2 tsunami tsunami 4.0K Jan  1  1970 .
drwxr-xr-x 3 tsunami tsunami 4.0K Jan  1  1970 ..
-rw-r--r-- 3 tsunami tsunami 4.3M Jan  1  1970 devilutionx.mpq
-rw-r--r-- 3 tsunami tsunami 2.4K Jan  1  1970 README.txt
```

But the game can't read it? o_O
Anyway, I'm done for the day, if anyone wants to debug this, I'm available on Discord and can screen share my environment

**Comment by glebm** [comment]
@tsunamistate the file is in the wrong location (it should be in the `diasurgical/devilution/` subdirectory). If you run devilutionx with --verbose you can see the list of MPQ search paths

**Comment by glebm** [comment]
Notice how the directory is `devilution/` whereas you have `devilutionx/`

**Comment by tsunamistate** [comment]
@glebm your patch appends diasurgical/devilutionx/
https://github.com/diasurgical/devilutionX/commit/9feb3139e2af3bc7dfcaa922f9139ee89aeb708e#diff-182d11279b04848f147542f775902a179cd6febdf67592e49e057d8ac168a97bR105

Install location is the same
```
Installing: /app/share/diasurgical/devilutionx/devilutionx.mpq
```

Also, passing --verbose show the following MPQ search paths:
```
VERBOSE: MPQ search paths:
     1. '/app/bin/'
     2. '/home/tsunami/.var/app/org.diasurgical.DevilutionX/data/diasurgical/devilution/'
     3. '/app/share/diasurgical/devilutionx/'
     4. '/usr/share/diasurgical/devilutionx/'
     5. '/usr/share/runtime/share/diasurgical/devilutionx/'
     6. '/run/host/user-share/diasurgical/devilutionx/'
     7. '/run/host/share/diasurgical/devilutionx/'
     8. ''
```
Note path 3. So the path was right all along. 😂 
Also, after VM restart, game launched with no error. Looks like the path didn't update until reboot, there are some flatpak problems like that (.desktop files show with no icons until reboot)

False alarm, everyone!
Sorry for bothering

**Comment by glebm** [comment]
I've noticed we're using `diasurgical/devilution` suffix for `XDG_DATA_HOME` but `diasurgical/devilutionx` suffix for `XDG_DATA_DIRS`. This is inconsistent and we should probably fix this.

**Comment by AJenbo** [comment]
We are not going to break installations for everyone except a subset of Linux installations where they manually transferred the MPQ files in to an undocumented folder that required admin privileges.
