### ISSUE TITLE
Incorrect US Keyboard Number Key Handling

### ISSUE THREAD

**Issue by recv5x** [diasurgical/devilutionX#532]
Issue: Pressing 2, 7, or 8 while holding down the shift key fails to drink a potion from the belt. Pressing 6 while holding down the shift key drinks a potion from slot 7. Pressing 2, 6, 7, or 8 without the shift key held down correctly drinks a potion from the corresponding belt slot. Could this be due to devilutionX either having erroneous key mapping, or incorrectly handling a US-layout keyboard when the shift key is held down? Console logs of versions compiled from source demonstrating the problem are attached below.

Testing: Tested using both the binary linux-x86_64 release of v1.0.0, by compiling release v1.0.0 from source (using sources from v1.0.0.tar.gz), and by compiling the latest git sources (using git clone). Multiple Keyboards were tested, both in the same USB port, and different USB ports. 2 different window managers were tested.

The game was tested with multiple variations of settings in diablo.ini, with "grab input" set to both 1, and 0, and with "fullscreen" set to both 1 and 0; neither of which resolved the issue.

The game was actively played for about 8 hours, and the issue persisted. The system was also rebooted multiple times, and the issue continued to persist after reboot. Otherwise, everything else, input related or otherwise, appeared to function normally.

-------------------------------------------------------------------------------

System Information
Operating System: Manjaro Linux
Architecture: x86_64
Kernel: Linux 5.3.18-1-MANJARO
Desktop Environment: XFCE 4
Window Manager: both XFWM 4 and Compiz were tested; the issue persists
Keyboard Layouts: all 104-key US QWERTY layout USB keyboards.

Source Compilation Information
    cmake version (installed via repository): 3.16.2-1
    Library Version Information (installed via repository)
        SDL2: 2.0.10-1 (version 2.0.10 stable)
        SDL2_mixer: 2.0.4-3
        SDL2_ttf: 2.0.15-1
        libsodium: 1.0.18-1
        glibc: 2.30-3
        gcc-libs: 9.2.0-4 (provides libasan and libubsan)

Console Logs
Console Log (Binary Release):
```
$ ./devilutionx 
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
```

Console Log (Source Compilation of v1.0.0.tar.gz, minus address sanitizer log); sequence of action was: 1) start a game in multiplayer using loopback; 2) hold down shift, and press 2, 6, 7, and 8 in sequence. :
```
$ ./devilutionx
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
DUMMY: TranslateMessage : char: "
DUMMY: TranslateMessage : char: &
DUMMY: TranslateMessage : char: '
DUMMY: TranslateMessage : char: (
```

Console Log (Source Compilation of latest git, minus address sanitizer log); sequence of action was: 1) start a game in multiplayer using loopback; 2) hold down shift, and press 2, 6, 7, and 8 in sequence. :
```
$ ./devilutionx
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
DUMMY: TranslateMessage : char: "
DUMMY: TranslateMessage : char: &
DUMMY: TranslateMessage : char: '
DUMMY: TranslateMessage : char: (
```

**Comment by AJenbo** [comment]
Everyone who worked on the input code are from the EU so this matches how the game has always worked for us, so we had mistakenly made it dynamically behave in this way for all keyboards. It's frustrating how many games are hardcoded to a US layout, but at least now you know the frustration it brings :D

The fix for this is a bit of a trade-off as it fixes the behavior for all keyboards, but makes it hard to write chat messages on non-US keyboards. At some point, we should remove the abstraction and make the engine not assume a US-layout.
