### ISSUE TITLE
Fedora: game doesn't launch

### ISSUE THREAD

**Issue by shawnmuzick** [diasurgical/devilutionX#5329]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

AppImage fails to recgonize diabdat.mpq in the same folder. 

Running the installer from the [devilutionx-linux-x86_64.tar.xz] release throws the error "nothing provides libbz2.so.1.0()(64 bit) needed by devilutionx-1.4.1-1.x86_64. 

I am using Fedora 36. I was able to successfully install the game in a windows vm from my cd, so the original game source files are correct.

### To Reproduce

App image:
-Copy the appImage and diabdat.mpq to the same folder
-run the appImage

Tar
-Download the tarball
-Extract the files
-run the devilutionx.rpm installer

### Expected Behavior

The installer should run

**Comment by AJenbo** [comment]
Have you installed libbz2?

**Comment by StephenCWills** [comment]
It seems that the `bzip2-libs` package has the library you need, but it assumes the names `libbz2.so.1` and `libbz2.so.1.0.8`.
https://packages.fedoraproject.org/pkgs/bzip2/bzip2-libs/fedora-36.html#files

You'll probably need to make a symlink for yourself with `sudo ln -sT libbz2.so.1.0.8 /usr/lib/libbz2.so.1.0`.
https://www.reddit.com/r/Fedora/comments/htfg0n/steam_libbz2so10_missing_on_fedora_32/

I don't really know where the appimage expects to find diabdat.mpq.

**Comment by AJenbo** [comment]
The appimage located the MPQ in cwd with out issues

```
ajenbo@L4:~$ ./devilutionx-linux-x86_64.appimage --verbose
VERBOSE: MPQ search paths:
     1. '/tmp/.mount_deviluKnbVNE/usr/bin/'
     2. '/home/ajenbo/.local/share/diasurgical/devilution/'
     3. '/usr/share/diasurgical/devilutionx/'
     4. '/usr/local/share/diasurgical/devilutionx/'
     5. ''
VERBOSE:   Found: diabdat.mpq in 
```

Maybe you are calling it from a different path then where it is located.

**Comment by AJenbo** [comment]
> No, it's not mentioned in the installation instructions.

Try working with us here.

**Comment by shawnmuzick** [comment]
![Screenshot from 2022-09-05 15-46-20](https://user-images.githubusercontent.com/55474353/188506786-64835f6c-99d3-41e5-86a4-2e7f9ac162cc.png)
They're both in the same folder, terminal window is running from that folder.

**Comment by StephenCWills** [comment]
Hm, it says it found it, but that it's unable to open it. Could it be a permissions issue?

**Comment by shawnmuzick** [comment]
![Screenshot from 2022-09-05 16-00-46](https://user-images.githubusercontent.com/55474353/188507754-39d9c88b-5656-41d0-8214-f111ccdb365e.png)
Permissions should be fine, I'd think. Set to 777 to try to force it, still fails with the same error.

**Comment by StephenCWills** [comment]
My best recommendation then is to try running `md5sum diabdat.mpq` to see if maybe the MPQ data is corrupt. It should come up with either `011bc6518e6166206231080a4440b373` or `68f049866b44688a7af65ba766bef75a`.

**Comment by AJenbo** [comment]
maybe fedora is applying additional isolation

**Comment by AJenbo** [comment]
Have you checked with other versions. Can you please try the 3 ohter mentioned search paths.

**Comment by shawnmuzick** [comment]
> My best recommendation then is to try running `md5sum diabdat.mpq` to see if maybe the MPQ data is corrupt. It should come up with either `011bc6518e6166206231080a4440b373` or `68f049866b44688a7af65ba766bef75a`.

Interesting, I got: 0fd176d2b99b004cd7ea732565854899. 
I re-copied it off the CD, got the same result. It works fine on my windows install, so it shouldn't be a bad disk or anything.

**Comment by AJenbo** [comment]
A damaged mpq could definitely explain the error after it locates the file.

Can you please try the shareware file instead (spawn.mpq). If that works you could overwrite the broken content with the files from the shareware.

**Comment by shawnmuzick** [comment]
Turns out it was a bad data file. I don't understand how since I copied it directly off of my retail CD, but was able to launch it from another copy of the data file that I got elsewhere.
