### ISSUE TITLE
Golem can drop items when killed by Na-Krul

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5340]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

Golem can drop items when killed by Na-Krul.
In my last game, my first golem was killed by Na-Krul and dropped a magic ring.
After that my second golem killed Na-Krul and I immediately returned to town.
After I returned to the crypt, a duplicate of the same ring fell on the floor at the back of the Na-Krul chamber.
I suspect that it is a duped item.

### To Reproduce

The issue will probably be difficult to reproduce, or at least time consuming.
From the process you have to be able to cast a golem to let it to be killed,
and then there would be an uncertain chance that some item would be dropped.

### Expected Behavior

It doesn't seem useful when golem drops items, so this feature should be removed.

### Additional context

It's unclear if golem can drop items in general or if it only happens on kills by Na-Krul.

**Comment by qndel** [comment]
Probably related to this line https://github.com/diasurgical/devilutionX/blob/master/Source/monster.cpp#L4627 and broken by turn players into vector commit

**Comment by Chance4us** [comment]
> 

I use master with commit e348fa3b1e4ef50955a9d9a023243b560402ff21

**Comment by qndel** [comment]
ye that's definitely it then
