### ISSUE TITLE
dungeon graphic quality is not high quality

### ISSUE THREAD

**Issue by muziling** [diasurgical/devilutionX#5344]
Change config file:

> [Graphics]
Width=1280
Height=960

Go to dungeon , graphic  quality   is still low.  
Low is compare with Belzebub diablo mod.
Hope can merge Belzebub‘s diablo mod.

![image](https://user-images.githubusercontent.com/1459795/190144749-04da4c03-4b5a-4b82-ad13-de9563ea1c52.png)
![image](https://user-images.githubusercontent.com/1459795/190144772-61ab606c-318b-4b63-a4af-ee0933219943.png)

**Comment by AJenbo** [comment]
Belzebub uses a different engine and different lighting, it's to possible to use it or it's lighting. But it also does not appear to apply the correct falloff.

The original engine only has 8bit lighting tile aligned lighting. But you also appear to be applying some harsh gamma setting that make it looks much worse:
![image](https://user-images.githubusercontent.com/204594/190148369-2e4f8d37-48e3-41f7-a80b-1d0108731943.png)

**Comment by julealgon** [comment]
Funny this one... I think Belzebub looks totally washed out compared to the original lighting.

Also cranking up the gamma for no reason and not using integer scaling to keep zoom levels the same makes the comparison above completely irrelevant.
