### ISSUE TITLE
not working music when creating or choosing character in devilutionX

### ISSUE THREAD

**Issue by Gadaften** [diasurgical/devilutionX#535]
Little bug but very important who like old experience.

**Comment by qndel** [comment]
well, then you should be happy because you are actually gettiing the "old experience" - there was no sound during character creation in original diablo, gog's version patched that out, but your point is invalid ;)

**Comment by AJenbo** [comment]
The music did not play during character selection in the original Diablo, this is one of the two changes that where done to the GOG release. Supposedly for better Windows 10 comparability.

Original 1.09:
https://youtu.be/55h1zezhKcs?t=311

GOG:
https://youtu.be/1TlRhc7ohws?t=198

**Comment by Gadaften** [comment]
Sorry that was my bad. I played a lot with gog version;)

**Comment by AJenbo** [comment]
No worries :)
