### ISSUE TITLE
Config dir needs a way to specify data dir

### ISSUE THREAD

**Issue by DuendeInexistente** [diasurgical/devilutionX#5355]
Title says it all. Would be good if I could specify the data/diablo.mpq in the config dir to avoid having to fiddle with direct links or launch scripts.

**Comment by AJenbo** [comment]
> Title says it all
How can a dir specify a dir?

use `--data-dir`

**Comment by DuendeInexistente** [comment]
> > Title says it all
> 
> How can a dir specify a dir?
> 
> use `--data-dir`

Mistyped, I meant the config file.
