### ISSUE TITLE
Crash when rendering invalid objects loaded from savegame

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#5360]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

4cff046ba946859fca1d9e4cb07df950f9773928 on Debian Sid, nVidia closed driver

### To Reproduce

* Start game
* Load savegame

### Expected Behavior

Play game

### Additional context

I'm guessing it's related to https://github.com/diasurgical/devilutionX/pull/4931

There are 2 ways to trigger the bug:
* .INI has `Zoom=1` load the save game, then press Z (to zoom)
* .INI has `Zoom=0` load the save game, crashes right away

```
CRITICAL: Unable to find object_graphic_id 7 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 7 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 7 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 5 in list of objects to load, level generation error.
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
ERROR: Eroare
assertion failed (Source/engine/clx_sprite.hpp:130)
spriteIndex < numSprites()
```

**Comment by AJenbo** [comment]
from the log it sounds more like the issue is an object not being loaded and failing to render, nothing actually related ti zoom, also its failing on a debug assert and not actually crashing

**Comment by AJenbo** [comment]
what level is the save on, how was it created?

**Comment by licaon-kter** [comment]
It's an old save that I use for random testing, will upload it asap.

**Comment by licaon-kter** [comment]
Attached savegame:
[a.zip](https://github.com/diasurgical/devilutionX/files/9638985/a.zip)

**Comment by StephenCWills** [comment]
I added a bit of logging and got these messages.

```
DEBUG: OBJ_SKFIRE (29,33)
CRITICAL: Unable to find object_graphic_id 7 in list of objects to load, level generation error.
DEBUG: OBJ_SKELBOOK (29,31)
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
DEBUG: OBJ_SKELBOOK (29,35)
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
DEBUG: OBJ_SKFIRE (29,39)
CRITICAL: Unable to find object_graphic_id 7 in list of objects to load, level generation error.
DEBUG: OBJ_SKELBOOK (29,37)
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
DEBUG: OBJ_SKELBOOK (29,41)
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
DEBUG: OBJ_SKFIRE (89,71)
CRITICAL: Unable to find object_graphic_id 7 in list of objects to load, level generation error.
DEBUG: OBJ_BANNERR (90,70)
CRITICAL: Unable to find object_graphic_id 5 in list of objects to load, level generation error.
DEBUG: OBJ_SKELBOOK (89,69)
CRITICAL: Unable to find object_graphic_id 13 in list of objects to load, level generation error.
```

@licaon-kter, the object must be visible from the character's position in the savegame at your resolution. At 640x480, it doesn't crash unless I walk north. It seems that the crash occurs because one of these objects is just north of the player.

Level seed is `1701434666`. Regenerating the level from the same seed doesn't produce these errors. There doesn't seem to be any rhyme or reason to it either. After regenerating the level, here's what I found at each of the locations that were logged.

(29,33) Zombie
(29,31) Zombie
(29,35) Empty
(29,39) Fallen One
(29,37) Empty
(29,41) Empty
(89,71) Burning cross
(90,70) Empty
(89,69) Empty

**Comment by licaon-kter** [comment]
Do I need to test anything or?
