### ISSUE TITLE
"Print Screen" hotkey has issues

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#537]
I'm on Windows 10. Pressing "Print Screen" on the keyboard saves screenshots in some ancient "PCX" format. If you spam the key quickly, you get a disk space error message and the screen colors glitch out.

Seems like there are multiple issues here. Format should probably be updated to PNG, hitting the key too fast shouldn't trigger HD space errors, and the colors shouldn't glitch after an error message.

**Comment by AJenbo** [comment]
1 issue per per ... issue, please.

png vs pcx is opinion / feature request. png support would add additional dependencies. BMP and PCX can be handled by the engine/sdl already, pcx is more efficient then bmp.

What did the error message say? We need the exact text to trace down the issue.

**Comment by qndel** [comment]
@AJenbo we don't need anything, it's the exact same issue that I've reported months ago :P

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/71856040-f89cf700-30e2-11ea-972a-140ab50c208c.png)
then after closing the error you get "happy" diablo
![image](https://user-images.githubusercontent.com/14297035/71856063-09e60380-30e3-11ea-82c6-3711c1499a8c.png)

**Comment by jefetienne** [comment]
I can confirm that I am also getting the same issue as qndel.

**Comment by FitzRoyX** [comment]
> png vs pcx is opinion / feature request. png support would add additional dependencies. BMP and PCX can be handled by the engine/sdl already, pcx is more efficient then bmp.

Sorry, I've never heard of PCX before. Wikipedia says it's deprecated and neither Chrome, Firefox, or my file manager will display them. I only suggested PNG because it's so widely supported and used on the web. Same quality as BMP at 1/4 the size.

**Comment by AJenbo** [comment]
PCX is on of the first standardized image formats, on Windows you can use https://www.irfanview.com/ to view them. On Linux I just use GIMP.

**Comment by AJenbo** [comment]
This issue should now be fixed

**Comment by qndel** [comment]
I'll be happy to test ;)
