### ISSUE TITLE
Strange message on TTY console: "INFO: Removed file: /root/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo"

### ISSUE THREAD

**Issue by vanfanel** [diasurgical/devilutionX#5372]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Using latest/current GIT code, which is commit 7ad5a4590508b8388312f0454516a7c294c91cec,
I get that strange message on the TTY console where I run the engine from:
`INFO: Removed file: /root/.local/share/diasurgical/devilution/Diablo1ReadOnlyTest.foo`

What does that mean and how can I prevent that strange file from being created and deleted?
Thanks!

### To Reproduce

1. Run the engine normally
2. Watch the TTY

### Expected Behavior

No strange files are created and deleted for testing purposes, I guess

**Comment by StephenCWills** [comment]
It's just testing to make sure it has write permissions to the pref path. If it doesn't have write permissions, the game can't persist settings to diablo.ini.

https://github.com/diasurgical/devilutionX/blob/7ad5a4590508b8388312f0454516a7c294c91cec/Source/restrict.cpp#L15-L25

If you want to remove that logic, it's called from diablo.cpp at startup.

https://github.com/diasurgical/devilutionX/blob/7ad5a4590508b8388312f0454516a7c294c91cec/Source/diablo.cpp#L1011
