### ISSUE TITLE
App title and minor bug.

### ISSUE THREAD

**Issue by Winterwolf9729** [diasurgical/devilutionX#5378]
### Discussed in https://github.com/diasurgical/devilutionX/discussions/5377

<div type='discussions-op-text'>

<sup>Originally posted by **Winterwolf9729** September 26, 2022</sup>
Hi, I have two suggestions for improvements for the app. First, I think that it would be better off simply being titled "Diablo" if that's legal because that would help to reinforce the sensation that you're playing the actual game rather than on an emulator.

Second, and more importantly, it looks to me like the game is still dealing with minor issues. All I've encountered so far is some inaccurate reporting on the number of monsters I've killed and some slight issues with control responsiveness, but I'll keep an eye out for anything else so that the app can be the best it can.</div>

**Comment by AJenbo** [comment]
Please only report concrete issues, and not multiple ones in the same report.

**Comment by Winterwolf9729** [comment]
> Please only report concrete issues, and not multiple ones in the same report.

Sorry. I didn't know there were rules.

**Comment by AJenbo** [comment]
Did you lower your App review to 2 stars because of this? Maybe you didn't see the reply on the discussion page, we still need more info from you before we will know what the issues your are reporting are caused by.

**Comment by Winterwolf9729** [comment]
I'm sorry, I'm not trying to be offensive or anything, I guess I just don't
understand how this whole system works.

At the moment, what I care about the most is a title change. The bug I
reported isn't even showing up at the moment. I honestly would prefer that
the app is just called Diablo—maybe I'm weird but that's how I feel.
If it's not possible, that's okay since the game is still awesome, but at
the very least, I would like some answers, please.

**Comment by AJenbo** [comment]
Please read the reply in the discussion where I have given you some answers: https://github.com/diasurgical/devilutionX/discussions/5377

**Comment by AJenbo** [comment]
For one thing the Diablo name is trademarked by Blizzard. We are not associated with them in any way.

**Comment by Winterwolf9729** [comment]
Alright. I'll do that. Thank you.

**Comment by Winterwolf9729** [comment]
Okay. I understand.

Thanks for the letting me know. I'll adjust my review accordingly because
getting to play Diablo on my phone is an awesome experience.

**Comment by Winterwolf9729** [comment]
And thanks for being so patient with me and my inexperience, too.
