### ISSUE TITLE
Ability to pause multiplayer games

### ISSUE THREAD

**Issue by martinvonwittich** [diasurgical/devilutionX#538]
I tend to play multiplayer games without actually having other people in my game (so I might use the character later on in a proper multiplayer game), and sometimes I miss the ability to pause the game. It would be nice if it would be possible to pause multiplayer games if there's only one player in the game (for example by pressing the P button).

Possibly this would even be useful for private multiplayer games with trusted friends?

**Comment by AJenbo** [comment]
i could maybe see this work if the game only has 1 player, and then unpause if someone joins, but there is a down side to that if your afk. Also i don't know if it will let you join in that case. will think about it

**Comment by khanduras** [comment]
In other multiplayer games (OpenRA for example) it pauses the game for everyone. Is this possible if we can't pause for 1?

**Comment by predator8bit** [comment]
With multiple people, there could be a voting command in chat to agree to- or prevent the game pause

**Comment by qndel** [comment]
isn't that an overkill?  You want a pause, just go to town, then you can afk all you want xD

**Comment by AJenbo** [comment]
agreed, its not something we will be looking into for now

**Comment by martinvonwittich** [comment]
Thanks for looking into it, anyway :)

**Comment by kraileth** [comment]
Just adding another thought on this: There were some old games (wasn't it even WarCraft II?) where you could pause in multiplayer - but every other player could unpause. I think this is a pretty simple way of dealing with it. If you're playing with close friends (most likely in case of Diablo I today, I guess), they will probably respect your pause.

What about something like this? Certainly less complex than a voting system or having to check how many people are in the game. Another might be to allow pause in games played over loopback.

**Comment by AJenbo** [comment]
Checking if you are only playing with close friends is a lot harder then checking if you are the only player :)

If someone sends an elegant solution for this we might merge it, but this isn't something the core team probably be working on.
