### ISSUE TITLE
Reflect can be turned off on some hits randomly

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5384]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID) -> does not matter

### Describe

Reflect can be turned off seemingly randomly on some hits.

### To Reproduce

Get hit often.

### Expected Behavior

It is illogical that reflect is sometimes turned off. Should not happen.

### Additional context

It is also a vanilla issue, see the following animation.
The same thing happens in devilutionx.
Savegame:
[Uploading reflect_test.zip…]()

Vanilla behaviour:

![reflect](https://user-images.githubusercontent.com/45902449/193423086-41e9d8b1-ef1f-4ffb-ae6b-6ad17419b812.gif)

**Comment by StephenCWills** [comment]
This is just how the spell was designed to work. Each time you cast Reflect, it adds `slvl * clvl` "reflections" to your counter. If you get hit that number of times while Reflect is active, it will wear off. FYI, the number of reflections stacks each time you cast the spell, so you can refresh it periodically before the spell wears off and it wont necessarily "waste" any reflections.

**Comment by Chance4us** [comment]
Thanks, I didn't know that, the thing is somehow not self-explanatory.

**Comment by Chance4us** [comment]
I've been thinking about this non-intuitive fact.
What do you think about giving the reflect sign a counter with the number of reflections left @StephenCWills?

**Comment by StephenCWills** [comment]
I'd rather not use it myself, but I wouldn't really mind having the option for those who enjoy seeing numbers everywhere. #4580

**Comment by Chance4us** [comment]
I understand that not everyone likes numbers.
What would you think of a solution like this https://github.com/diasurgical/devilutionX/pull/1299
or something similar that makes the reflect sign turn red in some way?

**Comment by AJenbo** [comment]
The problem with that is that there is no known total

**Comment by Chance4us** [comment]
I understand. I'm not that good at programming so I hope you have a little patience.
Nevertheless i try the best in my context.
Thank you for your contribution.
