### ISSUE TITLE
Potions can only be collected after multiple clicks

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5385]
### Operating System

Linux x64

### DevilutionX version

Custom build (commit 7ad5a4590508b8388312f0454516a7c294c91cec)

### Describe

Potions can only be collected after multiple clicks.

Background:
Collected useless healing potions in the game for a long time, with the purpose of turning them into rejuvenation potions at a later date. An "Eldritch Shrine" in level 7 (as far as I can remember) was used for the conversion.
The transformed potions were then left in the town for later use.
After playing some more and returning to the town, the affected potions could only be picked up after repeated clicks, about 13-14 times.

### To Reproduce

It can probably be reproduced something like this and unfortunately somewhat lengthy. As a prerequisite you need a game with an existing Eldritch Shrine. Then have some potions transformed and left in town. Try to collect the potions later in the game.

### Expected Behavior

The potions should be collected on the first click.

### Additional context

1. The issue has not occurred before.
2. It's unclear since which commit the issue started.
3. The affected potions also behave the same way in vanilla.
4. Furthermore, there is the possibility that these are duped items.
5. It's unclear if a random shrine has the same effect.
6. It is unclear if a Divine Shrine is capable of similar behavior and producing similarly flawed potions.
7. It needs to be studied in the longer term.

Savegame:
[potions.zip](https://github.com/diasurgical/devilutionX/files/9690984/potions.zip)

https://user-images.githubusercontent.com/45902449/193424317-f06757ab-cfb4-4bf0-8835-2d9036192b30.mp4

**Comment by StephenCWills** [comment]
It's tripping the logic in `GetItemRecord()`. The way Eldritch Shrine spawns these, the item records for these potions are all identical.

https://github.com/diasurgical/devilutionX/blob/4015dc186a27d27ebc8f385acc2424fed6b73802/Source/items.cpp#L4343-L4358

It used to be that the seeds Eldritch-spawned rejuvenation potions were generated randomly, but that logic was removed by 2d2362d.
