### ISSUE TITLE
Unable to compile libsodium statically

### ISSUE THREAD

**Issue by ImanolBarba** [diasurgical/devilutionX#5392]
Hiya!

I'm trying to create a build of devilutionX with the least amount of dependencies possible, as I'm crosscompiling against an embedded device that has no way of having libsodium installed in the system.

In Issue #117 it is mentioned that using the BINARY_RELEASE CMake flag will produce a build that links everything statically except SDL2 and libc. Fortunately, these libraries are present in the target system.

In https://github.com/diasurgical/devilutionX/commit/66beceba59dcb805f5418036877ae3a2133180e5, this build flag was removed with no explanation, and judging vaguely from the code, I assumed that 

```
-DCMAKE_BUILD_TYPE=Release -DCPACK=ON
```

Would produce the same result.

I have tried to build with those flags, but libsodium is still linked dynamically:
```
 objdump -p devilutionx | grep NEEDED
  NEEDED               libz.so.1
  NEEDED               libbz2.so.1.0
  NEEDED               libsodium.so.23
  NEEDED               libSDL2-2.0.so.0
  NEEDED               libm.so.6
  NEEDED               libpthread.so.0
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
```

Any idea on how to compile libsodium statically?

Thanks!

**Comment by ImanolBarba** [comment]
For the record, I also tried:

```
cmake -DCMAKE_BUILD_TYPE=Release -DCPACK=ON -DDEVILUTIONX_STATIC_LIBSODIUM=on  ..
```

And got:
```
[...]
[ 91%] Linking CXX shared library liblibdevilutionx_so.so
[ 91%] Building CXX object CMakeFiles/devilutionx.dir/Source/main.cpp.o
[ 91%] Linking CXX executable devilutionx
[ 91%] Built target devilutionx
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libsodium.a(libsodium_la-randombytes.o): warning: relocation against `randombytes_sysrandom_implementation' in read-only section `.text'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libsodium.a(libsodium_la-randombytes.o): relocation R_X86_64_PC32 against symbol `randombytes_sysrandom_implementation' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/libdevilutionx_so.dir/build.make:429: test/liblibdevilutionx_so.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:3704: test/CMakeFiles/libdevilutionx_so.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by AJenbo** [comment]
> In https://github.com/diasurgical/devilutionX/commit/66beceba59dcb805f5418036877ae3a2133180e5, this build flag was removed with no explanation, and judging vaguely from the code, I assumed that

Because it was replaced by `DEVILUTIONX_STATIC_*` and better auto detection. Which happened over a period ot time prior to the removal it self.

Your libsodium must be build correctly:
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libsodium.a(libsodium_la-randombytes.o): relocation R_X86_64_PC32 against symbol `randombytes_sysrandom_implementation' can not be used when making a shared object; recompile with -fPIC
```

Is your embeded system really an x86_64 arch?

**Comment by StephenCWills** [comment]
> In [66beceb](https://github.com/diasurgical/devilutionX/commit/66beceba59dcb805f5418036877ae3a2133180e5), this build flag was removed with no explanation...

You can follow the link to the PR, which links to the discussion that led to its removal. https://github.com/diasurgical/devilutionX/issues/225#issuecomment-963406590

> For the record, I also tried:
> 
> ```
> cmake -DCMAKE_BUILD_TYPE=Release -DCPACK=ON -DDEVILUTIONX_STATIC_LIBSODIUM=on  ..
> ```

You're close with that one. FYI, `CPACK` is for building the deb/rpm/appimage so you may not need it for your platform. Here are a few options you can try.

---

If you want to have libsodium compiled statically for the platform, use...

```
cmake -DCMAKE_BUILD_TYPE=Release -DEVILUTIONX_SYSTEM_LIBSODIUM=OFF  ..
```

---

If you want to build with TCP and/or ZeroTier support but without encryption (to remove the dependency on libsodium), you can use this one.

```
cmake -DCMAKE_BUILD_TYPE=Release -PACKET_ENCRYPTION=OFF  ..
```

---

If you want to build without TCP or ZeroTier (removing libsodium, libzt, and asio dependencies), try this one.

```
cmake -DCMAKE_BUILD_TYPE=Release -NONET=ON  ..
```

**Comment by ImanolBarba** [comment]
Yes, my system (Both the target and the one I'm using to build) are x86_64, don't know what the error means too much sorry

The system libsodium looks promising! if I tweak that off and use the builtin one I don't think I'll have issues. Gonna try that!

**Comment by ImanolBarba** [comment]
Yes! `-DDEVILUTIONX_SYSTEM_LIBSODIUM=OFF` did the trick!

Thank you very much!

Feel free to close the issue (unless y'all wanna follow up on the linking error)
