### ISSUE TITLE
Controller: Add Accept and Cancel buttons swap in settings

### ISSUE THREAD

**Issue by rlach** [diasurgical/devilutionX#5393]
Currently the controller setup uses Nintendo button layout where A button(accept) is on right, and B button(cancel) is on bottom. This is fine on Nintendo platforms, and not fine on most other platforms/controllers.

Western Playstation has X button(accept) on the bottom, and Circle button(cancel) on the right(recently that is true even in Japan). Xbox has A button(accept) on the bottom, while B button(cancel) on the right. Xbox controller is also most commonly used setup for PC controllers, and even steam input uses this setup by default.

Having the accept/cancel swapped from regular setup leads to many user mistakes, like pressing A(accept), but it being B(cancel) shuts down the whole game without a warning. After playing for some time it's hard to say what to press to save the game etc. It makes it confusing to operate game overlay, if the platform has one.

This can't be easily fixed with just swapping the buttons on console level, since the location of the button is used to operate right-hand menu you can see while holding start/select. It needs to be in-game setting to work properly.

Currently it can be changed with Mapping= section in .ini file, but it is very hard to fill in, especially on non-windows platforms. It requires to use another tool, with exactly the same .dll version as used by devilutionX, and most users won't be able to do it.

The setting can be a simple toggle under Controls section of the in-game settings.

**Comment by AJenbo** [comment]
We are working to make it mappable so you can set it up any way you like.
