### ISSUE TITLE
Rune of Fire is useless

### ISSUE THREAD

**Issue by Winterwolf9729** [diasurgical/devilutionX#5398]
### Operating System

Android

### DevilutionX version

1.4.1 (latest release)

### Describe

I have started playing Hellfire, and when I tried to use some runes of fire for the first time, I couldn't. Basically, I activated them in my inventory, but when I tried to click on a space in the dungeon to place the trap, nothing happened. Further investigation revealed that the cursor can't even move outside of the inventory window when the rune is activated and is ready to be placed in the dungeon. Because of this, runes of fire—and presumably all other trap items—cannot be deployed at all.

### To Reproduce

1. Play Hellfire. (Item does not exist in Diablo)
2. Open inventory.
3. Tap on any rune of fire in inventory.
4. Tap on "cast spell" button.
5. When cursor appears, attempt to move it outside of the inventory window and place the trap in the dungeon.

### Expected Behavior

I expected to be able to deploy the trap by activating the rune and then tapping on the screen where I wanted to place it.

**Comment by AJenbo** [comment]
Known issue, interface is being worked on

**Comment by Winterwolf9729** [comment]
Good to know. Thanks.

**Comment by Winterwolf9729** [comment]
Can I still report on the monster kill count bug even though it's minor?

**Comment by AJenbo** [comment]
Yes, but if it's the issue with it resetting between each session then it's a known issue and there are already proposed PRs for it.

**Comment by AJenbo** [comment]
the behaviour depends on if you are playing multiplayer, single player, an how you start a session

**Comment by Winterwolf9729** [comment]
Yeah, I'm playing Single Player right now. I've also noticed that I haven't
faced any new varieties of enemies so far in Hellfire. Was there like a
file specifically holding them that I should have downloaded into the app?

**Comment by AJenbo** [comment]
The Hellfire monsters recide in the new levels (crypt and hive) which are accessed from town by talking to the farmer.

**Comment by Winterwolf9729** [comment]
I see, that makes sense.

Last question: does the diasurgical team have any plans to port any other
old Blizzard ganes to mobile devices? Warcraft 2 and its expansion pack in
particular are what I and no doubt many other fans would love to play.

**Comment by glebm** [comment]
> does the diasurgical team have any plans to port any other old Blizzard ganes to mobile devices?

No

>  Warcraft 2 and its expansion pack in particular are what I and no doubt many other fans would love to play.

Wargus can do this and has an Android port https://play.google.com/store/apps/details?id=com.drodin.stratagus&hl=en&gl=US
https://stratagus.com/

**Comment by Winterwolf9729** [comment]
Alright, thank you.
