### ISSUE TITLE
[Virtual Gamepad] Button texture exceeds size limitation on Motorola Droid 4

### ISSUE THREAD

**Issue by buzztiaan** [diasurgical/devilutionX#5403]
### Operating System

Other (please specify)

### DevilutionX version

Custom build (please specify commit ID)

### Describe

On a Maemo Leste phone (the Motorola Droid 4) i have compiled the current git version ( 22adb0a93f1ad53b4fb064ff45a203ce822b8fa7 )

Everything seems perfectly functional! I think we could even use it without touch controls (as we have a full qwerty keyboard) , but i cant see/find any option to disable this. Fine by me :)

BUT , the issue is that half the touchscreen controls seem to not be displayed or functional? I was expecting action buttons on the right, but none get displayed and touching that part of screen doesn't seem to do anything.

### To Reproduce

Just run it on a 960x540 display fullscreen. See below for a screenshot (this is after touching on the left and right, where the touch inputs should be afaik)

### Expected Behavior

I was hoping to see and use the buttons :)

### Additional context

![Uploading image.png…]()

Trying to package this up for maemo-leste today, but figured this -might- be a blocking issue ;)

**Comment by buzztiaan** [comment]
Uploaded screenshot again, not sure where it went : 

![image](https://user-images.githubusercontent.com/940336/194759345-8640e398-a3ef-4ad4-8f1f-ca490c96228a.png)

**Comment by buzztiaan** [comment]
To be specific , the -movement- touch input on the left is working , the -action- inputs on the right are not.

**Comment by AJenbo** [comment]
does it work if you change the resolution?
what dpi is the device reporting?

**Comment by buzztiaan** [comment]
I'm not sure where i'd read a dpi report (xrandr doesnt tell me?) 
But , it should be 275 pixels per inch, give or take

By change the resolution, you mean editting diablo.ini to force 640x480 or something? I can try

**Comment by StephenCWills** [comment]
It appears to me like you're missing the graphics for the buttons under the potions. Maybe your build is somehow simply missing some of the assets?

When you attempt to test the buttons that you are unable to see, you should make sure there is an action bound to it. For instance, in the screenshot you provided, the only button that would actually do anything is the left one, which triggers the repair skill and opens the inventory. That button would likely be pretty close to the INV button, which could cause confusion as well.

**Comment by buzztiaan** [comment]
I just disabled 'fit to screen' , set 640x480 , left upscale enabled  (with upscale disabled i get nothing rendered to screen??)

Sadly, the same issue happens, touchcursor for movement is displayed and functional, the action buttons on the right arent displayed.

The 'assets/ui_art/*' files are there , i'm not sure i would have to do anything special for those?

**Comment by DakkJaniels** [comment]
Could be because master branch is being used, rather than release? Doesn't master branch require a different devilutionx.mpq?

**Comment by StephenCWills** [comment]
There is no devilutionx.mpq on Android.

**Comment by buzztiaan** [comment]
This isn't running android though, it's maemo leste (basically devuan beowulf with mainline-ish kernel)

**Comment by DakkJaniels** [comment]
Does it load the different assets required automatically?

**Comment by buzztiaan** [comment]
Oh, i just noticed , i don't have any devilutionx.mpq at all

**Comment by StephenCWills** [comment]
> This isn't running Android though, it's Maemo Leste (basically Devuan Beowulf with mainline-ish kernel)

Ah, I assumed you were running LineageOS. If you're using Linux, it's a different story, though I still couldn't tell you why the joystick and menu graphics work when the others don't. If you don't have smpq, the build is supposed to copy the files over to an `assets` folder under the build directory. I'd assume that's where the assets are being loaded from.

Maybe you can try running the game from the terminal using the `--verbose` flag to get more information on where assets are being loaded from and which ones might be missing.

**Comment by AJenbo** [comment]
> with upscale disabled i get nothing rendered to screen

Maybe your system doesn't support software blitting?

**Comment by buzztiaan** [comment]
> Maybe your system doesn't support software blitting?

Likely, the video driver is in flux quite hard. Not very important for the issue at hand though :) See the log, there's many weird things about the video output , i think ;)

> Maybe you can try running the game from the terminal using the `--verbose` flag to get more information on where assets are being loaded from and which ones might be missing.

Here's the stderr from a --verbose session ; https://space.nurdspace.nl/~buzz/devilutionXverbose.log

I do see missing devilutionX.mpq but no messages about it missing any assets? (that i can see)
In the mentioned assets folder i have all the right stuff, afaik... 

![image](https://user-images.githubusercontent.com/940336/194764002-55a67890-2822-458e-b8ec-23f0c41d58d2.png)

**Comment by buzztiaan** [comment]
why the change? does it work anywhere else on 960x540?

**Comment by buzztiaan** [comment]
> When you attempt to test the buttons that you are unable to see, you should make sure there is an action bound to it. For instance, in the screenshot you provided, the only button that would actually do anything is the left one, which triggers the repair skill and opens the inventory. That button would likely be pretty close to the INV button, which could cause confusion as well.

Oh! I really couldn't make that out, but trying out on a different machine, yes, the buttons DO work, they are just invisible. :) 

And indeed overlays the INV button somewhat (just like the movement ones overlap on the left a bit)

**Comment by StephenCWills** [comment]
This must be the problem.

```
DEBUG: Texture dimensions are limited to 2048x2048
```

`button.png` is 87x2262 so the image is probably too tall.

**Comment by buzztiaan** [comment]
Oh gee, any easy routes around that? Maybe resizing to a tiny bit smaller, or eh, changing the layout of it would be probably wisest? 6x5 should be big enough for those 26 (?) buttons..

**Comment by StephenCWills** [comment]
> Oh gee, any easy routes around that? Maybe resizing to a tiny bit smaller, or eh, changing the layout of it would be probably wisest? 6x5 should be big enough for those 26 (?) buttons..

The problem with changing the layout is that the game only knows the number of frames in the image (26) and divides the height by that number to determine the coordinates of each frame. The easiest workaround would be to simply resize the image to 29x754, but that makes the graphics three times smaller so I don't know how it will look when scaled up from that size. It's got to be better than nothing at all, though, right?

**Comment by buzztiaan** [comment]
right, but would require a special fork of devilutionX on my repos (or maemo leste) just for a resized image? I wonder why 87 was chosen and not, say, 64 (26*64 = 1664, should be fine?)

**Comment by StephenCWills** [comment]
> right, but would require a special fork of devilutionX on my repos (or maemo leste) just for a resized image?

No, the reason I suggested resizing the image was because it wouldn't require any code change.

> I wonder why 87 was chosen and not, say, 64 (26*64 = 1664, should be fine?) Oh, or even 80x80 .. *26 is 2080

I suppose if you're downscaling the image either way, you can just go with 78x2028. My brain told me that an integer divisor would work better, but I don't really think that's necessarily the case in hindsight.

**Comment by buzztiaan** [comment]
Would it be desirable to add a 'button-lowerres.png' and just have the game grab that on failure with button.png somewhere here? 

https://github.com/diasurgical/devilutionX/blob/9b65eca49b5b6a9640ad44cb72bd95f6e21587cf/Source/controls/touch/renderers.cpp#L94

**Comment by StephenCWills** [comment]
FYI, this is likely a bridge we'll have to cross for 1.6.0 as we have plans to add support for hardware rendering in that version. If you don't mind maintaining a low-res version in your fork for now, I expect we'll begin that work within the next six months or so. Otherwise, I'd be okay reviewing whatever workaround you can come up with to submit back to this repo for 1.5.0. Maybe a CMake flag to select the low-res texture during compilation would work okay?

**Comment by buzztiaan** [comment]
Come to think of it, the Nokia N900 (one of Maemo Leste's targets) has a even older gpu, maybe i should check what GLES2 max texture is supported on that ... big featurecreep for 'lets package this' , lol

**Comment by buzztiaan** [comment]
just for confirmation

# mogrify -resize x2028 button.png

This 'totally' fixes it ;) 

![image](https://user-images.githubusercontent.com/940336/194767239-b08909ff-9738-4244-aad8-a27c60ddaacf.png)

and looks fine too ; 

![image](https://user-images.githubusercontent.com/940336/194767276-ec5ecd89-b225-4f0c-a00d-90ccdaf85ac5.png)

**Comment by StephenCWills** [comment]
> I do think they could be a bit more towards the 'outside' of screen, to prevent the overlapping with other UI items.

It's an easy critique, but much harder than it sounds. For one thing, the size of the buttons depends on the device's DPI. Second, the amount of space available next to the main panel depends on both the screen resolution and the selected game resolution. Last, there may be physical constraints the game would be completely unaware of, like a protective case that prevents the user from easily tapping that close to the edge of the screen. We would like to somehow make the size and position configurable, though.

**Comment by buzztiaan** [comment]
Yeah just a offset to add or something, 'put touch controls 0/8/16/32 pixels further from the center' and let the users figure out if they need it, come to think of it, maybe negative offset could be desirable aswell , for those eh, 1920x480 resolution screens.

**Comment by AJenbo** [comment]
> why the change? does it work anywhere else on 960x540?

You said it didn't work on any other resolutions, so it's not related to resolutions

**Comment by buzztiaan** [comment]
Ah yeah, indeed, when i forced 640x480 output , i didn't get them either. Maybe it should be 'Touch button textures can silently fail to load if GPU doesn't allow it'

**Comment by AJenbo** [comment]
> FYI, this is likely a bridge we'll have to cross for 1.6.0 as we have plans to add support for hardware rendering in that version.

easy solution is to check for 2048 support, and if it's not available then flag it as not able to use the hardware render option.

**Comment by AJenbo** [comment]
> and looks fine too ;

Debatable:

![image](https://user-images.githubusercontent.com/204594/194777514-3af4e4ec-cc99-4be3-9b28-d3c8cf31c46a.png)

What is the native resolution of your device?

**Comment by AJenbo** [comment]
Ironically the software rendere shouldn't have this limitation, so another solution would be to figure out what the issue with switching upscaling to off is (with upscaling enabled hardware rendering is used for this element).

**Comment by AJenbo** [comment]
> I wonder why 87 was chosen and not, say, 64 (26*64 = 1664, should be fine?) Oh, or even 80x80 .. *26 is 2080

Because of the content, projected size on various devices. 128 would be the nearest ^2 option that don't result in a down grade of image quality.

**Comment by buzztiaan** [comment]
> What is the native resolution of your device?
scroll up? :D 960x540 , the issue is 2048x2048 max texture size  

am i correct in that this texture message only appears when the device can report DPI?  
On a Pinephone running Maemo Leste i dont get any texture max message , but i do get > DEBUG: Couldn't get DPI
But , running the game, it seems to load the button.png totally fine in 87x87 pixel size.

Currently building on a Nokia N900 , lets see if that needs the same fix.

**Comment by StephenCWills** [comment]
> am i correct in that this texture message only appears when the device can report DPI? On a Pinephone running Maemo Leste i dont get any texture max message , but i do get > DEBUG: Couldn't get DPI But , running the game, it seems to load the button.png totally fine in 87x87 pixel size.

No, it should have nothing to do with whether the device can report DPI. I suspect that this issue is specific to Motorola Droid 4, but there's a decent chance we'll run into similar limitations on other devices eventually.

> I dont get 'we picked 87 because 128 is next'

He's saying we picked 87 because of the content and projected size on various devices. The comment about 128 was likely in response to your suggestion of 64, implying that we would have more likely chosen to go up to 128 because it wouldn't be a downgrade in quality.

**Comment by buzztiaan** [comment]
`DEBUG: Texture dimensions are limited to 2048x2048`

I'm looking around but i can't seem to find where this message about texture limits originates?

**Comment by AJenbo** [comment]
> scroll up? :D 960x540 , the issue is 2048x2048 max texture size

You never said this was the native resolution, just that it's what you where running the game at. I'm aware that the issue is with 2048x2048, I'm trying to figure out what quality you would expect the controls to be for them to look good on your device compared to what we support.

**Comment by buzztiaan** [comment]
Heh, honestly, as my fingers would be over them while playing , i don't really have a big opinion on what they look like.
Also i'm very quickly satisfied :D

**Comment by AJenbo** [comment]
> `DEBUG: Texture dimensions are limited to 2048x2048`
> 
> I'm looking around but i can't seem to find where this message about texture limits originates? My thinking was that this message might actually be the -error- telling me/us about the failed loading of texture?

SDL saying that it's unable to load buttons.png as a hardware texture.

**Comment by buzztiaan** [comment]
Man if its really that easy, maybe i should really just 'try catch' around this code and load lower res on failure? So it can be in Maemo Leste's 1.4.1 fork and later in your 1.5?

https://github.com/diasurgical/devilutionX/blob/9b65eca49b5b6a9640ad44cb72bd95f6e21587cf/Source/controls/touch/renderers.cpp#L94

**Comment by AJenbo** [comment]
For Motorola Droid 4 the ideal size is 46x1196. On my device it's 116x3016, but the artist didn't drew them at 87 so they are a bit blurry there.

**Comment by buzztiaan** [comment]
Well, i'm building for maemo leste extras, so it would be installable on all three (and other devices that i sadly do not have here)
Hence my desire for something that can work all ways ;)

**Comment by StephenCWills** [comment]
> Man if its really that easy, maybe i should really just 'try catch' around this code and load lower res on failure? So it can be in Maemo Leste's 1.4.1 fork and later in your 1.5?

There's no exception being thrown here, so there won't be anything to catch. I'm nearly certain that the failure is actually not on the call to `LoadPNG()` but rather the call to `SDL_CreateTextureFromSurface()` just a few lines down. It should be returning `nullptr` on error, so you'd have to capture the return value and handle the `nullptr` case. However, if I could help it, I'd rather not implement a workaround like this for one platform since it would effectively require us to package the low-res texture on many platforms that don't need it.

**Comment by buzztiaan** [comment]
You'd rather see a -DUNDER2048=ON that just calls mogrify (or similar) on building?

**Comment by AJenbo** [comment]
Yeah that would be really ugly, the error could be anything, not necessarily max supported texture size being exceeded. Much better to probe for that is support. Besides this may not be the only place where this could be an issue.

**Comment by StephenCWills** [comment]
Yeah, that would be my knee-jerk preference, although I do see your point about supporting many other devices which might have similar limitations.

**Comment by buzztiaan** [comment]
If the button drawing code could scan a 2x13 matrix instead of a 1x26 one, that might also be a option on all platforms without extra data (afaics)

**Comment by buzztiaan** [comment]
Or 6x5 like i suggested above , would lead to a almost square image of just 522x435  (and have 4 more bonus places!)

**Comment by AJenbo** [comment]
I'm still thinking for devices that has this limit we should simply not use hardware rendering.

Let figure out why upscaling=off is failing, then we don't have to look in to workarounds.

**Comment by buzztiaan** [comment]
Oh sure, but thats maybe a different issue? I do really want to have hardware rendering on these old devices like n900 and droid4 , they are kinda fast, but without acceleration its quickly disappointing.. Willing to try though

**Comment by AJenbo** [comment]
> If the button drawing code could scan a 2x13 matrix instead of a 1x26 one, that might also be a option on all platforms without extra data (afaics) and without resizing the texture.

I find this to focused on the one spot where an issue was noticed. How will this work when we eventually support rendering monsters via hardware. There sprite sheets have each angle in a separate column.

**Comment by StephenCWills** [comment]
For now, the hardware rendering only applies to the virtual gamepad UI elements. Without hardware rendering, they may look really awful, but it shouldn't affect performance at all.

**Comment by AJenbo** [comment]
> Current fps on droid4 with the hw renderer is 20-30fps

We do not have hardware rendering, just hardware scaling, you would probably get better FPS with it off, since it sounds like you are already settings the game to render at native resolution from the get go. All game rendering is CPU based.

**Comment by buzztiaan** [comment]
> There sprite sheets have each angle in a separate column.

Wouldnt this also benefit from 'wider matrix textures' to reduce overall texture size?

**Comment by buzztiaan** [comment]
I'll open a new issue for 'sw renderer doesnt work on Leste'

**Comment by buzztiaan** [comment]
Funny enough : 

Nokia N900 running Maemo Leste does not get the touchscreen interface at all. Might be because of resistive touchscreen instead of capacitive? But, as such , i cannot confirm/deny the 2048x2048 limit exists there :(

**Comment by AJenbo** [comment]
> Might be because of resistive touchscreen instead of capacitive?

i dont know that SDL draws a destinction, but it would be an issue since you cant use more then one input at a time

**Comment by buzztiaan** [comment]
Well, on N900 , log states : 
`VERBOSE: Control: device None -> KeyboardAndMouse, mode None -> KeyboardAndMouse`

While on pinephone or droid4 there is : 
```
VERBOSE: Control: device None -> KeyboardAndMouse, mode None -> KeyboardAndMouse
VERBOSE: Control: device KeyboardAndMouse -> VirtualGamepad, mode KeyboardAndMouse -> VirtualGamepad

```

**Comment by buzztiaan** [comment]
Oooo, i'm not sure what triggered it, but i do have in a N900 --verbose now this message : 

`DEBUG: Texture dimensions are limited to 2048x2048
`

So maybe some of the other textures are >2048 aswell?

**Comment by StephenCWills** [comment]
> So maybe some of the other textures are >2048 aswell?

You must have entered a game session, right? Even if the control mode is KeyboardAndMouse, the game still has to load the assets for the virtual gamepad so they can be displayed if the user starts using the touchscreen.

**Comment by buzztiaan** [comment]
Ah, right, yeah ok. So i guess in lew of some detection, i'll just resize the texture for all devices on Maemo Leste on my own 1.4.1 fork, and later rebase on yours if there's some route around it. Any objections? :)

**Comment by StephenCWills** [comment]
I have no problem with that plan.

**Comment by glebm** [comment]
Hopefully we can make the button texture rectangular in the future (e.g. one column per button type)

**Comment by buzztiaan** [comment]
yeah , 2x13 matrix would make it easier for buttons.png, but still might run into issues on other textures. (somewhere above mentioned a loading of monsters which would include huge textures)

**Comment by glebm** [comment]
Monsters are not loaded as textures currently. Even when they are, a fully hardware renderer will always be optional. Even then, I'm not sure whether monsters actually exceed 2048x2048.

**Comment by StephenCWills** [comment]
Ultimately, it may or may not be relevant to any intermediate or final solution we choose to implement, but I just wanted to point out that AJenbo's suggestion of querying the capabilities of the renderer to determine the maximum texture size should be 100% feasible.

https://wiki.libsdl.org/SDL_GetRendererInfo
https://wiki.libsdl.org/SDL_RendererInfo
