### ISSUE TITLE
Implement support for loading maps build using Tiled

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#541]
@mewmew has a tool for convertingn .dun files to the Tiled format, it would be good to have support for loading maps that have been build using Tiled

This simple implementation may help us in doing so
https://github.com/RandyGaul/cute_headers/blob/master/cute_tiled.h

Alternatively we could develop a .dun plugin for Tiled https://github.com/bjorn/tiled/tree/master/src/plugins the benefit being that it would work with any Diablo engine.

Similar issue for DGE with some how to load maps:
https://github.com/dgengin/DGEngine/wiki/Tiled-map-support
DUN file format specefications:
https://github.com/savagesteel/d1-file-formats/blob/master/DUN.md

**Comment by mewmew** [comment]
> @mewmew has a tool for convertingn .dun files to the Tiled format, it would be good to have support for loading maps that have been build using Tiled

For a quick step by step, this is how to convert DUN files to TMX:

```bash
# Set GOAPTH
$ export GOPATH=/tmp/go
$ export PATH=$GOPATH/bin:$PATH

# Extract DIABDAT.MPQ
$ go get github.com/sanctuary/mpq
$ mpq -m /path/to/diabdat.mpq

# Convert DUN files to TMX format
$ go get github.com/sanctuary/formats/cmd/dun_dump
$ dun_dump -a

# Merge Tristram sectors into a single DUN file
$ go get github.com/sanctuary/formats/cmd/dun_merge
$ dun_merge -o diabdat/levels/towndata/tristram.dun diabdat/levels/towndata/sector1s.dun diabdat/levels/towndata/sector2s.dun diabdat/levels/towndata/sector3s.dun diabdat/levels/towndata/sector4s.dun

# Convert Tristram DUN file to TMX format
$ dun_dump diabdat/levels/towndata/tristram.dun
```

![screenshot_2020-01-19_22:09:04](https://user-images.githubusercontent.com/1414531/72688520-5d574900-3b08-11ea-931a-7bd5d6f307bd.png)

**Comment by julealgon** [comment]
> @mewmew has a tool for convertingn .dun files to the Tiled format

Kinda off-topic: where can I get that tool? Sounds really interesting.

**Comment by yuripourre** [comment]
@julealgon good question, it used to be here, I think: https://github.com/sanctuary/djavul

Now, there is no project at: https://github.com/sanctuary/

**Comment by yuripourre** [comment]
@julealgon Take a look at: https://github.com/diasurgical/modding-tools

**Comment by AJenbo** [comment]
Adding support for loading the tile format would still be nice, but for now, we have a plugin in Tiled that can export .dun.
