### ISSUE TITLE
Virtual controls broken

### ISSUE THREAD

**Issue by Trihedraf** [diasurgical/devilutionX#5430]
### Operating System

iOS

### DevilutionX version

Other (please specify version number)

### Describe

Since #5411 was merged the right side buttons on the virtual controls don’t do anything. Can’t talk to NPC, attack monsters or cast spells.

### To Reproduce

Go to an NPC and try to talk to them using the virtual controls

**Comment by Trihedraf** [comment]
Further testing it's all the virtual controls except the movement stick and stand ground button.
Also if the virtual controls get lost touching the screen doesn't bring them back like it used to it just moves the mouse cursor.

**Comment by AJenbo** [comment]
touch controls should probably skip the mapper a call directly

**Comment by StephenCWills** [comment]
I think it's because we slipped in the logic to move the `GameAction` handler. I added the code to forward gamepad events along in `FetchMessage_Real()`, but I forgot about touch events.
