### ISSUE TITLE
Solitary pillar

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5432]
I don't know either, but somehow discovered the following pillar.
I've never seen a single one that big.

![pillar](https://user-images.githubusercontent.com/45902449/197560645-cc15989e-d04e-425e-a576-0b72b8ba34ff.png)

Savegame:
[pillar.zip](https://github.com/diasurgical/devilutionX/files/9852782/pillar.zip)

**Comment by NiteKat** [comment]
I just saw this on Tenka's stream today. I wonder if this is a bug or just very rare generation, never seen it in person.

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/202486572-761e6548-f80a-4e6e-851b-c56f3757133d.png)
I'd say this confirms it also exists in vanilla = we good.

**Comment by StephenCWills** [comment]
FWIW, it seems that the `predungeon` data doesn't match the layout here. It's as if the dungeon generation placed a lonely wall in that spot and then stomped over part of it with the room to the right.

![image](https://user-images.githubusercontent.com/9203145/202496051-1d82c797-5061-4c3a-8dca-1488bb4c585d.png)
