### ISSUE TITLE
Unable to open the nest

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5433]
Unable to open the nest with the rune bomb.
The issue appears since commit ba65d5fbff5adb266df09a70db60c01ab473fd38.
Not tested whether the entrance to the crypt behaves similarly.

Savegame:
[bomb.zip](https://github.com/diasurgical/devilutionX/files/9853193/bomb.zip)

**Comment by StephenCWills** [comment]
It seems the handler for `CMD_PUTITEM` is the one that invokes `OpenHive()`, so the fact that we are finding a valid location to drop the rune bomb in `LeftMouseDown()` is problematic.

`TryDropItem()` handles Rune Bomb and Map of Doom separately before sending `CMD_PUTITEM` so it actually still works properly on gamepad. Incidentally, this means you can still open these areas using `Ctrl+Click` to drop the item when standing next to the dungeon entrance.
