### ISSUE TITLE
Huge request, toggle/hide the UI bar which consumes 30% of the screen

### ISSUE THREAD

**Issue by and00r** [diasurgical/devilutionX#5439]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

It would be amazing to hide that huge info bar which always consumes such a large portion of the screen.
I think you would agree.

I am also hoping this is something which is possible to do

### To Reproduce

Play the game

**Comment by qndel** [comment]
That's not easy + someone would have to prepare a smaller UI - feel free to do it.

**Comment by and00r** [comment]
im not able to do this. and im also not the person who is bothering to modifying this game. seems like someone has a considerable passion for this game, which is why i believe my suggestion pertains directly to this. 
and also, the request is to toggle and hide the info bar, not shrink it. this would not require any new graphics.
thank you

**Comment by qndel** [comment]
No clue what's info bar, you provide 0 information in your issues, such things get closed.

**Comment by StephenCWills** [comment]
The passion for this project runs much deeper than your proposed solution would suggest. We have plans to make the UI moddable using Lua scripts, which would enable us to create custom HUD designs and provide revamped defaults for mobile platforms.

Thus far, developers that have attempted to replace existing HUD elements have reported that it's especially difficult compared to many other modifications so I don't really expect anything official to be done with the UI until the Lua scripting is ready.

**Comment by and00r** [comment]
Yes I'm not sure what to call the huge thing which constantly consumes almost half the screen. You know, that giant thing which displays your health and mana. It would be nice to have a button which toggles and hides/shows this thing.

**Comment by qndel** [comment]
you know you can take a screenshot right? 😞

**Comment by AJenbo** [comment]
The goal is to long standing and non specific to warrant an issue in GitHub. Work is being done to slowly improve the UI over time.

**Comment by StephenCWills** [comment]
If you want more viewing area, change the game resolution. In fact, some have suggested that the game feels much better at 1280x960 with zoom enabled (Z key) because the HUD is much smaller at that scale.

**Comment by and00r** [comment]
I like playing it in 640x480 with scaling being done on the GPU and set to maintain aspect ratio... This is very aesthetically pleasing to me but unfortunately that huge health bar really does almost take up half the screen. I was just thinking maybe it would be nice if it could just magically disappear with the push of a button and then reappear whenever you need it at another push of a button.

**Comment by and00r** [comment]
If it's difficult or not possible to do this, then I certainly would understand. I was just hoping that it would be possible to do this. And was also hoping that someone would equally agree. I personally feel that giant UI bar is very distasteful.

**Comment by StephenCWills** [comment]
> I like playing it in 640x480 with scaling being done on the GPU and set to maintain aspect ratio...

If you truly enjoy playing at that resolution, then this wouldn't be an issue. Sounds like maybe you prefer playing at 640x608, which is equivalent to what you'd be playing at if you hide the main panel. Also, I urge you to actually try playing at 1280x960 with zoom enabled. You may not notice a difference.

**Comment by and00r** [comment]
Yeah maybe. But The game still seems better to me in its native resolution. And that huge bar Really does consume a ridiculous amount of space on the screen.

**Comment by StephenCWills** [comment]
To be clear, you're telling me that this...

![image](https://user-images.githubusercontent.com/9203145/198131525-eec98f43-0fe4-4b05-80a4-bbda4a0bd41c.png)

... is better than this.

![image](https://user-images.githubusercontent.com/9203145/198131540-d28418b2-7d66-4919-80d4-fa5c888d1309.png)

**Comment by and00r** [comment]
Yes. To be clear, the game does indeed look good at higher resolution, but to me personally playing in its native resolution sort of has its own aesthetic charm.  
What I'm proposing is sort of a compromise too native gameplay but only with the giant HUD removed. This seems like it's still keeps the spirit of the original game but also improving upon it without changing the entire nature of the game such as changing the entire resolution. I really don't like the look of the bottom picture in the screenshot. The hud just looks silly. 

But to be honest with you, I actually do enjoy both options. I've never played this game before so the first time I wish to play it will certainly be in its native resolution. But I also like the option of changing the resolution and making it larger. Obviously that does indeed look very good. 
But also it would be nice to just be able to play the game and it's original states and just get rid of that giant ugly HUD. Once again It still feels like I'm playing the original game only with like an improvement done to it. If you can understand that.

**Comment by StephenCWills** [comment]
In that case, you do indeed want something extremely specific to your preferences. In cases like these, we generally recommend just implementing it yourself, which has already been mentioned. The main thing the suggestion has going for it is that it _seems_ easy, but it is surely not actually as easy as it seems.

**Comment by and00r** [comment]
Honestly it just seems like you are looking for any excuse to disagree. That HUD is poor and hideous, I don't think it's unreasonable to agree with this.
And it would seem like a better option to just hide it instead of you know changing the HUD with a skin which makes it look better but it's still changing a fundamental portion of the game... You think maybe perhaps just toggling the HUD on and off would be the proper way of dealing with this? It seems like it would be more proper of a fix rather than replacing it all together with a different skin. I don't know man. I don't even care about changing this anymore. It was only a suggestion and you really seem like you are just looking for any excuse to argue with random strangers. And no offense, but I don't even care about the Nintendo switch. The only person I ever seen use one of those had autism unfortunately.

**Comment by qndel** [comment]
Okay that's enough, want it done? Do it yourself, nobody else needs/wants it.

**Comment by AJenbo** [comment]
> That HUD is poor and hideous

Then you do not like the original aesthetic

> just hide it

Like has been pointed out a bunch of times, it's not simple to do. No one is trying to pick a fight with you, just simply make it clear that what you are asking is a long term goal, and there for alternatives have been offered.

> I don't even care about the Nintendo switch. The only person I ever seen use one of those had autism unfortunately.

This just seams inappropriate, please refrain from such arguments in future communications.
