### ISSUE TITLE
Inconsistent gamepad mappings on SDL1 + Nintendo

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#5448]
On the rg350, we use SDL1 and `set(DEVILUTIONX_GAMEPAD_TYPE Nintendo)`.

This results in the following inconsistent mappings:

1. In the main menu, A is used to confirm.
2. In the in-game menu, B is used to confirm (should be A)

(A and B refer to the actual labels on the buttons on this Nintendo-type gamepad)

**Comment by glebm** [comment]
Actually it's displaying the xbox hints so I think the issue is with the gamepad type propagation

**Comment by glebm** [comment]
@StephenCWills Any idea what might be causing this?

**Comment by StephenCWills** [comment]
I haven't really looked into it yet, but from my testing so far, I got the feeling that it might just be backwards on all gamepad types.
