### ISSUE TITLE
Data File Error: Unable to open main data archive

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [diasurgical/devilutionX#5454]
### Operating System

Mac

### DevilutionX version

1.4.1 (latest release)

### Describe

Data File Error: Unable to open main data archive (diabdat.mpq or spawn.mpq). Make sure that it is in the game folder.

![image](https://user-images.githubusercontent.com/6131040/198885321-f5eee060-6af8-45bd-9272-79a5b20fe321.png)

### To Reproduce

1. Open `DevilutionX.app`
2. See error message

### Expected Behavior

Game window should appear.

**Comment by StephenCWills** [comment]
Did you make sure that either `diabdat.mpq` or `spawn.mpq` are in the game folder?

**Comment by AJenbo** [comment]
The error and description make it sound like you might not have provided the needed game data. If that is not the case then please update the description and we can reopen the issue.

Please see the installation instructions: https://github.com/diasurgical/devilutionX#how-to-install

**Comment by dmitrykolesnikovich** [comment]
Thanks for the answer. Now everything is running.

![image](https://user-images.githubusercontent.com/6131040/198893468-a8d0ff05-7239-403d-a414-c059adf2aca7.png)
