### ISSUE TITLE
Separate spell icons from background to save RAM

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#5470]
We could separate spell icons from backgrounds on low-RAM systems to save some RAM.

Currently we have ~200 KiB of spell icons:

spelicon.clx 138 KiB
spelli2.clx 67.5 KiB

I'm guessing we can save 100-150 KiB by doing this.

Perhaps this can be done semi-automatically.

The background only uses indices 192 to 207 (inclusive).
The inner section of the box is 192 to 205.
[204..207] are also used by the icon's shadow.

So we could probably automate the extraction as follows:
1. Replace [192...203] with transparent in the inner section of the box
2. Make the entire outer section of the box transparent.
3. Make each pixel that has all transparent neighbours transparent (to handle the occasional [204..207] in the inner background)

This is only useful on low-RAM systems, so it could be done as part of `unpack_and_minify_mpq`

**Comment by AJenbo** [comment]
I agree that this should be done in the script that aims to minify the mpq and not the game itself

**Comment by glebm** [comment]
Optimized total: 68 KiB, savings: 137 KiB

**Comment by AJenbo** [comment]
Nice that is a pretty big save :) If you wanted to be extra aggressive I guess you could blank out the frames that are unused.

**Comment by glebm** [comment]
I did remove out the unused frames except for the empty gap (to avoid reindexing in the code).
A blank frame is very cheap to store

**Comment by AJenbo** [comment]
Are these used?
![image](https://user-images.githubusercontent.com/204594/200929224-06bac8be-f946-4c4f-95d4-e3e9d674adf0.png)

**Comment by glebm** [comment]
@AJenbo Ah I see what you mean! Yeah that would save a few KiB, though the total size is already pretty small.

One thing I've noticed is that my code is too agressive at removing soft shadows. Will need to tweak it a bit.

**Comment by AJenbo** [comment]
Another option would be to diff the frame against the background sprite.

**Comment by kphoenix137** [comment]
> Are these used?
> ![image](https://user-images.githubusercontent.com/204594/200929224-06bac8be-f946-4c4f-95d4-e3e9d674adf0.png)
> 

Sentinel, Blood Ritual (I think), Invisibility, 5 completely unused, Elemental (used)

**Comment by glebm** [comment]
I have come up with a method that preserves the soft shadows and is only ~22 KiB larger.
Large: ![spelicon_fg_clx](https://user-images.githubusercontent.com/216339/200956825-6d35cd7c-61d7-486c-a2eb-5ae1dab9251e.png)
Small: ![spelli2_fg_clx](https://user-images.githubusercontent.com/216339/200956831-964cec90-6773-49f1-801e-b7be649d2df8.png)
