### ISSUE TITLE
Add MPQ-path to the config file

### ISSUE THREAD

**Issue by legluondunet** [diasurgical/devilutionX#55]
Hello,
with a config file we could:
- precise where the diabdat.mpq is located instead of copy it in the devilutionX
- what is the name of  diabdat.mpq (could be another CASE or another name)

On linux the config file should be located in /home/your_profile/config/ folder.

**Comment by LinRs** [comment]
Now  `diabdat.mpq` might be located in ``~/.local/share/diasurgical/devilution/`` .

**Comment by AJenbo** [comment]
The original game already has a diablo.ini, we have expanded it to also hold all the settings that where normally saved to the registry + some additional values https://github.com/diasurgical/devilutionX/pull/44.
`~/.local/share/diasurgical/devilution/diablo.ini`
This path is controlled by SDL.

I believe the game already looks for the mpq file in `~/.local/share/diasurgical/devilution/`, we are currently trying to avoid modifying the original code and only build the surrounding parts that it needs to run, this is for one thin to avoid merge conflicts when pulling in new cleanups from upstream, but also allows us to faithfully recreate the game behavior before doing any refactoring. This currently prevents us from specifying the path directly, but we might be able to ad the "CD" path as an option to the config.

**Comment by predator8bit** [comment]
ln -s /wherever/your/data/is/DIABDAT.MPQ /wherever/devilutionx/exists/diabdat.mpq

**Comment by cjsthompson** [comment]
I've tried ln -s from an NFS4 share, so diabdat.mpq is shared between several machines. I usually do that for other games such as Doom or Quake. But it seems devilutionX can't find diabdat.mpq when it's a symlink. Or it has problems with NFS which would be surprising.

Save for this minor problem, DevilutionX works wonders on Linux/x86_64 so far. I had been wanting for years to play Diablo on Linux without the need for emulation or WINE and the 32bits deps that come with it. Truly a dream come true. I now consider this year to be the year of the Linux desktop. A desktop OS without Diablo is no desktop OS. :) Thanks for the efforts in making this possible!

**Comment by legluondunet** [comment]
Thank you for the workaround but that is not the final objective of this issue: precise the name and the path to the file in a config file. Then you could store your diabdat.mpq where you want, uppercase or lowercase.

**Comment by predator8bit** [comment]
That seems like the way to go, but for now symlinks work, thugh I only tried on the same machine.

**Comment by legluondunet** [comment]
I confirm symlink workaround works (ext4 filesystem)

**Comment by NeonLightning** [comment]
would being able to type in `./devilutionx /path/to/diabdat.mpq` be doable?

**Comment by AJenbo** [comment]
yeah that's probably a much better solution

**Comment by NeonLightning** [comment]
it would make things easier for those of us on rockpro64 and raspberry pi running thera or retropie.

**Comment by AJenbo** [comment]
You can now specify the MPQ path:
https://www.youtube.com/watch?v=fk9GwVIhOGc
