### ISSUE TITLE
Assertion error trying to build devilutionx.mpq from latest GIT 

### ISSUE THREAD

**Issue by vanfanel** [diasurgical/devilutionX#5549]
### Operating System

Other (please specify)

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Trying to build latest GIT code, commit 20e12dcc3affb2009859cfd47cda65d4bf7f5950
This happens on latest stable Debian 11 on aarch64.

I get this when trying to build latest code when the build system is trying to build the .mpq file:

```
smpq: /build/stormlib-ZqSJqm/stormlib-9.22/src/SFileAddFile.cpp:103: int FillWritableHandle(TMPQArchive*, TMPQFile*, ULONGLONG, DWORD, DWORD): Assertion `sizeof(hf->hctx) >= sizeof(hash_state)' failed.
Aborted

``` 

Do you have an idea on what could be wrong? Thanks!

### To Reproduce

Try to build the current GIT codebase.

### Expected Behavior

The devilutionx.mpq file builds with no problems.

**Comment by AJenbo** [comment]
installing smpq should solve that

**Comment by vanfanel** [comment]
> installing smpq should solve that

I have already done that before even trying to build it.

**Comment by glebm** [comment]
Try installing it using this script: https://github.com/diasurgical/devilutionX/blob/master/tools/build_and_install_smpq.sh

The 9.22 version of StormLib that the error message points to might be too old.

**Comment by vanfanel** [comment]
> Try installing it using this script: https://github.com/diasurgical/devilutionX/blob/master/tools/build_and_install_smpq.sh
> 
> The 9.22 version of StormLib that the error message points to might be too old.

Ah, so it's the StormLib version included in stable Debian, it seems...
No way to make it work with stable Debian packages?

**Comment by AJenbo** [comment]
https://packages.debian.org/source/bullseye/smpq should work

**Comment by glebm** [comment]
@AJenbo The version you point to uses StormLib 9.22 which is broken on some platforms (ARM IIRC).

@vanfanel Even testing is still on 9.22. You could send a patch to Debian to update to 9.24.

For justification, 9.22 is completely broken on ARM (https://github.com/ladislav-zezula/StormLib/issues/235) and in some cases other platforms (https://github.com/ladislav-zezula/StormLib/issues/167).

**Comment by vanfanel** [comment]
@glebm I totally understand the problem now, Thanks a lot, I hope it serves to future Debian users that may find the same problem.
I will build without smpq for now (ie: copying the assets directory instead) until Debian gets it fixed... which won't be until Debian 12 I guess.

**Comment by Srandista** [comment]
Unfortunately, the same broken version (9.22) is also used in latest Debian Bookworm, so you need to build smpq from source with mentioned script.
