### ISSUE TITLE
Ability to toggle off Blended Transparency removed?

### ISSUE THREAD

**Issue by krustacean2** [diasurgical/devilutionX#5550]
**Operating System:**
Mac OS Monterey version 12.3.1

**DevilutionX Version:**
1.4.1

The Blended Transparency=? option was not present in the diablo.ini file when I installed Devilution (I only learned about this feature from the Configuration Guide).  I tried manually typing it in using TextEdit but this did not do anything whether I set it to 0 or 1.  For clarity, I am trying to turn it off because I want to make the game look as close as possible to how it did when it was originally released.  Is it no longer possible to turn off the Blended Transparency feature, or is there maybe some other way to do it?

Thanks

**Comment by AJenbo** [comment]
The old transparency mode was removed in 1.4.0 so you would need to use 1.3.0 or older releases for that.

It was removed since it appeared that no one used it or prefered it and we didn't want to maintain the extra code.

**Comment by krustacean2** [comment]
I tried 1.3.0 as recommended.  Unfortunately the settings in the .ini that I used to get the graphics to look how I want, after trial and error changing around the different values, which worked in 1.4.1 do not in 1.3.0, and I couldn't get them to after going through the same process of trial and error.  I attached screenshots of the game screen and the graphics section of the .ini, for each version, to show what I'm talking about.  (just using the same settings in each one as an example; I did try changing around the values in 1.3.0 in case anything worked differently, but nothing I did got the same result as what I was able to achieve in 1.4.1).

Just want to add my 2 cents and say I am at least one person who'd be in support of you guys re-adding this feature in a future release.  I know you said nobody uses or prefers it so maybe that answers my question already haha.  I think the original stippled/dithered transparency looks better because it looks more retro.  Also I've actually yet to do a full playthrough of the game (had been wanting to try it and Devilution is what is enabling me to do so on a modern Mac); as it's the first time, I wanted the experience to be as "vanilla" as possible.  Just giving some reasons as to why players might want this feature.  I understand if there's not enough demand and that it takes work, time and energy to implement things in code, just figured I would speak my thoughts.

![Screen Shot 2022-12-03 at 3 08 30 AM copy](https://user-images.githubusercontent.com/119370820/205432012-1992f60b-55a7-4245-b755-bf244650d86e.jpg)
![Screen Shot 2022-12-03 at 3 15 15 AM copy](https://user-images.githubusercontent.com/119370820/205432015-e693f1a0-a0ee-4114-aca9-579b3bcd30b9.jpg)

**Comment by AJenbo** [comment]
That is a really odd resolutions...

Could you let us know what you are trying to achieve with your settings?

It looks like you are aiming for 3x scaling since that is the max integer scaling that would match your monitors resolution (`floor(1600/480)`). Then growing the view area by 10% to avoid most of the black board at the top and bottom, but not the width. It feels a bit arbitrary to grow the view to a 4:3 since you are already growing the view area to fit your screen height, you might as well grow it to your screen width, or not change the width since 708x531 isn't the same as 640x480 despite them both being 4:3.

Instead of trying to migrate the ini settings I would suggest renaming your 1.4.1 config and letting the game generate a new one for 1.3.0 so you can see what actual options are there.

I would recomend just setting integer scaling, quality 0, trasprancy 0, and let the rest be handled automatically. This should give you basically the same result but also fully remove the black boarders on the side.

It seams that the two issues you have with 1.3.0 is that it's only doing 2x and bilinear scaling. I'm guessing the 2x is an issue with a older SDL that isn't detecting your retina resolution properly and the scaling is probably down to renaming of options.

**Comment by krustacean2** [comment]
![Screen Shot 2022-12-10 at 12 06 15 AM copy](https://user-images.githubusercontent.com/119370820/206831070-d808441c-ad21-4e0e-bf37-6e83767f4fb7.jpg)

![1KKWF00O3BBU1551141065997](https://user-images.githubusercontent.com/119370820/206831069-09227bdf-a404-4529-a265-35342e540595.png)

For the reason why I had 708 x 531 before, I noticed 640x480 was almost right but had about 1 inch of black space on the top and bottom (in addition to the bars on the sides, but I was ok with having bars on the sides because I know my monitor isn't 4:3 so there's no other way) Since it was so close, I used an aspect ratio calculator and just kept increasing the dimensions little by little to try and get rid of the bars (as you increased one value, the site would show you if the other one would be a whole number or not.  I wanted to make sure there wouldn't be distortion).  Ending up with almost zero black bars on the top and bottom, only like 1 pixel of space, so it worked.  But the transparency thing, I couldn't do anything about.

I tried the settings you recommended after having 1.3.0 create a fresh .ini file, producing the image I attached.  

The goal I had with the graphics settings was to get something that's as close as possible to how the game looks on a 90s computer from the time when it was released, in terms of aspect ratio, in-game field of view, and UI size.  Basically to just get it to look unaltere, in its original form (attached a screenshot from the internet to show what I'm talking about).

That makes sense that it could be the retina display screwing with the scaling when Fit to Screen is off in 1.3.0, I'm surprised I was able to get something to work in 1.4.1 then, glad it does though lol. 

Again if there's anything you think I haven't thought of to try in 1.3.0 lmk!

**Comment by AJenbo** [comment]
Well increasing view size by 10% in both direction just feels a bit odd if your goal is to keep it true to the original, it gives you a big advantage over someone playing in the 90 in some situations. Might as well increase the width by 33% to also get rid of the side bars.

Platform abstraction (and there by retina resolution) is handled by the SDL 2 framework. You could try replacing the one used in 1.3.0 with the one from 1.4.1.

If you right click he application you can select Show Package Contents to show the containing files, the path for the SDL 2 framework is devilutionx.app/Contents/Frameworks/libSDL2-2.0.0.dylib

You can also try downloading the latest version from SDL https://github.com/libsdl-org/SDL/releases

**Comment by krustacean2** [comment]
I tried swapping the 1.3.1 libSDL2-2.0.0.dylib file for the one from 1.4.0 but it didn't make any noticeable changes.  The files had the same name btw (libSDL2-2.0.0), I still tried making the switch though in case the contents were different or something.

I tried altering the settings in the menu that's in your screenshot.  Mine only has 4 options.  The one that's selected by default is just named "Default" and says "looks like 1280x800".  Decreasing it, going one to the left, makes it "look like 1024x640".  This at least did something, it made the game window take up more of the screen, although there were still black bars on all sides.  There's no way to manually type in what resolution you want.  I would've tried making it 640x480

If I put Upscale=0 in the .ini file it makes it perfect in terms of aspect ratio, but the pixels become blurry.  I'm assuming this has to do with what the config guide says, that it's changing your monitor's resolution to match the internal width and height.  Is there any way to get sharp graphics without having Upscale on?

**Comment by AJenbo** [comment]
> If I put Upscale=0 in the .ini file it makes it perfect in terms of aspect ratio, but the pixels become blurry.

with this its left up to your os/gpu/monitor how to display the image. im not sure what options mac gives you here, or where to find them

**Comment by julealgon** [comment]
> Your screen shot shows that you are ending up with a 2x scaling (instead of 3x) which makes sens if the true resolution of your screen is being obscured by a 1.1-1.6x retina multiplier.

@AJenbo could this perhaps be related to OS-specific DPI-awareness configuration? Perhaps a MacOS-specific change similar to the one I did for this:
- https://github.com/diasurgical/devilutionX/issues/786

The "0 upscaling => still blurry pixels" is giving me similar vibes from back then.

**Comment by AJenbo** [comment]
It's a similar issue, but the underlying problem is specific to the os. Without a suitable Mac I am unfamiliar unable to get any close to what change resolved it
