### ISSUE TITLE
Can't find libfmt on older Ubuntu

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5559]
### Operating System

Other (please specify)

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Ubuntu 16.10 PowerPc

Since af08a99691fbeda0235868ef2552c631a8f335d2 my super powerful BE desktop has been unable to resolve libfmt during configuration:

```
-- 📚 libfmt: static system library
CMake Error at CMake/Dependencies.cmake:101 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" (requested
  version 7.0.0) with any of the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:174 (include)


-- Configuring incomplete, errors occurred!
See also "/home/ajenbo/devilutionX/build/CMakeFiles/CMakeOutput.log".
See also "/home/ajenbo/devilutionX/build/CMakeFiles/CMakeError.log".
Makefile:4542: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```

### To Reproduce

1. mkdir build
2. cd build
3. cmake ..

**Comment by StephenCWills** [comment]
Does this happen with a clean build? I'd think that you'd have to have `DEVILUTIONX_SYSTEM_LIBFMT=ON` in your CMakeCache.txt file. Otherwise, it would fail to detect and switch over to building libfmt from source.

https://github.com/diasurgical/devilutionX/blob/af08a99691fbeda0235868ef2552c631a8f335d2/CMake/Dependencies.cmake#L90-L98

**Comment by glebm** [comment]
Also the call stack look suspect, this is line 174 in the current codebase:
https://github.com/diasurgical/devilutionX/blob/5024bc0f07d2de2de46ad882077e4123acaf96c1/CMakeLists.txt#L174

**Comment by StephenCWills** [comment]
It's from the referenced commit, I think.

https://github.com/diasurgical/devilutionX/blob/af08a99691fbeda0235868ef2552c631a8f335d2/CMakeLists.txt#L173-L174

**Comment by AJenbo** [comment]
It feels a bit flaky since its actually building latest master right now...
It's a bit slow debug since a full build take something like an hour

**Comment by StephenCWills** [comment]
Your last known good build is from before glebm reorganized the build scripts. Back then, the script didn't bother with `find_package(fmt 7.0.0 REQUIRED)` and would just build it from source if it wasn't found.

https://github.com/diasurgical/devilutionX/blob/eb04c5f5544306a387e10b5e764e88364a519302/CMakeLists.txt#L222-L232

Also, the default for `DEVILUTIONX_SYSTEM_LIBFMT` was `ON`, so it absolutely would have been added to your CMakeCache.txt file, even though you were technically building it from source each and every time. You would have had to do a clean build after pulling the latest DevilutionX source to resolve it. That might be why it seems flaky.

https://github.com/diasurgical/devilutionX/blob/eb04c5f5544306a387e10b5e764e88364a519302/CMakeLists.txt#L75-L77

**Comment by AJenbo** [comment]
Closing this at it appears to have been reolved in master, just got confused by the multiple issues for BE over the past year

**Comment by AJenbo** [comment]
> Does this happen with a clean build?

Clean builds are scary on a 700mhz cpu :hot_face:
