### ISSUE TITLE
Cursor buffer is drawn sometimes when there is no cursor

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#5560]
Need a way to reproduce this:
![image](https://user-images.githubusercontent.com/216339/205496942-e0d3d537-5687-47fa-add6-258eba2353ca.png)
/cc @kphoenix137

**Comment by StephenCWills** [comment]
It has something to do with the transition between hardware and software cursor.

1. Turn on Hardware Cursor
2. Turn off Hardware Cursor For Items
3. Enter a game
4. Open the inventory
5. Pick up an item and then place it somewhere in the inventory
6. Close the inventory
7. Trigger some lag

Some additional notes:
* The hourglass always flickers when using software cursor.
* You can see a similar effect during the fade after selecting `New Game` from the game menu.

https://user-images.githubusercontent.com/9203145/206339175-2495c6e8-8f2a-4922-9345-2ee8dd05768a.mp4

**Comment by StephenCWills** [comment]
Also, I went ahead and uploaded a branch you can use to fake some lag. I was using `lag 20` for testing.
https://github.com/StephenCWills/devilutionX/tree/fake-lag

**Comment by glebm** [comment]
Thanks! This was easy to fix thanks to this repro :)
