### ISSUE TITLE
Too many issues!

### ISSUE THREAD

**Issue by hiperiondev** [diasurgical/devilutionX#5570]
There are 232 open issues, some since 2018. It is very likely that many have already been resolved, or will never be resolved. They should be closed or moved to the next version, if applicable.

**Comment by AJenbo** [comment]
Stop spamming: https://github.com/diasurgical/devilutionX/issues/5472

**Comment by qndel** [comment]
Feel free to go through them and let us know which ones should be closed 👀 and I'll start with closing this one xD
