### ISSUE TITLE
Staircase Teleport Bug

### ISSUE THREAD

**Issue by Diablo-1996** [diasurgical/devilutionX#5571]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

On any character, if you go down the stairs to the next level and rapidly use teleport, it will behave largely like phasing instead and catapult the character to a random location on the current level. This is an old trick that was used primarily on Normal/Hell by Sorcerers to stumble upon the next level ultra fast.

### To Reproduce

1- Go to Hell with any character
2- Loading screen appears
3-Spam or Use Teleport, see how far you lend from initial stairs

### Expected Behavior

The bug should just be fixed. This was clearly unintended and teleport should behave normally upon entering a new level.

**Comment by AJenbo** [comment]
From what I have seen this is caused by the targeted coordinate carrying over from the previous level.
