### ISSUE TITLE
Dungeon generation tests are failing for BE systems

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5572]
### Operating System

Other (please specify)

### DevilutionX version

Custom build (please specify commit ID)

### Describe

15a22d0210a97b46cbfe86af6d69a43c8dac818d

All dungeon generation tests are failing with the following error on PowerPc
```
[ RUN      ] Drlg_l1.CreateL5Dungeon_diablo_1_2588
test/drlg_test.hpp:48: Failure
Expected equality of these values:
  Size(40, 40)
    Which is: (width: 40, height: 40)
  Size(DunData[0], DunData[1])
    Which is: (width: 10240, height: 10240)
```

40 just happens to be the reverse of 10240 so there is probably a simple swap missing somewhere

### To Reproduce

./drlg_l1_test

**Comment by glebm** [comment]
This just looks like an issue in the test helper:

https://github.com/diasurgical/devilutionX/blob/529a1631de97ddb9a2d4551b9f015e47f679e9da/test/drlg_test.hpp#L48

Should be calling `SDL_SwapLE16` because the dungeons are stored in little-endian.
