### ISSUE TITLE
Latest master crashes me when I visit Wirt or go down to dlvl 13

### ISSUE THREAD

**Issue by FireIceTalon** [diasurgical/devilutionX#5596]
![Screen Shot 2022-12-10 at 7 36 33 PM](https://user-images.githubusercontent.com/98377923/206883849-4a2579b5-6461-4bf8-a7ae-31457c4dd2fd.jpg)

**Comment by FireIceTalon** [comment]
This version here.

**Comment by AJenbo** [comment]
That doesn't look like master but #1683 ...

Either please confirm that this happens with a new hero or provide a save

**Comment by qndel** [comment]
Is following the damn template so hard? 🙄

**Comment by AJenbo** [comment]
Level 13 :shrug: 
![image](https://user-images.githubusercontent.com/204594/206936180-22e12a63-5f9a-40dc-87c7-62dac8ffa862.png)

**Comment by AJenbo** [comment]
Had a chat with Wirt:
![image](https://user-images.githubusercontent.com/204594/206936257-c6d2937d-5a37-4334-a10b-a3492b4def58.png)
