### ISSUE TITLE
Attempting to drop item into a pile in town will not fall

### ISSUE THREAD

**Issue by IttyBitty997** [diasurgical/devilutionX#5597]
### Operating System

Mac

### DevilutionX version

1.4.1 (latest release)

### Describe

When I attempt tp drop an item from my personal stash to the ground in town the item will not fall. 

### To Reproduce

I have about 140 items in various piles in town and when I try to drop another it will not fall. I end up placing it back into my stash.

### Expected Behavior

The item to drop.

### Additional context

![Screen Shot 2022-12-10 at 11 48 43 PM](https://user-images.githubusercontent.com/63123996/206888573-3dbc2906-cbd8-4601-ad8f-73cc3b520600.png)

![Screen Shot 2022-12-10 at 11 55 57 PM](https://user-images.githubusercontent.com/63123996/206888744-5020263a-53b8-419c-b23e-36628a7bc4a4.png)

**Comment by AJenbo** [comment]
This is because of the 127 items per level limit, it's the same for the original game
