### ISSUE TITLE
insensible CASE

### ISSUE THREAD

**Issue by legluondunet** [diasurgical/devilutionX#56]
Hello,
is it possible to give devilutionX case insensitive. Like this it could recognize diabdat.mpq or diabdat.MPQ or DIABDAT.MPQ....

Less error for the user.

**Comment by AJenbo** [comment]
The only real way to do so is check the name if every file in a folder, it's kinda costly and not the way programs normally work on Unix systems. The real reason for the issue is how the file system works.

**Comment by ssjkakaroto** [comment]
@AJenbo couldn't you call grep (on *nix systems) to get the file name before passing it to devilutionx? My original Diablo cd has that file in uppercase, but devilutionX expects it in lowercase.

**Comment by AJenbo** [comment]
@ssjkakaroto grep filters text, it dosn't find files, but calling an external program would not be a robust way to solve this (and not really any easier either).

**Comment by ApertureSecurity** [comment]
> couldn't you call grep (on *nix systems) to get the file name before passing it to devilutionx? My original Diablo cd has that file in uppercase, but devilutionX expects it in lowercase.

You need to learn linux and don't know the operating system you're using. Take some time to learn the O.S first before making such requests. You'll run into this on every O.S except for windows from what I understand.

**Comment by AJenbo** [comment]
something similar to what freeablo did here could be acceptable as a pull request https://github.com/wheybags/freeablo/blob/2b0a44350ce84e7ad430960ace36090d7437fc77/components/faio/faio.cpp#L230

> You'll run into this on every O.S except for windows from what I understand.

macOS's default file system isn't case sensitive.

**Comment by ApertureSecurity** [comment]
Not case sensitive eh? I used it before and I though it was. I was using bash in the terminal mostly , I wonder if there was a change or if I missed something. 

I stand corrected then )
At any rate it would bad programming to have mixed cases and such .I think it would make a lot of unfairness changes to compensate for making one file lowercase. 

I thought at one point to keep the original file name(DIABDAT.MPQ)  and have linux look for that only.

**Comment by AJenbo** [comment]
It is a slippery slop. If we do it for the mpq, then why not also for all mods and direct file access?

Wine is forced to do something similar and is not happy about it:
https://wiki.winehq.org/Case_Insensitive_Filenames

**Comment by ssjkakaroto** [comment]
> > couldn't you call grep (on *nix systems) to get the file name before passing it to devilutionx? My original Diablo cd has that file in uppercase, but devilutionX expects it in lowercase.
> 
> You need to learn linux and don't know the operating system you're using. Take some time to learn the O.S first before making such requests. You'll run into this on every O.S except for windows from what I understand.
> 
> I think we should close this case.

That's exactly why I mentioned *nix systems and it was a question, not a request. I guess you couldn't see that I wasn't the OP.

**Comment by predator8bit** [comment]
Like I said here: https://github.com/diasurgical/devilutionX/issues/55#issuecomment-495706654 creating a symlink could work around this issue.
