### ISSUE TITLE
Game crashes when trying to melee any Balrog monster type

### ISSUE THREAD

**Issue by FireIceTalon** [diasurgical/devilutionX#5624]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

When trying to engage any Balrog monster type with melee, the game crashes. Sometimes it happens on the first Balrog you try to fight, other times it takes a few. It doesn't happen when you fight them with missiles, only melee. Taking place on multi-player Diablo 1.

### To Reproduce

Go to any level that has a Balrog monster type, engage and try to attack it using a melee attack.

### Expected Behavior

To engage and attack as normal

### Additional context

Using build [f325030](https://github.com/diasurgical/devilutionX/commit/f325030af9a9b4c0be2d2269e4cab33943f5bdee)

**Comment by kphoenix137** [comment]
Problem occurs in `animationinfo.cpp` in the function `setNewAnimation`. I was able to use SDL_Logs to see what was being assigned to variables at the time of the crash. When inflicting hit recovery on a Balrog, I got the following:
`INFO: CALLING setNewAnimation -----------------------
INFO: revelantAnimationTicksWithSkipping = relevantAnimationTicksForDistribution (1) - (numSkippedFrames (0) * ticksPerFrame (1)
INFO: relevantAnimationTicksWithSkipping is now 1
INFO: relevantAnimationTicksWithSkipping (1) -= 1
INFO: relevantAnimationTicksWithSkipping is now 0
INFO: relevantAnimationTicksWithSkipping (0) *= baseValueFraction (128)
INFO: relevantAnimationTicksWithSkipping is now 0
INFO: relevantAnimationTicksWithSkipping (0) += previewShownGameTickFragments (0)
INFO: relevantAnimationTicksWithSkipping is now 0
Exception thrown at 0x00007FF7B30666DE in devilutionx.exe: 0xC0000094: Integer division by zero.
Unhandled exception at 0x00007FF7B30666DE in devilutionx.exe: 0xC0000094: Integer division by zero.`

The game is attempting divide by `relevantAniimationTicksWith` skipping while it is set to 0.

**Comment by kphoenix137** [comment]
I reverted #5469 to see if there was any difference, but no.

Currently investigating #5469 as it's the only merged PR that makes changes to this function within the last 5 months.

**Comment by kphoenix137** [comment]
To expand on my previous comment, the `numberOfFrames` argument here is `1` for Balrog monster class hit recovery. It's not playing well with the math being done in this function as seen here:

INFO: CALLING setNewAnimation -----------------------
INFO: relevantAnimationFramesForDistributing = numberOfFrames (1)
INFO: relevantAnimationFramesForDistributing is now 1
INFO: relevantAnimationTicksForDistribution = relevantAnimationFramesForDistributing (1) * ticksPerFrame (1)
INFO: relevantAnimationTicksForDistribution is now 1
INFO: revelantAnimationTicksWithSkipping = relevantAnimationTicksForDistribution (1) - (numSkippedFrames (0) * ticksPerFrame (1)
INFO: relevantAnimationTicksWithSkipping is now 1
INFO: relevantAnimationTicksWithSkipping (1) -= 1
INFO: relevantAnimationTicksWithSkipping is now 0
INFO: relevantAnimationTicksWithSkipping (0) *= baseValueFraction (128)
INFO: relevantAnimationTicksWithSkipping is now 0
INFO: relevantAnimationTicksWithSkipping (0) += previewShownGameTickFragments (0)
INFO: relevantAnimationTicksWithSkipping is now 0
Exception thrown at 0x00007FF7AEAA676B in devilutionx.exe: 0xC0000094: Integer division by zero.
Unhandled exception at 0x00007FF7AEAA676B in devilutionx.exe: 0xC0000094: Integer division by zero.

**Comment by kphoenix137** [comment]
When testing with the build immediately before the PR for AnimationInfo: Used fixed point math, I noticed that it still attempts to divide by 0, but using floats, and does not crash. The result is that `tickRate` = 0.
