### ISSUE TITLE
Controller mapping not working

### ISSUE THREAD

**Issue by CyberKiller40** [diasurgical/devilutionX#5641]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

I created a simple mapping to swap A/B and X/Y buttons to make the controller work as the normal xbox layout
`030000006d0400001fc2000000007801,swapab,platform:Windows,a:b1,b:b0,x:b3,y:b2,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,`
I set it as the env var, rebooted to be sure, not worked. So I added it to the config file like
```
[Controller]
Mapping=030000006d0400001fc2000000007801,swapab,platform:Windows,a:b1,b:b0,x:b3,y:b2,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,
```
Still no effect, neither in main menu, nor in the game.

### To Reproduce

Set the controller mapping to
`030000006d0400001fc2000000007801,swapab,platform:Windows,a:b1,b:b0,x:b3,y:b2,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,`
and run the game.

### Expected Behavior

The A and B buttons are swapped - like the xbox layout.

### Additional context

Windows 7 64bit
Logitech F710 gamepad
Diablo from GOG, running with Hellfire

**Comment by AJenbo** [comment]
make sure that the tool is using the same SDL version, or use the 1.5.0 beta where you can remap from the settings menu

**Comment by CyberKiller40** [comment]
It was 2.0.7 vs 2.0.20, hard to believe a minor version would break compatibility, but I just checked and libsdl doesn't use semver, so I guess all bets are off.

**Comment by AJenbo** [comment]
they changed to semver recently
