### ISSUE TITLE
Update to ubuntu-20.04 for Linux binaries

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#5655]
Ubuntu 18.04 EOL is April 30th, 2023.
Let's update our Linux binary builds to Ubuntu 20.04.

**Comment by AJenbo** [comment]
On a side note I'm also ok with upgrading the x86_64 Linux builds to Buster or equivalent at this point.

**Glibc versions**
Ubuntu 20.04: 2.31
Buster: 2.28
Stretch: 2.24

**Comment by glebm** [comment]
20.04 is actually based on Bullseye so I've switched to that in #5656

**Comment by glebm** [comment]
Why is Bullseye aggressive but 20.04 isn't? They're the same version.
Buster EOL'd on 2022-09-10.

**Comment by AJenbo** [comment]
20.04 is also aggressive :)

Isn't buster covered by the LTS program until 2024? The Debian dokumentation is a bit fuzzy here admittedly.

**Comment by glebm** [comment]
End-of-life dates:

1. Buster https://wiki.debian.org/DebianReleases: [2022-09-10](https://www.debian.org/News/2022/20220910)
2. Ubuntu 18.04 https://ubuntu.com/about/release-cycle: April 30th, 2023

I don't think it's aggressive to not support EOL releases?

**Comment by glebm** [comment]
Note that LTS security support is done by a separate team. It's a best effort support and users should update to a non-EOL release as soon as possible.

**Comment by AJenbo** [comment]
Switching to Bullseye/20.40 would mean that the releases would not work with Ubuntu 18.04 (glibc 2.27) which is still a support version. By May I'm fine with us upgrading to 20.04 for the release builds.

**Comment by AJenbo** [comment]
Mental not, try to get 1.5.0 ready for release before April 30th

**Comment by glebm** [comment]
I've updated the PR to use `debian:buster` for the only (?) release build, and Ubuntu 22.04 elsewhere
