### ISSUE TITLE
Choosing difficulty in multiplayer

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#566]
**Describe**
Character level's seems to only be checked when selecting the character, but you go back to point after character selection when leaving multiplayer game = level doesn't get updated = couldn't enter nightmare with lvl 20 char, had to go back to character selection to make it work

**To Reproduce**
Enter multi with lvl 19 char, get lvl 20 during the game, leave the game, try to enter nightmare

**Expected behavior**
The character is lvl 20 so it can enter nightmare = enters nightmare

**Comment by galaxyhaxz** [comment]
Might be worth changing to `pDiabloKillLevel` instead, that way like in diablo 2 you just complete diablo on each difficulty.

**Comment by AJenbo** [comment]
@qndel can please check to sed if the issue is solved for you?

**Comment by qndel** [comment]
not really, I got rid of that char long time ago :)

**Comment by AJenbo** [comment]
Hmm didn't work for me :(
