### ISSUE TITLE
Xbox One build fails with  error APPX0108: The certificate specified has expired. 

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#5661]
This is a different error from zlib failing to download:

>     2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(4704,5): error APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478. [D:\a\devilutionX\devilutionX\uwp-project\devilutionx.vcxproj]

@fwannmacher

**Comment by fwannmacher** [comment]
I'll have a look on those

**Comment by fwannmacher** [comment]
https://github.com/diasurgical/devilutionX/pull/5665

**Comment by AJenbo** [comment]
@fwannmacher there still appears to be some issue:
> Certificate file 'devilutionX_TemporaryKey.pfx'

https://github.com/diasurgical/devilutionX/pull/5666

**Comment by fwannmacher** [comment]
https://github.com/diasurgical/devilutionX/pull/5669 now the error is related to ZLIB :/

**Comment by AJenbo** [comment]
That at least brings it back to where it was last week, so you actually fixed the issue for this report :)

**Comment by glebm** [comment]
I've triggered a rerun of the failed job

**Comment by fwannmacher** [comment]
```
  -- Using src='https://www.zlib.net/zlib-1.2.13.tar.gz'
  -- verifying file...
         file='D:/a/devilutionX/devilutionX/build/_deps/zlib-subbuild/zlib-populate-prefix/src/zlib-1.2.13.tar.gz'
  -- MD5 hash of
      D:/a/devilutionX/devilutionX/build/_deps/zlib-subbuild/zlib-populate-prefix/src/zlib-1.2.13.tar.gz
    does not match expected value
      expected: '9b8aa094c4e5765dabf4da391f00d15c'
        actual: 'bf8e7f3081d3d52ed195a2a1c1ba0fa5'
  -- Hash mismatch, removing...
  -- Using src='https://www.zlib.net/fossils/zlib-1.2.13.tar.gz'
  -- verifying file...
         file='D:/a/devilutionX/devilutionX/build/_deps/zlib-subbuild/zlib-populate-prefix/src/zlib-1.2.13.tar.gz'
  -- MD5 hash of
      D:/a/devilutionX/devilutionX/build/_deps/zlib-subbuild/zlib-populate-prefix/src/zlib-1.2.13.tar.gz
    does not match expected value
      expected: '9b8aa094c4e5765dabf4da391f00d15c'
        actual: '17cb44aadf7bf77465665e19457e53ab'
  CMake Error at zlib-subbuild/zlib-populate-prefix/src/zlib-populate-stamp/download-zlib-populate.cmake:170 (message):
    Each download failed!
```

I have downloaded and checked the MD5 manually and everything looks good. It looks like the downloads are getting just a piece of the file.

**Comment by fwannmacher** [comment]
> I've triggered a rerun of the failed job

Same error :/

**Comment by glebm** [comment]
Sent https://github.com/diasurgical/devilutionX/pull/5670
