### ISSUE TITLE
cmake --install does not install anything with smpq absent

### ISSUE THREAD

**Issue by kruceter** [diasurgical/devilutionX#5664]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

I am trying to update your engine in https://github.com/void-linux/void-packages/pull/41658 to the latest version.

For one reason or another void does not have `smpq` packaged in the repository, so here I am.

In my understanding, smpq is an optional dependency here, so I assume that with this archiver absent asset files are supposed to be included and installed instead.

The current and temporary solution for me was this dirty hack

```diff
--- /dev/null
+++ b/srcpkgs/devilutionX/patches/smpq.patch
@@ -0,0 +1,19 @@
+If smpq is not present (in our case not packaged for void at all),
+cmake --install will not install anything to DESTDIR.
+
+DEVILUTIONX_MPQ is used during the installation to DESTDIR, but
+undefined if smpq is not found (see CMake/Assets.cmake),
+thus it is also set in this patch.
+
+--- a/CMakeLists.txt
++++ b/CMakeLists.txt
+@@ -405,7 +405,8 @@
+   target_compile_definitions(libdevilutionx PRIVATE __UWP__=1)
+ endif()
+ 
+-if(CPACK AND (APPLE OR BUILD_ASSETS_MPQ OR SRC_DIST))
++if(CPACK)
++  set(DEVILUTIONX_MPQ "${CMAKE_CURRENT_BINARY_DIR}/devilutionx.mpq")
+   if(WIN32)
+     if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
+       set(SDL2_WIN32_DLLS_DIR "${CMAKE_BINARY_DIR}")
```

From seeing `CMakeLists.txt`, the installation process deeply involves devilutionx.mpq without giving space for assets, so `mpqtool` (written in rust, unfortunately) was used in `post_build()` to make `devilutionx.mpq` before invoking `cmake --install` to satisfy the installation script.

Also our main concern is that `smpq` is turned into abandonware with its last release in 2016, and the last change to the code in 2018.

### To Reproduce

1. Build without smpq installed.
2. Execute `cmake --install`.

### Expected Behavior

Assets are supposed to be installed

**Comment by AJenbo** [comment]
What's wrong with Rust?

**Comment by kruceter** [comment]
> What's wrong with Rust?

Nothing. Aside from that, mpqtool works perfectly well for creating `devilutionx.mpq` without any side-effects.

**Comment by kruceter** [comment]
I jumped into conclusions too quickly.

It seems you already provide the tarball with `devilution.mpq` shipped. Not only that, you also have all 3rd party dependencies bundled there.

If I use this one, the need for patching and use of mpqtool/smpq falls out.

Thank you for being so considerate about using this approach.

My sincere apologies for spending your time to read my issue. Closing the issue as "not planned".

**Comment by AJenbo** [comment]
No worries

**Comment by glebm** [comment]
@kruceter You should use `devilutionx-src.tar.xz` rather than the `fully-vendored` one. It still includes `devilutionx.mpq` and dependencies that must be vendored (because they contain devilutionx-specific patches) but does not include e.g. SDL2. With the fully-vendored one, you're building and statically linking **all** the dependencies, which is usually not what package managers want.

**Comment by kruceter** [comment]
> It still includes `devilutionx.mpq` and dependencies that must be vendored (because they contain devilutionx-specific patches) but does not include e.g. SDL2.

Just skimmed through `tools/make_src_dist.py` and you are right: the repo already has googletest, sdl2, sdl_image, libpng (I think it is not used in your project?), libfmt, bzip2, and libsodium.

> and dependencies that must be vendored

Like `asio`, I get it.

> With the fully-vendored one, you're building and statically linking **all** the dependencies, which is usually not what package managers want.

Caught myself with this phenomena, so I used `-DDEVILUTIONX_SYSTEM_<LIB>=ON` to mitigate these effects.

I guess I will just swap the tarball and remove unneeded flags at some point.


Thank you once again for dedicating your time to explain the difference between those two tarballs.

**Comment by AJenbo** [comment]
libpng is actually used, the touch interface graphics is loaded from PNG files. It's not used when linking with SDL1 since it doesn't have touch support.

googletest is an optional dependency (tests can be disabled with a cmake flag)
