### ISSUE TITLE
Stuck at menu. controls are unresponsive

### ISSUE THREAD

**Issue by HagenKemal** [diasurgical/devilutionX#5687]
### Operating System

PlayStation Vita

### DevilutionX version

1.4.1 (latest release)

### Describe

I have been trying to get this to working since 3 days. The homebrew starts, the menu of hellfire shows and the 2 pentagram icons are spinning but the controls are not working. I cannot move the cursor or start the game. I have tried v1.4.1 - 1.4.0 and 1.3.0 all with the same issue. My vita is a slim version and it is on 3.65 enso. quake 3 and 2 are working but have the same problem with quakespasm-spiked v1.6. Any help would be appreciated 

### To Reproduce

start the vpk
wait

**Comment by AJenbo** [comment]
Sounds like this is an issue with the console and not the games since multiple are showing the behavior. It would probably be best to ask on a vita forum for how to solve it. Maybe try upgrading things. Or switch to a known stable version.

**Comment by HagenKemal** [comment]
Solution is removing MiniVitaTV plugin.

**Comment by AJenbo** [comment]
Nice that you figured it out
