### ISSUE TITLE
Tricky to build for arm32 and aarch64 because of libzt

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#5689]
ZeroTier on aarch64 requires the ArmV8A Crypto Extension.
This extension is optional and not all CPUs support it.

If the CPU does not support it, currently ZeroTier has to be disabled entirely.

Additionaly, ZeroTier apparently tries to use crypto extensions on arm32, which is never supported.

Example from a distro: https://github.com/batocera-linux/batocera.linux/blob/4a2d3af26b15f2a1852d6addede9385500289285/package/batocera/ports/devilutionx/devilutionx.mk#L22-L31

ZeroTier should instead check if the extension is supported and fall back to the non-accellerated implementation if it isn't.

@StephenCWills 

Also filed https://github.com/zerotier/libzt/issues/205 in libzt

**Comment by glebm** [comment]
I've sent a fix to ZeroTierOne in https://github.com/zerotier/ZeroTierOne/pull/1855

@StephenCWills Can you please merge it into our libzt / ZeroTierOne fork?

**Comment by StephenCWills** [comment]
I noticed your note...

> This check should ideally happen in the source file using compiler macros, rather than in the build system

And your fix certainly does that, but something still needs to be done in the build system to detect whether the compiler flag should be included, right?

**Comment by glebm** [comment]
> And your fix certainly does that, but something still needs to be done in the build system to detect whether the compiler flag should be included, right?

No:
1. When cross-compiling, that's up to the system / distro / the person compiling.
2. When compiling for host, if you use `-march=native` and your CPU supports the crypto extension, the macro will be defined by the compiling.

**Comment by StephenCWills** [comment]
How would you use `-march=native`? Is that added automatically when not cross-compiling?

Was this a bad idea: https://github.com/zerotier/libzt/pull/164? Now I'm worried that there might be some Android CPUs that don't support the extensions.

**Comment by glebm** [comment]
> Was this a bad idea: https://github.com/zerotier/libzt/pull/164

Yeah, https://github.com/zerotier/libzt/pull/164 is wrong, a ton of CPUs do not support the crypto extension (including the one in Raspberry Pi 4).

It is up to the user to set the target architecture or provide the right toolchain file.
This kind of thing should never be done by the library's CMake.

The default compiler flags (whether `-march=native` is included) depends on the distribution.
Generally, distributions "for the masses" such as Ubuntu do not set it by default.

**Comment by glebm** [comment]
Per https://github.com/diasurgical/devilutionX/issues/5275#issuecomment-1398775041, this is now fixed! 🎉
