### ISSUE TITLE
Hashes of valid diabdat.mpq

### ISSUE THREAD

**Issue by ssjkakaroto** [diasurgical/devilutionX#57]
According to [this reply](https://github.com/diasurgical/devilutionX/issues/53#issuecomment-475871700) by @AJenbo there is more than one valid diabdat.mpq. Is there a list of versions/hashes available anywhere?

This is the one I have in my 1.00 cd:

Name: DIABDAT.MPQ
Size: 517501242 bytes (493 MB)
CRC32: 855951D6
CRC64: 91EB406CA29379C7
MD5: 68F049866B44688A7AF65BA766BEF75A
SHA256: 6BC120A603FDB383FF91F374E7DB599765D6230D81E5A4C1B33F8254911774E7
SHA1: FE35CBA676A0A194CCDF1D4357DE49DFF252FA40
BLAKE2sp: 86F1016C2BFBAE621EFA9F7789537154DCC20BC66238519CC883D0F6E816E40F

**Comment by AJenbo** [comment]
Yours is the original US version, it has a broken logo video. There are no more known diabdat.mpq versions (except pirated striped down versions, for obvious reasons we do not support these).

See this issue on free about for the list and future reference: https://github.com/wheybags/freeablo/issues/427
