### ISSUE TITLE
Severe: Game crash

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#5709]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

Commit 1401e130

Game crashes with assertion failure.

### To Reproduce

1. Toggle on "Show Graphics in Stores"
2. Create multiplayer game
3. Talk to Griswold

**Comment by Trihedraf** [comment]
Also happening for me. Debug minGW x86.

**Comment by AJenbo** [comment]
What is the assertion?

**Comment by AJenbo** [comment]
```

ERROR: Error
assertion failed (C:\Users\Eric\Documents\GitHub\devilutionX\Source\engine/clx_sprite.hpp:616)
value_.data_ != nullptr
The thread 0x3758 has exited with code 0 (0x0).
avcore\audiocore\client\audioclient\audioclientcore.cpp(1907)\AUDIOSES.DLL!00007FF9D77B3EF5: (caller: 00007FF993683F12) ReturnHr(1) tid(47c8) 80070057 The parameter is incorrect.
```
