### ISSUE TITLE
Cow Rendering Bug

### ISSUE THREAD

**Issue by mgpat-gm** [diasurgical/devilutionX#571]
**Describe**
When moving character in town from left to right the top two cows do not appear correctly.

**To Reproduce**
1. Get the cows to where they are one tile movement from appearing on the right side of the screen.
2. Move character one tile to the right.
3. Cows suddenly appear.

**Expected behavior**
Portions of the cow should already be visible.

**Screenshots**
![cows](https://user-images.githubusercontent.com/60494513/73597011-e3569500-44f5-11ea-8afc-d69224f3a018.png)

**Additional context**
Version 1.0.0 prebuilt
Ubuntu 18.04 (updated)
GTX 1080
Ryzen 3900x

**Comment by qndel** [comment]
only the cows? can't you do the same with npc?

**Comment by AJenbo** [comment]
Yeah this is a general bug with all sprites.

**Comment by qndel** [comment]
doesn't it happen because cow takes more than 1 tile and the game doesn't know that 1 tile below there's a cow that should be partially visible? :P

**Comment by mgpat-gm** [comment]
I assumed it was only an issue with the top two cows because they are left/right oriented. The buffering for the rest of the NPCs takes place before my screen hits them. I can confirm it does not happen with the other NPC sprites.

**Comment by AJenbo** [comment]
This happens with monsters etch and it's also in the original game. This will be fixed as part of the render rewrite, so closing this for now.
