### ISSUE TITLE
Stuck walking to a direction when entering or exiting a floor playing with a controller.

### ISSUE THREAD

**Issue by daedrixxx2** [diasurgical/devilutionX#5716]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Test Build Windows MinGW x64 named "Do not create Hellfire sprites in Diablo" commit https://github.com/diasurgical/devilutionX/commit/f9f61fcb0c652445f0f8fd11f7d8c31b54f87e14

When changing floors the character remains stuck walking to a direction (as if I were pressing "Up" on the d-pad).
To resolve the bug one has to enter the Game Menu (Esc) and press each direction on the d-pad once.

It doesn't seem to happen if playing exclusively with Mouse + Keyboard.

### To Reproduce

Just start a New Game and enter the Church Dungeon.
Sometimes the bug happens immediately, others it is triggered by exiting the dungeon and re-entering again.

**Comment by AJenbo** [comment]
Can confirm this happened to me on PS2 as well
