### ISSUE TITLE
Resurrect Crash in MP

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#5717]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

commit 81c7d061

Game crashes when Resurrecting players in Multiplayer. Tested in D1.

Call Stack:
![image](https://user-images.githubusercontent.com/68359262/214157224-771f3562-7bfb-4e83-bd9a-c746ff6bedc6.png)

### To Reproduce

1. Create multiplayer Diablo game
2. Have 2 players in game
3. Cast Resurrect on a dead player

**Comment by glebm** [comment]
`CalcPlrInv` is called and eventually accesses the South sprite, which does not exist for the Death player graphics.

https://github.com/diasurgical/devilutionX/blob/c99f7cf644907256cdde103b6cda03fe07d5a1d2/Source/spells.cpp#L296-L302

It is called before `StartStand`, which changes the player graphics.

**Comment by kphoenix137** [comment]
> I think this might be the cause:
> 
> `CalcPlrInv` is called and eventually accesses the South sprite, which does not exist for the Death player graphics.
> 
> https://github.com/diasurgical/devilutionX/blob/c99f7cf644907256cdde103b6cda03fe07d5a1d2/Source/spells.cpp#L296-L302
> 
> It is called before `StartStand`, which changes the player graphics to the Stand variant.

Looking at the death graphics, it appears there is a "dying" animation for all 8 facing directions?

**Comment by glebm** [comment]
IIRC think the "corpse" one only has one direction.
Perhaps we need to do player._pmode = PM_STAND; before the call to CalcPlrInv?

**Comment by glebm** [comment]
Here is the place where it crashes (line 2638):

https://github.com/diasurgical/devilutionX/blob/3eed9228ab195c4ff11567eca3f43963892136f6/Source/items.cpp#L2626-L2642
