### ISSUE TITLE
Ground Tile Rendering Grey

### ISSUE THREAD

**Issue by mgpat-gm** [diasurgical/devilutionX#572]
**Describe**
When I first join a game the right floor tile is grey next to the building.

**To Reproduce**
1. Start single or multiplayer game
2. See tile adjacent to the closest building on the top right.

**Expected behavior**
This tile should match the ground.

**Screenshots**
![tile](https://user-images.githubusercontent.com/60494513/73597132-eef68b80-44f6-11ea-86db-9099c29d4416.png)

**Additional context**
Version 1.0.0 (prebuilt)
Ubuntu 18.04 (updated)
GTX 1080
Ryzen 3900x

**Comment by AJenbo** [comment]
Sorry I don't see it, could you do one with the correct on and one with the wrong one so we can compare

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/73598409-40733a80-4538-11ea-9b51-0b72ee89224c.png)
is this the thing?

**Comment by mgpat-gm** [comment]
That's the "thing". AJenbo I cannot show it correct because I do not have a windows system to test the original game.

**Comment by AJenbo** [comment]
This is a hole in the town map, not something specific to DevilutionX and fixing it requires patching the data so out of scope for what we are doing atm. You can report original issues like this in the upstream bucket issue: https://github.com/diasurgical/devilution/issues/64
