### ISSUE TITLE
Provide sensible resolution when upscaling is enabled

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5723]
For Android and iOS only the max resolution is suggested isn't the OS doesn't provide a method for changing the screen resolution. This means that users only have the option between 640x480 and 4k on some devices, not very useful.

So in case the OS only reports a single resolution it would be nice if we can check if up-scaling is enabled and in that case generate some sensible alternatives below that size.

This can also help to mitigate that the UI will sometimes overlap on devices that aren't 21:9

**Comment by AJenbo** [comment]
> The maximum possible integer-scaled 4:3 resolution

Considering that we are talking internal resolution maybe this one doesn't make that much sens since you would get a very large view. Fit to aspect + interger scaling would instead give a meaningful result.

**Comment by StephenCWills** [comment]
Good point. Also, maybe we should include 1280x960 since some players seem to prefer that coupled with the zoom flag.
