### ISSUE TITLE
Oil of Accuracy not applying To Hit bonus

### ISSUE THREAD

**Issue by Voths** [diasurgical/devilutionX#5725]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

The Hellfire item Oil of Accuracy is not increasing the To Hit % on items that already have such a modifier on them such as King's or Silver.  The bonus does not apply either to the weapon directly or on the character sheet.

When applied to an item that does not have a To Hit % modifier on it, the oil does work.  

### To Reproduce

1.  Apply Oil of Accuracy to an item with a preexisting To Hit % modifier.
2.  Check the item description and character sheet to see that your To Hit score has not increased by 1%.
3.  Apply Oil of Accuracy to an item without a preexisting To Hit % modifier.
4.  Check the character sheet to see that your To Hit score has increased by 1%.

### Expected Behavior

The To Hit % of the item the oil is applied to increases by 1%, up to a maximum of 100% to hit.

### Additional context

There is another item in the game called Oil of Mastery which does the same effect but gives more than 1%.  This item does work on items that already have a To Hit % modifier on them leading me to believe it is a problem solely with the Oil of Accuracy.

**Comment by StephenCWills** [comment]
This is how Oil of Accuracy has always worked. It can't raise CTH on a weapon above 50%. Also, Oil of Mastery only works up to 100%.
