### ISSUE TITLE
Guardian damage

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#5729]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

The intended damage for the Guardian spell in the AddGuardian function https://github.com/ikonomov/DiabloX/blob/df3a990f0d596492769c4f662a9de783f80d1aec/Source/missiles.cpp#L2038 is never used because it uses the missiles and damage of Firebolt.

### To Reproduce

normal gameplay

### Expected Behavior

Guardian should use its own damage formula

**Comment by DakkJaniels** [comment]
See #5731
