### ISSUE TITLE
Error message when Web-Browser is opened on Haiku OS.

### ISSUE THREAD

**Issue by Kitsune64** [diasurgical/devilutionX#575]
**Describe**
devilutionX give me an error message when a web-browser is opened at same time than the launcher on Haiku OS.

**To Reproduce**
1. Building and install devilutionX on Haiku x86_64
2. Launch a web browser
3. Launch devilutionX at same time.

**Expected behavior**
Return to desktop with a error message.

Error log:
Debug information for team /boot/system/apps/devilutionx/devilutionx (9549):
CPU(s): 1x AMD Phenom II
Memory: 2.00 Gio total, 796.38 Mio used
Haiku revision: hrev52295+132 Jan  5 2020 07:51 (x86_64)

Active Threads:
        thread 9550: MidiRosterLooper
        thread 9551: MidiEventThread
        thread 9552: SDLTimer
        thread 9553: SDLApplication
        thread 9563: direct daemon
        thread 9564: drawing_thread
        thread 9565: w>DevilutionX
        thread 9567: team 9549 debug task
        thread 9549: devilutionx (main)
                state: Exception (Segment violation)

**Additional context**
This is done on Haiku OS operating system with the last version 5 of devilutionX

**Solution**
Close the browser before running devilutionX "resolve" this error.

**Comment by AJenbo** [comment]
Thanks for the report, but this more like an issue in Haiku, possibly SDL. You mentioned version 5, is that 0.5.0? Have you tried 1.0.0?

**Comment by qndel** [comment]
`last version 5 of devilutionX` ?? devilutionx has 1.0 version

**Comment by Kitsune64** [comment]
I have see V in DevilutionX when I launch Diablo...
I believed that this symbol represented the 5 in Roman numeral. I have downloaded sources and build it today. Don't find the version then...

**Comment by AJenbo** [comment]
The "v" stands for "version", this is missing the version number then. Probably you downloaded the source in a zip file instead of via git, in which case the version information will be missing.

Did you build a debug or release?

**Comment by Kitsune64** [comment]
Yes I have compiled from a zip file downloaded here. I build it following the cmake command in the readme file:

cd build
cmake ..
cmake --buil. -j $(nproc)

I just have disable "lubsan" (that give me error when compiling) Haiku 64 don't have this library for now.

**Comment by AJenbo** [comment]
Try doing a release build instead, first clear you build folder then run:
```
`cmake .. -DBINARY_RELEASE=ON`
 cmake --buil. -j $(nproc)
```

**Comment by Kitsune64** [comment]
I have a lstdc error when I follow these steps..But I have take the git package before run your commands by:

> git clone https://...

I don't have this error before with the zipped version. Haiku don't have the stdc++ library apparently.

**Comment by AJenbo** [comment]
Please try commenting out the following line and make a release build:
https://github.com/diasurgical/devilutionX/blob/master/CMakeLists.txt#L439

Also I recommend that you check out 1.0.0 (71d8a00), you can do that by running `git checkout 71d8a00`.

**Comment by AJenbo** [comment]
Closing as there has been no response for a few days and everything points to this being a Haiku issue.

**Comment by Kitsune64** [comment]
Sorry i don't really understand the  previous post about "commenting out" the lines.

Maybe you wait something like it?
line 106:

```
if(HAIKU)
  set(ASAN OFF)
  set(UBSAN OFF)
endif()
```

Cause I have disable it into the build.

**Comment by AJenbo** [comment]
Sorry the link I gave you wasn't permanent so it points to the wrong section since there have been changes to the files in the mean time, the part I want you to remove is:
`  target_link_libraries(${BIN_TARGET} PUBLIC -static-libgcc -static-libstdc++)`
clean you build folder, then run
```
cmake .. -DBINARY_RELEASE=ON
cmake --buil. -j $(nproc)
```

**Comment by Kitsune64** [comment]
Your method work great in Haiku when I remove this line from the Cmakelists.txt file.

But someone had building DevolutionX on Haiku system before me. I saw it later...A prebuild paquage on this system is already available for now.

Thanks

**Comment by AJenbo** [comment]
Thanks for testing, I'll fix the Haiku builds, do you still have the browser conflict with the most recent build you did?

It looks like the prebuild package isn't a release build, but a debug version with all debug features disabled. But your machine would have to be pretty old for it to make much of a difference :)

**Comment by Kitsune64** [comment]
The browser bug seem disappear for now with this method.

I test it on a Virtual Box machine with Haiku installed on it here.

**Comment by AJenbo** [comment]
I fixed the Haiku builds now so no more workarounds needed. I'm still pretty sure that the crash you where having is a bug in Haiku so you may wan to report that to them.

**Comment by Kitsune64** [comment]
I don't know why exactly do this app crashed? Is it about SDL or is it about the web server?

**Comment by AJenbo** [comment]
You will have to have ask the Haiku developers, one app being able to crash another is a serious issue in an operating system, unless it's because your system is out of memory.
