### ISSUE TITLE
Bad rewards from the chests in the quest "Leoric's Tomb" and "Chamber of bone"

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5757]
I've noticed for a while that there are very low quality items in the chests from the above quests.
The value of the items is often only slightly more than the value of 100 gold coins.
I'm relatively sure that the value of the items should be much higher.
I would ask all contributors to at least confirm the issue, so we can narrow it down soon.

**Comment by Chance4us** [comment]
The suspicion is hereby confirmed.
Here is a comparison of the list of items received.

Vanilla first pass:
1. Bow of plenty - 562
2. Deadly Bow - 742
3. Ravens Staff of Elemental - 5225
4. Jagged Staff of Reflect - 754
5. Buckler of Vim - 630
6. Silver Scimitar - 775
[vanilla_pass_1.zip](https://github.com/diasurgical/devilutionX/files/10679247/vanilla_pass_1.zip)

Vanilla second pass:
1. Grand Mail of Craftmanship - 1688 gold
2. Sword of Swiftness - 1750 gold
3. Deadly Bow - 764 gold
4. Armor of Stability - 1300 gold
5. Sword of Strength - 950 gold
6. Red Staff of Manashield - 2050 gold
[vanilla_pass_2.zip](https://github.com/diasurgical/devilutionX/files/10679251/vanilla_pass_2.zip)

Devilutionx only one pass:
1. Blade of Light - 327
2. Jagged Short Sword - 189
3. Scimitar of Quality - 150
4. Hunter's Bow of Many - 362
5. Cap of Health - 57
6. Book of Search - 750
[devilutionx.zip](https://github.com/diasurgical/devilutionX/files/10679253/devilutionx.zip)

So we only have to determine since which commit the issue has appeared.

**Comment by Chance4us** [comment]
I have the impression that the repair does not work. But I will retest and report the result.
Below are items from my last game and they are not of good value.

![1](https://user-images.githubusercontent.com/45902449/222407741-c318c86c-6ff0-4f2c-958c-0f0de6b29cdd.png)
![2](https://user-images.githubusercontent.com/45902449/222407785-505960f8-7233-49df-a883-1039dd059ea9.png)

There is a high probability that we will have to reopen this issue.

**Comment by Chance4us** [comment]
What I can say after some testing is that the loot averages around 6000 gold pieces.
It's not quite as high as before, but it's not bad either.
So I will test over a longer period of time and report back at some point.

**Comment by qndel** [comment]
@Chance4us wouldn't the ultimate test be saving before opening chests and open them in vanilla & devx and compare items (they should be the same) ?

**Comment by Chance4us** [comment]
> @Chance4us wouldn't the ultimate test be saving before opening chests and open them in vanilla & devx and compare items (they should be the same) ?


If the contents of the chests are only generated during opening, it makes a lot of sense.
Is it the case?

**Comment by qndel** [comment]
> > @Chance4us wouldn't the ultimate test be saving before opening chests and open them in vanilla & devx and compare items (they should be the same) ?
> 
> If the contents of the chests are only generated during opening, it makes a lot of sense. Is it the case?

You can easily check by loading a save twice and seeing if drops are the same lol, I'm assuming that's the case because I've never heard about people saving before opening a chest and farming loot that way ;) also it would break timedemos

**Comment by Chance4us** [comment]
I will check again this way :neckbeard: :grin:
