### ISSUE TITLE
Black Mushroom quest behavior

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5781]
The default behavior is as follows.
https://diablo-archive.fandom.com/wiki/Adria_(Diablo_I)#Black_Mushroom

Citation Quest Successful:
    "What? Now you bring me that elixir from the healer? I was able to finish my brew without it. Why don't you just keep it..."

In master the above sentence is missing, as soon you finish the quest.
What is also new is that the elixir turns red if it cannot/may not be used, but that is not a problem.

Spectral elixir red:
![spectral_elixir](https://user-images.githubusercontent.com/45902449/217844413-ac6757cc-cfc6-482a-ba5a-e97c1e358f57.png)

Missing speech/sentence:

https://user-images.githubusercontent.com/45902449/217844617-4c0afe1b-4106-4ce7-af87-680ff4a4ae76.mp4

Savegame:
[spectral_elixir.zip](https://github.com/diasurgical/devilutionX/files/10698326/spectral_elixir.zip)

**Comment by FitzRoyX** [comment]
> What is also new is that the elixir turns red if it cannot/may not be used, but that is not a problem.

It is though, this is only supposed to happen from unmet reqs.
