### ISSUE TITLE
Move save files between systems?

### ISSUE THREAD

**Issue by ArneAnka** [diasurgical/devilutionX#579]
Hi! Where do i find the save file on MacOS so i can move it to a Linux system?

**Comment by qndel** [comment]
Reading the text in the big "How To Play" section on main devilutionx page would've answered that question
https://github.com/diasurgical/devilutionX
"The data folder path may differ depending on OS version and security settings, but will normally be as follows:
macOS ~/Library/Application Support/diasurgical/devilution
Linux ~/.local/share/diasurgical/devilution/
Windows C:\Users\[username]\AppData\Roaming\diasurgical\devilution"
