### ISSUE TITLE
ConsumeScroll: Invalid item index 2

### ISSUE THREAD

**Issue by ChaosMarc** [diasurgical/devilutionX#5791]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

When using the town portal scroll from the right click menu the game crashes with the following error:

![image](https://user-images.githubusercontent.com/1343751/218476913-f04a6b46-0d90-4255-a52f-33c142b30d77.png)

When right clicking the scroll in the inventory everything is fine.

I'm using the latest Windows MinGW x64 master build (b46482f41481826e562477619820c25c2a0bd244) from here: https://github.com/diasurgical/devilutionX/actions/runs/4155463518

Savegame: [single_3.zip](https://github.com/diasurgical/devilutionX/files/10722838/single_3.zip)

### To Reproduce

1. load the attached savegame
2. right click somewhere to open a town portal
3. crash

**Comment by qndel** [comment]
4f9e9e04b1086141cda4361413a0c20dd03b72c7 is the first bad commit
commit 4f9e9e04b1086141cda4361413a0c20dd03b72c7
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sun Dec 18 15:01:02 2022 +0000

    Fix ConsumeScroll

**Comment by galaxyhaxz** [comment]
> Date: Sun Dec 18 15:01:02 2022 +0000
Fix ConsumeScroll

It's hilarious how a commit with that name caused this bug :P

**Comment by qndel** [comment]
Using a scroll by selecting it in spells and then right clicking doesn't set `spellFrom`, in this case 2 came from loading the save.

**Comment by qndel** [comment]
Casting nova crashes everyone else with index 3

**Comment by glebm** [comment]
item slot 2 is `INVITEM_RING_RIGHT` and 3 is `INVITEM_AMULET` :sweat_smile:

**Comment by obligaron** [comment]
This was fixed with #5988 and #5799
