### ISSUE TITLE
cannot build 32bit version

### ISSUE THREAD

**Issue by nsklaus** [diasurgical/devilutionX#58]
i did build a 64bit version, the game started but crashed upon trying to enter the church.
i was told to build the 32bit version instead, but the 32bit version doesn't seem to be able to compile properly, please see attached log.
[crashlog2.txt](https://github.com/diasurgical/devilutionX/files/2999521/crashlog2.txt)

**Comment by AJenbo** [comment]
You need to clear out your build folder to remove your previous 64bit CMake setup (`make clean` does not do this as it is a process after CMake), what you are building here appears to be a hybrid of 64 and 32bit and so the compile fails.

**Comment by nsklaus** [comment]
thanks for the help, but here's what i have now:
[crashlog3.txt](https://github.com/diasurgical/devilutionX/files/2999543/crashlog3.txt)
it seems it cannot find sdl2 now ?

**Comment by AJenbo** [comment]
You installed the 32bit version of SDL but ran the cmake command for configuring the 64bit build.

Notice this in the log:
```
CMake Warning at CMakeLists.txt:55 (message):
  Not 32-bit, highly experimental!
```

**Comment by nsklaus** [comment]
yes, i just noticed this, but you replied faster..
it built the 32bit version fine
my bad, apologies.

**Comment by AJenbo** [comment]
no worries
