### ISSUE TITLE
Backbone One controller for iOS not supported, SDl button mapping addition doesn't work.

### ISSUE THREAD

**Issue by 616dustin** [diasurgical/devilutionX#5804]
### Operating System

iOS

### DevilutionX version

1.4.1 (latest release)

### Describe

DevilutionX does not recognize the Backbone One controller, the on screen controls disappear if a controller button is pressed but no buttons correspond to actions in the game.

I have tried adding the SDL2 mapping to the diablo.ini file using SDL2 Gamepad Tool but it still does not recognize it.

### To Reproduce

1. start DevilutionX
2. connect Backbone One controller
3. press a button on the controller

### Expected Behavior

Buttons on the controller should correspond to actions in the game

### Additional context

SDL Mapping String

[Controller]
Mapping=030000005e0400008e02000000007801,Backbone One,a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,
Swap Shoulder Button Mode=0
Dpad Hotkeys=0
deadzone=0.070000

**Comment by AJenbo** [comment]
You should report this issue to https://github.com/libsdl-org/SDL as that is what handles controller support.

> I have tried adding the SDL2 mapping to the diablo.ini file using SDL2 Gamepad Tool but it still does not recognize it.

this is likely because it's using a different SDL version then the game, make sure to replace it's SDL dll with the same version as the game (for DevilutionX 1.4.1 that should be SDL 2.0.22 i belive)
