### ISSUE TITLE
Valor quest log plays King Leoric script

### ISSUE THREAD

**Issue by aronneu** [diasurgical/devilutionX#5829]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

In single player mode, I received the Valor quest in the Catacombs. Clicking the Book of Blood played the quest activation dialog as expected, "...And so, locked beyond the Gateway of Blood and past the Hall of Fire, Valor awaits for the Hero of Light to awaken..."

A few minutes later, I clicked on Valor in my quest log, and rather than replaying the Valor quest dialog, it instead played the following, "The dead who walk among the living follow the cursed King. He holds the power to raise yet more warriors for an ever-growing army of the Undead. If you do not stop his reign, he will surely march across this land and slay all who still live here." The Fandom wiki tells me that's Adria's comment on The Curse of King Leoric.

### To Reproduce

1. Activate the Valor quest (single player Catacombs level 5)
2. Open the quest log (Q)
3. Click on Valor within the quest to replay the quest dialog

### Expected Behavior

I expected to see and hear the quest dialog for the Valor quest

**Comment by StephenCWills** [comment]
Confirmed in 454efdc. This was tricky to reproduce, actually. It requires a few more steps.

1. Set game mode to Diablo.
2. Create a new Single Player game using the Bard class.
3. Go to dlvl 5 and activate the Valor quest.
4. Go to any dlvl other than 5 and save the game.
5. Load the game, open the quest log, and select Valor from the list.

The short version is that `TEXT_BBLOODY` is 264, which doesn't fit in an 8-bit unsigned integer.

https://github.com/diasurgical/devilutionX/blob/c2c0211ad8aaaab3d1b6050e0cb5e8f18890afe3/Source/loadsave.cpp#L1565-L1570
