### ISSUE TITLE
Streaming mp3 audio causes the game to crash

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#5832]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Tested in commit 6a5210e

I added some debug logging to see what audio file it was attempting to play when it crashed. This one occurred when I attempted to talk to Cain using `pl.mpq` from https://github.com/diasurgical/devilutionx-assets/releases/tag/v2.

```
DEBUG: PlaySfxPriv: sfx\towners\storyt25.wav
DEBUG: drmp3_init failed.
Exception thrown: read access violation.
this->stream_._Mypair.**_Myval2** was nullptr.
```

This same error seems to occur with any streamed mp3 file, such as the voice line that plays when the character first enters dlvl 1.

### To Reproduce

1. Install `pl.mpq` in the data directory
2. Set language to Polish (or hardcode `lang_mpq` in `LoadLanguageArchive()`)
3. Start a game, and go talk to Cain

### Expected Behavior

The game should play the audio

### Additional context

I also tried extracting `storyt25.mp3` and loading it directly from disk, but it didn't make a difference.

```
DEBUG: PlaySfxPriv: sfx\towners\storyt25.wav
VERBOSE: Loaded MPQ file override: ...\AppData\Roaming\diasurgical\debug\sfx\towners\storyt25.mp3
DEBUG: drmp3_init failed.
Exception thrown: read access violation.
this->stream_._Mypair.**_Myval2** was nullptr.
```

**Comment by realnc** [comment]
Looks like drmp3 fails on it, but aulib has a missing check on rwops creation. I pushed https://github.com/realnc/SDL_audiolib/commit/b2df2dfeddc692caa01fd1e1769f59b285912b87 that fixes it, but obviously this just prevents the segfault. It still won't play if drmp3 can't open it.

**Comment by AJenbo** [comment]
odd, i'm pretty sure this worked in 1.4.1

**Comment by StephenCWills** [comment]
Confirmed, I just talked to Cain without the game crashing in devilutionx-windows-x86_64 1.4.1 using `pl.mpq` v2. Also, if I extract them from the mpq, the mp3 files work fine in VLC.

**Comment by StephenCWills** [comment]
Bisected to 0dd95ad
