### ISSUE TITLE
Spell queuing not fixed for some spells

### ISSUE THREAD

**Issue by D1-Constantine** [diasurgical/devilutionX#5842]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

You can still double-cast Flash and Telekinesis.

### To Reproduce

Cast Flash , while the cast is proceeding right click again and then the Flash spell will be cast twice in a row. 

Right click (cast) Telekinesis twice, after your cursor changes to the Telekinesis one use it , shortly after another one will appear.

### Expected Behavior

The spells will be cast twice instead of once.

### Additional context

I'm using the latest master , but this is present in the game also in 1.4.1

**Comment by DakkJaniels** [comment]
Isn't the second spell supposed to be cast? I thought the issue was casting things when you don't have mana to cast them, or double casting scrolls. Is that still an issue?

**Comment by D1-Constantine** [comment]
No, the double-casting bug has been fixed , except for those two spells

**Comment by DakkJaniels** [comment]
For telekinesis, that seems to only happen for me if I click on the item before the 2nd cast has been completed. I don't know what's up with Flash, but I think that's an interesting quirk of the spell - as long as it isn't using mana that isn't there, I don't see why that double cast functionality should change. I did confirm that it will only do 1 cast if there is only enough mana for a single cast, even if you queue up the second cast.

**Comment by qndel** [comment]
"Love" when people say "latest master", how about actually providing the commit ? ;/

**Comment by DakkJaniels** [comment]
I just checked 55bf5348

**Comment by D1-Constantine** [comment]
> "Love" when people say "latest master", how about actually providing the commit ? ;/

I'm sorry I just don't know how to check.

**Comment by AJenbo** [comment]
check when you download

**Comment by StephenCWills** [comment]
> To clarify:
> I see no issue with telekinesis, you have to click before the second cast is done to have the cursor appear again.
> Flash I see as a unique quirk of the spell, not sure why it needs to be changed.

I can understand Flash since it seems like you're not supposed to be allowed to cast while `MyPlayer->_pInvincible == true`, but I also don't see the problem with Telekinesis. Note that you can spam Telekinesis like any other spell by simply spamming the right mouse button to continually clear the cursor between cast actions.

**Comment by D1-Constantine** [comment]
The problem with Telekinesis is that you get 2 executions of the spell for the cast duration of one.

**Comment by DakkJaniels** [comment]
Can you record what you see happening?

**Comment by D1-Constantine** [comment]
No , my patato laptop can't support any recording program :/

**Comment by DakkJaniels** [comment]
I haven't seen one cast duration result in two telekinesis cursors. I've only seen the second cursor show up after the 2nd cast has completed. It would help if we could see what you are seeing.

**Comment by kphoenix137** [comment]
This is fixed right?
