### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by fuckbeamdog** [diasurgical/devilutionX#5843]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

Seems like the text can't always fit into the boxes. Sometimes the text will hide under an object, sometimes it will be on-top. In the case of the damage numbers it almost looks like it got compressed or something?

![Screenshot](https://user-images.githubusercontent.com/53155671/221680241-e12a8707-0f99-4739-9302-b1b99a3a4269.png)

[multi_1.zip](https://github.com/diasurgical/devilutionX/files/10844082/multi_1.zip)

### To Reproduce

Open the character and check the text? It's just a minor graphical bug.

### Expected Behavior

Making the text boxes a bit bigger, if possible.

### Additional context

I'm not sure how difficult it is to make the text boxes bigger. I like the current font size, so would prefer not to change it.

**Comment by DakkJaniels** [comment]
I doubt boxes will get bigger, the spacing between characters will probably decrease, in the case of the sword. I don't see an issue with damage though.

**Comment by StephenCWills** [comment]
The game squeezes the spacing between characters down to fit in a rectangle that represents the area inside the info panel. Here are some examples of tight fitting names using the latest codebase, with the rectangle rendered as well.

![image](https://user-images.githubusercontent.com/9203145/221689991-df1e5288-2cb1-4b1d-9c61-540282efda6f.png)

![image](https://user-images.githubusercontent.com/9203145/221689971-71b2bf4f-456a-4878-a201-e39c7db7557b.png)

![image](https://user-images.githubusercontent.com/9203145/221689941-7a5d2fbf-7e54-4ab8-9b64-f9c7e7c91af6.png)

![image](https://user-images.githubusercontent.com/9203145/221689906-025a63a3-4e33-46fa-ae9f-190e089098ed.png)

Something seems to have been modified between 1.4.1 and now to make these names fit a bit better, but I'm not really sure what that is. I do know that the entire panel's text `InfoString` is now being drawn in one call to `DrawString()`, whereas 1.4.1 was broken into lines and had to call `DrawString()` on each one (see 8b6db3a). Regardless, the position of the rectangle does suggest that characters could theoretically still render underneath the wings of the angel and demon statues, but I wasn't able to find one through random guesswork.

As for the damage numbers, the spacing was indeed compressed to make them fit. There is nothing for us to fix there.

I'm inclined to mark this as resolved, unless someone thinks it's a good idea to adjust the position and width of the info panel rectangle.
