### ISSUE TITLE
Every 12th line on the credit screen pops in

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#585]
**Describe**
As the text scrolls on screen every 12th line or so pops on screen with out transitioning in to the viewport.

**To Reproduce**
Watch the bottom of the credits for a few seconds.

**Expected behavior**
All credit lines should transition nicely on and off the view port area

**Screenshots**
![image](https://user-images.githubusercontent.com/204594/74094079-7afe4980-4adb-11ea-82d1-c6507b644855.png)
Left is missing the start of the next line, middle is after is pops on screen, right shows how much should have been visible in the left one.
Not it is much more clear then what i managed to capture here, the lines doesn't appear until well after it should have been fully visible.

**Comment by AJenbo** [comment]
@glebm any idea what could be causing this?

**Comment by glebm** [comment]
Reproduced. Not sure why but here is where the math happens:

How many lines to keep in memory:

https://github.com/diasurgical/devilutionX/blob/532ca3cb10c050a4b4de7f94bfacaf389bfc940f/SourceX/DiabloUI/credits.cpp#L165

Which lines to render:
https://github.com/diasurgical/devilutionX/blob/532ca3cb10c050a4b4de7f94bfacaf389bfc940f/SourceX/DiabloUI/credits.cpp#L206-L207

(`offset_y` is 0 at this point, it's only non-zero for the initial lines)
