### ISSUE TITLE
Unique hidden light aura

### ISSUE THREAD

**Issue by ghost** [diasurgical/devilutionX#5850]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

All unique monsters have a light aura, but it just seems out-of-place on the unique Hidden-type monsters.

![TotallyNotVisible](https://user-images.githubusercontent.com/53155671/222255350-f9b35ef6-1e94-473e-83bd-dfad1ae74107.png)

### To Reproduce

Get a unique hidden to spawn in-game.

### Expected Behavior

The light aura gives it away. I expected them to be masters of stealth.

**Comment by DakkJaniels** [comment]
I believe this is vanilla behavior (for tagging purposes)

**Comment by D1-Constantine** [comment]
I don't see what is the problem. All unique monsters have a light radius , changing that will go against the core concept of the game itself.

**Comment by fuckbeamdog** [comment]
It just feels weird that the invisible monster is so easily spot-able. But it is vanilla behavior, just always felt weird.
