### ISSUE TITLE
MP: Initiating quest dialogs starts it for all players

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5854]
Version 95c20c7ce953b42a9d6511b74d197a4f4ce90efc

When any play speaks to a monster like Gharbad or uses the Skeleton Tomb it will trigger the dialog for all players on the level. Instead this should work like the lore books found on every 4th level (only play the dialog for the player triggering it)

**Comment by obligaron** [comment]
I'm not sure if it should always start only on the triggering player.
Some dialogs can't be replayed (for example when you return ogden's sign to snotspil).
But in many cases it's safe to limit it only on the triggering player.

**Comment by AJenbo** [comment]
I don't think it's an issue that only one player hears the dialog, if this is the very first time that the one player plays the game they will have to either infer it or have it referenced by the other player.

**Comment by D1-Constantine** [comment]
I agree with Ajenbo, quest dialogues triggering for the given player only is the way to go as otherwise it doesn't make much sense.
