### ISSUE TITLE
MP: Valor, only the player opening the chambers will see them open

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5855]
Version 95c20c7ce953b42a9d6511b74d197a4f4ce90efc

When placing the blood stones only the player who activates it will see the chambers opening, other players will just see the blood stone dropping near where the chamber should be and will see the player an monsters walking through walls.

**Comment by StephenCWills** [comment]
When the player clicks the pedestal, the client sends `CMD_OPOBJXY` to sets the destination action for that player on remote clients. When the player reaches the pedestal, `OperatePedestal()` removes the Blood Stone from the player's inventory on the local client which triggers `CMD_DELINVITEMS` to be sent to remote clients. At this point, there is a race condition on the remote client.

If, on the remote client, the local player reaches the pedestal before `CMD_DELINVITEMS` is processed, the Blood Stone will be removed by `ProcessPlayers() > CheckNewPath() > OperateObject() > OperatePedestal()` and the quest will proceed normally.

If, on the remote client, `CMD_DELINVITEMS` is processed before the local player reaches the pedestal, the Blood Stone will be removed before the calls to `OperateObject()` and the quest will fail to progress on the local client.

I suspect the best course of action would be to prevent `OperatePedestal()` from progressing the quest if the player operating the pedestal is not `MyPlayer`, then sync the quest on remote clients separately. Maybe in `ResyncQuests()`?

**Comment by obligaron** [comment]
The thing with the pedestal's is that they don't update any quest state (qvar1 or qvar2).
They get synced with the `CMD_OPERATEOBJ` command (also when loading the level).

I think the easiest fix would be that `OperatePedestal` doesn't check `RemoveInventoryItemById` when called from `SyncOpObject` / `CMD_OPERATEOBJ`. Cause `CMD_OPERATEOBJ` is only generated when the check `RemoveInventoryItemById` on the remote player was successfully. 🤔
Currently `SyncOpObject` does something like this already for `sendLootMsg`.
