### ISSUE TITLE
MP: Quest dialogs initiated from the quest menu will always read in the rogue's voice

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5856]
Version 95c20c7ce953b42a9d6511b74d197a4f4ce90efc

During multiplayer when opening the quest panel and selecting a quest entry it will play the dialog in the voice of the rogue even when playing as a different hero.

The game was started by a barbarian

**Comment by StephenCWills** [comment]
I'm pretty sure this occurs because `qmsg` is one of the fields being synced by `CMD_SYNCQUEST`. This goes back to what you were saying about `herosounds[]` in https://github.com/diasurgical/devilutionX/pull/5830#issuecomment-1445014153.

**Comment by obligaron** [comment]
Perhaps we should change the player specific `qmsg` in `SetMultiQuest`.
There we know what the correct player class is. 🤔
