### ISSUE TITLE
MP: Sorc's spells are often not seen by other players

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5857]
Version 95c20c7ce953b42a9d6511b74d197a4f4ce90efc

Often when playing with a sorcerer other players won't see them casting magic but will just see monsters dropping dead from the effect. This is likely caused by the player not being synced to where casting the spell would be possible for them on the other end. 

This most often seamed to happen at the start of a level, but that may just have been user bias.

**Comment by StephenCWills** [comment]
I assume staff charges are not syncing, but I don't know for sure. However, it was also happening when I was casting spells as normal, and mana should be syncing at the same time as player health so there was also something else going on.

**Comment by D1-Constantine** [comment]
I play-tested PvP a lot recently and I haven't noticed any spells casts being invisible to the other player/s or to me, even in bad latencies. As Staphen noted this bug must be connected to spell charges mainly.

**Comment by obligaron** [comment]
I still wish we would have something like #4536 in master. 🙂 
That would make checking this kind of desyncs much easier.
@qndel 😅
