### ISSUE TITLE
Flash not being able to damage players in the NE direction

### ISSUE THREAD

**Issue by D1-Constantine** [diasurgical/devilutionX#5872]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

In the picture bellow the 1'st Warrior(using the chain-mail) will not be able to hit the 2'nd Warrior(using the plate armor) while using Flash. We tested it and it seems Flash will damage your opponent in any direction except this one.

![123](https://user-images.githubusercontent.com/126438721/224522799-0ee0c687-1ff0-428b-84c7-e47944056e42.png)

### To Reproduce

Position two characters like the picture
Cast Flash
The character position in the North-East direction won't get damage

### Expected Behavior

Flash should always deal damage to all direction

**Comment by AJenbo** [comment]
thanks
