### ISSUE TITLE
[improvement request] Integrate church stairs widescreen loading screen

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5885]
Here are some graphics for the loading screen in the church. I need your feedback on whether you like the result and whether there are any copyright concerns. Every pixel was generated entirely with the help of AI (stable diffusion inpainting method). The original image is used as the basic input.
As you can see the transition at the edge is not perfect.
The AI is able to generate a smoother edge, but it paints a bit over the original image.

Cutout with dimensions 1280x480:
![000271 1582548348__cut_1280](https://user-images.githubusercontent.com/45902449/225280861-f0249553-9385-4519-84e6-7c772d279042.png)

Cutout with wider dimensions 1366x480:
![000271 1582548348__cut_1366](https://user-images.githubusercontent.com/45902449/225281050-2dfaab94-2671-4a13-9d70-ffcfabfbd37f.png)

Full sample image at 1366x480:
![000271 1582548348__cut_1366_full](https://user-images.githubusercontent.com/45902449/225281279-c76bb965-2e7b-419a-b74d-040afa9af84c.png)

Example how the final result looks like with full HD:
![000271 1582548348__cut_1366_fullHD](https://user-images.githubusercontent.com/45902449/225281451-3dc6050f-a30f-4061-bee2-c28e7928b8ca.png)

I'm looking forward to your feedback.

**Comment by D1-Constantine** [comment]
Look awesome man , can the same be done for the rest dungeon levels ?

**Comment by Chance4us** [comment]
> Look awesome man , can the same be done for the rest dungeon levels ?

The AI seems smart enough, so I think it's doable. It does take a few attempts, though, and each attempt takes about two hours.

**Comment by AJenbo** [comment]
Nice work, the size should preferably be 1366x480 to match the other ones. I'll get to work on integrating it. Feel free to generate some more. I'll probably do some minor adjustments like breaking up the bricks in the lower left.

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/225460336-832a4f67-02f4-451d-852b-66dd1a7ddc8e.png)
