### ISSUE TITLE
[improvement request] Integrate catacombs stairs widescreen loading screen

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/DevilutionX#5888]
As already discussed in #5885 the graphic for the catacombs as follow up.

Please let me know if you like the result.

Cutout 1366x480:
![000281 1782548348__cutl2](https://user-images.githubusercontent.com/45902449/225668840-7e76ae7e-9058-4001-a551-e16f8cb12b32.png)

Full image 1366x480:
![000281 1782548348__cutl2_full](https://user-images.githubusercontent.com/45902449/225669408-e9fab726-6acc-44a2-95c0-3298ccd8e73d.png)

**Comment by AJenbo** [comment]
AI is scary some times. I feel like we can almost turn around and see a monster her.

**Comment by AJenbo** [comment]
Here is the adjusted one. The reason I have darkened it a bit is that the palette simply does not contain colors that bright:

![image](https://user-images.githubusercontent.com/204594/225696274-59cc759b-131d-4123-8c6b-00e5350f74b1.png)
