### ISSUE TITLE
touch buttons are too big

### ISSUE THREAD

**Issue by emacs-newer** [diasurgical/devilutionX#5892]
### Operating System

Android

### DevilutionX version

1.4.1 (latest release)

### Describe

my phone's resolution is 960x540,and the touch buttons are too big when i launch game.

i also set the same resolution in game options.

### To Reproduce

just launch normally, on other need

### Expected Behavior

touch buttons can adjust the screen size properly

**Comment by qndel** [comment]
I really suggest attaching some screenshot because at the moment all I can do is write "they look good to me" and close this issue ...

**Comment by AJenbo** [comment]
The buttons are adjusted to DPI ireported by your device. If your device is reporting an incorrect DPI then the buttons will be the wrong size. This is most often seen of phones running an unofficial firmware where the people that put it together did not set it correctly. Please provide more info regarding your phone and a screen shot to show what it looks like. If sufficient info is provided we can reopen the issue unless it's a fault with the device.

**Comment by emacs-newer** [comment]
![Screenshot_20230318-200441](https://user-images.githubusercontent.com/126228876/226145219-d31bcfda-2d63-4606-bd89-eb1cde6aa899.jpg)

phone: oneplus 3
screen: 960x540
density: 240

**Comment by AJenbo** [comment]
Assuming that is pixels and pixels per inch that you are listing then your screen should be 4.6 inches diagonally.

None of this fits with what I see listed as the specs for Oneplus 3 thought so that might explain why the UI is oversized.

You never mentioned if you are running stock firmware or are using something else.

**Comment by emacs-newer** [comment]
sorry, i find the reason why the buttons are too big according what you say.

i use adb shell wm to change default resolution and dpi to save battery.

maybe i should i switch back to default values to play it noramlly.

thanks very much

**Comment by emacs-newer** [comment]
by the way, i want to create my mod, but some tools like mpq editor and d1-graphics-tool only have x64 bit version for the latest realease.

**Comment by AJenbo** [comment]
Nice, that's good to know that there is a way for the user to change this without having to change there OS. Might be helpful for others :+1:  d1-graphics-tool there has been a lot of updates to d1gt and it's actually close to having it's 1.0 release, as part of that we ported it to 32bit systems, the latest development version also has a 32bit Windows test build. If you are not using Windows then I suggest you install QT Creator and biuld it for you system.

**Comment by emacs-newer** [comment]
thanks for replying so quickly.

i think i should work on windows for a long time which is impossible to go back to linux.

so you say all the tool chain of mod have tools for 32 bits?

**Comment by AJenbo** [comment]
yes

**Comment by emacs-newer** [comment]
great thanks to you again
