### ISSUE TITLE
Game crashes on latest master with certain loading screens.

### ISSUE THREAD

**Issue by FireIceTalon** [diasurgical/devilutionX#5898]
Occurs when attempting to enter Catacombs from town, and between levels in Church areas. Does not occur when entering or traveling between levels in Caves or Hell.

**Comment by StephenCWills** [comment]
Introduced by #5887 and #5889. The clx files from those PRs seems to be malformed.

**Comment by AJenbo** [comment]
They where generated with D1GT, I think there is a bug in the most recent build that is causing it to use .cel format and not allowing you to change the settings. I regenerated them using pcx2clx, hopefully that fixes it, but I need someone else to test since I can't do so atm.

**Comment by StephenCWills** [comment]
It works for me now.

**Comment by AJenbo** [comment]
Thanks
