### ISSUE TITLE
character light radius is gone

### ISSUE THREAD

**Issue by ChaosMarc** [diasurgical/devilutionX#5906]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

latest master: https://github.com/diasurgical/devilutionX/commit/d57e59d9ee19683a8f09712cb0fdf95cc1a5d659

not sure what caused this, but the character light radius is completely gone and I'm running around in total darkness 🤣 
using the town portal fixes the problem

![Screenshot-from-0123-03-21-09-54-29](https://user-images.githubusercontent.com/1343751/226558689-10788d8d-5c9b-4a07-b3d5-59753d97ad33.png)
![Screenshot-from-0123-03-21-10-03-16](https://user-images.githubusercontent.com/1343751/226560207-955db24f-7e0c-4611-9b7a-e320cffb05d4.png)

[single_0.zip](https://github.com/diasurgical/devilutionX/files/11026482/single_0.zip)

### To Reproduce

sorry no clue :-/ see savegame

**Comment by D1-Constantine** [comment]
Did Diablo hit you? He has the ability to reduce your light radius upon hit

**Comment by qndel** [comment]
> Did Diablo hit you? He has the ability to reduce your light radius upon hit

since when?

**Comment by AJenbo** [comment]
probably a conflict between you and a monster both having light id 0 and the monster there for taking yours.

**Comment by ChaosMarc** [comment]
> Did Diablo hit you? He has the ability to reduce your light radius upon hit
nope, hadn't triggered him yet

> The best would be a save game right before this happens.
sorry, can't help with that. If this happens to me again, I will try and backup the savegame before it happens

**Comment by AJenbo** [comment]
Closing since we do not have a way to replacete it atm
