### ISSUE TITLE
[improvement request] Integrate widescreen loading screen for the caves

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5912]
As already discussed in #5885 the graphic for the caves as follow up.
Unfortunately, it was a bit difficult due to the perspective and it took a long time to achieve optimal optics.
Basically, there are numerous optimization possibilities, but I think that it's okay for now.
Please let me know if you like the result.

Cutout 1366x480:
![000315 2732701444_caves_borders](https://user-images.githubusercontent.com/45902449/226705920-60a4a99d-28d2-46fa-a8e2-10e92e22e78c.png)

Full image 1366x480:
![000315 2732701444_caves_full](https://user-images.githubusercontent.com/45902449/226705995-1948f461-a5f4-438d-b278-ce7d935d3598.png)

**Comment by AJenbo** [comment]
Not much change here, mostly just palette conversion:

![image](https://user-images.githubusercontent.com/204594/226796255-bf8d38ca-4766-4f18-9cf4-c9c604b9e46a.png)

**Comment by AJenbo** [comment]
Fixed by https://github.com/diasurgical/devilutionX/commit/4bd0148f4982a171446f0f0ce75844b733fb1227

**Comment by Chance4us** [comment]
I apologize for not creating an issue. I would like to share here that the wide loading screen is not showing and the game occasionally crashes on this loading screen. I hope the information is sufficient, could this be due to the graphic format?

**Comment by AJenbo** [comment]
Yeah it was already pointed out, can you check if it's fixed now?
https://github.com/diasurgical/devilutionX/commit/45023b568087a1e049e4213e4e94fa625b91c08b

**Comment by StephenCWills** [comment]
No, it's still broken.

**Comment by StephenCWills** [comment]
Sorry, ignore me. I needed to pull again.

**Comment by AJenbo** [comment]
Thanks :)

**Comment by Chance4us** [comment]
Thanks for fixing :heart_eyes:
