### ISSUE TITLE
Modding?

### ISSUE THREAD

**Issue by Winterwolf9729** [diasurgical/devilutionX#5918]
I don't know if this would really count as an issue, but can Diablo be modded even on this app with mods like Beelzebub? I want to try out Diablo HD.

**Comment by yuripourre** [comment]
If you are talking about Diablo or Devolution, yes they should work with existing mods.

DevolutionX on the other hand is incompatible with them but there is nothing preventing someone to recreate their functionalities.

**Comment by Winterwolf9729** [comment]
Well, shoot. I guess that means there's nothing I can do.

**Comment by qndel** [comment]
Don't open issues for questions, there's discord/discussions for that ...

**Comment by AJenbo** [comment]
It's not that it's not compatible. Beelzebub replaces the exe so it isn't compatible with any thing, not the original either. If you replace devilutionX with Beelzebub you are no longer using devilutionX. Diablo dose not have any mod support to speak of so most are either ful on replacements or hacks that won't even work between minor updates of the game.
