### ISSUE TITLE
Controller doesn't work on iOS

### ISSUE THREAD

**Issue by jdactal** [diasurgical/devilutionX#5919]
I have a Backbone One controller that connects through the lightning port on my iPhone. When I try to use it one DevilutionX on iOS, it's not detected and doesn't do anything. It works fine on other sideloaded iOS apps but it doesn't seem to work for this one, which is annoying because i find it a bit cramped to play on my phone screen.

**Comment by AJenbo** [comment]
You should bring this issue up with libsdl it its what takes care of detecting the gamepad
