### ISSUE TITLE
Unable to set mapping for PS5 controller

### ISSUE THREAD

**Issue by rtrzebinski** [diasurgical/devilutionX#5921]
I need help with configuring PS5 controller.

I read these:

https://github.com/diasurgical/devilutionX/wiki/Game-Controller-Scheme

https://github.com/gabomdq/SDL_GameControllerDB

But I can't make it work, what I do is editing `~/Library/Application Support/diasurgical/devilution/diablo.ini`

section:

```
[Controller]
Mapping=
```

I tried to put there multiple versions for instance:

```
[Controller]
Mapping=a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,misc1:b14,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,touchpad:b13,x:b0,y:b3
```

But I can't find the right format, can I have a hint what it should be?

I'm trying one of these: https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L927

I promise to document the answer once I make it working :)

**Comment by AJenbo** [comment]
Make sure you are using a tool with the same version of SDL as DevilutionX (you can probably copy the lib between the two).

Also this way of mapping gamepads is being replaced in the next release to an ingame setting, so closing this it's it pretty much will be unsupported (but not removed) in the future.

**Comment by StephenCWills** [comment]
I'm feeling helpful today, so just a couple suggestions.

First, if you can figure out how to run the game with the `--verbose` flag and retrieve console output from the game, that console output should tell you exactly what mapping the game uses by default for your gamepad. You can use that as a starting point and tweak it.

Second, when you enter the mapping into the INI file, you should include all the fields from the game controller database. This includes the alphanumeric identifier and the name of the game controller which are the first two fields for every entry in that database.

**Comment by rtrzebinski** [comment]
Thank you for replying so quickly on a Friday afternoon :D

@AJenbo

> Make sure you are using a tool with the same version of SDL as DevilutionX (you can probably copy the lib between the two).

Sorry, what tool? What I do is copying the config from - `https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L927` - I don't use no tool.

Also the [docs](https://github.com/diasurgical/devilutionX/wiki/Game-Controller-Scheme) saying `For now, they can be re-mapped by changing SourceX/controls or by setting the SDL_GAMECONTROLLERCONFIG environment variable (see [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB)).` - is a bit cryptic, it might make sense for the game devs, but I don't understand it - would be nice to add some more human readable docs (I am happy to help with that).

@StephenCWills So I run:

```
./devilutionx --verbose
(...)
2023-03-24 18:02:02.143 devilutionx[68996:3791527] INFO: Opened game controller with mapping:
030000004c050000e60c000000016800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,touchpad:b15,misc1:b16,platform:Mac OS X
```

I see the mapping now.

So let's say I want to use [this setting](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L927):

```
030000004c050000e60c000000010000,PS5 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,misc1:b14,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,touchpad:b13,x:b0,y:b3,platform:Mac OS X,
```

I put it to:

```
[Controller]
Mapping="030000004c050000e60c000000010000,PS5 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,misc1:b14,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,touchpad:b13,x:b0,y:b3,platform:Mac OS X,"
```

OR

```
[Controller]
Mapping=030000004c050000e60c000000010000,PS5 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,misc1:b14,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,touchpad:b13,x:b0,y:b3,platform:Mac OS X,
```

But it has no effect, game is being started with the default mapping, what do I do wrong?

Actually I found out it is adding a line about PS5 controller to the log, while still using the default mapping:

```
2023-03-24 18:07:04.792 devilutionx[69010:3794831] INFO: Adding joystick 0: PS5 Controller
2023-03-24 18:07:04.802 devilutionx[69010:3794831] INFO: Opening game controller for joystick at index 0
2023-03-24 18:07:04.802 devilutionx[69010:3794831] INFO: Opened game controller with mapping:
030000004c050000e60c000000016800,*,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,touchpad:b15,misc1:b16,platform:Mac OS X
```

**Comment by StephenCWills** [comment]
> So let's say I want to use [this setting](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L927):
> 
> ...
> 
> But it has no effect, game is being started with the default mapping, what do I do wrong?

Those entries in the database are not settings, they are mappings. The mapping you chose has no effect because your gamepad identifier is `030000004c050000e60c000000016800`, not `030000004c050000e60c000000010000`. You should modify the mapping that the game printed out rather than picking one out from the database. But I can't tell you what it should be since I don't know which buttons you want swapped. What I can tell you, though, is that you shouldn't use quotes in the INI file.

> Sorry, what tool? What I do is copying the config from - `https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L927` - I don't use no tool.

I imagine he's referring to these tools.
https://github.com/gabomdq/SDL_GameControllerDB#mapping-tools

If you use one of those tools to determine your gamepad's mapping, it might not work for DevilutionX if the version of SDL doesn't match.

> Also the [docs](https://github.com/diasurgical/devilutionX/wiki/Game-Controller-Scheme) saying `For now, they can be re-mapped by changing SourceX/controls or by setting the SDL_GAMECONTROLLERCONFIG environment variable (see [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB)).` - is a bit cryptic, it might make sense for the game devs, but I don't understand it - would be nice to add some more human readable docs (I am happy to help with that).

I imagine it's cryptic because it's not exactly a straightforward process. It depends on several factors such as SDL version, platform, and gamepad make/model. The main purpose of that line in the doc is to drop hints for further reading since the mapping configuration is a feature of SDL and not DevilutionX.

**Comment by AJenbo** [comment]
> Sorry, what tool? What I do is copying the config from - `https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L927` - I don't use no tool.

Ok better hope they used the same version as you need then :/

**Comment by rtrzebinski** [comment]
@StephenCWills 

> You should modify the mapping that the game printed out rather than picking one out from the database. 

Perfect, this is it! Thank you!

So I put this (I only needed to replace X with O so it's more PS user intuitive) to `diablo.ini` and did what I needed:

```ini
[Controller]
Mapping=030000004c050000e60c000000016800,*,b:b0,a:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,touchpad:b15,misc1:b16,platform:Mac OS X
Swap Shoulder Button Mode=0
Dpad Hotkeys=0
deadzone=0.070000
```

@AJenbo Right, looking forward for the new version, thank you so much!

**Comment by rtrzebinski** [comment]
FYI I added some docs about it to the wiki, maybe someone will find it useful :)

[How to change the default mapping? Case study - update PS5 controller so A ○, B × -> B ○, A × - this will become more natural for PS users.](https://github.com/diasurgical/devilutionX/wiki/Game-Controller-Scheme#how-to-change-the-default-mapping-case-study---update-ps5-controller-so-a--b----b--a----this-will-become-more-natural-for-ps-users)
