### ISSUE TITLE
Multi: Leoric quest state issues

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5926]
- ~~Leoric is agro from the start and will run to the gate where he can easily be killed~~
- Opening the secret room (player 2) not all players had it open for them (player 0)

**Comment by obligaron** [comment]
I tried to reproduce this, but couldn't. 😢 
Perhaps some special condition is missing? A third player?

Theory:
Perhaps some monsters mistakenly become aggro?
This would also explain #5927 (there the skeletons would open the door).
Theoretically, this could also be a general multiplayer problem, which has just never been noticed in this way.
🤔

**Comment by AJenbo** [comment]
We where having strange desync issues that day. Some times getting completly different levels, dying towns man missing, unable to join.

I have thought about it since, and I think the issue might have been that I didn't enable all-quests in my settings but the host and other player did. Which makes me think that we need to sync the state of all quests when a player joins?

**Comment by obligaron** [comment]
Yeah it was a rhino. So it could really be other issues.
The full quest option is part of synced `GameData`, so it should work regardless of the settings.
But I will check again.
And yeah in the other case it was a rhino, my bad sorry.

**Comment by FitzRoyX** [comment]
I have a single player savegame right before entering Leo's tomb. I noticed that if my sorc goes in guns blazing with lightning spells, he is usually off his spawn point by the time I open the gates. Basically what happens is that stray lightning bolts are travelling offscreen into his room and through the gates. If it hits him or his minions enough times he'll be right up near the gate when it opens, sometimes even without his source source attached.

**Comment by AJenbo** [comment]
Hmm that is actually a likely explanation, we did shoot at things pretty carelessly.

**Comment by AJenbo** [comment]
I think I will close this for now, there where many sync issues with the whole game state related to quest so i think it would be better to tackle this first as a general thing. Will test a bit more and narrow down what was going wrong.
