### ISSUE TITLE
[improvement request] Integrate widescreen loading screen for the hell

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5928]
As already discussed in #5885 the graphic for the hell as follow up.
Please let me know if the result is satisfactory.

Cutout 1366x480:
![000339 1090848580_hell_borders](https://user-images.githubusercontent.com/45902449/227746003-2dc2ca90-f71a-4bf4-bdef-23057117e1ad.png)

Full image 1366x480:
![000339 1090848580_hell_full](https://user-images.githubusercontent.com/45902449/227746017-f8d30ba0-1d11-482a-8cb6-7abd98cddc03.png)

**Comment by AJenbo** [comment]
To bad the real levels aren't this interesting

**Comment by AJenbo** [comment]
Adjusted, will convert and implement later:
![image](https://user-images.githubusercontent.com/204594/227756008-8ff25642-5feb-40b6-ac2c-e1b1bbe44efe.png)

**Comment by AJenbo** [comment]
Implemented in and for once i had a chance to test that it works before just pushing it :D
https://github.com/diasurgical/devilutionX/commit/5a1f0f42808b34f2e441dc8b796e4105883f831f
