### ISSUE TITLE
Bad pallet at end of loading poisoned water

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#593]
**Describe**
When entering the poisoned water level blue colors appear in the image as the screen fades.
[single_0.zip](https://github.com/diasurgical/devilutionX/files/4176447/single_0.zip)

**To Reproduce**
Load attached save game and walk in to the poisoned water level

**Expected behavior**
The colors should persist as the scree fade.

**Screenshots**
![image](https://user-images.githubusercontent.com/204594/74095661-4cd93380-4af4-11ea-8bf6-f0fb9ec217ad.png)

**Comment by galaxyhaxz** [comment]
This is a vanilla bug to. It has to do with the fact palettes are loaded during fade, and the poisoned water (blue/yellow) overwrites it. Can probably be fixed by adding a check to make the palette load right as the screen turns black, given it will be fast enough.

**Comment by AJenbo** [comment]
Wow I even missed this when looking at the videos online, most of them cut to black around this point for no good reason (maybe they wanted to hid the bug) but this one actually show it: https://www.youtube.com/watch?v=YSjRHiwGoT4
I guess i could also have missed it if my monitor is horribly calibrated... which it may by. Thanks for the info.

**Comment by Chance4us** [comment]
This is definitely a vanilla bug.
It can also appear when entering a town portal.

**Comment by julealgon** [comment]
Interesting issue. I don't think I've ever personally seen this in the poisoned water supply quest, but I definitely saw it with town portal.

Do we know why this doesn't happen consistently in vanilla though? I just double checked a playthrough I was watching earlier and the bug doesn't happen in that instance.

https://youtu.be/UhR6HiAIj08?t=777

**Comment by AJenbo** [comment]
Afaik, it's because poison water has an animated color pallet, apparently it also gets loaded a bit to early.

**Comment by qndel** [comment]
I think all quest levels load palettes, just that poisoned water supply's one happens to affect the loading screen

**Comment by julealgon** [comment]
I assume the various loading screens were created with the target floor's palette in mind, and since the poisoned water supply uses a different palette (caves) the cathedral loading screen graphics are not prepared for that.

Another way of ensuring this works would be to not use those pixel values in the cathedral loading art, so that they are never swapped.

But I figure just changing the palette after fading out is probably a better long term solution indeed.
