### ISSUE TITLE
[improvement request] Integrate wide loading screen for Diablo

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5934]
As already discussed in #5885 the graphic for the last level as follow up.
I hope you like this picture too.

Cutout 1366x480:
![000346 1454279779_gate_borders](https://user-images.githubusercontent.com/45902449/228052385-785ae0ce-f2f7-4e30-9785-55e182ce8a62.png)

Full image 1366x480:
![000346 1454279779_gate_full](https://user-images.githubusercontent.com/45902449/228052421-8f9f2417-aa9a-4ec5-9747-b2232430632e.png)

**Comment by AJenbo** [comment]
Very nice, my only critique would be that the fire doesn't follow the same arch as the original, but I doubt the AI would listen to me.

**Comment by Chance4us** [comment]
> Very nice, my only critique would be that the fire doesn't follow the same arch as the original, but I doubt the AI would listen to me.

It's difficult to explain it to the AI and each attempt takes much time.
There were some pictures where the ground was going down lower, but the overall impression was worse.
My fast computer is too slow to make more attempts in a short time. :D
I would like to finish the remaining images first (Hive, Crypt).
Afterwards I could try to create some better graphics.

**Comment by Chance4us** [comment]
@AJenbo I warped the graphics in GIMP a bit. How do you like the result?

Cutout 1366x480:
![000346 1454279779_gate_borders_2](https://user-images.githubusercontent.com/45902449/228368849-6310804f-416a-420c-abfd-61bf5484367e.png)

Full image 1366x480:
![000346 1454279779_gate_full_2](https://user-images.githubusercontent.com/45902449/228368883-6753e861-bff3-4f32-bf27-a26a32456dcb.png)

**Comment by AJenbo** [comment]
Nice!

**Comment by galaxyhaxz** [comment]
The world is on fyhaaaaaa :D

**Comment by AJenbo** [comment]
Done https://github.com/diasurgical/devilutionX/commit/82d233baf947b98e0d11935579d8ceade88587b5

![image](https://user-images.githubusercontent.com/204594/229650064-52ee8e20-6aa1-412a-a18e-eea1c36c9d5c.png)
