### ISSUE TITLE
[improvement request] Integrate wide loading screen for the hive

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5936]
[improvement request] Integrate wide loading screen for the hive
As already discussed in #5885 the graphic for the hive as follow up.
So only one remains for the Crypt.

Cutout 1366x480:
![000357 3511979025_cut6_borders](https://user-images.githubusercontent.com/45902449/228660193-d5e8a551-92e1-4720-b7d5-a57a9c8e6ac0.png)

Full image 1366x480:
![000357 3511979025_cut6_full](https://user-images.githubusercontent.com/45902449/228660218-e5f1bbd0-ad78-4df6-8dbe-42e1a17f0a0d.png)

**Comment by julealgon** [comment]
This one feels a bit disconnected to me. It's as if I can immediately tell the seams by looking at the complete image.

**Comment by Chance4us** [comment]
Yes, the seams need to be corrected.

**Comment by AJenbo** [comment]
It also looks like the AI though it was seaweed and not tentacles

**Comment by galaxyhaxz** [comment]
> It also looks like the AI though it was seaweed and not tentacles

How do you know what aliens are made from? :sweat_smile:

**Comment by qndel** [comment]
> > It also looks like the AI though it was seaweed and not tentacles
> 
> How do you know what aliens are made from? 😅

I've heard you have to tell AI 18+ for tentacles 🤪

**Comment by Chance4us** [comment]
Finally, is a bit of seawead enough or can the picture not be used? :D

**Comment by NikoVP** [comment]
Hi, long time no see. I think the picture can be edited and have the right side darkened. Would improve things a lot

**Comment by AJenbo** [comment]
@NikoVP good to see you :)

I gave retouching this a go, not sure if I'm moving entirely in the right direction but I do think it has less of the "falling appart sea weed" feeling that I wasn't so happy with.

![image](https://user-images.githubusercontent.com/204594/229657144-50b66cba-15b9-4a5a-9a65-c630c17e55e5.png)

I can try and come back to it, but anyone should feel free to do what ever :)

**Comment by Chance4us** [comment]
I can also try to generate more such images, maybe it would reduce the amount of work.

**Comment by NikoVP** [comment]
If someone does a zip of all those images I can probably rework them so the newly extended content fits better the original style.

**Comment by Chance4us** [comment]
This image is ready too.
Changes made.
1. Improved brightness
2. Fixed seams
3. Added some noise in places to get closer to the original

![hive_fertig](https://user-images.githubusercontent.com/45902449/229801091-aea742ce-d099-4769-9e19-b24fa9bbd0dd.png)

**Comment by Chance4us** [comment]
Another example:
![000300 1328576690](https://user-images.githubusercontent.com/45902449/230167506-e8cbce7f-4798-4cde-9260-2fa92bde333f.png)

**Comment by julealgon** [comment]
> Another example: ![000300 1328576690](https://user-images.githubusercontent.com/45902449/230167506-e8cbce7f-4798-4cde-9260-2fa92bde333f.png)

I like the art on this one much more even if the seams are still somewhat visible.

**Comment by Chance4us** [comment]
> I like the art on this one much more even if the seams are still somewhat visible.

We can of course edit the seams a little bit at the very edge.

**Comment by Chance4us** [comment]
I will generate more, we can then also combine the left side of one example and the right side of another.
Howsoever, the calculation takes forever on my PC.

**Comment by Chance4us** [comment]
New one:
![000301 1946660807](https://user-images.githubusercontent.com/45902449/230214536-0586eb4b-8253-4327-83c1-868cd7807460.png)

**Comment by Chance4us** [comment]
Two more:
![000302 1727158871](https://user-images.githubusercontent.com/45902449/230279798-7a3067da-361c-4135-9970-c3fa6f888d3e.png)
![000302 2284582791](https://user-images.githubusercontent.com/45902449/230280096-37f86090-a010-45e1-98fb-f0564e2705f0.png)

**Comment by AJenbo** [comment]
wow these are starting to get really good <3

**Comment by Chance4us** [comment]
> wow these are starting to get really good <3

One last picture for now, do you think these are enough?
![000302 4164439273](https://user-images.githubusercontent.com/45902449/230289355-d9518d8f-e9f4-4692-a126-b717f4b14c52.png)

**Comment by AJenbo** [comment]
Yeah i think there is a good selection to work from here, nice work :+1:

**Comment by Chance4us** [comment]
@AJenbo 
It became possible to create slightly smoother and more neutral shapes.
The seams would still need to be worked on.
What do you think about the following example?

![cut6_1](https://github.com/diasurgical/devilutionX/assets/45902449/660f6148-7c52-4716-b996-c34dd8354ddf)

**Comment by Chance4us** [comment]
Oh, and by the way, thanks again to @galaxyhaxz for the opportunities that have arisen through your work.
As you can see, the project is evolving in every way, both graphically and functionally.

**Comment by AJenbo** [comment]
Looks really good! I'll add it in a bit.

**Comment by galaxyhaxz** [comment]
Looks great, crazy what AI can do. Now make it taller :D

**Comment by AJenbo** [comment]
Fun fact, this screen only uses 128 colors instead of 256 :question: :exclamation:

**Comment by AJenbo** [comment]
@Chance4us thanks for all the hardwork with making the reamaning widescreen load screens :pray:

**Comment by Chance4us** [comment]
Thanks for the great project and I'm sure there will be more graphical improvements.
