### ISSUE TITLE
New menu on SDL1: Green background if software scaling is disabled

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#594]
```
cmake .. -DUSE_SDL1=ON -DSDL1_VIDEO_MODE_HEIGHT=320
```

![diab-green](https://user-images.githubusercontent.com/216339/74103709-64d9a300-4b46-11ea-9bd8-f0d5e720dd0f.png)

**Comment by glebm** [comment]
This happens because we're converting the surface to the output format before calling BlitScaled. If the output surface doesn't have the alpha channel, transparency information is lost.

**Comment by AJenbo** [comment]
Ok, i expect this should be solved by converting and scaling them during loading instead of when we are about to blit. This should also help performance a good deal. Good to to have this as a test to make sure thinks work correct.

**Comment by glebm** [comment]
@AJenbo I'm working on a fix
