### ISSUE TITLE
[Controller] Players keeps walking the same direction after loading screen

### ISSUE THREAD

**Issue by Phalcon22** [diasurgical/devilutionX#5946]
### Operating System

Android

### DevilutionX version

Custom build (please specify commit ID)

### Describe

 Version   #7602

With a controller only, if the player changes level, he will automatically walks toward the same direction as before the loading screen even if the stick is no longer pressed. This only occurs when using the joystick, using the dpad works perfectly.

The issue is not present with touch controls which also makes use of a joystick to move around. It could be interesting to see how the issue is avoided there.

### To Reproduce

1. Enter the dungeon by pressing the joystick (not Dpad)
2. Release the joystick during the loading screen
3. Witness how the character keeps moving the same direction

**Comment by qndel** [comment]
"Version #7602" there's no such a thing

**Comment by Phalcon22** [comment]
Indeed d2bc7c1

**Comment by StephenCWills** [comment]
I guess this was probably introduced by the initial padmapper PR. Calls to `ProcessControllerMotion()` were moved from `FetchMessage_Real()` to the `GameEventHandler()`, meaning that the `DisableInputEventHandler()` used on the loading screen isn't updating axis state.
