### ISSUE TITLE
Gear (probably) poofs after dying

### ISSUE THREAD

**Issue by myself600** [diasurgical/devilutionX#5947]
### Operating System

Other (please specify)

### DevilutionX version

1.4.1 (latest release)

### Describe

Yesterday, I was playing co-op with a random player on ZT and my character got mobbed and died. I tried to exit the game to avoid it, but I was late (heard the scream) and when I rejoined, my character was naked, so I equipped my backup gear and went down. Since the enemies have surrounded the entrance, I immediately teleported away and when I got back to the stairs, I couldn't find any of my stuff where it should have been. I vaguely remember similar stuff happening in the past, as well as I don't remember hearing my items drop or seeing them despite being quick.

### To Reproduce

I tried to reproduce this on TCP, but couldn't

### Expected Behavior

The gear should appear at the location of the corpse

### Additional context

Operating system: Manjaro ARM 23.02 (aarch64)

Thumbs up for the new bug reporting system, btw. It's much clearer now.

**Comment by AJenbo** [comment]
if you manage to quit before the other players are aware of your gear dropping but after it has been removed from your hero this could explain the case you are describing. Since it is p2p it relies on the other players re transmitting the state of the game to you once you join, and they might not have been fully in sync with you.

**Comment by myself600** [comment]
I believe this would have happened even if I would not leave the game. It think this has to do something with desync, based on my previous experiences.

**Comment by StephenCWills** [comment]
> ... when I got back to the stairs, I couldn't find any of my stuff where it should have been.

Can you clarify whether you found your gear in places where it shouldn't have been or weren't able to find any of your gear at all?

**Comment by myself600** [comment]
Sure. I remember dying around the stairs at the beginning of dlvl 14, so none of my gear dropped (I restored it from backup by leaving the game and moving the items from backup save to stash). Similarly, yesterday I was playing co-op with another player who died around Lazarus' lair and his armor poofed (the other gear dropped as it should). I've looked around the level (and my inventory) by teleporting around to confirm it have poofed (it was an Obsidian Full Plate Mail). There was no hourglass (lag) while we played, but I noticed some slight desync, like the other player dying while Lazarus was still stone cursed and no enemies were around. This confirms my memory to be correct in this regards (items randomly poofing when characters die).

**Comment by obligaron** [comment]
When only some items are gone/missing it could be the same bug as #4124 (depending which player is level owner).
And then it would be hopefully fixed with #5423.

**Comment by StephenCWills** [comment]
As obligaron stated, it might already be fixed. Or, as AJenbo stated, it could be that the remote clients never processed the `CMD_RESPAWNITEM` commands. It's not really clear that there's any specific issue here that needs to be fixed, so I think it's appropriate to close.

**Comment by myself600** [comment]
This issue reappeared a few days ago, but for the other player I was playing with. We were both on the same floor and he left the game, then rejoined and appeared "naked" (bare character model) so I looked around and there was no gear anywhere on the floor. He confirmed that he died when I asked. There was sound for dying when he left the game. I believe he was the host and there were only the 2 of us in game.

**Comment by AJenbo** [comment]
I recommend not leaving at game right at the point where items are being transferred to the other player.
If they player is not in game by the time the package is being processed it will be discarded
