### ISSUE TITLE
I can't copy the diablo file to the folder

### ISSUE THREAD

**Issue by Lufims** [diasurgical/devilutionX#5948]
### Operating System

Android

### DevilutionX version

1.4.1 (latest release)

### Describe

I can't copy the game files to the folder, because I use Android go, and I don't have access to the android/data folders, so, for Android go at least, could be a way to use another folder outside the android folder that can have the game files.

### To Reproduce

Use Android 11 Go

### Expected Behavior

Copy the files to the Android/Data folder.

### Additional context

![Screenshot_20230405-105657](https://user-images.githubusercontent.com/73536178/230103373-f4e3719c-3cfc-4003-8863-232d9babf42e.png)

**Comment by StephenCWills** [comment]
I believe you can either use a file manager app that enables you to grant access to the folder. You can also try the Import process as described in the following wiki page.
https://github.com/diasurgical/devilutionX/wiki/Extracting-the-.MPQs-from-the-GoG-installer#android-13

Closing for now as I don't believe there is any action to take on our part.

**Comment by AJenbo** [comment]
Yeah this looks to be a limitation of what ever file manager you are using more then anything else
