### ISSUE TITLE
Crashing on loading save

### ISSUE THREAD

**Issue by vzhestkov** [diasurgical/devilutionX#5949]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

devilutionX created a save which is not possible to load after. devilutionX is crashing on loading this save.
Originally it was created with devilutionX port for Miyoo Mini, but there was no any issues for more than a week before.
I've tried to load it with android, linux and windows builds of 1.4.1 but all of them are crashing on loading.
I also tried to load it with latest available GOG Diablo, it's crashing also.

[Affected save file](gdrive link - file posted in next comment - qndel)

Are there any chances to fix it?

### To Reproduce

1. Copy save file to the saves directory
2. Load this save

**Comment by qndel** [comment]
[single_69.zip](https://github.com/diasurgical/devilutionX/files/11171335/single_69.zip)
Reuploaded and renamed the save - don't upload files with names that require them to be manually changed for them to work

**Comment by qndel** [comment]
Looks like a lot broke in it, you can keep playing by selecting new game 🤷

**Comment by vzhestkov** [comment]
I can play with new for sure, but the problem that the save was made on one of the latest levels and I have no previous saves. And the reason of getting this broken save is unknown. The save was made as usual, no creashes of the app or the OS on the device, the filesystem is fine.

**Comment by StephenCWills** [comment]
I poked at it a bit. I'm not sure if the save file is corrupt, actually. But I doubt this can be resolved quickly regardless so you're probably better off not holding your breath. Thanks for the bug report.

**Comment by vzhestkov** [comment]
Nope, the device itself doesn't have any network device. But I'll add to the shell script to copy the saves on each start of the game to avoid such issue.

**Comment by StephenCWills** [comment]
@vzhestkov I take it back. It was easy to salvage the save file: [single_69.zip](https://github.com/diasurgical/devilutionX/files/11174551/single_69.zip)

Somehow, `leveltype` was captured in the save file as `DTYPE_HELL` instead of `DTYPE_CATHEDRAL` while in Lazarus' chamber. This caused the game to load the wrong files for object graphics.

**Comment by sskras** [comment]
> Nope, the device itself doesn't have any network device. But I'll add to the shell script to copy the saves on each start of the game to avoid such issue.

It would be nice if the game itself would rotate a defined number of latest save files.

**Comment by vzhestkov** [comment]
@StephenCWills thanks for fixing the save file :+1:

I've never been on this level, but before creating the save there were a blinking lights like a waves on this level. Now the light is constant on the level. I have no idea what does it mean, but maybe has some sense for the case.

**Comment by vzhestkov** [comment]
I'll enable rotating saves in the script to try creating the save before facing the issue and find the steps to reproduce the issue.

**Comment by AJenbo** [comment]
> I've never been on this level, but before creating the save there were a blinking lights like a waves on this level. Now the light is constant on the level. I have no idea what does it mean, but maybe has some sense for the case.

This fits with error in the save file, somehow the game had switched to thinking you where in the hell level where the light is animated. In hell level this just makes the blood walls shimmer, but in cathedral it would have the effect you describe.

**Comment by vzhestkov** [comment]
Strange thing with this light animation. On the  device itself the light is starting flickering like a weaves on saving the game, but on restoring from the save it's not flickering, but it's only on Miyoo Mini. When I try to reproduce the same with the linux build on my laptop it's not flickering. I've entered the level from the 15th level (or 16th sorry not remember for sure from the place with the pentagram, there was a portal on it). And now I have no idea how to leave the level :laughing:

**Comment by AJenbo** [comment]
almost sounds like an obscure compiler error, or it could be some sort of overflow.
could you try making a unoptimized, or debug build and test that?

**Comment by AJenbo** [comment]
> And now I have no idea how to leave the level laughing

Go to the two circles at either side on the bottom of the level and read the books, it will teleport you to two small rooms. Then stand on the circle in the room where you entered the level. Kill the boos, now there is a portal where you entered the level... yeah pretty unintuitive...

**Comment by vzhestkov** [comment]
@AJenbo thanks, found the solution already, but anyway thanks a lot.

@StephenCWills it could sound a bit strange, but I was able to continue gaming with the save you fixed on Miyoo Mini and found a clear case to reproduce the bug:
1. Load the save
2. Save the game (the environment is starting flickering with waveaves on the wall.
3. Save the game one more time
4. The game is crashing on loading the save
So in general it breaks the save on second save while the walls are flickering.
BUT, I can reproduce it on Miyoo Mini only (actually it's arm 32), but with other builds (Android, Linux, Windows) I'm unable to move on the level. The character got stuck on the place where it is on loading the save.

In general it could be a bug specific to the single build for this device.

**Comment by AJenbo** [comment]
Are you able to make custom builds to test on it?

**Comment by glebm** [comment]
> with other builds (Android, Linux, Windows) I'm unable to move on the level

Sounds like there is an issue resulting in a UB that behaves differently on different platforms.
A Linux debug build with sanitizers will hopefully catch it.

**Comment by StephenCWills** [comment]
Another occurrence of the same issue, courtesy of Discord user jonah7yay. [single_0.zip](https://github.com/diasurgical/devilutionX/files/11187391/single_0.zip)

This is also in Lazarus' chamber, but the game seems to have used `DTYPE_CATACOMBS` instead of `DTYPE_HELL`.

**Comment by AJenbo** [comment]
could you let us know the exact version and where you got it from?

**Comment by glebm** [comment]
We haven't released a Miyoo Mini build yet (will do with the 1.5.0 release).
Here is the latest build from the current master (the usual disclaimers about dev builds apply - may crash, destroy your save, etc): https://github.com/diasurgical/devilutionX/actions/runs/4687841385

**Comment by AJenbo** [comment]
Closing since this pretty much is a fixed bug from an early beta, or impossible for us to verify
