### ISSUE TITLE
[improvement request] Integrate wide loading screen for the crypt

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#5952]
As already discussed in #5885 the current state for the crypt as follow up.
Since this is the most difficult task and the geometries that are not nicely shaped have to be isolated one by one in several passes, I've only provided the right side for now.

The issue is that the AI does not properly recognize the geometric shapes (circles, diamonds) of the tiles.
The AI therefore usually paints snails, bolts an helices instead of perfectly round circles.
That's why I ask you to specify individual pixel areas if you don't like the look somewhere.

Current state:
![end](https://user-images.githubusercontent.com/45902449/230611083-07c2fff0-1778-4a7d-ab11-9677c90eddac.png)

As a fun factor, I also want to share my experience with the AI with you below.
1.) Trying to force the AI to draw perfectly round circles. Result:
![000004 1926605450](https://user-images.githubusercontent.com/45902449/230614553-b8f8c3e9-8382-44b7-8e2c-495da26d921f.png)
![000004 2319259500](https://user-images.githubusercontent.com/45902449/230614557-98ca1d94-a6c3-4d06-8773-b44ec6b390b2.png)
![000027 3226164730](https://user-images.githubusercontent.com/45902449/230614559-7e6f1420-bbca-45b2-9b2d-ac456bd85235.png)
![000036 540567514](https://user-images.githubusercontent.com/45902449/230614561-1a3441c0-aee4-40f6-bbfd-e0426d1e4edd.png)
![000038 171196351](https://user-images.githubusercontent.com/45902449/230614564-dcc46e7b-18e3-4475-86d9-4c764f9d4821.png)
![000038 620247180](https://user-images.githubusercontent.com/45902449/230614566-8ab09b57-46b2-431d-a769-3779dccd260b.png)
![000038 887112309](https://user-images.githubusercontent.com/45902449/230614568-06bbea6c-fb9e-4b1f-8bfc-8aa8d18ba9f1.png)
![000038 3052988678](https://user-images.githubusercontent.com/45902449/230614570-fd92dbcc-59aa-471e-ac19-16d38bf8e6a0.png)
![000038 3199930116](https://user-images.githubusercontent.com/45902449/230614575-3b478267-6e14-4c72-8664-b0613c973e0b.png)
![000055 3672487393](https://user-images.githubusercontent.com/45902449/230614577-7746d912-c22c-4019-8bc8-7174907f0ba8.png)
![000065 554638129](https://user-images.githubusercontent.com/45902449/230614581-db748937-6fda-454e-b349-b2520ab46586.png)
![000065 1092119634](https://user-images.githubusercontent.com/45902449/230614583-59e63def-fcb4-4d7f-a88c-cd0edfb5bb4a.png)
![000066 203273053](https://user-images.githubusercontent.com/45902449/230614585-a94cc9fc-2c91-434b-8a36-cc6d1bb7b783.png)
![000067 596056018](https://user-images.githubusercontent.com/45902449/230614588-5b34dfc9-93be-441d-b67b-d0c3215ee551.png)
![000067 975644225](https://user-images.githubusercontent.com/45902449/230614590-e55d3dd9-d26d-4042-a2d0-fb05086024ad.png)

2.) Some interesting objects:
![000001 2359848280](https://user-images.githubusercontent.com/45902449/230614721-f42bbdae-7e90-4427-a5aa-b36823de8e8a.png)
![000002 777133775](https://user-images.githubusercontent.com/45902449/230614726-19d90340-d7db-4499-9c53-f6d9f1df00bd.png)
![000002 4261728101](https://user-images.githubusercontent.com/45902449/230614731-fbea32c8-4ccd-453d-a6ad-f1648a6700e5.png)
![000004 816445907](https://user-images.githubusercontent.com/45902449/230614734-71f43409-7822-442d-8d34-71e06f6c3901.png)
![000005 170254591](https://user-images.githubusercontent.com/45902449/230614739-7ccd2041-9f14-45d8-af5e-b5bc9f74e39f.png)
![000006 62294156](https://user-images.githubusercontent.com/45902449/230614742-d56c6330-757f-416b-876d-3776270e4a6d.png)
![000006 80086353](https://user-images.githubusercontent.com/45902449/230614744-476a0882-a28a-42d2-acfc-3e7da40bf4f6.png)
![000006 224839186](https://user-images.githubusercontent.com/45902449/230614750-c3cc03e7-3071-4b43-a02e-47222be1dbe5.png)
![000006 572950670](https://user-images.githubusercontent.com/45902449/230614753-b6d96d3f-aae3-4b19-bb2d-4102244d08db.png)
![000006 638426366](https://user-images.githubusercontent.com/45902449/230614757-a132b56e-1761-4131-999c-8fb04ace4245.png)
![000006 643334009](https://user-images.githubusercontent.com/45902449/230614760-3c4d64bd-b0ed-4807-97cd-d72841faef19.png)
![000006 830271919](https://user-images.githubusercontent.com/45902449/230614762-d79b67cd-c0bb-4a0e-8567-35b4bfee9bef.png)
![000006 834188094](https://user-images.githubusercontent.com/45902449/230614766-9535feb7-93f9-4056-8a75-4fa69c1568f8.png)
![000006 882288791](https://user-images.githubusercontent.com/45902449/230614769-c56ac13a-6447-40b3-9f65-f9f035f1115d.png)
![000006 971944395](https://user-images.githubusercontent.com/45902449/230614773-637e77dc-d880-4a77-9b27-ae6f16bb3aa6.png)
![000006 1069736781](https://user-images.githubusercontent.com/45902449/230614779-473e043f-6e92-4894-9d3e-0961b0be337e.png)
![000006 1501752557](https://user-images.githubusercontent.com/45902449/230614783-acf3bc56-1f13-4fdc-9816-091d65e2b7d3.png)
![000006 1529110433](https://user-images.githubusercontent.com/45902449/230614787-94e1dcaa-2698-403f-82bb-dceffdcd5fe2.png)
![000006 1533406408](https://user-images.githubusercontent.com/45902449/230614790-4dc88c69-4639-4a21-b1c5-e0c121475033.png)
![000006 1575526894](https://user-images.githubusercontent.com/45902449/230614791-819caa38-eeee-4dc6-a3d9-68e125421d4f.png)
![000006 1641006910](https://user-images.githubusercontent.com/45902449/230614792-afb74609-5304-4798-9f10-5261105df7db.png)
![000006 1858675071](https://user-images.githubusercontent.com/45902449/230614797-40a881d1-ff8c-450e-b075-3431599c2f7b.png)
![000006 2012191767](https://user-images.githubusercontent.com/45902449/230614801-ca4a64d5-ef09-4619-8a70-bbcbc32d06b4.png)
![000006 2066215042](https://user-images.githubusercontent.com/45902449/230614803-f6386860-c106-4228-b9cb-7d21a5f14a21.png)
![000006 2547475365](https://user-images.githubusercontent.com/45902449/230614805-1f5d07a7-b26c-43d5-9596-f993e5c1b50e.png)
![000006 2636088076](https://user-images.githubusercontent.com/45902449/230614807-f9da8d88-cd96-4ffa-a6eb-4c22219950fe.png)
![000006 2710120788](https://user-images.githubusercontent.com/45902449/230614811-7467affb-46d1-4c53-91e9-b0c4f94739a1.png)
![000006 2967118991](https://user-images.githubusercontent.com/45902449/230614813-31f8bb6d-a3aa-4fbc-912a-d3af3da215e3.png)
![000006 3111393895](https://user-images.githubusercontent.com/45902449/230614816-36ec2f60-bf59-4017-9c26-e5d5fed24274.png)
![000006 3193552653](https://user-images.githubusercontent.com/45902449/230614821-062b916f-a179-42b1-9960-6938f55a0cae.png)
![000006 3229949481](https://user-images.githubusercontent.com/45902449/230614825-27c20e3c-82e6-4f8d-8b44-1d988adbc879.png)
![000006 3342931854](https://user-images.githubusercontent.com/45902449/230614826-641b4def-099c-4576-b4dd-c04344f1eb33.png)
![000006 3417532400](https://user-images.githubusercontent.com/45902449/230614828-5c499011-ea25-45e9-aa7a-bbee3f25a6b1.png)
![000006 3450147572](https://user-images.githubusercontent.com/45902449/230614831-189c6e5c-3a4c-468c-9d13-1b367260c628.png)
![000006 3691455204](https://user-images.githubusercontent.com/45902449/230614834-25d30cf3-5f2d-46e0-aeec-ca3d7232c25d.png)
![000006 3865149322](https://user-images.githubusercontent.com/45902449/230614838-1ce99b51-285b-48f4-ae96-b538e532a720.png)
![000006 4118529066](https://user-images.githubusercontent.com/45902449/230614843-af78beb4-4c14-43ee-bff5-5e86e76b706b.png)
![000011 1027537702](https://user-images.githubusercontent.com/45902449/230614845-a88dc321-a7c8-4356-b7ce-c9e56b797f7c.png)
![000022 2802654282](https://user-images.githubusercontent.com/45902449/230614847-92e69167-7107-4980-8816-6eb5ac2b351d.png)
![000023 1560582298](https://user-images.githubusercontent.com/45902449/230614851-a0846b01-2637-408c-be73-491a83ec3f48.png)
![000023 3880554886](https://user-images.githubusercontent.com/45902449/230614858-f8d62150-e8af-4b86-9599-6baf21b8aa73.png)
![000025 1277816941](https://user-images.githubusercontent.com/45902449/230614860-6308fa11-9311-4605-b43d-28b8835e6b73.png)
![000026 45628696](https://user-images.githubusercontent.com/45902449/230614863-5555cbbe-de7d-4916-9543-52853571aa21.png)
![000029 3469483607](https://user-images.githubusercontent.com/45902449/230614864-4fbc5d83-50ef-445d-a449-ec8cd23cc900.png)
![000034 90191067](https://user-images.githubusercontent.com/45902449/230614865-a729b634-6988-417e-95bb-3fee6e035938.png)

**Comment by qndel** [comment]
what's wrong with last ones lol

**Comment by AJenbo** [comment]
some funny ones in there :)

i think the wall is better no 2, but easy to combine withe 1

**Comment by Chance4us** [comment]
> some funny ones in there :)
> 
> i think the wall is better no 2, but easy to combine withe 1s floor

You mean the second picture counted from the top?
Do you think the wall patterns in the top picture are exaggerated?

**Comment by Chance4us** [comment]
Greetings @AJenbo, I need your opinion on the floor was modeled in Blender.
The walls have an incorrect texture, can be ignored here.

Floor:
![FLOOR1](https://user-images.githubusercontent.com/45902449/235373049-18a9bd35-c1a2-4b74-b061-30702e61723b.png)

Overall impression:
![FLOOR2](https://user-images.githubusercontent.com/45902449/235373079-82697fb7-49b4-4a4c-846d-b28f39169477.png)

Floor with a bit noise:
![FLOOR3](https://user-images.githubusercontent.com/45902449/235373111-d1bdc548-df1f-46a4-b8e2-c14de262c60f.png)

Floor with a bit noise overall impression:
![FLOOR4](https://user-images.githubusercontent.com/45902449/235373141-574f00b4-9437-4fc7-93bf-1668e33d7996.png)

We can still warp the edges a bit.
I'm afraid it doesn't get much better.
Is that enough for us?
Can I produce the walls as next step?

**Comment by AJenbo** [comment]
Oh wow nice work 🙂

**Comment by Chance4us** [comment]
I would like to present an interim result and need feedback on some of the following questions.
First of all, I need feedback on whether the design with the pillar and the left wall structure is sufficiently well designed. The shadows are still missing and the rhombuses are not colored appropriately. Some areas are not quite sharp and there is a slight difference between left and right side.
I therefore need feedback as to whether there are still objections or suggestions for improvement in some areas.

![crypt](https://github.com/diasurgical/devilutionX/assets/45902449/6b076102-81d7-480d-b1f5-e302786bf04b)

**Comment by AJenbo** [comment]
Holy shit that's amazing!

I don't think you need to really do much more work on the walls. Maybe have a bit of variation to the floor (is see they had both a wet and damaged tile in the original.

For lighting I would try something like this:
![image](https://github.com/diasurgical/devilutionX/assets/204594/acd7c257-c5f7-47e8-ae31-3d87ced1f2e0)

**Comment by Chance4us** [comment]
Thanks, so I'll try to get some broken and wet tiles and after some improvements I think we can complete this task.

**Comment by Chance4us** [comment]
Before we try modifications below are new raw data with improved shape and color texturing.

![crypt_loading](https://github.com/diasurgical/devilutionX/assets/45902449/83292876-95b8-4375-952c-1f2579cfe872)

**Comment by Chance4us** [comment]
@AJenbo 

I post-processed the image as follows to match the colors and noise first.
![post-processed](https://github.com/diasurgical/devilutionX/assets/45902449/0d902595-d618-4f8e-a3de-42b0a42b97b7)

Afterwards I broke some tiles a bit.
![broken_tiles](https://github.com/diasurgical/devilutionX/assets/45902449/71c410cb-971a-40d2-8166-a81dff70c6b8)

I need a short feedback if you like the result.
I haven't been able to make good progress with wet tiles yet, but working on it.

**Comment by AJenbo** [comment]
Nice work that breaks it up in a good way :+1: 
I don't think there really needs to be more wet tiles, it already blends better.

**Comment by Chance4us** [comment]
Great, then I suggest we do some proper lighting and then it should be done. :smiley:

**Comment by AJenbo** [comment]
Should I do the lighting or can you handle that as well :)

**Comment by Chance4us** [comment]
You're welcome to do it and I'll tell you if I like it. :wink:

**Comment by AJenbo** [comment]
If you have time to do it then I would much appriciate it :)

**Comment by Chance4us** [comment]
Is that okay?
![crypt_loading](https://github.com/diasurgical/devilutionX/assets/45902449/b2962c42-42b1-4bce-8406-f4231e7587ac)

**Comment by AJenbo** [comment]
It's more then ok :)

**Comment by Chance4us** [comment]
Will probably dream of this tile pattern for a long time. :joy:

**Comment by AJenbo** [comment]
Here it is converted to 8bit. The only change i did was lower the overall brightness by 2, if I didn't the conversion ended up putting to much gray in the dark area.

![image](https://github.com/diasurgical/devilutionX/assets/204594/87045fc5-2b85-48af-a46e-ad84a213e022)

**Comment by Chance4us** [comment]
I see no difference at all.
