### ISSUE TITLE
Dark graphical error under voice button

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#5982]
![image](https://user-images.githubusercontent.com/204594/232251032-263d1a4e-9ab9-4e05-b6d9-bc1238ee73fe.png)

**Comment by ephphatha** [comment]
It looks like https://github.com/diasurgical/devilutionX/blob/master/Packaging/resources/assets/data/talkbutton.clx is malformed. This appears to be a sheet of three 16 pixel high sprites (button neutral, then two copies of a button pressed graphic) but the header indicates it's a single sprite at 48 pixels high. The translated versions of the buttons end up being built on a surface that's 48*3 pixels high and the wrong offsets are assigned to both pressed sprites so they appear all black.
