### ISSUE TITLE
Adria - ui misaligned text

### ISSUE THREAD

**Issue by thiagol-fenix** [diasurgical/devilutionX#5992]
### Operating System

Linux x64

### DevilutionX version

1.4.1 (latest release)

### Describe

When you interact with Adria and select the "Recharge staves" option and you don't have any, the header text breaks slightly.

If you do have a staff, the text is displayed correctly aligned.

### To Reproduce

![Captura desde 2023-04-17 19-55-45](https://user-images.githubusercontent.com/131033547/232582120-a8902a25-3ff4-4d25-ac7c-c38b67f9e8c1.png)

![Captura desde 2023-04-17 19-55-23](https://user-images.githubusercontent.com/131033547/232582181-7762c212-5374-43bd-8f6f-22dc842b9372.png)

### Additional context

I found the error playing with the Spanish language and it also breaks, so I deduce that it is not a translation error.

**Comment by ephphatha** [comment]
Already fixed in master (by https://github.com/diasurgical/devilutionX/pull/5189)

**Comment by thiagol-fenix** [comment]
It's nice to see people so active, well done! :D
