### ISSUE TITLE
Error messages not implemented in main UI

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#60]
Errors like when a game was not detected at the target ip should be shown as an in UI error message. Currently they are instead displayed as a popup.

Most critically this allows you to overwrite an existing hero of the same name.

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/59956110-83dbd580-948e-11e9-855d-5c18402bfa82.png)

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/59956113-8ccca700-948e-11e9-8827-ea3a15473f0d.png)

**Comment by glebm** [comment]
This would improve SDL1 experience as well because SDL1 doesn't it even have a popup (there's no `SDL_ShowSimpleMessageBox` in SDL1).

**Comment by AJenbo** [comment]
Another case
![image](https://user-images.githubusercontent.com/204594/65858988-7eccd300-e367-11e9-8262-b2c1c590cabf.png)

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/71428411-effaf880-26c0-11ea-91cc-f8d43f017df3.png)

![image](https://user-images.githubusercontent.com/204594/71428412-f2f5e900-26c0-11ea-8898-a68695822fb0.png)

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/71565494-80fe1500-2aaf-11ea-8c83-d201d1271bb2.png)

![image](https://user-images.githubusercontent.com/204594/71565496-83606f00-2aaf-11ea-9449-108568739ab9.png)
