### ISSUE TITLE
Defective lighting under the missiles

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6028]
The lighting under the missiles are dim in current master see below.
Only tested it in the crypt at first.

https://user-images.githubusercontent.com/45902449/233831709-8756299a-0d6a-459b-8cf6-87b6e1ce91ef.mp4

Let me know if further information is needed.

Savegame:
[single_3.hsv.zip](https://github.com/diasurgical/devilutionX/files/11303318/single_3.hsv.zip)

**Comment by AJenbo** [comment]
Lighting in Hellfire is fairly broken, I'm currently working on rewriting it in a way that works properly within the engine.

**Comment by AJenbo** [comment]
Closed since this is being solved as part of https://github.com/diasurgical/devilutionX/issues/3601

**Comment by AJenbo** [comment]
For extra context this is fixed in https://github.com/diasurgical/devilutionX/pull/6025
