### ISSUE TITLE
Anvil of fury wrong color

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6039]
The anvil of fury has wrong color in town.
I believe that it is a regression and the issue has already occurred before.

![Bildschirmfoto vom 2023-04-24 22-58-53](https://user-images.githubusercontent.com/45902449/234116118-5613f4f0-3cbc-4588-adaa-e07de02a37a1.png)

Savegame:
[anvil.zip](https://github.com/diasurgical/devilutionX/files/11314657/anvil.zip)

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/234367663-01545f51-9d52-466b-b9eb-17e3e12f869d.png)
Not sure what you expected here?

**Comment by julealgon** [comment]
Maybe this is a lighting mismatch illusion? Town has zero shadows so it appears brighter than in caves in general I think.

**Comment by Chance4us** [comment]
Sorry for the disinformation.
The texture hardly differs from the grass and the anvil is barely visible on ground. :joy:
