### ISSUE TITLE
Invisible player

### ISSUE THREAD

**Issue by myself600** [diasurgical/devilutionX#6051]
### Operating System

Other (please specify)

### DevilutionX version

Other (please specify version number)

### Describe

May be related to #4546

Yesterday, I was playing on ZT (test builds) when someone joined my game. The *only* way to tell I'm not alone was the lag (flickering hourglass). This happened 3x, while the first time he dropped out (flickering to static hourglass, then no lag). After leaving the game, I was able to see my game up with the player who joined the game, but couldn't join. ~I assume this isn't some incompatibility with mods like wkdmod as that day I've encountered other players (test build) with no issues. (can't confirm)~

### To Reproduce

(none)

### Screenshots

![Screenshot_20230426_002401](https://user-images.githubusercontent.com/3542623/234533693-8f47c12a-e4e5-4531-9da6-1786a2aa3edd.gif)
![Screenshot_20230426_003534](https://user-images.githubusercontent.com/3542623/234550411-67aba596-8bdd-46c8-83d3-4e95abdf2f95.gif)
Only the flickering hourglass revealed the presence of another player (no presence log on the left side)

![Screenshot_20230426_003755](https://user-images.githubusercontent.com/3542623/234530485-0c98d389-0843-4a14-ada3-770097165046.gif)
The hidden player

![Screenshot_20230426_003735](https://user-images.githubusercontent.com/3542623/234534032-939a23de-1330-4dc1-9582-2a93b0179e8d.gif)
Nothing happened when I tried to join him

![2023-04-08-114706_1920x1080_scrot](https://user-images.githubusercontent.com/3542623/234531991-9e4a41d8-dd69-4af5-a06f-6ab8891b71d2.gif)
A different case (v1.4.1) with the character animation visible (April 08, 2023 11:47:06 CEST)

### Additional information

**Version**: Github Actions (test) build from April 19, 2023 01:26:18 CEST
**Operating system**: Manjaro ARM 23.02

**Comment by StephenCWills** [comment]
> ### Additional information
> **Version**: Github Actions (test) build from April 19, 2023 01:26:18 CEST
> **Operating system**: Manjaro ARM 23.02

There is no such build. Maybe you're saying that's when you downloaded it? Assuming you got the latest version available at that time, that would mean it's probably 31810d7.

> Only the flickering hourglass revealed the presence of another player (no presence log on the left side)

I'm pretty sure this means he wasn't in your game. Most likely, he was stuck on the loading bar just like you were when you tried to rejoin.

> Nothing happened when I tried to join him

My guess is he was sitting in the menu or on the loading bar, transmitting that he was in your game even though he wasn't actually in it. However, even if he was in a game, I imagine you probably wouldn't be able to join him. We don't know what build he was using, so it's difficult to say whether this is an issue or just an incompatibility between versions.

If he was in the menu transmitting your game info, it would either have to be a really old test build, a custom build, or an edge case that's not fixed by #4626.

**Comment by AJenbo** [comment]
Likely this is an incompatibility between two different testbuilds

**Comment by myself600** [comment]
> There is no such build. Maybe you're saying that's when you downloaded it? Assuming you got the latest version available at that time, that would mean it's probably [31810d7](https://github.com/diasurgical/devilutionX/commit/31810d759602fd9c5be401b0a4522f6dcbcb192c).

It's the extracted files modified date. Why isn't a Git commit hash shown within the main menu (bottom-left corner) or in terminal? (`--version` flag)

> > Only the flickering hourglass revealed the presence of another player (no presence log on the left side)
> 
> I'm pretty sure this means he wasn't in your game. Most likely, he was stuck on the loading bar just like you were when you tried to rejoin.

When someone tries to join a ZT game (v1.4.1) and can't, the game freezes (except the hourglass cursor) for a while and then the game continues normally, without any message. If a player successfully joins a game and I get microlags (flickering hourglass), depending on how bad it is, it sometimes end up that the game freezes (again, only the hourglass cursor is responding) and the player drops with a message that "Player 'XYZ' dropped due to timeout". Hence, I assume the player was present judging by the lag.



> Likely this is an incompatibility between two different testbuilds

There were two games with two players in both before and another player joined my game afterwards (test build). I believe the other two players *may* have been Brewbeck and wkdmgr playing wkdmod, but I'm not sure. I should ask on Discord.

**Comment by DakkJaniels** [comment]
> and that wkdmod ZT public games does not show up in DevilutionX test builds.

I don't think that's true. It uses the same multicast address, so I think the games should show up in beta builds.
