### ISSUE TITLE
Stuck in PrepareInnerBorders() when entering level 14

### ISSUE THREAD

**Issue by crashGG** [diasurgical/devilutionX#6061]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

Game crashes when entering level 14

here is the save file just before entering
[save.zip](https://github.com/diasurgical/devilutionX/files/11358811/save.zip)

### To Reproduce

Click on the Entrance of the level 14

### Additional context

The issue also occurs in the latest master version

**Comment by AJenbo** [comment]
Ok, had to defeat a bunch of monsters and the warlord of blood befor i was able to click the entrance, but at that point it just loaded level 14 normally. Both in 1.4.1 and 1.5.0-beta. So I'm unable to replicate the issue.

**Comment by AJenbo** [comment]
Never mind, I had two save games both on level 13 and picked the wrong one.

**Comment by AJenbo** [comment]
Here is a test build with the fix for this issue: https://github.com/diasurgical/devilutionX/suites/12571808477/artifacts/672139954

Thanks for reporting.

**Comment by crashGG** [comment]
you did great,the issue has been fixed !
