### ISSUE TITLE
Multiplayer -> Armor disappear after death

### ISSUE THREAD

**Issue by andrey-barbyshev** [diasurgical/devilutionX#6097]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

After death and full stuff drop, I'm trying to pick up armor and it just disappear from the floor. Second player can't even see armor on floor when I die. Happened multiple time during several hours of game.
One time happened with multiple items, but usually it is only armor.

### To Reproduce

1. Die with equipped armor
2. restart in town
3. Go back to death place
4. Try to pick up amor
5. Armor disappear

### Expected Behavior

Expected to get all stuff after death

**Comment by Trihedraf** [comment]
#5423 Already fixed in upcoming release.
