### ISSUE TITLE
Awaking packs of enemies in another room (by hit or noise)

### ISSUE THREAD

**Issue by MerleMoqueur** [diasurgical/devilutionX#6107]
If there are enemies in the next room that don’t know I’m here, they’ll stay quiet as long as I don’t mess with them. Let’s imagine I shoot an arrow through the entrance in a pack of such enemies, one of them will be hit, and only the one that has been hit will awake and come to me.

From a realistic point of view, all the enemies close to it should notice what happened and awake at the same time. And that’s true too for anything that would pass close to them, even without being hit (arrows, and noisy/flashy spells), and even battling noise only should be enough, which may lead to the imagine the concept of "noise radius".

That would obviously increase difficulty (especially for Diablo’s lair), but I think it should be considered.

**Comment by AJenbo** [comment]
considered a mod

**Comment by julealgon** [comment]
> From a realistic point of view, all the enemies close to it should notice what happened and awake at the same time.

Depends on their intelligence level (which is something that is already modeled in D1 so it could be leveraged for this).

Not disagreeing with you, just pointing out it has that extra complication factor that I think should be considered in the implementation if you want to make it "realistic inside the constraints of the game".

Also this could be part of a much larger mechanism that involved other scenarios, for example, a monster fleeing from you triggering other monster to flee as well.

**Comment by nickgavran** [comment]
The feature explained here is both present in TH1 and TH2. If you want to get a feel for how this plays, you could boot up those mods.
From my own experience, it adds quite a lot to the gameplay, in a positive way.

But for the sake of DevilutionX, this feature would be a mod,
