### ISSUE TITLE
Monk class is not available

### ISSUE THREAD

**Issue by JulianoFdeS** [diasurgical/devilutionX#6113]
### Operating System

Windows x64

### DevilutionX version

1.4.1 (latest release)

### Describe

As the title says, Monk class is not available to be playable for me.
I have already put hellfire.mpq, hfmonk.mpq, hfmusic.mpq and hfvoice.mpq inside the folder and Monk is still unavailable.
I went through the settings, I could activate Bard and Barbarian but no option to Monk.

![image](https://github.com/diasurgical/devilutionX/assets/26306497/51579621-98e8-420c-95ce-143854563e83)

Am I doing something wrong?

I'm looking forward to play this Mod, just want to figure out where's the Monk class before start.

### To Reproduce

Copy DIABDAT.MPQ from the CD or GOG-installation (or [extract it from the GoG installer](https://github.com/diasurgical/devilutionX/wiki/Extracting-the-.MPQs-from-the-GoG-installer)) to the DevilutionX folder.

To run the Diablo: Hellfire expansion you will need to also copy hellfire.mpq, hfmonk.mpq, hfmusic.mpq, hfvoice.mpq.

### Expected Behavior

Monk Class Available

**Comment by ChaosMarc** [comment]
You're in "Diablo-Mode" and have to switch to "Hellfire-Mode" as the monk is only available there:

![image](https://github.com/diasurgical/devilutionX/assets/1343751/49a18ae2-b5f6-4b36-bfae-9ba0a27f2bd4)

![image](https://github.com/diasurgical/devilutionX/assets/1343751/ed8e6133-75a2-41a6-8dcb-ebabb6d0b4b0)

![image](https://github.com/diasurgical/devilutionX/assets/1343751/2a3f0913-f65b-4e2c-a812-08b4d613733d)

![image](https://github.com/diasurgical/devilutionX/assets/1343751/8e2ed0e2-812d-495d-92d6-22e666ddd7b3)

**Comment by JulianoFdeS** [comment]
> You're in "Diablo-Mode" and have to switch to "Hellfire-Mode" as the monk is only available there:
> 
> ![image](https://user-images.githubusercontent.com/1343751/239318864-49a18ae2-b5f6-4b36-bfae-9ba0a27f2bd4.png)
> 
> ![image](https://user-images.githubusercontent.com/1343751/239318951-ed8e6133-75a2-41a6-8dcb-ebabb6d0b4b0.png)
> 
> ![image](https://user-images.githubusercontent.com/1343751/239319017-2a3f0913-f65b-4e2c-a812-08b4d613733d.png)
> 
> ![image](https://user-images.githubusercontent.com/1343751/239319084-8e2ed0e2-812d-495d-92d6-22e666ddd7b3.png)

I feel stupid for not realized this before. THANK YOU VERY MUCH!
