### ISSUE TITLE
[improvement request] NPC should stop repeating their welcoming sentence

### ISSUE THREAD

**Issue by MerleMoqueur** [diasurgical/devilutionX#6119]
Currently, when the players talks several times to the same NPC, the latter repeats the same welcoming sentence each time, over and over. This is both weird sounding and annoying. It would be better and much more realistic if the NPC uttered the welcoming sentence only once for each time the player comes to town.

**Comment by AJenbo** [comment]
At best we could say that there could be a time delay or a visit elsewhere would reset it, but I think this is both a bit zealous and opinion based. On top of that I would also work against the accessibility goals for 1.6.0
