### ISSUE TITLE
[improvement request] Close NPC window when clicking outside of it

### ISSUE THREAD

**Issue by MerleMoqueur** [diasurgical/devilutionX#6120]
It's currently necessary to click "say goodbye" or "leave […]" in the dialog window of the NPCs in town to leave them, which is a little bit rigid (especially when the player is used to Diablo II). A friendlier option would be to be allowed to just click outside the window in order to close it and leave the NPC.

**Comment by AJenbo** [comment]
you can also press esc

**Comment by kphoenix137** [comment]
I agree 100% with this sentiment. I personally have found it annoying to have to press ESC a few times or click the back/leave buttons to exit a shop.

**Comment by julealgon** [comment]
A bit surprised to see a couple downvotes on this one. @agris-codes and @FitzRoyX do you have any specific concerns about it?

Clicking outside windows to dismiss them is a fairly common UX pattern. Even though I'm used to pressing ESC by this point, I can see it not being very intuitive to a lot of folks.

Was wondering if there is maybe something I'm missing with this in terms of impact.

**Comment by qndel** [comment]
@julealgon as if fitzroy would need a reason to downvote xD

**Comment by agris-codes** [comment]
> A bit surprised to see a couple downvotes on this one. @agris-codes and @FitzRoyX do you have any specific concerns about it?
> 
> Clicking outside windows to dismiss them is a fairly common UX pattern. Even though I'm used to pressing ESC by this point, I can see it not being very intuitive to a lot of folks.
> 
> Was wondering if there is maybe something I'm missing with this in terms of impact.

To me, it’s a solution in search of a problem. I agree it’s innocuous enough, but the general idea of brining 2020-era UX conventions to D1 slowly erodes its identify as a 1996 game. There’s a lot that’s already been done in that regard, like optional widescreen, xp bar, monster health bar with immunities; I could go on. 

They are all optional and I understand why they exist, but this general notion of small tweaks to make function X or Y more palatable to current design trends should not be a guiding sentiment. Rather, it should be heavily scrutinized with a default assumption of OG 1996 behavior.

and ok, maybe I’m a keyboard supremacist :P

enough old man yells at clouds, but that’s why I downvoted

**Comment by kphoenix137** [comment]
> 

We have a version of DevilutionX for people who don't like modernization. It's called Devilution.

**Comment by julealgon** [comment]
> > A bit surprised to see a couple downvotes on this one. @agris-codes and @FitzRoyX do you have any specific concerns about it?
> > Clicking outside windows to dismiss them is a fairly common UX pattern. Even though I'm used to pressing ESC by this point, I can see it not being very intuitive to a lot of folks.
> > Was wondering if there is maybe something I'm missing with this in terms of impact.
> 
> To me, it’s a solution in search of a problem. I agree it’s innocuous enough, but the general idea of brining 2020-era UX conventions to D1 slowly erodes its identify as a 1996 game. There’s a lot that’s already been done in that regard, like optional widescreen, xp bar, monster health bar with immunities; I could go on.
> 
> They are all optional and I understand why they exist, but this general notion of small tweaks to make function X or Y more palatable to current design trends should not be a guiding sentiment. Rather, it should be heavily scrutinized with a default assumption of OG 1996 behavior.
> 
> and ok, maybe I’m a keyboard supremacist :P
> 
> enough old man yells at clouds, but that’s why I downvoted

Thanks for sharing @agris-codes . 

Yeah... I guess we'll have to agree to disagree on some of those aspects. My view is that, as long as the change doesn't violate the original design, it should be mostly ok. Now.... I do admit this criteria is extremely subjective... perhaps to you it already fits in the "violates the original design" criteria.

Now... I do think that enabling widescreen and, especially, higher internal resolutions, massively impact the gameplay and I thus wouldn't put those in the same category. The fact that those are configurable alleviates some of the concerns though.
