### ISSUE TITLE
Monsters slide when stone cursing during movement and then save/loading

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#6125]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

latest master
[single_3r.zip](https://github.com/diasurgical/devilutionX/files/11523364/single_3r.zip)

### To Reproduce

Load savegame and do nothing. When stone curse expires, both rhinos will teleport 1 tile backwards and do a forward slide. Something about their animation state isn't being saved or restored correctly when stone cursed.

**Comment by StephenCWills** [comment]
Tested with a Black Death, and the same thing happens.

**Comment by AJenbo** [comment]
any idea when this started?

**Comment by obligaron** [comment]
When blizzard added stone curse  😉 
It's a vanilla issue, but it surfaces a little bit different in devilutionX.

https://github.com/diasurgical/devilutionX/assets/25415264/8ad98cb4-7bb3-4505-b902-9691c597af90

**Comment by AJenbo** [comment]
oh that's not all to bad, it's just that the current walk cycle isn't animated

**Comment by StephenCWills** [comment]
Monsters are loaded before missiles, so the Stone Curse missile can't be used to sync the animation at the point when the monster is loaded.
