### ISSUE TITLE
Adria forcibly turns on the staff after recharging

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6143]
Adria forcibly turns on the staff after recharging.
For example the Staff of Mana spell will be forcibly turned on after recharging.

**Comment by AJenbo** [comment]
like it's getting set as the active spell?

**Comment by Chance4us** [comment]
Yes :grin:

**Comment by qndel** [comment]
![image](https://github.com/diasurgical/devilutionX/assets/14297035/3bfe6185-a8f1-44e2-b812-3acb17dd97ee)
