### ISSUE TITLE
Add list of known mods to README?

### ISSUE THREAD

**Issue by mewmew** [diasurgical/devilutionX#616]
This is a start, feel free to add more:

* https://github.com/qndel/Infernity
* https://github.com/Manuel-K/devilutionX-QOL-patches
* https://github.com/sergi4ua/equine
* ...

**Comment by AJenbo** [comment]
By request:

- Render for the Raspberry Pi Sense HAT: https://github.com/AJenbo/devilutionX/tree/SenseHAT
<a href="http://www.youtube.com/watch?feature=player_embedded&v=756WmJguxZA
" target="_blank"><img src="http://img.youtube.com/vi/756WmJguxZA/0.jpg"
alt="Game play video" width="240" height="180" border="10" /></a>

- Rouge-like text render: https://github.com/AJenbo/devilutionX/tree/roguelike
<a href="https://www.youtube.com/watch?feature=player_embedded&v=3p9j7j2SVOA
" target="_blank"><img src="http://img.youtube.com/vi/3p9j7j2SVOA/0.jpg"
alt="Game play video" width="240" height="180" border="10" /></a>

**Comment by mewmew** [comment]
Closing this issue for now. If you know of any mods that are not yet on the list, just send a PR :)
