### ISSUE TITLE
Gharbad's speech is wrong

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6160]
Gharbad's speech is wrong and it is not possible to complete the quest.

![gharbad](https://github.com/diasurgical/devilutionX/assets/45902449/8d6026a2-ed5c-416f-89a6-825578e3c30f)

Savegame:
[gharbad.zip](https://github.com/diasurgical/devilutionX/files/11593635/gharbad.zip)

Additional context:
He stole Ogden's sign.

**Comment by Chance4us** [comment]
Two quests cannot be completed with this issue (Gharbad the weak, Ogden's sign).
Gharbad was spoken first while the banner was in inventory.

**Comment by AJenbo** [comment]
Nice catch
