### ISSUE TITLE
IOS: Unable To Install "DevilutionX" This app cannot be installed because its integrity could not be verified.

### ISSUE THREAD

**Issue by rtrzebinski** [diasurgical/devilutionX#6183]
Hi, is there any way around

```
Unable To Install
"DevilutionX"
This app cannot be installed
because its integrity could not be
verified.
```

On IOS?

I copied `devilutionx-ios.ipa` to my iPhone but it does not run with the following message:

![IMG_4409](https://github.com/diasurgical/devilutionX/assets/3026410/09955245-3510-41a8-acfe-9d4e68a9a8bc)

This page mentions that I can have up to 3 app not from the official APP Store, but I only have - DevilutionX https://idevicecentral.com/ios-guide/app-cannot-be-installed-because-its-integrity-could-not-be-verified-on-ios/

**Comment by StephenCWills** [comment]
Have you tried following the installation instructions?
https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md

**Comment by rtrzebinski** [comment]
@StephenCWills Thank you for replying - yes, I'm stuck on `Once the App is installed, launch it once.`

**Comment by AJenbo** [comment]
which method did you use?

**Comment by rtrzebinski** [comment]
@AJenbo I installed with `Install IPA with Apple Configurator on Mac` as described here -> https://chrunos.com/install-ipa-on-iphone/

Perhaps I have to used one of the methods mentioned in the docs. (I didn't think it matters)

**Comment by AJenbo** [comment]
Please try `Method 2: Using Finder (MacOS)` as described here -> https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md

**Comment by rtrzebinski** [comment]
`Method 2: Using Finder (MacOS)` is the way to copy `diablodat.mpq` however before that app needs to run and create a folder for it (it is also described in https://github.com/diasurgical/devilutionX/blob/master/docs/installing.md).

**Comment by rtrzebinski** [comment]
This videos says it might be because of some outdated certificates - https://www.youtube.com/watch?v=SYMqCB_t-Jg

**Comment by AJenbo** [comment]
maybe @bubio can help?

**Comment by StephenCWills** [comment]
> This videos says it might be because of some outdated certificates - https://www.youtube.com/watch?v=SYMqCB_t-Jg

Maybe update iTunes and/or AltStore/Sideloadly?

**Comment by rtrzebinski** [comment]
I used `Apple Configurator` to copy a file to my iPhone, it is in latest version (just installed), I'm also on the latest iOS.

**Comment by StephenCWills** [comment]
> I used `Apple Configurator` to copy a file to my iPhone, it is in latest version (just installed), I'm also on the latest iOS.

Sounds like you didn't follow the installation instructions, then. I don't see anything about `Apple Configurator`. You need to install using AltStore or Sideloadly.

**Comment by rtrzebinski** [comment]
I wanted to use an official Apple software for that, not really trusting these 2 3rd party apps. Since this is just to copy the file to iPhone, which worked just fine, it should not matter, or am I wrong? Perhaps these 2 do something else on top of simply copying the file.

**Comment by StephenCWills** [comment]
It does matter, because the certificate is not vetted through Apple's app store verification process or whatever it is they do.

**Comment by rtrzebinski** [comment]
@StephenCWills Thank you, will try that then 👍

**Comment by rtrzebinski** [comment]
Both these apps want me to give them my Apple password, so I guess I'll skip, not trusting them, thank you for all your help.

**Comment by AJenbo** [comment]
That's fair. In addition to copying the file the apps also uses your certifikat at re-sign the IPA so that it's trusted by your device. If you can figure out how to do so manually you could probably copy it like you where trying to originally.

The reason for all of that is that we do not have access to a certificate that is recognized by Apple as that costs an annual fee.

**Comment by rtrzebinski** [comment]
I understand @AJenbo thank you.

**Comment by Trihedraf** [comment]
@rtrzebinski if you have a Mac you can build and install it through Xcode

**Comment by rtrzebinski** [comment]
> @rtrzebinski if you have a Mac you can build and install it through Xcode

@Trihedraf  Interesting, I might try that. Do I need to compile it from the source code, or use Xcode to copy the file to the iPhone only?

**Comment by AJenbo** [comment]
Probably from source, but should be pretty straight forward. Please see instructions here: https://github.com/diasurgical/devilutionX/blob/master/docs/building.md
