### ISSUE TITLE
Suffix "of the moon" does not give points to all attributes

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6185]
Not sure if the item is valid.
![mace](https://github.com/diasurgical/devilutionX/assets/45902449/02253ab4-2092-4be5-a7de-ff3015c7d6f4)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/11676456/single_0.hsv.zip)

The width of the text is not good either.

**Comment by DakkJaniels** [comment]
Where did you find this? What commit is this?
