### ISSUE TITLE
Wall transparency issues in debug builds

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6192]
There are wall transparency issues in debug builds when pressing the "ALT" key.
"ALT" key  is not pressed:
![alt_not_pressed](https://github.com/diasurgical/devilutionX/assets/45902449/c6563376-36f2-4909-8b6a-e472c92fba7b)

"ALT" key  is pressed:
![alt_pressed](https://github.com/diasurgical/devilutionX/assets/45902449/b2952033-3095-4f40-b006-5548d05652a7)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/11710080/single_0.hsv.zip)

Additional context:
The issue appears only in debug builds and has been occurring since at least V. 1.4.1

**Comment by Trihedraf** [comment]
It’s intentional for debugging.

**Comment by Chance4us** [comment]
Thanks. I didn't expect that, so I'll close the issue.
