### ISSUE TITLE
Lists do not scroll in menu UI

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#62]
This shows when having more then 5 heros in the select hero screen, but is also present in other places.

**Comment by vimino** [comment]
This may be related to having _UiInitList_ (in _SourceX/DiabloUI/diabloui.cpp_) min and max arguments getting the entire list instead of just the visible section.
Perhaps **SelectedItemMin** and **SelectedItemMax** have to be updated on _UiFocus_ to show the right sub-section. I'll look into it.

**Comment by AJenbo** [comment]
![image](https://user-images.githubusercontent.com/204594/65857574-66a78480-e364-11e9-9997-b086e3a5a320.png)

Scrollbar keyboard behavior:
- page down jumps down one page, but leave the selection on the same relative item (if you 7 of 7 selected page down will leave 5 selected instead)
- page up jump one page

Scrollbar mouse behavior:
- click down arrow moves one down
- click up arrow moves one down
- clicking in area above or below the indicator does the same as page up and down.

**Comment by AJenbo** [comment]
The graphics for the scroll bar are found in the following 3 files:
ui_art\sb_arrow.pcx
ui_art\sb_bg.pcx
ui_art\sb_thumb.pcx

**Comment by glebm** [comment]
Thanks, this is some crazy PageUp/Down behaviour.
