### ISSUE TITLE
 Tabs spontaneously opening 

### ISSUE THREAD

**Issue by Netrunner42** [diasurgical/devilutionX#6205]
### Operating System

PlayStation Vita

### DevilutionX version

1.4.1 (latest release)

### Describe

During the game, tabs spontaneously open, such as: inventory and character characteristics.

### To Reproduce

1. Just run the game 
2. Load the game file or start a new game 
3. Having the issue 

### Expected Behavior

A normal gameplay without the issue

**Comment by AJenbo** [comment]
tabs? Are you refering to the inventory panel and character sheet?

**Comment by StephenCWills** [comment]
The inventory panel and character sheet are triggered by touch events on the back panel of the PS Vita. You can disable this in Controller settings by modifying the `Enable Rear Touchpad` option.

**Comment by Netrunner42** [comment]
Well, my dudes, I feel so stupid because it causes by touching on the back panel of the ps vita lol. Perhaps I have been touching the panel and did even not notice that. So simple to solve that.

**Comment by AJenbo** [comment]
No worries
