### ISSUE TITLE
Android TV support fails d-pad verification

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#6210]
![image](https://github.com/diasurgical/devilutionX/assets/204594/0a3aa31a-22a0-4899-a8b2-9a30621e42db)

Home Screen Banner: https://developer.android.com/training/tv/start/start.html#banner
UI Patterns: https://developer.android.com/design/tv/patterns.html#banner (404)
Visual Design and User Interaction https://developer.android.com/docs/quality-guidelines/tv-app-quality#TV-LB

DPAD Control: https://developer.android.com/training/tv/start/navigation.html#d-pad-navigation
Hardware Declaration: https://developer.android.com/training/tv/start/hardware.html#declare-hardware-requirements

**Comment by AJenbo** [comment]
I guess we should slap the app name on the banner:
https://github.com/diasurgical/devilutionX/blob/master/android-project/app/src/main/res/drawable/banner.jpg

I could sware the thing works with a dpad, but maybe they have some stipulations we are not following.

**Comment by StephenCWills** [comment]
Maybe they're testing with a remote control style d-pad.

![image](https://github.com/diasurgical/devilutionX/assets/9203145/6fe92542-7792-4cea-85d1-8dca66c588f2)

**Comment by StephenCWills** [comment]
This may be pretty hard if we have to follow their guidelines.

> Follow these guidelines to test that your app's navigation system works well with a D-pad on a TV device:
> 
> * Ensure that a user with a D-pad controller can navigate to all visible controls on the screen.
> * For scrolling lists with focus, make sure that the D-pad up and down buttons scroll the list and that the select button selects an item in the list. Verify that users can select an element in the list and that the list still scrolls when an element is selected.
> * Ensure that switching between controls is straightforward and predictable.

**Comment by AJenbo** [comment]
it could be that they think transfering the mpq files is to much work using a remote :D

But downloading the shareware is working though :)

**Comment by AJenbo** [comment]
> Is there a way we can contact them for more clarification? Otherwise, this is just going to be a guessing game.

It's Google, one way communication and no details. They do have a general support email but they mostly just reply "sorry can't help, try the website"

**Comment by StephenCWills** [comment]
> It's Google, one way communication and no details. They do have a general support email but they mostly just reply "sorry can't help, try the website"

Do you think they'd notice if we resubmit with no d-pad changes? Maybe they'll change their mind.

**Comment by AJenbo** [comment]
We did comply with what they said: :shrug: 

> Please make sure that menus and app navigation needed for the app’s core functionality are fully functional using a DPad. Please refer to our DPAD Control and Hardware Declaration documentation.

**Comment by glebm** [comment]
From StackOverflow: https://stackoverflow.com/questions/49713825/androidtv-missing-dpad-functionality

**Comment by AJenbo** [comment]
A good read, I wonder if the DataActivity should also have LEANBACK intent. And maybe they are getting stuck on the shareware download or something similar and we can just add a toast.
I think ideally we would make a progress bar for all active downloads though that doesn't feel like fun to implement.

**Comment by Kiiro-Yakumo** [comment]
It could be a fluke but when I tried to go around my remote controller, [1] and [2] actually made me drink the potions on the belt. Rewind, Forward, Stop unselect NPC, something like moving mouse away from the NPC itself. The "OK" button opens skills/spells belt. So at least in this case it's impossible to talk to anyone, probably impossible to fight either.

Oh and while on it, I'm not sure if it's global for Android but when typing name with on-screen keyboard, it covers a lot of space so one has to guess if the name has been deleted or not and such. Minor inconvenience but it exists.

**Comment by AJenbo** [comment]
Well playing the actual game should be done with a gamepad, not the remote. Only the menus have to be navigatable with it.

**Comment by Kiiro-Yakumo** [comment]
Makes sense. Still that's pretty nice set of possibilities to do with just a remote controller. Actually with "accept" and "cancel" one way or another, we could do at least some emergency buy/sell for example.

Tested quickly Logitech F710 and seems to work properly. The talking, menu, checking stash.

As for the Google's statement, in my humble opinion downloadable version for Android TV from here is more than sufficient. Many good programs go that way with skipping the Google Store for one reason or another. If you still want to push that update to the Store then honestly I don't know. Not many "usable" buttons on the remote controller to work with. If the back button can work without exitting the game then this could be "cancel" (Cross on Sony's gamepad), then middle button on directional section "ok" (Circle on Sony's gamepad) as on the image above. 1-8 probably will go for potions so 9 and 0 probably can be used as a backup if something would be still missing for Google...

**Comment by AJenbo** [comment]
Google has accepted the new banner, but is still faulting the app for not having d-pad navigation:
https://developer.android.com/training/tv/start/navigation.html#d-pad-navigation

**Comment by AJenbo** [comment]
Não falamos esta língua.  Entre em contato com o Google e eles lhe darão mais informações.  Seu comentário não parece estar relacionado a este projeto, portanto será removido.

**Comment by FullHDSG** [comment]
The same issue over here does anyone have a solution to this please share!

**Comment by AJenbo** [comment]
> The same issue over here does anyone have a solution to this please share!

@FullHDSG Contact Google, the issue will be different for each app. Get your own issue tracker for your app instead of spamming ours.

**Comment by AJenbo** [comment]
READ BEFORE POSTING HERE: If you have "this" issue with some other app don't write here. You issue will be different then ours, you should write Google to get further details about where in your app the issue is.

**Comment by AJenbo** [comment]
We have been accepted for Android TV:
![image](https://github.com/diasurgical/devilutionX/assets/204594/4422b80c-0554-4842-a5fd-7a0812cb72dc)

**Comment by Presheda** [comment]
> We have been accepted for Android TV: ![image](https://private-user-images.githubusercontent.com/204594/303274014-4422b80c-0554-4842-a5fd-7a0812cb72dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODQ4ODEsIm5iZiI6MTcwNzM4NDU4MSwicGF0aCI6Ii8yMDQ1OTQvMzAzMjc0MDE0LTQ0MjJiODBjLTA1NTQtNDg0Mi1hNWZkLTdhMDgxMmNiNzJkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwOTI5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTUzMmJkYTMwN2UwMGM0YWVkZjg3MzIzZTMxNGNmMTI4ZmRmYmE1YjVjMThjYmI1MTgzZjlhOTVkNDc4YTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PpEOOJDDy_MUb7IpDFTJ9oSuX4wPh3xNcRbDkusOPck)

What changes did you make @AJenbo

I'm still stuck

**Comment by AJenbo** [comment]
@Presheda I can't help you with your app, please write Google and not us about the issue you have with them. There is a contact link in the message they sent you.
