### ISSUE TITLE
Crash on level 4

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#6213]
### DevilutionX version

1.5.0 (latest release)

### Describe

[single_0.zip](https://github.com/diasurgical/devilutionX/files/11749828/single_0.zip)

Game closing on level 4, in the middle of the hall, walking down.

### To Reproduce

1. load
2. on level 4
3. walk down middle of the hall

**Comment by AJenbo** [comment]
Looks like there is a difference between how 1.4.1 and 1.5.0 generates this level.

**Comment by AJenbo** [comment]
Diablo 1.00:
![image](https://github.com/diasurgical/devilutionX/assets/204594/5d7350f3-1761-46c4-aa8b-6fd9a7d12fc1)
(didn't get the full map since i forgot to reset the level first)

This appears to be in line with 1.4.1 since the objects are placed sensibly

**Comment by AJenbo** [comment]
1.5.0 and 1.4.0
![image](https://github.com/diasurgical/devilutionX/assets/204594/32838ed7-b336-4099-9ba1-020a2662eff5)

1.2.0 and 1.3.0:
![image](https://github.com/diasurgical/devilutionX/assets/204594/6a1510ea-2632-4a82-9da3-d9bca2c28775)

**Comment by Chance4us** [comment]
Does this issue only happen on Android?

**Comment by AJenbo** [comment]
no, it happens on all systems

**Comment by Chance4us** [comment]
PlaceMiniSet in drlg_l1.cpp does no more return a 0, just true.
Can it have anything to do with it?

**Comment by AJenbo** [comment]
The issue is that if the BANNER quest is active then the stairs up should always be `STAIRSUP`
