### ISSUE TITLE
Misdirected to the Lazarus quest

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6217]
The previous events:
1. The Staff of Lazarus was already in inventory
2. When the hero was on the gate to Diablo, a Balrog was killed with chain lightning
3. The aforementioned Balrog lost a ring
4. When the player clicked on the ring, Lazarus' quest level was loaded surprisingly.

Situation after solving the quest.
![gate](https://github.com/diasurgical/devilutionX/assets/45902449/4925f735-70ac-43ef-9e6d-4611446ac332)

Savegame after loading the quest:
[single_1.hsv.zip](https://github.com/diasurgical/devilutionX/files/11759953/single_1.hsv.zip)

Additional context:
After solving the quest, Cain no longer accepts the staff of Lazarus.

**Comment by StephenCWills** [comment]
I forgot to link the PR.
