### ISSUE TITLE
Gameplay option to make broken items unusable without disappearing

### ISSUE THREAD

**Issue by tunbridgep** [diasurgical/devilutionX#6226]
In Diablo 1, when an item reaches 0 durability it disappears.

From Diablo 2 onwards, items would instead "break" and become unusable, but could be repaired.

Could this be added as a gameplay option?

EDIT: This didn't come up after searching "durability" or "broken", but it was quite far down the list when searching for "repair", so I guess this is a duplicate. Closing

**Comment by julealgon** [comment]
Use proper syntax when referring to other issues so Github adds the proper link between them:
- #3931
