### ISSUE TITLE
Mac: Requires macOS 12+

### ISSUE THREAD

**Issue by moreira** [diasurgical/devilutionX#6230]
### Operating System

Mac

### DevilutionX version

1.5.0 (latest release)

### Describe

Version 1.4.1 was working fine, but version 1.5.0 gave me a crash:

```
dyld: Library not loaded: @executable_path/../Frameworks/libsodium.23.dylib
  Referenced from: /Applications/_DevilutionX.app/Contents/MacOS/./devilutionx
  Reason: no suitable image found.  Did find:
	/Applications/_DevilutionX.app/Contents/MacOS/./../Frameworks/libsodium.23.dylib: cannot load 'libsodium.23.dylib' (load command 0x80000034 is unknown)
	/Applications/_DevilutionX.app/Contents/MacOS/../Frameworks/libsodium.23.dylib: cannot load 'libsodium.23.dylib' (load command 0x80000034 is unknown)
[1]    33822 abort      ./devilutionx
```

### To Reproduce

Just try to start the app

### Additional context

I'm using a 2017 macbook with intel processor

**Comment by AJenbo** [comment]
could you please let us know what version of macOS you are running?

**Comment by moreira** [comment]
Sure, Mojave - 10.14.6

**Comment by AJenbo** [comment]
Hm the latest release was build on 14.2 which should produce code compatible with macOS 10.13+. Which also appears to be the case for the libsodium we use from brew.

**Comment by AJenbo** [comment]
Looking a bit closer at it it appears that the libsodium that brew delivers for macOS 14 specifically is only compatible going back to macOS 12+

**Comment by moreira** [comment]
That's a bummer!

Is it possible to point directly to a version compatible with older macOS's?

**Comment by AJenbo** [comment]
For now I would have to point you to the https://github.com/diasurgical/devilutionX/blob/master/docs/building.md#building-from-source

Mac is a bit difficult to support across a wide range of versions as they have a tendency to kill backwards comparability aggressively.
On the bright side it's easy to build the project.

**Comment by AJenbo** [comment]
Here is a fresh build from my dying macOS 10.13.6 system.

[devilutionx-macOS-x86_64.dmg.zip](https://github.com/diasurgical/devilutionX/files/11776783/devilutionx-macOS-x86_64.dmg.zip)

Note this is 1.5.1-dev and not 1.5.0 so it's not able to join most multiplayer games, but let me know how it works for you.

**Comment by moreira** [comment]
It worked! Thanks for the effort!

**Comment by AJenbo** [comment]
We still need an official release before this is considered solved

**Comment by AJenbo** [comment]
Looks like the libs provided by brew are all targeting macOS 12.0 and there is no way to specify that you want older versions, other then actually running an older version.

Another issue though is the Discord integration which is build for macOS 11.0, so unless we can get an older version of that we have to either accept targeting 11+ or disable it.

I tried building the libs from src but unfortunately that just meant that they where being build for the underlying OS meaning 12.6+ which is even worse then what Homebrew provides. So some additional work would be needed for that solution to work.

All in all I feel like all of this simply forces me to manually build on an old mac for as long as possible.

**Comment by moreira** [comment]
Is it possible to embed the 10.13+ lib or download directly from the source during build?

**Comment by AJenbo** [comment]
When I tried building form source they where targeting 12.6+ sine that was the version of the system the build runs on.

**Comment by moreira** [comment]
I was thinking more like embedding the compiled lib instead of the source.

But of course that would increase the size of the repository.

But an alternative is to download the compiled lib from a different source, instead of homebrew.

**Comment by AJenbo** [comment]
Vcpkg is only used on msvc targets so I don't have any experience with it. I don't even think it delivers bineries so in that regard I don't think it will be an improvement over what we get using cmake.

**Comment by AJenbo** [comment]
No it's not necessary at all. What I said was that our CMake setup is already able to fetch and build the dependencies form source, so it sound like there wouldn't be any benefit to using vcpkg if it's just going to do the same thing. Then it's just adding the complexity of installing vcpkg with out any benefits.
The issue, like I said in one of my [previous comments](https://github.com/diasurgical/devilutionX/issues/6230#issuecomment-1595808095), is that when build from source the libs target 12.6+ which is even worse then what brew provides.

It's not really making it easier or harder, but it does make it slower and gives an worse end result.

If you know how to build the libs so that they will target 10.13+ that would be very helpful.

**Comment by glebm** [comment]
Yeah, when you pass `-DDEVILUTIONX_SYSTEM_LIBSODIUM=OFF`, libsodium is built from source, the vcpkg version you install on the line before isn't used.
