### ISSUE TITLE
Manjaro: x11i not available

### ISSUE THREAD

**Issue by ryanmusante** [diasurgical/devilutionX#6243]
### Operating System

Linux x64

### DevilutionX version

1.5.0 (latest release)

### Describe

~ > devilutionx                                                    
Failing with error on launch, is there a configuration file required or something?
```
ERROR: SDL Error
x11i not available

The error occurred at: Source/utils/display.cpp line 311
```
I have what should be all required libraries installed.

### To Reproduce

1. Launch from .desktop file or from commandline
2. See error above

### Expected Behavior

To launch

### Additional context

~/.local/share/diasurgical/devilution > neofetch --ascii_distro manjaro_small
```
||||||||| ||||   ryan@xmg 
||||||||| ||||   -------- 
||||      ||||   OS: Manjaro Linux x86_64 
|||| |||| ||||   Host: NB01 PC5x_7xHP_HR_HS 
|||| |||| ||||   Kernel: 6.3.8-273-tkg-cfs 
|||| |||| ||||   Uptime: 24 mins 
|||| |||| ||||   Packages: 1444 (pacman) 
                 Shell: zsh 5.9 
                 Resolution: 3840x2160 
                 DE: GNOME 44.2 
                 WM: Mutter 
                 WM Theme: default-pure 
                 Theme: Adw-dark [GTK2/3] 
                 Icons: Papirus-Dark [GTK2/3] 
                 Terminal: kitty 
                 Terminal Font: Hack Regular 12.0 
                 CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
                 GPU: NVIDIA GeForce RTX 3080 Mobile / Max-Q 8GB/16GB 
                 Memory: 2537MiB / 64083MiB 
```

**Comment by AJenbo** [comment]
You just need sdl2, maybe sdl2_image.

What display manager is being used? X11i isn't showing up in a quick Google. But it sounds like SDL2 is unable to acquire a graphical context from your system. How are you accessing the system?

**Comment by ryanmusante** [comment]
~/.local/share/diasurgical/devilution > pacman -Qd | grep sdl2                     
```
lib32-sdl2 2.26.5-1
sdl2 2.26.5-2
sdl2_image 2.6.3-1
sdl2_mixer 2.6.3-1
sdl2_net 1:2.2.0-1
```
I have those installed. I'm running xorg + Gnome + GDM. I have the data file inside of the correct directory.
~/.local/share/diasurgical/devilution > ll
```
drwx------ ryan ryan 4.0 KB Sat Jun 17 21:23:42 2023 🗁 .
drwx------ ryan ryan 4.0 KB Sat Jun 17 20:45:32 2023 🗁 ..
.rw-r--r-- ryan ryan 494 MB Sat Jun 17 21:23:42 2023 🗋 DIABDAT.MPQ
```

**Comment by AJenbo** [comment]
yes, my point was that you had way more then needed, you only need the one or two, not all 5.

The error you are getting is when the application is trying to start a window, which is before it tries to access the data. I'm not really sure what to say since it's getting a message from your OS saying that it's not available.

You could try the appimage instead and see if it's embedded SDL2 works better on your system (you would think the one provided by the system would work the best).

You could also try installing it via AUR

**Comment by StephenCWills** [comment]
The `x11i` in that error message is the name of the driver SDL is trying to load.
https://github.com/libsdl-org/SDL/blob/f168f9c81326ad374aade49d1dc46f245b20d07a/src/video/SDL_video.c#L506

SDL gets it from the `SDL_VIDEO_DRIVER` environment variable.

**Comment by ryanmusante** [comment]
I got devx from AUR

~/.local/share/diasurgical/devilution > yay devilutionx                                                                                                                                                                                    ```
INT
7 aur/devilutionx-graphics-tools-git 1-1 (+0 0.00) 	DevilutionX graphics format conversion tools (git version)
6 aur/devilutionx-mpq-tools-git 1-1 (+0 0.00) 	DevilutionX MPQ minifier tool (git version)
5 aur/devilutionx-assets-git 1.4.0.r1542.fa0147cfa-1 (+5 0.00) 	Additional assets for DevilutionX
4 aur/devilutionx-voices 1.5.0-2 (+16 1.02) 	Additional voices for DevilutionX
3 aur/devilutionx-fonts 1.5.0-2 (+16 1.02) 	Additional fonts for DevilutionX
2 aur/devilutionx-git 1.4.0.r1542.fa0147cfa-1 (+5 0.00) 	Diablo devolved for linux (git version)
1 aur/devilutionx 1.5.0-2 (+16 1.02) (Installed)	Diablo devolved for linux (main package)
```

**Comment by AJenbo** [comment]
Maybe you typed it wrong? I can find what looks relevant if i search X11 instead of X11i:

https://github.com/ValveSoftware/Proton/issues/6376

**Comment by AJenbo** [comment]
> Oh, I can just use an environment variable?

Yeah, from the looks of it Manjaro sets it wrong for x11 based desktops.

**Comment by ryanmusante** [comment]
But what would the SDL_VIDEO_DRIVER be correctly set to?

**Comment by AJenbo** [comment]
vim strikes again

**Comment by ryanmusante** [comment]
lol, confirmed all is well, it loads now
~ > devilutionx --verbose
```
VERBOSE: Paths:
    base: /usr/bin/
    pref: /home/ryan/.local/share/diasurgical/devilution/
  config: /home/ryan/.local/share/diasurgical/devilution/
  assets: /usr/bin/assets/
VERBOSE: MPQ search paths:
     1. '/usr/bin/'
     2. '/home/ryan/.local/share/diasurgical/devilution/'
     3. '/usr/local/share/diasurgical/devilutionx/'
     4. '/usr/share/diasurgical/devilutionx/'
     5. ''
VERBOSE:   Found: devilutionx.mpq in /usr/share/diasurgical/devilutionx/
```
