### ISSUE TITLE
Add virtual gamepad also to initial menu (Android)

### ISSUE THREAD

**Issue by Zlva** [diasurgical/devilutionX#6246]
### Operating System

Android

### DevilutionX version

1.5.0 (latest release)

### Describe

Quality of life

### To Reproduce

Just play android version

**Comment by AJenbo** [comment]
The menu may need some refactoring to work better with touch. I don't think having the dpad in the menu would be a good solution as it would probably overlap things and not always be intuitive.
In any case this issue is very sparse on details, but thank you for the suggestion.
