### ISSUE TITLE
Can one use the save file from standard hellfire?

### ISSUE THREAD

**Issue by Rheoscope** [diasurgical/devilutionX#6250]
I copied the hellfire hsv file into devilutionx directory, and it does not work. By the way, does the duplicating item trick still work?

**Comment by AJenbo** [comment]
Please do not use issue report for support. Either use Discussions or the chat for that.

Yes it's compatible with standard save games. See here for where to put save files: https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide

No that bug was fixed long ago.
