### ISSUE TITLE
Save process is sometimes to fast to see the message

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6259]
I have to press several times to be able to quicksave.
Fast loading works fine.
To check the keyboard I swapped F2 and F3 and the keyboard shouldn't be the cause.
Can someone confirm the issue?

**Comment by Chance4us** [comment]
Very important note. The issue only occurs when VSYNC is turned off.

**Comment by Chance4us** [comment]
One more important note.
The save works fine, but the message that says "Saving..." skips or appears so briefly that it doesn't appear.

**Comment by AJenbo** [comment]
I guess we have optimized the save process to much. Time to add an indicator

**Comment by Layarion** [comment]
i came on to suggest that the indicator be forced to last at least 1 second, because i too with no vsync on PC haz the same issue.

**Comment by Layarion** [comment]
> I guess we have optimized the save process to much. Time to add an indicator

i came on to suggest that the indicator be forced to last at least 1 second, because i too with no vsync on PC haz the same issue.

**Comment by julealgon** [comment]
@Chance4us , should this issue be renamed after your last comment? If the functionality is working, but the label is the problem, current title is a bit misleading.
