### ISSUE TITLE
Is patch_rt.mpq required anymore?

### ISSUE THREAD

**Issue by FyiurAmron** [diasurgical/devilutionX#6260]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

As in title - I find conflicting information on the internet, and the README.txt doesn't mention it at all. I stumbled upon info that it might be needed for localized versions etc., but still it's completely unobvious for me whether and when it should be used (or never at all?)

### To Reproduce

1. Try to install DevilutionX
2. Ponder whether you should use patch_rt.mpq or not XD

**Comment by StephenCWills** [comment]
No, there isn't any code in DevilutionX that loads `patch_rt.mpq`. Looks like it had some additional and/or modified assets used for battle.net, so it might be necessary if you want to play the original game on bnet.

**Comment by AJenbo** [comment]
Some patches used it to load additional translation assets but DevilutionX dosrnt. Instead it has an mpq per language (pl.mpq)

**Comment by FyiurAmron** [comment]
@AJenbo TBH I only asked about it because it's the "official" MPQ installed as part of the normal (i.e. both GOG and vanilla) "official" instalation, and I guess it might not be that obvious whether is should actually be copied or not (even if it's not mentioned in the README, one might assume it's optional or might do something etc., since many places on the net mention it).

FWIW, I'd say that explicitly stating that it's not needed in the README would make it clearer for people in the future (since it's the only "official" MPQ that's not needed for DevilutionX, IIUC), but obviously that's your call, guys.

**Comment by AJenbo** [comment]
Including it has no negative effect either. GOG also included a mpq file that they didn't need (a left over from a failed update when they where patching it).
Older versions of Diablo didn't have a patch_rt.mpq file.
The shareware has patch_sh.mpq, some mods make use of the 2 mpq files that it tries to load but where never shipped for loading there additional content.
The Mac version of Diablo also has an additional mpq file with some unknown content.
There are lots of other files that are needed for the original and GOG release that we do not use. To avoid having a long list of thing we don't use we have instead opted to specifically list what we do use and why.
If you can point to the places where you see it mention I can maybe better help clear up the confusion.

**Comment by FyiurAmron** [comment]
@AJenbo I get your point. That's why I put the "official" in scare quotes, I am aware there are other official MPQs that can be found in the wild, it's just that, obviously, a common install-and-patch run of full PC vanilla D1 (i.e. statistically the most common setup for it) will give you only those 2 MPQs.

I'm thinking, to not spam the readme, maybe just add an explicit "only" to the phrase, like "Copy _only_ DIABDAT.MPQ (no other MPQ are needed) from the CD or GOG-installation"?

As to the places, e.g.:
https://github.com/diasurgical/devilutionX/issues/466
https://www.gog.com/forum/diablo/is_this_some_joke_or_what ("DIABDAT.MPQ is definitely required, but the others may or may not be. (follow up:) And patch_rt.mpq [because] devilutionX only requires the mpq files")
https://www.reddit.com/r/RG350/comments/krwncx/devilutionx_freezing_around_level_20/ ("make sure you use the GOG diabdat.mpq, and newest patch_rt.mpq")
https://artishq.wordpress.com/2020/03/09/devilutionx-diablo-engine/ ("Polish version already works through modified patch_rt.mpq.")

etc. I'm not making it up, there actually _is_ some confusion about it. I honestly think that over-specifying this in the README (like above) might make it more obvious to people. I am aware it's obvious to you guys,

**Comment by StephenCWills** [comment]
IMO, it doesn't really matter if it's not obvious. Whether the user chooses to place `patch_rt.mpq` in the DevilutionX folder or not, the game will still work. We've just now explicitly confirmed that you don't need it which should hopefully help anyone who's digging that deep for clarification. So let's keep the instructions simple and to the point without meandering to mention anything we don't need.

**Comment by AJenbo** [comment]
> I'm not making it up, there actually is some confusion about it

Oh I don't doubt that at all, sorry if it came of as such. There are also people that think we only require the mpq to verify ownership as a form of CD check. And I think we could probably do a better job of explaining that there is no need to copy the files if you have it installed via GOG .

**Comment by AJenbo** [comment]
The first and the last of the links are talking about unofficial translations that work via a modefied patch_rt.mpq, so they aren't really related to the issue of weather the official one is used or not.

The one who was having issues with the game locking up was because of a damaged diabdat.mpq, I guess when copying it the second time they went all in just to be sure and didn't try testing if it would still work without it.

I guess the one on GOG from 2019 is so long ago that the documentation might not have not have been as explicit as it is now as that was a beta prior to the 1.0.0 release, and maybe not worth replying to at this point
