### ISSUE TITLE
Unable to create Hell difficulty game session with character under level 30

### ISSUE THREAD

**Issue by VonKossa** [diasurgical/devilutionX#627]
Hi!

When i was young and played Diablo i was able to create a Hell difficulty multiplayer game with a under level 30 character. Well... This seems to be impossible now. You are now prompted with a message telling you that this is too hard for you.
What happened with freedom of choice and keeping with the original?

Actually this was a well developed "sport" in the old days, starting a new game in Hell difficulty with a level 1 character.
Wondering if this is a permanent feature?

Thanks in advance

**Comment by AJenbo** [comment]
What version are you referring to? Was it single or multiplayer. We haven't added this it's from the original version 1.09. You have all the freedom to change this.

**Comment by qndel** [comment]
Yet another person that doesn't remember how it really was ... You could change difficulty in single player by playing a multiplayer game on that difficulty, it's a well known bug, anything else was hacking.

**Comment by AJenbo** [comment]
https://diablo2.diablowiki.net/Diablo_I

Other options are playing Hellfire, or joining someone who had level 30 via modem...

**Comment by VonKossa** [comment]
oh sorry, actually multiplayer.

________________________________

**Comment by VonKossa** [comment]
Sorry about that, i have read the wiki link and i am very confused about this.
I never had Hellfire and as far as i remember i never used any game mod.
And i know i created Hell difficulty multiplayer games....

Well apparently i am getting old. This is disturbing....

________________________________
