### ISSUE TITLE
Crash when entering town portal

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#6277]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

The app crashes when entering the town portal in the save file posted here https://github.com/diasurgical/devilutionX/issues/4293

Could be a fixable problem, or could just be an acceptable byproduct from improvements. The savefile works in 1.4.1 and the portal leads to the nest. I'll guess that the lighting changes to the nest have something to do with this and the game is trying to restore data that is no longer where it expects... or something.

### To Reproduce

load save, go through portal

**Comment by Chance4us** [comment]
On linux no crash but the hero is not visible until he starts moving.
![invisible](https://github.com/diasurgical/devilutionX/assets/45902449/334b2ffd-e5c7-4d85-991c-d2dd92eee081)

**Comment by kphoenix137** [comment]
> On linux no crash but the hero is not visible until he starts moving.
> ![invisible](https://github.com/diasurgical/devilutionX/assets/45902449/334b2ffd-e5c7-4d85-991c-d2dd92eee081)
> 

Why does it say level 20

**Comment by Chance4us** [comment]
It was displayed like this :penguin:

**Comment by AJenbo** [comment]
Level 20 is the nest. It's somehow not detecting that the level should remapped as a nest type and is using the cave theme instead.

**Comment by FitzRoyX** [comment]
> Level 20 is the nest. It's somehow not detecting that the level should remapped as a nest type and is using the cave theme instead.
> 
> @FitzRoyX was this save created with some early 1.5.0 beta?

You'll have to ask glebm, it's his savegame posted on April 6, 2022. That would be some version right before 1.4.0 was released.

**Comment by FitzRoyX** [comment]
k thx for checking guys. I setup vanilla hellfire today and can confirm that the tp works and goes to the nest.
