### ISSUE TITLE
PS Vita version freezes shortly after minimize or system sleep

### ISSUE THREAD

**Issue by Jvk1166z** [diasurgical/devilutionX#6281]
### Operating System

PlayStation Vita

### DevilutionX version

1.5.0 (latest release)

### Describe

Hey, this port is awesome! However I have one minor issue with it that I haven't been able to find an answer too. When you either go back to the system menu or sleep the system, the game freezes and must be restarted in order to play again.

It's not a huge issue as you can just save and reload when you want to play again, but is inconvenient nonetheless. I'm happy to provide any files needed, just let me know what you want and where to get it. I have a feeling you may already know about this bug considering it's so easy to reproduce, but I thought I'd report it as I didn't see anyone else with it when I searched the issues.

### To Reproduce

1. Play the game
2. Minimize the game or sleep the system.

### Expected Behavior

Not freezing.

**Comment by AJenbo** [comment]
@isage ?

**Comment by isage** [comment]
Install repatch or fd_fix plugin

**Comment by isage** [comment]
No official way to automagically do that, so you'll have to do it for every FILE/fstream on read failure (which would require tracking filenames for them).

**Comment by Jvk1166z** [comment]
Thanks for the help!
