### ISSUE TITLE
Adding external (higher quality) soundtrack support

### ISSUE THREAD

**Issue by voivodpl** [diasurgical/devilutionX#6290]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

So far I saw 192kb/s 44100khz mp3 Diablo in mp3 format. There might be even better. Make support for external in mp3 + flac please :)

### To Reproduce

Go to options, choose external soundtrack, place the files in reasonable folder within diablo 1 dir. Done.

**Comment by DakkJaniels** [comment]
Can't you just convert to .wav and override existing assets?

**Comment by FitzRoyX** [comment]
I'm not aware of an actual 44100khz soundtrack existing that isn't just an upscale of the 22050 mpq files.

**Comment by AJenbo** [comment]
We already support both .wav and .mp3
