### ISSUE TITLE
Darker spell casting animation

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#6294]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

Healing animation looks slightly darker in town for a warrior wearing a one handed weapon in plate armor. Probably looks fine in the dungeons since the lightning there is darker.  Video attached in the PR here: https://github.com/diasurgical/devilutionX/pull/1980#issuecomment-1615019631

https://user-images.githubusercontent.com/5624187/250166070-bbb5d831-7f77-4ebf-9cf8-8577fdd8e76c.mp4

### To Reproduce

.

### Expected Behavior

.

### Additional context

.

**Comment by AJenbo** [comment]
Compared to what? Light armer, two handed weapons. I see in some animations the particles are blue.

P.s. you don't need to write `.` in the optional files, and would be nice to have a way to replicate this cause I don't undertand what I'm supposed to compare to :(

**Comment by qndel** [comment]
![image](https://github.com/diasurgical/devilutionX/assets/14297035/3cc80c11-ba76-4d36-807e-10ea080298e0)
should be fixable, it's dark in town because no light is applied!

**Comment by qndel** [comment]
nvm, it's the unarmed sprite that's broken, if you unequip weapon, you get the same dark sprite in the dungeon ... duh

**Comment by galaxyhaxz** [comment]
The Rogue casting lightning with light armor+axe is darker too. In general the player sprites are quite buggy, some pop out of place, some have wrong colors, some have holes in them. They all need to be redone using 3d models.
