### ISSUE TITLE
Ogdens speech [Leoric's tomb]

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6295]
Ogden still speaks the following two speeches, even though the Leoric's quest has already been completed.
When the hero was already in the crypt and Ogden was clicked, the speeches mentioned above came up.
I guess that these are obsolete for the already completed quest.

![speech1](https://github.com/diasurgical/devilutionX/assets/45902449/36b5bfaf-6452-4028-b0a9-362771910368)

![speech2](https://github.com/diasurgical/devilutionX/assets/45902449/61cccf27-56d9-43fd-9014-e8372dad7a67)

**Comment by FitzRoyX** [comment]
I don't think this is a bug. All quests are triggered by dialog, either a person or a tome. This is so that when you go into the quest log, you can click on the quest to hear the initial dialog again. That's just how D1 works. D2 doesn't have the same type of quest log.

**Comment by AJenbo** [comment]
### Not from dialog
- Diablo is activated by killing Lazarus
- Defiler is activated by entering The Nest
- Grave is activated by finding Cathedral Map

### only if books are dialogs
- Halls of the Blind
- Valor
- Warlord of Blood
- The Chamber of Bone
- Na-Krul

### optionally from dialog or
- Anvil of Fury can be activated by finding it
- The Magic Rock can be activated by finding it
- The Curse of King Leoric can be activated going to his tomb
- Poisoned Water Supply can be activated going to The Passage

**Comment by FitzRoyX** [comment]
Not sure what you mean by activated, but quest log entries can be clicked to replay dialog, and vanilla does not create quest log entries for conversations you've never had. For example:

1. Pick up the magic rock before talking to Griswold. The quest log stays blank and does not populate with a clickable dialog you've never heard.
2. Talk to Griswold with rock, hear dialog 1 (quest begins, log entry that can replay dialog 1 appears).
3. Talk to Griswold again to hear dialog 2 (quest ends, log entry goes golden)

Same thing happens with Leo. Poison water is a bit bugged. If you clear the water before talking to Pepin, Pepin will skip dialog 1.

**Comment by kphoenix137** [comment]
Is anyone able to reproduce this? I just attempted to, and if I kill Leoric before talking to Ogden, Ogden no longer has any dialogue about Leoric whatsoever.

**Comment by julealgon** [comment]
Wondering if we could rename this issue to be a bit more specific. I had no idea what it was about before opening it (usually one would want to avoid that).

**Comment by AJenbo** [comment]
Come up with a better name. Now we are just pinging people who will open it to see others complain that they opened it for no reason ... For no reason

**Comment by kphoenix137** [comment]
Old issue with no update containing more details, and nobody has mentioned that they can understand the issue or reproduce. Going to close unless somebody has more useful information.
