### ISSUE TITLE
enchancement proposal - waypoints

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6296]
I suggest adding waypoints to the game that you can set by yourself and add a description to.

**Comment by DakkJaniels** [comment]
What does this mean? Permanent Town Portals? I don't understand the proposal from what you've described. There already are waypoints (in multiplayer).

**Comment by Chance4us** [comment]
I mean that you can give a coordinate in a certain level and give it a description.
Ideally, it would be good to see this coordinate on the automap as soon as the level is entered.

**Comment by DakkJaniels** [comment]
What is the purpose of this? When would one want to use it?

**Comment by Chance4us** [comment]
As a reminder, for example to mark shrines that you want to use later.
Or you need a position for a quest, for testing purposes.
Or you have hidden something and want to find it again.

**Comment by kphoenix137** [comment]
How would this work exactly? I understand the premise but not the execution

**Comment by AJenbo** [comment]
Can reopen if we get a better detailed feature. It's also a bit in risk of being out of scope though.

**Comment by yuripourre** [comment]
> As a reminder, for example to mark shrines that you want to use later. Or you need a position for a quest, for testing purposes.

If I may add, both quest "triggers" and shrines could be shown on the map. This would be a really useful QoL and mimics what Diablo 2 has. I think the need for waypoints is less necessary with those icons.

**Comment by AJenbo** [comment]
that's a fair suggestion but maybe a different one from this one.

**Comment by julealgon** [comment]
The word "waypoint" is extremely misleading here. My understanding is that @Chance4us want's to be able to place custom "markers" in the automap, right?

That would be potentially really interesting... but it does conflict a bit with #6515 in that this might just become obsolete once that is implemented.

**Comment by AJenbo** [comment]
The correct term is point of interest

**Comment by kphoenix137** [comment]
Perhaps I should also create markers for shrines that have been discovered. I think that would be useful
