### ISSUE TITLE
All 1.4.0 HF saves crashing in 1.5.0

### ISSUE THREAD

**Issue by jkh0208** [diasurgical/devilutionX#6299]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

All of my 1.4.0 Hellfire saves crash when loading them in 1.5.0.  They load fine in 1.4.0, and my 1.5.0 saves work properly in 1.5.0.  This issue does not affect my Diablo (non-HF) saves.

### To Reproduce

Create a HF character in DevilutionX 1.4.0, and save.  Open DevilutionX 1.5.0 and load the save file created in 1.4.0.

### Additional context
Latest crash report:

Version=1
EventType=APPCRASH
EventTime=133326856844814512
ReportType=2
Consent=1
UploadTime=133326856847770307
ReportStatus=268435456
ReportIdentifier=c32e2bee-69f2-459b-a452-4bbfbe38c43f
IntegratorReportIdentifier=44b572ed-20af-44d7-b342-5d68e1506f2f
Wow64Host=34404
NsAppName=devilutionx.exe
AppSessionGuid=000022e4-0001-002a-bfd2-15910eacd901
TargetAppId=W:00061696f8bec47d1b23a00f38d3528eb2a40000ffff!0000d432ca6a80ed95ece8cc158a1ae8f24806aedff7!devilutionx.exe
TargetAppVer=1970//01//01:00:00:00!57ddc7!devilutionx.exe
BootId=4294967295
TargetAsId=925
UserImpactVector=271594288
IsFatal=1
EtwNonCollectReason=4
Response.BucketId=c6ce62f0b7e020b2d0cc4eaad43b8cc0
Response.BucketTable=4
Response.LegacyBucketId=1210428895467900096
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=devilutionx.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=00000000
Sig[3].Name=Fault Module Name
Sig[3].Value=devilutionx.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=00000000
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000153276
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.22621.2.0.0.768.101
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=f1a0
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=f1a041c4779f2e643ca93ff5284ed93d
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=3f80
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=3f80704d16581b6bf397031dcc141148
UI[2]=C:\Games\Diablo\devilutionx\devilutionx.exe
LoadedModule[0]=C:\Games\Diablo\devilutionx\devilutionx.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Program Files\Avast Software\Avast\aswhook.dll
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[6]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[7]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\System32\sechost.dll
LoadedModule[9]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[10]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[11]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[13]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[14]=C:\WINDOWS\System32\USER32.dll
LoadedModule[15]=C:\WINDOWS\System32\win32u.dll
LoadedModule[16]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[17]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[18]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[19]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\WSOCK32.dll
LoadedModule[21]=C:\Games\Diablo\devilutionx\zlib1.dll
LoadedModule[22]=C:\Games\Diablo\devilutionx\discord_game_sdk.dll
LoadedModule[23]=C:\WINDOWS\System32\ole32.dll
LoadedModule[24]=C:\WINDOWS\System32\combase.dll
LoadedModule[25]=C:\WINDOWS\SYSTEM32\ktmw32.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[27]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[28]=C:\Games\Diablo\devilutionx\SDL2.dll
LoadedModule[29]=C:\WINDOWS\System32\IMM32.dll
LoadedModule[30]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[31]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[32]=C:\WINDOWS\SYSTEM32\MSWSOCK.DLL
LoadedModule[33]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\cfgmgr32.DLL
LoadedModule[36]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[38]=C:\WINDOWS\System32\SHCORE.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[40]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\mscms.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\icm32.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[44]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[45]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[46]=C:\WINDOWS\System32\MMDevApi.dll
LoadedModule[47]=C:\WINDOWS\System32\DEVOBJ.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\avrt.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\hid.dll
LoadedModule[50]=C:\WINDOWS\System32\WINTRUST.dll
LoadedModule[51]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\MSASN1.dll
LoadedModule[53]=C:\Windows\System32\dinput8.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\inputhost.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\CoreMessaging.dll
LoadedModule[56]=C:\Windows\System32\Windows.Gaming.Input.dll
LoadedModule[57]=C:\Windows\System32\twinapi.appcore.dll
LoadedModule[58]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\textinputframework.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[62]=C:\WINDOWS\SYSTEM32\POWRPROF.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\UMPDC.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
LoadedModule[65]=C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[67]=C:\WINDOWS\SYSTEM32\D3D9.DLL
LoadedModule[68]=C:\WINDOWS\System32\DriverStore\FileRepository\u0392410.inf_amd64_db8e7eec2f31b31d\B392251\aticfx64.dll
LoadedModule[69]=C:\WINDOWS\System32\DriverStore\FileRepository\u0392410.inf_amd64_db8e7eec2f31b31d\B392251\atiu9p64.dll
LoadedModule[70]=C:\WINDOWS\System32\DriverStore\FileRepository\u0392410.inf_amd64_db8e7eec2f31b31d\B392251\atiumd64.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\dbghelp.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\dbgcore.DLL
LoadedModule[73]=C:\WINDOWS\System32\DriverStore\FileRepository\u0392410.inf_amd64_db8e7eec2f31b31d\B392251\atiumd6a.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\amdihk64.dll
LoadedModule[75]=C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22621
OsInfo[3].Key=ubr
OsInfo[3].Value=1848
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=101
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222208614
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22621.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=28552
OsInfo[19].Key=svolsz
OsInfo[19].Value=930
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=220506
OsInfo[22].Key=bldtm
OsInfo[22].Value=1250
OsInfo[23].Key=bldbrch
OsInfo[23].Value=ni_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22621.1848.amd64fre.ni_release.220506-1250
OsInfo[30].Key=buildflightid
OsInfo[30].Value=2326143B-AB3D-484A-90AA-3BC64E1A7C0C.1
OsInfo[31].Key=edition
OsInfo[31].Value=Core
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=RS:15232,ME:25762F0,ME:27B9BC4,FX:12AAB778
OsInfo[34].Key=fconid
OsInfo[34].Value=18299130,0,2,0;19194231,0,2,0;19194292,0,2,0;19194297,0,2,0;19195481,0,2,0;19638787,0,2,1;23531064,2,2,1;23562335,2,2,1;23563673,2,2,1;25704915,1,2,1;27075521,1,2,1;32862274,0,2,0;35681102,0,1,0;36803287,0,2,1;36803295,0,2,0;36803303,0,2,1;37482934,1,2,1;38859191,0,2,1;39263329,1,2,0;39281392,0,2,1;40025975,0,1,0;40616880,0,1,1;40733296,0,2,1;40883769,0,1,0;40981503,0,1,0;41137130,0,1,0;41313221,0,2,1;41342175,0,1,1;41655236,0,2,1;41772259,0,2,1;42052423,0,2,0;42092123,0,2,1;42235377,0,2,1;42921948,0,1,1;42922989,0,2,1;43572857,0,2,1;44521793,0,1,0
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
OsInfo[39].Key=featureupdatependingreboot
OsInfo[39].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=devilutionx.exe
AppPath=C:\Games\Diablo\devilutionx\devilutionx.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=B3E570A630BA994C7A85E8315B2EBC05
MetadataHash=-125939181

**Comment by AJenbo** [comment]
1. please provide correct versions, there is no 1.14 or 1.15.
2. Please share the offending save games.

**Comment by jkh0208** [comment]
> 1. please provide correct versions, there is no 1.14 or 1.15.
> 2. Please share the offending save games.

My apologies.  I made the corrections.

**Comment by AJenbo** [comment]
Can you replicate this using 1.4.1 instead of 1.4.0?

I still don't see any attached save games?

**Comment by StephenCWills** [comment]
I was unable to reproduce, following the instructions provided.

@jkh0208 If this is still an issue for you, please provide your corrupted save files so we can analyze them.
