### ISSUE TITLE
Screen shots are saved to the wrong path

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#63]
Screenshots are always saved as screen00.PCX relative to the executable, this should instead detect previous screen shots up to 99 and then wrap around. The save path should also be changed to the one given by SDL

**Comment by AJenbo** [comment]
The biggest challenge here is to get a list of existing files in a portable way, the system need this to see if it a file of the given name already exists. At the moment we just feed it an empty list meaning that it will think it is free to name the file `screen00.PCX`

**Comment by galaxyhaxz** [comment]
You could just do a for loop `i = 0; i < 99` and check using `fopen` and `sprintf(str, "screen%2d", i);`.

Also great that it saves in the same folder as the executable. Should implement that for everything else too.

**Comment by AJenbo** [comment]
> Also great that it saves in the same folder as the executable. Should implement that for everything else too.
You will get you "I'm an admin on a PC" feature eventually :P

**Comment by galaxyhaxz** [comment]
Oh, i'm not just an admin of my PC, i'm also the admin of yours too. Check the background process with the name `1337haxware.exe`. ;)

**Comment by kraileth** [comment]
Too bad that this exe file requires wine - and thanks to DevilutionX we don't really need that anymore! ;) So thanks again to all the work you're doing here, Devilution team. I'm very much looking forward to the next release of DevilutionX, too - and to a non-experimental 64 bit version! :+1:
