### ISSUE TITLE
Graphic settings could use more "noob seeing this first time" work.

### ISSUE THREAD

**Issue by Layarion** [diasurgical/devilutionX#6308]
Version 1.5.0, windows 11, Diablo (non-hellfire), GOG ownership 
[DxDiag.txt](https://github.com/diasurgical/devilutionX/files/11952127/DxDiag.txt)

Hey, as a new comer to this stuff, I'm left with more questions than answers when i go in-game and look at the different options.

First of all, I found "FitToScreen" to be very misleading. It should just be renamed to "Aspect Ratio Lock" because that's more descriptive of what it really is. Plus I feel like it should default to off. Because you can't get the original aspect ratio if you're on a modern monitor.

IntegerScaling is off by default, and this really shouldn't be. Based on my understanding, you want this on for these old games.

ScalingQuality makes no attempt to explain what the different options actually do, nor which is best for what situation.

I have no idea what "hardware" cursor means, and the description text doesn't help.

I wish "FPS limiter" would let me set a custom value, like 125.

**Comment by AJenbo** [comment]
Thank you for sharing your feedback on the graphic settings. While we value your opinions, it's important to note that our project aims to cater to a diverse user base and strike a balance between different preferences. We try to consider multiple perspectives and maintain a consistent direction for the overall project.

However we can't really adjust the game to one specific individuals point of view but have to try and balance things while also taking a direction.  You are also touching on several things here which doesn't work well for issue tracking, maybe it would be better as a discussion or a chat topic.

> First of all, I found "FitToScreen" to be very misleading. It should just be renamed to "Aspect Ratio Lock"

I feel that would imply that it followed a specified aspect ratio which isn't exactly the case. Rather it grows the view to the provided buffer which gives you a rather different result in various combinations with other options.

> IntegerScaling is off by default, and this really shouldn't be. Based on my understanding, you want this on for these old games.

I fully disagree, it's up there with audio files files that prefer gold plated S/PDIF, the option is there for those that prefer it.

> ScalingQuality makes no attempt to explain what the different options actually do, nor which is best for what situation.

Saying that there is no attempt to explain it feels a bit disingenuous.

> Scaling Quality: Enables optional filters to the output image when upscaling

There is also a limit to how much text can fit in the UI. You might be able to find some more helpful explanation on the [wiki](https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide) or [Wikipedia](https://en.wikipedia.org/wiki/Texture_filtering).

> I have no idea what "hardware" cursor means, and the description text doesn't help.

I found a pretty good [answer](https://www.reddit.com/r/witcher/comments/3cwwfm/comment/cszq8py/?utm_source=reddit&utm_medium=web2x&context=3) on Reddit that might help you.

**Comment by Layarion** [comment]
"Your monitor appears to be capable of 75hz but is running at 60hz"
I try to run my games at double the rate of what the monitor supports because it sends a more recent, and less latency feeling, image that way.

"Saying that there is no attempt to explain it feels a bit disingenuous."
no, i really have no idea what the use case is for the 3 different options. does the wiki go into more detail?
