### ISSUE TITLE
Creating a Public game, but selecting Cancel on game speed changes to Passworded game

### ISSUE THREAD

**Issue by IAmTrial** [diasurgical/devilutionX#6319]
### Operating System

Linux x64

### DevilutionX version

1.5.0 (latest release)

### Describe

The bug affects multi player, during creation of public Zerotier and Client-Server (TCP) games. When creating a public game, if Cancel is selected during the Game Speed selection, then the Difficulty and Game Speed are selected, then the game will request for a password for creation, as if a passworded game were selected.

### To Reproduce

1. Start at the Main Menu.
2. Select Multi Player.
3. Select either Zerotier or Client-Server (TCP).
4. Select any hero.
5. Select Create Public Game.
6. Select any difficulty.
7. Cancel out of Game Speed selection.
8. Select any difficulty again.
9. Select any Game Speed.
10. A game password will be requested, despite Create Public Game being selected. The game is effectively a passworded game.

### Expected Behavior

A public game should be created, no password requested for creation, after selecting the game speed in step 9.

**Comment by AdriaTheWitch1** [comment]
same bug if u take a dificulty but your not level required in step 6, and skip step 7
