### ISSUE TITLE
Item crtl + click put into Gillian storage if cluttered dissapairs.

### ISSUE THREAD

**Issue by AlarPa** [diasurgical/devilutionX#6321]
Operating System
Windows 11

DevilutionX version
1.5.0 (latest release)

Describe
The bug affects multi player, Having open both storage and stash. If storage is cluttered and you crtl+click item from inventory the item dissapairs.

To Reproduce

open Storage and stash.
Clutter the storage that the item cant fit.
crtl+click on stash item and it dissapairs.

**Comment by qndel** [comment]
It's in a separate tab

**Comment by AlarPa** [comment]
ill be damned. Hoarded too many items. Close thread.
