### ISSUE TITLE
[request] put vender value of item in the tool-tip.

### ISSUE THREAD

**Issue by Layarion** [diasurgical/devilutionX#6325]
When deciding if i should spend that $200 portal scroll, it would help if I could see the market value of the items i hover the mouse over. 

I'm still new to the game and don't always remember what is worth only single digits.

**Comment by Korth999** [comment]
What do you mean by "market value" for items?

You can buy items from Griswold, Wirt, Adria, and Pepin. At the prices they charge.

You can sell items to Griswold and Adria. They always pay the same price for the same item.

**Comment by Layarion** [comment]
> What do you mean by "market value" for items?
> You can sell items to Griswold and Adria. They always pay the same price for the same item.

I mean, it shows me what i would get if i sold it to them, but on the tooltip. so that i can decide if i wanna burn a scroll for it, or just leave it on the ground and press on.

**Comment by kphoenix137** [comment]
By tooltip do you mean that big black box on the bottom of the screen?

**Comment by Layarion** [comment]
> By tooltip do you mean that big black box on the bottom of the screen?

yes

**Comment by qndel** [comment]
"When deciding if i should spend that $200 portal scroll, it would help if I could see the market value of the items i hover the mouse over." - value is meaningless, you either need the item or don't
