### ISSUE TITLE
[request] option to skip sell/buy/identify confirmations

### ISSUE THREAD

**Issue by Layarion** [diasurgical/devilutionX#6328]
I seem to spend a lot of time just hitting "yes" to "are you sure?" and it would be great if this could be adjusted in the gameplay options.

**Comment by kphoenix137** [comment]
I'd suggest being able to hold Shift and click to skip the prompt

**Comment by Layarion** [comment]
that would also work

**Comment by qndel** [comment]
I don't see a point - it would only be an issue while buying a lot of items and you only buy a lot of items that have unlimited amount - like mana potions at adria, and in that case you can simply hold enter, lack of confirmation sounds like a good way to have players complaining "hurr durr I accidentally sold my items"
