### ISSUE TITLE
[request]be able to sell from inventory screen

### ISSUE THREAD

**Issue by Layarion** [diasurgical/devilutionX#6329]
I know this request is going to be a bit different from the other features of X, but hear me out.

Sometimes i have to make a trip back just because i'm full, even though i'm still fine on heath and mana. I feel like having to break out of the dungeon only for the reason of, i ran out of room, breaks the dungeon crawler vibe.

especially when it's low quality stuff. "so don't pick up the low quality stuff", well i'm still learning what is, plus i'm a bit of a hoarder.

idk how we'd go about implementing this though. Maybe right-shift clicking an item sells it?

**Comment by kphoenix137** [comment]
A GUI based shop is still up in the air. I've been advocating for it. Just have to convince everyone else it's a positive change.

**Comment by Layarion** [comment]
oh sorry, i tried searching for post like it already. i must have not googled the right word

**Comment by qndel** [comment]
Definitely mod territory.

**Comment by qndel** [comment]
> A GUI based shop is still up in the air. I've been advocating for it. Just have to convince everyone else it's a positive change.
Think you misunderstood his suggestion, he wanted to be able to sell items without having to leave the dungeon

**Comment by AJenbo** [comment]
I learned to be less of a hoarder, I think that was the right solution.

**Comment by Layarion** [comment]
> Definitely mod territory.

hey if such a mod were made, would it prevent other mods from being installed? like the ones listed on this repo.

**Comment by DakkJaniels** [comment]
Every mod is it's own binary, so yes, unless you changed the code to implement whatever it is you wanted in that mod.

**Comment by kphoenix137** [comment]
> > A GUI based shop is still up in the air. I've been advocating for it. Just have to convince everyone else it's a positive change.
> 
> Think you misunderstood his suggestion, he wanted to be able to sell items without having to leave the dungeon

Ah okay. Yeah that's definitely never going to happen

**Comment by Layarion** [comment]
well the short of it is i wouldn't, also i played a bit of Torchlight myself, though not much (yet). There's a lot in the game that you already just kinda "accept", like that you can't turn a club sideways to fit into your "pack" even though there's room.

as for the choice thing, in the early game it feels like a choice yes...but in the late game it feels like the game wasn't meant to tax your mood with trips back and forth. i get what you're saying, just make the choice to pick up only uncommon items...but after making a lot of trips back and forth through town from griswald and back to the witch, it gets tedious. the atmosphere starts to lose it's charm.

i just feel like this would enhance what i think the game wanted to focus on, which i don't think was on the selling part, but on the getting loot part.
