### ISSUE TITLE
Armor class

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6337]
I'm a little unsure whether the marked value isn't too high.
I'm wondering if anyone can verify this considering the items being carried.
![armor](https://github.com/diasurgical/devilutionX/assets/45902449/a9e95293-255c-4c61-bab2-7b882fd57016)

Savegame:
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/11999808/single_0.hsv.zip)

**Comment by qndel** [comment]
it's fine, we include "hidden" bonus from player level
