### ISSUE TITLE
Warp can still place you on a solid tile

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6338]
The starting point (red) was used by the hero to warp. After using the warp spell the level went black.
![black](https://github.com/diasurgical/devilutionX/assets/45902449/e8d366e7-2115-4fdb-a687-aa4504ee9c2f)

Savegame:
[black.zip](https://github.com/diasurgical/devilutionX/files/12003467/black.zip)

When the hero starts moving the level goes back to normal.

**Comment by qndel** [comment]
f345087e753e998dda62dd67c7346b8fc8d78c5f is the first bad commit
commit f345087e753e998dda62dd67c7346b8fc8d78c5f
Date:   Sun Apr 23 03:09:49 2023 +0200

**Comment by AJenbo** [comment]
Wait is he standing inside a wall?

**Comment by qndel** [comment]
No, he's standing on a spike that's next to stairs, you don't have to use warp, going level 15->16 normally has the same result

**Comment by qndel** [comment]
Solid tile next to stairs was fixed on master already = this bug doesn't happen anymore

**Comment by AJenbo** [comment]
Using the stairs work, but if you cast warp you are placed on top of the spite as it's not doing the check for solid tiles.

**Comment by Chance4us** [comment]
> Solid tile next to stairs was fixed on master already = this bug doesn't happen anymore
> 
> @Chance4us don't use outdated builds :)

The issue happens on current master.
