### ISSUE TITLE
Hellfire is currently unable to generate proper suffixes for Staffs

### ISSUE THREAD

**Issue by wkdgmr** [diasurgical/devilutionX#6348]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

Hellfire is currently unable to generate proper suffixes for Staffs

 I just tested current master of DevilutionX (d5b60666641c838bee8bd657e36496d46c2bdbbe) and the issue I was seeing in my mod is happening in DevilutionX.

If you try and use drop command for staffs in Hellfire, it will not produce a staff with a suffix other than a random spell charge suffix.  For instance, in Diablo, if I type in "drop King's staff" and spam that a few times, I will usually get a King's Staff of Wizardry pretty quick, typically in less than 5 - 10 tries.

I did this in Hellfire and it did not drop any suffx that was not spell charges.  I tried to type in explicitly prefix/suffix combos I know can spawn on staves, and the drop command would NOT produce them.

I shopped Adria for a bit, and she also did not once produce a suffix on a Staff that was not a random spell charge suffix

I was able to convert a diablo save where I produced a quarter staff of speed into hellfire and the staff did not get deleted or morph or anything, however the game itself refuses to produce staffs with any other suffixes 

Confirmed with multiple people in the discord that DevX current master at the hash above Hellfire is not able to produce suffixes currently that are not spell charges

### To Reproduce

Launch current DevX master select hellfire and use drop command and try and drop a staff of speed, you wont be able to do it

may need to modify https://github.com/diasurgical/devilutionX/blob/master/Source/items.cpp#L1267-L1270

**Comment by DakkJaniels** [comment]
Probably not an issue: 
![image](https://github.com/diasurgical/devilutionX/assets/6080734/97744865-f15d-4ae5-a6de-95c5c7ad7996)

**Comment by StephenCWills** [comment]
Vanilla Hellfire behavior, not a bug. Though I am curious to know whether this was something removed by Hellfire devs or added later in a patch by Diablo devs.

https://github.com/diasurgical/devilutionX/blob/d5b60666641c838bee8bd657e36496d46c2bdbbe/Source/items.cpp#L1265-L1270
