### ISSUE TITLE
Replace font `.bin` files with CLX frame widths

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#6361]
CLX natively supports frame widths so we can get rid of the `.bin` files if we encode the widths into the CLX files themselves.
This will make font files smaller and will improve rendering performance.

**Comment by AJenbo** [comment]
Might even be simpler for people to make the font files.
I would suggest that for the src we use a text where each frame width is on it's own line.

Of cause alternately people can just provide 256 variable size frames and use any clx editor they like.

**Comment by glebm** [comment]
>  I would suggest that for the src we use a text file with line breaks to separate the frame widths.
Yeah, this is a great idea
