### ISSUE TITLE
Contacting Brightlord of Beelzebub project

### ISSUE THREAD

**Issue by sheepo99** [diasurgical/devilutionX#64]
Since game enhancements are planned for a not-so-distant future, I think it would be a good idea to contact Brightlord, the author of the enhanced [Beelzebub mod](https://mod.diablo.noktis.pl/) for Diablo. Many of the features present in the mod already cover many of the desired enhancements. Moreover, Brightlord [was contacted in the past](https://freeablo.org/2016/07/17/multiplayer-and-tchernobog.html) by Wheybags, the author of Freeablo, and agreed to privately share his sources for the sake of aiding his project. It would be possible he would agree to help you guys as well.

**Comment by AJenbo** [comment]
Hi @sheepo99 

Thanks for the suggestion, but since Beelzebub is a different engine written from scratch with a different architecture - the benefits of doing so is expected to be minimal. We do also communicate a bit with the Freeablo team.
