### ISSUE TITLE
[Warp spell] Gate not processed as a level entrance

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6409]
As you can see, when you use warp spell, the hero doesn't jump to the gate entrance as it normally should, but to the entrance to level 14. The issue happens on current master.

Start position:
![gate](https://github.com/diasurgical/devilutionX/assets/45902449/88bcf71f-0ba4-40b9-a7de-606f20e1fedc)

End position:
![l14](https://github.com/diasurgical/devilutionX/assets/45902449/cd7cea1a-0470-4d31-a10d-ea2619291251)

Savegame:
[warp.zip](https://github.com/diasurgical/devilutionX/files/12161641/warp.zip)

**Comment by Chance4us** [comment]
Additional information:
In vanilla warp works as expected.

**Comment by qndel** [comment]
09bc43b0edcc05c68d9970a125289e8113d8841b is the first bad commit
commit 09bc43b0edcc05c68d9970a125289e8113d8841b
Author: obligaron <obligaron@live.com>
Date:   Tue Jul 18 22:35:51 2023 +0200

    Ensure warp and teleport target position is free

**Comment by qndel** [comment]
Okay that was quite a trip, the code is basically find except this:
```cpp
Displacement off = player.position.tile - candidate;
```

player.position.tile = WorldTilePosition = PointOf<WorldTileCoord> = PointOf<uint8_t>

```cpp
        Displacement triggerOffset = getTriggerOffset(trg);
        candidate += triggerOffset;
        Displacement off = src - candidate;
        SDL_Log("OFF: %d %d, CANDI %d %d SRC %d %d", off.deltaX, off.deltaY, candidate.x, candidate.y, src.x, src.y);
        ```
        
        
        
working ver:
INFO: OFF: -50 1, CANDI 90 46 SRC 40 47
INFO: OFF: 2 -2, CANDI 38 49 SRC 40 47

broken ver
INFO: OFF: 206 1, CANDI 90 46 SRC 40 47
INFO: OFF: 2 254, CANDI 38 49 SRC 40 47

So as you can see it wrapped around and instead of -50 we got 206, I think this shows a bigger flaw with our code - does it mean all our subtraction with WorldTilePosition is broken? 😅

**Comment by qndel** [comment]
@glebm mind giving this a look? :) It's trivial to fix just this function but I'm worried about it happening in other places

**Comment by StephenCWills** [comment]
@qndel Besides the line of code you found, there appears to be only one other call to `operator-(WorldTileCoord, OtherPointCoordT)` in a VS x64-Debug build.

https://github.com/diasurgical/devilutionX/blob/1b42a17153e943dfbf5da095e4df9a16015db5db/Source/levels/drlg_l2.cpp#L1762

In this case, the variable names of the parameters and type of the explicit use of `WorldTileDisplacement` both suggest that there should be no error like the one you found.

---

The following shows how I got the compiler to find usages of `operator-(WorldTileCoord, OtherPointCoordT)`.

```diff
diff --git a/Source/engine/point.hpp b/Source/engine/point.hpp
index ff809bbfa..6d5c84823 100644
--- a/Source/engine/point.hpp
+++ b/Source/engine/point.hpp
@@ -1,6 +1,7 @@
 #pragma once
 
 #include <cmath>
+#include <cstdint>
 #include <type_traits>
 #ifdef BUILD_TESTING
 #include <ostream>
@@ -190,6 +191,12 @@ constexpr PointOf<PointCoordT> operator+(PointOf<PointCoordT> a, Direction direc
 	return a;
 }
 
+template <typename OtherPointCoordT>
+constexpr DisplacementOf<uint8_t> operator-(PointOf<uint8_t> a, PointOf<OtherPointCoordT> b)
+{
+	static_assert(sizeof(OtherPointCoordT) == -1, "fail");
+}
+
 template <typename PointCoordT, typename OtherPointCoordT>
 constexpr DisplacementOf<PointCoordT> operator-(PointOf<PointCoordT> a, PointOf<OtherPointCoordT> b)
 {
diff --git a/Source/levels/drlg_l2.cpp b/Source/levels/drlg_l2.cpp
index 13b549003..40b9ae6a3 100644
--- a/Source/levels/drlg_l2.cpp
+++ b/Source/levels/drlg_l2.cpp
@@ -1759,7 +1759,7 @@ void CreateRoom(WorldTilePosition topLeft, WorldTilePosition bottomRight, int nR
 	if (nRoomCnt >= 80 || topLeft.x + AreaMin > bottomRight.x || topLeft.y + AreaMin > bottomRight.y)
 		return;
 
-	WorldTileDisplacement areaDisplacement = bottomRight - topLeft;
+	WorldTileDisplacement areaDisplacement = static_cast<Point>(bottomRight) - topLeft;
 	WorldTileSize area(areaDisplacement.deltaX, areaDisplacement.deltaY);
 
 	constexpr WorldTileCoord RoomMax = 10;
diff --git a/Source/missiles.cpp b/Source/missiles.cpp
index 837344c31..519462ade 100644
--- a/Source/missiles.cpp
+++ b/Source/missiles.cpp
@@ -1476,7 +1476,7 @@ void AddWarp(Missile &missile, AddMissileParameter &parameter)
 		};
 		Displacement triggerOffset = getTriggerOffset(trg);
 		candidate += triggerOffset;
-		Displacement off = player.position.tile - candidate;
+		Displacement off = static_cast<Point>(player.position.tile) - candidate;
 		int distanceSq = off.deltaY * off.deltaY + off.deltaX * off.deltaX;
 		if (distanceSq < minDistanceSq) {
 			minDistanceSq = distanceSq;
```

**Comment by glebm** [comment]
In https://github.com/diasurgical/devilutionX/pull/4881 (a draft PR) I added an assertion requiring signed types for subtraction. Perhaps we should actually do that.
