### ISSUE TITLE
build error on Windows due to CreatePalette name collision

### ISSUE THREAD

**Issue by mewmew** [diasurgical/devilutionX#641]
**Describe**
When trying to build DevilutionX on Windows, using MSys2 and Mingw64, I get the following error:

```
C:\tools\msys64\mingw64\x86_64-w64-mingw32\include\wingdi.h:2709:29: error: functions that differ only in their return type cannot be overloaded
  WINGDIAPI HPALETTE WINAPI CreatePalette(CONST LOGPALETTE *plpal);
            ~~~~~~~~        ^
./Source/dx.h:16:6: note: previous declaration is here
void CreatePalette();
~~~~ ^
```

**To Reproduce**
1. Clone latest source of DevilutionX
2. Build using MSys2 and Mingw64 on Windows 10.
3. See build error.

**Expected behavior**
Successful compilation.

**Additional context**
I think we had this issue in the past, related to `random`, `SetCursor` and some other functions that collide with the Windows API.

**Comment by AJenbo** [comment]
By window APIs are you referring to window managers like mutter and openbox, or the underlying protocol like Wayland and x11?

**Comment by mewmew** [comment]
Sorry, Windows API, as in Microsoft Windows.

From MSDN: [CreatePalette](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createpalette)

**Comment by AJenbo** [comment]
Do we really need to support such fringe operating systems? Sorry I'm being in my sarcastic joke corner today for some reason :D
