### ISSUE TITLE
in-game menu crash in arena

### ISSUE THREAD

**Issue by ikonomov** [diasurgical/devilutionX#6410]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

version: 1.5.1 beta

### To Reproduce

1. visit arena 1
2. press escape button to show in-game menu
3. press escape button a second time to hide the menu
4. game crashes

**Comment by DakkJaniels** [comment]
What is version 1.5.1 beta? what commit is that?

**Comment by ikonomov** [comment]
Hah, doesn't happen on the newest commit.  It happened while playing my mod and I forgot to check the official devx.
