### ISSUE TITLE
Cannot be run on win XP

### ISSUE THREAD

**Issue by Vodnyk1234** [diasurgical/devilutionX#6422]
### Operating System

Windows x86

### DevilutionX version

1.5.0 (latest release)

### Describe

DevilutionX is compiled for x86, but still gives error message "[path]\devilutionx.exe is nota valid Win32 application."

### To Reproduce

system: win XP
Downloaded [devilutionx-windows-x86_64.zip](https://github.com/diasurgical/devilutionX/releases/download/1.5.0/devilutionx-windows-x86_64.zip) and following all steps. Then tried to run.
I also tried to compile it by myself, got the same result.

**Comment by StephenCWills** [comment]
x86_64 is the 64-bit version. What you want is [devilutionx-windows-i386.zip](https://github.com/diasurgical/devilutionX/releases/download/1.5.0/devilutionx-windows-i386.zip). It probably still won't work with Windows XP, though, because of libzt. I think @Trihedraf might be able to help you get a version that works on XP.

**Comment by AJenbo** [comment]
This guy has a version build without ZeroTier and Discord support which is what prevents it from running on anything older then Vista: http://www.gb-homepage.nl/index.htm

**Comment by Vodnyk1234** [comment]
I tried i386, but it did not work, as you anticipated. I will try what you suggested. Thanks for reply.

**Comment by Vodnyk1234** [comment]
> This guy has a version build without ZeroTier and Discord support which is what prevents it from running on anything older then Vista: http://www.gb-homepage.nl/backports.htm

Works perfectly, thank you!

**Comment by seascape** [comment]
Unfortunately the gb-homepage.nl website seems dead now, and I couldn't get any of the downloads to work via Wayback Machine. (The latest XP version I noticed them having on the archived website was 1.51.) If anyone has any XP builds to host elsewhere it'd be nice to share them here.

**Comment by AJenbo** [comment]
you could download the Window 95 compatible version from the test builds

**Comment by AJenbo** [comment]
I'm not sure what benefits it would have over the legacy Windows build we now have. Do many people use XP for LAN?

**Comment by Trihedraf** [comment]
The 9x build uses SDL1. The XP build just needs ZeroTier and Discord disabled.

**Comment by AJenbo** [comment]
I'm just having a hard time seeing a benefit over the extra overhead, it's hard for people to figure out how to download builds from a workflow and extra builds could confuse people trying to look for the best fit for there platform, so I'm not sure the few extra optimizations is worth it.

**Comment by Trihedraf** [comment]
What about a release only one? Obviously we don't need to be building XP for every commit and PR.

**Comment by Trihedraf** [comment]
I would just call it devilutionx-windows-XP.zip

**Comment by AJenbo** [comment]
Maybe `devilutionx-windows-xp-32bit.zip`?
