### ISSUE TITLE
PlayStation Vita documentation manual is outdated

### ISSUE THREAD

**Issue by iraposeiro39** [diasurgical/devilutionX#6428]
The manual for the psvita port is outdated.
For example, not only does multiplayer work, but it feels like the [controls] section has either been deprecated or is not working.

The manual in question:
https://github.com/diasurgical/devilutionX/blob/master/docs/manual/platforms/vita.md

**Comment by AJenbo** [comment]
@isage maybe this one is a better one to ping you for :)

I updated the MP section, would you be willing to update the default mapping description?

**Comment by isage** [comment]
Sure

**Comment by AJenbo** [comment]
Thanks :)
