### ISSUE TITLE
Apple TV Support

### ISSUE THREAD

**Issue by TheDiscordian** [diasurgical/devilutionX#6429]
It'd be cool if the IPA was built with Apple TV support. I've been trying to get it on there with Sideloadly, and it simply doesn't want to because it's not built with Apple TV support. I'm not sure what changes would be needed (if any), just a flag enabling it to run on the Apple TV I believe.

**Comment by TheDiscordian** [comment]
I just realized I'd have no idea how to get the MPQs to the device, and how to backup saves so I'll just close this.

**Comment by julealgon** [comment]
@TheDiscordian if you want to close this, please use the "Close as not planned" option instead, to avoid confusion. Otherwise, people looking at the issues list might think this was proposed and implemented.

**Comment by AJenbo** [comment]
> I'm not sure what changes would be needed (if any), just a flag enabling it to run on the Apple TV I believe.
It looks to me like apple consider them as different systems and require you to build individual apps for each platform, since we don't have an Apple TV handy we haven't done so. But maybe you could give it a shot?
