### ISSUE TITLE
Warrior Heavy Armor Graphical Glitch

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#6444]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

Unsure if this is vanilla or not, but when attacking straight down with a heavy armor warrior with a sword and shield, the animation for the attack looks a bit awkward, as it sometimes starts on a frame with the shield way out to the right, and other times it runs smooth. Maybe depends on the idle frame animation you're on when you attack?

### To Reproduce

1. Get a warrior with heavy armor, sword, and shield.
2. Attack straight down a single time from the idle animation. If done on the correct frame(s)(?) then you'll see the graphical glitch.

### Expected Behavior

The attack animation should always be smooth with no awkward starting frame.

### Additional context

![graphic glitch](https://github.com/diasurgical/devilutionX/assets/28605404/ae5af050-886d-4b23-8a82-233206943f44)

Not sure if this is vanilla or not, will need to confirm later. I've never noticed this before.

**Comment by julealgon** [comment]
The fact that this appears intermittent is _really_ odd... I wonder if there is something bigger behind it. If it is happening with this particular animation, my gut feeling would say it _should_ be happening with all others, but we are just not noticing it.

Even if this was related to the missing first frame of animation (that was reintroduced in DevilutionX), there is no explanation that would justify it not happening every single time consistently IMHO.

> Maybe depends on the idle frame animation you're on when you attack?

And this should definitely not be the case unless something drastic changed lately.

Also highly doubt this is a vanilla issue, considering the way these animations work.

**Comment by NiteKat** [comment]
After further playing, I noticed that this happens with heavy warrior/sword/shield in multiple directions, not just facing downward. It does not appear to happen with heavy warrior with only a sword. I didn't test maces and maces/shields.

**Comment by AJenbo** [comment]
Thanks
