### ISSUE TITLE
No support for WASD / other movement keys

### ISSUE THREAD

**Issue by k4gi** [diasurgical/devilutionX#6451]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

Binding inputs for movement is supported, but only in Padmapping, not Keymapping

a bunch of stuff is, by the look at, movement is the one i feel is missing

### To Reproduce

in the Padmapping menu, between "Quick Spell" and "Use Health Potion", there are some extra controls, including movement

### Expected Behavior

support for WASD / other movement keys

**Comment by AJenbo** [comment]
I should come eventually. Possibly 1.6.0 since we are working on navigation. Closing the issue since I don't think it is necessary for us to have one for it as it's already in the sitegeist.

**Comment by garryspins** [comment]
Whens this happening?

**Comment by Trihedraf** [comment]
Someday if someone works on it. Which no has yet.

**Comment by mrbigmouth502** [comment]
Any progress? This would be really nice to have for accessibility. I'd love to be able to play Diablo without aggravating my repetitive strain injuries from clicking repeatedly.

**Comment by AJenbo** [comment]
@mrbigmouth502 no updates, but you can hold the mouse in DevilutionX, or use a gamepad.

**Comment by mrbigmouth502** [comment]
I've legit been considering finding a utility to map keyboard keys to gamepad actions as a workaround. I wonder if any exist that work in Wayland. 🤔

**Comment by StephenCWills** [comment]
FYI, there was one developer who worked on this briefly, but he scrapped his work before submitting it because he found that 4-directional inputs like WASD didn't play well with the gridlocked 8-directional movement this game uses. In other words, pressing `W` and `D` simultaneously enough to move diagonally from an idle position is a bit of a challenge.

**Comment by mrbigmouth502** [comment]
A bit of an unconventional solution I thought of would be to have keymaps for diagonals. I'd probably use Q, E, Z, and C for those, then WASD for the rest.

If Diablo didn't rely on mouse input so much, I'd probably use numpad inputs for movement like I do in Shattered Pixel Dungeon. That's another tile-based game, albeit a turn-based one with bump combat where you mostly only need the mouse for menus.
