### ISSUE TITLE
Can't open the character or inventory tabs,  while talking to someone

### ISSUE THREAD

**Issue by k4gi** [diasurgical/devilutionX#6452]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

my brain is literally a sieve, and i would like very much not to have to close the shop menu to check what stuff i have on me.

you can use a controller to open the menus, but not the onscreen buttons

### To Reproduce

go talk to someone and smash that fucking Inv button

### Expected Behavior

character and/or inventory menus open. the other ones don't open either, so them too maybe?

**Comment by AJenbo** [comment]
You are not supposed to be able to

**Comment by k4gi** [comment]
damn is that how it is

**Comment by julealgon** [comment]
> damn is that how it is

How would you suggest this would be implemented @k4gi ?

I don't like how trigger-happy Ajenbo is with closing these issues right away like this either... but this one seems far fetched even to me. Are you proposing a full UI redesign to support your use-case?

**Comment by AJenbo** [comment]
Managing almost 400 issues is a bit unwieldy so unless something has essential information I'm inclined not to have a tracker item for it. Once we solve a big chunk of what is already on the todo we can add some more pretty quick.

**Comment by k4gi** [comment]
@AJenbo this is a little different to how i've learned to expect people to use git, but fair :)

@julealgon i'm not sure what parts of the ui would have to be redesigned. if the only thing that changed was that the character and inventory buttons worked during a conversation, i would be happy. i suppose that might break something? and it doesn't exactly look right, but it would do

**Comment by julealgon** [comment]
> @julealgon i'm not sure what parts of the ui would have to be redesigned. if the only thing that changed was that the character and inventory buttons worked during a conversation, i would be happy. i suppose that might break something? and it doesn't exactly look right, but it would do

Again, I'm confused though. When you are talking to a towner, either the entire screen is already taken over by a transcript text, or half/entire the screen is taken over by the shop UI.

Are you suggesting the char/inventory should just open on top of whatever is in the screen currently?

**Comment by k4gi** [comment]
@julealgon yes. it's better than nothing

**Comment by julealgon** [comment]
> @julealgon yes. it's better than nothing, also in widescreen it's not quite half or whole screen

Well in that case I just don't agree with it. Not only it will look really messy, but it introduces nontrivial problems such as having to refresh the vendor when any changes are made to your inventory (like dropping/equipping items, gold, etc).

If you want to propose something that solves a problem you are having, I think you'll need to provide a more solid proposal than this.
