### ISSUE TITLE
[Question] Combat mlvl difficulty adjustment only applied once for uniques, intentional?

### ISSUE THREAD

**Issue by localappdata** [diasurgical/devilutionX#6461]
Hello,

I noticed unique monsters have their final combat mlvl adjusted by +15/+30 instead of the vanilla +30/+60 from the way it is doubled:

https://github.com/diasurgical/devilutionX/blob/98927e7a6eb002cc9f4dc2554ae7a713a885aa4d/Source/monster.h#L363-L392

Is it intended to work this way in DevX and are the extra mlvls treated like a bug/unintended behavior in vanilla?

Thanks for your time!

**Comment by StephenCWills** [comment]
Yes, it was a bug. #2766
