### ISSUE TITLE
Chore: Upgrade Android project to target Android 13

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#6479]
### Operating System

Android

### DevilutionX version

1.5.0 (latest release)

### Describe

https://developer.android.com/google/play/requirements/target-sdk

Starting August 31st, new apps must target Android 13 (API level 33)
Unfortunately, it's not as simple, as to change `targetSdkVersion` in build script

Here are behaviour changes for targeting Android 13: https://developer.android.com/about/versions/13/behavior-changes-13

### To Reproduce

Open project in Android Studio and see "Not targeting latest SDK version" warning

### Additional context

Related to https://github.com/diasurgical/devilutionX/issues/6210

**Comment by AJenbo** [comment]
... hopefully 1.5.1 will be out before then.

**Comment by tsunamistate** [comment]
Closed by https://github.com/diasurgical/devilutionX/pull/6486

**Comment by AJenbo** [comment]
Thanks
