### ISSUE TITLE
No sound in game

### ISSUE THREAD

**Issue by bbarski** [diasurgical/devilutionX#648]
**Describe**
No sound in game

**To Reproduce**
1. start game with ./devilutionx

**Expected behavior**
Full sound support in cinematics, menu and ingame

**Screenshots**
NA

**Additional context**

CLI SDL INFO:
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0

system info:

Linux version 5.3.0-28-generic (buildd@lcy01-amd64-009) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1))  nr.30 ~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020

00:00.0 Host bridge: Intel Corporation Device 3e35 (rev 0b)
00:02.0 VGA compatible controller: Intel Corporation Device 3ea0
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 0b)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Device 9df9 (rev 30)
00:14.0 USB controller: Intel Corporation Device 9ded (rev 30)
00:14.2 RAM memory: Intel Corporation Device 9def (rev 30)
00:15.0 Serial bus controller [0c80]: Intel Corporation Device 9de8 (rev 30)
00:16.0 Communication controller: Intel Corporation Device 9de0 (rev 30)
00:17.0 SATA controller: Intel Corporation Device 9dd3 (rev 30)
00:1d.0 PCI bridge: Intel Corporation Device 9db0 (rev f0)
00:1e.0 Communication controller: Intel Corporation Device 9da8 (rev 30)
00:1f.0 ISA bridge: Intel Corporation Device 9d84 (rev 30)
00:1f.3 Audio device: Intel Corporation Device 9dc8 (rev 30)
00:1f.4 SMBus: Intel Corporation Device 9da3 (rev 30)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device 9da4 (rev 30)
01:00.0 Network controller: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 31)

**Comment by qndel** [comment]
turned the speakers on? :P
