### ISSUE TITLE
Enable all cut quests (Island of the Sunless Sea, Maps of the stars, etc…)

### ISSUE THREAD

**Issue by Diablo-lost** [diasurgical/devilutionX#6495]
First of all, congratulations for the quality of the DevilutionX project and the updates you release on a quite regular basis. If you’ll start a Patreon, I'll sign up right away and I'll finance you!
As for the missions included in the original Diablo CD but cut in the final version of the game (Island of the Sunless Sea, Maps of the stars, etc…) I have already found they have been implemented in other mods (The Hell, Beelzebub). Are you able to add them on DevillutionX? That would be great, and I'm not the only user asking for this. Thank you for listening. You are the best!

**Comment by julealgon** [comment]
It is not a matter of "enabling" the quests, since most of them really don't exist per se: they are vastly incomplete.

Also, Belzebub is not really a mod... people should stop talking about that project as if it was IMHO.

**Comment by kphoenix137** [comment]
The content for these quests is not fully intact, and recreating aspects of these quests from scratch would be far beyond the scope of the project, as this is more of an improvement project and not a modding project.

**Comment by AJenbo** [comment]
Thanks, but we want to keep this project free of any form of payments.

The only thing that exists of the quests you mentioned are the voice lines. The rest is build from scratch by the Beelzebub developers based on the design pitch document and parts of Diablo 2.

**Comment by Diablo-lost** [comment]
OK fine, anyway thanks to all of you for your hard work! See you next release! I'm going to start another run in v1.5.0 trying all the quests in multiplayer ;-)

**Comment by kphoenix137** [comment]
> OK fine, anyway thanks to all of you for your hard work! See you next release! I'm going to start another run in v1.5.0 trying all the quests in multiplayer ;-)

Keep an eye out for upcoming DevilutionX mods in the Discord server.
