### ISSUE TITLE
Gamepad graphics

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#6537]
Per Android TV UI guidelines we should:

1. Tell the user that the gamepad is required
2. Show gamepad controls visually

I've made a CLX based on https://developer.android.com/training/tv/start/controllers:

![gamepad](https://github.com/diasurgical/devilutionX/assets/216339/b8961e20-f2b0-4509-aa02-9058d56ae0b5)

PCX: [gamepad.pcx.zip](https://github.com/diasurgical/devilutionX/files/12498550/gamepad.pcx.zip)
CLX: [gamepad.clx.zip](https://github.com/diasurgical/devilutionX/files/12498558/gamepad.clx.zip)

```
pcx2clx --transparent-color 1 gamepad.pcx
```

**Comment by AJenbo** [comment]
I chose to implement this on the Android side of things, at least for now.
https://github.com/diasurgical/devilutionX/pull/6546
