### ISSUE TITLE
[Issue Report]:  Cant find devilutionx.exe

### ISSUE THREAD

**Issue by blazeBR** [diasurgical/devilutionX#6538]
### Operating System

Windows x64

### DevilutionX version

1.5.0 (latest release)

### Describe

where can I find devilutionx.exe ?

### To Reproduce

cant find

**Comment by blazeBR** [comment]
Please, How can I find the .exe file?

**Comment by AJenbo** [comment]
If you need help please use Discusion or the chat.

Your question is also unclear, do you not know where things are located on your computer or are you having trouble finding the download section: https://github.com/diasurgical/devilutionX/releases/latest
