### ISSUE TITLE
Can't execute the 1.0.1 release on Debian 10

### ISSUE THREAD

**Issue by cosmincrihan** [diasurgical/devilutionX#654]
When trying to execute the Linux 64 binary (for version 1.0.1) on Debian 10, it throws the following error:
```
cosmin@debian-gl553v:/mnt/hdd/JOCURI/Diablo$ ./devilutionx 
./devilutionx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./devilutionx)
```
I found out that the cause is the binary being built with a more recent version of GLIBC than the system supports. I am using Debian 10 Buster (stable), which has GLIBC 2.28.
Can you please provide a binary for this glibc version?

I compiled devilutionx myself, but I still cannot run it, it gives me the following error:
```
ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD
```

Version 1.0.0 worked fine though, no issues.

**Comment by AJenbo** [comment]
My bad, build this on ubuntu 19.10 instead of the usual build server, will have one up later.

> ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD

Either do a release build or make sure that asan in loaded first (possibly by preloading via LD_PRELOAD)

**Comment by cosmincrihan** [comment]
> My bad, build this on ubuntu 19.10 instead of the usual build server, will have one up later.
> 
> > ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD
> 
> Either do a release build (see CMake options part of the readme) or make sure that asan in loaded first (possibly by preloading via LD_PRELOAD)

Thank you very much for the tip!
I used the `-DBINARY_RELEASE=ON` flag and the release version runs fine now.

**Comment by AJenbo** [comment]
Ok the Linux build is back up, this time in a version compatible with Debian 9+
