### ISSUE TITLE
[Issue Report]: Linux runner script doesn't pass arguments

### ISSUE THREAD

**Issue by michaelneverwins** [diasurgical/devilutionX#6553]
### Operating System

Linux x64

### DevilutionX version

1.5.1

### Describe

The `devilution.sh` script, which helps the `devilutionx` executable load the included `discord_game_sdk.so`, does not accept [command-line arguments](https://github.com/diasurgical/devilutionX/wiki/DevilutionX-additional-arguments-configuration-guide) — or, rather, does not pass them along to the `devilutionx` executable.

### To Reproduce

1. Download [`devilutionx-linux-x86_64.tar.xz`](https://github.com/diasurgical/devilutionX/releases/download/1.5.1/devilutionx-linux-x86_64.tar.xz) and unpack it.
2. Add game data (e.g. `DIABDAT.MPQ`) as necessary.
3. Run the unpacked `devilutionx.sh` with some command-line argument whose effect is easily noticeable, e.g. `-n` to skip intro videos.
4. Observe that the command-line argument did not have any effect.

### Expected Behavior

Ideally the `devilutionx.sh` script should accept command-line arguments and pass them to the `devilutionx` executable.

### Additional context

I've fixed this on my end by adding `$@` to the end of the last line of the script, as follows:
```bash
#!/bin/sh
BASEDIR="$(dirname "$(realpath "$0")")"
LD_LIBRARY_PATH="$BASEDIR" "$BASEDIR"/devilutionx $@
```
Disclaimer: I don't actually know whether that's the best way to do it. (Does this syntax work with every Linux shell? I'm not sure.)

**Comment by glebm** [comment]
Yeah that's the way to fix it, please send a PR!
It should be `"$@"` with quotes for the correct expansion though

**Comment by michaelneverwins** [comment]
I just installed DevilutionX 1.5.3 from `devilutionx-linux-x86_64.tar.xz` and the `devilutionx.sh` file still doesn't have the `"$@"`, even though it seems that `Packaging/nix/LinuxReleasePackaging.sh` is still as #6558 left it. Do recent releases not include that commit? Or is that not actually the script that builds the `devilutionx.sh` file for the `devilutionx-linux-x86_64.tar.xz` package specifically?

Anyway, it's not really a problem for me, since I can just modify the installed `devilutionx.sh` to my heart's content...

**Comment by AJenbo** [comment]
1.5.3 is on the 1.5 branch, not master which is what will become 1.6.0

**Comment by AJenbo** [comment]
I have added it to the 1.5 branch now, so in case there is a 1.5.4 it will also be in that one.

**Comment by michaelneverwins** [comment]
Oh, that makes sense. I didn't know the 1.5.x releases had their own branch, so I was afraid my old one-line merge request had gotten it wrong somehow : )
