### ISSUE TITLE
[Issue Report]: Player sent invalid player data during attempt to join the game

### ISSUE THREAD

**Issue by ebourg** [diasurgical/devilutionX#6559]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

I've imported a multiplayer character from Diablo 1.09 ([multi_0.zip](https://github.com/diasurgical/devilutionX/files/12505583/multi_0.zip)), when I start a network game (either ZeroTier or TCP), another player attempting to join gets the error message 'Player X sent invalid player data during attempt to join the game', and instead of joining the game he lands alone in a new game.

I don't know if that matter, but the game was started by DevilutionX  running on Windows 10, and the other player was on macOS with the same version of DevilutionX. 

The error also appears if the game is started by the other player instead.

### To Reproduce

1. Import the character and start a network game
2. Join the game with another player

**Comment by AJenbo** [comment]
try dropping all items, change level, then go back and pick up the items again

**Comment by ebourg** [comment]
I dropped the gold on the ground and the other player was able to join. I picked it back and the error no longer occurs.

What is causing this issue?

**Comment by kphoenix137** [comment]
> I dropped the gold on the ground and the other player was able to join. I picked it back and the error no longer occurs.
> 
> What is causing this issue?

Your Gold pile had a flag that should have been impossible to have, so the game flagged the item as invalid (illegal). Investigation is currently taking place to see how that happened, since it seems more likely that the vanilla game did something wrong.

**Comment by ebourg** [comment]
Thank you for the help and the quick fix!
