### ISSUE TITLE
[Issue Report]: "Game Saved" message stayed much longer than needed

### ISSUE THREAD

**Issue by Lywzc** [diasurgical/devilutionX#6573]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Since 1.5.1, the "Game Saved" message when you save becomes much longer. In the 1.5.0 it disappeared very quickly so I know I saved without it blocking part of my screen. Now it stays on the screen for 2 seconds which is unnecessarily long.

### To Reproduce

Press Quicksave button or press "Save Game" in the escape menu.

**Comment by qndel** [comment]
Some people complained it was too short before.

**Comment by Lywzc** [comment]
Why do you even need it to be long? There is no extra information whatsoever except the fact that you saved. It is not like you will miss any information by displaying it faster.

**Comment by AJenbo** [comment]
The old message only showed while the system was writing to disk. On some computers that was so short that the message never appeared on screen so some users did not get a confirmation that it saved.
The current one is set to stay on screen 1 after the save is successful. You can dismiss the message by pressing space or esc like with other messages.

If you are the message for 2 sec. that would imply that your system is at most 2% as fast as a modern PC. What kind of CPU and data storage does it have?

**Comment by Lywzc** [comment]
i7 9700k, the drive is an NVMe SSD with 1GB/s sequential and 300MB/s random write.

**Comment by AJenbo** [comment]
Hm then it should be much closer to 1 sec, could you please confirm how long the message is onscreen.

**Comment by Lywzc** [comment]
After measuring it with stopwatch, it turns out to be about 1.1s or so. My previous estimate seemed to be too generous.

And I did not know that you can close it by pressing esc or space. Since I usually quicksave before fighting bosses or dangerous creatures, the 1 second appears longer for me which I apologize.

Finally, is is possible to close it by clicking or make it not obstructive by shrinking and moving it to the upleft corner, since as I said, I am used to start fighting right after saving which makes esc or space not intuitive.

**Comment by AJenbo** [comment]
Ok thanks. I made an adjustment to discount the actual save time so that the total time should be exactly 1 sec.
https://github.com/diasurgical/devilutionX/pull/6574

When looking in to how long to make the message the general rekommendation was 2-3 sec. If we make it much less then 1 sec I think we could run the risk of some people not having time to see what the text says.

By the way you mention saving via the esc menu, but also said quick save. Are you refering to the quick save shortcut key (F2 by default)?

**Comment by Lywzc** [comment]
Yes. I use F5 since habits. I only bring up esc menu saves since it behaves the same. I almost exclusively use quicksave since it can be done while I am fighting. After the update the message will block my surroundings so it becomes very awkward to save while near or in fight.

That is why my last sentence says if it can be dismissed by clicking or be moved to a place where it will not block my immediate surroundings like the corner.
