### ISSUE TITLE
[Issue Report]: Upgrading some spells makes no sense

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#6575]
### Operating System

Linux x64

### DevilutionX version

1.5.1

### Describe

As the title suggests, there is no point in upgrading some spells because there are no benefits whatsoever.
Let's take Chain Lightning as an example and when you level it up, the mana consumption neither decreases nor the ability to generate greater damage increases. This is vanilla behavior.

### To Reproduce

1. Find and Read book of Chan Lightning to upgrade to level 2
2. As a result, notice that the values (mana, damage) do not change

![chain](https://github.com/diasurgical/devilutionX/assets/45902449/ba14ded3-4bbd-4042-83df-7186e712c08c)

### Expected Behavior

Unfortunately I don't know either. If we changed the values, the gameplay would change and would no longer be vanilla. We could set level 1 as maximum in gold color.

### Additional context

Further suggestions are very welcome.

**Comment by DakkJaniels** [comment]
Level 1 is maximum for chain lightning. It gets bonuses to range and duration. Additional information could be displayed.

**Comment by julealgon** [comment]
This is overly broad IMHO. I tend to agree that this is a bit nonsensical for some spells, but the issue should provide more exhaustive detail about which spells are problematic and why each of them is.

> Additional information could be displayed.

@DakkJaniels this is probably a good idea. We could potentially display "projectile speed", "projectile size" etc in the UI, but that's gonna require some adjustments to fit and also some decisions to be made in regards to which units of measure to use in the in-game representation.

Alternatively, one could also think about potentially displaying what the increments will be when consuming a book, either before or after it is consumed (not exactly sure how to show this in the UI as well, just throwing the idea out there).

**Comment by kphoenix137** [comment]
> ### Operating System
> 
> Linux x64
> ### DevilutionX version
> 
> 1.5.1
> ### Describe
> 
> As the title suggests, there is no point in upgrading some spells because there are no benefits whatsoever. Let's take Chain Lightning as an example and when you level it up, the mana consumption neither decreases nor the ability to generate greater damage increases. This is vanilla behavior.
> ### To Reproduce
> 
>     1. Find and Read book of Chan Lightning to upgrade to level 2
> 
>     2. As a result, notice that the values (mana, damage) do not change
> 
> 
> ![chain](https://user-images.githubusercontent.com/45902449/266589240-ba14ded3-4bbd-4042-83df-7186e712c08c.png)
> ### Expected Behavior
> 
> Unfortunately I don't know either. If we changed the values, the gameplay would change and would no longer be vanilla. We could set level 1 as maximum in gold color.
> ### Additional context
> 
> Further suggestions are very welcome.

Is this a prank?

**Comment by AJenbo** [comment]
> Is this a prank?

?

**Comment by DakkJaniels** [comment]
The name of the issue isn't accurate. It does make sense to upgrade many of these spells, the game just doesn't tell you what is changing.

**Comment by AJenbo** [comment]
fair point, lets open a new one once someone feels like writing that stuff
