### ISSUE TITLE
[Issue Report]: 1.5.1 broken on Vita

### ISSUE THREAD

**Issue by NaKrulity** [diasurgical/devilutionX#6581]
### Operating System

PlayStation Vita

### DevilutionX version

1.5.1

### Describe

Whenever I try to open the last version, it says that it Failed to load UI resources and to make sure that devilutionx.mpq is in the right folder (it is). I tried to update and to install from scratch, but nothing works. 1.5 still open the game, though. I never had any problem with the game before. Am I doing something wrong ?

### To Reproduce

Update 1.5 to 1.5.1, run the game.

### Expected Behavior

The game opens.

**Comment by AJenbo** [comment]
I don't beilve there is supposed to be a devilutionx.mpq for the via as it as it intergrated. Can you show the exact error. Maybe try deleting devilutionx.mpq, where did you get it from? My guess is that you are overwriting the internal resources with an old devilutionx.mpq that you got from a PC build or something.

**Comment by AJenbo** [comment]
Please make sure you do not have old files in your installation and provide exact error messages. Then we can re open the issue if the problem persist.

**Comment by DigiD2** [comment]
Just replying here to confirm the fix in case anyone else has the same issue for vita. 

I can confirm what AJenbo has said. Deleting devilutionx.mpq solves the issue. That is not needed anymore.
