### ISSUE TITLE
[Issue Report]: Wrong formula of Armor Class

### ISSUE THREAD

**Issue by GregAyrton** [diasurgical/devilutionX#6588]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Armor Class in mod version after 1.4.1 has wrong formula (like with Bard)

### To Reproduce

Compare versions of mod - 1.4.1 vs 1.5 or 1.5.1

**Comment by Trihedraf** [comment]
It was fixed to add the hidden bonus that has always been there.
