### ISSUE TITLE
[Issue Report]: spawn/spawnu debug commands fail with "Failed to parse argument as integer"

### ISSUE THREAD

**Issue by ChaosMarc** [diasurgical/devilutionX#6593]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

DevilutionX v1.6.0-dev-Debug-6c51496c6

spawn and spawnu can't be used anymore as they produce an error for any parameter combination there is:

```
INFO: DebugCmd: spawn skeleton 4 Result: Failed to parse argument as integer
INFO: DebugCmd: spawn skeleton Result: Failed to parse argument as integer 
INFO: DebugCmd: spawn 4 skeleton Result: Monster name cannot be empty. Duh.
INFO: DebugCmd: spawn 4 Result: Monster name cannot be empty. Duh.
```

propably broken since: https://github.com/diasurgical/devilutionX/commit/53db86ee9a92fefaae87b48ede3ee78054e4b450

### To Reproduce

* Start a single player game with a debug version of the game
* enter "spawn skeleton" or "spawn skeleton 5" in the chat

**Comment by DakkJaniels** [comment]
try it without a number - you didn't do that combination
