### ISSUE TITLE
Multiplayer difficulty selection with keyboard arrows

### ISSUE THREAD

**Issue by MysteryFTG** [diasurgical/devilutionX#661]
This is just a very minor issue, not really a bug, but still something that's different from Diablo 1.09.

When starting a new multiplayer game the normal difficulty is selected by default. In 1.09 I can press "up" on the keyboard to wrap down to hell difficulty. This is also how the main menu behaves.

The main menu works correctly in devilutionX, however the multiplayer difficulty selection doesn't wrap around and I have to press down twice to get from normal to hell.

**Comment by yuripourre** [comment]
This is the first time I dive deep into the menu code, so I may be wrong.
My guess is that is something related to this function: https://github.com/diasurgical/devilutionX/blob/master/Source/gmenu.cpp#L133

**Comment by AJenbo** [comment]
@yuripourre that would be the ingame menu. For DiabloUI you define if the menu should wrap or not via the last parameter for `UiInitList` https://github.com/diasurgical/devilutionX/blob/master/SourceX/DiabloUI/selgame.cpp#L152

**Comment by yuripourre** [comment]
Thanks @AJenbo. I am trying to understand the code.
