### ISSUE TITLE
data file error - unable to open diabdat.mpq

### ISSUE THREAD

**Issue by pc-star** [diasurgical/devilutionX#662]
Hello,

And thanks for all the good work, you been putting through until there. It is really appreciated.

I took some time and looked at the closed issues, to see if this issue was mentioned before, I am currently trying to run it on Debian 9 64-bit. Not sure if that could be a bug related to the project itself, or if might be related somehow to the diablo cd / iso I own.

What I done so far :

- copy the diabdat.mpq from the iso created from the original disc
- get the latest available version ( 1.0.1 ) as for the README
- extract it, and copy inside the same folder the aforementioned diabdat.mpq
- run ./devolutionx --data-dir $unzipped_folder_path
- get the error from the title

The files I can see in the current folder are

drwxr-xr-x 2 paul paul      4096 Mar 17 10:33 .
drwxr-xr-x 3 paul paul      4096 Mar 17 10:33 ..
-rw------- 1 paul paul   1602332 Sep 19 21:33 CharisSILB.ttf
-rwxr-xr-x 1 paul paul   3184192 Mar  9 23:17 devilutionx
-rw-r--r-- 1 paul paul 517501282 Mar 17 10:33 diabdat.mpq
-rw------- 1 paul paul      4533 Sep 19 21:33 LICENSE.CharisSILB.txt
-rw-r--r-- 1 paul paul      1476 Dec 31 19:24 README.txt

tried also building it from source, using the latest version, and specifying the -DBINARY_RELEASE=ON -DASAN=OFF -DUBSAN=OFF options during the cmake build step, but got the same error message when tried to run it after being able to build it. As a further check I tried omitting the data-dir option and copying the diabdat.mpq into the ~/.local/share/.. folder, but with no luck.

I checked the file permissions and made sure it was at least 644 with owner and group assigned as the current user on the system.

there is anything else could I try ?

**Comment by yuripourre** [comment]
The correct folder is `~/.local/share/diasurgical/devilution` is the file there?

**Comment by pc-star** [comment]
yes the file is in that directory. 

I did not mention the full path before, as it seemed to me something clear.

The binary, it is in a complete different directory, indeed.

**Comment by yuripourre** [comment]
Have you tried to run only `./devolutionx` ?

**Comment by pc-star** [comment]
tried both, calling ./devolutionx without any option and declaring the absolute path without tilde, but same result I am afraid.

**Comment by AJenbo** [comment]
What is the md5 of your mpq?

**Comment by pc-star** [comment]
fe5166d2d7c7b7965a80131e93f01fab  diabdat.mpq

**Comment by AJenbo** [comment]
This doesn't appear to be the correct MPQ file, the size does appear to be correct, but the md5 should be 011bc6518e6166206231080a4440b373

are you able to open it using mpq explorer or a similar tool?

**Comment by pc-star** [comment]
I was able to extract all the files inside it, due to the use of [MPQExtractor](https://github.com/Kanma/MPQExtractor).

At the moment I can see there are several files, between wav, xxx and pcx extensions. 

But, I am not so sure how to get the 10 first bytes of any of those, or the archive itself.

**Comment by AJenbo** [comment]
Use a hex editor. It's the 10 first bytes of the MPQ that we are interested in.

**Comment by pc-star** [comment]
hopefully that will be what needed.

hexdump -n10 diabdat.mpq
0000000 504d 1a51 0020 0000 714a
000000a

**Comment by AJenbo** [comment]
That appears correct, this is rather interesting as it's a version of the MPQ that I have never seen before. Would you be able to get on Discord so we can maybe try debugging it a bit?

**Comment by pc-star** [comment]
Sure. Do we want to carry on into the development channel ? or ... ?

**Comment by AJenbo** [comment]
We have concluded that the MPQ in question had been corrupted, the size is identical to the second release, but the hash was not identical and tools showed that several files in it where damaged and even missing. This was also supported by the original game seamed unable to run.
