### ISSUE TITLE
Force -DNONET=ON for singleplayer?

### ISSUE THREAD

**Issue by moonburnt** [diasurgical/devilutionX#664]
Unless compiled with -DNONET=ON flag, game dies on me after character creation (in singleplayer mode, obviously) with following error:
![image](https://user-images.githubusercontent.com/52989889/76888155-1ed1d680-688c-11ea-8025-7d1fdc77e34e.png)

I assume, it happens because Im running it on linux machine without any network connection available. I have no idea which changes this flag make, code-wise (can only assume that, by default, game launches a server on localhost even for singleplayer campaign) - but maybe its possible to make game work with changes it provide by default, in case you select singleplayer?

**Comment by arrowgent** [comment]
do you have localhost?
127.0.0.1

**Comment by moonburnt** [comment]
seems like, due to misconfigured firewall, I indeed didnt have access to 127.0.0.1. Now everything works. Sorry for bothering

**Comment by AJenbo** [comment]
Thank you for the feedback
