### ISSUE TITLE
[Issue Report]: Chamber of Bone already open when entering the level

### ISSUE THREAD

**Issue by ChaosMarc** [diasurgical/devilutionX#6662]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

Commit: ffc7190

The door to the horde of skeletons was already open when I entered the level for the first time.

[single_6.zip](https://github.com/diasurgical/devilutionX/files/12731221/single_6.zip)

### To Reproduce

- Load savegame
- note that the map is not revealed very far
- walk to the chamber with the supposedly closed door
- it's already open...

**Comment by AJenbo** [comment]
This happens sometimes when the horned monster dets close to the door and decides to open it before doing in your direction.

**Comment by ChaosMarc** [comment]
I didn't know that! Thanks for the explanation 🙂
