### ISSUE TITLE
[Issue Report]: Opening trapped chest with loot unleashes a silent missile

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#6668]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

https://github.com/diasurgical/devilutionX/assets/57089001/4d0e6fef-a2be-40ad-b2ad-81d51b12310f

[single_3.zip](https://github.com/diasurgical/devilutionX/files/12769813/single_3.zip)

### To Reproduce

Open save file and open chest

**Comment by qndel** [comment]
I think everything works fine, you just did the same thing I did and associated bow firing sound with arrows. Other missiles have sounds, arrows never did, to address this situation I think we could add the "trap trigger" sound also to chests.
