### ISSUE TITLE
[Feature Request]: Please add LAN games auto-discovery / ZeroConf / mDNS / Bonjour / Avahi

### ISSUE THREAD

**Issue by Technologov** [diasurgical/devilutionX#6671]
### Feature Type

Quality of Life

### Describe

Hello,

As of v1.5.1, DevilX requires to manually enter an IP address for multi-player games; I believe this requirement can be waived for LAN games by adding auto-discovery mechanism;

Such protocol is called "mDNS" aka "ZeroConf". Implementations are called "Avahi" and "Bonjour".

Try this ?
https://github.com/mjansson/mdns

**Comment by AJenbo** [comment]
You can use the ZeroTier network for autodiscover
