### ISSUE TITLE
[Issue Report]: Random crashes during game

### ISSUE THREAD

**Issue by Technologov** [diasurgical/devilutionX#6672]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Random crashes during multi-player game; v1.5.1. Using Hellfire

How to find a stack or a crash dump or log file ?

Just playing around with 2 Sorcs on level 2 over LAN.

One client was Windows x64 (host); other was Android 13 (guest); Game on Windows host crashed;
We need some log-files.

### To Reproduce

Difficult to reproduce. 
This bug may be possible to reproduce with single-player game or maybe not.

**Comment by StephenCWills** [comment]
The best log file you can get from a release build is from adding `--verbose` and capturing stderr. This is often not useful for investigating crashes.

`devilutionx.exe --verbose 2> devilutionx.log`

The best way to investigate crashes is to find out how to reproduce them.

**Comment by AJenbo** [comment]
On Android the OS will collect stack traces on crashes. When this isn't the case you would need to run a debug build.

There is not enough here to replicate the issue, or even know if it is indeed the same issue if replicated so closing it for now, feel free to update it if you manage to get more info on it.
