### ISSUE TITLE
[Issue Report]: Quests are NOT shown as completed

### ISSUE THREAD

**Issue by Technologov** [diasurgical/devilutionX#6674]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

v1.5.1 ; Quests are NOT shown as completed.
Poisoned water supply + The Butcher were completed;
In original Diablo they would disappear from the Quests List; but not here. Why ?
The should either disappear as in original game or be marked as [Completed].

### To Reproduce

1. complete Poisoned water supply 
2. complete The Butcher 
3. Open "Quest" menu item (on Windows x64)
4. the quests are still there

**Comment by Trihedraf** [comment]
Quests turn gold when completed and are no longer selectable
