### ISSUE TITLE
[Issue Report]: Incorrect string display in shrine

### ISSUE THREAD

**Issue by bubio** [diasurgical/devilutionX#6675]
### Operating System

Mac

### DevilutionX version

Custom build (please specify commit ID)

### Describe

b318d702e5ee6e1c7da93ad4c2f46d7287c8cad8

The string display of the shrine is corrupted. 
Probably occurs in CJK languages.

### To Reproduce

Click on Shrine

### Additional context

![スクリーンショット 2023-09-30 17 18 02](https://github.com/diasurgical/devilutionX/assets/78299054/c66cd477-9588-433f-8a54-1505237c61c3)

**Comment by AJenbo** [comment]
Sorry I think I need some help understanding what "corrupted" mean here.

**Comment by bubio** [comment]
The bottom of the text has been cut off.
The correct answer is as follows.

"天よりの眺め、道は明らかとなる"

![スクリーンショット 2023-09-30 21 55 21](https://github.com/diasurgical/devilutionX/assets/78299054/e2096247-7a90-4bbc-8d31-32b31ca525be)


https://github.com/diasurgical/devilutionX/blob/b318d702e5ee6e1c7da93ad4c2f46d7287c8cad8/Source/error.cpp#L34

LineHeight was set to 20 to display.
