### ISSUE TITLE
LeakSanitizer-reported leaks during startup / latest master

### ISSUE THREAD

**Issue by perchrh** [diasurgical/devilutionX#668]
Hi, thanks for your work on devilution :)
I just built it from source, and it starts fine. I noticed some warnings from LeakSanitizer (below). 
I'm using master/d3ea0ec7975ca1cd828659ce3c10a5a6df8339b1 on Ubuntu 19.10/x86-64. 

  INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
  INFO: Unhandled SDL event: SDL_TEXTEDITING 0
  
  =================================================================
  ==9860==ERROR: LeakSanitizer: detected memory leaks
  
  Direct leak of 6280 byte(s) in 3 object(s) allocated from:
  #0 0x7fcdd5cdace6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dce6)
  #1 0x7fcdcd641085  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.440.64+0xe58085)
  
  Direct leak of 512 byte(s) in 1 object(s) allocated from:
  #0 0x7fcdd5cdaf1e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10df1e)
  #1 0x7fcdcd641aaf  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.440.64+0xe58aaf)
  
  Direct leak of 24 byte(s) in 6 object(s) allocated from:
  #0 0x7fcdd5cdace6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dce6)
  #1 0x7fcdd422d842 in pa_xmalloc0 (/lib/x86_64-linux-gnu/libpulse.so.0+0x3b842)
  
  Direct leak of 17 byte(s) in 1 object(s) allocated from:
  #0 0x7fcdd5cdaae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
  #1 0x7fcdd41107d6 in _XlcDefaultMapModifiers (/lib/x86_64-linux-gnu/libX11.so.6+0x5c7d6)
  
  Indirect leak of 80808 byte(s) in 251 object(s) allocated from:
  #0 0x7fcdd5cdace6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dce6)
  #1 0x7fcdcd641085  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.440.64+0xe58085)
  
  Indirect leak of 2813 byte(s) in 199 object(s) allocated from:
  #0 0x7fcdd5cdaae8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dae8)
  #1 0x7fcdcd64089b  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.440.64+0xe5789b)
  
  Indirect leak of 752 byte(s) in 6 object(s) allocated from:
  #0 0x7fcdd5cdaf1e in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10df1e)
  #1 0x7fcdcd641aaf  (/lib/x86_64-linux-gnu/libnvidia-glcore.so.440.64+0xe58aaf)
  
  SUMMARY: AddressSanitizer: 91206 byte(s) leaked in 467 allocation(s).

**Comment by AJenbo** [comment]
Thank for reporting, but these are all in drivers like libnvidia, libX11 and libpulse, so are mostly likely outside our influence. Also if they do not grow over time it is probably just because they perform a dirty shutdown rather then actual leak memory.

Also if you are not wanting to debug but rather just play the game it might be an idea to build a release build instead so you do not get warnings and notices like this (see CMake options section of the build instructions).
