### ISSUE TITLE
[Issue Report]: Softlock removing Auric Amulet

### ISSUE THREAD

**Issue by StephenCWills** [diasurgical/devilutionX#6681]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Removing Auric Amulet when your inventory is full will drop excess gold on the ground. Doing so may cut off the empty tiles around the player, making it impossible to drop the Auric Amulet.

Basically the same thing that was happening in #4205, but under different circumstances.

[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/12776012/single_0.hsv.zip)

### To Reproduce

1. Download the attached save
2. Load game
3. Open inventory
4. Pick up the amulet on the ground
5. Replace Auric Amulet with the amulet you picked up

### Expected Behavior

Maybe the game should ensure that one space remains open around the player so the amulet can be dropped.

**Comment by kphoenix137** [comment]
What if we revise item dropping behavior to mimic what happens when the game attempts to place items around a tile when there are no available spots? Like when you die, it's able to drop items more than 1 tile away from the player.

**Comment by StephenCWills** [comment]
That sounds like what we did in #3481. It was restricted to vanilla-like behavior in #3530. And qndel has one that's still open in #3489.

That approach would certainly fix this, but whether it would be accepted is another matter. My thought was we could check `HoldItem` in `DeadItem()` to see if we should reserve one of the spaces around the player when scanning the area around the player.

**Comment by AJenbo** [comment]
could we drop HoldItem in DeadItem()?

**Comment by StephenCWills** [comment]
Well, we can go to the function that calls `DeadItem()`. `StripTopGold()` could check for empty spaces around the player and invoke `DeadItem()` on `HoldItem` if necessary. It might be a bit surprising for the player when they can't find their Auric Amulet right away, but it would solve the softlock in this case... unless the ground runs out of space. And we could prevent the ground running out of space by checking `ActiveItemCount` while dropping gold.

**Comment by AJenbo** [comment]
I think that sounds like a good solution.
