### ISSUE TITLE
[Issue Report]: Can't cast some spells when standing at a bookshelf

### ISSUE THREAD

**Issue by myself600** [diasurgical/devilutionX#6691]
### Operating System

Other (please specify)

### DevilutionX version

1.5.1

### Describe

In title

**Operating System**: Manjaro ARM (aarch64)

### To Reproduce

1. Find a bookshelf (church/catacombs)
2. Step on its tile
3. Cast spells like Charged Bolt, Elemental, Nova, Bone Spirit and Blood Star
4. The spell doesn't affect the surroundings of the tile

### Expected Behavior

Spells shouldn't hit an invisible wall

### Additional context

**Screenshot**

![Screenshot from 2023-10-07 18-28-05](https://github.com/diasurgical/devilutionX/assets/3542623/e1a4bc5d-ccbb-4d6d-b09a-ed88996a0d51)

**Comment by ephphatha** [comment]
There are two different types of bookshelf depending on whether they're part of a theme room or not. Both collide with missiles, but the non-theme room bookshelves are solid so you can't stand on them. The spell missile is colliding with the bookshelf as soon as it spawns.
