### ISSUE TITLE
[Issue Report]: Bone Spirit and Blood Star is reducing health without Mana Shield

### ISSUE THREAD

**Issue by myself600** [diasurgical/devilutionX#6692]
### Operating System

Other (please specify)

### DevilutionX version

1.5.1

### Describe

In title

**Operating System**: Manjaro ARM (aarch64)

### To Reproduce

In title

### Expected Behavior

Health bar should not be affected

### Additional context

**Screenshots**

Before casting the spell

![Screenshot from 2023-10-07 18-45-45](https://github.com/diasurgical/devilutionX/assets/3542623/27e7d38d-cb31-477a-8295-85b68a5ce2db)

After casting it

![Screenshot from 2023-10-07 18-45-49](https://github.com/diasurgical/devilutionX/assets/3542623/0fec25c8-f0b8-442e-b838-ab17c349fa87)

**Comment by qndel** [comment]
In my opinion working as intended

**Comment by myself600** [comment]
A quick search on the wiki says that this is to be expected. Closing.
