### ISSUE TITLE
[Issue Report]: Two small regressions with revised automap

### ISSUE THREAD

**Issue by FitzRoyX** [diasurgical/devilutionX#6694]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Lines that make up some corners reveal as pillars before turning into lines when you get closer.

https://github.com/diasurgical/devilutionX/assets/57089001/3cba62e1-1044-49be-bfde-b511f7152e50

In Lazarus chamber, two doors that are close to each other fail to draw a complete line between them

https://github.com/diasurgical/devilutionX/assets/57089001/82de37ef-e322-4229-a66f-489adec44c96

### To Reproduce

nm

**Comment by qndel** [comment]
First issue easiest to reproduce in poisoned water supply

**Comment by qndel** [comment]
I'll add a 3rd issue with automap here:
![image](https://github.com/diasurgical/devilutionX/assets/14297035/6ace8c21-672c-4bc1-8a06-cafd61d6e817)
