### ISSUE TITLE
Build issue from git

### ISSUE THREAD

**Issue by nigelsollars** [diasurgical/devilutionX#671]
**Describe**
Attempting a build after pull request,

[ 98%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/tcp_server.cpp.o
make[2]: *** No rule to make target '/usr/lib64/libSDL2main.a', needed by 'devilutionx'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/udp_p2p.cpp.o
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/devilutionx.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Have built the latest git many times..

**To Reproduce**

Regular cmake build steps

**Expected behavior**
Completed build with no errors

**Screenshots**

**Additional context**

Only question might be, perhaps I need to do a fresh clone?.

**Comment by AJenbo** [comment]
What system are you on? It looks like you removed the SDL developer pacages since running CMake the first time.

**Comment by nigelsollars** [comment]
Currently FedoraCore I made sure that SDL2 and SDL2 devel was there and that are which is why I found this confusing.

Currently installed,

[root@localhost ~]# rpm -qa | grep SDL2
SDL2-2.0.12-1.fc31.x86_64
SDL2_image-devel-2.0.5-2.fc31.x86_64
SDL2_ttf-2.0.15-2.fc30.x86_64
SDL2_image-2.0.5-2.fc31.x86_64
SDL2_ttf-devel-2.0.15-2.fc30.x86_64
SDL2_mixer-devel-2.0.4-4.fc31.x86_64
SDL2_mixer-2.0.4-4.fc31.x86_64
SDL2-devel-2.0.12-1.fc31.x86_64

Perhaps I am missing something obvious

**Comment by AJenbo** [comment]
I see you have upgraded to the recent 2.0.12, maybe there is an issue with locating it. Or maybe you simply need to rerun CMake, try clearing your build folder also.

**Comment by nigelsollars** [comment]
Unfortunatly same result here is what the cmake .. shows,

-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found sodium: /usr/lib64/libsodium.so (found version "1.0.18") 
-- Found SDL2_ttf: /usr/lib64/libSDL2_ttf.so  
-- Found SDL2: /usr/lib64/libSDL2.so  
-- Found SDL2_mixer: /usr/lib64/libSDL2_mixer.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nsollars/tmp/devilutionX/build

cmake-gui seems to be happy with it also,  I did not realize there was an SDL change to be honest.  It would seem likely the b0rkage is caused by this as something has changed

**Comment by namtsui** [comment]
There is a proposed update for SDL2 2.0.12 on OpenBSD that I am testing out with building release 1.0.1. OpenBSD currently has SDL2 2.0.10, which works. SDL 2.0.12 returns a similar error as the OP:

```
[ 98%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/tcp_server.cpp.o
/usr/ports/pobj/devilutionx-1.0.1/bin/c++  -DASIO_STANDALONE -DSODIUM_STATIC -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -I/usr/ports/pobj/devilutionx-1.0.1/devilutionX-1.0.1/SourceX -I/usr/ports/pobj/devilutionx-1.0.1/devilutionX-1.0.1/3rdPar
2 warnings generated.
gmake[2]: *** No rule to make target '/usr/local/lib/libSDL2.so', needed by 'devilutionx'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/udp_p2p.cpp.o
```
Full build log: https://gist.github.com/namtsui/c1272e91fc4fe60a3db911e2cf81a31b

**Comment by AJenbo** [comment]
Mac OSX is also affected by this issue in SDL 2.0.12. Closing as it´s not DevilutionX related.

**Comment by namtsui** [comment]
Yes, this is a problem with SDL2. Diablo now builds once I used an updated proposed diff reverting an SDL2 commit. FYI:
https://marc.info/?l=openbsd-ports&m=158527856531418&w=2
