### ISSUE TITLE
[Issue Report]: Leoric seems to be invincible in multiplayer.

### ISSUE THREAD

**Issue by undyamon** [diasurgical/devilutionX#6722]
### Operating System

Linux x64

### DevilutionX version

1.4.1

### Describe

On a 2-player multiplayer Diablo game (NixOs Linux x64 and Windows 11 x64) at around character level 8 (rogue + barbarian) Leoric (as Skeleton King on the 3rd level) doesn't seem to take any damage ever.
This doesn't seem to be related to his lifesteal. 

### To Reproduce

1. Setup a 2-player multiplayer game
2. Reach 3rd level
3. Try to damage Skeleton King (which is found roaming in multiplayer)

### Expected Behavior

Should be able to damage Leoric

### Additional context

I'll try updating to latest version but in NixOS the process is a bit more involved.

**Comment by AJenbo** [comment]
1: upgrade to 1.5.1
2: He has life steal, if you are not strong enough to keep up with how much life he drains from you, you won't be able to defeat him.

**Comment by undyamon** [comment]
Maybe it is just that. I'll try again and report back if this is not the case. Thanks :smile:

**Comment by StephenCWills** [comment]
@undyamon Per qndel's comment, can you turn on the monster HP bar when you do try again? It would make it more obvious if it's due to lifesteal.

**Comment by undyamon** [comment]
> @undyamon Per qndel's comment, can you turn on the monster HP bar when you do try again? It would make it more obvious if it's due to lifesteal.

This I can answer immediately. We have HP turned on and it stays full and red.



> if the packagemanger does not have the latest version then grab it from the release section. Either a raw linux one or the AppImage. You can also try a FlatHub installation as an alternative.

NixOS does not work like a normal linux distribution (does not provide the same filesystem structure one would expect) so running precompiled executable even AppImages is a little more involved. I'll try as soon as I find the time :)

**Comment by AJenbo** [comment]
> This I can answer immediately. We have the monster HP bar turned on and it stays full and red.

True, but you are on 1.4.1 so it's a bit i relevant since I think that was added in 1.5.0...

**Comment by undyamon** [comment]
Gotcha, I'll update to the latest version and report back. Thanks
