### ISSUE TITLE
Cant resize window after toggeling full screen

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#673]
When switching from full screen to window mod with alt+enter it's not possible to resize the window even when upscaling is enabled.

**Comment by arrowgent** [comment]
is that because the resolution of the window is 640x480
is it a SDL issue?

**Comment by AJenbo** [comment]
No, it is simply because we do not set the SDL_WINDOW_RESIZABLE when starting the game in fullscreen mode:
https://github.com/diasurgical/devilutionX/blob/master/SourceX/display.cpp#L83

Should be simple to fix.

**Comment by yuripourre** [comment]
@AJenbo in this case, it would solve it?
```
	if (fullscreen) {
		flag |= SDL_WINDOW_FULLSCREEN_DESKTOP;
	}
	flags |= SDL_WINDOW_RESIZABLE;
```

**Comment by AJenbo** [comment]
Feel free to send a PR

**Comment by yuripourre** [comment]
https://github.com/diasurgical/devilutionX/pull/676

**Comment by arrowgent** [comment]
tested this fix with my latest build
working great
