### ISSUE TITLE
[Feature Request]: expand the game engine 

### ISSUE THREAD

**Issue by actraiser30** [diasurgical/devilutionX#6733]
### Feature Type

Quality of Life

### Describe

Hello there,will you expand the game engine to support also diablo 2 ???

Thanks

**Comment by qndel** [comment]
We planned to include sonic the hedgehog first
![image](https://github.com/diasurgical/devilutionX/assets/14297035/182b9786-485a-4252-b863-c0e6e76923cd)

**Comment by AJenbo** [comment]
the games are not related at all on a technical level

**Comment by actraiser30** [comment]
The graphics looks Almost
the same that's why i ask

**Comment by AJenbo** [comment]
It's an old engine, it is not very flexible and very tailor made to how Diablo 1 plays. We are adding mod support, but there are many things that just do not work how Diablo 2 does. Like for example movement. Adding Diablo 2 support is not realistic. Even if you added support for Diablo 2 graphics you would just have Diablo 1 with Diablo 2 graphics and not Diablo 2.
