### ISSUE TITLE
Townsfolk (and cows) disappearing

### ISSUE THREAD

**Issue by CWBHV** [diasurgical/devilutionX#674]
**Describe**
Townsfolk disappear randomly, mostly Pepin and Farnham. After saving and reloading they reappear or not. Interaction works fine, they are just invisible.
It really seems to be completely random, if you have any ideas how to collect useful information please tell me.

**To Reproduce**
1. Start
2. Play

**Expected behavior**
Every NPC in town should be visible.

**Screenshots**
![devilutionX_missing](https://user-images.githubusercontent.com/62724322/77699161-2858ee00-6fb2-11ea-8fc3-ac7cbd7faad7.png)

**Additional context**

**Comment by galaxyhaxz** [comment]
Pepin gets quite tired of giving out free healing. He's been doing it for over 20 years and has got to the point where sometimes he just decides to disappear.

**Comment by AJenbo** [comment]
What system are you using, what build are you running, does it happen as you enter an leave the town or only when saving and reloading?

**Comment by CWBHV** [comment]
Yes, of course. Sorry about that, I don't do bug reports very often.

Linux, Debian 10 64 bit
deviluionX 1.0.1, compiled from source

Dis- or reappearances can happen every time I enter town, either after reloading or when returning from the dungeons. But, as I said, it seems to be random, sometimes it happens, sometimes not.

**Comment by galaxyhaxz** [comment]
> it seems to be random, sometimes it happens, sometimes not.

On a serious note, I had almost the same issue two years ago when devilution wasnt quite working. The issue was the global array `AnimOrder` would reach the last frame and crash or cause the towner to disappear. Given how the order is variable length, it appeared to be "random". Not sure if it's the same issue here, but might be worth checking `ProcessTowners` in a debugger.

**Comment by MaxDesiatov** [comment]
I have this same issue reproduced in my [iOS build](https://github.com/MaxDesiatov/devilutionX/tree/iOS-arm64), which is quite an old fork though, made off `master` about 3 months ago.

**Comment by AJenbo** [comment]
I seem to remember this being fixed upstream previously.

**Comment by qndel** [comment]
@AJenbo I also had this problem, I thought it was related to my pixel light but it doesn't seem so, npc would be invisible after I loaded the game and reappeared when I reloaded (windows)

**Comment by AJenbo** [comment]
I'm guessing we are dealing with an OOB issue if it can't be consistently replicated :/

**Comment by arrowgent** [comment]
ubuntu 18.04
compiled devilutionx 1.0.1 + qol

been playing multiplayer through a Raspberrypi4b

never seen this issue

**Comment by MaxDesiatov** [comment]
If this was a true OOB I guess it would crash on ARM platforms like RPi and iOS.

**Comment by glebm** [comment]
Only unaligned OOB crash on ARM, and only on ARM<v7

**Comment by AJenbo** [comment]
@CWBHV do see this in both release and debug builds or only debug builds?

**Comment by CWBHV** [comment]
It is in both builds, just checked with debug build (screenshot above is from release build).

**Comment by CWBHV** [comment]
Fun fact: Cows are also disappearing, apparently all at once (...maybe you expected this from the code, it's still funny :smile: ).
![invisible cow](https://user-images.githubusercontent.com/62724322/78076295-700eb980-73a6-11ea-8240-996f9b8d3dfc.jpg)

**Comment by AJenbo** [comment]
Hmm, that makes me think that it's probably something like what @galaxyhaxz mentioned.

**Comment by qndel** [comment]
@AJenbo didn't we figure this out?

**Comment by AJenbo** [comment]
Yeah, but i'm not sure i applied the fix yet

**Comment by CWBHV** [comment]
Good news anyway

**Comment by AJenbo** [comment]
This was indeed fixed already: https://github.com/diasurgical/devilutionX/commit/2104bf2af2d96c44203959a10193d7653df9cccc
