### ISSUE TITLE
Xbox: nxdk does not support hypot()

### ISSUE THREAD

**Issue by Toddimyre** [diasurgical/devilutionX#6746]
### Operating System

Other (please specify)

### DevilutionX version

1.5.1

### Describe

OS: Xbox

I came across a hard crash upon entering floor / level 1 and attempting to open a sarcophagus. I grabbed a screenshot of the crash with its error info. It can be viewed here:

![image](https://github.com/diasurgical/devilutionX/assets/14297035/166d7516-8bb6-4a04-ae6c-1780795614f7)

### To Reproduce

I'm not sure if it can be reproduced easily, as I turned off the Xbox for the evening. But, I did the following:

1. Selected my warrior.
2. Sold the starting club.
3. Accepted the butcher quest.
4. Entered the cathedral.
5. Walked southwest a bit.
6. Attempted to open a sarcophagus as a fallen one got close enough to pop the health bar.

### Expected Behavior

I had hoped some awesome goodies would've appeared from the sarcophagus.

**Comment by AJenbo** [comment]
The issue here appears to be that nxdk does not actually implement this function:
https://github.com/XboxDev/nxdk-pdclib/blob/nxdk/platform/xbox/functions/math/hypot.c

The issue so should be reported with them, but they are probably also aware of the defect. I have created a PR for them to consider, so hopefully this can be solved in a not to fare in to the future version of nxdk.

**Comment by qndel** [comment]
@Toddimyre why would you upload the pic on some 3rd party website instead of on github directly?

**Comment by JayFoxRox** [comment]
> but they are probably also aware of the defect

The maintainers are aware that the nxdk libc is rather incomplete in general 😛 

However, at least I wasn't aware that this function even existed in the C standard, so I didn't even know it was a low-hanging fruit (I always implemented this myself, despite `hypot` leaving more room for compiler optimizations.. probably).

Thanks for reporting and sending the PR 👍

**Comment by AJenbo** [comment]
@glebm do you know if we are building nxdk in debug mode since we have asserts like this?

**Comment by glebm** [comment]
@AJenbo Don't know but here is how we're building it:

https://github.com/diasurgical/devilutionX/blob/8b141d927b3a5a695874791276d170235ebd73e4/.github/workflows/xbox_nxdk.yml#L41

**Comment by glebm** [comment]
@AJenbo Yes we are!
https://github.com/XboxDev/nxdk/blob/ed21e83da43b8b8da14a9a78cf2528d9b5df86a7/.github/workflows/build_docker_image.yml#L14-L23

**Comment by glebm** [comment]
Fixed in https://github.com/diasurgical/devilutionX/pull/6761 by avoiding `hypot`

**Comment by Toddimyre** [comment]
> @Toddimyre why would you upload the pic on some 3rd party website instead of on github directly?

My apologies for the delay. But to answer your question, I don't use GitHub very often, so I was unaware that was even and option. And I used Google Photos as the upload location because my device automatically uploads photos there anyway. It was quick and painless to create a link.

**Comment by glebm** [comment]
Version 1.5.2 is now out with a fix for this issue!
