### ISSUE TITLE
dungeon items - cant pickup and disappear (Linux & Multiplayer)

### ISSUE THREAD

**Issue by arrowgent** [diasurgical/devilutionX#675]
**Describe**
in multiplyer:
occasionally i will find a potion, or a book laying on the ground
Hover mouse over item and it seems like a legit item
character walks over to item to pick it up
nothing happens.
click several times and item remains on ground.
then item disappears, not in inventory

**To Reproduce**
1. multiplayer dungeon
2. item on ground
3. click on item
4. item disappears

**Expected behavior**
item should attempt to go into inventory

**Screenshots**
i have video, i will get back to this with clips
1st or 2nd glitch:
potion/book
2nd or 3rd glitch: short sword
https://clips.twitch.tv/PiercingTolerantWatermelonRedCoat
3nd or 4rd glitch: book of healing
https://clips.twitch.tv/FilthyBenevolentPelicanChefFrank

**Additional context**
compiled linux ubuntu 18.04 client devilutionx 1.0.1 + qol patches
downloaded binary linux raspberrypi4b host devilutionx 1.0.1

diabdat.mpq is based on original RETAIL CD (not gog release)
12-26-1996

similar report:
https://github.com/diasurgical/devilutionX/issues/171
but not exactly the same

**Comment by qndel** [comment]
I believe this is a vanilla bug

**Comment by Chance4us** [comment]
This is definitely a vanilla bug experienced very often.

**Comment by arrowgent** [comment]
yeah i remember it was vanilla, that was 20-25 years ago! lol
atleast adding it so maybe it can be fixed someday

gg
