### ISSUE TITLE
What is the correct directory to put the game assets to test the WiiU and PSP distributions?

### ISSUE THREAD

**Issue by wikiblog0** [diasurgical/devilutionX#6794]
Hello everyone

I have been reading the forums and I saw that you have created the executable files for WiiU and PSP, however I have not seen anywhere the instructions, especially for the Wii U port.

I would like to know what is the correct directory to put the game assets for both Diablo and the Hellfire Expansion on Wii U and PSP?

On the PSP Support forum user stefanmielke wrote that he put the PSP version files like this: 

- PSP/GAME/DevilutionX/devilutionx.mpq (grabbed from the Linux Build)
- PSP/GAME/DevilutionX/DIABDAT.MPQ
- PSP/GAME/DevilutionX/EBOOT.PBP

1) Is it necessary to have the devilutionx.mpq file to launch devilutionx on PSP or is it enough just to have DIABDAT.MPQ? 

2) The directory stefanmielke used is the correct one? 

3) And if so, could I put the Hellfire files there too or would it have to be another directory?

I will be very grateful for any help you can give me, I really want to test the game on these two platforms (as I saw that the PSP one doesn't run on the console so I would like to test it on PPSSPP).

Greetings.

**Comment by qndel** [comment]
3. hellfire files are being read from the same place as diabdat.mpq

**Comment by AJenbo** [comment]
What forums? I'm missing a bit of context here.

Both the PSP and Wii U ports are incomplete as we are missing someone with hardware that is able to debug the issues with them.

You can find the current state here:
PSP: https://github.com/diasurgical/devilutionX/pull/5869
Wii U: https://github.com/diasurgical/devilutionX/pull/5944

There isn't much point in testing them in there current form. Someone needs to debug the current known issues so we can find a solution and finish the ports.

I'm going to close this issue as it's more of a support question.
