### ISSUE TITLE
Lightning sounds echo oddly

### ISSUE THREAD

**Issue by CubeTheThird** [diasurgical/devilutionX#68]
I found this particularly noticeable in the caves, but when casting lightning spells, the sound effect seems to echo inconsistently, sometimes sounding jittery.

**Comment by AJenbo** [comment]
Any chance you could record this?

**Comment by CubeTheThird** [comment]
Following is a clip (had to zip to attach):

[2019-03-27 22-18-48.zip](https://github.com/diasurgical/devilutionX/files/3015961/2019-03-27.22-18-48.zip)

**Comment by AJenbo** [comment]
I don't have the best of audio setups here, but he original appears to have a similar echo:
https://www.youtube.com/watch?v=kUG9Lj8Btco

**Comment by CubeTheThird** [comment]
I've uploaded a couple samples to youtube. First is the [Original Diablo](https://youtu.be/mNoaa6XuBCY) on Windows (no video with it). Second is [Diablo/DevilutionX](https://youtu.be/wq-BCCK3_rE) on Linux. For some reason the volume on the latter is about 30% higher, but I find the echo there is much more choppy. I'm starting to wonder if it's just my imagination though.

**Comment by AJenbo** [comment]
Har to tell, the volume definitly seams higher on the DevilutionX video for what ever reason. It not unthinkable that there are still some scaling issues in relation to the implementationthat of spatial sound, even at 100% volume. There are probably also less limitations on simulations sounds then in the original. The original seams to have a limit of either 8 (definatly in some cases) or infinit (depending on the direct sound implementation, not real number is given, but probably it's also 8). Here DevilutionX has a limit of 24 sounds (adjustable via ini). I will try to dig a bit deeper in to this once I get to work on the volume scaling. Thanks for reporting and uploading the samples.

**Comment by AJenbo** [comment]
@CubeTheThird Could you please build the latest code from source and see if the issue is still pressent?

**Comment by CubeTheThird** [comment]
It would seem the situation is much improved. The volume level appears to be normalized, and the weird echo is no longer happening.
That being said, I'm finding there a sort of delayed echo that's sometimes happening. I will need to test though to make sure it isn't present on the original version.

**Comment by CubeTheThird** [comment]
I was unable to recreate the new version in the original Diablo. A recording of the problem can be seen [here](https://youtu.be/iqe04oEzKH4).
In short, there is a delayed echo that is now happening, which also doesn't appear to follow the stereo positioning properly.

**Comment by AJenbo** [comment]
Unfortunately the audio quality is very different from the different recordings and the conditions aren't identical making it very hard to tell what the difference is if any.

**Comment by AJenbo** [comment]
It could also be directly related to https://github.com/diasurgical/devilutionX/issues/252

**Comment by CubeTheThird** [comment]
Now that I've got my save file working, I can confirm that these issues are no longer present in release version 0.4.0

**Comment by AJenbo** [comment]
Cool thanks 😊
