### ISSUE TITLE
[Issue Report]: --help no longer working

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#6812]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Using [e350d9b](https://github.com/diasurgical/devilutionX/commit/e350d9be066d8aa20a51d280b6bcd481eed002d5) I can no longer print the --help screen from the terminal. This worked for 1.5.1 :shrug: 

### To Reproduce

1. `./devilutionx --help`
2. Watch in confusion as the game starts normally

**Comment by glebm** [comment]
:thinking: 
![image](https://github.com/diasurgical/devilutionX/assets/216339/95343ae1-a415-4548-8639-b6bb45b39ac9)

**Comment by AJenbo** [comment]
Confirmed ...
