### ISSUE TITLE
[Feature Request]: Keep playing after killing Diablo

### ISSUE THREAD

**Issue by raburton** [diasurgical/devilutionX#6813]
### Feature Type

Quality of Life

### Describe

Would it be possible to add an option to allow play to continue after killing Diablo? The ending is a bit jarring, and leaves stuff to kill and pickup.

Looks like it would probably be fairly easy implement, by making most of the content of PrepDoEnding conditional on the option (except the part where the kill level is saved). Might need to add a check in the caller too, as you probably don't want to force the view to shift if you're still being attacked by other things. I was going to have a go myself, but couldn't get it to build under Visual studio easily.

**Comment by DakkJaniels** [comment]
The problem isn't allowing play after Diablo is killed, it's allowing it in a way that doesn't look like garbage and also meshes with people who do not have this feature enabled in a multiplayer game.

**Comment by StephenCWills** [comment]
There are implications in Multiplayer that make it quite a bit harder than it seems, but yes. I think it should be possible and would like to see this implemented at some point.

**Comment by AJenbo** [comment]
> The ending ... leaves stuff to kill

killing Diablo kills all monsters, unless you are refering to other levels that you skipped

**Comment by raburton** [comment]
> and also meshes with people who do not have this feature enabled in a multiplayer game.

Yes, agreed that would be a bit more complicated. Maybe more logical to be a single player only option.

> > The ending ... leaves stuff to kill
> 
> killing Diablo kills all monsters, unless you are refering to other levels that you skipped

I hadn't noticed that, as I always try and separate him off and kill him without a crowd. And I didn't spot the code that killed everything else when I was looking at this. If allowing continued play, I think better to not kill everyone else. But yes there might be other monsters/stuff in the rest of the dungeons or even in town, that you want to clear up.

**Comment by AJenbo** [comment]
Net people will aske for a new ending where the hero doesn't plunge the stone in there own heads :D

**Comment by AJenbo** [comment]
> Yes, agreed that would be a bit more complicated. Maybe more logical to be a single player only option.

It actually makes more sens in multiplayer as you could have lost items from the town as there is no save and the game just ended. Though you can actually get around this if one layer is in town when diablo dies then the games stays open and you can rejoin the session. Entering level 16 will then end the game.

**Comment by StephenCWills** [comment]
> Entering level 16 will then end the game.

I don't think it does, otherwise the PvP players would have to leave Diablo alive.

**Comment by malvarenga123** [comment]
Isn't Diablo 2's solution viable in this case? Just open a portal that will trigger the ending if the player enters it.

**Comment by AJenbo** [comment]
And just have Diablo stand there and bleed for ever? He has no death animation.

**Comment by AJenbo** [comment]
This is better left for a mod
