### ISSUE TITLE
[Feature Request]: Setting to remove Search spell from item drops

### ISSUE THREAD

**Issue by tunbridgep** [diasurgical/devilutionX#6827]
### Feature Type

Quality of Life

### Describe

Currently, with the "show item labels" setting turned on, Search is largely useless as a skill. This makes it annoying when it drops from bookshelves or other sources of magic books.

Perhaps a "no search spell" setting could be added to prevent it from ever being dropped, so that more useful spell books can take it's place.

In an ideal world, I'd also want to replace the Monk's innate Search skill, but that's too much of a gameplay change.

**Comment by AJenbo** [comment]
It's part of hellfire, altering it is out of scope, and would cause item morphing.
In the next version it will be very simple for yourself to make a mod like this as you can edit the item table as a text file.

**Comment by tunbridgep** [comment]
It being part of the old game isn't really relevant considering it's a devilutionx feature that has made it obsolete. If this project is going to obsolete parts of the old game (which is reasonable given it needs some QOL updates and Search was a terrible way to fix the issue of items being hard to find in the original game), it also makes sense to allow the old way of doing things to be subverted.

But I can wait for the text file method.

**Comment by DakkJaniels** [comment]
It is relevant that it will cause item morphing however.

**Comment by AJenbo** [comment]
@tunbridgep apologies if it seemed like I brushed off your suggestion. I did read and thought about it before closing, which is what I tried to express in my reply. We might not see eye to eye on the specifics, but if it's any consultation option to change this is already available in the latest test builds.

@julealgon feel free to integrate this into [DiabloCore](https://github.com/julealgon/DiabloCore/blob/master/Source/itemdat.cpp#L107C34-L107C161) if you think it's a solid idea.

**Comment by tunbridgep** [comment]
Would this actually cause item morphing?

If it's already dropped/already exists in the world, why not just leave it as normal?

The only time when it's really annoying is when you are expecting something worthwhile from a bookshelf and you get Search instead.

I'm not suggesting removing the item/spell at all, simply making it not drop.

**Comment by StephenCWills** [comment]
> I'm not suggesting removing the item/spell at all, simply making it not drop.

It's less annoying if the bookcase drops nothing than if it drops Book of Search?

**Comment by tunbridgep** [comment]
The idea is that it would instead drop something else

**Comment by StephenCWills** [comment]
If you prevent Book of Search from being generated, you will indeed cause items to morph. The text file method won't be able to do what you want without morphing items. If you want to avoid morphing items, you need to add some logic to the client to detect the Book of Search drop and generate a whole new item to replace it. I doubt that will be possible without modifying the engine.

**Comment by AJenbo** [comment]
> Would this actually cause item morphing?

Yes that is why I mentioned it. Since you don't know the minutia of how item generation works I don't think getting in to an argument about this is productive. If you need help modding I suggest joining the Discord chat or posting in [Discussions](https://github.com/diasurgical/devilutionX/discussions)
