### ISSUE TITLE
[Issue Report]: Not getting any new unique items after starting a new game (same character, different difficulty level)

### ISSUE THREAD

**Issue by bocak** [diasurgical/devilutionX#6828]
### Operating System

Mac

### DevilutionX version

1.5.1

### Describe

I've played sorcerer in normal difficulty until clvl 29, then started a new game in nightmare (with same character and stash containing all my uniques). I'm not getting any uniques (even from unique enemies like the butcher or the skeleton king), just magical items instead. Doesn't happen if I start a new game in normal difficulty (I get new unique items, and I can get a second butcher's cleaver even though I have it in my stash from the previous game).

### To Reproduce

1. Get a unique item in normal difficulty
2. Start a new game in a different difficulty level
3. No unique items generated

**Comment by StephenCWills** [comment]
This is expected behavior. Quests drop random magic items instead of their usual quest rewards in Nightmare and Hell difficulty. There is still a chance they could be unique items, but it will be random.

**Comment by bocak** [comment]
Oh ok, my bad... It's just after two runs of Nightmare and not getting any unique, I thought there was a bug. I guess it's just very low probabilities.
