### ISSUE TITLE
[Issue Report]: Fireball hurts other players even with friendly fire disabled

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6853]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

This is either a bug, or if it's intentional, I'm asking for the ability to toggle this off as a feature.

### To Reproduce

Cast fireball on other player.
If friendly fire is disabled, he still takes damage.

### Expected Behavior

Not hurting allies.

**Comment by DakkJaniels** [comment]
You turned it off in Settings or in game?

**Comment by AJenbo** [comment]
it sounds like you might have just been toggling hostile mode in game, and didn't change the game play settings before starting a game. let us know if that isnt the case and we can re open the issue

**Comment by Chonkblonk** [comment]
It turns out, the setting was on in the options, but I could have sworn I toggled it off. Mystery solved I guess.
I did experience a crash at some point, and some programs don't save changed settings when that happens.
