### ISSUE TITLE
[Feature Request]: Option to use scroll wheel to cycle through quick spells

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6858]
### Feature Type

Quality of Life

### Describe

Like it says, if I could use the scroll wheel to cycle through the spells I had tagged for quick spells.
I never have any utility for using the scroll wheel for the automap, so I'm perfectly good with exchanging that away if that would be necessary.

**Comment by StephenCWills** [comment]
If anyone implements this, make sure you don't break scrolling in shops or paging in stash.

**Comment by julealgon** [comment]
What order would the spells cycle through though on scroll up and down? Aren't hotkeys completely custom and arbitrary?

**Comment by DakkJaniels** [comment]
I would assume the order the hotkeys are listed in the configuration: 
![image](https://github.com/diasurgical/devilutionX/assets/6080734/775fedf6-a4a9-46f6-b898-17cfae632229)

**Comment by julealgon** [comment]
Hmm... fair @DakkJaniels , thanks for clarifying that.

**Comment by Chonkblonk** [comment]
Ooh, that's cool, so this will be an added feature when the next version is released?

**Comment by AJenbo** [comment]
Correct, it's already in the test builds

**Comment by Chonkblonk** [comment]
Awesome. Say, while you're here, I have two questions.
1. Where does DevilutionX store taken screenshots?
2. I've spotted one or two dungeon generation errors, if I get screenshots of them, are they any kind of useful input for any kind of debugging?
3. There's a very minor graphical glitch with Hellfire by the Alien Nest, is this something that'd be addressed at some point, or do you prefer to keep the Town unchanged?

**Comment by AJenbo** [comment]
1: Same place as save games/config/mpq: https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide
2: Not without a save game or an screen shot of what you get when entering `/seedinfo` in chat.
3: Depends on how big the minor issue is?

**Comment by julealgon** [comment]
> 3. There's a very minor graphical glitch with Hellfire by the Alien Nest, is this something that'd be addressed at some point, or do you prefer to keep the Town unchanged?

@Chonkblonk do you see an issue in the repository that describes the problem you are seeing? If not, please consider creating one.
