### ISSUE TITLE
[Issue Report]: Tiny graphical glitch in Town by Alien Nest (Hellfire)

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6869]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

Low priority. Probably a slip-up from way back when Synergistic did Hellfire.
![hellfireblemish](https://github.com/diasurgical/devilutionX/assets/114463804/26abbe0e-014e-4994-9c8f-a2a5d0898bfc)

I don't know if this would be bothersome to fix and would require like editing of the town. Maybe a crude fix could be done by just making a custom graphic to cover the erroneous tiles.

### To Reproduce

Open in Hellfire and then look across the river.

**Comment by AJenbo** [comment]
Looks like mega tile 19,7 and 20,7 just have to be patched with some grass. This is already the way the next is added to the town so not much difference.

**Comment by julealgon** [comment]
Is this a vanilla Hellfire issue?

**Comment by StephenCWills** [comment]
Screenshot from Hellfire v1.00a.

![image](https://github.com/diasurgical/devilutionX/assets/9203145/11627009-9ee6-4248-871c-f2da859ea5ae)
