### ISSUE TITLE
[Issue Report]: possible big endian problem

### ISSUE THREAD

**Issue by DarthChillash** [diasurgical/devilutionX#6871]
### Operating System

Other (please specify)

### DevilutionX version

1.5.1

### Describe

On Amiga OS the character in background looks like he was chopped to stripes and laid back on screen in reverse order of those stripes.

https://github.com/diasurgical/devilutionX/assets/1872435/d8c1e9eb-4ef9-4f0b-b5a8-7c2da79c57e5

### To Reproduce

Talk to any NPC and start the gossip or whatever conversation. Once the text starts rolling the background will be distorted as seen on the video above.

### Expected Behavior

NPC in the background should not look broken like he died in a "cube" horror movie.

**Comment by julealgon** [comment]
Love the new glass effect!
