### ISSUE TITLE
[Issue Report]: AppImage menu to switch between diablo and hellfire no longer shows up

### ISSUE THREAD

**Issue by lozenge57** [diasurgical/devilutionX#6883]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

The first time I ran the appimage image with the hellfire mpq's it showed a menu to select which game I wanted to play. Now, it forces me into hellfire every time. I've removed the appimage, redownloaded, and added it back to the folder but still no menu shows up to select.

### To Reproduce

Unknown how to reproduce. I simply added the app image and mpq files and on starting the appimage it showed the selection menu. Now it doesn't

### Expected Behavior

Shows hellfire or diablo selection menu every time you start appimage

**Comment by AJenbo** [comment]
If you want to reset the app you have to delete the config. But it's not forcing you though, you can just switch it under settings -> startup, or with the run time arguments.

**Comment by lozenge57** [comment]
thanks this clears everything up!
