### ISSUE TITLE
[Feature Request]: Griswold's Inventory (Multiplayer?)

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6885]
### Feature Type

Quality of Life

### Describe

In multiplayer, Griswold's inventory will never, ever reset. I saw someone suggest giving the player the ability to manually refresh it, which you rejected. Fair enough.

I think that maybe giving the player an unlimited ability to refresh his inventory on the spot would be a bit much, but would it be possible to give the player the option to have him do the single player behavior where it resets every time you come back into town? Potentially add a cooldown timer to that behavior so that you need to spend some time in the dungeon to let it happen.

Slightly related, but did Griswold not use to sell Rings and Amulets as premium items? Is this something Hellfire changed, if so, could this ever be considered as a toggleable option for Hellfire, if my assumption is correct?

**Comment by AJenbo** [comment]
> In multiplayer, Griswold's inventory will never, ever reset.

Did you try leveling up or starting a new game?

> would it be possible to give the player the option to have him do the single player behavior where it resets every time you come back into town? 

I'm pretty sure that isn't how it works

> Slightly related, but did Griswold not use to sell Rings and Amulets as premium items?

Only in single player

**Comment by Chonkblonk** [comment]
> Did you try leveling up or starting a new game?
New game works, levelling up does not.
 
> I'm pretty sure that isn't how it works
Been a long time since I played original unmodified Diablo 1, so maybe my memory is hazy.
 
> Only in single player
I actually did not know that was the case.

**Comment by StephenCWills** [comment]
Griswold's basic items refresh every time you visit the dungeon. Griswold's premium items are updated when you level up or buy an item. Nothing refreshes his premium items except starting a new game or buying all his items. This is the case in both Single Player and Multiplayer.

**Comment by Chonkblonk** [comment]
Alright.
Any willingness for an option for Griswold to offer Rings and Amulets in multiplayer? Considering single player quests and Hellfire support is added to multiplayer I mean.

**Comment by StephenCWills** [comment]
> Any willingness for an option for Griswold to offer Rings and Amulets in multiplayer? Considering single player quests and Hellfire support is added to multiplayer I mean.

Unfortunately, that would cause items to morph, breaking backwards compatibility. So I'd say that's a pretty solid no.

**Comment by Chonkblonk** [comment]
Oh, would that require altering item generation as a whole? That's interesting.
Uh, anyway, I hope I didn't come off as belligerent or needy, this is a super cool project.

**Comment by StephenCWills** [comment]
> Oh, would that require altering item generation as a whole?

Not as a whole. You would have to add rings and amulets back to Griswold's base item pool, which increases the size of the pool. You only have to understand modular arithmetic.. and maybe a little bit about how it's used in RNG, to understand why that would cause items to morph.

**Comment by Chonkblonk** [comment]
> You only have to understand modular arithmetic

No hope for me then, lol! Anyway, thanks for the answers and insight.

**Comment by AJenbo** [comment]
Just imagine a very long list of items and all your hero knows is what number in the list the rng gave them. If we then add new items in random places of the list all the items are going to shift so when your hero goes to pick the item with the assigned number it will be a diffent item then lady time because the list is different.

It's worth noting that it won't just shift things a bit, the list will actually be entirely different, so it's not simply possible to figure out the new position, an identical item might not even exist in the new list of items.

**Comment by Chonkblonk** [comment]
Hey, so I just had a thought, it seems like Griswold would be using a separate list of items to reference from in MP, and that while trying to alter that list would not be useful for base DevX (I assume there's no problem if you wanted to create a mod with no characters carrying over), but could Griswold be made to reference the SP list of items without causing problems?

**Comment by DakkJaniels** [comment]
If you mod the game so multiplayer Griswold follows the same procedure for generating items as single player, sure, I imagine that would be fine.

**Comment by julealgon** [comment]
> Alright. Any willingness for an option for Griswold to offer Rings and Amulets **in multiplayer**? Considering single player quests and Hellfire support is added to multiplayer I mean.

Why specifically multiplayer though?

**Comment by StephenCWills** [comment]
> Why specifically multiplayer though?

Because he already offers rings and amulets in Single Player. For SP you'd need the converse, which is an option to stop offering rings and amulets.
