### ISSUE TITLE
[Issue Report]: Life/mana added at level 50

### ISSUE THREAD

**Issue by dntco43u** [diasurgical/devilutionX#6886]
### Operating System

Windows x64

### DevilutionX version

1.5.1

### Describe

From level 1 to level 49 there is no problem.
However, this is a case where you go from level 49 to level 50.
In vanilla, life and mana do not increase.
In devliutionx life and mana are increased.
Was this intended to fix bugs in the original?
Thanks for reading.

### To Reproduce

1. Prepare a level 49 character with full experience points.
2. Check your life/mana values when you reach level 50.

**Comment by StephenCWills** [comment]
Looks like it was intentional. https://github.com/diasurgical/devilutionX/pull/5782#issuecomment-1424692156
