### ISSUE TITLE
[Feature Request]: Unique Monsters In Hellfire?

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6887]
### Feature Type

Quality of Life

### Describe

Hellfire doesn't feature any uniques of any of its new monsters in its new dungeons, is this something which could be added without wrecking any indexes or introducing problems?
For clarification, I mean like how Warpskull can spawn on level 2 if there are Hiddens there, or how Baron Sludge can spawn on level 8 when there are Mud Demons there.

I know that many of the added monsters in Hellfire are recycled from unused ones from the base game's development, and if I recall right there are even some remnant entries for that stuff (which Hellfire doesn't use), could that be applied somehow?

Or would that be past the scope of DevX?

**Comment by DakkJaniels** [comment]
Sounds like something for a mod

**Comment by Chonkblonk** [comment]
Arguably, but so is the ability to have SP quests in MP (a feature I think is pretty cool).

**Comment by DakkJaniels** [comment]
Making it so content that already exists in the game is available in a different mode of play is not at all equivalent to making up new content all together. What should the stats be for the monsters? What levels should they show up in? That's not for DevilutionX to decide.

**Comment by AJenbo** [comment]
There kind of are some, but they are designated for other levels then the monsters appear so never spawn, also they appear to be inherited from the unused monsters that Hellfire reused so not something hellfire really intended.

In 1.6.0 you can easily create new unique monsters just by editing https://github.com/diasurgical/devilutionX/blob/master/assets/txtdata/monsters/unique_monstdat.tsv so mods like this will be trivial once released. You can even do so now with the beta, but you will have to manually coordinate the changes with who ever you play with. 

Regarding the SP quests comparison, it was clear that at some point it was intended for the quests to be in MP bug there was missing features that caused it to not work correctly which is probably why it was disabled before release.

**Comment by julealgon** [comment]
This could be naturally supported once all monster data/sizes/types are softcoded I think. Ideally, to remove or add a unique monster, you'd only need to edit a .csv or .json file: add a new entry, and the monster would start to show up in the game. The underlying infrastructure to _support_ that would be in DevilutionX, but the _actual_ specific monsters and their names/stats would be in a mod.

**Comment by StephenCWills** [comment]
@julealgon Posting info that AJenbo already posted in an issue that is already closed...?

**Comment by AJenbo** [comment]
Maybe he doesn't like .tsv and think we should switch to .json or .csv :shrug:

**Comment by julealgon** [comment]
> @julealgon Posting info that AJenbo already posted in an issue that is already closed...?

My bad. I actually skipped some posts including Ajenbo's one.
