### ISSUE TITLE
Buttom of item text lables are being cut off for CJK font

### ISSUE THREAD

**Issue by teddy516** [diasurgical/devilutionX#6889]
![屏幕截图 2024-01-10 165440](https://github.com/diasurgical/devilutionX/assets/156179250/7818a2a5-f328-4df1-b12e-1d7fd2492bc4)

The previous version 1.4.1 text display was perfect, but the new version has this problem, I hope it can be fixed, thank you.

**Comment by AJenbo** [comment]
Can you please be more specific about what the error is, maybe show a comparison

**Comment by teddy516** [comment]
![屏幕截图 2024-01-10 205801](https://github.com/diasurgical/devilutionX/assets/156179250/a9d0823e-7719-4e3a-8256-db0a3970dfb2)

Compare text labels for potions on the ground

**Comment by DakkJaniels** [comment]
Are you saying the bottom of the text is getting cut off? Probably would have been helpful if you used the same potions.

**Comment by teddy516** [comment]
![屏幕截图 2024-01-10 211746](https://github.com/diasurgical/devilutionX/assets/156179250/d8720344-fc53-4ee8-b112-ecffb4412189)
![屏幕截图 2024-01-10 212303](https://github.com/diasurgical/devilutionX/assets/156179250/cdae8354-d36b-4fd8-bb57-b8078248572b)

**Comment by teddy516** [comment]
![屏幕截图 2024-01-10 213528](https://github.com/diasurgical/devilutionX/assets/156179250/ec7fd7f3-2b3a-49df-bb07-aa2aa012218b)
In addition, the font size displayed in the status bar at the bottom is not appropriate.

**Comment by AJenbo** [comment]
Please give us an idea of what is expected, most of us do not read cjk, so "not right" is practically impossible for us to fix with out saying exactly what needs to be changed for it to be corrected.

**Comment by teddy516** [comment]
I'm sorry, I'm just an ordinary player, I don't know what the specific reason is, I can't understand why the text will be abnormal when I update the new version, I only hope to restore the normal text display state of 1.4.1, if I know programming, maybe I can find out the difference between the two versions of the font, so I can only ask the professionals here. Maybe it could be done by challenging the font size or changing it to another font?

**Comment by DakkJaniels** [comment]
It's not about the programming. We (or at least I) don't understand what the characters are supposed to look like.

That being said, I think it's more clear in the potion comparison that the bottom of the characters are getting cut off in 1.5.1.

**Comment by AJenbo** [comment]
> Maybe it could be done by resizing the font or changing it to another font?

The CJK font is already the minimal size possible for representing legible CJK letters.

> If you look at the two pictures, you can see in 1.4.1 that the text is going beyond the bottom of the box and still rendering, but in 1.5.1 the text is cut off a pixel or two from the bottom of the box:

Sounds like the box simply needs to be higher when displaying CJK texts

**Comment by AJenbo** [comment]
@teddy516 like Dakk said we do not expect you to tell us what technical changes are needed, but you do need to explain to us what "appropriate" looks like.


> ![屏幕截图 2024-01-10 213528](https://private-user-images.githubusercontent.com/156179250/295583621-ec7fd7f3-2b3a-49df-bb07-aa2aa012218b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MDUzNjIsIm5iZiI6MTcwNDkwNTA2MiwicGF0aCI6Ii8xNTYxNzkyNTAvMjk1NTgzNjIxLWVjN2ZkN2YzLTJiM2EtNDlkZi1iYjA3LWFhMmFhMDEyMjE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxNjQ0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzc4MWFmMmE2OTVjMDQ2OTRhNDI2ZGY3MzFmNmY4ZThkMzI0OWZiNmZlOTVlZmJmNjYwZTNmZWE4YzY0NzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GoHdZwDaFjPVwOqpSh2o5c56REtppkxOKuqAEgTnajg) In addition, the font size displayed in the status bar at the bottom is not appropriate.

I have no idea what isn't appropriate about this, you might as well have shown me The Monalisa and said it wasn't done right by the artist. I don't know if she was actually supposed to look like an old man or there should be snow in the background.

**Comment by teddy516** [comment]
**good**
![屏幕截图 2024-01-11 150508](https://github.com/diasurgical/devilutionX/assets/156179250/e64d9d3a-038a-48df-8bb7-459f965ac2fd)

**bad**
![屏幕截图 2024-01-11 150453](https://github.com/diasurgical/devilutionX/assets/156179250/26c98cc9-8b4e-46bf-8e91-f38705689d53)

**Comment by glebm** [comment]
I've sent a fix for the item labels in #6894 

The info box is a known issue and was like this in 1.4.1 as well (there simply isn't enough space) but I've made it slightly less bad in #6895

**Comment by glebm** [comment]
Item labels are now fixed, info box issue is known and is tracked in https://github.com/diasurgical/devilutionX/issues/3549

**Comment by AJenbo** [comment]
Feel free to put it in the 1.5 branch as well, I have a cold atm so will be a bit spotty atm
