### ISSUE TITLE
Doing atexit(SDL_Quit) causes segfaults sometimes in some configurations.

### ISSUE THREAD

**Issue by vanfanel** [diasurgical/devilutionX#689]
Hi there,

I have to report that using atexit() to get SDL_Quit() on exit is causing segfaults in some SDL2 configurations like SDL2 on MESA on KMS/DRM.
This is a known SDL2 issue with MESA:
https://bugzilla.libsdl.org/show_bug.cgi?id=4530
https://lists.freedesktop.org/archives/mesa-users/2019-March/001519.html
Look at MESA reply on this:
https://lists.freedesktop.org/archives/mesa-users/2019-March/001520.html

Back to devilutionx, `atexit(SDL_Quit)` is currently being called here:
https://github.com/diasurgical/devilutionX/blob/afca5d9fef750ece89677d2c04e9a7e0d5f84a1e/SourceX/display.cpp#L54

What I do for my own builds for X-less systems is to call SDL_Quit() directly in `SourceX/DiabloUI/diabloui.cpp`, just before `exit(0)` here:

https://github.com/diasurgical/devilutionX/blob/afca5d9fef750ece89677d2c04e9a7e0d5f84a1e/SourceX/DiabloUI/diabloui.cpp#L331

So what do you think? Can you move it or should I do a PR for this? 

Thanks!

**Comment by AJenbo** [comment]
The prolem is that we could need to call SDL_Quite in all places where exit is called, and in the end of main. Does it at least handle being called before SDL_init?

**Comment by vanfanel** [comment]
@AJenbo 

I am trying to figure out if calling SDL_Quit() directly in devilutionX/SourceX/DiabloUI/diabloui.cpp after exit(0) is enough and correct. I will sumarize:

-In Source/diablo.cpp, exit() is called a couple of times, but that is while processing used-passed parameters, before SDL can be initialized, so no SDL_Quit() is needed there as far as I understand.

-There is an exit() call in 3rdParty/libsmacker/smk_malloc.h, I dont know how that one would relate to SDL since its an exit on memory allocation. Maybe that should cause devilutionx to exit instead of directly exiting from the video library?

-There is an exit() call in Source/movie.cpp. I guess it should be called when WM is told to close the window while playing a movie, right? I have not been able to get devilutionx to exit on that exit() call.

-In Source/appfat.cpp there is exit(1). I dont know how/when devilutionx exits there.

-In Source/init.cpp there is exit(0) in MainWndProc(). I dont know how/when devilutionx exits there, either.

-There is exit(1) in SourceX/DiabloUI/fonts.cpp in LoadTtfFont(). That is called when SDL_ttf initialization fails (TTF_init()). That is after SDL_Init() so clearly SDL_Quit() would need to be called there too, just in case.

Well, in conclusion:
I think exit(exit_code) should never be called directly. There should be a diablo_exit() function instead, that would receive the exit code as a parameter, and do:

```
void diablo_exit(int exit_code) {
        SDL_Quit()
        exit(exit_code)
}
```

...and then change every exit(exit_code) call for diablo_exit().
Also, SDL-related things done via atexit() could be added to this diablo_exit() function.

What do you think?

**Comment by AJenbo** [comment]
The exit in Source/movie.cpp can be triggered by clicking the window close button as the intro movie plays.

Source/appfat.cpp happens after showing a fatal error dialog. Like trying to access a OOB mosnter.

**Comment by AJenbo** [comment]
I like the idea of a proper shutdown function. It also seems that there is less exit() usage then i feared.

**Comment by vanfanel** [comment]
@AJenbo Will you do it or should I do a PR? In the later case, what could be a good name for the function and where do you think it should live?

**Comment by AJenbo** [comment]
I would appreciate a PR, DiabloExit() :)

**Comment by qndel** [comment]
Diablout() 😂
