### ISSUE TITLE
[Issue Report]: Softlock random generated wall encased the enterence to level 14

### ISSUE THREAD

**Issue by hungrymonkey** [diasurgical/devilutionX#6896]
### Operating System

Linux x64

### DevilutionX version

1.5.1

### Describe

Diablo 1 Gog version/app image ran on the latest opensuse tumbleweed on gnome wayland. 

Somehow, the next level became encased with wall. How do I extract the save file from my game? This run is my first ever play through in Diablo 1.

```
Steam Deck
Vendor: Valve
Version: F7A0120


lsb_release -a
LSB Version:	n/a
Distributor ID:	openSUSE
Description:	openSUSE Tumbleweed
Release:	20240109
Codename:	n/a

Linux steamdeck.lan 6.6.10-1-default #1 SMP PREEMPT_DYNAMIC Mon Jan  8 08:58:39 UTC 2024 (e04388e) x86_64 x86_64 x86_64 GNU/Linux

Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Custom GPU 0405 (vangogh, LLVM 17.0.6, DRM 3.54, 6.6.10-1-defaul
t) (0x163f)
    Version: 23.2.1
```

### To Reproduce

1. Go to hell
2. Fight your way to the next level.
3. The random generated wall may encased the path to the staircase to level 14

### Expected Behavior

All  random generated paths should be accessible

### Additional context

![Screenshot from 2024-01-11 19-48-57](https://github.com/diasurgical/devilutionX/assets/771339/d6d26b32-9bc7-4598-b2f3-c0f80f7abcf4)

**Comment by Trihedraf** [comment]
You need to find the Steel Tome and click on it and it will open the way to fight the Warlord of Blood standing on the staircase entrance.

**Comment by hungrymonkey** [comment]
Hi. I actually cleared the whole map and didn't find the steel Tomb. Somehow, the generate procedural map is an unusually small square shaped.

![Screenshot from 2024-01-12 04-18-04](https://github.com/diasurgical/devilutionX/assets/771339/222facfe-7016-4c70-9059-f924319602c6)
![Screenshot from 2024-01-12 04-18-10](https://github.com/diasurgical/devilutionX/assets/771339/91284769-fbb2-4184-b754-d20e38e810e9)

![Screenshot from 2024-01-12 04-18-15](https://github.com/diasurgical/devilutionX/assets/771339/e2adb715-3e3a-4a7e-b6d4-7c8812a7af6b)
![Screenshot from 2024-01-12 04-19-05](https://github.com/diasurgical/devilutionX/assets/771339/c52a4839-cee3-4d97-bfd1-91d4a03481e5)

To give you idea, I couldn't find the anvil in level 10 either.

**Comment by hungrymonkey** [comment]
![Screenshot from 2024-01-12 04-33-39](https://github.com/diasurgical/devilutionX/assets/771339/1ab2bfe5-22e4-4159-a6a3-b855005b4317)
![Screenshot from 2024-01-12 04-33-08](https://github.com/diasurgical/devilutionX/assets/771339/084f3a50-bbec-4cfc-8140-abc3ed4a8c3d)
![Screenshot from 2024-01-12 04-32-29](https://github.com/diasurgical/devilutionX/assets/771339/ac08015d-a0f5-47ea-82e8-1687a39c4312)
![Screenshot from 2024-01-12 04-32-07](https://github.com/diasurgical/devilutionX/assets/771339/d5000bb9-4587-49d2-853a-70b1930ca8e9)

**Comment by hungrymonkey** [comment]
Should I create a new bug report? Anvil didn't spawn and the tome too

**Comment by AJenbo** [comment]
The anvil is only in 2/3 games so probably it's just not in this one, it's not listed in your quests after all

**Comment by ChaosMarc** [comment]
@hungrymonkey the Tome (a book on a pedestal) can be placed anywhere on the map and is sometimes easy to miss. If you upload your save game I could take a look around.

**Comment by hungrymonkey** [comment]
> @hungrymonkey the Tome (a book on a pedestal) can be placed anywhere on the map and is sometimes easy to miss. If you upload your save game I could take a look around.

Where is the save file? Remember, this attempt is the first time I every played the game. My level 13 is pretty small for no reason whatever

**Comment by AJenbo** [comment]
The level isn't small, that is a perfectly normal size, it's isn't very complex bu that is perfectly normal for a Hell level.

By default you will find saves in the config folder: https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide

**Comment by hungrymonkey** [comment]
> The level isn't small it's the normal size, it's isn't very complex but that is perfectly normal for a Hell level.
> 
> By default you will find saves in the config folder: https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide

[savefile.zip](https://github.com/diasurgical/devilutionX/files/13920925/savefile.zip)

Thanks. I saw other people's play through and their first hell level isn't as regular as mine. I might should had ask through discord because I do not know what look correct to be honest.

**Comment by AJenbo** [comment]
![image](https://github.com/diasurgical/devilutionX/assets/204594/93136383-a83c-4295-9d61-de8a2588fa2c)
