### ISSUE TITLE
bug in devilutionx

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#6898]
from email

-------------------

Hi,

I found a bug, running devilutionx 1.5.1 and Hellfire.

1. shop at Adria
2. buy a book
3. read it
4. save
5. reload (either via "load save" menu option, or via new game>select character>load game)
6. book is there again

Please let me know if I may provide any other information.

Sincerely,
Dragos

**Comment by StephenCWills** [comment]
This is a duplicate of #3172

**Comment by AJenbo** [comment]
Arh, I understood it as being in the inventory again, this makes more sens :+1:
