### ISSUE TITLE
Small UI

### ISSUE THREAD

**Issue by YALdysse** [diasurgical/devilutionX#6906]
### Operating System

Linux x64

### DevilutionX version

1.5.1

### Describe

Please, help me.
On my resolution 1920x1080 I have too small UI, such as text.
How can i fix it ?
![Screenshot at 22-44-50](https://github.com/diasurgical/devilutionX/assets/84655481/08fe6676-c3bb-4e38-a189-2b8ee59c7f96)

### To Reproduce

My graphics settings:
![Screenshot at 22-46-39](https://github.com/diasurgical/devilutionX/assets/84655481/19d359f4-1034-490d-86c5-2a84231e2887)

**Comment by Trihedraf** [comment]
Reduce the resolution and the ui will get bigger

**Comment by AJenbo** [comment]
The menu is 640x480, the only reason to choose higher resolutions is if you want things to take up less space on the screen
