### ISSUE TITLE
[Feature Request]:  Favorites Spells UI

### ISSUE THREAD

**Issue by orion164** [diasurgical/devilutionX#6908]
### Feature Type

Quality of Life

### Describe

Hi, is it possible to add an option that always displays spells that have a hotkey? a bit like it appears in the image I edited
just to help remember what you have :)

Thanks

![test](https://github.com/diasurgical/devilutionX/assets/9025865/7766d811-d7b9-4965-af7c-399b7eebeec2)

**Comment by julealgon** [comment]
I hate the inconsistency in how the skills are presented in comparison with the potions in the UI but I think this is an interesting proposal.

If there were only 4 shortcuts, one could even consider showing these icons in place of the "readied spell" in the UI with an added highlight for the selected one. Although that would create a complication in case you were to select a spell that you _don't_ have a hotkey for... unless you went crazy and disallowed using any skill that doesn't have a hotkey 😛 (limited spell slots, like "modern" RPGs).

**Comment by kphoenix137** [comment]
More UI clutter. We need less UI clutter.

**Comment by AJenbo** [comment]
I think this is better left to Lua for custom UIs. This still isn't fully support but it should be before we can call the Lua integration complete.
