### ISSUE TITLE
[Feature Request]: Runes also affected by Autofill

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#6909]
### Feature Type

Quality of Life

### Describe

I notice in Hellfire that when you put runes in your belt and then use them, they won't pull the next rune of the same type from your inventory. I feel that the runes would be more useful and appealing if they could be autofilled like that.

**Comment by julealgon** [comment]
How does this work with scrolls?

**Comment by Chonkblonk** [comment]
Uh, that's a good question. Lemme go and test that real quick.
No, scrolls don't draw from the inventory like potions do either.
I guess it would be nice if both scrolls and runes would do that, as an optional feature.

**Comment by julealgon** [comment]
Thanks for checking @Chonkblonk . That's precisely why I asked: I'd rather these requests be fully consistent and apply to all similar items in the game, rather than be special cases for consumable X and not consumable Y.

**Comment by kphoenix137** [comment]
> Thanks for checking @Chonkblonk . That's precisely why I asked: I'd rather these requests be fully consistent and apply to all similar items in the game, rather than be special cases for consumable X and not consumable Y.

There was no special case. The logic was broken and the original intent with this QoL feature was that it would refill *any* item. It just didn't because a variable being passed to the next function wansn't being set and spells were being cast from the originally clicked item.
