### ISSUE TITLE
[Issue Report]: Text String Truncation Issue (in Japanese)

### ISSUE THREAD

**Issue by bubio** [diasurgical/devilutionX#6911]
### Operating System

Mac

### DevilutionX version

1.5.1

### Describe

There is a problem with text string truncation, where the Japanese text is not fitting properly.

Correct,

セーブファイルがあります
キャンセル

![screen_shot](https://github.com/diasurgical/devilutionX/assets/78299054/43c1429e-d401-4e0e-9c60-cf2a40bd0f54)

### To Reproduce

1. Language : 日本語(Japanese)
2. シングルプレイヤー(SINGLE PLAYER)
3. ヒーローの選択(SELECT HERO)

### Additional context

There are multiple "キャンセル"("Cancel") locations.

**Comment by glebm** [comment]
This should be easy to fix, I'll have a look
