### ISSUE TITLE
[Feature Request]: Deleted Character Backup

### ISSUE THREAD

**Issue by 5himmy** [diasurgical/devilutionX#6919]
### Feature Type

Quality of Life

### Describe

It will be a nice feature to create backup files for deleted characters, one day cats can dance on ur keyboard :)
Ex: I deleted character named test, it will be renamed as test.backup so if i need it i can access it later.

**Comment by qndel** [comment]
And then what happens if you make another character with same name and delete it? Or what about platforms where you can't access files easily? Own your mistake and learn from it, I suggest locking your screen when going away from the computer if you have cats...

**Comment by AJenbo** [comment]
i would imagine that it get overwritten by the next one

**Comment by julealgon** [comment]
An autosave feature with a dedicated autosave slot would be a _far_ better approach to this. I remember it was discussed but I don't see any issues for it, maybe there should be one?

**Comment by AJenbo** [comment]
Not really cause they would both be deleted when deleting it's save file

**Comment by julealgon** [comment]
> Not really cause they would both be deleted when deleting it's save file

Unless the feature is coded in a way that the autosave slot is decoupled from the characters, which I think would be the way to go about it.
