### ISSUE TITLE
Switch: Build fails with latest devkitpro build image

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#6922]
### Operating System

Nintendo Switch

### DevilutionX version

Custom build (please specify commit ID)

### Describe

https://app.circleci.com/pipelines/github/diasurgical/devilutionX/19759/workflows/d28960fe-4cac-459f-a520-2d2e3e32b2e6/jobs/120154

```
Scanning dependencies of target devilutionx
[100%] Building CXX object CMakeFiles/devilutionx.dir/Source/main.o
[100%] Linking CXX executable devilutionx.elf
aarch64-none-elf-g++: error: unrecognized command-line option '-march'; did you mean '-march='?
```

### To Reproduce

1: Trigger a build with the latest devkitpro

**Comment by StephenCWills** [comment]
Reported on the devkitPro forum.
https://devkitpro.org/viewtopic.php?t=9532
