### ISSUE TITLE
[Feature Request]: Keeping game choice at the beginning.

### ISSUE THREAD

**Issue by 20Phoenix** [diasurgical/devilutionX#6931]
### Feature Type

Quality of Life

### Describe

I would like to have ALWAYS the choice between Hellfire and Diablo after starting the game, not only the first time.
Otherwise it to complicated to switch between the two.
I mean please add [StartUp] Game=0 as a choice in the settings, not only 1 and 2 for the two games.
Thanks :smile:

**Comment by AJenbo** [comment]
This is an opinion that not everyone shares. You can make shortcuts that starts either, maybe that would be a solution?

**Comment by obligaron** [comment]
I'm not sure if you know this, but you can switch from Diablo to Hellfire and vice versa in the settings menu and don't need to edit diablo.ini manually.
Main Menu -> Settings -> Start up -> Game mode

**Comment by glebm** [comment]
You can also create shortcuts with `--diablo` and `--hellfire` and use [these icons](https://github.com/diasurgical/devilutionX/tree/master/Packaging/resources).

**Comment by 20Phoenix** [comment]
> This is an opinion that not everyone shares. You can make shortcuts that starts either, maybe that would be a solution?

Oh, I forgot something important: I speak about the XBOX version.

**Comment by 20Phoenix** [comment]
> I'm not sure if you know this, but you can switch from Diablo to Hellfire and vice versa in the settings menu and don't need to edit diablo.ini manually. Main Menu -> Settings -> Start up -> Game mode

I know. That's what I've meant with "complicated".

**Comment by 20Phoenix** [comment]
> You can also create shortcuts with `--diablo` and `--hellfire` and use [these icons](https://github.com/diasurgical/devilutionX/tree/master/Packaging/resources).

On PCs an easy thing of course, not so on consoles.

**Comment by StephenCWills** [comment]
On Xbox, isn't it more complicated to exit the game and launch it again than to visit the `Settings` menu and switch the game mode?

**Comment by 20Phoenix** [comment]
If I want to start Hellfire and have to start Diablo therefore ... feels wrong handling.
It is a decision that everyone can make for themselves and shape according to their wishes.
Adding a third options (Diablo/Hellfire/Choice) to the start settings needs less time than discussed here.
I would use it as standard.

**Comment by julealgon** [comment]
> > You can also create shortcuts with `--diablo` and `--hellfire` and use [these icons](https://github.com/diasurgical/devilutionX/tree/master/Packaging/resources).
> 
> On PCs an easy thing of course, not so on consoles.

Does the XBOX not support any means of changing/setting cmdline arguments?

**Comment by 20Phoenix** [comment]
Imo two icons for one app is uncomfortable, even on PC.
The app can handle both games, therefor the choice screen was made that appears the first time starting.
This screen appears with [StartUp] Game=0. After selection this value is set to 1 or 2.
I miss a setting to keep it at 0 to get always asked at the beginning. One simple click.

**Comment by DakkJaniels** [comment]
Adjust programming to make another option (or I guess add 4th enumeration) so that it always asks, and won't update the ini. Feel free to adjust code and make UI changes to support (probably a checkbox that says always ask, or something?)

**Comment by julealgon** [comment]
> Imo two icons for one app is uncomfortable, even on PC.

Fair enough. I disagree, but this is widely subjective. I can understand your perspective.

> The app can handle both games, therefor the choice screen was made that appears the first time starting.
> This screen appears with [StartUp] Game=0. After selection this value is set to 1 or 2.
> I miss a setting to keep it at 0 to get always asked at the beginning. One simple click.

Ok. I do think it would make sense to allow the setup you want considering the behavior already exists to pick the game. If this was completely new behavior, I'd be against it as well.

**Comment by StephenCWills** [comment]
Two icons for one app... but it's wrong to load up Diablo so you can switch to Hellfire? I really do not understand what you're getting at. I'm kind of speaking for others here, but it seems the general consensus has been that having the option in the `Settings` menu should be sufficient for anyone who frequently switches back and forth. And I'm speaking for myself when I say that this seems like an even worse request for Xbox specifically, since you'd have to go back to the home screen, manually close the game with a menu option, then open the game back up to see the prompt.

**Comment by julealgon** [comment]
> Adjust programming to make another option (or I guess add 4th enumeration) so that it always asks, and won't update the ini. Feel free to adjust code and make UI changes to support (probably a checkbox that says always ask, or something?)

The way this "usually" goes is to have a setting on the message that you can click to "do not ask me again". If the user doesn't click on it, the option is always presented.

**Comment by DakkJaniels** [comment]
> The way this "usually" goes is to have a setting on the message that you can click to "do not ask me again". If the user doesn't click on it, the option is always presented.

That works. Still need someone to do it.

**Comment by qndel** [comment]
This whole discussion is pointless in my opinion because dude is behaving like he'd be switching between diablo and hellfire every day. I'd suggest seeing a doctor if that's the case（。々°）
99% of people prefer either diablo or hellfire and stick to their choice, I really don't see a reason to waste our time trying to please the 1% - what about people that turn their monitor upside down? Can we add a setting for rotating the game?

**Comment by AJenbo** [comment]
> what about people that turn their monitor upside down? Can we add a setting for rotating the game?

We already have since there are a few handhelds where it is actually installed upside down and games need to account for that.

**Comment by StephenCWills** [comment]
IMO, the one in the settings menu is not really about how often someone needs to switch, but just about giving them the option to switch in the first place. Many platforms don't really provide tools to enable the user to switch between Diablo and Hellfire except within the game itself. I'm pretty sure Xbox is a good example of such a system, actually. I certainly don't have any text editors I can use to modify INI files on my Xbox One.

So now that we do have the option in the settings menu, and that's what makes it possible to switch between Diablo and Hellfire, adding another option needs to justify itself differently as it doesn't provide anything you can't already do.
