### ISSUE TITLE
[Feature Request]: MacOS ARM64 builds

### ISSUE THREAD

**Issue by Traace** [diasurgical/devilutionX#6945]
### Feature Type

Quality of Life

### Describe

Since github now has a Mac M1 runner.... Any chance for getting official devilutionX builds for arm64?

I tried to fork the project, changed `runs-on` to `macos-14` and it build successfully for "Apple Chips" but the binary just gave me a SEGFAULT on launch. 
Maybe more work is needed than simply changing the runner. Unfortunately this is out of my scope.

**Comment by DakkJaniels** [comment]
Did you see #6685 ? Could try doing what that said, maybe it will help resolve the issue.

**Comment by AJenbo** [comment]
We would rather move to a universal build rather having two separate builds for Mac. There is practically no upsides to having a native build for ARM other then a nice feeling and some micro watts.

Please see https://github.com/diasurgical/devilutionX/discussions/1403#discussioncomment-6368994 for a longer explanation.
