### ISSUE TITLE
Potions Downgrading in Belt[Issue Report]: 

### ISSUE THREAD

**Issue by kpklukken** [diasurgical/devilutionX#6949]
### Operating System

Linux x64

### DevilutionX version

1.5.2

### Describe

While playing my bard in hellfire (GOG version) the potions in my belt will randomly downgrade. Fulls become standard and this happens to all 3 potion Full Heal, Full Mana, and Full Rejuvenation. It seems to only happen during melee since I can run entire levels, cast spells and level up with no noticeable issues. I did not notice this ever happen with my rogue but I have yet to melee with here since she has only ever used bows.

### To Reproduce

It happens during melee with my bard. That seems to be the only trigger on my system.

### Additional context

I am using the devilutionx-x86_64-linux-gnu appimage on CachyOS with kernel 6.7.4-2-cachyos.

**Comment by julealgon** [comment]
Did you open a trapped chest? In Hellfire, there are traps that have precisely this effect. The trap has a specific "breaking" sound as well so it should be noticeable when it happens.

**Comment by kpklukken** [comment]
I will have to watch. I suppose maybe i am accidentally clicking on chests during combat and not noticing it since combat is usually hectic. I will close the issue and re-open it if i see that it's not that.
