### ISSUE TITLE
[Issue Report]: [Switch] Controller inputs are ignored in latest buildbot version 

### ISSUE THREAD

**Issue by rsn8887** [diasurgical/devilutionX#6950]
### Operating System

Nintendo Switch

### DevilutionX version

Other (please specify version number): CircleCI build from 02/07/2024

### Describe

Controller inputs are completely ignored on latest CircleCI build from February 7.

USB mouse and keyboard still works. Rebinding menu doesn't react to controller inputs either.

### To Reproduce

Start DevilutionX for Switch, February 7 build from CircleCI. Observe that controller inputs have no effect. 

### Expected Behavior

Controller input should allow to control the game.

### Additional context

This is most probably related to the recent update to SDL2 version 2.28.5. Is it possible to enable logging to a file?

**Comment by StephenCWills** [comment]
FYI, I mentioned this already over on the devkitPro forums so we're working with them on it.
https://devkitpro.org/viewtopic.php?t=9532#p17820

**Comment by rsn8887** [comment]
I think I found the fix to SDL2 that fixes this. See here:  https://github.com/devkitPro/SDL/pull/54

**Comment by AJenbo** [comment]
dodged a bullet there with 1.5.2 i guess, we didn't build it with that version because of another bug

**Comment by rsn8887** [comment]
This has been fixed in the latest switch-sdl2 package

**Comment by AJenbo** [comment]
Thanks for the heads up
