### ISSUE TITLE
[Feature Request]: 8 or 16 players max cap

### ISSUE THREAD

**Issue by Tormentor667** [diasurgical/devilutionX#6953]
### Feature Type

Other (please specify)

### Describe

Dear developers,

I have a couple of friends with which I'd love to play DevilutionX. Unfortunately the max cap of 4 players is a very low player count. Can't this be extended to 8 or 16?

Kind regards,
Dan

**Comment by julealgon** [comment]
Duplicate of:
- https://github.com/diasurgical/devilutionX/issues/543
