### ISSUE TITLE
[Issue Report]: libsodium issue on Manjaro Arm64

### ISSUE THREAD

**Issue by coreybruce** [diasurgical/devilutionX#6954]
### Operating System

Other (please specify)

### DevilutionX version

1.5.2

### Describe

Hey just want to inform you that while you did fix the issue eith Libsodium on Manjaro x64 the issue still persists on Manjaro Arm64

```./diablo: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory```

I downloaded the Arm64 binary from your repo also

### To Reproduce

Try and play game

### Expected Behavior

Game runs

**Comment by AJenbo** [comment]
Please provide relevant info such as if libsodium is installed, if so what version, and what version of the os you are using.

**Comment by coreybruce** [comment]
> Please provide relevant info such as if libsodium is installed, if so what version.
> 
> Also consider using a package aimed at your distribution rather then the genetic build which depends on specific package version that may not be provided by your distribution, AUR should work for Manjaro as I understand it https://aur.archlinux.org/packages/devilutionx
> 
> We cannot maintain and test versions for every distribution out there, if you want to maintain support for Manjaro that is always an option.

Yes it is installed and it is version 1.0.19-2

It works on Manjaro x64 also I don't think you saw even tho it is very suprising since you moderate the Github repos but 1.5.2 was made to fix the issue on Manjaro libsodium which previously reported

https://github.com/diasurgical/devilutionX/releases/tag/1.5.2

"Manjaro: Unable to locate libsodium"

The odd issue is that for some reason the issue persists on the Arm64 binary but not has been fixed on the x64 binary, it may need to be fixed.

I also use the binaries on my AUR package for binaries https://aur.archlinux.org/packages/devilutionx-bin

**Comment by AJenbo** [comment]
> I don't think you saw even tho it is very suprising since you moderate the Github repos but 1.5.2 was made to fix the issue on Manjaro libsodium

What ever do you mean by this?

**Comment by coreybruce** [comment]
I was letting you know that they did a fix on this release for Manjaro so it is supports distros like Manjaro

**Comment by qndel** [comment]
"The odd issue is that for some reason the issue persists on the Arm64 binary but not has been fixed on the x64 binary, it may need to be fixed." english pls

**Comment by AJenbo** [comment]
> I don't think you saw even tho it is very suprising since you moderate the Github repos

Not only have I seen it, I wrote it. Maybe take the time to see who you are quoting before you start making accusations, assumptions and conclusions based on it: https://github.com/diasurgical/devilutionX/releases/tag/1.5.2

> I was letting you know that they did a fix on this release specifically for Manjaro so it is supports distros like Manjaro

Who do you think "they" are? I was also the one who made the change to the x86 build script: https://github.com/diasurgical/devilutionX/pull/6938
Like we explained last time this embeds the libsodium library rather then rely on the system package. But configurations like that are build specific so that's why it doesn't affect other architectures.

> I could even recompile it for Arm64 and provide the binary to you guys.

If it's build against what ever libraries are present on Manjaro at the time then it won't work on most other distros as the glibc version going to conflict with them. Besides the build is handled by the automated actions and it's prefered that way to avoid having potential mitm issues.

> Also since I have provided the information that was needed you can remove the Insufficient information label

I'll get to it. Maybe you can add it to the original post while you wait.

**Comment by coreybruce** [comment]
>  Not only have I seen it, I wrote it. Maybe take the time to see who you are quoting before you start making accusations, assumptions and conclusions based on it: https://github.com/diasurgical/devilutionX/releases/tag/1.5.2

why are you getting aggressive and assuming I am making accusation here lol

>  Who do you think "they" are? I was also the one who made the change to the x86_64 build script: https://github.com/diasurgical/devilutionX/pull/6938

I was referring to the devilutionX in general here and if you were the one who did the fix then great

> Like we explained last time this embeds the libsodium library rather than rely on the system package. But configurations like that are build specific so that's why it doesn't affect other architectures.

Yes I know that, I was just letting you know that the fix you did for x64 in the build script will also need to be applied to the Arm64 binary when compiling, that's all I am informing you about.

**Comment by coreybruce** [comment]
> "The odd issue is that for some reason the issue persists on the Arm64 binary but not has been fixed on the x64 binary, it may need to be fixed." english pls

Fixed it

**Comment by AJenbo** [comment]
> why are you ... assuming I am making accusation here lol

Your message implies doubt about whether I saw something despite my role in moderating the GitHub repositories, suggesting I should have seen it. Where I come from that's called an accusation.

> why are you getting aggressive

You also chose to use an intensifiers in that statement. You not even realizing that you are quoting me back to me gave me the impression that this was going to be a repeat of our last which was rather unpleasant.

**Comment by coreybruce** [comment]
Wow ok how about we get back on topic and stop being aggressive and making aggressive assumptions, I never implied or had doubts, I was just informing about the issue etc in case you didn't know also no I didn't know you wrote the post but you were acting like it wasn't supported despite it does and the fix for Manjaro was there but not completely fixed sadly

Getting back to the topic at hand I just want to help fix the issue but attacking me isn't going to solve anything, I am your friend not your enemy

**Comment by coreybruce** [comment]
> I don't know how else to read this "I don't think you saw even tho it is very suprising"?

Well I am sorry if you feel like I was doubting you

> I think you miss understood something then. It's a build time option, not something that you can fully "fix", it depends on how you run the build process for each binary. 

I assume we would need to rebuild the binary for Arm64 to fix it

> I have updated the release nots to hopefully make it less confusing: "Linux: Statically link BZIP2 and libsodium on x86_64"

Alright, does Arm64 do the same thing? 

> You are not the only one feeling attacked here.

I'm sorry if you feel attacked, that wasn't my attention and I just wanted to report the issue and help fix it

**Comment by AJenbo** [comment]
I don't think we will be re-releasing the 1.5.2 Linux Aarch64 build since it will reset the download counter and it has already been a week since the release. It would also cause the hash to change which might cause issues down stream.

If you want to prevent issues like that it would be good if you can test the test builds prior to a release: https://github.com/diasurgical/devilutionX?tab=readme-ov-file#test-builds

I felt defensive because it seemed like you were making unnecessary personal comments and denying it when I pointed it out.

**Comment by coreybruce** [comment]
> I don't think we will be re-releasing the 1.5.2 Linux Aarch64 build since it will reset the download counter and it has already been a week since the release. It would also cause the hash to change which might cause issues down stream. 

Ah ok that's understandable :+1: 

> If you want to prevent issues like that it would be good if you can test the test builds prior to a release: https://github.com/diasurgical/devilutionX?tab=readme-ov-file#test-builds

Yeah no problem I can do that

> I felt defensive because it seemed like you were making unnecessary personal comments and denying it when I pointed it out.

Oh I'm sorry but  that wasn't my intention at all
