### ISSUE TITLE
[Translation Request] Italian language for DevilutionX

### ISSUE THREAD

**Issue by M0Rf30** [diasurgical/devilutionX#697]
Hi,
I extracted all the strings with the command ```strings -t x Diablo.exe``` from a patched Language conversion linked here: http://www.zuminator.altervista.org/progetti/schedadiabloallversion.htm

Cause I've noticed the branch translations, I hope to give a contribution with the attached file
Some stats:
Dialogues:100%
Village menu entries: 100%
Internal Game Help: 100%
Quest names: 100%
Monsters names: 89%
Items and miscs names: 79%
These stats are related to 1.09b executable version
I know that is clean of garbage but I prefer to upload the untouched version, so here is the file
[Diablo-Italian.txt](https://github.com/diasurgical/devilutionX/files/4465475/Diablo-Italian.txt)

**Comment by AJenbo** [comment]
Thanks, but since we don't speak Italien it would be hard for us to apply the translations in this way. It would help if you download the pot file and generate an Italian .po file from it, and then apply the translation. This can be done with any translation tool, like Poedit. https://poedit.net/download
(you will need to download the whole branch in order for it to scan for translatable strings)

Alternately if you can copy the da.po and edit it if you want to skip generating one from the pot file.
https://github.com/diasurgical/devilutionX/blob/9fb8281116c108126486430e9be9f273a6b6144c/translations/da.po

Note that only the menu is translatable at this point as we still need figure out how to make this work on Windows and Mac before we apply it to the rest of the source.

**Comment by M0Rf30** [comment]
Yes I know about po extensions and management. I will push an it.po asap. In the meantime I'm thinking about to automatically associate english and relative italian entries matching the hex address. That's why I uploaded the file. Anyway thanks to put efforts on this project

**Comment by cyruzin** [comment]
> Thanks, but since we don't speak Italien it would be hard for us to apply the translations in this way. It would help if you download the pot file and generate an Italian .po file from it, and then apply the translation. This can be done with any translation tool, like Poedit. https://poedit.net/download
> (you will need to download the whole branch in order for it to scan for translatable strings)
> 
> Alternately if you can copy the da.po and edit it if you want to skip generating one from the pot file.
> https://github.com/diasurgical/devilutionX/blob/9fb8281116c108126486430e9be9f273a6b6144c/translations/da.po
> 
> Note that only the menu is translatable at this point as we still need figure out how to make this work on Windows and Mac before we apply it to the rest of the source.

Nice! I'm going to translate to PT-BR as well.

**Comment by cyruzin** [comment]
@AJenbo here is the translation for brazilian portuguese: https://gofile.io/?c=93V1fn

**Comment by AJenbo** [comment]
@cyruzin could you please attach the translation as a zip or preferably as a PR for the translation branch. Thank you.

**Comment by VanackSabbadium** [comment]
Hi Morfeo,

did you manage to translate it and create an it.po file?

---

Ciao Morfeo,

sei riuscito poi a fare la traduzione e creare il file it.po?

**Comment by M0Rf30** [comment]
@VanackSabbadium No I've only created an it.po for existing strings. Extracting translated strings from Diablo-italian.txt (uploaded in the 1st post), should be trivial

**Comment by M0Rf30** [comment]
Here I attach the devilutionx-it.po and the original strings with msgid equal to ```strings -t``` comparison between executables
[devilutionx.zip](https://github.com/diasurgical/devilutionX/files/5447281/devilutionx.zip)

**Comment by AJenbo** [comment]
Thanks that will prove very useful for integrating it.

**Comment by AJenbo** [comment]
The translation has now been integrated, I'm updating the mapping as more of the application is exposed to the translation function, but some parts aren't 1:1 with the actual texts so they may end up incorrectly mapped or not mapped at all. Hope you will be ok doing those parts again :)
