### ISSUE TITLE
[Feature Request]: Proposal to Add Confirmation When Clicking NewGame/QuitGame Buttons

### ISSUE THREAD

**Issue by zensai3805** [diasurgical/devilutionX#6973]
### Feature Type

Quality of Life

### Describe

Hello,

I've started playing D1 this year and have been really enjoying the experience. I would like to suggest an enhancement.

## Feature Request:
My suggestion is to add a confirmation option for the NewGame/QuitGame buttons. Currently, it's easy to accidentally click these buttons, located near the "Return in Town" option, after dying in the dungeon and dropping equipment, which results in losing all the equipment.

Being new to D1 and this project, I might not be aware if there's already a mechanism in place to prevent such accidents. If such a mechanism exists, I would greatly appreciate being informed about it. I am moved by the community's transparency and the efforts to maintain this project.

Thank you for considering my suggestion.

**Comment by Trihedraf** [comment]
#3902

**Comment by zensai3805** [comment]
Thank you for the information; I support the PR(#3902) mentioned above. I believe the changes proposed in the PR will address the issue I've experienced.

While my suggestion would require a check every time NewGame is clicked, the PR's focus on the scenario after dying seems more appropriate.

I am unsure if #3902 will be merged, but having discovered that similar considerations have been made, I will now close this issue.
