### ISSUE TITLE
[Issue Report]: 

### ISSUE THREAD

**Issue by ildar** [diasurgical/devilutionX#6974]
### Operating System

Linux x64

### DevilutionX version

1.5.2

### Describe

Cathedral/Dungeon level 3 fountain doesn't work

### To Reproduce

1. goto Cathedral/Dungeon level 3
2. drink from the fountain
3. see you've got -2 to mana

### Expected Behavior

work normally

### Additional context

![Screenshot-2024-02-19-15:57:32](https://github.com/diasurgical/devilutionX/assets/517752/14db67e4-efa8-480f-aa4d-1773dc03abe2)

**Comment by AJenbo** [comment]
Levels are random, what fountain?
What equipment do you have?
Please add a title for the issue.

**Comment by julealgon** [comment]
I see -2 mana in the description, and then -1 mana in the screenshot. Did you click the fountain only once?

Fountains in D1 do not work the same way as wells do in D2. They do not refill your entire pool in a single click.

**Comment by ildar** [comment]
sorry for this issue:
1. somehow I forgot to fill in the title
2. I don't really know how this fountain should work.
Next time I'll provide exhaustive infos.
