### ISSUE TITLE
[Issue Report]: stuttering sound after console standby

### ISSUE THREAD

**Issue by locksoft** [diasurgical/devilutionX#6985]
### Operating System

Nintendo Switch

### DevilutionX version

1.5.2

### Describe

Every time I put the console in standby (pressing power button) and wake it up again, if Devilution-X was running, the sound starts stuttering like if the whole game is slowing down (even if it’s not).

I need to close the app and start it again.

### To Reproduce

1 - Launch the game and start playing;
2 - Press the power button to put the Switch in standby;
3 - Press again the power button to wake up the console and keep playing;
4 - The sound is weird.

### Expected Behavior

The sound should keep working normally.

**Comment by AJenbo** [comment]
I don't think this is an issue specifically related to DevilutionX. Please report this issue with the Switch port of SDL.

**Comment by locksoft** [comment]
Sorry, I’m very noob here. How can I report it the the Switch developing team?

**Comment by AJenbo** [comment]
Here I think https://devkitpro.org/viewforum.php?f=17

**Comment by locksoft** [comment]
Thank you.

**Comment by locksoft** [comment]
Hmmm… it seems I’m not able to register on that website:

“Forbidden. Your IP belongs to a high spam risk network. Please, try again without VPN.”

I’ve no idea what they mean. It’s an Italian IP (my Internet provider) and I’ve never sent a spam email in my whole life. And never had problems with my IP. :\

**Comment by AJenbo** [comment]
Yeah they are not the most easy to work with :/

**Comment by locksoft** [comment]
> What is your IP?

At the moment is 195.94.154.229. But it's dynamic, it changes every time my Internet connection resets.
