### ISSUE TITLE
[Feature Request]: semitransparent overlay map

### ISSUE THREAD

**Issue by locksoft** [diasurgical/devilutionX#6987]
### Feature Type

Quality of Life

### Describe

I mostly play the game with the map open, to avoid to get lost, but it’s a bit too intrusive. Maybe adding a middle transition like ON, 50%, OFF could be more convenient. It may be triggered by the same button to activate and deactivate it.

**Comment by Trihedraf** [comment]
Already in the next unreleased version #6607

**Comment by locksoft** [comment]
Thanks. I had a quick look on the previous suggestions but I should have missed it, sorry. :)
