### ISSUE TITLE
[Issue Report]: Na-Krul error message

### ISSUE THREAD

**Issue by locksoft** [diasurgical/devilutionX#7001]
### Operating System

Nintendo Switch

### DevilutionX version

1.5.2

### Describe

Every time I kill Na-Krul I get this error message on the bottom left of the screen:

Player ‘name_of_my_hero’ sent an invalid packet.

No other issue, game keeps working normally. I don’t know if it’s important.

***

I also have a bonus question about Hellfire: according to this page, there should be various different oil potions:

https://diablo2.diablowiki.net/D1_Hellfire_Oils

some should be easier to find, some more rare. In about four full Hell runs of Hellfire I only found a few of them:

Blacksmith Oil: a lot, like 3-4 per session (2-3 levels);
Oil of Sharpness: quite often, like 1-2 per session;
Oil of Accuracy: more or less like Sharpness;
Oil of Mastery: only one so far;
Oil of Skill: I think 2-3 so far.

No trace of all other kinds. Are they implemented in DevilutionX and are just super rare (just no luck for me) or are they still missing?
Thanks.

### To Reproduce

Just kill Hellfire final boss.

### Expected Behavior

I don’t know, no error message? :)

**Comment by Chonkblonk** [comment]
Oils are a matter of rarity, in my experience some seed gens appear to be more generous with dropping oils than others.
In multiplayer, incidentally, you also can only find Blacksmith Oil, Oil Of Sharpness, Oil Of Accuracy, and Oil Of Fortitude.

**Comment by AJenbo** [comment]
This has already been fixed: https://github.com/diasurgical/devilutionX/pull/6960

This is not the place for bonus questions... or questions. One issue per issue please.
