### ISSUE TITLE
[Feature Suggestion]: LAN between Single Player characters, or "Open Multiplayer"

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#7002]
### Feature Type

Other (please specify)

### Describe

In Diablo 2, there was a feature where you could take your Single Player characters and use them for playing LAN, TCP/IP, and on "Open Battle.net," which was a separate network from the regular Battle.net

Would the option for a similar concept be an idea to consider some day? Ergo a separate 'branch' of Multi Player or even just LAN available for people's Single Player characters. They would not be able to play or interact with normal Multi Player games or players, and they would have to create a new game together to play, then create a new game when they want to go back to Single Player again.

An entire separate network may be a lot to ask, but I do think that it would be cool if at least LAN or TCP/IP would be an option this way.

**Comment by julealgon** [comment]
Related (somewhat):
- https://github.com/diasurgical/devilutionX/issues/74

There's been discussions in other places around unifying single player and multiplayer saves as well but I couldn't find them.

I absolutely hate the D2 approach on this one and would vote against it.

**Comment by Chonkblonk** [comment]
There's different kinds of shrines and item generation in Single Player, so the gameplay is somewhat different on that point. 
It'd also just be cool for multiple people to join up the Single Player characters they've built up for adventuring.
(Further, King Leoric functions differently in SP, though that's apparently something planned to be added to MP).

To my understanding, unifying SP and MP saving wouldn't be easy, as you would kill backwards compatibility and cause warping for one of them.

**Comment by Chonkblonk** [comment]
So, what would be the eventual approach, sacrifice MP character's items so that they can have SP items? The opposite would be less desirable, obviously. Either is a hard sell.

As for MP quests, best I can tell they function virtually perfectly. 
The only hangup I have ever had was that dropping the Golden Elixir on the ground in front of Lachdanan and then picking it up and giving it to him, made him do his thankyou speech but then soon cutting it off to die prematurely (no idea if this was what caused it, or if it was a fluke).
Having SP quests in MP is one of the best parts of DevX.

**Comment by AJenbo** [comment]
No this will not happen. We are bringing missing features to multiplayer. Single Player heroes will not become multiplayer enabled and or segment the games even more.

There would not be a Heal Other or Resurect.

>  @Chonkblonk (Further, King Leoric functions differently in SP, though that's apparently something planned to be added to MP).

This has been addressed for 1.6.0

> BUT, what if there was an algorithm which scanned through a character's inventory, identified the item in question, deleted the MP item, and put in its place the SP counterpart from the SP list?

What counter part? They are randomly generated from a seed, you would have to scan 4,294,967,295 to look for a match, and might not find a perfect match.

> @julealgon And yes, there are plans to have all quests work in multiplayer.

That's already in 1.5

**Comment by Chonkblonk** [comment]
> We are bringing missing features to multiplayer.

Would that mean things like adding the SP oils which are absent from Hellfire's MP?

> What counter part? They are randomly generated from a seed, 

I was under the impression that there was a separation between item generation in SP and MP, thus why you couldn't have the SP vendor lists in MP.

> you would have to scan 4,294,967,295 to look for a match, and might not find a perfect match

When you put it like that, my suggestion is actually pretty worthless.

**Comment by AJenbo** [comment]
> Would that mean things like adding the SP oils which are absent from Hellfire's MP?

No, items will morph. But mods could and we are making modding easy
