### ISSUE TITLE
Windows: Audio distortion when running in the background of other games

### ISSUE THREAD

**Issue by Sergei3000yt** [diasurgical/devilutionX#7014]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

If another game is open at the same time as DevilutionX (for example, Minecraft or Crysis 3), then the sound in DevilutionX will knock as if damaged audio equipment is connected to the computer.

### To Reproduce

1. Run other game (in my case Minecraft or Crysis 3)
2. Run DevilutionX
3. Listen bad sound in Devilution

**Comment by AJenbo** [comment]
what is your audio settings in game and what sound card do you have

**Comment by Sergei3000yt** [comment]
> what is your audio settings in game and what sound card do you have

I didn't understand the question well, so I'll just send you a screenshot.
![image](https://github.com/diasurgical/devilutionX/assets/162808446/0298ffdb-3f71-4e2e-a716-faf5f724cb7e)
![image](https://github.com/diasurgical/devilutionX/assets/162808446/20a26d81-35f0-4c4f-8616-ce919aa3035a)

**Comment by Sergei3000yt** [comment]
> what is your audio settings in game and what sound card do you have

Sound Card (I do not know which of these is the sound card)
![image](https://github.com/diasurgical/devilutionX/assets/162808446/1fafcc1b-7381-4d45-89dc-6eda2d4f07be)

**Comment by AJenbo** [comment]
Can you try switching the Resampler from Speex to SDL and see if that makes a difference.

**Comment by Sergei3000yt** [comment]
No, switching to SDL does not change anything.

**Comment by kphoenix137** [comment]
> No, switching to SDL does not change anything.

1) Try disabling audio enhancements for either/both in the Sound Settings in Control Panel in Windows
2) Update your sound card drivers. Check for Windows updates.
3) Do you have a low end system? Perhaps high system resource usage might be the problem, and running multiple games at once is not something you should be doing if so.
4) Try disabling sound hardware acceleration in the Windows Sound Control panel.
5) Check your sound output device sample rate. Perhaps it's set to a rate that may be be causing the issue.

**Comment by Sergei3000yt** [comment]
> 5. Check your sound output device sample rate. Perhaps it's set to a rate that may be be causing the issue.

Yes! That's the reason! In Windows, the default value for audio output devices is "24 bits, 44100 Hz". This is the only simple rate where audio problems occur. Any other value of the sample rate, whether it is higher or lower, does not have similar problems. The rest of the tips didn't help. On point 4, I have pretty powerful hardware for several applications. If you are interested in which one, ask in the Discord group DevilutionX or in private messages (@sergei_3000).

**Comment by AJenbo** [comment]
Did you try changing the sample rate in game to match that of your sound card ?

**Comment by Sergei3000yt** [comment]
No, I haven't tried /

**Comment by kphoenix137** [comment]
> Did you try changing the sample rate in game to match that of your sound card ?

Safe to close issue as solved?

**Comment by AJenbo** [comment]
From what I can tell the issue is with the specific setup not properly handling mixing of audio of two different frequencies. I don't think there is much we can do from our side
