### ISSUE TITLE
[Feature Request]: support .mpq mods

### ISSUE THREAD

**Issue by Sergei3000yt** [diasurgical/devilutionX#7015]
### Feature Type

Other (please specify)

### Describe

I suggest adding support for existing mods for Diablo & Hellfire. I do not know how difficult it is to do this. I understand that it is very difficult to support all mods. I propose to support those mods that require mpq mod files to work with, as with Hellfire. I think it won't be too difficult if DevilutionX just reads mpqs and plays back their contents. Correct me if I misunderstood how the emulator works. There are very few mods based on Devilution and almost no one deals with them, while there are already a huge number of suitable mods for the game itself, like the "HD Mod" and the "The Hell" series of mods.

**Comment by AJenbo** [comment]
We already support mpq mods and direct file loading. Belzebub (HD) and The Hell both modefy/replace the engine, which would mean replacing DevilutionX, so we cannot support them. Instead they would need to rebase there mods on DeviluionX. In the up coming version there is also support for Lua scripting which will remove the need to modefy the engine it self.

**Comment by qndel** [comment]
Please allow running sonic the hedgehog in devilutionx

**Comment by Sergei3000yt** [comment]
Sorry, I don't know what DevilutionX support .mpq mods. Looks like I haven't used it for too long this.

**Comment by yuripourre** [comment]
@Sergei3000yt mpq is a file format, think about it as .zip file.

Those mods you mentioned are much more than just an mpq file. It's hard to explain without going to technical.
