### ISSUE TITLE
[Issue Report]: Bug hole in textures (Hellfire)

### ISSUE THREAD

**Issue by Sergei3000yt** [diasurgical/devilutionX#7017]
### Operating System

Android

### DevilutionX version

1.5.2

### Describe

Due to errors in the generation of "Nest" (possibly incorrect name), holes may appear that duplicate the surrounding landscape while moving at the speed of the available frame rate, like a Windows error, which is duplicated thousands of times. Doesn't do anything bad, just a visual bug.

https://github.com/diasurgical/devilutionX/assets/162808446/f9c4e270-c01a-4f23-9f8d-d1c0fb21c0e6

### To Reproduce

Get into the "Nest" and try to find it

**Comment by AJenbo** [comment]
Thanks, this is a known issue with missing graphics in the original art. We would have to draw them our selfs and patch them in to the game to fix it which is a bit hard to do.

Duplicate: https://github.com/diasurgical/devilutionX/issues/3182
