### ISSUE TITLE
[Feature Request]: Stash objects “center of gravity”

### ISSUE THREAD

**Issue by locksoft** [diasurgical/devilutionX#7019]
### Feature Type

Quality of Life

### Describe

I’m not quite sure if this is a bug or just a missing feature: when you move the gamepad cursor in the inventory over objects bigger than one square, it jumps straight in the middle of them, so exactly in the center of a book (4 squares) or an armor (6 squares). This is very convenient and useful to save time.
It doesn’t happen in the stash, where the cursor keeps moving by a square every time, even on bigger object. This requires several joypad movements to pass from a big weapon to the next one.
Is it possible to have the same inventory behavior everywhere?

**Comment by ThomasChr** [comment]
Can reproduce. Will try to solve.

**Comment by ephphatha** [comment]
This is the first task in #4270, but I think having a dedicated issue for it is good as the changes needed are independent of the other tasks in that issue.
