### ISSUE TITLE
[Issue Report]: New entrances/exits to the Labyrinth open in the city before they are discovered

### ISSUE THREAD

**Issue by Sergei3000yt** [diasurgical/devilutionX#7020]
### Operating System

Android

### DevilutionX version

1.5.2

### Describe

It is known that in addition to the entrance to the Labyrinth through the Cathedral, there are 3 more - the entrance next to the cows, the entrance to the caves next to Virt and the entrance to Hell to the left of the girl with the vault. Logically, these entrances should open when discovered in the Labyrinth, but they open even before visiting the level with the entrance. One could turn a blind eye to the premature opening, but another problem appears - the Hellfire dungeons. The fact is that if you complete the expansion levels, the entrances to the Labyrinth will still open, even if you have never visited the Labyrinth. Thus, this is what happened to me: I started a new game as a Barbarian, began to go through the Labyrinth, and upon reaching level 15, I took the task “Jersey, Jersey” and began to go through the Nest. By that time, the Labyrinth had been completed to level 6, but the entrance to the caves was already open. I went through the Nest and killed the Defiler, and upon returning I discovered that the entrance to Hell in the form of a crack in the ground was also open. What happens is that the system considers that the dungeons of the add-on belong to the main Labyrinth and counts the number of levels completed, over time opening new entrances to the Labyrinth. I consider this to be a DevX problem, since when playing vanilla Diablo + Hellfire I did not find any self-opening entrances to the Labyrinth. I always opened them manually from the Labyrinth itself, leaving through them into the City from the Labyrinth. Now, having completed only 6 levels of the maze, I can immediately visit 13 :)

Also tested on Windows. The same thing happens.

### To Reproduce

1. Complete the Nest and dungeons with Na-Krul without completing the standard Labyrinth or completing it only briefly
2. You will enter the City after completing these dungeons or one of them completely. You will find open entrances to the Labyrinth (1 or 2) that were previously closed.

**Comment by StephenCWills** [comment]
What's actually happening is those entrances are opening based on character level. Maybe you don't remember seeing this when you played vanilla Hellfire, but that's how it works.
