### ISSUE TITLE
[Issue Report]: Changing Item Parameters [1.6.0-dev]

### ISSUE THREAD

**Issue by Sergei3000yt** [diasurgical/devilutionX#7029]
### Operating System

Android

### DevilutionX version

1.6.0-dev-debug

### Describe

For a long time I didn’t understand what the hell was going on in 1.6.0-dev-debug. I have already noticed 7 times that the game changes the parameters of my weapons or the weapons themselves. Firstly, the characteristics of any items can change at any time. Secondly, the equipment you use can disappear at any time. More details in the video.

In the video, the weapon has -83% damage to undead, although I bought this weapon with +278% damage.

### To Reproduce

Just play

### Expected Behavior

Let such crap not happen

### Additional context

https://github.com/diasurgical/devilutionX/assets/162808446/b7e07117-d015-4906-b843-d1d4c5914d58

**Comment by Sergei3000yt** [comment]
P.S. how to send videos weighing more than 10mb? :)

**Comment by DakkJaniels** [comment]
Provide an actual commit id please

**Comment by StephenCWills** [comment]
That's how the item works. It has the "decay" suffix.

https://github.com/diasurgical/devilutionX/blob/ad452cb6c03fd0f8ec6c2c616fb10a7f46fb5b4b/Translations/ru.po#L4455-L4458
