### ISSUE TITLE
[Issue Report]: Enabling Integer Scaling would yield lua\user.lua error

### ISSUE THREAD

**Issue by runlevel5** [diasurgical/devilutionX#7044]
### Operating System

Other (please specify)

### DevilutionX version

1.5.2

### Describe

Got `ERROR: Asset not found lua\user.lua` after enabling `Integer Scaling` for graphic option

### To Reproduce

1. Go to Settings and turn on Integer Scaling mode for graphic
2. Game crashes..

### Expected Behavior

Game does not crash

**Comment by DakkJaniels** [comment]
That's weird, lua isn't in 1.5.2. Are you sure you have the version correct?

**Comment by AJenbo** [comment]
If you don't have a custom lua script that is just a notice, not really an error

**Comment by AJenbo** [comment]
And it's not related to any setting just to be clear, just part of 1.6.0-dev

**Comment by DakkJaniels** [comment]
> If you don't have a custom lua script that is just a notice, not really an error

Wouldn't the game crashing be an error?
