### ISSUE TITLE
Launching singleplayer campaign gets a debug error

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#707]
**Describe**
Loading existing character or creating a new one shows a debug error during loading screen

**To Reproduce**
1. Go to 'Singleplayer'
2. Click on existing character or create a new one
3. Click 'OK'
3. See error

**Expected behavior**
Character campaign loads where it was saved, or in start position in case of new character.

**Screenshots**
![DPF1RPXYTO](https://user-images.githubusercontent.com/4958520/79320988-57101780-7f13-11ea-9215-300ed3dedd73.png)

**Additional context**
DevilutionX was compiled on Windows 10, using Visual Studio 2019 16.5.4 with x64-Debug configuration on `5641e2bde` commit.
Visual Studio shows the error might be here: https://github.com/diasurgical/devilutionX/blob/7108145a04c902a1638e93d937e48c47549257d0/Source/items.cpp#L1700

**Comment by AJenbo** [comment]
There are lots of uninitialized variables in the original code, this is simply a runtime warning from MSVC. If you press ignore things should work as expected. During release builds these issues are always ignored.

I'm closing this issue as it is covered by https://github.com/diasurgical/devilutionX/issues/279

**Comment by tsunamistate** [comment]
Yes, when pressing "Ignore" the game launches, also it reappears when you reenter Town.

**Comment by AJenbo** [comment]
Turns out this actually was a bug on our part and not present in the original game. Thank you for bringing attention to it. It has now been fixed upstream and will be merged here at the next merge (probably later this week):
https://github.com/diasurgical/devilution/commit/fe82c0b1f17077b3d9a4586cc78fe2be8970f83b
