### ISSUE TITLE
Compiling MSVC x64-Release build fails with C1001 internal compiler error

### ISSUE THREAD

**Issue by tsunamistate** [diasurgical/devilutionX#708]
**Describe**
Attempting to compile x64-Release build on Visual Studio 2019 results in linking errors. x64-Debug build compiles fine and shows only warnings.

**To Reproduce**
1. Install needed 64 bit dependencies via vcpkg
2. Open Visual Studio
3. Open devilutionX project via "File - Open- CMake"
4. Choose "x64-Release" configuration
5. Click "Build - Build All"
6. See linking errors

**Expected behavior**
Compilation is successful and results in working `devilutionX.exe`

**Screenshots**
![2020-04-15_12-39-56](https://user-images.githubusercontent.com/4958520/79323377-caffef00-7f16-11ea-8f09-b3e1bd0bf539.png)

**Additional context**
* OS: Windows 10
* Compiler: Visual Studio 2019 16.5.4
* sdl2 2.0.10-3
* sdl2-mixer 2.0.4-9
* sdl2-ttf 2.0.15-3
* libsodium 1.0.18-2

**Comment by AJenbo** [comment]
Does it work under MSVC 2017? We do not have a Windows maintainer so it's limited how much we can test and fix MSVC specific issues.

Most of the errors show appear to be related to https://github.com/szewczukk/Radon and debug function. Can you check if it is indeed building the relevant parts in release mode, and maybe check the other issues with the Radon project.

**Comment by tsunamistate** [comment]
x64-Release does compile fine in VS2017, seems it's VS2019 specific.

Also, just to check I have made another build generating the VS solution in CMake-GUI, and it has a different error
`7>D:\src\devilutionX\Source\drlg_l3.cpp(1351): fatal error C1001: Internal compiler error.
7>(compiler file 'd:\agent\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 182)
7> To work around this problem, try simplifying or changing the program near the locations listed above.
7>If possible please provide a repro here: https://developercommunity.visualstudio.com
7>Please choose the Technical Support command on the Visual C++
7> Help menu, or open the Technical Support help file for more information
7>  link!InvokeCompilerPassW()+0x2c6e4
7>  link!InvokeCompilerPassW()+0x2c6e4`

**Comment by AJenbo** [comment]
That looks like a bug in msvc, maybe you can get them to help with solving it

**Comment by tsunamistate** [comment]
Is this really MSVC bug? Around 2 months ago Release build was building fine without any errors.

**Comment by AJenbo** [comment]
I so no other way of interpreting this message:
> Internal compiler error ... If possible please provide a repro here: https://developercommunity.visualstudio.com, Please choose the Technical Support command on the Visual C++ 7> Help menu

Microsoft is basically asking you to help them solve the issue.

And after all it still works in MSVC 2017, and all other compilers that we are testing. The mentioned code also hasn't changed for 6 months.

**Comment by glebm** [comment]
@tsunamistate in the first screenshot it looks like the Release build is being linked against Debug libraries, or perhaps the other way around

**Comment by glebm** [comment]
is your cmake at least v3.14? From what I can tell, VS2019 is not supported in versions below v3.14.

**Comment by AJenbo** [comment]
I think MSVC came with CMake 3.10 build in.

**Comment by glebm** [comment]
It works for me with VS2019

**Comment by tsunamistate** [comment]
Alright, I have deleted the repo, cloned it again and rebuilt the project - Radon.lib errors are gone, and I'm only left with `C1001 compiler error` in `drlg_l3.cpp`, line 1351
@glebm looks like you are right that build was linked against wrong libraries.
I will try to report the C1001 to MSVC, but think this should be left open

**Comment by glebm** [comment]
I've updated my VS2019 and I now see the same bug in the compiler error.
Looks like this bug has been introduced recently.

It's not a DevilutionX bug though, so I think we should close this as "wontfix".

**Comment by glebm** [comment]
The x64-Debug build works

**Comment by tsunamistate** [comment]
Thank you for helping me in identifying the problem, I have reported this bug to MSVC team:
https://developercommunity.visualstudio.com/content/problem/995884/internal-compiler-error-c1001-in-x64-release-build.html
I really appreciate this project, even though I have no nostalgia with Diablo, you've gotta respect the classics!

**Comment by AJenbo** [comment]
Thanks for taking it all the way :)

**Comment by tsunamistate** [comment]
BTW @AJenbo @qndel I just got news from MSVC team, that compiler bug that I filed as a result of this issue has been fixed in Visual Studio 17.3.6 🎉
Yes, two years later, but better late than never
https://developercommunity.visualstudio.com/t/Internal-compiler-error-C1001-in-x64-Rel/995884#T-N10196234


Should we revert #973? Or `#if (_MSC_VER >= 1920)` doesn't apply to VS2022 anyway?

**Comment by qndel** [comment]
lol, that makes me a bit depressed - I've also found a compiler bug while poking tchernobog, if I have to wait that long to get it fixed... 😢

**Comment by glebm** [comment]
It's good motivation to switch to the clang compiler backend ;)

**Comment by AJenbo** [comment]
It's the webkit of compilers :)
