### ISSUE TITLE
A place to hang out together

### ISSUE THREAD

**Issue by grepwood** [diasurgical/devilutionX#71]
Is there a place like that where devs and users could converse?
Personally I'm all in favor of IRC and Tox :)

**Comment by MBeijer** [comment]
Discord is the place you're looking for. A link is in the README.md file
for the repo.

**Comment by grepwood** [comment]
Discord? The place where people do @everyone for most benign, uninteresting reasons? ;)

**Comment by AJenbo** [comment]
They don't on our server 😜

**Comment by CubeTheThird** [comment]
Not gonna lie, I had to look over the README like 5 times before I spotted the discord link :p

**Comment by AJenbo** [comment]
Yeah I think it wouldn't hurt with the word "chat" and a logo added to the line

**Comment by AJenbo** [comment]
fixed 
![image](https://user-images.githubusercontent.com/204594/55268125-60d2c880-5287-11e9-8903-60a40de7b840.png)

**Comment by NeonLightning** [comment]
discord link needs updating i'm getting invalid link.

**Comment by qndel** [comment]
@NeonLightning msg Qndel#2237
