### ISSUE TITLE
[Issue Report]: Unique rings and amulets drop are always the same.

### ISSUE THREAD

**Issue by OMightyBuggy** [diasurgical/devilutionX#7109]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

Every drop of unique rings and amulets are always the same. Acolyte's Amulet and Gladiators Ring. Quest rings and amulets are correct. I have stacks of the Acolyte's Amulet and Gladiators Ring.

### To Reproduce

Kill unique bosses, find a unique ring or amulet and it is always the same.

### Expected Behavior

Maybe one of the many other rings or amulets?

**Comment by StephenCWills** [comment]
Try farming unique rings and amulets in Nightmare or Hell Cathedral.

**Comment by StephenCWills** [comment]
It's hard to accurately apply labels to this issue because it's too specific to one player's experience. Given that we have two PRs already, I don't think it needs to be tracked. Rather than generalizing it and filling it out with more accurate information, I think it's easier to just close it.

**Comment by OMightyBuggy** [comment]
I will keep farming. I am just getting tired of the drops being the same when it is rings and amulets. I will start farming Nightmare.

**Comment by DakkJaniels** [comment]
That's pretty much what you are going to find in multiplayer Hellfire for any monster at level 10 and above.

**Comment by OMightyBuggy** [comment]
> That's pretty much what you are going to find in multiplayer Hellfire for any monster at level 10 and above.

That now makes sense. But also dang...
