### ISSUE TITLE
[Issue Report]: Hellfire spells stay dormant if you switch to Classic.

### ISSUE THREAD

**Issue by D1-Constantine** [diasurgical/devilutionX#7111]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

So a new player gave me his files to fix his HP/Mana as he was hit by Black Death and so on, once I inspected him char in Vanilla he had slvl Nova and was triggering the *SPELL HACKS trigger. The spell itself was not usable but my guess is it stayed dormant just like my slvl 15 Infravision on the Warrior, thus if I use a scroll the duration will be longer as it will take an effect that spell level. 

Without saying this can cause errors if the anti-hack/cheat system is brought back again.

### To Reproduce

1. Go to Hellfire
2. Learn a Classic compatible Spell from a Book
3. Transfer your char to Classic
4. Go to Vanilla and inspect that char via the old tools, or cast a scroll/staff with that spell
5. Dormant spell effect should take place

### Expected Behavior

Non Classic learnable Spells Levels Should be deleted upon changing from Hellfire to Classic

### Additional context

The list from the tool:

XXXXXX
Warrior            Experience 1310707109
Level 50           Next Level 1583495809
                         Gold 0     
Attribute Base\Now
 Strength 250 260   Damg 142    152     +Bonuses     Mods
 Vitality 100 110   Life 317    317     633    633    (1)     (316)
    Magic 50  60    Mana 90     90      252    252    (-8)    (98)
Dexterity 60  70      AC 71                           (-7)    
      Add 0      Shrines 68     (135)
 Resistances:  75% Magic,  71% Fire,  71% Lightning

Helmet 02:DC1850B632:34 Royal Circlet 40_40 +10a +40bm +10%Lr
Armour 10:3221287AD9:39 Diamond Robe of the whale 5_24 +95L +58%rm
<-Hand 00:DC24355CB3:85 King's Hammer of haste 5<9_100(50) +83%th +155%h FA3 R40s
->Hand 08:1E475D9B56:4B Obsidian Shield of the tiger 12_60(50) +42L +34%ra R60s
Amulet 01:1E0E37A83F:UD Dragon's Amulet of the tiger +50L +54bm
<-Ring 01:1E0DEAB2DE:UC Dragon's Ring of the lion +54L +58bm
->Ring 01:1E22E23616:UC Obsidian Ring of the lion +55L +37%ra

11 Blood Star       13 Bone Spirit      15 Chain Lightning  15 Charged Bolt     
13 Elemental        15 FIRE BALL        15 Firebolt         15 Fire Wall        
15 Flame Wave       15 Flash             9 Golem            15 Guardian         
15 Healing          12 Heal Other       15 Holy Bolt        15 Inferno          
15 Lightning        15 Mana Shield      15 Phasing          12 Stone Curse      
14 Telekinesis       9 Teleport         15 Town Portal       **4~{Nova}**           

Belt01    ( EMPTY )     ( EMPTY )
Belt02    ( EMPTY )     ( EMPTY )
Belt03    ( EMPTY )     ( EMPTY )
Belt04    ( EMPTY )     ( EMPTY )
Belt05    ( EMPTY )     ( EMPTY )
Belt06    ( EMPTY )     ( EMPTY )
Belt07    ( EMPTY )     ( EMPTY )
Belt08    ( EMPTY )     ( EMPTY )

**Comment by kphoenix137** [comment]
Good find. I believe nova increases in damage the higher you level it up, so this is actually a big deal since you get a more powerful nova scroll or staff in Diablo as a result.

**Comment by DakkJaniels** [comment]
Fixing character HP/Mana?? 🚔 👮🏽

**Comment by D1-Constantine** [comment]
> Good find. I believe nova increases in damage the higher you level it up, so this is actually a big deal since you get a more powerful nova scroll or staff in Diablo as a result.

Exactly, The Infravision I have from D+ also increase the scroll duration by a very long time. Guess people have to use DoomGaze if they want to stay legit, er ? What a day to live in :-D

**Comment by kphoenix137** [comment]
> > Good find. I believe nova increases in damage the higher you level it up, so this is actually a big deal since you get a more powerful nova scroll or staff in Diablo as a result.
> 
> Exactly, The Infravision I have from D+ also increase the scroll duration by a very long time. Guess people have to use DoomGaze if they want to stay legit, er ? What a day to live in :-D 

Will fix tonight

**Comment by kphoenix137** [comment]
https://github.com/diasurgical/devilutionX/pull/7112
