### ISSUE TITLE
[Issue Report]: Butcher did not drop his unique cleaver

### ISSUE THREAD

**Issue by Avalancs** [diasurgical/devilutionX#7124]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

I tried out DevilutionX for the first time with my Hellfire save, killed the Butcher on Hell difficuly, and he dropped a small axe of might instead of his signature unique cleaver. I think it the original game the cleaver dropped 100% of the time?

### To Reproduce

1. Start a new game in Hellfire on Hell difficulty
2. Kill Butcher
3. Check dropped item

### Expected Behavior

Butcher should drop his signature unique cleaver

**Comment by yuripourre** [comment]
@Avalancs just to clarify, are you playing Single or Multiplayer?

**Comment by Trihedraf** [comment]
Not a bug. This was changed when singleplayer quests were added to multiplayer so only normal difficulty monsters will drop quest uniques.

**Comment by Avalancs** [comment]
Sorry, playing single player. Now the tainted waters quest gave me a regular magic ring as well.

**Comment by Avalancs** [comment]
Maybe that should be in the readme then, quite a big change from the vanilla game in my opinion. Closing issue

**Comment by julealgon** [comment]
@Avalancs please use "Closed as not planned" for issues like this.

**Comment by Trihedraf** [comment]
Deleted comment said it was singleplayer.

**Comment by AJenbo** [comment]
Ok, well in that case I would point out that it's the 3 item mentioned as changes for 1.5.0: https://github.com/diasurgical/devilutionX/releases
