### ISSUE TITLE
[Issue Report]: Show item labels turns on by itself

### ISSUE THREAD

**Issue by Avalancs** [diasurgical/devilutionX#7129]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

The "Show item labels" option turns on by itself during single player, after about 20-30 minutes of playing. I have to go out to the main menu to turn it off. Is there some hidden shortcut that I accidentally press? Did not find anything about this in the readme.

### To Reproduce

1. Disable "Show item labels" in the options
2. Play the game for 20-30 minutes and labels will show themselves

### Expected Behavior

Option does not turn itself on

**Comment by DakkJaniels** [comment]
> Is there some hidden shortcut that I accidentally press?

Probably that. Left Ctrl, I think, turns that on.

**Comment by Avalancs** [comment]
Just tried it and it did not turn it on for me. Left alt temporary shows item names, but does not permanently turn it on. This happens after playing the game for some time :/

**Comment by Trihedraf** [comment]
It's right control by default.

**Comment by Avalancs** [comment]
Yup, right control does it. I might have deposited gold into the storage with it without realizing. Would be nice to put it in the readme, thank you for the answer!
