### ISSUE TITLE
[Issue Report]: Hellfire Murphy's shrine is not disabled by option

### ISSUE THREAD

**Issue by Avalancs** [diasurgical/devilutionX#7130]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

"Disable crippling shrines" does not disable Murphy's Shrine which breaks items or takes 1/3 of player's gold. Is this an oversight, or not considered "crippling" because it does not permanently lower stats?

### To Reproduce

1. turn "Disable crippling shrines" on
2. Find a Murphy's Shrine

### Expected Behavior

Murphy's Shrine should be disabled?

**Comment by DakkJaniels** [comment]
Already addressed in #6273

**Comment by Avalancs** [comment]
Thanks, closing ticket in favor of #6273

**Comment by DakkJaniels** [comment]
It should be closed as completed as it was

**Comment by kphoenix137** [comment]
> It should be closed as completed as it was

`not planned` has a definition of `Won't fix, can't repro, duplicate, stale` with the emphasis here being on duplicate
