### ISSUE TITLE
[Issue Report]: Blacksmith does not sell premium shields

### ISSUE THREAD

**Issue by Avalancs** [diasurgical/devilutionX#7131]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

Sorry for opening a lot of issues with questions today, but I seem to get confused by changes from the Vanilla game and can't tell if it's a bug or a feature.

I've been going to new game > hell with my lvl35 warrior many times today to check premium items on blacksmith (over 30-40 times I think) and I still haven't seen a single shield for sale. Armour/helmets are also pretty rare while two-handed swords and axes are pretty common, as are bows. I don't know about the distribution in the vanilla game, but the blacksmith definitely sold shields, and armor at a much higher rate.

### To Reproduce

1. Start a new game on Hell difficulty
2. Check Blacksmith's premium items and take note of different item types
3. Repeat many times

### Expected Behavior

Blacksmith should sell magic shields

**Comment by Trihedraf** [comment]
The randomness is unchanged from vanilla.

**Comment by StephenCWills** [comment]
It sounds like the gear you're wearing must be fairly expensive. Griswold in Hellfire attempts to give you better gear than what you already have. This can have the effect of making item types you're not carrying more common.

FYI, if you're not sure about whether something is a bug, you can join the Discord server to ask about it or create a discussion instead of an issue.

**Comment by Avalancs** [comment]
> It sounds like the gear you're wearing must be fairly expensive. Griswold in Hellfire attempts to give you better gear than what you already have.
It is, good to know! This would explain a lot, since now I can remember buying that shield yesterday, and I think it might have perfect stats for this level. Tried vanilla Hellfire and don't see shields coming up either...

> FYI, if you're not sure about whether something is a bug, you can join the Discord server to ask about it or create a discussion instead of an issue
Didn't realize there is a Discord, thank you for the suggestion!

**Comment by AJenbo** [comment]
> opening a lot of issues with questions

A general GitHub tip: https://github.com/diasurgical/devilutionX/discussions
