### ISSUE TITLE
[Feature Request]: Allow to choose language independently from Windows config

### ISSUE THREAD

**Issue by danmoller** [diasurgical/devilutionX#7136]
### Feature Type

Quality of Life

### Describe

I want to play the game in English, but my Windows is restricted to Portuguese. 
The quality of the PT-BR translation is no better than terrible. Word orders completely inverted, "names" treated as adjectives. 
I would like to simply be able to select English and play the original language independently from Windows.

**Comment by AJenbo** [comment]
setting -> language -> pick
