### ISSUE TITLE
[Issue Report]: Error when enabling upscaling - Renderer already associated with window

### ISSUE THREAD

**Issue by PcChip** [diasurgical/devilutionX#7141]
### Operating System

Linux x64

### DevilutionX version

1.5.2

### Describe

On first launch, upscaling was enabled and worked  
I disabled it to try other settings, but when trying to re-enable it, it crashes with this error every time now
I cannot find a config file anywhere to delete to start fresh again
![image](https://github.com/diasurgical/devilutionX/assets/28493830/9922060b-998e-4e55-8285-3cca7bd61e69)

### To Reproduce

Go to settings -> graphics  
enable "Upscaling"  

### Expected Behavior

no crash

**Comment by StephenCWills** [comment]
https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide

**Comment by PcChip** [comment]
Hi @StephenCWills  - thank you!

I was able to resolve it by deleting the config file there

not sure if you want to leave this issue open since technically it is still a problem, but it's easy enough to resolve

**Comment by StephenCWills** [comment]
We already have #5168 and #6055 so it's probably best to close this as a duplicate.
