### ISSUE TITLE
[Issue Report]:  CTD when entering the Crypt

### ISSUE THREAD

**Issue by bennori** [diasurgical/devilutionX#7154]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

When trying to enter the Crypt in Hellfire I get a CTD: "Failed to open file: objects\15door.cel

I cannot find that file neither on the Diablo-CD, Hellfire-CD, nor the installed folders.
Any tipps? 
Regards, benno

### To Reproduce

1. Click on opened Crypt
2. CTD

**Comment by qndel** [comment]
can you try to get a fresh copy of your hellfire MPQ files?

**Comment by bennori** [comment]
That actually worked, thanks a lot!

**Comment by ozmatox** [comment]
Hi, damnn i have the same issue in hellfire on Android, when I want to enter to the crypt I have issue.I Put the fresh HELLFIRE.MPQ to directory but steel won't work ;(

![Image](https://github.com/user-attachments/assets/6ea945aa-742a-49d7-b24d-5893371bc1c8)

**Comment by AJenbo** [comment]
Suggested solutions:
- Get the game from GOG
- Get the game from Blizzard
- Polish your CD and see if it reads correctly this time

**Comment by ozmatox** [comment]
Ok I have original iso and now wor perfectly 
Thx!
Now, I'm back to the 🎮
