### ISSUE TITLE
Premium items

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#716]
I have to complain about Griswold.
He has dared to sell normal items under premium items since commit 9a5ff805ed0c70d95e973012c93ae3dbea8245cb.
![inv](https://user-images.githubusercontent.com/45902449/80137988-6e4ea500-85a4-11ea-941a-69a59c96a5ec.png)

**Comment by qndel** [comment]
what XD

**Comment by qndel** [comment]
how can this affect griswold?

**Comment by Chance4us** [comment]
In fact, it is strange. It should be checked again. But it seems to affect him.

**Comment by qndel** [comment]
there is no way for this to affect anything as this only moves a hardcoded thing to function arguments which were unused befoer and this function gets called only once, if this affects griswold then all I know about C++ is wrong

**Comment by Chance4us** [comment]
I tested it again and it appears to be another commit that is causing the behavior.

**Comment by Chance4us** [comment]
Can you test and  confirm the bug?

**Comment by qndel** [comment]
checked 3 times, works fine for me

**Comment by Chance4us** [comment]
Thank you. I will continue to check why it happens.

**Comment by Chance4us** [comment]
It seems to be commit 7108145a04c902a1638e93d937e48c47549257d0.

**Comment by Chance4us** [comment]
So that it can be seen you have to scroll through the whole list.

**Comment by Chance4us** [comment]
It it definitely commit 7108145.

**Comment by Chance4us** [comment]
Issue found. The following commit have to be applied to resolve it.

https://github.com/diasurgical/devilution/commit/fe82c0b1f17077b3d9a4586cc78fe2be8970f83b

**Comment by qndel** [comment]
Duuude .... and you made me go through that big fat merge commit xD

**Comment by Chance4us** [comment]
I'm sorry. Was not an intention.

**Comment by AJenbo** [comment]
It will be merged this weekend.
