### ISSUE TITLE
[Issue Report]: Visual Studio Build failed

### ISSUE THREAD

**Issue by ZhiZe-ZG** [diasurgical/devilutionX#7165]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

I tried use the Visual Studio and CMake to build devilutionX on Windows. It's failed. It Should be a path error. 

The `$(VSINSTALLDIR)` in `devilutionx.vcxproj` should be `C:\Program Files\Microsoft Visual Studio\2022\Community` （the default installation）. But here the `$(VSINSTALLDIR)` may be `C:\`. I don't know how to change it.

```
1>------ Build started: Project: devilutionx, Configuration: Debug|x64 ------
1>E:\GitRepositories\devilutionX\uwp-project\devilutionx.vcxproj(42,5): error MSB4019: The imported project "C:\Common7\IDE\Extensions\Microsoft\VsGraphics\ImageContentTask.props" was not found. Confirm that the expression in the Import declaration "\Common7\IDE\Extensions\Microsoft\VsGraphics\ImageContentTask.props" is correct, and that the file exists on disk.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
Build failed.
```

### To Reproduce

1. follow the build guide to build the devilutionX on Windows via Visual Studio.
2. press Build=>Build devilutionx.sln
3. build failed

**Comment by StephenCWills** [comment]
You do not build `devliutionx.sln`. You should be building `devilutionx.exe`.

FYI, we use the issue tracker for keeping track of issues with we need to address with DevilutionX. It's not meant for users to ask what they did wrong when following the instructions. It would help to keep things organized if you could use the Discussions tab or the Discord server instead.

**Comment by ZhiZe-ZG** [comment]
@StephenCWills Thank you very much for your reply. I'm new to GitHub, so I'm not familiar with the process of asking questions. I'll keep an eye out for Discord and Discussions.
