### ISSUE TITLE
[Issue Report]: Mana cost of certain spells is lower than expected

### ISSUE THREAD

**Issue by Fed64** [diasurgical/devilutionX#7171]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

Certain spells have lower cost when learned the first time on a new character.
-  Stone Curse: 1st level expected 60, was 45; learned another level and it did not reduce cost by 2 but 3
![image](https://github.com/diasurgical/devilutionX/assets/53566426/2b7af0c4-3702-4adb-92ee-722e65811edb)
Stone curse level 2 should have cost of 58.
- Town Portal: same picture as above; Town Portal cost for level 4 should be 23 not 19.
- Flash: 1st level expected cost is 30, not 22 as in above pic.
- Chain Lightning: 1st level expected cost 30, was 22
![image](https://github.com/diasurgical/devilutionX/assets/53566426/b2ddb99d-2a67-4469-8652-e4b625debba4)

There are other wrong cost as well in the two pictures I attached (Guardian for example).

### To Reproduce

For this type of issue I don't have direct steps to reproduce but I suspect the cause to be related to some kind of interaction between different characters.
The screenshots above were captured on a Rogue character. Some of the erroneous spell cost values seem to be inherited from another character (a sorcerer). Some of the books used on the Rogue were found on different characters (Sorc and War) and transferred with the stash.
Books found on the Warrior and used on the Sorc seem to have correct costs but that might be because I used almost no books on the warrior and thus no costs could be "inherited".
If needed I can provide more screenshots or the save files.

**Comment by Trihedraf** [comment]
Rogue's have 75% mana cost compared to warrior and sorcerer.

**Comment by julealgon** [comment]
> Rogue has 75% mana cost compared to warrior and sorcerer.

Makes me wonder @Trihedraf ... is there an issue anywhere proposing a way to expose these class "traits" somewhere in the UI? The character creation screen could have a place to put those in for example.

Stuff like the mana cost reduction, potion bonuses, block % bonuses, etc could be listed somewhere. Would be a cool addition IMHO and not very intrusive as it doesn't change behavior.

If a more comprehensive UI was created, it could probably show even deeper, more specific details such as "how much +life/mana per vitality/energy/clvl up, what the maximums stats are for each attribute (I don't recall this being shown anywhere as well), hit recovery speeds, etc.
