### ISSUE TITLE
Game won't use whole screen

### ISSUE THREAD

**Issue by morpheus092511** [diasurgical/devilutionX#7172]
### Operating System

Android

### DevilutionX version

1.5.2

### Describe

Running android 15 pixel 7 game will only use center area of screen and selecting fit to screen actually seems to make it use a smaller area of the screen
![Screenshot_20240703-065922](https://github.com/diasurgical/devilutionX/assets/117562472/17331290-d19a-4c7e-bbc3-bac8d05edead)
![Screenshot_20240703-065933](https://github.com/diasurgical/devilutionX/assets/117562472/66c0e4e3-7bf3-4652-9072-43b8a20ccede)
![Screenshot_20240703-070001](https://github.com/diasurgical/devilutionX/assets/117562472/85a7884c-45b3-4d2c-9811-a05ef0a2eb66)
![Screenshot_20240703-070013](https://github.com/diasurgical/devilutionX/assets/117562472/835e1a99-d8f3-4fb8-be51-2f75691e323e)
![Screenshot_20240703-070034](https://github.com/diasurgical/devilutionX/assets/117562472/d0782cf5-199a-4eea-bc1d-5631fb894771)
![Screenshot_20240703-070347](https://github.com/diasurgical/devilutionX/assets/117562472/b9ec4b30-481b-4c0d-aa84-e617a45bff11)

### To Reproduce

Install game
 start game 

### Expected Behavior

Start game go to options fit to screen causes game to use the whole screen

### Additional context

![Screenshot_20240703-070347](https://github.com/diasurgical/devilutionX/assets/117562472/290fcdf9-ea22-484d-a700-e0dfefd2f2de)
![Screenshot_20240703-070034](https://github.com/diasurgical/devilutionX/assets/117562472/a799b64b-9716-4106-88bc-1580d8eab05c)
![Screenshot_20240703-070013](https://github.com/diasurgical/devilutionX/assets/117562472/72c13e46-dbd9-4a8c-bef0-1fd5df512f4a)
![Screenshot_20240703-070001](https://github.com/diasurgical/devilutionX/assets/117562472/ca6d695b-0da2-40c3-8628-f3f5a60e5908)
![Screenshot_20240703-065933](https://github.com/diasurgical/devilutionX/assets/117562472/904b6a27-dd4f-47c9-982f-d9661eb9d325)
![Screenshot_20240703-065922](https://github.com/diasurgical/devilutionX/assets/117562472/8b49d620-4fa3-4b55-8bac-f9afa9e04866)

**Comment by DakkJaniels** [comment]
Do you have a screenshot of how it looks in game? I don't think the menu screen uses the sides of the screen.

**Comment by DakkJaniels** [comment]
On Android 14 on Pixel 8 Pro:
![Screenshot_20240703-071109.png](https://github.com/diasurgical/devilutionX/assets/6080734/e8a1a518-da89-4afc-9087-5e971e111e62)

![Screenshot_20240703-071135.png](https://github.com/diasurgical/devilutionX/assets/6080734/7ae56b15-44cf-4858-abe0-971946acda71)

**Comment by morpheus092511** [comment]
Here screen shot in game this as big as I can get it 
![Screenshot_20240703-071521](https://github.com/diasurgical/devilutionX/assets/117562472/b866164e-fbfe-4163-95bb-eef76f28e14f)

**Comment by Trihedraf** [comment]
Turn integer scaling off and fit to screen on.

**Comment by morpheus092511** [comment]
Thanks you that fixed it much appreciated

**Comment by AJenbo** [comment]
@morpheus092511 was this you? Are you still having issues?

![image](https://github.com/diasurgical/devilutionX/assets/204594/9341a643-2bcd-4596-b4f4-4bea44e1ada7)
