### ISSUE TITLE
[Feature Request]: Documentation is incomplete

### ISSUE THREAD

**Issue by Gunnar-GO** [diasurgical/devilutionX#7188]
### Feature Type

Quality of Life

### Describe

I wanted to set the deadzone for the xbox port, thankfully i found a setting for but i don't know which values are expected.

https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide 

if i set 20 the game doesn't start. i found in old issues, values of 0.07 and other .. so i will try these later.

**Comment by Gunnar-GO** [comment]
even the mentioned 0.7 or 0.070000 didn't work, it results like other values in a black screen at start.

**Comment by Trihedraf** [comment]
If you delete the line and run the game again it will autocreate the default.

**Comment by AJenbo** [comment]
Use Discussion for support

**Comment by Gunnar-GO** [comment]
i didn't asked for support i pointed out that, the documentation is incomplete, 'cause it lacks any information or example of expected entries.

@Trihedraf empty after the = ... so it is still open which data is expected.

**Comment by DakkJaniels** [comment]
What version of the game are you running? It should default to 0.07. It should be a float less than or equal to 1.

**Comment by qndel** [comment]
> i didn't asked for support i pointed out that, the documentation is incomplete, 'cause it lacks any information or example of expected entries.
> 
> @Trihedraf empty after the = ... so it is still open which data is expected.

Feel free to fix it

**Comment by AJenbo** [comment]
The wiki is a community project where people try to help each other. Not finding the info you need there is support related.

The black screen could be an issue with NXDK not being able to parse the float value.

**Comment by Gunnar-GO** [comment]
i would add this info , if i could find valid informations about .. 

And your thinking would be a bug, that should be tested and reported.

**Comment by StephenCWills** [comment]
> i would add this info , if i could find valid informations about ..

DakkJaniels explained it. It's a floating-point value between 0 and 1. The default is 0.07.

> And your thinking would be a bug, that should be tested and reported.

Not to worry. #6967
