### ISSUE TITLE
[switch] SDL2 failes to build

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#719]
Recently builds for Nintendo Switch have been failing: https://circleci.com/gh/diasurgical/devilutionX/10870

`make[2]: *** No rule to make target '/opt/devkitpro/portlibs/switch/lib/libSDL2.so', needed by 'devilutionx.elf'.  Stop.`

I'm guessing this is because devkit-pro recently updated there SDL to 2.0.12 https://github.com/devkitPro/pacman-packages/commit/f4a071c99e1827917747630dbc420c33effd00ad#diff-debbdb4b70712bf95a0b2ca62209fd45

**Comment by rsn8887** [comment]
It seems there's a bug in your cmakelistsl:
```CMake Warning (dev) at /opt/devkitpro/portlibs/switch/lib/cmake/SDL2/sdl2-config.cmake:21 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
Call Stack (most recent call first):
  CMakeLists.txt:142 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
It is trying to use libsdl2.so (shared lib) but Switch doesn't have shared libs, only static libs (libsdl2.a)

**Comment by AJenbo** [comment]
The first filing commit is this https://github.com/diasurgical/devilutionX/commit/3227fea5c0926a661e38256600e37579605e4ff4 which doesn't change the build so it's all a bit odd to me.

**Comment by AJenbo** [comment]
The issue appears to be identical to the issue with building on Mac OS with SDL 2.0.12 https://github.com/Homebrew/homebrew-core/issues/52261

The issue was resolved in SDL here https://bugzilla.libsdl.org/show_bug.cgi?id=5039
So probably Devkit-pro needs to merge this patch for things to work.

**Comment by WinterMute** [comment]
Part of the issue here is that none of https://github.com/diasurgical/devilutionX/tree/master/CMake/switch should exist in your project. Most of those files have some fundamental errors but primarily these should be provided by the toolchain not by projects.

ADD_LIBRARY shouldn't be called with SHARED option on switch. This is an error.

**Comment by glebm** [comment]
> these should be provided by the toolchain not by projects.

Unfortunately, it seems like the toolchain authors don't want to support CMake:
https://github.com/devkitPro/docker/issues/3#issuecomment-473355590

Has this changed now?

**Comment by rsn8887** [comment]
I thought I fixed this issue with this PR?
https://github.com/diasurgical/devilutionX/pull/734

Is there still a problem even?

**Comment by WinterMute** [comment]
> > these should be provided by the toolchain not by projects.
> 
> Unfortunately, it seems like the toolchain authors don't want to support CMake:
> [devkitPro/docker#3 (comment)](https://github.com/devkitPro/docker/issues/3#issuecomment-473355590)
> 
> Has this changed now?

We don't want to encourage people to use cmake for no good reason. We provide Makefile based templates intended to encourage homebrewers to stick to a standard that allows them to collaborate on projects regardless of host OS. There are reasons for this that may not be apparent to anyone without experience of homebrew projects that barely managed to compile on the host OS of the original dev never mind anything else.

We also don't want terrible cmake templates proliferating and being copy pasta'd around random projects. 

I would rather have a proper cmake toolchain file provided by devkitPro than have people make their own cmake templates that are going to break if we refactor anything in the future.

**Comment by AJenbo** [comment]
> I would rather have a proper cmake toolchain file provided by devkitPro than have people make their own cmake templates that are going to break if we refactor anything in the future.

Sounds good, let us know when you provide such a toolchain so that we can make the switch.
