### ISSUE TITLE
[Issue Report]: Theo quest bug - Girl NPC not spawning after quest enabled in Settings

### ISSUE THREAD

**Issue by diademist** [diasurgical/devilutionX#7192]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

Theo quest after being enabled does not spawn the Little Girl NPC. 

### To Reproduce

1. Go to Settings
2. Then go to Gameplay
3. Turn 'Theo quest' ON
4. Start new game - NPC is nowhere to be found. 

### Expected Behavior

Expecting to see the quest NPC after enabling the option in the menu.

**Comment by AJenbo** [comment]
You need to enter the Nest first
