### ISSUE TITLE
[Issue Report]: Discord link seems to be broken

### ISSUE THREAD

**Issue by sjp761** [diasurgical/devilutionX#7195]
### Operating System

Other (please specify)

### DevilutionX version

1.5.2

### Describe

The Discord link in the github seems to have expired. I cannot access it at all

### To Reproduce

1. Click on Discord link
2. See that it expired

**Comment by AJenbo** [comment]
What link?

**Comment by ephphatha** [comment]
https://github.com/diasurgical/devilutionX/blob/63d525fe4715f492e5a0da82b97fee39f5dac3f1/README.md?plain=1#L38

Looks like the discord server dropped below level 3 and the custom link was deactivated. Need two more boosts for it to come back

**Comment by AJenbo** [comment]
Ok, I payed the Discord ransom fee, if anyone else has an option to boost the server I would appreciate it.
