### ISSUE TITLE
[Issue Report]: White fire art in main menu

### ISSUE THREAD

**Issue by SODIX** [diasurgical/devilutionX#7199]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

When switching resolution in other than 4:3, white fire art in main menu is goes away.

### To Reproduce

1. Click to options
2. Click to video options
3. Change resolution to 16:9 or 16:10

### Expected Behavior

Art in main menu should be visible at any resolution

### Additional context

![12312](https://github.com/user-attachments/assets/ce3fc645-02c6-46a7-94f1-8fcdd87afdf9)

**Comment by DakkJaniels** [comment]
Not sure what you mean:
(640x480)
![image](https://github.com/user-attachments/assets/4dde10d8-c8e1-4102-99fe-321273197709)
![image](https://github.com/user-attachments/assets/f61f4f88-ce87-48f5-931f-2dc4cbfead31)

(1920x1080)
![image](https://github.com/user-attachments/assets/af883a04-df81-487d-804b-5fcb119ff9ff)

**Comment by SODIX** [comment]
There is pink-white fire texture at menu, and it have a bug. For some reason it can not be captured at screenshot.

**Comment by DakkJaniels** [comment]
> There is pink-white fire texture at menu, and it have a bug. For some reason it can not be captured at screenshot.

Yes, I have it in my screenshot at 640x480 and at 1920x1080, unless there is something else I'm missing there.

**Comment by SODIX** [comment]
Can't see it in 800x600 and 900p(1440x900), and 720p. Bug also doubled by fact, that texture isn't visible in screenshot.

**Comment by DakkJaniels** [comment]
I don't understand what you mean, I see the white flame in both screenshots. It's just not in the settings menu.

**Comment by qndel** [comment]
take a picture with phone then? we don't really need screenshots that don't show any bug ...

**Comment by DakkJaniels** [comment]
800x600
![image](https://github.com/user-attachments/assets/42bef153-ff7a-4bce-9fca-c1cd0602d01e)

1600x900 (I didn't have 1440x900):
![image](https://github.com/user-attachments/assets/8e36b169-c907-4b88-ac13-638cb73a101e)

1280x720:
![image](https://github.com/user-attachments/assets/78873769-c7a6-4ddb-8598-b7c34b771cd4)

**Comment by julealgon** [comment]
Isn't the problem here related to the widescreen version of the background asset? Maybe OP is somehow missing that? Those live in a separate .MPQ file, right? Same as those extended loading screen backgrounds?

**Comment by StephenCWills** [comment]
@julealgon You must be talking about this.
https://github.com/diasurgical/devilutionX/blob/master/assets/ui_art/mainmenuw.clx

It goes in `devilutionx.mpq`, and it looks like this.
![mainmenuw_clx](https://github.com/user-attachments/assets/9b0eb1bb-da8e-4923-af3f-7ef44033c14c)

Unless you're seeing something I don't, neither his description nor his screenshot seem to indicate that he's missing this graphic, and I don't know how he could have lost it without losing the whole mpq.

**Comment by AJenbo** [comment]
Feel free to add relevant information, as it it just sounds like your screen is broken at best.

**Comment by SODIX** [comment]
![2342345234234234234](https://github.com/user-attachments/assets/a11f319c-2533-4aa8-a28d-593d095cdaa7)
I says about this FIRE art, it have a bug, and works only in a few in-game resolutions.

**Comment by SODIX** [comment]
@AJenbo

**Comment by AJenbo** [comment]
What bug? The fire is perfectly visible in all your pictures, maybe you just have bad screen settings that is making it to dark for you to see on screen.

> Can't see it in 800x600 and 900p(1440x900), and 720p. Bug also doubled by fact, that texture isn't visible in screenshot.

You posted a 800x600 with the fire in it, can you show a resolution where it's not working?

![image](https://github.com/user-attachments/assets/4b16adfe-f1c9-4510-8da0-199e62d8dc5c)

**Comment by SODIX** [comment]
This is 800x600
![Изображение WhatsApp 2024-07-23 в 11 01 23_8e3aa41b](https://github.com/user-attachments/assets/47a2711b-b29c-4b9a-9596-e3b149dfc8c8)

**Comment by julealgon** [comment]
@SODIX do you see the graphic if you bump the resolution to a multiple of 640x480? Like 1280x960?

It's weird to me because 800x600 is also a 4:3 resolution, yet it doesn't show...

**Comment by AJenbo** [comment]
what graphics card do you have

**Comment by SODIX** [comment]
> 1280x960

This resolution show needed graphics(fire).

@AJenbo RTX2060SUPER, monitor Samsung B1930(1440x900). Reopen the bug, confirmed by @julealgon

**Comment by DakkJaniels** [comment]
@SODIX Can you screenshot your graphics settings? and also screenshot your DevilutionX folder, with file sizes visible? @julealgon didn't confirm this as far as I can tell, there is only 1 picture from you showing the fire missing.

**Comment by AJenbo** [comment]
Is this a SDL1 build you are running?

**Comment by DakkJaniels** [comment]
It said Windows x64 in report, I had assumed it was just the release version, but probably good to confirm if @SODIX is building this instead of using release.

**Comment by SODIX** [comment]
I also use Linux, can confirm the same bug, on Linux(and even more, if you use wayland).

**Comment by DakkJaniels** [comment]
Why do you have all that other stuff in there? Extract DevilutionX to its own folder, and move the mpq's into that folder, then see if there is still an issue.

**Comment by AJenbo** [comment]
What did you do differently initially when you where able to post a 800x600 screen shots where the background shows up correctly?

**Comment by AJenbo** [comment]
> Why do you have all that other stuff in there?

I think that is mostly left overs from older versions

**Comment by StephenCWills** [comment]
> I also use Linux, can confirm the same bug, on Linux(and even more, if you use wayland).

Did you run your Linux tests on the same hardware?

**Comment by DakkJaniels** [comment]
> I think that is mostly left overs from older versions

Looks to me like it's extracted to Hellfire install folder from a CD.

Also diabdat.mpq look a bit small.

**Comment by SODIX** [comment]
@AJenbo This was 960x540. This shows graphics. 800x600 don't work.



> > I also use Linux, can confirm the same bug, on Linux(and even more, if you use wayland).
> 
> Did you run your Linux tests on the same hardware?

Yep. OpenSUSE Tumbleweed, Plasma5, Wayland, last proprietary drivers.

**Comment by SODIX** [comment]
> > I think that is mostly left overs from older versions
> 
> Looks to me like it's extracted to Hellfire install folder from a CD.
> 
> Also diabdat.mpq look a bit small.

This is Russian unofficial(still why?) localization, few bits here, few bits there.

**Comment by SODIX** [comment]
> even

![image](https://github.com/user-attachments/assets/96885cec-0295-42cd-853a-a9c86faebeaa)
Bug still there.

**Comment by SODIX** [comment]
I tested all my screenshots in GIMP(upped the brightness), yes in you turn up the brightness, you can see the art, but game will looks like crap, it's and resolution/brightness bug.

**Comment by DakkJaniels** [comment]
![image](https://github.com/user-attachments/assets/1133be11-fb2b-4c4c-9231-479853c7e998)
![image](https://github.com/user-attachments/assets/560c4929-69c5-4f74-ac8d-d2bef7206bd6)

Maybe it has to do with your monitor resolution. I can't select 1440x900 to test that myself.

**Comment by SODIX** [comment]
> ![image](https://private-user-images.githubusercontent.com/6080734/351412914-1133be11-fb2b-4c4c-9231-479853c7e998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTMwMDgsIm5iZiI6MTcyMTc1MjcwOCwicGF0aCI6Ii82MDgwNzM0LzM1MTQxMjkxNC0xMTMzYmUxMS1mYjJiLTRjNGMtOTIzMS00Nzk4NTNjN2U5OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTYzODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUwMDRiMjJhYjQ0YzgyNjNjYjNkYTZmNzBhZTEzZjY1ODU1YWQ1ZWE1MWRkYzY5ODdkYjE4ZGJkNmI2MWM3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hpnm_tXXDPgMuh3YmM14_yQYPF9qB-5E6-du62jNo3A) ![image](https://private-user-images.githubusercontent.com/6080734/351413036-560c4929-69c5-4f74-ac8d-d2bef7206bd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTMwMDgsIm5iZiI6MTcyMTc1MjcwOCwicGF0aCI6Ii82MDgwNzM0LzM1MTQxMzAzNi01NjBjNDkyOS02OWM1LTRmNzQtYWM4ZC1kMmJlZjcyMDZiZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMTYzODI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRiY2Q4MzAzMDIzOTliODlmYTlkMDliZjgwMzhkZWE4MjVhMjBkMmUyYTJiOGZjOGY5NmQ3ODk0MmRlYmJhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UiCGTBkfHg31-1fuM-iShX6tDHzPhueMxOuV8-4Z2g8)
> 
> Maybe it has to do with your monitor resolution. I can't select 1440x900 to test that myself.

Confirmed by two people, on Windows(me, @julealgon) and Linux(me). I will not play thimbles, my monitor is ok.

**Comment by DakkJaniels** [comment]
@SODIX where did @julealgon confirm this? I see no screenshots from him, but maybe I missed it. 

I'm not sure what "I will not play thimbles" means, probably some idiom that doesn't translate. I'm trying to figure out where your issue is, because I'm not having it using the same settings as you. The only difference I can tell, so far, is that my monitor is set to 2560x1440. I tried setting it to 1600x900 and did not experience the missing fire issue.

**Comment by StephenCWills** [comment]
> Confirmed by two people, on Windows(me, @julealgon) and Linux(me). I will not play thimbles, my monitor is ok.

To be clear, julealgon did not explicitly confirm the issue. He was asking you whether it works at 1280x960 because you erroneously reported that it only works on 4:3 resolutions.

I still don't see anything in the code that would make the appearance of the background art change based on resolution, except maybe this.

https://github.com/diasurgical/devilutionX/blob/3555346ed8d4a515162eb82df3ad9729f2386e2c/Source/DiabloUI/diabloui.cpp#L732-L736

What's clear to me is that you are the only one here who can reproduce the issue so it seems to be something specific to your setup. It could be either your graphics card, your graphics driver, your Russian unofficial MPQ, or something I haven't even thought of. I'm sorry, but there is just not enough information for us to even approach a fix for this based on what you provided.

**Comment by SODIX** [comment]
Ok, I can delete ru.mpq, and there is typo it's DON'T work on 4:3 resolution.
![image](https://github.com/user-attachments/assets/732b5739-047c-4c9f-a499-b41aa7b5b3d9)
![image](https://github.com/user-attachments/assets/e53f140a-d728-4021-9e8a-ef26614dfc17)

**Comment by SODIX** [comment]
Can confirm, I can see graphics, on phone(Samsung M12, Android, Whatsapp), screenshot from PC. Still I'm think it's a bug.

**Comment by DakkJaniels** [comment]
Isn't that a picture of it working? Can you provide screenshot of graphics settings and screenshot of it not working? Or are you saying it shows up in the screenshots, but doesn't show up on your monitor?

It's very confusing what resolutions you say it's working at and what resolutions you say it's not working at.

**Comment by SODIX** [comment]
> Isn't that a picture of it working? Can you provide screenshot of graphics settings and screenshot of it not working? Or are you saying it shows up in the screenshots, but doesn't show up on your monitor?
> 
> It's very confusing what resolutions you say it's working at and what resolutions you say it's not working at.\
> 
> Edit: just noticed this:
> 
> > I tested all my screenshots in GIMP(upped the brightness), yes in you turn up the brightness, you can see the art, but game will looks like crap, it's and resolution/brightness bug. Only few resolutions(1280x960 for example), show needed art with default brightness.
> 
> Seems like it's an issue with your hardware and not an issue with the program 🤷🏽‍♂️

I tested hardware with different regimes and full brightness (monitor: magicbright, magicolor). Don't work on PC. But, if I change resolution to 1280x960 or 960x540 everything work as fine.

**Comment by DakkJaniels** [comment]
As far as I can tell, you are posting screenshots where the fire is clearly visible to all of us, but it's not visible to you. Like here, it seems you don't see the fire?

> Ok, I can delete ru.mpq, and there is typo it's DON'T work on 4:3 resolution. ![image](https://private-user-images.githubusercontent.com/22780561/351419797-732b5739-047c-4c9f-a499-b41aa7b5b3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTQ3NzYsIm5iZiI6MTcyMTc1NDQ3NiwicGF0aCI6Ii8yMjc4MDU2MS8zNTE0MTk3OTctNzMyYjU3MzktMDQ3Yy00YzlmLWE0OTktYjQxYWE3YjViM2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE3MDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZmNhYjY1MGQ4NTdjYmJlMWIzNGMwMjA4YWMxYjIxY2VhZmE5YzNmYWIwNjQwNDVhNzRkNTc5Y2EyYjAxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oTJYr0vU8-0-4VWmMUVyIagIGoEWm-fOm_b4VeJaXHI) ![image](https://private-user-images.githubusercontent.com/22780561/351419836-e53f140a-d728-4021-9e8a-ef26614dfc17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTQ3NzYsIm5iZiI6MTcyMTc1NDQ3NiwicGF0aCI6Ii8yMjc4MDU2MS8zNTE0MTk4MzYtZTUzZjE0MGEtZDcyOC00MDIxLTllOGEtZWYyNjYxNGRmYzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE3MDc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NDVmNjI5ZDJlNGExMThhNzQwYTU5Y2IyOWVkZWJjNmM2M2E3ZTJmNjExYWMwYmRiMjg5MWVmYTUwMjM1YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YWNtbVlTR0wA-Dxukf6Vitz8s18xlLBW1f-bwgAWdC8)

**Comment by SODIX** [comment]
@DakkJaniels 

> This is 800x600 ![Изображение WhatsApp 2024-07-23 в 11 01 23_8e3aa41b](https://private-user-images.githubusercontent.com/22780561/351238796-47a2711b-b29c-4b9a-9596-e3b149dfc8c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTQxMjcsIm5iZiI6MTcyMTc1MzgyNywicGF0aCI6Ii8yMjc4MDU2MS8zNTEyMzg3OTYtNDdhMjcxMWItYjI5Yy00YjlhLTk1OTYtZTNiMTQ5ZGZjOGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE2NTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzExYzFmMjk0YThlZmY3ZTg2MGQ5MGI0MTczMWJjMjhkODQ2NjE4YTA0ZTI1ZTE1YWJmODRlYmE0YWI1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsyunW6fllI0S9Hkvk6DZL6cp227hTHTA29wp0RUjaI)

**Comment by DakkJaniels** [comment]
> @DakkJaniels
> 
> > This is 800x600 ![Изображение WhatsApp 2024-07-23 в 11 01 23_8e3aa41b](https://private-user-images.githubusercontent.com/22780561/351238796-47a2711b-b29c-4b9a-9596-e3b149dfc8c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NTQxMjcsIm5iZiI6MTcyMTc1MzgyNywicGF0aCI6Ii8yMjc4MDU2MS8zNTEyMzg3OTYtNDdhMjcxMWItYjI5Yy00YjlhLTk1OTYtZTNiMTQ5ZGZjOGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE2NTcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzExYzFmMjk0YThlZmY3ZTg2MGQ5MGI0MTczMWJjMjhkODQ2NjE4YTA0ZTI1ZTE1YWJmODRlYmE0YWI1N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsyunW6fllI0S9Hkvk6DZL6cp227hTHTA29wp0RUjaI)

Right, the only time we see it not show up is with a picture of your screen. Your screenshots all include the fire. Seems like a settings/hardware problem.

**Comment by julealgon** [comment]
@SODIX 
> ...and there is typo it's DON'T work on 4:3 resolution.

Oh...... that changes things. It then becomes more likely to be related to your Russian original data files since I'm pretty sure DevilutionX just reuses the resources from the original MPQ directly using known keys for the original 4:3 assets. It would be nice if you could retest using the original US .mpq from the US release (if you have access to that).

BTW, like others have mentioned, I did not _confirm_ the bug: I just asked you extra questions to try to understand where the problem could be. I don't have access to your Russian release to test this.

**Comment by DakkJaniels** [comment]
@SODIX do you see the fire in all of the screenshots I've posted?

**Comment by StephenCWills** [comment]
To be very clear, 100% of the time, regardless of the resolution, the game draws the widescreen background art followed by the original 640x480 background art.

The only thing that depends on the resolution is the `UiClearScreen()` function. If the resolution is larger than 640x480, it will draw a black rectangle before drawing the background art in order to clear portions of the screen that aren't covered by the background art.

Best I can figure is that maybe this has something to do with double buffering, but I can't reproduce it even with `Upscale: OFF`.

**Comment by DakkJaniels** [comment]
> Best I can figure is that maybe this has something to do with double buffering, but I can't reproduce it even with `Upscale: OFF`.

Based on what he said, I'm not sure it's even related to that. He said he can see the fire in his screenshots if he adjusts them in GIMP, so it's there, he just can't see it on his monitor.

> I tested all my screenshots in GIMP(upped the brightness), yes in you turn up the brightness, you can see the art, but game will looks like crap, it's and resolution/brightness bug. Only few resolutions(1280x960 for example), show needed art with default brightness.

**Comment by SODIX** [comment]
> related to that. He said he can see the fire in his screenshots if he adjusts them in GIMP, so it's there, he just can't see it on his monitor.
> 
> >

I can't see it even on photo, on phone.



> To be very clear, 100% of the time, regardless of the resolution, the game draws the widescreen background art followed by the original 640x480 background art.
> 
> The only thing that depends on the resolution is the `UiClearScreen()` function. If the resolution is larger than 640x480, it will draw a black rectangle before drawing the background art in order to clear portions of the screen that aren't covered by the background art.
> 
> Best I can figure is that maybe this has something to do with double buffering, but I can't reproduce it even with `Upscale: OFF`.

You do code, and fix bugs. So you can see better.

**Comment by DakkJaniels** [comment]
> > related to that. He said he can see the fire in his screenshots if he adjusts them in GIMP, so it's there, he just can't see it on his monitor.
> > >
> 
> I can't see it even on photo, on phone.

Yes, I can't see it on the photo of your monitor either. Every other screenshot you've posted includes the fire that is easily seen on (my) PC.

I will note, however, that when I looked at this GitHub issue on my phone. it is much harder to see the fire on many of the screenshots. Again, it seems to me like this is a hardware/settings issue, not a program issue.

**Comment by SODIX** [comment]
> issue

It's the program bug, because of you can't set brightness up to see fire, and have the still the same default darkness in-game.

**Comment by Trihedraf** [comment]
It's probably the monitor and OS setting for full vs limited RBG being mismatched causing the colors to be crushed, so it can't be seen on the monitor because there isn't enough contrast between the dark colors.

**Comment by AJenbo** [comment]
> > I think that is mostly left overs from older versions
> 
> Looks to me like it's extracted to Hellfire install folder from a CD.
> 
> Also diabdat.mpq look a bit small.

Arh I though you where referring to the DLL files and such.

**Comment by AJenbo** [comment]
> You do code, and fix bugs. So you can see better.

> It's the program bug, because of you can't set brightness up to see fire, and have the still the same default darkness in-game.

You not making sens, and/or being rude now. Please refrain from this, I know it's hard to communicate across language barriers. To be clear no one has found anything that can explain this EXCEPT for an issue with your monitor settings.

> I tested all my screenshots in GIMP(upped the brightness), yes in you turn up the brightness, you can see the art, but game will looks like crap, it's and resolution/brightness bug. Only few resolutions(1280x960 for example), show needed art with default brightness.

Try adjusting the gamma or contrast instead. The color grading is likely wrong on your monitor and compensating for it by maxing out brightness while letting your see some of the darker colors won't give you a full color range and thus result in bad visuals in other parts of the spectrum.

The reason it relates to resolution for you is probably because your system has different profiles for the different resolutions.

The only point where the art is not in the picture is when taking an image of your screen, meaning the issue is between the game and your screen, not in the game.

The fact that you also have the issue when running Linux points to the issue being with with the monitor it self and not the software, unless you load some of the same color profile in the Nvidia driver or OS.
