### ISSUE TITLE
[Feature Request]: Tremain the Priest

### ISSUE THREAD

**Issue by SODIX** [diasurgical/devilutionX#7204]
![image](https://github.com/user-attachments/assets/3387045a-f834-497a-a8a2-629c9129651d)
### Feature Type

Quality of Life

### Describe

PLS add option to enable Tremain the Priest NPC, and his quests. It's all in DATA and original code, but disabled by default. DIABLODAT.mpq have all replicas(voice and text) from this NPC, and he is original, not from mod or such. 
Add just as option, as TEOQUEST and COWQUEST.

PS. Tremain.

**Comment by DakkJaniels** [comment]
What quests? As far as I know, there is no code for quests.

**Comment by StephenCWills** [comment]
> It's all in DATA and original code, but disabled by default.

You are misinformed. `DIABDAT.MPQ` has audio files with his voice lines and sprites for an idle animation, but there is no code and no text.

**Comment by SODIX** [comment]
> > It's all in DATA and original code, but disabled by default.
> 
> You are misinformed. `DIABDAT.MPQ` has audio files with his voice lines and sprites for an idle animation, but there is no code and no text.

There is code and texts. What is missing is priest death animation by demons.

**Comment by AJenbo** [comment]
> There is code and texts. What is missing is priest death animation by demons.

Then point to it, we sure have not seen it when looking

**Comment by SODIX** [comment]
> > There is code and texts. What is missing is priest death animation by demons.
> 
> Then point to it, we sure have not seen it when looking

I'm not good at code, but you can see texts in diablo wiki: https://diablo.fandom.com/wiki/Tremain_the_Priest

**Comment by qndel** [comment]
> > > There is code and texts. What is missing is priest death animation by demons.
> > 
> > 
> > Then point to it, we sure have not seen it when looking
> 
> I'm not good at code, but you can see texts in diablo wiki: https://diablo.fandom.com/wiki/Tremain_the_Priest

Surely a website where anyone can write anything is a good source of information

**Comment by AJenbo** [comment]
> I'm not good at code

Then please trust us when we tell you that there is no code for this NPC. If you think there is because of Belzebub or some other mods (Looks like your screen shot is from The Hell) then please understand that these mods made there own code and quests and have not shared it. It's not part of the original game as Tremain was never added to the original game.

**Comment by julealgon** [comment]
This is also not QOL, it's a feature/MOD request. QOL is something else entirely.

**Comment by qndel** [comment]
You ask, we said no, end of discussion.

**Comment by SODIX** [comment]
> You ask, we said no, end of discussion.

![image](https://github.com/user-attachments/assets/053b0ad7-4672-48ae-af92-301039a1846c)
Bad Vlad, from this picture, asking for this.
