### ISSUE TITLE
Cannot join a Nightmare game (may affect Hell as well)

### ISSUE THREAD

**Issue by cwright814** [diasurgical/devilutionX#721]
**Describe**
I'm hosting with a lv29 character on Nightmare. My friend tries to join with their own lv29 character. My friend receives an error message stating they must be lv20 or higher. However, we can connect fine on Normal difficulty. We can also connect fine with the web port of this project on Nightmare. Additionally, we can connect fine with the original game on Nightmare.

**To Reproduce**
1. Host TCP game on Nightmare
2. Join TCP game with lv20+ character
3. See error stating that character level must be 20 or higher

**Expected behavior**
Be able to join the Nightmare game and load into the town.

**Comment by AJenbo** [comment]
There is currently a bug where you will need to start (host) a game before you will be able to join a nightmare or hell game. This will be fixed in the next release. Sorry for the inconvenience.

**Comment by cwright814** [comment]
Thanks for the quick response and the workaround! We played for the past two hours and everything worked well - excellent work.

**Comment by kphoenix137** [comment]
Has this been fixed?

**Comment by StephenCWills** [comment]
Yes #663
