### ISSUE TITLE
Update bundled libsmacker library

### ISSUE THREAD

**Issue by mnhauke** [diasurgical/devilutionX#723]
The current version of libsmacker is v1.1.1r35, released on Jan 5, 2020.

Starting with this release libsmacker is complete relicensed under the LGPL-2.1
http://libsmacker.sourceforge.net/#license

**Comment by AJenbo** [comment]
It's been updated. Someone should also upstream smk_palette_updated https://github.com/diasurgical/devilutionX/blob/master/3rdParty/libsmacker/smacker.h#L95, as it could probably help otheres do more efficient rendering of videos.
