### ISSUE TITLE
Host Cannot Rejoin Game

### ISSUE THREAD

**Issue by mgpat-gm** [diasurgical/devilutionX#724]
**Describe**
When a host exits a LAN game they cannot rejoin.

**To Reproduce**
1. Create a game on LAN TCP
2. Have guest join.
3. Host leave
4. Host try to rejoin
5. "Connect: Connection Refused"

**Expected behavior**
Host should be able to rejoin.

**Screenshots**
![Screenshot from 2020-05-07 20-57-28](https://user-images.githubusercontent.com/60494513/81359868-5bf66000-90a8-11ea-9f56-4739e6014f05.png)

**Additional context**
I tested exiting the game rather than trying "new game". Restarting game did not help. Left zerotier networks to no avail. Exiting Diablo while in game rather than menu: new game might have worked once, but I could not reproduce correct behavior. I may have forgotten which machine was host for that test run.

Both machines:
Ubuntu 5.3.0
DevilutionX Version 1.0.0

**Comment by AJenbo** [comment]
this is a limitsation of tcp since only the host is hosting.
