### ISSUE TITLE
Ubuntu Cannot Find Libraries?

### ISSUE THREAD

**Issue by mgpat-gm** [diasurgical/devilutionX#727]
**Describe**
Cannot run game due to shared library error.

**To Reproduce**
1. Download latest release 1.0.1: devilutionx-linux-x86_64.7z
2. Extract
3. Run devilutionx
4. Error: 
![1](https://user-images.githubusercontent.com/60494513/81478256-104bcf80-91ea-11ea-9770-3f97d53d7c03.png)

**Expected behavior**
Normal startup

**Additional context**
Installed:
libsdl2-2.0-0: 2.0.8+dfsg1- amd64
libsdl2-mixer- 2.0.2+dfsg1- amd64
libsdl2-ttf-2. 2.0.14+dfsg1 amd64

Ubuntu 18.04
Devilution: 1.0.1

**Comment by AJenbo** [comment]
You need to run it via a terminal or shortcut, double clicking will make it think it's a library and not an application

**Comment by mgpat-gm** [comment]
"/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./devilutionx)"
I tried the terminal(sometimes I forget I'm on linux).
Looks like Ubuntu 18.04 libc6 is still on 2.27. I'll see if I can force it or wait. A cursory search indicates I could build from source and it will use my C library version. May try that.
Thanks.

**Comment by AJenbo** [comment]
The official DevilutionX 1.0.1 only requires libc 2.27:
```
ldd -r -v devilutionx | grep libc | sort -u
libc.so.6 (GLIBC_2.10) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.11) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.15) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.16) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.17) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.18) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.25) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.27) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.3.3) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.7) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.8) => /lib/x86_64-linux-gnu/libc.so.6
libc.so.6 (GLIBC_2.9) => /lib/x86_64-linux-gnu/libc.so.6
```
(I just tested it from Ubuntu 18.04 also)

Where/when did you get your version?

**Comment by mgpat-gm** [comment]
Got it March 9th. Downloaded again and replaced all files. Seems to be working properly.

**Comment by AJenbo** [comment]
ok, there was a brief window on that day where the wrong build (build from Ubuntu 19.10 instead of Debian 9) was uploaded, i guess you where one of the ~30 people that ended up downloading that verison.
