### ISSUE TITLE
Running DevilutionX 1.0.1/1.0.0 on Ubuntu 16.04 crashes at startup with: symbol lookup error: ./devilutionx: undefined symbol: SDL_CreateRGBSurfaceWithFormat

### ISSUE THREAD

**Issue by Tim-Blokdijk** [diasurgical/devilutionX#728]
Downloaded and ran DevilutionX 1.0.1 and 1.0.0 (devilutionx-linux-x86_64.7z) on Ubuntu 16.04
Crashes with the following error:
`./devilutionx: symbol lookup error: ./devilutionx: undefined symbol: SDL_CreateRGBSurfaceWithFormat`

`sudo apt-get install libsdl2-ttf-2.0-0 libsdl2-mixer-2.0-0` packages were installed successfully.

Running the 1.0.1 Windows version via Wine did work as expected.

**Comment by qndel** [comment]
what's your SDL2 version?

**Comment by glebm** [comment]
We have a backport for this function: https://github.com/diasurgical/devilutionX/blob/master/SourceS/sdl2_backports.h#L15-L24

The release is probably compiled with a newer version of SDL2, so the backport doesn't get compiled in. @Tim-Blokdijk You can either update the `sdl2` package or compile from source

**Comment by AJenbo** [comment]
As Glebm mentioned the release builds do not support Ubuntu 16.04 buy default. You will either have to upgrade SDL to a least 2.0.5 or build the game from source (see build instructions in the readme). The following PPA might be an option for upgrading SDL, but not that this hasn't been tested: https://launchpad.net/~litenstein/+archive/ubuntu/sdl2-xenial

**Comment by Tim-Blokdijk** [comment]
@AJenbo well, it's tested now. Upgrading to the sdl2 PPA seems to work with DevilutionX 1.0.1
Thanks!

Compiling DevilutionX 1.0.1 on Ubuntu 16.04 fails as DevilutionX needs cmake 3.10 where Ubuntu 16.04 has 3.5.1, changing it to cmake_minimum_required(VERSION 3.5.1) in CMakeLists.txt fails to compile as newer features are used.
So the PPA is the way for people like me that actually like the Unity shell. ;-)

**Comment by AJenbo** [comment]
Yeah, I realized after posing that you would need to upgrade things even if compiling manually :D Thanks for reporting back after testing.

I like the Unity shell :'(

**Comment by glebm** [comment]
@AJenbo I use this https://extensions.gnome.org/extension/1287/unite/

**Comment by AJenbo** [comment]
https://www.forbes.com/sites/jasonevangelho/2020/05/12/a-surprising-new-remix-of-ubuntu-2004-revives-the-unity-desktop/amp/
