### ISSUE TITLE
[Issue Report]: Trying to pick up the magic rock with a full inventory causes it to appear at ground level behind the stand

### ISSUE THREAD

**Issue by ephphatha** [diasurgical/devilutionX#7304]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

Attempting to pick up the magic rock when you don't have room in your inventory causes it to drop back on the same tile as the pedestal/stand object, but using the ground sprites and selection mode instead of the elevated sprites/mode.

### To Reproduce

 1. Fill up your inventory so there's no space for a 2x2 item
 2. Go to dlvl 5 in a game with the magic rock available
 3. Attempt to pick up the rock
 4. See it get drawn behind the base of the pedestal

### Expected Behavior

The rock should either stay elevated, or spawn on an adjacent tile (using the same logic as if it was dropped by the player)

### Additional context

![2024-07-28T130307_devilutionx](https://github.com/user-attachments/assets/296ec286-5d52-477a-84c5-c0a3de331c5b)

**Comment by AJenbo** [comment]
Nice write up, I have seen it happen but was mostly just confused about what just happened

**Comment by julealgon** [comment]
I was trying to remember what other items have custom stands like the magic rock... does this also happen with the Lazarus Staff on hell, by any chance?

I don't recall if there are any other similar item stands for unique/quest items.

**Comment by StephenCWills** [comment]
The Vile Stand works more like an armor rack. Therefore, Lazarus' Staff always flips onto the ground before you can put it in your inventory.
