### ISSUE TITLE
[Issue Report]: Spell sounds not present

### ISSUE THREAD

**Issue by kphoenix137** [diasurgical/devilutionX#7331]
### Operating System

Windows x64

### DevilutionX version

Other (please specify version number)

### Describe

In commit [d3e30d1](https://github.com/diasurgical/devilutionX/commit/d3e30d1ce98364f4ec6400b921c6be3e02a545de), Spell sounds are not present. The casting sound is present, but the sound made by the spell itself is not.

### To Reproduce

Cast a spell in the dungeon.

**Comment by qndel** [comment]
I'll bisect with my tool later

**Comment by qndel** [comment]
91306d8c22fb458df195a3fac81433eb3339789a is the first bad commit
    Migrate misdat.cpp data to TSV

**Comment by qndel** [comment]
+ it's more than that, sounds are still broken, cast charged bolt into a wall - collision sound = footsteps

**Comment by qndel** [comment]
Thx for fix :)
