### ISSUE TITLE
Self compiled binaries and assets

### ISSUE THREAD

**Issue by DerPit** [diasurgical/devilutionX#7332]
I have compiled the latest git version of devilutionx on my computer at home (openSUSE Tumbleweed), following the guide in the docs.  No issues with that.
However, this build always insists in loading assets (lua stuff etc) from the build tree, and doesn't run if those cannot be found.  The binary in the release doesn't show that behavior.
I was searching whether I need some additional flags to cmake, but didn't find anything.
A hint what I'm probably doing wrong would be highly appreciated....

**Comment by qndel** [comment]
Open a discussion for things like these or ask on discord ...

**Comment by AJenbo** [comment]
Probably give some examples of error messages and paths as well as how you launch it as well
