### ISSUE TITLE
[Issue Report]: Building 1.5.2 from source failed on MacOS 13.0.1

### ISSUE THREAD

**Issue by danissimo** [diasurgical/devilutionX#7342]
### Operating System

Mac

### DevilutionX version

1.5.2

### Describe

```shell
git clone https://github.com/diasurgical/devilutionX.git    # ok
cd devilutionX                                              # ok
git checkout 1.5.2                                          # ok
brew bundle install                                         # ok
cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release                # ok
cmake --build build -j $(sysctl -n hw.logicalcpu)           # failure
test/animationinfo_test.cpp:115:30: error: no member named 'setprecision' in namespace 'std'
                            << std::fixed << std::setprecision(2)
                                             ~~~~~^
```

### To Reproduce

See the description.

**Comment by danissimo** [comment]
Sorry, I'm from the other part of software development world and I didn't check out the app directory. I got an executable there.

**Comment by AJenbo** [comment]
try disabling the test suite, it's not clear from your log which compiler you are using or if it's x86_64 or ARM64.

**Comment by glebm** [comment]
`test/animationinfo_test.cpp` is missing `#include <iomanip>`, sent https://github.com/diasurgical/devilutionX/pull/7343
