### ISSUE TITLE
Add support for looking server up by host name

### ISSUE THREAD

**Issue by kai4785** [diasurgical/devilutionX#735]
**Describe**
When choosing a multiplayer server, a hostname cannot be used and users are forced to use an IP address.

**To Reproduce**
From the top level menu, choose:
1) Multi Player
2) Client-Server (TCP)
3) < Choose any player, or create a new one >
4) Enter IP
5) < Enter a hostname like `localhost` >
6) < Enter a password >

At the end, you will be presented with an error screen and the message "Invalid argument".

**Expected behavior**
Allow users to enter hostnames in step 5 above.
As an added bonus, change Step 4 to "Join Server", and the prompt in step 5 to "Enter hostname or IP address."

**Screenshots**
![image](https://user-images.githubusercontent.com/729693/82059357-25f64480-9683-11ea-8233-2faf667fdebc.png)

![image](https://user-images.githubusercontent.com/729693/82059396-34dcf700-9683-11ea-993f-7c300345c16d.png)

![image](https://user-images.githubusercontent.com/729693/82058627-3b1ea380-9682-11ea-843f-d976f22e8360.png)

**Additional context**

**Comment by AJenbo** [comment]
This will require implementing a DNS lookup and probably pattern matching to test if what was entered was an IP or not. It does look like ASIO has the needed functionality to implement this.

**Comment by kai4785** [comment]
Awesome, thanks for the quick fix! This will make it much easier on my kids playing multiplayer with each other. No more looking up IPs!

**Comment by AJenbo** [comment]
@ahwayakchih in case you didn't see the message above :)

**Comment by ahwayakchih** [comment]
Thanks :D
