### ISSUE TITLE
[Issue Report]: Black spots on screen

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#7351]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

https://github.com/diasurgical/devilutionX/commit/31f91ac8aaed0c213b36edd7a8ca5383109e085b
![image](https://github.com/user-attachments/assets/673cc545-0590-4c5a-8679-9f20ddebc5d1)

Caused by https://github.com/diasurgical/devilutionX/commit/d41c7e422184d14cc8622b57a89cd6a8a1781638 (PR https://github.com/diasurgical/devilutionX/pull/7345 )

### To Reproduce

Launch the game

**Comment by AJenbo** [comment]
@glebm anything specific to town or something else?

**Comment by qndel** [comment]
it's not only in town, it was broken in lazarus lair too
