### ISSUE TITLE
Latest release does not have a 3DS .cia

### ISSUE THREAD

**Issue by PhoenixUp** [diasurgical/devilutionX#7384]
### Operating System

Nintendo 3DS

### DevilutionX version

1.5.2

### Describe

The latest release does not have a 3DS .cia and breaks both the install instructions and the UniversalDB entry.

### To Reproduce

1. open universal updater on your 3DS
2. attempt to install from the DevilutionX entry's .cia

**Comment by AJenbo** [comment]
It's on its way

**Comment by AJenbo** [comment]
3ds builds are here now
