### ISSUE TITLE
Please do not include scripts to install devkitPro toolchains 

### ISSUE THREAD

**Issue by WinterMute** [diasurgical/devilutionX#739]
https://github.com/diasurgical/devilutionX/blob/master/Packaging/switch/build.sh should not exist. These things have a terrible habit of propagating and being "fixed" by people who seem to think the toolchains are just some random component of random projects rather than the carefully curated and constructed tools for building homebrew that they are.

This kind of thing causes endless support headaches for devkitPro. Please stop doing it.

**Comment by AJenbo** [comment]
related topic https://github.com/devkitPro/pacman-packages/issues/143

**Comment by AJenbo** [comment]
@WinterMute would you prefer we direct people to https://devkitpro.org/wiki/devkitPro_pacman and then instruct them on what packages to install?

Is there a similar solution to Homebrew's [Brewfile](https://github.com/diasurgical/devilutionX/blob/master/Brewfile) for simplifying the instructions?

**Comment by WinterMute** [comment]
Yes, direct people to our install instructions. Please do not try to automate it (especially when your script will only work on one small subset of systems we support :( )

A lot of systems have pacman natively in which case users call sudo pacman, unless it's msys2 where sudo is omitted. On debian based systems and macOS users call sudo dkp-pacman.

Using a text file that contains a list of packages you can simply do
 `(sudo) (dkp-)pacman -S --needed - < pkg-list.txt `

The parts in brackets should be omitted or included as appropriate.

**Comment by ThomasChr** [comment]
@AJenbo Does it make any sense to leave this issue open?
I don't think it's really an "Issue"...

**Comment by StephenCWills** [comment]
No one has fixed the build instructions for Switch, so it is still an issue.
