### ISSUE TITLE
[Issue Report]: Latest release don't have Android apk built

### ISSUE THREAD

**Issue by kai11** [diasurgical/devilutionX#7391]
### Operating System

Android

### DevilutionX version

1.5.3

### Describe

Latest release (1.5.3) dont have Android build and probably few others.
1.5.3 on github have only 16 artifacts, but 1.5.2 have 26.

### To Reproduce

1. Go to https://github.com/diasurgical/devilutionX/releases/tag/1.5.3
2. Try to find android apk - its missing
3. Go to https://github.com/diasurgical/devilutionX/releases/tag/1.5.2
4. Android apk is there

### Expected Behavior

Apk built for android should be available

### Additional context

I assume build failed in CI.

**Comment by AJenbo** [comment]
See the known issues

**Comment by AJenbo** [comment]
It's there now
