### ISSUE TITLE
[Issue Report]: devilutionx: Source/engine/render/scrollrt.cpp:582: Assertion failed.

### ISSUE THREAD

**Issue by zboszor** [diasurgical/devilutionX#7404]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Current master built from commits later that a75f77bfa87b6960a9853281b6ab3cc2048a2a61 fails with the newly added ˙assert()` in this commit:
```
commit a75f77bfa87b6960a9853281b6ab3cc2048a2a61
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Mon Sep 2 04:31:11 2024 +0100

    DrawFloor: Remove a redundant check
    
    Floor tiles always come in pairs. If the left triangle (mt[0]) exists, so does the right one.
```

Happened on a pre-existing savegame and also on a new one:
```
zozo@localhost:~/git/devilutionX/build$ ./devilutionx 
INFO: Asset not found: lua\user.lua
devilutionx: Source/engine/render/scrollrt.cpp:582: void devilution::{anonymous}::DrawFloorTile(const devilution::Surface&, devilution::Point, devilution::Point): Assertion `DPieceMicros[levelPieceId].mt[0].hasValue() == DPieceMicros[levelPieceId].mt[1].hasValue()' failed.
Félbeszakítva (core készült)
```

### To Reproduce

1. Walk to the gate of the cathedral in the town.
2. Assertion fails

**Comment by glebm** [comment]
Very curious, can you please upload the savegame?

**Comment by AJenbo** [comment]
@zboszor hellfire or diablo?

**Comment by StephenCWills** [comment]
I can reproduce it very easily just walking to the dungeon, like the description suggests. Are you sure you need a savegame? It happens in both Diablo and Hellfire.

**Comment by zboszor** [comment]
Diablo. Just starting a new game and trying to walk to the cathedral triggers the assertion.

Unfortunately, I can't send you the savegame, as I deleted it because it didn't have much progress anyway and suspected that it might have been an incompatible change in the game. Apparently, it's not the case.

Reverting the commit fixes the problem.

**Comment by zboszor** [comment]
FWIW, the mpq files are from the gog.com version of the combined D1+Hellfire.

**Comment by AJenbo** [comment]
> Walk to the gate of the cathedral in the town.

I read this as it happening in town and not the dungeon

**Comment by glebm** [comment]
Please revert the commit for now, I won't have time to look at it until Saturday

That said, there shouldn't be any half floor tiles in the game, so I'm very curious to see what's up with that

**Comment by StephenCWills** [comment]
Here are some values from my debugger:
![image](https://github.com/user-attachments/assets/7edd7662-8958-43b4-8293-83d3d79c9505)

I'm pretty sure this is the right tile in D1GT:
![image](https://github.com/user-attachments/assets/8d9d5b1d-8ff5-4ca3-b4ed-e172c18b7190)

**Comment by glebm** [comment]
`levelPieceId` is 1-based, so the issue with tile 725 rather than 726
My guess is either (a) my assumption about floors is incorrect or (b) tile 725 is incorrectly marked as a floor.

**Comment by StephenCWills** [comment]
> `levelPieceId` is 1-based, so the issue with tile 725 rather than 726

I thought so too, but then the frame index doesn't make sense. It was enough to make me think that maybe `dPiece` in town works differently.

**Comment by StephenCWills** [comment]
I think, based on this screenshot, it's safe to say I found the right tile in D1GT. The in-game tile 725 is in exactly the right spot compared to how the D1GT tile 726 looks. Plus, the in-game tile 726 is not even close to the red doorway.

![image](https://github.com/user-attachments/assets/ba9cd9e5-4b03-46a2-93ac-7844c9e9f7a0)
