### ISSUE TITLE
[Issue Report]: Cmake errors and warnings

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#7406]
### Operating System

Linux x64

### DevilutionX version

Custom build (commit 77020db5ffcf37d296ebfc9805e8999a915f958f)

### Describe

When I run the command
(cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release),
the following error message appears (log file [cmake.txt](https://github.com/user-attachments/files/16906196/cmake.txt) ).

Message:
"Could not find a package configuration file provided by "benchmark" with any of the following names:"

### To Reproduce
Just clone the repository and try the mentioned command.
If I edit the following file and change DEVILUTIONX_SYSTEM_BENCHMARK ON to OFF the process runs through.

File:
devilutionX/CMake/Dependencies.cmake

### Expected Behavior

Running through the cmake process without errors and warnings

### Additional context

The issue happens since commit 4aa9d37f0fb3ef0bd2e69b3db28e7b0c55ce7d8b

**Comment by Chance4us** [comment]
[cmake.txt](https://github.com/user-attachments/files/16905984/cmake.txt)

**Comment by AJenbo** [comment]
Did you install `libbenchmark-dev`?

**Comment by Chance4us** [comment]
No. But after I did it the issue no longer occurs.
