### ISSUE TITLE
[Issue Report]: Several additional mirroring effects

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#7407]
### Operating System

Linux x64

### DevilutionX version

Custom build (commit 77020db)

### Describe

We have a bug with several additional mirroring effects since commit a75f77bfa87b6960a9853281b6ab3cc2048a2a61.

How it looks like:
![mirroring](https://github.com/user-attachments/assets/f314d30f-5d90-4d5a-bef4-fb24da6aee18)

Savegame:
[mirroring.hsv.zip](https://github.com/user-attachments/files/16912524/mirroring.hsv.zip)

### To Reproduce

Compile the affected commit and look at the marked areas while running around.

**Comment by Chance4us** [comment]
Sorry. I was too quick. The commit 77020db has reverted the bug.

**Comment by AJenbo** [comment]
no worries

**Comment by qndel** [comment]
Good to know it had more side effects than just a crash in town :) Also good to see you!
