### ISSUE TITLE
[Issue Report]: The storage at Gillian from a deleted hero still available for a new hero

### ISSUE THREAD

**Issue by ColourGrey** [diasurgical/devilutionX#7408]
### Operating System

Windows x64

### DevilutionX version

1.5.2

### Describe

All the items stored at Gillian by a hero remain stored and accessible by subsequent heroes even if that hero is deleted.

### To Reproduce

1) I first completed the game as rogue, in normal mode.
2) I next deleted that hero profile.
3) I started the game as a warrior (still in normal mode).

To my surprise, all the inventory stored at Gillian in step 1) was still available in step 3).

### Expected Behavior

Deleting a hero should erase every trace of him/her, including the items stored at Gillian.

### Additional context

I have not tried the more complicated situation when one creates several heroes, deletes some of them, creates some other ones etc.

All of the above happens in single player mode.

**Comment by Trihedraf** [comment]
Stash is stored, not per character.

**Comment by kphoenix137** [comment]
> ### Operating System
> 
> Windows x64
> 
> ### DevilutionX version
> 
> 1.5.2
> 
> ### Describe
> 
> All the items stored at Gillian by a hero remain stored and accessible by subsequent heroes even if that hero is deleted.
> 
> ### To Reproduce
> 
> 1) I first completed the game as rogue, in normal mode.
> 2) I next deleted that hero profile.
> 3) I started the game as a warrior (still in normal mode).
> 
> To my surprise, all the inventory stored at Gillian in step 1) was still available in step 3).
> 
> ### Expected Behavior
> 
> Deleting a hero should erase every trace of him/her, including the items stored at Gillian.
> 
> ### Additional context
> 
> I have not tried the more complicated situation when one creates several heroes, deletes some of them, creates some other ones etc.
> 
> All of the above happens in single player mode

Navigate to your saves directory and delete the applicable stash save file to clear it
