### ISSUE TITLE
Cannot turn off FPS display on the upper left

### ISSUE THREAD

**Issue by PowerShellNoob** [diasurgical/devilutionX#7412]
So I read the readme/config file in %appdata%

When I play devilutionx it shows my current framerate in the upper left corner. I don't see anyway to turn it off. I tried Ctrl+R, Ctrl+F and such. Anyway to turn it off? 

I am on an OLED and don't like unnecessary text floating in the frame.

**Comment by DakkJaniels** [comment]
Did you try turning it off in settings? ![Screenshot_20240911-192407.png](https://github.com/user-attachments/assets/f60b0854-2c59-41f3-b142-515bda43a089)

**Comment by PowerShellNoob** [comment]
> Did you try turning it off in settings? 

Wow, before I posted this I checked the graphics options but I must have missed it. That did it. Thanks!

**Comment by AJenbo** [comment]
It's not on by default
