### ISSUE TITLE
Crash: Surface already associated with window

### ISSUE THREAD

**Issue by kardwen** [diasurgical/devilutionX#7413]
### Operating System

Linux x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Commit a0171b1b5a59464df57e10128548afb70382e5a5
Built on Alpine Linux Edge under Wayland (River)

Crashes when changing the Upscale setting to ON under Settings > Graphics > Upscale

```
SDL Error
Surface already associated with window

The error occured at:
Source/utils/display.cpp line 436
```

Runs great otherwise, I hope this is of some use!

### To Reproduce

Crashes when changing the Upscale setting to ON under Settings > Graphics > Upscale

**Comment by qndel** [comment]
There have been like 5 or more issues for this already, search for duplicates before opening a new one

**Comment by kardwen** [comment]
I did search for the error message but could not find an open issue.

A solution can be found in this closed issue: https://github.com/diasurgical/devilutionX/issues/7141#issuecomment-2167110558

Simply remove `diablo.ini` in `~/.local/share/diasurgical/devilution`

**Comment by AJenbo** [comment]
There are no open issues since it's is the systems and not with us that the issue exists
