### ISSUE TITLE
[Issue Report]: Empty weapon racks near the Warlord of Blood

### ISSUE THREAD

**Issue by ChaosMarc** [diasurgical/devilutionX#7414]
### Operating System

Windows x64

### DevilutionX version

Custom build (please specify commit ID)

### Describe

Commit: a0171b1 (https://github.com/diasurgical/devilutionX/actions/runs/10775384552)

2 of the 6 weapon racks / armor stands near the warlord of blood were empty on level creation. I have never encountered this, so I guess it's a bug.

I've attached my savegame: [single_0.zip](https://github.com/user-attachments/files/16993503/single_0.zip)

the game and level was created with an earlier commit around 2 weeks ago

### To Reproduce

1. walk a few steps north-east until you see the stairs
2. hover the nearest weapon racks. only the armor stand on the left hand side holds an item

### Expected Behavior

all 6 weapon racks / armor stands hold an item

**Comment by ChaosMarc** [comment]
hmm. sorry I only play very little these days. sometimes only for a few minutes. I don't remember if I did something weird like cranking up the resolution and using telekinesis on the weapon racks from far away in this savegame before. that at least would explain the state of the savegame. If you can see that the weapon racks were filled at level recreation, can you see what items they were holding? in the savegame I have 3 unidentified weapons in my inventory. if they are a match I'm very sorry to have bothered you just because I have no memories of having done something like this 2 weeks ago whatsoever...

**Comment by StephenCWills** [comment]
Yes, they are a match.

![image](https://github.com/user-attachments/assets/92bbfa27-c1dd-47dd-8db8-fb7bb84f23a0)
