### ISSUE TITLE
Part of stairs are not being rendered in Caves and Hell

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#7420]
### Operating System

Linux x64

### DevilutionX version

Custom build (commit 8970eaa)

### Describe

We have a bug with a  mirroring effect at the level exit in hell since commit 2580cd7b688b59ba761de4820e6a0f2fda646db2.

How it looks like:
![mirroring](https://github.com/user-attachments/assets/6a7d0f0c-95db-4fde-b05e-d959cecbab83)

Savegame:
[mirroring.hsv.zip](https://github.com/user-attachments/files/17019719/mirroring.hsv.zip)

### To Reproduce

Compile the affected commit and look at the marked area while running around.

**Comment by AJenbo** [comment]
![image](https://github.com/user-attachments/assets/fb547fe1-ffdb-44a6-9318-fb054d255dcc)
![image](https://github.com/user-attachments/assets/44823ce6-8e10-4ca5-80b1-c98ab54a3c9e)

**Comment by glebm** [comment]
Curious, if I add DPieceMicros mt display, nothing is shown for the broken tile:

![Screenshot from 2024-09-27 06-26-44](https://github.com/user-attachments/assets/d8033a7c-3d6e-45d5-a730-f3ab51342fe1)

**Comment by glebm** [comment]
Broken tile:
![Screenshot from 2024-09-27 06-39-47](https://github.com/user-attachments/assets/e67f7047-454b-4652-b01e-82290b954ea2)

**Comment by glebm** [comment]
While the hell one can be fixed by checking for BlocksMissile in isWall, the caves one cannot be fixed that way (it doesn't have BlocksMissile).

I think a proper fix is to not treat stairs as floor at all (they're not solid but the graphics are not laid out as floor graphics).
