### ISSUE TITLE
[Issue Report]: No money is spent on equipment repairs

### ISSUE THREAD

**Issue by Maderator3000** [diasurgical/devilutionX#7422]
### Operating System

Android

### DevilutionX version

1.5.3

### Describe

Immediately after upgrading to version 1.5.3, it began to seem to me that money was not being spent on equipment repairs. After a while, I realized that it did not seem to me that money was really not spent during the repair of anything, but it was still necessary to have enough money to make repairs.

### To Reproduce

1. Open a dialogue with Griswold
2. Select the repair option
3. Try to repair something. The money will stay with you.

### Expected Behavior

Money should definitely be spent on repairs ¯⁠\⁠_⁠(⁠ ͡⁠°⁠ ͜⁠ʖ⁠ ͡⁠°⁠)⁠_⁠/⁠¯

**Comment by AJenbo** [comment]
I'm guessing this is related to https://github.com/diasurgical/devilutionX/pull/7360, maybe @qndel has an idea...
