### ISSUE TITLE
[Issue Report]: Wirt's items are not based on character class

### ISSUE THREAD

**Issue by Thrax-x** [diasurgical/devilutionX#7432]
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

Wirt's items should be based on your character class.
E.g. he should never sell Bows and Staffs to Warrior and Barbarian,
Axes, Clubs, Swords, Staves and Shields to Rogue, etc.
He sells every item type to every character class.

### To Reproduce

1. Check Wirt's item
2. Buy the item
3. Go to the dungeon
4. Return to Wirt and check the new item

### Expected Behavior

Wirt will only sell certain item types depending on your character class.

### Additional context

I found another thing, I'm not sure if it's bug.
When you buy item from Wirt, SAVE, LOAD, go to dungeon and back and Wirt has the same item again.

**Comment by AJenbo** [comment]
That's an opinion and not how the original works.

> I found another thing, I'm not sure if it's bug.
When you buy item from Wirt, SAVE, LOAD, go to dungeon and back and Wirt has the same item again

Sounds like a bug, feel free to create an issue for it.

**Comment by DakkJaniels** [comment]
That is how it works in Hellfire, not in Diablo.
