### ISSUE TITLE
[Issue Report]: Changing the repair price when changing the maximum strength of the item

### ISSUE THREAD

**Issue by Maderator3000** [diasurgical/devilutionX#7441]
### Operating System

Android

### DevilutionX version

1.5.3

### Describe

Most likely, this error came from vanilla Diablo Hellfire. If you change the strength of an item using "Oil of Fortitude", the price per repair unit will change. As it was with me: I used the Butcher's weapon and when I found Oil of Fortitude, I immediately applied it to the weapon. The strength of 10 turned into 45, and the price per unit of strength dropped from about 250 to about 40 (I don't remember the exact numbers). Most likely, such a problem arises due to the fact that the repair price for the maximum number of units of strength is prescribed in advance for the items, and the price per unit is calculated according to a certain formula. Sierra did not calculate this when creating the add-on. As if you need to set a price per unit of strength, and not for its maximum value.

### To Reproduce

1. Take any item and Oil of Fortitude 
2. Apply Oil of Fortitude to the item
3. Damage the item and fix the repair price

**Comment by qndel** [comment]
Doesn't sound like a bug to me

**Comment by julealgon** [comment]
I got super confused by your use of "strength". Would suggest renaming to "durability" in your title/post at least to avoid confusion from other people stumbling into this issue later.
