### ISSUE TITLE
[Issue Report]: Keymapping -- "Stop hero" button

### ISSUE THREAD

**Issue by Venyam-N** [diasurgical/devilutionX#7447]
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

Can’t reassign the button, that prevents character from moving (LSHIFT by default)

### To Reproduce

1. Go to "keymapping", find "stop hero" option and map it to TAB. I've tried other buttons for this function – it doesn’t work anyway. I've even tried to assign LSHIFT or RSHIFT but these two couldn't be used anyway -- it's impossible to bind any actions on them.
2.  Start your game and press "hero stop" button while moving or attacking
3. Noting happens, but LSHIFT works properly

### Expected Behavior

Hero stops and attacks/casts without approaching the target

**Comment by qndel** [comment]
works as intended, seems you don't really understand the purpose of this function, if you mean "attack in place" it's bound to shift

**Comment by Venyam-N** [comment]
But can I rebind "attack in place"?

**Comment by DakkJaniels** [comment]
Not with mouse and keyboard

**Comment by Venyam-N** [comment]
May such an option appear in future or it's technically imposible?

**Comment by AJenbo** [comment]
Is shift+attack somehow different from what you want?

**Comment by Venyam-N** [comment]
I want to remap shift to tab

**Comment by AJenbo** [comment]
ok, that isn't an option currently
