### ISSUE TITLE
[Feature Request]: Option for Smaller Minimap in Top Right Corner

### ISSUE THREAD

**Issue by RednibCoding** [diasurgical/devilutionX#7458]
### Feature Type

Quality of Life

### Describe

_Issue_: In the original Diablo 1, pressing the "Tab" key brings up the minimap, which overlays the entire screen. While this provides detailed map information, it can obstruct the view of the actual gameplay, making it harder to focus on enemies, loot, or other in-game elements.

_Suggestion_: It would be good, adding an option (checkbox) in the game settings menu to display a smaller version of the minimap in the top right corner, as an alternative to the current full-screen overlay. This would give players better visibility of the gameplay while still providing easy access to map information.

_Benefits_:
- Improved gameplay visibility while using the minimap.
- Increased flexibility for players who prefer a less obstructive UI.
- Enhanced overall user experience without changing the core gameplay.

**Comment by StephenCWills** [comment]
You're in luck. We already have that.
