### ISSUE TITLE
Reduce CLX frame header size from 10 to 6

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#7477]
Let's save 4 bytes per header to save a bit of RAM.

Overall on-disk savings are ~390 KiB for diabdat and ~179 KiB for hellfire.

```
$ du -sb diabdat hellfire
491715471	diabdat
187260979	hellfire
$ du -sb diabdat hellfire
491324187	diabdat
187081007	hellfire
```

**Comment by StephenCWills** [comment]
This is done with #7478, right?

**Comment by AJenbo** [comment]
that probably translates to about 100kb of run time memory
