### ISSUE TITLE
[Issue Report]: Telekinesis won't push back if target is close to a wall

### ISSUE THREAD

**Issue by D1-Constantine** [diasurgical/devilutionX#7482]
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

So it appears that if the monster is bordering a wall the effect from Telekinesis won't have a push-back effect. I discovered that when facing Leoric in tonight's Ironman run. Xavier_sb also did confirm that this is a Vanilla bug/behaviour.

### To Reproduce

1. Chose a target (monster).
2. Position yourself in a such way that the monster will border a wall.
3. Cast Telekinesis and right-click on the monster.
4. Loose 8 mana for nothing.

### Expected Behavior

The monster should get pushed-back

### Additional context

I expect this problem will be the same with weapons with push-back effect, not sure about stuns* (when the monster is getting mlvl+ damage and moving towards you) .

**Comment by kphoenix137** [comment]
Can you post a short video showcasing the issue?

**Comment by D1-Constantine** [comment]
> Can you post a short video showcasing the issue?

Check 48:40 https://www.twitch.tv/videos/2274425579

**Comment by StephenCWills** [comment]
This is fixed in #7093

**Comment by kphoenix137** [comment]
For the sake of documentation so we don't have to watch 30 seconds of ads:

https://github.com/user-attachments/assets/07c0e649-fecc-4199-9e53-a2b643b4dc76

**Comment by AJenbo** [comment]
Good thing it was closed

**Comment by julealgon** [comment]
> Good thing it was closed

You missed the point. 

People might land on this issue after searching for stuff/coming from links/etc. There was no issue linked to @kphoenix137 original fix, so it would be nice if this issue was reworded to properly document the problem.

That is if anybody else cares, of course 🤷‍♂️

**Comment by StephenCWills** [comment]
> You missed the point.

Maybe your point should have included the actual change to the issue that you want us to make. Something actionable instead of philosophical.

**Comment by AJenbo** [comment]
> You missed the point.

You missed my point

**Comment by kphoenix137** [comment]
For future reference coming back to this, it seems like a good idea to rename the issue

**Comment by AJenbo** [comment]
> There was no issue linked to @kphoenix137 original fix

https://github.com/diasurgical/devilutionX/pull/7093#ref-issue-2583490232

**Comment by julealgon** [comment]
You really don't need to be this combative all the time... sheesh guys...

If you honestly just want people (or myself specifically) to not comment or share their opinions at all, just say so and I'll ignore this kind of stuff from now on. All I'm doing is attempting to help keep things a little bit more organized/reduce confusion for people coming into these issues later on.

**Comment by AJenbo** [comment]
I think it's mostly that:

> Based on the video above, I think this issue is slightly misleading in the way it is presented right now.

made it sounds like you where telling us to keep things more organized rather then making a clarifying comment.

**Comment by StephenCWills** [comment]
> That is if anybody else cares, of course 🤷‍♂️

This also could easily be misconstrued as, "I guess you guys don't care enough to fix it." Rather than what I now realize was probably the intended meaning: "If anyone else cares enough to Google this and learn all the details."

That said, I do personally think the PR does a fine job of describing the issue. I also think anyone who cares enough to go searching for this issue could be bothered to click that link. But maybe that's just me.

**Comment by D1-Constantine** [comment]
> For the sake of documentation so we don't have to watch 30 seconds of ads:
> 
>  Desktop.2024.10.12.-.19.50.04.27.mp4

I know I'm late to the party but I decided to just put this here for anyone (in the future) confused by the video. The first push-back happens even tho Leo is near a wall on his left side, nevertheless you can see him skip/relocate after a bit, this is due to desynch. 

What my guess was that on my comrade screen Leo was not facing or near a wall thus from his point of view he was able to push him back via Telekinesis. As you can see after the monster entity has been linked (corrected desynch) no push-back takes place from the spell.

Not sure if this comment was useful but I guess why not
