### ISSUE TITLE
[Feature Request]: Griswold's Shop Refresh

### ISSUE THREAD

**Issue by Venyam-N** [diasurgical/devilutionX#7492]
### Feature Type

Quality of Life

### Describe

I suggest to add a new option to Settings > Gameplay, that makes Griswold refresh his stock of magic items every time your hero visits the town, like it works with Adria. The witch’s item list update can be abused, and it puts sorcerers in front of other classes when it comes to getting fine equipment, so such an option can add some balance.

P.S. Maybe, there should be such an option for Virt's shop too.

**Comment by kphoenix137** [comment]
Griswold maintaining his stock was an intentional choice by the original developers, it would be very hard to justify undoing this.

**Comment by Venyam-N** [comment]
> Griswold maintaining his stock was an intentional choice by the original developers, it would be very hard to justify undoing this.

Adria don't refill mana in the original game, but we have such an option in DevilutionX. Why can't we have additional options for shops?

**Comment by kphoenix137** [comment]
> > Griswold maintaining his stock was an intentional choice by the original developers, it would be very hard to justify undoing this.
> 
> Adria don't refill mana in the original game, but we have such an option in DevilutionX. Why can't we have additional options for shops?

https://github.com/diasurgical/devilutionX/pull/7434

**Comment by kphoenix137** [comment]
As a followup, I'm against arbitrary changes or features that impact game balance, this would include both Adria giving a free mana refill and Griswold shop cycling. Typically, anything that affects game balance needs to be vetted, and have justification such as the change fixes a bug, or the change is directly in line with original developer intent. Changes that affect game balance in some impactful way where the only justification for them is "Because I like it" is not enough.

**Comment by Venyam-N** [comment]
> #7434

Done with reading, but I don't think it's a good decision to remove the toggle. An option is just an option, and it is turned off by default. Also, I saw a lot of good arguments for saving the toggle there (eg soft-lock possibility etc). 

Let me toss my two pennies: there is an option to auto-refill the belt from inventory, and there are added keys for auto-using health/mana potions -- those improvements affect the game in a more serious way! They make it less skill-dependent, much more easy to handle. But it was designed to be hard. Do you think we should remove this options too? Should we remove all the emprovements?

**Comment by kphoenix137** [comment]
> Let me toss my two pennies: there is an option to auto-refill the belt from inventory, and there are added keys for auto-using health/mana potions -- those improvements affect the game in a more serious way! They make it less skill-dependent, much more easy to handle. But it was designed to be hard. Do you think this options should be removed too?

These change help automate things you can already do manually, rather than changing how something inherently works, so no, I don't think they should be removed. Such reasoning can also be found in that PR I linked, where I explain that my proposed change for Adria refill is to make an existing functionality easier to do.

**Comment by Venyam-N** [comment]
> These change help automate things you can already do manually, rather than changing how something inherently works

When in the original Diablo 1 you had to retreat and refill your belt manually, in DevilutionX you can continue and win the fight. When belt is auto-refilled, you can click the mobs at the same time and do some damage, but when you move potions manually, you can't do damage -- so, this option adds something you can't do in the original game.

**Comment by kphoenix137** [comment]
> > These change help automate things you can already do manually, rather than changing how something inherently works
> 
> When in the original Diablo 1 you had to retreat and refill your belt manually, in DevilutionX you can continue and win the fight. When belt is auto-refilled, you can click the mobs at the same time and do some damage, but when you manually use/move potions from inventory during the fight, you can't do damage -- so, this option adds something you can't do in the original game.

It think we're spiraling into semantics. You could assert that nearly any change from vanilla to DevilutionX impacts how the game plays in some way, which could give way into asserting that it should be within project scope to change just about anything. That's what makes working with this project so difficult, because we have to make well thought out judgement calls and nothing is ever as black and white as it may seem.

**Comment by StephenCWills** [comment]
> Adria don't refill mana in the original game, but we have such an option in DevilutionX. Why can't we have additional options for shops?

We would close mana refill as well if it were proposed in the same manner as this request. Maybe this will become possible with Lua scripts, but I can't say whether anyone would be bothered to work on it.

**Comment by Venyam-N** [comment]
> We would close mana refill as well if it were proposed in the same manner as this request.

Excuse me if I said something impolite, it was not on purpose. It seems my English is not good enough to express myself in a proper manner((

**Comment by StephenCWills** [comment]
Ahh, no.. it's not that you were rude. It's just that the person who proposed mana refill was a developer who had made other contributions first. And when he proposed it, he actually wrote the code and submitted a PR. Additionally, he did it much earlier into the project when we were less worried about feature creep.

By contrast, this is just an out-of-the-blue feature request. I'm only saying that the circumstances cannot be compared.

**Comment by AJenbo** [comment]
Belt refill makes a big difference to people play on gamepad or touch

**Comment by Venyam-N** [comment]
> Ahh, no.. it's not that you were rude. It's just that the person who proposed mana refill was a developer who had made other contributions first.

Got it! Thanks for your detailed explanation.
