### ISSUE TITLE
[Issue Report]: SDL Error when changing to Upscale from in-game menu!

### ISSUE THREAD

**Issue by D1-Constantine** [diasurgical/devilutionX#7495]
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

Went to the menu, changed the setting to Upscale from the Graphics panel and got the error show bellow, no idea why it does that as it worked fine for 1.5.2
![Untitled](https://github.com/user-attachments/assets/5ef5a2fb-6805-4eb4-ba11-c5d39861f8f3)

### To Reproduce

1. Go to Setting -> Graphics
2. Turn on **Upscale**
3. Get the error with a black screen

Edit: (not sure if this is a me problem or if it for everybody else, but it seems it would have been reported and fixed quite fast if the error was not unique for me)

### Expected Behavior

Not crash the game upon choosing an option from the setting.

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/pull/7443
