### ISSUE TITLE
[Issue Report]: Speed bar in options is too wide when setting speed in diablo.ini

### ISSUE THREAD

**Issue by nesingho** [diasurgical/devilutionX#7505]
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

When I set the speed setting in diablo.ini to eg. 10 the speed bar in the game options (Esc -> Options) is too wide and hits the right screen border.

### To Reproduce

1. set speed in diablo.ini to a lower value than default (eg. 10)
2. start game
3. press Esc, go to options

### Expected Behavior

speed bar in game options is on the left side of the bar frame

**Comment by AJenbo** [comment]
The alternative is to cap the value and ignore what you set in your ini
