### ISSUE TITLE
[Issue Report]: Game crashes on switching audio output device when Windows language is set to Russian

### ISSUE THREAD

**Issue by Venyam-N** [diasurgical/devilutionX#7507]
### Operating System

Windows x64

### DevilutionX version

1.5.3

### Describe

This is a part 2 of an old issue  https://github.com/diasurgical/devilutionX/issues/7452  that  strikes back -- now after updating SDL to 2.30.9

I have a HP ProBook 445 G7 laptop with AMD Zen Audio Processor / HD Audio Controller ( Realtek High Definition Audio driver v. 6.0.9703.1) running Windows 10 22H2 19045.5011. When Windows language is set to Russian, the game crashes while changing audio output devices from built-in speakers to aux headphones. When Windows language is set to English, everything works properly.

### To Reproduce

1. Start the game sounding from speakers with unplugged headphones
2. Plug your headphones in
3. Game crashes. Or else, sound starts to glitch, and when you unplug the headhones and the game crashes anyway.

### Expected Behavior

Sound output device should change to headphones with no crashes

### Additional context

When the headphones are plugged before I run the game, unplugging them don't crash the game -- output switches to speakers with no glitches (that appeared on previous SDL version), but plugging them back still crashes the game.

Previous investigation by @StephenCWills: https://github.com/libsdl-org/SDL/issues/11122
Also, the game's behavior with system language set to RU end to EN differed on previous SDL version too.

**Comment by Venyam-N** [comment]
I've recorded a couple of videos to show how it works:

1. Windows language is set to RU, the headphones are plugged before running the game:
https://disk.yandex.ru/i/nwKoDTKK6pdINQ

2. Windows language is set to RU, the headphones are un-plugged before running the game:
https://disk.yandex.ru/i/Wz7DgIcKWGwjUg

3. Windows language is set to EN, the headphones are plugged before running the game:
https://disk.yandex.ru/i/gQ98jPuHnRhgaQ

4. Windows language is set to EN, the headphones are un-plugged before running the game:
https://disk.yandex.ru/i/IsIJCit4KqTJIQ

**Comment by StephenCWills** [comment]
I'm not finding anything useful from a code review. Can you check the Windows Event Viewer for new logs under the `Windows Logs > Application` category after a crash occurs? Maybe something useful will pop up there.

**Comment by Venyam-N** [comment]
Done. Started the game from command line with "--verbose" key and checked event viewer afterwards:
VERBOSE LOGS: https://disk.yandex.ru/i/SbeboSEVNSfsmQ
EVENT VIEWER LOGS: https://disk.yandex.ru/i/uCQZl8u6fsrlTw

**Comment by StephenCWills** [comment]
Okay, so exception code `0xc0000374` appears to indicate `STATUS_HEAP_CORRUPTION`. Sadly, this is still too generic, with a fairly sizable list of possible causes.

https://stackoverflow.com/a/1504307

Conventional wisdom seems to suggest reproducing the issue in a debugger. However, that would basically require me to set up a VM with the Russian language packs installed, get dev tools installed, and try to mock your audio setup. It's a lot of effort, and I'm not even sure if that last part is possible. I'm pretty much out of ideas on how to approach the issue for a solution, unless maybe we can enlist a developer who actually does speak Russian and is able to reproduce the issue on their developer system.

**Comment by glebm** [comment]
We're going to need output from a debug build of DevilutionX to diagnose this further.

We can supply a debug built later, for now, @Venyam-N, can you please install Visual Studio from https://visualstudio.microsoft.com/vs/community/? There is no need for you to compile anything, it simply has to be installed for the debug build to run.

**Comment by Venyam-N** [comment]
@glebm Done. What's next?

**Comment by glebm** [comment]
@Venyam-N Nice :+1: 
@StephenCWills will upload a debug build that you can run from the command line and hopefully get a much more detailed error message

**Comment by StephenCWills** [comment]
1. Unzip this to a directory on your computer: [devilutionX-1.5-Debug.zip](https://github.com/user-attachments/files/17791093/devilutionX-1.5-Debug.zip)
2. Open command prompt and `cd` into that directory
3. Run `devilutionx.exe --verbose 2> stderr.log`
4. Use your headphones to crash the game
5. Provide the output of `stderr.log` back to us

Please follow these steps as closely as you can. In particular, if you don't provide the `2> stderr.log` arguments, you won't get any logs on the command prompt at all.

**Comment by Venyam-N** [comment]
For some reason, debug verison doesen't crash (while generic 1.5.3 still does). Anyway, here are the logs: https://disk.yandex.ru/i/_sP3EACkBls8JQ

**Comment by StephenCWills** [comment]
> For some reason, debug version doesn’t crash and works just fine...

Seems that's okay. I think we still got what we needed from the logs.

**Comment by StephenCWills** [comment]
@Venyam-N Looks like SDL 2.30.10 just dropped. Since I was actually able to reproduce your issue this time, I'm pretty confident that this will completely resolve it. https://github.com/libsdl-org/SDL/releases/tag/release-2.30.10
