### ISSUE TITLE
Unable to load Diablo save game due to invalid monster animation

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#7509]
### Discussed in https://github.com/diasurgical/devilutionX/discussions/7508

> On dlvl 7, there is an Illusion Weaver that is walking northeast, but its animation info is invalid (ticksPerFrame is zero). It's causing a divide-by-zero error when trying to convert the level.

https://github.com/user-attachments/files/17621051/Saves.zip

**Comment by StephenCWills** [comment]
The debugger stops on this line.

https://github.com/diasurgical/devilutionX/blob/6318c557dec57360c8376f684e5b731e4965c997/Source/loadsave.cpp#L1434

Ronb1238 said that the save was created in vanilla Diablo, and that he only downloaded DevilutionX to transfer the save to Hellfire. This is just speculation, but it could be that this is a vanilla edge case for invisible Hidden-type monsters that wouldn't occur in saves created by DevilutionX.
