### ISSUE TITLE
macOS 10.4 Tiger PPC port

### ISSUE THREAD

**Issue by glebm** [diasurgical/devilutionX#7537]
@AJenbo tried with https://github.com/mistydemeo/tigerbrew/ with some success for older versions of DevilutionX, but ultimately cmake and gcc are too old to build the current master.

I'm now trying in a VM with MacPorts, which seems to have decent 10.4 support (it even provides backports of modern macOS headers: https://github.com/macports/macports-legacy-support) and much newer versions of all packages (cmake is 3.29, gcc12 reportedly works on 10.4, etc).

The latest release of MacPorts for macOS 10.4 is v2.9.3. After installing, it can be updated to the latest v2.10.3 with `sudo port selfupdate`. It's important to run `sudo port sync` before running `selfupdate` (https://trac.macports.org/ticket/71307)

Known issues:
* #653

**Comment by AJenbo** [comment]
For tigerbrew you need to first update the cmake install script to have it updated to 3.13, the changes needed to do so can be found here: https://github.com/mistydemeo/tigerbrew/pull/620

This will allow building up to 1.1.0 of DevilutionX. For later versions there is a linking error that I'm currently trying to track down.
