### ISSUE TITLE
ERROR: Requested Address is not valid in its context

### ISSUE THREAD

**Issue by clydevins** [diasurgical/devilutionX#754]
**Describe**
When trying to connect to an existing multiplayer game the error message is returned.

**To Reproduce**
1. Computer 1 creates multiplayer game with Password
2. Computer 2 enters IP Address
3. Computer 2 enters Password
4. Error message provided on Computer 2.

**Expected behavior**
Expected the Computer 2 to enter game created by Computer 1.

**Screenshots**
n/a - just error message

**Additional context**
The IP address was created by Computer 1 by default (not user inputted).

Windows 10 machines.

**Comment by AJenbo** [comment]
what is the ip, are both players on the same network?

**Comment by clydevins** [comment]
The IP created was 0.0.0.0 and presumed same network.

**Comment by AJenbo** [comment]
That isn't your IP, but what range it is limited to (no limit). You need to check your hosts IP. The game can't see that since you could be on a NAT or have multiple interfaces.

**Comment by clydevins** [comment]
I don't understand your response in terms of what I'm supposed to do about it ?  Computer/Host 1 assigned an IP.  There was no option to input an IP address.  If Computer 2 were to use the same IP Address of Computer 1 would that resolve the issue ?  None of this is stated/referenced in the readme file.  What is the normal protocol for folks to have multiplayer computers communicate.  Thanks.

**Comment by AJenbo** [comment]
Your computer is assigned an IP by your network (DHCP). The person joining needs to know the relative IP of the computer hosting the game.

Since both computers are on the same network this makes things easy as you only need to know the local IP. You can find this by following the guide that I linked above. If the computer hosting the game is not running Windows 10 then please let me know what it is running so that I can find a relevant guide for you.

**Comment by clydevins** [comment]
Progress I presume but not working yet.  Current situation.
Computer 1 creates game and notes IP address.
Computer 2 enters IP address and password.
Around a 20 pause ...
Then this error message:
"Connect: A Connection attempt failed because the connected party did not properly respond after a period of time, or establishe"

What do I do next to resolve ?

**Comment by AJenbo** [comment]
There's a few options this that could cause this. It could be the firewall, or network issues. You can try starting two games on the same computer in window mode and see if you can join locally, via the IP you noted, or 127.0.0.1 (local host). That will help narrow things down a bit.

**Comment by clydevins** [comment]
Ok will try that next.  When you say window mode - can you elaborate on how to do that.  Run it through a cmd prompt with a switch ( -w ? ) ... at the moment I copied a shortcut to the desktop and launch from there.

**Comment by clydevins** [comment]
More info if it helps.  Both computers have network profiles set to Public.  I click on Config firewall settinngs and see Domain/Private/Public Networks show Firewall ON (with Public being active).  When I click on allow an app through firewall ... I see 2 entries for the executable devilutionx.  One has private selected and one has public selected.  The one marked private is selected.  Does that help ?

**Comment by AJenbo** [comment]
You can switch fullscreen via alt+enter, you can launch in window mode with -x or set it in the ini

> First one has check box selected along with public. The second entry is not checked and shows Public selected. Does that help ?

Sorry I'm not a Windows user and not sure how to configure this.

**Comment by clydevins** [comment]
Presume that isn't the issue then and help troubleshoot the error message that I get.  Windows is a pretty common OS.

**Comment by AJenbo** [comment]
Let me know when you have tried running two instances on the same machine.

**Comment by clydevins** [comment]
O.K.  Instance 1 created game.  Instance 2 joined game.  That worked successfully.

**Comment by AJenbo** [comment]
Did you use the IP of the machine or 127.0.0.1?

**Comment by clydevins** [comment]
I used the IP of the machine found in settings.

**Comment by AJenbo** [comment]
Ok, I think that should rule out firewall issues. That means that the issue is probably in regards to how the network between the two machines are set up. Could you describ it in detail?

**Comment by clydevins** [comment]
Quick followup on previous connection made.  Instance 2 can join Instance 1.  Instance 2 can drop and rejoin.  Instance 1 cannot drop and rejoin ie hosting did not shift to Instance 2.  I did not that Instance 1 shows IP 0.0.0.0 and Instance 2 actually updates IP to correct IP that it joined (from Instance 1).

**Comment by clydevins** [comment]
Not sure what detail needed.  Both computers are laptops running Windows 10 using same wifi connection.  This is interesting.  If Computer 2 hosts game, Computer 1 is able to join.  Not vice versa.  Computer 1 is the newer of the two and the preferred host.  Computer 2 is older clunker.  The IP addresses used by both computers are different.

**Comment by AJenbo** [comment]
Each computer is assigned a unique IP. Diablo doesn't require much of your computer and there is almost no difference between being the host or client, so there isn't really any benefit to having one be a host instead of the other. It sounds like the issue is firewall related since you can do outgoing connections but not incomming.

**Comment by clydevins** [comment]
O.K. will continue exploring that path.  If nothing else I'll try and investigate the settings from both computers since one of them is acting ideally.  Thanks for helping to troubleshoot even though Windows not your forte.  While I'm here - 2 quick questions.  1. 
 Will an instance time out ?  And how to prevent that.  2) Did the setting/use of Hotkeys ever get fixed ?  Thx

**Comment by AJenbo** [comment]
The game should be quite tolerant to dropped packages before issuing a time out, but you should be able to just join back in if it happens.

Not sure what you are referring to in regards to fixing hotkeys? Spell hotkeys should work correctly if that is what you are referring to.

**Comment by clydevins** [comment]
I meant - if the host drops THEY won't be able to rejoin the game.  So want to prevent a host from timing out.

Hotkeys hasn't worked for me.  Just double checked.  Spellbook opened.  Cursor over a spell.  Select one of the F5-F8 function keys.  No change.  Would love help in that area because game dynamic very different at high levels.

**Comment by AJenbo** [comment]
The host is ... the host, there isn't an internet server involved. This is why you need to know the IP. So unless the computer dies it shouldn't time out.

F5-F8 works fine here, not sure what could be your issue. Maybe you have FN-lock enabled.

**Comment by clydevins** [comment]
Dang.  You were 100% right !!!  Not something I ever consciously changed.  Thx
