### ISSUE TITLE
[Issue Report]: The link to extract MPQs from the GoG installer is a dead link.

### ISSUE THREAD

**Issue by Glubs9** [diasurgical/devilutionX#7546]
### Operating System

Other (please specify)

### DevilutionX version

1.5.3

### Describe

On the readme, clicking the link to extract the MPQs from the GoG installer links to creating a new page with this title because the link is a dead link.

### To Reproduce

1. Go to the read me
2. Click on "[extract it from the GoG installer](https://github.com/diasurgical/devilutionX/wiki/Extracting-the-.MPQs-from-the-GoG-installer)"

### Expected Behavior

It should open a guide on how to extract the MPQs from the GoG installer

**Comment by qndel** [comment]
Correct link: https://github.com/diasurgical/devilutionX/wiki/Extracting-MPQs-from-the-GoG-installer

**Comment by AJenbo** [comment]
Thanks, fixed
