### ISSUE TITLE
[Feature Request]: Can we have a built-in updater

### ISSUE THREAD

**Issue by qwltorn** [diasurgical/devilutionX#7564]
### Feature Type

Quality of Life

### Describe

so that when new version comes, we can see the notification in game menu and update from there
maybe even a toggle for auto-update

**Comment by StephenCWills** [comment]
We use Google Play for Android. Other platforms would also need their own custom solution. For example, #7556 could provide this for Debian-based Linux distros.

We've talked about simply checking for new versions and displaying a notification, which is significantly easier to implement across platforms. However, that would still require support for http which we don't currently have. It would also have the potential to be a nuisance.

**Comment by AJenbo** [comment]
For Steam Deck and Linux there is FlatHub. Building this isn't trivial which is why Steam and Google Play exists.
