### ISSUE TITLE
How to compile cmake in visual studio 2019?

### ISSUE THREAD

**Issue by uwodb** [diasurgical/devilutionX#758]
I selected the release 64/32 but I can't build devilutionx.exe in visual studio 2019. This messages does not appear in debug compile.
Can anyone help me with this issue? Thanks in advance :)

 [143/144] Building CXX object CMakeFiles\devilutionx.dir\SourceX\dvlnet\tcp_server.cpp.obj
  Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
  - add -D_WIN32_WINNT=0x0501 to the compiler command line; or
  - add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
  Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
  [144/144] Linking CXX executable devilutionx.exe
  FAILED: devilutionx.exe 
  cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\devilutionx.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x86\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x86\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx86\x64\link.exe /nologo CMakeFiles\devilutionx.dir\SourceX\dx.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\devices\game_controller.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\devices\joystick.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\devices\kbcontroller.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\controller.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\controller_motion.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\game_controls.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\menu_controls.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\modifier_hints.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\plrctrls.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\touch.cpp.obj CMakeFiles\devilutionx.dir\SourceX\display.cpp.obj CMakeFiles\devilutionx.dir\SourceX\miniwin\misc_msg.cpp.obj CMakeFiles\devilutionx.dir\SourceX\thread.cpp.obj CMakeFiles\devilutionx.dir\SourceX\sound.cpp.obj CMakeFiles\devilutionx.dir\SourceX\soundsample.cpp.obj CMakeFiles\devilutionx.dir\SourceX\storm\storm.cpp.obj CMakeFiles\devilutionx.dir\SourceX\storm\storm_net.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\abstract_net.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\loopback.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\packet.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\base.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\frame_queue.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\cdwrap.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\art_draw.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\errorart.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\art.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\button.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\credits.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\credits_lines.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\diabloui.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\dialogs.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\fonts.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\mainmenu.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\progress.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\scrollbar.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selconn.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selgame.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selhero.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selyesno.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selok.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\text_draw.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\text.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\title.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\ttf_render_wrapped.cpp.obj CMakeFiles\devilutionx.dir\SourceX\main.cpp.obj CMakeFiles\devilutionx.dir\Packaging\windows\devilutionx.rc.res CMakeFiles\devilutionx.dir\SourceX\dvlnet\tcp_client.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\tcp_server.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\udp_p2p.cpp.obj  /out:devilutionx.exe /implib:devilutionx.lib /pdb:devilutionx.pdb /version:0.0  /machine:x64 /INCREMENTAL:NO /subsystem:windows  /INCREMENTAL:NO /LTCG  devilution.lib  PKWare.lib  StormLib.lib  smacker.lib  Radon.lib  C:\diablo\vcpkg-master\installed\x64-windows\lib\libsodium.lib  C:\diablo\vcpkg-master\installed\x64-windows\lib\SDL2_ttf.lib  C:\diablo\vcpkg-master\installed\x64-windows\lib\SDL2_mixer.lib  C:\diablo\vcpkg-master\installed\x64-windows\lib\manual-link\SDL2main.lib  wsock32.lib  ws2_32.lib  wininet.lib  C:\diablo\vcpkg-master\installed\x64-windows\lib\SDL2.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D C:\diablo\devilutionX-1.0.1\build\x64-Release && powershell -noprofile -executionpolicy Bypass -file C:/diablo/vcpkg-master/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/diablo/devilutionX-1.0.1/build/x64-Release/devilutionx.exe -installedDir C:/diablo/vcpkg-master/installed/x64-windows/bin -OutVariable out""
  LINK: command "C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx86\x64\link.exe /nologo CMakeFiles\devilutionx.dir\SourceX\dx.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\devices\game_controller.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\devices\joystick.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\devices\kbcontroller.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\controller.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\controller_motion.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\game_controls.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\menu_controls.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\modifier_hints.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\plrctrls.cpp.obj CMakeFiles\devilutionx.dir\SourceX\controls\touch.cpp.obj CMakeFiles\devilutionx.dir\SourceX\display.cpp.obj CMakeFiles\devilutionx.dir\SourceX\miniwin\misc_msg.cpp.obj CMakeFiles\devilutionx.dir\SourceX\thread.cpp.obj CMakeFiles\devilutionx.dir\SourceX\sound.cpp.obj CMakeFiles\devilutionx.dir\SourceX\soundsample.cpp.obj CMakeFiles\devilutionx.dir\SourceX\storm\storm.cpp.obj CMakeFiles\devilutionx.dir\SourceX\storm\storm_net.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\abstract_net.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\loopback.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\packet.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\base.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\frame_queue.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\cdwrap.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\art_draw.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\errorart.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\art.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\button.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\credits.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\credits_lines.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\diabloui.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\dialogs.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\fonts.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\mainmenu.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\progress.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\scrollbar.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selconn.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selgame.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selhero.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selyesno.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\selok.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\text_draw.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\text.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\title.cpp.obj CMakeFiles\devilutionx.dir\SourceX\DiabloUI\ttf_render_wrapped.cpp.obj CMakeFiles\devilutionx.dir\SourceX\main.cpp.obj CMakeFiles\devilutionx.dir\Packaging\windows\devilutionx.rc.res CMakeFiles\devilutionx.dir\SourceX\dvlnet\tcp_client.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\tcp_server.cpp.obj CMakeFiles\devilutionx.dir\SourceX\dvlnet\udp_p2p.cpp.obj /out:devilutionx.exe /implib:devilutionx.lib /pdb:devilutionx.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:windows /INCREMENTAL:NO /LTCG devilution.lib PKWare.lib StormLib.lib smacker.lib Radon.lib C:\diablo\vcpkg-master\installed\x64-windows\lib\libsodium.lib C:\diablo\vcpkg-master\installed\x64-windows\lib\SDL2_ttf.lib C:\diablo\vcpkg-master\installed\x64-windows\lib\SDL2_mixer.lib C:\diablo\vcpkg-master\installed\x64-windows\lib\manual-link\SDL2main.lib wsock32.lib ws2_32.lib wininet.lib C:\diablo\vcpkg-master\installed\x64-windows\lib\SDL2.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:devilutionx.exe.manifest" failed (exit code 0) with the following output:
  Generating code
C:\diablo\devilutionX-1.0.1\Source\drlg_l3.cpp(1346): fatal error C1001: Internal compiler error.
  (compiler file 'd:\agent\_work\6\s\src\vctools\Compiler\Utc\src\p2\main.c', line 181)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  If possible please provide a repro here: https://developercommunity.visualstudio.com 
  Please choose the Technical Support command on the Visual C++ 
   Help menu, or open the Technical Support help file for more information
  
  Access violation
  ninja: build stopped: subcommand failed.

**Comment by qndel** [comment]
https://github.com/diasurgical/devilutionX/blob/master/Source/drlg_l3.cpp#L1158
make j volatile, it's a bug in vs2019
