### ISSUE TITLE
[Issue Report]: 1.5.3 asset for miyoo mini not available

### ISSUE THREAD

**Issue by devcodable** [diasurgical/devilutionX#7582]
### Operating System

Other (please specify)

### DevilutionX version

1.5.3

### Describe

I’m running 1.5.0 on a miyoo mini but sadly it gets stuck on the loading screen when entering level 5 and/or catacombs.

Tried to update but there is no asset on the release 1.5.3 for the miyoo, even though it’s mentioned in the release notes.

Thank you for the great work!

### To Reproduce

.

**Comment by AJenbo** [comment]
miyoo mini missing for 1.5.3 is a known issue, please upgrade to 1.5.2 for now.

Catacombs have a rare bug where a level might not load, you have to start a new game, the chance of this happening is 1 in 5 million so it's unlikely that you will hit on it again. This is an original Diablo bug and it's not trivial to solve without breaking save game comparability.

**Comment by devcodable** [comment]
That was really unlucky for me then. I tried the new game thing and it works fine now. Thank you for the quick answer!

**Comment by AJenbo** [comment]
Glad you enjoy it :)
