### ISSUE TITLE
No gamepad cursor in inventory

### ISSUE THREAD

**Issue by NeonLightning** [diasurgical/devilutionX#759]
**Describe**
when you open inventory the controller doesn't work to navigate the inventory.

**To Reproduce**
only seems to happen on void linux that i've noticed sofar.
but all you have to do to reproduce it is use a controller and open inventory.

**Expected behavior**
cursor control with gamepad in inventory.

**Screenshots**
can't figure out how to take screenshots without xserver

**Additional context**
as stated. only seems to happen on void linux sofar that i've noticed. i've tried 1.0.1 and git.
also controls work otherwise. i can even close the inventory window just fine. all that doesn't work is the cursor control.
got someone else to try and they encountered the same issue. but found out that mouse based control is still working.

**Comment by AJenbo** [comment]
is this using wayland?

**Comment by SeongGino** [comment]
That "someone else" here.

> 
> 
> is this using Wayland? Afaik Wayland doesn't allow for programmatic positioning of the mouse cursor and so SDL can't implement this feature which might be why the game, in the end, cannot control the mouse via the gamepad.

Nope, using no display server, all SDL2 (2.0.12).

**Comment by AJenbo** [comment]
We have narrowed it down to the fact that the SDL backend that you are using doesn't implement SDL_WarpMouseInWindow correctly, there isn't really much we can do about this and you need to either talk to the SDL developers or the distro maintainers. Using Xorg would solve the problem as SDL works correctly here.
