### ISSUE TITLE
[Feature Request]: Search Spell: Less Redundant?

### ISSUE THREAD

**Issue by Chonkblonk** [diasurgical/devilutionX#7600]
### Feature Type

Quality of Life

### Describe

As it is, what Search Spell does is highlight items on the ground, and also on the map, but this spell becomes mostly redundant when DevX plain just allows Diablo 2 style item highlighting anyway. DevX's current features makes the spell/skill pointless.

So, what if there was an option for letting Search highlight chests and other containers? That's something which would actually be useful IMO, because in places like Cave and Nest, sometimes chests are obscured by foreground walls, and on the smaller end, the slightly awkward boundary for things like Decapitated Bodies means it's not always immediately obvious if they've been searched or not.

This is a problem which a modified Search would help me actually solve, and which would make me actually want to use the spell.

A potential minor issue I see with this is that it would probably reveal hidden chests in special floors like King Leoric's Tomb and Chamber Of Bone. However, fact is that these chests are already entirely selectable even when they're still obscured, if you hover around with the mouse in the right spot you can highlight them, and then you can use Telekinesis to open and then plunder them, without opening their hidden rooms.

**Comment by StephenCWills** [comment]
We are planning to add this as an accessibility feature rather than modifying the Search spell. See #6182

Furthermore, modifying the Search spell sounds like mod territory.

**Comment by Chonkblonk** [comment]
Alright, I'm content with that approach too.

**Comment by julealgon** [comment]
> Furthermore, modifying the Search spell sounds like mod territory.

Have you guys considered flat out disabling the 'Search' spell/ability? At this point that spell is just completely useless and only serves to cause confusion as to why it exists IMHO.

For monk, it could maybe be replaced by a "passive skill" icon + description that detailed his adjacent tile damage capability, or something along those lines. Or you could just say "the monk has no skills" or whatever if you don't want to go there.

**Comment by StephenCWills** [comment]
> Have you guys considered flat out disabling the 'Search' spell/ability? At this point that spell is just completely useless and only serves to cause confusion as to why it exists IMHO.

DevilutionX allows you to disable or simply not use the item highlight feature, for a more vanilla-like experience. In that case, Search has exactly the same utility as it did in OG Hellfire. Maybe you could argue that nobody actually does this in practice, but it's not been our policy to compromise the principles of the project based on flaky supposition.

**Comment by Chonkblonk** [comment]
> > Furthermore, modifying the Search spell sounds like mod territory.
> 
> Have you guys considered flat out disabling the 'Search' spell/ability? At this point that spell is just completely useless and only serves to cause confusion as to why it exists IMHO.
> 

This is why I suggested modifying the spell so that it had a better purpose, but also one in line with its original purpose (finding items). Having to cast Search to find obscured containers and thus spending mana on it, I feel would be a bit less cheaty than just having container highlighting be an on and off toggle in options. Again also, it gives it purpose in spite of item highlighting existing.

Still, I'll settle for the other solution just the same, as it solves my problem.

**Comment by julealgon** [comment]
> **DevilutionX allows you to disable** or simply not use **the item highlight feature**, for a more vanilla-like experience.

You are right @StephenCWills , I had completely forgotten about the bolded in particular. If that feature is optional, other stuff can't be done based on its presence, totally agree there.

On a side note.... it's amazing to me that the Hellfire team saw the problem with item highlighting/visibility and the difficulty of spotting some items, and then decided that creating a _spell_ to highlight items was a good fix for that. Holy shit at that game design sense and/or laziness.
