### ISSUE TITLE
Caves Door Multiplayer Tearing

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#762]
**Describe**
In a multiplayer game with other players, there is visual tearing with the doors in caves when other players open or close the door. If you open or close the door yourself, there is no tearing on your client, but if the other player opens the door, there is tearing. I do not believe this issue exists in retail Diablo.

**To Reproduce**
1. Go to any floor on in the Caves section with at least two players in the same game.
2. Find a door.
3. Open the door one client. The other client will have tearing.

**Expected behavior**
Regardless of which player opens the door, no clients should see any visual tearing.

**Screenshots**
![tearing](https://user-images.githubusercontent.com/28605404/87899587-a6d51200-ca1f-11ea-81c0-57f4a9201050.png)

**Comment by AJenbo** [comment]
From what we were able to see when researching this it only happens on some levels and also happened in the original game. Thanks for the additional information, we will look to resolve it in the not to fare feature (regardless of it being vanilla or not).

**Comment by Baracudus** [comment]
I have the same issue, also a pattern error (??) in the caves. Savegame and Screenshot included!
[multi_0.zip](https://github.com/diasurgical/devilutionX/files/5457564/multi_0.zip)

![error](https://user-images.githubusercontent.com/71731621/97554561-3acb5800-19d7-11eb-8286-59b65029af6c.png)
![error2](https://user-images.githubusercontent.com/71731621/97554650-5b93ad80-19d7-11eb-96c7-9e1a7be3e85b.png)

**Comment by AJenbo** [comment]
This has been fixed
