### ISSUE TITLE
multi-byte characters support 

### ISSUE THREAD

**Issue by uwodb** [diasurgical/devilutionX#765]
My goal is multi-byte characters support in devilutionX and I want to replace the font displayed on the menu screen(and in-game screen) with another ttf.

I have already succeeded in printing multi-byte characters in the credits screen.
I can solve it by editing pcx(ui_art\fontXX.pcx) and cel(ctrlpan\smaltext.cel data\bigtgold.cel data\medtexts.cel) files, but using TTF_RenderUTF8_Solid() method helps to reduce my workload.

sourcex\diabloui\ui_item.h

			struct UiArtText : public UiItemBase {
			//	constexpr UiArtText(const char *text, SDL_Rect rect, int flags = 0)
			//	    : UiItemBase(rect, flags)
			//	    , text(text)
			//	{
			//	}
				constexpr UiArtText(const char *text, SDL_Color color, SDL_Rect rect, int flags = 0)
				    : UiItemBase(rect, flags)
				    , color(color)
				    , shadow_color { 0, 0, 0, 0 }
				    , text(text)
				    , render_cache(nullptr)
				{
				}

			//	const char *text;

				constexpr UiArtText(const char *text, SDL_Rect rect, int flags = 0)
				    : UiArtText(text, SDL_Color { 243, 243, 243, 0 }, rect, flags)
				{
				}

				SDL_Color color;
				SDL_Color shadow_color;
				const char *text;

				// State:
				TtfSurfaceCache *render_cache;

				void FreeCache()
				{
					delete render_cache;
					render_cache = nullptr;
				}

			};

sourcex\diabloui\diabloui.cpp

			void Render(UiArtText &ui_art_text)
			{
			//	DrawArtStr(ui_art_text.text, ui_art_text.rect, ui_art_text.flags);

				DrawTTF(ui_art_text.text, ui_art_text.rect, ui_art_text.flags,
				    ui_art_text.color, ui_art_text.shadow_color, &ui_art_text.render_cache);
			}

![1](https://user-images.githubusercontent.com/56031577/88270359-7b4c7300-cd10-11ea-92b1-13b39ce62911.png)

How can I display ttf font in menu screen ? :(

"no bitmap font, print text only" Can anyone help me with this? Thanks in advance :)

**Comment by noword** [comment]
I trace debugging the program, figure out that the ttf font was not be loaded.
Add "LoadTtfFont" in "UiInitialize" function of diabloui.cpp.

**Comment by AJenbo** [comment]
Looks like you solved the problem :)

**Comment by uwodb** [comment]
Yes. It work out. Thanks to you. :)
