### ISSUE TITLE
Integer Scaling from GPU driver does not work

### ISSUE THREAD

**Issue by CaptainCosmotic** [diasurgical/devilutionX#767]
**Describe**
The game seems to use a bilinear filter for scaling. It's always blurry.
If I play the GOG release (even with integer scaling disabled in the game options) my Radeon Software Integer scaler scales the game very crisp.

**To Reproduce**
1. Own a new Radeon Graphics Card
2. Enable GPU Scaling and Integer Scaling in the Display options
3. Launch original Diablo and DevilutionX 
4. See the difference

**Comment by CaptainCosmotic** [comment]
Okay, I fixed it myself. I just lowered the scaling quality in the diablo.ini to 0

**Comment by sskras** [comment]
Instead of closing the bug, it probably needs some way to ease the scaling reconfiguration by a user.

**Comment by qndel** [comment]
I see no bug, I see a feature that solved the problem when got used properly

**Comment by CaptainCosmotic** [comment]
I think it would be nice to see an integer scaler implemented in the game which ist Wirkung independent from the graphics driver (like in the gog release)
I dont need an ingame button for this but maybe a hint in the readme.txt would be nice.

**Comment by AJenbo** [comment]
Actual integer scaling has now been implemented, it can be set via diablo.ini

**Comment by CaptainCosmotic** [comment]
This is very nice

**Comment by MaxDesiatov** [comment]
Could someone clarify please what setting in `diablo.ini` can be used for this? Shouldn't this be documented in `README.md` or some other document linked from it?

**Comment by AJenbo** [comment]
At the moment diablo.ini is for advanced users who feel like exploring. Most of the settings have been mentioned in the release notes so the info is floating around, and of-cause there is the option to read the code :)
Having it documented would be really nice, I would be happy to answer questions regarding the options if someone wants to make a PR that documents the options.
