### ISSUE TITLE
Compile error 64-bit

### ISSUE THREAD

**Issue by VonKossa** [diasurgical/devilutionX#77]
Compile error when trying to compile with latest git.

[ 99%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/main.cpp.o
[100%] Linking CXX executable devilutionx
libdevilution.a(town.cpp.o): In function `dvl::T_DrawGame(int, int)':
town.cpp:(.text+0x595d): undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
town.cpp:(.text+0x5984): undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
libdevilution.a(town.cpp.o): In function `dvl::T_DrawZoom(int, int)':
town.cpp:(.text+0x5c57): undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
town.cpp:(.text+0x5c7d): undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/devilutionx.dir/build.make:528: devilutionx] Error 1
make[1]: *** [CMakeFiles/Makefile2:262: CMakeFiles/devilutionx.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by aldomann** [comment]
I'm getting essentially the same error with the [`devilutionx-git`](https://aur.archlinux.org/packages/devilutionx-git) AUR package:

```
[100%] Linking CXX executable devilutionx
/usr/bin/ld: libdevilution.a(town.cpp.o): in function `dvl::T_DrawGame(int, int)':
/home/aldomann/.cache/yay/devilutionx-git/src/devilutionx/Source/town.cpp:794: undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
/usr/bin/ld: /home/aldomann/.cache/yay/devilutionx-git/src/devilutionx/Source/town.cpp:798: undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
/usr/bin/ld: libdevilution.a(town.cpp.o): in function `dvl::T_DrawZoom(int, int)':
/home/aldomann/.cache/yay/devilutionx-git/src/devilutionx/Source/town.cpp:902: undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
/usr/bin/ld: /home/aldomann/.cache/yay/devilutionx-git/src/devilutionx/Source/town.cpp:906: undefined reference to `dvl::town_draw_upper(int, int, int, int, int, int, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/devilutionx.dir/build.make:528: devilutionx] Error 1
make[1]: *** [CMakeFiles/Makefile2:262: CMakeFiles/devilutionx.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by AJenbo** [comment]
Working on it, the good news is that the update makes the game mostly playable on x86_64.

You can also see this in twee build status of the project for both x86_64 Linux and Mac builds.

**Comment by AJenbo** [comment]
64bit builds are now fixed, and as opposed to previously are now some what playable.
