### ISSUE TITLE
Item "Drift" in Inventory

### ISSUE THREAD

**Issue by mgpat-gm** [diasurgical/devilutionX#770]
**Describe**
When you pick up an item in the inventory, it "drifts" to the left(left,up in win10). If you pick it up multiple times without moving the cursor, eventually the item will not fall back in the slot you grabbed it from.

**To Reproduce**
1. Hover cursor over any item in the inventory
2. Left click with mouse.
3. Do not move cursor.
4. Left click again.
5. Repeat 1-4 without moving the cursor to dramatic effect.

**Expected behavior**
When an item is picked up in vanilla, it jumps so that the item is centered on your cursors location when you clicked on it. It appears as though the cursor is the object that is moving, not the item, in devilutionx. This can have a direct effect on gameplay. If you are trying to get inventory items into your belt or swap items during a battle you could be hindered. It is fairly minor, but noticeable.

**Additional context**
Version: 
- 1.0.1
OS:
- Ubuntu 18.04
- Windows 10

**Comment by qndel** [comment]
For me it jumps just like in vanilla, I spammed the cursor for good 30 seconds, failed to reproduce

**Comment by mgpat-gm** [comment]
https://www.youtube.com/watch?v=XFEwH2UiOIw

This was on kubuntu 20.04. It is virtually the same on each OS I use. When I seemingly pause, it is because the item has moved to a spot that cannot be dropped to.

**Comment by qndel** [comment]
could you compile latest ver and try it there?

**Comment by mgpat-gm** [comment]
Build version: 1.0.1-8ca15061 on Ubuntu 18.04 has same issue.

**Comment by qndel** [comment]
is this latest? : P

**Comment by mgpat-gm** [comment]
Maybe I'm not sure what you mean by "latest version". I cloned the repo, compiled it, and tested it. Do you mean compile the lastest release?

As for Windows, I cannot compile from source. I only use Windows at work and keep software installations to a minimum.

**Comment by AJenbo** [comment]
@mgpat-gm could you try this in a window where no scaling has been applied, afaik this is caused by rounding errors. If possible try providing a video of the issue.

**Comment by mgpat-gm** [comment]
@AJenbo It appears you are correct. I cannot reproduce this in windowed mode.

**Comment by AJenbo** [comment]
I wonder if this is an issue if you enable interger scaling?

**Comment by mgpat-gm** [comment]
Someone with an Nvidia Turing card, AMD Ryzen 2000 or later with integrated graphics, ATI Radeon GCN(circa 2011+) architecture, or Intel Gen 11 graphics will have to test it out. Sadly, none of my four PCs have any of those.

**Comment by mgpat-gm** [comment]
OIC what you mean. It could be remedied by commit #785

**Comment by AJenbo** [comment]
Yes, if enabled in ini

**Comment by mgpat-gm** [comment]
It worked fine with the integer scaling turned on.
