### ISSUE TITLE
Can’t close game

### ISSUE THREAD

**Issue by ntaraku2** [diasurgical/devilutionX#778]
Upon exit game crashes on all versions for switch forcing applet mode to close back to switch menu.

**Comment by AJenbo** [comment]
From tests done today, it looks like this problem has been solved.

**Comment by ntaraku2** [comment]
> From tests done today, it looks like this problem has been solved.

From tests done today using the latest release now rather that closing the app to switch menu I get atmosphere error wall code and have to reboot or boot into payload. Anything I can do to help I’ll be happy to.

**Comment by AJenbo** [comment]
I that version 1.1.0, or build from master?

**Comment by AJenbo** [comment]
Do you have the same issue with older versions? Can you try and build the latest code or use a nightly build. Can you provide more details regarding your system and how you start the application?

**Comment by ntaraku2** [comment]
> Do you have the same issue with older versions? Can you try and build the latest code or use a nightly build. Can you provide more details regarding your system and how you start the application?

I haven’t used any builds other than the download link below assets for switch-devolutionx.

Old switch booting emu-10.2.0 switch version and Atmosphere 0.14.4.

to open home brew I hold “R” button over my game card app while loading, then select DevolutionX.

on all versions everything plays fine until I quit. Then I’ve struggled to return to homebrew menu like I normally do when closing a homebrew app. 

Exit Diablo always had issues giving error codes.

sorry if this is not helpful enough, I’ll be more than happy to answer all questions the best I can.

how would I build the latest version on windows or iOS? Is the latest release not the same?

**Comment by ntaraku2** [comment]
> Do you have the same issue with older versions? Can you try and build the latest code or use a nightly build. Can you provide more details regarding your system and how you start the application?

![67B8D894-7871-4D01-9521-E8E0673C6897](https://user-images.githubusercontent.com/26215007/104671966-760b2800-56a4-11eb-8401-e683bf8890bb.jpeg)

**Comment by AJenbo** [comment]
Curious, no one else using the Switch builds have reported this issue.
Here is a link for the latest test build: https://15404-143324737-gh.circle-artifacts.com/0/devilutionx.nro
@rsn8887 do you have any idea what might be going one here?

**Comment by ntaraku2** [comment]
> Curious, no one else using the Switch builds have reported this issue.
> Here is a link for the latest test build: https://15404-143324737-gh.circle-artifacts.com/0/devilutionx.nro
> @rsn8887 do you have any idea what might be going one here?

Interesting because it’s the first thing I install both times I’ve installed atmosphere fresh on a SD card. 
Both times have me the same results.

**Comment by ntaraku2** [comment]
I fixed by replacing the diabdat.mpq file from presumably my hellfire mod and copied it directly from the pc cd and it works now.
