### ISSUE TITLE
In-game scaling is not DPI-aware

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#786]
I found out about this while working on #784.

Turns out that SDL is currently adjusting the screen bounds based on the external Windows DPI scaling setting. Since I actually use 125% scaling on my machine (yeah... I'm kinda blind, don't mock me), the in-game scaling was completely off when going fullscreen. Instead of considering the full 1080p resolution of my monitor, SDL was adjusting it to 1536x864, effectively causing a second scaling to happen from that resolution up to 1920.

![image](https://user-images.githubusercontent.com/461579/91786121-48ce4980-ebdd-11ea-9957-436382e29851.png)

![image](https://user-images.githubusercontent.com/461579/91786139-4ff55780-ebdd-11ea-899d-ee372cd4ab3b.png)

Here is how the game looks when all this happens (absolutely terrible):

![image](https://user-images.githubusercontent.com/461579/91786240-8af78b00-ebdd-11ea-84cd-c6d6af250752.png)

It looks like we have to make DevilutionX DPI-aware to solve this problem. I have not looked at it yet but here is a useful article:
https://nlguillemot.wordpress.com/2016/12/11/high-dpi-rendering/

**Comment by qndel** [comment]
I use 125% too

**Comment by julealgon** [comment]
Just found a way to "fix" this which is seemingly very simple:

![image](https://user-images.githubusercontent.com/461579/92061746-6df1c200-ed6d-11ea-8e76-b7e6b63884db.png)

Setting this scaling overide fixes the integer/"fake resolution" scaling issue.

I'll see how I can integrate this in the source directly to avoid having to set this flag in the `exe`.
