### ISSUE TITLE
Scrolls and charges not consumed correctly if swapped before hit-frame

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#792]
When using a scroll from the spell position (speedbook -> select scroll -> right click), if the user casts the scroll spell, and then quickly changes to a different spell, the scroll is not consumed.

The same behavior happens for charges in a staff.

| Casting scroll without consuming it | Casting charge without consuming it | Casting and consuming different scroll |
| --- | --- | --- |
| ![cast-scroll-not-consumed](https://user-images.githubusercontent.com/461579/92314288-1725fb80-efac-11ea-895d-842f65ecde07.gif) | ![cast-charge-not-consumed](https://user-images.githubusercontent.com/461579/92314290-1d1bdc80-efac-11ea-9f4c-7cab52aac4bc.gif) | ![different-scroll-consumed](https://user-images.githubusercontent.com/461579/92314439-cca57e80-efad-11ea-9b35-3de593abcf13.gif) |

This occurs because scroll removal and charge deduction are done based on the spell selection at the time it executes, that is, it only removes the scroll and charges for the spell corresponding to the selection at the bottom right corner (the right button action). 
- For scrolls, the first scroll matching the spell selection is removed. Lookup searches from inventory, then from belt
- For charges, the logic checks if the currently equiped staff's spell matches the current selection, and only deducts a charge if the spell matches

All this happens inside the `UseMana` function. This function executes right after the "missile is created" (weird for Identify, but there you go... pretty much everything is a "missile" in this game) which in turn happens right at the hit-frame (the animation frame that causes the action to trigger).

I believe the obvious issue here is that the "link" used between the initial cast and the action is really weak (it can easily change between the initial frame and cast frame). Instead of relying on the current selection, it should perhaps save/transfer item information from one frame to the other, and then act on the specific item.

From my understanding, this would require significant changes. I'm not entirely sure if we can use the `pVar` values to add some data to try and help find the correct item, but that's something I thought about.

**Comment by AJenbo** [comment]
pVar and friends are scary, it's basically global temp vars that may be used by any code for anything at any time. If you can understand their usage well enough to do this safely I'm not against that approach, but I at least can't provide much insight in to it.

**Comment by mgpat-gm** [comment]
I'm adding the link so it's pinged in the upstream vanilla bugtracker. https://github.com/diasurgical/devilution/issues/64 ?
