### ISSUE TITLE
Scroll removal behavior is different when using as items vs using as spell

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#793]
While working on #789, I noticed that the behavior of scrolls is different if you use them as an item (belt hotkey, or right-click in inventory) vs using them as a spell (selecting on speed book, then right clicking).

| Direct use (instant consumption) | Spell use (consume on hit) |
| --- | --- |
| ![item-use-instant-consumption](https://user-images.githubusercontent.com/461579/92314582-24dd8000-efb0-11ea-8605-d3d630fee8ef.gif) | ![spell-cast-delayed-consumption](https://user-images.githubusercontent.com/461579/92314583-27d87080-efb0-11ea-8dfc-a1241b3dfd30.gif) |
| Clicked scroll is immediately removed from inventory on the same frame as the click happens &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | A scroll of the same spell is removed from inventory/belt after the spell is cast, on the same frame that mana is reduced for normal spells (after hit-frame, on missile fired) |

Currently, the way scrolls are removed relies on the player's "Spell Selection", which is also flawed (see #792).

I believe using a scroll directly should also result in it being removed only after the spell is cast, this way being consistent with spells. Let me know if that makes sense and I could look into this further.

**Comment by mgpat-gm** [comment]
@julealgon Nice work. Do you mind posting this and the other in the vanilla bug issue tracker @ https://github.com/diasurgical/devilution/issues/64 ?
