### ISSUE TITLE
Optionally disable Blizzard logo splash screen

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#794]
The original game has a flag that disables the intro cinematic after it has been seen once. For similar purposes, I'd like to propose that we introduce a separate flag to hide the Blizzard splash screen on startup.

The idea is to make getting into the actual game a bit faster.

**Comment by julealgon** [comment]
After checking this for a couple minutes, I realized there is already a custom cmdline argument for disabling this in `diablo.cpp`, `-n`.

https://github.com/diasurgical/devilutionX/blob/9e1428dd0b7738c0c305ffaa0b7e7882736c94f0/Source/diablo.cpp#L356

I have no idea how to pass arguments to the exe while debugging using CMake though. However, that's outside the scope of this request, so I'm closing it.

**Comment by AJenbo** [comment]
What are you running on? What IDE do you use, and how do you compile and run the game?

**Comment by julealgon** [comment]
@AJenbo I'm using Visual Studio 2019. Run/compile using F5 after opening the cmake file.
