### ISSUE TITLE
Incorrect Blighthorn Steelmace Palette

### ISSUE THREAD

**Issue by mgpat-gm** [diasurgical/devilutionX#795]
**Describe**
Blighthorn Steelmace palette is not showing the white pixels.

DevilutionX: | Vanilla
------------ | -------------
![4](https://user-images.githubusercontent.com/60494513/92315342-67a05780-efb2-11ea-9153-5d8862cd74a8.png) | ![1](https://user-images.githubusercontent.com/60494513/92315345-7129bf80-efb2-11ea-8ce3-7af4305b970c.png)
![5](https://user-images.githubusercontent.com/60494513/92315343-6a02b180-efb2-11ea-95fd-cd2ee0a7121e.png) | ![2](https://user-images.githubusercontent.com/60494513/92315349-84d52600-efb2-11ea-82f8-d407da082494.png)
![6](https://user-images.githubusercontent.com/60494513/92315344-6c650b80-efb2-11ea-8eb7-2a683ce55601.png) | ![3](https://user-images.githubusercontent.com/60494513/92315350-869ee980-efb2-11ea-84c8-31cefa3377ea.png)

Additional Info:
When using the monster.cpp info to recreate him in The Dark Graphics, the color is completely different.
Thanks KPhoenix for vanilla pics

**Comment by qndel** [comment]
he's using dungeon palette, why would you want him to show white pixels? It's ugly

**Comment by AJenbo** [comment]
i dont remember this being explicitly fixed so interestibg to find out what changed

**Comment by qndel** [comment]
are these 2 screenshots from the same save? Maybe you just had different dungeon palettes?

**Comment by sskras** [comment]
Do the behaviours of last 3 pics present in vanilla too?

**Comment by mgpat-gm** [comment]
> he's using dungeon palette, why would you want him to show white pixels? It's ugly

It's sexy and you know it.

@qndel
> are these 2 screenshots from the same save? Maybe you just had different dungeon palettes?

@sskras
> Do the behaviours of last 3 pics present in vanilla too?

The first set of 3 images is from devilutionX. The second set of three is from retail version.

**Comment by malvarenga123** [comment]
![image](https://user-images.githubusercontent.com/61893389/92414871-90e4f300-f12c-11ea-8bda-b7fde93adb84.png)
How can this be vanilla?

**Comment by mgpat-gm** [comment]
It's the torch mod monster health bar that works on classic/retail/vanilla Diablo.

**Comment by mgpat-gm** [comment]
> are these 2 screenshots from the same save? Maybe you just had different dungeon palettes?

I pieced together just now what you meant by that; Blighthorn uses the dungeon palette and if the dungeon palette changes, his display color would then possibly change.

You stated in #593 that quests can change the palette. Is there anything in multiplayer that could change the dungeon palette in vanilla?

**Comment by qndel** [comment]
not sure about catas but church has 5 random palettes

**Comment by julealgon** [comment]
> not sure about catas but church has 5 random palettes

Catacombs has quite a few as well:

![image](https://user-images.githubusercontent.com/461579/92669631-84a59500-f2e8-11ea-9823-8d52dd62fd87.png)

From the pictures provided, it is quite clear to me that level palettes are different. Notice the out of bounds area:

| Red/Brown (DevilutionX) | Blue (vanilla) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/461579/92669812-fb429280-f2e8-11ea-9499-6b80ebb8d178.png) | ![image](https://user-images.githubusercontent.com/461579/92669859-157c7080-f2e9-11ea-9226-67dbfa1b6e36.png) |

Could this be a palette oversight in the original game as well? The random white pixels do seem like a bug to me on first glance. Perhaps they were never intended? Maybe Blizzard didn't properly test all monsters with all palettes? 

@mgpat-gm , can you double check this using the exact same palette/seed across games?

**Comment by mgpat-gm** [comment]
> can you double check this using the exact same palette/seed across games?

I haven't a clue how to do that.

**Comment by julealgon** [comment]
> I haven't a clue how to do that.

Since save files are compatible between DevilutionX and vanilla, you should be able to find the situation in vanilla first (with the white pixels), save your character there, then copy the save file and load it in DevilutionX.

**Comment by mgpat-gm** [comment]
Save 1 Ubuntu Devilution 1.0.1:
-----------
![test1-1 0](https://user-images.githubusercontent.com/60494513/93231480-c4380b00-f746-11ea-90e7-062adae7c5a9.png)
![test1-1 1](https://user-images.githubusercontent.com/60494513/93231482-c4380b00-f746-11ea-9a84-29d1b09bcb9e.png)

Save 1 XP VM Vanilla:
-----------
![test1-2 0](https://user-images.githubusercontent.com/60494513/93231564-db76f880-f746-11ea-8553-f4e5bb69488e.png)
![test1-2 1](https://user-images.githubusercontent.com/60494513/93231565-db76f880-f746-11ea-941d-7ee0cfbb4956.png)

Save 2 Ubuntu Devilution 1.0.1:
-----------
![test2-1 0](https://user-images.githubusercontent.com/60494513/93231617-ed589b80-f746-11ea-921a-051094007347.png)
![test2-1 1](https://user-images.githubusercontent.com/60494513/93231618-ed589b80-f746-11ea-9cb6-de35ad0b6fdf.png)

Save 2 XP VM Vanilla:
-----------
![test2-2 1](https://user-images.githubusercontent.com/60494513/93231686-fea1a800-f746-11ea-93ad-70aabf23f853.png)
![test2-2 2](https://user-images.githubusercontent.com/60494513/93231688-ff3a3e80-f746-11ea-9a82-90fbd859c0f3.png)

Save 3 Ubuntu Devilution 1.0.1:
-----------
![test3-1 1](https://user-images.githubusercontent.com/60494513/93231768-1aa54980-f747-11ea-9c9c-6676528c6ae8.png)

Save 3 XP VM Vanilla:
-----------
![test3-2 1](https://user-images.githubusercontent.com/60494513/93231789-20029400-f747-11ea-9d3b-cab5677adf76.png)

Corresponding save files (labeled test[1,2,3]):
-----------
[test.zip](https://github.com/diasurgical/devilutionX/files/5226077/test.zip)

**Comment by mgpat-gm** [comment]
Also of note is in saves 1 & 2, the palette is different in devilution vs vanilla for the dungeon as well.

**Comment by AJenbo** [comment]
Time to bisect i guess

**Comment by AJenbo** [comment]
Tested all releases back to 0.3.1 (Mar 20, 2019)
All of them render Blightorn the same.

@mgpat-gm could you provide PCX screen shots from both vanila and DevilutionX (preferably with Blightorn in the same position in both)? Using that I can say a bit more about what's going on.

**Comment by AJenbo** [comment]
Ok by complete random chance while working on something else I noticed that if you change the gamma the game will render like the original Diablo, even if you lower it back to its original setting.

This actually seems to be a bug in the original game as the white pixels are now affected by fadeouts.
Also if you save the game and restart the game the rendering will again be correct with the non-default game applied:
![image](https://user-images.githubusercontent.com/204594/94368091-ad000280-00e2-11eb-931d-29b708277080.png).

When generating the trn files the original artist was probably working in an external tool like DeBabelizer where this issue was not present. Before claiming total victory though I would like to understand exactly why this happens, and also the behavior should be consistent when ganging the gamma value.

**Comment by AJenbo** [comment]
Turns out this is actually a vanilla bug where only the first 255 colors are affected by the fadeout/fade-in. The fade is what actually loads to colors for DevilutionX so this in turn had the effect seen in this bug report.

**Comment by mgpat-gm** [comment]
@AJenbo Wild! Should I open a different issue for the inconsistent color rendering of the walls?

**Comment by AJenbo** [comment]
Sure, especially if you attache some save games that will make it as easy to debug as this one :)
