### ISSUE TITLE
Avoid restarting music on same-tileset dungeon level transition

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#799]
This one is a suggestion for what I believe should be a simple change somewhere in the level loading logic. When moving from one floor to the next _on the same tileset_, I propose we do not stop playing the music. Currently, the music stops for the loading screen, and then starts over from the beginning after it finishes.

If we could check for the floor transition and validate that it is the same tileset as the previous level, we could keep the music going without interruption to provide a more seamless experience.

I also believe keeping the music playing is slightly more immersive.

IIRC, the "The Hell" MOD implemented something along these lines. I haven't played a lot of other mods so it might be the case for others as well.

Obviously, this being an improvement is my personal take. If the team agrees this is an interesting idea, I could look into it at some point. I have not looked into the implementation for this one yet.

**Comment by AJenbo** [comment]
GOG also appears to have employed a hack to make the music continue playing in the menu. Basically they commented out this line in ASM https://github.com/diasurgical/devilutionX/blob/3227fea5c0926a661e38256600e37579605e4ff4/Source/mainmenu.cpp#L133

**Comment by CaptainCosmotic** [comment]
Can we update this to also don't restart the music if a savegame is loaded on the same level/tileset or should I open a new issue?

**Comment by julealgon** [comment]
> Can we update this to also don't restart the music if a savegame is loaded on the same level/tileset or should I open a new issue?

That's a sensible addition. If this is implemented "right", I don't even think we have to have a special caveat for saving and loading: you could still consider those "potential level transitions", so it would be covered by the proposal here.

Yes, I totally agree it should also apply to loading.

**Comment by AJenbo** [comment]
I belive save/load actually even hits the same level transition code as the other cases.

One thing that @CaptainCosmotic declined to mention is that he looked in to how the game originally handled music in the menu. For 1.00 only the multiplayer hero select screen would stop the music, how ever this changed when the menus where altered in one of the later patches. I think it would be fair game to restore the behavior back to what it was in 1.00 as this change may not have been intentional but just a side effect of changing how the menu changes are done.

**Comment by julealgon** [comment]
@AJenbo you might want to remove the `proposal` label on this one since it was implemented now.

**Comment by qndel** [comment]
do we really care? it was a proposal, it got merged, no need to poke the corpse that is a closed issue ...
