### ISSUE TITLE
Newgame breaks old character

### ISSUE THREAD

**Issue by ApertureSecurity** [diasurgical/devilutionX#8]
Source Code Deleted has informed me that when he started a game that it killed his character . 

I have tested this and can confirm that this is a bug.

**Comment by ApertureSecurity** [comment]
Ok I have disabled the new game feature until I can figure this out. 

as it would turn out, when the new game button is clicked , the game is thrown in to the run game loop and when it hits the start it will just runs a loop in a loop which causes problems. I think unless I do something to break out of the loops and get back to the charactor load loop , I will have to just disable it.

**Comment by ApertureSecurity** [comment]
I might have a fix later on today. Sorry source code deleted for killing your save.

**Comment by AJenbo** [comment]
This was fixed in 0.1.0
