### ISSUE TITLE
MPQ patching

### ISSUE THREAD

**Issue by sergi4ua** [diasurgical/devilutionX#80]
`init_test_access` in vanilla Diablo adds the MPQs and patches DIABDAT.MPQ if needed. 
In DevilutionX using the same function will not work due to missing code in Storm.
Adding this function would be useful for modding custom graphics/music.

**Comment by Thaodan** [comment]
Imho this should happen in a seperate mpq to prevent errors on read only data and clearly seperate user from app data,

**Comment by AJenbo** [comment]
To clarify currently we hardcode the list of loaded MPQ files in SFileOpenFile, this should instead happen dynamically so we do not have to edit it for Hellfire or other mods.
https://github.com/diasurgical/devilutionX/blob/adad63cc72b44ff80b10a0300604d208886e1ae6/SourceX/storm/storm.cpp#L155

**Comment by AJenbo** [comment]
This is fixed, a little bit manually, and could be made easier to add more MPQs but hey it works for now.
