### ISSUE TITLE
Incorrect spelling of "right-click" verbs on item descriptions and help screen

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#809]
Currently, some items in the game tell the player to "right click" to use, while other say "right-click". The help UI also contains an occurrence where the verb is incorrect spelled.

| Place | Evidence |
| --- | :-: |
| Potions | ![image](https://user-images.githubusercontent.com/461579/93000355-41bd0a80-f4fe-11ea-8b26-7e5f4475c5c3.png) |
| Scrolls (correct) | ![image](https://user-images.githubusercontent.com/461579/93000362-4bdf0900-f4fe-11ea-8e7a-1713df24377a.png) |
| Help Text | ![image](https://user-images.githubusercontent.com/461579/93001363-e2aec400-f504-11ea-9680-e845a8921551.png) |

As a verb, the correct usage should always be 
- "right-click"
- "left-click"

**Comment by julealgon** [comment]
Please add the `vanilla` tag.

**Comment by AJenbo** [comment]
feel free to fix this for 1.1.0
