### ISSUE TITLE
Windowed mode

### ISSUE THREAD

**Issue by aldomann** [diasurgical/devilutionX#81]
I'm sorry if this has been asked before or if it is indeed implemented, but I couldn't find any info about it.

As the title says, is there any way of running `devilutionX` in windowed mode on Linux?

**Comment by sergi4ua** [comment]
There is an INI file located somewhere on your system called diablo.ini (probably /home/?)
Open it up, change `fullscreen=1` to `fullscreen=0`

**Comment by AJenbo** [comment]
The ini option is not in any release yet, so it requires that you compiled the latest code, or wait for 0.4.0

The ini file is located with your save games in ~/.local/share/diasurgical/devilution
