### ISSUE TITLE
Incorrect referece to "left mouse buttons" as "left click" on game help

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#810]
The game help screen currently refers to the "left mouse button" as a "left click"

![image](https://user-images.githubusercontent.com/461579/93001308-78961f00-f504-11ea-88f1-5170cb7498b1.png)

This usage is incorrect in this context, since it is refering to keys/buttons, and not actions, in the labels.

As a button, "[left|right] mouse button" should be used instead.

Found this while working on #809

**Comment by julealgon** [comment]
Please add `vanilla` tag as well.

**Comment by AJenbo** [comment]
You don't need an issue for every PR you create, you can just describe the issue in the PR itself :)

**Comment by julealgon** [comment]
> You don't need an issue for every PR you create, you can just describe the issue in the PR itself :)

I just like having a problem/feature detailed as part of an issue that the change(s) can refer to and people can search for later ;)
