### ISSUE TITLE
Character screen base/now attributes and life/mana values are misaligned in the UI

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#814]
This is extremely minor but appears to be a defect. I only noticed it these past couple days when looking at the screen while debugging.

Take a look at the standard display first:
![original](https://user-images.githubusercontent.com/461579/93154086-22c6a000-f6d9-11ea-943c-6a68a176a1fc.png)

It is hard to see at the standard resolution, but still noticeable if you pay attention. The "base" values are slightly off-center to the left (1 pixel) compared to the "now" values.

Picking one row and putting it one on top of each other. Added red line for reference:
![alignmentHighlight](https://user-images.githubusercontent.com/461579/93154150-4c7fc700-f6d9-11ea-9b02-306030f0a984.png)

Zoomed + grid version:
![alignmentHighlightZoom](https://user-images.githubusercontent.com/461579/93154163-56a1c580-f6d9-11ea-8adf-f9e3cc5958e9.png)

When I first saw it I figured it could be due to some scaling adjustment, but after checking in 640x480, it is clearly not the case.

Have not looked into this yet. Just wanted to register the problem first so that I don't forget about it.

**Comment by julealgon** [comment]
Same issue is reproducible in vanilla. Would suggest adding the `vanilla` tag for future reference.

**Comment by ChaosMarc** [comment]
Wouldn't that be something for: https://github.com/diasurgical/devilution/issues/64 ?
btw: your label is spelled vanila instead of vanilla

**Comment by PrisonOfMirrors** [comment]
Another "bug" is wide character names (O's and W's) don't fit in the name box. There are other small issues but I won't name them all. The character screen is garbage and needs to be treated as such: *taken out* and replaced with something nicer.
- Only looks good at one resolution? **_Check_**. (goes for entire UI)
- Fonts draw directly into the image? **_Check_**. (who the !@#$ thought this was a good idea?)
- Boxes draw directly as well? **_Check_**.
- Redundant stat boxes? **_Check_**. (could display some stats when hovering over boxes like in Diablo 2)
- No information on blocking? **_Check_**. (Getting block locked all the time kiddos? :P)

**Comment by julealgon** [comment]
@PrisonOfMirrors 
> Another "bug" is wide character names (O's and W's) don't fit in the name box.

Interesting, will check that out later.

> There are other small issues but I won't name them all.

Please reconsider. I think it is important to catalog the issues at least. Send me a PM on discord if you don't want to post it all here.

> The character screen is garbage and needs to be treated as such: taken out and replaced with something nicer.

I really like the look of it :( 

> - Only looks good at one resolution? Check. (goes for entire UI)

Sure well.... the game was coded for a fixed resolution. There was hardly any reason to make it dynamic. It would be nice if it self-adjusted of course, but that's not that trivial to implement.

> - Fonts drawn directly into the image? Check. (who the !@#$ thought this was a good idea?)
> - Boxes drawn directly as well? Check.

Oh wow... really? I wanted to consider some changes to labels in there, but hadn't looked at the code yet. I thought they were printed at runtime. That's really bad.

> - Redundant stat boxes? Check. (could display some stats when hovering over boxes like in Diablo 2)

I don't think they are redundant at all. Having information on base stats is actually incredibly useful. This is lacking in D2 and I've wanted it more than once there. Implementing information on hover would be a very drastic change to the overall game UI and will most certainly not be accepted as a DevilutionX upgrade.

> - No information on blocking? Check. (Getting block locked all the time kiddos? :P)

Yeah, maybe there could be something about blocking. There are a lot of things that are not showing today though, like "hit recorevy", "attack speed", "block chance", character traits (warrior with his inherent increased block chance and chance to hit, sorcerer with increased chance to crit mana potions and chance to hit spells, etc).

To fit every information in the screen would be quite challenging I think. It would probably require an extended UI similar to what Diablo 3 provides with a "list" of modifiers (ugly, but practical). Again, probably unviable for DevilutionX though I feel.

**Comment by PrisonOfMirrors** [comment]
> Please reconsider. I think it is important to catalog the issues at least.

We'll see. I'm lazy these days. ;P

> I really like the look of it :(

The UI panels look fine at 640x480. My only pet peeve here is the control panel that takes up too much vertical space. As with most Diablo quirks, it gets sympathy for its time, given the limitations of 1990s computers.

> Oh wow... really? I wanted to consider some changes to labels in there

Yep, you'd have to reconstruct the original concrete background then dynamically add the elements. That way you can easily add more stats, stat pages, hold shift to see this or that etc.

**Comment by AJenbo** [comment]
fixed in #2741
