### ISSUE TITLE
Slain hero quest can freze the game

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#826]
**Describe**
If a low level hero operates the Slain Hero the game will get stuck trying to generate the drop item. Basically the function will keep spawning random items until on of the given type is randomly created, for low level heros the given item would never spawn and so the game locks up in an infinite loop.

**To Reproduce**
1. Find (or spawn) the Slain Hero with a level 1 
2. Click on the slain hero
3. Note that the game has now locked up

**Expected behavior**
The Slain Hero should always drop the expected item

**Comment by ThomasChr** [comment]
Tried with Warrior and Roque. Can't reproduce. Character level was 1.

**Comment by MegaMak84** [comment]
Managed to recreate this with a Lv. 20 Rogue, on Hellfire. Save attached.

[single_2.zip](https://github.com/diasurgical/devilutionX/files/7860668/single_2.zip)

**Comment by StephenCWills** [comment]
I'm fairly certain this is a regression (bb9a20f).
