### ISSUE TITLE
does not launch on openbsd

### ISSUE THREAD

**Issue by brightersun99** [diasurgical/devilutionX#827]
**Describe**
Upon launching, the application closes out with these errors
INFO: 
INFO: SFileOpenFile: Not found: ui_art\title.pcx
INFO: SFileOpenFile: Not found: ui_art\black.pcx
INFO: TTF_OpenFont: Couldn't open CharisSILB.ttf

**To Reproduce**

On openbsd 6.7 stable amd64, build/download devilution
attempt to launch it after installing diablos data files 

**Expected behavior**
game to launch

**Screenshots**

**Additional context**
Using openbsd 6.7

**Comment by brightersun99** [comment]
I just downloaded the font and dragged it to the devilution data folder but it still says font not found....

**Comment by brightersun99** [comment]
Previously I got it from my distro's repos but now I just compiled it from source. 
Same issue.  Minus the font 
I compiled this fresh from source via git, and I  copied DIABDAT.MPQ to both the build folder and folder i fetched the code in, for good measure. So now it's in 3 locations. 
devilutionX
devilutionX/build (where the binary is)
/home/staff_test/.local/share/diasurgical

So it's definitely seeing the dat

**Comment by AJenbo** [comment]
Make sure it's diabdat.mpq in lower case

**Comment by brightersun99** [comment]
Just renamed it.  same issue 
FILE=~/.local/share/diasurgical/devilution/diadbat.mpq

if [[ -f "$FILE" ]]; then
    echo "$FILE exists."
fi
/home/staff_test/.local/share/diasurgical/devilution/diadbat.mpq exists. 

still does not launch

**Comment by brightersun99** [comment]
I figured it out. 
I had to try several DEs and WMs for some reason... 
It didn't work on fvwm, sawfish, vtwm, twm or fvwm2 or my main DE which is CDE. 
But it does launch on cwm, which is a problem for me because I don't use cwm.

**Comment by AJenbo** [comment]
You might have to report this issue with CDE, this is probably an issue between SDL and them.

**Comment by brightersun99** [comment]
It seems to be an issue with many WMs.  
I have been trying more of them, the more modern ones work whereas older ones (still developed) seem to have issues. 
I tried it on these too ... 
UDE, rox, MaXX,mwm,ctwm, same problem. 

What should I tell them? I mean, the sdl2 variants of quake 2 and 3 worked ok. As well as some ancient unix freeware games that I built..

**Comment by brightersun99** [comment]
What can I do to work around this? can I launch this in windowed mode or maybe fb mode somehow?

**Comment by brightersun99** [comment]
Found a few work arounds. 
In fvwm2, switching to and from a tty and skipping the startup video will make the game appear. 
alternatively, windowed mode works.

**Comment by AJenbo** [comment]
Interesting you might want to debug some of the windows initialization code to see if that is the issue.

https://github.com/diasurgical/devilutionX/blob/8d896d54f78342cf9dab5d697b5a93182d65cf09/SourceX/display.cpp#L50

You can start in window mode by suplying `-x` and skip video via `-n`. You can also switch to full screen via alt+enter.

**Comment by brightersun99** [comment]
Alright. I don't think it's an openbsd issue but rather an issue of ancient WMs, even if fvwm is still worked on it's still a relic. 
Openbsd, about to test it with CDE and fvwm on linux.

Either way, this can be closed, thanks for the help.

**Comment by brightersun99** [comment]
Everyone else on openbsd has had no problems with this port at all.

**Comment by AJenbo** [comment]
Ok cool, closing the issue then. It's not that we do not want to solve compatibility with ancient VMs, just that no one has bothered vs switching to a newer one whenever this has been the issue :)
