### ISSUE TITLE
can't pick up books "produced" by other player in multiplayer

### ISSUE THREAD

**Issue by yogo1212** [diasurgical/devilutionX#829]
hiho :-)

when i use a bookshelf in a game i host, i can see it and pick ip up.
my friend can't see those books.
if, instead, he opens the bookshelf, i can't see those books.
but if he tries to picks them up, they vanish :-(

**Comment by AJenbo** [comment]
Thanks for the report, what version are you using?

**Comment by yogo1212** [comment]
i'm running `1.0.1.r212.gf9b7ac3b-1` on linux.
my friend is running `1.0.1` on macos.

**Comment by yogo1212** [comment]
would it help if we build the same version for macos and test that?

**Comment by AJenbo** [comment]
it would save me the time of doing it :)
also if you could test 1.0.1 on both that would help as well.

i played a game earlier this month, using 1.0.1-7f7ab8c, and didn't have the issue you mention here.

i don't recognize gf9b7ac3b, what is it based on?

**Comment by yogo1212** [comment]
f9b7ac3bfaa58c1325cabd8ba02c080ad7bacb8a
Expose chest with traps to set maps

the `g` is for garbage :-D
a bug in the PKGBUILD i'm using.

i'll try 1.0.1 on my machine first then

**Comment by AJenbo** [comment]
I was using https://github.com/diasurgical/devilutionX/commit/9e1428dd0b7738c0c305ffaa0b7e7882736c94f0 afaik

**Comment by AJenbo** [comment]
I have just tested this with two build of the latest master. Thinks worked out correctly. I'm going to guess that the cause of the issue is simply a slight differences in game logic causing desync between the two games. I will make sure to bump the network protocol version with the next release so others won't have this issue. Thanks you for reporting.

**Comment by yogo1212** [comment]
@AJenbo sorry to have kept you waiting and thanks for the work.

we finally got around to testing and, indeed, if both of us use the same version, it works as intended.
