### ISSUE TITLE
Dont Drop items upon Death Multiplayer

### ISSUE THREAD

**Issue by mazeya** [diasurgical/devilutionX#837]
**Describe**
When Playing multiplayer dont drop items upon death
**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mazeya** [comment]
I am new I dont know how to post I just wanted to say dont drop items on ground upon death multiplayer

**Comment by qndel** [comment]
being new doesn't mean you can't read :roll_eyes:

**Comment by AJenbo** [comment]
We do not plan to change game behavior like this.
