### ISSUE TITLE
Diablo text - start screen position error on non-default resolution

### ISSUE THREAD

**Issue by licaon-kter** [diasurgical/devilutionX#841]
amd64 HEAD(25e0e2079794227577769f8d0a851183de765719)

![1920glitch](https://user-images.githubusercontent.com/2282799/94613231-d318d480-0293-11eb-8350-a28941d58894.jpg)

**Comment by AJenbo** [comment]
Please provide some system information.
What OS?
What GPU?
What Window Manager?
Is this SDL1.2 or SDL2?
What are your ini settings?

**Comment by licaon-kter** [comment]
Debian Sid
nVidia latest close source
i3
Dunno, SDL2 I guess
Default, just changed resolution, the logo goes down as the resolution goes up.

**Comment by AJenbo** [comment]
Thanks for catching and reporting this :)
