### ISSUE TITLE
Divide by zero exception when configuring aspect ratio setting

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#845]
Setting the `original aspect ratio` setting to `1` results in the following exception at runtime:

![image](https://user-images.githubusercontent.com/461579/94626599-cb583080-0291-11eb-8874-ff30c99f5769.png)

For reference, here is my diablo.ini file when this crash occurred:

```ini
[devilutionx] 
upscale=1
fullscreen=1
grab input=1
scaling quality=0
vsync=0
integer scaling=1
game speed=20
width=640
height=480
original aspect ratio=1
[Diablo] 
Intro=0
Sound Volume=0
Music Volume=0
Gamma Correction=100
Color Cycling=1

```

This is with latest master version, commit 25e0e207.

**Comment by julealgon** [comment]
@AJenbo FYI. I assume this is related to widescreen changes.

**Comment by AJenbo** [comment]
desktop resolution?

**Comment by julealgon** [comment]
> desktop resolution?

1920x1080
