### ISSUE TITLE
Item/cursor flickering when picking up items in inventory

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#846]
I noticed significant flicker and erratic cursor movement when picking and dropping items in inventory.

![FlickerItemSelection](https://user-images.githubusercontent.com/461579/94627364-b8466000-0293-11eb-870f-63eada547a13.gif)

Notice how the dagger moves up and down on selection, and how the sword next to it keeps blinking. Also note the description panel which quickly shows the sword properties for a few frames.

This problem seems to be a very old issue that impacts even the pre-release demo of the game.

**Comment by AJenbo** [comment]
I cannot replicate this, I'm guessing this is related to vsync=0 and not having a window manager that does vsync itself?

P.s. I believe you mentioned in the chat that this also affects you in older versions meaning that this isn't a recent regression? Could you update the issue if that is the case?

**Comment by julealgon** [comment]
> I cannot replicate this, I'm guessing this is related to vsync=0 and not having a window manager that does vsync itself?

I don't think it is related to vsync, because I'm able to repro this in the extremely old pre-release demo version (the version where the belt didn't exist). I believe now that I may have just not noticed it before and started seeing it when working with inventory stuff equipping and unequipping items a lot.

> P.s. I believe you mentioned in the chat that this also affects you in older versions meaning that this isn't a recent regression? Could you update the issue if that is the case?

Yep. Updated the issue to remove any references to recent changes. It is definitely not a recent regression.

**Comment by FitzRoyX** [comment]
I've always noticed this. Immediately after clicking on an item, the item graphic replaces the cursor graphic for like one frame before getting repositioned. That's what makes it appear to flicker.

**Comment by agris-codes** [comment]
I have this on a *slightly* modified current source build on Windows with vsync enabled.

**Comment by ikonomov** [comment]
I have also noticed this regardless whether Vsync is enabled or disabled.  Interestingly enough it only seems to happen when the game is running on full screen with Upscaling enabled.  If exit out of full screen, or disable upscaling the flickering does not happen, and possibly why AJenbo was unable to reproduce this.

**Comment by ikonomov** [comment]
Additionally there is a brown outline around the cursor while the game is upscaled and only happens when hardware cursor is enabled.

**Comment by julealgon** [comment]
> I have also noticed this regardless whether Vsync is enabled or disabled. Interestingly enough it only seems to happen when the game is running on full screen with Upscaling enabled. If exit out of full screen, or disable upscaling the flickering does not happen, and possibly why AJenbo was unable to reproduce this.

@ikonomov notice that this issue happens in vanilla Diablo as well. It is unlikely that it is caused by any DevilutionX-specific mechanism at this point, but more of an oversight in the original code.

> Additionally there is a brown outline around the cursor while the game is upscaled and only happens when hardware cursor is enabled.

I'd recommend opening a different issue for this part, since it is unrelated to the flickering from a user perspective.

Adding comments with other issues will reduce the chance that it is fixed since it is much harder to keep track of it.

**Comment by malvarenga123** [comment]
@julealgon any idea of what's causing this? It's a lot more noticeable when organizing the stash.

**Comment by julealgon** [comment]
> @julealgon any idea of what's causing this? It's a lot more noticeable when organizing the stash.

Not really. I don't think we ever dived into this one deep enough to understand what was going on. I do remember it being a lot more noticeable in DevilutionX vs vanilla for some reason (I suspect the refresh rate plays a role here).

**Comment by qndel** [comment]
This was one of the oldest d1 bugs :D amazing

**Comment by julealgon** [comment]
Amazing to see this being finally fixed!
