### ISSUE TITLE
Inventory select not working properly with controller.

### ISSUE THREAD

**Issue by Vundult** [diasurgical/devilutionX#847]
Using latest build, commit 38574b9. Tried using controller. The cursor moves across the inventory on the left side of the screen when navigating as if it's there when the interface is not. Tested on 1.0.1 release and it works perfectly fine though.

![1](https://user-images.githubusercontent.com/64669505/94731586-8fd26a80-0354-11eb-82a0-1622c11e19a7.png)

My cursor should be on the chest piece in this image.

**Comment by AJenbo** [comment]
Inventory navigation is now fixed, but there are still several UI issues with the controller that needs to be fixed so I'm keeping this issue open for now. Thanks for reporting.

https://github.com/diasurgical/devilutionX/commit/c28335d59722c25e14e0951b8890853122a18f8d

**Comment by Vundult** [comment]
Using latest build, commit c28335d. When navigating spells with controller, it skips over some of the spells and doesn't select them properly.

![Screenshot_2020-10-01_18-34-20](https://user-images.githubusercontent.com/64669505/94843857-d4214180-040c-11eb-9944-f23e15418dce.png)

Doesn't let me select heal, inferno, or fire wall.

**Comment by AJenbo** [comment]
Most of the controller issues are now solved https://github.com/diasurgical/devilutionX/commit/c1640483482fd2f40a92376d37713f733c6a36c7

The only thing left is drawing the help text
