### ISSUE TITLE
Attempting to buy item that cannot be used while inventory is full results in lost item

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#848]
While working on belt-related logic, I noticed that Adria/Pepin store checks do not currently check for items that cannot be used due to unmet requirements when purchasing items from them.

Surely enough, I was able to find a bug here.

## Repro steps
1. Fill inventory with loot. Ensure there are no free spaces (all 40 positions populated with some item)
2. Ensure there is at least one empty slot in the belt
3. Go to Adria and purchase a scroll whose requirements you do not meet (easy to do with Warrior)
4. Notice the gold is spent, but the item is not added to your inventory or belt

![ItemMissingAfterBuying](https://user-images.githubusercontent.com/461579/94738153-63fbb880-0345-11eb-90a0-0916ace7277e.gif)

Sample savefile ready to display this bug:
[single_0.zip](https://github.com/diasurgical/devilutionX/files/5308206/single_0.zip)

This happens because the game checks whether or not you can carry the item before presenting you with the confirmation dialog. During this check, done inside `SpecialAutoPlace`, the item is checked against the belt even if the requirements are not met by your character. However, items you cannot use due to missing requirements _cannot_ be put into the belt.

https://github.com/diasurgical/devilutionX/blob/09bd5f0bd88b07464fa55f76be5f74e284798cb0/Source/inv.cpp#L536-L547

The section above is executed right after testing all inventory positions. If the whole inventory is full, then the game checks to see if there is any empty belt slot where the item could be put. However, it only checks item sizes before doing this, and does not check whether the item's requirements are met. 

This means the confirmation dialog is shown, but the game fails when attempting to actually add the item to the belt later as it uses a more robust function to do that that tests whether the requirements for the item are met before allowing the belt to hold it.

## Expected Behavior
There should be a message saying you don't have space to put the item (same as if the belt was already full) for red items.

**Comment by julealgon** [comment]
Found this issue while working on #844

**Comment by julealgon** [comment]
I have a fix for this in the works.

**Comment by MaxDesiatov** [comment]
> ## Expected Behavior
>
> There should be a message saying you don't have space to put the item (same as if the belt was already full) for red items.

Would it work better if it just dropped the item on the ground without displaying the message?

**Comment by julealgon** [comment]
> Would it work better if it just dropped the item on the ground without displaying the message?

@MaxDesiatov 

I think that would be inconsistent with how other items are handled in vendors. When you cannot hold the item, a message is already shown today saying you cannot buy it.
