### ISSUE TITLE
Inconsistent highlight vs selection behavior in belt

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#853]
Currently, the game allows you to pick an item from the belt in a situation where the cursor is not actually highlighting the item.

![image](https://user-images.githubusercontent.com/461579/94962957-bcf65880-04cd-11eb-8f91-14ef2630774a.png)

At this exact position, if I click, the scroll is selected. I believe this is incorrect and that the item should only be selectable when it is highlightable, that is, 1 pixel below:

![image](https://user-images.githubusercontent.com/461579/94963187-224a4980-04ce-11eb-83e7-9d3d0f2eb371.png)

**Comment by ThomasChr** [comment]
Can anyone reproduce the problem? I had no luck and I could only cast a scroll wenn it's highlighted.
Most recent commit.
cf4e8bf27b4da7f9461f163728d6a54cf273c656

**Comment by julealgon** [comment]
There is a chance this got fixed by accident with some `Rectangle`/`Point` usage somewhere. It was definitely an issue before.

**Comment by ThomasChr** [comment]
I love issues solving themselves :)
