### ISSUE TITLE
Inconsistent behavior with hotkeys and belt items that cannot be used due to unmet requirements

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#856]
When an item in the belt becomes red, i.e. it cannot be used due to requirements, the game refrains from drawing the number hotkey in the belt:

![image](https://user-images.githubusercontent.com/461579/94970057-36944380-04da-11eb-8000-c7f6bc9c3916.png)

However, when pressing the hotkey (`3` in this case) the game will still try to execute it.

Even though red items cannot be moved to the belt by default, this situation can happen when the scroll is added to the belt in a usable state, and then equipment is removed making the player have less stats than needed to use it (thanks @qndel ) 

## Expected Behavior

One of:
1. The game should not move forward with the hotkey and do nothing when the player presses `3`
2. The game should still render the number hotkey even for items that cannot be currently used

**Comment by AJenbo** [comment]
It should probably be the same as if you right click a red scroll

**Comment by julealgon** [comment]
> It should probably be the same as if you right click a red scroll

Clicking a red scroll plays "I can't use that yet", which is what happens if you press the hotkey.

I take it your vote is for number 2 then.
