### ISSUE TITLE
Allow quick equipment management with shift+click

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#857]
This proposal is to add new functionality to the inventory, allowing quicker management of equipment by leveraging shift+clicking.

This does not conflict with "move to/from belt" (#844) as items that can go in the belt are never equipable and vice-versa.

## Scenario 1 - Shift+click on equiped item

Shift clicking on an equiped item should unequip that item and move it to inventory.
If inventory is full, "no room/overburdened" sound should be played and nothing should happen.

---

## Scenario 2 - Shift+click on equipment in inventory, corresponding equip slot empty

Shift clicking on an equipment item in the inventory should try to equip that item piece
1. If the item cannot be equiped due to requirements, "i cant use this, yet" plays and nothing happens
2. If the item can be equiped, equip the item, moving it from the inventory to the body

---

## Scenario 3 - Shift+click on equipment in inventory, corresponding equip slot has an item already

The equipment from inventory is equiped, and the equiped item is moved to inventory.
1. If the item can be equiped, but only due to attributes granted by the currently equiped item(s), follow existing logic: equip the item, but it immediately becomes red (questionable if this is intended behavior, but that's how it is today)
2. If there is not enough room in inventory after removing inv item and putting the existing equipment in the inventory, play "overburdened" sound and do nothing.

---

## Scenario 4 - Help screen

Help screen should have information about the new functionality. Differentiate from moving to/from belt

---

## Scenario 5 - Tooltip

Tooltip related to shift+clicking could be added to elligible items.
1. Mouse over equipped item: "Shift+click to unequip"
2. Mouse over equipment in inventory: "Shift+click to equip"
3 (possible) Mouse over equipment in inventory + equipment already exists: "Shift+click to swap equipment"

Challenge with tooltip is number of lines limit in info panel: magic item with 2 affixes and requirements occupies all 5 lines

**Comment by AJenbo** [comment]
I would prefer that this be split up in a PR for the functionality and one for tooltips.

The hardest part is probably checking that there is room when swapping 1 two handed item for two items.

**Comment by julealgon** [comment]
> I would prefer that this be split up in a PR for the functionality and one for tooltips.

That's probably what I'll do indeed. The tooltips for these equipments is a tough problem to solve due to spacing.

> The hardest part is probably checking that there is room when swapping 1 two handed item for two items.

I have already extracted a function for moving an item to inventory with the other belt->inventory feature, so this should not be a problem

**Comment by AJenbo** [comment]
Closing despite "Scenario 5 - Tooltip" still not being implemented. I think this part fits well with #3380 and so can be tackled when that is being implemented.
