### ISSUE TITLE
Allow automatically equipping all item types on pickup 

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#860]
In vanilla, weapons are automatically equipped when picked up if the player does not have a weapon equipped already. However, this behavior only exists for weapons: other item types (helms, armor, shield, rings and amulet) are just placed in the inventory.

I propose that we change this behavior for consistency with weapons and for QOL improvement: make it so that all item types can be equipped when picked up.

## Scenario 1: picking up item with empty slot in body

When picking up any equipment type, if the player does not currently have anything equipped in the corresponding slot, the picked up item should be checked for fitness and equipped. An item is fit for equipping if:
- Player has sufficient stats to use it
- Player has an empty slot with the location type matching the item's target location
- Shield should only be equipped if at least one of the hands is free, and the other is not a two-handed weapon or another shield
- Two-handed weapons should only be equipped if both hands are free
- One-handed weapons should only be equipped if at least one of the hands is free, and the other is not a weapon
- Ring should be equipped if any of the 2 ring slots are free

---

## Scenario 2: picking up item with already equipped item in slot

When the player already has equipment in the target slot for the picked up item, the item should be moved to inventory as normal.

---

## Scenario 3: play equipment sounds on equipping

When any equipment change happens, the corresponding sound should be played to alert the player. Each item type has a specific "placement" sound.

**Comment by AJenbo** [comment]
I belive this has now been solved?

**Comment by julealgon** [comment]
> I belive this has now been solved?

Absolutely. Thanks for closing, I forgot to do so once the sound change was merged.
