### ISSUE TITLE
[Switch] Use the system virtual keyboard for text input

### ISSUE THREAD

**Issue by spitfire** [diasurgical/devilutionX#865]
As I learned in https://github.com/diasurgical/devilutionX/issues/863 version 1.0.1 lets you create a character but..not name it.
The virtual keyboard does not pop up to let you type in your character name, and if you have a physical USB keyboard connected to the dock it only lets you use backspace to delete characters, but you can't type anything.\
Bonus points: support the USB keyboard as well ;)

**Comment by AJenbo** [comment]
It looks like this is related to how you start the application on Switch:
https://github.com/diasurgical/devilutionX/issues/863#issuecomment-705278774

**Comment by spitfire** [comment]
As I mentioned in #863 I am not running hbmenu in applet mode, so this is not causing this issue.
