### ISSUE TITLE
Character bug

### ISSUE THREAD

**Issue by Gadaften** [diasurgical/devilutionX#869]
Cannot write any name in new character creation menu. I am using english(US) keybord.

**Comment by Srandista** [comment]
Same here. Confirmed, that this was introduced with 1.0.2, since in 1.0.1 I can create character name without issue. Characters created in 1.0.1 can be loaded in 1.0.2, but I'm unable to create a new ones.

**Comment by qndel** [comment]
thx for reporting

**Comment by PrisonOfMirrors** [comment]
Try naming your character `Voldemort` instead. It will appear invisible ;P
