### ISSUE TITLE
Integer scaling

### ISSUE THREAD

**Issue by Srandista** [diasurgical/devilutionX#870]
How can I enable it? Do I need to compile code on my own? I can't find any info about it in Readme either here on GitHub or in new release package.

**Comment by Srandista** [comment]
Ok, so I found it in config file, but there could be some mention in Readme.

But thanks a lot for integration of this function anyway!

**Comment by AJenbo** [comment]
@julealgon is the one that implemented it :)

**Comment by julealgon** [comment]
#784
