### ISSUE TITLE
[Switch] Please fix/enable network support on Switch

### ISSUE THREAD

**Issue by spitfire** [diasurgical/devilutionX#880]
When trying to start Multiplayer on Switch it only shows "loopback" as available "protocol".
Apparently this is disabled in https://github.com/diasurgical/devilutionX/blob/master/CMake/switch/switch_defs.cmake because it (of course) doesn't compile with NONET disabled:
```
devilutionX/3rdParty/asio/include/asio/detail/socket_types.hpp:78:11: fatal error: sys/uio.h: No such file or directory
   78 | # include <sys/uio.h>
```

**Comment by qndel** [comment]
feel free to make it compile ;)

**Comment by spitfire** [comment]
> feel free to make it compile ;)

If I knew how, I wouldn't ask, I'd fix it and make a pull request ;)

**Comment by AJenbo** [comment]
It's a dependency problem as far as i rmember, but can't remember if it's ASIO or Sodium. Could you post the compile error, that would be a good starting point. It would probably be easy for some one who know about developing for the nintendo switch, unless it needs porting then it needs some one who is really good at developing for the switch :)

**Comment by spitfire** [comment]
> Could you post the compile error, that would be a good starting point. 
@AJenbo I did in the first post. There was not much more, and I believe it was not relevant (some other warnings). Simply a file not found.

**Comment by glebm** [comment]
These are the blocking issues on the switch newlib side:
* https://github.com/devkitPro/newlib/issues/18
* https://github.com/devkitPro/newlib/issues/17

**Comment by AJenbo** [comment]
An alternative is porting things to SDL_net if that's available on the switch?

**Comment by spitfire** [comment]
I just tried a 3DS build from https://app.circleci.com/pipelines/github/diasurgical/devilutionX/3160/workflows/a55919d4-5d57-4cd9-8268-a0ed5ed1bdd7 and it also seems to suffer from the same problem.

**Comment by AJenbo** [comment]
It's not so much a problem as the feature just not having been implemented yet :(

**Comment by StephenCWills** [comment]
It's still on my todo list to see if I can get ZeroTier working on 3DS and Switch, but it seems appropriate to close this issue at this point.

**Comment by AJenbo** [comment]
> It's still on my todo list to see if I can get ZeroTier working on 3DS and Switch

That would be insane

> it seems appropriate to close this issue at this point.

Defiantly

**Comment by spitfire** [comment]
Wait, there's a working build now?

**Comment by AJenbo** [comment]
Yes the latest test build has network support on switch
