### ISSUE TITLE
How to find install folder?

### ISSUE THREAD

**Issue by michaldybczak** [diasurgical/devilutionX#883]
I installed git version from AUR. You said that in Linux  it's:

~/.local/share/diasurgical/devilution/

However, I don't have this folder. Devilution works but it returns error since the mpq file is missing, because I didn't copy it there yet.

I checked /usr/local/share/ but it isn't there. I'm not sure where to look for it. I see devilution in /bin/ but that's probably not the proper place either.

EDIT:

~/.local/share/diasurgical/devilution/ showed up, so probably after the first launch.

Just add this info to the readme, so others wouldn't be so confused. So I guess, we have to either launch the devilution which shows error at this stage, or create folder ourselves and then copy mpq file there.

**Comment by AJenbo** [comment]
You need to talk to who ever is maintaning the AUR packaging, it's not us.

**Comment by michaldybczak** [comment]
You missed the point. It's enough to add in readme section that if this directory doesn't exist, create it. This will clear out confusion that one may have, because this issue can show up in AUR or multiple other places that you can't control. However, you can control the documentation and prepare it for various situations. That's it :)

**Comment by MaxDesiatov** [comment]
The `~/.local/share/diasurgical/devilution/` path is mentioned in [the "How To Play" section](https://github.com/diasurgical/devilutionX#how-to-play) in `README.md` at the top. What else do you find missing in this aspect of the documentation?

**Comment by michaldybczak** [comment]
That if the directory is missing, one should create it. That's it ;). It's not always obvious.
