### ISSUE TITLE
Include diablo.ini defaults

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#885]
With the evergrowing amount of settings people can set in the diablo.ini file. 
I think it would be a great idea to provide an ini file with all of the settings visible and set to their default values or commented out for the ones which are automatic.

**Comment by AJenbo** [comment]
On the first usage, devilutionx generate a diablo.ini with the defaults.

**Comment by predator8bit** [comment]
Interesring, for me it only had shortcut keys for chat messages in mine. Maybe something else modified it and devilutionx didn't want to overwrite it.
Oh well, my problem is solved then.

**Comment by AJenbo** [comment]
Better documentation wouldn't hurt though :)

**Comment by AJenbo** [comment]
There now exist documentation for this:
https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide

Also, I just realized that you were probably looking at the wrong ini file.
