### ISSUE TITLE
ChangeLog.md is not updated

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#886]
**Describe**
The file tracking changes (ChangeLog.md) is not updated, and still has 1.0.1 as the latest version, even under the 1.1.0 tag.

**To Reproduce**
Open the change log file and view it's contents.

**Expected behavior**
The change log file should have the changes for all versions pertinent to that tag/branch.

**Comment by AJenbo** [comment]
A PR for this would be appreciated :)
