### ISSUE TITLE
[Question] Where can I see the available diablo.ini options?

### ISSUE THREAD

**Issue by vanfanel** [diasurgical/devilutionX#887]
Hi!

I have just updated my devilutionX sources and rebuilt on the Pi today, and to my surprise the game is now running widescreen! Great!
But what settings are available in diablo.ini? Is there a list somewhere? README doesn't specify those, and I have just found some settings scattered through the code...

Thanks!

**Comment by AJenbo** [comment]
The ini file will be generated with all its default options so the simplest thing to do is look there.

We consider ini settings advanced usage and as such do not provide much description or documentation, but you are welcome to submit some if you write it as you try things out.

**Comment by vanfanel** [comment]
@AJenbo Thanks! Yes, I found it creates an .ini in ~/.local/share/diasurgical/devilution/diablo.ini

Everything seems evident, but what about game speed? Seems to be ticks/second, which translates in FPS/second in-game. There is no movement interpolation so the game runs at monitor refresh (~60Hz) but gameplay keeps normal speed, right?
I mean, "game speed=0" is "as fast as possible, gameplay-wise too", right?

**Comment by AJenbo** [comment]
game speed in the ini is in ticks per seconds, there is an in game option to adjust it that allows for values between 20-50, but youu can overwrite it in the ini with even higher/lower values. but it will be capped by your refresh monitor rate.

"game speed=0" would be paused, and probably defaults back to 20. speeds above 1000 will all just run as fast as your system is capable.

**Comment by vanfanel** [comment]
Great! Now I understand every option in the default .ini :)
May I redact a guide for these and to a PR to update the README.md?

**Comment by AJenbo** [comment]
The readme is getting cramped, i would rather you create a new file, maybe call it manual.md, then we can move the controller section there as well, maybe include it withe builds

**Comment by johndoe71rus** [comment]
Can you explain this options 
Upscale=1
Fit to Screen=0
Scaling Quality=2
Integer Scaling=1
and possible values

**Comment by AJenbo** [comment]
I'm not sure what it is you want to know about them, they pretty much do what they say and are mostly on/off (1/0) options.

https://en.wikipedia.org/wiki/Image_scaling
Scaling Quality=0/1/2
https://emulation.fandom.com/wiki/Scaling#Integer_scaling

**Comment by AJenbo** [comment]
Closing this as it is better suited for chat/discussion/wiki

**Comment by AJenbo** [comment]
A wiki page has now been written for the ini options: https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide

**Comment by johndoe71rus** [comment]
I had a question if there is a possibility of scaling interface elements.
For example, like in Quake.
at 1080 the font and the flasks are too small.
according to diablo.ini wiki - no. thanks.

**Comment by qndel** [comment]
no

**Comment by julealgon** [comment]
> I had a question if there is a possibility of scaling interface elements.
For example, like in Quake.
at 1080 the font and the flasks are too small.
according to diablo.ini wiki - no. thanks.

The game is not optimized for ultra high resolution (1080p is "ultra high" for vanilla standards). I suggest you play in a lower resolution for now.

UI scaling will take a while to be implemented properly.

Also, that question has nothing to do with this issue. Please try to post questions where they make more sense (join the discord, or open a different issue if one doesn't exist).
