### ISSUE TITLE
No access to new classes and Hellfire content

### ISSUE THREAD

**Issue by michaldybczak** [diasurgical/devilutionX#892]
I expected to have Diablo I+Hellfire after installing devilutionx and providing the mpq file. To my surprise, I saw only 3 heroes. So I thought, maybe the new content unlocks after finishing one of the main classes? Nope, still nothing.

DevilutionX itself works great. Documentation is written clearly but is lacking in certain aspects, like with the Hellfire addon. I have version from GOG and have no idea how to enable it in devilutionx.

**Comment by michaldybczak** [comment]
Ah, silly me. Just spotted the info:

"Hellfire is being worked on and is mostly done, though not fully playable at the moment."

All clear.

**Comment by qndel** [comment]
hellfire saw some massive progress recently, it should get finished soon :)

**Comment by AJenbo** [comment]
You can test hellfire by providing -DHELLFIRE=ON as a cmake option if you build devilutionx yourself. Not that hellfire savegames asn't fully supported atm.

**Comment by michaldybczak** [comment]
Thanks for the info :).
