### ISSUE TITLE
Lazarus Staff Skip

### ISSUE THREAD

**Issue by NiteKat** [diasurgical/devilutionX#894]
**Describe**
On some game seeds, you can skip finding Lazarus' staff and taking it to Cain. The game puts the trigger tile for going to Lazarus' set level a certain distance away from where it is supposed to appear when the player has activated it. If that position has an x and y value high enough, it's possible the "idle" position for this trigger will land in a section of the map where the player can path to. If this happens, and the player stands still on the tile, they will be taken to Lazarus' set level without having to take find and take the staff to Cain. This is single player only. I only scanned 1,470 seeds, and 13.26% of those scanned have this bug, so I think it happens more often than one would think it does.

**To Reproduce**
1. Start the game with a seed where this bug exists.
2. Work your way to Level 15.
3. Find the tile where the portal is supposed to spawn.
4. Subtract 16 from the x and y, then divide by 2 to find where the trigger is sitting prior to activating it.
5. Walk the character onto that calculated position, and stand still. You will be brought to Lazarus' set level.

**Expected behavior**
A player should not be able to access Lazarus' set level until the staff is found and brought to Cain on all seeds.

**Additional context**
This code here is where the trigger tile is moved when it is supposed to be active: https://github.com/diasurgical/devilutionX/blob/master/Source/quests.cpp#L202 . I think the idle tile gets set somewhere in the L4 dungeon generation code. This could probably be changed so that the tile is always set to (0, 0) when not active, and then the game can scan for the tile type it's supposed to spawn on/near to move it there (I forget if it's the tile it spawns on that is a unique tile ID, or the tile below it). There are probably other ways to solve this problem, but that's the first that jumps to mind for me.

**Comment by NiteKat** [comment]
Forgot to mention, this is a vanilla bug, so it should probably have the vanilla tag (I don't think i can add those)

**Comment by AJenbo** [comment]
This is a hilarious bug, a nice find :D It's particularly funny since in most cases the game will check the quest status to prevent things like that, and doing so would have prevented this issue without needing a temp position in the first place :)
Good find.

**Comment by NiteKat** [comment]
Thanks! I think I found this back in June or July, and just totally forgot to open an issue for it until someone in my Twitch chat asked if it was fixed in DevilutionX. And yeah, I think the code that actually takes you to the set level is somewhere in trigs.cpp. I forget the exact line, but wherever it checks your position vs. the trigs and all the quest trigger x and ys. You could probably add a check for quest status in there to solve it easier than messing with positions. I think most other quests don't stop you from using the triggers without having activated them. Quests like chamber of bone barr your character from physically reaching the trigger, unless you can phase or teleport to it without reading the book, and if you do, I'm pretty sure you can enter it. So quest triggers just have no checks at all IIRC.
