### ISSUE TITLE
Build from source failed on Fedora 32 with error "/usr/bin/ld: cannot find -lstdc++"

### ISSUE THREAD

**Issue by sjmalice** [diasurgical/devilutionX#896]
I resolved the error by installing the "libstdc++-static" package. Could we add this to the dependencies for Fedora?

**Comment by AJenbo** [comment]
This appears to be a general issue with Fedora it shoudn't require statics, please see https://github.com/diasurgical/devilutionX/pull/756 and https://github.com/diasurgical/devilutionX/pull/891.

**Comment by zboszor** [comment]
This also happens on Fedora 33 with no libstdc++-static package.

**Comment by AJenbo** [comment]
Can you test this PR?
https://github.com/diasurgical/devilutionX/pull/1703

**Comment by sjmalice** [comment]
libstdc++-staticlibstdc++-staticFinally getting around to trying this again. I've pulled the latest changes and removed libstdc++-static. But now when I try to build from source, it fails with error "No rule to make target '/usr/lib64/libSDL2main.a', needed by 'devilutionx'.  Stop."

**Comment by AJenbo** [comment]
Looks like it is still attempting to statically link SDL2. Maybe just to see what happens could you try building for Sdl1.2?

**Comment by sjmalice** [comment]
OK. So since I'm not entirely sure what I'm doing, please bare with me, here are all the steps I tried this morning.

1. I edited line 28 of "CMakeLists.txt" to set option "USE_SDL1" to "ON". 
2. Then I installed packages with the command "sudo dnf install SDL-devel SDL_ttf-devel SDL_mixer-devel".
3. Cleared the build folder and ran the commands to build from source again.

Unfortunately, now the build fails with the same error as before. "/usr/bin/ld: cannot find -lstdc++" :(

**Comment by AJenbo** [comment]
Sorry, but I think we need someone who knows how things are supposed to work on Fedora.
It's a bit odd since this works on most other Linux distributions, Mac and windows.

**Comment by yuripourre** [comment]
@sjmalice since Fedora 29 for some reason libc cannot be compiled using the same packages as before. Currently a workaround is to install `libstdc++-static`.

```
sudo dnf install -y libstdc++-static
```

**Comment by yuripourre** [comment]
@AJenbo I think that's a bug on Fedora packages. It used to work a few years ago.

**Comment by AJenbo** [comment]
Someone should probably report it to fedora maintenance
