### ISSUE TITLE
Make error : undefined reference to symbol 'SDL_RenderIsClipEnabled'

### ISSUE THREAD

**Issue by slriverin** [diasurgical/devilutionX#9]
When running make with Debian/Sid, I get the following error : 

```
[ 50%] Linking CXX executable devilution
/usr/bin/ld: CMakeFiles/devilution.dir/Stub/SDL_FontCache.cpp.o: undefined reference to symbol 'SDL_RenderIsClipEnabled'
/usr/bin/ld: //usr/lib/i386-linux-gnu/libSDL2-2.0.so.0: error adding symbols: DSO manquant dans la ligne de commande
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/devilution.dir/build.make:1434: devilution] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/devilution.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by ApertureSecurity** [comment]
Did you install all the libs in the install instructions?

**Comment by slriverin** [comment]
Yes and I edited sdl2-config.cmake according to instructions.

**Comment by ApertureSecurity** [comment]
You shouldnt need to edit that.

What did you edit exactly?

**Comment by slriverin** [comment]
I changed the last line of /usr/lib/i386-linux-gnu/cmake/SDL2/sdl2-config.cmake for : 

``
set(SDL2_LIBRARIES "-L${SDL2_LIBDIR} -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf ")
``

This was in the instructions under 'Building XDiablo (For Linux)'

**Comment by ApertureSecurity** [comment]
@slriverin  
I changed the requirements for the game over time. I forgot to pull certian parts out. It should no longer be needed SDL_image and SDL_ttf .  I will pull out the font right now.

**Comment by ApertureSecurity** [comment]
ok @slriverin  try now.  

I have changed 
set(SDL2_LIBRARIES "-L${SDL2_LIBDIR} -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf ")


to 

set(SDL2_LIBRARIES "-L${SDL2_LIBDIR} -lSDL2 -lSDL2_mixer ")

**Comment by slriverin** [comment]
@ApertureSecurity thanks it removed the error.

However a new one pops up : 

```
[ 50%] Linking CXX executable devilution
/usr/bin/ld: CMakeFiles/devilution.dir/Stub/sdlrender.cpp.o: undefined reference to symbol 'SDL_FreeSurface'
```

**Comment by ApertureSecurity** [comment]
Somwthing is missing. Are these 32 bit libs ? Are you mixing 64 bit libs or something ?

**Comment by slriverin** [comment]
See full error message below : 

From my understanding it is a 32 bit library : `i386-linux-gnu/libSDL2-2.0.so.0`

I imported the libraries with the :i386 suffix in apt.

Are there any other libs beside those mentioned in the readme file that should be installed in 32 bits?

```
[  2%] Linking CXX executable devilution
/usr/bin/ld: CMakeFiles/devilution.dir/Stub/sdlrender.cpp.o: undefined reference to symbol 'SDL_FreeSurface'
/usr/bin/ld: //usr/lib/i386-linux-gnu/libSDL2-2.0.so.0: error adding symbols: DSO manquant dans la ligne de commande
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/devilution.dir/build.make:1419: devilution] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/devilution.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by ApertureSecurity** [comment]
I am not sure what the problem is. I wonder if you're using an old version of debian or something. 

If you don't want to compile anymore and just play there is this 

https://github.com/diasurgical/devilutionX/blob/master/build/devilution

**Comment by ApertureSecurity** [comment]
Hey Do you have the normal SDL libs installed? I think they came with my system but you  can try

apt-get install libsdl2-2.0-0

**Comment by slriverin** [comment]
@ApertureSecurity my normal SDL libs were installed.

The game works with the already compiled bin file. Awesome work! Cheers!

**Comment by ApertureSecurity** [comment]
I updated the installation instructions.
