### ISSUE TITLE
Multiplayer host crashes after defeating Diablo

### ISSUE THREAD

**Issue by Baracudus** [diasurgical/devilutionX#900]
To reproduce (in my case)

- Open a multiplayer game, TCP server, Passwort 123, Normal, Normal speed
- Open Settings and set the "Music" slider to zero (to listen to music :) )
- Goto hell, fight,... kill diablo!
- Now the game ends to the Desktop after the Videos (as indented)
- Reopen the game. (Same as above..)
- The audio settings were not saved. (Music playing again!)

**Comment by AJenbo** [comment]
> Now the game ends to the Desktop after the Videos (as indented)

This is not intended. The game should return you to the main menu. This appears to be an issue for the host only and not people that join the game.

**Comment by Baracudus** [comment]
> > Now the game ends to the Desktop after the Videos (as indented)
> 
> This is not intended. The game should return you to the main menu. This appears to be an issue for the host only and not people that join the game.

Ok, I didn't knew that! (I would prefer to stay ingame when he is defeated as a host to collect the loot when playing only with myself (TCP for mule-chars on localhost, which is working great with a second instance)).

**Comment by franckbonin** [comment]
> > Now the game ends to the Desktop after the Videos (as indented)
> 
> This is not intended. The game should return you to the main menu. This appears to be an issue for the host only and not people that join the game.

I experience this during a 3 players multiplayer game (v1.1.0 Mac OS). Only the host crashed, other players return to main menu.
