### ISSUE TITLE
Feature request: CD Soundtrack

### ISSUE THREAD

**Issue by MrDowntempo** [diasurgical/devilutionX#901]
The web version of DevliutionX lets you compress the soundtrack for a smaller MPQ. Would it be possible to instead provide a way to replace the soundtrack with the higher quality files found on the 15th anniversary CD release? That way it's be possible to play Diablo with the CD quality sound?

**Comment by AJenbo** [comment]
DevilutionX will play any wave file that you put relative to your diabdat.mpq with the appropriate names:
music/dtowne.wav
music/dlvla.wav
music/dlvlb.wav
music/dlvlc.wav
music/dlvld.wav
music/dintro.wav

If you are looking to do this for webdiablo then you need to edit your mpq file.

**Comment by MrDowntempo** [comment]
Thank you! I didn't know this was supported. Are only .wav files supported? Would be great if FLAC or even mp3 support worked too.

**Comment by AJenbo** [comment]
It should be able to use any of the formats that SDL2-mixer supports but you will have to name it.wav 
    MUS_CMD,
    MUS_WAV,
    MUS_MOD,
    MUS_MID,
    MUS_OGG,
    MUS_MP3,
    MUS_MP3_MAD,
    MUS_FLAC,
    MUS_MODPLUG
