### ISSUE TITLE
NIGHTLY_BUILD on a release?

### ISSUE THREAD

**Issue by nunotexbsd** [diasurgical/devilutionX#908]
Hello,

I have an doubt about NIGHTLY_BUILD used in a release, like for example in FreeBSD [devilutionX](https://www.freshports.org/games/devilutionX/) port for latest version 1.1.0, that have this options:
`.if defined(WITH_DEBUG)
CMAKE_ON=  NIGHTLY_BUILD
.else
CMAKE_ON=  BINARY_RELEASE
.endif`

I don't know if I'm confused, but I think that FBSD port should use DEBUG for "WITH_DEBUG" option instead of NIGHTLY_BUILD.

I can't understand what NIGHTLY_BUILD could do on a release compared with BINARY_RELEASE...

Can anyone clarify me before I submit a patch to port maintaner?

Thanks,

Nuno Teixeira

**Comment by AJenbo** [comment]
NIGHTLY_BUILD enables some debugging and most optimizations, it should not be enabled for releases. We use it on CI so that the artifact gives us close to release performance but still provides some extra debug information in case of issues.

**Comment by nunotexbsd** [comment]
Thanks very much for your quick answer!

I will discuss it with port maintaner and see if DEBUG is more suitable.
