### ISSUE TITLE
Running in the opposite direction

### ISSUE THREAD

**Issue by Chance4us** [diasurgical/devilutionX#91]
While clicking on the left border in the fullscreen mode the hero begins to run in the opposite direction. Probably we need to clip the mouse (X,Y) coordinates.

**Comment by AJenbo** [comment]
Yeah i haven't found a good way to do so yet, moving the mouse when ever the user goes in to the boarder seams like a fragile solution.

**Comment by Chance4us** [comment]
Do we know where the code is being located for trying some of experiments to resolve it?

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/blob/3f9691bf2c47befe497d59c5d2ac4fdf62e9a03c/SourceX/miniwin/misc_msg.cpp#L152

**Comment by Chance4us** [comment]
Thank you.

**Comment by AJenbo** [comment]
The reason that it happens is that the value to the left is negative and the way things are mapped the signed bit is clipped, so -48px becomes 65487px (65535-48), this is way past the middle of the screen (640/2) so the game thinks you are requesting a move to the right.

`		lpMsg->lParam = (std::max(1, e.motion.y)) << 16) | (std::max(1, e.button.x) & 0xFFFF);`

One solution is to cap the values before mapping, but this means that the mouse will appear sticky when moving past the border, may be combined with moving the mouse this will appear correct but not sure how that would work out with leaving the application and you would probably have a loop of events if you do it in the event mapping.

Ideally, it should be something that can be set in SDL that limits the mouse to the area of the logical resolution.
https://github.com/diasurgical/devilutionX/blob/0cdb99eadf6394d6aba9849c67e48c26fb0ee0d6/SourceX/miniwin/misc.cpp#L353

**Comment by Chance4us** [comment]
So me and my brother capped the X coordinate to the left and to the right border. The negative bit is also copied now. The diff file is attached. More changes and improvements for better code are welcome.
[misc_msg.cpp.diff.txt](https://github.com/diasurgical/devilutionX/files/3125265/misc_msg.cpp.diff.txt)

**Comment by AJenbo** [comment]
While this solves the case of moving to the right when clicking to the left of the screen it has the unfortunate side effect of giving incorrect user feedback regarding the mouse position. The user might think the mouse has become stuck to the right side of the screen. A workaround for now could be to show the mouse cursor when moving outside the game screen:
`	SDL_ShowCursor(bShow ? SDL_ENABLE : SDL_DISABLE);`

**Comment by Chance4us** [comment]
What about using relative mouse coordinates to avoid the stuck cursor problem?: SDL_GetRelativeMouseState

**Comment by AJenbo** [comment]
I think it would be a good solution, but it would require some changes to the code.

**Comment by Chance4us** [comment]
Or a simple stupid solution.
Use this function to move the mouse to the given position within the window:
SDL_WarpMouseInWindow

**Comment by AJenbo** [comment]
SDL_WarpMouseInWindow can generate a new move event afaik so you easily end up in a loop

**Comment by Chance4us** [comment]
Could you try out these changes?
[misc_msg.cpp.diff.txt](https://github.com/diasurgical/devilutionX/files/3145390/misc_msg.cpp.diff.txt)

**Comment by AJenbo** [comment]
Not a bad solution :+1: will look into integrating it.

**Comment by Chance4us** [comment]
You could also try this code. This code is not approved, but the gameplay feeling is also acceptable.
[misc_msg.cpp.diff.txt](https://github.com/diasurgical/devilutionX/files/3145561/misc_msg.cpp.diff.txt)

**Comment by AJenbo** [comment]
@Chance4us could you submit your two proposals as PRs, it would make it much easier to test and also comment on.

**Comment by Chance4us** [comment]
I don't know for what PR stands for. Maybe:
Press Release
Public Relations
Personal Relationship
However I will create a tiny pull request for this issue now.
The issue was caused due of usage of the wrong fake sdl fullscreen mode.
In this case it is important to set the command: (xrandr --output your_display_output --set "scaling mode" "Full aspect") by the linux terminal before launching the game. The correct aspect ratio or centered timings are normally a task of the graphics driver (nvidia/mesa/xorg etc.)

**Comment by ApertureSecurity** [comment]
@Chance4us  

Allow me to explain everything...

https://www.youtube.com/watch?v=8wUOUmeulNs

**Comment by Chance4us** [comment]
Fantastic. You made me very happy. That's why I now resolved the issue for you

**Comment by ApertureSecurity** [comment]
On a more serious note, I think SDL has a function for this; To keep the mouse from leaving a specific area..

**Comment by AJenbo** [comment]
> In this case it is important to set the command: (xrandr --output your_display_output --set "scaling mode" "Full aspect") by the linux terminal before launching the game. The correct aspect ratio or centered timings are normally a task of the graphics driver (nvidia/mesa/xorg etc.)

It's chosen specifically so that users don't have do do that, it's not for sure that there GPU supports it and it would be different for each OS. Setting the resolution to 640x480 like you suggest is not a viable solution.

> On a more serious note, I think SDL has a function for this; To keep the mouse from leaving a specific area..

I coudn't find it, please refere to it if you can.

**Comment by Chance4us** [comment]
Please try out the new pull request.
