### ISSUE TITLE
Butcher does not provide its carver anymore

### ISSUE THREAD

**Issue by Vitexus** [diasurgical/devilutionX#912]
**Describe**
When defeat the Butcher year ago the reward was special powerfull item - it's carver.  But in current games i can found only some mace on bloody room ground. 

**To Reproduce**
1.) Kill the Bucher
2.) take what remains

**Expected behavior**
Reward have to be Butcher's carver

Maybe i am wrong. Please correct me then.

I use DevilitononX compiled from:

commit a091a56e8e973152e34932ff499c96bd1f134be2 (upstream/master)
Date:   Mon Oct 26 12:39:27 2020 +0000

**Comment by AJenbo** [comment]
You where probaly playing Multiplayer, unique quest items are not dropped in multiplayer.

I have verified that it works correctly in singleplayer in DevilutionX 1.1.0
![image](https://user-images.githubusercontent.com/204594/98455387-312cb780-2170-11eb-8e0a-90b1f4e8c5f4.png)

**Comment by Vitexus** [comment]
Thank you for your time!
