### ISSUE TITLE
Decouple UI scaling from game scaling

### ISSUE THREAD

**Issue by predator8bit** [diasurgical/devilutionX#916]
The idea here is to have the ability to run the game at 1080p for example, but have the UI elements, like the character sheet and inventory scaled up for convenient usage. Here I attached an example of the game running at 1080p and you can see that the inventory is a bit small.

![DIABLORES](https://user-images.githubusercontent.com/27356954/99131102-8bb39100-2612-11eb-9906-02c7110b21c7.png)

**Comment by qndel** [comment]
this would take rewriting half of the game

**Comment by AJenbo** [comment]
Yeah, it would require rewriting all UI-related code first. I'm not saying that this won't be done, in fact, I expect that we will do this rewrite as part of other code cleanups. But at the moment it is not feasible so having an issue for it is a bit meaningless.

**Comment by predator8bit** [comment]
I see, well it was worth a shot :D
