### ISSUE TITLE
Blackjade and Red Vex idle and cannot be attacked if lured back to the teleporter

### ISSUE THREAD

**Issue by john-parton** [diasurgical/devilutionX#918]
**Describe**
In Archbishop Lazarus's Lair, after triggering the encounter with Lazarus and the Hellspawn, if you lure the Hellspawn back to the teleporter, and then use the teleporter a 2nd time to get into the main chamber, and then go all the way back to the teleporter again, the Hellspawn sit idly on the teleporter, and cannot be interacted with. Killing Lazarus makes them return to normal

**To Reproduce**
1. Got to Lazarus's Lair
2. Go through all of the puzzle like normal until triggering the encounter
3. Lure Blackjade and Red Vex back to the teleporter
4. Go through the teleporter
5. Don't kill Lazarus
6. Go back to the teleporter
7. Blackjade and Red Vex will idle and cannot be attacked or interacted with

**Expected behavior**
Blackjade and Red Vex should attack the player and be able to be attacked

**Screenshots**
Sorry, no screenshot. 

**Additional context**
Version 1.1.0 on the RG350

**Comment by AJenbo** [comment]
Without specifically testing for this I'm pretty sure this is a vanilla issue. Still thanks for reporting.

**Comment by AJenbo** [comment]
This should have been fixed togeather with: https://github.com/diasurgical/devilutionX/issues/889
