### ISSUE TITLE
Item duplication vanilla behavior

### ISSUE THREAD

**Issue by bitshifter10** [diasurgical/devilutionX#919]
Please restore the item duplication vanilla behavior, e.g. gated behind a flag in the .ini file.
It is frustrating to switch between old Windows emulation and copy player files.

Reasoning is that it's sometimes fun to duplicate stuff; not necessarily to win the game, but as a cheat that adds fun for some reason and nostalgia both in single and multi player of course.

And this behavior is one of the key funny things in Diablo, as far as I see it, part of the original game.
The act of going back and forth to pickup items just in time is something that's identified with Diablo I, mentioned and illustrated many times in animations as well for many years..

Most games have cheats like DOOM, and it doesn't make them less of a challenge IMHO, anyone could edit the WAD to include all weapons - it's a fun convenience aka a cheat. Doom recreations of the original preserve its cheats.

In the future a host can get clients' ini and only reject if e.g. this setting differs when disabled on the host.
However I don't think whether this matters, as gaming over a LAN involves basic trust anyway, and limiting due to little brothers not listening keeping duping seems an irrelevant use-case to me :) alas this paragraph solves such a problem as stated. I'm not interested in hacking the game for this to work again as it originally did...

IIRC cain05 on Reddit wrote they implemented it very easily [1] so IMHO this request should be equally easy..

Very much appreciated. Please consider. Thanks.

[1] https://www.reddit.com/r/linux_gaming/comments/j95j7b/comment/g8kfx3s in the thread https://www.reddit.com/r/linux_gaming/comments/j95j7b/devilutionx_110_released_with_widescreen_support/
> My apologies for fixing the dupe bug, hopefully people won't be too upset about it. I never intended to fix it but I was playing with my brothers and one kept duping so I fixed it in my fork and ended up submitting a PR. It really does lessen the experience though, so hopefully it will make the game more challenging.

**Comment by bitshifter10** [comment]
I went over a large portion of the commits and unsure how to find the relevant one. Have to return to work assuming contributers know much better than I :)

**Comment by AJenbo** [comment]
Sorry, we don't have intentions of reverting this.

But just like with Doom you can mod it in if you like :)
https://github.com/diasurgical/devilutionX/commit/1ee9eee711b5f7ed83846870e8e83f9b79f56278
(if you build the game in debug mode you also get a bunch of cheat options)

**Comment by AJenbo** [comment]
P.s. bugs like these are not fixed in the 1.0.x branch so you can also just use them, but then you won't get new features (like widescreen support) eiter.
https://github.com/diasurgical/devilutionX/releases/tag/1.0.3

**Comment by bitshifter10** [comment]
Thanks for the prompt reply. Should future readers or I be interested, would you mind linking the commit that fixed it? :)
Thanks!

**Comment by qndel** [comment]
he did ...

**Comment by bitshifter10** [comment]
> he did ...

It's a release and the 1.1.0<-1.0.3 change has about 300 commits, it's hard to find the commit, I didn't find it...

**Comment by qndel** [comment]
previous message 🤦

**Comment by bitshifter10** [comment]
> previous message 🤦

Refreshed the page and saw it, didn't render on my phone. A more helpful reply could've been "https://github.com/diasurgical/devilutionX/commit/1ee9eee711b5f7ed83846870e8e83f9b79f56278"

**Comment by mrdeathjr28** [comment]
@bitshifter10 

In my case works ok (debug version compiled + inv.cpp modified)

https://www.youtube.com/watch?v=nQ-7MBMC-Y0

**Comment by qndel** [comment]
what a surprise that it works when you reverted the fix, who would've thought ...

**Comment by Espionage724** [comment]
Someone I installed this for specifically told me the other day they weren't able to dupe or proceed with the game; they are used to being able to dupe the gold. I was hoping there was a config setting or something to allow it.

I guess I'm fine with using an oudated build, but I would prefer this to be a setting.

**Comment by DakkJaniels** [comment]
Not going to happen

**Comment by AJenbo** [comment]
You must find another way to cheat or find a mod that makes the game easier.
