### ISSUE TITLE
Printf doesn't do anything on windows

### ISSUE THREAD

**Issue by qndel** [diasurgical/devilutionX#921]
printf doesn't work on windows - seems to be related to SDL

**Comment by AJenbo** [comment]
Check if this is related: https://github.com/diasurgical/devilutionX/blob/297e98e8487b79c0016226b4c97da071b32e50cb/CMakeLists.txt#L302

**Comment by heinermann** [comment]
Non-console windows applications won't output to a command line and it needs to attach itself, start here: https://stackoverflow.com/questions/30098229/win32-application-write-output-to-console-using-printf

**Comment by AJenbo** [comment]
Here is what I think would be needed. Since it links to windows.h it probably needs to live in SourceX and be declared in SourceS so that it is visible form the engine.

```cpp
void printInConsole(const char *message)
{
#ifdef __WIN32__
    static HANDLE stderrHandle = NULL;
    if (stderrHandle == NULL) {
        if (AttachConsole(ATTACH_PARENT_PROCESS)) {
            stderrHandle = GetStdHandle(STD_ERROR_HANDLE);
        }
    }

    if (stderrHandle == NULL)
        return;
    
    WriteConsole(stderrHandle, message, strlen(message), NULL, NULL);
#else
    printf(message);
#endif
}
```

But there might also be simpler ways to solve it :)

**Comment by AJenbo** [comment]
Code works, no changes needed...
![image](https://user-images.githubusercontent.com/204594/110948901-367a5880-8342-11eb-971c-1d8826b596ad.png)
