### ISSUE TITLE
Debug switches/functionality/"cheat mode"

### ISSUE THREAD

**Issue by Baracudus** [diasurgical/devilutionX#929]
Is there a way to enable the debug functionality programmed in the sourcecode? 

Just to mess a little around. I searched in the source for a hotkjey or commandline switch like "-debug" but found nothing. Is there a way to mess with things without compile it new with the debug flag on? Would be interesting when finding a bug in multiplayer mode,  the actual seed of the level could be posted to reproduce the bug or the odd situation (wrong texture placements etc..).

**Comment by qndel** [comment]
no
