### ISSUE TITLE
QOL change: Save Cursor position on vendors after purchasing

### ISSUE THREAD

**Issue by julealgon** [diasurgical/devilutionX#937]
In vanilla, the selection cursor is always reset to the top position when shopping after any action is taken, including purchasing an item. This results in a very poor user experience when purchasing many of the same item (potions), or many items close to each other (e.g. scroll of identify + scroll of town portal).

This is especially troublesome for purchasing potions when the desired potion is not the topmost item in the vendor inventory. People tend to use a combination of mouse and keyboard for purchasing these potions in bulk, somewhat like this:
1. Click "Full Healing Potion"
2. Press enter to select
3. Press enter to confirm
4. Back to 1

This is usually repeated many times, sometimes as long as it takes to fill in the player inventory. Thus, even if the actions are still relatively fast, they become really slow compared to just holding the "Enter" key.

The proposal here is to persist the cursor position in the same vendor screen, so as to allow people to buy items more easily.

The persistence should only happen while purchasing a specific vendor section. For example:
1. Open griswold normal items
2. Scroll to bottom
3. Purchase item
4. Vendor screen is refreshed, and cursor stays at bottom
5. Back to main griswold menu
6. Select Premium items
7. Cursor should be at the top
8. Back to main griswold menu
9. Open normal items again
10. Cursor should also be at the top

The cursor should point "to the next item available" when the item is bought. If the cursor was pointing to the last item, then it should keep pointing to the new last item.

**Comment by qndel** [comment]
I actually did it in infernity ;p

**Comment by AJenbo** [comment]
Time to resurect another patch i guess :)

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/5d2af51d01a31865e7384ba1fb0d24a2b2c55d26
