### ISSUE TITLE
Could upstream apply FreeBSD port patches?

### ISSUE THREAD

**Issue by nunotexbsd** [diasurgical/devilutionX#939]
Hello,

FreeBSD [devilutionX](https://www.freshports.org/games/devilutionX/) port uses 2 patches so compiling is possible.

Could devilutionX authors take a look at patches and see if it is possible to include in main code?

- [patch-3rdParty_StormLib_src_StormPort.h](https://svnweb.freebsd.org/ports/head/games/devilutionX/files/patch-3rdParty_StormLib_src_StormPort.h?view=markup)

- [patch-CMakeLists.txt](https://svnweb.freebsd.org/ports/head/games/devilutionX/files/patch-CMakeLists.txt?view=markup)

Thanks,

Nuno Teixeira

**Comment by AJenbo** [comment]
I don't see any issues with the changes, feel free to create a PR so it can get tested and reviewed

**Comment by AJenbo** [comment]
P.s. we also support mips CPUs so you can enable builds for it as well (haven't tested mips64)

**Comment by nunotexbsd** [comment]
Hello,

Sent: https://github.com/diasurgical/devilutionX/pull/940

Thanks
