### ISSUE TITLE
Missing Walls

### ISSUE THREAD

**Issue by Trihedraf** [diasurgical/devilutionX#941]
Walls that are supposed to be able to be semi transparent are just completely invisible

This happens on the current version when built from source. I tried just downloading 1.1.0 release and it did not do it. So I built 1.1.0 and then current with same libraries and everything and it only does it in the current version.

1.1.0 Source Built Version
![1 1 0](https://user-images.githubusercontent.com/26759970/101598055-6b29ed00-39ac-11eb-94d8-33e240ae4bbc.png)

Current Source Built Version
![Current](https://user-images.githubusercontent.com/26759970/101598065-711fce00-39ac-11eb-9d64-697dbad7b59c.png)

**Comment by AJenbo** [comment]
Can you give some additional info about what system and compiler you are using, also please see if this commit is related:
https://github.com/diasurgical/devilutionX/commit/8e1c61a6f7a76bacedc7311ffce9e4b79c2aab8a

**Comment by Trihedraf** [comment]
I am on Windows 10. Built with VS19 and MinGW.

I downloaded that git version and the one before and built both it is that commit that broke it. https://github.com/diasurgical/devilutionX/commit/8e1c61a6f7a76bacedc7311ffce9e4b79c2aab8a

**Comment by qndel** [comment]
can u upload save?

**Comment by Trihedraf** [comment]
[single_0.zip](https://github.com/diasurgical/devilutionX/files/5664305/single_0.zip)

**Comment by AJenbo** [comment]
@madmann91 could you look in to this?

> I am on Windows 10. Built with VS19 and MinGW.
Are you using VS19 as an IDE and MinGW as the compiler, or are you saying that you used both compiler and had the same issue with both?

**Comment by Trihedraf** [comment]
I have built it with both to make sure it wasn't a bug with one or the other. And I have tried it on multiple computers as well.

**Comment by spidertoast** [comment]
I can reproduce this on Gentoo Linux when I apply the RenderLine improvements to 1.1.0. 
Running a HP mini 110 without graphics acceleration as there's no driver for the integrated SGX545 PowerVR graphics of the Atom N2800 and I thought this to be a unique case to this outdated hardware. 
@Trihedraf you can try to apply the RenderLine improvements to v1.1.0 via this patch and see if the issue reoccurs:
[https://github.com/spidertoast/devilutionX-QOL-patches/blob/master/patches/0001-Improvements-to-the-RenderLine-function-920.patch](https://github.com/spidertoast/devilutionX-QOL-patches/blob/master/patches/0001-Improvements-to-the-RenderLine-function-920.patch) 
![renderline](https://user-images.githubusercontent.com/74438661/101602312-dde0aa00-3a38-11eb-914d-bad803ef0f73.png)

**Comment by Trihedraf** [comment]
@spidertoast Just applied that patch to 1.1.0 and the issue does occur after.

**Comment by madmann91** [comment]
I'll look into this.

**Comment by madmann91** [comment]
On my machine I do not observe the artefacts you describe, but I do observe different ones. I have created a PR (#942) that fixes those that I can see.
@Trihedraf Could you check that this indeed fixes the issue on your machine?

**Comment by spidertoast** [comment]
@madmann91 the fix works for me.

**Comment by Trihedraf** [comment]
@madmann91 it fixed it for me as well
