### ISSUE TITLE
Feature: hero password protection

### ISSUE THREAD

**Issue by galaxyhaxz** [diasurgical/devilutionX#946]
**_Repost from one of my private projects, but I think it's relevant and people would like this in DevilutionX._**

I had memories today of when I played Diablo on the family computer. One of my step mom's kids had used her character once and died and lost her items, they also ruined my barbarian. So I thought of a way to prevent this.

The game encrypts multi and single heroes with a different password by default. My idea is that there is no password by default and instead you can optionally enter a password for the character. This way the data can only be decrypted if you know the password since it's not stored anywhere.

So when you want to select the hero and make a game it asks for the password each time. This also goes along with my idea for a shared stash, where you can enter the password to access the stash of another player. For example if Jon wants to give some spell books to Sarah, he enters her password then can transfer items or take them from her stash.

This feature is only really useful if you share a computer with someone. But also protects against tampering. Any thoughts on this??

**Comment by AJenbo** [comment]
Should probably default to the legacy password instead of no password, for compatibility

**Comment by glebm** [comment]
Since DevilutionX stores saves in user-specific directories, is this actually useful?

**Comment by galaxyhaxz** [comment]
Yeah, you can do that obviously, and have a flag that determines if a custom pass is used. Just a thought. I think this idea would be more relevant on console ports where potentially a whole family shares it. It's such an easy thing to implement.

**Comment by galaxyhaxz** [comment]
@glebm, when your only way of playing Diablo is on your parents computer, on their account, all saves are on the same account. Plus, storing in the user folder hinders portability if you want to have it run from a flash drive and store everything in it's directory.

**Comment by glebm** [comment]
Fair, a command-line flag would be easy to implement too.

**Comment by galaxyhaxz** [comment]
By all means I'm an adult and have my own PC lol. I'm just thinking of those odd balls where a parent let's their kid play on their PC every now and then. I know quite a few that do.

**Comment by qndel** [comment]
I don't know any parents that'd ruin your diablo saves :D

**Comment by AJenbo** [comment]
Back in the 90s my brother actually played on one of my heros :o

**Comment by qndel** [comment]
back in the 90s I played on my brother's save :P

**Comment by galaxyhaxz** [comment]
back in the 90s I fly my pterodactyl all the way to pangaea for a nice trip.

**Comment by galaxyhaxz** [comment]
I'll close this. On the off chance the Grinch who stole save files visits you this Christmas, the idea was tossed out there ;)
