### ISSUE TITLE
Some command line arguments not working (in Windows?)

### ISSUE THREAD

**Issue by tomasz1986** [diasurgical/devilutionX#949]
**Describe**

I have a problem with command line arguments like `--config-dir` or `--data-dir` not working in Windows.

For instance, trying to use

```
devilutionx --config-dir=c:\devilutionx
```

only moves the cursor to a new line in CMD, but the program does not start. On the other hand, other arguments like `-x` seem to work fine, but I am not sure whether there is any pattern here.

**To Reproduce**

1. Download and unpack devilutionx-windows-i386.zip from https://github.com/diasurgical/devilutionX/releases/tag/1.1.0.
2. Open a new CMD window and navigate to the unpacked folder.
3. Type `devilutionx --config-dir=.` or `devilutionx --config-dir=%cd%`
4. Nothing happens.

**Expected behavior**

The game should launch with the specified command line arguments.

**Screenshots**

**Additional context**

I have tested both in Windows 10 and Windows 7, but there is no difference.

**Comment by qndel** [comment]
because it's not "=", you add the path after space

**Comment by tomasz1986** [comment]
Still nothing happens…

I have tried

```
devilutionx --config-dir "c:\devilutionx"
```

and

```
devilutionx.exe --config-dir "%cd%"
```

and

```
devilutionx.exe --config-dir "."
```

but the program does not launch at all.

**Comment by qndel** [comment]
because it's devilutionx.exe, not devilution >.>

**Comment by tomasz1986** [comment]
Hey, please just test instead of trying to discredit and outsmart a user.

Windows treats `devilutionx` and `devilutionx.exe` as the same command (unless you also have `devilution.cmd` in the same folder).

In additon, I have just tested `devilutionx.exe` explicitly, e.g.

```
devilutionx.exe --config-dir "c:\devilutionx"
```

and the result is exactly the same. Nothing happens.

**Comment by qndel** [comment]
Hey, I tested ... works fine

**Comment by tomasz1986** [comment]
Which Windows version exactly are you testing in? Can you post the whole command that you are using?

**Comment by qndel** [comment]
`devilutionx.exe --config-dir "giant potato"` even this works for me

**Comment by qndel** [comment]
I have no clue what's in 1.1.0 release, just saying it works 100% in latest github code

**Comment by tomasz1986** [comment]
Well, I guess that in order to use the latest GitHub code you need to compile it yourself, right?

If yes, then I would say that the issue is still relevant as it is, since very few people trying just to play the game are going to compile the code, and especially not Windows users.

**Comment by qndel** [comment]
that's what next releases are for

**Comment by qndel** [comment]
[devilutionx.zip](https://github.com/diasurgical/devilutionX/files/5743107/devilutionx.zip)
here's latest ver

**Comment by tomasz1986** [comment]
Thank you. The arguments do work in this one 🙂. This would mean that the last release version simply has no support for them yet.

**Comment by qndel** [comment]
the thing is printing text to console is currently broken on windows :D

**Comment by AJenbo** [comment]
Maybe we should have an issue regarding the Windows version not showing any out put in CLI?

I don't know if Windows allows for both GUI and CLI though since it seams to be kinda special.

**Comment by qndel** [comment]
what's this? https://github.com/diasurgical/devilutionX/issues/921 👍
