### ISSUE TITLE
Anyone get this DBUS error on Ubuntu 18.04?

### ISSUE THREAD

**Issue by xcom169** [diasurgical/devilutionX#95]
<pre>DUMMY: SetUnhandledExceptionFilter @ /home/ZZZ//D1/SourceX/miniwin/misc.cpp:496
DUMMY: FindWindowA : class: DIABLO window: (null)
DUMMY: SFileEnableDirectAccess @ /home/ZZ//D1/SourceX/storm/storm.cpp:670
DUMMY: LoadIconA @ /home///D1/SourceX/miniwin/misc.cpp:420
DUMMY: LoadCursorA @ /home///D1/SourceX/miniwin/misc.cpp:435
DUMMY: LoadImageA @ /home///D1/SourceX/miniwin/misc.cpp:429
DUMMY: RegisterClassExA @ /home///D1/SourceX/miniwin/misc.cpp:388
dbus[13366]: arguments to dbus_message_new_method_call() were incorrect, assertion &quot;path != NULL&quot; failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
</pre>

**Comment by AJenbo** [comment]
See https://github.com/diasurgical/devilutionX/issues/20
