### ISSUE TITLE
Hellfire binary for the RG350

### ISSUE THREAD

**Issue by rayhern** [diasurgical/devilutionX#954]
Is there any way possible we could get a ogk file for the rg350 and hellfire? That would really help me out. Great work on all you have done!

**Comment by qndel** [comment]
hellfire is not finished yet

**Comment by rayhern** [comment]
Oh, sorry about that, I had installed it on my 3ds and thought it was done. Great job everyone! Thank you for making my 2020. Without devilutionX, this year was useless. You all deserve an award.

**Comment by AJenbo** [comment]
Once Hellfire is done we will release 1.2.0, which will include a prebuild RG350 image. The goal is to have the game automatically detect the expansion based on the provided MPQ files, but allow you to force the base game by providing `--diablo` as an argument.
