### ISSUE TITLE
Magical Gothic Shields

### ISSUE THREAD

**Issue by Noleafcloverx** [diasurgical/devilutionX#957]
**Describe**

I just got 6 magical Gothic Shields in the Hell Levels (13-15) and they were all variants of Shield of the Wolf...

Not sure if a bug, but way too often to be random...

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AJenbo** [comment]
I clicked on "..." but did not encounter this issue.

In all seriousness though Diablo's RNG is known to be biased so this isn't totally unexpected.
