### ISSUE TITLE
DevilutionX complains at start on Haiku

### ISSUE THREAD

**Issue by extrowerk** [diasurgical/devilutionX#96]
Somewhere between 29. 04 and today a commit added some kind of check or something, now it complains:
"Diablo cannot read a required data file.\nYour diabdat.mpq may not be in the Devilution folder or it's read only.\nPlease ensure that the filename is in all lower case and try again.\n    %s"

I put the diabdat.mpq to the "/boot/home/config/settings/diasurgical/devilution" folder, this is the folder where devilutionx automatically saves the "diablo.ini" file, so this is, where it would search for it, and my old checkout finds it correctly, while the current just complains.

I assume it stat() the path and finds the Haiku's own packaged virtual file-system.
On Haiku the folder-structure is partially RO, and it is not possible to change it.
The folder, where the mpq resides is writeable, but the "/boot/home/config" folder not.

I can't seem to find the problematic commit,  but this problem doesn't allows to run the game on Haiku.

**Comment by AJenbo** [comment]
The game first looks in the same folder as the executable.

The game shouldn't require write access to the MPQ, this is currently a known but in DeviltuionX, see https://github.com/diasurgical/devilutionX/issues/45

**Comment by extrowerk** [comment]
I think this is something else, as i told the checkout from 29.04 works ok, while the one from today not.
I'll try to bisect.
