### ISSUE TITLE
CalculateGold() is looking at players belt.

### ISSUE THREAD

**Issue by rayhern** [diasurgical/devilutionX#961]
I was going through the code last night and i noticed the CalculateGold() function checks the players belt for gold stacks... you cant have gold in your belt...right? Am I losing it?

**Comment by qndel** [comment]
better safe than potato ;)

**Comment by nickgavran** [comment]
You can't have gold in your belt, but I believe there were early plans to allow goldpiles in your belt. The idea was scrapped early in development, but I guess the code is still there

**Comment by AJenbo** [comment]
It's some sort of left over from the beta times afaik
