### ISSUE TITLE
Changing MAXMISSILES causes Segmentation Fault

### ISSUE THREAD

**Issue by peter-lang** [diasurgical/devilutionX#963]
**Describe**
I tried to change `MAXMISSILES` as mentioned in the forum: https://www.gog.com/forum/diablo/sprite_limit_changed
After rebuilding with 250 value, lots of Sprites causes Segmentation Fault error.

Unfortunately I have no debug info, so I cannot be more concrete on the location of the segfault. This is the OS X syslog stacktrace I've got:
```
dvl::DrawMissilePrivate(dvl::MissileStruct*, int, int, int) + 98
DrawMissile + 183
dvl::scrollrt_draw_dungeon(int, int, int, int) + 1227
dvl::scrollrt_draw(int, int, int, int, int, int) + 953
dvl::DrawGame(int, int) + 989
...
```

As I've checked, it should be that the MissileStruct input param is NULL, however it comes from the globally initialized `missile` array, so it should not be null. My other guesses are:
- either `&missile[dMissile[x][y] - 1]` or `&missile[missileactive[i]]` is misaligned
- OSX does not let you allocate 250 length array of MissileStruct on the stack. I'm not sure on the behaviour in this case, if it is possible.

**To Reproduce**
1. Change MAXMISSILES to 250, rebuild on OS X.
2. Load a game saved in previous version using MAXMISSILES 125.
3. Go to dLvl15, cast Chain Lightning with lots of mobs around.
4. SegFault happens.

**Expected behavior**
No segmentation fault.

**Comment by qndel** [comment]
You can't change things like this and expect to load old saves ...

**Comment by peter-lang** [comment]
Hi, thank you for the fast reply!
Do you expect that the issue is caused by the old save file? Can you point me to where I should make further changes in the code, so the save files can be converted to working ones?

**Comment by qndel** [comment]
I'm sure that's the issue, I've increased MAXMISSILES to 10k in my mod infernity

**Comment by galaxyhaxz** [comment]
See here: https://github.com/diasurgical/devilutionX/blob/master/Source/gendung.cpp#L148

The missile array is `char` by default so any value more than 127 is a negative number. You need to change that to unsigned for 255 missiles or short/int for more. This will break saves as the array is different size.

It appears @AJenbo may have already updated it, but in the vanilla source `PutMissile` also needs to be changed. This is because of the cast: `dMissile[mx][my] = (char)i + 1;` The funny part is they used `int` everywhere, so conveniently only the array needs updating.

**Comment by peter-lang** [comment]
Thanks both of you for pointing me to direction! I would assume that saves are handled in https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp

I'll have a look at these sources and check for myself if I can make backward compatible changes.

**Comment by peter-lang** [comment]
@galaxyhaxz 
It seems that save files only break, when people are not in Town. This might be used to "convert" savefiles, people just need to be at town.
https://github.com/diasurgical/devilutionX/blob/master/Source/loadsave.cpp#L765

I'm also not sure, where is multi player saving handled. I think these methods are only invoked for Single Player - Save. Do you happen to know, where I might search for Multiplayer Load/Save?

It also seems that other types also assume that MAXMISSILE is less than 127.
Both `missileactive` and `missileavail` is handled in Save/Load to be CHAR, however the variables are defined as INT arrays, which might cause overflows also if MAXMISSILE is altered.

**Comment by qndel** [comment]
multiplayer doesn't save missiles as it doesn't save levels
