### ISSUE TITLE
Migrate from TravisCI builds to GitHub Actions

### ISSUE THREAD

**Issue by AJenbo** [diasurgical/devilutionX#965]
TravisCI is effectively dead when it comes to OSS projects. In December they introduced a new price model and gave each org a one time allotment of 10,000 "credit". For macOS they charge 50 credit per minute (rounded up), with each build taking roughly 3 minutes that gave us just enough for 50 commits, or about two weeks before it ran out.

It's possible to request more minutes, but current reports is that all requests are being rejected at the moment.

The only other option for macOS builds appears to be GitHub Actions, so if anyone has experience with that we would very much appreciate a PR that makes the migration from TravisCI to GitHub Actions.

Bonus points for also migrating the ppc64le builds, and or setting some up for FreeBSD

**Comment by glebm** [comment]
CircleCI claims to have free macOS builds for OSS:

> CircleCI offers organizations on our free plan 25,000 credits per month ($180 annual value) for open source macOS builds. To get access, contact us at billing@circleci.com. 

https://circleci.com/open-source/
