### ISSUE TITLE
Cannot change spells using the controller

### ISSUE THREAD

**Issue by rayhern** [diasurgical/devilutionX#967]
Platform:
rg351p and arkos

**Comment by AJenbo** [comment]
Version?

**Comment by glebm** [comment]
arkos is using the release version IIRC
this may already be fixed on master

**Comment by rayhern** [comment]
I actually built from source on master. I think maybe the issue might be SDL, after further research.

**Comment by rayhern** [comment]
I compiled as 32 bit and was able to change spells with the controller it seems this is related to the (not able to move mouse in 64 bit on ARM.)

**Comment by AJenbo** [comment]
?
