### ISSUE TITLE
Clicking an inventory item causes mouse/item to offset

### ISSUE THREAD

**Issue by heinermann** [diasurgical/devilutionX#969]
**Describe**
Based on the way inventory items are clicked, the mouse or item will be offset slightly. This normally happens in Diablo, but the cursor ends up at its original location. The behaviour is much worse in DevilutionX with a permanent cursor slide. Rapidly clicking an item in your belt slot for example will very quickly either stop or toss it on the ground because the cursor wants to move up and left.

**To Reproduce**
1. Place a minor healing potion in your belt slot.
2. Rapidly click the potion, between the center and bottom right. This will repeatedly pick it up and place it back in the belt.

**Expected behavior**
The potion and mouse cursor should be relatively stable and remain in the belt slot it came from.

**Screenshots**

**Diablo v1.09 (GOG) Win32**
![diabcursor](https://user-images.githubusercontent.com/1966366/103628107-609f3c80-4ef3-11eb-8f09-814218c6c70d.gif)

**61a580588ca09decdba01003cb45c49212454f99 Win64**
![dxcursor](https://user-images.githubusercontent.com/1966366/103628135-6ac13b00-4ef3-11eb-9184-3fdc5f4b110a.gif)

**Additional context**
Happens in 61a580588ca09decdba01003cb45c49212454f99 on Win64. Tested in 1.1.0 Win32 and it has a similar result.

Could be something with cursor events in SDL, an off-by-one issue with cursor related math, or something else.

**Comment by mgpat-gm** [comment]
For further information see:
https://github.com/diasurgical/devilutionX/issues/770

**Comment by heinermann** [comment]
@mgpat-gm to enable that do I create a `diablo.ini` in the same directory with the following contents?

```ini
[devilutionx]
integer scaling=1
```

Because if so it's not working, and why is it not enabled by default?

**Comment by qndel** [comment]
check readme for ini location

**Comment by heinermann** [comment]
The readme doesn't have anything on that...

**Comment by qndel** [comment]
`macOS ~/Library/Application Support/diasurgical/devilution
Linux ~/.local/share/diasurgical/devilution/
Windows C:\Users\[username]\AppData\Roaming\diasurgical\devilution`

**Comment by heinermann** [comment]
I guess I should have done more than CTRL+F "ini" xD

And duh, integer scaling does.... integer scaling. I'm going to try just replacing cursor pos with a float.
