### ISSUE TITLE
character selection window not scrolling

### ISSUE THREAD

**Issue by tomjtoth** [diasurgical/devilutionX#97]
When creating more characters than would fit into the character selection window the contents in right bracket won't scroll hence the name of the character does not show

Tried with my 4 years old 1.09 savegames (10 characters) and also in single player creating new blank characters

**Comment by tomjtoth** [comment]
dupe

**Comment by AJenbo** [comment]
You can still navigate them and see the info to the right. If you feel up for it you're more then welcome to work on this feature.
