### ISSUE TITLE
Unable to build devilutionx with opendingux toolchain

### ISSUE THREAD

**Issue by rayhern** [diasurgical/devilutionX#972]
**Describe**
When running OpenDingux build.sh script for rg350, build fails because of man pages on automake I think?

**To Reproduce**
Here is a notebook I setup trying to build devilutionx. 
https://colab.research.google.com/drive/1pWW1Uuck8RNlCY2-B0G5qaXVHF3dMsw6?usp=sharing

**Expected behavior**
Devilution OPK is generated.

**Error**
>>> host-automake 1.14.1 Building
  GEN      bin/automake
  GEN      bin/aclocal
  GEN      t/ax/shell-no-trail-bslash
  GEN      t/ax/cc-no-c-o
  GEN      doc/aclocal.1
  GEN      runtest
  GEN      doc/automake.1
  GEN      lib/Automake/Config.pm
  GEN      t/ax/test-defs.sh
  GEN      doc/aclocal-1.14.1
  GEN      doc/automake-1.14.1
help2man: can't get `--help' info from automake-1.14
Try `--no-discard-stderr' if option outputs to stderr
Makefile:3707: recipe for target 'doc/automake-1.14.1' failed
make[1]: *** [doc/automake-1.14.1] Error 255
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/devilutionx-buildroots/rg350/output/build/host-automake-1.14.1'
package/pkg-generic.mk:165: recipe for target '/root/devilutionx-buildroots/rg350/output/build/host-automake-1.14.1/.stamp_built' failed
make: *** [/root/devilutionx-buildroots/rg350/output/build/host-automake-1.14.1/.stamp_built] Error 2

Thanks in advance.

**Comment by rayhern** [comment]
This can be closed I was able to generate an opk with ubuntu in a virtual machine.

**Comment by AJenbo** [comment]
You can close issues that you open

**Comment by rayhern** [comment]
Thanks, I will keep that in mind. Sorry about that.
