### ISSUE TITLE
Multiplayer game crashes when trying to join a second time.

### ISSUE THREAD

**Issue by rayhern** [diasurgical/devilutionX#974]
**Describe**
The game crashes when joining a multiplayer game, then exiting, then joining again. When joining for the second time the game crashes hard and closes.

**To Reproduce**
1.) create multiplayer game.
2.) join created game with another client
3.) leave the game.
4.) Try to join the game again. (this is when the game will crash, on all operating systems I have tested on MacOS, and rg350.

**Expected behavior**
The game doesn't crash, and lets you join a second time.

**Screenshots**
Cant give screenshots because the game force closes.

**Additional context**
I am looking into the code to see if I can fix it. Just wanted to document it here, so that we know it's an issue. I am still a c/ cpp newbie. Thanks everyone.

**Comment by AJenbo** [comment]
what version?

**Comment by rayhern** [comment]
1.1.0 the newest for Mac OS

**Comment by AJenbo** [comment]
This has been fixed
