### ISSUE TITLE
Closing devolutionx error

### ISSUE THREAD

**Issue by ntaraku2** [diasurgical/devilutionX#975]
> Closing devolutionx error

From tests done today using the latest release(1.1.0), rather than closing applet mode error (issue below) to switch home menu, I get atmosphere error wall code and have to “reboot” or “boot into payload”. 

Anything I can do to help I’ll be happy to.

_Originally posted by @ntaraku2 in https://github.com/diasurgical/devilutionX/issues/778#issuecomment-760584900_

**Comment by AJenbo** [comment]
Duplicate https://github.com/diasurgical/devilutionX/issues/778
