### ISSUE TITLE
Ambiguity in save file location ... ?

### ISSUE THREAD

**Issue by arjunepr** [diasurgical/devilutionX#99]
So... from the docs it isn't clear where the saves are stored. I built the game on Linux, it opened and ran perfectly, so far - and I saved the game. I closed it, opened up the build directory where devilutionx is, and I was a little disappointed to see there wasn't any directory to hold the save states...

I did check my home directory and couldn't find a location there either...

If saves are being stored somewhere... then I think it would be great if it would be mentioned in the docs :)

I should mention that I'm REALLY grateful for this project and the effort being put to actively develop it. It'd be great if the saves are possibly usable across different builds, and if the locations of the said saves are documented

For me, it's so I could keep backups of my single player campaigns

Thanks again :)

**Comment by AJenbo** [comment]
It's mentioned in the Readme for release downloads, since each platform keeps user data in different locations.

On Linux it's in  .local/shared/diasurgical/devilution 

Glad you like it.
