### ISSUE TITLE
Items incorrectly flagged as duplicate

### ISSUE THREAD

**Issue by psychoreactorq** [diasurgical/devilutionX#990]
I got a shrine that changed my potions into rejuvenation, then I tossed them all on the ground in town. Later I found the same shrine again, and when I tossed the second set of rejuvenation potions on the ground, it said "Duplicate item detected. Removing"
I highly doubt this bug exists in the original game binary

**Comment by AJenbo** [comment]
What version?

I doubt this isn't also affecting the original game. We haven't even fixed the original bug that makes the shrine turn any item into a rejuvenation potion if holding it while using the shrine.

**Comment by psychoreactorq** [comment]
DevilutionX v1.1.0-99a433f2

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/commit/99a433f2

Hellfire or Diablo?

**Comment by psychoreactorq** [comment]
Sorry for lacking this information in the first place. I was using Diablo.

**Comment by qndel** [comment]
it's a vanilla bug, it wasn't uncommon for potions to get flagged as duplicates

**Comment by AJenbo** [comment]
Yeah, I have had some thoughts about doing that. It's pretty trivial to avoid for anyone that is determined to chat, and we have already solved the most common way of duplicating things.

**Comment by galaxyhaxz** [comment]
It's only useful imo for debugging to make sure items don't legitimately spawn as dupes. That and for people who plan on implementing a server where you don't want people to cheat (in diablo 2 dupes are only deleted online)

**Comment by AJenbo** [comment]
This is now "fixed", because we do not perform this check anymore
