### ISSUE TITLE
Translation support and editing current text in game.

### ISSUE THREAD

**Issue by saiyoucho** [diasurgical/devilutionX#994]
Is there a current planning on how to handle translation support in the game or is there any way right now to translate/edit the text in game? I understand that it seems both the original diablo exe and devilutionX have all the game's text baked into the .exe file and can be viewed in a hex editor, but I was wondering if there currently is a better way other than hexedit to translate using devilutionX.

I've seen some posts regarding translations and I would really like if there was support for it.

**Comment by qndel** [comment]
translation support will surely come after we finish integrating hellfire, this is the most important thing atm

**Comment by AJenbo** [comment]
https://github.com/diasurgical/devilutionX/issues/66
