### ISSUE TITLE
2x Zoom in Windowed mode/having Zoom mode set as default?

### ISSUE THREAD

**Issue by eisnerguy1** [diasurgical/devilutionX#998]
So, I was wondering if there was a way to scale everything 2x if the width & height are 2x the default values, or have the Zoom mode set as default?  

For instance, here's what it looks like with width=640 & height=480:
<img width="640" alt="Screen Shot 2021-02-07 at 3 02 53 PM" src="https://user-images.githubusercontent.com/3295271/107159707-bede9580-695f-11eb-9134-2a953c9a473d.png">

And here's what it looks like with width=1280 & height=960:
<img width="1280" alt="Screen Shot 2021-02-07 at 3 02 26 PM" src="https://user-images.githubusercontent.com/3295271/107159683-aa020200-695f-11eb-9864-97a727f095a1.png">

The graphics don't scale up by 2x.  It just zooms everything out. 

Here's what my Diablo.ini file has for settings:
```
[Diablo] 
Intro=0
Gamma Correction=100
Color Cycling=1
Sound Volume=0
Music Volume=0
[devilutionx] 
upscale=1
fullscreen=0
grab input=0
scaling quality=10
width=640
height=480
integer scaling=1
original aspect ratio=1
vsync=1
game speed=20
[Hellfire] 
Intro=0
```
Is there a setting that I'm missing?

**Comment by AJenbo** [comment]
You seem to have some HDPI going on the screenshot you posted is not 1280x960. Looks like you might be using macOS? I don't know how it handles HDPI or if it needs extra instructions like Windows.

You might want to debug the start-up process and see what resolutions are reported in `CalculatePreferdWindowSize`

`scaling quality` is 0-2, not 10. If you are doing integer scaling there is a chance you would prefer it at 0 (Nearest neighbor)

**Comment by AJenbo** [comment]
Using the ini you posted I do get 2x upscaling when the window resolution is sufficiently high.
![Screenshot from 2021-02-08 02-05-21](https://user-images.githubusercontent.com/204594/107165112-26bdcc00-69b2-11eb-8e04-022ed12a9f3b.png)

What if you disable integer scalign?

**Comment by eisnerguy1** [comment]
> You seem to have some HDPI going on the screenshot you posted is not 1280x960. Looks like you might be using macOS? I don't know how it handles HDPI or if it needs extra instructions like Windows.
> 
> You might want to debug the start-up process and see what resolutions are reported in `CalculatePreferdWindowSize`
> 
> `scaling quality` is 0-2, not 10. If you are doing integer scaling there is a chance you would prefer it at 0 (Nearest neighbor)

Yeah, I'm running macOS.  How would I debug the start-up process?


> Using the ini you posted I do get 2x upscaling when the window resolution is sufficiently high.
> ![Screenshot from 2021-02-08 02-05-21](https://user-images.githubusercontent.com/204594/107165112-26bdcc00-69b2-11eb-8e04-022ed12a9f3b.png)
> 
> What if you disable integer scalign?

Using these Diablo.ini settings:
```
[Diablo] 
Intro=0
Gamma Correction=100
Color Cycling=1
Sound Volume=0
Music Volume=0
[devilutionx] 
upscale=1
fullscreen=0
grab input=0
scaling quality=0
width=1280
height=960
integer scaling=0
original aspect ratio=1
vsync=1
game speed=20
[Hellfire] 
Intro=0
```

I still get this:
<img width="1280" alt="Screen Shot 2021-02-07 at 10 31 08 PM" src="https://user-images.githubusercontent.com/3295271/107172771-33cbc280-6994-11eb-9d82-190d4f39eea3.png">

**Comment by AJenbo** [comment]
That should force the view you are having so that at least makes sens.

Debug it by adding the following on line 95 and 103 of display.cpp:
```cpp
SDL_Log("integerScaling desktop: %dx%d, game: %dx%d", mode.w, mode.h width, height);
```

**Comment by eisnerguy1** [comment]
> ```c++
> SDL_Log("integerScaling desktop: %dx%d, game: %dx%d", mode.w, mode.h width, height);
> ```

Ok, I tried that and got this error:
```
[ 76%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/thread.cpp.o
[ 77%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/sound.cpp.o
/Users/eisnerguy1/Applications/Blizzard/Diablo/devilutionX/source/devilutionX-master_debug/SourceX/display.cpp:95:70: error: expected ')'
SDL_Log("integerScaling desktop: %dx%d, game: %dx%d", mode.w, mode.h width, height);
                                                                     ^
/Users/eisnerguy1/Applications/Blizzard/Diablo/devilutionX/source/devilutionX-master_debug/SourceX/display.cpp:95:8: note: to match this '('
SDL_Log("integerScaling desktop: %dx%d, game: %dx%d", mode.w, mode.h width, height);
       ^
/Users/eisnerguy1/Applications/Blizzard/Diablo/devilutionX/source/devilutionX-master_debug/SourceX/display.cpp:103:70: error: expected ')'
SDL_Log("integerScaling desktop: %dx%d, game: %dx%d", mode.w, mode.h width, height);
                                                                     ^
/Users/eisnerguy1/Applications/Blizzard/Diablo/devilutionX/source/devilutionX-master_debug/SourceX/display.cpp:103:8: note: to match this '('
SDL_Log("integerScaling desktop: %dx%d, game: %dx%d", mode.w, mode.h width, height);
       ^
2 errors generated.
gmake[2]: *** [CMakeFiles/devilutionx.dir/build.make:233: CMakeFiles/devilutionx.dir/SourceX/display.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:220: CMakeFiles/devilutionx.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
```

If I changed line 95 & 103 to:
```
SDL_Log("integerScaling desktop: %dx%d, game: %dx%d", mode.w, mode.h, width, height);
```
it builds but, I don't see any output/debug messages anywhere.  Was I wrong in changing that?

**Comment by AJenbo** [comment]
No, that was my mistake :)

You need to start the application from a terminal to see the console output.

Applications on Mac are actually folders containing various files, as well as the executable itself. So from a terminal you will need to navigate the structure, it's something like `devilutionx.app/Contents/MacOS/devilutionx`.

**Comment by eisnerguy1** [comment]
Oh, launching the app from Terminal.  Not sure why I didn't think of that.  Probably too distraught that Tom Brady won another Super Bowl XD.  I tried launching this build from Terminal and this is the entire output:
```
eisnerguy1s-MacBook-Pro-7:~ eisnerguy1$ cd /Users/eisnerguy1/Applications/Blizzard/Diablo/devilutionX/App/2x\ zoom/devilutionX-master_debug/build/devilutionx.app/Contents/MacOS 
eisnerguy1s-MacBook-Pro-7:MacOS eisnerguy1$ ./devilutionx
2021-02-08 02:44:51.144 devilutionx[18221:7172421] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
2021-02-08 02:44:51.192 devilutionx[18221:7172421] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
2021-02-08 02:44:51.197 devilutionx[18221:7172421] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
2021-02-08 02:44:51.197 devilutionx[18221:7172421] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
2021-02-08 02:44:51.197 devilutionx[18221:7172421] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
2021-02-08 02:44:51.197 devilutionx[18221:7172421] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
Alexs-MacBook-Pro-7:MacOS eisnerguy1$
```

**Comment by AJenbo** [comment]
Oh, `original aspect ratio` needs to be set to `0` for that part of the code to activate.

I think this might explain it, probably we are requesting 640x480 but because macOS thinks we are not HDPI aware it gives us a multiple of that, and then the render notices that the window is larger and draws to the full area.

Still, additional info would help confirm it. If you could also add this on line `66` (`AdjustToScreenGeometry`) we will get some more relevant info:
`SDL_Log("Display area: %dx%d", width, height);`

**Comment by eisnerguy1** [comment]
Here's the Terminal output:
```
eisnerguy1s-MacBook-Pro-7:~ eisnerguy1$ cd /Users/eisnerguy1/Applications/Blizzard/Diablo/devilutionX/App/2x\ zoom/devilutionX-master_debug/build/devilutionx.app/Contents/MacOS 
eisnerguy1s-MacBook-Pro-7:MacOS eisnerguy1$ ./devilutionx
2021-02-08 03:33:42.550 devilutionx[21526:7213351] INFO: integerScaling desktop: 1680x1050, game: 1280x960
2021-02-08 03:33:42.550 devilutionx[21526:7213351] INFO: Display area: 1536x960
2021-02-08 03:33:43.154 devilutionx[21526:7213351] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
2021-02-08 03:33:43.214 devilutionx[21526:7213351] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
2021-02-08 03:33:43.214 devilutionx[21526:7213351] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
2021-02-08 03:33:43.214 devilutionx[21526:7213351] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
2021-02-08 03:33:43.214 devilutionx[21526:7213351] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
2021-02-08 03:33:43.215 devilutionx[21526:7213351] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
eisnerguy1s-MacBook-Pro-7:MacOS eisnerguy1$
```

**Comment by AJenbo** [comment]
Oh, you set the internal resolution to 1280x960 in your latest ini file, based on that it looks to be giving you the correct result. Could you try again with 640x480?

**Comment by eisnerguy1** [comment]
```
eisnerguy1s-MacBook-Pro-7:~ eisnerguy1$ cd /Users/eisnerguy1/Applications/Blizzard/Diablo/devilutionX/App/2x\ zoom/devilutionX-master_debug/build/devilutionx.app/Contents/MacOS 
eisnerguy1s-MacBook-Pro-7:MacOS eisnerguy1$ ./devilutionx
2021-02-08 04:26:03.911 devilutionx[22137:7244790] INFO: integerScaling desktop: 1680x1050, game: 640x480
2021-02-08 04:26:03.911 devilutionx[22137:7244790] INFO: Display area: 768x480
2021-02-08 04:26:04.529 devilutionx[22137:7244790] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
2021-02-08 04:26:04.591 devilutionx[22137:7244790] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
2021-02-08 04:26:04.591 devilutionx[22137:7244790] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 0
2021-02-08 04:26:04.592 devilutionx[22137:7244790] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 1
2021-02-08 04:26:04.592 devilutionx[22137:7244790] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 2
2021-02-08 04:26:04.592 devilutionx[22137:7244790] INFO: Unhandled SDL event: SDL_AUDIODEVICEADDED 3
eisnerguy1s-MacBook-Pro-7:MacOS eisnerguy1$ 
```

**Comment by AJenbo** [comment]
Odd this doesn't really match the screenshot or my expectations :(

**Comment by eisnerguy1** [comment]
Is there a way to have Zoom mode automatically enabled?

**Comment by AJenbo** [comment]
diablo.cpp line 245 change:
`zoomflag = TRUE;`
to
`zoomflag = FALSE;`
(ues it's unintuitive named)

**Comment by eisnerguy1** [comment]
Hmm, I made that change but, the game doesn't automatically go into Zoom mode.  Do I need to change anything in my Diablo.ini file?
```
[Diablo] 
Intro=0
Gamma Correction=100
Color Cycling=1
Sound Volume=0
Music Volume=0
[devilutionx] 
upscale=1
fullscreen=0
grab input=0
scaling quality=0
width=640
height=480
integer scaling=1
original aspect ratio=1
vsync=1
game speed=20
[Hellfire] 
Intro=0
```

**Comment by AJenbo** [comment]
no, sounds odd that it didn't work.

**Comment by eisnerguy1** [comment]
I guess that enabled the mode that activates when pressing Z:
<img width="640" alt="Screen Shot 2021-02-08 at 5 51 41 PM" src="https://user-images.githubusercontent.com/3295271/107291634-7b0a8f80-6a36-11eb-9a97-4fb7ff8f5ccb.png">

Sorry, I meant if there is a way to enable the Zoom mode that normally requires you to select it from this menu?
<img width="240" alt="Screen Shot 2021-02-08 at 5 52 13 PM" src="https://user-images.githubusercontent.com/3295271/107291702-91185000-6a36-11eb-81ad-94ebdc0346f4.png">

**Comment by AJenbo** [comment]
I don't know what that is, must be macOS-related. It's not something related to the project.

**Comment by eisnerguy1** [comment]
I think I've figured out a possible solution.  Change width=1280 & height=960, enable Zoom via your code modification suggestion & all that I would need next would be to scale the entire UI *2.  Is that possible?  I've been looking in diabloui.h and I'm not sure exactly where I should be looking.

**Comment by AJenbo** [comment]
diabloui is the main menu before entering the game.

No the ingame UI does not have a way to scale.

**Comment by eisnerguy1** [comment]
Ah, oh well. I guess I can make do with the Zoom menu item
<img width="1680" alt="Screen Shot 2021-02-09 at 5 34 10 AM" src="https://user-images.githubusercontent.com/3295271/107351322-78408680-6a98-11eb-83cb-baf11638b5a8.png">

Going to close this then.

**Comment by AJenbo** [comment]
Unfortunatly there is no knowing when there will be a developer involved who knows how to handle macOS retina displays :/

Glad you have found a workaround.

**Comment by AJenbo** [comment]
Hmm on closer inspection of this issue I realize that what you are trying to do is have the game start in a 1280x960 window automatically. This isn't a feature, mostly we expect the game to be played in full-screen. But as you have found out you can simply resize the window manually (drag on the window boarder). So this isn't a bug after all but a feature request.

I suppose we could eventually add a setting with a multiplayer for what size the windowed mode should take compared to the game size.

p.s. on Mac you can maximize (zoom) windows by holding the `alt` key and pressing the green dot in the upper left of the window.

**Comment by johny-mnemonic** [comment]
@AJenbo That would be great. I just fought with this on my Windows 10 machine till I found the workaround you describes.
With these new high resolution widescreen displays it is not practical to have Diablo on full screen. 
I have 32:9 49" screen with 5120x1440 resolution and it is much more comfortable to have Diablo in the center part and still have usable parts of the screen around for a web browser, chat, etc.
So being able to specify both the game resolution and window resolution (or something even smarter taking DPI into account as you suggested) would be awesome.
For me the main motivation to keep game resolution low is the issues best described [here](https://github.com/diasurgical/devilutionX/issues/916). When I tried to increase the game resolution beyond 720p the game UI was simply too small.

**Comment by galaxyhaxz** [comment]
> I have 32:9 49" screen with 5120x1440 resolution and it is much more comfortable to have Diablo in the center part

It baffles my mind that there isn't a single 3:2 / 4:3 / 16:10 monitor left on the market yet we have abominations like 32:9 and it will probably only get worse from there. Setting a subset of first person games aside, could you imagine how hideous diablo would look or just about any game running fullscreen with far more horizontal FoV vs vertical?

**Comment by julealgon** [comment]
> It baffles my mind that there isn't a single 3:2 / 4:3 / 16:10 monitor left on the market yet we have abominations like 32:9 and it will probably only get worse from there. Setting a subset of first person games aside, could you imagine how hideous diablo would look or just about any game running fullscreen with far more horizontal FoV vs vertical?

It's a shame indeed @galaxyhaxz . In particular, i was very fond of 16:10 1920x1200 monitors. They nicely multiply multiple retro resolutions into full screen, contrary to 1920x1080 which really restricts what you can do in the vertical axis.

**Comment by galaxyhaxz** [comment]
>  In particular, i was very fond of 16:10 1920x1200 monitors

The funny thing is, we had 1600x1200 monitors as early as 2001 and 1920x1200 by 2006. Then in the 2010s they decided to go the 16:9 route so they could market it as "Full HD" like TVs. Our standard 1080p today has less overall pixels than the standard monitors from 15 years ago...

**Comment by johny-mnemonic** [comment]
@galaxyhaxz You have to look at 32:9 as the ultimate dual screen with no bezels between the two screens. 
I for one converted from 3x 16:9 mostly because I wanted to get rid of all those bezels and also the space consumed by monitor stands and cables. It is a downgrade regarding screen real estate, but it works really well and I am happy with it.
Back in the old day I loved 16:10 and I still have 2x 16:10 in the office. I would consider 32:10 or 40:10 as an ultimate goal. That would fill your entire vision without any clutter 😍

**Comment by StephenCWills** [comment]
> You have to look at 32:9 as the ultimate dual screen with no bezels between the two screens.

IMO, that's the type of look that someone with extravagant tastes would be more inclined to have. An equivalently-sized single monitor doesn't provide quite the same level of functionality as two separate monitors in terms of keeping your workspace organized. I suspect it would be more likely to appeal to users who are trying to stretch a single application horizontally, as gamers often do, but it has little practical benefit for those who'd need the space to work more productively. Personally, I feel I can actually sympathize better with those who rotate their monitors 90 degrees to get more vertical screen space.

**Comment by galaxyhaxz** [comment]
I know this is getting a bit off-topic but since I'm still using a 10 year old 16:10 laptop I'll pin another point.

Another factor to consider is integer up-scaling with 4:3 games/applications. When 16:10 came out it was marketed as WXGA (wide-xga) and featured resolutions of **equal** vertical pixels to the existing 4:3 ones but with more horizontal pixels. This means 800x600 would scale up perfectly 2x at 1920x1200 with black bars on the side.

16:9 slashed vertical pixels rather than increasing horizontal pixels. 1080/720 don't scale well with older applications and don't give you square pixels which makes everything look blurry. If 16:9 had kept 1200p we would have 2133x1200 monitors.

**Comment by julealgon** [comment]
@galaxyhaxz and 1600x1200 was a very common high-end resolution on 4:3 (as well as 2048x1536 but that one is too high for widescreen).

16:9 was absolute trash.

**Comment by AJenbo** [comment]
Aren't most computer monitors 1440p (x3 480, 2x 720p) at this point? 1200p might be good for up-scaling 800x600 but not so much 640x480 (2.5) which is the resolution of the subject matter.

**Comment by galaxyhaxz** [comment]
1440p is fairly recent so you have to factor in we went from ~2008-2017ish with 1080p being the standard (still is standard on nearly all laptops). 1280x960p has been around since the 90s and provided 2x scaling of 640x480.

**Comment by johny-mnemonic** [comment]
@AJenbo I am not sure. I guess both 1440p and 1200p are not ideal. For ideal upscaling of 480p, you need either 960p or 1920p. 
For the windowed mode the actual display resolution doesn't matter that much, but on both 1080p and 2160p you would be able to use integer scaling and stretch the window to 960p/1920p for the best results.
I guess you are spot on with the DPI as the reason why to scale the game. When I try to scale the original 640x480 it is simply too big (zoomed in) as it was designed for 12-14 inch screens and our screens are not physically 3x bigger while the resolution is. 
That's why I ended up using 1280x720 as render resolution and then [stretch the window](https://www.dropbox.com/s/5hiawy093r6jvvl/Diablo_720p_stretched%20on%201440p.png?dl=0) to roughly 1300p. With the original textures being so low res, it is blurry anyway (at least I don't see the difference between this and [480p scaled to 960p](https://www.dropbox.com/s/wtjoybl4mxr84eh/Diablo_480p_intscale2x%20on%201440p.png?dl=0) with integer scaling) and the correct size is more important for me.

@StephenCWills I think you would need to try it for yourself. Sorry for OT, but I have to ;-)
The freedom to separate the screen to any two or three horizontal areas (which behaves like separate screens with windows snapping, etc.) together with ability to override it and freely size any app as you want is really addictive. I for example work 90% time with three virtual screens on that 32:9 display. Games are the only apps I realistically stretch over the whole screen.
When I had 3x 16:9 I tried rotating some and all of them, but it was unnatural and uncomfortable...simply not for me. We humans are not made for narrow tall images. There is a reason why movies are widescreen. Our eyesight simply is widescreen as well.

**Comment by galaxyhaxz** [comment]
> Our eyesight simply is widescreen as well.

Yep. To be more precise, the human field of view is roughly 3:2, which made 3:2/16:10 quite comfortable.

**Comment by julealgon** [comment]
> With the original textures being so low res, it is blurry anyway (at least I don't see the difference between this and 480p scaled to 960p with integer scaling) and the correct size is more important for me.

@johny-mnemonic use scaling quality 0 to avoid blur

**Comment by johny-mnemonic** [comment]
@julealgon I tried both with 480p and 720p and to my eyes scaling quality 0 looks much worse. It is totally pixelated that way and there are even some "scaling artifacts" of sort. For example shading of health/mana bulbs is terrible.

**Comment by julealgon** [comment]
> and there are even some "scaling artifacts" of sort. For example shading of health/mana bulbs is terrible.

It's a technique called dithering, which creates gradients using fewer colors. You are right it becomes much more apparent without filtering. Some people like myself prefer it that way.
